### ISSUE TITLE
Complete quoting for parameters in "configure.ac"

### ISSUE THREAD

**Issue by elfring** [tesseract-ocr/tesseract#100]
I suggest to be more explicit where [macro expansion](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Autoconf-Language.html "The Autoconf language") will not be required in [the current build configuration script](https://github.com/tesseract-ocr/tesseract/blob/c4d52c77becbe092410e5ebfdc8a2533b0bbe374/configure.ac#L8 "Build specification").

**Comment by zdenop** [comment]
Please make a pull request or send the patch.

**Comment by amitdo** [comment]
@stweil
Do you think we need to fix something in the current `configure.ac` as suggested here? If the answer is 'yes', please send a PR.

**Comment by stweil** [comment]
PR #335 should fix this issue. I tested my patch like this:

    # Save old configure.
    mv configure old-configure
    # Apply my patch.
    ...
    # Create new configure.
    autoconf
    # Compare old and new configure. There should be only whitespace changes.
    diff -u --ignore-space-change old-configure configure
