### ISSUE TITLE
Detection of extra spaces while running own trained tesseract for Korean OCR 

### ISSUE THREAD

**Issue by abhishekchopde** [tesseract-ocr/tesseract#1009]
* **Tesseract Version**:  Tesseract 4.00 alpha
* **Platform**:  Linux -Ubuntu 14.04 64 bit 

I have trained a few layers of the base tesseract for Korean language. I have completed my training. Now I am testing it for different images containing Korea text. I am getting the excellent character accuracy but it is detecting extra spaces after each character so my word accuracy is more than 100%. I read another issue about the same problem in Chinese OCR but not much was mentioned over there. SO can someone please throw some light on this?
@stweil @theraysmith 

Here is the comparison between groundtruth and my tesseract output:- 
![screenshot from 2017-06-27 16 10 35](https://user-images.githubusercontent.com/26093128/27583775-2f0df1bc-5b53-11e7-843c-7b04570220d3.png)

**Comment by Shreeshrii** [comment]
Is the problem only with your traineddata or also with Korean traineddata posted for 4.00.00alpha?

Please do a similar test as above with kor.traineddata from tessdata repo.

**Comment by abhishekchopde** [comment]
No. The problem is with my trained data only. kor.traineddata from tessdata repo does not have that problem.

**Comment by abhishekchopde** [comment]
I got the solution for this.
Seems like we have to set the config variable - "preserve_interword_spaces" to 1 who's default value is 1 while running tesseract. The problem is solved by this for Korean language.

#991

**Comment by Shreeshrii** [comment]
see https://github.com/eighttails/MSYS2Private/commit/ee3210b283334f66ad3fdb1947dc79f23b817d08 which changes the default value of `preserve_interword_spaces`.

Should it also be applied to tesseract?
Will it break processing for other languages?

**Comment by amitdo** [comment]
It probably should be in the config files of CJK in fast & best.

**Comment by Shreeshrii** [comment]
@jbreiden This change should be applied before the debian release, it will improve CJK recognition.

Do you want us to create a PR with the change made to  `config files of CJK in fast & best` as suggested by @amitdo?

Though, it will probably be easier for you/Ray to apply at you end and upload to the repos.

**Comment by Shreeshrii** [comment]
Fixed via https://github.com/tesseract-ocr/tessdata_fast/pull/7

@zdenop  Please close this issue, after PR is merged in tessdata_fast.

**Comment by stweil** [comment]
What about `kor_vert`? Does it also need `preserve_interword_spaces=1`?
