### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by IngoBelka** [tesseract-ocr/tesseract#101]
Written in the WIKI
"Windows
An installer is available for Windows from our download page."

But as far as I can see there are no Windows installers to download. May be I'm not right, so, please, tell me, where I can get a current Windows installer.

**Comment by amitdo** [comment]
There is a Windows installer for tesseract version 3.02 here:

https://code.google.com/p/tesseract-ocr/downloads/list
tesseract-ocr-setup-3.02.02.exe

I don't think there is a Windows installer for newer versions.

**Comment by IngoBelka** [comment]
Ok, thank you. I took a further look for a newer version and I found:
http://domasofan.spdns.eu/tesseract/
with the newest development version. But the server is delivering the files really slow.

**Comment by solomon18** [comment]
Thank you for the latest Windows installer files :).

**Comment by stweil** [comment]
The NSIS installer configuration was added and removed twice, the last time with commit b8862b33dfa3bf42c87913911f62da7bc4ed2e45. Is there currently another method to build an installer for Windows? If not, I'd like to add the NSIS configuration files again. I just finished cross building Tesseract for Windows (including an installer) based on latest Git master and using the MinGW-w64 packages on Debian GNU Linux.

**Comment by zdenop** [comment]
This issue is not only about creating windows installer. It is also about providing support. And on windows the there is demand for VS based library (it is quiet easy to create mingw based library with msys, but VS based library need to rebuild all dependencies with VS)

**Comment by amitdo** [comment]
See also PR #162.

**Comment by zdenop** [comment]
@amitdo: Future is cmake. There is no sense to make and maintain  build system for each version of cmake. cmake correctly detect installed compiler and use it. We are just waiting for leptonica transfer to github, there cmake will be presented to.

**Comment by stweil** [comment]
@amitdo, that's interesting, but it still does not include an installer as far as I see.
@zdenop, maybe those Windows developers who are interested in libraries can also compile Tesseract. But those who just want to do OCR on Windows need an installer. Will cmake provide one?

Regarding leptonica, you can start with https://github.com/stweil/leptonica until there is an official GitHub version.

**Comment by amitdo** [comment]
>Future is cmake. There is no sense to make and maintain build system for each version of cmake. cmake correctly detect installed compiler and use it. We are just waiting for leptonica transfer to github, there cmake will be presented to.

https://github.com/DanBloomberg/leptonica

**Comment by Shreeshrii** [comment]
[See issue 209](https://github.com/tesseract-ocr/tesseract/issues/209)
