### ISSUE TITLE
ron.traineddata not working

### ISSUE THREAD

**Issue by sammy36ca** [tesseract-ocr/tesseract#1013]
------------------------

### Environment windows 10 pro

* **Tesseract Version**: 5.41
* **Commit Number**: 
* **Platform**: windows 10 pro 64-bit -->

### Current Behavior: closing when used with ron.traineddata 
[ocrerror.docx](https://github.com/tesseract-ocr/tesseract/files/1112600/ocrerror.docx) no other error or details  reported

**Comment by amitdo** [comment]
>Tesseract Version: 5.41

There is no such version of Tesseract.

**Comment by amitdo** [comment]
Apparently, you use [freeOCR](http://www.paperfile.net/). We don't support this software.

**Comment by sammy36ca** [comment]
Hisorry , I saw that after I posted the thread ; it is freeocr ver 5.41 but I don't know how to check what version of tesseract is used ; I will try the ocr for tesseract v3 to see if it's workingthank you Horia-Dan Samoila 

    On Thursday, June 29, 2017 12:45 PM, zdenop <notifications@github.com> wrote:
 

 Closed #1013.—
