### ISSUE TITLE
[Suggestion for discussion] Redesign of tessdata installation e.g. via a text file of needed languages and/or as git submodule (to clone or pull/update all languages automatically)

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#102]
I would like to suggest to slightly redesign the layout and installation of the training data.

At the present, one can install a single language (or a set of languages) by downloading the prepacked trainingdata as described in https://github.com/tesseract-ocr/tesseract/wiki/Compiling#Language%20Data _or_ by downloading the git repo https://github.com/tesseract-ocr/tessdata .

The process is difficult, in case that you always want to automatically use the latest version of (let's say) eng, deu, fra, spa, ita trainingdata.

Without presenting a concrete idea or a PR, I just wanted to start a discussion whether and how a redesign (which should be compatible to the current way of downloadlng/installing language data) could look like, if it is wanted and possible.

Perhaps a small json or text parameter file could indicate which languages are needed (or are currently installed), and only these files are then updated from git.

Or a method "git submodule" which automatically clones (or pulls) all languages from https://github.com/tesseract-ocr/tessdata .

**Comment by zdenop** [comment]
Please use tesseract-developers forum[1] for this suggestions like this.
[1] http://groups.google.com/group/tesseract-dev/

**Comment by correosdelbosque** [comment]
I think it is a good idea specially for people like me a normal windows user that is just learning
