### ISSUE TITLE
Fine Tuning Error

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#1021]
Hi,

i was trying to make fine tuning for the lstm file yet i got this error

**Deserialize failed: /home/ibr/tesstutorial/aratrain/ara.2_Baran.exp0.lstmf read 0/81 pages**
keep in mind that the path is correct so the error is **Deserialize failed**: not **Deserialize header failed**
and tesseract freezes after the error message and should press Ctrl C to stop it

i already used the same version of tesseract to tune for japanese, but for arabic i got the previous error
the command was 

`training/lstmtraining --model_output ~/tesstutorial/arabic_tuning/"arabic_tune" \
  --continue_from ~/tesstutorial/extracted_aralstm/ara.lstm \
  --train_listfile ~/tesstutorial/aratrain/ara.training_files.txt \
  --max_iterations 100000`

Thanks

**Comment by ibr123** [comment]
i was able to tune Arabic ara.lstm with the same lstmf files, but the difference i made tuning against a different version of tesseract which is: **367-g5baa8c8**. while the version that failed was: **547-g8c29e68**

strangely that the version **547-g8c29e68** passed for Japanese tuning yet it failed for Arabic tuning, as for the version **367-g5baa8c8** i didn't try it for Japanese tuning, only for Arabic and it succeeded
NOTE: both versions are running on the same VMware, and with the same leptonica version which is Leptonica1.47.1

**Comment by Shreeshrii** [comment]
You need to create the lstmf files and then do finetuning with same version of tesseract. If there is a mismatch, it may not work since Ray made some changes in the lstmf files format.

**Comment by ibr123** [comment]
actually all the LSTMFs (Arabic & Japanese) were created by the same version **547-g8c29e68**  yet fine tuning at the version **547-g8c29e68**  worked only for Japanese, but for Arabic (which was also created by the version **547-g8c29e68**) its fine tuning worked at the version **367-g5baa8c8**
