### ISSUE TITLE
Train error: tesseract 3.04 cannot distinguish 6 and 8

### ISSUE THREAD

**Issue by Anida-qin** [tesseract-ocr/tesseract#1022]
------------------------

### Environment
Tesseract 3.04 or Tesseract 3.05
windows and linux
### Current Behavior:
I follow the official training guide but the final train font data can not distinguish 6 and 8. It sometimes recognizes 6 as 8 and sometimes recognizes 6 as 5 or something else. It's strange since the first training data didn't have the problem but the second one have. But the training data is similar. 
1.tesseract eng.test3.exp0.tif -psm 10 eng.test3.exp0 box.train

2 unicharset_extractor eng.test3.exp0.box

3. set_unicharset_properties -U unicharset -O unicharset --script_dir=./langdata

4. create font file 
    test3 0 0 0 0 0 

5. shapeclustering -F font -U unicharset eng.test3.exp0.tr 

6.mftraining -F font -U unicharset -O test3.unicharset eng.test3.exp0.tr 

7. cntraining eng.test3.exp0.tr

8. rename file name test3.

9. combine_tessdata test3.

At last. I do get the trainedata at last. But the test result is very strange. It totally mixed number 6 and number 8. 

I don't know what's wrong with it. I think there is maybe some special requirements for the train data. But i didn't see in the doc. Could anyone can help?

Here is my tif/box pair.
[eng.test3.exp0.tif](https://drive.google.com/open?id=0B9BaT1tS42KuUVBkbU1TUkdpLXc)
[eng.test3.exp0.box](https://drive.google.com/open?id=0B9BaT1tS42KuX0cteVJrZlJsSG8)

Thanks a lot !!!!

Here is the question link from google. https://groups.google.com/forum/#!topic/tesseract-ocr/qRiAI7Zx9jg

**Comment by kirannaik25** [comment]
Hi used following sequence for Tesseract version 3.05.01 training on windows 64.
AS of now it working.
Please try this sequence.
1.	tesseract eng.test3.exp0.tif eng.test3.exp0 -l eng batch.nochop makebox
2.	tesseract eng.test3.exp0.tif eng.test3.exp0 box.train
3.	unicharset_extractor eng.test3.exp0.box
4.	set_unicharset_properties -U unicharset -O unicharset --script_dir=/home/tessdata/langdata-master
5.	shapeclustering -F /home/tessdata/langdata-master/font_properties -U unicharset eng.test3.exp0.tr
6.	mftraining -F /home/tessdata/langdata-master/font_properties -U unicharset -O unicharset eng.test3.exp0.tr
7.	cntraining eng.test3.exp0.tr
8.	move inttemp eng.inttemp
9.	move normproto eng.normproto
10.	move pffmtable eng.pffmtable
11.	move shapetable eng.shapetable
12.	combine_tessdata eng (before this command rename unicharset file to eng.unicharset)

**Comment by zdenop** [comment]
There is not plan 3.x tesseract version. Please try tesseract 4 (current code).
