### ISSUE TITLE
Tesseract creates output for missing input

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#1023]
If Tesseract is called with a non-existing image file, it creates an empty output file.

I'd expect that no output is created in that case.

Examples:

    # Empty output.txt is created.
    tesseract nonexisting_image.tiff output
    # Empty output.hocr is created.
    tesseract nonexisting_image.tiff output hocr

**Comment by amitdo** [comment]
The source of the problem:
https://github.com/tesseract-ocr/tesseract/blob/master/api/renderer.cpp

**Comment by Shreeshrii** [comment]
@stweil  for https://github.com/tesseract-ocr/tesseract/issues/1423

**Comment by zdenop** [comment]
Problem is that output file is created during [initialization of renderer](https://github.com/tesseract-ocr/tesseract/blob/master/src/api/renderer.cpp#L42) and it happens before [starting of OCR](https://github.com/tesseract-ocr/tesseract/blob/master/src/api/tesseractmain.cpp#L608)...

Maybe we can implement simple check if input file exists....

**Comment by zdenop** [comment]
Done.
But there could be scenarios where empty output is created. E.g. if input file exists but is malformed or leptonica can not process. That could be solved only by changing logic of renderer: create file only when we have something for writing to file. Or remove file if OCR output is empty.
