### ISSUE TITLE
merge_unicharsets.cpp

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#1024]
https://github.com/tesseract-ocr/tesseract/blob/master/training/merge_unicharsets.cpp

Should we add it to `training/Makefile.am` ?

**Comment by Shreeshrii** [comment]
Amit,

Which kind of unicharsets does it  merge? 
* The script based ones given in langdata
* The training text based ones created during training process

Does it just append or also eliminate duplicates?

Where would a merged unicharset be used?

**Comment by amitdo** [comment]
Good questions, Shree. Unfortunately, I simply don't have the answers...

**Comment by amitdo** [comment]
I just found this file, and saw it isn't in the Makefile.am which means it won't be compiled, so you can't actually use it.

**Comment by Shreeshrii** [comment]
In that case, we should add it to Makefile.am so that we can test and figure out what it does :-)

**Comment by amitdo** [comment]
It takes two or more unicharset files with this format:
https://github.com/tesseract-ocr/tesseract/wiki/Training-Tesseract#the-unicharset-file-format

I don't know when you are supposed to use it.

**Comment by amitdo** [comment]
It calls this function to do the merge:
https://github.com/tesseract-ocr/tesseract/blob/29f3de9be1fbae76925e946b9fb04bb976c3f9a0/ccutil/unicharset.cpp#L439

**Comment by theraysmith** [comment]
It could be used to create a combined unicharset for a script-level engine, like the new Latin or Devanagari.
It isn't referenced by the current training documentation, but it might be useful to someone, so it should probably be added to Makefile.am.

**Comment by Shreeshrii** [comment]
@theraysmith 

Is there a similar merge_language_model program, used for building a script-level engine?

Recently someone asked me:

```
Let us consider language as lat+san+guj 
```

Where lat is IAST or the roman transliteration of Sanskrit, in Latin script + English
san is Sanskrit in Devanagari script
guj is Gujarati in Gujarati script

So, something like this needs a combining of Devanagari + Gujarati + san_latn or IAST or Latin

What would be the best way to do this?

Sample image below:
![multi-language](https://user-images.githubusercontent.com/5095331/30238960-8e4a80fe-956f-11e7-9f1d-28ac9a18caec.png)

**Comment by Shreeshrii** [comment]
>It could be used to create a combined unicharset for a script-level engine, like the new Latin or Devanagari.
It isn't referenced by the current training documentation, but it might be useful to someone, so it should probably be added to Makefile.am.

Added as part of PR https://github.com/tesseract-ocr/tesseract/pull/1116/commits/9a038f893ad51e35157b393fcd95d1b661c528af

**Comment by amitdo** [comment]
For next time, I suggest not to mix unrelated commits in one PR.

**Comment by amitdo** [comment]
Thanks anyway!
