### ISSUE TITLE
Can not install libleptonica-dev on linux

### ISSUE THREAD

**Issue by diyali03** [tesseract-ocr/tesseract#1025]
I try to use sudo apt-get install libleptoncia-dev on linux.

It displays that I have already installed libleptoncia-1.74, which is the newest one.

While I use ./configure to congigure the package on my system, it shows an errors again:

` error: Leptonica 1.74 or higher is required. Try to install libleptonica-dev package.`

SO I try to remove the libleptoncia-1.74 and reinstall the dev again, but it put up another error:
`Failed to connect to socket /com/ubuntu/upstart: `

I have no idea to deal with those, can anybody give me some advices?

**Comment by Shreeshrii** [comment]
Use forum for asking questions.

See https://github.com/tesseract-ocr/tesseract/wiki/Compiling

Tesseract versions and the minimum version of Leptonica required:
TesseractLeptonicaUbuntu
4.00 1.74.2 Must build from source
3.05 1.74.0 Must build from source
3.04 1.71 Ubuntu 16.04 <http://packages.ubuntu.com/xenial/libtesseract3>
3.03 1.70 Ubuntu 14.04 <http://packages.ubuntu.com/trusty/libtesseract3>
3.02 1.69 Ubuntu 12.04 <http://packages.ubuntu.com/precise/libtesseract3>
3.01 1.67

One option is to install the distro's Leptonica package:

sudo apt-get install libleptonica-dev

but if you are using an oldish version of Linux, the Leptonica version may
be too old, so you will need to build from source.

The sources are at https://github.com/DanBloomberg/leptonica . The
instructions for building are given in Leptonica README
<http://www.leptonica.org/source/README.html>.

Note that if building Leptonica from source, you may need to ensure that
/usr/local/lib is in your library path. This is a standard Linux bug, and
the information at Stackoverflow
<http://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries>
is
very helpful.

**Comment by diyali03** [comment]
Thanks, it is helpful. I fix it.
