### ISSUE TITLE
Tesseract 4 and ita.traineddata

### ISSUE THREAD

**Issue by priore** [tesseract-ocr/tesseract#1026]
Hi,
when inizializing tesseract 4 with ita language (ita.traineddata for tesseract 4), the application crash on  configEngine method of G8Tesseract.mm.

<img width="585" alt="schermata 2017-07-06 alle 16 54 54" src="https://user-images.githubusercontent.com/1537350/27917284-e45683bc-626b-11e7-98bf-bc3666c1d500.png">

<img width="955" alt="schermata 2017-07-06 alle 16 51 01" src="https://user-images.githubusercontent.com/1537350/27917244-bed8d644-626b-11e7-8c2d-463004eaa036.png">

Please help me, thanks.

**Comment by zdenop** [comment]
We support only for C++. Please replicate problem with tesseract executable or C++ code. Otherwise please use tesseract user forum for your project.
