### ISSUE TITLE
Building Tesseract 4 Win32 DLL

### ISSUE THREAD

**Issue by LeifUK** [tesseract-ocr/tesseract#1027]
I need a Windows Win32 build of the Tesseract DLL version 4. I've tried and failed to build the code from the \Tesseract-4.00.00alpha branch. The first issue is that cppan.yml need editing to fix a known bug at the end: 

    pvt.cppan.demo.danbloomberg.leptonica: master

The next issue is that I get unresolved externals: 

Error	1	error LNK2001: unresolved external symbol "public: void __thiscall tesseract::Tesseract::TrainLineRecognizer(class STRING const &,class STRING const &,class BLOCK_LIST *)" (?TrainLineRecognizer@Tesseract@tesseract@@QAEXABVSTRING@@0PAVBLOCK_LIST@@@Z)	C:\Development\Projects\Tesseract-4.00.00alpha\vs2010\libtesseract\baseapi.obj	libtesseract304
Error	2	error LNK2001: unresolved external symbol "public: void __thiscall tesseract::Tesseract::LSTMRecognizeWord(class BLOCK const &,class ROW *,class WERD_RES *,class tesseract::PointerVector<class WERD_RES> *)" (?LSTMRecognizeWord@Tesseract@tesseract@@QAEXABVBLOCK@@PAVROW@@PAVWERD_RES@@PAV?$PointerVector@VWERD_RES@@@2@@Z)	C:\Development\Projects\Tesseract-4.00.00alpha\vs2010\libtesseract\control.obj	libtesseract304
Error	3	error LNK2001: unresolved external symbol "public: void __thiscall tesseract::Tesseract::RecogRawLine(class PAGE_RES *)" (?RecogRawLine@Tesseract@tesseract@@QAEXPAVPAGE_RES@@@Z)	C:\Development\Projects\Tesseract-4.00.00alpha\vs2010\libtesseract\control.obj	libtesseract304
Error	4	error LNK2001: unresolved external symbol "public: bool __thiscall tesseract::LSTMRecognizer::LoadDictionary(char const *,char const *)" (?LoadDictionary@LSTMRecognizer@tesseract@@QAE_NPBD0@Z)	C:\Development\Projects\Tesseract-4.00.00alpha\vs2010\libtesseract\tessedit.obj	libtesseract304
Error	5	error LNK2001: unresolved external symbol "public: bool __thiscall tesseract::LSTMRecognizer::DeSerialize(bool,class tesseract::TFile *)" (?DeSerialize@LSTMRecognizer@tesseract@@QAE_N_NPAVTFile@2@@Z)	C:\Development\Projects\Tesseract-4.00.00alpha\vs2010\libtesseract\tessedit.obj	libtesseract304
Error	6	error LNK2001: unresolved external symbol "public: __thiscall tesseract::LSTMRecognizer::LSTMRecognizer(void)" (??0LSTMRecognizer@tesseract@@QAE@XZ)	C:\Development\Projects\Tesseract-4.00.00alpha\vs2010\libtesseract\tessedit.obj	libtesseract304
Error	7	error LNK2001: unresolved external symbol "public: __thiscall tesseract::LSTMRecognizer::~LSTMRecognizer(void)" (??1LSTMRecognizer@tesseract@@QAE@XZ)	C:\Development\Projects\Tesseract-4.00.00alpha\vs2010\libtesseract\tesseractclass.obj	libtesseract304
Error	8	error LNK1120: 7 unresolved externals	C:\Development\Projects\Tesseract-4.00.00alpha\vs2010\DLL_Release\libtesseract304.dll	libtesseract304
	9	IntelliSense: identifier "round" is undefined	c:\Development\Projects\Tesseract-4.00.00alpha\api\baseapi.cpp	1367	43	libtesseract304

Thanks in advance.

**Comment by egorpugin** [comment]
What is those `libtesseract304` messages?

**Comment by amitdo** [comment]
@egorpugin,
No feedback from the OP, so please close this issue.
