### ISSUE TITLE
Memory management issues in tesseract 4 alpha

### ISSUE THREAD

**Issue by LeifUK** [tesseract-ocr/tesseract#1029]
### Environment
Tesseract4.00.00alpha
Windows 32-bit 

### Current Behavior:
Throws an exception in TessBaseAPI::ProcessPage()

### Expected Behavior:
No exception. 

### Suggested Fix:

The exception is thrown in imagedata.cpp in this method when calling free(data): 

void ImageData::SetPixInternal(Pix* pix, GenericVector<char>* image_data);

The data memory is allocated in the liblept library and should be freed using a call to the library. I assume the correct call is lept_free.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/f5c18f78c09ab028791c28c638d5cc2f96c6d6fb/ccstruct/imagedata.cpp#L327

>The data memory is allocated in the liblept library and should be freed using a call to the library. I assume the correct call is lept_free.

You are right.

**Comment by amitdo** [comment]
https://github.com/DanBloomberg/leptonica/blob/d20c5a68746d56a59a9b9e6f28a91364f5dd6e33/src/utils2.c#L128

Seems to only affect Windows.

**Comment by LeifUK** [comment]
And another one in the same vein, not sure if this should be here or in a new thread. In this method: 

void ScrollView::Image(struct Pix* image, int x_pos, int y_pos)

The free(data) should be lept_free(data). 

Using Visual Studio 2013 on Windows 10 to create a 32 bit build.

**Comment by stweil** [comment]
I now had a closer look on this issue and came to a different result. `ImageData::SetPixInternal` calls `pixWriteMem` which calls different functions depending on the image format. For JPEG, it calls `pixWriteMemJpeg` which calls `l_binaryReadStream` which allocates the memory using `LEPT_CALLOC` which is defined to be equal with `calloc`. So using `free` is not wrong. `lept_free` also basically calls `free`, so it should not make a difference whether `free` or `lept_free` is used.

@LeifUK, does the Visual Studio build use a different definition for `LEPT_CALLOC`, different implementations of `lept_free` or anything else which is different? Why does it throw an exception at all? And what kind of exception is that? Maybe it also depends on the image format. Which one did you process to get the exception?

**Comment by LeifUK** [comment]
The exception is heap corruption. It occurs because in Windows the app and the DLL each have their own heap, therefore you cannot allocate in the DLL and free in the app. So yes this is a Windows issue. 

That is a good point that my app could call lept_free.

**Comment by stweil** [comment]
Ideally the Tesseract code and the Leptonica DLL use the same C library DLL. That saves memory and load time, and it avoids problems with different heaps, different `errno`, different `stdin` / `stdout` / `stderr` and other FILE pointers. Maybe you mixed `msvcrt.dll` and `msvcrtd.dll`, or your code loads two different versions of the VC runtime library.

**Comment by stweil** [comment]
Pull request #1041 should fix this issue.

**Comment by LeifUK** [comment]
I use the same C runtime libraries throughout. And the same Visual Studio toolsets.

**Comment by stweil** [comment]
> I use the same C runtime libraries throughout.

See [my comment](https://github.com/tesseract-ocr/tesseract/issues/1030#issuecomment-316934477) for issue #1030.

**Comment by LeifUK** [comment]
As an aside, is there a discussion forum for Tesseract issues that are (probably) not bugs? I see very strange behaviour when unders Windows I run my memory leak tests against Leptonica and Tesseract and would appreciate feedback from others.

**Comment by stweil** [comment]
There are user and developer forums, see [Tesseract wiki](https://github.com/tesseract-ocr/tesseract/wiki#support).

**Comment by LeifUK** [comment]
Thank you.
