### ISSUE TITLE
Corrupt JPEG data: nnnn extraneous bytes before marker 0xnn

### ISSUE THREAD

**Issue by toddysm** [tesseract-ocr/tesseract#103]
On Windows I am getting the following error message for a JPG although the file can be opened with the viewer and shows correct:
Corrupt JPEG data: nnnn extraneous bytes before marker 0xnn
Image is attached
![ptdc0020](https://cloud.githubusercontent.com/assets/1007103/9982736/5b09231a-5f9a-11e5-84d2-ed5e2488cd91.JPG)

**Comment by jimregan** [comment]
That's a libjpeg warning. Is Tesseract not producing output for you, because it is for me (granted, the output isn't great).

**Comment by toddysm** [comment]
Yes, it seems it is producing. Just curious - what is the issue with the JPEG though?

**Comment by jimregan** [comment]
This page: http://www.artima.com/forums/flat.jsp?forum=1&thread=35958 says "before the EOI marker (0xFF 0xD9) one can include custom data other than data related to image" which seems reasonable.
Anyway... as this isn't a Tesseract issue per se, I'm going to close this issue.
