### ISSUE TITLE
`nobatch box.train` after insert boxes in Chinese, FAILURE! Couldn't find a matching blob

### ISSUE THREAD

**Issue by iChenwin** [tesseract-ocr/tesseract#1033]
After `makebox`, I edited chi.font.exp0.tif in jTessBoxEditor and insert boxes for some unrecognized character. Then I use `*** nobatch box.train`, it appears that all the characters I added manually was failed matching blob. Error like this:
```
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
FAIL!
APPLY_BOXES: boxfile line 431/汐 ((252,521),(281,550)): FAILURE! Couldn't find a matching blob
FAIL!
```
I'm using 3.0.5, so what's the matter?

**Comment by Shreeshrii** [comment]
@zdenop  Please close - duplicate https://github.com/tesseract-ocr/tesseract/issues/1166
