### ISSUE TITLE
Cannot generate training data, for english language (even by default settings) 

### ISSUE THREAD

**Issue by wqret1992** [tesseract-ocr/tesseract#1037]
------------------------

### Environment

* **Tesseract Version**:  4.00 alpha
* **Commit Number**: 
* **Platform**: ubuntu 14, 64 bit

### Current Behavior:

```
root@pl:~/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master# training/tesstrain.sh \
>   --fonts_dir /usr/share/fonts \
>   --lang eng --linedata_only \
>   --noextract_font_properties \
>   --langdata_dir /home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master \
>   --tessdata_dir /home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/tessdata \
>   --fontlist "Lucida Sans" \
>   --output_dir /home/pl/Downloads/SRI_/USING_FILES/OUTPUT_FILES/LSTM_TN_LUCIDA

=== Starting training for language 'eng'
[Tue Jul 11 13:05:43 IST 2017] /usr/local/bin/text2image --fonts_dir=/usr/share/fonts --font=Lucida Sans --outputbase=/tmp/font_tmp.XgxrkfyOjx/sample_text.txt --text=/tmp/font_tmp.XgxrkfyOjx/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.XgxrkfyOjx
Rendered page 0 to file /tmp/font_tmp.XgxrkfyOjx/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using Lucida Sans
[Tue Jul 11 13:05:45 IST 2017] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.XgxrkfyOjx --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0 --font=Lucida Sans --text=/home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master/eng/eng.training_text
Stripped 5 unrenderable words
Rendered page 0 to file /tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0.tif
Stripped 3 unrenderable words
Rendered page 1 to file /tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0.tif

=== Phase UP: Generating unicharset and unichar properties files ===
[Tue Jul 11 13:05:46 IST 2017] /usr/local/bin/unicharset_extractor -D /tmp/tmp.iafCx7Aypj/eng/ /tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0.box
Extracting unicharset from /tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0.box
Wrote unicharset file /tmp/tmp.iafCx7Aypj/eng//unicharset.
[Tue Jul 11 13:05:46 IST 2017] /usr/local/bin/set_unicharset_properties -U /tmp/tmp.iafCx7Aypj/eng/eng.unicharset -O /tmp/tmp.iafCx7Aypj/eng/eng.unicharset -X /tmp/tmp.iafCx7Aypj/eng/eng.xheights --script_dir=/home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master
Loaded unicharset of size 111 from file /tmp/tmp.iafCx7Aypj/eng/eng.unicharset
Setting unichar properties
Other case É of é is not in unicharset
Warning: properties incomplete for index 25 = ~
Writing unicharset to file /tmp/tmp.iafCx7Aypj/eng/eng.unicharset

=== Phase D: Generating Dawg files ===
Generating word Dawg
[Tue Jul 11 13:05:46 IST 2017] /usr/local/bin/wordlist2dawg -r 1 /home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master/eng/eng.wordlist /tmp/tmp.iafCx7Aypj/eng/eng.word-dawg /tmp/tmp.iafCx7Aypj/eng/eng.unicharset
Set reverse_policy to RRP_REVERSE_IF_HAS_RTL
Loading unicharset from '/tmp/tmp.iafCx7Aypj/eng/eng.unicharset'
Reading word list from '/home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master/eng/eng.wordlist'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.iafCx7Aypj/eng/eng.word-dawg'
Generating frequent-word Dawg
[Tue Jul 11 13:05:48 IST 2017] /usr/local/bin/wordlist2dawg -r 1 /tmp/tmp.iafCx7Aypj/eng/eng.wordlist.clean.freq /tmp/tmp.iafCx7Aypj/eng/eng.freq-dawg /tmp/tmp.iafCx7Aypj/eng/eng.unicharset
Set reverse_policy to RRP_REVERSE_IF_HAS_RTL
Loading unicharset from '/tmp/tmp.iafCx7Aypj/eng/eng.unicharset'
Reading word list from '/tmp/tmp.iafCx7Aypj/eng/eng.wordlist.clean.freq'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.iafCx7Aypj/eng/eng.freq-dawg'
[Tue Jul 11 13:05:48 IST 2017] /usr/local/bin/wordlist2dawg -r 0 /home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master/eng/eng.punc /tmp/tmp.iafCx7Aypj/eng/eng.punc-dawg /tmp/tmp.iafCx7Aypj/eng/eng.unicharset
Set reverse_policy to RRP_DO_NO_REVERSE
Loading unicharset from '/tmp/tmp.iafCx7Aypj/eng/eng.unicharset'
Reading word list from '/home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master/eng/eng.punc'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.iafCx7Aypj/eng/eng.punc-dawg'
[Tue Jul 11 13:05:48 IST 2017] /usr/local/bin/wordlist2dawg -r 0 /home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master/eng/eng.numbers /tmp/tmp.iafCx7Aypj/eng/eng.number-dawg /tmp/tmp.iafCx7Aypj/eng/eng.unicharset
Set reverse_policy to RRP_DO_NO_REVERSE
Loading unicharset from '/tmp/tmp.iafCx7Aypj/eng/eng.unicharset'
Reading word list from '/home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master/eng/eng.numbers'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.iafCx7Aypj/eng/eng.number-dawg'
[Tue Jul 11 13:05:48 IST 2017] /usr/local/bin/wordlist2dawg -r 1 /home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master/eng/eng.word.bigrams /tmp/tmp.iafCx7Aypj/eng/eng.bigram-dawg /tmp/tmp.iafCx7Aypj/eng/eng.unicharset
Set reverse_policy to RRP_REVERSE_IF_HAS_RTL
Loading unicharset from '/tmp/tmp.iafCx7Aypj/eng/eng.unicharset'
Reading word list from '/home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/langdata-master/eng/eng.word.bigrams'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.iafCx7Aypj/eng/eng.bigram-dawg'

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=/home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/tessdata
[Tue Jul 11 13:05:57 IST 2017] /usr/local/bin/tesseract /tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0.tif /tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0 lstm.train
Info in bmfCreate: Generating pixa of bitmap fonts from string
Error: unichar y in normproto file is not in unichar set.
Error: unichar m in normproto file is not in unichar set.
Error: unichar “ in normproto file is not in unichar set.
Error: unichar p in normproto file is not in unichar set.
Error: unichar f in normproto file is not in unichar set.
Error: unichar " in normproto file is not in unichar set.
Error: unichar ! in normproto file is not in unichar set.
Error: unichar @ in normproto file is not in unichar set.
Error: unichar [ in normproto file is not in unichar set.
Error: unichar ¢ in normproto file is not in unichar set.
Error: unichar | in normproto file is not in unichar set.
Error: unichar x in normproto file is not in unichar set.
Error: unichar * in normproto file is not in unichar set.
Error: unichar $ in normproto file is not in unichar set.
Error: unichar £ in normproto file is not in unichar set.
Error: unichar _ in normproto file is not in unichar set.
Error: unichar { in normproto file is not in unichar set.
Error: unichar } in normproto file is not in unichar set.
Error: unichar > in normproto file is not in unichar set.
Error: unichar ¥ in normproto file is not in unichar set.
Error: unichar © in normproto file is not in unichar set.
Error: unichar z in normproto file is not in unichar set.
Error: unichar ° in normproto file is not in unichar set.
Error: unichar q in normproto file is not in unichar set.
Error: unichar w in normproto file is not in unichar set.
Error: unichar « in normproto file is not in unichar set.
Error: unichar = in normproto file is not in unichar set.
Error: unichar ; in normproto file is not in unichar set.
Error: unichar < in normproto file is not in unichar set.
Error: unichar ? in normproto file is not in unichar set.
Error: unichar ﬂ in normproto file is not in unichar set.
Error: unichar ' in normproto file is not in unichar set.
Error: unichar j in normproto file is not in unichar set.
Error: unichar » in normproto file is not in unichar set.
Error: unichar é in normproto file is not in unichar set.
Error: unichar — in normproto file is not in unichar set.
Error: unichar # in normproto file is not in unichar set.
Error: unichar ~ in normproto file is not in unichar set.
Error: unichar + in normproto file is not in unichar set.
Error: unichar ® in normproto file is not in unichar set.
Error: unichar € in normproto file is not in unichar set.
Error: unichar ‘ in normproto file is not in unichar set.
Error: unichar ﬁ in normproto file is not in unichar set.
Error: unichar ” in normproto file is not in unichar set.
Error: unichar § in normproto file is not in unichar set.
Error: unichar \ in normproto file is not in unichar set.
Error: unichar ’ in normproto file is not in unichar set.
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Page 1
Page 2
Loaded 50/50 pages (1-50) of document /tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0.lstmf

=== Constructing LSTM training data ===
Moving /tmp/tmp.iafCx7Aypj/eng/eng.unicharset to /home/pl/Downloads/SRI_/USING_FILES/OUTPUT_FILES/LSTM_TN_LUCIDA
Moving /tmp/tmp.iafCx7Aypj/eng/eng.number-dawg to /home/pl/Downloads/SRI_/USING_FILES/OUTPUT_FILES/LSTM_TN_LUCIDA/eng.lstm-number-dawg
Moving /tmp/tmp.iafCx7Aypj/eng/eng.punc-dawg to /home/pl/Downloads/SRI_/USING_FILES/OUTPUT_FILES/LSTM_TN_LUCIDA/eng.lstm-punc-dawg
Moving /tmp/tmp.iafCx7Aypj/eng/eng.word-dawg to /home/pl/Downloads/SRI_/USING_FILES/OUTPUT_FILES/LSTM_TN_LUCIDA/eng.lstm-word-dawg
Moving /tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0.lstmf to /home/pl/Downloads/SRI_/USING_FILES/OUTPUT_FILES/LSTM_TN_LUCIDA

Completed training for language 'eng'

root@pl:~/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master# 
```

**Comment by wqret1992** [comment]
[error_text_when_training_data_generated.txt](https://github.com/tesseract-ocr/tesseract/files/1147429/error_text_when_training_data_generated.txt)
[tess_output_for_img_txt.txt](https://github.com/tesseract-ocr/tesseract/files/1147428/tess_output_for_img_txt.txt)

**Comment by Shreeshrii** [comment]
check  that your unicharset file is in utf8 encoding and not ANSI

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by wqret1992** [comment]
Hello shree devi, can you please tell how to generate unicharset file in utf-8 format.. i am not able to find a way for that.
Can you please tell me.

**Comment by amitdo** [comment]
```
=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=/home/pl/Downloads/SRI_/USING_FILES/TARS2_/tesseract-master/tessdata
[Tue Jul 11 13:05:57 IST 2017] /usr/local/bin/tesseract /tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0.tif /tmp/tmp.iafCx7Aypj/eng/eng.Lucida_Sans.exp0 lstm.train
Info in bmfCreate: Generating pixa of bitmap fonts from string
Error: unichar y in normproto file is not in unichar set.
....
```

This looks strange, because the error here comes from the legacy OCR engine, not the LSTM engine.

**Comment by wqret1992** [comment]
@amitdo  Can you please say what can i do to avoid this and train tesseract normally.

Can u give any clue why this is happening.

**Comment by amitdo** [comment]
Sorry, I don't know why it is happening.

**Comment by wqret1992** [comment]
@Shreeshrii @amitdo 

i am able to generate training data with tesseract code, which i have downloaded around april.
this is the text output regarding that. everyhting seems normal

``
=== Starting training for language 'eng'
[Sat Jul 15 23:49:58 IST 2017] /usr/bin/text2image --fonts_dir=/usr/share/fonts --font=FreeSans --outputbase=/tmp/font_tmp.9J4DwTjR0e/sample_text.txt --text=/tmp/font_tmp.9J4DwTjR0e/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.9J4DwTjR0e
Rendered page 0 to file /tmp/font_tmp.9J4DwTjR0e/sample_text.txt.tif
Rtl = 0 ,vertical=0

=== Phase I: Generating training images ===
Rendering using FreeSans
[Sat Jul 15 23:50:24 IST 2017] /usr/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.9J4DwTjR0e --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.RCyux9nJxb/eng/eng.FreeSans.exp0 --font=FreeSans --text=/home/dell/Downloads/Tesseract_new/tess_text/eng/eng.training_text
Rendered page 0 to file /tmp/tmp.RCyux9nJxb/eng/eng.FreeSans.exp0.tif
Rendered page 1 to file /tmp/tmp.RCyux9nJxb/eng/eng.FreeSans.exp0.tif
Rtl = 0 ,vertical=0

=== Phase UP: Generating unicharset and unichar properties files ===
[Sat Jul 15 23:50:26 IST 2017] /usr/bin/unicharset_extractor -D /tmp/tmp.RCyux9nJxb/eng/ /tmp/tmp.RCyux9nJxb/eng/eng.FreeSans.exp0.box
Extracting unicharset from /tmp/tmp.RCyux9nJxb/eng/eng.FreeSans.exp0.box
Wrote unicharset file /tmp/tmp.RCyux9nJxb/eng//unicharset.
[Sat Jul 15 23:50:26 IST 2017] /usr/bin/set_unicharset_properties -U /tmp/tmp.RCyux9nJxb/eng/eng.unicharset -O /tmp/tmp.RCyux9nJxb/eng/eng.unicharset -X /tmp/tmp.RCyux9nJxb/eng/eng.xheights --script_dir=/home/dell/Downloads/Tesseract_new/tess_text
Loaded unicharset of size 115 from file /tmp/tmp.RCyux9nJxb/eng/eng.unicharset
Setting unichar properties
Other case FF of ff is not in unicharset
Other case É of é is not in unicharset
Other case FI of fi is not in unicharset
Warning: properties incomplete for index 25 = ~
Writing unicharset to file /tmp/tmp.RCyux9nJxb/eng/eng.unicharset

=== Phase D: Generating Dawg files ===
Generating word Dawg
[Sat Jul 15 23:50:26 IST 2017] /usr/bin/wordlist2dawg -r 1 /home/dell/Downloads/Tesseract_new/tess_text/eng/eng.wordlist /tmp/tmp.RCyux9nJxb/eng/eng.word-dawg /tmp/tmp.RCyux9nJxb/eng/eng.unicharset
Set reverse_policy to RRP_REVERSE_IF_HAS_RTL
Loading unicharset from '/tmp/tmp.RCyux9nJxb/eng/eng.unicharset'
Reading word list from '/home/dell/Downloads/Tesseract_new/tess_text/eng/eng.wordlist'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.RCyux9nJxb/eng/eng.word-dawg'
Generating frequent-word Dawg
[Sat Jul 15 23:50:30 IST 2017] /usr/bin/wordlist2dawg -r 1 /tmp/tmp.RCyux9nJxb/eng/eng.wordlist.clean.freq /tmp/tmp.RCyux9nJxb/eng/eng.freq-dawg /tmp/tmp.RCyux9nJxb/eng/eng.unicharset
Set reverse_policy to RRP_REVERSE_IF_HAS_RTL
Loading unicharset from '/tmp/tmp.RCyux9nJxb/eng/eng.unicharset'
Reading word list from '/tmp/tmp.RCyux9nJxb/eng/eng.wordlist.clean.freq'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.RCyux9nJxb/eng/eng.freq-dawg'
[Sat Jul 15 23:50:30 IST 2017] /usr/bin/wordlist2dawg -r 0 /home/dell/Downloads/Tesseract_new/tess_text/eng/eng.punc /tmp/tmp.RCyux9nJxb/eng/eng.punc-dawg /tmp/tmp.RCyux9nJxb/eng/eng.unicharset
Set reverse_policy to RRP_DO_NO_REVERSE
Loading unicharset from '/tmp/tmp.RCyux9nJxb/eng/eng.unicharset'
Reading word list from '/home/dell/Downloads/Tesseract_new/tess_text/eng/eng.punc'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.RCyux9nJxb/eng/eng.punc-dawg'
[Sat Jul 15 23:50:30 IST 2017] /usr/bin/wordlist2dawg -r 0 /home/dell/Downloads/Tesseract_new/tess_text/eng/eng.numbers /tmp/tmp.RCyux9nJxb/eng/eng.number-dawg /tmp/tmp.RCyux9nJxb/eng/eng.unicharset
Set reverse_policy to RRP_DO_NO_REVERSE
Loading unicharset from '/tmp/tmp.RCyux9nJxb/eng/eng.unicharset'
Reading word list from '/home/dell/Downloads/Tesseract_new/tess_text/eng/eng.numbers'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.RCyux9nJxb/eng/eng.number-dawg'
[Sat Jul 15 23:50:30 IST 2017] /usr/bin/wordlist2dawg -r 1 /home/dell/Downloads/Tesseract_new/tess_text/eng/eng.word.bigrams /tmp/tmp.RCyux9nJxb/eng/eng.bigram-dawg /tmp/tmp.RCyux9nJxb/eng/eng.unicharset
Set reverse_policy to RRP_REVERSE_IF_HAS_RTL
Loading unicharset from '/tmp/tmp.RCyux9nJxb/eng/eng.unicharset'
Reading word list from '/home/dell/Downloads/Tesseract_new/tess_text/eng/eng.word.bigrams'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.RCyux9nJxb/eng/eng.bigram-dawg'

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=/home/dell/Downloads/Tesseract_new/tesseract-master/tessdata
[Sat Jul 15 23:50:45 IST 2017] /usr/local/bin/tesseract /tmp/tmp.RCyux9nJxb/eng/eng.FreeSans.exp0.tif /tmp/tmp.RCyux9nJxb/eng/eng.FreeSans.exp0 lstm.train
Info in bmfCreate: Generating pixa of bitmap fonts from string
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Page 1
Page 2
Loaded 53/53 pages (1-53) of document /tmp/tmp.RCyux9nJxb/eng/eng.FreeSans.exp0.lstmf

=== Constructing LSTM training data ===
Moving /tmp/tmp.RCyux9nJxb/eng/eng.unicharset to /home/dell/Downloads/Tesseract_new/output_dir/FreeSans/LSTM_FILES_1STEP/
Moving /tmp/tmp.RCyux9nJxb/eng/eng.number-dawg to /home/dell/Downloads/Tesseract_new/output_dir/FreeSans/LSTM_FILES_1STEP//eng.lstm-number-dawg
Moving /tmp/tmp.RCyux9nJxb/eng/eng.punc-dawg to /home/dell/Downloads/Tesseract_new/output_dir/FreeSans/LSTM_FILES_1STEP//eng.lstm-punc-dawg
Moving /tmp/tmp.RCyux9nJxb/eng/eng.word-dawg to /home/dell/Downloads/Tesseract_new/output_dir/FreeSans/LSTM_FILES_1STEP//eng.lstm-word-dawg
Moving /tmp/tmp.RCyux9nJxb/eng/eng.FreeSans.exp0.lstmf to /home/dell/Downloads/Tesseract_new/output_dir/FreeSans/LSTM_FILES_1STEP/

Completed training for language 'eng'

**Comment by wqret1992** [comment]
@Shreeshrii @amitdo 

I request any body give me brief overview,  how to train tesseract 4 with image files. How to give box and tif pairs to tesseract..

In the above command we can only see text file has been given to tesseract. What should be done if i want a image and box file is to given to tesseract.

Please advise me.

**Comment by Shreeshrii** [comment]
lstm training with box/tiff pairs is currently not supported.

**Comment by Shreeshrii** [comment]
> can you please tell how to generate unicharset file in utf-8 format

Use a text editor which can save file in utf-8 encoding. I use notepad++.

**Comment by Okersira** [comment]
you need add
--linedata_only

**Comment by Shreeshrii** [comment]
English can be trained with tesseract 4.0.0 using default files. The initial tesstrain.sh step creates the starter traineddata, which should be followed by lstmtraining.

Please read https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00

@zdenop Please close this issue.
