### ISSUE TITLE
error:'string' does not name a type

### ISSUE THREAD

**Issue by atuc17** [tesseract-ocr/tesseract#1047]
I guess the problem is that file unichar.h missed using namespace std;

In file included from /usr/local/include/tesseract/ltrresultiterator.h:26:0,
                 from /usr/local/include/tesseract/resultiterator.h:26,
                 from /usr/local/include/tesseract/baseapi.h:31,
                 from ../scr/detect_text.cpp:1:
/usr/local/include/tesseract/unichar.h:164:10: error: ‘string’ does not name a type
   static string UTF32ToUTF8(const std::vector<char32>& str32);
          ^~~~~~
`------------------------`

### Environment

* **Tesseract Version**:  4.00.00
* **Commit Number**: 
* **Platform**:  ubuntu 17.04

**Comment by amitdo** [comment]
See #1045. Try again with the latest commit.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
