### ISSUE TITLE
Unused function PrepareDistortedPix()

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#1052]
@theraysmith, 

The new (c1c1e426b327) function PrepareDistortedPix() in training/degradeimage.h is not being used currently.
https://github.com/tesseract-ocr/tesseract/blob/4efc539f512bf/training/degradeimage.h#L38

Are you going to fix that?

**Comment by amitdo** [comment]
@theraysmith 

Another try... hope you'll notice. Please read my above message (at !#1052). 

Please also see #1024

**Comment by theraysmith** [comment]
It is used internally at Google.
Text2image could be modified to use it too.

**Comment by Shreeshrii** [comment]
> Text2image could be modified to use it too.

That would be great. This is what I referred to in - https://github.com/tesseract-ocr/tessdata/issues/69#issuecomment-320302092

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesseract/issues/2221
That gives an indication that this function might have been used while training the _fast models.

@stweil Can this or parts of it be added to the currently used degradeimage function?

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/5fdaa479da2c52526dac1281871db5c4bdaff359/src/training/degradeimage.cpp#L184-L185

**Comment by Shreeshrii** [comment]
Partial implementation via  #2259
