### ISSUE TITLE
Win64 build fails on Visual Studio 2017

### ISSUE THREAD

**Issue by tdhintz** [tesseract-ocr/tesseract#1053]
The following line generates an error because `#include <algorithm>` is missing.

`max_offset = std::max(max_offset, (*code)(i)-han_offset);`

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'max': is not a member of 'std'	libtesseract	<path>\tesseract\ccutil\unicharcompress.cpp	208

**Comment by egorpugin** [comment]
Thanks!
But you did not push PR to our repository, so we cannot apply it.
You MUST create PR inside your github repo, not ours, then it should appear here.

**Comment by egorpugin** [comment]
Fixed https://github.com/tesseract-ocr/tesseract/pull/1054
