### ISSUE TITLE
Error	11	error LNK1104: cannot open file 'liblept171d.lib'

### ISSUE THREAD

**Issue by vanphuong357** [tesseract-ocr/tesseract#1056]
I try to build tesseract-3.04.00 on Visualstudio13 and have as issue as
Error	11	error LNK1104: cannot open file 'liblept171d.lib'. Please telI me, how to fix.
Thank in advance.

**Comment by stweil** [comment]
I suggest to try Tesseract 3.05. And please have a look at the [hints regarding support](https://github.com/tesseract-ocr/tesseract/wiki#support) in the Tesseract wiki.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
