### ISSUE TITLE
Unexpected surface format -1 

### ISSUE THREAD

**Issue by zhousteven** [tesseract-ocr/tesseract#1061]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below. 

------------------------

### Environment
Centos7
* **Tesseract Version**: 
tesseract 4.00.00alpha
 leptonica-1.74.4
  libjpeg 6b (libjpeg-turbo 1.2.90) : libpng 1.5.13 : libtiff 4.0.3 : zlib 1.2.7 : libwebp 0.3.0

 Found SSE

* **Commit Number**: 
* **Platform**: 
Linux System
### Current Behavior:
when run below command line in Centos7 system,all raw data comes from langdata file without any change.i try to change option parameter --ysize=48000 to transfer text file to image format follow handle reference..got this error,and try to search in issues which been showed in official website, but nobody encounter this error.some master can help fix the bug?
[root@localhost tesseract-ocr]# /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ityyPvgGxz --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.fjZbtlBpd5/chi_sim/chi_sim.STFangsong.exp0 --ysize=48000 --font=STFangsong --text=../langdata/chi_sim/chi_sim.training_text

in my log file show only these lines:
Unexpected surface format -1
Unexpected surface format -1
Unexpected surface format -1
Unexpected surface format -1
Unexpected surface format -1
Unexpected surface format -1
Unexpected surface format -1

**Comment by amitdo** [comment]
`--ysize=48000`

the default value for ysize is 4800. Why do you want 10 times larger page height?

**Comment by zhousteven** [comment]
want to render all raw data(480 lines) in a image of type .tiff, last night, i found that the box file contains all the desire characters,does it mean,the situation that tiff image contents didn't contain all characters is reasonable. if so, this may by not an error,just jump out of program spaces.

**Comment by amitdo** [comment]
Just keep the ysize in its default value. text2imhge will create multi-page tiff for you.

**Comment by zhousteven** [comment]
got it,thanks!

**Comment by Shreeshrii** [comment]
@zdenop Please close this issue.
