### ISSUE TITLE
Devanagari Unicharset not being compressed after training

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1068]
>For the scripts that use a virama character to generate conjunct consonants, (All the Indic scripts plus Myanmar and Khmer) the function NormalizeCleanAndSegmentUTF8 pairs the virama with an appropriate neighbor to generate a more glyph-oriented encoding in the unicharset. To make full use of this improvement, the --pass_through_recoder flag should be set for combine_lang_model for these scripts.

as per https://github.com/tesseract-ocr/tesseract/blob/master/training/tesstrain_utils.sh

```
  local pass_through=""
  # TODO(rays) set using script lang lists.
  case "${LANG_CODE}" in
    asm | ben | bih | hin | mar | nep | guj | kan | mal | tam | tel | pan | \
    dzo | sin | san | bod | ori | khm | mya | tha | lao | heb | yid | ara | \
    fas | pus | snd | urd | div | syr | uig | kur_ara )
      pass_through="--pass_through_recoder" ;;
```

However, I find that while the `san.unicharset` as part of `best traineddata` has only **145** characters, the newly generated starter unicharset through tesstrain.sh has the glyph based larger unicharset of **2308** and the final traineddata also has the larger unicharset of **2308** characters.

@theraysmith 

Is this the desired behavior or are we missing a step to convert the glyph based unicharset to the compressed unicharset after stopping training?

Also, how do we update the version string to be included in the final traineddata after training?

I am using the following command to build the final traineddata.

```
lstmtraining   --stop_training  \
  --continue_from  ../tesstutorial/vedic/santune_checkpoint  \
  --traineddata ../tesstutorial/vedic/san/san.traineddata  \
  --model_output ../tesstutorial/vedic/vedic.traineddata
```

**Comment by Shreeshrii** [comment]
```

USAGE: combine_lang_model
  --lang_is_rtl  True if lang being processed is written right-to-left  (type:bool default:false)
  --pass_through_recoder  If true, the recoder is a simple pass-through of the unicharset. Otherwise, potentially a compression of it  (type:bool defa
ult:false)
  --input_unicharset  Unicharset to complete and use in encoding  (type:string default:)
  --script_dir  Directory name for input script unicharsets  (type:string default:)
  --words  File listing words to use for the system dictionary  (type:string default:)
  --puncs  File listing punctuation patterns  (type:string default:)
  --numbers  File listing number patterns  (type:string default:)
  --output_dir  Root directory for output files  (type:string default:)
  --version_str  Version string to add to traineddata file  (type:string default:)
  --lang  Name of language being processed  (type:string default:)
```

**Comment by amitdo** [comment]
I believe that `[lang].lstm-recoder` is the compressed unicharset.

**Comment by amitdo** [comment]
It's a binary file, unlike the unicharset which is a textual file.

**Comment by Shreeshrii** [comment]
See Ray's comment at https://github.com/tesseract-ocr/tesseract/issues/1065#issuecomment-320709273

Needed to handedit the input unicharset

Will be fixed with new unichar_extractor.

**Comment by christophered** [comment]
@amitdo 
> I believe that [lang].lstm-recoder is the compressed unicharset.

Then why `eng.trainneddata` contains both `eng.lstm-unicharset` & `eng.lstm-recoder`?
Also, is there a way to unpack `eng.lstm-recoder`?

**Comment by kingmoduk** [comment]
hello world

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/bdf6629722ed795ead0b68ce9581d88b81e4165d/doc/combine_tessdata.1.asc
