### ISSUE TITLE
combine_lang_model not found

### ISSUE THREAD

**Issue by iuriigalaida** [tesseract-ocr/tesseract#1071]
I tried to train tesseract v4.0 and got 'combine_lang_model not found' error. This code was added 4 days ago so I tried to build latest master and got '.cppan/storage/etc/static/generate.cmake:106 (message):
  cppan command '0' not found '. Can somone build and share latest tesseract binaries for Windows. Thanks in advance.

**Comment by Shreeshrii** [comment]
You can use windows binaries linked from
https://github.com/UB-Mannheim/tesseract/wiki

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by iuriigalaida** [comment]
Yes. It worked. Thanks a lot ShreeDevi!
