### ISSUE TITLE
chi_sim can't recognize auto, and not right.

### ISSUE THREAD

**Issue by zhangchunsheng** [tesseract-ocr/tesseract#1078]
The original image
https://image.ibb.co/fEkAma/WX20170813_165113_2x.png

If there is no -l arg, the result is look like below.

> tesseract WX20170813_165113_2x.png stdout
IH640 done
ﬁﬁiaiﬂﬁma done
iiiéimﬁiiﬁﬁ done
ﬁlm: done
ﬁEEE done

> tesseract WX20170813_165113_2x.png stdout -l chi_sim
图片640 done
每页记录数可配 done
选择城市报错 done
地图检索 done
弹囡宽度 done

Another problem is the charactor "囡" in "弹囡宽度"，actually it is "窗".

**Comment by Shreeshrii** [comment]
use --oem 1 for the newer lstm engine

use the newly uploaded tessdata/best/chi_sim.traineddata

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by zhangchunsheng** [comment]
tesseract WX20170813_165113_2x.png stdout -l chi_sim
read_params_file: parameter not found:

Do I need to upgrade tessdata? @Shreeshrii

**Comment by Shreeshrii** [comment]
Use the traineddata from
https://github.com/tesseract-ocr/tessdata/tree/master/best

You can try

https://github.com/tesseract-ocr/tessdata/blob/master/best/HanS.traineddata
and
https://github.com/tesseract-ocr/tessdata/blob/master/best/chi_sim.traineddata

Make sure you have tesseract from latest sources in github



ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by zhangchunsheng** [comment]
Ok, Thanks.
