### ISSUE TITLE
Disabling OpenMP for Windows & Linux

### ISSUE THREAD

**Issue by Belval** [tesseract-ocr/tesseract#1081]
### Environment

* **Tesseract Version**: Latest / cloned from master
* **Platform**: Windows 10 x64 with VS2017

### Current Behavior:

The compiling section does not explain how to compile under Windows without OpenMP (neither under Linux mind you). How can it be done?

### Expected Behavior:

The compiling section of the wiki should include such informations as they are quite important if the binaries are to be used in a heavily threaded environnement.

### Suggested Fix:

For Linux, add a line in the wiki about using `./configure --disable-openmp` flag (although you can simply use `./configure --help`)

For Windows, add a line explaining how it can be done (I haven't figured out that one yet)

I am more than willing to make a PR for this if you consider it necessary, if not, **how can it be achieved under Windows?**

**Comment by stweil** [comment]
The option `--disable-openmp` works for Windows with Mingw-w64, too. You don't need it neither for Linux nor for Windows, because it is possible to tell OpenMP not to create any threads:

    export OMP_THREAD_LIMIT=1
    tesseract ...

or

    OMP_THREAD_LIMIT=1 tesseract ...

You can help improving the Wiki by adding any important information which is currently missing.

**Comment by Belval** [comment]
@stweil Than you for the quick response. I am using MSVC. Any parameter for that one? Also how can I set `OMP_THREAD_LIMIT` in Windows?
