### ISSUE TITLE
 Tesseract cant detect,its simple

### ISSUE THREAD

**Issue by pashaaa** [tesseract-ocr/tesseract#1083]
### Environment

* **Tesseract Version**: v4.00.00alpha
* **Platform**:  Windows7, version  64-bit

![1](https://user-images.githubusercontent.com/3613259/29336557-6b146636-8223-11e7-8d6b-6f74d61a7e72.jpg)

### Current Behavior:
 --oem 3 --psm 11 -l eng out.txt
 --oem 1 --psm 4 -l eng out.txt
 --oem 1 --psm 8 -l eng out.txt

output is S7LYHz
output is 57 LYHz
output is S7 LYHz

its simpleand clear

**Comment by scardine** [comment]
Looks like you are frustrated by Tesseract's performance. This is perfectly fine, but unfortunately this is not the right channel to vent about it.

From Contributing.md:

> Use the users mailing-list instead of creating an Issue if you are not satisfied with the accuracy of the OCR, and want to ask how you can improve it. Note: You should first read the [ImproveQuality](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality) wiki page.

Please check [CONTRIBUTING](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md) before opening an issue here.
