### ISSUE TITLE
build error for vs2015 64bit

### ISSUE THREAD

**Issue by CicadaKim** [tesseract-ocr/tesseract#1086]
### Environment

* **Tesseract Version**: 4.0
* **Commit Number**: 
* **Platform**: 
windows 64bit vs2015 community

2 error on build
1. in validator.cpp,
error c2039: back_inserter is not member of std and etc...
i solve it adding #include <iterator> in validator.cpp but i'm not sure it's enough.( build is working)

2. text2image project
if I build solution with text2image in Training Tools,
there are so many error
one of them:
variable "CPPAN_SYMBOL_IMPORT" is not name...blahblah <- i'm not english user 
in many header file on text2image

so i build solution excluding text2image. and it wokr. but i hope i can build it together

**Comment by egorpugin** [comment]
Thanks for the report!
Please download new cppan client (or run `cppan --self-upgrade`) and try to build tesseract again.
(Run `cppan` in tess folder, re-run cmake and try to build in VS.)

**Comment by LaurentBerger** [comment]
@CicadaKim you mean #include <iterator>

**Comment by CicadaKim** [comment]
Thank you for re-comment. I did it at that time but it's not working.
maybe my environment is something wrong.. retry after time.

**Comment by zdenop** [comment]
I check this with vs2017 on windows 10 64bit and it works.
