### ISSUE TITLE
error compiling text module in opencv 

### ISSUE THREAD

**Issue by LaurentBerger** [tesseract-ocr/tesseract#1091]
Hi, 
I have compiled tesseract 4.00.0 alpha using vs 2015 and now I want to compile text module in opencv I have got an error at : 

at line 164 of tesseract/unichar.h error 3646 'UTF32ToUtf8 'string' : unknown override specifier

[Another user](http://answers.opencv.org/question/172513/string-name-type-error-on-make-for-opencv-320330-with-tesseract/) got this message 
tesseract/unichar.h:164:10: error: ‘string’ does not name a type static string UTF32ToUTF8(const std::vector<char32>& str32); 

If I replace [line ](https://github.com/tesseract-ocr/tesseract/blob/aee910a7bfcbe0366806b68dc7f20535764c06d4/ccutil/unichar.h#L164)

static string UTF32ToUTF8(const std::vector<char32>& str32);

with 

static std::string UTF32ToUTF8(const std::vector<char32>& str32);

problem is solved for vs2015.

Is it an opencv problem or a tesseract problem ?

**Comment by zdenop** [comment]
please read other issues (also closed) before writing new issue.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues?utf8=%E2%9C%93&q=std%20string%20

**Comment by LaurentBerger** [comment]
@zdenop my mistake : not to read closed issue. thanks you very much
