### ISSUE TITLE
error: 'p1' was not declared in this scope

### ISSUE THREAD

**Issue by chankyu-choi** [tesseract-ocr/tesseract#1095]
### Environment

* **Tesseract Version**: tesseract 4.00.00alpha
* **Commit Number**: 1e3bf29cf6ca60b3eb318615b41da127b1d0eb4e
* **Platform**:  docker (tesseractshadow/tesseract4cmp)

### Current Behavior:
/usr/local/include/tesseract/tesscallback.h: In member function 'virtual R _TessFunctionResultCallback_6_5<del, R, P1, P2, P3, P4, P5, P6, A1, A2, A3, A4, A5>::Run(A1, A2, A3, A4, A5)':
/usr/local/include/tesseract/tesscallback.h:9666:31: error: 'p1_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                               ^
/usr/local/include/tesseract/tesscallback.h:9666:35: error: 'p2_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                                   ^
/usr/local/include/tesseract/tesscallback.h:9666:39: error: 'p3_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                                       ^
/usr/local/include/tesseract/tesscallback.h:9666:43: error: 'p4_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                                           ^
/usr/local/include/tesseract/tesscallback.h:9666:47: error: 'p5_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                                               ^
/usr/local/include/tesseract/tesscallback.h:9666:51: error: 'p6_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                                                   ^
/usr/local/include/tesseract/tesscallback.h:9669:31: error: 'p1_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                               ^
/usr/local/include/tesseract/tesscallback.h:9669:35: error: 'p2_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                                   ^
/usr/local/include/tesseract/tesscallback.h:9669:39: error: 'p3_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                                       ^
/usr/local/include/tesseract/tesscallback.h:9669:43: error: 'p4_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                                           ^
/usr/local/include/tesseract/tesscallback.h:9669:47: error: 'p5_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);
                                               ^
/usr/local/include/tesseract/tesscallback.h:9669:51: error: 'p6_' was not declared in this scope
       R result = (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);

### Help me:
I tested Basic example(https://github.com/tesseract-ocr/tesseract/wiki/APIExample), but I got above errors. Could you help me...

**Comment by devtodev** [comment]
I have the same problem, Did somebody fix it?

**Comment by amitdo** [comment]
>Platform: docker (tesseractshadow/tesseract4cmp)

We don't support 3rd party software.
 
Try ask the creator: https://github.com/tesseract-shadow

**Comment by shodow** [comment]
I have the same error,when the code is 
```
using namespace std;
#include <tesseract/baseapi.h>
#include <leptonica/allheaders.h>
```
change to 

```
#include <tesseract/baseapi.h>
#include <leptonica/allheaders.h>
using namespace std;
```
will solve it
