### ISSUE TITLE
tesseract read from gs

### ISSUE THREAD

**Issue by shengc** [tesseract-ocr/tesseract#1096]
I built tesseact out of 4.00.00dev. It seems like it has trouble directly reading stdin from ghostscript. Check out the following...

    gs -q -dNOPAUSE -sDEVICE=tiffg4 -sOutputFile=- demo.pdf -c quit | bin/tesseract stdin demo.ocr -oem 4

then it gives this error:

     Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
     TIFFFillStrip: Invalid strip byte count 0, strip 0.
     Error in pixReadFromTiffStream: line read fail

However if I generate the image first using ghostscript, then pipe the image to the stdin of tesseract, then it works. 

    gs -q -dNOPAUSE -sDEVICE=tiffg4 -sOutputFile=- demo.pdf -c quit > demo.tif
    cat demo.tif | bin/tesseract stdin demo.ocr -oem 4

**Comment by jbreiden** [comment]
I don't understand what could cause this.

**Comment by stweil** [comment]
Does one or both of the following commands work?

    gs -q -dNOPAUSE -sDEVICE=tiffg4 -sOutputFile=- demo.pdf -c quit | dd | bin/tesseract stdin demo.ocr -oem 4
    gs -q -dNOPAUSE -sDEVICE=tiffg4 -sOutputFile=- demo.pdf -c quit | dd bs=4096 | bin/tesseract stdin demo.ocr -oem 4

**Comment by shengc** [comment]
@stweil 

both failed

    gs -q -dNOPAUSE -sDEVICE=tiffg4 -sOutputFile=- demo.pdf -c quit | dd | bin/tesseract stdin demo.ocr -oem 4
    Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
    391+11 records in
    395+1 records out
    202521 bytes (203 kB) copied, 0.210738 s, 961 kB/s
    TIFFFillStrip: Invalid strip byte count 0, strip 0.
    Error in pixReadFromTiffStream: line read fail

    gs -q -dNOPAUSE -sDEVICE=tiffg4 -sOutputFile=- demo.pdf -c quit | dd bs=4096 | bin/tesseract stdin demo.ocr -oem 4
    Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
    46+12 records in
    46+12 records out
    202521 bytes (203 kB) copied, 0.247508 s, 818 kB/s
    TIFFFillStrip: Invalid strip byte count 0, strip 0.
    Error in pixReadFromTiffStream: line read fail

**Comment by jbreiden** [comment]
Try running Tesseract under strace and see where things first become different.

```
gs -q -dNOPAUSE -sDEVICE=tiffg4 -sOutputFile=- demo.pdf -c quit  |strace  bin/tesseract stdin demo.ocr -oem 4
cat demo.tif | strace bin/tesseract stdin demo.ocr -oem 4
```

**Comment by Shreeshrii** [comment]
> I built tesseact out of 4.00.00dev

Please try a build with the latest code in github.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by shengc** [comment]
@Shreeshrii 

./configure: line 4188: syntax error near unexpected token `-mavx,'
./configure: line 4188: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'

**Comment by shengc** [comment]
@jbreiden Following is the diff right before the two processes write to stdout/stderr

```bash
< munmap(0x7fe1e9661000, 4096)            = 0
< brk(0)                                  = 0x2367000
< brk(0x238d000)                          = 0x238d000
< write(2, "TIFFFillStrip: ", 15TIFFFillStrip: )         = 15
< write(2, "Invalid strip byte count 0, stri"..., 35Invalid strip byte count 0, strip 0) = 35
< write(2, ".\n", 2.
< )                      = 2
< write(2, "Error in pixReadFromTiffStream: "..., 47Error in pixReadFromTiffStream: line read fail
< ) = 47
< close(3)                                = 0
< gettid()                                = 23463
...
```

```bash
> munmap(0x7f49e88ad000, 4096)            = 0
> brk(0)                                  = 0x1c2a000
> brk(0x1c50000)                          = 0x1c50000
> write(2, "Page 1\n", 7Page 1
> )                 = 7
> gettid()                                = 23501
> brk(0)                                  = 0x1c50000
> brk(0x1cc1000)                          = 0x1cc1000
> gettid()                                = 23501
...
```

**Comment by stweil** [comment]
The interesting part of the diff is expected earlier. Calls with file handle 0 (STDIN) are especially interesting. Can you upload both strace outputs?

**Comment by zdenop** [comment]
Closed because of missing input from reporter. For reopening issue more details are needed (except already asked strace output, also input file is need, a and information about OS, gs version, tesseract -v output. Output from gs to file (instead of stdin) could help too.
