### ISSUE TITLE
Warning message if admin rights are needed in the folder in windows

### ISSUE THREAD

**Issue by Thimxx** [tesseract-ocr/tesseract#1099]
This is an enhancement targeting user friendliness.

### Environment

* **Tesseract Version**: v4.0.0
* **Commit Number**: 20170804
* **Platform**: <Windows 10 64bits>

### Current Behavior:

When running tesseract on a folder that needs admin rights and you are using the option tessinput.tif as true the file tessinput.tif is not created and no warning message is provided

### Expected Behavior:

Either a warning message shall be provided to the user (the file will not be created as working in a admin rights folder) or the execution shall break with a similar message.
It took me 10 minutes to realize.

### Suggested Fix:

Just introduce writing permission before execution and introduce the error message.

**Comment by amitdo** [comment]
I think this is outside the scope of tesseract, and the issue should be closed.

@stweil?

**Comment by stweil** [comment]
I think this is a (minor) bug.

When Tesseract fails to create a file (missing rights, disk full, or any other reason on any operating system), this should always be handled somehow in the code. In most cases at least a warning should be printed, other cases are fatal errors. We also have conditions where Tesseract creates a file, but terminates before writing to that file. I'd consider such empty files also as a bug.

So for this issue the code needs a fix. If a user sets `-c tessedit_write_images=1`, there should be either a valid output file or a warning message. I'll have a look and prepare a pull request.

**Comment by zdenop** [comment]
@stweil : Will you prepare PR for before 4.0 release?

**Comment by stweil** [comment]
I don't think so if the release should be published in two weeks.

**Comment by amitdo** [comment]
@stweil, maybe you want to solve this old issue?

**Comment by stweil** [comment]
I added the "help wanted" label to attract new developers for Tesseract...

**Comment by zdenop** [comment]
Closing as we do not provide windows installer (officially).
