### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by nonameShadow** [tesseract-ocr/tesseract#110]
At first test it compiled fine with this code:

    TessBaseAPI tess;
    tess.Init(NULL, "eng", tesseract::OEM_DEFAULT);
    Pix* img = pixRead("C:\\Users\\Paul\\Pictures\\phototest.tif");

But then, I added this line

   tess.SetImage(img);

 And it won't compile with error:

error LNK2019: unresolved external symbol "public: void __cdecl tesseract::TessBaseAPI::SetImage(struct Pix const *)" (?SetImage@TessBaseAPI@tesseract@@QEAAXPEBUPix@@@Z) referenced in function main

I have VS 2013, Windows 8.1 64 bit both. Compiled both tesseract and leptonica for x64 system, included everything, but still it doesn't want to work correctly.

Hope for your help. Paul.

**Comment by peirick** [comment]
Looks like you forgot to link a library. Have you double checked all your depentencies?

**Comment by peirick** [comment]
dependencies sorry

**Comment by nonameShadow** [comment]
Hello, peirick.
I believe i did not, as far as i know.
I've included those 3 libs: 
libtesseract304d.lib
liblept171d.lib
tesseractd.lib

**Comment by zdenop** [comment]
What is tesseractd.lib? 
Did you try to use/link release version of dependancies instead of debug version?

**Comment by nonameShadow** [comment]
zdenop,
Yes, i've tried. Unfortunatly it still gives the same error.
Tried to disable tesseractd.lib (have no idea what's this).

**Comment by peirick** [comment]
Maybe have a look at the repository at https://github.com/peirick/leptonica you will find a build_tesseract.bat.

**Comment by zdenop** [comment]
Please use tesseract forum for support.
