### ISSUE TITLE
 Can't open lstm.train ?

### ISSUE THREAD

**Issue by yoyoshuang** [tesseract-ocr/tesseract#1101]
------------------------

### Environment

* **Tesseract Version**: Tesseract 4.00
* **Platform**:  Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-129-generic x86_64) 

When I use the tutorial [https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for-%C2%B1-a-few-characters] to fine tune the model
my command is 
```
training/tesstrain.sh  \
   --fonts_dir /usr/share/fonts \
  --lang chi_sim  \
  --linedata_only \
  --noextract_font_properties \
  --exposures "0"    \
  --langdata_dir ../langdata \
  --tessdata_dir /home/hs/tessdata/tessdata  \
  --output_dir ../tesstutorial/chi_sim
```
I found that it print out as below in "Phase I: Generating training images":

` training/text2image --fontconfig_tmpdir=/tmp/font_tmp.k2AbBhbk8p --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.4UpMo5R9vj/chi_sim/chi_sim.KaiTi_Normal.exp0 --max_pages=3 --font=KaiTi Normal --text=../langdata/chi_sim/chi_sim.training_text`

Notice that **--max_pages=3**, so I checked the ".tif" files, finding that the pages number is 3.
 
To my own work, I need more pages for the "tif/box" files, so I try to change the parameter “--max_pages” （ie, --max_pages=6）

Instead of run the command above, I try to finish its work step by step. But when I did the "Phase E: Generating lstmf files " there comes out a error which I can't solved:

```
root@super-desk:~/tesseract# api/tesseract /home/hs/tmp/chi_sim.AR_PL_UKai_CN.exp0.tif /home/hs/tmp/chi_sim.AR_PL_UKai_CN.exp0 lstm.train ../langdata/chi_sim/chi_sim.config
read_params_file: Can't open lstm.train
```

I don't know where is the " lstm.train", how can I find it?

Can anyone help me?

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/blob/master/tessdata/configs/lstm.train

make sure it is there under configs folder in your tessdata folder.

**Comment by yoyoshuang** [comment]
Thank you @Shreeshrii ~

**Comment by PUYANG123** [comment]
@Shreeshrii ~
I do this like: 
src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only \
  --noextract_font_properties --langdata_dir ../langdata \
  --tessdata_dir ./tessdata/best \
  --fontlist "Impact Condensed" --output_dir ~/tesstutorial/engeval
and occur Errors like this:
=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=./tessdata/best
[Thu Aug 1 14:56:11 CST 2019] /usr/local/bin/tesseract /tmp/eng-2019-08-01.MU0/eng.Impact_Condensed.exp0.tif /tmp/eng-2019-08-01.MU0/eng.Impact_Condensed.exp0 --psm 6 lstm.train
read_params_file: Can't open lstm.train
Tesseract Open Source OCR Engine v5.0.0-alpha with Leptonica
Page 1
Page 2
ERROR: /tmp/eng-2019-08-01.MU0/eng.Impact_Condensed.exp0.lstmf does not exist or is not readable

But my tesseract/tessdata/configs has this file : lstm.train  Why？

**Comment by Shreeshrii** [comment]
Change

--tessdata_dir ./tessdata/best 

to

--tessdata_dir  tesseract/tessdata

**Comment by PUYANG123** [comment]
@Shreeshrii 
Hi Shreeshrii  
 i do as follow this :https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00, and It asks me to put the eng.traineddata in the Best file ,if do this as you said, a new Error as like :
=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=./tessdata
[Thu Aug 1 15:19:42 CST 2019] /usr/local/bin/tesseract /tmp/eng-2019-08-01.pFg/eng.Impact_Condensed.exp0.tif /tmp/eng-2019-08-01.pFg/eng.Impact_Condensed.exp0 --psm 6 lstm.train
Error opening data file ./tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
ERROR: Program tesseract failed. Abort.

**Comment by PUYANG123** [comment]
cd ~/tesstutorial
git clone --depth 1 https://github.com/tesseract-ocr/tesseract.git
cd tesseract/tessdata
mkdir best
cd best
wget https://github.com/tesseract-ocr/tessdata_best/raw/master/eng.traineddata
wget https://github.com/tesseract-ocr/tessdata_best/raw/master/heb.traineddata
wget https://github.com/tesseract-ocr/tessdata_best/raw/master/chi_sim.traineddata

if I put eng.traineddata and chi_sim.traineddata and heb.traineddata to the best file and run src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only \
  --noextract_font_properties --langdata_dir ../langdata \
  --tessdata_dir ./tessdata \
  --fontlist "Impact Condensed" --output_dir ~/tesstutorial/engeval
and Error occurs that can not find eng.traineddata

**Comment by PUYANG123** [comment]
drwxr-xr-x  5 root root 4096 Aug  1 15:19 ./
drwxr-xr-x 15 root root 4096 Aug  1 15:13 ../
drwxr-xr-x  2 root root 4096 Aug  1 14:35 best/
drwxr-xr-x  2 root root 4096 Aug  1 14:29 configs/
-rw-r--r--  1 root root   33 Aug  1 14:29 eng.user-patterns
-rw-r--r--  1 root root   27 Aug  1 14:29 eng.user-words
-rw-r--r--  1 root root  184 Aug  1 14:29 Makefile.am
-rw-r--r--  1 root root  572 Aug  1 14:29 pdf.ttf
drwxr-xr-x  2 root root 4096 Aug  1 14:29 tessconfigs/
==================================
drwxr-xr-x 2 root root     4096 Aug  1 14:35 ./
drwxr-xr-x 5 root root     4096 Aug  1 15:19 ../
-rw-r--r-- 1 root root 13077423 Aug  1 14:35 chi_sim.traineddata
-rw-r--r-- 1 root root 15400601 Aug  1 14:34 eng.traineddata
-rw-r--r-- 1 root root  3704077 Aug  1 14:34 heb.traineddata
================================
Is there a problem with this structure catalog?

**Comment by Shreeshrii** [comment]
tessdata/best/eng.traineddata is used as the base for further training when you use lstmtraining.

For tesstrain.sh, it expects eng.traineddata and config files in directory specified by TESSDATA_PREFIX 

Easiest solution will be to either copy or symlink both eng.traineddata and osd.traineddata from tessdata/best in tessdata

You can also check `env` for TESSDATA_PREFIX variable and see where thesefiles are installed.

**Comment by PUYANG123** [comment]
@Shreeshrii 
I do this: export TESSDATA_PREFIX=/root/tesstutorial/tesseract/tessdata/best ,But still fail and cannot find tessdata,why?

**Comment by PUYANG123** [comment]
@Shreeshrii
how to set TESSDATA_PREFIX ,Can you give an example for me ? Thanks

**Comment by Shreeshrii** [comment]
` export TESSDATA_PREFIX=/root/tesstutorial/tesseract/tessdata`

AND

`cp tesseract/tessdata/best/eng.traineddata tesseract/tessdata/eng.traineddata `
or
`ln -s tesseract/tessdata/best/eng.traineddata tesseract/tessdata/eng.traineddata `

**Comment by Shreeshrii** [comment]
Wiki instructions will need to be modified so that this issue does not occur.

**Comment by juliangilbey** [comment]
And the wiki instructions should mention where to put lstm.train.
