### ISSUE TITLE
numbers are not extracted while using  "-l heb+eng" but are extracted when using "-l eng" alone

### ISSUE THREAD

**Issue by amitm02** [tesseract-ocr/tesseract#1102]
Attempting the OCR the following document document: [link](https://www.dropbox.com/s/6d2x2gvvzko0wsc/002.png?dl=0)

- If setting Tesseract for English language alone  ("-l eng"), the numbers are getting extracted (the Hebrew character obviously do not).
- If attempting to use Hebrew language or Hebew+English ("-l heb+eng"), the Hebrew characters are extracted, but the numbers are all shown as a single "0".

Perhaps a bug related to RTL languages? 

Tesseract Version: 4.00.00alpha
platform: Darwin Kernel Version 16.7.0 (OXS)
------------------------

**Comment by amitdo** [comment]
Hi Amit!

It works for me with -l best/heb

**Comment by amitm02** [comment]
Thanks @amitdo!
I'm not familiar with "best", what is it? Is there a documentation reference you can point me to?

**Comment by amitdo** [comment]
Even better: -l best/Hebrew

The Hebrew.traineddata was trained for Hebrew and English.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tessdata/tree/master/best

You can create 'best' folder in your 'tessdata' folder and put there the traindata files you need from the above link.

Then you can use -l best/heb

**Comment by amitm02** [comment]
What is the difference between "best/heb" and the regular "heb"?

**Comment by amitdo** [comment]
>What is the difference between "best/heb" and the regular "heb"?

When you use best/heb Tesseract uses /tessdatapath/tessdata/best/heb.traindata. When you use heb it uses /tessdatapath/tessdata/heb.traindata.

The best folder in https://github.com/tesseract-ocr/tessdata/tree/master contains the newest traineddata models.

You need to build Tesseract from the master branch.

**Comment by amitm02** [comment]
Got it. 
So /best contains the newer, better models.
best/Hebrew is the newer trained data for both Hebrew and English.
best/heb is the newer trained data for Hebrew only.

This is very helpful @amitdo, i couldn't find this information in the wiki..

**Comment by amitdo** [comment]
If you want, you can put the new files in /tessdatapath/tessdata and then use just -l heb.

**Comment by amitm02** [comment]
attached another example image: [link](https://www.dropbox.com/s/h7oqngstm2h2gjz/test.png?dl=0)
Even, when using best trained data, problem pressist.
"-l best/eng" extract the numbers.
"-l best/Hebrew" does not extract the number, instead putting 0 where there is a number.

**Comment by amitdo** [comment]
I don't know why it fails to read the numbers in the second example.

**Comment by amitdo** [comment]
If I erase the NIS, I get:

>נזק ע"פ שמאי $450.00
שכ"ט שמאי 650.00

![test](https://user-images.githubusercontent.com/13571208/29920780-c7ddae28-8e57-11e7-8661-5b395f522851.png)

![test10](https://user-images.githubusercontent.com/13571208/29920874-349ec830-8e58-11e7-91dd-6b0203f18753.png)

**Comment by amitm02** [comment]
Hmm.. strange indeed. It repeats in many similar examples. Hopefully a fix would be found..

**Comment by christophered** [comment]
I think you need to fine-tune the model (training an existing model on new data without changing any part of the network) have a look at:
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for-impact

**Comment by amitm02** [comment]
I'm was dive into trying to fine tune the model, but as a last check, i've looked into the segmentation marks via VietOCR UI front-end. My observations:

- The numbers are getting segmented just perfect. 
- The number fonts look good. (or at least just as good as the Hebrew chars it managed to extract).
- Tesseract converts all the numbers to 0, and not replace the digits with the wrong value.

Hence, it seems to me that it is a software bug and not a network tweaking issue.

![29920780-c7ddae28-8e57-11e7-8661-5b395f522851](https://user-images.githubusercontent.com/1888927/33313426-4a020a5e-d433-11e7-9593-4dd4fa56f381.png)
<img width="1049" alt="screenshot 2017-11-28 11 58 07" src="https://user-images.githubusercontent.com/1888927/33313481-6c9f97ac-d433-11e7-8afc-c5fd9434c544.png">

**Comment by amitdo** [comment]
It's probably a bidi bug.

**Comment by arsenhakobyan** [comment]
Let me first ask a question then try to explain how/why I came to this question.

Can this issue be related to the trained data for Hebrew language ? 

Debugging the Tesseract sources to find a place where possible the correctly recognized digits are replaced by 0 didn't give result. Instead I found that in the alternates to the "Best Choice" which is returned by the tesseract there is no other choices for incorrectly recognized digits. For example the intermediate dumped alternate characters for the original image from this issue are:
Alternates for "ח"ש": {"ח"ש"}
Alternates for "0": {"0"}
Alternates for "יאמש": {"יאמש"}
Alternates for "פ"ע": {"פ"ע"}
Alternates for "קזנ": {"קזנ"}
Alternates for "ח"ש": {"ח"ש"}
Alternates for "0": {"0"}
Alternates for "יאמש": {"יאמש"}
Alternates for "ט"כש": {"ט"כש"}


Then I tried some experiments: 
I run tesseract with '-l heb' and '-l Hebrew'. (Assuming that '-l Hebrew' is version for which training data contains the english data as well). Also I used different modification of the input images, and some other input images as well.

Concerning the original image modification. I tried with only digits remaining in the image (
![modnumber](https://user-images.githubusercontent.com/10250134/34082293-b47352bc-e374-11e7-8c1d-204a428fd4a2.png))

The result for '-l Hebrew' is:
450.00
650.00

the result for '-l heb' is:
0
909000

Then I tried with added space between Hebrew characters and numbers (
![mod](https://user-images.githubusercontent.com/10250134/34082317-103e8a94-e375-11e7-92d3-fc72338ccb2b.png))

The result for '-l Hebrew' is:
נזק ע"פ שמאי 450.00 ש"ח
  
שכ"ט שמאי 650.00 ש"ח

the result for '-l heb' is:
נזק ע"פ שמאי 0 ש"ח
  
שכ"ט שמאי 9090000 ש"ח
-----------------------------------------------------

So expermients with other images containing different numbers in combination with Hebrew characters shows that '-l heb' outputs digits as expected and most of time it is correct.
That is why the last thing which is probably laid under the reported issue (IMHO) is the Hebrew train data used for '-l heb'.

Also if someone knows other places where it is useful to debug the recognized characters to see whether they have initially correct and only later replaced by '0' or some other incorrect character, Please let me know.

**Comment by amitm02** [comment]
turns out it was indeed a fine tune issue. we can close it.

**Comment by amitm02** [comment]
It turns out it was indeed a training issue. After training "heb" can get the number correctly.
Bug can be closed.

**Comment by amitdo** [comment]
>Bug can be closed.

You can close it yourself :-)

**Comment by amitm02** [comment]
silly me :)
