### ISSUE TITLE
DotProductSSE can't be used on Android this time on Fedora

### ISSUE THREAD

**Issue by pevogam** [tesseract-ocr/tesseract#1103]
Hi,

After manually compiling tesseract as follows

    $ ./autogen.sh 
    $ ./configure --prefix=/usr
    $ make; sudo make install; sudo ldconfig

and not encountering any errors along the way, when I finally run it I get

    DotProductSSE can't be used on Android
    Aborted (core dumped)

My platform is Fedora

    $ uname -a
    Linux drogon.whitetree 4.11.12-200.fc25.x86_64 #1 SMP Fri Jul 21 16:41:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

and my cpus seem to support the SSE flags

    $ cat /proc/cpuinfo
    processor	: 0
    vendor_id	: GenuineIntel
    ...
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave lahf_lm epb xsaveopt dtherm arat pln pts

while tesseract does not show any available dot products

    $ tesseract -v
    tesseract 4.00.00alpha
     leptonica-1.74.4
      libgif 4.1.6(?) : libjpeg 6b (libjpeg-turbo 1.5.1) : libpng 1.6.27 : libtiff 4.0.8 : zlib 1.2.8 : libwebp 0.5.2

Why doesn't tesseract error out with any clear message before this stage? During the configuration step, I can see "checking whether C++ compiler accepts -msse4.1... yes" and from the code (dotproductsse.cpp) I found

    #if !defined(__SSE4_1__)
    // This code can't compile with "-msse4.1", so use dummy stubs.

which is the source of the error message. Still it is not clear to me what goes wrong here.

**Comment by vidiecan** [comment]
The problem can be that you have compiled tesseract *without* sse support (missing appropriate defines/compiler switches), so your tesseract binary contains this definition
```
double DotProductSSE(const double* u, const double* v, int n) {
  fprintf(stderr, "DotProductSSE can't be used on Android\n");
  abort();
}
```
but you are running the binary on a system that supports SSE, https://github.com/tesseract-ocr/tesseract/blob/master/arch/simddetect.cpp
so tesseract tries to call DotProductSSE()
https://github.com/tesseract-ocr/tesseract/blob/4e9665debfb1043099d1ba054f90a8c8c1a69854/lstm/weightmatrix.cpp#L378

Ensure you compiled dotproductsse.cpp with the correct configuration e.g., on g++ try to look at the compilation command and/or check also 
```gcc -Q --help=target```
vs
```gcc -Q --help=target -march=native```

**Comment by pevogam** [comment]
Why isn't the sse support automatically detected like any other feature in during the configuration step? Shouldn't the default compilation in general be for the native architecture? Interestingly, the above checks do show a difference:

    $ gcc -Q --help=target
    The following options are target specific:
      -msse                       		[disabled]
      -msse2                      		[disabled]
      -msse2avx                   		[disabled]
      -msse3                      		[disabled]
      -msse4                      		[disabled]
      -msse4.1                    		[disabled]
      -msse4.2                    		[disabled]
      -msse4a                     		[disabled]
      -msse5                      		
      -msseregparm                		[disabled]
      -mssse3                     		[disabled]

with

    $ gcc -Q --help=target -march=native
    The following options are target specific:
      -msse                       		[enabled]
      -msse2                      		[enabled]
      -msse2avx                   		[disabled]
      -msse3                      		[enabled]
      -msse4                      		[enabled]
      -msse4.1                    		[enabled]
      -msse4.2                    		[enabled]
      -msse4a                     		[disabled]
      -msse5                      		
      -msseregparm                		[disabled]
      -mssse3                     		[enabled]

and passing the native architecture as an additional compiler flag solved the issue. It still puzzles me that this extra step is necessary though. The original (failing) compiler line for the file under question is

    /usr/bin/c++  -DHAVE_CONFIG_H -DTESS_EXPORTS -DUSE_STD_NAMESPACE=1 -DWINDLLNAME=\"libtesseract400.dll\" -D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS=1 -Dlibtesseract_EXPORTS -I/usr/include/leptonica -I/mnt/opencv-packs/tesseract-ocr/build -I/mnt/opencv-packs/tesseract-ocr/api -I/mnt/opencv-packs/tesseract-ocr/arch -I/mnt/opencv-packs/tesseract-ocr/ccmain -I/mnt/opencv-packs/tesseract-ocr/ccstruct -I/mnt/opencv-packs/tesseract-ocr/ccutil -I/mnt/opencv-packs/tesseract-ocr/classify -I/mnt/opencv-packs/tesseract-ocr/cutil -I/mnt/opencv-packs/tesseract-ocr/dict -I/mnt/opencv-packs/tesseract-ocr/lstm -I/mnt/opencv-packs/tesseract-ocr/opencl -I/mnt/opencv-packs/tesseract-ocr/textord -I/mnt/opencv-packs/tesseract-ocr/vs2010/port -I/mnt/opencv-packs/tesseract-ocr/viewer -I/mnt/opencv-packs/tesseract-ocr/wordrec  -march=native --std=c++11 -fPIC   -o CMakeFiles/libtesseract.dir/arch/dotproductsse.cpp.o -c /mnt/opencv-packs/tesseract-ocr/arch/dotproductsse.cpp

in case this may shed some light on the necessity of the extra flag.

**Comment by stweil** [comment]
If the compiler supports `-msse4.1` and it is called with that option, it is expected to set the macro `__SSE4_1__`. If it does not, you get the dummy function which was called in your case.

So the question is why does your compiler not set `__SSE4_1__`?

**Comment by pevogam** [comment]
I see. Here is some minimal info about the compiler in question perhaps for future reference:

    $ c++ -v
    Using built-in specs.
    COLLECT_GCC=c++
    COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/6.4.1/lto-wrapper
    Target: x86_64-redhat-linux
    Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --disable-libgcj --with-isl --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
    Thread model: posix
    gcc version 6.4.1 20170727 (Red Hat 6.4.1-1) (GCC) 

If anyone has any idea how to answer the question by @stweil I am ready to help. Otherwise I will close this issue with this information about the problematic compiler.

**Comment by amitdo** [comment]
You said you built it with autotools, but In your 'solution' you compiled it manually. without a build tool and you used object files which where built by CMake.

**Comment by pevogam** [comment]
I used autotools and encountered the above error. Then I tried again using CMake and still encountered the above error. Finally, it worked when I passed the "march=native" flag using CMake again (haven't tested passing the flag through autotools). I never manually compiled separate parts and the excerpts above are just a selection of the entire output.
