### ISSUE TITLE
recognizing on windows without new lines

### ISSUE THREAD

**Issue by gluehbire** [tesseract-ocr/tesseract#1105]
hi,

i try my first steps on tesseract. i have installed in on my macbook and a windows 7 32 bit machine via virtualbox. 

i want to recognize adresses from envelopes. so i made a picture (jpg and tif) and started the progress. on mac everything works fine - recognizing is very great and in the output file the adress is as expected. on windows the output file is in a single line.

e.g.

input:
name name
street number
code city

output mac is as input

output on windows:
name namestreet numbercode city

i tried all -psm modes with no effect i wanted.

**Comment by Shreeshrii** [comment]
How are you viewing the output?

Try notepad++ instead of notepad.

**Comment by gluehbire** [comment]
works. strange - but it works. thanks

**Comment by Shreeshrii** [comment]
It is related to the handling of `end of line` marks

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
