### ISSUE TITLE
Add ground truth for testing images

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1106]
https://github.com/tesseract-ocr/tesseract/tree/master/testing

has a number of images provided for testing.

Please add the corresponding groundtruth files also.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/pull/1088

adds groundtruth for phototest.tif and eurotext.tif.

**Comment by Shreeshrii** [comment]
@amitdo @jbreiden Please add groundtruth for the hebrew images, if available. Thanks!

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/tree/master/testing

hebtypo.jpg contains te'amim which Tesseract's heb.traineddata does not support.
https://github.com/tesseract-ocr/langdata/issues/82

**Comment by amitdo** [comment]
hebtypo.jpg seems to be taken from a copyrighted book.

**Comment by Shreeshrii** [comment]
@amitdo Ok. Thanks! 

Closing this.
