### ISSUE TITLE
Error: cppan command '0' not found

### ISSUE THREAD

**Issue by Bruevitz** [tesseract-ocr/tesseract#1107]
I tried compiling by following the instruction on https://github.com/tesseract-ocr/tesseract/wiki/Compiling.

When I run the command cmake ..
it gave me an error message: cppan command '0' not found, hence the solution (.sln) file was not created.

Please help.
------------------------

### Environment

* **Tesseract Version**: 4.00
* **Commit Number**: 
* **Platform**: Windows *8 64 bit

### Current Behavior:
Getting error message cppan command '0' not found.

![image](https://user-images.githubusercontent.com/31610445/30013790-be347f3c-9172-11e7-920a-047bdf5221fe.png)
Error log attached.
[CMAKE.zip](https://github.com/tesseract-ocr/tesseract/files/1273783/CMAKE.zip)

**Comment by egorpugin** [comment]
Hi,

Check if you're running the latest cppan client.
Remove your `tesseract/build` dir and re-create it again.
If this does not help, delete `c:\users\u\.cppan\storage\tmp` and re-run your commands.
If this does not help, remove the whole storage and try again.

**Comment by Bruevitz** [comment]
Hi,

It is solved. Apparently I forgot to set the PATH for CMAKE and GIT in the System Environment Variables.
I set the path and ran the command again.

Cheers.
