### ISSUE TITLE
Error: option 'subdir-objects' is disabled

### ISSUE THREAD

**Issue by fairsky66** [tesseract-ocr/tesseract#111]
while trying to autogen, i got the following errors.

<pre>
Makefile.am: error: required file './README' not found
api/Makefile.am:65: warning: source file '$(top_srcdir)/api/tesseractmain.cpp' is in a subdirectory,
api/Makefile.am:65: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
api/Makefile.am: installing 'config/depcomp'
ccutil/Makefile.am:53: warning: source file '../vs2008/port/strtok_r.cpp' is in a subdirectory,
ccutil/Makefile.am:53: but option 'subdir-objects' is disabled

  Something went wrong, bailing out!
</pre>

How can I make it?
Cheers,

**Comment by zdenop** [comment]
Please provide full information (full log, all commands you run, version of program autogen, tesseract code revision....)

**Comment by fairsky66** [comment]
i suspected that I had no tesseract.
Does the autogen have to use tesseract? If so, I will firstly install it.

**Comment by zdenop** [comment]
What are trying to do???

**Comment by fairsky66** [comment]
oh sorry about my heavy head due to a whole day of work :(

I did run autogen under directory of tesseract-ocr, but got the error message mentioned above.

FYI: 
i downloaded the source from google code (of version 3.02.02).
unpack it under mac os 10.10,
1: cd to tesserac-ocr
2: run autogen 
3: error for libtoolize, error for subdir-objects
4: change ibtoolize to glibtoolize
5: run autogen again
6: error for subdir-objects 

# here below the full log and version of glibtool, aclocal and automake:
* glibtool
<pre>
glibtool --version
glibtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
</pre>
* aclocal
<pre>
aclocal --version
aclocal (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
</pre>
* automake
<pre>
automake --version
automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
</pre>

## error ##
* autogen
<pre>
./autogen.sh 
Running aclocal
Running libtoolize
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
glibtoolize: copying file 'config/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
Running autoheader
Running automake --add-missing --copy
configure.ac:215: installing 'config/compile'
configure.ac:225: installing 'config/missing'
Makefile.am: error: required file './README' not found
api/Makefile.am:65: warning: source file '$(top_srcdir)/api/tesseractmain.cpp' is in a subdirectory,
api/Makefile.am:65: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
api/Makefile.am: installing 'config/depcomp'
ccutil/Makefile.am:53: warning: source file '../vs2008/port/strtok_r.cpp' is in a subdirectory,
ccutil/Makefile.am:53: but option 'subdir-objects' is disabled

  Something went wrong, bailing out!

</pre>

Hope these will help.

**Comment by zdenop** [comment]
First of all - why you use old version of tesseract (anyway it worked also on Mac OS)? Why you do not use version from github???

**Comment by fairsky66** [comment]
ok let me do it now/

**Comment by fairsky66** [comment]
new version from github worked now. 
thank you.
