### ISSUE TITLE
Compilation error - no std:: on string

### ISSUE THREAD

**Issue by nmcfarlane** [tesseract-ocr/tesseract#1110]
### Environment

* **Tesseract Version**: 
Tessearct 4.00
* **Commit Number**: 
Cloned from GitHub, 11:00am 6 Sept 2017
* **Platform**: 
Windows 10 64-bit

### Current Behavior:
Compling program linked to Tesseract fails.  Identifier "string" is undefined.  Problem is in ccutil/unichar.h, line 164:
  static string UTF32ToUTF8(const std::vector<char32>& str32);

### Suggested Fix:
Change string to std::string

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues?q=std+string+is:closed

**Comment by nmcfarlane** [comment]
Thank you.  I confirm that #define USE_STD_NAMESPACE solution solves the problem.
Regards
Nigel

**Comment by amitdo** [comment]
@nmcfarlane, please close this issue.
