### ISSUE TITLE
Can't run lstm training from tesseract 4.0

### ISSUE THREAD

**Issue by KevinZhuYF** [tesseract-ocr/tesseract#1115]
I'm trying to run this demo with tesseract 4.0 lstm training : 

mkdir -p ~/tesstutorial/engoutput
training/lstmtraining --debug_interval 100 \
  --traineddata ~/tesstutorial/engtrain/eng/eng.traineddata \
  --net_spec '[1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx96 Lrx96 Lfx256 O1c111]' \
  --model_output ~/tesstutorial/engoutput/base --learning_rate 20e-4 \
  --train_listfile ~/tesstutorial/engtrain/eng.training_files.txt \
  --eval_listfile ~/tesstutorial/engeval/eng.training_files.txt \
  --max_iterations 5000 &>~/tesstutorial/engoutput/basetrain.log

and system returns me a message as this:
Segmentation fault (core dumped)

When I checked the log file which is generated by this process, I got this:

mgr_.Init(traineddata_path.c_str()):Error:Assert failed:in file ../lstm/lstmtrainer.h, line 110

What should I do to make it work?

------------------------

### Environment

* **Tesseract Version**: <4.0>
* **Commit Number**: 
* **Platform**: <Ubuntu 16.04>

**Comment by Shreeshrii** [comment]
Ray is currently updating the repo with new code. You can try a commit from about a week back and check.

**Comment by Shreeshrii** [comment]
>The following example shows the command line for training from scratch. Try it with the default training data created with the command-lines above.

Did you create the required traineddata by 

training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only \
  --noextract_font_properties --langdata_dir ../langdata \
  --tessdata_dir ./tessdata --output_dir ~/tesstutorial/engtrain

**Comment by amitdo** [comment]
>... --traineddata ~/tesstutorial/engtrain/eng/eng.traineddata ...

>mgr_.Init(traineddata_path.c_str()):Error:Assert failed:in file ../lstm/lstmtrainer.h, line 110

Try this:
`mkdir -p  ~/tesstutorial/engtrain/eng/`

**Comment by amitdo** [comment]
@KevinZhuYF, please respond to @Shreeshrii's question.

**Comment by Shreeshrii** [comment]
>mgr_.Init(traineddata_path.c_str()):Error:Assert failed:in file ../lstm/lstmtrainer.h, line 110

This error is caused by a missing traineddata  file given in the training command. I think there is another similar issue.

It will be nice to have a more user-friendly message.

This issue can be closed and a link added to the other one ( more details in it)
