### ISSUE TITLE
Cannot build from source after PR #1116

### ISSUE THREAD

**Issue by nimroha** [tesseract-ocr/tesseract#1119]
### Environment

* **Tesseract Version**: 4.00 (cloned now from master)
* **Leptonica Version**: 1.7.8
* **Commit Number**: 7569c899f732829a56da1ed797dc3fc90093406f
* **Platform**: Linux vagrant-ubuntu-trusty-64 3.13.0-125-generic #174-Ubuntu SMP Mon Jul 10 18:51:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
Cannot build from source from branch master

### Expected Behavior:
Should be able to build

### Steps to reconstruct:
**Run:**
git clone --depth 1 https://github.com/tesseract-ocr/tesseract.git
cd /tesseract
./autogen.sh
./configure --enable-debug
LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include"
make
make install
make training

**Output:**
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11  -L/usr/local/lib -llept    -o unicharset_extractor unicharset_extractor.o libtesseract_tessopt.la  ../api/libtesseract.la  -lpthread 
libtool: link: g++ -g -O2 -std=c++11 -o .libs/unicharset_extractor unicharset_extractor.o  -L/usr/local/lib /usr/local/lib/liblept.so ./.libs/libtesseract_tessopt.a ../api/.libs/libtesseract.so -lpthread -fopenmp
unicharset_extractor.o: In function `tesseract::Main(int, char**)':
/tesseract/training/unicharset_extractor.cpp:66: undefined reference to `tesseract::ReadFile(std::string const&, bool (*)(STRING const&, GenericVector<char>*))'
unicharset_extractor.o: In function `AddStringsToUnicharset':
/tesseract/training/unicharset_extractor.cpp:48: undefined reference to `tesseract::NormalizeCleanAndSegmentUTF8(tesseract::UnicodeNormMode, tesseract::OCRNorm, tesseract::GraphemeNormMode, bool, char const*, std::vector<std::string, std::allocator<std::string> >*)'
/tesseract/training/unicharset_extractor.cpp:53: undefined reference to `tesseract::IsWhitespace(int)'
unicharset_extractor.o: In function `tesseract::Main(int, char**)':
/tesseract/training/unicharset_extractor.cpp:81: undefined reference to `tesseract::SetupBasicProperties(bool, bool, UNICHARSET*)'
unicharset_extractor.o: In function `main':
/tesseract/training/unicharset_extractor.cpp:96: undefined reference to `tesseract::ParseCommandLineFlags(char const*, int*, char***, bool)'
collect2: error: ld returned 1 exit status
make[1]: *** [unicharset_extractor] Error 1
make[1]: Leaving directory `/tesseract/training'
make: *** [training] Error 2

### Suggested Fix:
The rule to make `unichar_extractor` was changed in the last pull request closed (#1116)

**Comment by Shreeshrii** [comment]
I have made a PR to fix it. https://github.com/tesseract-ocr/tesseract/pull/1118

**Comment by nimroha** [comment]
Fixed in PR #1118
