### ISSUE TITLE
tesseract just can't  recognize the down part of a ticket

### ISSUE THREAD

**Issue by ivanzz1001** [tesseract-ocr/tesseract#1122]
### Environment

* **Tesseract Version**:  tesseract 4.00.00alpha (the latest)
* **Commit Number**:  don't know 
* **Platform**: Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux (CentOS 7.3.1611)

### Current Behavior:
I have a ticket image:
![ticket](https://user-images.githubusercontent.com/29993902/30318159-e18e242a-97de-11e7-8fd5-548f99ca9092.png)

then I use the following command:
<pre>
[root@localhost workspace]# /opt/tesseract4.0/bin/tesseract ticket.png out -l chi_sim
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 182
[root@localhost workspace]# cat out.txt 
  
    

本 付 束 方 证 件 号 :
履 吉方 名 称 。， 硕 逢 区 大 良 大 条 和 饮食 店
司 收 吉方 证 件 号 ，440623197507202615
</pre>
But some strange things happened:  It seems that ```tesseract``` can only recognize the top half of the ticket，the down half just can't recognize。 Then I split the ticket into two images: ```ticket_top.png``` and ```ticket_down.png```，and ```tesseract``` still don't recognize the original down half(now that's ticket_down.png). 

the following image is ```ticket_down.png```:
![ticket_down](https://user-images.githubusercontent.com/29993902/30318744-8ace537e-97e0-11e7-994e-cfe516e2100c.png)

### Expected Behavior:

the top half and the down half of the ticket has the same image-features, It should almost have the same behavior.

**Comment by Shreeshrii** [comment]
try with other page segmentation modes.

with --psm 6, I get the following output

```
本 付 束 方 证 件 号 : 本 | |

和 “ 适 兴 台 号 |
司 收 吉方 证 件 号 ，440623197507202615 由 机

se 二 EC 二 日
二 谭 潮 3813.00 过

ee 引 记 大 条 可
三 合计 金 砚 大 写 ) : 佐 什 抽 佰 查 拼 元 束 全 色 - 出 后 吕 雪 二 |

全 ET 这
三 汪 村 人 , 各 衣 乐 人

GO 从 人 e
```

**Comment by ivanzz1001** [comment]
It seems that works, thank you

**Comment by amitdo** [comment]
>It seems that works, thank you

Why did you re-opened it?
