### ISSUE TITLE
GetWords can not get right BoundingBox().x and BoundingBox().y

### ISSUE THREAD

**Issue by fjutxd** [tesseract-ocr/tesseract#1124]
for example
char[x,y,height,widthg]getConfidence()
有[193.0,438.0,29.0,28.0]99.415886
没[223.0,437.0,28.0,51.0]98.77193
有[900.0,0.0,0.0,0.0]99.5725
让[290.0,437.0,28.0,46.0]99.56392
the third “有” between "没" and "让",but BoundingBox().x is 900, BoundingBox().y is 0; use LSTM by Tess4j 4.0

**Comment by Shreeshrii** [comment]
Similar Issue - https://github.com/tesseract-ocr/tesseract/issues/1015

**Comment by amitdo** [comment]
@zdenop, as Shree noted, this issue is same as #1015, so please close this one.
