### ISSUE TITLE
Can't use latest tesseract from command line

### ISSUE THREAD

**Issue by mm-manu** [tesseract-ocr/tesseract#1130]
Hello,
I compiled and installed the latest Leptonica and Tesseract without problems.

`tesseract -v 
`

> tesseract 4.00.00alpha
 leptonica-1.74.4
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8
 Found AVX2
 Found AVX
 Found SSE

`tesseract image.jpg --tessdata_dir /usr/local/share/tessdata -l eng`

> tesseract: genericvector.h:713: T& GenericVector<T>::operator[](int) const [with T = char]: Assertion `index >= 0 && index < size_used_' failed.

When I use the tesserocr python wrapper, it seems to work.
Any suggestions?

**Comment by amitdo** [comment]
>tesseract image.jpg --tessdata_dir /usr/local/share/tessdata -l eng

try this:

>tesseract image.jpg **out** --tessdata_dir /usr/local/share/tessdata -l eng

**Comment by Shreeshrii** [comment]
tesseract imagename|stdin outputbase|stdout [options...] [configfile...]

OCR options:
  --tessdata-dir PATH   Specify the location of tessdata path.
  --user-words PATH     Specify the location of user words file.
  --user-patterns PATH  Specify the location of user patterns file.
  -l LANG[+LANG]        Specify language(s) used for OCR.
  -c VAR=VALUE          Set value for config variables.
                        Multiple -c arguments are allowed.
  --psm NUM             Specify page segmentation mode.
  --oem NUM             Specify OCR Engine mode.
NOTE: These options must occur before any configfile.

---------

--tessdata-dir is  with hyphen, not underscore

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by mm-manu** [comment]
`tesseract image.jpg out --tessdata_dir /usr/local/share/tessdata -l eng`
> tesseract: genericvector.h:713: T& GenericVector<T>::operator[](int) const [with T = char]: Assertion `index >= 0 && index < size_used_' failed.

`tesseract image.jpg out.txt --tessdata_dir /usr/local/share/tessdata -l eng`
> tesseract: genericvector.h:713: T& GenericVector<T>::operator[](int) const [with T = char]: Assertion `index >= 0 && index < size_used_' failed.

`tesseract image.jpg stdout --tessdata_dir /usr/local/share/tessdata -l eng`
> tesseract: genericvector.h:713: T& GenericVector<T>::operator[](int) const [with T = char]: Assertion `index >= 0 && index < size_used_' failed.

Would you recommend to reinstall?
