### ISSUE TITLE
can't load osd.traineddata

### ISSUE THREAD

**Issue by SourcesMl** [tesseract-ocr/tesseract#1133]
------------------------

### Environment

* **Tesseract Version**: Tesseract 4.00.00 alpha
* **Commit Number**:  188e1fc
* **Platform**: Ubuntu 16.04.02 LTS

### Current Behavior:
I've downloaded and compiled latest tesseract source file from git repository but when i run tesseract engine with mode --oem 1, --psm 0 or 1 it can't load osd.traineddata. My osd.traineddata file is downloaded from tessdata_best. I tried with older osd.traineddata file from tessdata directory it works fine. I've cloned tessdata_best from repo and checked any download error but it was okay. 
installed tesseract shown below.
![tesseract](https://user-images.githubusercontent.com/30248220/30473888-72f05e40-9a34-11e7-9518-de668fd6c024.png)

I can load and work well with osd.traineddata from tessdata which is created about 3 yrs ago and include following files 
![old](https://user-images.githubusercontent.com/30248220/30474105-1effef34-9a35-11e7-9118-d89403fca397.png)
 
the one tesseract fails at loading includes lstm files which is shown below.
![new](https://user-images.githubusercontent.com/30248220/30474201-74a6bbfc-9a35-11e7-82b5-09e97706263d.png)

![osdfailed](https://user-images.githubusercontent.com/30248220/30474253-98bbc1cc-9a35-11e7-8b04-29b2477bd070.png)
here i am using lstm mode of engine so it should load osd.traineddata successfully but it shows failure message. It can load other language's lstm traineddata files and i can get result of text recognition despite of giving 'failed loading language osd' message but i can't feel any difference using best osd so it is not loading best osd.traineddata at all. 

So i guess it is bug related to tesseract engine or osd.traineddata file which is in tessdata_best.

**Comment by jbreiden** [comment]
Thanks for the report. You are right, Orientation Script Detection (OSD) only works with the legacy recognizer. Discussing with Ray. The answer might be to delete osd.traineddata from tessdata_best and tessdata_fast repositories.

**Comment by jbreiden** [comment]
Does this copy of osd.traineddata have the same problem, or not?

https://github.com/tesseract-ocr/tessdata/blob/3a94ddd47be01fd897cbe31f05cbd2301454cf8a/best/osd.traineddata

**Comment by Shreeshrii** [comment]
/mnt/c/Users/User/shree# combine_tessdata -u osd.traineddata osd.
Extracting tessdata components from osd.traineddata
Wrote osd.lstm
Wrote osd.lstm-unicharset
Wrote osd.lstm-recoder
Wrote osd.version
Version string:4.00.00alpha:osd:synth20170629:[1,48,0,1Ct3,3,16Mp3,3Lfys64Lfx96Lrx96Lfx384O1c1]
17:lstm:size=7409547, offset=192
21:lstm-unicharset:size=7991, offset=7409739
22:lstm-recoder:size=715, offset=7417730
23:version:size=80, offset=7418445

https://github.com/tesseract-ocr/tessdata/blob/3a94ddd47be01fd897cbe31f05cbd2301454cf8a/best/osd.traineddata

only has the lstm components.

**Comment by jbreiden** [comment]
As per discussion with Ray, I have taken osd.traineddata from tessdata and copied it to both tessdata_fast and tessdata_best. This should resolve the problem and is the best we can do today.  Some day in the future, hopefully, there will be an Orientation Script Dectector (OSD) that works with the LSTM recognizer.

**Comment by sadiqkhoja** [comment]
facing same issue for urd.tessdata from tessdata_best
