### ISSUE TITLE
RFC: Move data for tests into a new repository

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#1137]
Recently the first regression tests were added to the Tesseract sources, and hopefully more will be added in the future. I expect that many of those tests will require images, maybe also related text and other files. Typically the images are large (much larger than source code files),  and most image formats are already compressed, so Git cannot compress them further. This is bad for the git repository size, but also for the size of the working directory or of release tarballs.

Currently 8 of the 10 largest files are test related:

    1444515 ccutil/universalambigs.cpp
     708120 testing/DuTillet1004Pg2LG.jpg
     444141 testing/hebtypo.jpg
     401757 testdata/chi_tra.unicharset
     399613 testing/hebrew-nikud-genesis-1-2.png
     378914 testdata/kan.unicharset
     359497 ccutil/tesscallback.h
     327214 testdata/chi_sim.unicharset
     239201 testdata/jpn.unicharset
     221628 testdata/mar.unicharset

We should avoid adding more such files. I suggest to create a new repository called `tesstest`,  `testdata`, `tesseract_testdata` or any other name for all test related data and move the existing test data to that repository. The `tesseract` repository can then include that new repository as a git submodule which is only needed when running tests (so most people won't need it).

OpenJPEG is an example of another Open Source project with a similar split of [source code](https://github.com/uclouvain/openjpeg) and [test data](https://github.com/uclouvain/openjpeg-data). They do not use a git submodule, but have a configure option to choose the location of the test data.

**Comment by Shreeshrii** [comment]
Good idea.

Google's tests probably use testdata as the directory, so the submodule can be pulled in under that name.

**Comment by jbreiden** [comment]
I can very easily image 175MB of test data.

**Comment by stweil** [comment]
... or more. Test images use a lot of disk space.

**Comment by zdenop** [comment]
https://github.com/tesseract-ocr/test
