### ISSUE TITLE
Any idea about 'allow_blob_division' ?

### ISSUE THREAD

**Issue by jacky9527** [tesseract-ocr/tesseract#114]
I have downloaded the sources and written the samples codes, just change the language 'eng' to 'chi_sim'. The traindata 'chi_sim' has been copied to \tessdata directory same with eng.traindata.

When I complie and start the sample, a error 'read_params_file: parameter not found: allow_blob_division' happens. But it works well with language 'eng'. Does anyone know how to resove it ?

Thanks a lot.

**Comment by zdenop** [comment]
Please use tesseract forum for asking support. Do not forget provide detail (version of tesseract, OS...)
