### ISSUE TITLE
building master fails:  libtool: error: '/usr/lib/x86_64-linux-gnu/libtiff.la' is not a valid libtool archive

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#1142]
```
In file included from ambigs.h:26:0,
                 from ambigs.cpp:21:
unichar.h:164:10: error: 'string' does not name a type
   static string UTF32ToUTF8(const std::vector<char32>& str32);
          ^~~~~~
In file included from ambigs.h:27:0,
                 from ambigs.cpp:21:
unicharset.h:241:10: error: 'string' does not name a type
   static string CleanupString(const char* utf8_str) {
          ^~~~~~
unicharset.h:244:10: error: 'string' does not name a type
   static string CleanupString(const char* utf8_str, int length);
          ^~~~~~
unicharset.h: In member function 'void UNICHARSET::unichar_insert_backwards_compatible(const char*)':
unicharset.h:265:5: error: 'string' was not declared in this scope
     string cleaned = CleanupString(unichar_repr);
     ^~~~~~
unicharset.h:265:5: note: suggested alternatives:
In file included from /usr/include/c++/6/string:39:0,
                 from /usr/include/c++/6/stdexcept:39,
                 from /usr/include/c++/6/array:39,
                 from /usr/include/c++/6/tuple:39,
                 from /usr/include/c++/6/functional:55,
                 from helpers.h:30,
                 from genericvector.h:29,
                 from params.h:25,
                 from tprintf.h:23,
                 from ambigs.h:25,
                 from ambigs.cpp:21:
/usr/include/c++/6/bits/stringfwd.h:74:33: note:   'std::__cxx11::string'
   typedef basic_string<char>    string;
                                 ^~~~~~
/usr/include/c++/6/bits/stringfwd.h:74:33: note:   'std::__cxx11::string'
In file included from ambigs.h:27:0,
                 from ambigs.cpp:21:
unicharset.h:266:9: error: 'cleaned' was not declared in this scope
     if (cleaned != unichar_repr) {
         ^~~~~~~
Makefile:584: die Regel für Ziel „ambigs.lo“ scheiterte
make[3]: *** [ambigs.lo] Fehler 1
make[3]: Verzeichnis „/work/usr/local/src/tesseract/ccutil“ wird verlassen
Makefile:626: die Regel für Ziel „all-recursive“ scheiterte
make[2]: *** [all-recursive] Fehler 1
make[2]: Verzeichnis „/work/usr/local/src/tesseract/ccutil“ wird verlassen
Makefile:481: die Regel für Ziel „all-recursive“ scheiterte
make[1]: *** [all-recursive] Fehler 1
make[1]: Verzeichnis „/work/usr/local/src/tesseract“ wird verlassen
Makefile:389: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by stweil** [comment]
You did not copy the command which was used to run the compiler from your build protocol. It should look like this:

    depbase=`echo ambigs.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
    /bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -DUSE_STD_NAMESPACE   -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -DTESSDATA_PREFIX=/usr/local/share/  -g -O2 -std=c++11 -MT ambigs.lo -MD -MP -MF $depbase.Tpo -c -o ambigs.lo ambigs.cpp &&\
    mv -f $depbase.Tpo $depbase.Plo
    libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -DUSE_STD_NAMESPACE -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -DTESSDATA_PREFIX=/usr/local/share/ -g -O2 -std=c++11 -MT ambigs.lo -MD -MP -MF .deps/ambigs.Tpo -c ambigs.cpp  -fPIC -DPIC -o .libs/ambigs.o
    libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -DUSE_STD_NAMESPACE -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -DTESSDATA_PREFIX=/usr/local/share/ -g -O2 -std=c++11 -MT ambigs.lo -MD -MP -MF .deps/ambigs.Tpo -c ambigs.cpp -o ambigs.o >/dev/null 2>&1

Check whether yours looks different, especially whether `-DUSE_STD_NAMESPACE` is missing. That would explain the build failure.

**Comment by Wikinaut** [comment]
I started from scratch ( .-/autogen.sh ; ./configure --enable-debug; make)  Seems to work.

**Comment by Wikinaut** [comment]
@stweil I apologize for my bug reports. But tesseract is a kind of PITA. When you want to build it after a while of not following the changes, building fails.

**Comment by Wikinaut** [comment]
libtool:   error: '/usr/lib/x86_64-linux-gnu/libtiff.la' is not a valid libtool archive

**Comment by Wikinaut** [comment]
Debian 9: make --> libtool:   error: '/usr/lib/x86_64-linux-gnu/libtiff.la' is not a valid libtool archive

**Comment by Wikinaut** [comment]
@stweil Stefan: please assist. Now we have a 'make' issue on debian9.

**Comment by stweil** [comment]
I also use Debian 9, same libtiff5-dev, and I do not have `/usr/share/tesseract-ocr/4/tessdata/`. I'd examine it with `ls -l` (is it old) and `dpkg -S` (where does it belong to) and move it out of the way.

**Comment by amitdo** [comment]
@Wikinaut, did you solve the issue?
