### ISSUE TITLE
tesseract 2cc531e6 does not work together with https://github.com/tesseract-ocr/tessdata_best

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#1143]
Please explain, why the current master does apparently not work together with https://github.com/tesseract-ocr/tessdata_best

I got this: 
```
Failed loading language 'deu'
Tesseract couldn't load any languages!
Could not initialize tesseract.
ObjectCache(0x7f0a269c9800)::~ObjectCache(): WARNING! LEAK! object 0x1a51780 still has count 1 (id /usr/local/share/tessdata/deu.traineddatalstm-punc-dawg)
ObjectCache(0x7f0a269c9800)::~ObjectCache(): WARNING! LEAK! object 0x28c1b40 still has count 1 (id /usr/local/share/tessdata/deu.traineddatalstm-word-dawg)
ObjectCache(0x7f0a269c9800)::~ObjectCache(): WARNING! LEAK! object 0x28c2470 still has count 1 (id /usr/local/share/tessdata/deu.traineddatalstm-number-dawg)
```

**Comment by Wikinaut** [comment]
It does work with the old tessdata.

**Comment by amitdo** [comment]
You have two options:
1. Put the deu.trainwddata directly ubder your tessdata dir.
2. Put tessdata_best dir under your tessdata dir, and use -l tessdata_best/deu

**Comment by amitdo** [comment]
>Put the tessdata_best dir under your tessdata dir, and use -l tessdata_best/deu

or rename the tessdata_best dir, for example to 'best',  and put it under your tessdata dir, and use -l best/deu

**Comment by Wikinaut** [comment]
@amitdo I simply replaced (exchanged) my existing .../tessdata with the the new .../tessdata_best. Tesseract does not work then.

What is changed, so that this fails?

**Comment by amitdo** [comment]
Tesseract has this parameter:
 
'm_data_sub_dir' - "Directory for data files"

It's not new.

The default value for that parameter is 'tessdata/'.

I simply replaced (exchanged) my existing .../tessdata with the the new .../tessdata_best. Tesseract 

In that case another option is to put this line in a text file
>m_data_sub_dir tessdata_best

and use it as config file to tesseract.

**Comment by Wikinaut** [comment]
@amitdo Thanks, I do know the tessdata configuration possibilities. In my case the reason was, that I checked out tessdata_best from github, but forgot to copy /tessdata files and subdirectories from the tesseract code directory. I simply forgot this.

Perhaps this can be improved: separation (split) of /tessdata(config-files) and /tessdata(language) files. Do you understand, what I mean?

I opened this issue and close it now.

**Comment by AlexGfocus** [comment]
I try tessdata_best by setting OCR Engine mode to OEM_LSTM_ONLY, add option --oem 1 to tesseract, it works ! Maybe new tessdata no longer supports old Tesseract recognizer.

**Comment by Wikinaut** [comment]
I used ```oem=2``` !!!

**Comment by Wikinaut** [comment]
Now finally, with ```oem=1``` it works.

**Comment by Shreeshrii** [comment]
AFAIK, tessdata_best and tessdata_fast have only LSTM models in them, so
--oem 1 (LSTM) and --oem 3 (default) should work, as long as the config
file is not using --oem 0 or --oem 2.

If you want the legacy models, use tessdata.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
