### ISSUE TITLE
Get invalid box information for some characters when using hocr options

### ISSUE THREAD

**Issue by shawnchen8255** [tesseract-ocr/tesseract#1146]
### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**: 
* **Platform**: Ubuntu 17.04

### Current Behavior:

When using HOCR in command line some characters will be recognized with the same box information as (0,0,width,height) of the total image  which is invalid. 
The position information is invalid for these characters

**Comment by vspol** [comment]
Same problem.
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica / windows 10

Used command line:
"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe" "C:\...\doc.tif" "C:\...\hocr" -l rus+eng -psm 1 hocr

Part of hocr-document:

`<span class='ocr_line' id='line_1_78' title="bbox 509 1652 2713 1682; baseline 0 -5; x_size 27.964552; x_descenders 5.5; x_ascenders 5.8769231"><span class='ocrx_word' id='word_1_397' title='bbox 0 0 3610 2628; x_wconf 69'><strong>Переходник</strong></span> <span class='ocrx_word' id='word_1_398' title='bbox 0 0 3610 2628; x_wconf 71'><strong>РМС</strong></span> <span class='ocrx_word' id='word_1_399' title='bbox 509 1652 1086 1682; x_wconf 96'><strong>симметричный</strong></span> <span class='ocrx_word' id='word_1_400' title='bbox 0 0 3610 2628; x_wconf 95' lang='eng'><strong>400/200</strong> ...`

word_1_397, word_1_398, word_1_400 - have **size of page** - bbox 0 0 3610 2628
word_1_399 - have size and coordinates of **five words** - bbox 509 1652 1086 1682

**graphical view**

Text line box have correct coordinates:
![image](https://user-images.githubusercontent.com/30173713/31377645-79d38efe-adb1-11e7-89eb-d067d2c0ce82.png)

but coordinates of some words are not correct:

![image](https://user-images.githubusercontent.com/30173713/31377695-9b3d3856-adb1-11e7-993c-0ddb11c8a12c.png)

![image](https://user-images.githubusercontent.com/30173713/31377752-c27bed54-adb1-11e7-9b68-b82ad94394e1.png)

**Comment by napasa** [comment]
Same Problem.

**Comment by devendrasr** [comment]
I am running into the same problem. How can we overcome this?

**Comment by willaaam** [comment]
Crosspost - but this issue is still very much relevant.

https://github.com/tesseract-ocr/tesseract/issues/1192#issuecomment-418182462

**Comment by zdenop** [comment]
can you please provide image for testing issue? + Test the current code.

**Comment by amitdo** [comment]
Same issue as #1192
