### ISSUE TITLE
text2image can't produce a complete tif file

### ISSUE THREAD

**Issue by ivanzz1001** [tesseract-ocr/tesseract#1149]
### Environment

* **Tesseract Version**: Tesseract4.0.0
* **Commit Number**: 2cc531e
* **Platform**: Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux (Centos7.3)

### Current Behavior:
I use the following command to produce the tif files:
<pre>
# /opt/tesseract4.0/bin/text2image --find_fonts \
--fonts_dir /usr/share/fonts \
--text ./langdata/chi_sim/chi_sim.training_text \
--min_coverage .9  \
--outputbase ./results/chi_sim/chi_sim\
|& grep raw | sed -e 's/ :.*/" \\/g'  | sed -e 's/^/  "/' >./results/chi_sim/fontslist.txt

# ls ./results/chi_sim/
chi_sim.Arial_Unicode_MS.tif               chi_sim.FangSong.tif                 chi_sim.Noto_Sans_SC.tif  chi_sim.STZhongsong.tif
chi_sim.AR_PL_UKai_CN.tif                  chi_sim.KaiTi.tif                    chi_sim.NSimSun.tif       chi_sim.WenQuanYi_Micro_Hei_Mono.tif
chi_sim.AR_PL_UKai_HK.tif                  chi_sim.LiSu.tif                     chi_sim.SimHei.tif        chi_sim.WenQuanYi_Micro_Hei.tif
chi_sim.AR_PL_UKai_TW_MBE.tif              chi_sim.Microsoft_YaHei_Bold.tif     chi_sim.SimSun.tif        chi_sim.WenQuanYi_Zen_Hei_Medium.tif
chi_sim.AR_PL_UKai_TW.tif                  chi_sim.Microsoft_YaHei.tif          chi_sim.STFangsong.tif    chi_sim.WenQuanYi_Zen_Hei_Mono_Medium.tif
chi_sim.AR_PL_UMing_CN_Semi-Light.tif      chi_sim.Noto_Sans_SC_Bold.tif        chi_sim.STKaiti.tif       chi_sim.WenQuanYi_Zen_Hei_Sharp_Medium.tif
chi_sim.AR_PL_UMing_HK_Semi-Light.tif      chi_sim.Noto_Sans_SC_Heavy.tif       chi_sim.STSong.tif        chi_sim.YouYuan.tif
chi_sim.AR_PL_UMing_TW_MBE_Semi-Light.tif  chi_sim.Noto_Sans_SC_Medium.tif      chi_sim.STXihei.tif       fontslist.txt
chi_sim.AR_PL_UMing_TW_Semi-Light.tif      chi_sim.Noto_Sans_SC_Semi-Light.tif  chi_sim.STXinwei.tif
</pre>

Then I used the "Windows photo viewer" to open the tif files， and I found that the tif file  contains only part of the chi_sim.training_text's content(langdata/chi_sim). that's why? 

then I append  "--ysize 9600" option to /opt/tesseract4.0/bin/text2image, the generated tif file can contains more. 

Now do I have to set "--ysize" to a very very large number to fix this problem? Is it the right way?

**Comment by Shreeshrii** [comment]
These are multipage tif files. Have you looked at the next page in it.

**Comment by ivanzz1001** [comment]
I checked that they are singlepage tif files, how to generate a multipage tif file? where is it going wrong?

**Comment by Shreeshrii** [comment]
use the following command to produce the tif files:

# /opt/tesseract4.0/bin/text2image --find_fonts \
--fonts_dir /usr/share/fonts \
--text ./langdata/chi_sim/chi_sim.training_text \
--min_coverage .9  \
--outputbase ./results/chi_sim/chi_sim\
|& grep raw | sed -e 's/ :.*/" \\/g'  | sed -e 's/^/  "/' >./results/chi_sim/fontslist.txt


The above command does not produce tif files for training. It is used for generating a list of fonts and a sample page for each font.

Please use tesstrain.sh command as described in training page on wiki.

**Comment by ivanzz1001** [comment]
OK, I use tesstrain.sh, it has the same problem, although this time it generates multipage tif files, they also contains only part of the chi_sim.training_text's content

**Comment by ivanzz1001** [comment]
@Shreeshrii I think I have found the reason. In the tesseract_master/training/tesstrain_utils.sh, there's the following function:
<pre>
# Helper function for phaseI_generate_image. Generates the image for a single
# language/font combination in a way that can be run in parallel.
generate_font_image() {
    local font="$1"
    tlog "Rendering using ${font}"
    local fontname=$(echo ${font} | tr ' ' '_' | sed 's/,//g')
    local outbase=${TRAINING_DIR}/${LANG_CODE}.${fontname}.exp${EXPOSURE}

    local common_args="--fontconfig_tmpdir=${FONT_CONFIG_CACHE}"
    common_args+=" --fonts_dir=${FONTS_DIR} --strip_unrenderable_words"
    common_args+=" --leading=${LEADING}"
    common_args+=" --char_spacing=${CHAR_SPACING} --exposure=${EXPOSURE}"
    common_args+=" --outputbase=${outbase} --max_pages=3"

    # add --writing_mode=vertical-upright to common_args if the font is
    # specified to be rendered vertically.
    for vfont in "${VERTICAL_FONTS[@]}"; do
      if [[ "${font}" == "${vfont}" ]]; then
        common_args+=" --writing_mode=vertical-upright "
        break
      fi
    done

    run_command text2image ${common_args} --font="${font}" \
        --text=${TRAINING_TEXT} ${TEXT2IMAGE_EXTRA_ARGS}
    check_file_readable ${outbase}.box ${outbase}.tif

    if ((EXTRACT_FONT_PROPERTIES)) &&
        [[ -r ${TRAIN_NGRAMS_FILE} ]]; then
        tlog "Extracting font properties of ${font}"
        run_command text2image ${common_args} --font="${font}" \
            --ligatures=false --text=${TRAIN_NGRAMS_FILE} \
            --only_extract_font_properties --ptsize=32
        check_file_readable ${outbase}.fontinfo
    fi
}
</pre>
It sets "--max_pages=3", then I modified it to "--max_pages=0", and then it generates the tif files which contain all the words in chi_sim.training_text。

Is it a bug in  tesseract_master/training/tesstrain_utils.sh? Should I report it as a bug?

**Comment by Shreeshrii** [comment]
This is a recent change to training. I guess, it is to limit the size of tif/box and hence lstmf files for finetune/plusminus training.

I did pose a question to @theraysmith regarding this, but no answer yet.

**Comment by ivanzz1001** [comment]
@Shreeshrii  Have you get answer from @theraysmith ?

**Comment by Shreeshrii** [comment]
@theraysmith hasn't answered yet, I had asked in one of these issue posts only.

I am not sure whether that change (adding maxpages) is intentional or accidental. 

Many languages need a higher limit to handle the training_text in current langdata repo (which has also NOT been updated for 4.0x).

So, unless the new langdata will have very short training_text which will be less than 3 pages, thi limit should be removed/changed.

@amitdo Do you have any insight regarding this?

**Comment by amitdo** [comment]
Maybe 'max_pages' should be a parameter to the shell script, so end users can change it easily.

**Comment by ivanzz1001** [comment]
yes,I think so

**Comment by ivanzz1001** [comment]
@Shreeshrii now have you get answer from @theraysmith ?

**Comment by Shreeshrii** [comment]
No. @theraysmith might reply when he does next set of updates. I hope ...

**Comment by kamrapooja** [comment]
In my system, in tesstrain_utils.sh MAX_PAGES is set to zero. Still it is not taking all images, Logs are as below:

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=/home/administrator/Downloads/tesseract-4.0.0/tessdata
[Thu Jun 13 15:31:46 IST 2019] /usr/bin/tesseract /tmp/eng-2019-06-13.oM2/eng.FreeMono.exp0.tif /tmp/eng-2019-06-13.oM2/eng.FreeMono.exp0 --psm 6 lstm.train
Tesseract Open Source OCR Engine v4.1.0-rc1-125-gac7e with Leptonica
Page 1
Page 2
Loaded 56/56 pages (1-56) of document /tmp/eng-2019-06-13.oM2/eng.FreeMono.exp0.lstmf

=== Constructing LSTM training data ===
[Thu Jun 13 15:31:47 IST 2019] /usr/bin/combine_lang_model --input_unicharset /tmp/eng-2019-06-13.oM2/eng.unicharset --script_dir /home/administrator/Downloads/tesseract-4.0.0/langdata --words /home/administrator/Downloads/tesseract-4.0.0/langdata/eng/eng.wordlist --numbers /home/administrator/Downloads/tesseract-4.0.0/langdata/eng/eng.numbers --puncs /home/administrator/Downloads/tesseract-4.0.0/langdata/eng/eng.punc --output_dir /home/administrator/pooja/train_test_lstmf/ --lang eng
Loaded unicharset of size 111 from file /tmp/eng-2019-06-13.oM2/eng.unicharset
Setting unichar properties
Other case É of é is not in unicharset
Setting script properties
Config file is optional, continuing...
Failed to read data from: /home/administrator/Downloads/tesseract-4.0.0/langdata/eng/eng.config
Null char=2
Reducing Trie to SquishedDawg
Reducing Trie to SquishedDawg
Reducing Trie to SquishedDawg

Please help.

**Comment by Shreeshrii** [comment]
Please try with latest code from masterbranch.
