### ISSUE TITLE
Add option to suppress banner

### ISSUE THREAD

**Issue by wasamasa** [tesseract-ocr/tesseract#115]
I'm spawning `tesseract` subprocesses for a project I'm working on and it's a bit annoying to see its banner on every invocation in the error log.  Redirecting stderr to `/dev/null` isn't an option as that would hide actual errors.

While the sources tell me redirecting stdout to the target file would hide it, I believe it would be better to have something like OpenSSH's `-q`.  Would that be an option?

I'd alternatively support dropping the banner entirely as the essential information is already given in `tesseract --version`.

**Comment by zdenop** [comment]
@amitdo: parameter file `quiet` should suppress tesseract banner. AFAIK reorganization (99110df75781c6907c84a3d23695a6900b933a97) caused that parameters are loaded/used after printing banner (e.g. `tesseract eurotext.tif eurotext -c debug_file=/dev/null` does not work too). Can you have a look at that?

**Comment by amitdo** [comment]
@zdenop
Nothing has changed in that respect. This is the same behaviour as before my commit.

**Comment by amitdo** [comment]
@zdenop
Anyway, I submitted a PR (#255) which makes `quiet` work as expected regarding tesseract's banner.

**Comment by zdenop** [comment]
Thanks!
@wasamasa: use can use parameter quiet:  `tesseract eurotext.tif eurotext quiet `

**Comment by wasamasa** [comment]
Thanks, works here as well.
