### ISSUE TITLE
Text string objects in pdf are not encoded correctly

### ISSUE THREAD

**Issue by mskrip** [tesseract-ocr/tesseract#1150]
### Environment

* **Tesseract Version**: tesseract 4.00.00alpha
* **Platform**: Linux 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux

### Current Behavior:
Text embedded using `PdfRenderer` are encoded using `UTF_16BE` but do not contain BOM bytes. Only text string that is encoded correctly is in `/Title` metadata.

### Expected Behavior:
According to [PDF reference](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf) all `text string` objects should be encoded in `PdfDocEncoding` or `UTF_16BE` with a leading `byte-order marker` (FEFF).

**Comment by amitdo** [comment]
CC: @jbreiden

**Comment by stweil** [comment]
See chapter 3.8.1 in the PDF reference.

**Comment by jbreiden** [comment]
@mskrip Thanks for problem report. I'll take care of it. Just curious, how did you locate this problem and are there any practical consequences, such a an incompatibility with a PDF renderer.

**Comment by jbreiden** [comment]
I don't know about this, checking in more detail. It's easy enough to put in the BOM. but it messes up highlighting on PDFium. The BOM highlights as if it was a character. 

[before.pdf](https://github.com/tesseract-ocr/tesseract/files/1322978/before.pdf)
[after.pdf](https://github.com/tesseract-ocr/tesseract/files/1322977/after.pdf)
![bad-highlight](https://user-images.githubusercontent.com/4961958/30722445-203f4d3a-9ee6-11e7-8c96-e70a2f32bbb9.png)

```diff
--- tesseract/api/pdfrenderer.cpp	2017-07-14 07:32:13.000000000 -0700
+++ tesseract/api/pdfrenderer.cpp	2017-09-21 15:47:32.000000000 -0700
@@ -476,7 +476,7 @@
           kCharWidth * prec(100.0 * word_length / (fontsize * pdf_word_len));
       pdf_str.add_str_double("", h_stretch);
       pdf_str += " Tz";          // horizontal stretch
-      pdf_str += " [ <";
+      pdf_str += " [ <FEFF";     // byte order marker (BOM)
       pdf_str += pdf_word;       // UTF-16BE representation
       pdf_str += "> ] TJ";       // show the text
     }
```

**Comment by jbreiden** [comment]
With the BOM, I get the same highlighting problem in Acroread and with Left-To-Right languages. Also seeing incorrect copy-paste. This is looking wrong to me.

**Comment by mskrip** [comment]
Hi @jbreiden I came across this while trying to extract text from PDFs in a generic way. I am not aware of any incompatibilities with PDF renderer but without BOM it is incompatible with multiple PDF parsers (i.e. `pdfminer`). From PDF reference chapter 3.8.1:

> For text strings encoded in Unicode, the first two bytes must be 254 followed by 255. These two bytes represent the Unicode byte order marker, U+FEFF, indicating
that the string is encoded in the UTF-16BE (big-endian) encoding scheme
specified in the Unicode standard.

**Comment by jbreiden** [comment]
I can't reproduce the incompatibility with `pdfminer`

```bash
$ apt-get install pdfminer
$ pdf2txt before.pdf
באתר
$ pdf2txt after.pdf
באתר
```

**Comment by jbreiden** [comment]
The 1.7 spec suggests you are right. There's some discussion in there about differences in how text string differs in various spec versions, but I don't think that matters. Perhaps the rendering problem I'm seeing with the BOM is simply due to having an entry for 0xFFEF in the glyphless font.

5.3 Text Objects contain "Text-showing operators"
5.3.2 Operator Tj "Shows a text string"
3.8.1 Text string is "either PDFDocEncoding or UTF-16BE with a leading byte-order marker."

**Comment by jbreiden** [comment]
I still have highlighting and copy-paste problems from the BOM even if I change the mappings.  So at the moment we are stuck.

```
--- tesseract/api/pdfrenderer.cpp	2017-07-14 07:32:13.000000000 -0700
+++ tesseract/api/pdfrenderer.cpp	2017-09-25 10:58:39.000000000 -0700
@@ -608,10 +608,10 @@
       "/CMapName /Adobe-Identify-UCS def\n"
       "/CMapType 2 def\n"
       "1 begincodespacerange\n"
-      "<0000> <FFFF>\n"
+      "<0000> <FEFE>\n"
       "endcodespacerange\n"
       "1 beginbfrange\n"
-      "<0000> <FFFF> <0000>\n"
+      "<0000> <FEFE> <0000>\n"
       "endbfrange\n"
       "endcmap\n"
       "CMapName currentdict /CMap defineresource pop\n"
```

**Comment by jbreiden** [comment]
Simplifying this down to a "Hello World" PDF example, the BOM is causing trouble.

```
%PDF-1.4
1 0 obj <</Type /Catalog /Pages 2 0 R>>
endobj
2 0 obj <</Type /Pages /Kids [3 0 R] /Count 1>>
endobj
3 0 obj<</Type /Page /Parent 2 0 R /Resources 4 0 R /MediaBox [0 0 500 800] /Contents 6 0 R>>
endobj
4 0 obj<</Font <</F1 5 0 R>>>>
endobj
5 0 obj<</Type /Font /Subtype /Type1 /BaseFont /Helvetica>>
endobj
6 0 obj
<</Length 44>>
stream
BT /F1 24 Tf 175 720 Td <FEFF00480065006C006C006F> Tj ET
endstream
endobj
xref
0 7
0000000000 65535 f
0000000009 00000 n
0000000056 00000 n
0000000111 00000 n
0000000212 00000 n
0000000250 00000 n
0000000317 00000 n
trailer <</Size 7/Root 1 0 R>>
startxref
406
%%EOF
```

**Comment by amitdo** [comment]
Evince has no problem with the BOM

pdf.js - same effect as pdfium.

**Comment by jbreiden** [comment]
I'm not going to make this change until (at least) PDFium can render correctly. That means filing a bug with PDFium. Don't have energy to chase this myself anytime soon, but won't stop someone with more energy than me.

**Comment by jbreiden** [comment]
Actually, Adobe Reader can't render hello-bom.pdf either. So I don't know what's up, but best guess is it isn't valid despite spec seemingly saying otherwise.

**Comment by amitdo** [comment]
If both Adobe Reader and PDFium can't render the "with BOM", I see no point in keeping this issue open.
