### ISSUE TITLE
Recognizing with the latest data files gives worse results (teseract 3.04)

### ISSUE THREAD

**Issue by Molochnik** [tesseract-ocr/tesseract#1152]
I have downloaded the latest eng and rus data files and tested them on a small [test file](https://drive.google.com/open?id=0B6JcVXKk0xudYTNnNWhnbDd5R00) with (eng+rus) option.
I also have data files from October, 2016. The results are almost the same 
September, 2017 files;
7) Отчет теперь можно получить и по активному заданию, а He только по законченному.
8) Корректная работа c доставленными SIVIS сообщениями

October, 2016 files;
7) Отчет теперь можно получить и по активному заданию, а He только по законченному.
8) Корректная работа с доставленными SMS сообщениями

but with one small difference in favor of the old files: "SMS" is recognized properly only using them

**Comment by amitdo** [comment]
IMO, the right place for this kind of small inaccuracy report is the forum.
