### ISSUE TITLE
Tesseract 4.0 segfault when using dictionary ces and psm 7

### ISSUE THREAD

**Issue by nektor211** [tesseract-ocr/tesseract#1154]
### Environment

* **Tesseract Version**: 
tesseract 4.00.00alpha
 leptonica-1.74.4
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8

* **Commit Number**: 
2a77d5ad691b53c0fff7400fc4fd66102a24bc27 - found after bisecting from current master
* **Platform**: 
Linux mc01 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
Segfault when running:
```
$tesseract bad.png - -l ces -psm 7
Warning. Invalid resolution 0 dpi. Using 70 instead.
contains_unichar_id(unichar_id):Error:Assert failed:in file ../ccutil/unicharset.h, line 513
Segmentation fault (core dumped)
```

Ces data were downloaded from https://github.com/tesseract-ocr/tessdata/raw/4.00/ces.traineddata .

![bad](https://user-images.githubusercontent.com/1188728/30782283-56613888-a12f-11e7-8bd4-24118e21a763.png)

### Expected Behavior:

```
$ tesseract bad.png - -l ces -psm 7
Warning. Invalid resolution 0 dpi. Using 70 instead.
nguzge gbopf/IUMNIC CZ spol. s r.o.
```

**Comment by amitdo** [comment]
What about other PSMs? 

>Ces data were downloaded from https://github.com/tesseract-ocr/tessdata/raw/4.00/ces.traineddata

There are newer traineddata files available.
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400-september-15-2017

**Comment by nektor211** [comment]
I cannot test it right now but I think that it worked ok when psm was not specified. I'll try to use the new data too, thanks.

**Comment by nektor211** [comment]
I've checked and new traineddata solved this issue.
As for what psm modes, the segfault appeared for modes 7, 8, 11 and 12 (also for 14- but those are probably not valid anyway).
I'm not sure wheter to close this issue right away, but my problem is now solved. Thank You.

**Comment by Shreeshrii** [comment]
Another reason for https://github.com/tesseract-ocr/tesseract/issues/293

Please give the URL link of the files which worked and which ones didn't? 

Which --oem are you using with it?

**Comment by nektor211** [comment]
I've uploaded one that didn't work in the original post. One that works can be seen here:
![1](https://user-images.githubusercontent.com/1188728/31050762-53a1d99c-a655-11e7-93b3-75de57a4bf07.png) . Otherwise it worked fine across a few thousand images, with only a single exception where it failed with the segfault mentioned above.

Oem was not set (as can be seen it examples above), so the default value.

**Comment by amitdo** [comment]
I suggest to close this issue since it was solved with an updated traineddata.

**Comment by IamDixit** [comment]
I had a similar issue.
Got it solved by taking a new training set from https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400-september-15-2017
