### ISSUE TITLE
Ad image recognition problem.

### ISSUE THREAD

**Issue by aijianiula0601** [tesseract-ocr/tesseract#1159]
I want to recognize the text from advertising image,but it takes low accuracy. I have tried grey,Binarisation before tesseract4.0 prediction,but it take the almost accuracy.  Has anyway to improve accuracy? I use chin_sim traindata. Thanking!

**Comment by amitdo** [comment]
[A guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).
Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).
