### ISSUE TITLE
Cannot get dictionary to change output

### ISSUE THREAD

**Issue by hellofishy** [tesseract-ocr/tesseract#116]
See

http://stackoverflow.com/q/33268289/2561126

**Comment by amitdo** [comment]
Does the word 'tor' appear in the word list?

Tesseract will never try to correct a valid word.

**Comment by zdenop** [comment]
We do not provide support for custom training (you need to demonstrate bug with traineddata from google).
You can use [tesseract user forum](https://groups.google.com/forum/#!forum/tesseract-ocr) for instead. I would suggest to search that forum before asking question.
