### ISSUE TITLE
why breaked here with tesseract-ocr on windows?

### ISSUE THREAD

**Issue by nagexiucai** [tesseract-ocr/tesseract#1160]
I have refered solutions like below:

    https://stackoverflow.com/questions/30932120/tesseract-assert-failed-trainingsampleset-cpp-line-622-with-mftraining
    https://stackoverflow.com/questions/18921810/assert-failed-training-tesseract
    https://groups.google.com/forum/#!topic/tesseract-ocr/3e4dV373u_o

But they do not work at all!

I checked font_properties yet.

Here is the [case](https://github.com/nagexiucai/milk-powder/commit/cd0aed443af6aa084da721d48bd107e92934544d) of mine:

    https://github.com/nagexiucai/milk-powder/commit/cd0aed443af6aa084da721d48bd107e92934544d

### Environment

* **Tesseract Version**:  OCR Engine v3.02 with Leptonica
* **Commit Number**: unnkown
* **Platform**: Win7x86-64

### Current Behavior:
    Reading .\pictures\chi_sim.CHei_PRC.exp0.tr ...
    Font id = -1/0, class id = 2/132 on sample 0
    font_id >= 0 && font_id < font_id_map_.SparseSize():Error:Assert failed:in file ..\..\classify\trainingsampleset.cpp, line 622

### Suggested Fix:
none

**Comment by nagexiucai** [comment]
Here is the [details](https://github.com/nagexiucai/milk-powder/blob/master/README.md)!

https://github.com/nagexiucai/milk-powder/blob/master/README.md

**Comment by zdenop** [comment]
3.02 version is old. Very old. Not supported. Please upgrade.

**Comment by Shreeshrii** [comment]
https://digi.bib.uni-mannheim.de/tesseract/

see link for windows binaries


see wiki for details

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
