### ISSUE TITLE
 error: possibly undefined macro: AC_OPENMP

### ISSUE THREAD

**Issue by mayank2711** [tesseract-ocr/tesseract#1161]
Hello All, 

I just downloaded tesseract from https://github.com/tesseract-ocr/tesseract/archive/master.zip and I am getting below error after running ./autogen.sh. I am on "Red Hat Enterprise Linux Server release 5.7 (Tikanga)". Does anyone know how to resolve this issue? 

_Running autoconf
configure.ac:183: error: possibly undefined macro: AC_OPENMP
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:483: error: possibly undefined macro: AC_CONFIG_FILES
configure.ac:509: error: possibly undefined macro: AM_COND_IF

  Something went wrong, bailing out!_

Thanks!!

**Comment by amitdo** [comment]
RHEL 5 is more than 10 years old. We don't support it.
