### ISSUE TITLE
tesseract scanning multiple text iOS 11 only ? 

### ISSUE THREAD

**Issue by burkaslarry** [tesseract-ocr/tesseract#1162]
Without using VNTextObservation , how can we scan multiple text ? it is because  VNTextObservation is only supported in iOS 11 instead of iOs 10 

   let recognizedText = tesseract?.recognizedText
//        print("recognizedText occured \(recognizedText ?? "nil")")

     

------------------------

### Environment

* **Tesseract Version**: 4.0.0 , cocoa pods
* **Commit Number**: 
* **Platform**:  64 bit , Mac OSX 10.12.6 , Xcode. 9

**Comment by amitdo** [comment]
[A guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).
Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).
