### ISSUE TITLE
Preprocessing always rotating portrait image, causing text to be vertical

### ISSUE THREAD

**Issue by Dan9er** [tesseract-ocr/tesseract#1165]
### Environment
* **Tesseract Version**:
```
tesseract 3.05.01
 leptonica-1.74.4
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8
```
* **Commit Number**: [2158661](https://github.com/tesseract-ocr/tesseract/commit/215866151e774972c9502282111b998d7a053562)
* **Platform**: `Linux Inspiron-530s 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

---

### Current Behavior:
```
dan9er@A-Computer:~/Pictures$ tesseract image.jpg out -c tessedit_write_images=1
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.
````

#### **image.jpg**:
![Pill bottle](https://imgur.com/pYjuSCn.png)

#### **tessinput.tif**:
![Black and white image of pill bottle with text "NPN 80051578" sideways](https://imgur.com/SOJFK2f.png)

#### **out.txt**:
```
22%mzzztnztzm 22:“: a $5.35

a
mhmﬁmoowuzgz

.

SEEESaEmS 2:

.32 8:325
§o3WK<S

 

```

---

#### **tessinput.tif**:
![B&W pill bottle with NPN text right side up](https://imgur.com/Q55k7v1.png)

#### **out.txt**:
```
[junk maybe]

NPN: 80051578

[junk maybe]
```

---

### Suggested Fix:
Add a config tag (`tessedit_rotation_override`?) that overrides the auto-rotation. It could be just 1/0 (never rotate input image if 1) or 0-3 (always rotate by this multiple of 90).

EDIT: I don't know why but turns out the [original image I posted](https://imgur.com/An1Fz1T.png) recognized fine, even though it was still rotated! The majority of my images output junk though, so I replaced the image with one that doesn't work. Oh, and added console output, out.txt and input image

**Comment by amitdo** [comment]
Upload the original image.

Write the full command you are using.

What the output you are getting, including errors messages, if any?

**Comment by Dan9er** [comment]
Ok, post updated

**Comment by amitdo** [comment]
>@tfmorris suggested changing the PSM, but that does nothing:

Including the output **text**?

**Comment by amitdo** [comment]
You should have osd.traineddata to make some PSMs work properly.

**Comment by Dan9er** [comment]
@amitdo PSM 12 is the only one that works (with the new image), but that's only if I run Tesseract with a config file I made:
```
load_system_dawg        F
load_freq_dawg          F
user_words_suffix       user-words
user_patterns_suffix    user-patterns
tessedit_char_whitelist NP0123456789:#
```
Plus, PSM 12 is described as "Sparse text *with OSD*". @tfmorris said it's the OSD that's doing the rotation.
And, if OSD is disabled for some of the PSMs, then why are ALL of the TIFF files rotated?

**Comment by Dan9er** [comment]
Bump

**Comment by Shreeshrii** [comment]
I remember seeing that if tesseract can't recognize image, it tries to rotate it to see if it gets better results. That could be causing the rotation in your case.

**Comment by Dan9er** [comment]
@Shreeshrii Well, is there any way to disable that rotation and force tesseract to recognise the unrotated image?

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/blob/a1c22fb0d0f6bde165ec7b7c3125420b0ba1d541/textord/colfind.cpp

**Comment by Dan9er** [comment]
Well if I give Tesseract a horizontal image of the bottle, tessinput.tif is not rotated. Upon closer inspection of the images that do not OCR correctly, **it looks like the binarization algorithm is the real culprit here**. Tesseract doesn't seem to care about the rotation of the text. Anyway, I don't think this is a problem with Tesseract itself so I'm closing this Issue. Some weird **** is going on here. It may be Leptonica, the `tessedit_write_images` code, or even Ubuntu that is rotating the image after Tesseract spits it out.

If I find anything I'm going to post in [this Google Groups thread](https://groups.google.com/forum/#!topic/tesseract-ocr/GAbzk9BTGDE).

**Comment by Dan9er** [comment]
It is Leptonica that is causing this to happen. Submitting an issue on there rn.

Not reopening this since there is nothing the Tesseract dev can do here, this is a Leptonica issue.
