### ISSUE TITLE
training/lstmtraining segment fault

### ISSUE THREAD

**Issue by ivanzz1001** [tesseract-ocr/tesseract#1168]
### Environment

* **Tesseract Version**: tesseract 4.00.00alpha
* **Commit Number**: 2cc531e
* **Platform**: Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
I use the following command to train:
<pre>
[root@localhost tesseract]# training/lstmtraining --debug_interval 100 \
>   --traineddata ../tesstutorial/chi_simtrain/chi_sim/chi_sim.traineddata \
>   --net_spec '[1,48,0,1 Ct3,3,16 Mp3,3 Lfys64 Lfx96 Lrx96 Lfx512 O1c111]' \
>   --model_output ../tesstutorial/chi_simoutput/base --learning_rate 20e-4 \
>   --train_listfile ../tesstutorial/chi_simtrain/chi_sim.training_files.txt \
>   --eval_listfile ../tesstutorial/chi_simeval/chi_sim.training_files.txt \
>   --max_iterations 10000 &>../tesstutorial/chi_simoutput/basetrain.log
Segmentation fault (core dumped)
</pre>
But it caught segmentation fault.

when training I use the following command to see the log:
<pre>
# tail -f ../tesstutorial/chi_simoutput/basetrain.log
....
Iteration 9998: ALIGNED TRUTH : 恽寿榕印刷width打垮年推荐评论Microsoft 邵武的月经沉,特性产权 巫山
Iteration 9998: BEST OCR TEXT : 
File /tmp/tmp.79zY0ByWtx/chi_sim/chi_sim.STFangsong.exp0.lstmf page 188 :
Mean rms=4.264%, delta=50.362%, train=99.57%(99.92%), skip ratio=0%
Iteration 9999: ALIGNED TRUTH : 》杂耍啤酒花href镁天竺葵垮塌帐篷 藕腱鞘炎 岷 关专业祭副4About 下挫
Iteration 9999: BEST OCR TEXT :  
File /tmp/tmp.79zY0ByWtx/chi_sim/chi_sim.STKaiti.exp0.lstmf page 91 :
Mean rms=4.264%, delta=50.364%, train=99.569%(99.92%), skip ratio=0%
2 Percent improvement time=10000, best error was 100 @ 0
At iteration 10000/10000/10000, Mean rms=4.264%, delta=50.364%, char train=99.569%, word train=99.92%, skip ratio=0%,  New best char error = 99.569 wrote checkpoint.

Finished! Error rate = 99.569
num_docs > 0:Error:Assert failed:in file imagedata.cpp, line 651
Exception in thread "main" java.lang.NullPointerException
        at com.google.scrollview.ui.SVWindow.drawImage(SVWindow.java:336)
        at com.google.scrollview.ScrollView.processInput(ScrollView.java:321)
        at com.google.scrollview.ScrollView.IOLoop(ScrollView.java:120)
        at com.google.scrollview.ScrollView.main(ScrollView.java:398)
</pre>

From the basetrain.log, It seems that the training iteration has reached 10000 and has finished the training. And from tesseract-master/training/lstmtraining.cpp:
<pre>
int main(int argc, char **argv) {
....

do {
    // Train a few.
    int iteration = trainer.training_iteration();
    for (int target_iteration = iteration + kNumPagesPerBatch;
         iteration &lt; target_iteration;
         iteration = trainer.training_iteration()) {
      trainer.TrainOnLine(&trainer, false);
    }
    STRING log_str;
    trainer.MaintainCheckpoints(tester_callback, &log_str);
    tprintf("%s\n", log_str.string());
  } while (trainer.best_error_rate() &gt; FLAGS_target_error_rate &&
           (trainer.training_iteration() &lt; FLAGS_max_iterations ||
            FLAGS_max_iterations == 0));
  delete tester_callback;
  tprintf("Finished! Error rate = %g\n", trainer.best_error_rate());
  return 0;
}
</pre>
It seems that it has already finished. So which process are executing the lstmtraining.cpp:
<pre>
const ImageData* DocumentCache::GetPageSequential(int serial) {
  int num_docs = documents_.size();
  ASSERT_HOST(num_docs > 0);

....
}
</pre>
and here the assert caused the segmentation fault? 

Here I checked the output dir:
<pre>
[root@localhost tesseract]# ls ../tesstutorial/chi_simoutput/ 
base_checkpoint  basetrain.log
</pre>
It has generated the base_checkpoint. So are there any following steps that the training process should do? And It seems that the segmentation fault doesn't effect much.

**Comment by Shreeshrii** [comment]
Are you trying to train from scratch?

10000 iterations are too low for that.

You have an error rate of 99%.

Did you try replace a layer for training?

**Comment by ivanzz1001** [comment]
Yes, I am training from scratch. But I don't know why error rate is 99%

**Comment by Shreeshrii** [comment]
You need to train for days and many iterations, with very large training
texts to train from scratch.

However, the crash should not happen.

**Comment by ivanzz1001** [comment]
@Shreeshrii The example give the iteration to be 5000, here I set it to 10000? Is it too small? Have you use the tesseract4.0alpha to train anything? you can set the  "--max_iteration" to a very small value and check whether it causes the segmentation fault.

**Comment by ivanzz1001** [comment]
@Shreeshrii  And In the basetrain.log,  it prints many "ALIGNED TRUTH"
<pre>
File /tmp/tmp.79zY0ByWtx/chi_sim/chi_sim.Arial_Unicode_MS_Bold.exp0.lstmf page 735 :
Mean rms=4.291%, delta=50.688%, train=99.996%(100%), skip ratio=0%
Iteration 5251: ALIGNED TRUTH : 尧 地区瑶族取暖调节软件 日问题遐想二陌77 1997及学会呵呵心态 85 for 的
Iteration 5251: BEST OCR TEXT :  
File /tmp/tmp.79zY0ByWtx/chi_sim/chi_sim.Arial_Unicode_MS.exp0.lstmf page 587 :
Mean rms=4.29%, delta=50.671%, train=99.995%(100%), skip ratio=0%
Iteration 5252: ALIGNED TRUTH : 鉴定关闭年激烈法规制药中轶读 五芍广场 皿 投资Qzone 霸62791813访问胫
Iteration 5252: BEST OCR TEXT : 
File /tmp/tmp.79zY0ByWtx/chi_sim/chi_sim.AR_PL_UKai_CN.exp0.lstmf page 9 :
Mean rms=4.29%, delta=50.665%, train=99.995%(100%), skip ratio=0%
Iteration 5253: ALIGNED TRUTH : 基金凋设 . 售后他Gzip 陈镒康 网站这里 1996 崖违规相信咕咚慈善日本
Iteration 5253: BEST OCR TEXT : 
</pre>

And in the [training tutorial -- error msg](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#error-messages-from-training), It seems that it's a problem

**Comment by Shreeshrii** [comment]
If you try training with debug level -1 and see the output on console
rather than sending to log file, you will see that for each line of
training text the ocred output and aligned truth will be displayed.

**Comment by ivanzz1001** [comment]
why the "BEST OCR TEXT " is empty? I have modified the langdata/chi_sim/chi_sim.training_text , I don't know whether this is the reason? And "--max_iteration" set to 1000 is too small?

**Comment by ivanzz1001** [comment]
@Shreeshrii  Hi, I use the "training/tesstrain.sh" to generate the training data and eval data; Should I use the following command to generate lstm-recoder([Creating Starter Traineddata](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#creating-starter-traineddata))?
<pre>
# training/combine_lang_model --input_unicharset ../tesstutorial/chi_simtrain/chi_sim/chi_sim.unicharset \
 --script_dir ../langdata \
 --words ../langdata/chi_sim/chi_sim.wordlist \
 --numbers ../langdata/chi_sim/chi_sim.numbers \
 --puncs ../langdata/chi_sim/chi_sim.punc \
 --output_dir ../tesstutorial/chi_simtrain \
 --lang chi_sim \
 --version_str "4.0.0alpha chi_sim"
</pre>
I greped the "combine_lang_model" and found it was called by "tesstrain_utils.sh", and "tesstrain_utils.sh"  is called by "training/tesstrain.sh", so I had skipped the step。Here I checked "ALIGNED TRUTH" problem, I think this may be the reason. But If It needs this step,  should I generate it for both training data and eval data?

**Comment by Shreeshrii** [comment]
When you start training from scratch, your error rate will be 100% and best
ocr text will be empty. After 10,000 iterations you are at 99% error rate
and best ocr text will still be empty.

For training from scratch Ray is using 400,000+ lines of text and probably
millions of iterations.

I would suggest you try to replace the top layer.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by ivanzz1001** [comment]
@Shreeshrii I retried the training:
<pre>
training/lstmtraining --debug_interval 100 \
>   --traineddata ../tesstutorial/chi_simtrain/chi_sim/chi_sim.traineddata \
>   --net_spec '[1,48,0,1 Ct3,3,16 Mp3,3 Lfys64 Lfx96 Lrx96 Lfx512 O1c111]' \
>   --model_output ../tesstutorial/chi_simoutput/base --learning_rate 20e-4 \
>   --train_listfile ../tesstutorial/chi_simtrain/chi_sim.training_files.txt \
>   --eval_listfile ../tesstutorial/chi_simeval/chi_sim.training_files.txt \
>   --max_iterations 10000 &>../tesstutorial/chi_simoutput/basetrain.log
</pre>
But It cause :
<pre>
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
</pre>
I think it is because the capacity of my vmware-centos's disk  is not enough, so I want to do the training work on a special server, but I found that the command can't be executed on remote. It must first login the centos , then open the terminal and thus you can execute the above command. If execute on remote, it may cause "broken pipe" error and quickly quit (the training process may need to communicate with other windows, eg CTC Output window) . How do I solve the problem?

**Comment by Shreeshrii** [comment]
Sorry, I do not know enough this to comment. @stweil @amitdo might be able to guide you.

**Comment by ivanzz1001** [comment]
@Shreeshrii You can execute the following english training command on remote(eg. use SSH to login your training computer)
<pre>
training/lstmtraining --debug_interval 100 \
  --traineddata ~/tesstutorial/engtrain/eng/eng.traineddata \
  --net_spec '[1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx96 Lrx96 Lfx256 O1c111]' \
  --model_output ~/tesstutorial/engoutput/base --learning_rate 20e-4 \
  --train_listfile ~/tesstutorial/engtrain/eng.training_files.txt \
  --eval_listfile ~/tesstutorial/engeval/eng.training_files.txt \
  --max_iterations 5000 &>~/tesstutorial/engoutput/basetrain.log
</pre>
and you may see the error "broken pipe"

**Comment by ivanzz1001** [comment]
@Shreeshrii sorry, maybe I haven't described it very clear. This is the log:
<pre>
Starting sh -c "trap 'kill %1' 0 1 2 ; java -Xms1024m -Xmx2048m -jar /root/tesseract-src/tesseract/java/ScrollView.jar & wait"
Socket started on port 8461
Created window Convolve of size 1511, 580
Client connected
Created window ConvNL of size 1310, 848
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at javax.swing.JFrame.<init>(JFrame.java:233)
        at com.google.scrollview.ui.SVWindow.<init>(SVWindow.java:204)
        at com.google.scrollview.ScrollView.processInput(ScrollView.java:340)
        at com.google.scrollview.ScrollView.IOLoop(ScrollView.java:120)
        at com.google.scrollview.ScrollView.main(ScrollView.java:398)
sh: line 1: kill: %1: no such job
Created window Lfys64 of size 530, 2000
</pre>
It is because when you execute the command on remote, it can't open the related window.

**Comment by Shreeshrii** [comment]
I do not use scrollview. I either use debug level -1 or 0.

I do not know much about Linux or C++ or tesseract. I test tesseract for
OCR of Indian languages, mainly devanagari for sanskrit.

So, I can only suggest options if it is something I have encountered while
training/testing.

**Comment by amitdo** [comment]
Try re-building with `./configure --disable-graphics`

**Comment by stweil** [comment]
... or simply hide or remove `scrollview`, so it won't be run.

**Comment by Shreeshrii** [comment]
See comment on https://github.com/tesseract-ocr/tesseract/issues/757#issuecomment-466302944

Seems to be a duplicate issue.

**Comment by stweil** [comment]
Issue #2191 indicates that this problem might be a thread synchronisation issue (which also explains why it cannot be reproduced in each call).

**Comment by Shreeshrii** [comment]
I think it might be related to the `eval` processing which is run in `async` mode.

**Comment by stweil** [comment]
Pull request #3016 hopefully fixes this.

**Comment by WangPengZhan** [comment]
Excuse me, i meet a tressble, as following
```
$ lstmtraining --debug_interval 100 --traineddata tesstutorial/Leveloutput/Level/Level.traineddata --net_spec '[1,48,0,1 Ct3,3,16 Mp3,3 Lfys64 Lfx96 Lrx96 Lfx512 O1c111]' --model_output tesstutorial/Leveloutput/base --train_listfile Level.training_files.txt --eval_listfile tesstutorial/Leveloutput/Leveleval/Level.training_files.txt --max_iterations 10000
Warning: given outputs 111 not equal to unicharset of 17.
Num outputs,weights in Series:
  1,48,0,1:1, 0
Num outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys64:64, 20736
  Lfx96:96, 61824
  Lrx96:96, 74112
  Lfx512:512, 1247232
  Fc17:17, 8721
Total weights = 1412785
Built network:[1,48,0,1[C3,3Ft16]Mp3,3Lfys64Lfx96Lrx96Lfx512Fc17] from request [1,48,0,1 Ct3,3,16 Mp3,3 Lfys64 Lfx96 Lrx96 Lfx512 O1c111]
Training parameters:
  Debug interval = 100, weights = 0.1, learning rate = 0.001, momentum=0.5
null char=16
Loaded 293/293 lines (1-293) of document Level.font.exp0.lstmf
Deserialize header failed: C:/workfile/jTessBoxEditorFX/tesseract-ocr/Level.font.exp0.lstmf
First document cannot be empty!!
num_pages_per_doc_ > 0:Error:Assert failed:in file ../../../src/ccstruct/imagedata.cpp, line 651
```
Tesseract Open Source OCR Engine v5.0.0-alpha.20200328 with Leptonica
lstmf file be created by two command:
tesseract Level.font.exp0.tif Level.font.exp0 --psm 7 nobatch box.train 
tesseract Level.font.exp0.tif Level.font.exp0 -l eng --psm 6 lstm.train

what's wrong

**Comment by WangPengZhan** [comment]
> Excuse me, i meet a tressble, as following
> 
> ```
> $ lstmtraining --debug_interval 100 --traineddata tesstutorial/Leveloutput/Level/Level.traineddata --net_spec '[1,48,0,1 Ct3,3,16 Mp3,3 Lfys64 Lfx96 Lrx96 Lfx512 O1c111]' --model_output tesstutorial/Leveloutput/base --train_listfile Level.training_files.txt --eval_listfile tesstutorial/Leveloutput/Leveleval/Level.training_files.txt --max_iterations 10000
> Warning: given outputs 111 not equal to unicharset of 17.
> Num outputs,weights in Series:
>   1,48,0,1:1, 0
> Num outputs,weights in Series:
>   C3,3:9, 0
>   Ft16:16, 160
> Total weights = 160
>   [C3,3Ft16]:16, 160
>   Mp3,3:16, 0
>   Lfys64:64, 20736
>   Lfx96:96, 61824
>   Lrx96:96, 74112
>   Lfx512:512, 1247232
>   Fc17:17, 8721
> Total weights = 1412785
> Built network:[1,48,0,1[C3,3Ft16]Mp3,3Lfys64Lfx96Lrx96Lfx512Fc17] from request [1,48,0,1 Ct3,3,16 Mp3,3 Lfys64 Lfx96 Lrx96 Lfx512 O1c111]
> Training parameters:
>   Debug interval = 100, weights = 0.1, learning rate = 0.001, momentum=0.5
> null char=16
> Loaded 293/293 lines (1-293) of document Level.font.exp0.lstmf
> Deserialize header failed: C:/workfile/jTessBoxEditorFX/tesseract-ocr/Level.font.exp0.lstmf
> First document cannot be empty!!
> num_pages_per_doc_ > 0:Error:Assert failed:in file ../../../src/ccstruct/imagedata.cpp, line 651
> ```
> 
> Tesseract Open Source OCR Engine v5.0.0-alpha.20200328 with Leptonica lstmf file be created by two command: tesseract Level.font.exp0.tif Level.font.exp0 --psm 7 nobatch box.train tesseract Level.font.exp0.tif Level.font.exp0 -l eng --psm 6 lstm.train
> 
> what's wrong

the number of imagesdata is 293
my images only contains "0123456789mVGMHz/R" chars. and only one font and size.
