### ISSUE TITLE
Algorithm principle： recognize a single word from a line word

### ISSUE THREAD

**Issue by craigtao** [tesseract-ocr/tesseract#1169]
Algorithm principle： recognize a single word from a line word

Where the code is in the source file， I want to use this algorithm

thank you very much, 

Craig Tao

**Comment by fakabbir** [comment]
Hey Tao,

I guess you need to extract words from the images that you are working on. Using tesseract you can create a **.html** file which contains the data about the coordinates of words.
- To create html file use command
`tesseract ImageName OutputHtmlName hocr`
- To extract words (Code Snippet):  
```python
from bs4 import BeautifulSoup
# filename would be OutputHtmlName ;)
def WordCoordinate(filename):
	html_doc = open(filename,'r')
	soup = BeautifulSoup(html_doc, 'html.parser')

	WordCordinates = []
	for line in soup.find_all(class_='ocrx_word'):
		lineVal =  line['title']
		inData = lineVal.split(" ")
		tuppleData = np.array([inData[1],inData[2],inData[3],inData[4]],dtype = int)
		#print tuppleData
		WordCordinates.append(tuppleData)
	#print LineCordinates
	html_doc.close()
	return WordCordinates
def DrawCoordinate(img,Cordinates):
	for item in Cordinates:
		x1,y1 = item[0],item[1]
		x2,y2 = item[2],item[3]
		#print x1,y1,x2,y2
		cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),3)
```
If you are interested in the algorithm I suggest you to look at https://github.com/tesseract-ocr/docs specially the **das_tutorial2016**.
The code for segmentation is in 
```
tessetact/ccmain/linerec.cpp
tessetact/ccmain/paragraphs.cpp
tessetact/ccmain/applybox.cpp
```

Hope this helps. :) 

Also divert any other query at stackexchange for better visibility.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
