### ISSUE TITLE
Conversion to pdf is okay, but conversion to default filetype like .txt is giving empty file.

### ISSUE THREAD

**Issue by shilpi230** [tesseract-ocr/tesseract#117]
```tesseract scan.tif filename``` This command is giving empty text file. 
But this ``` tesseract scan.tif filename pdf ``` is giving correct pdf file. What can be the issue ?

**Comment by amitdo** [comment]
try tesseract scan.tif filename -psm 1

**Comment by zdenop** [comment]
Please use tesseract forum for asking support: https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice
