### ISSUE TITLE
namespace error while using tesseract API

### ISSUE THREAD

**Issue by emilzak** [tesseract-ocr/tesseract#1170]
In file included from /usr/local/include/tesseract/ltrresultiterator.h:26:0,
                 from /usr/local/include/tesseract/resultiterator.h:26,
                 from /usr/local/include/tesseract/baseapi.h:31,
                 from perHash.cpp:1:
/usr/local/include/tesseract/unichar.h:164:10: error: ‘string’ does not name a type
   static string UTF32ToUTF8(const std::vector<char32>& str32);

**Comment by stweil** [comment]
It looks like we'll get error reports for this forever. @emilzak, please search for earlier issues and the suggested solutions for that. They are not hard to find.
