### ISSUE TITLE
Box & Tiff File example

### ISSUE THREAD

**Issue by ErnstTmp** [tesseract-ocr/tesseract#1174]
Hello,
thanks for creating Tesseract 4.0.
I have problems creating the box files correctly (where should the tab go?) and get error messages from LSTM training.

There is a link for an example Box File in github, but it is not working any more (https://github.com/tesseract-ocr/tesseract/wiki/Making-Box-Files---4.0 the links on this page are broken). Could you please publish a working *.box and a corresponding *.tif file for LSTM-Training?

Thanks & kind regards
Ernst

**Comment by Shreeshrii** [comment]
Easiest way for you to get this is to run tesstrain.sh for English with a short training text and one font. Then look in your tmp folder for the box/tif files.

**Comment by Shreeshrii** [comment]
Here are sample files for English ...

[eng-box-tif.zip](https://github.com/tesseract-ocr/tesseract/files/1404580/eng-box-tif.zip)

**Comment by ErnstTmp** [comment]
@Shreeshrii  thank you very much for your files!!!! I used tesstrain.sh, but did not look into /tmp. Shame on me!
I could not get tesseract to create box files. I used

tesseract pol.ocrb.exp$i.tif pol.ocrb.exp$i batch.nochop makebox

as described, but it created a file called batch.nochop.box, but not the box file I expected (an old style box file would be OK)

Thanks,
Ernst

**Comment by Shreeshrii** [comment]
The following works for me.

img_files=${img_files}' '$(ls shritatvanidhi-0056*.tif)
    for img_file in ${img_files}; do
       echo ${img_file}
       tesseract ${img_file} ${img_file%.*}  --psm 6 --oem 1 -l hin
--tessdata-dir /mnt/c/Users/User/shree/tessdata makebox
    done

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by ErnstTmp** [comment]
@Shreeshrii thank you very much, that works for me also, that is great!!!
I do not know why the original calls (and I tried many) did not work. 
Kind regards
Ernst

**Comment by sayedmohsen560** [comment]
@Shreeshrii  I want to talk to you about tesseract training
