### ISSUE TITLE
Memory Leak and OCR Improvment in Android

### ISSUE THREAD

**Issue by mazmik25** [tesseract-ocr/tesseract#1175]
Environment
I'm currently using tess-two version 8.0.0

Current Behavior:
I've tested my app at several images. Actually some of them worked very nice. But the issues starts when i take a picture from water metering which contains of numbers. The tesseract doesn't recognize it and instead of returning it as numbers, it gave me random words. Also, when i've done with the recognition, the memory didn't release. So, here's my question:
 
1. How can i release the memory after the recognition, and 
2. How can i improve the reading when the text is coming from the water metering?

Expected Behavior:
1. The memory will be released (so i can save up to 30 MB)
2. The OCR works on Water metering (at least up to 75%)

**Comment by zdenop** [comment]
Please read & follow instruction for posting issue.
