### ISSUE TITLE
Error: Call PrepareToWrite before WriteTesseractBoxFile!!

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1176]
Version: Tesseract 4.0alpha from github
Platform: Windows10/WSL Ubuntu 14.04

```
Rendered page 338 to file /tmp/tmp.Bja2jDWX7C/san/san.Nakula.exp0.tif
Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!
```

The tif files are being created by text2image but the box files have size zero. It seems to be dependent on the training_text and works with other text files.

**Comment by Shreeshrii** [comment]
Seems to be related to font and text line combinations.

Changing text, textline order, fonts causes the error to go away.

**Comment by Shreeshrii** [comment]
Rendered page 1 to file /tmp/tmp.kGtpoGFL6c/iast/iast.Arapey_Italic.exp-2.tif
Stripped 7 unrenderable words
Stripped 64 unrenderable words
Rendered page 2 to file /tmp/tmp.kGtpoGFL6c/iast/iast.Arapey_Italic.exp-2.tif
Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!
Rendered page 0 to file /tmp/tmp.kGtpoGFL6c/iast/iast.Archivo_Italic.exp-2.tif
Stripped 63 unrenderable words
Rendering using Arial
[Sat Jun 30 17:06:46 UTC 2018] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.qOsVOAd65k --fonts_dir=/home/ubuntu/.fonts/ --strip_unrenderable_words --leading=32 --xsize 2560 --char_spacing=0.0 --exposure=-2 --outputbase=/tmp/tmp.kGtpoGFL6c/iast/iast.Archivo_Narrow_Italic.exp-2 --max_pages=0 --font= Archivo Narrow Italic --text=./tmp_thistraining_text
Stripped 118 unrenderable words
Rendered page 1 to file /tmp/tmp.kGtpoGFL6c/iast/iast.Archivo_Italic.exp-2.tif
Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!
Rendered page 0 to file /tmp/tmp.kGtpoGFL6c/iast/iast.Archivo_Narrow_Italic.exp-2.tif
Stripped 97 unrenderable words
Rendering using Arial Italic

**Comment by XinAlo** [comment]
i have the same error , do u konw how to solve it ?  thanks !

**Comment by zdenop** [comment]
Sorry, but we do not have crystal balls to find out what you did and how.
Error message is clear: 
> /tmp/chi_sim-2018-10-30.6vi/chi_sim..exp0.box does not exist or is not readable
Find the reason why it does not exists or make it readable.

**Comment by Shreeshrii** [comment]
Duplicate of https://github.com/tesseract-ocr/tesseract/issues/1902
