### ISSUE TITLE
Assert failed:in file ../ccutil/unicharset.h, line 513

### ISSUE THREAD

**Issue by TerryZH** [tesseract-ocr/tesseract#1177]
------------------------

### Environment

* **Tesseract Version**: Tesseract Open Source OCR Engine v4.00.00dev-692-gad5ee184 with Leptonica
* **Platform**: Linux 4.9.43-17.39.amzn1.x86_64 #1 SMP x86_64 GNU/Linux

### Current Behavior:
Command '['tesseract', '/tmp/tr_tmp.jpg', '/tmp/tr_tmp', '--tessdata-dir', '/var/task/tessdata', '--psm', '12', '--oem', '2', '-l', u'eng', 'hocr']' returned non-zero exit status -11: CalledProcessError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 22, in lambda_handler
**event
File "/var/task/lib/ocr/common/procedures.py", line 105, in recognize
scanned = scanner.scan_jpg(swabbed, file_desc['pagenum'], **kwargs)
File "/var/task/lib/ocr/common/scanner.py", line 62, in scan_jpg
'hocr',
File "/usr/lib64/python2.7/subprocess.py", line 541, in check_call
raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['tesseract', '/tmp/tr_tmp.jpg', '/tmp/tr_tmp', '--tessdata-dir', '/var/task/tessdata', '--psm', '12', '--oem', '2', '-l', u'eng', 'hocr']' returned non-zero exit status -11

### Expected Behavior:
no crash

**Comment by zdenop** [comment]
Please follow instruction of issue tracker - we do not support 3rd party sw (python)

**Comment by leisoneduardo** [comment]
Hi friend, did you find a solution?

**Comment by Shreeshrii** [comment]
'--oem', '2', '

Please use --oem 1 for the LSTM engine.

**Comment by IamDixit** [comment]
had a similar issue.
Got it solved by taking a new training set from https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400-september-15-2017
