### ISSUE TITLE
build training tools failed

### ISSUE THREAD

**Issue by xinqinglxl** [tesseract-ocr/tesseract#1179]
I meet a error while building training tools from source(4.0 master)
First, I build the tesseract-ocr which is successful.
1 yum install autoconf automake libtool libjpeg-devel libpng-devel libtiff-devel zlib-devel
2 build leptonica from source(leptonica-1.74.4)
3 build tesseract-ocr
   ./autogen.sh
  ./configure --prefix=/usr/local/tesseract --with-extra-libraries=/usr/local/leptonica/lib   
  make
  make install
--------------------------
Then I try to build training tools
1 yum install libicu-devel
2 yum install pango-devel
3 yum install cairo-devel
make training
But it comes the following error

`depbase=`echo boxchar.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../lstm -I../arch -I../viewer -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil  -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng15 -I/usr/include/libdrm    -g -O2 -std=c++11 -MT boxchar.lo -MD -MP -MF $depbase.Tpo -c -o boxchar.lo boxchar.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../lstm -I../arch -I../viewer -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng15 -I/usr/include/libdrm -g -O2 -std=c++11 -MT boxchar.lo -MD -MP -MF .deps/boxchar.Tpo -c boxchar.cpp  -fPIC -DPIC -o .libs/boxchar.o
boxchar.cpp: In member function 'void tesseract::BoxChar::GetDirection(int*, int*) const':
boxchar.cpp:67:42: error: 'U_RIGHT_TO_LEFT_ISOLATE' was not declared in this scope
         dir == U_ARABIC_NUMBER || dir == U_RIGHT_TO_LEFT_ISOLATE) {
                                          ^
make[1]: *** [boxchar.lo] Error 1
make[1]: Leaving directory `/home/lixl/workspace/tesseract/tesseract-ocr/training'
make: *** [training] Error 2`

What's wrong with my work, any advice?
My OS is centos 7

**Comment by zdenop** [comment]
Did you check the output of configure?

**Comment by xinqinglxl** [comment]
I change the OS to Ubuntu and it seems OK.
Thanks for the reply and please close the issues

**Comment by EllenSong77** [comment]
I've already installed tesseract by make && sudo make install.
But I got the same error when using command make training.

OS: Centos 7
Tesseract: 4.00 master

Any advice?

**Comment by EllenSong77** [comment]
I tryed and got the same error.
Still thanks for your reply.

**Comment by amitdo** [comment]
>-o .libs/boxchar.o boxchar.cpp: In member function 'void tesseract::BoxChar::GetDirection(int*, int*) const': boxchar.cpp:67:42: error: 'U_RIGHT_TO_LEFT_ISOLATE' was not declared in this scope

The training tools need icu version `52` and up. The icu version in RHEL & CentOS 7 is `50`.

**Comment by EllenSong77** [comment]
Thank you so much for your answer!
Finally setup my training tool!

**Comment by 20Aditya** [comment]
> Thank you so much for your answer!
> Finally setup my training tool!

Can you tell me how did you upgrade the ICU version because I did `locate uchar.h` which gives me `/usr/include/uchar.h`  and `/usr/include/unicode/uchar.h`

I dont know if this seems a totally stupid question.
