### ISSUE TITLE
Detection Error with Fine Tuned Model

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#1180]
Hi,

i was using the newest versions of Tesseract to:
1- create LSTMFs
2- extract the LSTM from official traineddata
3- fine tune the LSTM according to the created LSTMFs
4- and then use the new traineddata for detection for better results
i was able to do all these steps and get the final traineddata but when i made detection using it i got an error, now the same case happened for Arabic and Japanese languages, and both i was able to get fine tuned traineddata and both failed in detection and gave the same error.
the commands i used as described [here](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#lstmtraining-command-line)
and they were: 
**for creating LSTMFs**
training/tesstrain.sh --fonts_dir ~/.local/share/fonts --lang ara --linedata_only --noextract_font_properties --langdata_dir /home/ibr/latest_leptonica_4/langdata --tessdata_dir ./tessdata --output_dir /home/ibr/latest_leptonica_4/lstmf_ara_lep4

**extracted LSTM from [*here*](https://github.com/tesseract-ocr/tessdata_best)

**tuned LSTM**
training/lstmtraining --model_output /home/ubuntu/lep_latest/ara_tune/tune_result/ara_tune \
  --continue_from /home/ubuntu/lep_latest/ara_tune/extracted/ara.lstm \
  --traineddata /home/ubuntu/lep_latest/ara_tune/original_traineddata/ara.traineddata \
  --train_listfile /home/ubuntu/lep_latest/ara_tune/ara.training_files.txt \
  --max_iterations 1200

**then unpacked official traineddata"official traineddata", replaced the tuned LSTM and combined everything together again **

**detection command**
tesseract ara2.png tuned -l ara --tessdata-dir ./tessdata --oem 1

and when i used the new tuned traineddata i got the error:
**index >= 0:Error:Assert failed:in file strngs.cpp, line 270
Segmentation fault (core dumped)** 

that happened when i tried fine tuning for Arabic and Japanese, twice, first time using the version:
**tesseract 4.00.00dev-690-g1b0379c   leptonica-1.74.4**
second time: **tesseract 4.00.00dev-691-gfb359fc  leptonica-1.74.4**

_keep im mind the same exact steps worked for previous versions of tesseract with leptonica 1.74.1_

**NOTE: detection worked fine with both versions for the official traineddata, meaning the error only occurred only after fine tuning**

Thanks in advance

**Comment by Shreeshrii** [comment]
Please read instructions given in the wiki page for training for 4.0.

You have to use lstmtraining command with --stop-training to create the new
traineddata.

**Comment by Shreeshrii** [comment]
The new format traineddata file has a version string,
unicharcompressor/recorder, and a unicharset which matches with the lstm
model.

If you combine your fine-tune lstm with existing traineddata, the files
will not be in sync. You are getting error because of mismatch of
unicharset with lstm.

Also, your lstmtraining command should use the starter traineddata.

Wiki pages have more details.

**Comment by ibr123** [comment]
@Shreeshrii sorry, my mistake, i forgot to mention the command to create the LSTM from the check point which is:
_training/lstmtraining --model_output /home/ibr/latest_leptonica_4/ara_tune/tuned_lstm/ara.lstm --continue_from /home/ibr/latest_leptonica_4/ara_tune/results/ara_checkpoint --traineddata /home/ibr/latest_leptonica_4/ara_tune/original_traineddata/ara.traineddata --stop_training_

now, summarize everything,
**i create LSTMFs
extract LSTM from "best_traineddata"
tune LSTM according LSTMFs , in the command " --traineddata  best_traineddata"
create LSTM from checkpoint,  in the command " --traineddata  best_traineddata"
unpack  "best_traineddata"
replace LSTM with the new tuned one
combine everything**

> If you combine your fine-tune lstm with existing traineddata, the files
will not be in sync
means in combination step i have to combine the new LSTM with the traineddata that is created when creating LSTMFs? 
i used "best_traineddata" in the command
_training/lstmtraining --model_output /home/ubuntu/lep_latest/ara_tune/tune_result/ara_tune 
--continue_from /home/ubuntu/lep_latest/ara_tune/extracted/ara.lstm 
--traineddata /home/ubuntu/lep_latest/ara_tune/original_traineddata/ara.traineddata 
--train_listfile /home/ubuntu/lep_latest/ara_tune/ara.training_files.txt 
--max_iterations 1200_
because if i pointed the --traineddata to the traineddata that is created with LSTMFs (starter traineddata)
i will get this message:
**Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 307 to 74!
Must supply the old traineddata for code conversion!
Failed to continue from: /home/ibr/latest_leptonica_4/ara_tune/extracted/ara.lstm
**
so since i got "Must supply the old traineddata" i used the trained data from "best_traineddata" the whole time, so what im missing?
Thanks

**Comment by Shreeshrii** [comment]
Read https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00

specially
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for--a-few-characters

Command has to be as follows:

training/lstmtraining --model_output /path/to/output [--max_image_MB 6000] \
  --continue_from /path/to/existing/model \
  --traineddata /path/to/traineddata/with/new/unicharset \
  --old_traineddata /path/to/existing/traineddata \
  [--perfect_sample_delay 0] [--debug_interval 0] \
  [--max_iterations 0] [--target_error_rate 0.01] \
  --train_listfile /path/to/list/of/filenames.txt


​Also see
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#combining-the-output-files

training/lstmtraining --stop_training \
  --continue_from ~/tesstutorial/eng_from_chi/base_checkpoint \
  --traineddata ~/tesstutorial/engtrain/eng/eng.traineddata \
​
 --model_output ~/tesstutorial/eng_from_chi/eng.traineddata​​





ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by ibr123** [comment]
the last two command actually worked and the traineddata i created is fine, i changed the first command to:
_training/lstmtraining --model_output /home/ubuntu/lep_latest/test/tuning_results/jpn \
  --continue_from /home/ubuntu/lep_latest/jpn_tune/extracted/jpn.lstm \
  --traineddata /home/ubuntu/lep_latest/jpn_tune/jpn_lstmf/jpn/jpn.traineddata \
  --old_traineddata /home/ubuntu/lep_latest/jpn_tune/original_traineddata/jpn.traineddata \
  --train_listfile /home/ubuntu/lep_latest/jpn_tune/jpn.training_files.txt \
  --max_iterations 3600_
but this command was in "Fine Tuning for ± a few characters" section, in my case i want only to train the best_traineddata to a new fonts only without changing it so i assumed that i needed to go though fine tuning but it didn't work, so does this tuning command covers it? 

also another question, when i run the above command sometime i get the message **checkpoint failed to write checkpoint**  when that message shows following command fails:
_training/lstmtraining --stop_training \
  --continue_from /home/ubuntu/lep_latest/test/tuning_results/jpn13.689_2618.checkpoint \
  --traineddata /home/ubuntu/lep_latest/jpn_tune/jpn_lstmf/jpn/jpn.traineddata \
  --model_output /home/ubuntu/lep_latest/test/traineddata/jpn.traineddata_
what causing this message to show?

Thanks

**Comment by Shreeshrii** [comment]
If your unicharset size is different, you need to provide --old_traineddata
.

failed to write checkpoint usually happens if you have not created the
output directory.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
