### ISSUE TITLE
Tesseract crashes when processing certain documents

### ISSUE THREAD

**Issue by TerryZH** [tesseract-ocr/tesseract#1181]
### Environment

* **Tesseract Version**: 
Tesseract Open Source OCR Engine v4.00.00dev-692-gad5ee184 with Leptonica

* **Platform**: 
Platform: Linux 4.9.43-17.39.amzn1.x86_64 #1 SMP x86_64 GNU/Linux

### Current Behavior:

The following command will crash in the above stated environment:
tesseract /tmp/tr_tmp.jpg /tmp/tr_tmp --tessdata-dir /var/task/tessdata --psm 12 --oem 2 -l eng hocr

tessdata is legacy data from tesseract-ocr/tessdata

Crash error: Assert failed:in file ../ccutil/unicharset.h, line 513

related jpg file: 
![c767234e7e51a92ee5a9c211f5892ad66b990e75-2](https://user-images.githubusercontent.com/399202/31865534-f08d1728-b73d-11e7-91b1-a31002dd1061.jpg)

related binaries:
[Archive.zip](https://github.com/tesseract-ocr/tesseract/files/1405268/Archive.zip)

### Expected Behavior:

When tesseract v4 using `--oem 2` and legacy trained data, error message of missing LSTM data should be printed instead of crashing.

### Suggested Fix:

n/a

**Comment by Shreeshrii** [comment]
The latest traineddatas (tessdata_best and Tessdata_fast) no not support legacy engine, so --oem 0 and --oem 2 are not supported.

However, program should not crash but rather give an error message.

**Comment by TerryZH** [comment]
Thanks for the update. Where can I get the 'latest traineddata' please? I got my data from https://github.com/tesseract-ocr/tessdata/

**Comment by Shreeshrii** [comment]
Please see
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400-september-15-2017

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by TerryZH** [comment]
Thanks for your reply. Just to be rigid. I was using tessdata, which supports oem mode 2 according to the wiki.

**Comment by amitdo** [comment]
>The latest traineddatas (tessdata_best and Tessdata_fast) do not support legacy tesseract engine, so --oem 0 and --oem 2 are not supported.

Although I wrote something similar to the above remark, since commits [1] and [2]. --oem 0 -l osd works with 'fast' and 'best'. Not sure about --oem 2.

[1] https://github.com/tesseract-ocr/tessdata_best/commit/f1d12682c0f1afe61db892f4b2bfaa7909ad7a59  
[2] https://github.com/tesseract-ocr/tessdata_best/commit/f1d12682c0f1afe61db892f4b2bfaa7909ad7a59

**Comment by TerryZH** [comment]
Since the discussion is a bit side-tracked, I'm repeating the problem. The original comment is also updated.

Tesseract v4.00.00dev-692-gad5ee184 crashes when using `--oem 2` and `tesseract-ocr/tessdata`.

**Comment by PaniniGelato** [comment]
The master branch (commit ad5ee18415bf59b9f5d1fd1806cb3aad3f18f381) runs good with your image @TerryZH 

However, tesseract should not crash

**Comment by TerryZH** [comment]
@PaniniGelato Are you sure? As reported in the "Environment" section, this crash happens on the build from master commit ad5ee18. And I can still reproduce the crash.

**Comment by zdenop** [comment]
It does not crash on windows (the latest code):
```
>tesseract.exe i1181.jpg i1181 --psm 12 --oem 2 -l eng hocr
Tesseract Open Source OCR Engine v4.0.0-beta.4 with Leptonica
```
I will try to test it on linux later. In meantime please check if you are using the latest traineddata...

**Comment by stweil** [comment]
This is the well known assertion `ASSERT_HOST(contains_unichar_id(unichar_id));` which occurs with certain images, but only when using both legacy and LSTM OCR engine.

**Comment by zdenop** [comment]
duplicate to #1205.
Anyway it should be fixed with https://github.com/tesseract-ocr/tesseract/commit/9efedc15b2c4f9ecc46dbe1d33bb22015b2d9c21.
