### ISSUE TITLE
 jTessBoxEditorFX2.0 generate tess4.0 box file

### ISSUE THREAD

**Issue by IT-Glory** [tesseract-ocr/tesseract#1184]
1、Are jTessBoxEditorFX2.0 can generate tess4.0 box and tif file?

**Comment by amitdo** [comment]
CC: @nguyenq

**Comment by nguyenq** [comment]
I believe they can be used for training once you mark EOL the box file to make it compatible for Tesseract 4.0. @Shreeshrii can give testimony on this feature. Use the non-FX version, jTessBoxEditor, if you don't have glyph-rendering issues with your text.
