### ISSUE TITLE
Running Multiple Programs with Tesseract

### ISSUE THREAD

**Issue by ryan-cahill** [tesseract-ocr/tesseract#1186]
### Environment

Version: 4.00.00alpha
Commit Hash: ad5ee18415bf59b9f5d1fd1806cb3aad3f18f381
Platform: Linux ryan-VirtualBox 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 GNU/Linux

### Current Behavior:
Running four programs that use the `TessBaseAPI` class will cause some of them to lock up indefinitely and never finish processing. There will also be a number of cores running at 100% indefinitely, where the number of cores is equal to the amount of locked processes. This is using the alpha release with the `TessBaseAPI` initialized with the parameter `OEM_LSTM_ONLY`. The environment variable `OMP_THREAD_LIMIT=1` was also used, but doesn't seem to stop this issue from happening.

### Expected Behavior:
That any number of programs using the TessBaseAPI object should be able to run simultaneously without locking up some of the processes and cores indefinitely.

### Suggested Fix:
I don't actually know enough about the codebase itself to to suggest a fix, but would be interested in more information or a workaround.

**Comment by alexis-gruet** [comment]
There might be a workaround but this crap. Supposing your are using the capi, you can set a timeout for the ProcessPage. 

```c
if (!TessBaseAPIProcessPage( api, image, 0, "", NULL, 2000, renderer)) {
            std::cout << "Error during processing" << std::endl;
}
```

if after 2000ms the api is not able to process the page, it will skip the processing. So no processing... 
I'm trying to figure out if by setting OMP_THREAD_LIMIT=1 in the shell could help really when relying on the capi/c++ api

**Comment by Shreeshrii** [comment]
@ryan-cahill  Please test with the latest code and report if you are still facing this isuue.

**Comment by amitdo** [comment]
This a known issue.

The solution is to turn off OpemMP at compile time with `--disable-oppenmp` (autotools build) or at run-time with `OMP_THREAD_LIMIT=1 tesseract....`
