### ISSUE TITLE
Cannot compile tesseract in vs2015

### ISSUE THREAD

**Issue by Juddd** [tesseract-ocr/tesseract#1187]
### Environment

* **Tesseract Version**:3.05 

* **Platform**: windows 10

### Current Behavior:
I can compile it successfully in my this computer yesterday by such command
```
cppan
mkdir build && cd build
cmake ..
```
But after I reinstall the system today, it will give me such error information

> LINK : fatal error LNK1104: cannot open file “Debug\unicharset training.lib

But I cannot search any information about it. Can anybody can tell me something?

**Comment by zdenop** [comment]
...and it describe clearly there is no issue in tesseract but in your computer setting. Use tesseract forum as described in issue tracker instruction.
