### ISSUE TITLE
Makebox not working on a self created eng.traineddata

### ISSUE THREAD

**Issue by ErnstTmp** [tesseract-ocr/tesseract#1188]
Hello,
with the help from @Shreeshrii  I could create box-files for improving the existing eng.traineddata for my purpose.

I could use these box files to create a new eng.traineddata. It works and is much better for reading my text. However, when I want to use this new eng.traineddata to create box files for new images, it fails with

read_params_file: Can't open makebox

If I leave everything else identical, but switch to the original eng.traineddata, everything works, and the boxes are created.

New Traineddata:
Version string:4.00.00alpha:eng:synth20170629:[1,36,0,1Ct3,3,16Mp3,3Lfys64Lfx96Lrx96Lfx512O1c1]
17:lstm:size=11689099, offset=192
18:lstm-punc-dawg:size=4322, offset=11689291
19:lstm-word-dawg:size=3694794, offset=11693613
20:lstm-number-dawg:size=4738, offset=15388407
21:lstm-unicharset:size=6360, offset=15393145
22:lstm-recoder:size=1012, offset=15399505
23:version:size=80, offset=15400517

Original Traineedata
Version string:4.00.00alpha:eng:synth20170629:[1,36,0,1Ct3,3,16Mp3,3Lfys64Lfx96Lrx96Lfx512O1c1]
17:lstm:size=11689099, offset=192
18:lstm-punc-dawg:size=4322, offset=11689291
19:lstm-word-dawg:size=3694794, offset=11693613
20:lstm-number-dawg:size=4738, offset=15388407
21:lstm-unicharset:size=6360, offset=15393145
22:lstm-recoder:size=1012, offset=15399505
23:version:size=80, offset=15400517

What did I do wrong?

Do you need more info? The script to create the boxes (thaks to @Shreeshrii !) is attached.

Thanks & kind regards
Ernst
Thanks

**Comment by ErnstTmp** [comment]
[makebox.txt](https://github.com/tesseract-ocr/tesseract/files/1420017/makebox.txt)
Script to make the boxes attached

**Comment by Shreeshrii** [comment]
read_params_file: Can't open makebox

Your tessdata-dir does not have the config file 'majebox'. Please check.

**Comment by ErnstTmp** [comment]
@Shreeshrii  Thank you very much for the fast help, that was the problem!
Kind regards
Ernst
