### ISSUE TITLE
missing namespace specifier for string in unichar.h

### ISSUE THREAD

**Issue by anubhavrohatgi** [tesseract-ocr/tesseract#1189]
### Linux - Ubuntu 16.04 LTS Environment

* **Tesseract Version 4.0.0 : 

### Current Behavior:
Any program using tess does not compile and throws an error where it says 'string' was not declared in this scope. 

### Expected Behavior:

Should compile smoothly.

### Suggested Fix:

In unichar.h file 
at line no : 164 
               static string UTF32ToUTF8(const std::vector<char32>& str32);

should be changed to 
              static std::string UTF32ToUTF8(const std::vector<char32>& str32);

Add prefix namespace resolution to string.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues?q=std+string+is%3Aclosed
