### ISSUE TITLE
Inverted Image Colors

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#1194]
Hi,

i have a document in Arabic language, i tried that image against Tesseract version: 4.00.00dev-692-gad5ee18 and the model was ara.traineddata from [tessdata_best](https://github.com/tesseract-ocr/tessdata_best) using the command: **tesseract ara_image out -l ara --tessdata-dir ./tessdata/ara_best/ --oem 1**  
the detection for normal image was good, and the image was kind of a formal article, but when i converted the images color so the black is white and vice versa, some parts of the text was missing, another thing which is when i set the variable `tessedit_write_images` to true, the output image for both images, "normal colors and inverted colors" was the same

**the original image:**
**IMAGE**
![longimage](https://user-images.githubusercontent.com/26926171/32227677-b4e00e92-be54-11e7-8be1-40935c745de2.jpg)

**OUTPUT IMAGE IS**
![tessinput](https://user-images.githubusercontent.com/26926171/32227939-63b262b2-be55-11e7-9843-3f5b934826ef.jpg)

**DETECTION TEXT WAS**
[out.txt](https://github.com/tesseract-ocr/tesseract/files/1430960/out.txt)

**inverted colors image**
**IMAGE**

![inverted2](https://user-images.githubusercontent.com/26926171/32227994-9192692a-be55-11e7-8143-7fa8f7452468.jpg)

**OUTPUT IMAGE IS**
![tessinput2](https://user-images.githubusercontent.com/26926171/32228007-9b0cee30-be55-11e7-922d-8abedf7d251b.jpg)

**DETECTION TEXT WAS**
[out2.txt](https://github.com/tesseract-ocr/tesseract/files/1430965/out2.txt)

so what am i missing?

Thanks

**Comment by ahmed-tea** [comment]
@ibr123 
لمؤخذة ايه اللغة الجزائرية و اللغة المصرية
انا اعرف ان لغة الجزائر و مصر هى اللغة العربية

**Comment by ibr123** [comment]
@ahmed-tea اللغة عربية للبلدين, المقصود يمكن اللهجة
على كل حال المقال للتجرية فقط ماخوذ من ويكيبيديا

**Comment by ahmed-tea** [comment]
Try with --psm 6

**Comment by ibr123** [comment]
@ahmed-tea already tried, but same results, parts of the original text is missing

**Comment by ibr123** [comment]
problem was solved at the version `4.0.0-beta.1-21-gbdf6629` with `leptonica-1.75.3`
