### ISSUE TITLE
"pix_malloc fail for data"

### ISSUE THREAD

**Issue by mbgalloway** [tesseract-ocr/tesseract#1196]
I am attempting to run this:

```
lapply(myfiles, function(i){

    shell(shQuote(paste0("pdftopng -f 1 -l 10 -r 600 ", i, " ocrbook")))
mypngs <- list.files(path = dest, pattern = "png", full.names = TRUE)
lapply(mypngs, function(z){
    shell(shQuote(paste0("tesseract ", z, " out")))
    #file.remove(paste0(z))
    })
})
```

However, even though I am feeding it a PNG file, I get the error
```
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Error in pixCreateNoInit: pix_malloc fail for data
Error in pixCreate: pixd not made
Error in pixReadStreamPng: pix not made
Error in pixReadStream: png: no pix returned
Error in pixRead: pix not read
Error during processing.
```
```
1: running command 'C:\Windows\system32\cmd.exe /c "tesseract C:\users\gallowmb\desktop/ocrbook-000001.png out"' had status 1 
2: In shell(shQuote(paste0("tesseract ", z, " out"))) :
  '"tesseract C:\users\gallowmb\desktop/ocrbook-000001.png out"' execution failed with error code 1
```

phototest works.  There seems to be an issue with the file itself.  What is the issue?

RStudio 1.1.383
Tesseract 3.05.01
Win 7 64 bit

**Comment by zdenop** [comment]
please post output of
tesseract -v

Dňa 3. 11. 2017 22:44 používateľ "Mitchell Galloway" <
notifications@github.com> napísal:

**Comment by mbgalloway** [comment]
zdenop, here is the output of tesseract -v in CMD.

`tesseract 3.05.01
  leptonica-1.74.1
   lipgif 4.1.6(?)  :  libjpeg 8d (libjpeg-turbo 1.5.0)  :  libpng 1.6.20  :  libtiff 4.0.6  :  zlib 1.2.8  :  libwebp 0.4.3  :  libopenjp2 2.1.0`

**Comment by zdenop** [comment]
Can you share ocrbook-000001.png and info how to get/installed tesseract?

**Comment by mbgalloway** [comment]
Hi, I found what the problem was after using an example scanned PDF from the internet.  The DPI was too high for the PDFtoPNG conversion.  I took it down to 150 and it worked like a charm.  It seems there is a DPI limit for Tesseract.  

So I went from this:
` shell(shQuote(paste0("pdftopng -f 1 -l 10 -r 600 ", i, " ocrbook")))`

To this:
` shell(shQuote(paste0("pdftopng -f 1 -l 10 -r 150 ", i, " ocrbook")))`

**Comment by mbgalloway** [comment]
I also updated my script to have a more dynamic name, so no overwriting because of static naming.

```

dest <- "C:\\users\\yourname\\desktop"

      files <- tools::file_path_sans_ext(list.files(path = dest, pattern = "pdf", full.names = TRUE))
        lapply(files, function(i){
          shell(shQuote(paste0("pdftoppm -f 1 -l 10 -r 150 ", i,".pdf", " ",i)))
          })
      
      
      myppms <- tools::file_path_sans_ext(list.files(path = dest, pattern = "ppm", full.names = TRUE))
        lapply(myppms, function(y){
          shell(shQuote(paste0("magick ", y,".ppm"," ",y,".tif")))
          file.remove(paste0(y,".ppm"))
          })
  
      mytiffs <- tools::file_path_sans_ext(list.files(path = dest, pattern = "tif", full.names = TRUE))
        lapply(mytiffs, function(z){
          shell(shQuote(paste0("tesseract ", z,".tif", " ",z)))
          file.remove(paste0(z,".tif"))
          })

```

**Comment by mbgalloway** [comment]
In addition to the above, make sure image magick has a specified DPM.  So for the Image Magick part of the script, the options need to include "-density 300" or something of that nature.

Like such (along with a multitude of other options)
```
      myppms <- tools::file_path_sans_ext(list.files(path = dest, pattern = "ppm", full.names = TRUE))
        lapply(myppms, function(y){
          shell(shQuote(paste0("magick -colorspace gray ", y,".ppm","  -density 300 -depth 8 -flatten -auto-orient -auto-level -rotate -90^> +dither -colors 2 -normalize"," ",y,".tif")))
          file.remove(paste0(y,".ppm"))
          })
```
