### ISSUE TITLE
Compiling c++ 

### ISSUE THREAD

**Issue by KarimTarabishy** [tesseract-ocr/tesseract#1197]
I have a c++ code using tesseract api, all the functions link well but a single function doesn't:

` undefined reference to `tesseract::TessBaseAPI::SetImage(Pix*)'`

the code uses other tesseract base api functions like `getUTF8text` and linker doesn't complain.

**Comment by nam-leduc** [comment]
Hi @KarimTarabishy , can you produce some information like:
1. Tesseract version (commit hash)
2. Operating system 
3. GCC configuration for building your c++ code

Best regards,
Le Duc. Nam

**Comment by amitdo** [comment]
Please move this question to our [forum](https://groups.google.com/d/forum/tesseract-ocr) if you still have this issue.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
