### ISSUE TITLE
build from Github base on Fedora 26 failed

### ISSUE THREAD

**Issue by fangqiao** [tesseract-ocr/tesseract#1199]
I am trying to build the latest from git on Fedora 26, 4.13.10-200.fc26.x86_64.

While run ./configure, following error was reported:

./configure: line 4243: syntax error near unexpected token `-mavx,'
./configure: line 4243: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'

**Comment by zdenop** [comment]
Please use google or other search engine before posting issues.

**Comment by amitdo** [comment]
You can also use the search options in GitHub.

https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+AX_CHECK_COMPILE_FLAG+is%3Aclosed
