### ISSUE TITLE
Setrectangle while using pdfrenderer not possible

### ISSUE THREAD

**Issue by ArjanSchouten** [tesseract-ocr/tesseract#120]
If you look at the [```processpage```](https://github.com/tesseract-ocr/tesseract/blob/master/api/baseapi.cpp#L1199) method you can see that's it's not possible to set a subrectangle while using the pdfrenderer. Is there still a way to set the rectangles if you use the method ```processpage```? 

If there is no way, how can we create such functionality?

**Comment by peirick** [comment]
What is your usecase for such a functionality? Maybe just cropping the pix before calling the method helps?

**Comment by ArjanSchouten** [comment]
I've a lot of large pdf documents to process. Since tesseract is only using one cpu I decided to let the other cpu pre process the documents. By doing that I can create rectangles with interesting sections.

**Comment by ArjanSchouten** [comment]
@peirick after some time I understand you're comment better. Because of the method name and the comment above it I thought that I can set a few rectangles on an image before Tesseract will process that image. Therefore my main issue is that it's not possible to restrict a few subrectangles before calling a recognize method on the base api. Cropping is not an option for me because I wan't to use the PdfRenderer.

**Comment by peirick** [comment]
The PdfRender outputs PDF. To realize what you are planning, you should put the interesting section into a pix, let tesseract do the OCR, and then you have to post process combine all the results into one PDF. That is a bin project if performance is just your concern.

**Comment by ArjanSchouten** [comment]
Yes I'm going to do that. But to me it sounds easier to just use the setrectangle. Turns out I wasn't understanding exactly what setrectangle is doing.
