### ISSUE TITLE
Table Detection In tesseract 4.0 alpha..

### ISSUE THREAD

**Issue by Chandrahar** [tesseract-ocr/tesseract#1202]
getting table capture....... in excel....
input like.....
can anyone tell me how get table data each cell seperately.....
![1](https://user-images.githubusercontent.com/32842699/32480565-74a9438c-c3b5-11e7-96df-57c6a81c7d17.jpg)

**Comment by zdenop** [comment]
Please respect instruction for posting issue: use tesseract user forum for asking support.

**Comment by Chandrahar** [comment]
i am got getting ...
i am getting result.... like this....
110 - पैठण विधानसभा मतदार संघ

प्रारूप मतदार यादी 2017
राज्य - (एस 13) महाराष्ट्र

यादी भाग क्रमांक : 2

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

1 नायगव्हाण/हनुमंतगांव/खंडेवाडी
ता. पैठण जि. औरंगाबाद पिनकोड 431105
11 1ॐ0870659 2] 1ॐ0870758 31 7\×4202057
मतदाराचे पुर्ण : महाजन कोंडीराम मतदाराचे पुर्ण : महाजन श्रीमतं मतदाराचे पुर्ण : महाजन अशोक
नांव मोहन नांव कोंडीराम नांव भानुदास
वडीलांचे नांव : महाजन मोहन Photo वडीलांचे नांव : महाजन कोंडीराम Photo वडीलांचे नांव : महाजन भानुदास Photo
घरक्रमांक ; 1 ४990 |) घरक्रमांक : 1 Available || RT : 3 Available
वय: 78 लिंग ` पुरुष वय: 35 लिंग ` पुरुष वय: 29१ लिंग ` पुरुष
41 1ॐ30873273 5] 6४1
मतदाराचे पुर्ण : महाजन नाथा मतदाराचे पुर्ण : महाजन कचराबाई मतदाराचे पुर्ण : महाजन सुनिता नाथा
नांव कोंडीराम नांव नाथा नांव
वडीलांचे नांव : महाजन कोंडीराम Photo पतीचे नांव : महाजन नाथा Photo पतीचे नांव : महाजन नाथा Photo
घर क्रमांक :? Available || RT | : 2 Available || RT | : 2 Available
वय: 5 लिंग ` पुरुष वय: 52२ for ‘@t वय: 48 लिंग ‘@t
7] 7\×4202008 ४1 JSFO870626 9|
मतदाराचे पुर्ण : देसाई रमेश हरीभाउ मतदाराचे पुर्ण : महाजन भानुदास मतदाराचे पुर्ण : महाजन कडूबाई
नांव नांव कोंडीराम नांव भानुदास
वडीलांचे नांव : देसाई हरीभाउ Photo वडीलांचे नांव : महाजन कोंडीराम Photo पतीचे नांव : महाजन भानुदास Photo
घरक्रमांक : 3 Available || RT : 3 Available || RT : 3 Available
वय: 52२ लिंग ` पुरुष वय: 5 लिंग ` पुरुष वय: 4१ लिंग ‘@t
101 7\%6412993 111 7\%4201976 12] 7\%6045025
मतदाराचे पुर्ण : देसाई राणी नानासाहेब मतदाराचे पुर्ण : देसाई छाया बद्रीनाथ मतदाराचे पुर्ण : देसाई संगीता
नांव नांव नांव बाबासाहेब
वडीलांचे नांव : देसाई नानासाहेब Photo पतीचे नांव : देसाई बद्रीनाथ Photo पतीचे नांव : देसाई बाबासाहेब Photo
घर क्रमांक : ०३ Available || RT | : 4 Available || | : ox Available
वय: 20 लिंग : स्त्री वय: 30 लिंग ‘@t वय: 30 लिंग ‘@t
13] 7\%6412977 14] 7\%6412985 15]
मुतदाराचे पुर्ण : देसाई कल्याणी योगेश मुतदाराचे पुर्ण : देसाई रेणुका सतीश मतदाराचे पुर्ण : महाजन धोंडीराम
पतीचे नांब : देसाई योगेश Photo पतीचे नांव : देसाई सतीश Photo वडीलांचे नांव : महाजन मोहन Photo
घर क्रमांक : ०४ ४990 |) घरक्रमांक : ०४ Available || RT : 5 Available
वय: 23 लिंग ` स्त्री वय: 21 लिंग ` स्त्री वय: 70 लिंग ` पुरुष
161 — JSFO871137 17] 7\%0530014 18] 7\%4201950
पुर्ण - 7 पुर्ण - T पुर्ण -
पतीचे नांव : महाजन धोंडीराम Photo वडीलांचे नांव : महाजन धोंडीराम Photo वडीलांचे नांव : महाजन धोंडीराम Photo
घरक्रमांक : 5 ४190 |) घरक्रमांक ;: Available || RT | : 5 Available
वय: ५4५ लिंग ` स्त्री वय: 35 लिंग ` पुरुष वय: 3२ लिंग ` पुरुष
191 7\%4201968 201 27%6413017 211 2736413090
मुतदाराचे पुर्ण : मुह्युलन गोरखनाथ मतदाराचे पुर्ण : देसाई स्वाती गणेश मतदाराचे पुर्ण : महाजन संतोष संजय
नाव नाव नाव
वडीलांचे नांव : महाजन धोंडीराम Photo पतीचे नांव : देसाई गणेश Photo वडीलांचे नांव : महाजन संजय Photo
घरक्रमांक : 5 Available || RFT® | : on Available || RFT® | : on Available
वय: 31 लिंग ` पुरुष वय: 25 लिंग ` स्त्री वय: 2० लिंग ` पुरुष
221 23| — JSFO872622 241 — ZYX0530022
your ur . mem g मुतदाराचे पुर्ण : महाजन कडूबाई खंडू मतदाराचे पुर्ण : महाजन कचरू खंडू
वडीलांचे नांव : महाजन मोहन Photo पतीचे नांव : महाजन खंडू Photo वडीलांचे नांव : महाजन खंडू Photo
: 6 Available || RT _ : 6 Available || RT _ : 6 Available
वय: 6५6 लिंग ` पुरुष वय: 55 fr ‘@t वय: 33३ लिंग ` पुरुष
251 — ZYX0530204 2681 — JSFO871665 27| — JSFO871178
मतदाराचे पुर्ण : महाजन कैलास खंडू मतदाराचे पुर्ण : गाढेकर भावराव लिंबा मतदाराचे पुर्ण : गाढेकर केसरबाई
नांव नांव नांव भावराव
वडीलांचे नांव : महाजन खंडू Photo वडीलांचे नांव : गाढेकर लिंबा Photo पतीचे नांव : गाढेकर भावराव Photo
: 6 Available || RT _ : 6 Available || RT _ : 6 Available
वय: 30० लिंग ` पुरुष वय: 6१ लिंग ` पुरुष वय: 6० fr ‘@t
281 — ZYX0499103 29 — ZYX6412928 30| — JSFO907899
yh ; men प्रभु भाउराव मुतृदाराचे पुर्ण : महाजन वैशाली कैलाश मतृदाराचे पुर्ण : लिबोरे सुभद्रबाई नंदू
वडीलांचे नांव : गाडेकर भाउराव Photo पतीचे नांव : महाजन कैलाश Photo पतीचे नांव : लिबोरे नंदू Photo
: 6 Available || RT | : ०६ Available || RTs | : 7 Available
ans os लिंग ` पुरुष वय: 26 लिंग : स्त्री वय: 44 लिंग ‘@t
01/01/2017 रोजी < aa ran नौयणी अधिकारी याच्या गरे पृष्ठ क्रमांक : 3

 
I want output like.................................................
![dddd](https://user-images.githubusercontent.com/32842699/32481144-12195efc-c3b8-11e7-92bb-fe5ba644ba00.jpg)
