### ISSUE TITLE
GetUTF8Text() return in Arabic

### ISSUE THREAD

**Issue by ahmed-tea** [tesseract-ocr/tesseract#1203]
### Environment

* **Tesseract Version**: Current main repository (4.00.00alpha)
* **Platform**: Windows7 32-bit

### Current Behavior:
**GetUTF8Text();** return in Arabic(ara) invalid characters

ط¬ظ…ط¹ظٹط§طھ ظپط§ظ†ط¶ ط§ظ„ط·ط¹ط§ظ… ظپظٹ ط§ظ„ظ…ط²ط§ط­ظ…ظٹط© ظˆط§ظ„ظ‚ظˆظٹط¹ظٹط© ظˆظ…ط§ط¬ط§ظˆط±ظ‡ط§
7-9 ظ„ظ„ط´ظƒظ„
ظ†ط³طھظ‚ط¨ظ„ ط§ظ„ظپط§ظ†ط¶ ظ…ظ† ط§ظ„ط·ط¹ط§ظ… ظپظ‚ط· ط§طھطµظ„ ط¨ظ†ط§ ظˆظ†ط­ظ† ظ†ط£طھظٹ ط§ظ„ظٹظƒ ط¨ط³ظٹط§ط±ط§طھظ†ط§ ظˆط¹ظ…ط§ظ„ظ†ط§ ظˆظ†ط£ط®ط°
ظپط§ظ†ط¶ ط§ظ„ط·ط¹ط§ظ… ظ„ط¯ظٹظƒ ظˆظ†ط¹ط·ظٹظ‡ ظ„ظ„ظ…ط­طھط§ط¬ظٹظ† ظˆط§ظ„ظپظ‚ط±ط§ط، ظˆط£ظ†طھ ظ…ط±طھط§ط­ ظ…ط§ط¬ظˆط±
3 ظ‡ظ†طھظٹ:
ظ†ظƒ ط§ط´ظƒ ط´ظپظ‰
ط·ط±ظٹظ‚ ظ…ظƒط© ظ…ط®ط±ط¬ / ظ…ظ‚ط§ط¨ظ„ ظ…ط±ظƒط² ط¬ظˆ
ظ€
ط§ظ„ظ‚ظˆظٹط¹ظٹط© ط­ظٹ ط§ظ„ط¨ط³ط§طھظٹظ† ط¨ط¬ظˆط§ط± ط§ط¯ط§ط±ط© ط§ظ„طھط¹ظ„ظٹظ… ط¨ظ…ظ†ط·ظ‚ط© ط§ظ„ط¹ط±ط¶
ط«ط§ط¨طھ طں ظ‡ + طں51طں ط§ + ط«ط§ط¨طھ 5%ظ‡ظ‡ظ‡ظ‡طں1ط§ .
ط¬ظˆط§ظ„ ++*1**/0ظ‡ظ‡. ط¬ظˆط§ظ„ 5.749.
ط¬ظ…ط¹ظٹط© ط§ظ„ط¨ط± ط§ظ„ط®ظٹط±ظٹط© ط¨ط§ظ„ظپظˆظٹظ„ظ‚ ظ…ط­ط§ظپط¸ط© ط§ظ„ظ‚ظˆظٹط¹ظٹ
11*ط©ط§ظ„ط§ظ„ظ„ط،ط© .
ط¬ظ…ط¹ط© ط§ظ„ط¨ط± ط¨ط§ظ„ط±ظˆظٹط·
ط«ط§ط¨طھ 881***%ط§ . ط¬ظˆط§ظ„ 41 ظ‡ظ‡,
ط­ 00-01
ط«ط§ط¨طھ 1154151 . ط¬ظˆط§ظ„ طںطں ط§ظ‡}1%.ظ‡.
17
ط«ط§ط¨طھ + 41+ طں ظ‡ط§ . ط¬ظˆط§ظ„ ط§ظ‡
ط¬ظ…ط¹ظٹط© ط§ظ„ط¨ط± ط§ظ„ط®ظٹط±ظٹط© ط¨ظپظٹط¶ط© ط§ظ„ط³ط±
ط«ط§ط¨طھ 44+ + طںطںطں ط§ + ط¬ظˆط§ظ„ 581150511,
ط®ظٹ ط£ط·ط¨ط¹ ظ‡ط°ظ‡ ط§ظ„ظˆط±ظ‚ط© ظˆظ†ط´ط±ظ‡ط§ ظˆظˆط²ط¹ظ‡ط§ ط¹ظ„ظ‰ ط§ط§ظ„ط³طھط±ط§ط­ط§طھ ظˆظ‚طµظˆط± ط§ط£ظ„ظپط±ط§ط­ ظˆط§ظ„ظ…ط·ط§ط¨ط® ظˆط£ظ…ط§ظƒظ† ط§ظ„ظˆط§ظ„
ط£ط¨ط´ط± ط¨ط®ظٹط±ظٹ ط§ظ„ط¯ظ†ظٹط§ ظˆط§ط¢ظ„ط®ط±ط© ظˆظ„ظƒ ظ…ط«ظ„ ط£ط¬ظˆط±ظ‡ظ… ط¨ط¥ط°ظ† ط§ظ‡ظ„ظ„ ظپط§ظ„ط¯ط§ظ„ ط¹ظ„ظ‰ ط§ظ„ط®ظٹط± ظƒظپط§ط¹ظ„آ»

### Expected Behavior:
return Arabic characters

**Comment by amitdo** [comment]
Which traineddata, Arabic or ara? Try both.

**Comment by hsen-dev** [comment]
@ahmed-tea can you please, share your code?
