### ISSUE TITLE
TIFF file: Warning. Invalid resolution 0 dpi. Using 70 instead.

### ISSUE THREAD

**Issue by clarkk** [tesseract-ocr/tesseract#1204]
When sending a TIFF file through tesseract I get this error

```
Warning. Invalid resolution 0 dpi. Using 70 instead.
```

TIFF
https://i.imgur.com/uwXa8gK.png

**Comment by clarkk** [comment]
Tesseract 3.0.5

**Comment by stweil** [comment]
Please read https://github.com/tesseract-ocr/tesseract/wiki#support.

**Comment by guglie** [comment]
Maybe these are useful resources:

https://github.com/tesseract-ocr/tesseract/issues/649
https://groups.google.com/forum/#!forum/tesseract-ocr

By the way, if you're using imagemagick's `convert` to prepare your images, be sure to set the `-units PixelsPerInch` option together with `-density [your-density]` to set correctly the dpi metadata.
