### ISSUE TITLE
No recent Windows installer download appears on google drive

### ISSUE THREAD

**Issue by brianbv** [tesseract-ocr/tesseract#121]
https://drive.google.com/folderview?id=0B7l10Bj_LprhQnpSRkpGMGV2eE0&usp

There is an installer on the old Google code page from 2012.

**Comment by zdenop** [comment]
Project move to github, so there is no reason to use google drive

**Comment by brianbv** [comment]
Does this mean that the compiled installer will be added to the Github project, or the  links will be updated/removed to reflect that there is no longer a Windows installer provided?  It is mentioned in the README.MD file, as well as the Wiki pages:

https://github.com/tesseract-ocr/tesseract/wiki
https://github.com/tesseract-ocr/tesseract/wiki/Downloads

**Comment by zdenop** [comment]
Yes, when somebody provide installer for windows it will be publish on Github projekt page. Previous installer/downloads are at original location.
