### ISSUE TITLE
Plate Detection Failing

### ISSUE THREAD

**Issue by mmderakhshani** [tesseract-ocr/tesseract#1214]
Hi,
I have installed tesseract version 4 (LSTM-based OCR) and Leptonika-1.74.4 on my ubuntu 16.04. I have decided to detect the character on a license plate. 

![plak](https://user-images.githubusercontent.com/16706043/33034100-f9dddece-ce3b-11e7-851d-679949b43539.jpeg)

I have run bellow command:

`tesseract plak.jpeg output --oem 1 -l fas`

But the output is not appropriate.
```
٤ ت
ات

 

 

۵٣ 6۱

 

 

```

Just some characters without any logic. Could you please help me how I can get a better result for this license. Another thing which I would like to mention is that the license is related to (Farsi/Persian) language.

Best,
Mohammad

**Comment by roozgar** [comment]
​for this kind of detection you can train your own fonts
because license plate in iran have some limited characters ​...

**Comment by mohammad-py** [comment]
@roozgar, Thanks for your great response. Could you please give some more information?

**Comment by roozgar** [comment]
its better to ask this kind of question in google groups
because here a developer repository
how ever you need image processing to split the pelak in image and detect letter in each image...
