### ISSUE TITLE
Do we need to continue to support giflib before 5.1?

### ISSUE THREAD

**Issue by DanBloomberg** [tesseract-ocr/tesseract#1215]
@amitdo 
@stweil 
@egorpugin 

I'd like to stop supporting old giflib versions, before 5.1 when the interface was last changed.
leptonica is currently supporting 4.1.6 and 5.0, as well as 5.1+.

Is this practical? What would be effect be on tesseract if giflib 5.1+ were required?

**Comment by egorpugin** [comment]
My vote is for dropping different versions.

**Comment by amitdo** [comment]
Hi Dan!

I think it's OK to move to 5.1 as the minimum version.

https://packages.debian.org/search?searchon=sourcenames&keywords=giflib
https://packages.ubuntu.com/search?searchon=sourcenames&keywords=giflib

Gif support is not very critical for OCR purpose.

Maybe you should target a new release for Ubuntu 18.04 LTS.

**Comment by DanBloomberg** [comment]
OK.  Will drop pre-5.1 giflib support.

And I expect to have a new leptonica release in Dec or Jan that Jeff will
debianize for 18.04.

**Comment by stweil** [comment]
CC'ing @jbreiden. `libgif4` (4.1.6) was last used in Debian's `oldstable`, so I see no problem in dropping support for that version. Support for 5.1 which is used by Debian `stable` is required of course.

**Comment by DanBloomberg** [comment]
libgif support in gifio.c cleaned up.
Old pre-5.1 distributions are no longer supported.
libgif 5.1 or later only (and not 5.1.2)

**Comment by ryandesign** [comment]
MacPorts uses giflib 4.2.3, because when giflib 5 was released, its API was different from giflib 4 and nothing supported the new API, so updating to giflib 5 would have broken everything that uses giflib. See [this MacPorts ticket](https://trac.macports.org/ticket/35817) for my investigations into that. Granted that was 5 years ago and maybe some projects have now added giflib 5 support. But I count 68 different ports in MacPorts that use giflib, and I don't know if all of those projects have added giflib 5 support, but my strong suspicion is that they have not, because some of them are probably not in development anymore.

All of which is to say that if you drop giflib 4 support, it will be a lot of work for me in MacPorts to probably create separate giflib 4 and 5 ports and then update and test those 68 ports.

**Comment by egorpugin** [comment]
Is it possible to have gif4 and gif5 simultaneously in macports?
E.g., create giflib5 and set it for leptonica only. Other packages will use it when they're ready.

**Comment by amitdo** [comment]
Homebrew has support for giflib 5.1.4.
https://github.com/Homebrew/homebrew-core/blob/master/Formula/giflib.rb

**Comment by DanBloomberg** [comment]
Ryan, I'm sorry to hear that.  I know what a pain it is when a basic library changes its interface. The gifilib interface changed at 5.0 and at 5.1.  If you look at leptonica gifio.c from 1.74.4, you'll see what I had to do to support 4.6.x and 5.0 and 5.1+.

Have another look, and if you still want me to revert, at least to give you more time to bring macports up to date, let me know and I will do so.

  -- Dan

**Comment by ryandesign** [comment]
Ah, I see you already committed the removal in https://github.com/DanBloomberg/leptonica/commit/64961e9ae9151f9c9e251de9fe7be0363e780fbd.

Maybe that will motivate me to finally deal with giflib 5 in MacPorts.

**Comment by DanBloomberg** [comment]
The offer still stands, if you need it.  I expect that version 1.75 will be released some time in January, to set your time frame.

**Comment by egorpugin** [comment]
Maybe you should drop it right after 1.75 release? So the change will be for 1.76 which is released after some another reasonable time.

**Comment by DanBloomberg** [comment]
Makes sense.  Ryan, I'll revert the gifio.c change for 1.75.

**Comment by DanBloomberg** [comment]
Reverted to support of giflib 4.1.6+

@ryandesign   please let me know when we're ready to use the new (improved) version, which uses no temp files on any platform.

**Comment by DanBloomberg** [comment]
@egorpugin 

travis is still using giflib 4.6, so it fails with the new gifio.c.  Can we get that changed to 5.1.3+

**Comment by DanBloomberg** [comment]
I need to make leptonica 1.75 for Ubuntu 18.04, which is a major release that they guarantee support for at least 4 years.

@ryandesign 
Can we switch to the new version of leptonica's gifio.c, which uses no temp files?  It requires 5.1+.

@egorpugin 
Can we upgrade travis to giflib 5.1.3+?   (or has it been done already?)

**Comment by stweil** [comment]
Travis still uses Ubuntu trusty with libgif-dev 4.1.6-11 (see https://packages.ubuntu.com/trusty/libgif-dev).

**Comment by egorpugin** [comment]
> Can we upgrade travis to giflib 5.1.3+?

Done now to 5.1.4.

**Comment by ryandesign** [comment]
> Can we switch to the new version of leptonica's gifio.c, which uses no temp files? It requires 5.1+.

It's as you wish. I haven't touched the giflib situation in MacPorts yet. We can delay updating to newer leptonica releases until we figure out what we want to do about giflib.

**Comment by DanBloomberg** [comment]
It's unfortunate that so much effort has been wasted on gif, which is only supported today because of an accident of history: it was available in the early days of the web and png came just a bit later.

The main problems with gif are:
(1) It is a poor and inflexible compression format, compared to png; e.g., it doesn't even support rgb.
(2) Implementations still in use don't even support file streams -- they use file descriptors!  Compare to webp, for example, which uses a very simple memory-based interface that is almost trivial to use.
(3) The gif implementors have changed the basic interface numerous times, making tons of extra work for everyone else.  Compare to png, tiff and jpeg, which have maintained backward compatibility for decades.

Interfacing to giflib has been a series of frustrations, and I consider the current gifio.c interface to be a mess. Thank you Ryan for giving me permission to clean this up a bit.

**Comment by amitdo** [comment]
https://github.com/DanBloomberg/leptonica/commit/fab8484cbbd091
https://github.com/DanBloomberg/leptonica/issues/301

This issue can be closed.
