### ISSUE TITLE
configure missing from release

### ISSUE THREAD

**Issue by tpolekhin** [tesseract-ocr/tesseract#1219]
Hello,

Releases 3.05.00 and 3.05.01 are missing `./configure` in release bundle
Im struggling to build tesseract for 3 days now

Also, release 3.05.01 is missing build fixes from 3.05 branch
Would be great if you could re-upload release bundles with them

Appreciated

**Comment by amitdo** [comment]
You're supposed to run ./autogen.sh as a first step, which will generate the configure script.

**Comment by ryandesign** [comment]
You (the developer) are supposed to do that, and generate a tarball from the result, and upload it to GitHub as a release download.

**Comment by zdenop** [comment]
There are [clear instructions](https://github.com/tesseract-ocr/tesseract/wiki/Compiling) how to build tesseract from source. If somebody decide to ignore them, it is hie/her problem and not tesseract project.

Using autogen.sh is common way how to start configuration on build process in many opensource projects.

**Comment by tpolekhin** [comment]
@amitdo yes, i understand, but for some reason i had to resolve a bunch of errors with autogen.sh, and finally ended up with
```
./configure: line 17577: syntax error near unexpected token `LEPTONICA,'
./configure: line 17577: `PKG_CHECK_MODULES(LEPTONICA, lept >= 1.74, have_lept=true, have_lept=false)'
```
even with `pkg-config` installed

i've successfully builded 3.04.01 witch seems to be the last release with bundled `./configure`

Any help appreciated

**Comment by amitdo** [comment]
If you installed pkg-config after you run autogen.sh, re-run autogen.sh.

**Comment by tpolekhin** [comment]
@amitdo i re-run autogen.sh a million times already... :(

**Comment by zdenop** [comment]
1. How did you installed leptonica?
2. Do you have more leptonica (e.g. from source and by system) installations?

**Comment by tpolekhin** [comment]
Leptonica is built from source:
https://github.com/DanBloomberg/leptonica/releases/download/1.74.4/leptonica-1.74.4.tar.gz
with:
```
./configure --prefix=$pkg_prefix
make
make install
```

Building tesseract from release tar 3.05.00 I'm getting:
```
...
checking for mbstate_t... yes
checking for leptonica... configure: error: leptonica not found
```

Building tesseract from git branch 3.05 I'm getting:
```
...
checking for mbstate_t... yes
./configure: line 17577: syntax error near unexpected token `LEPTONICA,'
./configure: line 17577: `PKG_CHECK_MODULES(LEPTONICA, lept >= 1.74, have_lept=true, have_lept=false)'
```

Build script is the same:
```
  libtoolize
  ./autogen.sh
  ./configure --enable-debug \
	  --prefix="${pkg_prefix}" \
	  --host=x86_64-pc-linux-gnu \
	  --with-extra-includes=$(pkg_path_for tpolekhin/leptonica)/include \
	  --with-extra-libraries=$(pkg_path_for tpolekhin/leptonica)/lib
  make
```

Also, `pkg-config --cflags lept` and `pkg-config --libs lept` gives:
```
-I/hab/pkgs/tpolekhin/leptonica/1.74.4/20171124113357/include/leptonica
-L/hab/pkgs/tpolekhin/leptonica/1.74.4/20171124113357/lib -llept
```

**Comment by tpolekhin** [comment]
Building from release tar 3.05.01 is the same:
```
./configure: line 17577: syntax error near unexpected token `LEPTONICA,'
./configure: line 17577: `PKG_CHECK_MODULES(LEPTONICA, lept >= 1.74, have_lept=true, have_lept=false)'
```

**Comment by tpolekhin** [comment]
Nothing if this helps also:
`LIBLEPT_HEADERSDIR=$(pkg_path_for tpolekhin/leptonica)/include`
`LIBLEPT_HEADERSDIR=$(pkg_path_for tpolekhin/leptonica)/include/leptonica`

**Comment by zdenop** [comment]
> syntax error near unexpected token `LEPTONICA,
this means that pkg-config is not aware about leptonica installation

**Comment by tpolekhin** [comment]
So this means nothing?
```
pkg-config --cflags lept
-I/hab/pkgs/tpolekhin/leptonica/1.74.4/20171124113357/include/leptonica
pkg-config --libs lept
-L/hab/pkgs/tpolekhin/leptonica/1.74.4/20171124113357/lib -llept

**Comment by tpolekhin** [comment]
I've found why i have v3.04.00 building normally
configure.ac in branch 3.04 is missing this:
`PKG_CHECK_MODULES([LEPTONICA], [lept >= 1.74], [have_lept=true], [have_lept=false])`
that is present in 3.05

**Comment by zdenop** [comment]
I am not pkg-config guru (or user ;-), but installing leptonica to custom location (e.g. not system wide) is always source of troubles... Before "pkg-config era" (3.04) this trick worked: https://github.com/tesseract-ocr/tesseract/wiki/Compiling#install-elsewhere--without-root.

Can you try this?
`ACLOCAL_FLAGS="-I /hab/pkgs/tpolekhin/leptonica/1.74.4/20171124113357/lib" ./autogen.sh`

**Comment by tpolekhin** [comment]
I think that the issue here is that pkg-config can't find m4 macros for PKG_CHECK_MODULES
Here's what i found in `config.log`
```
ACLOCAL='${SHELL} /hab/cache/src/tesseract-3.05.01/config/missing aclocal-1.15'
```

**Comment by tpolekhin** [comment]
@zdenop tried `ACLOCAL_FLAGS="-I /hab/pkgs/tpolekhin/leptonica/1.74.4/20171124113357/" ./autogen.sh` with same error :(

**Comment by stweil** [comment]
Did you install `autoconf-archive` (or another package needed for your Linux distribution which provides the macro `PKG_CHECK_MODULES`?

**Comment by tpolekhin** [comment]
okay, so the issue was that `automake/share/aclocal/` was missing `pkg.m4`

**Comment by amitdo** [comment]
`PKG_CHECK_MODULES` comes from `pkg-config`
https://cgit.freedesktop.org/pkg-config/tree/pkg.m4.in

**Comment by amitdo** [comment]
https://stackoverflow.com/a/10229811
