### ISSUE TITLE
MSVC optimization /Ot (included in /O2) breaks tesseract release build

### ISSUE THREAD

**Issue by MarkusGH** [tesseract-ocr/tesseract#1223]
### Environment

* **Tesseract Version**:  4.00.00dev with current training data (tessdata_best).
* **Commit Number**: eba0ae3b88a46a93e981770caa0b148d65cc4468
* **Platform**: Windows 64-bit build, Visual Studio 2017 15.4.4

### Current Behavior:

[Test.zip](https://github.com/tesseract-ocr/tesseract/files/1505927/Test.zip)

1) MinSizeRel build

Command: 

tesseract.exe C:\Test.tif C:\Test -l deu+eng --psm 1 --oem 1 pdf

Error messages:

None

Result:

Correct PDF created, OCR results OK

2) Release build

Command: 

tesseract.exe C:\Test.tif C:\Test -l deu+eng --psm 1 --oem 0 pdf

Error messages:

None

Result:

Correct PDF created, OCR results OK

3) Release build

Command: 

tesseract.exe C:\Test.tif C:\Test -l deu+eng --psm 1 --oem 1 pdf

Error messages:

Multiple times:

Error in pixCreateHeader: height must be > 0
Error in pixCreateNoInit: pixd not made
Error in pixCreate: pixd not made
Error in pixClipRectangle: pixd not made

Result:

Broken PDF created.

Conclusion:

Release build shows erratic behavior when LSTM is used, errormessages and/or wrong output.
Debug And MinSizeRel builds work slowly but correctly.
As soon as the optimization /Ot is switched to /Os (or from /O2 to /O1) or LSTM is not used all problems go away.

### Expected Behavior:

Release build behaves like MinSizeRel/Debug built.

### Suggested Fix:

Problem is located in Tesseract::GetRectImage

As soon as speed optimization for this function is switched off with #pragma optimize( "t", off ) the problem goes away.

**Comment by zdenop** [comment]
How did you build tesseract?
Error messages you posted comes from leptonica, so...

**Comment by MarkusGH** [comment]
As I made some progress I updated the issue to better describe what is happening.
I built tesseract exactly like described here:
 https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows
Develop Tesseract -> Building for x64 platform

**Comment by zdenop** [comment]
I would suggest you make sure that the all dependencies (at least leptonica) are build as 64bit and with the same version of compiler...

**Comment by hoangtocdo90** [comment]
@zdenop  Please resolve this ! I have same error when building tesseract

**Comment by MarkusGH** [comment]
It is a 64 bit version of leptonica - otherwise it would not work at all.
Why should the compiler used to build leptonica make any difference?
Due to my findings the problem is located in Tesseract::GetRectImage, and goes away as soon as that very function is not optimized for speed anymore.
I would not expect that the way tesseract interfaces with external libraries is changed by the optimization option.

**Comment by egorpugin** [comment]
Hi,

Not sure if this is your post https://groups.google.com/forum/#!topic/tesseract-ocr/lufafrAAEnk
It points to `/Ob2` option while you state `/Ot`.

Did you try `RelWithDebInfo` configuration?

**Comment by MarkusGH** [comment]
Not my post and it does not look like the problem has anything to do with /Ob2.
RelWithDebugInfo shows the same behaviour as Release as both use /O2.

**Comment by MarkusGH** [comment]
Found similar problem in ColPartitionGrid::ComputeTotalOverlap with some input files.
A Release build hits the following assertion:
contains_unichar_id(unichar_id):Error:Assert failed:in file C:\Users\mw\Desktop\OCR\tesseract-master\ccutil\unicharset.h, line 513
As soon as I add #pragma optimize( "t", off ) directly in front of the function ColPartitionGrid::ComputeTotalOverlap  the problem goes away.

**Comment by stweil** [comment]
@MarkusGH, did you also restore optimization after `ColPartitionGrid::ComputeTotalOverlap` and `Tesseract::GetRectImage`, so we can be sure that only those functions used code without optimization in your test?

**Comment by MarkusGH** [comment]
Yes - I put #pragma optimize( "", on )  directly after the functions.
It looks like the following have a strong effect on the problem:
Training files used, size of input file (pixel count), engine.
Strange enough I found at least one file which works with --oem 0 and --oem 1 but not with --oem 3.

**Comment by egorpugin** [comment]
To check if this is VS2017 issue, it's necessary to check on VS2015.
As I understand if we haven't any troubles on gcc/clang, it's problem of MSVC, not tesseract.

**Comment by MarkusGH** [comment]
I think it is too early to blame MSVC for this issue.
Could be a compiler error or could be sloppy programming which leads to unexpected behaviour when that kind of optimization is active. Again - to me it feels a lot like it has to do with signed integer overflow handling. 
Signed integer overflow behaviour is undefined per C++11 standard. 
Without optimizations signed integer overflow will simply wrap around (this is simply what the processor does). With optimizations anything can happen...
You actually do not really know, if the issue is not also present in gcc builds, because the effects are not necessarily obvious - could be there are only slight variations in OCR results.

As you use gcc I would kindly suggest to create a build with the gcc option -ftrapv (and maybe other options necessary to bring the debugger to break on integer overflows) and try the test case I provided to see if it actuall produces integer overflows. If so this makes a case to investigate further in that direction.

**Comment by stweil** [comment]
A Tesseract executable which was compiled with `-ftrapv` does not raise an overflow exception. What about debugging the buggy Windows executable and setting a conditional breakpoint on `pixCreateHeader` (waiting for `height <= 0`)?

**Comment by MarkusGH** [comment]
I searched for that already. Unfortunately I did not build leptonica from source and it does not look like this function is called from anywhere outside leptonica.

**Comment by stweil** [comment]
I tested the binary from [AppVeyor](https://ci.appveyor.com/api/buildjobs/qlkwgwrntp1gnr7l/artifacts/build%2Fbin%2Ftesseract-master.1240.zip). It shows the same problem when running `tesseract --oem 1 Test.tif stdout` with LSTM.

**Comment by stweil** [comment]
@egorpugin, I tried a local build on Windows 7 to debug the problem, but failed: cppan.exe crashed very often with SIGSEGV, and when it finally passed, I got a cmake failure similar to https://github.com/cppan/cppan/issues/36. Is there an alternative way to build Tesseract with VS 2017 community edition?

**Comment by egorpugin** [comment]
Could you try the latest build?

[cppan.zip](https://github.com/tesseract-ocr/tesseract/files/1523752/cppan.zip)

**Comment by Salfai77210** [comment]
@stweil I have the same issue here with `Visual 15 2017 Win64` Enterprise & Community editions

Thanks @egorpugin i will try that

**Comment by egorpugin** [comment]
@Salfai77210, @stweil 
Please, try another one client.

[cppan.zip](https://github.com/tesseract-ocr/tesseract/files/1524081/cppan.zip)

**Comment by Salfai77210** [comment]
@egorpugin okay i will try this tkx. Have you read my edited comment on cppan/cppan#36 ?

**Comment by egorpugin** [comment]
New client is a possible fix for your issue too. Try it.

**Comment by stweil** [comment]
Even with the latest `cppan` it takes about 20 iterations until `cppan` has fetched all required packages and passes without failure. It looks like these iterations don't get everything correctly set up, because the following `cmake` still complains about missing files and fails.

**Comment by egorpugin** [comment]
Are you trying this on windows?

**Comment by stweil** [comment]
Sure. I tried it on Windows 7 / 64 bit.

**Comment by egorpugin** [comment]
Maybe this one?
Sorry, I can't repro the issue locally, so we have this kinda "game".
Did you see any messages about crash dumps? Check `c:\users\u\appdata\local\temp\cppan\dump` folder.

[cppan.zip](https://github.com/tesseract-ocr/tesseract/files/1528701/cppan.zip)

**Comment by stweil** [comment]
I got messages about crash dumps (minidumps), but did not find the dump files. I'll  have a look at the indicated location later.

**Comment by stweil** [comment]
The `cppan` crash seams to occur while trying to free memory, maybe related to `setlocale`. Could you please create an executable with debug information (even better: a debug build)? Then I'll get more information about the exact code location.

**Comment by egorpugin** [comment]
Debug version:
https://www.dropbox.com/s/lja1dmzn6iwzxnx/cppand.zip?dl=1

**Comment by zdenop** [comment]
@MarkusGH @stweil @FaisalHussain95 Is this issue solved?

**Comment by stweil** [comment]
I just repeated the previous test with [the latest binary](https://ci.appveyor.com/api/buildjobs/qmrykp1ds4mjrjmg/artifacts/build%2Fbin%2Ftesseract-master.1996.zip), and it looks like the issue is fixed.

**Comment by FaisalHussain95** [comment]
@zdenop Yes it works !
