### ISSUE TITLE
Unable to build from 4.00.00 releases

### ISSUE THREAD

**Issue by L30Bola** [tesseract-ocr/tesseract#1224]
### Environment

4.00.00alpha/dev
Download both releases from 4.00.00
Linux 913374a2f5ee 4.13.16-300.fc27.x86_64 #1 SMP Mon Nov 27 18:19:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux - It's a CentOS 7.4 Docker container 

### Current Behavior:
Running `tesseract -oem 0` indicates warnings about leaks:
```
[root@913374a2f5ee tesseract-4.00.00alpha]# tesseract -oem 0
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.
ObjectCache(0x7f9538b735a0)::~ObjectCache(): WARNING! LEAK! object 0x2fb87b0 still has count 1 (id /usr/local/share/tessdata/eng.traineddatapunc-dawg)
ObjectCache(0x7f9538b735a0)::~ObjectCache(): WARNING! LEAK! object 0x2fb85c0 still has count 1 (id /usr/local/share/tessdata/eng.traineddataword-dawg)
ObjectCache(0x7f9538b735a0)::~ObjectCache(): WARNING! LEAK! object 0x2fb8670 still has count 1 (id /usr/local/share/tessdata/eng.traineddatanumber-dawg)
ObjectCache(0x7f9538b735a0)::~ObjectCache(): WARNING! LEAK! object 0x2fb8720 still has count 1 (id /usr/local/share/tessdata/eng.traineddatabigram-dawg)
ObjectCache(0x7f9538b735a0)::~ObjectCache(): WARNING! LEAK! object 0x2fbb780 still has count 1 (id /usr/local/share/tessdata/eng.traineddatafreq-dawg)
```

### Expected Behavior:
After building from source from the master branch I get the expected behaviour:
```
[root@913374a2f5ee tesseract]# tesseract -oem 0
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.
```

**Comment by amitdo** [comment]
> Unable to build from 4.00.00 releases #1224 

In both cases it is clear that the you were able to **build** the software successfully.

https://en.wikipedia.org/wiki/Software_release_life_cycle#Alpha

**Comment by amitdo** [comment]
https://help.github.com/articles/creating-releases/

>If the release is unstable, select This is a pre-release to notify users that it's not ready for production. 

@zdenop,
Is it possible to add this label?
Also, why those xx.xx.xx**dev** are in the releases?

**Comment by zdenop** [comment]
@amitdo: I do not see them in releases:
https://github.com/tesseract-ocr/tesseract/releases

@L30Bola: your report is wrong: As already pointed by amitdo: you claim you are not able to build tesseract and you also run tesseract with wrong way (without required parameters).

**Comment by stweil** [comment]
@zdenop, the releases `4.00.00alpha` and `4.00.00dev` are listed between `3.05.00 Release` and `3.04.01 release`.

**Comment by zdenop** [comment]
Ahh... Than this has to be because of tags.

**Comment by stweil** [comment]
Yes.
