### ISSUE TITLE
(pre-req) leptonica OUTPUT NAME-NOT FOUND - FIXED

### ISSUE THREAD

**Issue by cchalend** [tesseract-ocr/tesseract#1228]
Hi,

(pre-requisite) Standard leptonica 1.74+ installation (cmake then make) produces a **wrong** library definition file (used by pkg-config):

PROMPT> cat /usr/local/lib/pkgconfig/lept.pc
...
Version: 1.74.4
Libs: -L${libdir} -l**leptonica_OUTPUT_NAME-NOTFOUND**
...

Changing this line into Libs: -L${libdir} -l**leptonica** will remove this problem when building tesseract

Cheers,
Christophe

**Context**: ubuntu 16.04 (xenial)

**Comment by amitdo** [comment]
Did you install Leptonica from its master branch or a released version?

In any case, for Linux and macOS, don't use CMake. Use Autotools for both Leptonica and Tesseract.

**Comment by zdenop** [comment]
if lept.pc is not correct you should report it to leptonica developers

**Comment by Sineaggi** [comment]
- Workaround 1, use autotools
- Workaround 2, set `Leptonica_DIR` to convince tesseract to search for leptonica using `find_package` (for example, `cmake -DLeptonica_DIR=/Users/sin/.local/cmake ..`)
- Fix 1, make leptonica produce a non-broken pc file
- Fix 2, make cmake look for tesseract using `find_package` before using `pkg_check_modules`, which was our solution https://github.com/Sineaggi/tesseract/commit/db8fb49f8494bc59204fb44b16ca2535ea30faf6

**Comment by amitdo** [comment]
@zdenop, please close this issue.
