### ISSUE TITLE
Cannot install libpng12-dev

### ISSUE THREAD

**Issue by Juddd** [tesseract-ocr/tesseract#1229]
### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**: 
* **Platform**: ubuntu 17.04

### Current Behavior:
I cannot install libpng12-dev. After I run `sudo apt-get install libpng12-dev`. I will get such error information
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libpng12-0

E: Package 'libpng12-dev' has no installation candidate

```

**Comment by Juddd** [comment]
But the command `sudo apt-get install libpng-dev` can run normally. If I have install `libpng-dev` succussfully. Have I to install the `libpng12-dev` still?

**Comment by amitdo** [comment]
Installing libpng-dev is fine. You don't need libpng12-dev.

**Comment by Juddd** [comment]
If it is fine, I think the document should have an aside for other user

**Comment by amitdo** [comment]
>If it is fine, I think the document should have an aside for other user

I already edited the wiki.

**Comment by Mohamed1991A** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libjasper-dev
E: Package 'libpng12-dev' has no installation candidate
