### ISSUE TITLE
i can't build the source with  vs2010,  can't find the file "allheaders.h"

### ISSUE THREAD

**Issue by xinkaven** [tesseract-ocr/tesseract#123]
i can't build the source with  vs2010,  can't find the file "allheaders.h" .  the version is tesseract-3.04.00

**Comment by zdenop** [comment]
https://github.com/tesseract-ocr/tesseract#dependencies-and-licenses

**Comment by huangMingHua** [comment]
this repository can't find the file "allheaders.h"
