### ISSUE TITLE
Generating Training Images: "exp0.box file does not exist or is not readable"

### ISSUE THREAD

**Issue by Chelagat** [tesseract-ocr/tesseract#1230]
------------------------

### Environment

* **Tesseract Version**: 4.0
* **Commit Number**: eba0ae3b88a46a93e981770caa0b148d65cc4468
* **Platform**: Darwin DN0a1feb60.SUNet 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64

### Current Behavior:
I am in the "create training data" step of the tesseract 4.0 tutorial.
I have cloned the langdata repo in tesseract repo. 
When I run:
`training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only   --noextract_font_properties --langdata_dir ./langdata   --tessdata_dir ./tessdata   --fontlist Arial --output_dir ./tesstutorial/engeval`
I get the following log:

`=== Starting training for language 'eng'
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
training/tesstrain_utils.sh: line 197: /sample_text.txt: Permission denied
[Sun Dec 10 07:45:18 PST 2017] /usr/local/bin/text2image --fonts_dir=/usr/share/fonts --font=Arial --outputbase=/sample_text.txt --text=/sample_text.txt --fontconfig_tmpdir=
Failed to read file: /sample_text.txt

=== Phase I: Generating training images ===
Rendering using Arial
[Sun Dec 10 07:45:19 PST 2017] /usr/local/bin/text2image --fontconfig_tmpdir= --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/var/folders/m6/h4j509sd3rj_qvmtrbv41fw40000gn/T/tmp.bj52lBMQ/eng/eng.Arial.exp0 --max_pages=3 --font=Arial --text=./langdata/eng/eng.training_text
ERROR: /var/folders/m6/h4j509sd3rj_qvmtrbv41fw40000gn/T/tmp.bj52lBMQ/eng/eng.Arial.exp0.box does not exist or is not readable
ERROR: /var/folders/m6/h4j509sd3rj_qvmtrbv41fw40000gn/T/tmp.bj52lBMQ/eng/eng.Arial.exp0.box does not exist or is not readable` 

List of fonts includes Arial ( ran command `text2image --fonts_dir /usr/share/fonts --list_available_fonts` to confirm). Snapshot of output is below.
`67: Arial
 68: Arial Black, weight=810
 69: Arial Black, weight=810 Italic
 70: Arial Bold
 71: Arial Bold Italic
 72: Arial Hebrew
 73: Arial Hebrew Bold
 74: Arial Hebrew Bold Italic
 75: Arial Hebrew Italic
 76: Arial Hebrew Scholar
 77: Arial Hebrew Scholar Bold
 78: Arial Hebrew Scholar Bold Italic
 79: Arial Hebrew Scholar Italic
 80: Arial Hebrew Scholar weight=237
 81: Arial Hebrew Scholar weight=237 Italic
 82: Arial Hebrew weight=237
 83: Arial Hebrew weight=237 Italic
 84: Arial Italic
 85: Arial Narrow
 86: Arial Narrow Bold
 87: Arial Narrow Bold Italic
 88: Arial Narrow Italic
 89: Arial Rounded MT Bold,
 90: Arial Rounded MT Bold, Italic
 91: Arial Unicode MS
 92: Arial Unicode MS Italic`

**Comment by Shreeshrii** [comment]
>`=== Starting training for language 'eng'
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
mktemp [-d] [-q] [-u] -t prefix
training/tesstrain_utils.sh: line 197: /sample_text.txt: Permission denied
[Sun Dec 10 07:45:18 PST 2017] /usr/local/bin/text2image --fonts_dir=/usr/share/fonts --font=Arial --outputbase=/sample_text.txt --text=/sample_text.txt --fontconfig_tmpdir=
Failed to read file: /sample_text.txt

Looks like  you don't have rights to create the tmp directory.

**Comment by Shreeshrii** [comment]
@zdenop Please close this issue.
