### ISSUE TITLE
tesseract from git crashes with particular file & language data

### ISSUE THREAD

**Issue by thilo-hub** [tesseract-ocr/tesseract#1232]
### Environment

* Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
* eba0ae3b88a46a93e981770caa0b148d65cc4468
*11.1-STABLE FreeBSD 11.1-STABLE #0 994fc1be1(freenas/11-stable): Sun Aug 27 05:02:31 UTC 2017 
64 bit

-rw-r--r--  1 root  wheel  20193615 Nov 11 16:19 /usr/local/share/tessdata/deu.traineddata
-rw-r--r--  1 root  wheel  15400601 Nov 11 16:19 /usr/local/share/tessdata/eng.traineddata
MD5 (/usr/local/share/tessdata/eng.traineddata) = 4be3f51b55c0074d8c6b1ee5b5100f95
MD5 (/usr/local/share/tessdata/deu.traineddata) = 1c809fc10ef1f6e561978ddb33e7a1b0

### Current Behavior:
LD_LIBRARY_PATH=api/.libs:/usr/local/lib/gcc7 api/tesseract ~thilo/outa.png   out -l deu
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 381
Detected 190 diacritics
contains_unichar_id(unichar_id):Error:Assert failed:in file ../ccutil/unicharset.h, line 513
Segmentation fault

without -l deu, it does not crash

### Expected Behavior:
no assertation error
### Suggested Fix:

![outa](https://user-images.githubusercontent.com/23134554/33811120-a47a854e-de0e-11e7-860b-4e46cad5f389.png)

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+contains_unichar_id

Make sure you have tessdata for deu from the best/fast repo.
