### ISSUE TITLE
Providing a number greater than 13 for --psm option causes it to run in psm mode 8

### ISSUE THREAD

**Issue by jsreid13** [tesseract-ocr/tesseract#1234]
### Environment

* **Tesseract Version**: 4.0
* **Commit Number**: Built from source as of commit eba0ae3b88a46a93e981770caa0b148d65cc4468
* **Platform**: Ubuntu 16.04, 64-Bit

### Current Behavior:
Running tesseract from command line with option --psm 100  (or any number greater than 13) causes tesseract to run in PSM 8 (PSM_SINGLE_LINE).

After digging through how Tesseract handles PSM values it seems that if the value entered is greater than 13 then it behaves similarly to PSM 8 based on the PSM functions in publictypes.h, there's only a difference if LSTMRecognizeWord is ran. This is nonintuitive behaviour and should throw an error to the user to warn them to use a valid PSM.

### Expected Behavior:
Entering a number outside of 0-13 for PSM should throw an error to the user.

### Suggested Fix:
Include a function to check that that value entered in the command line for PSM is between 0 and 13 in the ParseArgs function in tesseractmain.cpp, if not print a message to the user and exit. I made this function flexible enough to work with the OEM value too because this also doesn't throw an error currently when a value is entered outside of 0-3(or 5? there's two new modes CUBE_ONLY and CUBE_COMBINED not sure if they're still in development but they will be counted by this function).
<pre>
void checkArgValues (int arg, const char* mode, int count) {
  if (arg >= count || arg < 0) {
    printf("Invalid %s value, please enter a number between 0-%d", mode, count - 1);
    exit(0); 
  }
}
</pre>
and this will be used in the following way:
<pre>
      else if (strcmp(argv[i], "-psm") == 0 && i + 1 < argc) {
      // The parameter -psm is deprecated and was replaced by --psm.
      // It is still supported for compatibility reasons.
      <b>checkArgValues(atoi(argv[i+1]), "PSM", tesseract::PSM_COUNT);</b>
      *pagesegmode = static_cast<tesseract::PageSegMode>(atoi(argv[i + 1]));
      ++i;
    } else if (strcmp(argv[i], "--psm") == 0 && i + 1 < argc) {
      <b>checkArgValues(atoi(argv[i+1]), "PSM", tesseract::PSM_COUNT);</b>
      *pagesegmode = static_cast<tesseract::PageSegMode>(atoi(argv[i + 1]));
      ++i;
    } else if (strcmp(argv[i], "--oem") == 0 && i + 1 < argc) {
      <b>checkArgValues(atoi(argv[i+1]), "OEM", tesseract::OEM_COUNT);</b>
      *enginemode = static_cast<tesseract::OcrEngineMode>(atoi(argv[i + 1]));
      ++i;
    }
</pre>
and requires the following addition to OcrEngineMode in publictypes.h, similar to what is currently in PageSegMode:

<pre>
enum OcrEngineMode {
  OEM_TESSERACT_ONLY,           // Run Tesseract only - fastest
  OEM_LSTM_ONLY,                // Run just the LSTM line recognizer.
  OEM_TESSERACT_LSTM_COMBINED,  // Run the LSTM recognizer, but allow fallback
                                // to Tesseract when things get difficult.
  OEM_DEFAULT,                  // Specify this mode when calling init_*(),
                                // to indicate that any of the above modes
                                // should be automatically inferred from the
                                // variables in the language-specific config,
                                // command-line configs, or if not specified
                                // in any of the above should be set to the
                                // default OEM_TESSERACT_ONLY.
  OEM_CUBE_ONLY,                // Run Cube only - better accuracy, but slower
  OEM_TESSERACT_CUBE_COMBINED,  // Run both and combine results - best accuracy
  <b>OEM_COUNT			// Number of OEMs</b>
};
</pre>

Created pull request #1236 to merge this change

**Comment by zdenop** [comment]
thanks
