### ISSUE TITLE
Tesseract contains_unichar_id error

### ISSUE THREAD

**Issue by psinger** [tesseract-ocr/tesseract#1237]
Hi,

I have image files that fail with the following error:

> contains_unichar_id(unichar_id):Error:Assert failed:in file ../ccutil/unicharset.h, line 513                                                                                                      Segmentation fault (core dumped)    

I am running it with

> -l deu -c preserve_interword_spaces=1 -psm 3

I know that similar questions have been asked, but I have not seen an applicable solution yet.

I tried different languages, which did not help.

------------------------

### Environment

* **Tesseract Version**: v4.00.00alpha
* **Platform**: Ubuntu 64bit

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+%22contains_unichar_id%28unichar_id%22+is%3Aopen

**Comment by Shreeshrii** [comment]
@zdenop  Please close this issue.

**Comment by stweil** [comment]
This is a duplicate of issue #1205.
