### ISSUE TITLE
quiet is not quiet (using opencl)

### ISSUE THREAD

**Issue by Meriipu** [tesseract-ocr/tesseract#1240]
### Environment

* **Tesseract Version**: 
> tesseract 4.00.00alpha
>  leptonica-1.74.4
>   libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.2) : libpng 1.6.34+apng : libtiff 4.0.9 : zlib 1.2.11
> 
>  OpenCL info:
>   Found 1 platform(s).
>   Platform 1 name: NVIDIA CUDA.
>   Version: OpenCL 1.2 CUDA 9.1.98.
>   Found 1 device(s).
>     Device 1 name: GeForce GTX 950.
>  Found AVX2
>  Found AVX
>  Found SSE
> 

* **Commit Number**: cdc3533
* **Platform**: Linux Meowth 4.13.11-gentoo-pix #2 SMP PREEMPT Wed Dec 13 20:41:04 CET 2017 x86_64 GenuineIntel Linux

### Current Behavior:
A couple of [DS]-lines are printed out despite me passing in the quiet-parameter

### Expected Behavior:
Only detected text is printed/returned, nothing else.  

### Suggested Fix:
be a bit more quiet

### Various
#without quiet
$ tesseract single.png stdout
[DS] Profile read from file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 1:GeForce GTX 950 score is 0.099900
[DS] Device[2] 0:(null) score is 0.539240
[DS] Selected Device[1]: "GeForce GTX 950" (OpenCL)
Empty page!!
Empty page!!

#with quiet
$ tesseract single.png stdout quiet
[DS] Profile read from file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 1:GeForce GTX 950 score is 0.099900
[DS] Device[2] 0:(null) score is 0.539240
[DS] Selected Device[1]: "GeForce GTX 950" (OpenCL)

I know it does not output any ocr'ed text for this particular image (that is not really the issue here...), though my other filenames for images that do get their text read (and also prints the annoying DS-lines) have somewhat inappropriate filenames so I just used this one to be the example.

**Comment by Meriipu** [comment]
https://github.com/tesseract-ocr/tesseract/blob/master/opencl/openclwrapper.cpp#L2650

**Comment by amitdo** [comment]
To make a message quiet, tprintf() should be used.

**Comment by Meriipu** [comment]
I have spent the past hour or so trying with tprintf actually but despite replacing the occurences of printf with tprintf, the messages are still printed 
https://github.com/Meriipu/tesseract/commit/9941a2a3acfd49c4eae234ae635e176e94e552b7

...so I have no idea how to fix this myself, but for my own purposes I might just comment them out completely even if that does not really tackle the issue
https://github.com/Meriipu/tesseract/commit/4c7a5a32fc0d974f8461de5818a348cf8fa87127

**Comment by amitdo** [comment]
You can disable OpenCL when building Tesseract.

**Comment by Meriipu** [comment]
I feel like disabling OpenCL is an aside to this particular issue with these prints not being silenced by a quiet option
though would you say disabling OpenCL is a highly recommended course of action in general? Like is OpenCL a slowdown if I am making a bunch of calls on tiny images with 4-5 characters each (or even a slowdown for most use cases)? 
Or is the suggestion to disable it just a workaround to the issue here with these messages being printed?

I do not understand why changing printf to tprintf did not make any changes happen for me with regards to the quiet option being respected though.

**Comment by amitdo** [comment]
>I do not understand why changing printf to tprintf did not make any changes happen for me with regards to the quiet option being respected though.

Did you rebuild Tesseract after editing the file?

**Comment by Meriipu** [comment]
I rebuilt it after making the changes.

I will try disabling opencl then if it has known bugs.

**Comment by Meriipu** [comment]
Building without opencl actually improved performance by like 2x (at least for my use case).

So while I probably would not close this issue myself as the issue strictly speaking is still there (when using opencl), this works better for me. 
Thanks.

**Comment by amitdo** [comment]
I already suggested to completely remove the OpenCL code.

**Comment by amitdo** [comment]
@jbreiden , can we completely remove the OpenCL code?

**Comment by Shreeshrii** [comment]
@zdenop Please label

Performance

**Comment by zdenop** [comment]
commit above should this tesseract  part of issue. I am not sure if we can have include on messages from opencl libs...
