### ISSUE TITLE
Debian Bug#884903: libtesseract-dev: headers broken: missing std::; headers missing

### ISSUE THREAD

**Issue by jbreiden** [tesseract-ocr/tesseract#1242]
### Environment

* **Tesseract Version**: 

git2188-cdc35338, from Alex's PPA Dec 15, 2017 PPA. True with older versions as well.

* **Commit Number**: 

2188-cdc35338 (I think)

* **Platform**: 

Debian Unstable

### Current Behavior:

Compile errors with some headers. Stuff like string when we need std::string. Details here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884903

### Expected Behavior:

Happy compiler

### Suggested Fix:

Work through these.

**Comment by amitdo** [comment]
Known issue.
https://github.com/tesseract-ocr/tesseract/issues/1045

We get a lot of reports about that issue:
https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+std+string+is%3Aclosed

**Comment by amitdo** [comment]
@jbreiden,

There are two relevant PRs:
* #1082 - Same as your Debian/Ubuntu patch
* #1164 - Add `std:: ` to `string` in `ccutil/unichar.h` **and** in  `ccutil/unicharset.h`

Which one should be committed?

**Comment by stweil** [comment]
PR #1164 is more complete, but it would also be possible to merge both as git is clever enough to handle that.

**Comment by jbreiden** [comment]
PR #1164 sounds good to me. How about adjusting the .cpp files to match?

**Comment by amitdo** [comment]
Both PRs were merged by Zdenko.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
