### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by ZinCoin** [tesseract-ocr/tesseract#1244]
In file included from arith_uint256.cpp:8:0:
uint256.h: In function ‘const uint256 operator+(const base_uint256&, const base_uint256&)’:
uint256.h:602:76: error: ambiguating new declaration of ‘const uint256 operator+(const base_uint256&, const base_uint256&)’
 inline const uint256 operator+(const base_uint256& a, const base_uint256& b) { return uint256(a) += b; }
                                                                            ^
In file included from arith_uint256.cpp:6:0:
arith_uint256.h:210:35: note: old declaration ‘const base_uint<256u> operator+(const base_uint<256u>&, const base_uint<256u>&)’
     friend inline const base_uint operator+(const base_uint& a, const base_uint& b) { return base_uint(a) += b; }
                                   ^
In file included from arith_uint256.cpp:8:0:
uint256.h: In function ‘const uint256 operator-(const base_uint256&, const base_uint256&)’:
uint256.h:603:76: error: ambiguating new declaration of ‘const uint256 operator-(const base_uint256&, const base_uint256&)’
 inline const uint256 operator-(const base_uint256& a, const base_uint256& b) { return uint256(a) -= b; }
                                                                            ^
In file included from arith_uint256.cpp:6:0:
arith_uint256.h:211:35: note: old declaration ‘const base_uint<256u> operator-(const base_uint<256u>&, const base_uint<256u>&)’
     friend inline const base_uint operator-(const base_uint& a, const base_uint& b) { return base_uint(a) -= b; }
                                   ^
arith_uint256.cpp: In member function ‘void base_uint<BITS>::SetHex(const char*)’:
arith_uint256.cpp:156:40: error: there are no arguments to ‘uint256S’ that depend on a template parameter, so a declaration of ‘uint256S’ must be available [-fpermissive]
     *this = UintToArith256(uint256S(psz));
                                        ^
arith_uint256.cpp:156:40: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
arith_uint256.cpp: In function ‘uint256 ArithToUint256(const arith_uint256&)’:
arith_uint256.cpp:251:21: error: ‘class uint256’ has no member named ‘begin’
         WriteLE32(b.begin() + x*4, a.pn[x]);
                     ^
arith_uint256.cpp: In function ‘arith_uint256 UintToArith256(const uint256&)’:
arith_uint256.cpp:258:30: error: ‘const class uint256’ has no member named ‘begin’
         b.pn[x] = ReadLE32(a.begin() + x*4);
                              ^
arith_uint256.cpp: In instantiation of ‘void base_uint<BITS>::SetHex(const char*) [with unsigned int BITS = 256u]’:
arith_uint256.cpp:198:49:   required from here
arith_uint256.cpp:156:36: error: ‘uint256S’ was not declared in this scope
     *this = UintToArith256(uint256S(psz));
                                    ^
arith_uint256.cpp: In instantiation of ‘void base_uint<BITS>::SetHex(const char*) [with unsigned int BITS = 160u]’:
arith_uint256.cpp:162:11:   required from ‘void base_uint<BITS>::SetHex(const string&) [with unsigned int BITS = 160u; std::__cxx11::string = std::__cxx11::basic_string<char>]’
uint256.h:465:19:   required from here
arith_uint256.cpp:156:36: error: ‘uint256S’ was not declared in this scope
Makefile:7528: recipe for target 'libbitcoinconsensus_la-arith_uint256.lo' failed
make[2]: *** [libbitcoinconsensus_la-arith_uint256.lo] Error 1
make[2]: Leaving directory '/home/joey/zincoin/src'
Makefile:8933: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/joey/zincoin/src'
Makefile:687: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by amitdo** [comment]
https://github.com/bitcoin/bitcoin/blob/master/src/arith_uint256.cpp

https://github.com/bitcoin/bitcoin/issues
