### ISSUE TITLE
OCR not execute inside the Container

### ISSUE THREAD

**Issue by aswinkumarrhex** [tesseract-ocr/tesseract#1245]
Hi
installed GO -TESSARECT inside the container fabric-tools. But application still not able to recognize the same at runtime.
![sm1](https://user-images.githubusercontent.com/20457599/34337496-b487ee2c-e985-11e7-82f7-1be332857e2d.png)
![sm2](https://user-images.githubusercontent.com/20457599/34337498-b55d5774-e985-11e7-8f69-053d6f3e1c0a.png)

**Comment by zdenop** [comment]
We do not provide support for 3rd party project. You can try to use tesseract user forum.
