### ISSUE TITLE
tesseract build fails on an ARMv5 NAS

### ISSUE THREAD

**Issue by MrDini123** [tesseract-ocr/tesseract#1246]
### Environment

* **Tesseract Version**: master (git) and 3.05.01
* **Commit Number**: bc668da
* **Platform**: Linux testnas 2.6.31.8 #2 Thu Jun 8 14:26:59 CST 2017 armv5tel GNU/Linux 

### Current Behavior:

When I am trying to build tesseract from source on a NAS, running uClibc, it gives me the following error:

```
make[2]: Entering directory '/i-data/bf835951/build/tesseract/api'
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11   -o tesseract tesseract-tesseractmain.o libtesseract.la -llept  -fopenmp  -lrt -lpthread
libtool: link: g++ -g -O2 -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o -fopenmp  ./.libs/libtesseract.so -L=/lib -L/lib /lib/libstdc++.so /lib/liblept.so /lib/libpng16.so /lib/libgif.so /lib/libtiff.so /lib/liblzma.so /lib/libjpeg.so -lz /lib/libwebp.so -lm -lrt -lpthread -pthread -fopenmp -Wl,-rpath -Wl,/lib
/bin/ld: warning: libm.so.0, needed by /lib/libstdc++.so, may conflict with libm.so.6
/bin/ld: warning: libc.so.0, needed by /lib/libstdc++.so, may conflict with libc.so.6
/lib/libc.so.0: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/lib/libc.so.0: warning: the use of `mktemp' is dangerous, better use `mkstemp'
/lib/libc.so.0: warning: the `getpw' function is dangerous and should not be used.
/lib/libc.so.0: warning: the `gets' function is dangerous and should not be used.
/lib/libc.so.0: warning: the use of `tempnam' is dangerous, better use `mkstemp'
/bin/ld: /bin/../lib/gcc/arm-ffp-linux-uclibcgnueabi/4.9.2/../../../crt1.o: undefined reference to symbol '__uClibc_main'
/lib/libc.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:562: recipe for target 'tesseract' failed
make[2]: *** [tesseract] Error 1
```

This is interesting, because it seems like, the libc has that DSO:

```
833: 00057720   868 FUNC    GLOBAL DEFAULT    7 __uClibc_main
```

### Expected Behavior:

The automake compile tesseract successfully.

**Comment by jbreiden** [comment]
That's weird. We get a good build on Debian's armel architecture, which works on Armv5t processors

https://buildd.debian.org/status/package.php?p=tesseract&suite=unstable
https://wiki.debian.org/ArmEabiPort

Here's a direct link to the build log

https://buildd.debian.org/status/fetch.php?pkg=tesseract&arch=armel&ver=4.00~git2219-40f43111-1.2&stamp=1519712057&raw=0

**Comment by MrDini123** [comment]
This binary is good, but not for uClibc. That's why I am looking for a way to compile it by myself.

**Comment by jbreiden** [comment]
Good luck. I imagine it will be horribly slow without NEON instructions.

**Comment by MrDini123** [comment]
Unfortunately I Cannot do anything with the error that I pasted here in the past.

**Comment by stweil** [comment]
@MrDini123, do you still get the error with the latest code?

**Comment by zdenop** [comment]
Closssing as error message is not related to tesseract but `uclibc`: 
/bin/ld: /bin/../lib/gcc/arm-ffp-linux-uclibcgnueabi/4.9.2/../../../crt1.o: undefined reference to symbol '__uClibc_main'
/lib/libc.so.0: error adding symbols: DSO missing from command line
