### ISSUE TITLE
"makefile not found" error when build from source

### ISSUE THREAD

**Issue by zhuguangqiang** [tesseract-ocr/tesseract#1247]
I try to build from source of V4.0 with LSTM, and error happend when I excute "make" command saying "no makefile found", my OS is Centos 7.0.   
what can I do to resolve this problem?

**Comment by zdenop** [comment]
Solution is very easy: read documentation.

**Comment by Shreeshrii** [comment]
Alex  compiled an rpm package with tesseract-ocr for CentOS, Fedora, ScientificLinux, OpenSuse.

https://build.opensuse.org/project/show/home:Alexander_Pozdnyakov

@zhuguangqiang   Please check if it works on Centos7.
