### ISSUE TITLE
got wrong result when OCR a binary-inv(black background and white frontground) img

### ISSUE THREAD

**Issue by zhuguangqiang** [tesseract-ocr/tesseract#1249]
![2](https://user-images.githubusercontent.com/20946442/34384614-3973959a-eb58-11e7-8ea8-11164490b13f.png)
![3](https://user-images.githubusercontent.com/20946442/34384617-3e6ead6e-eb58-11e7-822a-f392093843fc.png)
 
attached are 2 imgs, the first is a 3-D img and get a reasonable result of "MNB", and the second img is a 2-D binary-inv img and get a wrong result of "|", and there is a warning prompt when run the ocr command like:
tesseract -l chi_sim --psm 13  1.png 1.txt
warning prompt as below:
Tesseract Open Source OCR Engine v4.0.0-alpha.20170804 with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.

is that a bug?how to resolve?

**Comment by zhuguangqiang** [comment]
sorry, a mistake,actually the first img is a 2-D and the second is 3-D, and the 2-D img get a wrong result

**Comment by zdenop** [comment]
`tesseract.exe --help-psm`
