### ISSUE TITLE
After training, again identified the results of the error-related issues or there

### ISSUE THREAD

**Issue by fenghn** [tesseract-ocr/tesseract#1257]
1, how to know the final training is successful (ie: the generated object with the extension named traineddata is valid).

2, how to open the extension named traineddata target file.

3, a variety of different fonts (numbers) how to train into a target library inside.

**Comment by amitdo** [comment]
[A guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).
Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).
