### ISSUE TITLE
java.lang.Error: Invalid memory access

### ISSUE THREAD

**Issue by Singhak** [tesseract-ocr/tesseract#1261]
As I am using the eng training dataset [Error-causing Tessdata](https://github.com/tesseract-ocr/tessdata_best) then tess4j syas that Invalid memory access But I am using tessdata from here [Working testsdata](https://github.com/tesseract-ocr/tessdata) it is working fine. Is there is some difference in the tessdata in both link which I mention here 

------------------------

### Environment

* **Tesseract Version**: 3.4.2
* **Commit Number**: 
* **Platform**: Window

**Comment by Shreeshrii** [comment]
Please report error for tese4j project.

Tessdata_best only supports lstm engine and needs tesseract 4.

Tessdata supports legacy engine.
