### ISSUE TITLE
Create a PDF with multiple pages?

### ISSUE THREAD

**Issue by kviolka** [tesseract-ocr/tesseract#1268]
Hi,

I tested tesseract 4 to create a PDF file with embedded OCR text, that works very nicely for me :).
But how can I feed tesseract multiple images so I can create a multipage PDF? Thanks!

**Comment by amitdo** [comment]
One option is to feed it with multi page tiff.

**Comment by amitdo** [comment]
Second option:
https://github.com/tesseract-ocr/tesseract/issues/928

**Comment by jbreiden** [comment]
Third option:

https://github.com/tesseract-ocr/tesseract/wiki/FAQ#how-to-do-streaming

**Comment by ariefcfa** [comment]
Fourth option (in Windows), use pipe. For example image files in D:\Data\Scanned Images A

`dir /s/b "D:\Data\Scanned Images A" | tesseract - "D:\Data\OCR\A" pdf`

(got the idea from [here](https://github.com/tesseract-ocr/tesseract/issues/660#issuecomment-274213632)

**Comment by jbreiden** [comment]
Similar to my personal favorite:

https://github.com/tesseract-ocr/tesseract/wiki/FAQ#how-to-ocr-streaming-images-to-pdf-using-tesseract

>
