### ISSUE TITLE
Can't use cppan

### ISSUE THREAD

**Issue by QuantumLiu** [tesseract-ocr/tesseract#1269]
I copy cppan.exe to tesseract's dir, and run cppan in cmd, but got error:
C:\cprojects\tesseract>cppan.exe
You have spaces in the storage directory path. CPPAN could not work in this directory: 'C:/Users\Quantum Liu\.cppan\storage'

**Comment by egorpugin** [comment]
Cppan currently works in evironments (user names) without spaces.
Sorry for the inconvenience, please proceed on cppan site.
I opened a ticket https://github.com/cppan/cppan/issues/39 for this.

**Comment by aps9** [comment]
A workaround (from the command prompt):
`set USERPROFILE=C:\code\tesseract-vs` (A folder without any spaces, where CPPAN data will go.)
`cppan`

However, I don't know whether the Tesseract build documentation is still valid or whether this approach will ultimately work...  

[1] https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows
[2] https://github.com/cppan/cppan
