### ISSUE TITLE
Build fails during link if there's a space in the path to the source code

### ISSUE THREAD

**Issue by araftis** [tesseract-ocr/tesseract#1272]
### Environment

tesseract 4.00.00alpha
leptonica-1.74.4
libgif 4.2.3 : libjpeg 9b : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

Found AVX2
Found AVX
Found SSE

Commit Hash:
10a8a67

Platform:
Mac OS X, High Sierra (10.13.4)
Note that support libraries were built with Mac Ports, but I pulled and built the source from scratch.

### Current Behavior:

Yeah, yeah, I know, who puts spaces in their path names? Anyways, if there's a space in the path to the source code, the full build works, and then fails with trying to link libtesseract.

### Expected Behavior:

Build succeeds.

### Suggested Fix:

Probably just need to quote something in a command invocation.

**Comment by egorpugin** [comment]
> Yeah, yeah, I know, who puts spaces in their path names?

True, so this ticket won't get a lot of attention.

**Comment by zdenop** [comment]
You did not provide any log...
So I put here just output from google search: [Sorry, there are just a few things that you can't do with autoconf and have a path with spaces in the name is one of them](https://stackoverflow.com/questions/16194124/autoconf-spaces-in-path). Reason is at [autoconf: File System Conventions](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/File-System-Conventions.html).

Seems like nothing we can fix in tesseract.
