### ISSUE TITLE
Automatic Page segmentation mode is not working in Tesseract 4.0

### ISSUE THREAD

**Issue by nirajan-pant** [tesseract-ocr/tesseract#1273]
### Environment
* **Tesseract Version**: tesseract 4.00.00alpha (windows executables from UB Mannheim)
* **Platform**: Windows 10 64-bit

### Current Behavior:
I am using Tesseract with nep.trainneddata but the automatic page segmentation results with empty result. Only --psm 4 and 6 (single column or uniform block of text) are working with the Nepali text image attached [here](https://lh3.googleusercontent.com/-deZEGcNi7-M/WleM_DV1s7I/AAAAAAAAFgs/AvR3lGALhu0hrOcsK7ZQ4pRIySBDhur9ACLcBGAs/s1600/tmp_20180111201447661_page-6.png). Both automatic page segmentation modes with or without OSD gives no result.  

The discussion on tesseract-ocr forum is [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/tesseract-ocr/FZzfjwrR0iM).

### Expected Behavior:
It is expected that the automatic page segmentation mode must automatically check whether to treat the image as single column or multi-column document.

### Suggested Fix:
Fixing of automatic psm modes.

**Comment by Shreeshrii** [comment]
I investigated this further with latest code from github.

1. eng (tessdata_best and tessdata_fast) work ok with phototest.tif.
2. Latin  (tessdata_best and tessdata_fast) work ok with phototest.tif.

The image with Nepali text in Devanagari script provided as test case by Niranjan.

1. san  (tessdata_best and tessdata_fast) work ok.
2. Devanagari (tessdata_best and tessdata_fast) BOTH DO NOT WORK for psm 1 and 3.
3. hin, mar, nep (tessdata_best) works ok.
4. hin, mar, nep (tessdata_fast) DO NOT WORK for psm 1 and 3.

I have not tested for other languages.

@jbreiden You may want to check on this before bundling 'fast' traineddata for debian.

**Comment by jbreiden** [comment]
Hmm... This was not expected.

**Comment by Shreeshrii** [comment]
For sake of completeness, I also tried with traineddata from tessdata repo, using --oem 1.

1. Devanagari - traineddata does not exist
2. hin - psm 1, 3, 4, 6, 11 - ALL work ok
3. mar - psm 1 and 3 don't work
4. nep - psm 1 and 3 don't work
5. san - psm 1 and 3 don't work.

'work' means it produces OCR output, I have not compared the accuracy of the recognition.

--------------
I also looked at the version strings in the traineddata in tessdata_fast and tessdata_best.

I had assumed (incorrectly, it seems) that tessdata_fast traineddata files were integer versions of the tessdata_best files. However, that might not the case - at least for ALL languages.

eg. for Nepali

tessdata_best
4.00.00alpha:nep:synth20170629:[1,48,0,1Ct3,3,16Mp3,3Lfys64Lfx96Lrx96Lfx512O1c1]

tessdata_fast
4.00.00alpha:nep:synth20170629:[1,48,0,1Ct3,3,16Mp3,3Lfys64Lfx96Lrx96Lfx128O1c1]

best has Lfx512 vs Lfx128 in fast.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/issues/1167 could be related

Segfault on using -psm 0 when using fast eng.traineddata

**Comment by amitdo** [comment]
@stweil,
Shree's Comments are related to your question about fast vs best data in the dev forum.

**Comment by stweil** [comment]
I see, thank you. That makes things even more confusing. So there is no general rule how the fast data was produced. The version string for fast English not even tells me the LSTM parameters (it is `4.00.00alpha:eng:synth20170629`).

**Comment by amitdo** [comment]
>best has Lfx512 vs Lfx128 in fast.

https://groups.google.com/forum/?hl=en#!topic/tesseract-dev/6lcwffUpK1U

*Far greater performance improvements can be made by making the network smaller.* As I already indicated, I have had some very good results in this area, with a network 3x faster than the legacy code (for English) and *much* faster than the legacy code for complex scripts.

**Comment by Shreeshrii** [comment]
@stweil I just saw this in the help for combine_tessdata 

```
Usage for compacting LSTM component to int:
  combine_tessdata -c traineddata_file
```

**Comment by Shreeshrii** [comment]
@jbreiden @AlexanderP 

I figured out the problem for Devanagari script languages traineddata using default PSM from tessdata_fast. None of these (except san) have a lang.config file.

config files are used for layout analysis. tessdata_best has the config files for san, hin, nep and mar but not for Devanagari.

Adding the config files to these traineddata files fixes the problem. I will make PRs for the tessdata_fast (Devanagari, hin, nep and mar) and tessdata_best (Devanagari).

It is possible that config files are needed for other languages also.  I haven't looked beyond this set of files.

**Comment by Shreeshrii** [comment]
1. Not able to upload Devanagari.traineddata for tessdata_best as it is greater than 25MB.

2. Created PR for tessdata_fast 

https://github.com/tesseract-ocr/tessdata_fast/pull/10

**Comment by amitdo** [comment]
>Not able to upload Devanagari.traineddata for tessdata_best as it is greater than 25MB.

Open an issue in https://github.com/tesseract-ocr/tessdata_best and describe the needed changes.

**Comment by stweil** [comment]
@Shreeshrii, I just tested `git push` from a local git clone and had no problem with the size, see [my test commit](https://github.com/stweil/tessdata_best/commit/fcf6d8c7cdbd141cadf6dfba9ea29c51268c45b6). If that does not work for you, you could perhaps provide your patch in a different form, so I can upload it?

**Comment by Shreeshrii** [comment]
Yes, it will be good to update the traineddata files. The PR in
tessdata_fast has already been merged.

It would also help if we can check if any other languages were similarly
impacted.

On 26-Feb-2018 10:37 PM, "jbreiden" <notifications@github.com> wrote:

Good news, package migration to Ubuntu went much faster than expected. If
this is a critical change, I think we can attempt another packaging
iteration.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tesseract-ocr/tesseract/issues/1273#issuecomment-368574148>,
or mute the thread

**Comment by amitdo** [comment]
The current code in Ubuntu 18.04 is based on 766b7bd6207051.
It misses a few fixes from master.

**Comment by AlexanderP** [comment]
I updated tesseract-lang and tesseract in PPA.
https://github.com/AlexanderP/tesseract-lang-debian/commit/4c7bf8a689cc04d0e0d8e350406d8ee8a90bd394
https://github.com/AlexanderP/tesseract-debian/commit/412b06cd3a9e518022d398c3f42450561193d8ef

**Comment by jbreiden** [comment]
Great! Done!

**Comment by Shreeshrii** [comment]
Are the language and script packs also updated in the PPA for trusty etc?

On 27-Feb-2018 1:04 AM, "Alexander Pozdnyakov" <notifications@github.com>
wrote:

I updated tesseract-lang and tesseract in PPA.
AlexanderP/tesseract-lang-debian@4c7bf8a
<https://github.com/AlexanderP/tesseract-lang-debian/commit/4c7bf8a689cc04d0e0d8e350406d8ee8a90bd394>
AlexanderP/tesseract-debian@412b06c
<https://github.com/AlexanderP/tesseract-debian/commit/412b06cd3a9e518022d398c3f42450561193d8ef>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tesseract-ocr/tesseract/issues/1273#issuecomment-368622012>,
or mute the thread

**Comment by AlexanderP** [comment]
@Shreeshrii Yes

**Comment by jbreiden** [comment]
Today is the Ubuntu 18.04 cutoff date. Alexander's latest packages made it. Total success. 

https://launchpad.net/ubuntu/+source/tesseract
https://launchpad.net/ubuntu/+source/tesseract-lang

**Comment by amitdo** [comment]
https://packages.ubuntu.com/search?keywords=libtesseract&searchon=names&suite=bionic&section=all
libtesseract4 & libtesseract-dev
`4.00~git2207-766b7bd6-3.1`

**Comment by jbreiden** [comment]
Oh no, I read the dashboard wrong!

```
The Bionic Beaver (active development)Tesseract trunk series
--
4.00~git2207-766b7bd6-3.1 | release (universe) | 2018-02-23
4.00~git2219-40f43111-1.2 | proposed (universe) | 2018-02-28
```

**Comment by Shreeshrii** [comment]
They were late changes.​ I am still happy that 4.00... has been packaged
and will ship :-)

What is the next date for updates, so that we can plan better.

**Comment by amitdo** [comment]
@jbreiden, an update:

https://packages.ubuntu.com/search?keywords=libtesseract&searchon=names&suite=bionic&section=all
libtesseract4 & libtesseract-dev
4.00~git2219-40f43111-1.2
