### ISSUE TITLE
Issue with running autogen on Tesseract v4

### ISSUE THREAD

**Issue by Freedomafia** [tesseract-ocr/tesseract#1277]
I am trying to test out Tesseract version 4. I downloaded the github repository and ran `./autogen.sh` as it states in the **INSTALL** instructions however it returned the following error message:

```
Unable to find a valid copy of libtoolize or glibtoolize in your PATH!
./autogen.sh: 59: ./autogen.sh: bail_out: not found
Running aclocal
./autogen.sh: 82: ./autogen.sh: aclocal: not found

  Something went wrong, bailing out!
```

------------------------

**Comment by amitdo** [comment]
Duplicate of #833

**Comment by Freedomafia** [comment]
@amitdo Thanks! :+1:
