### ISSUE TITLE
get_isdigit() failing causes program to abort

### ISSUE THREAD

**Issue by craigbroadbear** [tesseract-ocr/tesseract#1279]
------------------------

### Environment

* **Tesseract Version**:  latest master from github cloned on 18 Jan 2018
* **Commit Number**:
* **Platform**: Windows 10, 32 bit build using Visual studio 2017  -->

### Current Behavior:
My program which statically links to tesseract libs crashes / aborts on some images.  Note I can not reproduce this issue using command line tesseract, only from my code.

### Expected Behavior:
No crash.

### Suggested Fix:

get_isdigit - should not abort.  Just return true or false yes?

Replace current get_isdigit() function in ccutil/unicharset.h with:
```

  bool get_isdigit(UNICHAR_ID unichar_id) const {
    if (INVALID_UNICHAR_ID == unichar_id) return false;
    //ASSERT_HOST(contains_unichar_id(unichar_id)); // CRAIG COMMENT - comment out to stop ABORTS
	if (!contains_unichar_id(unichar_id)) return false; // CRAIG COMMENT - added line to stop ABORTS
	return unichars[unichar_id].properties.isdigit;
  }
```

That seems to do the trick.

**Comment by amitdo** [comment]
#1205

**Comment by zdenop** [comment]
@Shreeshrii  (or whoever has time ;-) ): can you test if this modification has effect on quality of OCR?

**Comment by amitdo** [comment]
Just like PR #1286, it's a wrong a fix.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/1205#issuecomment-422113492

**Comment by stweil** [comment]
@zdenop, that function should decide whether a unichar is a digit or not. If it gets a unichar which is not part of the unichar set used in the trained data, that is definitely a bug.

Of course we could remove the assertion and return a random value. We could also change the code and return `false` for that case with the argument, that most unichars are not digit. But all this would only hide the bug, and the same bug might have other effects on the OCR result which are not so obvious.

I close this issue as it is a duplicate.
