### ISSUE TITLE
generated unicharset does not match lstm-unicharset using current langdata training_text

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1280]
### Environment

* **Tesseract Version**: 4.0.0alpha from latest commit in github
* **Tessdata Version**: latest version from tessdata_best repo
* **Langdata Version**: latest version from langdata repo

### Current Behavior: 

I  have tested this for a few languages only.

- lstm-unicharset in the traineddata files in tessdata_best repo does not match the unicharset generated using the training text in langdata repo for the same language. 
- The size of the unicharsets is different. eg. hin.lstm-unicharset is 123 while hin.unicharset is 114, nep.lstm-unicharset is 110 while generated nep.unicharset is 104.
- All characters from hin.unicharset are NOT there in hin.lstm-unicharset.
- All characters from hin.lstm-unicharset are NOT there in hin.unicharset.
- The size of generated unicharset can change based on the fonts used, either because of unrenderable characters or because of limitation of three pages in the text2image generated tif file by tesstrain.sh. Depending on the font's internal sizing, line spacing, the number of lines of text covered in the 3 pages can be different.

This leads to 'finetune' training NOT being possible.

```
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 123 to 114!
Must supply the old traineddata for code conversion!
```

This can also lead to transcription errors using 'plus-minus' training, because all characters from lang.unicharset may NOT be there in lang.lstm-unicharset.

### Expected Behavior:

generated unicharset should match lstm-unicharset for the language when using the training_text from langdata using the tesstrain.sh process to build the starter traineddata.

### Suggested Fix:

1. Update langdata repo for LSTM.
2. Since LSTM training requires large amount of training text (~400,000 lines) provide a representative smaller  sample as training_text for finetuning and plusminus training. This sample training_text should have an adequate representation of all the desired_characters and include ALL the characters in the lstm-unicharset.
3. During finetuning and plusminus training, compare the unicharset of training with the lstm-unicharset from the continue_from model and display on console the characters being 'added' or 'removed' from the unicharset. This is specially important, since tesstrain.sh only uses first 3 pages of the training_text and hence it is possible that certain characters might be inadvertently being dropped from the new unicharset.
4. It will also be helpful if the unicharset files can be sorted, it will make it easier to find any missing characters and compare.

**Comment by Shreeshrii** [comment]
Attached diff file was generated by `diff hin.unicharset.txt hin.lstm-unicharset.txt -y  --suppress-common-lines  > diff.txt'

[hin.lstm-unicharset.txt](https://github.com/tesseract-ocr/tesseract/files/1642991/hin.lstm-unicharset.txt)
[hin.unicharset.txt](https://github.com/tesseract-ocr/tesseract/files/1642992/hin.unicharset.txt)
[Uploading diff.txt…]()

**Comment by abaland** [comment]
Issue also experienced with "jpn" language.

The jpn.lstm-unicharset file extracted from tessdata_best/jpn.traineddata contains 2693 characters (2703 for the "Japanese.traineddata equivalent) but  error "Can't encode transcrption: '**japanese characters**' in language ''" occurs when training on an unmodified version of jpn.training_text from langdata (All downloads made on Jan 31, 2018 from master branch).

**Comment by Shreeshrii** [comment]
@abaland  

>current training_text provided generates warnings for the model it is supposed to be associated with does not seem ideal.

That current training_text is for version 3.0x. It has NOT been updated for 4.00.

I suggest that you create your own representative training text - about 100-120 lines, as only 3 pages are being used via tesstrain.sh.

**Comment by Shreeshrii** [comment]
@andesai2003 which o/s? which version of tesseract? which traineddata?

**Comment by andesai2003** [comment]
iOS 10 +
4.0 tesseract
Need to read arabic data

**Comment by syedaunn** [comment]
@Shreeshrii any update on size of unicharsets? I am facing same issue with Norwegian language.

**Comment by Shreeshrii** [comment]
@syedaunn I have a workaround, if you are doing finetune and want to add a character.

By using 'merge_unicharsets' you can ensure all characters in original unicharset are included. However, then you need to run 'combine_lang_model' command again. Usually that is run by tesstrain.sh.

I use the following as a bash script to handle it:

```
#!/bin/bash
# original script by J Klein  - https://pastebin.com/gNLvXkiM
# based on https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for--a-few-characters

################################################################
# variables to set tasks performed
MakeTraining=yes
MakeEval=yes
RunTraining=yes
BuildFinalTrainedFile=yes
################################################################

# Language
Lang=iast
Continue_from_lang=eng

# Number of Iterations
MaxIterations=300

# directory with training scripts - tesstrain.sh etc.
# this is not the usual place-  because they are not installed by default
tesstrain_dir=./tesseract-training

# directory with the old 'best' training set
bestdata_dir=./tessdata_best

# downloaded directory with language data -
langdata_dir=./langdata

# IMPORTANT - 
# Copy 100-120 lines from $langdata_dir/$Lang/$Lang.training_text 
# as max 3 pages of training text is used; copy to a new file
# $langdata_dir/$Lang/$Lang.plus.training_text
# ADD about 15 instances per char to be added to it
plusTraining_text=plus.training_text

# fonts directory for this system
fonts_dir=/mnt/c/Windows/Fonts

# fonts to use for training - a minimal set for fast tests
fonts_for_training=" \
 'Arial Unicode MS' \
 "
 
# fonts for computing evals of best fit model
fonts_for_eval="'Arial Unicode MS'"

# output directories for this run
train_output_dir=./trained_plus_chars_$Continue_from_lang
eval_output_dir=./eval_plus_chars_$Continue_from_lang

# the output trained data file to drop into tesseract
final_trained_data_file=$train_output_dir/$Lang-FAST.traineddata

# fatal bug workaround for pango
#export PANGOCAIRO_BACKEND=fc 

if [ $MakeTraining = "yes" ]; then

  echo "###### MAKING TRAINING DATA ######"
  rm -rf $train_output_dir
  mkdir $train_output_dir
 
  echo "#### run tesstrain.sh ####"
  
# the EVAL handles the quotes in the font list
eval $tesstrain_dir/tesstrain.sh \
   --lang $Lang \
   --linedata_only\
   --noextract_font_properties \
   --exposures "0" \
   --fonts_dir $fonts_dir \
   --fontlist $fonts_for_training \
   --langdata_dir $langdata_dir \
   --tessdata_dir  $bestdata_dir \
   --training_text $langdata_dir/$Lang/$Lang.$plusTraining_text \
   --output_dir $train_output_dir

fi

# at this point, $train_output_dir should have $Lang.FontX.exp0.lstmf
# and $Lang.training_files.txt

# eval data
if [ $MakeEval = "yes" ]; then
  echo "###### MAKING EVAL DATA ######"
  rm -rf $eval_output_dir
  mkdir $eval_output_dir
  
eval $tesstrain_dir/tesstrain.sh \
   --fonts_dir $fonts_dir\
   --fontlist $fonts_for_eval \
   --lang $Lang \
   --linedata_only \
   --noextract_font_properties \
   --langdata_dir $langdata_dir \
   --tessdata_dir  $bestdata_dir \
   --training_text $langdata_dir/$Lang/$Lang.$plusTraining_text \
   --output_dir $eval_output_dir
 
fi

# at this point, $eval_output_dir should have similar files as
# $train_output_dir but for different font set

if [ $RunTraining = "yes" ]; then

echo "#### combine_tessdata to extract lstm model from 'tessdata_best' for $Continue_from_lang ####"
  
  combine_tessdata \
   -u $bestdata_dir/$Continue_from_lang.traineddata \
    $train_output_dir/$Continue_from_lang.

echo "#### build version string ####"
   Version_Str="$Lang finetuned on $(date +%F) from "
   sed -e "s/^/$Version_Str/" $train_output_dir/$Continue_from_lang.version > $train_output_dir/$Lang.new.version

echo "#### merge unicharsets to ensure all existing chars are included ####"
merge_unicharsets \
   $train_output_dir/$Continue_from_lang.lstm-unicharset \
   $train_output_dir/$Lang/$Lang.unicharset \
   $train_output_dir/$Lang.unicharset
   
echo "#### rebuild starter traineddata ####"
#  --lang_is_rtl  True \
#  --pass_through_recoder True \
#
combine_lang_model \
  --input_unicharset $train_output_dir/$Lang.unicharset \
  --script_dir $langdata_dir \
  --words $langdata_dir/$Lang/$Lang.wordlist \
  --numbers $langdata_dir/$Lang/$Lang.numbers \
  --puncs $langdata_dir/$Lang/$Lang.punc \
  --output_dir $train_output_dir \
  --lang $Lang \
  --version_str $train_output_dir/$Lang.new.version 
  
echo "#### training from $bestdata_dir/$Continue_from_lang.traineddata #####"
  
lstmtraining \
  --continue_from  $train_output_dir/$Continue_from_lang.lstm \
  --old_traineddata $bestdata_dir/$Continue_from_lang.traineddata \
  --traineddata   $train_output_dir/$Lang/$Lang.traineddata \
  --max_iterations $MaxIterations \
  --debug_interval -1 \
  --train_listfile $train_output_dir/$Lang.training_files.txt \
  --model_output  $train_output_dir/pluschars 
 
lstmeval \
  --model $train_output_dir/pluschars_checkpoint \
  --traineddata   $train_output_dir/$Lang/$Lang.traineddata \
  --eval_listfile $eval_output_dir/$Lang.training_files.txt
 
fi


if [ $BuildFinalTrainedFile = "yes" ] ; then
  echo "#### Building final trained file $final_trained_data_file d####"
  
  lstmtraining \
  --stop_training \
  --convert_to_int \
  --continue_from $train_output_dir/pluschars_checkpoint \
  --traineddata $train_output_dir/$Lang/$Lang.traineddata \
  --model_output $final_trained_data_file

fi

# now $final_trained_data_file is substituted for installed


```

**Comment by Shreeshrii** [comment]
The new repo https://github.com/tesseract-ocr/langdata_lstm has the files used for LSTM training.
