### ISSUE TITLE
Tesseract not detecting number 8.

### ISSUE THREAD

**Issue by HassanQamar07** [tesseract-ocr/tesseract#1282]
### Environment

* **Tesseract Version**: 
* **Commit Number**: 3.04
* **Platform**: Ubuntu 17.10
### Current Behavior:
Detecting 8,6 as 5 
### Expected Behavior:
Should detect 8 as 8 and 6 as 6
![phoneb 2](https://user-images.githubusercontent.com/6995005/35121925-f6972246-fcbe-11e7-99ae-ba5e1a032e9a.png)
![phoneb 1](https://user-images.githubusercontent.com/6995005/35121928-f6d16a78-fcbe-11e7-980d-9c0dbd3bdb18.png)

**Comment by zdenop** [comment]
3.04 is not supported version.
