### ISSUE TITLE
text2image: some punctuation in vertical text isn't being rendered correctly

### ISSUE THREAD

**Issue by wareya** [tesseract-ocr/tesseract#1284]
### Environment

* **Tesseract Version**: 4.00.00alpha
* **Commit Number**: 10a8a67ca2bde
* **Platform**: archlinux, in a VM, compiled from source, using pango-git (1addea2f) and harfbuzz-git (g461a6)

### Current Behavior:

![image showing text rendering bug](https://user-images.githubusercontent.com/585488/35197758-73c64338-feb2-11e7-99c3-0a463bad7b73.png)

top: output of text2image in a VM, bottom: firefox nightly, rendering everything correctly

〰 and ‼ in particular are rendering with the wrong orientation - note: the ‼ is a single character, not two exclamation characters, and the "WAVY DASH" might be converted to an emoji by github making it look very different from how it does in the screenshot. the exact locations of the opening quote brackets is also wrong, probably wrong enough to mess with the LSTM a little, but not major.

messing with gravity in the string renderer doesn't fix anything, it's a problem with pango

text2image chokes on vertical text entirely on windows (it spits out tiny rectangles for most characters), but that's probably a problem with the packages being used to compile windows, not tesseract itself

### Expected Behavior:

the output of text2image should have the same glyph orientations as firefox nightly, which is rendering this text correctly

### Suggested Fix:

probably bug pango (maybe harfbuzz-icu, not sure where the responsibility is) to implement http://www.unicode.org/Public/vertical/revision-17/VerticalOrientation-17.txt , which specifies which characters fall back to being programmatically rotated in vertical text if the font doesn't have a vertical flow variant - does pango have cairo do glyph orientation stuff instead? -  my VM has have cairo 1.15.10-1 but changing to cairo-git (g14f5b98d2) doesn't help

going the firefox route and going straight to harfbuzz and freetype in the first place would also work, but take a lot of effort to implement: harfbuzz does all the heavy lifting for telling where glyphs go, but it doesn't do RTL reversing (e.g. for RTL text stored earliest-grapheme-lowest-address, needs to be reordered to leftmost before feeding it to harfbuzz) nor does it split the text into sequences of given orientations. there's so much to get wrong doing it from scratch that there's a very high chance of introducing regressions, but if the dependencies don't get fixed it might be the only option.

Also for some reason the tessdata-best japanese traineddata sometimes spits out ー (vowel elongation mark) instead of 一 (one) for short horizontal lines in vertical Japanese text, which is 100% extremely wrong and indicates that whatever image data was used to train the tessdata-best japanese traineddata used incorrect text rendering software. Vertical rendering correctness has an actionable impact on OCR quality, even if and when it's font-dependent.

**Comment by amitdo** [comment]
Firefox on Linux uses pango (which uses cairo and harfbuzz).

https://packages.ubuntu.com/bionic/firefox
https://packages.ubuntu.com/bionic/libpangocairo-1.0-0
https://packages.ubuntu.com/bionic/libpangoft2-1.0-0

**Comment by wareya** [comment]
Firefox does manual text layouting for web content. https://bugzilla.mozilla.org/show_bug.cgi?id=1431305

html/css is too complicated for systems like pango.

**Comment by amitdo** [comment]
Learning new things each day... :-)

Is this issue occurs with all Japanese fonts?

**Comment by wareya** [comment]
It might not occur with fonts that include vertical variations of every single glyph but that's really uncommon

**Comment by amitdo** [comment]
https://github.com/harfbuzz/harfbuzz/issues/355 seems related to this issue.

**Comment by wareya** [comment]
I think that harfbuzz issue is only for falling back to other codepoints, not for falling back to rotated glyphs. Having rotated glyphs requires having a separate text run with a different writing direction; a single run of text can only be "shaped", i.e. kerned and have ligatures applied, if it's in the same direction, and harfbuzz only does shaping. Whatever uses harfbuzz for shaping has to do glyph rotation fallback stuff itself.

**Comment by zdenop** [comment]
@wareya: Can you report this to pango directly?

**Comment by wareya** [comment]
Upstream issue: https://gitlab.gnome.org/GNOME/pango/issues/322

**Comment by wareya** [comment]
Wouldn't you just leave the issue open until Pango does something??

**Comment by zdenop** [comment]
Problem is that we can not do nothing with it. So why to have it open?

**Comment by zdenop** [comment]
Marked as wontfix, but should be readed as "can do nothing with this" ;-)
So reopen issue until I have time to look what is happening with pange, because there is other issue related to pango and text2image...

**Comment by amitdo** [comment]
@wareya, 

Please provide a sample text file.

Did you test it with other applications that rely directly on Pango for text layout?

**Comment by wareya** [comment]
You can use "テスト。\n一ー〰" as test text.

I could open an issue on Gimp's bug tracker if you think it would be more effective in getting Pango to move. Gimp supports vertical text now, I'm PRETTY sure it uses Pango, and it has the same issue.

The issue is font-dependent. ー (vowel lengthener) usually has vertical typographic fallbacks, but not always. 〰 almost never has vertical typographic fallbacks, but does in the bitmap versions of MS Gothic/Mincho.

If ー (vowel lengthener) ever renders horizontally in the training data for vertical Japanese, even if it's only for a couple fonts, then OCRing vertical Japanese with 一 (kanji for "one") in it will sometimes give ー (lengthener) instead of 一 (one), because their horizontal forms are so similar. Rendering ー (lengthener) horizontally in vertical text is like rendering a latin letter upside-down or sideways in horizontal text.

So like I said earlier, I'm PRETTY sure that Gimp uses Pango, and Gimp 2.10.6 supports vertical text. If you use 〰 in it with the libre fonts Noto Sans CJK JP or Noto Serif CJK JP, it will render 〰 wrong:

![image](https://user-images.githubusercontent.com/585488/46943145-04635000-d03d-11e8-8147-4994cf6059b1.png)

If you use HanaMinA (one half of Hanazono Mincho, a libre font), both ー (vowel lengthener) and 〰 will render wrong. (。 will also render in the wrong position)

![image](https://user-images.githubusercontent.com/585488/46943274-48eeeb80-d03d-11e8-9881-fc89d7b24f68.png)

The correct way to render this test text looks like this (using IPAexMincho, another libre font):

![image](https://user-images.githubusercontent.com/585488/46943502-c61a6080-d03d-11e8-8ce7-f7355eef6a50.png)

(Note: my browser is rendering 〰 in this post as an emoji, but its uses as an emoji and punctuation are different. It's punctuation in the top left of the images in the first post.)

**Comment by amitdo** [comment]
Related old thread I found in cairo mailing list:
https://lists.cairographics.org/archives/cairo/2007-October/011796.html

**Comment by amitdo** [comment]
https://developer.gnome.org/pango/stable/pango-Vertical-Text.html

https://github.com/tesseract-ocr/tesseract/search?q=gravity&unscoped_q=gravity
It does not follow the advice in Pango's reference manual.

**Comment by wareya** [comment]
Pango just merged support for this: https://gitlab.gnome.org/GNOME/pango/merge_requests/28

I guess it'll be in the next release after 1.43.0.

**Comment by amitdo** [comment]
Pango 1.44.0 was finally released.

**Comment by amitdo** [comment]
I think that this issue can be closed now.

**Comment by zdenop** [comment]
Closing. But it would be nice it somebody can test it ;-)
