### ISSUE TITLE
List of parameters considered by Tesseract 4 

### ISSUE THREAD

**Issue by mm-manu** [tesseract-ocr/tesseract#1285]
Hello,
is the a (comprehensive) list of settings which work in Tesseract 4?
I can only find a list for Tesseract 3 and most of them have no effect in v4.

For example I want to modify the minimum confidence value for a word to be detected.

Kind regards

**Comment by amitdo** [comment]
>tesseract --print-parameters

But many of them does not have any effect on the new lstm based ocr engine.

**Comment by sergiocorreia** [comment]
As a follow up, @amitdo from the top of your head what parameters do you think are useful with lstm? I'm trying to improve some results on tables and I'm having a hard time finding out what parameters work (so far, all the ones that I recall were useful for v3 don't do anything)

**Comment by amitdo** [comment]
Most parameters related to the **layout analysis** should work as in 3.05.

For tables maybe the info in #825 will help you.

For the text recognition (ocr), I can clearly see that most parameters are related to the legacy engine.
I don't have a list of the parameters that effect the lstm based ocr engine.

**Comment by Ooiyenchun** [comment]
Currently I encountered the same issue too. Running Tesseract on version 5.0.1 and this is the input and output.
input: tesseract city.jpg stdout --oem 3 --psm 7 -c language_model_viterbi_list_max_size=2000
output: cIiTyY

Attached the image used
![city](https://user-images.githubusercontent.com/33864420/161200955-e2b9ead9-e1ca-4977-bca7-554d610e0138.jpg)


Also tried parameter language_model_viterbi_list_max_num_prunable. Doesn't has any luck so far.

**Comment by zdenop** [comment]
```
tesseract -v
tesseract 5.1.0-7-g0e526
 leptonica-1.83.0 (Jan 26 2022, 19:15:03) [MSC v.1929 LIB Release x64]
  libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.0.91) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 2019
 Found libarchive 3.5.1 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.6 libzstd/1.4.9
 Found libcurl/7.75.0 zlib/1.2.12 libssh2/1.10.1_DEV
```

```
tesseract city.jpg stdout --oem 3 --psm 7 -c language_model_viterbi_list_max_size=2000
CITY
```

language model: tessdata_best
