### ISSUE TITLE
Error while building ScrollView.

### ISSUE THREAD

**Issue by MehulBhardwaj91** [tesseract-ocr/tesseract#1289]
### Environment

* **Tesseract Version**: Version 4.0
* **Commit Number**: 
* **Platform**: Ubuntu 16.04.
After running
`make ScrollView.jar`
I get the following error
`./com/google/scrollview/ui/SVImageHandler.java:19: error: package javax.xml.bind is not visible
import javax.xml.bind.DatatypeConverter;
                ^
  (package javax.xml.bind is declared in module java.xml.bind, which is not in the module graph)
`
It seems that in Java 9 this module has been deprecated which is most probably causing this error. I have looked online but can't find a way around this. I am not a Java expert so I don't know what's the possible solution to this.

But this is definitely something that should be looked into and other deprecated packages as well.

**Comment by toxic-0518** [comment]
I encountered  the same problem in Mac OS High Sierra 10.13

**Comment by toxic-0518** [comment]
It seems that using JDK 8 can solve this problem. @MehulBhardwaj91

**Comment by shanalikhan** [comment]
Facing same in java 10

**Comment by MehulBhardwaj91** [comment]
@toxic-0518 : Since this was optional, I went ahead with the training without it. Didn't try it with JDK 8.
@shanalikhan : I would recommend going ahead with training without it.

**Comment by zdenop** [comment]
Can somebody familiar with java make it work on various Java  version (8-10)?

**Comment by amitdo** [comment]
I think that scrollview should be disabled by default.

**Comment by zdenop** [comment]
well it is build just on user request e.g. user want it. But build seems to work only on old java. So we need to modernize it as we did with cpp code.

**Comment by amitdo** [comment]
>it is build just on user request e.g. user want it. 

`./configure --help`

>...
  --enable-graphics       enable graphics (ScrollView) (default)
  --disable-graphics      disable graphics (ScrollView)
  --enable-embedded       enable embedded build (default=no)
  --disable-openmp        do not use OpenMP
  --enable-opencl         enable opencl build (default=no)
  --enable-visibility     enable experimental build with fvisibility
                          (default=no)
  --enable-multiple-libraries
                          enable multiple libraries (default=no)
  --disable-tessdata-prefix
                          don't set TESSDATA-PREFIX during compile
  --enable-debug          turn on debugging (default=no)


of course, changing the default will not solve the problem, but I still thing we should change it, because scrollview is not necessary for most users.

**Comment by amitdo** [comment]
[Zdenko, please read my above comment]

https://www.google.com/search?client=firefox-b&ei=1OGvW4O_NsWXkwXysYOgDA&q=package+javax.xml.bind+is+not+visible+import+javax.xml.bind.DatatypeConverter

https://www.logicbig.com/tutorials/core-java-tutorial/modules/root-modules.html

https://github.com/contiki-os/contiki/issues/2214https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by amitdo** [comment]
Okay :-)

**Comment by nguyenq** [comment]
Attached is the fix, which is to download the required `jaxb-api-2.3.1.jar`. The files should be placed into `java` folder, replacing the existing ones.

[java.zip](https://github.com/tesseract-ocr/tesseract/files/2462903/java.zip)

**Comment by zdenop** [comment]
Thanks nguyenq!

**Comment by zdenop** [comment]
I tested it with java-1_8_0-openjdk and it worked for me.

**Comment by amitdo** [comment]
Please update the wiki.
https://github.com/tesseract-ocr/tesseract/wiki/ViewerDebugging

**Comment by zdenop** [comment]
done
