### ISSUE TITLE
compiling tesseract 

### ISSUE THREAD

**Issue by ymontes24** [tesseract-ocr/tesseract#1292]
Hi, I'm too new in this ..
I need help with the installation of tess, I follow the steps of:
https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows
but an error occurs when trying to build the solution ....
I think it's because of this "VS2015 redist is required" what should I do in that case?
apologies for the beginner question.
thank you very much.

**Comment by theceday** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by ymontes24** [comment]
@theceday  thanks! 
and now i have a new problem after execute this: 

$ cmake .. -G "Visual Studio 14 2015 Win64" -DCPPAN_USE_CACHE=0 

the error is this:

CMake Error: install(EXPORT "TesseractTargets" ...) includes target "libtesseract" which requires target "95b9aa73" that is not in the export set.

I have also dealt with: 
$ cmake .. -G "Visual Studio 14 2015 Win64" -DCPPAN_USE_CACHE=0 -DCMAKE_INSTALL_PREFIX=C:/lib/tesseract/bin_x64/Install/tesseract
but the error percist....
thanks for you help!

**Comment by Shreeshrii** [comment]
An unofficial installer for windows for Tesseract 3.05-dev and Tesseract 4.00-dev is available from Tesseract at UB Mannheim. This includes the training tools.

https://github.com/UB-Mannheim/tesseract/wiki

**Comment by Shreeshrii** [comment]
@egorpugin This is related to cmake.

**Comment by egorpugin** [comment]
Download & install the latest cppan, cmake. If does not help - the latest VS, Windows
Try to clear cppan storage `c:\users\u\.cppan\storage`.
Re-run commands.
Currently tesseract build does not have any issues.
