### ISSUE TITLE
Automated training always fails (file not found)

### ISSUE THREAD

**Issue by atrbx5** [tesseract-ocr/tesseract#1293]
### Environment

* **Tesseract Version**: v4.00.00alpha, 3.04

* **Platform**: osx 10.13.2, ubuntu 16.04

### Current Behavior:

When I try to automate training some font I'm getting such output for OSX

`$ tesseract -v
tesseract 4.00.00alpha
 leptonica-1.74.4
  libgif 4.2.3 : libjpeg 9c : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX2
 Found AVX
 Found SSE
$ tesseract training/text2image --text=training_text.txt --outputbase=eng.avant.exp0 --font='ITC Avant Garde Gothic LT Book Regular' --fonts_dir=fonts
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.

 `
and for Ubuntu

`VirtualBox:~/Downloads/AvantTrain$ tesseract -v
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0

VirtualBox:~/Downloads/AvantTrain$ tesseract training/text2image --text=training_text.txt --outputbase=eng.avant.exp0 --font='ITC Avant Garde Gothic LT Book Regular' --fonts_dir=fonts
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
ERROR: Can not open input file training/text2image
Error during processing.
`

**Comment by amitdo** [comment]
$ tesseract training/text2image

You are mixing two different commands.
1) tesseract
2) text2image

**Comment by atrbx5** [comment]
hm what is the correct then?

**Comment by Shreeshrii** [comment]
For automated training use

https://github.com/tesseract-ocr/tesseract/blob/master/training/tesstrain.sh

**Comment by Shreeshrii** [comment]
>tesseract training/text2image

Incorrect usage.

@zdenop  Please close this issue.
