### ISSUE TITLE
Tesseract4 version confirmation

### ISSUE THREAD

**Issue by MerlinArul** [tesseract-ocr/tesseract#1294]
[Tesseract.zip](https://github.com/tesseract-ocr/tesseract/files/1664216/Tesseract.zip)
Please find the below link and confirm us is this **"Tesseract version 4 "** or below version 4 

https://github.com/charlesw/tesseract/tree/feature/321-Tesseract-4

In source it is metioned as 
**TesseractVersion = "3.04.01";**

 
Eg:
using Tesseract.Internal;

namespace Tesseract
{
    /// <summary>
    /// The tesseract OCR engine.
    /// </summary>
    public class TesseractEngine : DisposableBase
    {
        private const string TesseractVersion = "3.04.01";
        private static readonly TraceSource trace = new TraceSource("Tesseract");

**Comment by amitdo** [comment]
Please ask them directly.
https://github.com/charlesw/tesseract/issues

**Comment by Shreeshrii** [comment]
@zdenop  Please close this.
