### ISSUE TITLE
missing manpages for v4 training binaries

### ISSUE THREAD

**Issue by jbreiden** [tesseract-ocr/tesseract#1297]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below. 

------------------------

### Environment

* **Tesseract Version**:   4.00dev
* **Commit Number**:  cdc35338
* **Platform**:  Linux

### Current Behavior:

We've got a lot of manpages in the `doc/` directory, but not for the v4 training tools. Does it make sense to write some more?

```
usr/bin/classifier_tester
usr/bin/combine_lang_model
usr/bin/lstmeval
usr/bin/lstmtraining
usr/bin/merge_unicharsets
usr/bin/set_unicharset_properties
usr/bin/text2image
```

### Expected Behavior:

Manpage for every binary.

### Suggested Fix:

Write some manpages?

**Comment by Shreeshrii** [comment]
Even the help messages for some of these binaries are incorrect.

A few default to a common training tools routine which was meant for the legacy engine. I had created issues re that earlier. Will find links and post here later.

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesseract/issues/871

**Comment by Shreeshrii** [comment]
@jbreiden Current man pages also need to be updated.

eg. tesseract man page at https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc  refers to user-words, user-patterns files. These options do NOT work at all with tesseract4 and in fact ` user-patterns` seem to have been NOT working at all for a few releases (see https://github.com/tesseract-ocr/tesseract/issues/960#issuecomment-305971476)

Should that section be deleted from the man page?

**Comment by Shreeshrii** [comment]
@jbreiden Jeff. is this something you will be addressing before debian release?

If not, is there a template of how the man pages need to be setup?

Is it ok just to modify the markdown in the tesseract/doc/*.1.asc files?

Does the number need to be incremented from 1.asc to  4.asc to indicate that it is for 4.0.0 release?

**Comment by Shreeshrii** [comment]
I have tried my hand at creating a few manpages. WIll appreciate feedback. If they look ok, I will work on the others and then create a PR.

https://github.com/Shreeshrii/tesseract/blob/doc/doc/classifier_tester.1.asc
https://github.com/Shreeshrii/tesseract/blob/doc/doc/set_unicharset_properties.1.asc

https://github.com/Shreeshrii/tesseract/blob/doc/doc/merge_unicharsets.1.asc

https://github.com/Shreeshrii/tesseract/blob/doc/doc/text2image.1.asc

text2image manpage needs further changes and formatting.

**Comment by jbreiden** [comment]
@Shreeshrii  Sorry, it's hard to keep up with all these issues. I did not get a chance to look at the man pages. You are doing the right thing by updating tesseract/doc/*.1.asc, thank you. Just so you know, the 1 refers to the section of the manual.

https://en.wikipedia.org/wiki/Man_page#Manual_sections

**Comment by Shreeshrii** [comment]
FYI

I seem to have lost (accidentally deleted??) the doc branch where I was making the man pages.  Hence above links don't work. I will redo and create a PR.

**Comment by Shreeshrii** [comment]
Fixed via https://github.com/tesseract-ocr/tesseract/pull/1378

Please review for syntax, correct formatting and other required changes.
