### ISSUE TITLE
api->DetectOS() segfaults in Tesseract 4

### ISSUE THREAD

**Issue by jeroen** [tesseract-ocr/tesseract#1298]
I maintain the Tesseract bindings for the R programming language. After upgrading `libtesseract-dev` in Debian (testing) to Tesseract4, the following segfaults. Everything works fine in Tesseract3.

```c++
void ocr_pix(tesseract::TessBaseAPI * api, Pix * image){

  api->ClearAdaptiveClassifier();
  api->SetImage(image);
  char *outText = api->GetUTF8Text();

  //meta data
  OSResults out;
  api->DetectOS(&out);

  ...
```

```
 *** caught segfault ***
address (nil), cause 'memory not mapped'
```

Has the api for `DetectOS()` changed? Is there another API to get the script / orientation of a page?

**Comment by amitdo** [comment]
Hi Jeroen!

See https://github.com/tesseract-ocr/tesseract/pull/544

**Comment by Shreeshrii** [comment]
@amitdo Do you have a sample program using the new API call?

**Comment by amitdo** [comment]
I'll add something to the wiki.

https://github.com/tesseract-ocr/tesseract/wiki/APIExample#orientation-and-script-detection-osd-example
This one is just wrong, even with Tesseract 3.04.

**Comment by amitdo** [comment]
Here is an example which is equivalent to tesseract command with `--psm 0`.
https://gist.github.com/amitdo/7c7a522004dd79b398340c9595b377e1

I didn't test that it compile and work as intended...

**Comment by amitdo** [comment]
@jeroen, can this issue be closed?

**Comment by jeroen** [comment]
Yes thank you for the example. I commented in the gist.
