### ISSUE TITLE
[Suggestion] add check code in configure for "g++" (gcc-c++) and adjust the error message

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#130]
In #129 I reported a configure problem, which stemmed from ```g++``` being unavailable at that moment on my build system. A test code in configure tried to compile ```pixCreate``` with ```g++``` but this failed (because g++ was not there).

Main problem: the output text is misleading ("configure: error: leptonica library missing").

In that case, a special test for presence of g++ should be added **and** the text should better say "g++ (gcc-c++ compiler) not available".

@zdenop pls. let me know, if you want me to add further details. I just wanted to point you to that test, which tests a compilation of ```pixCreate```, but this fails only because already the invocation of ```g++``` fails (not present) - not because missing leptonica code.

**Comment by arvidj** [comment]
I had the same problem, and discovered the cause by looking in the `config.log` file. I see a lot of people having this problem, so might be a good idea to add a check.

**Comment by Wikinaut** [comment]
@arvidj yep. do you, by chance, still have the relevant lines from the config.log , this could be helpful.

**Comment by arvidj** [comment]
I'm pretty sure it was this:

```
./configure:17287: g++ -o conftest -I/Usr/local/include/leptonica -L/usr/local/lib conftest.cpp -llept >&5
./configure: line 2040: g++ command not found
```

**Comment by arvidj** [comment]
Perhaps also update the wiki, installations instructions and the FAQ for this error.

**Comment by Wikinaut** [comment]
@arvidj the best method is to fix the configure, or autogen.sh but I don't know, how, because I have no knowledge how that works.

**Comment by Wikinaut** [comment]
@zdenop Danke - thanks - merci - bedankt....

**Comment by Wikinaut** [comment]
(not yet tested, but I trust @zdenop )

**Comment by zdenop** [comment]
It works (do not forget to run ./autogen.sh first). First is check for g++. If it is not found it looks for clang++... I do not know if this is good or bad ;-) 
When I just used "AC_PROG_CXX" (instead of "AC_PROG_CXX(g++ clang++)") it looks for much more compiler, but it did not found clang++ automatically (which is IMO bad)...
