### ISSUE TITLE
Segmentation fault (core dumped) during new font Tesseract Training

### ISSUE THREAD

**Issue by Tamoghna-Saha** [tesseract-ocr/tesseract#1300]
I am currently working to improve the accuracy of Tesseract OCR engine on new font in English language.
_OS: Ubuntu 16.04 LTS_

**The prerequisites:**
Tesseract version: 3.04
Python 2.7
jTessBoxEditor (and hence JDK)

**Story till now:** Let us consider the new font is breip. So, before training, I performed tesseract OCR and result was pretty bad. So I performed training on this font by following the instruction from the Tesseract GitHub itself. I wrote a Python script to run those commands which are to be executed in the terminal for training. The box files, shapetable - everything has been generated properly. In the end, I wanted to copy the traineddata file to tesseract source directory so that it can be accessed. This is the last line of the python script.
```
print 'Copy the trained data file to tessdata'
command6 = 'sudo cp -f '+language+'.'+fontname+'.* /usr/local/share/tessdata' 
os.system(command6)
print 'Copy Successful!'
```
In the above script, language is the ISO language code and fontname in this case is breip. Everything copied successfully.

**The problem:** However, when I executed tesseract with the following command:

`tesseract test_doc.tif test-after-training -l eng.breip`

I am getting this error:
```
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
tessdata_manager.SeekToStart(TESSDATA_INTTEMP):Error:Assert failed:in file adaptmatch.cpp, line 537
Segmentation fault (core dumped)
```
Can someone help me to fix this issue?

**Comment by stweil** [comment]
That version of Tesseract is old and no longer supported. Please use either v3.05.01 or the experimental version v4.00.* (git master).

**Comment by Tamoghna-Saha** [comment]
Thank you. I tried to do first with 3.05 bur some more error came out from cntraining which I wasn't expecting.
Then I installed 4.00 and executed the same python script, it worked like a charm with very good accuracy.

**Comment by Shreeshrii** [comment]
@zdenop Please close.
