### ISSUE TITLE
Can tesseract an image but can't tesseract list of files

### ISSUE THREAD

**Issue by HURIMOZ** [tesseract-ocr/tesseract#1301]
Hi,
it looks like I'm able to tesseract individual images but because I have thousands of images I created a list (which I've named savedlist.txt) of the files like this:
```
opt/Tesseract-Tamatoa/png-files/IMG-018.png
opt/Tesseract-Tamatoa/png-files/IMG-019.png
opt/Tesseract-Tamatoa/png-files/IMG-020.png
``` 
etc.
Then I type this:
`tesseract /opt/Tesseract-Tamatoa/savedlist.txt /opt/Tesseract-tamatoa/output/
`
I get these messages:
```
Tesseract Open Source OCR Engine v3.03 with Leptonica
Error in pixReadStream: Unknown format: no pix returned
Error in pixRead: pix not read
Error in pixGetInputFormat: pix not defined
Reading /opt/Tesseract-Tamatoa/savedlist.txt as a list of filenames...
Error in fopenReadStream: file not found
Error in pixRead: image file not found
Image file opt/Tesseract-Tamatoa/png-files/IMG-018.png cannot be read!
Error during processing.
```
I even tried to change the files' extension to jpg and jpeg and I encountered the same issue: Tesseracting a single image works fine but not with the list of a thousand files.

Thank you in advance for your help,
Tamatoa 
------------------------

### Environment

* **Tesseract Version**: 3.03
* **Leptonica Version**: 1.70
* **Commit Number**: 
* **Platform**:  Ubuntu 14.04.5 LTS
* **Leptonica libraries**: libgif 4.1.6(?) : libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : webp 0.4.0

**Comment by stweil** [comment]
Try using an absolute file path by adding a leading slash. Example:

    /opt/Tesseract-Tamatoa/png-files/IMG-018.png

**Comment by HURIMOZ** [comment]
Hi stweil
thank you for your reply.
I however still get the same errors...

**Comment by Shreeshrii** [comment]
- *Tesseract Version*: 3.03


ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

On Mon, Jan 29, 2018 at 6:13 AM, Huri Translations <notifications@github.com

**Comment by HURIMOZ** [comment]
what's wrong with - *Tesseract Version*: 3.03?

**Comment by Shreeshrii** [comment]
I don't know whether it is supported in version 3.03. Anyway, that is a quite old and NOT supported.

I tested with 4.0alpha and it works.

```
tesseract list.txt list.out.txt
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Page 0 : Capture.png
Page 1 : digits.png
```

**Comment by stweil** [comment]
This message indicates that Tesseract tries to use the list of image names:

    Image file opt/Tesseract-Tamatoa/png-files/IMG-018.png cannot be read!

Can that file be read by other programs? Try for example `file opt/Tesseract-Tamatoa/png-files/IMG-018.png` or `file /opt/Tesseract-Tamatoa/png-files/IMG-018.png`.

In addition I suggest that you upgrade your Linux installation. As @Shreeshrii said, Tesseract 3.03 is definitely very old. Use Tesseract 3.05 (still not included in Ubuntu, so you have to build it yourself).

**Comment by Shreeshrii** [comment]
>Tesseract 3.03 is definitely very old. Use Tesseract 3.05 (still not included in Ubuntu, so you have to build it yourself).

I don't think 3.05 is going to released on ubuntu. Next one will be 4.00 only (@jbreiden can confirm). 

The 3.05 packages were available from Alex's PPA, but have been superseded now.

https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr/+packages?field.name_filter=tesseract&field.status_filter=superseded&field.series_filter=trusty

```
Publishing details
Superseded on 2016-12-06 by tesseract - 4.00~git1564-6551779-1ppa1~trusty1
Published on 2016-11-29
Changelog
tesseract (3.05.00~git20161129-1ppa1~trusty1) trusty; urgency=medium
```

**Comment by amitdo** [comment]
'/opt/' is a system directory.
Put your the images in a directory under your $HOME (/home/yourusername).

If you want them to be in '/opt' use `sudo tesseract...`

**Comment by jbreiden** [comment]
Works for me.

```
$ cat list.txt
/opt/Tesseract-Tamatoa/png-files/IMG-018.png

$ tesseract -v
tesseract 3.03
 leptonica-1.70
  libgif 4.1.6(?) : libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : webp 0.4.0

$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

$ tesseract list.txt - -
Error in pixReadStream: Unknown format: no pix returned
Error in pixRead: pix not read
Error in pixGetInputFormat: pix not defined
Reading list.txt as a list of filenames...
Page 0 : /opt/Tesseract-Tamatoa/png-files/IMG-018.png
This is a lot of 12 point text to test the
ocr code and see if it works on all types
of file format.

The quick brown dog jumped over the
lazy fox. The quick brown dog jumped
over the lazy fox. The quick brown dog
jumped over the lazy fox. The quick
brown dog jumped over the lazy fox.
```

**Comment by jbreiden** [comment]
I am confident that Ubuntu 18.04  "Bionic Beaver" will have Tesseract version 4. You can follow along here.
https://launchpad.net/ubuntu/+source/tesseract

**Comment by amitdo** [comment]
There is no bug in our side.

@zdenop, please close this issue.

**Comment by huacao123** [comment]
I meet this problem and I solve , you can try to "vi savedlist.txt " , to find any name  not include  ".png"; 
I  remove it  and try again then succeed. hope can help you .

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by Al-Shafi-Github** [comment]
> Hello. I am facing the same issue. I can tesseract an individual image using pytesseract.image_to_string(image) function but I cannot do this: pdfs = pytesseract.image_to_pdf_or_hocr("list.txt", lan='eng', extension='pdf')
> 
> It throws error suggesting that reads : 'Error in fopenReadStream: file not found Error in pixRead ..... ' I using Windows machine and the tesseract version is <Version('5.3.1.20230401')> Can someone please help?

Have you found any solution, yet?
