### ISSUE TITLE
Issue creating PDF with Tesseract 4.00 alpha and Tess4J

### ISSUE THREAD

**Issue by nusynergi** [tesseract-ocr/tesseract#1304]
### Environment

* **Tesseract Version**: 4.00alpha
* **Platform**: Ubuntu 16.04 64bit

### Current Behavior:
When calling OCR to render a PDF, the result from using Tess4J in Java displays the following error. The PDF is not created.

```
Can not open file "�/pdf.ttf"!
Please call SetImage before attempting recognition.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fee9ddcbe90, pid=6286, tid=0x00007fee9ee1d700
#
# JRE version: OpenJDK Runtime Environment (8.0_151-b12) (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.so.4+0x91e90]  TessPageIteratorBegin+0x0
```

On different builds the preceding chars that appear before '/pdf.ttf' differ. But they are never in the standard char set. Typically a question mark in a black block or similar. 

This issue prevents the building of a PDF.

Issue has been apparent for approx 9 months and was hoping it would have just been fixed. 

From what I have found the issue appears to be in pdfrender.cpp. The data directory is not passed correctly from Tess4J to allow creation of a PDF with OCR results. 

To resolve I hard code the C code to point to the required font file location. See pdfrender.cpp file in /dev/tesseract/api at line 654 i.e.

```
tprintf("Custom Code - PDF : Using directory \"%s\"!\n", datadir_);
tprintf("/home/myuser/build/tesseract/tessdata/pdf.ttf");

//n = snprintf(buf, sizeof(buf), "%s/pdf.ttf", datadir_);
n = snprintf(buf, sizeof(buf), "/home/myuser/build/tesseract/tessdata/pdf.ttf");
```

The issue goes away after making this change and recompiling.

### Expected Behavior:
The expected behavior is that the font file should be picked up automatically based upon the tesseract folder I have supplied via Tess4J.

### Suggested Fix:
Trace the use of the tesseract folder supplied by use of Tess4J.

**Comment by amitdo** [comment]
CC:@nguyenq

**Comment by jbreiden** [comment]
I agree with this analysis. The PDF renderer needs to know where the font is.
If you look at the C++ tesseract binary,  we feed it api->GetDataPath(). Need
to do the same thing with Java.

```c++
tesseract::TessPDFRenderer(outputbase, api->GetDatapath(), textonly)
```

**Comment by jbreiden** [comment]
I'm going to close here since there is nothing to do on the Tesseract side. Refile with Tess4J please.
