### ISSUE TITLE
tesseract 3.5.1 configure error: Leptonica 1.74 or higher is required.

### ISSUE THREAD

**Issue by xfengfeng** [tesseract-ocr/tesseract#1305]
### Environment

* **Tesseract Version**: 3.5.1
* **Commit Number**: 
* **Platform**: 3.10.0-514.26.2.el7.x86_64

### Current Behavior:
I already install leptonica 1.74.4, and it was suscceed. 
# ldconfig -p |grep lept
        liblept.so.5 (libc6,x86-64) => /usr/local/lib/liblept.so.5
        liblept.so (libc6,x86-64) => /usr/local/lib/liblept.so
As can be seen from above, leptonica has been installed successfully. When I install the tesseract 3.5.1, configuration error! I don't know why. Finally I download tesseract 3.5.0, and I install suscceed.

**Comment by zdenop** [comment]
There could be various reason  for it (e.g. several version of leptonica installed). Without details there is no way how to help. Anyway fee free to test the latest code with tesseract 4.0
