### ISSUE TITLE
id < this->size():Error:Assert failed:in file unicharset.cpp, line 300 Abort trap: 6

### ISSUE THREAD

**Issue by GitHubGS** [tesseract-ocr/tesseract#1308]
### Environment

* **Tesseract Version**: <tesseract 4.00.00alpha>
* **Platform**: <mac os 64-bits>

### Current Behavior:
run cmd :" tesseract xxxxx.tif xxxxx --psm 6 --oem 0 nobatch box.train", the program will crash, output the following : 
"id < this->size():Error:Assert failed:in file unicharset.cpp, line 300
Abort trap: 6"
if I use --psm 5, it works well
btw, I am sure the *.traineddata is the latest one
how to solve this problem?

**Comment by Shreeshrii** [comment]
--oem 0 will NOT work with traineddata from tessdata_best and tessdata_fast

**Comment by GitHubGS** [comment]
@Shreeshrii , many thanks for your reply, but I didn't use LSTM mode, so it's useless for me

**Comment by Shreeshrii** [comment]
Which traineddata did you use?

**Comment by GitHubGS** [comment]
hi man , I use the default eng.traineddata, downloaded from https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-400-november-29-2016

**Comment by Shreeshrii** [comment]
If you don't want to use LSTM mode, then you should use code from 3.05 branch, which will work better with the legacy tesseract engine. 

@stweil @amitdo your advice?

**Comment by GitHubGS** [comment]
if I specify "-l chi_sim", it works well!, Y?

**Comment by amitdo** [comment]
I don't have any advise on issues regarding using **legacy** engine (oem 0 or 2, or 3 with 3.0x traineddata).

>if I specify "-l chi_sim", it works well!, Y?

because it uses the LSTM engine, not the legacy one.

**Comment by amitdo** [comment]
>btw, I am sure the *.traineddata is the latest one

>I use the default eng.traineddata, downloaded from https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-400-november-29-2016

These two statements don't match. fast/best is the latest.

**Comment by stweil** [comment]
I just tested `tesseract testing/eurotext.tif xxxxx --psm 6 --oem 0 nobatch box.train` and got no assertion, but an error message ("Error during processing") ...

**Comment by stweil** [comment]
The error message is caused because Tesseract excepts a file `testing/eurotext.box` which is missing, so that's a case where Tesseract could give better information to the user.

I created the box file with `tesseract testing/eurotext.tif testing/eurotext batch.nochop makebox`. Now the test gives this output:

    Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
    Page 1
    FAIL!
    APPLY_BOXES: boxfile line 100/b ((513,548),(520,571)): FAILURE! Couldn't find a matching blob
    FAIL!
    APPLY_BOXES: boxfile line 348/o ((668,146),(675,169)): FAILURE! Couldn't find a matching blob
    APPLY_BOXES:
       Boxes read from boxfile:     349
       Boxes failed resegmentation:       2
       Found 347 good blobs.
       Leaving 49 unlabelled blobs in 0 words.
    Generated training data for 66 words

Tesseract does not crash. @GitHubGS, do you get a crash with my commands, too? If yes, the problem might be related to our different platforms (macOS / Linux). If no, then the problem could be related to your data. Is it possible to provide the tif and box files which you used for your test?

**Comment by amitdo** [comment]
@Shreeshrii also had this issue in #1178

**Comment by GitHubGS** [comment]
@amitdo hello friend, 
> I don't have any advice on issues regarding using the legacy engine (oem 0 or 2, or 3 with 3.0x traineddata).
I've already used '--oem 0' to specify the legacy engine, and more, 3.0x traineddata can apply to tesseract 4.00.00alpha?

**Comment by GitHubGS** [comment]
@stweil , tks ur reply!

> The error message is caused because Tesseract expects a file testing/eurotext.box which is missing, so that's a case where Tesseract could give better information to the user.

I have the tif and box both existed, using jTessBoxEditor to check it, box file no problem at all.
the problem is :
cmd1: tesseract XX.tif XX --psm 6 --oem 0 nobatch box.train
cmd2: tesseract XX.tif XX --psm 5 --oem 0 nobatch box.train
cmd1 will cause tesseract crash, but cmd2 will not.
since my XX.tif nearly 2GB, if you really want, leave me a mail address I send you

**Comment by GitHubGS** [comment]
final conclusion, it's the input image file problem! thank you all guys!
