### ISSUE TITLE
can't build tesseract 4.0 visual studio 2017

### ISSUE THREAD

**Issue by linhkk3214** [tesseract-ocr/tesseract#1310]
i can't build tesseract 4.0 in visual studio 2017
i downloaded tesseract 4.0 DLL from https://github.com/tdhintz/tesseract4win64 
following the https://stackoverflow.com/questions/18180824/how-to-implement-tesseract-to-run-with-project-in-visual-studio-2010
i added Addtional Include Directories, Additional Library Directories, Additional Dependencies like this
![image](https://user-images.githubusercontent.com/32235851/36007924-4f03bbc4-0d77-11e8-8b0a-63c58c166c7e.png)
![image](https://user-images.githubusercontent.com/32235851/36007943-65a6e7f2-0d77-11e8-89c3-41c2597fcd6d.png)
![image](https://user-images.githubusercontent.com/32235851/36007987-a099f7aa-0d77-11e8-9f9a-da1712c80826.png)
Is this a bug or could anyone give some solutions?
Thanks in advance.

**Comment by zdenop** [comment]
... and you are reporting it on wrong place. We do not support 3rd party projects

**Comment by AbdelsalamHaa** [comment]
@linhkk3214 im not sure but it seems like u put in both the directory the same thing. in c++/c general u shall include only the directory of  h and cpp files for both tesseract and leptonica in the other one the linker u shall include the directory  libraries or lib files

**Comment by NarendraKintali** [comment]
@linhkk3214 , Did you find solution to the problem ? let me know what you did ? I want to use Tesseract in my VisualStudio 2017. Please help me.

**Comment by linhkk3214** [comment]
@NarendraKintali i just following this article https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows
