### ISSUE TITLE
mftrainining takes forever on Win10 or Killed on Ubuntu 

### ISSUE THREAD

**Issue by roywong10** [tesseract-ocr/tesseract#1311]
### Environment

* **Tesseract Version**: 3.05.01
* **Platform**: win10 and Ubuntu 17.10

I try to use tesseract train my own language data, I followed steps of official document and use jTessBoxEditor-1.7.3 to correct the tif, everything went fine except the mftraing process, 
`mftraining -F font_properties -U unicharset -O wr.unicharset wr.sydtoday.exp0.tr`
which output "Warning: No shape table file present: shapetable" and takes forever long on Win10. I switched the platform to Ubuntu and try it again, which the process output the same shapetable warining and  been killed  after several seconds(tried sudo either). 
I am very confusing about it, 
currently the files I got are 
![pic](https://user-images.githubusercontent.com/22558226/36015244-a0864c74-0da8-11e8-853b-bb62dd522063.png)

Please help me!! ORZ ORZ ORZ

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesseract/wiki/Training-Tesseract#shapeclustering

You may need to build the shapetable.

Even otherwise, mftraining used to fail in certain cases - search issues.

Have you tried tesseract4? Does it support your language?

**Comment by zdenop** [comment]
Closed because of missing input from reporter
