### ISSUE TITLE
cppan command '0' not found

### ISSUE THREAD

**Issue by linhkk3214** [tesseract-ocr/tesseract#1312]
i have a issue when run cmake like this
![image](https://user-images.githubusercontent.com/32235851/36017803-d8329f8a-0dab-11e8-8e2e-6eda3a4de1ff.png)
i found this closed solution
https://github.com/tesseract-ocr/tesseract/issues/1107
but i don't unterstand "Apparently I forgot to set the PATH for CMAKE and GIT in the System Environment Variables" in the last reply.
Please help me!

**Comment by fcgll520** [comment]
because you should add "cpan" path to the system path Environment Variables.

**Comment by Shreeshrii** [comment]
@zdenop  Please close this issue.
