### ISSUE TITLE
[Question] How to define a new word in tesseract training

### ISSUE THREAD

**Issue by hoangtocdo90** [tesseract-ocr/tesseract#1313]
Hi guys!
How to add one or some  word to wordlist?
All char in addition word are defined in lstm-unicharset file.
Did we need retrain lstm model or simply  edit wordlist.txt and create new lstm-word-dawg and recombine tessdata file?
Thanks!

**Comment by Shreeshrii** [comment]
I think the following will work.

>edit wordlist.txt and create new lstm-word-dawg and recombine tessdata file

Did you give it a try? Does it improve recognition?

**Comment by hoangtocdo90** [comment]
nope !
i doing may test in english and japanese model. I delete almost of data in wrordlist (keep only 10 record) and recombine tessdata. but result of tesseract is the same

**Comment by zdenop** [comment]
Please respect rules for issues posting: for question use tesseract user forum.
