### ISSUE TITLE
wrong Unicode mapping of some Romanian diacritics

### ISSUE THREAD

**Issue by latrau** [tesseract-ocr/tesseract#1314]
### Environment
Debian Linux

* **Tesseract Version**: tesseract 4.00.00alpha

* **Platform**: Linux 4.15.0 SMP PREEMPT 2018 x86_64 GNU/Linux

### Current Behavior:
romanian diacritics șȘțȚ are mapped into the wrong Unicode codes, namely:
Ș -> Ş=U+015E
ș -> ş=U+015F
Ț -> Ţ=U+0162
ț -> ţ=U+0163
### Expected Behavior:
Ș -> Ș=U+0218
ș -> ș=U+0219
Ț -> Ț=U+021A
ț -> ț=U+021B

### Suggested Fix:
edit the map accordingly, thanks

**Comment by zdenop** [comment]
Why you are opening duplicate  issues? (#1315)
