### ISSUE TITLE
Tesseract makebox is showing different behaviour with different trained data

### ISSUE THREAD

**Issue by bharatkumarreddy** [tesseract-ocr/tesseract#1316]
Hi ,

When I am running MakeBox function In Tesseract 4.0 alpha with Ubuntu with the tessdata_best trained model I am getting the following 
![besttrained](https://user-images.githubusercontent.com/6673708/36083805-f985f686-0fdc-11e8-9669-0b0c805bca2d.png)

you can see it only recognized few chars

and when I am running with the data I trained I got the following result

![mytrained](https://user-images.githubusercontent.com/6673708/36083847-70acf0f2-0fdd-11e8-8cbb-b7e69ecb2c67.png)

It recognised more characters . 
So, My question here is does make-box is also learning. when we are training the model

**Comment by amitdo** [comment]
That is expected behavior. No bug here.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
