### ISSUE TITLE
Performance Improvement (./configure --disable-openmp has no effect)

### ISSUE THREAD

**Issue by mm-manu** [tesseract-ocr/tesseract#1317]
`CPU: Intel 7700k (4 cores + ht)`
`OS: Ubuntu 16.04`
`Tesseract Version: commit ce7ee87fa40745f9e4cb13ec0329787afd13ff56 (latest master)`
`tesseract --version
`
> tesseract 4.00.00alpha  (is it normal that "alpha" is shown here instead of "dev"?)
>  leptonica-1.75.0
>   libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8
> 
>  Found AVX2
>  Found AVX
>  Found SSE
> 

Hello, 
I'm trying to reduce the time needed for my ocr jobs. 
In my current pipeline, I use Tesseract's layout analysis to extract word coordinates from the image and perform OCR on every image patch. I do this because the domain of my documents differ a lot from the documents used to train Tesseract (Wikipedia?) and I don't want that the recognition of a word is influenced by its predecessor.

The architecture of the workflow is roughly like this:
![ocrflow](https://user-images.githubusercontent.com/2395900/36096103-23179ee2-0ff5-11e8-9ab3-f4617ed48280.png)

On average, the images have 50px height and 72px width.

| setup | n_tesseract_instances | OpenMP Threads | Duration | OEM | Comment
| ------------- | ---------------- | ----------------------- | --------------------- |------- | ------------- |
| 6000 images (one word each) | 4 | 4 | 125s | RAW_LINE | long processing time due to thread switching overhead? |
| 6000 images (one word each) | 2 | 4 | 11s | RAW_LINE |  too slow |
| 6000 images (one word each) | 4 | 2 | 9.4s | RAW_LINE |  too slow |
| 6000 images (one word each) | 4 | 1 | 10.2s | RAW_LINE |  too slow |
| 6000 images (one word each) | 8 | 1 | 11.7s | RAW_LINE |  too slow |
| 6000 images (one word each) | 2 | 2 | 10.3s | RAW_LINE |  too slow |
| 1 image (6000 words) | 1 | 2 | 18.9s | AUTO_OSD |  too slow |
| 1 image (6000 words) | 1 | 4 | 14.1s | AUTO_OSD |  too slow |

To control the number of OpenMP threads I used the environment variable OMP_THREAD_LIMIT.
I was not able to increase the number of OpenMP threads above 4 (for example through OMP_NUM_THREADS, which seems to be ignored).
I've also tried to rebuild tesseract with ./configure --disable-openmp however it still used 4 threads.

Any recommendation on how to improve recognition speed  and criticism of the illustrated architecture would be highly appreciated :)
Furthermore I would like to know why --disable-openmp has no effect and how to increase the number of OpenMP threads.

**Comment by stweil** [comment]
Please read the [previous issues](https://github.com/tesseract-ocr/tesseract/issues?utf8=%E2%9C%93&q=OpenMP+) which include "OpenMP". They should answer at least most of your questions.

Generally your workflow will work best with OpenMP disabled, as you can distribute your work on single tesseract processes which occupy one CPU core each.

**Comment by amitdo** [comment]
>I would like to know why --disable-openmp has no effect

I don't know, but you can use `OMP_THREAD_LIMIT=1` instead.

>OMP_NUM_THREADS, which seems to be ignored).

Tesseract is blocking this variable.

>how to increase the number of OpenMP threads.

The code is built to work with 4 threads using OpenMP, more threads wont help.

**Comment by stweil** [comment]
One additional note: you did not say which `traineddata` was used in your workflow. Did you already use the [fasted data](https://github.com/tesseract-ocr/tessdata_fast)?

**Comment by mm-manu** [comment]
thanks for the quick and insightful  responses!
I currently use the "best" traineddata. Will definitely try the fast variant. (Although accuracy is as important as speed).

**Comment by stweil** [comment]
The current Tesseract executable only processes a single page at one time, so you need several instances running parallel.

**Comment by sonusainju** [comment]
Thanks for making that clear stweil. But how can I achieve faster recognition then? Doesn't having multiple instances of the api also mean having to load the training files multiple times and in my case I see that this initialization takes about three times more time than one OCR on an image (my images are pretty small - 40x20)

**Comment by mm-manu** [comment]
you can pre-initialize a certain amount of workers and distribute your ocr jobs among them.

**Comment by mooncrater31** [comment]
@amitdo  I tried : 
```
tesseract myshit.png stdout -l eng --psm 6 OMP_THREAD_LIMIT=1
read_params_file: Can't open OMP_THREAD_LIMIT=1
Warning: Invalid resolution 0 dpi. Using 70 instead.
Tomorrow, and
tomorrow, and
tomorrow; creeps
in this petty pace
from day to day,
until the last syll-
able of recorded
time. And all our
yesterdays have
lighted fools the
way to dusty


```
Can you give the exact format of the command?
