### ISSUE TITLE
git clone https://github.com/tesseract-ocr/tesseract/    fails

### ISSUE THREAD

**Issue by smartinsightsfromdata** [tesseract-ocr/tesseract#1324]
### Environment
OSX 10.13.3
git 2.16.2 installed with homebrew

Cloning tesseract to compile from source, as per instructions [here](https://github.com/tesseract-ocr/tesseract/wiki/Compiling)

### Current Behavior:
```
e$ git clone https://github.com/tesseract-ocr/tesseract/
Cloning into 'tesseract'...
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```
### Expected Behavior:
Usual git clone behaviour: tesseract folder created with source code

**Comment by zdenop** [comment]
This is not tesseract isssue that your local git command fails...
