### ISSUE TITLE
Tesseract should not exit when init fails

### ISSUE THREAD

**Issue by jeroen** [tesseract-ocr/tesseract#1334]
I maintain the tesseract bindings for R. 

When the user passes an unsupported option to `api->Init()`, tesseract immediately quits/crashes the entire process. This should never happen for a c++ library; it should just throw an error or return NULL so we can deal with it.

```r
> library(tesseract)
> tesseract(options = c(foo = "bar"))
Error setting param foo
## QUITS R PROGRAM
```
Is there an option to make tesseract throw an error when an invalid parameter is set? Example:

```cpp
#define USE_STD_NAMESPACE
#include <baseapi.h>
#include <allheaders.h>
#include <genericvector.h>

int main(){
  GenericVector<STRING> names;
  GenericVector<STRING> values;
  names.push_back("foo");
  values.push_back("bar");

  tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
  if (api->Init(NULL, "eng",  tesseract::OEM_DEFAULT, NULL, 0, &names, &values, false))
    printf("Failed init\n");
  printf("cleaning up\n");
  api->End();
  delete api;
}

```

Compile using

```sh
clang++ main.cpp $(pkg-config --cflags --libs Tesseract)
```

### Environment

* **Tesseract Version**: 3.05.01
* **Platform**: any

### Current Behavior:

Quit process.

### Expected Behavior:

Throw an error.

**Comment by stweil** [comment]
A closely related problem is how to report the kind of error which was detected. "Failed init" might be acceptable for some special applications, but that error message is too unspecific for a general application like the `tesseract` program. There can be lots of different reasons, and users should be informed what caused the problem. Printing a precise error message somewhere deep in the call stack solves that for `tesseract`, but not for an API.

**Comment by jeroen** [comment]
Why not just throw a C++ exception that we can catch in the application to get the error message?

**Comment by stweil** [comment]
That would be the natural solution for the C++ API. But what about the C API?

**Comment by jeroen** [comment]
If you want to support that, you could make init return an errno integer. Possibly provide a `errstr()` to convert these to human readable error strings.

However I think the most important thing is to convert the cpp code to throw exceptions instead of `exit()`. I think this will retain the current behavior from a C api because the exception, if uncaught, prints the error and then exits. But it does give applications an option to catch the problem by wrapping it into c++ tryCatch.

**Comment by jeroen** [comment]
Alternatively you can allow for setting a messages callback. Let me open a separate issue for this.

**Comment by Shreeshrii** [comment]
Also see related post by @jeroen in the forum

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/chq7Yu17ROc/GdhUqZHoBAAJ

**Comment by amitdo** [comment]
The core of Tesseract is written by Googlers, mainly by Ray Smith.

https://google.github.io/styleguide/cppguide.html#Exceptions

>we need to advise against exceptions in Google open-source projects as well.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/cb0c024a6f92fd04c951add6cf7ff497625cfda0/src/ccmain/tessedit.cpp#L138-L143

**Comment by zdenop** [comment]
@amitdo: Nice catch. I wanted to replace it with `return false;`, but IMO failing to set param value is not reason for returning from function (or exit of all application)... 
Any objection to remove it?

**Comment by amitdo** [comment]
I think it's okay to remove the exit(1).

>tprintf("Error setting param %s\n", (*vars_vec)[i].c_str()); 

Should be replaced with:
>tprintf("Warning: The parameter '%s' was not found.\n", (*vars_vec)[i].c_str());

**Comment by zdenop** [comment]
Thanks.
