### ISSUE TITLE
Request: Reverse commit 173ad2b

### ISSUE THREAD

**Issue by Antagonistic** [tesseract-ocr/tesseract#1335]
#https://github.com/tesseract-ocr/tesseract/commit/173ad2bd0044c82973fe17b6f077e7202602cb99

Hi,  I would like to request that we hold off on this change for now.  This change does negatively affect my workflow.  Let me explain:

While the LSTM process gives me MUCH better results than the old mode, at this point in time makebox gives crazy results.  My workflow involves a loop of scanning a document, segmenting, checking results, results that are wrong I create box files, turn into lstmf files, feed back into training, process more documents and repeat.  Training JUST off of automatically created text has not given me the results I seek on these documents, but it does mean I train and use both tess3 and tess4 data, the latter for processing, the former for its makebox.  In some cases I have found that tess3 can even outperform tess4 even, simply because of the ability to set a whitelist, a feature tess4 still does not support. (but something I have worked around wiith +- training to REMOVE characters)

While I can have an installation of tess3 alongside tess4, I feel that depreciating at this stage without better makebox and whitelist support for tess4, you will lose possible functionality without replacement.

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesseract/commit/349de8b7397454681d1af7f174c8c7b48efe61eb

* Restore support for the legacy engine

It is still needed to get text attributes which are unsupported by the
LSTM engine, and it also has better recognition rates for some texts.

**Comment by Antagonistic** [comment]
Ah, apologies and thank you, I saw the depreciating commit but not the restoring commit.

I'll close the issue.
