### ISSUE TITLE
JRE Fatal Error while working with libtesseract.so

### ISSUE THREAD

**Issue by laviua** [tesseract-ocr/tesseract#134]
I have created java web controller with tesseract.
If I use windows libraries - no errors, but in linux sometimes I get a fatal error

> Problematic frame:
[libtesseract.so+0x22a730]  tesseract::HistogramRect(unsigned char const*, int, int, int, int, int, int, int*)+0x70

> Stack: [0x00007f2d040d2000,0x00007f2d041d3000],  sp=0x00007f2d041cdf20,  free space=1007k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libtesseract.so+0x22a730]  tesseract::HistogramRect(unsigned char const*, int, int, int, int, int, int, int*)+0x70

> Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  net.sourceforge.tess4j.TessAPI1.TessBaseAPIGetUTF8Text(Lnet/sourceforge/tess4j/ITessAPI$TessBaseAPI;)Lcom/sun/jna/Pointer;+0
j  net.sourceforge.tess4j.Tesseract1.getOCRText(Ljava/lang/String;I)Ljava/lang/String;+43
j  net.sourceforge.tess4j.Tesseract1.doOCR(Ljava/util/List;Ljava/lang/String;Ljava/awt/Rectangle;)Ljava/lang/String;+69
j  net.sourceforge.tess4j.Tesseract1.doOCR(Ljava/util/List;Ljava/awt/Rectangle;)Ljava/lang/String;+4
j  net.sourceforge.tess4j.Tesseract1.doOCR(Ljava/awt/image/BufferedImage;Ljava/awt/Rectangle;)Ljava/lang/String;+6
j  net.sourceforge.tess4j.Tesseract1.doOCR(Ljava/awt/image/BufferedImage;)Ljava/lang/String;+3

**Comment by zdenop** [comment]
We do not provide support for tesseract wrappers[1]. Please use tesseract user forum.
[1] https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice

**Comment by laviua** [comment]
I'm not sure that an issue with java wrapper.
But ok. I'll take a look at java wrapper and how it works with pointers in HistogramRect.
Thanks

**Comment by zdenop** [comment]
If you are able to replicate problem with tesseract executable on linux I can try to find reason/solution. Otherwise please use tesseract user forum. There are people that use tesseract in java, so they can provide you support.
