### ISSUE TITLE
Access Violation Exception is coming in Tesseract

### ISSUE THREAD

**Issue by njani7** [tesseract-ocr/tesseract#1344]
Team,

When i try do OCR in Tesseract using Hindi Language , I am getting following error.

Access Violation Exception. 
m_tesseractOCREngine = new TesseractEngine(TesseractTessData, m_LanguageList, EngineMode.Default);

------------------------

### Windows 10 OS
Tesseract Version :3.0.2.0
Platform : 64 Bit

### Current Behavior:
I am getting following error while i select Hindi Language as OCR Option.
'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

Problem is in hin.traineddata file. 

Expected Behavior:
It should allow to load Tesseract  engine without problem.

**Comment by zdenop** [comment]
We do not provide support for 3rd party project. Please use tesseract user forum for it. But version 3.0.2 is tool old.

**Comment by Shreeshrii** [comment]
New Windows binaries can be downloaded from

https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-
setup-4.0.0-alpha.20180109.exe

More details are available from https://github.com/UB-Mannheim
/tesseract/wiki

This will work well with the latest traineddata files from
https://github.com/tesseract-ocr/tessdata_fast

You will get better accuracy for Hindi from this.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
