### ISSUE TITLE
 "/" is added for filenames even on Windows

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1345]
Originally reported in forum at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/O81luGbEbHI/flBHt7OYDAAJ

> The thing is that the training software adds a "/" instead of a "\\".
I've looked on unicharset_training_utils.cpp, in the line 166, the "/" is added without taking care if the command is used on Windows or Linux.

https://github.com/tesseract-ocr/tesseract/blob/2633fef0b6ac9b616eae3d457bf796076eb8f43c/training/unicharset_training_utils.cpp#L145-147

https://github.com/tesseract-ocr/tesseract/blob/2633fef0b6ac9b616eae3d457bf796076eb8f43c/training/unicharset_training_utils.cpp#L168-170

There also seem to be instances in https://github.com/tesseract-ocr/tesseract/blob/master/training/lang_model_helpers.cpp

**Comment by Sheo31** [comment]
Thanks, I was going to do it :)

Jehan

**Comment by amitdo** [comment]
Failed to load script unicharset from:C:\Program Files (x86)\Tesseract-OCR\training/Latin.unicharset

[I'm a Linux guy]
I think that Windows can handle forward slash as path separator.

**Comment by stweil** [comment]
Yes. Although it is widely unknown, all versions of MSDOS and Windows work with `/` as a directory separator.

**Comment by Sheo31** [comment]
So the problem is not that.
I'll see why I can't load the file.

**Comment by Shreeshrii** [comment]
Are you sure you have  Latin.unicharset in the right path? Are you able to open it in a text editor?

Sometimes if file is not downloaded correctly you may get an error.

**Comment by Sheo31** [comment]
OK, so I downloaded Latin.unicharset again and it worked !
