### ISSUE TITLE
Extracting Text from Product image / Photos taken from a Camera

### ISSUE THREAD

**Issue by gkdeepasri** [tesseract-ocr/tesseract#1350]
### Environment

* **Tesseract Version**:  3.04.01
* **Commit Number**: 
* **Platform**:  Ubundu

### Current Behavior:
Tesseract is unable to read cursive text from the product labels (image/photos) like Kelloggs, Nivea, etc
### Expected Behavior:
To read all texts of different sizes, fonts and cursive styles on the product image files / photos. 
### Suggested Fix:
If the tesseract english engine/ML is trained to recognise such texts of different sizes, fonts and cursive styles would be ideal. Also please let us know some sample input files that need to be prepared for the above.
![1_400](https://user-images.githubusercontent.com/36851648/36674805-250b7244-1b2d-11e8-94bc-27b2d4f40f24.png)

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr).
