### ISSUE TITLE
Tesseract outputs empty string for absolutely evey image

### ISSUE THREAD

**Issue by zirikatzaile** [tesseract-ocr/tesseract#1352]
### Environment
* **Tesseract Version**: tesseract 4.00.00alpha leptonica-1.73
* **Commit Number**: 
* **Platform**: Linux 64.bit
### Current Behavior:
> tesseract storage/app/tmp/180e4a91ef3cfb0162180dd597952a70.jpeg stdout -l spa
tesseract: symbol lookup error: /usr/lib/libtesseract.so.4: undefined symbol: pixGenerateHalftoneMask

### Expected Behavior:
Ouput at least some text, but not just empty

Recently updated. Before updating to 4.00.00alpha everything worked

**Comment by amitdo** [comment]
You should update leptonica to 1.74 or higher.

**Comment by zirikatzaile** [comment]
How should I do that ? I mean, I just have following Debian packages installed

```
ii  libtesseract-data                   3.04.01-6                    all          Development files for the tesseract command line OCR tool
ii  libtesseract3                       3.04.01-6                    amd64        Tesseract OCR library
ii  libtesseract4                       4.00~git2188-cdc35338-5      amd64        Tesseract OCR library
ii  tesseract-ocr                       4.00~git2188-cdc35338-5      amd64        Tesseract command line OCR tool
ii  tesseract-ocr-eng                   4.00~git15-45ed289-6         all          tesseract-ocr language files for English
ii  tesseract-ocr-osd                   4.00~git15-45ed289-3         all          tesseract-ocr language files for script and orientation
ii  tesseract-ocr-spa                   4.00~git15-45ed289-6         all          tesseract-ocr language files for Spanis
```

And I do not find a separated leptonica package.  All the above packages are up2date in debian testing

**Comment by amitdo** [comment]
It's possible that the Debian  package has a bug.
CC: @jbreiden

**Comment by Shreeshrii** [comment]
https://packages.debian.org/buster/tesseract-ocr

shows  dep: liblept5 <https://packages.debian.org/buster/liblept5>

You could also try with newer version in
https://packages.debian.org/sid/tesseract-ocr


>

**Comment by Shreeshrii** [comment]
After using dpkg, run the following command to install the dependencies :

sudo apt-get -f install

**Comment by zirikatzaile** [comment]
Thanks a lot @Shreeshrii  ! got it working again with the Sid packages

```
[root@node01 ~]# tesseract --version
tesseract 4.00.00alpha
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.2) : libpng 1.6.24 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.6.1 : libopenjp2 2.1.0
```

**Comment by Shreeshrii** [comment]
Good. You can close the issue.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by jbreiden** [comment]
Which Linux distribution are you running?

**Comment by zirikatzaile** [comment]
I closed yesterday the issue, being solved thanks to @Shreeshrii . Anyway as I said, if it helps you :  Debian testing. And as @Shreeshrii told me, for tesseract I am using unstable (sid).
