### ISSUE TITLE
Tesseract outputs empty files for valid png image

### ISSUE THREAD

**Issue by pager72** [tesseract-ocr/tesseract#1361]
I have tesseract installed on gentoo linux with all its components enabled. Heres what I do to run it

> $ tesseract test.png out
> [DS] Profile file not available (tesseract_opencl_profile_devices.dat); performing profiling.
> 
> [DS] Device: "AMD CARRIZO (DRM 3.23.0 / 4.15.6-gentoo, LLVM 5.0.1)" (OpenCL) evaluation...
> [OD] write binary[kernel-AMD_CARRIZO_(DRM_3.23.0___4.15.6-gentoo,_LLVM_5.0.1).bin] successfully
> [DS] Device: "AMD CARRIZO (DRM 3.23.0 / 4.15.6-gentoo, LLVM 5.0.1)" (OpenCL) evaluated
> [DS]          composeRGBPixel: 0.060458 (w=1.2)
> [DS]            HistogramRect: 0.032581 (w=2.4)
> [DS]       ThresholdRectToPix: 0.018510 (w=4.5)
> [DS]        getLineMasksMorph: 0.014743 (w=5.0)
> [DS]                    Score: 0.307755
> 
> [DS] Device: "(null)" (Native) evaluation...
> [DS] Device: "(null)" (Native) evaluated
> [DS]          composeRGBPixel: 0.041112 (w=1.2)
> [DS]            HistogramRect: 0.076788 (w=2.4)
> [DS]       ThresholdRectToPix: 0.020729 (w=4.5)
> [DS]        getLineMasksMorph: 0.188474 (w=5.0)
> [DS]                    Score: 1.269281
> [DS] Scores written to file (tesseract_opencl_profile_devices.dat).
> [DS] Device[1] 1:AMD CARRIZO (DRM 3.23.0 / 4.15.6-gentoo, LLVM 5.0.1) score is 0.307755
> [DS] Device[2] 0:(null) score is 1.269281
> [DS] Selected Device[1]: "AMD CARRIZO (DRM 3.23.0 / 4.15.6-gentoo, LLVM 5.0.1)" (OpenCL)
> Tesseract Open Source OCR Engine v3.05.01 with Leptonica

# **attached files:** 
png image ![test](https://user-images.githubusercontent.com/37059493/36958719-a2075ba4-1ff2-11e8-914f-1f14b77d74aa.png)

tesseract --print-parameters [print-parameters.txt](https://github.com/tesseract-ocr/tesseract/files/1779595/print-parameters.txt)

tesseract -v [version-info.txt](https://github.com/tesseract-ocr/tesseract/files/1779596/version-info.txt)

I could not install latest tesseract version 4 because it does not compile, it fails to build, however the version I am using is stable. I hope I get some pointers on how to remedy this.

**Comment by pager72** [comment]
I have tesseract installed on gentoo linux with all its components enabled. Heres what I do to run it

> $ tesseract test.png out.txt 
> 
> [DS] Profile read from file (tesseract_opencl_profile_devices.dat).
> [DS] Device[1] 1:AMD CARRIZO (DRM 3.23.0 / 4.15.6-gentoo, LLVM 5.0.1) score is 0.318045
> [DS] Device[2] 0:(null) score is 1.448047
> [DS] Selected Device[1]: "AMD CARRIZO (DRM 3.23.0 / 
4.15.6-gentoo, LLVM 5.0.1)" (OpenCL)
> Tesseract Open Source OCR Engine v3.05.01 with Leptonica
> Page 1
> 

attached file: tiff image to be ocr'ed, tesseract --print-parameters and tesseract -v




attached files: 
png image ![test](https://user-images.githubusercontent.com/37059493/36958719-a2075ba4-1ff2-11e8-914f-1f14b77d74aa.png)

tesseract --print-parameters [print-parameters.txt](https://github.com/tesseract-ocr/tesseract/files/1779595/print-parameters.txt)

tesseract -v [version-info.txt](https://github.com/tesseract-ocr/tesseract/files/1779596/version-info.txt)

I could not install latest tesseract version 4 because it does not compile, it fails to build, however the version I am using is sable. I hope I get some pointers on how to remedy this.

**Comment by stweil** [comment]
I‌ suggest to disable OpenCL support when building Tesseract (any version) unless you want to improve the OpenCL code. And of course it should be possible to build Tesseract 4.

**Comment by Shreeshrii** [comment]
>I could not install latest tesseract version 4 because it does not
compile, it fails to build,

What error are you getting?

**Comment by pager72** [comment]
I will rebuild version 4 and post build log, however I must say disabled opencl has resolved the issue, and I find tesseract a poor ocr engine and Im sure acrobat is better.

**Comment by Shreeshrii** [comment]
Tesseract works quite well, specially for English. The problem could be
related to using an incompatible traineddata file or --oem mode. Please
provide a test input file on which you got poor results.

**Comment by pager72** [comment]
Strangely disabling opencl for version 4 permitted the build without failure. However here are some things I found, previous experience with acrobate says the box label "swanson" will be ocr'ed, not so with tesseract. Don't get me wrong I really like it being open source and also support to write text searchable pdfs, which is what I do, but maybe I should disable training support and rebuild for better results?

Test image:
![test](https://user-images.githubusercontent.com/37059493/36962131-2be16cd8-2003-11e8-81d5-17a813511f2b.png)

**Comment by stweil** [comment]
Disabling training would not change the results. Using data from http://github.com/tesseract-ocr/tessdata_fast would (unless you already used that).

**Comment by pager72** [comment]
Is there a guide on how to use this?

**Comment by Shreeshrii** [comment]
>disabled opencl has resolved the issue

Then please close the issue.
