### ISSUE TITLE
Zero's being interpreted as O

### ISSUE THREAD

**Issue by astutesoftware** [tesseract-ocr/tesseract#1363]
Please see this image here (A prehistoric captcha image)
https://imgur.com/a/Agl71
Zero's being interpreted as O

### Environment

* **Tesseract Version**: 1.0.10
* **Commit Number**: 
* **Platform**: Windows 64 bit

### Current Behavior:
OETOK
### Expected Behavior:
0ET0K
### Suggested Fix:
When doing a OCR probably it can check the width of the character set and figure out what is a zero and what is a O.
In this case this is a captcha i am solving to automate some daily stuff. Quite useful and saves me some man hours. But my script would do at least half a dozen mistakes because of the zero O thing and finally get me logged in.
What i have observed is if it an image containing the same character set then based on the width of the characters we can figure out if its a Zero or a O. When doing manually thats what our brain does.
Maybe mimic the same?

**Comment by Shreeshrii** [comment]
>Tesseract Version: 1.0.10

Stable version is 3.05.01
Preview version is 4.0.0-beta.1

Try with those and report.

**Comment by amitdo** [comment]
It does look more like zeros rather than Os.

**Comment by Shreeshrii** [comment]
@astutesoftware 

If using tesseract 4.0.0-beta.1
you can finetune minustrain with a restricted unicharset and font similar to the ones you need.

Test with the attached traineddata file. 

[eng-numCAPS.zip](https://github.com/tesseract-ocr/tesseract/files/1851425/eng-numCAPS.zip)

**Comment by Shreeshrii** [comment]
This is another instance of issue reported in https://github.com/tesseract-ocr/tesseract/issues/733

@zdenop, please close.
