### ISSUE TITLE
the unicharset_extractor impact accuracy from Arabic like language.

### ISSUE THREAD

**Issue by nkmamatjan** [tesseract-ocr/tesseract#1364]
how can I joined the characters in unicharset_extractor ,for continuous words from Arabic like language?tesseract accuracy can be improved, if the unicharset_extractor can joined characters.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by zdenop** [comment]
Please follow rules for posting issues: ask for support on tesseract user forum.
