### ISSUE TITLE
Configure fails

### ISSUE THREAD

**Issue by anshul1912** [tesseract-ocr/tesseract#1366]
### Environment

* **Tesseract Version**: Master branch
* **Commit Number**: MSVC 8.0 was released in 2005 and we don't support it.
* **Platform**: Linux

### Current Behavior:
Configuration failed

### Expected Behavior:
Configuration should Pass.

### Suggested Fix: Unknown

Following error were seen:
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
./configure: line 4234: syntax error near unexpected token `-mavx,'
./configure: line 4234: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'

**Comment by stweil** [comment]
Please read [previous issues](https://github.com/tesseract-ocr/tesseract/issues?utf8=%E2%9C%93&q=%22syntax+error+near+unexpected+token%22) and close this one.
