### ISSUE TITLE
Italic info in hocr output

### ISSUE THREAD

**Issue by niksedk** [tesseract-ocr/tesseract#1371]
I cannot find any italic info In Tesseract 4.00.00alpha hocr output.

Tesseract 3.x included this info via the `em` tag.

It would be very helpful if this could be added again in some way.

**Comment by stweil** [comment]
That's a missing feature of the new LSTM engine: it does not support attributes like bold, italic and more.

Tesseract 4 still supports the old OCR engine as long as you use traineddata files which include the necessary information. The files from https://github.com/tesseract-ocr/tessdata will work for you.

**Comment by niksedk** [comment]
@stweil: thx for the info :)
It it likely this feature will be added to the new LSTM engine at some point?

**Comment by stweil** [comment]
Who knows? I don't – maybe @theraysmith has plans to enhance the LSTM engine in that direction.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/1074#issuecomment-327814244

**Comment by amitdo** [comment]
@zdenop, please close this issue.
