### ISSUE TITLE
Make training issue 

### ISSUE THREAD

**Issue by 16seven** [tesseract-ocr/tesseract#1374]
### Environment

* **Tesseract Version**: 4.0.0-beta.1-16-g4b2bea7
* **Commit Number**: 4b2bea
* **Platform**: CentOS Linux 7 64-bit

### Current Behavior:
Install tesseract from git source
Tesseract tools was installed fine
But compile training tools when exec
`make training`
occur
`boxchar.cpp:67:42: error: 'U_RIGHT_TO_LEFT_ISOLATE' was not declared in this scope
         dir == U_ARABIC_NUMBER || dir == U_RIGHT_TO_LEFT_ISOLATE) {`

### Suggested Fix:
Remove the code? 
` || dir == U_RIGHT_TO_LEFT_ISOLATE`
Does have any effect?

**Comment by godofcheerup** [comment]
Hi . I have never seen before 4.00 - beta ...

Are you sure beta??? tesseract is yet Alpha

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/releases/tag/4.0.0-beta.1

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
>>Platform: CentOS Linux 7 64-bit

Do you have the additional dependencies required for building training tools?

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesseract/issues/1179#issuecomment-363057346

>>The training tools need icu version 52 and up. The icu version in RHEL & CentOS 7 is 50.

**Comment by 16seven** [comment]
thx @Shreeshrii

**Comment by Shreeshrii** [comment]
Alex  compiled an rpm package with tesseract-ocr for CentOS, Fedora, ScientificLinux, OpenSuse.

https://build.opensuse.org/project/show/home:Alexander_Pozdnyakov

@16seven  Please check if it works on Centos7.

**Comment by stweil** [comment]
`configure.ac` should detect whether `make training` is supported. Currently it includes a [check](https://github.com/tesseract-ocr/tesseract/blob/master/configure.ac#L436) which wrongly assumes that there is a usable ICU package installed.

**Comment by amitdo** [comment]
The issue was reported before 98747b37e was merged.

**Comment by amitdo** [comment]
On which OS did you test this?

**Comment by stweil** [comment]
The build was done on a Red Hat Enterprise Linux Server release 7.5.

**Comment by JensHumrich** [comment]
The issue still seems to exist. Any solutions yet?

**Comment by zdenop** [comment]
What do you mean with "the issue still exist"? Is there issue with recent version of ICU (>52.1)?

**Comment by JensHumrich** [comment]
If icu is below 52.1, no error is thrown, when configuring. The error appears first during make-ing the training.

**Comment by zdenop** [comment]
So why you asks for solution? amitdo already wrote you need to have ICU >= 52.1

**Comment by JensHumrich** [comment]
The missing requirements should be found, but is not. The missing ICU libraries should be complained during configure. The option to make training should not be displayed. Instead a warning: "Missing ICU..." 
There have been some lines added to the configure check, which are not working correctly.

**Comment by stweil** [comment]
See pull request #2211 for a fix of this issue.

**Comment by JensHumrich** [comment]
Thanks a lot @stweil  for your contribution. This is the solution I was hoping for.

**Comment by abneetOSS** [comment]
@JensHumrich If you have trouble with ICU version you can add remi repo for CentOS 7 and install libicu62. I was having similar issue as i was not able to make training because icu <=51.2 in release4.1.1
`$wget http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
$rpm -Uvh remi-release-7.rpm`
>>
`$vim /etc/yum.repos.d/remi.repo `

>> find enable=0 and make it as enable=1
>>this will enable the repo

`$yum install libicu62-devel`
then you can do `./configure`
