### ISSUE TITLE
Release bug fixes for 3.05 as 3.05.02

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1376]
Please see request at https://github.com/tesseract-ocr/tesseract/pull/585#issuecomment-372151304

Are there any other changes that need to be backported to 3.05 before this?

@zdenop Anything we can do to help in this?

**Comment by dylanjw** [comment]
:+1:

**Comment by amitdo** [comment]
IMO, we should focus on the final release of 4.0.0.

**Comment by Shreeshrii** [comment]
I don't use 3.05. However the 3.05.01 release has a bug related to leptonica linking. At a minimum a bug fix release should be done so that the fix which is already there can be applied. 
It is referred to in the comment above.

**Comment by amitdo** [comment]
The problem I see with new 3.05.xx release is that it might encourage people to use 3.05 instead of moving to 4.0.0...

**Comment by amitdo** [comment]
3.05.02 was released. It includes the fix for #585 (https://github.com/tesseract-ocr/tesseract/commit/4ccef1087122ed).

**Comment by Shreeshrii** [comment]
Thank you!
