### ISSUE TITLE
Failed to Run Tesseract on AWS EC2

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#1377]
Hi,

i have and AWS EC2 instance **(OS is Ubuntu 14.04**) with **leptonica-1.75.3** and **tesseract 4.0.0-beta.1-17-g79c6fa6**

i followed [this article](https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32) to install and compile leptonica the tesseract, (which always worked)

when i type `tesseract -v` i get the following

```
tesseract 4.0.0-beta.1-17-g79c6fa6
 leptonica-1.75.3
  libjpeg 6b : libpng 1.2.50 : zlib 1.2.8

 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found SSE
```
and then when i detect by: `tesseract image.jpg results -l eng --tessdata-dir ./tessdata`
 any image i get the following error:

```
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
Tesseract Open Source OCR Engine v4.0.0-beta.1-17-g79c6fa6 with Leptonica
Error during processing.
```

what could be the problem?
Thanks in advance

**Comment by Shreeshrii** [comment]
Maybe your libjpeg is too old.

Have you tried a png or a tif?

I use libjpeg 8d (libjpeg-turbo 1.3.0)

**Comment by ibr123** [comment]
Thanks,
mine are `libjpeg 6b : libpng 1.2.50 : zlib 1.2.8`
could you please tell me what is the latest dependencies?

**Comment by jbreiden** [comment]
Looks to me like `libtiff-dev` (or is it `libtiff4-dev` ?) package was missing when Leptonica was built.

**Comment by ibr123** [comment]
i installed any dependency i know about that contained anything with images such `libpng-dev` or `libtiff4-dev` and the trick was to install Leptonica again and build it after the dependencies were installed, then it worked, thanks @Shreeshrii @jbreiden
Since we on the subject, i noticed that the argument --oem doesn't exist anymore what i run the command `tesseract --help`, is that normal?
also what is the best treainddata for the new beta version for tesseract?

**Comment by Shreeshrii** [comment]
​​>  i noticed that the argument --oem doesn't exist anymore what i run the command tesseract --help, is that normal? 
> what is the best treainddata for the new beta version for tesseract?

If you want to OCR, **tessdata_fast**

If you want to do finetune/add a layer training, **tessdata_best**

If you need to use the legacy tesseract engine with --oem 0 or --oem 2, **tessdata**

**tesseract --help-extra** will show all the advanced options (such as --oem).

**Comment by amitdo** [comment]
>i noticed that the argument --oem doesn't exist anymore what i run the command tesseract --help, is that normal?

`--oem` is still valid. See `--help-extra`.

**Comment by ibr123** [comment]
Thanks
