### ISSUE TITLE
Remaining compiler warnings in 479fe9c

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#138]
479fe9c37055ecf8004f4eeb9bcb8dcc7c1e89c5 still results in these warnings (only warnings are shown):  http://dpaste.com/3DWZ4VP

Created with
```
(git pull)
./autogen.sh
./configure --enable-debug
make &>make.log
agrep -d "^/bin/sh" warning make.log > make-warnings.txt
(uploaded to http://dpaste.com/3DWZ4VP )
```

ProTip: I used agrep: https://github.com/Wikinaut/agrep because the option "-d" allows to define a "record" which is then printed, if if a match within is found (here: "warning").

**Comment by Wikinaut** [comment]
@stweil Stefan, hi. I identified some more remaining warnings. See https://github.com/tesseract-ocr/tesseract/issues/138#issue-115242227

**Comment by stweil** [comment]
@Wikinaut Most of those warnings also occur in my builds and are less interesting (like -Wsign-compare which can be ignored IMHO), but there are also some warnings which need further investigations (-Warray-bounds).

**Comment by Wikinaut** [comment]
@stweil I informed you, and listed the remaining warnings, because it looked as if you were "hunting" these last (moretheless cosmetic) problems. I really would like to see them disappearing one after the other... :-))
