### ISSUE TITLE
In the replacing top layer. (tesseract 4.0)

### ISSUE THREAD

**Issue by godofcheerup** [tesseract-ocr/tesseract#1382]
------------------------

### Environment

* **Tesseract Version**:  4.00 Alpha
* **Commit Number**: 
* **Platform**: 

### Current Behavior:

inplat@inplat-System-Product-Name:/usr/share/tesseract-ocr/4.00/tessdata/tesseract/training$ lstmtraining --debug_interval 100 --continue_from ~/tesstutorial/ko
r/kor.lstm --traineddata ~/tesstutorial/kortrain/kor/kor.traineddata --append_index 5 --net_spec '[Lfx512 O1c1]' --model_output ~/tesstutorial/kor/base  --train_listfile ~/tesstutorial/kortrain/kor.training_text.txt --eval_listfile ~/tesstutorial/koreval/kor.training_text.txt --max_iterations 3000> ~/tesstutorial/kor/basetrain.log
bash: 3000: 잘못된 파일 디스크립터

**Comment by godofcheerup** [comment]
I just want to replace top layer. such a phonemon take place

**Comment by Shreeshrii** [comment]
You need to make sure that you have the required starter traineddata and list of lstmf files.

Here is a bash script which can be used for replacing top layer. It is similar to the one for finetuning, just the lstmtraining command is changed.

However, you need to  review it fully and change for your language, training_text, fonts and paths where the files are.

[tesstrain_replacelayer.sh.txt](https://github.com/tesseract-ocr/tesseract/files/1806188/tesstrain_replacelayer.sh.txt)

**Comment by godofcheerup** [comment]
Thank U very much.

**Comment by godofcheerup** [comment]
Thank  you I replaced top-layer. But, 

I have a error message . "Can't encode transcription"

I also have an error like that https://github.com/tesseract-ocr/tesseract/issues/1012 ㅜㅜ

**Comment by godofcheerup** [comment]
Thank you for replying to @Shreeshrii
