### ISSUE TITLE
How to use tesseract 4 on Android applications?

### ISSUE THREAD

**Issue by rezaee** [tesseract-ocr/tesseract#1387]
I try to build tesseract4 for android, but when I use `ndk-build` in the main folder of tesseract it gives me this error message:

> Android NDK: Could not find application project directory !    
> Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
> /home/m/android-ndk-r16b/build/core/build-local.mk:151: *** Android NDK: Aborting    .  Stop.
> 

Why this happens and how can I fix it?

**Comment by AbdelsalamHaa** [comment]
Hi, @rezaee rezaee you have post this quasion quit some time ago , i assume that u already able to do it . if yes can u plz give me a step by step how to do it . i have used tesseract 4.0 with windows only but never try with Android . 
thanks in advance

**Comment by zdenop** [comment]
I am sorry but we do not provide support for mobile platforms (yes it is know that tesseract run on Android and IOS). 
Anyway - error itself has no connection to tesseract and it seem to me related to [Android build generally](https://stackoverflow.com/questions/14156596/ndk-cant-find-the-application-directory).
Please use tesseract user forum for asking question&support.
