### ISSUE TITLE
brew reinstall tesseract --HEAD Throws An Error

### ISSUE THREAD

**Issue by jsl303** [tesseract-ocr/tesseract#1389]
I'm trying to install Tesseract on High Sierra using home brew. However, I get an error below.
Is there any fix for this? Thanks for your help!
$ brew reinstall tesseract --HEAD
==> Reinstalling tesseract 
==> Cloning https://github.com/tesseract-ocr/tesseract.git
Updating /Users/user/Library/Caches/Homebrew/tesseract--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/tesseract/HEAD-023e1b3
Last 15 lines from /Users/user/Library/Logs/Homebrew/tesseract/02.configure:
2018-03-14 23:54:58 -0400

./configure
--disable-dependency-tracking
--prefix=/usr/local/Cellar/tesseract/HEAD-023e1b3

./configure: line 5: .: filename argument required
.: usage: . filename [arguments]

READ THIS: https://docs.brew.sh/Troubleshooting

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:210:in `raise_api_error': GitHub  (GitHub::AuthenticationFailedError)
The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'

**Comment by balachandarsv** [comment]
I too faced the same issue. 
Editing the brew formula to point to the latest release of [4.0.0-beta.1](https://github.com/tesseract-ocr/tesseract/releases/tag/4.0.0-beta.1). You would be able to use the latest release of tesseract using brew. 

Update the formula with the values below

`url "https://github.com/tesseract-ocr/tesseract/archive/4.0.0-beta.1.tar.gz"`

`sha256 "122ded950050abba89897ce8cc9fe57b45149640c46d4baa5abfc7048d2e406a"`

**Comment by Shreeshrii** [comment]
Does the following require updating?

https://github.com/Homebrew/homebrew-core/blob/master/Formula/tesseract.rb

**Comment by balachandarsv** [comment]
Yes @Shreeshrii. Otherwise its difficult to install the latest release using brew. Its still pointing to the version 3.05.1

**Comment by Shreeshrii** [comment]
What about building head with the following ?

 head do
    url "https://github.com/tesseract-ocr/tesseract.git"
    resource "tessdata-head" do
      url "https://github.com/tesseract-ocr/tessdata_fast.git"
    end
  end

(I use windows, so can't test).

**Comment by zdenop** [comment]
It does not seem that error come from tesseract. Anyway current code is possible to [compile on Mac OS](https://github.com/tesseract-ocr/tesseract/issues/1453#issuecomment-429662370).
