### ISSUE TITLE
Update wikipedia page for tesseract ocr

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1390]
https://en.wikipedia.org/wiki/Tesseract_(software)

I will update the languages and scripts list.

Some info that needs updating:
---------------

Release|Version
-- | --
Stable release | 3.05.01 / June 1, 2017; 9 months ago[1]
Preview release | 4.00.00dev / November 24, 2016; 15 months ago[1]

If Tesseract is used to process right-to-left text such as Arabic or Hebrew, the results are ordered as though it is left-to-right text.[11]

Tesseract is suitable for use as a backend and can be used for more complicated OCR tasks including layout analysis by using a frontend such as OCRopus.[12]

**Comment by stweil** [comment]
I updated the preview release in the English Wikipedia. @zdenop, Wikidata automatically scans release and preview release information from GitHub. That requires that [4.0.0-beta.1](https://github.com/tesseract-ocr/tesseract/releases/tag/4.0.0-beta.1), 4.00.00dev and 4.00.00alpha are marked as pre-releases in GitHub. It would also be good to have a short release note for 4.0.0-beta.1 on GitHub.

**Comment by zdenop** [comment]
Can somebody prepare release notes ;-) ? I am sorry but I have no spare time..

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/4.0x-Changelog

This is probably too detailed for your purposes.

**Comment by stweil** [comment]
I'd keep it short for pre-releases and just take the text from the tags:

- 4.00.00alpha – Added new LSTM-based neural network line recognizer
- 4.00.00dev – Alpha code
- 4.0.0-beta.1 – Beta release for Ubuntu 18.04

**Comment by zdenop** [comment]
[This way](https://github.com/tesseract-ocr/tesseract/releases/tag/4.0.0-beta.1)?

**Comment by stweil** [comment]
Nearly. I'd repeat the release tag in the summary because that is what most other large projects do and because Wikidata also uses the summary to show the release name. So instead of "Beta release for Ubuntu 18.04", the summary could be as short as "4.0.0-beta.1", or it could be "4.0.0-beta.1 Release" as for the earlier releases.

**Comment by Shreeshrii** [comment]
Release | Version
-- | --
Stable release | 3.05.01 / June 1, 2017; 9 months ago[1]
Preview release | 4.0.0-beta.1 / March 10, 2018; 8 days ago[1]
