### ISSUE TITLE
Could not set option: include_page_breaks=1

### ISSUE THREAD

**Issue by trevdog94** [tesseract-ocr/tesseract#1391]
------------------------

### Environment
Working in a CentOS Virtual Desktop Environment inside of an Ubuntu 16.04 Docker Container. Here is the docker info:

Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 6
Server Version: 18.03.0-ce-rc3
Storage Driver: devicemapper
 Pool Name: docker-8:17-3113089-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 32.21GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /docker/devicemapper/devicemapper/data
 Metadata loop file: /docker/devicemapper/devicemapper/metadata
 Data Space Used: 27.36GB
 Data Space Total: 107.4GB
 Data Space Available: 80.01GB
 Metadata Space Used: 22.65MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.125GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67GiB

------------------------------------------------------------------------------------------------------------------
## Tesseract Version
tesseract 4.00.00alpha
 leptonica-1.74.4
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4

 Found AVX2
 Found AVX
 Found SSE

-------------------------------------------------------------------------------------------------------------------
### Current Behavior:
I am trying to run the following command:

tesseract -c include_page_breaks=1 <.txt list of input images> <output .txt file> --oem 3 --psm 6 

We are running tesseract on a batch of images and need the page breaks option so that we can split the output text file and attribute each block of text to its original input image 
However the page breaks option doesn’t appear to be recognized 
----------------------------------------------------------------------------------------------------------------- 
### Expected Behavior:
include_page_brakes parameter is successfully set and no error is observed.
------------------------------------------------------------------------------------------------------------------
### Suggested Fix:
Need to know why this error is occurring (maybe due to ocr engine used or maybe there is another paramater that can achieve the same behavior)

**Comment by Shreeshrii** [comment]
Please see

http://github.com/tesseract-ocr/tesseract/commit/aa6eb6bd466101a3b89880f87580471a7694359d

You may want to install the latest source from github tesseract.0.0-beta.1

**Comment by Shreeshrii** [comment]
@trevdog94 You should be able to split the output file by pages with the latest code. Please close this issue, if problem is solved.

**Comment by Shreeshrii** [comment]
@zdenop  Please close this issue.
