### ISSUE TITLE
make: *** [obj/local/armeabi/objs/tess/tessbaseapi.o] Error 1

### ISSUE THREAD

**Issue by rezaee** [tesseract-ocr/tesseract#1392]
I tried to copy the `tesseract 4` inside the `/home/m/tess/tess-two/jni/com_googlecode_tesseract_android/src` tess-two to compile it with the `ndk-build` for Android. But I got these result:

> 
> jni/com_googlecode_tesseract_android/tessbaseapi.cpp:550:31: error: assigning to
>       'PROGRESS_FUNC' (aka 'bool (*)(int, int, int, int, int)') from
>       incompatible type 'bool (void *, int, int, int, int, int)': different
>       number of parameters (5 vs 6)
>   monitor.progress_callback = progressJavaCallback;
>                               ^~~~~~~~~~~~~~~~~~~~
> jni/com_googlecode_tesseract_android/tessbaseapi.cpp:553:11: error: no member
>       named 'progress_this' in 'ETEXT_DESC'
>   monitor.progress_this = nat;
>   ~~~~~~~ ^
> jni/com_googlecode_tesseract_android/tessbaseapi.cpp:628:44: error: no matching
>       constructor for initialization of 'tesseract::TessPDFRenderer'
>   ...= new tesseract::TessPDFRenderer(c_output_path, nat->api.GetDatapath());
>            ^                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> jni/com_googlecode_tesseract_android/src/api/renderer.h:186:16: note: candidate
>       constructor (the implicit copy constructor) not viable: requires 1
>       argument, but 2 were provided
> class TESS_API TessPDFRenderer : public TessResultRenderer {
>                ^
> jni/com_googlecode_tesseract_android/src/api/renderer.h:186:16: note: candidate
>       constructor (the implicit move constructor) not viable: requires 1
>       argument, but 2 were provided
> jni/com_googlecode_tesseract_android/src/api/renderer.h:190:3: note: candidate
>       constructor not viable: requires 3 arguments, but 2 were provided
>   TessPDFRenderer(const char* outputbase, const char* datadir, bool textonly);
>   ^
> 3 errors generated.
> make: *** [obj/local/armeabi/objs/tess/tessbaseapi.o] Error 1
>

**Comment by zdenop** [comment]
We do not support custom/3rd party project. Please use tesseract user forum instead as stated in rules for posting issues

**Comment by rezaee** [comment]
@zdenop : What if I want to compile it without 3dparty(tess-two) for Android? Is there any tutorial for that?

**Comment by zdenop** [comment]
For android I am aware only about 3d party solution (tess-two).
I never heard that anybody to make android library directly from official
source code.

Zdenko

2018-03-16 10:47 GMT+01:00 rezaee <notifications@github.com>:
