### ISSUE TITLE
Tesseract fails for this image

### ISSUE THREAD

**Issue by earthat** [tesseract-ocr/tesseract#1395]
I am trying to recognise the number in this image but doesn't return anything. 

------------------------

### Environment

* **Tesseract Version**: <3.04-->
* **Platform**: <ubuntu 14.0->

![1](https://user-images.githubusercontent.com/11607018/37555076-f20ab564-2a07-11e8-8d74-2061865bf0fb.png)

**Comment by Shreeshrii** [comment]
@earthat  Try to install a newer version from https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr and test.

**Comment by Shreeshrii** [comment]
With tesseract4.0.0-beta.1 and with a modified image after preprocessing, tessdata and tessdata_best give the correct result.


![1395](https://user-images.githubusercontent.com/5095331/38135826-f56a2fc0-3437-11e8-948d-1c79b03749d1.jpg)

[1395-tessdata_fast-eng-1-jpg.txt](https://github.com/tesseract-ocr/tesseract/files/1863445/1395-tessdata_fast-eng-1-jpg.txt)
[1395-tessdata-eng-1-jpg.txt](https://github.com/tesseract-ocr/tesseract/files/1863446/1395-tessdata-eng-1-jpg.txt)
[1395-tessdata_best-eng-1-jpg.txt](https://github.com/tesseract-ocr/tesseract/files/1863447/1395-tessdata_best-eng-1-jpg.txt)

**Comment by earthat** [comment]
what preprocessing steps are considered

**Comment by Shreeshrii** [comment]
@earthat 

Increase dpi to 300, double image in size, invert, convert to black and white - see the resulting image.

See https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

Please close the issue.
