### ISSUE TITLE
Decimal separator missing if more than 7 digits ?

### ISSUE THREAD

**Issue by cedric-lemaitre-alyotech** [tesseract-ocr/tesseract#142]
The command tesseract seems to miss the decimal separator character if there is more than 7 digits in the decimal number : 
In the image below, tesseract detects 34056789 = not OK ! 
![bug_number1c](https://cloud.githubusercontent.com/assets/14107462/10996075/0e90e966-8482-11e5-9e8c-0f1289f250d0.png)
In the image below, tesseract detects 440.5678 => OK
![bug_number1c2](https://cloud.githubusercontent.com/assets/14107462/10996076/126ef0fa-8482-11e5-956a-ea61e87f5b99.png)

**Comment by amitdo** [comment]
With the latest snapshot in the git repo i get:
340.56789

**Comment by cedric-lemaitre-alyotech** [comment]
Ok I have recompiled with the tesseract-master.
And now, i got good result with 340.56789. Thanks...

But the problem is still there when i use more digits:
Example below is ok
![bug_number3a](https://cloud.githubusercontent.com/assets/14107462/11002130/3c4dc440-84ab-11e5-99fd-876e688f72bf.png)
Example below is returning 1234056789
![bug_number3b](https://cloud.githubusercontent.com/assets/14107462/11002155/58cd30b0-84ab-11e5-988c-7eab13438bee.png)

**Comment by zdenop** [comment]
see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice):
* For general questions and support please use the tesseract-ocr user forum.
* Read the wiki, search issues (also closed), search in the tesseract forum before you post your issues/question. Maybe it was solved already.
