### ISSUE TITLE
What is the (lang).xhegits & How can I make (lang).xhegits? 

### ISSUE THREAD

**Issue by godofcheerup** [tesseract-ocr/tesseract#1429]
Hi. I'm using tesstrain.sh (for rendering) 

with my korean fonts, and korean training_text

and In the /tmp --- folder I found the kor.xhegihts 
![xheights](https://user-images.githubusercontent.com/25732817/37881924-2b695a18-30d9-11e8-98f4-4f3b5dd21be7.png)
What is the kor.xhegiths?

this file affect rendering? 

Could I modify this file before rendering ?? 

Plz let me know~ 
------------------------

### Environment

* **Tesseract Version**:  4.00 Beta.1
* **Commit Number**: 
* **Platform**:  ubuntu 16.04.03 LTS

### Current Behavior: 
When using tesstrain.sh (for rendering) 

with my korean fonts, and korean training_text

and In the /tmp --- folder I found the kor.xhegihts

**Comment by zdenop** [comment]
Please respect rules for issue posting. Use tesseract user forum for asking questions.
