### ISSUE TITLE
Is it possible to train tesseract images which I owned && this issue is related ? tesseract logistic outputs not implemented yet! error

### ISSUE THREAD

**Issue by godofcheerup** [tesseract-ocr/tesseract#1437]
------------------------

### Environment

* **Tesseract Version**:  tesseract 4.00 Beta.1
* **Commit Number**: 
* **Platform**:  ubuntu 16.04.03 LTS

### Current Behavior:
To train tesseract by using images I owned, But, explanation is very poor
I made box/tif pair (in the terms of tesseract 4.00 )
I manage to use lstmtraining 
But, I meet the error  logistic outputs not implemented yet!

**Comment by Shreeshrii** [comment]
>Is it possible to train tesseract images which I owned 

No. Training from box/tiff pairs is currently NOT supported.

>logistic outputs not implemented yet!

As  the message says, current code does not support Logistic Outputs.

@zdenop Please close the issue.

**Comment by godofcheerup** [comment]
@Shreeshrii @zdenop Thank you I was sick . ㅜㅜ
