### ISSUE TITLE
Japanese gives an error

### ISSUE THREAD

**Issue by niksedk** [tesseract-ocr/tesseract#1441]
When running tesseract cmd line with Japanese (latest language file - tried both tessdata and tessdata_best) this error message is returned: `read_params_file: parameter not found: textord_tabfind_vertical_horizontal_mix`

Tesseract version: latest (2cc46fa6d456f9b49bc8a70036fa989a9c3baf50), build via `vcpkg install tesseract:x64-windows --HEAD`

**Comment by amitdo** [comment]
>Is it possible that some deprecated parameters are still there in config files?

Yes. 

That parameter was removed in #1418

**Comment by stweil** [comment]
It looks like we should add a testcase which simply loads all languages.

**Comment by niksedk** [comment]
@Shreeshrii: thx for the info,`tessdata_fast` does not crash :)

**Comment by stweil** [comment]
According to my tests, `jpn.traineddata and `jpn_vert.traineddata` in tessdata are the only files which need to be fixed. This is addressed by https://github.com/tesseract-ocr/tessdata/pull/92.

All other languages and also the files from tessdata_best and tessdata_fast look good.

**Comment by amitdo** [comment]
@stweil, what did you look for? Just `textord_tabfind_vertical_horizontal_mix`
or all removed parameters?

**Comment by stweil** [comment]
I first looked for all parameters used in tessdata and checked whether they still exist in tesseract git master. In addition I looked for `textord_tabfind_vertical_horizontal_mix` (which was the only problem reported from the first test) in tessdata_best and tessdata_fast.

Finally, I also checked all parameters in [tesseract/tessdata](https://github.com/tesseract-ocr/tesseract/tree/master/tessdata) (no problem found):

    cat $(ls tessdata/*configs/*|grep -v Make)|sort|uniq|grep -v '^#'|sed 's/[[:space:]].*//'|uniq|grep ^[a-z] >/tmp/parameters.txt
    for p in $(cat /tmp/parameters.txt|sort|uniq); do git grep -q $p || echo $p not found; done

**Comment by delonzhou** [comment]
@stweil I found the issue still exists in the latest tessdata_best.

**Comment by stweil** [comment]
You are right. See https://github.com/tesseract-ocr/tessdata_best/pull/28.
