### ISSUE TITLE
[Suggestion] "Training light" - Learning by doing - re-feeding a corrected text file to retrain tesseract

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#1442]
(probably something for https://github.com/tesseract-ocr/tesseract/issues/1423)

When I have a manually corrected text version (txt output file), my deep wish is to have an **easy** way to retrain tesseract, based upon the 1. first tesseract txt output and the related 2. manually corrected txt file.

I remember that I asked this question already some years ago. But now situation has changed (more and other developers, new algorithms).

Do you like the idea? Is it possible?

**Comment by stweil** [comment]
The idea is good, it is possible, but today the way is not easy. So there remains work to be done to make it easy.

**Comment by Wikinaut** [comment]
@stweil Can I help with a donation?

**Comment by stweil** [comment]
See http://gepris.dfg.de/gepris/projekt/394264782 (German).

**Comment by amitdo** [comment]
As @stweil already said, this feature was implemented years ago (fine tuning a lstm model). 

We should not keep this 'issue' open for the 'make it easy' part. PRs to this repo or to the tesstrain repo are welcomed.
