### ISSUE TITLE
"brew install --with-training-tools tesseract" doesn't work.

### ISSUE THREAD

**Issue by TonyDongLB** [tesseract-ocr/tesseract#1444]
When I using brew to install tesseract, it doesn't work, and I google it ,I try install it  from code,
- and it say ` line 17577: syntax error near unexpected token `LEPTONICA,'`  and I do installed pkg-config and LEPTONICA.
The brew information is: 
```
TonyMaster@MBP aclocal$ brew install --with-training-tools tesseract
==> Downloading https://github.com/tesseract-ocr/tesseract/archive/3.05.01.tar.gz
Already downloaded: /Users/apple/Library/Caches/Homebrew/tesseract-3.05.01.tar.gz
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/tesseract/3.05.01
==> make install
Last 15 lines from /Users/apple/Library/Logs/Homebrew/tesseract/03.make:
make[2]: *** [elst.lo] Error 63
make[2]: *** [bitvector.lo] Error 63
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.2.6b.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.2.6b.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[2]: *** [ccutil.lo] Error 63
make[2]: *** [clst.lo] Error 63
make[2]: *** [elst2.lo] Error 63
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting
```
and I try many other ways, none of it works.
MANY THANKS!!!!!!!
-----------------------

### Environment Mac High Sierra 10.13.3
```
 # autoconf --version
autoconf (GNU Autoconf) 2.69

# aclocal --version
aclocal (GNU automake) 1.15

# libtoolize --version
libtoolize (GNU libtool) 2.4.6

libtool --version
ltmain.sh (GNU libtool) 2.2.6b
```

* **Tesseract Version**:tesseract-3.05.01

* **Platform**: Darwin MBP.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesseract/pull/585

**Comment by zdenop** [comment]
1. 3.05.02 was release. Please use it if you want report bud for 3.05 branch. Anyway using 4.0 version is highly recommended. There are detailed instruction how to [build it on Mac](https://github.com/tesseract-ocr/tesseract/issues/1453).
2. There is clear message what it wrong: `libtool: Version mismatch error. ` and how you should fix it:  `libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6` and `READ THIS: https://docs.brew.sh/Troubleshooting`

@Shreeshrii : as you can see this is not related to issue you point out.
