### ISSUE TITLE
Issue while using indian language traineddata.

### ISSUE THREAD

**Issue by Claw12** [tesseract-ocr/tesseract#1446]
I'm using tesseract ocr 3.05.Whenever i use traineddata file to extract text from image.
I'm getting error like this .
I was using hin.traineddata and guj.traineddata.

```
Error: unichar ं in normproto file is not in unichar set.
Error: unichar ः in normproto file is not in unichar set.
Error: unichar ु in normproto file is not in unichar set.
Error: unichar ँ in normproto file is not in unichar set.
Error: unichar ॉ in normproto file is not in unichar set.
```

Please help me out to resolve this.
Thank you

**Comment by Shreeshrii** [comment]
Please use tesseract 4.0.0-beta.1

It will give you much better recognition for Hindi and Gujarati.

**Comment by Shreeshrii** [comment]
@zdenop Please close.

**Comment by pikeview** [comment]
I installed tesseract 4 beta in ubuntu 18.04. I am running ubuntu as a guest OS in virtualbox running in my windows 10 .

I copied the indic tessdata from indic-ocr git repo to my tessdata folder

I, then, used jTessBoxEditorFX to create a TIF file of one telugu char in NOTO font 8px size and tried to run tesseract.
I am facing two issues

1) I see a bunch of Error: unichar ె in normproto file is not in unichar set. kind of errors
2) Tesseract says the TIFF page is empty even though it has one char in it.

Please could you advise how to fix this.

**Comment by Shreeshrii** [comment]
>I copied the indic tessdata from indic-ocr git repo to my tessdata folder

Please use traineddata files from tessdata_fast or tessdata_best

**Comment by pikeview** [comment]
thank you. the errors are not occurring now. But the recognition is not good enough. I will post them on a different thread..

**Comment by Shreeshrii** [comment]
Tesseract 4 does line based recognition. Please test with a scanned real world image rather than synthetic single letter.

If you want to recognize a single character, try with --psm set appropriately (page segmentation mode).

**Comment by ajuber0** [comment]
the same problem, when open a file, how to resolve it
