### ISSUE TITLE
Failed to continue from: *.lstm

### ISSUE THREAD

**Issue by GDStephen** [tesseract-ocr/tesseract#1447]
### Environment

* **Tesseract Version**: 4.0.0-beta.1-65-gf8e2
* **Platform**: 16.04.1-Ubuntu

### Current Behavior:
Fine Tuning for ± a few characters:
_first:_
`training/combine_tessdata -e tessdata/best/eng.traineddata   ~/tesstutorial/trainplusminus/eng.lstm`
_second:_
`training/lstmtraining --model_output ~/tesstutorial/trainplusminus/plusminus   \`
`--continue_from ~/tesstutorial/trainplusminus/eng.lstm   \`
`--traineddata ~/tesstutorial/trainplusminus/eng/eng.traineddata  \` 
`--old_traineddata tessdata/best/eng.traineddata   \`
`--train_listfile ~/tesstutorial/trainplusminus/eng.training_files.txt   \`
`--max_iterations 3600`

result:
`Loaded file /root/tesstutorial/trainplusminus/eng.lstm, unpacking...`
`Failed to continue from: /root/tesstutorial/trainplusminus/eng.lstm`

### Expected Behavior:
Start Fine Tuning.

**Comment by Shreeshrii** [comment]
Please check that you have read write access to the root directory you are
using.

Make sure that you have the traineddata file from tessdata_best repo to
continue from.

Use wget or similar utility to download and verify file size, to make sure
download was correct.

**Comment by GDStephen** [comment]
Thks，@Shreeshrii.

I re-download traineddata file with wget from [https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata](https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata), and redo `training/combine_tessdata -e tessdata/best/eng.traineddata ~/tesstutorial/trainplusminus/eng.lstm`.

When I execute :
```
training/lstmtraining --model_output ~/tesstutorial/trainplusminus/plusminus \
--continue_from ~/tesstutorial/trainplusminus/eng.lstm \
--traineddata ~/tesstutorial/trainplusminus/eng/eng.traineddata \
--old_traineddata tessdata/best/eng.traineddata \
--train_listfile ~/tesstutorial/trainplusminus/eng.training_files.txt \
--max_iterations 3600
```
return:
```
Loaded file /root/tesstutorial/trainplusminus/eng.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 111 to 111!
Num (Extended) outputs,weights in Series:
  1,36,0,1:1, 0
Num (Extended) outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys64:64, 20736
  Lfx96:96, 61824
  Lrx96:96, 74112
  Lfx512:512, 1247232
  Fc111:111, 0
Total weights = 1404064
Previous null char=110 mapped to 110
Continuing from /root/tesstutorial/trainplusminus/eng.lstm
Loaded 72/72 pages (1-72) of document /root/tesstutorial/trainplusminus/eng.Garuda.exp0.lstmf
Loaded 72/72 pages (1-72) of document /root/tesstutorial/trainplusminus/eng.Liberation_Sans.exp0.lstmf
Loaded 72/72 pages (1-72) of document /root/tesstutorial/trainplusminus/eng.SimSun.exp0.lstmf
Loaded 72/72 pages (1-72) of document /root/tesstutorial/trainplusminus/eng.NSimSun.exp0.lstmf
!int_mode_:Error:Assert failed:in file weightmatrix.cpp, line 244
Segmentation fault (core dumped)
```

**Comment by Shreeshrii** [comment]
I re-download traineddata file with wget from
https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata

Please use tessdata_best repository for using as continue_from for LSTM
training

You have used tessdata

**Comment by GDStephen** [comment]
Thks, @Shreeshrii . According to your guidance, I solved the problem.

**Comment by Shreeshrii** [comment]
@zdenop Please close.

**Comment by eravallirao** [comment]
Can't we retrain using the tesseract_fast model, why I am unable to that? Is there any particular reason.

**Comment by argideritzalpea** [comment]
This issue must be made clear in the wiki. There is no mention of not being able to use tesseract_fast for continuation

**Comment by Shreeshrii** [comment]
I have added the info to wiki - please see

https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00/_compare/f638b9bf123fbe2d90d1ec8116e6593c31b29228...585ae54e5789b26557aa27319145037a96d85a8c
