### ISSUE TITLE
Python3.6 : Bad text recognition

### ISSUE THREAD

**Issue by SylvainBert** [tesseract-ocr/tesseract#1450]
**Environement**

- plateform : Windows 10

- tesseract version : 3.05.01

**Problem**

I don't know why text recognition is bad in my case : 

File to convert into text : [CV_berthelot.pdf](https://github.com/tesseract-ocr/tesseract/files/1875730/CV_berthelot.pdf)

````python
import io
from wand.image import Image
import pyocr
from PIL import Image as PI
from wand.color import Color

final_text=[]
req_image=[]
tool = pyocr.get_available_tools()[0]
file = "Cv_berthelot.pdf"
with Image(filename=file,resolution = 300) as image_pdf:
    image_pdf.background_color = Color("white")
    image_pdf.alpha_channel = 'remove'
    with image_pdf.convert('jpeg') as image_jpeg:
                        
        for img in image_jpeg.sequence:
            img_page = Image(image=img)
            req_image.append(img_page.make_blob('jpeg'))
        
        for img in req_image: 
            with PI.open(io.BytesIO(img)) as tmp:
                txt = tool.image_to_string(tmp)
                final_text.append(txt)
                
        decoup_text=[]
        for dec in final_text:
            decoup_text.append(dec.split("\n"))

        text_complet = ''
        for part in decoup_text:
            for partie in part:
                if(partie!=''):
                    text_complet = text_complet+' '+ partie
        
text_complet


````
The code works but the result (below) is not very good... Any idea why?

`SYLVAIN.J.BERTHEL[]T@ EMAILGUM 142 AVENUE DE L\'EYBALA 38700 GURENB SYLVAIN BERTHELUT . % 0627844021 RECHERCHE IJ\'UN STAGE DE 8 SEMAINESA PAHTIH DU 2 MAI O 69 A PROPOS DE MOI EXPERIENCES PROFESSIONNELLES — “ Lors de mes saisons en tant qu\'animateur j‘ai développé mon réle de leader et mon habilité 3 STAGE EN RECHERCHE STATISTlﬂUES, prendre des décisions. J\'ai eu I\'opportunité de mener des réunions d\'une équipe d\'une vingtaine de personnes. Mes expériences m\'ont permis d\'avoir un sens du relationnel plus CHU GRENUBLE SUD aiguisé et de m\'exprimer plus facilement a I‘orale. J‘ai acquis une certaine méthodologie de AVR|L 2015 -]U|N 2015 travail Iors de mes stages en recherche statistiques. Les compétences acquises durant ma formation me permettent d‘avoir une capacité d\'adaptation et de compréhension rapide. Analyse de trartement de sugnal de fréquence cardiaque STAGE EN RECHERCHE STATISTIﬂUES, INRA AVIGNUN AVRIL 2015 - JUIN 2015 Q P 0 R M A T I O N S Comprendre Ia structure spatiale des comm unautés dadventioes. ANIMATEUR HIP HOP. MJCD\'APT SEP.2016-PBESENT 2011-2015 MASTER1IMIASHSPARBUURSSSD UNIVERSITE DE GRENDBLE ALPES - GRENUBLE. Avec un public de 6 a 25 ans. ANIMATEUR PDLYVALENT SEP. 2015 - JUIN.?01B BHAHUEETEDEPUISZUH LICENCE 3 MI PARCUURS MATHEMATIHUES Essentiellementdesadolescents. UNIVERSITE DE BRENUBLE ALPES - BRENDBLE. SEP.2013-JU|N.2015 .LANGUES DUT STATISTIUUES ET INFORMATIUUE DEGISIUNNELLE I N ST I T UT UNIVERSITAIRE DE TECHNOLOGIE D\'AVIBNUN - AVIBNUN. SEP.2012-JU|N.2013 Nlmuﬁz LICENCE 1 INFORMATIUUE ESPAGNUL UNIVERSITE D\'AVIGNDN - AVIGNDN. mvmum ANGLAIS J U | N . 2 U I 2 BACCALAUREAT SCIENTIFIUUE: UPTIUN MATHEMATIUUES LYGEE D\'APT - APT. |\'|\' COMPETENCES 8 HOBBIES — O YUSEIKAN ART MARTIAL R/ RSTUDIU HTML 0 GULTURE "\'P "0" MUSIUUE, DANCE, HISTUIRE SAS PHP SCILAB CSS 0 SPORTS MATLAB PYTHUN BASKET, FUIJT, TENNIS MAPLE C EXCEL JAVA O ASSOCIATION MEMBRE BDE, MEMBRE CUNSEIL D\'ADMINISTRATIUN MYSﬂL/PSUL 3” MJG APT'`

**Comment by stweil** [comment]
Why don't you try the latest Tesseract version?

**Comment by SylvainBert** [comment]
Yeah you're right! Is better, just question of training data i think! 
It's possible that text font is diffcult to identify ? Because i don't have any problem with other files (with tesseract 3.05, so with 4.0 it's very better), just with my resume. I compile with a text font create by a friend.

Thank you!

**Comment by stweil** [comment]
@SylvainBert, good to hear that 4.0 works for you. Could you please close the issue then?
