### ISSUE TITLE
make target issue

### ISSUE THREAD

**Issue by rdp** [tesseract-ocr/tesseract#1451]
Cross compiling in this case, not sure if it makes a difference:

with 10f4998aee3

```

$ ./configure --host=i686-w64-mingw32 --prefix=/home/x --disable-shared --enable-static
...
$ make
...
make[3]: *** No rule to make target 'bits16.cpp', needed by 'bits16.lo'.  Stop.
```

 8209ce36636ab7 seemed to work fine.  Cheers!

**Comment by stweil** [comment]
`bits16.cpp` was removed recently. Please update your `Makefile.in` files by running `./autogen.sh`.

**Comment by stweil** [comment]
Normally an autotools build should automatically run automake in that situation. For Tesseract this feature is [explicitly disabled](https://github.com/tesseract-ocr/tesseract/blob/10f4998aee3ccc68e9c4931ce744dd292ad6ff19/configure.ac#L68). I wonder why ...

**Comment by amitdo** [comment]
It was added by @zdenop in:
 ihttps://github.com/tesseract-ocr/tesseract/commit/8299e2a6051568c2c9da1e12a011782db50ef81d#diff-67e997bcfdac55191033d57a16d1408a

**Comment by stweil** [comment]
He only moved that lines. The code was already there in commit 425d593ebe2c4136312964a434ca7bc13904679f, more than 10 years ago.

**Comment by amitdo** [comment]
My mistake. Sorry!

**Comment by rdp** [comment]
Thought I had restarted from scratch but it seems to be working fine today <scratch head>.  Sorry for the noise.

**Comment by amitdo** [comment]
>Normally an autotools build should automatically run automake in that situation. For Tesseract this feature is explicitly disabled. I wonder why ...

Another one for #1423 ?

**Comment by stweil** [comment]
See PR #1454 which removes the unwanted maintainer mode.
