### ISSUE TITLE
Fontconfig error on tesstrain.sh

### ISSUE THREAD

**Issue by FernandoGOT** [tesseract-ocr/tesseract#1461]
### Environment

* **Tesseract Version**: 4.0.0-beta.1-69-g10f4
leptonica-1.75.3
  libjpeg 9c : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11

 Found AVX2
 Found AVX
 Found SSE

* **Platform**: Darwin Fernandos-MBP.home 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

### Current Behavior:

If I execute the tesstrain.sh command with a lot of fonts it start getting error that couldn't find some fonts.

the code I used was:

```
PANGOCAIRO_BACKEND=fc \
~/projects/tesseract/training/tesstrain.sh \
  --fonts_dir ~/Library/Fonts \
  --lang kor \
  --linedata_only \
  --noextract_font_properties \
  --langdata_dir ~/projects/langdata \
  --tessdata_dir ~/projects/tesseract/tessdata \
  --fontlist  "210 Byulbitcha" \
              "210 Byulddongbyul" \
              "210 HaneuljungwonOTF" \
              "210 Misslee" \
              "210 Sangsangongjakso" \
              "210 Sunflower" \
              "Arial Unicode MS" \
              "BM DoHyeon OTF" \
              "BM HANNA 11yrs old OTF" \
              "BM JUA_OTF" \
              "BM KIRANGHAERANG OTF" \
              "BM YEONSUNG OTF" \
              "Baekmuk Batang" \
              "Baekmuk Gulim" \
              "Baekmuk Dotum" \
              "Baekmuk Headline" \
              "DX빨간우체통B Medium" \
              "DX아기사랑B" \
              "HCR Batang" \
              "HL" \
              "HanS" \
              "NanumGothic Eco" \
              "NanumMyeongjo Eco" \
              "SangSangAnt" \
              "Source Han Serif" \
              "Source Han Serif K" \
              "Source Han Serif SC" \
              "Source Han Serif TC" \
              "Typo_Ballerina" \
              "Typo_Crayon" \
              "Typo_Dodam" \
              "Typo_DonkiRound" \
              "Typo_JeongJo" \
              "Typo_Papyrus" \
              "Typo_SSiMyungJo" \
              "UhBee Joker" \
  --output_dir ~/projects/ocr/training/kortrain/new_train
```

Most of the fonts was installed recently, all of the fonts can be found with:

```
PANGOCAIRO_BACKEND=fc \
text2image --list_available_fonts --fonts_dir=~/Library/Fonts
```

It return this error:
```
Fontconfig error: "/var/folders/xl/gqcd7ljn0k7d3r_3j9dy7x340000gn/T/font_tmp.XXXXXXXXXX.wFQSjK0B/fonts.conf", line 1: no element foundFontconfig error: "/var/folders/xl/gqcd7ljn0k7d3r_3j9dy7x340000gn/T/font_tmp.XXXXXXXXXX.wFQSjK0B/fonts.conf", line 1: Fontconfig error: "/var/folders/xl/gqcd7ljn0k7d3r_3j9dy7x340000gn/T/font_tmp.XXXXXXXXXX.wFQSjK0B/fonts.conf", line 1:
Fontconfig error: Cannot load config file from /var/folders/xl/gqcd7ljn0k7d3r_3j9dy7x340000gn/T/font_tmp.XXXXXXXXXX.wFQSjK0B/fonts.conf
no element found
Fontconfig error: Cannot load config file from /var/folders/xl/gqcd7ljn0k7d3r_3j9dy7x340000gn/T/font_tmp.XXXXXXXXXX.wFQSjK0B/fonts.conf
no element found
Fontconfig error: Cannot load config file from /var/folders/xl/gqcd7ljn0k7d3r_3j9dy7x340000gn/T/font_tmp.XXXXXXXXXX.wFQSjK0B/fonts.conf
Could not find font named Baekmuk Gulim.
```

The font name in the error change every time I run the code

### Expected Behavior:

For the code to generate the files and complete without errors

### Suggested Fix:

After a lot of debugging i think that I found the issue, the problem is that wen search for all fonts simultaneous the lib use (not sure which one) fail to get some fonts.

I was able to fix it changing the file ```training/tesstrain_utils.sh```

```diff
for font in "${FONTS[@]}"; do
+         sleep 1
            generate_font_image "${font}" &
            let counter=counter+1
            let rem=counter%par_factor
            if [[ "${rem}" -eq 0 ]]; then
              wait
            fi
        done
```

**Comment by Shreeshrii** [comment]
Thanks for investigating the issue and finding a resolution.

Please submit a Pull Request with the change.

**Comment by stweil** [comment]
That looks strange. Was this issue also observed on other platforms? Could someone else reproduce the problem with a different font list?

We should at least add a comment to the sleep statement pointing to this issue here and marking it as a hack which needs further investigation.

**Comment by Shreeshrii** [comment]
I have had the font problem multiple times, on WSL - Ubuntu 16.04.

It is random, goes away sometimes on a second run.

I had found that running

fc-cache -vf

usually made the next run proceed ok. But that was after the fact, after a
training run had crashed.

I agree that a comment before sleep statement will be useful.
