### ISSUE TITLE
How to include tesseract 4.0 into my c++ project using visual studio 

### ISSUE THREAD

**Issue by AbdelsalamHaa** [tesseract-ocr/tesseract#1462]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below. 

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by AbdelsalamHaa** [comment]
hi , i have been using tesseract 3.04 in my project c++ , however i want to change it to use 4.00 since it's more accurate . i did include tesseract 3.04 just by including a path to the include fill . when i download tesseract 4.0 there was no include fill .plz any one can pass me any link to follow the steps  . thank you in advance

**Comment by zdenop** [comment]
Did boíther to read:
"Before you submit an issue, please review the guidelines for this repository.
Please report an issue only for a BUG, not for asking questions."??? 
If you do not care about it, why we should care about your problem?

**Comment by AbdelsalamHaa** [comment]
im sorry buti have read it actually , but i didn't get what does bug mean ?? and i don't know where can i ask my question ??

**Comment by AbdelsalamHaa** [comment]
can u plz give me some guidness

**Comment by zdenop** [comment]
Maybe you do not under what does it mean bug (see [wikipedia](https://en.wikipedia.org/wiki/Software_bug)). But what is unclear on "not for asking questions"???

There are [guideliness](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md) for ["Creating an Issue or Using the Forum"](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md#creating-an-issue-or-using-the-forum) - do you need more?
