### ISSUE TITLE
tessdata_prefix error with Fraktur.traineddata on High Sierra

### ISSUE THREAD

**Issue by ghost** [tesseract-ocr/tesseract#1464]
I downloaded Fraktur.traineddata to /usr/local/share/tessdata

When using (I am new and following this guide: [https://www.youtube.com/watch?v=QhJiOCwz-_I](url)

$ tesseract file.tiff -l Fraktur Fraktur 

The following error appears: 

Error opening data file ./tessdata/Fraktur.traineddata 
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory. Failed loading language 'Fraktur' Tesseract couldn't load any languages! Could not initialize tesseract.

The same happens when using eng.

**Comment by Shreeshrii** [comment]
tesseract file.tiff outputfile.tiff -l Fraktur 
--tessdata-dir /usr/local/share/tessdata

You need to give in following order

tesseract input output --options

––

Also check

tesseract -v
tesseract --list-langs
Tesseract --help

**Comment by Ni-2** [comment]
Thank you for your reply. In this case I won't follow the above mentioned guide. 
However, if I enter e.g. tesseract --list-langs the same error occurs:

Error opening data file ./tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.

**Comment by Shreeshrii** [comment]
What is your tesseract version and o/s?

Did you try the command adding --tessdata-dir directly to it?

**Comment by Ni-2** [comment]
tesseract 3.01.01
macOS 10.13.3

When using tesseract file.tiff outputfile.tiff -l Fraktur --tessdata-dir /usr/local/share/tessdata it says 
Failed loading language 'Fraktur'
Tesseract couldn't load any languages!
Could not initialize tesseract.

**Comment by Shreeshrii** [comment]
3.01.01  is too old.

Please try to use the latest tesseract4.0.0beta.

**Comment by Ni-2** [comment]
3.05.01 is the version I use (typo), the one from mid-2017. Is this still too old? It is this version I get with the command brew install tesseract

**Comment by amitdo** [comment]
You are using a traineddata file that was trained for 4.0.0 and that is not compatible with 3.0x.
 
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files

**Comment by Ni-2** [comment]
I see. I tried to install tesseract4.0 using this guide [https://github.com/tesseract-ocr/tesseract/issues/1453](url) 
However, apparently I already fail running the code ln -hfs /usr/local/Cellar/icu4c/60.2 /usr/local/opt/icu4c since nothing happens. 
Since I haven't used terminal before I guess I just can't do it. I already tried abbyy finereader, but there the Fraktur ocr is useless.

**Comment by Shreeshrii** [comment]
You can try the GUI frontends to tesseract. I use gimagereader and vietocr. I am not sure whether they are available for your platform, but u can check their project pages for details.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
