### ISSUE TITLE
Tesseract fails on page 2 and won't process remaining pages in a TIFF

### ISSUE THREAD

**Issue by agaace** [tesseract-ocr/tesseract#1468]
### Environment

* **Tesseract Version**: 
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0

* **Platform**:
Ubuntu on Windows
Linux Alienka-PC 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
I have a 238 page TIFF file converted from a 238 page PDF file (using Ubuntu convert command).
I verified I can open and vied the TIFF file just fine in IrfanView.
When I try to convert it to a searchable PDF file using this command:

```
tesseract -book.tiff book pdf
```
it stops with an error after first page. The output document only includes the first page. Here's the complete output:

```
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Page 1
OSD: Weak margin (2.41) for 123 blob text block, but using orientation anyway: 0
Error in pixReadFromTiffStream: spp not in set {1,3,4}
```

This is the same error I will see if I execute this command:
```
tesseract -c tessedit_page_number=1 book.tiff page1 pdf
```

If I skip second page, and convert just third page, all is well:

```
tesseract -c tessedit_page_number=2 book.tiff page2 pdf
```

Meaning second page is the culprit. It is an empty page with no text on it.

Since the entire TIFF file is 3 GB in size (at 300 dpi), it's not feasible to attach it here, and I wasn't able to extract that single page from the TIFF without changing the behavior. I can make the original file 
temporarily available somewhere if needed.

### Expected Behavior:
I want to be able to convert entire 238-page-long document in one command. Doing it page by page by skipping problematic pages and then merging 238 pages back together is not acceptable.

### Suggested Fix:
Please provide a way to skip problematic pages (leave them as image? or leave them blank?).
Alternately, please provide a way to convert a subset of the document, for example skip page 2 but still be able to convert the remaining pages 3-238 all in one go.

**Comment by zdenop** [comment]
First of all: 3.04 is too old. Please you use current of tesseract (4.0.beta1).
Next: try to google for error message [Error in pixReadFromTiffStream: spp not in set {1,3,4}](https://stackoverflow.com/questions/5083492/tesseract-and-tiff-format-spp-not-in-set-1-3)

**Comment by Shreeshrii** [comment]
Try converting pdf to tiff using ghostscript.
