### ISSUE TITLE
Unable to parse cyrillic

### ISSUE THREAD

**Issue by kurkale6ka** [tesseract-ocr/tesseract#147]
This is the failing test: (all locales, packages seem correctly installed).
For info, parsing english works fine.

```
% tesseract test.png test -lbul
Tesseract Open Source OCR Engine v3.04.00 with Leptonica

% cat test.txt
Ila mnpmm "mm npanHM Mama m m: m: m :3 mm mm. Ms M:

% locale -a | grep bg
bg_BG.utf8

% pacman -Qs tesseract-data-bul
local/tesseract-data-bul 3.04.00-1 (tesseract-data)
```

Also tried:
* `LANG=bg_BG.UTF-8 tesseract test.png test -lbul`
* a different bul traindata: https://code.google.com/p/tesseract-ocr/downloads/detail?name=bul.traineddata.gz

**Comment by kurkale6ka** [comment]
![test](https://cloud.githubusercontent.com/assets/52182/11091324/3871125e-8871-11e5-8f9d-0472f36b68b2.png)

**Comment by amitdo** [comment]
Try this:
> tesseract test.png test -l bul

**Comment by kurkale6ka** [comment]
Ha, that's funny, I actually tried it like this the very first time but I had an error and thought that that caused it!

Works much better like this:
`tesseract test.png test -l bul`:
`Да извършва всякакви правни „щения пт на: им: и за мая см:-дка. пя „=`

Still not 100% accurate but I guess that's up to me/options to fix now?

**Comment by kurkale6ka** [comment]
Suggestion: using `-lbul` should fail with an error

**Comment by amitdo** [comment]
The font in this image is quite small. You should try to rescale the image (X2-X4).
https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

In general, the right place to ask questions is here:   
https://groups.google.com/forum/?hl=en#!forum/tesseract-ocr

**Comment by kurkale6ka** [comment]
I found out exactly what were the encountered issues. Here is a sum up:

* First I ran `tesseract test.png -l bul` which fails because it sees an option instead of `outputbase|stdout` but I thought it was because of the space between `-l` and `bul`
* Then I tried `tesseract test.png -lbul` which doesn't give errors because it wrongly thinks that the output file is `-lbul` and it uses the default `eng` data. Indeed `-lbul.txt` gets created
* And eventually: `tesseract test.png test -lbul` which creates `test.txt` and uses `eng` as default and simply discards `-lbul` which is nonsense to it

**Comment by zdenop** [comment]
Tesseract executable is simple example how to use tesseract library. There is no intentional make it more complex (just because of parsing arguments and reporting user mistakes)
