### ISSUE TITLE
Testing a picture get null string.

### ISSUE THREAD

**Issue by GDStephen** [tesseract-ocr/tesseract#1472]
### Environment

* **Tesseract Version**: 4.0.0-beta.1-65-gf8e2
* **Platform**:16.04.1-Ubuntu

### Current Behavior:
```
tesseract xxx.jpg test
```
xxx.jpg is 
![image](https://user-images.githubusercontent.com/17470296/38653382-0924d1be-3e3d-11e8-9d1f-aa4aeef0beb9.png)

return:
```
Tesseract Open Source OCR Engine v4.0.0-beta.1-65-gf8e2 with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 671
Empty page!!
Estimating resolution as 671
Empty page!!
```
but the other picture:
```
tesseract 金额1_Binary.jpg test1
```
金额1_Binary.jpg is 
![image](https://user-images.githubusercontent.com/17470296/38653612-324863ac-3e3e-11e8-8a35-120f19280ac5.png)
return:
```
Tesseract Open Source OCR Engine v4.0.0-beta.1-65-gf8e2 with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 347
```
vim test1.txt is '7179. 49'.
### Expected Behavior:
tesseract xxx.jpg test result is "09194514".

**Comment by FernandoGOT** [comment]
try to use ```tesseract xxx.jpg test -l eng --oem 3 --psm 6````

**Comment by GDStephen** [comment]
Thks, @FernandoGOT 
'-l eng --oem 3 --psm 6' is worked.
image resolution is 51 × 38.
