### ISSUE TITLE
I tried to OCR a PDF file with ver 4 on Windows 10 but returned:...

### ISSUE THREAD

**Issue by BudiKusasi** [tesseract-ocr/tesseract#1476]
I tried to OCR a file "Kamus_Arab-Indonesia.pdf" - in English: "Arabic - Indonesia Dictionary"..
so I typed from tesseract install dir:
```
tesseract.exe D:\DOC\ARABIC\Kamus_Arab-Indonesia.pdf  z:\t\Kamus.pdf  -l ara+ind --psm 1

Tesseract Open Source OCR Engine v4.0.0-alpha.20180109 with Leptonica
Error in pixReadStream: Pdf reading is not supported
Error in pixRead: pix not read
Error during processing.
```

How could I solve mine such above?.. many thanks in advance.

**Comment by stweil** [comment]
Tesseract does not support reading PDF files.

You can try other software, for example [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF/).
