### ISSUE TITLE
Empty page! (tesseract cannot recognition text)

### ISSUE THREAD

**Issue by dns2316** [tesseract-ocr/tesseract#1480]
Image which tesseract can not recognition.
---
![test](https://user-images.githubusercontent.com/18660182/38784890-505b182c-4121-11e8-8348-55ce9afa809f.jpg)

---

Used ubuntu 16.04, python 3.5.2, tesseract 3.04.01, leptonica-1.73(~1.74).

**Comment by zdenop** [comment]
Read the [wiki](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality) first.
