### ISSUE TITLE
Parse error: syntax error, unexpected '.' in TesseractOCR.php on line 38

### ISSUE THREAD

**Issue by afeef1915** [tesseract-ocr/tesseract#1482]
i have updated wrapper from url https://github.com/thiagoalessio/tesseract-ocr-for-php

php is throwing error in _call function

        public function __call($method, $args)
	{
		if ($this->isShortcut($method)) {
			$class = $this->getShortcutClassName($method);
			$this->options[] = $class::buildOption(...$args);
			return $this;
		}
		if ($this->isOption($method)) {
			$class = $this->getOptionClassName($method);
			$this->options[] = new $class(...$args);
			return $this;
		}
		$this->options[] = new Option\Config($method, $args[0]);
		return $this;
	}

error message
Parse error: syntax error, unexpected '.' in D:\xamppNew\htdocs\tesseract-ocr-for-php\src\TesseractOCR.php on line 38

i try to call wrapper

require_once './src/TesseractOCR.php';

echo (new TesseractOCR('https://progur.com/assets/block1/inputTesseract.png'))
    ->run();
But wrapper throws Exception in line code
  $this->options[] = $class::buildOption(...$args);

can anyone suggest the solution for this error.

composer.json

{
	"name": "thiagoalessio/tesseract_ocr",
	"description": "A wrapper to work with Tesseract OCR inside PHP.",
	"version": "2.2.2",
	"type": "library",
	"keywords": ["Tesseract", "OCR", "text recognition"],
	"license": "MIT",
	"authors": [
		{
			"name": "thiagoalessio",
			"email": "thiagoalessio@me.com"
		}
	],
	"support": {
		"issues": "https://github.com/thiagoalessio/tesseract-ocr-for-php/issues",
		"irc": "irc://irc.freenode.net/tesseract-ocr-for-php",
		"source": "https://github.com/thiagoalessio/tesseract-ocr-for-php"
	},
	"require": {
		"php": "^5.6 || ^7.0"
	},
	"require-dev": {
		"phpunit/php-code-coverage": "^4.0.8",
		"codacy/coverage": "dev-master"
	},
	"autoload": {
		"psr-4": {
			"thiagoalessio\\TesseractOCR\\": "src/"
		}
	},
	"autoload-dev": {
		"psr-4": {
			"thiagoalessio\\TesseractOCR\\Tests\\": "tests/"
		}
	}
}

**Comment by zdenop** [comment]
TesseractOCR.php is part of this project. Please report your issue to its author.

**Comment by afeef1915** [comment]
can you help in this as TesseractOCR is not working
