### ISSUE TITLE
 error when i run 32bit code and use 64bit library 

### ISSUE THREAD

**Issue by AbdelsalamHaa** [tesseract-ocr/tesseract#1490]
Hi , and good day first i hope i'm following the correct instructor  to start this issue , if i'm not please let me know what is wrong so i can avoid it .

I'm using tesseract4.0 with leptonica 1.75.3 . im using win 10 ,vs2017 . i have install tesseract4.0 and did a simple program to test it before i go for my main program . the code worked very fine 
http://livezingy.com/compilation-tesseract4-in-vs2017-win10 
(it's in Chinese though but i used google translate ) i have even print the version to make sure it's tesseract4.0 and all was fine .
here is the code 
![image](https://user-images.githubusercontent.com/35866217/38967738-04270460-43bb-11e8-8aec-d62746414651.png) .the code is made by using win64 . 

now i started to get this error in my other program which use win32 , 

Error	LNK2019	unresolved external symbol "public: __thiscall tesseract::TessBaseAPI::TessBaseAPI(void)" (??0TessBaseAPI@tesseract@@QAE@XZ) referenced in function "public: __thiscall OCRCardReader::OCRCardReader(void)" (??0OCRCardReader@@QAE@XZ)	TestCode	C:\Users\iradar\Desktop\iSenseOCR\TestCode\OCRCardReader.obj	1	

is that mean i shall install tessreact4.0 again using win 32 or if there's a way that i can change the code to be win64 coz in top only win 32 is available 
hope to get ur help in this thanks in advance

**Comment by Shreeshrii** [comment]
Please see https://github.com/UB-Mannheim/tesseract/wiki

It has a win32 installer also.

**Comment by zdenop** [comment]
This has nothing to do with tesseract. AFAIK you can not mix 64bit and 32bit libraries ([e.g. No Mixed 64-Bit/32-Bit Processes](https://support.microsoft.com/sk-sk/help/282423/list-of-limitations-in-64-bit-windows))
