### ISSUE TITLE
--max_iterations is only applied to 100 denominations

### ISSUE THREAD

**Issue by christophered** [tesseract-ocr/tesseract#1491]
When fine-tuning an existing model, I have set an option of **--max_iterations 105** but it stopped at iteration 200, which means that lstmtraining is only handling iterations in every 100th denomination.

**Comment by amitdo** [comment]
The relevant code is here:
https://github.com/tesseract-ocr/tesseract/blob/a07ee5c40bf958de26ba46175f97f23fe9e5fc2b/training/lstmtraining.cpp#L194

**Comment by stweil** [comment]
Pull request #1493 should fix that. Thanks to both of you for reporting and also for the helpful link.

**Comment by christophered** [comment]
@amitdo @stweil Thanks for your hard work
