### ISSUE TITLE
Segmentation fault while using lstm based trained data

### ISSUE THREAD

**Issue by AzkaGilani1** [tesseract-ocr/tesseract#1497]
I have been trying to use tesseract with OEM 1 on ubuntu 16.04. I downloaded the LSTM based trained data file from [here](https://github.com/tesseract-ocr/tessdata_best/raw/master/nor.traineddata)
When i run tesseract via command line, it throws this exception. 
 ```tesseract --tessdata-dir /usr/local/share/tessdata/ image.jpeg outputbase -l nor_best --psm 3 --oem 1
Info in bmfCreate: Generating pixa of bitmap fonts from string
lstm_recognizer_->DeSerialize(&fp):Error:Assert failed:in file tessedit.cpp, line 193
Segmentation fault (core dumped)
```
But when i use default nor.traineddata, it runs perfectly.
Tesseract version:
```
tesseract 0afd593
 leptonica-1.74
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8

 Found AVX
 Found SSE
```
Any pointers to resolve this issue?

**Comment by Shreeshrii** [comment]
You only mention leptonica version.
What is your version of tesseract-ocr? Did you build it?

**Comment by AzkaGilani1** [comment]
@Shreeshrii i have compiled tesseract from commit (0afd593)

**Comment by amitdo** [comment]
>But when i use default nor.traineddata, it runs perfectly.

What do you mean by 'default'?

Paste the full command you used.

**Comment by AzkaGilani1** [comment]
By default, i mean the oldest version of traineddata https://github.com/tesseract-ocr/tessdata/blob/bf82613055ebc6e63d9e3b438a5c234bfd638c93/nor.traineddata
While the one that give segmentation fault is from this link https://github.com/tesseract-ocr/tessdata_best/
The command that I am using to run tesseract is 
```
tesseract --tessdata-dir /usr/local/share/tessdata/ invoicepage-125778.jpeg outputbase -l nor --psm 3 --oem 1
```

**Comment by Shreeshrii** [comment]
Is that from a commit 12 months ago?

Please rebuild with latest source from master?

**Comment by AzkaGilani1** [comment]
Yes rebuild it. It is working fine now. Thanks :)
