### ISSUE TITLE
Dead links on Wiki Page: Making-Box-Files 4.0

### ISSUE THREAD

**Issue by topherseance** [tesseract-ocr/tesseract#1502]
On this wiki page:  
[https://github.com/tesseract-ocr/tesseract/wiki/Making-Box-Files---4.0](https://github.com/tesseract-ocr/tesseract/wiki/Making-Box-Files---4.0)  

The link to the

- Box File
- Tif Image

Is missing -- Leads to the Github's 404 error page.

(P.S. I'm a newbie and want to try Tesseract)

Thanks :)

**Comment by Shreeshrii** [comment]
Thanks for the report.

To try tesseract, you don't need to make box files. It works out of the box for hundreds of languages. 

tesseract --help

will give you the syntax

**Comment by Shreeshrii** [comment]
I have updated the wiki page. You can close this issue.

**Comment by topherseance** [comment]
Thanks for you help :smile:
