### ISSUE TITLE
unicharset_extractor command not found - Mac OSX

### ISSUE THREAD

**Issue by caydenliew** [tesseract-ocr/tesseract#151]
i've installed tesseract using brew, but when run command unicharset_extractor,mftraining or cntraining, the command is not found.

**Comment by gabriel-fsa** [comment]
Hey dude. Dd you manage to solve?

**Comment by Alexander174rus** [comment]
> Hey dude. Did you manage to solve?

Faced an identical problem. I'm guessing Brew installs tesseract without the learning package. The problem could not be solved
