### ISSUE TITLE
Tesseract forcing all letters or all numbers. Could you advice to obtain better results?

### ISSUE THREAD

**Issue by lohhenzo** [tesseract-ocr/tesseract#152]
I am trying to read serial number, bios version, dimm capacity and cpu type from a BIOS screen shot but cannot improve the results. I attached a zip file with the images.

These information are not words or sentences, and looks like tesseract is trying to give sense or forcing the info to all letters or to all numbers (if preceding a number force to a number). 

Below share my results to see if you know what settings or image pre processing I need to use to improve the results. 

I am using Tesseract 3.03 and ImageMagick 6.8.8-10 on a Fedora 21 OS.

screen shot:
![screen](https://cloud.githubusercontent.com/assets/4931834/11312205/05da2e7a-8f92-11e5-8d74-e6043fcf9d7f.jpg)

bios.jpg:
![bios](https://cloud.githubusercontent.com/assets/4931834/11312193/f78dd010-8f91-11e5-8c8a-5d36c1c1cee8.jpg)

bios-resize300.jpg:
![bios-resize300](https://cloud.githubusercontent.com/assets/4931834/11312222/151035c4-8f92-11e5-863d-aa187d55c585.jpg)

cpu.jpg:
![cpu](https://cloud.githubusercontent.com/assets/4931834/11312197/fc9e87de-8f91-11e5-978e-46c2bfe96e2e.jpg)

cpu-resize300.jpg:
![cpu-resize300](https://cloud.githubusercontent.com/assets/4931834/11312225/151f787c-8f92-11e5-9749-fdd02d924bf7.jpg)

cpu-threshold40.jpg:
![cpu-threshold40](https://cloud.githubusercontent.com/assets/4931834/11312223/15115f4e-8f92-11e5-88ce-a3abbc48d62d.jpg)

dimm.jpg:
![dimm](https://cloud.githubusercontent.com/assets/4931834/11312199/fee89c1e-8f91-11e5-98d4-200677f63a6c.jpg)

dimm-resize300.jpg:
![dimm-resize300](https://cloud.githubusercontent.com/assets/4931834/11312224/151e5d2a-8f92-11e5-9efd-b77363014f0d.jpg)

stn.jpg:
![stn](https://cloud.githubusercontent.com/assets/4931834/11312201/0171e1ca-8f92-11e5-9225-aa867039f7ae.jpg)

stn-resize300.jpg:
![stn-resize300](https://cloud.githubusercontent.com/assets/4931834/11312226/15203e10-8f92-11e5-8288-5da388909b78.jpg)

Thanks.

bios.jpg

command: 
tesseract bios.jpg -psm 8 stdout tessdata

tessdata content:
load_system_dawg F
load_freq_dawg F
language_model_penalty_non_dict_word F
language_model_penalty_non_freq_dict_word F
tessedit_char_whitelist A0123456789

expected:
A08

result:
A05

comments:
BAD RESULT

-------------------------------------------------------------------
bios.jpg

command:
convert bios.jpg -resize 300% bios-resize300.jpg
tesseract bios-resize300.jpg -psm 8 stdout tessdata

tessdata content:
load_system_dawg F
load_freq_dawg F
language_model_penalty_non_dict_word F
language_model_penalty_non_freq_dict_word F
tessedit_char_whitelist A0123456789

expected:
A08

result:
908

comments:
Better results resizing 300% the original image, but still wrong. Made a lot of changes on size and adding threshold and still getting a 9 instead of A.

-------------------------------------------------------------------
dimm.jpg

command:
tesseract dimm.jpg -psm 8 stdout tessdata

tessdata content:
load_system_dawg F
load_freq_dawg F
language_model_penalty_non_dict_word F
language_model_penalty_non_freq_dict_word F
tessedit_char_whitelist 0123456789MB

expected:
4096MB

result:
4036MB

comments:
BAD RESULTS

-------------------------------------------------------------------
dimm.jpg

commands:
convert dimm.jpg -resize 300% dimm-resize300.jpg
tesseract dimm-resize300.jpg -psm 8 stdout tessdata

tessdata content:
load_system_dawg F
load_freq_dawg F
language_model_penalty_non_dict_word F
language_model_penalty_non_freq_dict_word F
tessedit_char_whitelist 0123456789MB

expected:
4096MB

result:
4096MB

comments:
GOOD RESULTS

-------------------------------------------------------------------
stn.jpg

commands:
tesseract stn.jpg -psm 8 stdout tessdata 

tessdata content:
load_system_dawg F
load_freq_dawg F
language_model_penalty_non_dict_word F
language_model_penalty_non_freq_dict_word F
tessedit_char_whitelist BCDFGHJKLMNPQRSTVWXYZ0123456789

expected:
CDTL082

result:
CDTLGBZ

comments:
BAD RESULTS, appears that tesseract force all letters or all numbers.

-------------------------------------------------------------------
stn.jpg

commands:
convert stn.jpg -resize 300% stn-resize300.jpg
tesseract stn-resize300.jpg -psm 8 stdout tessdata 

tessdata content:
load_system_dawg F
load_freq_dawg F
language_model_penalty_non_dict_word F
language_model_penalty_non_freq_dict_word F
tessedit_char_whitelist BCDFGHJKLMNPQRSTVWXYZ0123456789

expected:
CDTL082

result:
CDTLGBZ

comments:
BAD RESULTS, appears that tesseract force to all letters or to all numbers.

-------------------------------------------------------------------
cpu.jpg

commands:
tesseract cpu.jpg -psm 7 stdout tessdata

tessdata content:
load_system_dawg F
load_freq_dawg F
language_model_penalty_non_dict_word F
language_model_penalty_non_freq_dict_word F
tessedit_char_whitelist BCDFGHJKLMNPQRSTVWXYZ0123456789@.

expected:
CPU G3260 @ 3.30GHz

result:
M BPH 63260 6 3.30912

comments:
BAD RESULTS

-------------------------------------------------------------------
cpu.jpg

commands:
convert cpu.jpg -resize 300% cpu-resize300.jpg
tesseract cpu-resize300.jpg -psm 7 stdout tessdata 

tessdata content:
load_system_dawg F
load_freq_dawg F
language_model_penalty_non_dict_word F
language_model_penalty_non_freq_dict_word F
tessedit_char_whitelist BCDFGHJKLMNPQRSTVWXYZ0123456789@.

expected:
CPU G3260 @ 3.30GHz

result:
W CPLJ 83260 @ 3.30GHZ

comments:
Better results, but still wrong.

-------------------------------------------------------------------
cpu.jpg

commands:
convert cpu.jpg -resize 300% cpu-resize300.jpg
convert cpu-resize300.jpg -threshold 40% cpu-threshold40.jpg
tesseract cpu-threshold40.jpg -psm 7 stdout tessdata

tessdata content:
load_system_dawg F
load_freq_dawg F
language_model_penalty_non_dict_word F
language_model_penalty_non_freq_dict_word F
tessedit_char_whitelist BCDFGHJKLMNPQRSTVWXYZ0123456789@.

expected:
CPU G3260 @ 3.30GHz

result:
F0 CPH 83260 @ 3.306HZ

comments:
Adding threshold still wrong, and looks like is better without threshold.

**Comment by zdenop** [comment]
see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice):
* For general questions and support please use the tesseract-ocr user forum.
* Read the wiki, search issues (also closed), search in the tesseract forum before you post your issues/question. Maybe it was solved already.
