### ISSUE TITLE
Tesseract calls exit(1) when trying to set an option it doesn't recognise

### ISSUE THREAD

**Issue by vibertk** [tesseract-ocr/tesseract#1520]
### Environment

* **Tesseract Version**: 4
* **Commit Number**: c0f9699e9ba8176634cb0dd04193dd808e4a4a2c
* **Platform**: Windows 32 and 64

### Current Behavior:
We are using tesseract as a dll. When reading in a traineddata file that has options at the start we found that tesseract crashes.

Doing some investigation we found that the issue occurs in Params.cpp->ReadParamsFromFp. If the option is not found then the code calls exit(1).

This might be fine when running tesseract as a standalone but when using it as a dll this causes an unpreventable crash. 

### Expected Behavior:

I would expect that unrecognised options should be ignored (outputting a message if appropriate) and tesseract continues on regardless. At the worst, an exception thrown that can be caught so that the main app can deal with the problem gracefully

### Suggested Fix:

Ignore the option and continue

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/5d22fdfeed901ec8b73c2f490ba84da9414f1b79/src/ccutil/params.cpp#L83

**Comment by stweil** [comment]
Thank you for reporting. This will be fixed with pull request #1920.

**Comment by stweil** [comment]
@zdenop, please add label "enhancement".
