### ISSUE TITLE
add smoke test on build, because of big endian failures

### ISSUE THREAD

**Issue by jbreiden** [tesseract-ocr/tesseract#1525]
### Environment

* **4.00.00alpha**: 
* **git2288-10f4998a**: 
* **S390 Ubuntu 18.04**: 

### Current Behavior:

Unit tests from OCRMyPDF provide strong evidence that Tesseract is segfauling on S390. This is a big endian architecture.

http://autopkgtest.ubuntu.com/packages/o/ocrmypdf/bionic/s390x

### Expected Behavior:

If something is totally wrong, we should know it ourself.  Not depend on someone else's test.

### Suggested Fix:

Suggest that we run one or more self tests during build. Especially packaging build. If that's already easy & available, please give me guidance on how to invoke. If not, let's add something.

**Comment by stweil** [comment]
@jbreiden, it looks like this is either fixed in the latest test (which passed) or a sporadic problem which cannot be reproduced 100 %. Is that correct?

Where can I get the PDF (or the PNG files for the pages) used for the failing test?

**Comment by AlexanderP** [comment]
@Shreeshrii no, only manually after assembly in VM

**Comment by jbreiden** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849094 for people who can supply `linn.pdf`

I think running tesseract on phototest.tif during build is probably enough of a smoke test.

**Comment by jbreiden** [comment]
Thinking more, maybe the smoke test should be part if the Debian package build and not the regular autotools build. It's not fair to make the autotools build require English traindata.

Also to my best understanding it problems on big endian happen every time. Ocrmypdf tests have started ignoring the failures. I think. It's all a little confusing.

**Comment by stweil** [comment]
I can now confirm that both the official Debian packages and latest Tesseract built from git master crash with SIGSEGV on big endian machines (tested on Debian buster s390x and mips). It's not possible to make OCR using traineddata_fast on such machines.

It currently looks like deserialisation might be causing the problem. Build cycles and tests in my QEMU based big endian emulation are extremely time consuming. @jbreiden, does Debian have some better big endian machines which I could use?

**Comment by Shreeshrii** [comment]
@stweil do the traineddata files from tessdata or tessdata_best repos work on these machines?

**Comment by stweil** [comment]
I tested tessdata_best with the latest code, and it fails with SIGSEGV, too.

And I‌ also just finished a test with tesseract 8e79297dcefecdb929d753d28554fec51417ec39. That is the first official version which should support big endian. Neither tessdata_best nor tessdata_fast were supported in that version (independent of endianness). The bad news is that it also fails with an [old tessdata](https://github.com/tesseract-ocr/tessdata/commit/eb769ead0516ecd3c83e10f27678e8fd9e474cb8) on big endian mips, so it looks as if we don't have a regression, but big endian LSTM never worked.

I wonder whether I should update pull request #703 (which worked on big endian).

**Comment by Shreeshrii** [comment]
Will  pull request #703
<https://github.com/tesseract-ocr/tesseract/pull/703> fix this issue or is
additional work needed after that to get big endian to work?

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by stweil** [comment]
#703 needs a lot of updates to match latest Tesseract code. I'm just working on that.

**Comment by jbreiden** [comment]
Debian does have big endian machines, there is a list of them here. I'm still trying to do the right dance with ssh keys to get access myself. I'll get back to you once there is progress.

https://db.debian.org/machines.cgi

**Comment by amitdo** [comment]
https://popcon.debian.org/stable/index.html


Statistics per Debian architectures

Number of submissions considered: 89013

amd64            : 80126  
i386             : 8408  


mips             : 12
s390x            : 4

**Comment by jbreiden** [comment]
I agree, big endian is very rarely used, and I won't shed a tear if it goes entirely extinct. However, if take Tesseract off of big endian machines, it causes a cascading dependency failure for hundreds of other packages. That's not great either.

**Comment by jbreiden** [comment]
@AlexanderP What do you think?

```
override_dh_auto_build:
	make -j$(NUMJOBS)
	make -j$(NUMJOBS) training
	./api/tesseract ./testing/phototest.tif - 
```

and  `tesseract-ocr-eng` in `Build-Depends`

**Comment by Chak-On** [comment]
Thank you for the help guys!!
Am gonna try doing that, t✌️✌️✌️✌️

**Comment by stweil** [comment]
[This line](https://github.com/tesseract-ocr/tesseract/blob/master/src/lstm/input.cpp#L52) is causing the crash on big endian machines. I'll send a fix tomorrow.

**Comment by stweil** [comment]
Pull request #1551 addresses the big endian issue.

**Comment by amitdo** [comment]
@stweil,

How does the current serialization implementation work?
Does it always save the model in little-endian format?

**Comment by stweil** [comment]
Ray's current implementation always saves in native endian format: little endian on little endian machines (=‌ most machines), big endian on big endian machines. I'd prefer to replace that by always using little endian (that reduces the complexity).

**Comment by jbreiden** [comment]
@AlexanderP updated the Debian builds. Now has @stweil's fix and a simple smoke test. Great.
