### ISSUE TITLE
Build Error on Debian Jessie

### ISSUE THREAD

**Issue by rolfschumacher** [tesseract-ocr/tesseract#1527]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below. 

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by rolfschumacher** [comment]
What I did:
cloned the git repository to my local disk, which created and filled a "tesseract" folder.
cd in tesseract, read INSTALL.GIT.md
entered "./autogen.sh" as normal user and later as root

What I expected:
no failure messages

What I got:
rsc@rolf29 ~/workspace/git/tesseract $ ./autogen.sh 
Running aclocal
Running /usr/bin/libtoolize
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
Running autoheader
Running automake --add-missing --copy
Makefile.am:21: error: required directory ./arch does not exist
Makefile.am:21: error: required directory ./ccutil does not exist
Makefile.am:21: error: required directory ./viewer does not exist
Makefile.am:21: error: required directory ./cutil does not exist
Makefile.am:21: error: required directory ./opencl does not exist
Makefile.am:21: error: required directory ./ccstruct does not exist
Makefile.am:21: error: required directory ./dict does not exist
Makefile.am:21: error: required directory ./classify does not exist
Makefile.am:21: error: required directory ./wordrec does not exist
Makefile.am:21: error: required directory ./textord does not exist
Makefile.am:21: error: required directory ./lstm does not exist
Makefile.am:21: error: required directory ./ccmain does not exist
Makefile.am:21: error: required directory ./api does not exist
Makefile.am:5: error: required directory ./training does not exist

  Something went wrong, bailing out!

**Comment by Shreeshrii** [comment]
Source code directory structure is currently being restructured.

Please use an earlier commit such as 
https://github.com/tesseract-ocr/tesseract/commit/e8fceb58ab2afabfe9dffd34ece58889db036735

**Comment by Shreeshrii** [comment]
@AlexanderP Do you have a package for Jessie?

**Comment by Shreeshrii** [comment]
Newer packages are available in testing. Please see 

https://github.com/tesseract-ocr/tesseract/wiki

**Comment by Shreeshrii** [comment]
>"tesseract my.pdf"

tesseract does not directly read pdfs. It works on image files, image formats supported in build should be shown with

tesseract -v

---------
Please install tesseract 4.0.0-beta-1

**Comment by AlexanderP** [comment]
I confirm. Build with autotools now does not work ...

**Comment by Shreeshrii** [comment]
Source code directory is currently being restructured. The makefiles will need changes to add src/ to filenames.

Please use an earlier commit such as
e8fceb5 

@stweil will be updating the repo to complete this reorganization.

**Comment by AlexanderP** [comment]
Thank you! Did not notice

**Comment by rolfschumacher** [comment]
used pypdfocr which in turn uses tesseract - work fine for me.

**Comment by stweil** [comment]
@rolfschumacher, the build errors should be fixed now. Please test and report any remaining problems or close this issue if everything works.

**Comment by rolfschumacher** [comment]
hmm - autogen.sh is improved, runs smoothly. But how about the ./configure step? There is a configure.ac but no configure shell script.

**Comment by stweil** [comment]
Running `./autogen.sh` creates `configure` from `configure.ac` (unless there was some error like missing preconditions).

**Comment by rolfschumacher** [comment]
You're right: I missed that the last sentence or running ./autogen.sh reads:
Missing autoconf-archive. Check the build requirements.
However, I do not know where to get autoconf-archive and where to find build requirements.
btw. I also cloned leptonica which build smoothly. Was that necessary? Was that wrong?

**Comment by stweil** [comment]
autoconf-archive is part of Linux distributions, Cygwin, MacPorts, ...

See the [wiki](https://github.com/tesseract-ocr/tesseract/wiki/Compiling-%E2%80%93-GitInstallation) for the build requirements and examples.

Leptonica does not require autoconf-archive.

**Comment by rolfschumacher** [comment]
Yes, thank you. That description was better suited for me: tessaeract --version gives:

tesseract 4.0.0-beta.1-192-g3c26
 leptonica-1.76.0
  zlib 1.2.8
 Found AVX2
 Found AVX
 Found SSE

**Comment by Shreeshrii** [comment]
@stweil I did `git pull origin` in my cloned local repo. It showed messages such as ` rename {ccstruct => src/ccstruct}/vecfuncs.h (98%)` etc., 

However looking in explorer all the old subfolders are still there, in addition to the new `src`.

**Comment by stweil** [comment]
You have to remove those old subfolders once manually, because they typically include generated files `Makefile.in` (which must be removed, too). Or start with a fresh clone from Git.

**Comment by Shreeshrii** [comment]
Thanks. I will do that.
