### ISSUE TITLE
Automatic Training with a Font File

### ISSUE THREAD

**Issue by skibulk** [tesseract-ocr/tesseract#153]
It seems to me that an automatic, font file training approach could generate substantially better results in just a few seconds. Characters in any font file have unicode mapped codepoints for easy alphanumeric / punctuation / language identification. The characters could be automatically rendered at multiple point sizes and trained at each size. A multi-lingual dictionary could be used to render and train thousands words in the selected typeface.

**Comment by jimregan** [comment]
The current training scripts already generate the images from font files, in much the way that you've described.
