### ISSUE TITLE
Multiple calls give different results for the same image

### ISSUE THREAD

**Issue by lorenzob** [tesseract-ocr/tesseract#1535]
### Environment

* **Tesseract Version**:

tesseract 3.05.01
 leptonica-1.75.3
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.6.20 : zlib 1.2.8

* **Commit Number**: (built from HEAD a few days ago, I do not know the exact commit number)

* **Platform**: Linux sentiero 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:

I create an api object and I use it multiple times to recognize the very same image. The first two calls return a low confidence value, the following ones gives an higher confidence. Depending on the image the recognized text could also be different (like is the case with the attached images).

Creating an api object every time or calling Init() every time fixes the problem but the confidence is always the lowest one.

I initially reported the problem here (with a slightly different version of the script):

https://github.com/sirfz/tesserocr/issues/106

I'm using a python wrapper, I do not know if it is part of the problem or not.

[tess-example.zip](https://github.com/tesseract-ocr/tesseract/files/1956382/tess-example.zip)

This is the output I get with the script and the attached images:

Tesseract version: 3.05.01
('8769254\n\n', [67])
('8769254\n\n', [67])
('8769254\n\n', [99])
('8769254\n\n', [99])
('8769254\n\n', [99])
work/AR 5748788-1/front/numbers.png
('5.748788\n\n', [83])
('5.748788\n\n', [83])
('5748788\n\n', [90])
('5748788\n\n', [90])
('5748788\n\n', [90])
again: data/numbers.png
('8769254\n\n', [99])
('8769254\n\n', [99])
('8769254\n\n', [99])
('8769254\n\n', [99])
('8769254\n\n', [99])

From command line I get this:

$ tesseract numbers-err.png -l ita+eng --psm 8  stdout
Warning. Invalid resolution 0 dpi. Using 70 instead.
5.748788

Calling the Init() every time helps but is not enough to definitely fix the problem: I still have a few cases where, this time recognizing different images in sequence, the result changes according to the order of the images (this may be a different variation of this problem). I can reproduce this problem too but I cannot share the images due to privacy concerns and it is not easy to recreate it with other images. On this second machine tesseract and leptonia were installed from PPA repos (similat versions).

I did a few more tests, with 50 images, and even creating a new instance of the api (and calling clear and end every time) does not fix the problem. I get different, consistent, wrong results depending on what elements I recreate or reuse.

@sirfz, tesserocr main developer, is not able to reproduce the problem. 

On another similar machine I am also not able to reproduce the error with this script, but I get the same "random" errors when I process a group of different images. For example processing a batch I get: "AR 51748788" while individually it is "AR 5748788" (the correct value). Calling Init() on this machine every time fixes the problem but I suspect it is just luck.

If I call GetThresholdedImage() I get strictly identical images in both cases.

### Expected Behavior:

Of course it should always give the same result :)

**Comment by amitdo** [comment]
It's probably related to the adaptive classifier which you can turn off.

**Comment by amitdo** [comment]
Try to set `classify_enable_learning` to `0` or `false`.

**Comment by zdenop** [comment]
This is not error but know and many time desired behavior. If it does not work for you, you need to turn off adaptive classifier as pointed by amitdo.
