### ISSUE TITLE
user_words_suffix not working

### ISSUE THREAD

**Issue by devendrasr** [tesseract-ocr/tesseract#1538]
We are trying to provide a user words file via available control params. Unfortunately I am getting below error - 

------------------------

### Environment

* **Tesseract Version**:
 tesseract 4.00.00alpha
 leptonica-1.74.4
 libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.1) : libpng 1.6.34 : libtiff 4.0.8 : zlib 1.2.11 : libwebp 0.6.0 : 
 libopenjp2 2.2.0
 Found AVX
 Found SSE
* **Platform**: Linux 9cadf37d2e9c 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
Using below params to supply user words file - 
``` sh
tesseract --user_words_file /usr/share/tesseract-ocr/4.00/tessdata/eng.user-words    -psm=1 -l=eng source.ppm res11 txt 
```

I am getting error as - 
``` 
read_params_file: parameter not found: P6
```
Is this supported in above tesseract version? I can see the support is mentioned in the help
```
user_words_file		A filename of user-provided words.
user_words_suffix            A suffix of user-provided words located in tessdata.
user_patterns_file            A filename of user-provided patterns.
user_patterns_suffix        A suffix of user-provided patterns located in tessdata.
```
Please note I have tried all possible options to supply the file - **user_words** | **user_words_file** | **user_words_suffix** |  **user_patterns_file** | **user_patterns_suffix**

Please suggest the right way to achieve the same.

Thanks,
  - Dev

**Comment by Shreeshrii** [comment]
Usage:
  tesseract --help | --help-extra | --version
  tesseract --list-langs
  tesseract imagename outputbase [options...] [configfile...]

Try giving the parameters as specified above.

Use the latest beta version from GitHub rather than alpha.

**Comment by Shreeshrii** [comment]
Also see https://github.com/tesseract-ocr/tesseract/issues/403

**Comment by Shreeshrii** [comment]
--version etc are part of the latest code on github, tesseract-4.0.0-beta .
not there in older versions.

tesseract 4.00.00dev-672-g7e4f5fa

That is
https://github.com/tesseract-ocr/tesseract/commit/7e4f5faa72244955f8dcb81b516ce11b7a12a959

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment]
`tesseract source.ppm res11 --psm 1 -l eng -c user_words_file=eng.user-words `

**Comment by Shreeshrii** [comment]
@devendrasr Please let us know the differences in **user-words** usage between

tesseract 4.00.00dev-672-g7e4f5fa

tesseract 4.00.00alpha

and

tesseract 4.0.0-beta-1 or current GitHub code

Is there any regression in how it works?

**Comment by Shreeshrii** [comment]
>read_params_file: Can't open 6

Use` --psm 6 `instead of `-psm 6`

**Comment by devendrasr** [comment]
thanks @Shreeshrii after modifying the command to 

```
tesseract source.ppm with-user-words  -l eng -psm 1 --user-words=eng.user-words
```
the command ran successfully but the results were not as expected. Somehow same [commit](https://github.com/tesseract-ocr/tesseract/commit/7e4f5faa72244955f8dcb81b516ce11b7a12a959) setup in another docker container is not producing expected results. 

--user-words is working with tesseract version 3 only. 

Can you please make it clear if tesseract 4 with/without lstm has got support for --user-words or not?

Other than this I have tried to use below steps too (in a separate install) to get user-words injected in traineddata but it does't seem working :(  

```
convert user-words to dawg file - 
wordlist2dawg eng.user-words eng.word-dawg eng.unicharset
combine word list to eng.traineddata - 
combine_tessdata -o eng.traineddata eng.word-dawg
```

**Comment by amitdo** [comment]
You might want to try 4.0.0-beta from master.

The new LSTM engine does not have adaptive learning stage.

**Comment by devendrasr** [comment]
It does't seem working to me with above branch. Somehow it works when we install it using mix and match instructions of below links - 
[link1](https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32) and [link2](https://bingrao.github.io/blog/post/2017/07/16/Install-Tesseract-4.0-in-ubuntun-16.04.html)
It must be working because we are installing in DEBUG MODE with this [commit:7e4f5fa](https://github.com/tesseract-ocr/tesseract/commit/7e4f5faa72244955f8dcb81b516ce11b7a12a959)

**Comment by Shreeshrii** [comment]
OK, I think I have figured out why it is NOT working.

See
https://github.com/tesseract-ocr/tesseract/blob/2645f72c4a9fecbb19dfe1dc04a94baf723c61b9/src/dict/dict.cpp#L214-295

and

https://github.com/tesseract-ocr/tesseract/blob/2645f72c4a9fecbb19dfe1dc04a94baf723c61b9/src/dict/dict.cpp#L297-316

void Dict::Load(const STRING &lang, TessdataManager *data_file)
is for legacy tesseract and needs to use lang.unicharset for converting wordlist to dawg

void Dict::LoadLSTM(const STRING &lang, TessdataManager *data_file) 
is for LSTM model and needs to use lsng.lstm-unicharset for converting wordlist to dawg

Lines
https://github.com/tesseract-ocr/tesseract/blob/2645f72c4a9fecbb19dfe1dc04a94baf723c61b9/src/dict/dict.cpp#L249-287
apply for user-words and user-patterns and should be loaded for both Dict::Load and Dict::LoadLSTM

@stweil Is this right?

**Comment by Shreeshrii** [comment]
Ok, I added the lines to Dict::LoadLSTM and it works, with the the following:

```
# tesseract test.png stdout --tessdata-dir ./tessdata --oem 0 -c page_separator=''
Dnline

# tesseract test.png stdout --tessdata-dir ./tessdata --oem 0 -c page_separator='' bazaar
Online


```
![test](https://user-images.githubusercontent.com/5095331/39809185-bd27a706-539e-11e8-9e60-3efb3b506a4c.png)

`Dnline ` is corrected to `Online`

I now need to find an image that does not work with tessdata_best and tessdata_fast in order to test further.

**Comment by amitdo** [comment]
Nice find!

> tesseract test.png stdout --tessdata-dir ./tessdata --oem 0 bazaar

`--oem 0` is supposed to use `Dict::Load()`.

**Comment by Shreeshrii** [comment]
>--oem 0 is supposed to use Dict::Load().

You are right. Haven't got it to work with --oem 1 yet.

**Comment by devendrasr** [comment]
@Shreeshrii Thanks for the help! It's seems working to me using oem 0 with latest commit, but I see only a few words are getting detected out of my list. 
Say I have 10 spell mistakes in my text but only few of them are getting corrected. 

Do we have any document/link to refer for the expected behaviour?

Thanks,
  - Dev

**Comment by codingforpleasure** [comment]
I have been working on:
**tesseract 4.0.0-beta.3-249-g607e
 leptonica-1.76.0
 libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 :**

and I have searched the web for few hours for finding a solution for user's words.
The steps I took:
Step 1: I have added the **eng.user-words** file  `<path-to-dir>/tessdata` on each line a single word 
Step 2:  I have added `<path-to-dir>/tessdata/configs/bazaar` for disabling the default dictionary and to use user-words, file content:
```
load_system_dawg     F
load_freq_dawg       F
user_words_suffix    user-words
```
Step 3: ran the command:

```
tesseract example.png stdout  with-user-words 
                                       -l eng
                                       --oem 1
                                       --psm 6 
                                       --user-words <path-to-dir>tessdata/eng.user-words
```

But it seems something is wrong,
@amitdo, @Shreeshriido do you have by any chance a suggestion what am i missing? :+1:

**Comment by Shreeshrii** [comment]
>https://github.com/tesseract-ocr/tesseract/issues/1538#issuecomment-387703855

**Comment by zdenop** [comment]
closed as duplicate to issue 403

**Comment by jtlz2** [comment]
> > --oem 0 is supposed to use Dict::Load().
> 
> You are right. Haven't got it to work with --oem 1 yet.

@Shreeshrii Is that still the case?
