### ISSUE TITLE
Various Hebrew fonts that need better recognition

### ISSUE THREAD

**Issue by MaxPower85** [tesseract-ocr/tesseract#1543]
Various Hebrew fonts on this page have recognition issues with Tesseract...

https://opensiddur.org/help/fonts/

You can click on the font name there to see various characters that it contains and if the font includes "Nikkud" (vowel marks), those are shown too... so you can improve the support for "Nikkud" too, if you want.

They also have a PDF with sample text in those fonts.

I've tried it with Tesseract 4 using both heb.traineddata from here https://github.com/tesseract-ocr/tessdata and from here https://github.com/tesseract-ocr/tessdata_fast

Historical typefaces need better recognition... and maybe you can add support for cursive Hebrew fonts too (letters aren't joined and you don't have to worry about capital or lowercase letters, so it should be easier than supporting some Latin font that looks "handwritten"), since text in those styles can appear in some books too or even on webpages sometimes

**Comment by amitdo** [comment]
Hi @MaxPower85!

>Various Hebrew fonts on this page have recognition issues with Tesseract...
>
>https://opensiddur.org/help/fonts/

I added a link to that page a while ago.
https://github.com/tesseract-ocr/tesseract/wiki/Fonts#hebrew-fonts

Related issue: 
https://github.com/tesseract-ocr/langdata/issues/82

**Comment by amitdo** [comment]
Usually, if a quote from the bible is used in a book or an article, the cantillation marks are dropped.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
