### ISSUE TITLE
Would it be possible to somehow support English "long s" character (the "ſ" character) which many old books use?

### ISSUE THREAD

**Issue by MaxPower85** [tesseract-ocr/tesseract#1545]
Many older books in English use the “long s” (which is/was a separate letter and there is an UTF-8 character “ſ” for it, which looks almost like an “f”, but without the line on it or just with a small line on the left side, but not on the right side)… I mean this: https://en.wikipedia.org/wiki/Long_s

So it’s not just some style that some “old-looking” fonts use for an “s”… it was actually a letter different from “s” that old books used besides “s”, like in a word “Uſefulneſs” (Usefulness).

Many old books that were published before 20th century have it and high resolution scans of books like those can be found online since they are in Public Domain… so, many people may wish to do OCR on them, even if they are also available in PDF form with searchable text because PDFs of those old books often have many errors that OCR software has made because it confused “ſ” with an “f” or some other letter.

Here are a couple of example out of many: 
https://archive.org/details/artistsvademecum00laur
https://archive.org/details/gri_33125008226413

(you can get high resolution scans of the book in JPEG2000 format if you click on “SINGLE PAGE PROCESSED JP2 ZIP”)
There are lots and lots of old books on Archive.org and many have OCR mistakes when downloaded as a PDF.

Could it be added to English, but only used if the resolution was hight enough to clearly distinguish “ſ” from an “f”, to clearly detect that there aren't any traces of a line on the right side?

That could help someone a lot to digitalize old books more accurately, without having to do lots and lots of manual corrections.

**Comment by stweil** [comment]
Try `script/Fraktur` or `frk` – both contain the long S (ſ) and some ligatures which are also needed. In addition, using a different word list is useful for old texts (otherwise Tesseract finds words like "Google" even in historic texts.

**Comment by stweil** [comment]
Maybe you are interested in a German project which has a focus on OCR for historic texts, see https://github.com/OCR-D.

**Comment by stweil** [comment]
I forgot that there is also `enm`, the trained data for old English which also has the long S. Here is the complete list of all languages and scripts with that character:

    enm/enm.lstm-unicharset:ſ 3 0,255,0,255,0,0,0,0,0,0 Latin 20 0 90 s	# ſ [17f ]a
    Fraktur/Fraktur.lstm-unicharset:ſ 3 0,255,0,255,0,0,0,0,0,0 Latin 20 0 90 s	# ſ [17f ]a
    frk/frk.lstm-unicharset:ſ 3 0,255,0,255,0,0,0,0,0,0 Latin 13 0 82 s	# ſ [17f ]a
    frm/frm.lstm-unicharset:ſ 3 0,255,0,255,0,0,0,0,0,0 Latin 18 0 106 s	# ſ [17f ]a
    ita_old/ita_old.lstm-unicharset:ſ 3 0,255,0,255,0,0,0,0,0,0 Latin 12 0 92 s	# ſ [17f ]a
    spa_old/spa_old.lstm-unicharset:ſ 3 0,255,0,255,0,0,0,0,0,0 Latin 9 0 109 s	# ſ [17f ]a

**Comment by stweil** [comment]
@MaxPower85, can this issue be closed?

**Comment by whisere** [comment]
Hello I wonder how the ground truth for enm.traineddata was created, which font was used to produced the long s in historical text? And what datasets/text (that containing ſ and ſ?) were used to automatically generated the ground truth  ? Thanks.

**Comment by whisere** [comment]
also Æ for ae etc.

**Comment by stweil** [comment]
That's all available information: https://github.com/tesseract-ocr/langdata_lstm/tree/main/enm.
It contains some training text and a list of fonts.

**Comment by whisere** [comment]
Thank you! Is there way to know what is all the original ground truth used in the enm model training, and how the ground truth was created? This is related to https://github.com/tesseract-ocr/tessdata/issues/156
Thanks!

**Comment by stweil** [comment]
We simply don't know the answer as the training was done at Google and there are only some hints in several issues.

**Comment by wollmers** [comment]
I see no issue at all.

The training files at https://github.com/tesseract-ocr/langdata_lstm/tree/main/enm look good and have long s.

Just a try with a page https://github.com/wollmers/ocr-deu-bio-testfiles/blob/master/naturgeschichte00gt/naturgeschichte00gt_0014.png in German Fraktur (typical 18th century):

```
ocr-deu-bio-testfiles/naturgeschichte00gt$ tesseract naturgeschichte00gt_0014.png naturgeschichte00gt_0014.l_enm -l enm --psm 6 --tessdata-dir  /usr/local/share/tessdata txt pdf hocr
Tesseract Open Source OCR Engine v5.0.0-alpha-773-gd33ed with Leptonica
Warning: Invalid resolution 0 dpi. Using 70 instead.

$ cat naturgeschichte00gt_0014.l_enm.txt | grep ſ
ben , miiſſen es bfters mehr dem Zufall als ihree
GeſcHicflichkeit verdanfen. Aber ſon genannte
Naturalien genauer zu beſhreiben und zu bes
ſtimmen , als bisher geſchehen, dazu iſt mehr
Gelegenheit vorhanden, und auch dieſe Bemys
bung iſt niiglich und verdienſilich. ,, — Dieſ
fage im Hanauiſhen Magazin, welce
die Maturgeſchichte einiger Vsgel betreffen,
mchrere Aufinerkſamkeit zu verwenden , und ſie
bishu mit allem FJleifſe groſtentheils ganz aus-
gUarbeiten. Die ſeltenſten unter den hier bes
ſchriebmnen Vegeln befinden ſi in der hieſigen
* F$in{il. Phaſanerie, wo ich ſie nach Gefallen
beobachten und die Beobachtungen des Phaſa#- _
fi< von dieſen und den Ubrigen wohl erhaltene
meiner Aufſicht ſtehenden Naturalienkabinete
der Durchlauchtigſten Prinzeſſin Marie
/ Friederike zu Heſſen. Die Scthriftſteller
\ \ 4abl iſt} hier alle qu nennen; whrde gu weiclauſtig
\ ſein 3
```

Not the best quality as it isn't trained on German alphabet (äöüÄÖÜß), texts and typical typefaces, but it supports longs s.

**Comment by whisere** [comment]
Thank you. I don't have issue with the long S.. just wanted to know how the historical English ground truth for training was created, and what datasets were used. Thanks.
