### ISSUE TITLE
It would be good if Hebrew OCR could detect Latin words like how Serbian Cyrillic .traineddata can detect a switch to Latin

### ISSUE THREAD

**Issue by MaxPower85** [tesseract-ocr/tesseract#1548]
After noticing that .traineddata for Serbian Cyrillic can detect a switch to Latin when there are like several Latin words in a row, I thought that I should mention this...

Since Hebrew looks much more distinct from Latin, it should be easier for OCR engine to detect if there is an English word in a Hebrew text... and it would be really good to have that, especially if someone wanted to do OCR of some books for learning Hebrew or some dictionary or something like that...

Obviously, in cases where it is not very clear is it Hebrew or Latin (like if there were just some individual letters that can look similar in some fonts), then it should just default to Hebrew... like if there was just the Latin letter "I" somewhere, it shouldn't assume that it would be a Latin letter if there aren't any Latin letters near it because "vav" (letter "ו") in Hebrew can look kind of similar in some fonts.

But if there are whole words and it is very clear is it Latin or Hebrew, then it would be very useful to detect the switch.

**Comment by amitdo** [comment]
Something like this is already implemented:
https://github.com/tesseract-ocr/tessdata_fast/blob/master/script/Hebrew.traineddata

**Comment by stweil** [comment]
@MaxPower85, is that solution sufficient? Or does giving more than one language to Tesseract help? Then please close this issue.

**Comment by amitdo** [comment]
@zdenop, please close this issue.

**Comment by MaxPower85** [comment]
I've tested the "Hebrew.traineddata" now... yes, that seems to work for texts that have mixed Hebrew and English words... 

But it would be good if there was a version of "Hebrew.traineddata" in https://github.com/tesseract-ocr/tessdata and https://github.com/tesseract-ocr/tessdata_best also.

**Comment by Shreeshrii** [comment]
It should be there in tessdata_best. Look under the script folder.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
