### ISSUE TITLE
OCR accuracy with "Ultra Light" and "Ultra Light Italic" fonts at large font sizes and some other common fonts

### ISSUE THREAD

**Issue by MaxPower85** [tesseract-ocr/tesseract#1553]
I had issues with OCR trying to recognize text from Retina screenshots with some Ultra Light fonts at larger sizes (sizes like 18px for the font size or maybe even 24px or 48px... so the text should be very clear, especially since Retina screenshots would use 4 times larger resolution, or twice as wide & twice as high)... for English it wasn't like "very bad", but at those font sizes and resolution, someone would expect all characters to be recognized accurately... and there were some issues, especially with 7s (they seem to be confused with "/" often when some fonts are used)... but for various non-English languages that use Latin or Cyrillic, the accuracy seems to be low with Ultra Light fonts.

If someone can confirm the issue for English, maybe someone could fine-tune .traineddata files to accurately recognize Ultra Light fonts at large sizes... without confusing "7" with "/" often and things like that... for small sizes, it's probably not necessary, since Ultra Light fonts are mostly used at larger sizes because of how thin they are

When not using English, it really seems like that non-English languages need better optimization for Ultra Light fonts... so I think that the issue probably is that .traineddata just need more training with those fonts.

I'll write the names of some fonts, for someone to check the accuracy with Tesseract 4 with .traineddata from https://github.com/tesseract-ocr/tessdata

I also tried it with tessdata_fast, but it seemed even less accurate

Try it with different variations of these fonts, especially with the Ultra Light (or Extra Light) versions and Ultra Light Italic versions... Helvetica Neue, Gill Sans, Source Sans Pro, GT America, Avenir Next... and other similar looking fonts... 

Also... OCR seems to have issues with lowercase "i" especially with Georgia Regular... it seems to "confuse" it with number "1" very often because "i" and "1" in that font look similar, even though "i" clearly has a dot... with Courier Regular, Courier New Regular, Cochin Regular, Times New Roman Regular and Monaco Regular there also seems to be a similar issue, although "1" and "i" in those fonts look more distinct... although issues like those would probably be expected at small sizes if it's not very clear is the dot there or is it just some noise, so for smaller sizes it would maybe be OK... but for larger sizes someone would expect it to clearly distinguish "1" from "i".

With Skia there seem to be issues recognizing number "9" (it gets confused with a "0")

In some cases, there even seem to be issues with some characters when Verdana or Arial are used with "7" and lowercase "l" (lowercase L)

Try something like this at 18px and 24px font sizes and maybe a few other larger sizes and check that everything was recognized correctly... try all fonts that I mentioned... and test non-Enlish OCR too (all these fonts seem to support characters used for Serbian Latin / Croatian / Slovenian... etc... and most support Cyrillic too).

> luxurious ... luxury ... luxuriousness ... let it snow ... lemur ... lol ... lump ... lulu ... let's go
>let's try random number combinations
> 257,767,890,275,143,197,876 
> 257.767.890.275.143.197.876 
> some more numbers, with and without additional characters
>1234567890 0987654321 11223344556677889900
>1/2/3/4/5/6/7/8/9/0/ \1\2\3\4\5\6\7\8\9\0\ 
>(1)(2)(3)(4)(5)(6)(7)(8)(9)(0)
>[1][2][3][4][5][6][7][8][9][0]
>{1}{2}{3}{4}{5}{6}{7}{8}{9}{0}
>-1-2-3-4-5-6-7-8-9-0-
>'1'2'3'4'5'6'7'8'9'0'
>1,2,3,4,5,6,7,8,9,0,
>1.2.3.4.5.6.7.8.9.0
> 1:2:3:4:5:6:7:8:9:0
>1+2+3+4+5+6+7+8+9+10 1x2x3x4x5x6x7x8x9x10x
> 1@2@3@4@5@6@7@8@9@0@ 0@9@8@7@6@5@4@3@2@1
> 1st, 2nd, 3rd, 4th, 5th, 6th, 7th, 8th, 9th, 10th
> and in a sentence...
>is it 1st or is it 2nd or maybe 9th... or maybe it's 7th
>ABCDEFGHIJKLMNOPQRSTUVWXYZ ZYXWVUTSRQPONMLKJIHGFEDCBA
>abcdefghijklmnopqrstuvwxyz zyxwvutsrqponmlkjihgfedcba
>AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz
>AaBaCaDaEaFaGaHaIaJaKaLaMaNaOaPaQaRaSaTaUaVaWaXaYaZa
>AeBeCeDeEeFeGeHeIeJeKeLeMeNeOePeQeReSeTeUeVeWeXeYeZe
>AiBiCiDiEiFiGiHiIiJiKiLiMiNiOiPiQiRiSiTiUiViWiXiYiZi
>AoBoCoDoEoFoGoHoIoJoKoLoMoNoOoPoQoRoSoToUoVoWoXoYoZo
>AuBuCuDuEuFuGuHuIuJuKuLuMuNuOuPuQuRuSuTuUuVuWuXuYuZu
>aabacadaeafagahaiajakalamanaoapaqarasatauavawaxayaza
>aebecedeeefegeheiejekelemeneoepeqereseteuevewexeyeze
>aibicidieifigihiiijikiliminioipiqirisitiuiviwixiyizi
>aobocodoeofogohoiojokolomonooopoqorosotouovowoxoyozo
>aubucudueufuguhuiujukulumunuoupuqurusutuuuvuwuxuyuzu
>A'B'C'D'E'F'G'H'I'J'K'L'M'N'O'P'Q'R'S'T'U'V'W'X'Y'Z'
>a'b'c'd'e'f'g'h'i'j'k'l'm'n'o'p'q'r's't'u'v'w'x'y'z'
>A a B b C c D d E e F f G g H h I i J j K k L l M m N n O o P p Q q R r S s T t U u V v W w X x Y y Z z

To test for some non-English characters (if doing OCR for non-English languages)

> Additional characters for Serbian Latin/Croatian/Slovenian: Š š Đ đ Č č Ć ć Ž ž Â â 
> ŠaĐaČaĆaŽa ŠeĐeĆeŽe ŠiĐiČiĆiŽi ŠoĐoČoĆoŽo ŠuĐuČuĆuŽu 
> šađačaćaža šeđečećeže šiđičićiži šođočoćožo šuđučućužu
> ŠAĐAČAĆAŽA ŠEĐEČEĆEŽE ŠIĐIČIĆIŽI ŠOĐOČOĆOŽO ŠUĐUČUĆUŽU
> Š, Đ, Č, Ć, Ž, š, đ, č, ć, ž, Š.Đ.Č.Ć.Ž. š.đ.č.ć.ž. Š:Đ:Č:Ć:Ž: š:đ:č:ć:ž: Š'Đ'Č'Ć'Ž' š'đ'č'ć'ž'

(BTW... Â and â need to be added for Serbian and Croatian, as I mentioned in another issue)

Without English words... to test OCR for languages that use Cyrillic or some other script:

> 257,767,890,275,143,197,876
> 257.767.890.275.143.197.876
> 1234567890 0987654321 11223344556677889900
> 1/2/3/4/5/6/7/8/9/0/ \1\2\3\4\5\6\7\8\9\0\
> (1)(2)(3)(4)(5)(6)(7)(8)(9)(0)
> [1][2][3][4][5][6][7][8][9][0]
> {1}{2}{3}{4}{5}{6}{7}{8}{9}{0}
> -1-2-3-4-5-6-7-8-9-0-
> '1'2'3'4'5'6'7'8'9'0'
> 1,2,3,4,5,6,7,8,9,0,
> 1.2.3.4.5.6.7.8.9.0
> 1:2:3:4:5:6:7:8:9:0
> 1@2@3@4@5@6@7@8@9@0@ 0@9@8@7@6@5@4@3@2@1
>1+2+3+4+5+6+7+8+9+10 1x2x3x4x5x6x7x8x9x10x

To test Serbian Cyrillic... various combinations of letters:

> АБВГДЂЕЖЗИЈКЛЉМНЊОПРСТЋУФХЦЧЏШ
> ШЏЧЦХФУЋТСРПОЊНМЉЛКЈИЗЖЕЂДГВБА
> А, Б, В, Г, Д, Ђ, Е, Ж, З, И, Ј, К, Л, Љ, М, Н, Њ, О, П, Р, С, Т, Ћ, У, Ф, Х, Ц, Ч, Џ, Ш,
> А.Б.В.Г.Д.Ђ.Е.Ж.З.И.Ј.К.Л.Љ.М.Н.Њ.О.П.Р.С.Т.Ћ.У.Ф.Х.Ц.Ч.Џ.Ш.
> -А-Б-В-Г-Д-Ђ-Е-Ж-З-И-Ј-К-Л-Љ-М-Н-Њ-О-П-Р-С-Т-Ћ-У-Ф-Х-Ц-Ч-Џ-Ш-
> (А)(Б)(В)(Г)(Д)(Ђ)(Е)(Ж)(З)(И)(Ј)(К)(Л)(Љ)(М)(Н)(Њ)(О)(П)(Р)(С)(Т)(Ћ)(У)(Ф)(Х)(Ц)(Ч)(Џ)(Ш)
> /А/Б/В/Г/Д/Ђ/Е/Ж/З/И/Ј/К/Л/Љ/М/Н/Њ/О/П/Р/С/Т/Ћ/У/Ф/Х/Ц/Ч/Џ/Ш/
> \А\Б\В\Г\Д\Ђ\Е\Ж\З\И\Ј\К\Л\Љ\М\Н\Њ\О\П\Р\С\Т\Ћ\У\Ф\Х\Ц\Ч\Џ\Ш\
> [А][Б][В][Г][Д][Ђ][Е][Ж][З][И][Ј][К][Л][Љ][М][Н][Њ][О][П][Р][С][Т][Ћ][У][Ф][Х][Ц][Ч][Џ][Ш]
> абвгрђежзијклљмнњопрстћуфхцчџш
> шџчцхфућтсрпоњнмљлкјизжеђдгвба
> а, б, в, г, р, ђ, е, ж, з, и, ј, к, л, љ, м, н, њ, о, п, р, с, т, ћ, у, ф, х, ц, ч, џ, ш,
> а.б.в.г.р.ђ.е.ж.з.и.ј.к.л.љ.м.н.њ.о.п.р.с.т.ћ.у.ф.х.ц.ч.џ.ш.
> -а-б-в-г-р-ђ-е-ж-з-и-ј-к-л-љ-м-н-њ-о-п-р-с-т-ћ-у-ф-х-ц-ч-џ-ш-
> (а)(б)(в)(г)(р)(ђ)(е)(ж)(з)(и)(ј)(к)(л)(љ)(м)(н)(њ)(о)(п)(р)(с)(т)(ћ)(у)(ф)(х)(ц)(ч)(џ)(ш)
> /а/б/в/г/р/ђ/е/ж/з/и/ј/к/л/љ/м/н/њ/о/п/р/с/т/ћ/у/ф/х/ц/ч/џ/ш/
> \а\б\в\г\р\ђ\е\ж\з\и\ј\к\л\љ\м\н\њ\о\п\р\с\т\ћ\у\ф\х\ц\ч\џ\ш\
> [а][б][в][г][р][ђ][е][ж][з][и][ј][к][л][љ][м][н][њ][о][п][р][с][т][ћ][у][ф][х][ц][ч][џ][ш]
> А а Б б В в Г г Д д Ђ ђ Е е Ж ж З з И и Ј ј К к Л л Љ љ М м Н н Њ њ О о П п Р р С с Т т Ћ ћ У у Ф ф Х х Ц ц Ч ч Џ џ Ш ш
> АаБаВаГаДаЂаЕаЖаЗаИаЈаКаЛаЉаМаНаЊаОаПаРаСаТаЋаУаФаХаЦаЧаЏаШа
> АеБеВеГеДеЂеЕеЖеЗеИеЈеКеЛеЉеМеНеЊеОеПеРеСеТеЋеУеФеХеЦеЧеЏеШе
> АиБиВиГиДиЂиЕиЖиЗиИиЈиКиЛиЉиМиНиЊиОиПиРиСиТиЋиУиФиХиЦиЧиЏиШи
> АоБоВоГоДоЂоЕоЖоЗоИоЈоКоЛоЉоМоНоЊоОоПоРоСоТоЋоУоФоХоЦоЧоЏоШо
> АуБуВуГуДуЂуЕуЖуЗуИуЈуКуЛуЉуМуНуЊуОуПуРуСуТуЋуУуФуХуЦуЧуЏуШу
> аабавагарађаеажазаиајакалаљаманањаоапарасатаћауафахацачаџаша
> аебевегеређееежезеиејекелељеменењеоепересетећеуефехецечеџеше
> аибивигириђиеижизииијикилиљиминињиоипириситићиуифихицичиџиши
> аобовогорођоеожозоиојоколољмоноњооопоросотоћоуофохоцочоџошо
> аубувугуруђуеужузуиујукулуљумунуњуоупурусутућуууфухуцучуџушу

(BTW... Â and â should be added for Serbian Cyrillic too, even though Â and â are technically Latin characters... but lots of people seem to use them in Serbian Cyrillic, just as they do for Serbian Latin / Croatian... you can search on Google for example for "сâм" with quotes and there are many examples of people using that letter in Serbian Cyrillic texts).

**Comment by zdenop** [comment]
Closing it here because this issue tracker is dedicated to OCR engine only.
Please check also https://github.com/tesseract-ocr/tessdata_best and [tessdata_fast](https://github.com/tesseract-ocr/tessdata_fast) and make there your report,
Eventually make PR to [langdata_lstm](https://github.com/tesseract-ocr/langdata_lstm).
