### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by loralyc** [tesseract-ocr/tesseract#1560]
hello,
I got error when i compile thd latest Tesseract 4.0. could you give me a suggestion? thanks!
Platform:Ubuntu 14.04.5 LTS
gcc: 4.8.4 
g++:4.8.4

i was refer to the instructions in github [https://github.com/tesseract-ocr/tesseract/wiki/Compiling-%E2%80%93-GitInstallation](url)

1.sudo apt-get install g++ # or clang++ (presumably)  
sudo apt-get install autoconf automake libtool  
sudo apt-get install autoconf-archive  
sudo apt-get install pkg-config  
sudo apt-get install libpng12-dev  
sudo apt-get install libjpeg8-dev  
sudo apt-get install libtiff5-dev  
sudo apt-get install zlib1g-dev  
sudo apt-get install libicu-dev  
sudo apt-get install libpango1.0-dev  
sudo apt-get install libcairo2-dev  

2.then i compile the leptonica  by:
sudo apt install git  
git clone https://github.com/DanBloomberg/leptonica   
cd leptonica  
autoreconf -vi  
./autobuild  
./configure  
make 
sudo make install 

3.then i download the tesseract in the same level directory with leptonica  
git clone --depth 1 https://github.com/tesseract-ocr/tesseract.git  
cd tesseract  
./autogen.sh  
./configure --enable-debug  
LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make  
sudo make install  
sudo ldconfig

when i conduct to the step: LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make ,
the error occured:
mv -f .deps/tesseract-tesseractmain.Tpo .deps/tesseract-tesseractmain.Po
/bin/bash ../../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11   -o tesseract tesseract-tesseractmain.o libtesseract.la -L/usr/local/lib -llept   -fopenmp  -lrt -lpthread 
libtool: link: g++ -g -O2 -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o -fopenmp  ./.libs/libtesseract.so -L/usr/local/lib /usr/local/lib/liblept.so -lrt -lpthread -fopenmp
/usr/local/lib/liblept.so: undefined reference to `TIFFReadScanline@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFCleanup@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFSetDirectory@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFPrintDirectory@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFGetVersion@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFGetFieldDefaulted@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFCurrentDirOffset@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFSetSubDirectory@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFOpen@LIBTIFF_4.0'
/usr/local/lib/liblept.so: undefined reference to `TIFFReadRGBAImageOriented@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status

**Comment by stweil** [comment]
Setting `CFLAGS` has no effect – Tesseract only uses `CXXFLAGS`.
Using `LDFLAGS="-L/usr/local/lib -ltiff" should fix your problem.

**Comment by loralyc** [comment]
i try it, but the same error. did you have another idea? @stweil

**Comment by stweil** [comment]
Maybe the order of the libraries is important. What about `LDFLAGS="-L/usr/local/lib -llept -ltiff"`?

**Comment by zdenop** [comment]
Compiling software from source requires knowledge (at least of your OS and compiling software). 
Please stop to misuse of tesseract issue tracker as free course from programming. Tesseract is available for Ubuntu, so you can use it without need to compile it from source.
