### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [tesseract-ocr/tesseract#1564]
Hello! I want to contribute on your project with making logo design. What do you think about it?

Arslan Şahin
Graphics Designer

**Comment by zdenop** [comment]
It could be great - we are planing to release new version 4.0 soon. Can you provide some suggestions?

**Comment by christophered** [comment]
@Arslanshn can you post your logo concept and sketch for us to see.
@zdenop in the finalized 4.0 will it include an "annotation tool" similar to ocropy & kraken? in-which we can provide our own scanned images, and tesseract segments all the lines/ words, and outputs an html file for us to transcribe, later-on can be used for training. will this feature be implemented?
![gt](https://user-images.githubusercontent.com/33478216/39887316-9aafe6e6-549a-11e8-9c38-697573590e4b.png)

**Comment by stweil** [comment]
@christophered, you can use the existing tools which you already named, or use other tools like the [ocr-gt-tools](https://github.com/UB-Mannheim/ocr-gt-tools). I don't expect a new tool for Tesseract.

**Comment by zdenop** [comment]
I am closing this, because there is nothing what tesseract developers can do with original topic.

**Comment by christophered** [comment]
@stweil calm down, I think tesseract 4.x is great, all I was asking about was the ability to train our own scanned documents.
