### ISSUE TITLE
Can't find the folder named api,training and so on

### ISSUE THREAD

**Issue by loralyc** [tesseract-ocr/tesseract#1566]
hello,
i am confused that i already compile tesseract successful, can past the test and out the result, but i found it lost some folder and file, such as  api, training .... (without these i can't try to train new data)
Maybe I still have nothing to do? could you give me some suggestion? thanks.
tesseract 4.0
Platform:Ubuntu 14.04.5 LTS
gcc: 4.8.4

**Comment by zdenop** [comment]
Building from source requires knowledge.
Building from development source (git master) request to follows changes.
Please use tesseract user forum for asking support (or better try to use google before posting anything).

**Comment by loralyc** [comment]
sorry, i try to search it but i can't find answer, maybe i described it  improper.Next time i will use tesseract user forum first. Thank you all the same.@zdenop
