### ISSUE TITLE
new logo proposal

### ISSUE THREAD

**Issue by Arslanshn** [tesseract-ocr/tesseract#1570]
hello sorry for the delay :(
![tesseract](https://user-images.githubusercontent.com/36132662/39890333-2000472a-54a3-11e8-889d-bbfbe3c4e887.png)

**Comment by zdenop** [comment]
Just to avoid misunderstanding: can you clarify licence of your artwork?

**Comment by Arslanshn** [comment]
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Lisansı" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Bu eser <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"> Creative Commons Atıf 4.0 Uluslararası Lisansı</a> ile lisanslanmıştır.

**Comment by zdenop** [comment]
Thanks. 
Can you please explain idea behind logo? Right&Bottom slice is clear for me, but Left&Top is not...

**Comment by Arslanshn** [comment]
![tesseractlogo](https://user-images.githubusercontent.com/36132662/39891386-13796236-54a6-11e8-9856-a99a0923a9f2.png)

**Comment by stweil** [comment]
Creative Commons suggests [not to use their licenses for a logo](https://creativecommons.org/faq/#could-i-use-a-cc-license-to-share-my-logo-or-trademark).

**Comment by christophered** [comment]
@zdenop @stweil I didn't like this logo, it's not clear.

**Comment by christophered** [comment]
@Arslanshn my suggestion would be a Cube and some papers within that cube:
![cafeto-concept-compressed-80](https://user-images.githubusercontent.com/33478216/39959038-6fc2a628-5614-11e8-96d8-f82de07a6d87.jpg)
![cube_1x-compressed-80](https://user-images.githubusercontent.com/33478216/39959052-a097227e-5614-11e8-9c4b-41c6c17cb9b5.jpg)
![tesseracth-01-compressed-80](https://user-images.githubusercontent.com/33478216/39959054-aa7b6138-5614-11e8-9961-25d137dcb43b.jpg)
![cube-compressed-80](https://user-images.githubusercontent.com/33478216/39959056-b465f258-5614-11e8-916d-27b2c860de40.jpg)

**Comment by christophered** [comment]
![download 2](https://user-images.githubusercontent.com/33478216/39959099-533bb566-5615-11e8-8c38-eb1b4c8dd359.png)

**Comment by Arslanshn** [comment]
https://drive.google.com/drive/folders/1o3c7RMAvadkzJhjFc_VX9P9EwmLBTyMc?usp=sharing

**Comment by lifeinchords** [comment]
that orange pinkish one from [now-deleted] @ghost was awesome.. memorable. 
@Arslanshn 's logo is also memorable.. maybe a bit too busy at small sizes, but that can be worked out..  

Why were these never used? Proj could def use a sweet logo.
