### ISSUE TITLE
Why the traineddata i got from the fine tuning even can't recognize the words as it's based traineddata(download from github)?

### ISSUE THREAD

**Issue by dyygs** [tesseract-ocr/tesseract#1572]
### Environment

* **Tesseract Version**: 4.0
* **Commit Number**: latest version
* **Platform**: centos 7

### Current Behavior:

Hello guys, I follow [Tesseract 4.0 training](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for--a-few-characters) to Fine Tuning the best chi_sim.traineddata i got from github.

I add some "ABCD" to chi_sim.training_files to Fine Tuning for the old chi_sim.traineddata recognized "ABCD" to "4BCD". The other training steps is similar with [FINE TUNING](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for--a-few-characters).At the end , the rate error is 5.358.

But when training is complete, the new traineddata even can't recognize the words as the old traineddata, what's the reason? I will appreciate any reply ! Thanks.

**Comment by christophered** [comment]
@dyygs you need to provide more information:
- What commands did you use to ( generate your initial data, train, combine) also provide the result logs.
- How many iterations & hours did you train for?
- Did you see fluctuation in the error rate (increase or decrease), or was it mostly constant?

My guess of the problem is that you might:
0- Generated your initial data wrongly
1- Used `max_iterations` , the solution is to use `target_error_rate`
2- When combining, you might used the wrong `traineddata`

Unless you provide the 3 commands that you used & their logs (outcome in terminal), you wont get serious help, my guess is that you have a couple of hours before your topic gets closed for posting in the wrong place, so reply soon.

**Comment by dyygs** [comment]
@christophered     Thanks for your reply !!
This is the training file i use. And i change `max_iterations` to `target_error_rate`, the logs will be uploaded after the new training(`target_error_rate`).

[chi_sim_train.zip](https://github.com/tesseract-ocr/tesseract/files/2003219/chi_sim_train.zip)

Let me describe the problems i want to solve. 

![test](https://user-images.githubusercontent.com/18184561/40032994-0f10719a-5829-11e8-825f-4b682187082d.png)


This is the picture I want to recognize, when I use the `chi_sim_best.traineddata`, I got the output files like this.

`如 图 ， 在 长 方形 MB0D 中 ，4 人 4，5r8， 将 长 方形 4500`

So I want to use FINE TUNING to resolve it .Firstly I add some `ABCD` and etc.

I want to know if the FINE TUNING I use was the correct way to solve this problems?

If it's correct, after I train `ABCD`, what I should do with the other characters like `< =` ? Because I can't add all unrecognized characters to `chi_sim.training_text` for FINE TUNING.


If it's wrong.what's the best way to solve it ?

Thanks for your help again!

**Comment by dyygs** [comment]
@christophered 
Further more, i realize the problem is because `Italic`  fonts, could you give some suggestion?

**Comment by christophered** [comment]
@dyygs Basically you need to train using a similar font & style (italic) to the one you need.
- Once you find your desired font that you want to use in training, **install it.**
- Then you need to **list all available fonts that you have installed** on your system.
- Finally, when using the training script "tesstrain.sh" you need to specify the font that you want to use via `--fonts_dir` & `--fontlist ""`

Find your installed fonts:
https://github.com/tesseract-ocr/tesseract/wiki/Fonts#find-fonts

List of font names:
https://github.com/tesseract-ocr/tesseract/blob/d8c04e8/training/language-specific.sh#L36

**Comment by dyygs** [comment]
@christophered  OK， Thanks. I understand what you mean, but there is still a problem.

For the pictures that produces by some software(like microsoft office word), there is no  `Italic` style  fonts available, what should i do for that?

![word_github](https://user-images.githubusercontent.com/18184561/40037556-7a25f13c-5840-11e8-8a59-e217f13c2039.png)

**Comment by Shreeshrii** [comment]
@dyygs 

Have you tried the HanS traineddata from https://github.com/tesseract-ocr/tessdata_best/tree/master/script

Does that give better result for your image?

**Comment by Shreeshrii** [comment]
![1542](https://user-images.githubusercontent.com/5095331/40047052-0d1c4828-584c-11e8-9bbf-77b9d02240f9.png)

如 图 ， 在 长 方形 ABCD 中 ，A 庆 4，BC-8， 将 长 方形 ABCD

![1542-300](https://user-images.githubusercontent.com/5095331/40047054-0d52d636-584c-11e8-88e4-b672175af60e.png)

如 图 ， 在 长 方形 ABCD 中 ，A 匠 4，BC=8， 将 长 方形 ABCD

**Comment by christophered** [comment]
@Shreeshrii @stweil can you have a look at http://wiki.wareya.moe/Tesseract
 `tesstrain_utils.sh` https://pastebin.com/TfqJUxSR
`tesstrain.sh` https://pastebin.com/cD5wctUG
to see if we can use anything from his modified code

**Comment by christophered** [comment]
Comparision between the original (Left) and the modified (right)
`tesstrain.sh` https://www.diffchecker.com/erEbEA7y
`tesstrain_utils.sh` https://www.diffchecker.com/XuS9XMjW

**Comment by Shreeshrii** [comment]
@christophered Thank you for the links to modified versions of training scripts at  http://wiki.wareya.moe/Tesseract

I think it all depends on the type of training to be done and the script type eg. RTL, Vert, Indic. Those who want to do training can look at it and use features that will help them.

I am still waiting for update to official version of scripts.

**Comment by christophered** [comment]
@Shreeshrii ` waiting for update to official version of scripts `?
Will Ray include a new feature in the scripts?

**Comment by Shreeshrii** [comment]
I am hoping that whenever langdata files are updated by @jbreiden , the corresponding training scripts willalso be updated.
