### ISSUE TITLE
Error during conversion of wordlists to DAWGs!!

### ISSUE THREAD

**Issue by loralyc** [tesseract-ocr/tesseract#1574]
Tesseract Version: tesseract 4.00.00alpha
Platform: Ubuntu 14.04

I excute the following command:
tesstrain.sh --fonts_dir /usr/share/fonts/ --lang ara --linedata_only --noextract_font_properties --exposures "0" --langdata_dir ../langdata --fontlist "Arial" --output_dir ../tesstutorial/ara

But when it goes to Constructing LSTM training data, it generates the following error:
Loaded unicharset of size 74 from file /tmp/tmp.7uMJLCCWMH/ara/ara.unicharset
Setting unichar properties
Mirror { of } is not in unicharset
Setting script properties
Config file is optional, continuing...
Reducing Trie to SquishedDawg
Error during conversion of wordlists to DAWGs!!
Moving /tmp/tmp.7uMJLCCWMH/ara/ara.Arial.exp0.lstmf to ../tesstutorial/ara

Created starter traineddata for language 'ara'

Run lstmtraining to do the LSTM training for language 'ara'

I already download the lastest langdata and compile the newest tesseract, do you know what is the reason for the error,how can i fix it ? thank you

**Comment by Shreeshrii** [comment]
Does ../langdata/ara have the ara.wordlist ara.numbers and ara.punc files?

**Comment by loralyc** [comment]
yes,it all have
the content of langdata/ara :

**Comment by Shreeshrii** [comment]
>tesseract 4.00.00alpha

newest tesseract is tesseract4.0.0-beta.1

You can install from links given in

https://github.com/tesseract-ocr/tesseract/wiki#tesseract-400-beta-1-packages-with-lstm-engine-and-related-traineddata

**Comment by loralyc** [comment]
i am sorry. i made a mistake. i already install the newest tesseract4.0.0-beta.1
the detail of my log:

=== Starting training for language 'ara'
[2018年 05月 14日 星期一 19:29:58 CST] /usr/local/bin/text2image --fonts_dir=/usr/share/fonts/ --font=Arial --outputbase=/tmp/font_tmp.5QMVVpeBrn/sample_text.txt --text=/tmp/font_tmp.5QMVVpeBrn/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.5QMVVpeBrn
/usr/local/bin/text2image: /home/zjw409/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/liblept.so.5)
Rendered page 0 to file /tmp/font_tmp.5QMVVpeBrn/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using Arial
[2018年 05月 14日 星期一 19:30:02 CST] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.5QMVVpeBrn --fonts_dir=/usr/share/fonts/ --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.1s0ZmeKgq2/ara/ara.Arial.exp0 --max_pages=0 --font=Arial --text=../langdata/ara/ara.training_text
/usr/local/bin/text2image: /home/zjw409/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/liblept.so.5)
Rendered page 0 to file /tmp/tmp.1s0ZmeKgq2/ara/ara.Arial.exp0.tif
Rendered page 1 to file /tmp/tmp.1s0ZmeKgq2/ara/ara.Arial.exp0.tif

=== Phase UP: Generating unicharset and unichar properties files ===
[2018年 05月 14日 星期一 19:30:07 CST] /usr/local/bin/unicharset_extractor --output_unicharset /tmp/tmp.1s0ZmeKgq2/ara/ara.unicharset --norm_mode 2 /tmp/tmp.1s0ZmeKgq2/ara/ara.Arial.exp0.box
/usr/local/bin/unicharset_extractor: /home/zjw409/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/liblept.so.5)
Extracting unicharset from box file /tmp/tmp.1s0ZmeKgq2/ara/ara.Arial.exp0.box
Mirror { of } is not in unicharset
Wrote unicharset file /tmp/tmp.1s0ZmeKgq2/ara/ara.unicharset
[2018年 05月 14日 星期一 19:30:07 CST] /usr/local/bin/set_unicharset_properties -U /tmp/tmp.1s0ZmeKgq2/ara/ara.unicharset -O /tmp/tmp.1s0ZmeKgq2/ara/ara.unicharset -X /tmp/tmp.1s0ZmeKgq2/ara/ara.xheights --script_dir=../langdata
/usr/local/bin/set_unicharset_properties: /home/zjw409/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/liblept.so.5)
Loaded unicharset of size 74 from file /tmp/tmp.1s0ZmeKgq2/ara/ara.unicharset
Setting unichar properties
Mirror { of } is not in unicharset
Setting script properties
Writing unicharset to file /tmp/tmp.1s0ZmeKgq2/ara/ara.unicharset

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=/media/data2/lyc409/tesseract-ocr/tessdata
[2018年 05月 14日 星期一 19:30:07 CST] /usr/local/bin/tesseract /tmp/tmp.1s0ZmeKgq2/ara/ara.Arial.exp0.tif /tmp/tmp.1s0ZmeKgq2/ara/ara.Arial.exp0 lstm.train ../langdata/ara/ara.config
/usr/local/bin/tesseract: /home/zjw409/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/liblept.so.5)
Tesseract Open Source OCR Engine v4.0.0-beta.1-228-gd057 with Leptonica
Page 1
Page 2
Loaded 53/53 pages (1-53) of document /tmp/tmp.1s0ZmeKgq2/ara/ara.Arial.exp0.lstmf

=== Constructing LSTM training data ===
[2018年 05月 14日 星期一 19:30:09 CST] /usr/local/bin/combine_lang_model --input_unicharset /tmp/tmp.1s0ZmeKgq2/ara/ara.unicharset --script_dir ../langdata --words ../langdata/ara/ara.wordlist --numbers ../langdata/ara/ara.numbers --puncs ../langdata/ara/ara.punc --output_dir ../tesstutorial/ara --lang ara --pass_through_recoder --lang_is_rtl
/usr/local/bin/combine_lang_model: /home/zjw409/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/liblept.so.5)
Loaded unicharset of size 74 from file /tmp/tmp.1s0ZmeKgq2/ara/ara.unicharset
Setting unichar properties
Mirror { of } is not in unicharset
Setting script properties
Config file is optional, continuing...
Reducing Trie to SquishedDawg
Error during conversion of wordlists to DAWGs!!
Moving /tmp/tmp.1s0ZmeKgq2/ara/ara.Arial.exp0.lstmf to ../tesstutorial/ara

Created starter traineddata for language 'ara'

Run lstmtraining to do the LSTM training for language 'ara'
@Shreeshrii

**Comment by Shreeshrii** [comment]
>/usr/local/bin/text2image: /home/zjw409/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/liblept.so.5)

This could be unrelated. However, let me know what is output of 

`tesseract -v`

> --langdata_dir ../langdata

What is the output of 

`ls -l ../langdata/ara`

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesseract/issues/1147#issuecomment-332775119

this problem could be related to incorrect line endings in your langdata files.

**Comment by loralyc** [comment]
Thank you very much! @Shreeshrii 
i redownload the langdata in the linux then fix the problem, it seems the problem about the incorrect line endings.

**Comment by madhuri-dadhich** [comment]
getting error when trying to train tesseract on new font
=== Constructing LSTM training data ===
[Tue, Sep 10, 2019 1:42:29 PM] /c/Program Files (x86)/Tesseract-OCR/combine_lang_model --input_unicharset /tmp/eng-2019-09-10.lCl/eng.unicharset --script_dir langdata_lstm --words langdata_lstm/eng/eng.wordlist --numbers langdata_lstm/eng/eng.numbers --puncs langdata_lstm/eng/eng.punc --output_dir train --lang eng
Loaded unicharset of size 99 from file C:/Users/MADHUR~1.DAD/AppData/Local/Temp/eng-2019-09-10.lCl/eng.unicharset
Setting unichar properties
Setting script properties
Warning: properties incomplete for index 68 = ~
Config file is optional, continuing...
Failed to read data from: langdata_lstm/eng/eng.config
Null char=2
Invalid format in radical table at line 0: 19886 3 23 6 3
Creation of encoded unicharset failed!!
Error writing recoder!!
Reducing Trie to SquishedDawg
Error during conversion of wordlists to DAWGs!!
basename: extra operand ‘(x86)/Tesseract-OCR/combine_lang_model’
Try 'basename --help' for more information.
ERROR: Program failed. Abort.

**Comment by Shreeshrii** [comment]
>Invalid format in radical table at line 0: 19886 3 23 6 3

Check that you have latest version of the files - after this commit https://github.com/tesseract-ocr/langdata/commit/3e32be3dc07be0994f3687664a44cb3246b5aa11

What is the output of

tesseract -v

**Comment by madhuri-dadhich** [comment]
$ tesseract -v
tesseract v4.0.0-beta.1.20180608
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.2.0

**Comment by Shreeshrii** [comment]
Please upgrade your version of tesseract and related files.

**Comment by madhuri-dadhich** [comment]
still getting the same error

**Comment by DavraYoung** [comment]
Same error:
> tesseract -v
                                                                                                                                      tesseract 4.1.1                                                                                                                                                                                                                               leptonica-1.79.0      
                                                                                                                                                                                                                        libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1                                                                                                            Found AVX2                                                                                                                                                                                                                                   Found AVX                                                                                                                                                                                                                                    Found FMA                                                                                                                                                                                                                                    Found SSE                                                                                                                                                                                                                                    Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4
