### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION at TessBaseAPI::Recognize and application crashed 

### ISSUE THREAD

**Issue by Inzaghi2012** [tesseract-ocr/tesseract#1575]
### Environment

* **Tesseract Version**: 3.4.0.0
* **Commit Number**: Not Sure
* **Platform**: Windows 7 32 bit

### Current Behavior:
Exception happened at TessBaseAPI::Recognize function and make application (C#) crashed.

### Expected Behavior:
Exception happened in tesseract  won't make application crashed.

### Suggested Fix:
Handle the exception inside tesseract dll

### Detail Logs : 

ExceptionAddress: 2E7D91E4
ExceptionCode: C0000005(EXCEPTION_ACCESS_VIOLATION)
ExceptionFlags: 00000000
NumberParameters: 2
Parameter[0]: 00000000
Parameter[1]: 00000000
attempt to read from address 00000000
Registers:
EAX:00000003
EBX:2D243050
ECX:00000000
EDX:00000006
ESI:2CE804F8
EDI:FDDEFFD4
EBP:1581DE54
Flags:00010246
CS:EIP: 001B:2E7D91E4
SS:ESP: 0023:1581DA50
DS:0023  ES:0023  FS:003B  GS:0000
Address   Module     Function            SourceFile(Line)
2E7D91E4: libtesseract304.dll void ERRCODE::error(char const *,enum TessErrorLogCode,char const *,...)const  + 212 bytes 
2E85EBB1: libtesseract304.dll STRING::STRING(void) + 139265 bytes 
2E87A50C: libtesseract304.dll virtual tesseract::TessResultRenderer::~TessResultRenderer(void) + 1484 bytes 
2E87B186: libtesseract304.dll virtual tesseract::TessResultRenderer::~TessResultRenderer(void) + 4678 bytes 
2E7BBA20: libtesseract304.dll TessVersion + 127744 bytes 
2E7BC724: libtesseract304.dll TessVersion + 131076 bytes 
2E7BC3E8: libtesseract304.dll TessVersion + 130248 bytes 
2E7DCF5D: libtesseract304.dll void ERRCODE::error(char const *,enum TessErrorLogCode,char const *,...)const  + 15949 bytes 
2E7DD18B: libtesseract304.dll void ERRCODE::error(char const *,enum TessErrorLogCode,char const *,...)const  + 16507 bytes 
2E7DDC25: libtesseract304.dll void ERRCODE::error(char const *,enum TessErrorLogCode,char const *,...)const  + 19221 bytes 
2E7BF38C: libtesseract304.dll TessVersion + 142444 bytes 
2E78D0E7: libtesseract304.dll int tesseract::TessBaseAPI::Recognize(class ETEXT_DESC *) + 695 bytes 
2E78C32D: libtesseract304.dll bool tesseract::TessBaseAPI::ProcessPage(struct Pix *,int,char const *,char const *,int,class tesseract::TessResultRenderer *) +(0)
2E78C794: libtesseract304.dll bool tesseract::TessBaseAPI::ProcessPages(char const *,char const *,int,class tesseract::TessResultRenderer *) + 900 bytes 
1D6E1ED3: MyTesseractOcr.dll <no symbol>
1D6E4235: MyTesseractOcr.dll <no symbol>
1D6E8ACF: MyTesseractOcr.dll SetSourceFile + 15 bytes 
1D496E7C: <no module><no symbol>
2247398C: <no module><no symbol>
1587CB8B: <no module><no symbol>
19A85FB4: <no module><no symbol>
19A84BED: <no module><no symbol>
1531AD7E: <no module><no symbol>
1A4EE0DE: <no module><no symbol>
1587CB8B: <no module><no symbol>
19A85FB4: <no module><no symbol>
19A84BED: <no module><no symbol>
1531AD7E: <no module><no symbol>
6FB42AE9: clr.dll <no symbol>
6EDAC9FF: mscorlib.ni.dll <no symbol>
6EDA2367: mscorlib.ni.dll <no symbol>
6EDA22A6: mscorlib.ni.dll <no symbol>
6EDA2261: mscorlib.ni.dll <no symbol>
6EDACA7C: mscorlib.ni.dll <no symbol>
6FB42652: clr.dll <no symbol>
6FB5264F: clr.dll InstallCustomModule + 579 bytes 
6FB52E95: clr.dll InstallCustomModule + 2697 bytes 
6FBE07D8: clr.dll DllGetActivationFactoryImpl + 16369 bytes 
6FBB7D4D: clr.dll LogHelp_TerminateOnAssert + 37389 bytes 
6FBB7DBB: clr.dll LogHelp_TerminateOnAssert + 37499 bytes 
6FBB7E88: clr.dll LogHelp_TerminateOnAssert + 37704 bytes 
6FB4C3BF: clr.dll DllUnregisterServerInternal + 8907 bytes 
6FBE0694: clr.dll DllGetActivationFactoryImpl + 16045 bytes 
6FC5A0CF: clr.dll DllGetClassObjectInternal + 348246 bytes 
77C7EF8C: KERNEL32.dll BaseThreadInitThunk + 18 bytes 
77B2367A: ntdll.dll RtlInitializeExceptionChain + 239 bytes 
77B2364D: ntdll.dll RtlInitializeExceptionChain + 194 bytes

**Comment by Inzaghi2012** [comment]
OK, thanks very much. I will try to reproduce in C++. BTW, if there similar issues reported before ?

**Comment by zdenop** [comment]
If it was reported already please add you note/test case to existing issue.
