### ISSUE TITLE
bug in training command sequence

### ISSUE THREAD

**Issue by kirannaik25** [tesseract-ocr/tesseract#1578]
i am using Tesseract Version3.05.01. My platform is windows 64 bit system.
I used abc.size1.exp0.png as input image for training.
![abc size1 exp0](https://user-images.githubusercontent.com/15606755/40099102-378cc3ca-58fc-11e8-836e-8262e72addeb.png)
My training sequence is 
1.	tesseract abc.size8.exp0.bmp abc.size8.exp0 -l eng batch.nochop makebox
2.	tesseract abc.size8.exp0.bmp abc.size8.exp0 nobatch box.train
3.	unicharset_extractor abc.size8.exp0.box
4.	set_unicharset_properties -U unicharset -O new_unicharset --script_dir=/home/langdata-master/Latin.unicharset
5.	shapeclustering -F /home/font_properties -U new_unicharset
6.	mftraining -F /home/font_properties -U new_unicharset abc.size8.exp0.tr
7.	cntraining abc.size8.exp0.tr
8.	move inttemp abc.inttemp
9.	move normproto abc.normproto
10.	move pffmtable abc.pffmtable
11.	move shapetable abc.shapetable
12.	combine_tessdata abc

Training font generated is not giving any result on similar images.
can anyone help me to train a new FONT.

**Comment by nguyenq** [comment]
You probably need a much larger sample -- several thousands of characters.

**Comment by zdenop** [comment]
... And please use tesseract user forum for asking support.
