### ISSUE TITLE
Tesseract doesn't recognize multiple languages

### ISSUE THREAD

**Issue by tomdoe420** [tesseract-ocr/tesseract#1579]
If I were to run `tesseract page356.png page356 -l eng+osd+ell pdf` 

It would only recognize the English characters, but produce no errors about other language recognition

If I run `tesseract page356.png page356greek -l ell`

It recognizes the Greek fine, but now there is no English

If I run tesseract page356.png greekandenglish356 -l ell+eng+osd pdf I get this pdf
[greekandenglish356.pdf](https://github.com/tesseract-ocr/tesseract/files/2010860/greekandenglish356.pdf)

only recognizes English

I ran `apt-get install tesseract-ocr-all`

and I'm experiencing this issue on multiple linux distros

Here is a sample image
![1200_page_356](https://user-images.githubusercontent.com/32225549/40138427-a13a3c6c-591a-11e8-8c6a-78b7fde035dd.png)

**Comment by raffopazzo** [comment]
AFAIK multiple language support is only for version 4+, not necessarily available in the default repo of the distro

**Comment by jbreiden** [comment]
Multiple languages are supported on v3.x

**Comment by jbreiden** [comment]
Share a sample image please.

**Comment by jbreiden** [comment]
It gives very poor results, but Tesseract 4 is producing a mix of Greek & English. This is also true in PDF output. Problem is not reproducing for me.

```
$ tesseract -l ell+eng example.png - -

[...]
6- 5- 4- 3- 2- α- β- N- Entry Name
[...]
```

**Comment by jbreiden** [comment]
And I even see some Greek in your attached PDF. There is a β in there.

**Comment by Shreeshrii** [comment]
Changing order of languages usually changes the results.

OP had used eng+ell

**Comment by Shreeshrii** [comment]
Also, try with the script trained data

https://github.com/tesseract-ocr/tessdata_best/blob/master/script/Greek.traineddata

It should have both Greek and English.

**Comment by zdenop** [comment]
Could be issue be closed? 
There is no reaction from original reporter for several months....

**Comment by nemobis** [comment]
zdenop, 30/09/2018 17:19:
> There is no reaction from original reporter for several months....

What information is needed? I have the same experience with tesseract 
3.05.02, but I don't understand from the responses above whether it's 
considered expected result until version 4.

**Comment by zdenop** [comment]
Reported claims that there are only English characters. jbreiden but see there greek alphabets...
Shreeshrii provided several suggestion for testing... No reply...

If reporter does not care why we should? We are not paid for this. If reporter does not value our time and cooperate than I will eliminate such report (if it does not have some value for this project)

**Comment by Shreeshrii** [comment]
Same problem reported in the forum today, but with a custom traineddata for Thai and English.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/YLvnrS-01kI/x0PUNGsGBAAJ

**Comment by Shreeshrii** [comment]
![en_th](https://user-images.githubusercontent.com/5095331/46363888-41454500-c642-11e8-80fc-5ad4bf41b9f2.jpg)

As mentioned by the OP in the forum `if the input image have both language(eng+thai) in the same line it will read only in 1 language but when having single language in that line it will read in correct language`

script/Thai.traineddata seems to give correct result.

```
ubuntu@tesseract-ocr:~/TEST$ bash ./en_th.sh

 *****  ./en_th.jpg LANG tha+eng TESSDATA tessdata OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
1โล!10 สวัสดีจ้า
This is a test.
นี่คือการทดสอบ

 *****  ./en_th.jpg LANG tha+eng TESSDATA tessdata_best OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
1โล!1๐0 สวัสดีจ้า
This is a test.
นี่คือการทดสอบ

 *****  ./en_th.jpg LANG tha+eng TESSDATA tessdata_fast OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
1โล!10 สวัสดีจ้า
This is a test.
นี่คือการทดสอบ

 *****  ./en_th.jpg LANG eng+tha TESSDATA tessdata OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
1โล!10 สวัสดีจ้า
This is a test.
นี่คือการทดสอบ

 *****  ./en_th.jpg LANG eng+tha TESSDATA tessdata_best OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
Hello aaa
This is a test.
นี่คือการทดสอบ

 *****  ./en_th.jpg LANG eng+tha TESSDATA tessdata_fast OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
Hello ayaa
This is a test.
นี่คือการทดสอบ

 *****  ./en_th.jpg SCRIPT Thai TESSDATA tessdata_best OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
Hello สวัสดีจ้า
This is a test.
นี่คือการทดสอบ

 *****  ./en_th.jpg SCRIPT Thai TESSDATA tessdata_fast OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
Hello สวัสดิจ้า
This is a test.
นี่คือการทดสอบ
DONE

```

**Comment by Shreeshrii** [comment]
Last(?) change from Ray regarding multi-language mode seems to be 

https://github.com/tesseract-ocr/tesseract/commit/b453f74e0194f2cf08e9251b1846a0132657c4f8

**Comment by nawabhussain** [comment]
Any updates on this issue. I am using Tesseract v4 to detect text "Bœuf Stroganoff" using German and French traindata. Text detection doesn't work when I use traindata for multiple languages together.

**Comment by amitdo** [comment]
You can try `Latin.traineddata` from best/fast.

**Comment by nawabhussain** [comment]
@amitdo Tried that. It doesn't work as well. The command I used :
`tesseract <input image> <output file> -l lat`

**Comment by Shreeshrii** [comment]
-l lat is Latin language.

Use script/Latin which is Latin script and has been trained using all
languages using that script.

**Comment by Shreeshrii** [comment]
Please provide a test image. We need to test whether this is a regression .

**Comment by nawabhussain** [comment]
![test](https://user-images.githubusercontent.com/18714720/46577045-dc8c4080-c9db-11e8-8bb7-8fa3a367bbb8.png) _This image shows the character set I am targetting_
![test1](https://user-images.githubusercontent.com/18714720/46577046-dc8c4080-c9db-11e8-9ba9-43a02dcf291c.png) _This image shows the text I was experimenting with as mentioned in the previous comments_ 

Any input on these would be highly appreciated.

**Comment by amitdo** [comment]
Please post an representative image, not ABC demo.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/langdata/issues/83#issuecomment-375027879

theraysmith commented on Mar 21
>I did have an idea for a better multi-language implementation that would cleanly use models from multiple languages at once, but that depends on getting rid of the old code, and moving the multi-language functionality into the beam search. Until the old code is gone, that would be very messy. …

**Comment by Shreeshrii** [comment]
I can replicate this.

it seems  to me that `œ` is only trained for French. However, it is not being recognized when French is listed second.


 *****  ./euro.png OEM 1 PSM 6 LANG deu+fra TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+deu TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
**Bœuf Stroganoff**

 *****  ./euro.png OEM 1 PSM 6 LANG eng+fra TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+eng TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
**Bœuf Stroganoff**

 *****  ./euro.png OEM 1 PSM 6 LANG script/Latin TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bouf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
**Bœuf Stroganoff**

**Comment by Shreeshrii** [comment]
Results with all three repos, tessdata,  tessdata_fast and tessdata_best

 *****  ./euro.png OEM 1 PSM 6 LANG deu+fra TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG deu+fra TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG deu+fra TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+deu TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+deu TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+deu TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG eng+fra TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG eng+fra TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG eng+fra TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+eng TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+eng TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+eng TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG script/Latin TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bouf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG script/Latin TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bouf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG script/Latin TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

**Comment by amitdo** [comment]
You already summarized the behavior when lstm is activated.

>As mentioned by the OP in the forum if the input image have both language(eng+thai) in the same line it will read only in 1 language but when having single language in that line it will read in correct language

'in 1 language' -> 'in the first given language'

**Comment by sirius0503** [comment]
> Also, try with the script trained data
> 
> https://github.com/tesseract-ocr/tessdata_best/blob/master/script/Greek.traineddata
> 
> It should have both Greek and English.

My OCR even became faster by using `Devanagari.traineddata`, is there any reason for this to happen, also `hin+eng` was converting a lot of the hindi text to english

**Comment by Shreeshrii** [comment]
@sirius0503 Devanagari was trained with hin+san+mar+nep+eng so it is better at recognition, plus only one traineddata file is used rather than two diff ones.

**Comment by sirius0503** [comment]
@Shreeshrii : Surprisingly, it is faster than `hin.traineddata`

**Comment by amitdo** [comment]
That's due to a difference in the net-spec between the two, which makes Devanagari's network smaller than hin's network.

In addition, like Shree said, in the case of hin you add another network, eng. Devanagari has just one network for both languages.

**Comment by sirius0503** [comment]
> That's due to a difference in the net-spec between the two, which makes Devanagari's network smaller than hin's network.

@amitdo : When I am using only `-l Devanagari` instead of  `-l hin` , I get better speed ( not even `hin + eng`), Can you explain more about the **net-spec difference**

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/VGSLSpecs

https://github.com/tesseract-ocr/tesseract/issues/1404#issuecomment-374680492

**Lang** | **Repo** | **Height** | **Lfys** | **Lfx,Lrx** | **Lrx**
:----------: | :----------: | :------------: | :---------: | :------------: | :----------
Devanagari | best  | 48  | 64 | 64 | 512
hin               | best  | 48  | 64 | 96 | 512
Devanagari | fast   | 36  | 48 | 96 | 192
hin               | fast   | 48  | 64 | 96 | 384

**Comment by Haleybelinda** [comment]
I am struggling to get it to talk to laser. It states cannot find path? Which part am I missing, please?

**Comment by amitdo** [comment]
Shree, can you retest the eng+tha / tha+reng, best/fast, with code from the mater branch?
.

**Comment by Shreeshrii** [comment]
Using the same image used for test in https://github.com/tesseract-ocr/tesseract/issues/1579#issuecomment-426351989 and master code built with disable-legacy:

```
ubuntu@tesseract-ocr:~/TEST$ bash en_th.sh
tesseract 5.0.0-alpha-473-g6d171
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.4.4 : libopenjp2 2.3.0

 *****  ./en_th.jpg LANG tha+eng TESSDATA tessdata OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
Hello สวัสดีจ้า
This is ล test.
นี่คือการทดสอบ
1.66user 0.02system 0:01.70elapsed 99%CPU (0avgtext+0avgdata 81408maxresident)k
0inputs+0outputs (0major+1568minor)pagefaults 0swaps

 *****  ./en_th.jpg LANG tha+eng TESSDATA tessdata_best OEM 1 PSM 3 ****
Warning: Parameter not found: segsearch_max_futile_classifications
Warning: Parameter not found: language_model_ngram_on
Warning: Parameter not found: language_model_ngram_space_delimited_language
Warning: Parameter not found: chop_enable
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
Hello สวัสดีจ้า
This is ล test.
นี่คือการทดสอบ
2.00user 0.03system 0:02.06elapsed 98%CPU (0avgtext+0avgdata 64768maxresident)k
0inputs+0outputs (0major+1936minor)pagefaults 0swaps

 *****  ./en_th.jpg LANG tha+eng TESSDATA tessdata_fast OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
Hello สวัสดีจ้า
This is ล test.
นี่คือการทดสอบ
1.23user 0.00system 0:01.24elapsed 99%CPU (0avgtext+0avgdata 25408maxresident)k
0inputs+0outputs (0major+666minor)pagefaults 0swaps

 *****  ./en_th.jpg LANG eng+tha TESSDATA tessdata OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
Hello สวัสดีจ้า
This is ล test.
นี่คือการทดสอบ
1.64user 0.02system 0:01.67elapsed 99%CPU (0avgtext+0avgdata 78144maxresident)k
0inputs+0outputs (0major+1527minor)pagefaults 0swaps

 *****  ./en_th.jpg LANG eng+tha TESSDATA tessdata_best OEM 1 PSM 3 ****
Warning: Parameter not found: segsearch_max_futile_classifications
Warning: Parameter not found: language_model_ngram_on
Warning: Parameter not found: language_model_ngram_space_delimited_language
Warning: Parameter not found: chop_enable
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
Hello สวัสดีจ้า
This is ล test.
นี่คือการทดสอบ
1.95user 0.02system 0:01.97elapsed 99%CPU (0avgtext+0avgdata 59136maxresident)k
0inputs+0outputs (0major+1667minor)pagefaults 0swaps

 *****  ./en_th.jpg LANG eng+tha TESSDATA tessdata_fast OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 376
Hello สวัสดีจ้า
This is ล test.
นี่คือการทดสอบ
1.30user 0.02system 0:01.33elapsed 99%CPU (0avgtext+0avgdata 25472maxresident)k
0inputs+0outputs (0major+625minor)pagefaults 0swaps
DONE
ubuntu@tesseract-ocr:~/TEST$
```

`Hello` is now being recognized correctly.

`a` in This is a test is now being recognized as a Thai character.

**Comment by amitdo** [comment]
Interesting, thanks.

**Comment by Shreeshrii** [comment]
Results for test case in https://github.com/tesseract-ocr/tesseract/issues/1579#issuecomment-428432287 are also changed.

```

ubuntu@tesseract-ocr:~/TEST$ bash euro.sh

 *****  ./euro.png OEM 1 PSM 6 LANG deu+fra TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG deu+fra TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG deu+fra TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+deu TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+deu TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+deu TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG eng+fra TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG eng+fra TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG eng+fra TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+eng TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+eng TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra+eng TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Boeuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG script/Latin TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bouf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG script/Latin TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bouf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG script/Latin TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra TESSDATA tessdata ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra TESSDATA tessdata_best ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff

 *****  ./euro.png OEM 1 PSM 6 LANG fra TESSDATA tessdata_fast ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Bœuf Stroganoff
DONE
```

**Comment by amitdo** [comment]
https://raw.githubusercontent.com/tesseract-ocr/langdata_lstm/master/fra/fra.wordlist
has these words:
Boeuf, boeuf, BOEUF, bœuf, but not Bœuf.
https://raw.githubusercontent.com/tesseract-ocr/langdata_lstm/master/eng/eng.wordlist
has boeuf, but not Boeuf.
