### ISSUE TITLE
Unable to detect text from button from image

### ISSUE THREAD

**Issue by sneha07** [tesseract-ocr/tesseract#1580]
------------------------

### Environment

* **Tesseract Version**: 3.05
* **Platform**:  Windows, version and 64-bit

### Current Behavior
I need hocr file for text present into image. I am not able to get text from button.  I have attached the image , please check. 
![image](https://user-images.githubusercontent.com/2361705/40173768-863210d0-59f0-11e8-9062-9da7c80637d0.png)

As you can see the Connect button. Unable to detect it. Let me know what should be fix . I am using python langauage to write a code.
### Expected Behavior:
Connect Button text should be detected so that i can get its [coordinates.]

**Comment by nguyenq** [comment]
This question should be posted in the Forum.

The binarized (monochrome) image produced this:

Connection Profile: <new> > | Save | | Delete
Connection Type: via Energy Portal ~

IP Address


Connect
