### ISSUE TITLE
LSTM makefile prepends one too many slashes to 'tessdata' during build

### ISSUE THREAD

**Issue by RNCTX** [tesseract-ocr/tesseract#1582]
### Environment

* **Tesseract Version**: tesseract 4.0.0-beta.1-232-g45a6
* **Commit Number**: 
* **Platform**: FreeBSD 11.1-STABLE amd64

### Current Behavior:
`./configure --prefix=/usr/local`

lstm makefile prepends an extra slash before tessdata (ex: /usr/local/share//tessdata)

### Expected Behavior:

/usr/local/share/tessdata for tessdata default folder after building/installing

### Suggested Fix:

Worked around it by modifying the src/lstm/Makefile on line 92..

`am__append_1 = -DTESSDATA_PREFIX=${datarootdir}/`

changed to...

`am__append_1 = -DTESSDATA_PREFIX=${datarootdir}`

**Comment by stweil** [comment]
Thanks for reporting. The additional slash does not cause harm, so everything will work as expected. But of course if does not look nice. Your proposed solution looks good. Can you send a pull request which implements that, please?

**Comment by amitdo** [comment]
>Your proposed solution looks good

Hmmm... He proposed to change the generated Makefile. The Makefile.am is the file that should be modified.

https://github.com/tesseract-ocr/tesseract/blob/45a65463247cfc6856a186341c6918da0b1f44be/src/lstm/Makefile.am#L15

Another one:
https://github.com/tesseract-ocr/tesseract/blob/45a65463247cfc6856a186341c6918da0b1f44be/src/ccutil/Makefile.am#L6

**Comment by stweil** [comment]
Yes, that's correct. While looking closer at it, I noticed that the line in `src/lstm/Makefile.am` is not needed and should be removed. Changing `src/ccutil/Makefile.am` is sufficient to fix this issue.

**Comment by RNCTX** [comment]
Yes, I spoke too soon, I noticed after working some more with the stuff I'm using today that in some contexts the extra slash was still there. 

Do you still want me to double check them all and submit a pull?

**Comment by stweil** [comment]
That would be great – otherwise someone else (maybe I myself) must do. :-)
