### ISSUE TITLE
lstmtraining --model_output doesn't generate new folders

### ISSUE THREAD

**Issue by MrOCR** [tesseract-ocr/tesseract#1586]
When running lstmtraining:
```
lstmtraining --model_output ./output/
```
If the destination folder does not exist it wont create it, the program will keep training but the models are not saved, until you create the folder manually.

Also can't extract a traineddata model if the destination folder does not exist when running combine_tessdata:
```
combine_tessdata -e eng.traineddata ./output/eng.lstm
```

Basically what I am saying is that if the destination folder does not exist, create it automatically.

**Comment by Shreeshrii** [comment]
See LSTM: Training: failed to write checkpoint #695 for more details

**Comment by christophered** [comment]
@Shreeshrii I am root, and I don't have any problems in training.
This issue is rather a suggestion, so that `lstmtraining` and `combine_tessdata` automatically creates the destination folders if they don't exist.

**Comment by Shreeshrii** [comment]
@christophered Good suggestion.

**Comment by Shreeshrii** [comment]
@zdenop please label as Feature Request.

**Comment by stweil** [comment]
I implemented an alternate solution which makes `lstmtraining` fail if the model output cannot be written. See pull request #1951.

It does not create directories, because I think this is the user's responsibility and easy to be done.

**Comment by stweil** [comment]
Pull request #1951 now also handles `combine_tessdata`.

**Comment by nijanthan0** [comment]
zdenop
