### ISSUE TITLE
Crash with libtesseract with PSM_AUTO_OSD

### ISSUE THREAD

**Issue by nek0** [tesseract-ocr/tesseract#1596]
### Environment

* **Tesseract Version**: 4.00~git2288-10f4998a-2
* **Platform**: Linux cloud-STK1AW32SC 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
I am using above mentioned version of libtesseract for reading. When initializing tesseract with following code, the program crashes at startup.

```c++
    TessBaseAPI _tess_ptr = new TessBaseAPI();
    if (_tess_ptr->Init(NULL, "osd+deu+eng")) {
        fprintf(stderr, "Could not initialize tesseract\n");
        exit(1);
    }
    _tess_ptr->SetPageSegMode(PSM_AUTO_OSD);
```
The only error message I get is:

```
Error: Illegal Parameter specification!
"Fatal error encountered!" == NULL:Error:Assert failed:in file globaloc.cpp, line 75
```
### Expected Behavior:

I would expect the Program to actually start up or give a more explanatory error message.
I don't rule out an error on my side.

**Comment by amitdo** [comment]
The error handling in libtesseract is indeed problematic.

**Comment by amitdo** [comment]
Which traineddata variant did you use (tessdata/tessdata_fast/tessdata_best)?

**Comment by nek0** [comment]
I don't know which traineddata I did use. When trying to run the tesseract CLI utility with the command `tesseract bc.png stdout -l eng+deu --psm 0` I get a segfault.
I can not provide a sample image, but I don't think it has to do something with the image. I tried different images, but they all fail.

**Comment by amitdo** [comment]
>When trying to run the tesseract CLI utility with the command tesseract bc.png stdout -l eng+deu --psm 0

Try this:

>tesseract bc.png stdout -l osd --psm 0

**Comment by Shreeshrii** [comment]
Also see issue https://github.com/tesseract-ocr/tesseract/issues/1463

**Comment by nek0** [comment]
> Try this:
>>    tesseract bc.png stdout -l osd --psm 0

The CLI utility does not crash, but does not give me only this output:

```
Page number: 0
Orientation in degrees: 180
Orientation confidence: 0.13
Script: Japanese
Script confidence: 0.20
```

I have two problems with this:
1. This is interesting, but incorrect metadata. What I am trying to read is German.
2. The utility does not output any text it has read.

**Comment by amitdo** [comment]
Without a sample image it's hard to tell what the source of the issue.

>This is interesting, but incorrect metadata. What I am trying to read is German.

The osd module needs a certain minimum amount of characters for each block of text.


>The utility does not output any text it has read.

You can try
`tesseract bc.png stdout -l deu --psm 1`
Or
`tesseract bc.png stdout -l deu+eng --psm 1`
Or
`tesseract bc.png stdout -l script/Latin --psm 1`

https://github.com/tesseract-ocr/tessdata_fast/tree/master/script

but if --psm 0 recognized German text as Japanese these command won't recognize your text properly.

**Comment by nek0** [comment]
> You can try
> `tesseract bc.png stdout -l deu --psm 1`
reads the image fine.

> Or
> `tesseract bc.png stdout -l deu+eng --psm 1`
reads the image fine.

> Or
> `tesseract bc.png stdout -l script/Latin --psm 1`
also works fine.

all three commands resulted in the image being (more or less) correctly read. It's the OSD part that fails. setting `--psm 0` results in a crash. Using any Page segmentation that ends on `OSD` in my code results in a crash.

**Comment by Shreeshrii** [comment]
The reason for crash is this:

osd.traineddata only has legacy tesseract model in it, so any command that causes osd to be called along with a language which only supports --oem 1 (LSTM ) results in crash. 

If there is a fix for this for 4.0.0, it will only be to give an error message rather than a crash. 

I don't think Ray is going to update osd.traineddata for LSTM now.

**Comment by Shreeshrii** [comment]
>I have two problems with this:
This is interesting, but incorrect metadata. What I am trying to read is German.
The utility does not output any text it has read.

For German, just using `-l deu` should suffice. Why are you using osd?

**Comment by nek0** [comment]
I am using OSD, because I can't guarantee that the text is oriented the right way.

**Comment by amitdo** [comment]
Specifying `-l lang1+osd` is wrong usage.

`-l deu --psm 1`
will use the deu **and osd** traineddata

However, with --psm 0 the right usage is:
`-l osd --psm 0`

**Comment by stweil** [comment]
> However, with --psm 0 the right usage is: `-l osd --psm 0`

I just had a crash because I did not use `-l osd` with `--psm 0`. If `--psm 0` requires `-l osd`, we should either abort with an error message if `-l osd` was missing, or enforce it automatically. Which of both alternatives would be preferred?

**Comment by stweil** [comment]
Pull request #1818 implements that.

@nek0, I tried your test code. After fixing a compiler error in `TessBaseAPI _tess_ptr = new TessBaseAPI();`, that code compiled and could be run without a crash.
