### ISSUE TITLE
“low accuracy” on mixed language (fas+eng)

### ISSUE THREAD

**Issue by reza6966** [tesseract-ocr/tesseract#1599]
### Environment

* **Tesseract Version**: 4.0.0-beta.1 Release
* **Platform**: Windows, 64-bit

### Current Behavior:
Hi
when we use tesseract only for english or persian, accuracy is very high.
but when i have a image with mixed persian and english, the accuracy is very low for second language (-l fas+eng)

i attached the sample and the results.
[
![test fas eng](https://user-images.githubusercontent.com/4763752/40464110-67fdf384-5f2e-11e8-87c5-e5ad945ad2af.png)
](url)

نویسه‌خوان نوری!" که با سرواژه‌ی ***/:)0)** شناخته می‌شود. عبارت است از تشخیص (**۳6600۲۱]0070**) خودکار متون موجود در
تصاویر اسناد و تبدیل آن‌ها به متون قابل جستجو و ویرایش توسط رایانه. تصویر سند غالبا توسط روبشگر یا دوربین دیجیتال تولید


### Suggested Fix:
i think we should train a model with mixed persian and english text ?!

**Comment by Shreeshrii** [comment]
Related Issue: “no best words!!” on mixed language (fra+ara) items #235

**Comment by amitdo** [comment]
Ray said he can improve it, but the legacy engine needs to be dropped first.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/langdata/issues/83#issuecomment-375027879

**Comment by Pouya-Khalilzad** [comment]
I have the same problem with tesseract 4.1.1 version. Is there found any solution?
