### ISSUE TITLE
Inconsistent results with VERY similar images

### ISSUE THREAD

**Issue by vojtekm** [tesseract-ocr/tesseract#160]
Hi,
I use tesseract (Tesseract 3.02 on Windows 7) to process sets of scanned invoices issued by the same company (very similar to each other).
I've noticed that **_some of them are recognized properly and some not_**.
The **original paper documents are of very good quality** and so are the TIFF files (at least to me) - so I thought there should be no problem for tesseract to recognize them properly, but...

I have played a bit with the scanning parameters and produced different images of the same paper document that originally caused problems. 

Now I have two TIF files of the same paper invoice:
1. one that gives incorrect results (ex_bad.tif)
2. one that gives correct results (ex_good.tif)

and the **ex_diff.tif** showing which part did not get recognized properly.
I attach also the hOCR files produced for both TIFF files and tesseract configuration.
All the above mentioned files are however packed in one docx file :smiley: 

[Incosistency.docx](https://github.com/tesseract-ocr/tesseract/files/48291/Incosistency.docx)

Don't know if it is the same issue but looking at the line 26 in ex_bad.html one can find empty strings (I know it's been reported already but do not know if it was fixed):

``` html
     <span class='ocr_line' id='line_5' title="bbox 176 379 2119 464"><span class='ocrx_word' id='word_13' title="bbox 176 403 269 439"></span> <span class='ocrx_word' id='word_14' title="bbox 286 404 546 448"></span> <span class='ocrx_word' id='word_15' title="bbox 562 404 648 439"></span> <span class='ocrx_word' id='word_16' title="bbox 1357 379 1759 464"></span> <span class='ocrx_word' id='word_17' title="bbox 1773 379 2119 458"></span> 
     </span>
```

**I have also noticed that removing the picture from the top left corner of the first page of the invoice helps recognizing text properly.**

Is this a bug or simply 'a user education error'?
:smiley:

Thanks in advance for any kind of help and/or guidance here
Wojtek

**Comment by amitdo** [comment]
> All the above mentioned files are however packed in one docx file :smiley: 

Please attach a zip file instead.

**Comment by vojtekm** [comment]
I have tried at the time of postinig the original issue but I was not allowed to upload zip file....
Hope this time will work...
[Issues.zip](https://github.com/tesseract-ocr/tesseract/files/76707/Issues.zip)

**Comment by amitdo** [comment]
Tesseract layout analysis gets really confused with the 'bad' image.
The main difference between the two images is the black frame around the page margins. If you'll remove the black borders Tesseract will produce a better output.

**Comment by swayson** [comment]
I havent used tesseract in two years or so, but I recall as part of preprocessing, we had to first remove all images and do some denoising. That greatly improved things.

**Comment by zdenop** [comment]
Closing as current code produces much better [result](https://github.com/tesseract-ocr/tesseract/files/2475740/ex_bad.tiff.hocr.zip) for ex_bad.tif (with tessdata_best):
`tesseract i160\ex_bad.tif i160\ex_bad.tiff -l pol hocr`
