### ISSUE TITLE
Run Tesseract using more than 4 threads ?

### ISSUE THREAD

**Issue by Chien-Hao** [tesseract-ocr/tesseract#1600]
Hello, 

I am using tesseract-4.0.0-beta.1, and I have a ARM server with 96 CPU cores/threads.
When I ran tesseract, it seems that by default it only uses 4 cores of the machine.
Is it possible to run tesseract using more than 4 threads ? 

I have tried to modify the parameter "kNumThreads" in the source code : lstm/fullyconnected.cpp, also num_threads() in ccmain/par_control.cpp and re-compiler tesseract. But the execution time is still almost the same. I have searched many web pages for the answer but none of them is satisfied.

Any suggestion and advice is welcome and appreciated. 
Thanks a lot.

Platform:
Linux localhost.localdomain 4.14.0-49.el7a.aarch64

**Comment by KyleBruene** [comment]
Short answer: No

As per FAQ

> Can I increase speed of OCR?
> If you are running Tesseract 4, you can use the "fast" integer models.
> 
> Tesseract 4 also **uses up to four CPU threads** while processing a page, so it will be faster than Tesseract 3 for a single page.
> 
> If your computer has only two CPU cores, then running four threads will slow down things significantly and it would be better to use a single thread or maybe a maximum of two threads! **Using a single thread eliminates the computation overhead of multithreading and is also the best solution for processing lots of images by running one Tesseract process per CPU core.**
> 
> Set the maximum number of threads using the environment variable OMP_THREAD_LIMIT.
> 
> To disable multithreading, use OMP_THREAD_LIMIT=1.

In your case, I would simply split the document/image into multiple files and use GNU Parallel to run multiple instances of tesseract with multithreading disabled.

**Comment by Chien-Hao** [comment]
Okay, thanks a lot for your suggestion.

**Comment by christophered** [comment]
@KyleBruene Good suggestion. but when using parallel, will the command be the same in the terminal?
`parallel tesseract image.jpg output.txt -l eng`

**Comment by christophered** [comment]
@Chien-Hao also have a look at 
https://github.com/tmbdev/das2018-tutorial
https://github.com/tmbdev/ocropy2

**Comment by Chien-Hao** [comment]
@christophered Thanks a lot for your information. I will try them if necessary.

**Comment by sirius0503** [comment]
> Short answer: No
> 
> As per FAQ
> 
> > Can I increase speed of OCR?
> > If you are running Tesseract 4, you can use the "fast" integer models.
> > Tesseract 4 also **uses up to four CPU threads** while processing a page, so it will be faster than Tesseract 3 for a single page.
> > If your computer has only two CPU cores, then running four threads will slow down things significantly and it would be better to use a single thread or maybe a maximum of two threads! **Using a single thread eliminates the computation overhead of multithreading and is also the best solution for processing lots of images by running one Tesseract process per CPU core.**
> > Set the maximum number of threads using the environment variable OMP_THREAD_LIMIT.
> > To disable multithreading, use OMP_THREAD_LIMIT=1.
> 
> In your case, I would simply split the document/image into multiple files and use GNU Parallel to run multiple instances of tesseract with multithreading disabled.

@KyleBruene What is the difference between GNU parallel and multiprocessing module of python, and which might be faster?

**Comment by Witiko** [comment]
> @KyleBruene Good suggestion. but when using parallel, will the command be the same in the terminal?
> `parallel tesseract image.jpg output.txt -l eng`

You can specify `--jobs 25%`, which will instruct parallel to run no more tesseract processes than a quarter of the available CPUs.

**Comment by baonq-me** [comment]
> Hello,
> 
> I am using tesseract-4.0.0-beta.1, and I have a ARM server with 96 CPU cores/threads. When I ran tesseract, it seems that by default it only uses 4 cores of the machine. Is it possible to run tesseract using more than 4 threads ?
> 
> I have tried to modify the parameter "kNumThreads" in the source code : lstm/fullyconnected.cpp, also num_threads() in ccmain/par_control.cpp and re-compiler tesseract. But the execution time is still almost the same. I have searched many web pages for the answer but none of them is satisfied.
> 
> Any suggestion and advice is welcome and appreciated. Thanks a lot.
> 
> Platform: Linux localhost.localdomain 4.14.0-49.el7a.aarch64

@Chien-Hao  Are you using `ThunderX3` CPU ?
