### ISSUE TITLE
passing base64 image to tesseract

### ISSUE THREAD

**Issue by nick4477** [tesseract-ocr/tesseract#1606]
### Environment

* **Tesseract Version**: 4 beta
* **Platform**: ubuntu 16

### Current Behavior:
I need passing a base64 image to tesseract for input ... anyone could help me how should change the ImageProcess function ?

sorry for this issue.
thanks

**Comment by zdenop** [comment]
Use tesseract user forum for asking question. But your question is not really related to tesseract....
