### ISSUE TITLE
small font issue

### ISSUE THREAD

**Issue by tofutim** [tesseract-ocr/tesseract#161]
It has been mentioned before that tesseract struggles with small fonts. I'm seeing this with standard sized Chinese in Chrome. If the image is magnified 2x (with no increase in information, just scale up the png), the recognition works great. Is there a way to do font size detection and just auto-scale up? Perhaps this is an English vs Chinese issue internally, so that when recognizing Chinese fonts, the image has to be increased in size before processing. I am not too familiar with tesseract internals, but could someone advise on (1) automatic font size detection, and (2) where to scale things up if it is for Chinese?

**Comment by tofutim** [comment]
Here's an actual sample:

(1) 100% font size screen cap from Chrome (Google News)
![orig](https://cloud.githubusercontent.com/assets/157766/11524501/21c2487e-9880-11e5-8caf-b1203b04adf2.png)

夜叉 鏖巴布韦迸行国
〈〈让中建友渲绽放出
不平FL的发展咸就y
""巴

(2) 1.5x
![1 5x](https://cloud.githubusercontent.com/assets/157766/11524541/58a5d3f6-9880-11e5-93d9-ccd9e6fc722d.png)

在对逞巴布韦迸行国
<<i上中津友谊绽放出
不平凡的发展成就'

习近平访犀巴

(3) 2x  - much much better (though still misses some chars...)
![2x](https://cloud.githubusercontent.com/assets/157766/11524549/68f085d0-9880-11e5-9df1-2b030a26f7eb.png)

在对逵巴布韦进行国
<<让中津友谊绽放出
不平凡的发展成戴，
逞评: 习近平访津巴

**Comment by tofutim** [comment]
Maybe it is possible to train with smaller fonts?

**Comment by Wikinaut** [comment]
Please make sure not to use the 72dpi screen resolution, which is always too small for Tesseract. Simply resize the screenshot (if you use screenshots) by +400% and repeat your tesseract runs, and please report here, if that solved your problem.

See https://github.com/tesseract-ocr/tesseract/wiki/FAQ#is-there-a-minimum-text-size-it-wont-read-screen-text

**Comment by tofutim** [comment]
10 pt screen resolution works perfectly for English. Is there a way to create a training set for lower resolution?

**Comment by amitdo** [comment]
> 10 pt screen resolution works perfectly for English.

You are mixing between two concepts. Screen resolution is measured  in dpi/ppi. 'pt' (point) is another concept.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

For questions, please use [Tesseract users forum](https://groups.google.com/d/forum/tesseract-ocr).
