### ISSUE TITLE
[Android] Not recognized in 4.0.0-beta.1 Release

### ISSUE THREAD

**Issue by firiona** [tesseract-ocr/tesseract#1612]
### Environment
* **Tesseract Version**: 4.0.0-beta.1 Release

### Current Behavior:
I have developed a Android application and updated tesseract version to 4.0.0-beta.1
I fixed many build errors, but characters are not recognized,

### Expected Behavior:
I read old issues lstm doesn't support Android.
https://github.com/tesseract-ocr/tesseract/issues/678
https://github.com/tesseract-ocr/tesseract/issues/1387

Android not supported since 4.0.0?

I want to know if you have a plan to support Android since 4.0.0.

Thank you,

**Comment by zdenop** [comment]
Please use tesseract user forum for asking questions
