### ISSUE TITLE
I do not understand how to use OCR with PHP please help

### ISSUE THREAD

**Issue by mohammadribhee** [tesseract-ocr/tesseract#1615]
I downloaded the project that has an example of OCR and installed the Composer but it always gives me an error on the argv variable 
The link you downloaded the project from
https://github.com/thiagoalessio/tesseract-ocr-for-php

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not support 3rd party project.  Use tesseract user forum for asking question.
