### ISSUE TITLE
Tesseract Binary: read_params_file: parameter not found: enable_new_segsearch

### ISSUE THREAD

**Issue by jmercouris** [tesseract-ocr/tesseract#1620]
Compiling with Xcode and Macports instructions: https://github.com/tesseract-ocr/tesseract/wiki/Compiling#macos-with-macports

Please see my configuration: [config.log](https://github.com/tesseract-ocr/tesseract/files/2064357/config.log)

------------------------

### Environment

* **Tesseract Version**: master
* **Commit Number**: f227f84231c6df8f596b19ad37a8bab80bd5ffac
* **Platform**: MacOS High Sierra

### Current Behavior:

executing `tesseract --list-langs` leads to:

`read_params_file: parameter not found: enable_new_segsearch`

also attempting `tesseract text.tiff outputbase -l eng` leads to: 

`read_params_file: parameter not found: enable_new_segsearch`

interestingly enough, the help arguments still work (e.g. `tesseract --help-extra`) without outputting any error messages

### Expected Behavior:
I would expect the program to work

### Suggested Fix:
No idea, attempting to install GCC via Macports now

**Comment by Shreeshrii** [comment]
Which traineddata file are you using? It seems using an obsolete config variable.

**Comment by jmercouris** [comment]
I didn't realize the training data was not portable across versions! I was using training data from version 3.5!

Let me try recompiling and using with new training data

**Comment by Shreeshrii** [comment]
@jmercouris Update?

**Comment by jmercouris** [comment]
I'm sorry, I have to do some reconfiguration with macports as that is how I originally got the training data sources, you can close this issue, I will reopen it if I find fault when using the correct training data

**Comment by Chandresh-SerpentCS** [comment]
I am also facing same issue right now

**Comment by barabanus** [comment]
I had the same problem because I installed `tesseract 4.0.0-beta.2-338-gda4a` over `tesseract 3.x`, so new version tried to use old trained data. When I updated trained data to match new version the error disappeared.

**Comment by lababidi** [comment]
`brew remove tesseract` then reinstall the beta version of the compiled tesseract via `sudo make install`

**Comment by jmercouris** [comment]
@lababidi Not everyone is using `brew`

**Comment by lababidi** [comment]
@jmercouris I posted my comment to help anyone out that has the similar error. No need to create a whole new thread. I've not used MacPorts, so I wouldn't know how to `remove` using it, but this may help someone using it. Once 4.0 is released as installable executables this issue may not come up anymore.

**Comment by JensHumrich** [comment]
I fixed it, by setting the TESSDATA_PREFIX path correctly, via export TESSDATA_PREFIX=/Users/jh186076/tessdata (path will be different).

**Comment by Shujaat34** [comment]
> I fixed it, by setting the TESSDATA_PREFIX path correctly, via export TESSDATA_PREFIX=/Users/jh186076/tessdata (path will be different).

Can you please explain the Steps how did you set TESSDATA_PREFIX path I have set the Environment Variable in widows but it keeps giving me this Error read_params_file: parameter not found: enable_new_segsearch

**Comment by Macilias** [comment]
Looks like same issue exist within on iOS, when running in simulator it works, on real device it crashes

**Comment by khalidhussain2021** [comment]
read_params_file: parameter not found: enable_new_segsearch 
a getting the that type of issue and did not extreact the data in windows
