### ISSUE TITLE
tesseract failing at FFmpeg configuration

### ISSUE THREAD

**Issue by logicomyu** [tesseract-ocr/tesseract#1622]
by using media-autobuild the following issue occurs:

https://pastebin.com/SxbA1CCt

**Comment by Warblefly** [comment]
Something connected with commit e313ed1bb960b71e61b645f54373a694260985fb?

**Comment by wpapp** [comment]
same here.
![snipaste_2018-06-07_07-27-22](https://user-images.githubusercontent.com/2141609/41072612-8ddfbe58-6a31-11e8-9091-44949d6896e7.png)

**Comment by wpapp** [comment]
Thanks a lot, it's ok now. You are great.
