### ISSUE TITLE
Moving the Tesseract project to Gitlab.com

### ISSUE THREAD

**Issue by christophered** [tesseract-ocr/tesseract#1631]
@theraysmith @egorpugin @zdenop 
Will you consider moving the Tesseract project to Gitlab.com?
Github was good while it lasted, but now it's time to move-on.
Gitlab vs Github
https://about.gitlab.com/comparison/

![ezgif-4-33acad734e](https://user-images.githubusercontent.com/33478216/40971275-c3a3f166-68c5-11e8-8bfd-7bd8ab415526.jpg)

**Comment by lucivpav** [comment]
What's wrong with GitHub? Just because Microsoft acquires GitHub doesn't make it a bad platform (yet), does it?

**Comment by egorpugin** [comment]
From my POV mirror will be enough for the first time. Just in case.

**Comment by zdenop** [comment]
What will be benefits from moving to gitlab?

Zdenko


po 4. 6. 2018 o 22:24 Egor Pugin <notifications@github.com> napísal(a):

**Comment by christophered** [comment]
Just in case Microzoft try to do some funny stuff to the users in the future `If you get what I'm saying`
They are a private company taking ownership of an open-source platform :sunglasses:
https://about.gitlab.com/features/

The Missing features are
https://about.gitlab.com/features/#missing

**Comment by christophered** [comment]
@zdenop Comparision between gitlab and github
https://about.gitlab.com/comparison/

**Comment by christophered** [comment]
@raffopazzo sure, but lets not forget the track-record of Microzoft of buying others, then ruining them.

**Comment by zdenop** [comment]
I don't want to take action based on FUD talks.
I am satisfied user of github and I will take action when I will not be
satisfied.
Moving to other platform need resources and usually means distraction from
main topics (you need to get familiar with platform). We have this
experience with moving from code.google.

Zdenko


ut 5. 6. 2018 o 12:26 christophered <notifications@github.com> napísal(a):
