### ISSUE TITLE
How can I recognize these images correctly with Tesseract?

### ISSUE THREAD

**Issue by yiran-THU** [tesseract-ocr/tesseract#1634]
### Environment

* **Tesseract Version**:  4.00.00-alpha
* **Commit Number**:   I don't know
* **Platform**:  Windows 10 64-bit, VS2015

### Current Behavior:
I have followed the guidance of [ImproveQuality](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality) strictly, but the accuracy recognization is still poor.
  
Here is my test images.
1.  
![caokqsoomoocahkbr1429](https://user-images.githubusercontent.com/16274710/40959415-38832e94-68cf-11e8-804b-eb3227817044.jpg)
Result is `CAOKQSOOMOOCAHKBR1429`  

2.  
![caokqsoomoocahkhbr1429](https://user-images.githubusercontent.com/16274710/40959416-392af606-68cf-11e8-9bd6-6c39e10f27d8.jpg)
Result is `CAOKQSOOMOOCAHKHBR1429`  

3.  
![caokqsoomoocakbr142_1](https://user-images.githubusercontent.com/16274710/40959417-39915914-68cf-11e8-85a8-4bfd76a79158.jpg)
Result is `CAOKQSOOMOOCAKBR142$`  

4.  
![caokqsoomoocakbr142](https://user-images.githubusercontent.com/16274710/40959419-3a121afe-68cf-11e8-9c5b-b3f0817971a5.jpg)
Result is `CAOKQSOOMOOCAKBR142$`  

5.  
![caokqsoomoocahkbr1429_1](https://user-images.githubusercontent.com/16274710/40959420-3a6b6ee2-68cf-11e8-9eda-d89733889c2e.jpg)
Result is `CAOKQSOOMOOCAHKBR1429`  

### Expected Behavior:  
I expect Tesseract recognize these images correct , don't take H as K anymore.

### Suggested Fix:
These image are good. Why tesseract can't recognize correctly？

What can I do to improve the accuracy?

**Comment by Shreeshrii** [comment]
Please try with latest version of the code (beta.1).

Which traineddata file did you use?

**Comment by yiran-THU** [comment]
@Shreeshrii 

I am using the best tessdata repo.

**Comment by Shreeshrii** [comment]
Please try with tessdata_fast as well as the current code. I am getting accurate results.

 File: ./num1.jpg

 ********** tessdata_fast eng psm 3

Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 1477
CAOKQSOOMOOCAHBR1429

 ********** tessdata_fast eng psm 4

Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 1477
CAOKQSOOMOOCAHBR1429

 ********** tessdata_fast eng psm 6

Warning. Invalid resolution 0 dpi. Using 70 instead.
CAOKQSOOMOOCAHBR1429

 ********** tessdata_fast eng psm 7

Warning. Invalid resolution 0 dpi. Using 70 instead.
CAOKQSOOMOOCAHBR1429

**Comment by Shreeshrii** [comment]
Also working with tessdata_best and tessdata. 


 File: ./num1.jpg

 ********** tessdata_best eng psm 3

Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 1477
CAOKQSOOMOOCAHBR 1429

 ********** tessdata_best eng psm 4

Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 1477
CAOKQSOOMOOCAHBR 1429

 ********** tessdata_best eng psm 6

Warning. Invalid resolution 0 dpi. Using 70 instead.
CAOKQSOOMOOCAHBR 1429

 ********** tessdata_best eng psm 7

Warning. Invalid resolution 0 dpi. Using 70 instead.
CAOKQSOOMOOCAHBR 1429

 ********** tessdata eng psm 3

Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 1477
CAOKQSOOMOOCAHBR1429

 ********** tessdata eng psm 4

Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 1477
CAOKQSOOMOOCAHBR1429

 ********** tessdata eng psm 6

Warning. Invalid resolution 0 dpi. Using 70 instead.
CAOKQSOOMOOCAHBR1429

 ********** tessdata eng psm 7

Warning. Invalid resolution 0 dpi. Using 70 instead.
CAOKQSOOMOOCAHBR1429

**Comment by zdenop** [comment]
Please respect guidelines for posting issue (use tesseract user forum for asking support)

**Comment by yiran-THU** [comment]
@Shreeshrii 
Thanks for your answer!
I tested with  tessdata_fast, but my result is not the same as yours.
I will try the latest version of Tesseract.

@zdenop 
Sorry, I thought I can help Tesseract to improve the accuracy， although the fact is not.
Next time , I will use tesseract user forum first.
Apologize again。
