### ISSUE TITLE
LoadDataFromFile should reserve an extra byte for '\0'

### ISSUE THREAD

**Issue by paulk124** [tesseract-ocr/tesseract#1636]
### Environment

* **Tesseract Version**: 
3.05
* **Commit Number**: 
65e5b7a4a65cdf6755503f07ce26d871aa2e2f01
* **Platform**: 
Windows 64-bit, Visual Studio 2015 Update 3

### Current Behavior:

Here is a sample of the problem it causes. I run the following to train the attached image and box file:

`tesseract gdt.symbols.exp0.tif gdt.symbols.exp0 box.train
`

And here is the output:

```
Tesseract Open Source OCR Engine v3.05.01 with Leptonica

Page 1
Bad box coordinates in boxfile string! ²²²²▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌╦ÇÆ§≡¿←
APPLY_BOXES:
   Boxes read from boxfile:       7
   Found 7 good blobs.
Generated training data for 3 words

```
The message about the bad box coordinates is caused because function ReadMemBoxes() reads memory past the end of the const char* box_data parameter.

### Expected Behavior:

Here is the expected output from running the tesseract command:

```
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Page 1
APPLY_BOXES:
   Boxes read from boxfile:       7
   Found 7 good blobs.
Generated training data for 3 words

```
### Suggested Fix:

To fix this, change function LoadDataFromFile() to always reserve an extra byte so the caller can add a ‘\0’ if they want. Then in ReadAllBoxes(), append ‘\0’ to the vector after calling LoadDataFromFile(). Here are the fixed functions:

```
inline bool LoadDataFromFile(const STRING& filename,
                             GenericVector<char>* data) {
  bool result = false;
  FILE* fp = fopen(filename.string(), "rb");
  if (fp != NULL) {
    fseek(fp, 0, SEEK_END);
    size_t size = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    if (size > 0) {
      // reserve an extra byte in case caller wants to append a '\0' character
      data->reserve(size + 1);
      data->resize_no_init(size);
      result = fread(&(*data)[0], 1, size, fp) == size;
    }
    fclose(fp);
  }
  return result;
}
```

```
bool ReadAllBoxes(int target_page, bool skip_blanks, const STRING& filename,
                  GenericVector<TBOX>* boxes,
                  GenericVector<STRING>* texts,
                  GenericVector<STRING>* box_texts,
                  GenericVector<int>* pages) {
  GenericVector<char> box_data;
  if (!tesseract::LoadDataFromFile(BoxFileName(filename), &box_data))
    return false;
  box_data.push_back('\0');
  return ReadMemBoxes(target_page, skip_blanks, &box_data[0], boxes, texts,
                      box_texts, pages);
}

```

**Comment by paulk124** [comment]
Here are the files mentioned in the description:
[gdt.symbols.exp0.zip](https://github.com/tesseract-ocr/tesseract/files/2072827/gdt.symbols.exp0.zip)

**Comment by zdenop** [comment]
Fixed with ee2ab73

**Comment by stweil** [comment]
I think the fix was unnecessary, because the problem did not exist in git master.

**Comment by paulk124** [comment]
@stweil, I agree the bug was already fixed with your earlier pull request. The only issue was the costly reallocation needed when the caller wants to append a '\0' character. Reserving an extra byte in LoadDataFromFile() doesn't affect any other caller because the size of the GenericVector will still be the same as it was before. The only slight downside is that all callers will have an extra byte allocated for the vector. This shouldn't impact performance and uses a very small amount of extra memory. I think the trade-off is well worth avoiding the memory reallocation.
