### ISSUE TITLE
Incorrect recognition with rotated images

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1651]
The following tests the recognition of the phototest image which has been rotated 90, 180 and 270 degrees, with both --psm 3 and --psm 6. While the program does not crash, the recognition is incorrect in most of the rotated images.

ubuntu@tesseract-ocr:~/tesseract$ tesseract ./test/testing/phototest.tif - --tessdata-dir ../tessdata_fast --oem 1 --psm 3 -l eng -c page_separator=''
Page 1
This is a lot of 12 point text to test the
ocr code and see if it works on all types
of file format.

The quick brown dog jumped over the
lazy fox. The quick brown dog jumped
over the lazy fox. The quick brown dog
jumped over the lazy fox. The quick
brown dog jumped over the lazy fox.
ubuntu@tesseract-ocr:~/tesseract$ tesseract ./test/testing/phototest-rotated-R.png - --tessdata-dir ../tessdata_fast --oem 1 --psm 3 -l eng -c page_separator=''
This is a lot of 12 point text to test the
ocr code and see if it works on all types
of file format.

The quick brown dog jumped over the
lazy fox. The quick brown dog jumped
over the lazy fox. The quick brown dog
jumped over the lazy fox. The quick
brown dog jumped over the lazy fox.
ubuntu@tesseract-ocr:~/tesseract$ tesseract ./test/testing/phototest-rotated-L.png - --tessdata-dir ../tessdata_fast --oem 1 --psm 3 -l eng -c page_separator=''
“‘xoy AZe] By} JBAO peduunl Bop umosgq
yoinb ay *xo} Aze] au} JOA peduun{
Bop umosg yoInb ay “xo Aze] ay} JaA0
peduun{ Bop umoiq yoinb aus ‘xoy Aze]
24} J8A0 peduun{ Bop umosg yoinb ayy
“JEUOY SII} JO

sadfj ||— UO SyJOM }I JI 89S PUe Bpod 490
OU} 4S9} 0} }X9} Julod Z|, JO jo] © SI SIYL
ubuntu@tesseract-ocr:~/tesseract$ tesseract ./test/testing/phototest-rotated-180.png - --tessdata-dir ../tessdata_fast --oem 1 --psm 3 -l eng -c page_separator=''
“‘xoy AZe] By} JBAO peduunl Bop umosgq
yoinb ay *xo} Aze] au} JOA peduun{
Bop umosg yoInb ay “xo Aze] ay} JaA0
peduun{ Bop umoiq yoinb aus ‘xoy Aze]
24} J8A0 peduun{ Bop umosg yoinb ayy
“JEUOY SII} JO

sadfj ||— UO SyJOM }I JI 89S PUe Bpod 490
OU} 4S9} 0} }X9} Julod Z|, JO jo] © SI SIYL
ubuntu@tesseract-ocr:~/tesseract$ tesseract ./test/testing/phototest-rotated-180.png - --tessdata-dir ../tessdata_fast --oem 1 --psm 6  -l eng -c page_separator=''
“‘xoy AZe] By} JBAO peduunl Bop umosgq
yoinb ay *xo} Aze] au} JOA peduun{
Bop umosg yoInb ay “xo Aze] ay} JaA0
peduun{ Bop umoiq yoinb aus ‘xoy Aze]
24} J8A0 peduun{ Bop umosg yoinb ayy
“JEUOY SII} JO

sadfj ||— UO SyJOM }I JI 89S PUe Bpod 490
OU} 4S9} 0} }X9} Julod Z|, JO jo] © SI SIYL
ubuntu@tesseract-ocr:~/tesseract$ tesseract ./test/testing/phototest-rotated-L.png - --tessdata-dir ../tessdata_fast --oem 1 --psm 6  -l eng -c page_separator=''
o Dp

o o .
2s £88x x
Se Lecos
a= o£EE§s
Da $535 >
2. oa8ek
2° BSvie
% acs ea
<2 @ Be
25 ESssz
25 §2385
a Seezs
£2 Bale
oe SxF 8
as eat e8
NN ® case
~2 §358
54: 8 as S
5 ;50RG5
em egos
SEESERS 2
Qoevrs 8
s2s5oxog
ogeesege
255 = es
255 2RSES
E8sfass
FOoOoFS
ubuntu@tesseract-ocr:~/tesseract$ tesseract ./test/testing/phototest-rotated-R.png - --tessdata-dir ../tessdata_fast --oem 1 --psm 6  -l eng -c page_separator=''
x
TOD
Sre2as
o5 987357
aT =
Sgag2°85
2 aSeca®
ges ESBS
SoRataes
o>
EaRssRac
3sc22' 2
gases 85
x aS an
Bass =3
gisge 25
Ss2aes z2
nees§ ea
s £53 Soa
34233 a
Regeo g8
<2 ee >
sss a é
s5538 2
2605 oF
off ZZ
eke $i
®
n
ubuntu@tesseract-ocr:~/tesseract$

**Comment by Shreeshrii** [comment]
These images are used in the osd test and get the correct result.


[----------] 1 test from TessdataFastRotated90/OSDTest
[ RUN      ] TessdataFastRotated90/OSDTest.MatchOrientationDegrees/0
************ Orientation in degrees: 90, Orientation confidence: 9.30
             Script: Latin, Script confidence: 8.06
[       OK ] TessdataFastRotated90/OSDTest.MatchOrientationDegrees/0 (415 ms)
[----------] 1 test from TessdataFastRotated90/OSDTest (415 ms total)

[----------] 1 test from TessdataFastRotated180/OSDTest
[ RUN      ] TessdataFastRotated180/OSDTest.MatchOrientationDegrees/0
************ Orientation in degrees: 180, Orientation confidence: 10.99
             Script: Latin, Script confidence: 5.83
[       OK ] TessdataFastRotated180/OSDTest.MatchOrientationDegrees/0 (414 ms)
[----------] 1 test from TessdataFastRotated180/OSDTest (414 ms total)

[----------] 1 test from TessdataFastRotated270/OSDTest
[ RUN      ] TessdataFastRotated270/OSDTest.MatchOrientationDegrees/0
************ Orientation in degrees: 270, Orientation confidence: 9.62
             Script: Latin, Script confidence: 3.03
[       OK ] TessdataFastRotated270/OSDTest.MatchOrientationDegrees/0 (412 ms)
[----------] 1 test from TessdataFastRotated270/OSDTest (412 ms total)


My suggestion would be that tesseract also use the osd check internally and rotate the image as needed.

**Comment by amitdo** [comment]
If you anticipate that some of the images might be rotated, use psm 1.
Use psm 3 only for pages that you know that are unrotated.  

'you' - not just you, but any user.

**Comment by Shreeshrii** [comment]
@amitdo Thank you. That works. Now need to check whether it will work with the image from Spanish UNLV test.

ubuntu@tesseract-ocr:~/tesseract$ tesseract ./test/testing/phototest-rotated-R.png - --tessdata-dir ../tessdata_fast --oem 1 --psm 1  -l eng -c page_separator=''
This is a lot of 12 point text to test the
ocr code and see if it works on all types
of file format.

The quick brown dog jumped over the
lazy fox. The quick brown dog jumped
over the lazy fox. The quick brown dog
jumped over the lazy fox. The quick
brown dog jumped over the lazy fox.

ubuntu@tesseract-ocr:~/tesseract$ tesseract ./test/testing/phototest-rotated-L.png - --tessdata-dir ../tessdata_fast --oem 1 --psm 1  -l eng -c page_separator=''
This is a lot of 12 point text to test the
ocr code and see if it works on all types
of file format.

The quick brown dog jumped over the
lazy fox. The quick brown dog jumped
over the lazy fox. The quick brown dog
jumped over the lazy fox. The quick
brown dog jumped over the lazy fox.

ubuntu@tesseract-ocr:~/tesseract$ tesseract ./test/testing/phototest-rotated-180.png - --tessdata-dir ../tessdata_fast --oem 1 --psm 1  -l eng -c page_separator=''
This is a lot of 12 point text to test the
ocr code and see if it works on all types
of file format.

The quick brown dog jumped over the
lazy fox. The quick brown dog jumped
over the lazy fox. The quick brown dog
jumped over the lazy fox. The quick
brown dog jumped over the lazy fox.

**Comment by Shreeshrii** [comment]
```
Page segmentation modes:
  0    Orientation and script detection (OSD) only.
  1    Automatic page segmentation with OSD.
  2    Automatic page segmentation, but no OSD, or OCR.
  3    Fully automatic page segmentation, but no OSD. (Default)
  4    Assume a single column of text of variable sizes.
  5    Assume a single uniform block of vertically aligned text.
  6    Assume a single uniform block of text.
```
