### ISSUE TITLE
tesseract error: count > 0:Error:Assert failed:in file serialis.cpp, line 115

### ISSUE THREAD

**Issue by zzubqh** [tesseract-ocr/tesseract#1664]
**Environment**
**Tesseract Version**
 tesseract 4.0.0-beta.1
 leptonica-1.76.0 (Jun 12 2018, 21:33:36) [MSC v.1900 LIB Debug x86]
 libgif 5.1.4 : libjpeg 9b : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

**Platform**
windows10
**Current Behavior**
I had compiled  tesseract source code by vs2015, but when I run 'tesseract.exe --list-langs' , I got this error:
`count > 0:Error:Assert failed:in file serialis.cpp, line 115`
I fond this error caused by this code in "intproto.cpp" at 905 line number:

   ```
   // fp->FReadEndian() broken because num_configs  = 0 
    int num_configs = version_id < 4 ? MaxNumConfigs : Class->NumConfigs;
    ASSERT_HOST(num_configs <= MaxNumConfigs);
    if (fp->FReadEndian(Class->ConfigLengths, sizeof(uint16_t), num_configs) !=
        num_configs) {
      tprintf("Bad read of inttemp!\n");
    }
```
I do not know why is like that. Please tell me how can I do? Thanks a lot!

**Comment by amitdo** [comment]
Did you download any traineddata file? Which one, from which repo?

**Comment by zzubqh** [comment]
I have download the eng.traineddata, and config the "TESSDATA_PREFIX" in my environment variables, like this : D:\Program Files (x86)\Tesseract-OCR\tessdata\
If I run 'tesseract.exe 1.tif 1" , I got the same result:
`count > 0:Error:Assert failed:in file serialis.cpp, line 115`

**Comment by Shreeshrii** [comment]
@stweil This seems related to https://github.com/tesseract-ocr/tesseract/commit/52fddc3ca9931f3452cc8fa92fe3288857f3cda5

**Comment by amitdo** [comment]
>D:\Program Files (x86)\

 @Shreeshrii,
Does Tesseract can handle a TESSDATA_PREFIX that includes spaces?

**Comment by zzubqh** [comment]
Hi all, I have resolved this problem. I am so sorry that the error occurred in master version ont 4.0.0-beta.1 version.
The following code is added to the latest version, in serialis.cpp at TFile::FRead() function
  ```
  ASSERT_HOST(size > 0);
  ASSERT_HOST(count > 0); 
  size_t required_size;
  if (SIZE_MAX / size <= count) {
    // Avoid integer overflow.
    required_size = data_->size() - offset_;
  } 
```
**ASSERT_HOST(count > 0);**  This code leads to the error. In 4.0.0-beta.1 version, the variable ’num_configs’  is also  equal to 0.

**Comment by Shreeshrii** [comment]
@zzubqh If the problem is there in master version, please reopen the issue.
