### ISSUE TITLE
can "traineddata" for tesseract 3 be used for training tesseract 4

### ISSUE THREAD

**Issue by c-c-3** [tesseract-ocr/tesseract#1668]
I have trained tesseract 3 using 64 fonts with box files and jpg images and .tr files respectively but can i use the same trained data along with the starter trained generated to train further the tesseract 4.
The starter trained data has been generated as using the lang data provided in the documentation as follows:-
'''Using tesstrain
The setup for running tesstrain.sh is the same as for base Tesseract. Use --linedata_only option for LSTM training. Note that it is beneficial to have more training text and make more pages though, as neural nets don't generalize as well and need to train on something similar to what they will be running on. If the target domain is severely limited, then all the dire warnings about needing a lot of training data may not apply, but the network specification may need to be changed.

Training data is created using tesstrain.sh as follows: Note that your fonts location may vary.

training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only \
  --noextract_font_properties --langdata_dir ../langdata \
  --tessdata_dir ./tessdata --output_dir ~/tesstutorial/engtrain
The above command makes LSTM training data equivalent to the data used to train base Tesseract for English. For making a general-purpose LSTM-based OCR engine, it is woefully inadequate, but makes a good tutorial demo.

Now try this to make eval data for the 'Impact' font:

training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only \
  --noextract_font_properties --langdata_dir ../langdata \
  --tessdata_dir ./tessdata \
  --fontlist "Impact Condensed" --output_dir ~/tesstutorial/engeval'''
Now the problem is that the previous trained data that was used had .tr files and no .lstmf files as required by the tesseract 4.
Can the .tr files along with the box files and .jpg images be used to generate the required .lstmf files as issue#1172.
Requesting a solution asap.

**Comment by Shreeshrii** [comment]
>Can the .tr files along with the box files and .jpg images be used to generate the required .lstmf files 

NO. 

You can use box files and jpgs to generate .lstmf files only after the box files have been modified for Tesseract4, otherwise training will not work.

It will be easiest for you to use the 64 fonts and training text to create the appropriate lstmf files.

**Comment by Shreeshrii** [comment]
Please use tesseract forum for asking questions.

@zdenop please close the issue.

**Comment by c-c-3** [comment]
Actually I am manually updating the box files for generating the .lstmf
file by the way thanks for the reply and if required would ask for much
more help.

**Comment by Shreeshrii** [comment]
@zdenop please close the issue.
