### ISSUE TITLE
Error writing unicharset on running combine_lang_model

### ISSUE THREAD

**Issue by srdg** [tesseract-ocr/tesseract#1673]
### Environment

* **Tesseract Version**: tesseract 4.0.0-beta.1-370-g8b64
* **Platform**: Ubuntu 16.04

### Current Behavior:

I have a custom made unicharset file made with unicharset_extractor by running with hand-modified box files available from tesseract 3 training. I generated the lstmf files successfully by running tesseract `${img_file} ${img_file%.*} 'lstm.train'`.
According to [this part of tesstrain_utils.sh](https://github.com/tesseract-ocr/tesseract/blob/master/src/training/tesstrain_utils.sh#L517), the next step is to run `combine_lang_model` that'll generate the starter traineddata and use that in addition to the lstmf files to train Tesseract using `lstmtraining`. However, when I run the following command from `langdata/digits` directory :
`combine_lang_model --input_unicharset 'digits.unicharset' --script_dir '../' --output_dir '../digout' --lang digits`
it fails with the following log :
```
Loaded unicharset of size 11 from file digits.unicharset
Setting unichar properties
Setting script properties
Error writing unicharset!!

```

Any idea what is causing this and how to resolve?

**Comment by Shreeshrii** [comment]
see https://pastebin.com/gNLvXkiM for a bash script with complete 4.0 training process. If you hand create files, then you need to ensure correct input is given to next step.

Is the output directory created before hand and writable by you?

**Comment by srdg** [comment]
@Shreeshrii No, I did not create the output directory beforehand. This is the content of my custom folder with lstmf files:

```
digits.f0.exp0.box     digits.f16.exp0.txt    digits.f23.exp0.lstmf  digits.f30.exp0.jpg    digits.f4.exp0.jpg
digits.f0.exp0.jpg     digits.f17.exp0.box    digits.f23.exp0.txt    digits.f30.exp0.lstmf  digits.f4.exp0.lstmf
digits.f0.exp0.lstmf   digits.f17.exp0.jpg    digits.f24.exp0.box    digits.f30.exp0.txt    digits.f4.exp0.txt
digits.f0.exp0.txt     digits.f17.exp0.lstmf  digits.f24.exp0.jpg    digits.f31.exp0.box    digits.f5.exp0.box
digits.f10.exp0.box    digits.f17.exp0.txt    digits.f24.exp0.lstmf  digits.f31.exp0.jpg    digits.f5.exp0.jpg
digits.f10.exp0.jpg    digits.f18.exp0.box    digits.f24.exp0.txt    digits.f31.exp0.lstmf  digits.f5.exp0.lstmf
digits.f10.exp0.lstmf  digits.f18.exp0.jpg    digits.f25.exp0.box    digits.f31.exp0.txt    digits.f5.exp0.txt
digits.f10.exp0.txt    digits.f18.exp0.lstmf  digits.f25.exp0.jpg    digits.f32.exp0.box    digits.f6.exp0.box
digits.f11.exp0.box    digits.f18.exp0.txt    digits.f25.exp0.lstmf  digits.f32.exp0.jpg    digits.f6.exp0.jpg
digits.f11.exp0.jpg    digits.f19.exp0.box    digits.f25.exp0.txt    digits.f32.exp0.lstmf  digits.f6.exp0.lstmf
digits.f11.exp0.lstmf  digits.f19.exp0.jpg    digits.f26.exp0.box    digits.f32.exp0.txt    digits.f6.exp0.txt
digits.f11.exp0.txt    digits.f19.exp0.lstmf  digits.f26.exp0.jpg    digits.f33.exp0.box    digits.f7.exp0.box
digits.f12.exp0.box    digits.f19.exp0.txt    digits.f26.exp0.lstmf  digits.f33.exp0.jpg    digits.f7.exp0.jpg
digits.f12.exp0.jpg    digits.f1.exp0.box     digits.f26.exp0.txt    digits.f33.exp0.lstmf  digits.f7.exp0.lstmf
digits.f12.exp0.lstmf  digits.f1.exp0.jpg     digits.f27.exp0.box    digits.f33.exp0.txt    digits.f7.exp0.txt
digits.f12.exp0.txt    digits.f1.exp0.lstmf   digits.f27.exp0.jpg    digits.f34.exp0.box    digits.f8.exp0.box
digits.f13.exp0.box    digits.f1.exp0.txt     digits.f27.exp0.lstmf  digits.f34.exp0.jpg    digits.f8.exp0.jpg
digits.f13.exp0.jpg    digits.f20.exp0.box    digits.f27.exp0.txt    digits.f34.exp0.txt    digits.f8.exp0.lstmf
digits.f13.exp0.lstmf  digits.f20.exp0.jpg    digits.f28.exp0.box    digits.f35.exp0.box    digits.f8.exp0.txt
digits.f13.exp0.txt    digits.f20.exp0.lstmf  digits.f28.exp0.jpg    digits.f35.exp0.jpg    digits.f9.exp0.box
digits.f14.exp0.box    digits.f20.exp0.txt    digits.f28.exp0.lstmf  digits.f35.exp0.lstmf  digits.f9.exp0.jpg
digits.f14.exp0.jpg    digits.f21.exp0.box    digits.f28.exp0.txt    digits.f35.exp0.txt    digits.f9.exp0.lstmf
digits.f14.exp0.lstmf  digits.f21.exp0.jpg    digits.f29.exp0.box    digits.f36.exp0.box    digits.f9.exp0.txt
digits.f14.exp0.txt    digits.f21.exp0.lstmf  digits.f29.exp0.jpg    digits.f36.exp0.jpg    digits.font_properties
digits.f15.exp0.box    digits.f21.exp0.txt    digits.f29.exp0.lstmf  digits.f36.exp0.lstmf  digits.inttemp
digits.f15.exp0.jpg    digits.f22.exp0.box    digits.f29.exp0.txt    digits.f36.exp0.txt    digits.normproto
digits.f15.exp0.lstmf  digits.f22.exp0.jpg    digits.f2.exp0.box     digits.f3.exp0.box     digits.pffmtable
digits.f15.exp0.txt    digits.f22.exp0.lstmf  digits.f2.exp0.jpg     digits.f3.exp0.jpg     digits.shapetable
digits.f16.exp0.box    digits.f22.exp0.txt    digits.f2.exp0.lstmf   digits.f3.exp0.lstmf   digits.traineddata
digits.f16.exp0.jpg    digits.f23.exp0.box    digits.f2.exp0.txt     digits.f3.exp0.txt     digits.unicharset
digits.f16.exp0.lstmf  digits.f23.exp0.jpg    digits.f30.exp0.box    digits.f4.exp0.box     Thumbs.db

```
What purpose do the txt files serve? Contain the text corpus so tesseract knows the ground truth?

**Comment by srdg** [comment]
@Shreeshrii I created the `output-dir` manually with full permissions to myself, and sure enough, the log extended a bit more. This was the command -
`combine_lang_model --input_unicharset 'digits.unicharset' --script_dir '..' --output_dir './digout' --lang digits`
The error log : 
```
Loaded unicharset of size 11 from file digits.unicharset
Setting unichar properties
Setting script properties
Config file is optional, continuing...
Failed to read data from: ../digits/digits.config
Null char=11

```
It seems it needs a config file anyway. How do I make it?
P.S. I am sure enough that the inputs are correct, I followed exactly what `tesstrain.sh` does!

**Comment by Shreeshrii** [comment]
>Config file is optional, continuing...

It is just an info message.

>What purpose do the txt files serve? Contain the text corpus so tesseract knows the ground truth?

Wish they contained the ground truth... They seem to be empty files with just line feeds  and form feeds. They seem to be generated by tesseract while building lstmf files. 

The box, tif, txt are NOT used in further training, only the lstmf files and the starter traineddata is used.

tesstrain.sh only does the first step for training tesseract 4 (unlike tesseract3 where it prouces the final traineddata file).

You need to run the actual lstmtraining after that.

**Comment by Shreeshrii** [comment]
>Error writing unicharset on running combine_lang_model

The output directories MUST be made manually before running the commands.

**Comment by srdg** [comment]
@Shreeshrii yes, I created the output directory manually and the [error log changed](https://github.com/tesseract-ocr/tesseract/issues/1673#issuecomment-397790532).

> `Failed to read data from: ../digits/digits.config`

How to create this file? Does tesstrain.sh generate a config file automatically?

**Comment by ShreyDixit** [comment]
@srdg How did you fix that issue?

**Comment by srdg** [comment]
@ShreyDixit  as far as I remember, the training procedure required me to run `tesstrain.sh` itself, like mentioned [here](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#using-tesstrainsh). If you follow the wiki properly, it would not be a problem. I'd suggest reading the entire thing first before trying out the commands. 
Also, I don't know if this will be of any help, but just for information, it turned out there was a bug during `lstmtraining` (at the time tesseract was in beta version). You can view it at #1748.
