### ISSUE TITLE
Japan Gives an Error

### ISSUE THREAD

**Issue by psukardi** [tesseract-ocr/tesseract#1675]
After reading https://github.com/tesseract-ocr/tesseract/issues/1441 I've downloaded the suggested file.  However when attempting to run the following 

tesseract my_file.jpg out -l jpn

I'm given the following error

Tesseract Open Source OCR Engine vv4.0.0-beta.1.20180608 with Leptonica
Error during processing.

**Comment by Shreeshrii** [comment]
Please share the input image you gave.

Which traineddata file are you using? Where is it installed/located?

**Comment by ValadezRicardo** [comment]
Hello everyone, 

I have the same problem

**Comment by laidayang** [comment]
I have the same problems too

**Comment by Shreeshrii** [comment]
"I have same problem" is NOT HELPFUL in solving it.

Please mention:

Version of tesseract
Which Operating system
Which version of jpn.traineddata
What command was used
Sample image which gave error

**Comment by zdenop** [comment]
Closed because of missing input from reporter
