### ISSUE TITLE
tesseract --list-langs doesn't print languages installed

### ISSUE THREAD

**Issue by srdg** [tesseract-ocr/tesseract#1679]
### Environment

* **Tesseract Version**:4.0.0-beta.1-370-g8b64
* **Platform**: Linux Ubuntu 16.04 LTS

### Current Behavior:
`tesseract --list-langs` gives the following error log : 
`read_params_file: parameter not found: enable_new_segsearch`

### Expected Behavior:
Should give a list of all languages installed.

Any idea what to do? I tried searching previous issues, the closest I came to was #1620 .
Also, I'm using a custom `digits.traineddata` file made from running `lstmtraining`.

**Comment by Shreeshrii** [comment]
Looks like you have an old version (3) installed and tessdata_prefix is pointing to that.

try

```
tesseract --tessdata-dir /path/to/your/tessdata --list-langs
```

**Comment by stweil** [comment]
It looks like you have installed the Debian / Ubuntu package(s) for Tesseract and installed a newly built Tesseract. Now you have a `/usr/local/bin/unicharset_extractor` executable, and maybe it still loads the shared library from `/usr/lib` instead of using the shared library from `/usr/local/lib`. Try `ldd /usr/local/bin/unicharset_extractor` to see which library is used.

**Comment by Chandresh-SerpentCS** [comment]
+1

**Comment by Shreeshrii** [comment]
post output from

env

tesseract -v

text2image -v

lstmtraining -v

unicharset_extractor -v

ldd /usr/local/bin/unicharset_extractor

ldd /usr/bin/unicharset_extractor

do a find on eng.traineddata and osd.traineddata and post results

**Comment by srdg** [comment]
@Shreeshrii  I resolved the error. Apparently the unicharset_extractor that tesseract4 was using by default was in `/usr/local/bin` and the recompiled unicharset_extractor was in `~/local/bin`. Same for the others.
I replaced the files and it worked smoothly.
However, on running 
`lstmtraining --debug_interval -1   --traineddata ./alphaout/alpha/alpha.traineddata   --net_spec '[1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx96 Lrx96 Lfx256 O1c111]'   --model_output ./alphaout/base --learning_rate 20e-4   --train_listfile ./alpha.training_files.txt  --max_iterations 5000 &>./alphaout/basetrain.log
`
I'm getting an error as `Compute CTC Targets failed!`.
The same command when run with `--debug_interval 100` gives 
```
Loaded 1/1 pages (1-1) of document alpha.f0.exp0.lstmf
Loaded 1/1 pages (1-1) of document alpha.f10.exp0.lstmf
Loaded 1/1 pages (1-1) of document alpha.f13.exp0.lstmf
Loaded 1/1 pages (1-1) of document alpha.f16.exp0.lstmf
Loaded 1/1 pages (1-1) of document alpha.f18.exp0.lstmf
Loaded 1/1 pages (1-1) of document alpha.f11.exp0.lstmf
Loaded 1/1 pages (1-1) of document alpha.f17.exp0.lstmf
Loaded 1/1 pages (1-1) of document alpha.f14.exp0.lstmf
Loaded 1/1 pages (1-1) of document alpha.f15.exp0.lstmf
Starting sh -c "trap 'kill %1' 0 1 2 ; java -Xms1024m -Xmx2048m -jar ./ScrollView.jar & wait"
Error: Unable to access jarfile ./ScrollView.jar
sh: 1: kill: No such process

```
What might be causing this? I checked and the `ScrollView.jar` file was in its right place.
I'm posting the results you asked below

env
```
CLUTTER_IM_MODULE=xim
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
GNOME_KEYRING_PID=
LESSCLOSE=/usr/bin/lesspipe %s %s
LANG=en_IN
GDM_LANG=en_US
DISPLAY=:0
COMPIZ_CONFIG_PROFILE=ubuntu
GTK2_MODULES=overlay-scrollbar
UPSTART_INSTANCE=
XDG_VTNR=7
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
SESSIONTYPE=gnome-session
XDG_SESSION_ID=c2
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/soumik
USER=soumik
DESKTOP_SESSION=ubuntu
JOB=gnome-session
QT4_IM_MODULE=xim
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
QT_QPA_PLATFORMTHEME=appmenu-qt5
PWD=/home/soumik
HOME=/home/soumik
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1273
XDG_SESSION_DESKTOP=ubuntu
GTK_MODULES=gail:atk-bridge:unity-gtk-module
UPSTART_EVENTS=started starting
TERM=xterm-256color
SHELL=/bin/bash
VTE_VERSION=4205
TESSDATA_PREFIX=/usr/share/tesseract-ocr/tessdata
GNOME_KEYRING_CONTROL=
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=1
INSTANCE=Unity
XDG_CURRENT_DESKTOP=Unity
GPG_AGENT_INFO=/home/soumik/.gnupg/S.gpg-agent:0:1
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
XDG_SEAT=seat0
SHLVL=1
LANGUAGE=en_IN:en
WINDOWID=69227561
GDMSESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=soumik
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-sFYs4CYrnp
UPSTART_JOB=unity-settings-daemon
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/home/soumik/.Xauthority
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
PATH=/home/soumik/bin:/home/soumik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
_=/usr/bin/env

```

tesseract -v
```
tesseract 4.0.0-beta.1-376-gb1f79
 leptonica-1.74.1
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8

 Found AVX2
 Found AVX
 Found SSE

```

text2image -v
`4.0.0-beta.1-376-gb1f79`

lstmtraining -v
`4.0.0-beta.1-376-gb1f79`

unicharset_extractor -v
`4.0.0-beta.1-376-gb1f79`

ldd /usr/local/bin/unicharset_extractor
```        
        linux-vdso.so.1 =>  (0x00007ffe103f1000)
	libicui18n.so.55 => /usr/lib/x86_64-linux-gnu/libicui18n.so.55 (0x00007f6fbb208000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f6fbae74000)
	libtesseract.so.4 => /home/soumik/local/lib/libtesseract.so.4 (0x00007f6fba692000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6fba306000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6fba0f0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6fb9d26000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6fb9a1d000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f6fb7f66000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6fb7d62000)
	liblept.so.5 => /usr/local/lib/liblept.so.5 (0x00007f6fb78f9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6fb76dc000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f6fb74ac000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6fbb66a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6fb7292000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f6fb706d000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f6fb6e14000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f6fb6ba0000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f6fb697a000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f6fb676c000)
```

ldd /usr/bin/unicharset_extractor
 ` ldd: /usr/bin/unicharset_extractor: No such file or directory`

The eng.traineddata file is in `/usr/share/tesseract-ocr/tessdata`, along with `digits.traineddata`.

**Comment by Chandresh-SerpentCS** [comment]
**env**

`XDG_VTNR=7
XDG_SESSION_ID=c2
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/serpentcs
SELINUX_INIT=YES
CLUTTER_IM_MODULE=xim
COMP_WORDBREAKS= 	
"'><;|&(:
SESSION=ubuntu
GPG_AGENT_INFO=/run/user/1000/keyring-lDM9Ul/gpg:0:1
TERM=xterm
VTE_VERSION=3409
XDG_MENU_PREFIX=gnome-
SHELL=/bin/bash
DERBY_HOME=/usr/lib/jvm/java-8-oracle/db
WINDOWID=92274699
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/2440
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-lDM9Ul
GTK_MODULES=overlay-scrollbar:unity-gtk-module
USER=serpentcs
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/run/user/1000/keyring-lDM9Ul/ssh
SESSION_MANAGER=local/serpentcs-A5:@/tmp/.ICE-unix/2613,unix/serpentcs-A5:/tmp/.ICE-unix/2613
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
DESKTOP_SESSION=ubuntu
PATH=/home/serpentcs/.local/share/umake/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=appmenu-qt5
PWD=/home/serpentcs
JOB=dbus
XMODIFIERS=@im=ibus
JAVA_HOME=/usr/lib/jvm/java-8-oracle
GNOME_KEYRING_PID=2438
LANG=en_IN
GDM_LANG=en_US
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
COMPIZ_CONFIG_PROFILE=ubuntu
IM_CONFIG_PHASE=1
GDMSESSION=ubuntu
SESSIONTYPE=gnome-session
SHLVL=1
HOME=/home/serpentcs
XDG_SEAT=seat0
LANGUAGE=en_IN:en
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=serpentcs
COMPIZ_BIN_PATH=/usr/bin/
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-uEjTbswRCp
J2SDKDIR=/usr/lib/jvm/java-8-oracle
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/
QT4_IM_MODULE=xim
INSTANCE=
TEXTDOMAIN=im-config
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
XDG_CURRENT_DESKTOP=Unity
GTK_IM_MODULE=ibus
J2REDIR=/usr/lib/jvm/java-8-oracle/jre
TEXTDOMAINDIR=/usr/share/locale/
XAUTHORITY=/home/serpentcs/.Xauthority
COLORTERM=gnome-terminal
OLDPWD=/home/serpentcs/Downloads
_=/usr/bin/env`

**tesseract -v**

`tesseract 4.0.0-beta.1
 leptonica-1.74.4
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.0

 Found AVX2
 Found AVX
 Found SSE`

**text2image -v**

`text2image: command not found`

**lstmtraining -v**

`lstmtraining: command not found`

**unicharset_extractor -v**

`unicharset_extractor: command not found`

**ldd /usr/local/bin/unicharset_extractor**

`ldd: /usr/local/bin/unicharset_extractor: No such file or directory`

**ldd /usr/bin/unicharset_extractor**

`ldd: /usr/bin/unicharset_extractor: No such file or directory`

**locate eng.traineddata**

`/usr/share/tesseract-ocr/tessdata/eng.traineddata`

**locate osd.traineddata**

`/usr/share/tesseract-ocr/tessdata/osd.traineddata`

**Comment by Shreeshrii** [comment]
@srdg 

>Apparently the unicharset_extractor that tesseract4 was using by default was in /usr/local/bin and the recompiled unicharset_extractor was in ~/local/bin

That means you have multiple versions installed/built. It will help if you uninstall/remove all old versions of programs, includes, libraries etc.

which tesseract

which unichar_extractor 

would show which version is being run.

Regarding scrollview, please search in open/closed issues, forum and wiki. I am sure a solution is posted somewhere. I do not use it hence do not know the details.

**Comment by Shreeshrii** [comment]
@Chandresh-SerpentCS 

Looks like you only have tesseract installed, it does not seem to include the training tools. If building yourself, you need to

make training
make training-install

You also need to check that there are not multiple versions of tesseract and traineddata files installed.

**Comment by Chandresh-SerpentCS** [comment]
combine_tessdata -d /usr/share/tesseract-ocr/tessdata/eng.traineddata


combine_tessdata: command not found

**Comment by Shreeshrii** [comment]
@Chandresh-SerpentCS 

How did you build/install tesseract?

**Comment by Chandresh-SerpentCS** [comment]
https://lucacerone.net/2017/install-tesseract-3-0-5-in-ubuntu-16-04/

**Comment by Chandresh-SerpentCS** [comment]
If you have any other way for the installation then please direct me.

**Comment by Shreeshrii** [comment]
You are following instructions to build 3.0.5 and wanting to use 4.0.0 - no wonder there are problems.

I suggest you remove the existing versions and then do a clean install from one of the links given on 

https://github.com/tesseract-ocr/tesseract/wiki

**Comment by Shreeshrii** [comment]
@srdg A few of CTC errors can be ignored. If there are many then there maybe problems with the way you built the lstmf files.

**Comment by srdg** [comment]
@Shreeshrii while building the `Unicharset` files I got the following:
```
Extracting unicharset from box file alpha.f48.exp0.box
Extracting unicharset from box file alpha.f49.exp0.box
Extracting unicharset from box file alpha.f50.exp0.box
Extracting unicharset from box file alpha.f51.exp0.box
Extracting unicharset from box file alpha.f52.exp0.box
Extracting unicharset from box file alpha.f53.exp0.box
Extracting unicharset from box file alpha.f54.exp0.box
Extracting unicharset from box file alpha.f55.exp0.box
Extracting unicharset from box file alpha.f56.exp0.box
Extracting unicharset from box file alpha.f57.exp0.box
Extracting unicharset from box file alpha.f58.exp0.box
Extracting unicharset from box file alpha.f59.exp0.box
Extracting unicharset from box file alpha.f60.exp0.box
Extracting unicharset from box file alpha.f61.exp0.box
Other case a of A is not in unicharset
Other case b of B is not in unicharset
Other case c of C is not in unicharset
Other case d of D is not in unicharset
Other case e of E is not in unicharset
Other case f of F is not in unicharset
Other case g of G is not in unicharset
Other case h of H is not in unicharset
Other case i of I is not in unicharset
Other case j of J is not in unicharset
Other case k of K is not in unicharset
Other case l of L is not in unicharset
Other case m of M is not in unicharset
Other case n of N is not in unicharset
Other case o of O is not in unicharset
Other case p of P is not in unicharset
Other case q of Q is not in unicharset
Other case r of R is not in unicharset
Other case s of S is not in unicharset
Other case t of T is not in unicharset
Other case u of U is not in unicharset
Other case v of V is not in unicharset
Other case w of W is not in unicharset
Other case x of X is not in unicharset
Other case y of Y is not in unicharset
Other case z of Z is not in unicharset
Wrote unicharset file unicharset

```
Could this be the problem?

**Comment by Chandresh-SerpentCS** [comment]
@Shreeshrii 

**ldd /usr/bin/unicharset_extractor**

linux-vdso.so.1 =>  (0x00007ffc613b0000)
	libicui18n.so.52 => /usr/lib/x86_64-linux-gnu/libicui18n.so.52 (0x00007fdd26ed9000)
	libicuuc.so.52 => /usr/lib/x86_64-linux-gnu/libicuuc.so.52 (0x00007fdd26b60000)
	libtesseract.so.4 => /usr/local/lib/libtesseract.so.4 (0x00007fdd26335000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdd26030000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdd25e1a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdd25a51000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdd2574a000)
	libicudata.so.52 => /usr/lib/x86_64-linux-gnu/libicudata.so.52 (0x00007fdd23edd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdd23cd9000)
	liblept.so.5 => /usr/local/lib/liblept.so.5 (0x00007fdd2386d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdd2364f000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fdd23440000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559b94c27000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fdd23226000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fdd23000000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fdd22dab000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fdd22b37000)
	libwebp.so.5 => /usr/lib/x86_64-linux-gnu/libwebp.so.5 (0x00007fdd228df000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fdd226bc000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007fdd224ae000)

**Comment by srdg** [comment]
@Shreeshrii I got it, thanks for the clarification. You have been a huge help! Closing the issues.

**Comment by srdg** [comment]
@Shreeshrii sorry to bother again, could you provide even a crude list of things that might cause the error `"Compute CTC Targets failed!"` ? I'm pretty sure my `.lstmf` files were generated correctly, since Tesseract trains itself when I add the LSTM layers in the `net-spec`, however, the error pops up as soon as I remove the same and implement only ConvLayers and Fully Connected ones. Any idea what might be causing this?

**Comment by Shreeshrii** [comment]
Sorry, no idea. I don't think Ray has mentioned much about this in the wiki.

**Comment by amitdo** [comment]
Tesseract 4 was design to use LSTM. I don't think CNN only will work.

From the wiki:

## VGSL Specs - rapid prototyping of mixed conv/LSTM networks for images

Variable-size Graph Specification Language (VGSL) enables the specification of a neural network, composed of convolutions and LSTMs, that can process variable-sized images, from a very short definition string.

**Comment by srdg** [comment]
@Shreeshrii @amitdo okay, maybe I have to do a workaround. Could you point me to the architectures that were used to generate the initial `.traineddata` files? I saw it somewhere, but lost the link. The architectures were used in the alpha version, if I remember correctly.

**Comment by Shreeshrii** [comment]
For tessdata_best the network spec is as part of version string in most
files.

For tessdata_fast I added the info to a wiki page. Look under data files
for 4.0.

Ray's emailed comment had specs for tessdata_best also but that part was
truncated.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files-in-tessdata_fast

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/issues/1404#issuecomment-374680492

Ray's comment, attached file has the network specs
