### ISSUE TITLE
tesseract help VS2013 help

### ISSUE THREAD

**Issue by tvrajja** [tesseract-ocr/tesseract#168]
Hi 
I am interested your OCR and quite impressive. I planning to use in VS2013 (web & windows applications). I saw the example VS2013 Soultions (Tesseract.ConsoleDemo & Tesseract.WebDemo) and working fine for plain tiff and it is not working PDF, also i want to read the attached pdf OCR? how to do ? where to start? please guide me.

[sample.pdf](https://github.com/tesseract-ocr/tesseract/files/58849/sample.pdf)

I am used VISUAL STUDIO 2013 FRAME WORK 4.5

thanks
Raja

**Comment by zdenop** [comment]
See [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice) - use tesseract forum for suppoprt.
