### ISSUE TITLE
Uncaught assertion error (lstm_recognizer_->DeSerialize(&fp))

### ISSUE THREAD

**Issue by wehrstedt** [tesseract-ocr/tesseract#1680]
### Environment

* **Tesseract Version**: 
```tesseract --version   
tesseract 4.00.00alpha
 leptonica-1.74.1
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.5.0) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0
```
* **Platform**: Windows 64 Bit

Installed tesseract using [this](http://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-4.00.00dev.exe) installer
### Current Behavior:
Running the following command, everything works fine
```
> tesseract image.jpg outFile
```

If I pass a language, in my case german, I get the following error:
```
> tesseract image.jpg outFile -l deu

lstm_recognizer_->DeSerialize(&fp):Error:Assert failed:in file ../../../../ccmain/tessedit.cpp, line 193
```

The following languages are installed
```
> tesseract --list-langs

deu
deu_frak
eng
equ
osd
```

If I pass any other language except "deu", it works. But then the text recognation failed for my image, because the question contains a german specail char "ß" which will be recognized as a "B" if I use other languages.

### Expected Behavior:
No error.

### Suggested Fix:
Maybe the error has something to do with the special char? Howevere, here's the image I try to process:
![1_question](https://user-images.githubusercontent.com/27811714/41547588-e0aacefa-7320-11e8-9b84-03b56152c3d6.jpg)

**Comment by stweil** [comment]
That's identical to `tesseract-ocr-setup-4.0.0dev-20170510.exe`, so a version which is more than a year old. Please don't report issues for such old versions – they don't work with current traineddata files, and they contain several known bugs.

See https://github.com/UB-Mannheim/tesseract/wiki for current versions.

**Comment by stweil** [comment]
Tesseract has no problems with the image and `-l deu` (from `tessdata`, `tessdata_best` or `tessdata_fast`). It also works with `-l script/Latin` from `tessdata` or `tessdata_best`, but the result from `tessdata_fast` is really bad, so bad that I wonder whether it is a good idea using `tessdata_fast` for Debian / Ubuntu.

**Comment by wehrstedt** [comment]
ok, with the version you provided it works. Didn't know that the version I installed is that old. Thanks!
