### ISSUE TITLE
text2image fails to generete box file when enable --find_fonts, not supported on multilingual text

### ISSUE THREAD

**Issue by Layneww** [tesseract-ocr/tesseract#1685]
### Environment

* **Tesseract Version**: 
tesseract 4.00.00alpha
 leptonica-1.74.4
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8

 Found AVX2
 Found AVX
 Found SSE

* **Commit Number**: 
* **Platform**: 
ubuntu 16.04
Linux <my_container_id> 4.4.0-97-generic # 120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
### Current Behavior:
I first tried
```
training/text2image --font='Microsoft Sans Serif' --text /data/dataset/tha+eng/txt/0.txt --outputbase /data/dataset/tha+eng/0 --max_pages=1 --box_padding=2 --ptsize=10  --underline_continuation_prob=0.1  --fonts_dir=/usr/share/fonts  --min_coverage 0.9
```
It gives both tif and box files.

Because my text file is a mixture of 2 different languages, I enable the ```--find_fonts``` to find the fonts that are available for rendering. So I tried
```
training/text2image --find_fonts  --text /data/dataset/tha+eng/txt/0.txt --outputbase /data/dataset/tha+eng/0 --min_coverage 0.9 --max_pages=1 --box_padding=2 --ptsize=10  --underline_continuation_prob=0.1  --fonts_dir=/usr/share/fonts
```
Then it only gives one output, 0.Microsoft Sans Serif.tif, which means it only renders for 1 font and has no output for box file.
I also tried on english-only text using the same --find_fonts flag, and it has the same problem.

Another problem is when I tried to render for a file with 3 languages, using ```--find_fonts```, it returns
```
Stripped 1 unrenderable words
Microsoft Sans Serif : 276 hits = 96.50%, raw = 85 = 89.47%
Rendered page 0 to file /data/dataset/tha+eng+zho/0.Microsoft_Sans_Serif.tif
```
When I tried with ```--fonts=Microsoft Sans Serif```, it returns:
```
Stripped 1 unrenderable words
Rendered page 0 to file /data/dataset/tha+eng+zho/0.tif
Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!
```
### Expected Behavior:
Give multiple tif.box pairs in different fonts
### Suggested Fix:
It is hard to find fonts which support 3 languages from different writing system. Any chance to provide a function which can render on whatever fonts available on each language text?

**Comment by Shreeshrii** [comment]
You have to do it as two steps.

Use findfonts to get a list of fonts.

Then use that list for making box/tiff pairs.

I have found with using multiple languages that sometimes a page may have no text in a language, the process fails for that font then.

**Comment by Layneww** [comment]
- I  tried using ```--find_fonts --render_per_font=false``` for an English text file, it only returns one font that is available, which is the first available font the program finds.
- The current solution to multilingual text is just to get a font that works for both languages right?

**Comment by Shreeshrii** [comment]
Arial Unicode MS, Noto Sans etc may have multiple language support.

For multilingual text, you can also create box/tiff/lstmf separately for each language also. Then train with all three - lang1, lang2 and lang1+lang2. That way you can get support for more fonts.

You will need to modify the training_files.txt to have links to all the .lstmf files.

**Comment by Shreeshrii** [comment]
I use the following command to get a list of fonts. Change the directory and file names.

```
nice text2image --find_fonts \
--fonts_dir ./.fonts \
--text ./langdata/ara/ara.diacritics.training_text \
--min_coverage 0.99975 \
--render_per_font=false \
--outputbase ./langdata/ara/ara \
|& grep raw \
 | sed -e 's/ :.*/@ \\/g' \
 | sed -e "s/^/  '/" \
 | sed -e "s/@/'/g" > ./langdata/ara/ara.diacritics.fontslist.txt
```

**Comment by Layneww** [comment]
Thanks for your explanation.
The find_fonts issue is still not solved. I cannot automatically get the tiff/box files for all available fonts via one command. It did not return a list of fonts.

**Comment by Layneww** [comment]
Thanks! It's really helpful.

**Comment by Shreeshrii** [comment]
tesseract 4.00.00alpha

You should upgrade to latest version.

**Comment by Layneww** [comment]
I'm upgrading to tesseract beta version (master branch). I found that text2image does not give good box output sometimes. How does tesseract 4.0.0beta generate the box/tiff pairs? I look into the tesstrain.sh, then combine_lang_model, but could not find the command that actually generate the pairs. 
If putting txt files in the langdata directory, will tesseract generate multiple tiff/box files from each txt files?

**Comment by Layneww** [comment]
UPDATE: I figured out why the text2image doesn't work. It's because of the version issue (Thanks for your advice! @Shreeshrii ). Now my question remain is for a new image, how to generate the box file to pass into the lstm model?

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00---Finetune

The scripts at wiki.wareya.moe are modified to use multiple text files as input.

**Comment by Layneww** [comment]
@Shreeshrii How should I get the preprocessing (page layout) result for the lstm model when taking in a new image for recognition? I tried ```batch.nochop makebox```, the box file didn't give good bounding box for each character.

**Comment by Layneww** [comment]
- Why does the input of the training data for LSTM is character-based?
- LSTM is line-based. Does it mean during the training, it takes the whole line as input to the model? From my understanding, the input should have some windows moving along the textline, which means the segmentation of the textline is involced. What would be the ground truth for each of the LSTM node?

**Comment by amitdo** [comment]
See  https://github.com/tesseract-ocr/tesseract/issues/1276

**Comment by Shreeshrii** [comment]
Sorry, I do not know about the internal processing regarding LSTM to answer your questions. You will have to look at the code.

The tesstrain.sh script calls text2image, the box files created by it have the spaces/tabs and are used to further generate the lstmf files.

jtessboxeditor can be used to put tabs for EOL in makebox generated box files, but it does not have a facility to add interword spaces.

Another alternative is the ocrd-train project, But that handles one line images only and creates box files based on ground truth.

**Comment by amitdo** [comment]
>Why does the input of the training data for LSTM is character-based?

For some scripts (e.g. Devanagari) the basic unit of training may contain more than one character.
