### ISSUE TITLE
Arabic Language output is reversed

### ISSUE THREAD

**Issue by christophered** [tesseract-ocr/tesseract#169]
Hi there,
I have created my own Arabic Language traindata, but the problem is that when used it gives the recognized text reversely (opposite direction), noting that the Arabic and Hebrew languages are written and read from Right to left handside (RTL).
People keep implying to use Cube for training Arabic, but I think no one really knows how to use Cube for training, and yes I have read the tesseract extra Cube documentation, and it seems that they purposely don't want anyone to use Cube.
How can I make a tesseract traineddata that recognize RTL languages as Arabic correctly?
Waiting for your reply

**Comment by amitdo** [comment]
Hi @christophered,

How did you generate the tif images for training? Did you use the text2image tool?

From https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#dictionary-data-optional

> For right-to-left languages (RTL) use option "-r 1".

You can also try to use tesstrain.sh
https://github.com/tesseract-ocr/tesseract/wiki/tesstrain.sh

In general, the right place to ask questions like these is here:
http://groups.google.com/group/tesseract-ocr

See also:
http://groups.google.com/d/topic/tesseract-ocr/HdT8V1nFTtYJu

**Comment by christophered** [comment]
I have just used the "wordlist2dawg -r 1" and it's has solved my "reversed words" problem.
But now I have a new problem, the recognized text are combined together, meaning the words have no spacing between them. Does tesseract recognize all as 1 word?
waiting for reply

**Comment by amitdo** [comment]
Try using this config file:
 https://github.com/tesseract-ocr/langdata/blob/master/ara/ara.config

Remove this line:
> tessedit_ocr_engine_mode 1

**Comment by christophered** [comment]
The problem has been solved! Thanks to the user (amitdo) The solution was:
To use "wordlist2dawg.exe -r 1" to create the "freaquent_words_list" + "words_list"
To use "ara.config" and removing this line from it "tessedit_ocr_engine_mode 1"

This solved my 2 problems of Arabic Language reversed words, and Arabic Language combined word.
Thank you

**Comment by lisaied** [comment]
Hello,

I'm facing the same problem, I spent long time trying to solve this issue.
Can you provide me the steps you did to solve this or can you share the fix arabic lanuage files.

Thanks a lot,
Loai.

**Comment by lisaied** [comment]
I used wordlist2dawg.exe to and ara.cube-word-dawg is generated, but eventually I don't know what's the next step.

**Comment by roozgar** [comment]
@christophered 
did you get any good results by training? my best accuracy is about 40-50% on 300 dpi scanned document

**Comment by christophered** [comment]
roozgar, I will conduct some tests and will reply back after couple of days

**Comment by roozgar** [comment]
@christophered 
i tried to find official Arabic resources to make up a better train file but not lucky 
so
if you need i can help you by providing Arabic words list or some scanned page 
just send me an email: roozgar@gmail.com

**Comment by christophered** [comment]
Thank you roozgar.
I am currently conducting some tests on Arabic Tesseract and I am exhausting all resources available to me to make sure finding the best method for arabic recognition.
Don't worry I will conduct some tests and reply back to you ( by GOD)
By-the-way send me the scanned Arabic Document that you've been testing the accuracy on.
waiting for your reply

**Comment by roozgar** [comment]
@christophered 
sure
please tell me your email address

**Comment by christophered** [comment]
christopher.edward@outlook.com

**Comment by christophered** [comment]
I have tested tesseract 3.02+3.04+3.05dev all have failed in arabic ocr.
Some-how I got the feeling that Arabic Language was purposely neglected and rejected.

**Comment by roozgar** [comment]
@christophered do you have any plan to work more on this subject?!
the official train data for arrabic in working really good on 'times' font
so i think its possible to have a good accuracy other fonts too!

**Comment by amitdo** [comment]
The official trained data use the cube engine. There is no documented way to train cube with other fonts.

**Comment by roozgar** [comment]
@amitdo Oops! i found this

https://code.google.com/archive/p/tesseract-ocr-extradocs/wikis/Cube.wiki

its really undocumented!!
but how thay build current Arabic file!!

**Comment by amitdo** [comment]
I suppose they have a program for that task...

**Comment by roozgar** [comment]
@amitdo who are they? i there any way to find who build each trained file?

**Comment by amitdo** [comment]
Developers from Google. The guy who wrote 'Cube' code left Google years ago.

See here what Ray Smith said about 'Cube'.
https://github.com/tesseract-ocr/tesseract/issues/238

**Comment by areebakamil** [comment]
@christophered 
hey christopher, can you please tell me how you created your own .traineddata file for arabic or send me a link that contains a tutorial that i can use to follow.
I have been trying to implemented Tresseract ara.traineddata file but for some reason, the app gets stuck

**Comment by christophered** [comment]
Hi @areebakamil  I have replyed by email also here is the Tutorial that you requested.
https://www.youtube.com/watch?v=vohgRChtRck

also here is one method to improve the recognition, just for testing
https://www.youtube.com/watch?v=tLJvHWhX_JA

**Comment by Shreeshrii** [comment]
@christophered 
How do you take into account the different forms - isolated, initial, medial and final forms of the same letter, during training?

[https://tsl620atnaz.wikispaces.com/file/view/arabic.gif/130745645/arabic.gif](url)

**Comment by christophered** [comment]
@Shreeshrii 
one of the methods that I use in training:
example:
Isolated: **(ك)**
Initial: (ك) then press "Shift j or ت" , so the result will be **( كـ)**
Medial: "Shift j or ت" , then press (ك), then "Shift j or ت"
Final: "Shift j or ت" , then press (ك)

**Comment by harinadhkota** [comment]
Hi , 
can you please provide me any version of tesseract-ocr which supports "Arabic " Language ,
I am tried with tesseract-ocr3.02 version ,
It is not supportng "Arabic " Language,
if any upgade  or downgrade versions supports "Arabic " language 
Please Let me know 

1) If any supported version is there "send me " tesseract-ocr " software and all supported configuration files as well
2) or else if download is available send me  "dowload link " to "saimuralikrishna005@gmail.com "
3) In case if required please  provide to my business mail id : "saikrishna.yalakala@wissen.com "
send me mail "saimuralikrishna005@gmail.com"

**Comment by usharf** [comment]
@amitdo should this work for hebrew as well? Do I need to create training data myself (i.e.  "freaquent_words_list" + "words_list" etc)?


10x

**Comment by amitdo** [comment]
Hi Uri !

There is a tessdata package for Hebrew.
https://github.com/tesseract-ocr/tesseract/wiki/Data-Files

Try to use it before you start training Hebrew.

Also, read this page:
https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

>should this work for hebrew as well?

By 'this' you mean

1) 'Tessseract' ?
Yes. Tessseract supports Hebrew.
The provided tessdata does not supports Hebrew diacritics (nikud).

2)
>From https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#dictionary-data-optional
>For right-to-left languages (RTL) use option "-r 1".

Yes, it should be used for Hebrew too.

If you have further questions please use the [forum](https://groups.google.com/d/forum/tesseract-ocr) (I'm not participating there).

For Hebrew OCR questions / discussions you can also try here:
https://github.com/amitdo/Hebrew-OCR-Discussions

**Comment by usharf** [comment]
@amitdo thank you very much! I will go through you suggestions.
I meant should the solution for Arabic reverse output should apply for Hebrew as well. 
One of the participants mensons reversing the strings int the training data, wasn't sure if this is somethng I need to do...?

**Comment by adinetoiu** [comment]
Hi, 
I am also having problems with tesseract OCR for arabic and i need your help.

Can you please send me a trained data file for arabic language for tesseract 3.0.2?
My email is adinetoiu@yahoo.com.

Thank you in advance,
Adrian

**Comment by christophered** [comment]
@adinetoiu I suggest that you skip using Tesseract 3.x for Arabic, instead use Tesseract 4.
a binary is also available at [http://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-4.00.00dev.exe](http://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-4.00.00dev.exe)

**Comment by adinetoiu** [comment]
Thank you very much!

**Comment by adinetoiu** [comment]
Do you have a sample project or link that uses tesseract 4?

**Comment by Shreeshrii** [comment]
Both gimagereader and vietocr have versions which use tesseract 4.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by christophered** [comment]
@adinetoiu I have contacted the developer of jtessboxeditor, he stated that it might take time until we see an automated lstm trainer, until then, you must train manually.
secondly, the steps and examples are available in the Wiki along with some test box files.
Note: please edit your replies and leave only your replies, your adding unrequired information.
`From: chris <notifications@github.com` ......... delete that

**Comment by nsoud** [comment]
hello man, please can you send me the ara.traineddata so i can test it, i don't know how to train iOS tesseract 3.x to recognize arabic in a great way?
also is  tesseract 4 made for iOS , i didn't find an example for iPhone or iPad with tesseract 4, and also if there is one how can i update me old tesseract with the new one. thank you very much

**Comment by moeneqbal** [comment]
hello every one, i have a issue in urdu language data, any expert here who can help me please mail me.
My email is moen.eqbal@gmail.com
