### ISSUE TITLE
RFC: Use GitMate to detect related issues for all tesseract-ocr projects?

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#1693]
GitMate.io is a tool which automatically tries to detect duplicate or related issues. Here is its output for tesseract-ocr/tesseract: https://gitmate.io/report/http:%2F%2Fgithub.com%2Ftesseract-ocr%2Ftesseract%2F.

The tool can automatically handle all issues for one or more projects on GitHub, but must be given some permissions by the project administrators (@zdenop, @egorpugin).

Maybe it would help if GitMate would watch all projects on https://github.com/tesseract-ocr/. I suggest to try that.

**Comment by sils** [comment]
Hi, I'm one of the founders of GitMate, if you have any questions to help you figure something out just let us know :)

**Comment by stweil** [comment]
Thank you for your offer, @sils. See the comment for #1695: "Nice idea, but seems to produce a lot of noise."

**Comment by amitdo** [comment]
We tried it. It didn't work well.

**Comment by stweil** [comment]
Indeed, I close this issue therefore. @sils, if there are newer versions of GitMate we can give it a new try.
