### ISSUE TITLE
Unable to Differentiate between close look like letters 

### ISSUE THREAD

**Issue by engahmed1190** [tesseract-ocr/tesseract#1695]
### Environment

```
tesseract 4.0.0-beta.1-370-g8b64
 leptonica-1.76.0
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8
 Found AVX2
 Found AVX
 Found SSE
```

* **Platform**:` Linux ubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### Current Behavior:
I would like to recognize the below image correctly. I am using the last eng.traineddata that failed to detect the difference between **Z** and **2**

![top_1](https://user-images.githubusercontent.com/25582838/41740389-28d5caee-7598-11e8-9d06-e9802c4f6ae1.png)

I have tried the following configuration --psm 6 --oem 0,1,2 
### Expected Behavior:
The letter to be recognized correctly 
### Suggested Fix:

retrain eng.traineddata on the miss-recognized letters

**Comment by zdenop** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by zdenop** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/tesseract-ocr/tesseract/issues/438 (Please close milestones for 3.04), https://github.com/tesseract-ocr/tesseract/issues/1341 (Groups of letters are being interpreted as one single letter when too close together), https://github.com/tesseract-ocr/tesseract/issues/147 (Unable to parse cyrillic), https://github.com/tesseract-ocr/tesseract/issues/1580 (Unable to detect text from button from image), and https://github.com/tesseract-ocr/tesseract/issues/1224 (Unable to build from 4.00.00 releases).

**Comment by amitdo** [comment]
About this GitMate...

Nice idea, but seems to produce a lot of noise.

**Comment by zdenop** [comment]
I turn it off. I was not aware is started to post comments..

**Comment by christophered** [comment]
@engahmed1190 please provide more information:
Did you use `tessdata_best` or `tessdata_fast`?
Is this the entire image that you are trying to recognize? if not, please provide the entire image.

**Comment by engahmed1190** [comment]
@christophered 
I use this https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata
also this is the output [out.txt](https://github.com/tesseract-ocr/tesseract/files/2127888/out.txt)
and command used `tesseract top_1.png out --psm 6 --oem 1`
finally i see this warning` Warning. Invalid resolution 0 dpi. Using 70 instead.`

**Comment by christophered** [comment]
@engahmed1190 here are the results:
[tessdata_fast](https://github.com/tesseract-ocr/tessdata_fast/blob/master/eng.traineddata) 63Z2
[tessdata_best](https://github.com/tesseract-ocr/tessdata_best/blob/master/eng.traineddata) 6372
[Latin.traineddata](https://github.com/tesseract-ocr/tessdata_best/blob/master/script/Latin.traineddata) 63Z2

My guess is that, the file that you were using is actually based on the tessdata_best, but was converted and integerized to a fast model, bywhich it's size was reduced and it's recognition rate.

For your situation, you can use tessdata_fast & Latin.traineddata from the best scripts (links are provided).
Also you can finetune the tessdata_best if you wish.

**Comment by christophered** [comment]
@zdenop close this topic.
