### ISSUE TITLE
Windows build unavailable

### ISSUE THREAD

**Issue by jacool** [tesseract-ocr/tesseract#171]
The wiki page states "An installer is available for Windows from our download page." The statement is incorrect since there in no Windows installer available from the said page.

**Comment by stweil** [comment]
See #101 which handles the same issue. Maybe you want to try the installer from https://github.com/UB-Mannheim/tesseract/wiki.

**Comment by amitdo** [comment]
The [Downloads](https://github.com/tesseract-ocr/tesseract/wiki/Downloads) wiki page has a link to  [Former project page](https://code.google.com/p/tesseract-ocr/downloads/list) under 'Old Downloads'.

There, you can find Windows installer for tesseract 3.02. There is no **official** Windows installer for later versions.

You can build on Windows the latest version from source.
The wiki has a link to [Releases](https://github.com/tesseract-ocr/tesseract/releases)

Still, the wiki needs to be more clear on this.

**Comment by jacool** [comment]
Yes, a clear Wiki message like "no Windows artifacts for current versions of Tesseract will be provided in the project" would clarify the situation.

**Comment by amitdo** [comment]
I hope it clearer now.
https://github.com/tesseract-ocr/tesseract/wiki/Downloads

**Comment by amitdo** [comment]
@zdenop please close this issue.
