### ISSUE TITLE
Training tesseract 4 with images instead of font

### ISSUE THREAD

**Issue by mhdsRahnama** [tesseract-ocr/tesseract#1710]
Hello.
I have some questions about making tiff/box files for tesseract 4.
In TrainingTesseract 4.00 document  written:
“ Making Box Files
As with base Tesseract, there is a choice between rendering synthetic training data from fonts, or labeling some pre-existing images (like ancient manuscripts for example).”
but it did not explain how to train with pre-existing images.
I want to train  Persian language in tesseract 4 (lstm). I have some images from ancient manuscripts and I want to train with images and texts instead of font.  So I can’t use text2image command. I know that the old format box files will not work for LSTM training. 
1-How can I make tif/box for tessearct 4 lstm then labeled them and how to change tesseract commands? 
2-should I use another tools for generate box file (Given that Persian language is right to left )?
3-should I train Fine Tuning or From Scratch?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by Shreeshrii** [comment]
Try https://github.com/OCR-D/ocrd-train
