### ISSUE TITLE
Newbie needs help

### ISSUE THREAD

**Issue by rcetrangolo** [tesseract-ocr/tesseract#172]
Hello.

My goal is simple, I need to extract the identification number from id photos.
I run tesseract and it

![20151211_105843](https://cloud.githubusercontent.com/assets/6429534/11748020/f8484ef8-a004-11e5-9fdf-bc658e13390e.png)

 recognizes only the last surname but I need to get the number (the photo is attached).

Could you please help me?

Thank you very much

**Comment by zdenop** [comment]
Use tesseract forum for asking help https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice
