### ISSUE TITLE
Segmentation fault: tesseract -c hocr_font_info=T hocr 

### ISSUE THREAD

**Issue by vov4ik829** [tesseract-ocr/tesseract#174]
When I run "tesseract -c hocr_font_info=T hocr"  on attached file the segmentation fault is received. Output file is empty.
But when I run "tesseract hocr" on the same file without "-c hocr font_info=T", the recognition runs as expected, without any errors.
![1050103_world-markets-at-a-glancepp](https://cloud.githubusercontent.com/assets/8905596/11893647/bf069384-a58b-11e5-8283-7e1fc75600f9.jpeg)

**Comment by amitdo** [comment]
> tesseract issue174.jpg issue174 -c hocr_font_info=T hocr

This works with the latest commit in the repo.  No segfault.

**Comment by vov4ik829** [comment]
I was using stock ubuntu 14.10 version. Build from repo and solved. Thank you!

**Comment by amitdo** [comment]
@vov4ik829
Ubuntu 14.10 had reach EOL. You should upgrade the distro.

**Comment by vov4ik829** [comment]
Oh, I mean 15.10, you're right.
