### ISSUE TITLE
Public key for tesseract-4.00~git2686-1.1.x86_64.rpm is not installed

### ISSUE THREAD

**Issue by gitscamI** [tesseract-ocr/tesseract#1749]
I install tesseract on centos 7 by the following commands:
yum-config-manager --add-repo https://download.opensuse.org/repositories/home:/Alexander_Pozdnyakov/ScientificLinux_7/
yum update
yum install tesseract 
yum install tesseract-langpack-deu

the command"yum install tesseract "" show the error informatio:
Downloading packages:
warning: /var/cache/yum/x86_64/7/download.opensuse.org_repositories_home_Alexander_Pozdnyakov_CentOS_7_/packages/tesseract-4.00~git2686-1.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID ad8883f8: NOKEY

Public key for tesseract-4.00~git2686-1.1.x86_64.rpm is not installed

Help please!

**Comment by zdenop** [comment]
We do not provide binary packages. Please report issue to packager

**Comment by Patataman** [comment]
You can skip the key check using the --nogpgcheck flag ;)

**Comment by Drivible** [comment]
> --nogpgcheck

Ohh that helped a lot for my current build script. Thank you!

**Comment by Drivible** [comment]
> nogpgcheck

I use the following:

```
sudo yum-config-manager --add-repo http://download.opensuse.org/repositories/home:/Alexander_Pozdnyakov/RHEL_7/
sudo yum update -y
sudo yum install tesseract -y --nogpgcheck
```
