### ISSUE TITLE
The Billion Word Arabic Corpus

### ISSUE THREAD

**Issue by christophered** [tesseract-ocr/tesseract#1764]
Hi there,
In an effort to improve the Arabic language recognition model, I have decided to create a vast and diverse Arabic corpus gathered from the web.

A model needs to be trained but I am afraid that by using my modest computer resources it might take a long time. Thus, one of the Tesseract developers or contributors must step-in and create the model using the large training text that I am going to provide, so that it could be published in the official Tesseract tessdata repo.
@theraysmith @stweil @egorpugin @zdenop @jbreiden etc... 
**Anyone?**

**Comment by christophered** [comment]
Information about the corpus:
Gathered from the web using `wget` (news agencies, religious entities, wikipedia, etc...)
Extracted the text using `jusText`
Might work on removing the duplicate parts using `Onion`

**Comment by stweil** [comment]
See http://corpus.tools/ for the tools `jusText` and `Onion`.

**Comment by christophered** [comment]
@stweil who is responsible to create the `tessdata` ? so I could talk to.

**Comment by stweil** [comment]
The current `tessdata` files were initially created by Ray Smith, and some of them were later modified by community contributors (see Git history).

I think the right place to discuss the matter is the [Tesseract developer forum](http://groups.google.com/group/tesseract-dev) or here.

**Comment by rmarji** [comment]
@christophered let me know how I can help with this, I'm a native Arabic speaker and I have done NLP work with it before.

**Comment by christophered** [comment]
@rmarji what are your computer specs?

**Comment by christophered** [comment]
@stweil @amitdo @zdenop Which network specification do you suggest to use in training?

**Comment by christophered** [comment]
closed for no interest

**Comment by naourass** [comment]
No interest YET you mean...
