### ISSUE TITLE
read_params_file: parameter not found: Date:

### ISSUE THREAD

**Issue by loralyc** [tesseract-ocr/tesseract#1771]
Tesseract Version: tesseract 4.00.00beta
Platform: Ubuntu 14.04
hi，i run the same command as before , but now it had some porblems. i can't understand why it happen ,would you mind give me some suggestions. Thank you very much.
`bash training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only --noextract_font_properties --tessdata_dir ../tessdata --langdata_dir ./langdata --output_dir ./tesstutorial/FZSTK/train --fontlist "Arial" --exposures "0"
`
`=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=../tessdata
[2018年 07月 10日 星期二 10:29:00 CST] /usr/local/bin/tesseract /tmp/tmp.HY57m4AN7Y/eng/eng.Arial.exp0.tif /tmp/tmp.HY57m4AN7Y/eng/eng.Arial.exp0 lstm.train
read_params_file: parameter not found: Date:
ERROR: /tmp/tmp.HY57m4AN7Y/eng/eng.Arial.exp0.lstmf does not exist or is not readable
`

**Comment by Shreeshrii** [comment]
Please try with latest beta version.

**Comment by loralyc** [comment]
@Shreeshrii  i am sorry. i made a wrong. it is already latest beta version.

**Comment by Shreeshrii** [comment]
>i run the same command as before , but now it had some porblems

What change have you made?

different machine?
different o/s?
different version?
??

**Comment by loralyc** [comment]
nothing. it must the same machine,the same o/s, the same version. and i remember i haven't change any code . is it possible that i lost some important files?

**Comment by loralyc** [comment]
sorry. i already found the reason. I made a  mistake in a file.
