### ISSUE TITLE
how to detect  continuous underline by tesseract 4?

### ISSUE THREAD

**Issue by ospf99** [tesseract-ocr/tesseract#1772]
Tesseract Version: tesseract 4.00.00alpha
  Platform:  centos 6.5
 Current Behavior:   text of image:   You're a student, go _ to ______ school.
                                detect text:  You're a student, go _ to school.
 Expected Behavior:  detect coninuous underline: You're a student, go _ to _______ school.
![my](https://user-images.githubusercontent.com/39789546/42493887-30e8fb8a-8451-11e8-9eac-bb38e25d53e4.png)

**Comment by amitdo** [comment]
This feature is not supported. #251.
