### ISSUE TITLE
pkg-config file broken in beta3

### ISSUE THREAD

**Issue by jeroen** [tesseract-ocr/tesseract#1773]
In Tesseract 3 and also Tesseract 4 up till beta2 we would see:

```sh
pkg-config --cflags tesseract
# -I/usr/local/opt/tesseract/include/tesseract -I/usr/local/opt/leptonica/include/leptonica
```

However as of Tesseract beta 3 we get:

```sh
pkg-config --cflags tesseract
#-I/usr/local/opt/tesseract/include -I/usr/local/opt/leptonica/include/leptonica
```

As a result existing applications that rely on this fail to find the headers:

```cpp
In file included from RcppExports.cpp:4:
./tesseract_types.h:1:10: fatal error: 'baseapi.h' file not found
#include <baseapi.h>
         ^~~~~~~~~~~
1 error generated.
```

Is this intended?

**Comment by stweil** [comment]
It is intended: You now have to write `#include <tesseract/baseapi.h>`.

This change was required to get unique names for the include statements.

**Comment by jeroen** [comment]
Oh no that will break everything 🙈

Is there a trick to write an application that will compile both with the previous and new structure?

**Comment by stweil** [comment]
Typically the new variant will also work with old Tesseract.

**Comment by jeroen** [comment]
Hmm the file `params.h` also has disapppeared?

**Comment by amitdo** [comment]
It's still there:
https://github.com/tesseract-ocr/tesseract/blob/master/src/ccutil/params.h

**Comment by egorpugin** [comment]
> Is there a trick to write an application that will compile both with the previous and new structure?

Pass an additional include dir to compiler. `-Iusr/local/opt/tesseract/include/tesseract` or somthing like this.

**Comment by jeroen** [comment]
@egorpugin it's hard to automate that because the include dir is generated by pkg-config...

**Comment by jeroen** [comment]
@amitdo the `params.h` header is no longer installed with Tesseract 4 beta.3:
```
Jeroens-MacBook-Pro:~ jeroen$ ls -l /usr/local/Cellar/tesseract/HEAD-ba757a4/include/tesseract/
total 1176
-rw-r--r--  1 jeroen  admin    1356 Jul 10 11:43 apitypes.h
-rw-r--r--  1 jeroen  admin   36681 Jul 10 11:43 baseapi.h
-rw-r--r--  1 jeroen  admin   23598 Jul 10 11:43 capi.h
-rw-r--r--  1 jeroen  admin   37193 Jul 10 11:42 genericvector.h
-rw-r--r--  1 jeroen  admin    6700 Jul 10 11:42 helpers.h
-rw-r--r--  1 jeroen  admin    1711 Jul 10 11:42 host.h
-rw-r--r--  1 jeroen  admin    9643 Jul 10 11:43 ltrresultiterator.h
-rw-r--r--  1 jeroen  admin    8363 Jul 10 11:42 ocrclass.h
-rw-r--r--  1 jeroen  admin   15187 Jul 10 11:43 pageiterator.h
-rw-r--r--  1 jeroen  admin    2162 Jul 10 11:42 platform.h
-rw-r--r--  1 jeroen  admin   12379 Jul 10 11:42 publictypes.h
-rw-r--r--  1 jeroen  admin    9061 Jul 10 11:43 renderer.h
-rw-r--r--  1 jeroen  admin    9399 Jul 10 11:43 resultiterator.h
-rw-r--r--  1 jeroen  admin    4146 Jul 10 11:42 serialis.h
-rw-r--r--  1 jeroen  admin    6807 Jul 10 11:42 strngs.h
-rw-r--r--  1 jeroen  admin    1173 Jul 10 11:43 tess_version.h
-rw-r--r--  1 jeroen  admin  360256 Jul 10 11:42 tesscallback.h
-rw-r--r--  1 jeroen  admin    7877 Jul 10 11:43 thresholder.h
-rw-r--r--  1 jeroen  admin    6508 Jul 10 11:42 unichar.h
```

**Comment by stweil** [comment]
If `params.h` is used by third party code like R, I'll have to add it again, so this is a regression which needs a fix.

**Comment by amitdo** [comment]
Do you need it?

**Comment by jeroen** [comment]
No I think I can just take it out, and publish a new release of the bindings. However users won't be able to use the current versions of the bindings with Tesseract >= 4.0.0 beta.3, but that's alright.
