### ISSUE TITLE
LDFLAGS='-static' getting overwritten during make

### ISSUE THREAD

**Issue by shawngong** [tesseract-ocr/tesseract#1775]
Hey, I am trying to build a static binary for tesseract using:
`./configure LDFLAGS='-static -static-libgcc -static-libstdc++'  --disable-openmp  --disable-graphics --disable-opencl`

It looks like the link output when running make says:
`-std=c++11 -static-libgcc -static-libstdc++ -o tesseract tesseract-tesseractmain.o`

There is no -static. 

Any tips on how to fix this, or on how to build a static binary?

Running ldd on the resulting binary shows that it has dynamically linked dependencies.

**Comment by amitdo** [comment]
`./configure --disable-shared`

**Comment by zdenop** [comment]
Please respect rules for posting issues.
