### ISSUE TITLE
exception when free memory

### ISSUE THREAD

**Issue by mengxiangdu** [tesseract-ocr/tesseract#1779]
### Environment
* **Tesseract Version**: 4.0.0 Beta1
* **Commit Number**: Unknown
* **Platform**: Windows 7, 64-bit. Visual Studio 2015 Pro

### Current Behavior:
This code occurs an exception when running at "delete[]charactors;". But the note says: The recognized text is returned as a char* which is coded as UTF8 and must be freed with the delete [] operator. code here.
![default](https://user-images.githubusercontent.com/41225168/42721363-27f78474-876c-11e8-94ee-3fd33d5c869e.png)

```
std::string recognizeImage(const IplImage *cutImage)
{
	cvCvtColor(cutImage, cutImage, CV_BGR2RGB);
	TessBaseAPI api;
	api.Init(0, "eng");
	api.SetImage((unsigned char*)(cutImage->imageData), cutImage->width, cutImage->height, cutImage->nChannels, cutImage->widthStep);
	char *charactors = api.GetUTF8Text();
	std::string str(charactors);
	delete[]charactors; // exception occurs!
	return str;
}

void main()
{
	const char path[] = "D:/lang.fontname.exp0.tif";
	IplImage *image = cvLoadImage(path);
	std::string text = recognizeImage(image);
	std::cout << text << std::endl;
	cvReleaseImage(&image);
	getchar();
}
```

**Comment by amitdo** [comment]
Call `api.End();` before the delete.

**Comment by mengxiangdu** [comment]
i have tried, but it doesn't work.
