### ISSUE TITLE
tess-two lib accuracy

### ISSUE THREAD

**Issue by vikas34338** [tesseract-ocr/tesseract#178]
Hi all,

I am working on the OCR based android application which loads the image from gallery or photo click from phone's camera. All went well using the tess-two lib. However, the accuracy of reading the text from the image is very poor. Quality of photos are good(8 megapixel camera) and whereas, other application on stores read them much better.

Could you please suggest me how can I improve the accuracy.

Thanks,
Vikas Yadav

**Comment by zdenop** [comment]
[FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice) : If you found a bug - please create an issue: Please make sure you are able to replicate the problem with tesseract executables on Linux or Windows. For other platforms or external/your programs (including tesseract wrappers) please use the tesseract forums.
