### ISSUE TITLE
Cannot continue from _checkpoint

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1782]
Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-122-generic ppc64le)

 tesseract -v
tesseract 4.0.0-beta.3-180-gab1f
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0

and

Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-130-generic x86_64)

 tesseract -v
tesseract 4.0.0-beta.3-199-gba757
 leptonica-1.76.0
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.0 : libopenjp2 2.3.0

----------------------
```
At iteration 4988/5000/5000, Mean rms=3.855%, delta=17.627%, char train=75.487%, word train=98.179%, skip ratio=0%,  wrote checkpoint.

Finished! Error rate = 54.122
shree@sanskrit:~/tesseract-ocr/tesseract$ lstmeval \
>   --model ../tesstutorial/engoutput/base_checkpoint \
>   --traineddata ../tesstutorial/engtrain/eng/eng.traineddata \
>   --eval_listfile ../tesstutorial/engeval/eng.training_files.txt
../tesstutorial/engoutput/base_checkpoint is not a recognition model, trying training checkpoint...
Loaded 72/72 pages (1-72) of document ../tesstutorial/engeval/eng.Impact_Condensed.exp0.lstmf
Deserialize failed
```

```
~/tesseract-ocr/tesseract$ lstmtraining \
>   --model_output ../tesstutorial/impact_from_small/impact \
>   --continue_from ../tesstutorial/engoutput/base_checkpoint \
>   --traineddata ../tesstutorial/engtrain/eng/eng.traineddata \
>   --train_listfile ../tesstutorial/engeval/eng.training_files.txt \
>   --max_iterations 1200
Loaded file ../tesstutorial/engoutput/base_checkpoint, unpacking...
Failed to continue from: ../tesstutorial/engoutput/base_checkpoint
```

Continue_from is NOT working currently from _checkpoint, however it works from the numbered checkpoints.

This seems to be a result of some recent commits, as this used to work before.

**Comment by Shreeshrii** [comment]
tesseract$ tesseract -v
tesseract 4.0.0-beta.2
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0


```
lstmeval \
>   --model ../tesstutorial/engoutput/base_checkpoint \
>   --traineddata ../tesstutorial/engtrain/eng/eng.traineddata \
>   --eval_listfile ../tesstutorial/engeval/eng.training_files.txt
../tesstutorial/engoutput/base_checkpoint is not a recognition model, trying training checkpoint...
Loaded 86/86 pages (1-86) of document ../tesstutorial/engeval/eng.Impact_Condensed.exp0.lstmf
Truth:any can't his Post with Send about 3G Video also 10 -- from | about 2007, data
OCR  :SM iis Paioh Smdopm S3Oitim 0 . bom | sou 10 tn
Truth:group April including just place 18 service Articles as could these Community to
```

**Comment by Shreeshrii** [comment]
tesseract -v
tesseract 4.0.0-beta.3
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0

```
 lstmeval \
>   --model ../tesstutorial/engoutput/base_checkpoint \
>   --traineddata ../tesstutorial/engtrain/eng/eng.traineddata \
>   --eval_listfile ../tesstutorial/engeval/eng.training_files.txt
../tesstutorial/engoutput/base_checkpoint is not a recognition model, trying training checkpoint...
Loaded 86/86 pages (1-86) of document ../tesstutorial/engeval/eng.Impact_Condensed.exp0.lstmf
Truth:any can't his Post with Send about 3G Video also 10 -- from | about 2007, data
OCR  :YWitio Poat Vih Sm op 2)8 Cion tin it - bPou ! tpom 0RD tm
Truth:group April including just place 18 service Articles as could these Community to
```

**Comment by Shreeshrii** [comment]
tesseract -v
tesseract 4.0.0-beta.3-131-g6d170
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0

lstmeval \
>   --model ../tesstutorial/engoutput/base_checkpoint \
>   --traineddata ../tesstutorial/engtrain/eng/eng.traineddata \
>   --eval_listfile ../tesstutorial/engeval/eng.training_files.txt
../tesstutorial/engoutput/base_checkpoint is not a recognition model, trying training checkpoint...
Loaded 86/86 pages (1-86) of document ../tesstutorial/engeval/eng.Impact_Condensed.exp0.lstmf
Truth:any can't his Post with Send about 3G Video also 10 -- from | about 2007, data
OCR  :

**Comment by Shreeshrii** [comment]
Tried with latest version

```
ubuntu@tesseract-ocr:~/tesseract$ time lstmeval \
>   --model ../tesstutorial/engoutput/base_checkpoint \
>   --traineddata ../tesstutorial/engtrain/eng/eng.traineddata \
>   --eval_listfile ../tesstutorial/engeval/eng.training_files.txt
../tesstutorial/engoutput/base_checkpoint is not a recognition model, trying training checkpoint...
Loaded 86/86 pages (1-86) of document ../tesstutorial/engeval/eng.Impact_Condensed.exp0.lstmf
Deserialize failed

```

**Comment by Shreeshrii** [comment]
@stweil Have you tried the tutorial? Is the problem reproducable or is it limited just to the POWER architecture?

**Comment by stweil** [comment]
I tried it now with the latest git version and get the same error when running `lstmeval`. Can you say when it worked last?

`basetrain.log` contains several warnings: `Warning: given outputs 111 not equal to unicharset of 110` and `Warning: LSTMTrainer deserialized an LSTMRecognizer!`.

Why does the training end with different error rates (54.122 / 8.957 in your runs, 99.592 in my test)?

**Comment by stweil** [comment]
An interesting result regarding the performance: the training took about 18 minutes (nearly an hour CPU time) in the default configuration (up to 4 threads). When running with a single thread, the duration increased to about 28 minutes which is also the CPU time, so running a single thread is much more efficient. There seems to be a huge overhead for OpenMP multithreading while training.

**Comment by Shreeshrii** [comment]
@stweil I am currently using the following commit where training is working.

tesseract -v
tesseract 4.0.0-beta.3-162-g3ea9cf
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0

I initially noted the error with the following commit:

tesseract 4.0.0-beta.3-180-gab1f

So the change might be somewhere between these.

**Comment by Shreeshrii** [comment]
Regarding different error rates, also see

For commit - tesseract 4.0.0-beta.3-180-gab1f

```
with
./configure --enable-openmp --disable-debug --disable-opencl
I get
At iteration 4856/5000/5000, Mean rms=1.191%, delta=2.276%, char train=7.534%, word train=16.772%, skip ratio=0%,  New best char error = 7.534 wrote best model:../tesstutorial/engoutput/base7.534_4856.checkpoint wrote checkpoint.
Finished! Error rate = 7.534
```

```
with
./configure --enable-debug --disable-shared --disable-static CXXFLAGS="-Wall -Wextra -g -O0"
I get
At iteration 4992/5000/5000, Mean rms=5.853%, delta=49.475%, char train=100%, word train=100%, skip ratio=0%,  wrote checkpoint.
Finished! Error rate = 25.515
```

I do not know what would cause the difference in results. 

BTW. these are also different from the ones Ray posted on the wiki in the tutorial. I am now using the fontlist as given in language_specific.sh rather than a larger list based on installed fonts, so the results should be comparable.

**Comment by stweil** [comment]
Commit 992031e8248c3b95cda23315bf390303c7c7955c caused that regression. I'll send a fix.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/71bb9c373b4001865b18e7e8bb7592e8428e28c6/src/lstm/networkbuilder.cpp#L453

https://github.com/tesseract-ocr/tesseract/blob/3a7f5e4de459f4c64f36e08b18ce1b66b1fbc876/src/lstm/lstmtrainer.cpp#L474

**Comment by Shreeshrii** [comment]
@stweil Thank you. Continue_from is now working from _checkpoints. That problem is fixed.

Do you want me to keep this issue open for the differences in error rates?

**Comment by Shreeshrii** [comment]
Looks like I spoke too soon ...

Continuing with next step of the tutorial, I am getting the error again:

Commands used:

```
rm -rf ../tesstutorial/impact_from_full
mkdir -p ../tesstutorial/impact_from_full
#
combine_tessdata -e ../tessdata_best/eng.traineddata \
  ../tesstutorial/impact_from_full/eng.lstm
#
lstmtraining \
  --debug_interval -1 \
  --model_output ../tesstutorial/impact_from_full/impact \
  --continue_from ../tesstutorial/impact_from_full/eng.lstm \
  --traineddata ../tessdata_best/eng.traineddata \
  --train_listfile ../tesstutorial/engeval/eng.training_files.txt \
  --max_iterations 400
#------------------------
lstmeval \
  --model ../tesstutorial/impact_from_full/impact_checkpoint \
  --traineddata ../tessdata_best/eng.traineddata \
  --eval_listfile ../tesstutorial/engeval/eng.training_files.txt
```

Console Output and Error Message

```
Mean rms=0.305%, delta=0.125%, train=0.387%(1.179%), skip ratio=0%
2 Percent improvement time=50, best error was 100 @ 0
At iteration 50/400/400, Mean rms=0.305%, delta=0.125%, char train=0.387%, word train=1.179%, skip ratio=0%,  New best char error = 0.387 wrote best model:../tesstutorial/impact_from_full/impact0.387_50.checkpoint wrote checkpoint.

Finished! Error rate = 0.387


ubuntu@tesseract-ocr:~/tesseract$ lstmeval \
>   --model ../tesstutorial/impact_from_full/impact_checkpoint \
>   --traineddata ../tessdata_best/eng.traineddata \
>   --eval_listfile ../tesstutorial/engeval/eng.training_files.txt
../tesstutorial/impact_from_full/impact_checkpoint is not a recognition model, trying training checkpoint...
Loaded 86/86 pages (1-86) of document ../tesstutorial/engeval/eng.Impact_Condensed.exp0.lstmf
Deserialize failed
```

**Comment by Shreeshrii** [comment]
FYI,
Attached is a bash script with the initial steps from tutorial (mainly for training from scratch and eval) that I have been trying so far.

[tesstutorial.sh.txt](https://github.com/tesseract-ocr/tesseract/files/2214701/tesstutorial.sh.txt)

**Comment by stweil** [comment]
The new issue is caused by the same problem. When de-serializing `../tesstutorial/impact_from_full/impact_checkpoint`, Tesseract wants to read about 35000000 characters, but I raised the limit only to 30000000. I'll now use a new upper limit of 50000000, but we should think about @amitdo's remark how we can split such large reads in smaller pieces.

**Comment by stweil** [comment]
Fix #1796 increases the limit further.

**Comment by Shreeshrii** [comment]
> I'll now use a new upper limit of 50000000, but we should think about @amitdo's remark how we can split such large reads in smaller pieces.

Yes, that may be needed as many traineddata files are much larger than eng.traineddata.

**Comment by Shreeshrii** [comment]
@stweil Thanks. Closing this issue now. 

Tested by using both eng.traineddata and Latin.traineddata to continue_from. No error.

```
 time lstmeval \
>   --model ~/tesstutorial/impact_from_full/impact_checkpoint \
>   --traineddata ../tessdata_best/eng.traineddata \
>   --eval_listfile ~/tesstutorial/engeval/eng.training_files.txt
/home/ubuntu/tesstutorial/impact_from_full/impact_checkpoint is not a recognition model, trying training checkpoint...
Loaded 86/86 pages (1-86) of document ../tesstutorial/engeval/eng.Impact_Condensed.exp0.lstmf
At iteration 0, stage 0, Eval Char error rate=0, Word error rate=0

real    0m27.761s
user    1m29.040s
sys     0m0.392s

```

```
 time lstmeval \
>   --model ~/tesstutorial/impact_from_Latin/impact_checkpoint \
>   --traineddata ../tessdata_best/script/Latin.traineddata \
>   --eval_listfile ~/tesstutorial/engeval/eng.training_files.txt
/home/ubuntu/tesstutorial/impact_from_Latin/impact_checkpoint is not a recognition model, trying training checkpoint...
Loaded 86/86 pages (1-86) of document ../tesstutorial/engeval/eng.Impact_Condensed.exp0.lstmf
At iteration 0, stage 0, Eval Char error rate=0, Word error rate=0

real    0m42.231s
user    2m12.728s
sys     0m0.428s
```

**Comment by Shreeshrii** [comment]
@stweil

Regarding, Warning: given outputs 111 not equal to unicharset of 110

The number used to be the same before for training from scratch. In other cases, any number can be given and it will be replaced by size of unicharset.

This displayed size of unicharset has changed, not by recent changes to code, but earlier modifications. It is probably related to changes regarding NULL and Nullptr.

**Comment by Shreeshrii** [comment]
>The number used to be the same before for training from scratch.

I.e. Ray had used  numbers in network spec which matched the size of eng.unicharset.

**Comment by christophered** [comment]
@Shreeshrii you once asked me about my experience with fine-tuning.
Here is the thing, when you fine-tune you should use as few lines as possible, and you should be smart about the text that you use, meaning it should include the characters that you want to add/improve along with the reset of the characters that you already have. It's weird, I know, somehow when you fine-tune it improves a thing, and forgets a thing, that's why i suggest including every character/form in your fine-tuning text. Another thing, depending on your language, some suggest fine-tuning works better when you have a trained model for each book/font/ etc....
if you are serious about the fine-tuning thing, and want to really understand tesseract's weakness in such matters, have a look the Calamari OCR Engine released paper:
https://arxiv.org/ftp/arxiv/papers/1807/1807.02004.pdf
https://github.com/Calamari-OCR/calamari

Also released papers by Reul
https://arxiv.org/search/?searchtype=author&query=Reul%2C+C

and by Wick
https://arxiv.org/search/?searchtype=author&query=Wick%2C+C

**Comment by Shreeshrii** [comment]
@christophered Thanks for the details about finetuning. Yes, it is works better for Latin script based languages. Not so well for Indic and other languages that need recoding.

**Comment by user514** [comment]
Would like to mention that I have been fighting some days with this problem too. I'm on:
tesseract 4.1.1-rc2-25-g9707
And write here because I have the EXACT same symptoms as @Shreeshrii mentions in the first message:

Trying to compile the final mimodelo.traineddata results in
Failed to read continue from: mimodelo_checkpoint

  If I use the previos (numbered) checkpoint: mimodelo0_1283.checkpoint it creates the mimodelo.traineddata without problem (but not sure if this is the proper solution as I suppose not using the last checkpoint will produce more errors than using the last checkpoint).

  More exact same symptoms is getting the 'Deserialize failed' when passing the lstmeval command.

  What I'm trying to teach is with 50 images on a paged .tif with hand edited .box files and only 6 numbers on each image. It really is pictures of a utility water counter (rolling numbers type) and only 0,1,2,3,4,5,6,7,8,9 digits. In other threads I saw the command proposed by Shreeshrii and added 'debug -1' and calculations end up with 0 errors and I read 'perfect' on every step at the end. Finishing with rms=0.185%.

  Probably I will try same process with tesseract 5.0.0 in the following days and see if result is different. I will post results here.
