### ISSUE TITLE
Bad accuracy reading numeric string

### ISSUE THREAD

**Issue by nedark** [tesseract-ocr/tesseract#1787]
Output: 0579405577
Expected output: 0679408877

![image](https://user-images.githubusercontent.com/8337317/42908714-fd7d8756-8ae1-11e8-8607-8c08c03b7b05.png)

**Comment by zdenop** [comment]
Bad issue report. Closing.

**Comment by jaimecoj** [comment]
Why is it bad?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue and you will not why.
