### ISSUE TITLE
OCR results are diffent between tsv and txt outputs in 4.0.0-beta version

### ISSUE THREAD

**Issue by mimi3421** [tesseract-ocr/tesseract#1788]
### Environment

* **Tesseract Version**: 4.0.0-beta.1.20180608 with Leptonica
* **Commit Number**: tesseract-ocr-w64-setup-v4.0.0-beta.1.20180608.exe downloaded from https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v4.0.0-beta.1.20180608.exe
* **Platform**: windows 10 64 bit

### Current Behavior:
tesseract.exe 36_text.png out -l trained_data_fast/mal+trained_data_fast/jpn_vert --psm 12 **txt**
tesseract.exe 36_text.png out -l trained_data_fast/mal+trained_data_fast/jpn_vert --psm 12 **tsv txt**
generate completely different results in OCR texts. 

Here I use trained language data "mal" as a decoy library to increase accuracy. Anyway the results are also different when only jpn_vert is set. The trained data files are downloaded from <https://github.com/tesseract-ocr/tessdata_fast>

source image:
![36_text](https://user-images.githubusercontent.com/41418689/42928346-a0a0d1ea-8b69-11e8-8dad-edccde96aefb.png)

result without "tsv" parameter
ടോ1 czrie気持 ちいഴ്‌ ചു

result with "tsv"parameter
നിഴ്‌ ചു 、

### Expected Behavior:
The results should be the same.

**Comment by mimi3421** [comment]
I can now get the same results explicitly setting tessedit_pageseg_mode=12 like: 
tesseract.exe 36_text.png out -l trained_data_fast/mal+trained_data_fast/jpn_vert **-c tessedit_pageseg_mode=12** tsv txt
Although it's a little bit tricky but works. It seems that the --psm parameter doesn't work as generally thinking. Thank you for the useful reply.

**Comment by zdenop** [comment]
Your [tsv](https://github.com/tesseract-ocr/tesseract/blob/master/tessdata/configs/tsv) parameter is just simple text file with list of variables setting. 
You have two options:

1. put to your variable settings to command line instead of using tsv config
2. create your own config file and place it tessdata/config

**Comment by stweil** [comment]
Fixed with PR #1943.
