### ISSUE TITLE
Exception: this->AdaptedTemplates was nullptr.

### ISSUE THREAD

**Issue by NaxAlpha** [tesseract-ocr/tesseract#1793]
### Environment

* **Tesseract Version**: 4.0.0-beta.3
* **Commit Number**: b1f7990
* **Platform**: Windows 10 64-bit (latest) 

### Sample Code
Here is sample code (Note: I used tesseract 4 language data files)
``` C++
int main() {
	auto api = new TessBaseAPI; 
	Mat image = imread("../../samples/0.jpg");
	bool res = api->Init(0, "eng", OcrEngineMode::OEM_TESSERACT_LSTM_COMBINED);
	api->SetPageSegMode(PageSegMode::PSM_SINGLE_LINE);
	api->SetImage(image.data, image.cols, image.rows, image.channels(), image.step1());
	api->Recognize(0);
	auto text = api->GetUTF8Text();
	return 0;
}
```
### Current Behavior:
![image](https://user-images.githubusercontent.com/11090613/42983900-d52497a0-8c02-11e8-8552-f22b59895b80.png)

### Expected Behavior:
Error occurs at `Recognize(0)` call. It should have had returned correct result. 
### Suggested Fix:
N/A

**Comment by NaxAlpha** [comment]
Fixed: Error was related to loading language

**Comment by Dejauxvue** [comment]
@NaxAlpha Hi, it seems that I have the same issue. Could you post a solution to this problem?

**Comment by svebert** [comment]
Same problem here. 
I am trying the basic example from here: https://github.com/tesseract-ocr/tesseract/wiki/APIExample
Image is a bmp showing 3 line MRZ
