### ISSUE TITLE
tesseract is not installed or it is not in your path

### ISSUE THREAD

**Issue by pete111** [tesseract-ocr/tesseract#1799]
Hi, 
I am using tesseract in while loop in my script. But from time to time (once daily) I am getting this error. Tesseract is installed and works, but I get this message once per day. How to solve it?

```
Traceback:
File file.py, line 169, in <module> results.append(pytesseract.image_to_string(im))
File /usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py, line 286, in image_to_string
return run_and_get_output(image, 'txt', lang, config, nice)
File /usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py, line 201, in run_and_get_output
   raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your path
```

version:
```
tesseract 3.04.01
 leptonica-1.74.1
  libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.1) : libpng 1.6.28 : libtiff 4.0.8 : zlib 1.2.8 : libwebp 0.5.2 : libopenjp2 2.1.2
```

system:
`Raspberry Pi Linux Raspbian`

**Comment by amitdo** [comment]
We don't support 3rd party software. Turn to the author of the script with your question.

**Comment by pete111** [comment]
@amitdo, my question is not about third party software. My question is why is tesseract working but suddenly once daily tesseract returns "tesseract is not installed or it's not in your path". When I start script again, then it works correctly again.

**Comment by stweil** [comment]
I'd try a newer version of Tesseract and also of the Python part.

**Comment by zdenop** [comment]
@pete111: please read your post. @amitdo is right. It is 3rd party sw that claims  "tesseract is not installed or it's not in your path". It is not tesseract error message e.g. there is nothing we can fix or solve.

**Comment by danszw** [comment]
I have faced the same issue "TesseractNotFoundError" in 3rd party software, in fact it was Out Of Memory problem, because when I stopped some services everything started working.

**Comment by amirhosseinalikhahm** [comment]
I have faced the same issue, the solution is very easy, 

pytesseract.pytesseract.tesseract_cmd = r"full path to the exe file"
pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

text = pytesseract.image_to_string(new_image, config='--psm 11')

worked fine for me.

**Comment by sneharane588** [comment]
> I have faced the same issue, the solution is very easy,
> 
> pytesseract.pytesseract.tesseract_cmd = r"full path to the exe file"
> pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
> 
> text = pytesseract.image_to_string(new_image, config='--psm 11')
> 
> worked fine for me.

Thanks, it worked for me.

**Comment by saikirannarayana** [comment]
> > I have faced the same issue, the solution is very easy,
> > pytesseract.pytesseract.tesseract_cmd = r"full path to the exe file"
> > pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
> > text = pytesseract.image_to_string(new_image, config='--psm 11')
> > worked fine for me.
> 
> Thanks, it worked for me.

i could nt find the teeseract.exe in program files in my pc.so what shall i do now?

**Comment by tharun435** [comment]
How to add pytesseract in path in Ubuntu OS. There is no exe file in Ubuntu

**Comment by tharun435** [comment]
> Hi,
> I am using tesseract in while loop in my script. But from time to time (once daily) I am getting this error. Tesseract is installed and works, but I get this message once per day. How to solve it?
> 
> ```
> Traceback:
> File file.py, line 169, in <module> results.append(pytesseract.image_to_string(im))
> File /usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py, line 286, in image_to_string
> return run_and_get_output(image, 'txt', lang, config, nice)
> File /usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py, line 201, in run_and_get_output
>    raise TesseractNotFoundError()
> pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your path
> ```
> 
> version:
> 
> ```
> tesseract 3.04.01
>  leptonica-1.74.1
>   libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.1) : libpng 1.6.28 : libtiff 4.0.8 : zlib 1.2.8 : libwebp 0.5.2 : libopenjp2 2.1.2
> ```
> 
> system:
> `Raspberry Pi Linux Raspbian`

For Linux Distribution (Ubuntu)

try 

sudo apt install tesseract-ocr
sudo apt install libtesseract-dev

**Comment by saikirannarayana** [comment]
Tq

**Comment by jinshuihe** [comment]
> I have faced the same issue, the solution is very easy,
> 
> pytesseract.pytesseract.tesseract_cmd = r"full path to the exe file"
> pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
> 
> text = pytesseract.image_to_string(new_image, config='--psm 11')
> 
> worked fine for me.

where to add
 > pytesseract.pytesseract.tesseract_cmd = r"full path to the exe file"
> pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

Please let me know,THX!

**Comment by saikirannarayana** [comment]
Thanks

**Comment by achuga200** [comment]
i face same issue. first download tesseract if not in your system. link : https://github.com/UB-Mannheim/tesseract/wiki
second, install and check the necessary language during the process of installation
third: add tesseract to your path.  use: right click on start menu for  windows -> click on system -> system info -> advance setting -> environment variable -> add new  variable ( Variable Name: TESSDATA_PREFIX, value: "c:\program file\ Tesseract-OCR) -> ok
fourth step is to : pip install tesseract (for vscode) and also pip install pytesseract 
last step: add the file path to your current python script: pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe" . Note this file path depends on where you installed tesseract.

**Comment by marmikreal** [comment]
In Case of the user have installed it for user only the path will be in the user folder for windows 
Like :
C:\Users\<User.Name>\AppData\Local\Tesseract-OCR\tesseract.exe

using same in code works fine
pytesseract.pytesseract.tesseract_cmd = r'C:\Users\John.Doe\AppData\Local\Tesseract-OCR\tesseract.exe'

**Comment by yifan0011** [comment]
I got an error adding pytesseract.pytesseract.tesseract_cmd = r'...\Tesseract-OCR\tesseract.exe' to my Python script:

Traceback (most recent call last):
  File "C:\Users\USER\difficult PDFs\text.py", line 50, in <module>
    pytesseract.pytesseract.tesseract_cmd = r'C:/Users/USER/AppData/Local/Programs/Tesseract-OCR/tesseract.exe'
    ^^^^^^^^^^^
NameError: name 'pytesseract' is not defined

However, with just tesseract_cmd = r'C:/Users/USER/AppData/Local/Programs/Tesseract-OCR/tesseract.exe', it works like a charm.

Anyone knows why?
