### ISSUE TITLE
Segmentation fault error in alpine linux 

### ISSUE THREAD

**Issue by techrider888** [tesseract-ocr/tesseract#1800]
**Tesseract Version:** tesseract 3.04.01
 leptonica-1.74.1
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.1) : libpng 1.6.29 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.0

**Platform:** Alpine Linux v3.6 (docker container)

**STEP FOLLWED TO INSTALL TESSERACT IN ALPINE LINUX**
 
 apk add --no-cache tesseract-ocr

  wget -q -P /usr/share/tessdata/ https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.traineddata

  wget -q -P /usr/share/tessdata/ https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.cube.bigrams

  wget -q -P /usr/share/tessdata/  https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.cube.fold

  wget -q -P /usr/share/tessdata/ https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.cube.lm 

  wget -q -P /usr/share/tessdata/ https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.cube.nn

  wget -q -P /usr/share/tessdata/ https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.cube.params

  wget -q -P /usr/share/tessdata/ https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.cube.size 

  wget -q -P /usr/share/tessdata/ https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.cube.word-freq 

  wget -q -P /usr/share/tessdata/ https://github.com/tesseract-ocr/tessdata/blob/3.04.00/eng.tesseract_cube.nn

**Current Behavior:**

tesseract --list-langs , **error log :**

fseek(data_file_, static_cast<size_t>(offset_table_[tessdata_type]), SEEK_SET) == 0:Error:Assert failed:in file ../ccutil/tessdatamanager.h, line 173
Segmentation fault (core dumped)

tesseract FILENAME.tif FILENAME2 pdf , **error log :**
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
fseek(data_file_, static_cast<size_t>(offset_table_[tessdata_type]), SEEK_SET) == 0:Error:Assert failed:in file ../ccutil/tessdatamanager.h, line 173
Segmentation fault (core dumped)

**Comment by stweil** [comment]
That's an old unsupported version of Tesseract. Please use newer versions.
