### ISSUE TITLE
conversion fail ??

### ISSUE THREAD

**Issue by foxjazz** [tesseract-ocr/tesseract#1807]
tesseract Capture2.PNG t -l eng -oem 3 -psm 7
![capture2](https://user-images.githubusercontent.com/867496/43297578-69dcb6be-910f-11e8-8aec-4f6af2ef9790.PNG)

image produces this output.

‘ tuzksss

**Comment by zdenop** [comment]
Please respect instruction for posting issues.

**Comment by foxjazz** [comment]
if you can't figure out from the images posted what is wrong, you should quit programming.
