### ISSUE TITLE
Unable to extract grey or light grey text from an image, 

### ISSUE THREAD

**Issue by Yavdhesh** [tesseract-ocr/tesseract#1809]
tesseract 4.0.0 beta3
using java wrapper tess4j 4.0

when I putting an image for ocr, tesseract does not recognize grey or light grey text in the image.
![sample ola bill](https://user-images.githubusercontent.com/22321498/43363168-d447d782-931b-11e8-87ea-e32bd405468b.jpg)

this is the image file, where I am trying to extract the Base Fare, but after I run it for OCR. Base Fare is not there.

**Comment by zdenop** [comment]
Image quality is very low.
