### ISSUE TITLE
a problem about traineddata

### ISSUE THREAD

**Issue by loralyc** [tesseract-ocr/tesseract#1820]
hello,
i want to ask if the traineddata trained in linux can't use in windows? it seems that it alwasys crash when i try to use the traineddata from api in windows. it always crash when i run to the code api->end();
thank you!

ps: 
the version i set in linux is tesseract 4.0.0-beta.1-228-gd057
the version i set in windows is tesseract 4.0.0-beta.1

**Comment by stweil** [comment]
Traineddata is the same for Windows and Linux. Please note that this is not the [support forum](https://github.com/tesseract-ocr/tesseract/wiki#support) and close this issue.
