### ISSUE TITLE
tesseract 4.0.0.beta.4.r20.ge9b4e21e segfault

### ISSUE THREAD

**Issue by duk3luk3** [tesseract-ocr/tesseract#1824]
------------------------

### Environment

* **Tesseract Version**: 4.0.0 beta 4

```
erlacher@laprbg12 extracted-pdf(:|✔) % tesseract --version                                                                                                                                                    ~/scratch/qextract/extracted-pdf
tesseract 4.0.0-beta.4-20-ge9b4e
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0
 Found AVX2
 Found AVX
 Found SSE
```

* **Commit Number**: unsure - maybe ge9b4e21e
* **Platform**: Linux laprbg12 4.14.56-1-lts #1 SMP Tue Jul 17 20:11:42 CEST 2018 x86_64 GNU/Linux

Compiled and Installed from AUR: https://aur.archlinux.org/packages/tesseract-ocr-git/

### Current Behavior:

Commandline: `tesseract --tessdata-dir /usr/local/share/tessdata ./extracted-pdf-045.png tesseract-output`

Using this english training data file: https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/eng.traineddata

Input file: [extracted-pdf-045.png](https://user-images.githubusercontent.com/611471/43676870-6d060f96-983c-11e8-8eb2-46a356c740f7.png)

Result:

```
erlacher@laprbg12 extracted-pdf(:|✔) % tesseract --tessdata-dir /usr/local/share/tessdata ./extracted-pdf-045.png tesseract-output                                                                            ~/scratch/qextract/extracted-pdf
Tesseract Open Source OCR Engine v4.0.0-beta.4-20-ge9b4e with Leptonica
contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 509
zsh: segmentation fault (core dumped)  tesseract --tessdata-dir /usr/local/share/tessdata ./extracted-pdf-045.png 
```

### Expected Behavior:

It shouldn't segfault

### Suggested Fix:

Fix the memory handling bug

**Comment by amitdo** [comment]
>contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 509

This was reported multiple times before.

https://github.com/tesseract-ocr/tesseract/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+contains_unichar_id

**Comment by Shreeshrii** [comment]
>Using this english training data file: https://raw.githubusercontent.com/tesseract-ocr/tessdata/master/eng.traineddata

Please try with eng.traineddata from tessdata_best and tessdata_fast repos. Do you get the same error?

**Comment by stweil** [comment]
I want to get rid of those "segmentation faults" in user bug reports when it was only caused by Tesseract's way of error handling. Therefore pull request #1923 removes the deliberate segmentation fault in release builds.
