### ISSUE TITLE
tesseract not able to detect handwritten text even after improving image quality

### ISSUE THREAD

**Issue by rahul4tripathi2** [tesseract-ocr/tesseract#1827]
Hi,

I'm trying to extract the handwritten data from image but even after improving the image quality tesseract is not able to detect handwritten text . can you please suggest me the steps to detect handwritten from given image.

Reference link -
https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality#rescaling

Image link
https://drive.google.com/open?id=1wv0JvuedQl99fYLNn8BMUId74PtLt_Ej

Regards
Rahul

**Comment by zdenop** [comment]
Please respect guidelines for posting issue.
