### ISSUE TITLE
Unexpected operator error in autogen.sh

### ISSUE THREAD

**Issue by mustafashujaie** [tesseract-ocr/tesseract#183]
I downloaded `3.04.00.tar.gz` and ran `./autogen.sh` according to the compilation guide in the wiki. But I get the following output:

    ./autogen.sh: 30: [: unexpected operator
    Running aclocal
    Running libtoolize 
    # ...

**Comment by stweil** [comment]
The code looks good. Which operating system and shell do you use?

**Comment by mustafashujaie** [comment]
Yes I could perform the installation successfully. I use ubuntu 15.04. I think the problem is that this script is using the `sh` shell in the shebang line. (`#!/bin/sh`) If I run this script with `bash` shell explicitly there won't be any error.

**Comment by stweil** [comment]
On my Debian GNU Linux, /bin/sh is dash. dash has no problems with the code. Which /bin/sh does your Ubuntu Linux use?

I don't see bash specific code, so any POSIX conformant shell should work.

**Comment by mustafashujaie** [comment]
mustafa@mustafa-ThinkPad-T440:~$ ls -l /bin/sh
    lrwxrwxrwx 1 root root 4 Jan  2 15:10 /bin/sh -> dash

And this is the output using `bash`:

    mustafa@mustafa-ThinkPad-T440:~$ bash ./autogen.sh 
    Running aclocal
    Running libtoolize
    libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
    libtoolize: copying file `config/ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
    libtoolize: copying file `m4/libtool.m4'
    libtoolize: copying file `m4/ltoptions.m4'
    libtoolize: copying file `m4/ltsugar.m4'
    libtoolize: copying file `m4/ltversion.m4'
    libtoolize: copying file `m4/lt~obsolete.m4'
    Running autoheader
    Running automake --add-missing --copy
    configure.ac:248: installing 'config/compile'
    Running autoconf

    All done.
    To build the software now, do something like:

    $ ./configure [--enable-debug] [...other options]

**Comment by stweil** [comment]
The version which you used in your test is indeed buggy and uses bash specific code. That was fixed in commit 9851bb23b1b5bc776f0ed9f851aebf297bd1d9aa. Please look there how to fix it in your installation.
