### ISSUE TITLE
OSD doesn't work correctly

### ISSUE THREAD

**Issue by ColdenHaulfield** [tesseract-ocr/tesseract#1830]
### Environment

* **Tesseract Version**: 4.0.0-beta.3
* **Platform**: Windows 10 x64 

### Current Behavior:

OSD doesn't work correctly. Mycode:
`tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
	if (api->Init(tessdataPath, "osd", tesseract::OEM_DEFAULT))	
	Pix *image = pixRead(imagePath);
	api->SetPageSegMode(tesseract::PSM_OSD_ONLY);
	api->SetImage(image);	
	api->Recognize(0);	
	int orient_deg;
	float orient_conf;
	const char* script_name;
	float script_conf;
	bool detected = api->DetectOrientationScript(&orient_deg, &orient_conf,&script_name, &script_conf);
`

Result is:

![image](https://user-images.githubusercontent.com/42068116/43900901-c1c34494-9bee-11e8-913a-28e803120c41.png)

Orientation is always zero. Tessdata is usual, not fast or best.

### Expected Behavior:

Orientation: 180

### Suggested Fix:

May be some troubles with legacy and new engine?

**Comment by amitdo** [comment]
Please provide the input image you used. Without it, we won't able to help you.

Also try the command line tool.

**Comment by ColdenHaulfield** [comment]
> Also try the command line tool.

Same result.

Image:
![cuttedimage](https://user-images.githubusercontent.com/42068116/43942302-25a5ee8a-9c80-11e8-9287-671fe02e82ff.jpg)
