### ISSUE TITLE
Large text processing tesstrain.sh/text2image

### ISSUE THREAD

**Issue by qb1t0** [tesseract-ocr/tesseract#1831]
When I'm trying to prepare starter data for lstm training using tesstrain.sh with following arguments:

![2018-08-09 15 51 40](https://user-images.githubusercontent.com/26835866/43900332-3a272b00-9bed-11e8-9a5b-419933ac6e74.png)

**ukr.training_receipt.txt** - txt file with more than 5000 rows:

![2018-08-09 16 11 47](https://user-images.githubusercontent.com/26835866/43901027-1bddd0fc-9bef-11e8-9bdb-266345b75319.png)

------------------------

### Environment
* **Tesseract Version**: 4.0.0beta.3.0.0

### Current Behavior:
For now it is cropping first few lines from .txt file and creates only one *.exp0.tiff for each font.
![2018-08-09 16 04 41](https://user-images.githubusercontent.com/26835866/43900576-fda7ff00-9bed-11e8-82be-89c30a272c0d.png)

### Expected Behavior:
I supposed it will generate at least exp100+.tiff files  for ech part of an input text, instead of first few rows. 
### Suggested Fix:
idk

**Comment by Shreeshrii** [comment]
1. The tifs should be multipage covering all text. Please check. The box file should also have all the text.

2. Beta.3 has some issues with training process. Please use beta.4.

**Comment by qb1t0** [comment]
Oh, my bad.
Thanks.
