### ISSUE TITLE
Urdu language left to right output and no space recognize

### ISSUE THREAD

**Issue by moeneqbal** [tesseract-ocr/tesseract#1832]
i have trained my own model for urdu language using jtessboxeditor to create tiff/box file and then used Serak tesseract trainer for creating trainedata file, my model is recognizing urdu language but there are 2 issues mainly other than accuracy(accuracy will be test after solving following 2 issues).

1) model is not recognizing the spaces b/w the words.
2) model is showing the text in LTR form (Urdu is RTL language, similar to arabic)

thanx in advance.

**Comment by zdenop** [comment]
Please use issue tracker only for training files/programs provided by this project.
We do not provide support for custom training. 
Use tesseract user forum for asking support. Thanks.
