### ISSUE TITLE
cannot install new version, please help me

### ISSUE THREAD

**Issue by kimchicanh** [tesseract-ocr/tesseract#1833]
### Environment

* **Tesseract Version**: 3.04
* **Commit Number**: 3.04
* **Platform**: ubuntu 16.04

### Suggested Fix:

I installed tesseract 3.04 from source but now I cannot install up to 4 via command:
sudo apt install tesseract-ocr
It still install 3.04

Log:
sudo apt install tesseract-ocr
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  tesseract-ocr
0 upgraded, 1 newly installed, 0 to remove and 157 not upgraded.
Need to get 132 kB of archives.
After this operation, 562 kB of additional disk space will be used.
Get:1 http://vn.archive.ubuntu.com/ubuntu xenial/universe amd64 tesseract-ocr amd64 3.04.01-4 [132 kB]
Fetched 132 kB in 1s (90,3 kB/s)        
Selecting previously unselected package tesseract-ocr.
dpkg: warning: files list file for package 'tesseract-ocr-osd' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'tesseract-ocr-eng' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libtesseract-dev' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libtesseract3' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'tesseract-ocr-equ' missing; assuming package has no files currently installed
(Reading database ... 293846 files and directories currently installed.)
Preparing to unpack .../tesseract-ocr_3.04.01-4_amd64.deb ...
Unpacking tesseract-ocr (3.04.01-4) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up tesseract-ocr (3.04.01-4) ...
Thanks

**Comment by qb1t0** [comment]
have you tried  `sudo apt install libtesseract-dev` ?
[read more information](https://github.com/tesseract-ocr/tesseract/wiki)

**Comment by zdenop** [comment]
This is not tesseract issue - but Ubuntu. Contact their support or tesseract user forum.

**Comment by jbreiden** [comment]
Upgrade to Ubuntu 18.04 and everything will be puppy dogs and sunflowers.
