### ISSUE TITLE
3.05.02 built --with-opencl fails when invoked on OS X 10.13.6

### ISSUE THREAD

**Issue by p-b-west** [tesseract-ocr/tesseract#1835]
### Environment

* **Tesseract Version**: 3.05.02
* **Commit Number**: 7e5f0d6fc6b214093d5b660cdcf6ce36bbbdd30f
* **Platform**: Darwin lydia.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

Installed using brew install tesseract --with-opencl --with-serial-num-pack

### Current Behavior:
$ tesseract out2-1.png out2-1
[DS] Profile file not available (tesseract_opencl_profile_devices.dat); performing profiling.

[DS] Device: "Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz" (OpenCL) evaluation...
[OD] write binary[kernel-Intel(R)_Core(TM)_i7-4850HQ_CPU_@_2.30GHz.bin] successfully
OpenCL error code is -54 at   when clEnqueueNDRangeKernel .
OpenCL error code is -54 at   when clEnqueueNDRangeKernel kernel_HistogramRectAllChannels .
OpenCL error code is -54 at   when clEnqueueNDRangeKernel kernel_HistogramRectAllChannelsReduction .
OpenCL error code is -54 at   when clEnqueueNDRangeKernel kernel_ThresholdRectToPix .
Setting return value to -1
[DS] Device: "Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz" (OpenCL) evaluated
[DS]          composeRGBPixel: 0.001138 (w=1.2)
[DS]            HistogramRect: 340282346638528859811704183484516925440.000000 (w=2.4)
[DS]       ThresholdRectToPix: 340282346638528859811704183484516925440.000000 (w=4.5)
[DS]        getLineMasksMorph: 0.003314 (w=5.0)
[DS]                    Score: inf

[DS] Device: "Iris Pro" (OpenCL) evaluation...
[OD] write binary[kernel-Iris_Pro.bin] successfully
[DS] Device: "Iris Pro" (OpenCL) evaluated
[DS]          composeRGBPixel: 0.012276 (w=1.2)
[DS]            HistogramRect: 0.136262 (w=2.4)
[DS]       ThresholdRectToPix: 0.005064 (w=4.5)
[DS]        getLineMasksMorph: 0.012855 (w=5.0)
[DS]                    Score: 0.428823

[DS] Device: "GeForce GT 750M" (OpenCL) evaluation...
[OD] write binary[kernel-GeForce_GT_750M.bin] successfully
Illegal instruction: 4

### Expected Behavior:
Not that.
### Suggested Fix:
Beats me.

**Comment by amitdo** [comment]
OpenCL in tesseract is considered experimental and should not be not be used by regular users.
