### ISSUE TITLE
Segmentation fault on run for training.

### ISSUE THREAD

**Issue by Naozumi2k** [tesseract-ocr/tesseract#1836]
### Environment

* **tesseract 4.0.0-beta.4-26-gfd49
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0**

* **Arch Linux 4.17.12-arch1-1-ARCH x86_64**

### Current Behavior:
I'm trying to run tesseract for training on image and boxfile:
**tesseract eng.zaka.exp0.tif eng.zaka.exp0 box.train**

> Tesseract Open Source OCR Engine v4.0.0-beta.4-26-gfd49 with Leptonica
> Page 1
> Warning. Invalid resolution 0 dpi. Using 70 instead.
> Estimating resolution as 397
> a != 0 && b != 0:Error:Assert failed:in file applybox.cpp, line 326
> Segmentation fault (core dumped)

tif and box files that I used to run attached:
[training.zip](https://github.com/tesseract-ocr/tesseract/files/2282426/training.zip)

Thanks!

**Comment by XinAlo** [comment]
I had this question too，who can solve it

**Comment by Shreeshrii** [comment]
>box.train

Are you trying to train for legacy tesseract rather than LSTM?

I suggest that you use 3.05.02 instead of 4.0.0 beta.

**Comment by tangziwei** [comment]
I also meet this error, I guess it might be an bug, and I try the commit on APRIL and it works well.

**Comment by Shreeshrii** [comment]
The assert has been added by https://github.com/tesseract-ocr/tesseract/commit/09da044a77d2df2e55bdab7827be6a243fb19966

@stweil Could this be related to the default --oem mode being used for training?

**Comment by stweil** [comment]
The assert was added to avoid a division by zero. Here `b == 0`, so we would get a division by zero. As we have a float division here, Tesseract would not crash but the result of the division would be INF.

The problem is caused by a box with unset dimensions which is added [here](https://github.com/tesseract-ocr/tesseract/blob/master/src/ccmain/applybox.cpp#L126).

**Comment by stweil** [comment]
Pull request #1856 should fix this issue.
