### ISSUE TITLE
include twice

### ISSUE THREAD

**Issue by maddin200** [tesseract-ocr/tesseract#1837]
src/viewer/scrollview.cpp line 31 twin include (cstring) also in line 25

**Comment by maddin200** [comment]
better would be a PR by the standard contributors- thanks !

**Comment by zdenop** [comment]
I will do it.



ut 14. 8. 2018 o 12:48 Martin Strunz <notifications@github.com> napísal(a):

**Comment by stweil** [comment]
See PR #1840.

**Comment by zdenop** [comment]
seems like we worked in parallel ;-)
