### ISSUE TITLE
lstm-specific dictionaries load Failed

### ISSUE THREAD

**Issue by zwwlouis** [tesseract-ocr/tesseract#1839]
### Environment

Tesseract Open Source OCR Engine v4.0.0-beta.4-18-g4370
Linux bogon 3.10.0-862.3.3.el7.x86_64

### Current Behavior:
 I'm trying to fine tuning chi_sim by adding some characters
It goes well during training without any fault and I got my .traineddata file by --stop_training
But, when I trying to test it with tesseract command

tesseract test-0.png test --tessdata-dir ./chi_sim -l driver_name
I'v got these words
**Failed to load any lstm-specific dictionaries for lang driver_name!!**

this is what inside the file
combine_tessdata -d chi_sim/driver_name.traineddata
0:config:size=2106, offset=192
17:lstm:size=12169267, offset=2298
21:lstm-unicharset:size=382829, offset=12171565
22:lstm-recoder:size=94353, offset=12554394
23:version:size=21, offset=12648747

since " Tesseract 4.00 will run happily with a traineddata file that contains just lang.lstm, lang.lstm-unicharset and lang.lstm-recoder ", I thought I'v just satisfied this requirement
so what are these lstm-specific dictionaries?
are these data important?
will this issue critically influence my ocr result ?

**Comment by Shreeshrii** [comment]
Please see new langdata_lstm repository which has the source files used for LSTM training.

If you provide the wordlist, puncuation and numbers file for combine_lang_model command then it will create the dictionary dawg files.

**Comment by zwwlouis** [comment]
I see, I should take up wordlist, puncuation and numbers files while create starter traineddata.
But I wonder that what's the main different between langdata_lstm and langdata, since they have almost the same file pattern
.singles_text seems the only file that langdata_lstm has while langdata doesn't
But, .singles_text looks much like .wordlist or, to be more precisely, the subset of .wordlist
what's the purpose of this .singles_text file? Is it necessary for lstm training?
