### ISSUE TITLE
include twice

### ISSUE THREAD

**Issue by maddin200** [tesseract-ocr/tesseract#1843]
/src/viewer/svmnode.cpp (line 30):  (cstring) also in line 28.

same holds for svutil.cpp (line 50 + 51)  also in line 40 + 41

**Comment by amitdo** [comment]
>/src/viewer/svmnode.cpp (line 30): (cstring) also in line 28.

https://github.com/tesseract-ocr/tesseract/commit/debe3da36de 

 svutil.cpp has one `#include <cstring>` in `#ifdef` block and one outside it.

**Comment by stweil** [comment]
Thank you, @amitdo. I‌ removed that and also another duplicate include statement, so this issue can be closed as soon as my pull request was merged.
