### ISSUE TITLE
problems on narrow lines

### ISSUE THREAD

**Issue by ibaxx** [tesseract-ocr/tesseract#1845]
### Environment

recent Master branch

### Current Behavior:

I have huge problems with narrow lines.
attched is a sample... it is not possible to read the invoice number or the date.

I know the invoice is printed terrible, but i had this type of problem often.
![problem](https://user-images.githubusercontent.com/2786557/44212906-e37d9c00-a16c-11e8-9c04-6ad4fa2ff5ff.jpg)

**Comment by zdenop** [comment]
As suggested above you need to preprocess your image.

**Comment by ibaxx** [comment]
The image is preprocessed!
The problem are not the vertical lines.
The problem are the two text lines above the table!
they are too near. i think tesseract thinks it is one line

**Comment by zdenop** [comment]
It depend how you define preprocess. If you prepossess it fully - there would be just text. If you want to have great result from tesseract you should pass it only text - without any graphics, tables, vertical or horizontal lines.

**Comment by ibaxx** [comment]
Again to clear that the problem is nothing with the table.
Here is the problematic part of the image.

Theese two lines are interpretetd as one line:

![narrowproblem](https://user-images.githubusercontent.com/2786557/46788883-784ee100-cd3b-11e8-8760-2f05cebee753.jpg)

**Comment by zdenop** [comment]
Did you think about your response? 
You again and again confirm that problem is input. Fix input (preprocess image -> separate text areas) and it is done.

**Comment by ibaxx** [comment]
that means for me, that the comfort of the hocr output is gone.

@zdenop  pardon that my question annoys you. but tesseract still got parts of both lines. thats why i think it should be possible, that tesseract should interprets this part as two lines.

by the way, i have tested this file with Abbyy Flexicapture this morning. the flexicapture output is not better than the tesseract output on this area!

**Comment by amitdo** [comment]
Maybe ocropy's ocropus-gpageseg can do the lines cutting better.
https://github.com/tmbdev/ocropy/blob/master/ocropus-gpageseg

**Comment by zdenop** [comment]
@ibaxx: There will be always some inputs, that will not be possible to process automatically. I am familiar with one company providing professional high quality OCR services. First round OCR is done by software (not tesseract). Next one by 100 students ;-)
And you can not get good output from "bad" (or not suitable) input.

**Comment by amitdo** [comment]
>I am familiar with one company providing professional high quality OCR services. First round OCR is done by software (not tesseract). Next one by 100 students

What's the name of this company?
Which OCR engine do they use for first round? Their own, ABBYY?

**Comment by zdenop** [comment]
I will not name it ;-) I am not familiar with production details (intentionally not to compromise tesseract) - I was just there for visit when we were discussing contract. It is quite expensive if you want to have close to 100% OCR.  
That's why it is funny for me when people are feeding everything to tesseract (free solution) and expecting all their problems are solved...
Anyway I would expect to have this kind of production in Asia and but it seem there are able to make money on this in Europe.

**Comment by amitdo** [comment]
You can DIY with tesseract +  [Amazon's Mechanical Turk](https://en.wikipedia.org/wiki/Amazon_Mechanical_Turk)
