### ISSUE TITLE
use of undeclared identifier 'exit' in icuerrorcode.h

### ISSUE THREAD

**Issue by nohtanoj** [tesseract-ocr/tesseract#1847]
### Environment

* **Tesseract Version**: 4.0.0-beta.3
* **Commit Number**: 
* **Platform**: Darwin C02S10ZPG8WL 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64 

### Current Behavior:

I tried running `make training` and got this error 

```
In file included from normstrngs.cpp:28:
./icuerrorcode.h:56:5: error: use of undeclared identifier 'exit'
    exit(errorCode);
    ^
1 error generated.
make[1]: *** [normstrngs.lo] Error 1
```

### Expected Behavior:

The compilation should not fail. 

### Suggested Fix:

Applying

```
diff --git a/src/training/icuerrorcode.h b/src/training/icuerrorcode.h
index 5e50326..4b6dae9 100644
--- a/src/training/icuerrorcode.h
+++ b/src/training/icuerrorcode.h
@@ -36,6 +36,7 @@
 #ifndef TESSERACT_CCUTIL_ICUERRORCODE_H_
 #define TESSERACT_CCUTIL_ICUERRORCODE_H_

+#include "stdlib.h"
 #include "tprintf.h"
 #include "unicode/errorcode.h"  // From libicu
```

fixed the issue.

**Comment by Shreeshrii** [comment]
Have you tried with latest code from GitHub? Is the issue present in that?

**Comment by zdenop** [comment]
Close because of missing input from reporter and because it is know that tesseract can be build on various Linux platforms without above described problem.
