### ISSUE TITLE
RedHat yum installation failed

### ISSUE THREAD

**Issue by darrencl** [tesseract-ocr/tesseract#1857]
### Environment
RedHat Enterprise
* **Tesseract Version**: [On Installation Process]
* **Commit Number**: 
* **Platform**: 

### Current Behavior:
Failed on installation process. I have tried following the steps for CentOS and Scientific Linux (adding repo -> yum update), but when installing the tesseract, it has several error on its dependencies. The error message is something like:

Error: Package: leptonica-1.76.0-2.1.x86_64 (download. .....)
    Requires: libpng15.so.15()(64bit)

Is there any solution for this installation issue?

Thanks!

### Expected Behavior:

No error during installation

**Comment by darrencl** [comment]
Here I attached the screenshot:
![image](https://user-images.githubusercontent.com/21291776/44521287-df75ef00-a715-11e8-9418-cbcb54b496f5.png)

I have tried using --skip-broken option, but it still could not run tesseract in command line (-bash: tesseract: command not found) and it fails when I use textract ocr (ShellError could not find tesseract executable).

Any help would be highly appreciated!

**Comment by Shreeshrii** [comment]
@AlexanderP Any advice?

**Comment by AlexanderP** [comment]
Add RHEL 7

```
yum-config-manager --add-repo https://download.opensuse.org/repositories/home:/Alexander_Pozdnyakov/RHEL_7/
yum update
yum install tesseract 
yum install tesseract-langpack-deu
```
please check

**Comment by Shreeshrii** [comment]
@AlexanderP Thanks!

@darrencl  Please see https://github.com/tesseract-ocr/tesseract/wiki#tesseract-400-beta-packages-with-lstm-engine-and-related-traineddata

It has the commands for installing on various OSes.

**Comment by christophered** [comment]
@amitdo close the topic
