### ISSUE TITLE
Alpine 3.8 package SIGSEVs using tess4j

### ISSUE THREAD

**Issue by gamma** [tesseract-ocr/tesseract#1860]
Using the API I always receive SIGSEV errors when TessBasAPI -> Recognize is called inside an alpine container.

We're using the setup from [Docker](https://hub.docker.com/r/inetsoftware/alpine-tesseract/) to set up a tesseract4 alpine container. The error occurs in beta3, beta4 and master.

The error does not occur when running tesseract from command line, but since it's purely in native code I think it might be a problem from tesseract itself.

The error is:

    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGSEGV (0xb) at pc=0x00007f738f244b74, pid=49, tid=0x00007f73bc813ae8
    #
    # JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
    # Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
    # Derivative: IcedTea 3.8.0
    # Distribution: Custom build (Wed Jun 13 18:28:11 UTC 2018)
    # Problematic frame:
    # C  [libgomp.so.1+0xab74]  GOMP_doacross_ull_wait+0x284

Since it seems to work on Ubuntu this might be platform specific, maybe an unsatisfied dependency. But it does not even work with the build environment.

------------------------

### Environment

    / # tesseract -v
    tesseract 4.0.0-beta.3
     leptonica-1.76.0
      libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0
     Found AVX2
     Found AVX
     Found SSE

* **Tesseract Version**: 4.0.0-beta.3
* **Commit Number**: master
* **Platform**: Linux bb2a6f4f39a9 4.4.0-116-generic 140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 Linux

**Comment by gamma** [comment]
Thx, I’ll check the option.

**Comment by gamma** [comment]
I checked the option @nguyenq. It does indeed work. I still wonder why this happens, because the libs are there at build and runtime ...

**Comment by amitdo** [comment]
It's not a problem in tesseract itself.

@zdenop, please close this issue.
