### ISSUE TITLE
set whitelist in Tesseract4

### ISSUE THREAD

**Issue by andylanse** [tesseract-ocr/tesseract#1869]
hello ,I have a quesstion :
Recently, I'm using Tesseract4.0. but I found that it's no use to set withelist.
my codes as follows:(C++)

        TessBaseAPI *handle;
	handle = TessBaseAPICreate();
	//load tessdata and set language
	if (TessBaseAPIInit3(handle, tessdataPath.c_str(), "eng") != 0)
		die("Error initialising tesseract\n");

	if(!TessBaseAPISetVariable(handle, "tessedit_char_whitelist", ",.0123456789"))
		die("Error setVariable t\n");

Is it OK of my codes?

**Comment by Shreeshrii** [comment]
Whitelist not supported in tesseract4.

**Comment by andylanse** [comment]
It's a good way to improve the accuracy rate if set whitelist.
Why abolish whitelist in Tesseract4 ? 
I can't accept that.

**Comment by Shreeshrii** [comment]
This is a known issue - see https://github.com/tesseract-ocr/tesseract/issues/751
