### ISSUE TITLE
tesseract 3.04 hocr and hocr2pdf

### ISSUE THREAD

**Issue by eric-blabla** [tesseract-ocr/tesseract#187]
There seems some communication problem between tesseract 3.04 (package on debian stretch) and hocr2pdf 0.91 (package on debian stretch as well): whereas the tesseract output (up to a stupid xml tag) is a readable html and quite nice to look at ; but hocr2pdf will make VERY messy pdf's.

It seems that I am not alone to experience these problems, see e.g.
http://w3foverflow.com/question/tesseract-and-hocr-on-ubuntu-14-04/

How to make an example? Step 1: scan a messy, double page, Step 2: nice it up using scantailor, then use the output tiffs (in the "out" directory) ; Step 3: these are passed to tesseract with hocr option.   Step 4: finally invoke 

hocr2pdf -n -i image.tif  -o test.pdf  < image.hocr

By virtue of the "-n" option, you only see the (malformed) ocr output which is not overlayed by the right image.

It is unclear to me if this is an tesseract issue or an hocr2pdf issue, of course.

Cheers, Eric

**Comment by jbreiden** [comment]
It's best by far to produce PDF directly from Tesseract. If you really have to go via HOCR for some weird reason, use https://github.com/tmbdev/hocr-tools/blob/master/hocr-pdf instead of hocr2pdf.

**Comment by amitdo** [comment]
hocr2pdf's issues should be reported to hocr2pdf's developers.

@zdenop, please close this issue.
