### ISSUE TITLE
Confused on lstm training logic

### ISSUE THREAD

**Issue by zwwlouis** [tesseract-ocr/tesseract#1871]
Environment
Tesseract Open Source OCR Engine v4.0.0-beta.4-18-g4370
Linux bogon 3.10.0-862.3.3.el7.x86_64

### Current Behavior:
During Phase E (generate lstm file), tesseract always failed to give lstmf on pictures which can't be recognize by best-traineddata.
e.g.  render some number with a special font and exposure=-6
        It gave out "Empty page!" error  and process failed as lstmf didn't appear
![test](https://user-images.githubusercontent.com/4935248/44722917-293d4b80-ab01-11e8-933d-3a0a28c99146.jpg)
It seems that tesseract needs to recognize picture first before create training data.  And if recognization failed, whole process failed.
I was just confuse on this logic through training process
As I create some special data to adjust lstm+CTC network, I'm not expecting tesseract to recognize them at first time. 
On the other hand, if tesseract can give the almost right answer even before create lstmf, what's the meaing of the custom training by user?

Another phenomenon is that  there are so many "No block overlapping textline" errors
As tif/box file have already been given,  It is unreasonable to give these message
Obvisously, OCR engine make a judge on picture, and find something error.  why not just read position information from .box file?  It is precisely correct.

**Comment by zwwlouis** [comment]
here is my true type file
[xinshi.zip](https://github.com/tesseract-ocr/tesseract/files/2328105/xinshi.zip)

**Comment by zwwlouis** [comment]
Thank you so much for your attention.
The error occur when I use these simple numbers alone, not with eng.traing_text 
In my opinion, if you mix up these number with eng.training_text together, the word number become much largerer. The .tif pages are obviously not "Empty Page" again.
A page analysis goes before word recognization ,(am I right?) so the "Empty Page" error will block the trainging
But why the page is empty or not so important to training? Since we have pictures and Its precisely correct position data saved in box files.
 If ocr engine meet some words or fonts it never seen before, empty page is frequently occur. And these 'empty' data will be thrown out of the training set which, in the end, will not  training on some special case very well.

**Comment by Shreeshrii** [comment]
I have tested with your text file. I am not getting 'Empty Page'.

What is the output for?

`tesseract -v'
`text2image -v'

Please test again using the latest code from GitHub and report.

**Comment by zwwlouis** [comment]
`tesseract -v`
tesseract 4.0.0-beta.4-18-g4370
 leptonica-1.74.4
  libjpeg 6b (libjpeg-turbo 1.2.90) : libpng 1.5.13 : libtiff 4.0.3 : zlib 1.2.7 : libwebp 0.3.0

`text2image`
4.0.0-beta.4-18-g4370

I use '--underline_start_prob 0.5'  in text2image

**Comment by zwwlouis** [comment]
[tif_box_exp-5.zip](https://github.com/tesseract-ocr/tesseract/files/2336133/tif_box_exp-5.zip)
I'v upload tif/box file here, error can be made with command below 
`/usr/local/bin/tesseract /home/tmp/eng/eng.xinshi.exp-5.tif /home/tmp/eng/eng.xinshi.exp-5 lstm.train`
Is there something wrong with my tif/box file? Thanks again.

**Comment by zwwlouis** [comment]
solved
