### ISSUE TITLE
Some tesseract language packages are not available

### ISSUE THREAD

**Issue by stefanievonk** [tesseract-ocr/tesseract#1873]
### Environment

* **Tesseract Version**: tesseract 4.0.0-beta.4-50-g07acc
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE
* **Platform**: Ubuntu 18.04

### Current Behavior:
E: Unable to locate package tesseract-ocr-chi_sim
E: Unable to locate package tesseract-ocr-chi_tra
E: Unable to locate package tesseract-ocr-equ
E: Package 'tesseract-ocr-kur' has no installation candidate
E: Unable to locate package tesseract-ocr-tgl

### Expected Behavior:
Language packages are installed using apt-get install

**Comment by Shreeshrii** [comment]
@AlexanderP Please advise.

**Comment by zdenop** [comment]
We did not created this packages - you should consult directly problem with Ubuntu support.

**Comment by stweil** [comment]
The correct package names are `tesseract-ocr-chi-sim` and `tesseract-ocr-chi-tra`.
`tesseract-ocr-equ` and `tesseract-ocr-tgl` were only available for Tesseract 3.0x.
Ubuntu bionic has `tesseract-ocr-kur-ara`.
Use https://packages.ubuntu.com/ to search for other packages
