### ISSUE TITLE
Tesseract crashes during ClearResults() call

### ISSUE THREAD

**Issue by flagvadim** [tesseract-ocr/tesseract#1875]
### Environment

* **Tesseract Version**: 3.05.00dev
* **Commit Number**: 8972c0e91653bf6e4c946715b8f2f8b58c670085
* **Platform**: Windows 7 64-bit
* **Compiled**: using MS Visual Studio 2015 as DLL with /MD /MP /Zi /DEBUG flags, target platform x86.

### Current Behavior:
Tesseract crashes from time to time. By some reason I cannot reproduce this issue locally. But two different users of my system observe crashes. For them, usually it takes about 10-30 minutes to reproduce the issue. Stack trace is almost always as shown below.

Stack trace:
`
	tesseract305.dll!ELIST::internal_clear(void(*)(ELIST_LINK *) zapper) Line 53	C++
 	tesseract305.dll!GENERIC_2D_ARRAY<BLOB_CHOICE_LIST *>::delete_matrix_pointers() Line 196	C++
 	tesseract305.dll!WERD_RES::ClearResults() Line 1169	C++
 	tesseract305.dll!WERD_RES::Clear() Line 1138	C++
 	tesseract305.dll!WERD_RES::~WERD_RES() Line 1086	C++
 	tesseract305.dll!WERD_RES_zapper(ELIST_LINK * link) Line 33	C++
 	tesseract305.dll!ELIST::internal_clear(void(*)(ELIST_LINK *) zapper) Line 53	C++
 	tesseract305.dll!ROW_RES_zapper(ELIST_LINK * link) Line 33	C++
 	tesseract305.dll!ELIST::internal_clear(void(*)(ELIST_LINK *) zapper) Line 53	C++
 	tesseract305.dll!BLOCK_RES_zapper(ELIST_LINK * link) Line 32	C++
 	tesseract305.dll!ELIST::internal_clear(void(*)(ELIST_LINK *) zapper) Line 53	C++
 	tesseract305.dll!tesseract::TessBaseAPI::ClearResults() Line 2346	C++
 	tesseract305.dll!tesseract::TessBaseAPI::InternalSetImage() Line 2228	C++
 	tesseract305.dll!tesseract::TessBaseAPI::SetImage(Pix * pix) Line 551	C++
`

I am attaching sources, mostly for reference. This is not real code that I use.  I removed most of internal stuff not related to Tesseract.

[src.zip](https://github.com/tesseract-ocr/tesseract/files/2329226/src.zip)

Do you have any clue what can cause crashes? Thank you.

### Expected Behavior:
No crash.

**Comment by stweil** [comment]
@flagvadim, release `3.05.00 is an old release. Please use always the latest releases (here 3.05.02) which typically contain bug fixes. I also suggest to update to 4.0.0-rc1. Re-open the issue if the crash still occurs with current releases and add more information then. We need at least the exact command line and the image and traineddata used for the OCR.
