### ISSUE TITLE
When i use tesstrain.sh with other font for chi_sim.. get error : Could not find font named

### ISSUE THREAD

**Issue by XinAlo** [tesseract-ocr/tesseract#1877]
I used tesstrain.sh to create tif/box for chi_sim . The font is run ok which i copy from windows ..but i used other font which download from network , I get the error follow:
I run :
> training/tesstrain.sh --fonts_dir /home/tesseract_train/font --lang chi_sim --linedata_only --noextract_font_properties --langdata_dir ~/to/langdata-master --tessdata_dir ~/tesseract/tessdata --fontlist 'lishu' output_dir ~/tesstutorial/chi_sim_train

Get Error: 
=== Starting training for language 'chi_sim'
[Wed Aug 29 07:31:23 UTC 2018] /usr/local/bin/text2image --fonts_dir=/home/tesseract_train/font --font=lishu --outputbase=/tmp/font_tmp.xrbgQlxgph/sample_text.txt --text=/tmp/font_tmp.xrbgQlxgph/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.xrbgQlxgph
Could not find font named lishu.
Pango suggested font Microsoft YaHei.
Please correct --font arg.

=== Phase I: Generating training images ===
Rendering using lishu
[Wed Aug 29 07:31:25 UTC 2018] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.xrbgQlxgph --fonts_dir=/home/tesseract_train/font --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/chi_sim-2018-08-29.fE2/chi_sim.lishu.exp0 --max_pages=0 --font=lishu --text=/root/to/langdata-master/chi_sim/chi_sim.training_text
Could not find font named lishu.
Pango suggested font Microsoft YaHei.
Please correct --font arg.
ERROR: /tmp/chi_sim-2018-08-29.fE2/chi_sim.lishu.exp0.box does not exist or is not readable
Rendering using output_dir
[Wed Aug 29 07:31:26 UTC 2018] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.xrbgQlxgph --fonts_dir=/home/tesseract_train/font --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/chi_sim-2018-08-29.fE2/chi_sim.output_dir.exp0 --max_pages=0 --font=output_dir --text=/root/to/langdata-master/chi_sim/chi_sim.training_text
Could not find font named output_dir.
Pango suggested font Microsoft YaHei.
Please correct --font arg.
ERROR: /tmp/chi_sim-2018-08-29.fE2/chi_sim.output_dir.exp0.box does not exist or is not readable

### Please help me ### , THK

**Comment by XinAlo** [comment]
system :  ubuntu 16.04
run in docker container  ubuntu 16.04

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking support.
