### ISSUE TITLE
Q&A : How to Run Tesseract ON GPU

### ISSUE THREAD

**Issue by shanalikhan** [tesseract-ocr/tesseract#1880]
Can anyone help, i have NVIDIA Card 2GB delicated with Cuda Installed.
I want to setup Tesseract that it only use GPU memory not CPU.

Currently on training, i am getting these from system viewer:
**80% + CPU USAGE**

![maanger](https://user-images.githubusercontent.com/8774556/44784679-e7b3ab80-aba7-11e8-86ea-a053ed39602e.png)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking support.
