### ISSUE TITLE
Tesseract performed not good when LSTM trained with out of box data files

### ISSUE THREAD

**Issue by shanalikhan** [tesseract-ocr/tesseract#1881]
I have tried to run the tesseract with the .traineddata file that LSTM produced by training.
Results are poor compared compared with .traineddata file i have downloaded from the Git Repo.

**First Approach** - Out of box ( by default )

Initially i run the tesseract by having the .trainedata file from git Repo.
Here are the results:
```
Mary Jane Snith
100 Pine Streat

 

 

 

rdTech Bank Statement Sample

  

For Mar 15, 2010 to Apr 18, 2010
Account Mumber
```

**Second Approach**

I trained LSTM  using that the  .traineddata file generated by `tesstrain.sh` with out of box english lang data.
I run tesseract using .traineddata file generated by LSTM, here are the results

```
  

 

Mas i . (ae . IM {i
00.. uw . L4 L

 

 

 

28883

  

fru Ne [. [ = A' [4, 7 t
An "' Nw
```

My question is am i missing something as LSTM is trained from the `.traineddata` that is generated with out of box english data.

**Comment by Shreeshrii** [comment]
Please do not open issues if you just have a question. This is only for BUGS.

>LSTM is trained from the .traineddata that is generated with out of box english data.

You followed instructions for a **tutorial** which states clearly that it is using training data that is totally inadequate for LSTM training. It is ONLY for demonstrating  the training procedure.

If you read the training wiki page that I referred you to, you would have seen that training a language from scratch requires thousands of lines of training data, millions of iterations and will take days/weeks to complete.

Please read the wiki page in full. 

Close this issue.

**Comment by shanalikhan** [comment]
Okay, thanks.
