### ISSUE TITLE
Tesseract 3 & 4 both fail to process image with a single word

### ISSUE THREAD

**Issue by FarhadKhalafi** [tesseract-ocr/tesseract#1891]
This is a simple PNG file with the word Hello! in the middle. I tried both Tesseract 3.05 and 4.00 and both did not return anything. I even tried on grayscale, thresholded and darkened images.
![hello](https://user-images.githubusercontent.com/8490589/44949104-ae697e80-ade7-11e8-9e4f-023d4747daaa.png)

I am new to Tesseract and might not be doing everything right. Some online OCR providers also failed, but others succeeded, so it cannot be the image. Do I need to train the engine? I have english training files and the engine works in general, but not for this simple case. Thanks!

**Comment by Shreeshrii** [comment]
try with --psm 6 
page segmentation mode

**Comment by FarhadKhalafi** [comment]
This was a user error. I was using the wrong page segmentation mode. Sorry about it.

**Comment by FarhadKhalafi** [comment]
The above image has a white border outside the blue rectangle. If I remove the white border then it works. Same result in Tesseract 3.05 4.0 binaries and 4.0 beta source as of 8/31/2018.

**Comment by zdenop** [comment]
it is not bug - it is a feature ;-). You need to pre-process you image to provide text areas only for OCR for best result. (see e.g. blog post [Deep Learning based Text Recognition (OCR) using Tesseract and OpenCV](https://www.learnopencv.com/deep-learning-based-text-recognition-ocr-using-tesseract-and-opencv/))
