### ISSUE TITLE
TesseractConfig.cmake

### ISSUE THREAD

**Issue by Pastor** [tesseract-ocr/tesseract#190]
After cmake generation, `TesseractConfig.cmake` not contains `ccutil` include directory. And when i try use `TesseractConfig.cmake` in my build - receive error `platform.h not found`

**Comment by zdenop** [comment]
@egorpugin Can you have a look on this?

**Comment by egorpugin** [comment]
What headers should be public?
I thought all headers from api/

Tesseract really has bad directories structure.
Probably it should be reorganized as in many other projects.
include - public includes
src/[subdirs] - dir with sources and private headers

**Comment by zdenop** [comment]
At least headers that are mentioned in "include_HEADERS" in Makefile.am should be installed/public.
Each directory has its own Makefile.am...

**Comment by egorpugin** [comment]
While using tesseract with TesseractConfig.cmake (without install), we can include several directories.
So, unintentionally we will give an access to all headers from those dirs. Not only to "include_HEADERS".
Users won't know it and could use noinst headers, so later they'll have issues.

**Comment by egorpugin** [comment]
Fixed in 7b94871ba20
