### ISSUE TITLE
Tesseract - GetUTF8Text on Words boundary vs Line Boundary

### ISSUE THREAD

**Issue by kkurni** [tesseract-ocr/tesseract#1906]
### Environment

* **Tesseract Version**: 3.05.02
* **Commit Number**: 
* **Platform**:
Mac - Darwin 186590d0071d.ant.amazon.com 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64

tesseract 3.05.02
 leptonica-1.76.0
  libjpeg 9c : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.8

### Current Behavior:
I notice that GetUTF8Text on Word boundary returns different / worst text results compare to Line boundary.

    boxes = api.GetComponentImages(tr.RIL.WORD,True)
    # get full text
    full_text = api.GetUTF8Text()
    print("FULL TEXT", full_text)
        
    for i, (im, box, block_id, paragraph_id) in enumerate(boxes):
        text = api.GetUTF8Text()

The full text and the text return different results.
The Full-text results are better than the word text.

Based on this suggestion, I tried to use different PSM mode. But even with "SINGLE_LINE" PSM mode, it still produces worst text results
https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

Here is the image.
![screen shot 2018-09-13 at 1 02 38 pm](https://user-images.githubusercontent.com/698547/45512681-4e62c880-b755-11e8-8f4c-6ed978d047a6.png)

Here is the full line text detection with AUTO-OSD PSM
![screen shot 2018-09-13 at 1 03 29 pm](https://user-images.githubusercontent.com/698547/45512715-74886880-b755-11e8-9d8b-acc06bbf27ad.png)

Here is the Word Text detection with AUTO-OSD
![screen shot 2018-09-13 at 1 04 37 pm](https://user-images.githubusercontent.com/698547/45512759-97b31800-b755-11e8-8f57-446baeccc05f.png)
 PSM

Here is the Word Text detection with SIngle Line PSM
![screen shot 2018-09-13 at 1 03 38 pm](https://user-images.githubusercontent.com/698547/45512732-8702a200-b755-11e8-8412-7bdf7cc7c6c4.png)

### Expected Behavior:
I am expecting the same text results produces from line/words detection.

Is there any reason why Text Results are produced differently from Line vs Word detections?

**Comment by amitdo** [comment]
Please provide the input image and the full commands you used.

You should note that the current development focus is on the 4.0.0 version and its new CNN+LSTM based OCR engine.

**Comment by kkurni** [comment]
I just added the image and the code.

Do you think the word text will be solved in the LSTM version?

**Comment by amitdo** [comment]
Related: #1231, #1004

**Comment by kkurni** [comment]
Great, that iterator API is better.

Thanks

**Comment by zdenop** [comment]
So is your issue solved?
