### ISSUE TITLE
Tessaract LibPng libJpeg Dependecies

### ISSUE THREAD

**Issue by kkurni** [tesseract-ocr/tesseract#1909]
------------------------

### Environment

* **Tesseract Version**: Tessaract 3.5
* **Platform**: Redhat

### Current Behavior:
When I installing Tessaract manually, I did not see the LibPng / libJpeg dependencies.
I can find libJpeg/ libpng on my lib directory

tesseract --version
tesseract 3.05.02
 leptonica-1.72
  zlib 1.2.8

### Expected Behavior:
Something like this:

tesseract 3.05.02
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.2

How do I debug this?
Is there any way to check where the Tessaract find that LibPNG library?

Thanks

**Comment by zdenop** [comment]
It is not tesseract issue - tesseract does not use any image library dirrectly. Tesseract use only leptonica.
You need to fix your leptonica build.
