### ISSUE TITLE
Lack of ICU DLL files for latest release pre-built for Windows

### ISSUE THREAD

**Issue by CJFreePy** [tesseract-ocr/tesseract#1911]
Just installed the latest version on Win7 x64 ( released on 0912).
It shows error - "no ICUUC57.dll , icudata57.dll files"  when using "unicharset_extractor" command.
For 0608 version, they exist (under tesseract dir) and work fine.
Guess they were missed when build?

**Comment by stweil** [comment]
I fixed the [download](https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v4.0.0-beta.4.20180912.exe) (same executables, only added the two missing DLL files). The issue can be closed.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
