### ISSUE TITLE
Can't recognize certain Russian Cyrillic variants

### ISSUE THREAD

**Issue by MarjaE2** [tesseract-ocr/tesseract#1912]
Sorry I can't provide a free test case. Some early Soviet-era Russian Cyrillic texts make Л and Д look like Λ and Δ. I don't know if I have "fast" or "best" rus.traineddata, but the version I have reads these letters as А.
------------------------

### Environment

* **Tesseract Version**: 3.05.02
* **Commit Number**: 
* **Platform**: Darwin [name]MacBook.fios-router.home 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64

### Suggested Fix: perhaps a wider range of samples for training?

**Comment by zdenop** [comment]
You are not willing to share input images than you are alone with you problems.
You can try to use current code with the tessdata_best or tessdata_fast.

**Comment by MarjaE2** [comment]
And how am I supposed to switch from one tessdata to the other?

**Comment by MarjaE2** [comment]
This has the alternative L but not the alternative D:

https://archive.org/details/B-001-017-874/page/n11

**Comment by zdenop** [comment]
First of all need to install tesseract 4. Then you can have several tessdata folders and you will change TESSDATA_PREFIX environment variable to right place .e.g.:

```
export TESSDATA_PREFIX=/opt/tessdata
tesseract i1912.jpg i1912_tessdata -l rus

export TESSDATA_PREFIX=/opt/tessdata_best
tesseract i1912.jpg i1912_tessdata_best -l rus

export TESSDATA_PREFIX=/opt/tessdata_fast
tesseract i1912.jpg i1912_tessdata_fast -l rus
```
