### ISSUE TITLE
Documentation says 'to be fixed in 3.02' but current version is 3.04

### ISSUE THREAD

**Issue by diotteo** [tesseract-ocr/tesseract#192]
Here is the excerpt:

“Any language that has different punctuation and numbers is going to be disadvantaged by some of the hard-coded algorithms that assume ASCII punctuation and digits. To be fixed in 3.02.”

from https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#background-and-limitations

**Comment by tfmorris** [comment]
The nice thing about a wiki is that anyone can edit it.  I'm pretty sure none of this is hardcoded any more and, if you agree, you can update the wiki page to match the current reality.

**Comment by diotteo** [comment]
It depends, not all Wikis have open sign up or give access to anyone for that matter.

I see that in the case of Tesseract on github, I could edit it myself indeed, thanks for the information.

That being said, I haven't investigated the issue, so I don't know what the current status is. In my opinion, it is better to report the issue without fixing it rather than just not fix it. I'll try to look into this later.

**Comment by amitdo** [comment]
@diotteo
This info is indeed outdated. I removed it from that page.

Thanks for reporting.

@zdenko, please close this issue.

**Comment by amitdo** [comment]
Maybe instead of complete removal it's better to edit the paragraph;

> For versions prior to 3.02, any language that has different punctuation and numbers is going to be disadvantaged by some of the hard-coded algorithms that assume ASCII punctuation and digits.

**Comment by amitdo** [comment]
@zdenop, any preference?

**Comment by amitdo** [comment]
I edited it again;

> For versions 3.00/3.01, any language that has different punctuation and numbers is going to be disadvantaged by some of the hard-coded algorithms that assume ASCII punctuation and digits. [Fixed in 3.02]

**Comment by amitdo** [comment]
@zdenop, please close this issue.
