### ISSUE TITLE
image too large from Langdata_lstm

### ISSUE THREAD

**Issue by dewringmaster** [tesseract-ocr/tesseract#1922]
Tesseract Open Source OCR Engine v4.0.0-beta.4-18-g4370
text2image 4.0.0-beta.4-18-g4370

Now, I'm making train( 2 fonts) and eval (1 font) set by using langdata_lstm 
for finetune tessdata_best (Thai Language)
In finetune process 
ERROR: image too large!!!
 How to fix this?
Should i use langdata_lstm or langdata instead?

**Comment by anonynamja** [comment]
https://github.com/tesseract-ocr/tesseract/issues/590

**Comment by Shreeshrii** [comment]
>Now, I'm making train( 2 fonts) and eval (1 font) set by using langdata_lstm
for finetune tessdata_best (Thai Language)

The training_text in langdata_lstm is very large (many MBs). For finetuning you don't need the whole thing, you can try to limit number of pages using --max_pages in tesstrain.sh or create a smaller subset of training_text having samples of all characters and compound glyphs from the file in langdata_lstm  .
