### ISSUE TITLE
'NoneType' object is not iterable issue when iterate bounding box

### ISSUE THREAD

**Issue by kkurni** [tesseract-ocr/tesseract#1924]
### Environment

* **Tesseract Version**: 3.5.0 and 4.0
* **Platform**: mac & ubuntu 18.04

### Current Behavior:

I am iterating over recognize api as suggested here. "Result iterator example"
https://github.com/tesseract-ocr/tesseract/wiki/APIExample

it seems we do before calling next. If I am calling next first, it will skip over the first detections.

Unfortunately when I get this error, 
**'NoneType' object is not iterable issue**
When there is no detection.

Here is the code in python-tesserocr
 if (iterator != None):
        next = True
        while (next):
            x,y,right,bottom = iterator.BoundingBox(level)
                        
            next = iterator.Next(level)

it throws an error on iterator.BoundingBox saying that the iterator is empty.

If I call "next = iterator.Next(level)" first, it avoids that error, but it also skip over the first detection

Here is the image, just the whitespace image
![white-space](https://user-images.githubusercontent.com/698547/45849852-8c796280-bce8-11e8-9b06-196d8909d297.png)

### Expected Behavior:
It should not throw an exception, or I can call HasNext API

### Suggested Fix:
Is there any HasNext API that I can call?

Thanks

**Comment by amitdo** [comment]
It's not a bug in tesseract. You just don't use the API correctly.

Check the baseapi.cpp code to understand how to use the API correctly.

Please use our forum for getting support.

**Comment by kkurni** [comment]
From this API samples, https://github.com/tesseract-ocr/tesseract/wiki/APIExample
How do you detect the iterator returns no item in the beginning.
 ri->GetUTF8Text(level);

I am expecting there is a way to check "HasNext" whether there is next item in the iterator before calling GetUTF8Text(level);

> Pix *image = pixRead("/usr/src/tesseract/testing/phototest.tif");
>   tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
>   api->Init(NULL, "eng");
>   api->SetImage(image);
>   api->Recognize(0);
>   tesseract::ResultIterator* ri = api->GetIterator();
>   tesseract::PageIteratorLevel level = tesseract::RIL_WORD;
>   if (ri != 0) {
>     do {
>       const char* word = ri->GetUTF8Text(level);
>       float conf = ri->Confidence(level);
>       int x1, y1, x2, y2;
>       ri->BoundingBox(level, &x1, &y1, &x2, &y2);
>       printf("word: '%s';  \tconf: %.2f; BoundingBox: %d,%d,%d,%d;\n",
>                word, conf, x1, y1, x2, y2);
>       delete[] word;
>     } while (ri->Next(level));
>   }

Thanks

**Comment by amitdo** [comment]
The wiki sometimes has mistakes.

The best examples how to use the API are in baseapi.cpp, which the tesseract program itself uses.

https://github.com/tesseract-ocr/tesseract/blob/5d22fdfeed901ec8b73c2f490ba84da9414f1b79/src/api/baseapi.cpp#L1511

**Comment by amitdo** [comment]
also check the documentation/examples/tests of the tesseract's Python binding you are using.
