### ISSUE TITLE
Recognition fails with assertion contains_unichar_id(unichar_id)

### ISSUE THREAD

**Issue by FarhadKhalafi** [tesseract-ocr/tesseract#1925]
### Environment

* **Tesseract Version**: 4.0.0-beta3
* **Commit Number**: 
* **Platform**: Windows 10 (32-bit Tesseract) 

### Current Behavior:
Fails to recognize a one page Tiff image with this message

contains_unichar_id(unichar_id):Error:Assert failed:in file c:\projects\github\tesseract-ocr\src\ccutil\unicharset.h, line 511

### Expected Behavior:
Works in Tesseract 3

### Suggested Fix:
Would like to understand what this assertion means. It looks like a check on an internal table index before the table is accessed. I think the table holds Unicode classes. Cannot share the image as it has sensitive data. Can diagnose with some help.

**Comment by stweil** [comment]
@zdenop, please add label _duplicate_ and close this issue.

**Comment by FarhadKhalafi** [comment]
Duplicate #1205
