### ISSUE TITLE
language file available but fails to load with --psm1 --oem 0

### ISSUE THREAD

**Issue by CanadianHusky** [tesseract-ocr/tesseract#1927]
I have 3 different versions of Tesseract installed.
I have ensured that Environment variable points to correct path for tessdata folder

![image](https://user-images.githubusercontent.com/35332003/45925355-1eb57c80-bf1c-11e8-904b-ed1d46dcde23.png)

![image](https://user-images.githubusercontent.com/35332003/45925335-fc236380-bf1b-11e8-9df6-8799bf248a77.png)

can someone please explain this behaviour ?
language is detected and listed as available, but fails to be loaded when processing is required

**Comment by zdenop** [comment]
Multiple installation of tesseract is not supported as it is know to produce problems ;-) 

Anyway if you get such error can you post also output of `echo %TESSDATA_PREFIX%` and `dir %TESSDATA_PREFIX%`?

**Comment by CanadianHusky** [comment]
Sure. The environment variable seems correct. 

'dir %TESSDATA_PREFIX%' gives error, no surprize. what was it supposed to do anyways ?

directory listing and commands are attached. 
![image](https://user-images.githubusercontent.com/35332003/45932837-56a7d880-bf8b-11e8-9428-7f5a6602d68b.png)

**Comment by zdenop** [comment]
> 'dir %TESSDATA_PREFIX%' gives error, no surprize.

Why no surprise?

> what was it supposed to do anyways?

It should provide listing of files in %TESSDATA_PREFIX%. If  'echo %TESSDATA_PREFIX%' works, also this command has to works too.

Your output indicates that you use trainnedata from tessdata_fast (lstm), but you instructed tesseract to use legacy engine only. So tesseract is correct it can not load eng legacy data from lstm only data file. Use files from [correct repository](https://github.com/tesseract-ocr//tessdata/).

Option `--list-langs` only provide list of trainneddata files (e.g. it did not try to load them) and does not guarantee they will work. It is up to user to know what (s)he is doing.

**Comment by CanadianHusky** [comment]
understood. thank you.
