### ISSUE TITLE
Text-line Extraction based on Deep Learining [Feature Wanted]

### ISSUE THREAD

**Issue by ghost** [tesseract-ocr/tesseract#1932]
@theraysmith @stweil @egorpugin @Shreeshrii @amitdo 
Thank you for your hard work.

**Concept:**
Implement a deep learning model for page layout analysis, such model could extract text-lines.
The idea is simple, we train a model with ground-truth images & their annotated pixel baselines.
Later-on, the model would try to predict the baselines by itself, & finally extract each text-line.

**Benefit:**
 A layout analysis model based on deep learning could extract text-lines even in the most complex layouts, also when the layout contains many elements, such as: (images, tables, degradation, handwriting).

**Current situation of Tesseract:**
Tesseract works best on black&white pages with simple layouts, and are mostly printed text-lines.

**Example projects:**
https://dhlab-epfl.github.io/dhSegment/
https://github.com/dhlab-epfl/dhSegment
https://github.com/NVlabs/ocroseg
https://github.com/mittagessen/seg/tree/baseline
https://github.com/PRHLT/BaseLinePage
https://github.com/TobiasGruening/ARU-Net
https://github.com/lquirosd/P2PaLA
https://github.com/gaxler/dataset_agnostic_segmentation
https://github.com/watersink/ocrsegment

**Demonstrations:**

**Training**
![download](https://user-images.githubusercontent.com/33478216/46105481-c235b400-c1de-11e8-9cad-01d1fea48bf7.png)

**Detection**
![46105481-c235b400-c1de-11e8-9cad-01d1fea48bf7](https://user-images.githubusercontent.com/33478216/46106051-57857800-c1e0-11e8-8a43-a3e22135ba6c.png)

**Another Line Detection example**
![cbad](https://user-images.githubusercontent.com/33478216/46105431-9ca8aa80-c1de-11e8-9be1-4ee20e12187b.jpg)

**Comment by Shreeshrii** [comment]
@zdenop Please label as `Feature Request`.

**Comment by balachandarsv** [comment]
Here is another deep learning work which works pretty well.
https://github.com/argman/EAST

**Comment by MrOCR** [comment]
Text Line Segmentation for Challenging Handwritten Document Images using Fully Convolutional Network
https://github.com/beratkurar/textline-segmentation-using-fcn
https://www.cs.bgu.ac.il/~berat/papers/Icfhr2018Text.pdf
https://www.cs.bgu.ac.il/~berat/papers/Icfhr2018TextPoster.pdf

**Comment by amitdo** [comment]
@MrOCR. thanks for the links.

**Comment by amitdo** [comment]
We don't plan to implement this feature request.
