### ISSUE TITLE
Tesseract-ocr 4.0 on Indian number plate 

### ISSUE THREAD

**Issue by Aayushktyagi** [tesseract-ocr/tesseract#1933]
I am planning to perform ocr on Indian number plates using  tessract 4.0 beta which uses LSTM . Although recognized characters are not coming out to be correct. I used cv2.Laplacian() while picking up images without blur and performed noise reduction using cv2.fastNlMeansDenoisingColored() on the image . Still results seems not so accurate.

1)Can you please suggest what kind of noises tesseract is more sensitive toward so that i can eliminate them in prepossessing phase?
2)Is there a way to disable special characters in tesseract 4.0(using LSTM).
These are some sample images 
![36](https://user-images.githubusercontent.com/32107805/46134560-cacece80-c260-11e8-9948-c182b1f5a28d.jpg)
![93](https://user-images.githubusercontent.com/32107805/46134561-cacece80-c260-11e8-8fca-c9f72f3926c1.jpg)

Detected text 
*DLBCAUS368 “HR 10¥5803

Thanks in advance

**Comment by zdenop** [comment]
Please respect guidelines for posting issues: use tesseract user forum for asking support.
