### ISSUE TITLE
Arabic + English Language 

### ISSUE THREAD

**Issue by MariamHijazi** [tesseract-ocr/tesseract#1934]
I'm trying to use Tesseract for multiple language document. I use English+ Arabic tessData for Arabic + English file 
![traditionalarabic](https://user-images.githubusercontent.com/42976910/46143022-6f511080-c261-11e8-96c1-514d79891b72.jpg)
I get Result contain Arabic but all English word are digits 

Result : 

'جوجل 600916 " يستعد لاقتحام أدمغتنا
الاحد 9 سبتمبر 2018

الاقتصادية" من الرياض"

هل حَدث وأن بحَثث عن ن عبر وتفاجأت باقترإحخات عديدة لاحقاً على حسابك في ?Facebook «lsasis? لشركاتٌٍ توفر مُنْتَجَاتٍ مُشَابِهَة؟ الأمر
ليس صُدفة؛ ولكن ذلك يندرج ضمن استراتيجيات يتبنّاها عَمالقة التقنية للتأثير في قراراتنا الشّرائية.

وساهمت الشّبكة العنكبوتية في جَعل عملية جمع بياناث المستخدمين أكثر سهولة من أي وقت مضى؛ مع ترك هؤلاء لآثارهم الرقمية في العديد من المواقع
والتطبيقات» والتي تكون هدفا لشركات التكنولوجيا المَدعومة بترسانة من تقنيات الذكاء الاضطناعي 10161196006 ل2أ00تائم.

وبيّتت دراسة صَادرة عن باحثّن في جامعة 'برينستون" الأميركية؛ أن 6009/6 ترصد تحرّكات ما يزيد عن ملياري شخص حول العالم؛ ممن يشتعملون
أجهزة وهواتف تعمل نظام التشغيل الشُهير ?"Android"? بحسب ما ذكرت

وأكد تقرير لوكالة الأسوشيتد برس 55٤۲م ?Assiciated? أن الكثير من خدمات جوجل على أجهزة آيفون 1511006 وآندرويد 70 تخرّن بيانات

مواقع المستخدمين» حتى وإن قاموا بإيقاف تشغيل خدمات تحديد الموقع الجغرافي بتغيير إعدادات الخصوصية المتوفرة في تلك الأجهزة.
Is there any solution for this problem ?
Regards.

**Comment by amitdo** [comment]
Please post the full command you used.

**Comment by MariamHijazi** [comment]
I'm using TessBaseAPI in C# Tesseract 4.00 alpha with Leptonica
with this Code.
 string dataPath = ConfigurationManager.AppSettings["DataSet"];
string language = "ara+eng";
OcrEngineMode oem = OcrEngineMode.DEFAULT;
PageSegmentationMode psm = PageSegmentationMode.AUTO_OSD;
TessBaseAPI tessBaseAPI = new TessBaseAPI(dataPath, language, oem, psm);
tessBaseAPI.Init(dataPath, language, oem);
Pix pix = tessBaseAPI.SetImage(imageFilePath);
if (pix != null)
{
       tessBaseAPI.Recognize();
       stringBuilder = tessBaseAPI.GetUTF8Text();
       tessBaseAPI.Dispose();
       pix.Dispose();
}

**Comment by MariamHijazi** [comment]
Sorry , I’m using tesseract.net version 4.0.16 which is installed from Nuget , is it alpha or beta version?

**Comment by zdenop** [comment]
There has be several report like this (e.g. #235). Please search for "Arabic" in issue tracker.
Anyway when I tried 4.0 version with tessdata_best I got IMO better result
[i1934.txt](https://github.com/tesseract-ocr/tesseract/files/2431795/i1934.txt), but I am not familiar with Arabic ;-)

**Comment by MariamHijazi** [comment]
Actually , I'm trying to get it in different Arabic  font type, in some I get English word but in another I get it as digits 
for example : in this image with Arabic Traditional font type 
![traditionalarabic](https://user-images.githubusercontent.com/42976910/46275178-b04c6c00-c564-11e8-8090-e70b87d72358.jpg)
I get all text 
 

TraditionalArabic
?يستعد لاقتحام أدمغتنا? " Goo gle Js"
2018 ?الاحد 9 سبتمير?

الاقتصادية" من الرياض"

هل حدث وأن بحثت عن منتج معين عبر الإنترنت وتفاجأت باقتراحات عديدة لاحقا على حسابك في ?Facebook Sym? لشركات توفر منتجات مشابحة؟ الأمر ليس صدفةء ولكن ذلك يندرج
ضمن استراتيجيات يتبناها عمالقة التقنية للتأثير في قراراتنا الشرائية.
وساهمت الشبكة العنكبوتية في جعل عملية جمع بيانات المستخدمين ?ST? سهولة من أي وقت مضى» مع ترك هؤلاء لآثارهم الرقمية في العديد من المواقع والتطبيقات؛ والتي تكون هدفا لشركات

التكنولوجيا ?sop? بترسانة من تقنيات الذكاء الاصطاعي ?«Artificial intelligence?
وسّت دراسة صادرة عن باحثين في جامعة "برينستون" الأميركية؛ أن ,5008 ترصد تحركات ما يزيد عن ملياري شخص حول العام ممن يستعملون أجهزة وهواتف تعمل بنظام التشغيل
الشهير ?"Android"? بحسب ما ذكرت ?."Skynews"?

وأكد تقرير لوكالة الأسوشيتد برس ?Assiciated press? أن الكثير من خدمات جوجل على أجهزة يفون وآندرويد 10010 بيانات مواقع اللستخدمين›

حت وإن قاموا بإيقاف تشغيل خدمات تحديد الموقع الجغراتي بتغيير إعدادات الخصوصية المتوفرة في تلك الأجهزة.

.
but when I try another like Arabic Simplified font type like this: 
![simplifiedarabic](https://user-images.githubusercontent.com/42976910/46275277-06b9aa80-c565-11e8-916d-ed772baca12b.jpg)


I get English like digits: 
 

SimplifiedArabic
?"جوجل 600916 " يستعد لاقتحام أدمغتنا?
2018 ?الاحد 9 سبتمبر?

الاقتصادية" من الرياض"

هل حدث وأن بحثت عن منتج معين عبر الإنترنت وتفاجأت باقتراحات عديدة لاحقا على حسابك في فيسبوك 808500" لشركات توفر منتجات مشابهة؟ الأمر
ليس صدفة؛ ولكن ذلك يندرج ضمن استراتيجيات يتبناها عمالقة التقنية للتأثير في قراراتنا الشرائية.

?lugs? الشبكة العنكبوتية في جعل عملية جمع بيانات المستخدمين أكثر سهولة من أي وقت مضى؛ مع ترك هؤلاء لآثارهم الرقمية في العديد من المواقع
والتطبيقات» والتي ?a? هدفا لشركات التكنولوجيا المدعومة بترسانة من تقنيات الذكاء الاصطناعي ?Artificial intelligence?

?وبيّنت دراسة صادرة ,عن باحثين في جامعة "برينستون" الأميركية؛ أن 60096 ترصد تحركات ما يزيد عن ملياري شخص حول العالم» ممن يستعملون
أجهزة وهواتف تعمل بنظام التشغيل الشهير "8001010" بحسب ما ذكرت ?.'Skynews"?

?وأكد تقرير لوكالة الأسوشيتد برس 01885 0551018460 أن الكثير من خدمات جوجل على أجهزة آيفون 1011006 وآندرويد ?Android? تخزّن بيانات

?مواقع المستخدمين» حتى وإن قاموا بإيقاف تشغيل خدمات تحديد الموقع الجغرافي بتغيير إعدادات الخصوصية المتوفرة في تلك الأجهزة.

? 

? 
 I'm using Arabic + English tessdata_best

**Comment by zdenop** [comment]
Which version of tesseract?

**Comment by MariamHijazi** [comment]
I use tesseract.net.4.0.0.16 with leptonica.net.1.75.0.6 and try it with Tesseract Open Source OCR Engine vv4.0.0-beta.4.20180912 with Leptonica the same
