### ISSUE TITLE
Tesseract run on linux without shared libraries

### ISSUE THREAD

**Issue by lukiant-dev** [tesseract-ocr/tesseract#194]
Hello!
I need to run tesseract without leptonica installed on the CentOS system. 
I have leptonica liblept.so available, and I am able to compile tesseract pointing to that directory.

Is it possible to run tesseract without setting up LD_LIBRARY_PATH? 
Maybe there is some way to add some parameter to let tesseract know where leptonica is located in execution phase?

Is it possible to compile tesseract to be independent from shared library liblept.so? Is there any "configure" script parameter available to compile liblept.so into tesseract executable?

**Comment by zdenop** [comment]
[FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice): For general questions and support please use the tesseract-ocr user forum
