### ISSUE TITLE
fopenReadSteam and findFileFormat error saying file not found.

### ISSUE THREAD

**Issue by S-Mann** [tesseract-ocr/tesseract#1940]
I have read through some other people reporting such an issue. Not sure what's the solution but the error looks something like this. I guess the issue is from Leptonica? How do i fix it? The file is clearly there in the same directory. ( C:\Users\Mann\eng.sample_font.exp0.tif)

```console
PS C:\Users\Mann> tesseract eng.sample_font.exp0.tif eng.sample_font.exp0 batch.nochop makebox
Tesseract Open Source OCR Engine vv4.0.0-beta.4.20180912 with Leptonica
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.
```

.tif files are accepted right? Also what's a good GUI tool for tesseract? I just installed gImageReader.

**Comment by stweil** [comment]
Does `tesseract eng.sample_font.exp0.tif eng.sample_font.exp0` work?

**Comment by zdenop** [comment]
Please provide output for `tesseract -v` and input file.
Please try the latest code (at least from 30.09.2018.
For asking question please use tesseract user forum.

**Comment by stweil** [comment]
@zdenop, it's a rather new version (v4.0.0-beta.4.20180912 which is basically v4.0.0-beta.4) of our Windows installer.

**Comment by zdenop** [comment]
3 days ago I implement some additional checks for input file to teseract app.... https://github.com/tesseract-ocr/tesseract/commit/1a096441d05a76e72145859cabb5413bf9464dfa

**Comment by S-Mann** [comment]
> Please provide output for `tesseract -v` and input file.
> Please try the latest code (at least from 30.09.2018.
> For asking question please use tesseract user forum.

It's a TFF file I downloaded from this site.
https://www.dafont.com/runescape-uf.font

**Comment by S-Mann** [comment]
> Does `tesseract eng.sample_font.exp0.tif eng.sample_font.exp0` work? If it works: can you load `eng.sample_font.exp0.tif` in an image viewer? Is it really a correct TIFF file?

I will try loading the TFF in a viewer. Any recommended image viewer? The generated file from the command is 0kB.

**Comment by amitdo** [comment]
TFF != TIFF

Tesseract does not support font files like ttf as input. It does not make sense.
