### ISSUE TITLE
Failed to get Text extraction 

### ISSUE THREAD

**Issue by chethanamt** [tesseract-ocr/tesseract#1948]
### Environment

* **Tesseract Version**:  3.04.01
* **Platform**:  Linux

* **Test url**:  [https://samsung-nudge.s3.eu-central-1.amazonaws.com/20.jpeg](url)  & 
                       [https://samsung-nudge.s3.eu-central-1.amazonaws.com/18.jpeg](url)

### Current Behavior: 
System is failing to get the text extraction of all the texts present in the image, Especially what we need the most is alphanumeric located at left top of bar code. 
In above image : **WD90N645OOW/EP** is not contained in text extraction.

### Expected Behavior:
Having text extraction of the alphanumeric(**WD90N645OOW/EP**) located at left top of bar code along with other texts present in the image. 

### Suggested Fix: 
Having **WD90N645OOW/EP**  in text extraction result.

**Comment by zdenop** [comment]
1. Posted to [forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/axZReWpkB70/Syb9bG4rBAAJ)
2. More or less duplicate to #1751
