### ISSUE TITLE
Has stdin option changed?

### ISSUE THREAD

**Issue by uttrasey** [tesseract-ocr/tesseract#1959]
### Environment

* 4.0.0-rc1-37-g1e47
* 1e4768c1f56e530ecb301710eaa026abb5953ca8
* Mac OS

### Current Behavior:

calling with tesseract with `stdin` option should read from `stdin`. Instead now I get `Cannot open input file: stdin`

These are my args `[ 'stdin',
  'stdout',
  '-l',
  'eng',
  '-c',
  'tessedit_create_hocr=1',
  '-c',
  'tessedit_pageseg_mode=1',
  '-c',
  'hocr_font_info=0' ]`

### Expected Behavior:

in previous commits, this worked fine, for example when streaming images into Tesseract.

### Suggested Fix:

Update the documentation if it's changed or restore the original behavior.

**Comment by uttrasey** [comment]
Awesome project btw 😄 👏 👏 👏 👏 👏 👏 👏

**Comment by zdenop** [comment]
We do not support 3rd part project ;-)
You need to replicate it with tesseract executable,

**Comment by amitdo** [comment]
@zdenko, you need to take stdin into account here.

https://github.com/tesseract-ocr/tesseract/blob/a86292b111f836e543ce5d828a4b5c8d5ef15d2a/src/api/tesseractmain.cpp#L537

**Comment by uttrasey** [comment]
@zdenop apologies if I misunderstand but I am calling tesseract executable directly. 

The `stdin` option seems to have stopped working, it's a documented option

https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage#tesseract---help-extra

**Comment by amitdo** [comment]
I already found the cause, see above comment.

**Comment by stweil** [comment]
Pull request #1960 addresses this issue.

**Comment by amitdo** [comment]
@uttrasey,

Please try the latest commit from the master branch.

**Comment by uttrasey** [comment]
Looking good, thanks for the swift turnaround
