### ISSUE TITLE
jpg input files result in much bigger pdf 

### ISSUE THREAD

**Issue by ShinjiLE** [tesseract-ocr/tesseract#1961]
### Environment

* **Tesseract Version**: tesseract 4.0.0-beta.4-165-g971f
 leptonica-1.77.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.7.0beta84 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0 : libopenjp2 2.3.0
 Found AVX
 Found SSE
* **Commit Number**: 5fe1390748a15c0e445a5c57c834edff27ff2f4d
* **Platform**:  Linux leo.mybase 4.18.9-1-default #1 SMP PREEMPT Thu Sep 20 06:37:04 UTC 2018 (67901ec) x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
OCR jpeg files lead to bigger output pdf file .
Inputfilesize = 642K
pdf = 2,5M
### Expected Behavior:
the pdf size should not much bigger then the input  
pdf = 645K
### Suggested Fix:
not a fix , but this commit (5fe1390748a15c0e445a5c57c834edff27ff2f4d) introduce the problem . Exactly src/api/pdfrenderer.cpp line 719.

**Comment by stweil** [comment]
This looks like a regression. @zdenop, maybe we can try to fix it for 4.0.0, perhaps by writing the image in JPEG 2000 format (like at least one commercial OCR software does) if that is supported by Leptonica. That could reduce the size of the PDF a lot.

**Comment by zdenop** [comment]
Can you please provide you image for testing?
@stweil : pdfrenderer philosophy is not to modify input image for output (if is not needed for OCR or other reason). So if user what jp2 of tiff g4 compression in pdf, user should provide such encoded images.

**Comment by zdenop** [comment]
Thank for report. Should be fixed - please check.
