### ISSUE TITLE
crash with --psm 0 and -l eng or -l deu

### ISSUE THREAD

**Issue by CanadianHusky** [tesseract-ocr/tesseract#1962]
Hello,
the current master branch crashes on the attached file and some others and shows signifcant wrong results for confidence and script in comparion to 2017 alpha version.

sample files and minimalist test show the problem

input image : 
![cimg_1](https://user-images.githubusercontent.com/35332003/46600391-b2797200-caf2-11e8-8fc3-bef895be7aee.png)

test with current master source :

![image](https://user-images.githubusercontent.com/35332003/46600427-cae98c80-caf2-11e8-8f9b-fb0cee2e99a4.png)

Problems : confidence is reported 0.01 / scipt is reported japanese

![image](https://user-images.githubusercontent.com/35332003/46600501-fec4b200-caf2-11e8-8ffc-8db511b222bd.png)

![image](https://user-images.githubusercontent.com/35332003/46600512-04ba9300-caf3-11e8-99bb-01028940c557.png)

--psm 0 and -l eng or -l deu crashes for this image and some others

tests with other --psm values for reference only
![image](https://user-images.githubusercontent.com/35332003/46600533-17cd6300-caf3-11e8-9c1a-8660e0a7c0eb.png)

comparison to 2017 alpha version

![image](https://user-images.githubusercontent.com/35332003/46600549-26b41580-caf3-11e8-952f-6b762aef4a37.png)

![image](https://user-images.githubusercontent.com/35332003/46600552-2b78c980-caf3-11e8-9070-02185f87e9e6.png)

Result with 2017 alpha :
very high confidence
correct orientation detection
no crash

**Comment by CanadianHusky** [comment]
My installation steps are as follows :

**for 4.00 master tests :**

I use precompiled installer/binary from 
`https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v4.0.0-rc1.20181002.exe`
which downloads and installs its own language data.
After installer is finished, I replace tesseract.exe, tesseract.dll and about 20+ dlls from a local build because the -c min_characters_to_try is not incorportated in the 20181002 build

**for 4.00 alpha tests :**

I use precompiled installer/binary from 
`https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-4.0.0-20170804.exe`
which downloads and installs its own language data
After installer is finished, I replace tesseract.exe, tesseract.dll and about 20+ dlls from a local build because the I have modified the hardcoded constant -kMinCharacters in file osdetect.cpp from 50, down to 10 which is critical

I have not manually added or replaced any eng.traineddata files.
If the installer is not pulling the right versions of those traineddata files, I would need to know where those correct versions are to be downloaded from.

**Comment by CanadianHusky** [comment]
the issue seems to have something to do with the traineddata files

steps :
install tesseract-ocr-setup-4.0.0-20170804.exe
replace exe and all dll's from self compiled master

result does not crash anymore, gives some result, but still not as good as 20170804

rotation detection is correct
script type is correct
confidence is far lower (0.16 in master versus 1.26 in 20170804 )


![image](https://user-images.githubusercontent.com/35332003/46602372-a85a7200-caf8-11e8-9a35-063add6f5637.png)

**Comment by CanadianHusky** [comment]
problem solved.

when this .trainddata is used, there is no crash in current master and results are identical to 20170804

`https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata`
`https://github.com/tesseract-ocr/tessdata/blob/master/deu.traineddata`

the installers seem to use incompatible traineddata files that the engine does not expect which I was not aware of

**Comment by stweil** [comment]
The crash with LSTM models is addressed in pull request #1964.
