### ISSUE TITLE
README.md: insight.io badge

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#1969]
https://insight.io/github.com/tesseract-ocr/tesseract
The link is broken.

http://insight.io/github.com/
redirects to
https://www.elastic.co/blog/welcome-insight-io-to-the-elastic-team

**Comment by zdenop** [comment]
I do not see any alternative instead of insight.io at the moment.
Should the badge be removed?

**Comment by amitdo** [comment]
>I do not see any alternative instead of insight.io at the moment.

I do not even know what exactly insight.io provided when it was active. 

>Should the badge be removed?

Yes.

**Comment by zdenop** [comment]
Done. AFAIR it provided easy (clickable) browsing and searching source code.
