### ISSUE TITLE
allheaders.h missing

### ISSUE THREAD

**Issue by erichfrazer** [tesseract-ocr/tesseract#197]
disappointed w/ open-source stuff. allheaders.h seems to be missing. Trying to compile w/ Visual Studio 2010, using make file included in project. Not clear how to build this project otherwise. Why so much code? :-)

**Comment by stweil** [comment]
`allheaders.h` is part of the Leptonica package. You will need that package, too. And even more core ... :-)

**Comment by zdenop** [comment]
Maybe you can start with some reading: https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows

**Comment by AGLV0121** [comment]
Same for me. I don;t want to sound arrogant but when I release a package, I make sure it is complete.

**Comment by UnaPlugin** [comment]
Same for me too.

**Comment by UnaPlugin** [comment]
[https://tpgit.github.io/Leptonica/allheaders_8h_source.html ]
This is the homepage of allheaders.h

**Comment by UnaPlugin** [comment]
[https://tpgit.github.io/Leptonica/allheaders_8h_source.html ](url)
This is the homepage of allheaders.h

**Comment by amitdo** [comment]
>https://tpgit.github.io/Leptonica/allheaders_8h_source.html
This is the homepage of allheaders.h

The homepage of Leptonica is here:
http://www.leptonica.org/

Official GitHub repo:
https://github.com/DanBloomberg/leptonica

**Comment by kstian** [comment]
You can point the compiler to your Leptonica headers location.

```
sudo apt install libleptonica-dev
```
It will install leptonica header files in `/usr/include/leptonica`

then add CPPFLAGS:

`CPPFLAGS+=-I/usr/include/leptonica ./configure`

**Comment by stweil** [comment]
There is no need to add CPPFLAGS for Leptonica if it was installed correctly.
