### ISSUE TITLE
tesseract 4.0 is failed to detect less than “<” symbol

### ISSUE THREAD

**Issue by sachinchavan9** [tesseract-ocr/tesseract#1975]
* **Tesseract Version**: tesseract 4.0.0-rc2
it extracting <<<<<<<<<<<<<<<<<<<<<<<< symbols as
<KK<KLLLLLLLLLLLLLLLLLLLLLLLRLRK

**Comment by zdenop** [comment]
Please respect guidelines for posting issue.
