### ISSUE TITLE
Missing right side of image in ocr result

### ISSUE THREAD

**Issue by ibaxx** [tesseract-ocr/tesseract#1977]
Hi,

I have a big problem, that tesseract often only interprets the left side of the image.
![sample error](https://user-images.githubusercontent.com/2786557/46744911-5e19f200-ccac-11e8-8f14-c6c0c8ad0c07.jpg)

All Numbers from the right side are missing in the result.
Any ideas?

Regards
Ingo

**Comment by zdenop** [comment]
Please respect guidelines for posting issue - use tesseract user forum for asking support.
