### ISSUE TITLE
unknown command line argument '-psm'

### ISSUE THREAD

**Issue by YeisonVelez11** [tesseract-ocr/tesseract#1978]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **last**: 

* **windows 10 64 bit**: 

### Current Behavior:
I'm running the command:
 node app.js

I'm new to nodejs, I'm not sure if I need something. Thank you for helping me.

`
          var tesseract = require('node-tesseract');

          tesseract.process('17.jpg', (err, text) => {
            if(err){
                return console.log("An error occured: ", err);
            }

            console.log("Recognized text:");
            // the text variable contains the recognized text
            console.log(text);

            /*
            C:\Program Files (x86)\Tesseract-OCR>node app.js
            An error occured: { Error: Command failed: tesseract 17.jpg C:\Users\Chec\AppData\Local\Temp\node-       tesseract-07062fd3-c3dc-4056-871e-341c5c7c13a9 -l eng -psm 3
            Error, unknown command line argument '-psm'
            */

        });

`

know you, how can fix it?

**Comment by amitdo** [comment]
[A guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).
Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).

**Comment by amitdo** [comment]
Try '--psm' instead of '-psm'.

Please do not post more questions here. It's not a forum.

**Comment by YeisonVelez11** [comment]
I'm using this nodejs library. But I do not find where to change it. and apologize for the inconveniences.

**Comment by Mathankumar1312** [comment]
> Try '--psm' instead of '-psm'.
> 
> Please do not post more questions here. It's not a forum.

Thanks a lot it works after the changed it
