### ISSUE TITLE
//usr/lib/libtesseract.so.3: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by JohnWnx** [tesseract-ocr/tesseract#1989]
------------------------
![image](https://user-images.githubusercontent.com/40804580/46920743-59936780-d025-11e8-8466-755125640643.png)
Hi, I have tesseract correctly installed into leptonica. 
However, upon adding this "tesseract::TessBaseAPI ocr" to my code, I get the error as shown in the title.

![image](https://user-images.githubusercontent.com/40804580/46920814-4b921680-d026-11e8-80bc-d5a81dc9a6c1.png)

### Environment

* **Tesseract Version**: tesseract 4.0.0-rc2-68-ge371
tesseract 4.0.0-rc2-68-ge371

* **Commit Number**: 
* **Platform**: ubuntu 16.04

### Current Behavior:
/usr/bin/ld: obj/http_stream.o: undefined reference to symbol '_ZN9tesseract11TessBaseAPID1Ev'
//usr/lib/libtesseract.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.
