### ISSUE TITLE
I need help with training my chi_sim language

### ISSUE THREAD

**Issue by xuanyuanjia** [tesseract-ocr/tesseract#1995]
@Shreeshrii@amitdo@zdenop 
------------------------ 

### Environment 

* **Tesseract Version**: tesseract-ocr-w64-setup-v4.0.0-beta.1.20180608 
* **Platform**: Windows 7 professional Service Pack 1 edition, 64-bit 

Recently,I'm using tesseract training my chi_sim language. 
My training text file includes 82915 characters. 
[my_training.txt](https://github.com/tesseract-ocr/tesseract/files/2486090/my_training.txt)

There are about 5104 Exactly different characters in the text file. 
I used 7 fonts to generate box and tif (including:FZYaoti,KaiTi,LiSu,MingLiU,SimHei,SimSun,STXinwei) 
Text2image parameter is "--leading 40 --ptsize 36" 
the Training command parameters are as following: 
lstmtraining.exe --debug_interval 100 
--traineddata chi_sim.traineddata 
--net_spec "[1,48,0,1Ct3,3,16Mp3,3Lfys64Lfx96Lrx96Lfx512O1c1]" 
--model_output lyqcheck 
--learing_rate 20e-4 
--train_listfile chi_sim.training_files.txt 
--eval_listfile chi_sim.training_files.txt 
--max_iterations 20000000 

### Current Behavior: 
I have trained the 7 fonts about 40 days. 
These days it would print "Compute CTC targets failed!" occasionally. 
The "Mean rms" is fluctuating between 0.182 to 0.198 
The "delta" is fluctuating between 0.289 to 0.136 
The "train" is fluctuating between 0.551 to 0.264 
The "skip ratio" is fluctuating between 0% to 0.1% 
Especially,the "train" index can't decline. It is fluctuating between 0.551 to 0.264. 
Besides,my training library's Recognition effect is much more worse than the official library.

I want to know why? why does this happen?How could I improve my training?I want to train a library much more better than the official library. 
Looking forward to your reply and thank you for your help.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
