### ISSUE TITLE
Format specifier warning in pdfrenderer.cpp

### ISSUE THREAD

**Issue by rmtheis** [tesseract-ocr/tesseract#20]
I get a format specifier warning when building for Android using clang and tess-two:

    jni/com_googlecode_tesseract_android/src/api/pdfrenderer.cpp:537:28: warning: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Wformat]
                   "stream\n", len);
                               ^~~

I think it should be `%zd` or `%zu` instead of `%ld`, but I'm not sure if that works on Visual Studio too.

**Comment by zdenop** [comment]
it seems that the z prefix isn't defined in [VS Size Specification](https://msdn.microsoft.com/en-us/library/tcxf1dw6.aspx)

**Comment by jbreiden** [comment]
I'm the author of this code. I'd prefer to keep using size_t for this number since PDF files can be really big (although, this code will break for other reasons once we get larger than 10 gigabytes). Not sure what to do here to make all platforms happy.

http://stackoverflow.com/questions/2524611/how-to-print-size-t-variable-portably

**Comment by rmtheis** [comment]
OK--since this warning isn't indicative of a larger problem, and there's no clear solution for muting this warning across the board, let's close this issue.

**Comment by stweil** [comment]
That's not a solution. It's a bug, not a compiler warning which must be muted.

You will get a wrong results on little endian platforms when sizeof(long) != sizeof(size_t).
On big endian platforms the result is wrong when sizeof(long) > sizeof(size_t).

Adding a type cast would help: (long)len

Even better would be replacing "%ld" by "%lu" and using  this: (unsigned long)len

**Comment by amitdo** [comment]
It seems that @stweil solved this with this commit:
https://github.com/tesseract-ocr/tesseract/commit/997c4a6
