### ISSUE TITLE
No Windows Installation

### ISSUE THREAD

**Issue by tonym1995** [tesseract-ocr/tesseract#200]
Can you provide a Windows installation for those that do not have the expertise to compile these sources as you did before moving the project to Github?

The last installer I know of was for version 3.02.02

**Comment by stweil** [comment]
Does https://github.com/UB-Mannheim/tesseract help?

**Comment by tonym1995** [comment]
Hi,

Thanks for your reply. I downloaded the zip and extracted it. I still could
not find any .exe files. Plus the whole download is only 2.4MB and the
original 3.02.02 installation was 30+ MB as an installer.

Regards,
Tony

**Comment by stweil** [comment]
May fault, wrong link (the info is in the wiki): https://github.com/UB-Mannheim/tesseract/wiki should be better.

**Comment by tonym1995** [comment]
Perfect :-)

Thank you!

Enjoy you day.

**Comment by amitdo** [comment]
@stweil, you have a typo in the above comment, where can I send a PR?
:-)

**Comment by stweil** [comment]
@amitdo, thanks, pulled. :-)

**Comment by tonym1995** [comment]
Hi Stefan,

I installed the version 3.05.00dev and it produces the following error.

Tesseract Open Source OCR Engine v3.05.00dev with Leptonica
Warning in pixReadMemPng: work-around: writing to a temp file
libpng warning: Application built with libpng-1.4.3 but running with 1.5.14
Error in pixReadStreamPng: png_ptr not made
Error in pixReadMemPng: pix not read
Error in pixReadMem: png: no pix returned
Error during processing.

The installation replaced the previous version of 3.02.02

**Comment by stweil** [comment]
This might be caused by the Leptonica code used for Tesseract: it tries to create a temp file in c:\ and fails because you don't have write permission there. So it should work if you run Tesseract as admin or if you change the permissions for c:\.

I fixed this for JPEG-2000 files, but not for other image formats like PNG. See the discussion on https://github.com/DanBloomberg/leptonica/pull/116 for more information.

**Comment by bantilan** [comment]
Hi tonym1995,

I made a full instruction how to install and compile tesseract on windows http://gensanblog.com/2016/01/28/how-to-compile-tesseract-git-project-on-windows/

Hope this can help!

Erwin

**Comment by mightyuhu** [comment]
Hi,
thank you!
i have to say for a Windows newcomer finding this project it is horrible to get started from the README.md 
@bantilan your blog entry should be in the project's wiki!
Best
uhu

**Comment by Shreeshrii** [comment]
[See issue 209](https://github.com/tesseract-ocr/tesseract/issues/209)
