### ISSUE TITLE
Q&A: Unclear document for retrain(tunefine) Tesseract LSTM model for box/tiff with hand made created boxes file from image.

### ISSUE THREAD

**Issue by tonquangtu** [tesseract-ocr/tesseract#2006]
Hi,

I don't see any part of in this document (https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#creating-starter-traineddata)  for create .trainneddata from hand made boxes file.

I want to retrain tesseract 4 for recognize some special characters for my situation. In my case I want recognize some characters like: Φ, φ etc ...

So I create my training data (tiff image + box file) from my images.
I generated its via this command line: tesseract [lang].[fontname].exp[num].tif [lang].[fontname].exp[num] batch.nochop makebox, then after I edit manually by Qt-box-editor.
(I done with this link: https://github.com/tesseract-ocr/tesseract/wiki/Training-Tesseract-%E2%80%93-Make-Box-Files)

So now I files:
- .tif file
- .box file
- .tr file (generated by command: tesseract [lang].[fontname].exp[num].tif [lang].[fontname].exp[num] box.train
- unicharset file ( I don't set properties for unicharset file and don't generate font properties file)

My question is: How can I create .trainneddata and tunefine training ltsm for my case from them.
Thank you !

**Comment by tonquangtu** [comment]
I read tesstrain.sh, seems it use text2image to automatically generate box file from text. But I want to generate box file from my image. 
Thank you

**Comment by amitdo** [comment]
See here:
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#making-box-files

**Comment by tonquangtu** [comment]
@amitdo Thank you for replying me 
But I have read this part and now I have files:
    .tif file
    .box file
    .tr file (generated by command: tesseract [lang].[fontname].exp[num].tif [lang].[fontname].exp[num] box.train
    unicharset file ( I don't set properties for unicharset file and don't generate font properties file)

My question is: How can I create .trainneddata from them ?
Currently, I'm using combine_lang_model to generate .trainneddata but I get an error like:
![screenshot from 2018-10-19 13-42-33](https://user-images.githubusercontent.com/17746928/47201696-fbf47780-d3a4-11e8-98f2-f78e65449c47.png)

I downloaded langdata from here: https://github.com/tesseract-ocr/langdata

**Comment by tonquangtu** [comment]
I find 2 repo contain langdata:
What should I choose, I'm using LSTM in tesseract
1: https://github.com/tesseract-ocr/langdata_lstm
2:  https://github.com/tesseract-ocr/langdata

**Comment by tonquangtu** [comment]
I find 2 repo contain langdata:
What should I choose, I'm using LSTM in tesseract
1: https://github.com/tesseract-ocr/langdata_lstm
2:  https://github.com/tesseract-ocr/langdata

**Comment by tonquangtu** [comment]
I find 2 repo contain langdata:
What should I choose, I'm using LSTM in tesseract
1: https://github.com/tesseract-ocr/langdata_lstm
2:  https://github.com/tesseract-ocr/langdata

**Comment by zdenop** [comment]
lease respect guidelines for posting issue: use tesseract user forum for asking questions/support.
