### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rajil01** [tesseract-ocr/tesseract#201]
actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file
 ..\ccutil\tessdatamanager.cpp, line 48

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/FAQ#actual_tessdata_num_entries_-tessdata_num_entrieserrorassert-failedin-file-ccutiltessdatamanagercpp-line-55_
