### ISSUE TITLE
Tesseract.js Arabic OCR not working gvies error

### ISSUE THREAD

**Issue by rockerbaba** [tesseract-ocr/tesseract#2014]
Hey there i am been trying to setup OCR for Arabic language in tesseract.js but i am getting this error.
![rymbl](https://user-images.githubusercontent.com/7455689/47266107-e321c880-d542-11e8-86b7-e96db257d91e.jpg)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.
