### ISSUE TITLE
Page Segmentation Mode 0  -- Orientation and script detection (OSD) only Failed

### ISSUE THREAD

**Issue by rajeevkannav** [tesseract-ocr/tesseract#202]
Tesseract Orientation and script detection works fine on many images, but fails in many cases to like 

Image with maps, no EXIF-Data, Multiple text lines with different directions 

`tesseract shots-1.jpg out  - -psm 0
`

> Tesseract Open Source OCR Engine v3.04.00 with Leptonica
> Orientation: 3
> Orientation in degrees: 90
> Orientation confidence: 5.11
> Script: 1
> Script confidence: 9.74
> 
![shots-1](https://cloud.githubusercontent.com/assets/331827/12638871/5bae017c-c5c6-11e5-96bc-314418b73698.jpg)

Any other way to get best possible value for Orientation and script detection ?

**Comment by tfmorris** [comment]
General questions are better asked on the mailing list where more people will see them.

**Comment by amitdo** [comment]
I'm closing this because as I said, there is a good reason why Tesseract failed in this specific case, so I don't think there is a bug here.
