### ISSUE TITLE
tessdata_best deu.traineddata broken

### ISSUE THREAD

**Issue by k783s4** [tesseract-ocr/tesseract#2025]
### Environment

* **Tesseract Version**: 3.05.02
* **Platform**: MacOS

### Problem:

I downloaded the deu.traineddata from tessdata_best and pasted it into /usr/local/Cellar/tesseract/3.05.02/share/tessdata. When the code is run with the lang parameter set to deu the program crashes and says it was unable to load the language. 

I suspect the deu.traineddata is broken, as it works with other langs

**Comment by Shreeshrii** [comment]
tessdata_best is meant for use with tesseract 4.0.0. it will not work with 3.05

**Comment by stweil** [comment]
I created a new pull request https://github.com/tesseract-ocr/tessdata_best/pull/33 to add the missing information.

**Comment by Shreeshrii** [comment]
Thanks. Please also create a similar PR for tessdata_fast (unless it is already there).

**Comment by stweil** [comment]
Done and merged.

**Comment by horseshoe7** [comment]
This is broken for me.  I'm using tesseract ios 5.x

I have deu.traineddata, fra.traineddata, and eng.traineddata in my tessdata folder.  It will work if I specify "eng+fra" as a language, but not "deu".  So I'm guessing it's bad data?  How might I fix this?
