### ISSUE TITLE
iOS Chinese Crash

### ISSUE THREAD

**Issue by zhangfangtaozft** [tesseract-ocr/tesseract#2028]
I use chi_sim.traineddata ,but crashed,How can I do?

**Comment by zhangfangtaozft** [comment]
![47417273-36e21b00-d7aa-11e8-82bb-9771e77f924f](https://user-images.githubusercontent.com/11926205/47418408-a527dd00-d7ac-11e8-9aa8-85242a249f33.png)

**Comment by zhangfangtaozft** [comment]
I put the issue in Tesseract-OCR-iOS project,But it has no result.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. Use tesseract user forum for it.
