### ISSUE TITLE
Tesseract fails to initialize : cannot read traineddata files from $TESSDATA_PREFIX

### ISSUE THREAD

**Issue by srdg** [tesseract-ocr/tesseract#2029]
### Environment

* **Tesseract Version**: 4.0.0-rc4

* **Platform**: Linux host 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux [Ubuntu 16.04 Xenial]

### Current Behavior:
On executing `tesseract 581776b7-94f8-46e7-bab0-cfc936532d1f.jpg stdout` the following error stack occurs 
```
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
Error opening data file /usr/local/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.

```
Output of  ` ll /usr/local/share/tessdata/ --author` :
```
total 100K
-rw-rw-r-- 1 soumik soumik soumik  44K Oct 24 18:47 ben.traineddata
drwxr-xr-x 2 root   root   root   4.0K Oct 24 18:43 configs
-rw-rw-r-- 1 soumik soumik soumik  44K Oct 24 18:44 eng.traineddata
-rw-r--r-- 1 root   root   root    572 Oct 24 18:43 pdf.ttf
drwxr-xr-x 2 root   root   root   4.0K Oct 24 18:43 tessconfigs
```

Output of `echo $TESSDATA_PREFIX`:  `/usr/local/share/tessdata`

Output of `tesseract -v`:
```
tesseract 4.0.0-rc4
 leptonica-1.77.0
  libpng 1.2.54 : zlib 1.2.8
 Found AVX2
 Found AVX
 Found SSE
```
Output of `which tesseract`: `/usr/local/bin/tesseract`

### Expected Behavior:
Print OCR text on standard output

### Suggested Fix:
None. 
Any clues what is causing this?

**Comment by stweil** [comment]
You are using a file `eng.traineddata` which does not look like the official ones: it is much too small. Tesseract fails because it cannot read that file successfully.

**Comment by stweil** [comment]
Please see https://github.com/tesseract-ocr/tesseract/wiki#support if you need more support.

**Comment by srdg** [comment]
@stweil the `eng.traineddata` file is from `tesseract-ocr/tessdata` repository. That is the official one, right?

**Comment by stweil** [comment]
Then it should be 22.4 MB. Did you check your download? Maybe it is pure text? It's small enough to load it in an editor.

**Comment by srdg** [comment]
@stweil you are right, the download was corrupted, didn't notice that.
However, a new error stack pops up :
```
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
Error in pixReadStreamJpeg: function not present
Error in pixReadStream: jpeg: no pix returned
Error in pixRead: pix not read
Error during processing.
```
What might cause this to occur?

**Comment by Shreeshrii** [comment]
>>leptonica-1.77.0
  libpng 1.2.54 : zlib 1.2.8

Leptonic has not been built with libtiff, hence no support for reading tiff files.

**Comment by savanmorya** [comment]
is it possible to compile tesseract without tiff ?
as i have compiled leptonica without tiff {usecase of my project}.
any suggestion would be great help.

**Comment by tandelDipak** [comment]
@srdg  found the solution in forum. Check out this discussion https://groups.google.com/g/tesseract-ocr/c/KKTiag0VCFE/m/A4jpS6i6CwAJ

Let me know whether it solves your issue or not.

**Comment by ucas010** [comment]
have the same problem
