### ISSUE TITLE
Tesseract creates PDF documents with "glyphless" font

### ISSUE THREAD

**Issue by aderoks** [tesseract-ocr/tesseract#2034]
### Environment

* **Tesseract Version**: Tess4j 4.2.3
* **Platform**: Windows 10, 64 bit

### Current Behavior:

I have a set of PDFs which were scanned. Being scanned, the entire content was just images and was not searchable. I tried to convert the PDF into a searchable one by using the combo of Ghostscript and Tesseract (via Tess4j). I converted the scanned PDF into jpg images using Ghostscript, and converted the generated images back to PDFs using Tesseract.

```
Tesseract tessInst = new Tesseract();
tessInst.setDatapath("D://Tess//tessdata");
List list = new ArrayList();
list.add(RenderedFormat.PDF);

for (int i = 0; i < images.size(); i++)
tess.createDocuments(i + ".jpg", "D://Tess//output" + i, list);
```

The PDFs were generated fine, and are even searchable, but when I select a word, the selection highlight is a little skewed from the actual word. I tried generating a DOM structure by using PDF2Dom, as I had been doing with other PDFs which were searchable without OCR processing and getting great results, but when I ran it on these Tesseract generated PDFs, I got the following exception:

`Error loading type 0 with ttf descendant font 'GlyphLessFont' Message: java.io.IOException: Multi byte glyph name not supported. class java.io.IOException`

### Expected Behavior:

I could not find any configuration where I can change the output font. The output font should be a configurable parameter. The output should be compatible with libraries like PDF2Dom.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.

**Comment by aderoks** [comment]
The base issue is that Tesseract is creating PDFs with the "glyphless" font. How is that a third party issue, may I ask?

**Comment by zdenop** [comment]
The base issue is that you want to create pdf in 3rd party tool:

> Error loading type 0 with ttf descendant font 'GlyphLessFont' Message: java.io.IOException: Multi byte glyph name not supported. class java.io.IOException

Other issue is that you do not respect guidelines in other topic: for support you should use tesseract user forum and not issue tracker.

**Comment by zdenop** [comment]
Please stop to play blame  game by yourself! 
I asked you to respect our guidelines you ignored. 
If there is issue in tesseract, than reproduce error with tesseract executable and provide input image and exact command you used. That's all you need for issue tracker. Asking for support should go to forum.

**Comment by aderoks** [comment]
I need to parse the pdf since I require to know which text is contained in which cell of which table. Just having the hocr output will vomit the entire text without any contextual information.

**Comment by jbreiden** [comment]
I was willing to engage with the author of PDF2Dom to figure out the incompatibility. Not so motivated anymore, due to the incivility of the previous comment.

**Comment by aderoks** [comment]
Please pardon me if you were offended by the language. I didn't mean any disrespect by it. You may or may not contact the author, that's of course entirely up to you. I'm under a lot of pressure here to deliver results, so perhaps my language became rougher. I'm apologizing once again to you for it, since I don't want to hurt anyone's sentiments as a person. Please do as seems fit to you.

**Comment by nylen** [comment]
For a more helpful answer to this issue: https://github.com/tesseract-ocr/tesseract/issues/1769#issuecomment-509490277
