### ISSUE TITLE
Enabling openmp leads to 10x performance regression on mingw-w64

### ISSUE THREAD

**Issue by jeroen** [tesseract-ocr/tesseract#2035]
### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**:  release
* **Platform**: Windows 64, mingw-w64 gcc 8.2.0

### Problem

Updated the R bindings from Tesseract 3 to 4 on Windows and MacOS. However on Windows I noticed an enormous performance regression. Basic OCR examples that took 1sec before now took over 10 sec.

I noticed that the default was now to build with OpenMP which was not the case in Tesseract 3. I was able to solve the problem by rebuilding with `--disable-openmp`. Perhaps that should be the default on Windows

**Comment by zdenop** [comment]
Your approach is wrong: if something does not work for you it should be turn off? 

Please try to search before you post issue.  Public testing of version 4 last 2 years some there must be more info experiences that yours... e.g:
https://github.com/tesseract-ocr/tesseract/issues/1662#issuecomment-401349871
https://github.com/tesseract-ocr/tesseract/issues/1171#issuecomment-337452383
https://github.com/tesseract-ocr/tesseract/issues/1081

**Comment by amitdo** [comment]
Missing info:
Build tool: Autotools/CMake
* Did you built it on Windows or cross-compile from another OS?
* Number of CPU cores, does they support HyperThreading?
* Which training data did you use?
* Do you run it inside a VM?
*` tesseract -v` output.

There is a tesseract binary for MingW-w64, prepared by @stweil.
https://github.com/UB-Mannheim/tesseract/wiki

The old engine is still available in 4.0.0.
