### ISSUE TITLE
Multiple commands produce '/Users/***/Library/Developer/Xcode/DerivedData/OCR-bfippympeztzsyavgztvthhqaowr/Build/Products/Debug-iphoneos/TesseractOCRiOS/config_auto.h':

### ISSUE THREAD

**Issue by meloanyang** [tesseract-ocr/tesseract#2036]
Multiple commands produce '/Users/***/Library/Developer/Xcode/DerivedData/OCR-bfippympeztzsyavgztvthhqaowr/Build/Products/Debug-iphoneos/TesseractOCRiOS/config_auto.h':

xcode 10;Have you encountered any similar errors? What's the solution?

![error](https://user-images.githubusercontent.com/13743089/47707735-8a9bab00-dc67-11e8-98c0-787876ce4235.png)

**Comment by zdenop** [comment]
First of all: for finding solution you need to respect guidelines for posting issue: we do not provide support for 3rd party projects. 
Use tesseract user forum. Before that: try to search internet ;-)
