### ISSUE TITLE
Cannot open input file 'liblept171.lib' error

### ISSUE THREAD

**Issue by Wandererer** [tesseract-ocr/tesseract#204]
I download recent leptonica version but when i build opencv project  
"Cannot open input file 'liblept171.lib' error"
this msg came out..... where can i get liblept171.lib... 
i research google but there is no answer for this error....

**Comment by zdenop** [comment]
You try to run opencv report, that needs leptonica and you are putting issue to tesseract???

**Comment by Wandererer** [comment]
no I use this project...
and build this project .. that msg came from when i build it

**Comment by zdenop** [comment]
You wrote: "but when i build opencv project" Or???
Leptonica is external dependency - you need to build it by yourself (and maybe adjust paths according you directory structure). You need to use 1.71 or latter version.
There are several tutorials how to build tesseract from source. Just use google...
