### ISSUE TITLE
ubuntu 14 failed to fetch http://ppa.launchpad.net 403 Forbidden

### ISSUE THREAD

**Issue by marcelocecin** [tesseract-ocr/tesseract#2041]
reading the Wiki:
`sudo add-apt-repository ppa:alex-p/tesseract-ocr`
`sudo apt-get update`
but getting the error

`W: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/dists/trusty/main/binary-amd64/Packages  403  Forbidden`

`W: Failed to fetch http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/dists/trusty/main/binary-i386/Packages  403  Forbidden`

**Comment by stweil** [comment]
You should see from the error message that it is unrelated to Tesseract. Please check your other package sources.
