### ISSUE TITLE
License recognition by GitHub 

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#2042]
GitHub displays 'View License' in the main page. In the past, it recognized the 'Apache 2.0' license.

Does someone knows how to fix this issue in our side?

**Comment by zdenop** [comment]
'View License' is (automatically?) linked to project [License file](https://github.com/tesseract-ocr/tesseract/blob/master/LICENSE). It is really issue?
Also at the top of Readme we place badge for 'Apache 2.0'

**Comment by stweil** [comment]
It looks like GitHub is confused because Tesseract provides both `COPYING` and `LICENSE`. Removing `COPYING` helps, see https://github.com/stweil/tesseract.

**Comment by amitdo** [comment]
`COPYING` is used with GPL.
https://github.com/emacs-mirror/emacs/blob/master/COPYING

For Apache, apart from a `LICENSE` file.  a `NOTICE` file is sometimes used.

**Comment by stweil** [comment]
See pull request #2043 which solves this issue.

**Comment by amitdo** [comment]
Thank you!
