### ISSUE TITLE
Tesseract installation on ubuntu 18.04

### ISSUE THREAD

**Issue by Ankhi2** [tesseract-ocr/tesseract#2049]
HI,

I have typed sudo apt-get install -y libtesseract-dev libleptonica-dev tesseract-ocr-eng on ubuntu terminal, so it got successfully installed.
While working wit tasseract in R it says "NO such package found".
Thought of executing install.packages("tesseract") in R console got this-

------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------

Warning in install.packages :
  installation of package ‘tesseract’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpM4QboD/downloaded_packages’.

Not sure what to do?

Thanks
Ankhi Roy

**Comment by stweil** [comment]
This is not a help desk. Please use the [Tesseract user forum](https://github.com/tesseract-ocr/tesseract/wiki#support).
