### ISSUE TITLE
Error out less confusingly when data does not support engine mode

### ISSUE THREAD

**Issue by AdamWill** [tesseract-ocr/tesseract#2053]
### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**: N/A
* **Platform**: Fedora Rawhide

### Current Behavior:

If you have the tessdata_fast data - which is what most distros seem to ship - and you try to use the old engine, you get something like this:

    <mock-chroot> sh-4.4# tesseract --oem 0 data/bootmenu-ocr.ref.png testoutput
    Failed loading language 'eng'
    Tesseract couldn't load any languages!
    Could not initialize tesseract.

This is not helpful at all. You have to jump through quite a lot of hoops from there till you get to the text at https://github.com/tesseract-ocr/tessdata_fast which explains "These models only work with the LSTM OCR engine of Tesseract 4."

### Expected Behavior:

A less cryptic error.

### Suggested Fix:

Surely it should be possible to post a more helpful message explaining that the trained data lacks support for the selected engine, and maybe even explaining that this is commonly the case with packaged distributions of 4.x?

**Comment by zaidipoetra754** [comment]
Mohon maaf mata saya kurang baik dan tolong tuntun saya dengan bahasa Indonesia. Saya lagi belajar untuk program ini dari phyton dan Google untuk melindungi keluarga saya. Mohon maaf saya meminta bantuannya untuk dibimbing aplikasi tracker pelacak WhatsApp messenger isteri. Sebelumnya dan sesudahnya terimakasih Python dan tim Github. Sukses selalu buat semua untuk keselamatan dunia teknologi dan informasi.salam hormat

**Comment by zaidipoetra754** [comment]
Mohon ijinkan Aplikasi tracker pelacak WhatsApp messenger

**Comment by zaidipoetra754** [comment]
Apakah data dan engine dalam sistem handphone saya Xiaomi Mi Max 2 bisa dibantu diperbaiki dengan aplikasi

**Comment by zaidipoetra754** [comment]
Apabila tidak bisa, apakah bisa lewat disini tracker WhatsApp messenger memakai no kontak nya

**Comment by 13520836103** [comment]
12

**Comment by zaidipoetra754** [comment]
Terima kasih pemberitahuan nya, sudah saya hapus sesuai petunjuk. Terus terang saya lagi dalam proses pembelajaran. Sudah 3 Minggu saya belum mendapatkan hasil dalam pembuktian isteri saya kabur dari rumah dan menelantarkan yayasan Anak Asuh panti asuhan, Salam hormat buat semua yang sudah memberikan info
