### ISSUE TITLE
Training tesseract tesstrain.sh exits with a warning

### ISSUE THREAD

**Issue by rakesh-km** [tesseract-ocr/tesseract#2054]
src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only \
  --noextract_font_properties --langdata_dir ../langdata \
  --tessdata_dir ./tessdata --output_dir ~/tesstutorial/engtrain

throws warning : 
mktemp: option requires an argument -- t
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 

------------------------

### Environment

* **Tesseract Version**:  4.0.0
* **Commit Number**: NA
* **Platform**: Mac OS

**Comment by rakesh-km** [comment]
now it throws error in language-specific.sh

=== Starting training for language 'eng'
/tesseract/src/training/language-specific.sh: line 1175: FONTS: unbound variable

**Comment by zdenop** [comment]
@stweil: #2051 fix nothing

**Comment by johnlinp** [comment]
> @stweil: #2051 fix nothing

Why did you say so? Is there any problem with my fix?

**Comment by rakesh-km** [comment]
#2051 fixed the issue with mktemp. However the error now is the one that I have mentioned in the comment.

**Comment by zdenop** [comment]
@rakesh-km: than you problem should be not with mktemp (on mac usage is the same as before patch), but with this 2 definitions (there is missing `$`):
```
line 38: FONT_CONFIG_CACHE=$(${MKTEMP_DT} font_tmp.XXXXXXXXXX)
line 212: TMP_DIR=$(${MKTEMP_DT} ${LANG_CODE}-${TIMESTAMP}.XXX)
```

**Comment by stweil** [comment]
Yes, `$` was missing. Pull request #2051 fixes that, too.

**Comment by stweil** [comment]
@zdenop, [line 32](https://github.com/tesseract-ocr/tesseract/blob/master/src/training/tesstrain_utils.sh#L32) is causing the first error message on macOS. The pull request fixes this line.

**Comment by stweil** [comment]
The problem with error `unbound variable` seems to require lots of changes because it occurs not only on the line reported above. I can fix it by replacing `test -z "${VAR}"` by `test -z "${VAR:-}"`. Maybe `test -v VAR` would be better (at least for some cases).

I still don't know why this problem occurs with bash on macOS, but not on Linux. Hints are appreciated.

**Comment by stweil** [comment]
Commit 486940687c5e3020c60ad0a1d28cc3eb1e49d561 added `set -u` which activates the `unbound variable` error for bash.

**Comment by johnlinp** [comment]
@stweil I proposed a fix to fix the unbound variable problem. Thanks.

**Comment by stweil** [comment]
Does pull request #2058 fix this issue?

**Comment by rakesh-km** [comment]
sorry for the late response. Issues are fixed.

**Comment by lighting1012** [comment]
Hi,all,
I also met this problem when I tried to training tesseract 4.0. Is there any solution to this?
[root@VM_0_10_centos tesseract-4.0.0]# src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang chi_sim --linedata_only --noextract_font_properties --langdata_dir ../langdata --tessdata_dir ./tessdata --output_dir ~/tesstutorial/chi_simtrain

=== Starting training for language 'chi_sim'
src/training/language-specific.sh: line 1109: FONTS: unbound variable

Thanks.
