### ISSUE TITLE
tessedit_char_whitelist won't work for R package 4.0

### ISSUE THREAD

**Issue by AthenaHann** [tesseract-ocr/tesseract#2066]
------------------------

### Environment

* **Tesseract Version**:Tesseract 4.0 in R

* **Platform**: Windows 64-bit with R 3.5.1

### Current Behavior:

```
engine = tesseract(options = list(tessedit_char_whitelist = '0123456789'))
text = ocr('2.png',engine = engine)
```

![2](https://user-images.githubusercontent.com/45201560/48773720-2d919300-ed03-11e8-934d-22cde52200bb.png)

### Expected Behavior:

Only numbers should be returned after detection but some characters are returned.

**Comment by stweil** [comment]
This is a known issue: whitelisting is not implemented for the new LSTM based language models. It should still work with the models from [tessdata](http://github.com/tesseract-ocr/tessdata) and command line option `--oem 0` (legacy engine only).

**Comment by stweil** [comment]
Closing this issue because it is a duplicate.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/ReleaseNotes#tesseract-release-notes-oct-29-2018---v400
See the **important notes**

**Comment by stweil** [comment]
Maybe we can print a warning if blacklist or whitelist is set with an LSTM model.

**Comment by stweil** [comment]
LSTM currently has more [missing features](https://github.com/tesseract-ocr/tesseract/wiki/Planning#features-from-30x-which-are-missing-for-lstm).
