### ISSUE TITLE
How to Add newly created trained data to makefile Tesseract-OCR

### ISSUE THREAD

**Issue by sush0907** [tesseract-ocr/tesseract#207]
I have created new Trained data "eng2.traineddata", now i want to add it to config folder. not by this step "sudo cp eng2.traineddata /usr/local/share/tessdata/"

want to add in makefile and then install tesseract. ../tesseract-ocr/tessdata/Makefile.in
Dont want to execute by "tesseract test.png test -l eng2"
Want to make this as default.

can anybody help me with steps which all files do i need to change.

**Comment by zdenop** [comment]
For asking support please use the tesseract-ocr user forum (https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice)
