### ISSUE TITLE
read_params_file: Can't open -psm

### ISSUE THREAD

**Issue by gg4u** [tesseract-ocr/tesseract#2073]
I got to reopen this issue, cannot use parameters:

```
tesseract mybook.tif  mybookSearchable pdf --psm 3
read_params_file: Can't open -psm
read_params_file: Can't open 3

```
same with `-` or `--` to specify options:

```
mybook.tif  mybookSearchable pdf -l eng -psm 3
read_params_file: Can't open l
read_params_file: Can't open eng
read_params_file: Can't open psm
read_params_file: Can't open 3
```

Using:
```
tesseract 4.0.0
 leptonica-1.76.0
  libjpeg 9c : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.5
 Found AVX2
 Found AVX
 Found SSE
```

althout langs get listed:

```
tesseract --list-langs
List of available languages (2):
eng
osd

```

**Comment by stweil** [comment]
See `tesseract --help`:

      tesseract imagename outputbase [options...] [configfile...]

Options must be passed before configfiles. You tried to add options after the `pdf` configfile, so they are handled as configfiles (which don't exist).
