### ISSUE TITLE
Tesseract TESSDATE_PREFIX

### ISSUE THREAD

**Issue by zelade** [tesseract-ocr/tesseract#2077]
### Environment

* **Tesseract Version**: 

tesseract 4.0.0
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found SSE

* **Platform**: 

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

### Current Behavior:

I have the Problem, that i cant use the language files, because the path seems to be wrong.
The Tessdate is in "/usr/share/tesseract-ocr/4.00/tessdata/" and not in "/usr/local/share/tessdata/".
I tried to remove the packages and reinstall, but after removing i can still check the tesseract Version in terminal. And a fresh installation didn't fix it.
Note the error below.

~$ tesseract --list-langs
Error opening data file /usr/local/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.

**Comment by jsbien** [comment]
Cf. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913951

**Comment by zdenop** [comment]
IMO: This is not tesseract project issue, but user problem (maybe packager). 
There are  3 repositories of tessdatas and tesseract does not install any of them - it is up to users which they will use.
User can select proper tessdata directory (e.g in case of installing trainneddata from more repositories) by API, `TESSDATA_PREFIX `or `--tessdata-dir`.
