### ISSUE TITLE
Feature: Don't generate the default dir='ltr' in hocr 

### ISSUE THREAD

**Issue by wollmers** [tesseract-ocr/tesseract#208]
As far as I know dir='ltr' is default in HTML or could be inherited from a parent element (e.g. html, body, p). Should be enough only generating dir='rtl' where it applies.

Reasons:

1) Google Chrome and Safari have a funny bug 

    If the rightmost span element in a line has the attributes contenteditable="true" and dir="ltr",
    the cursor cannot move left of the first character in this element.

Of course I can filter it away before exposing to my JS hOCR editor.

2) Space consuming bloat.

**Comment by tfmorris** [comment]
I've generated a patch to address the immediate issue of text direction which will workaround the browser bugs, but more could be done to compress spans with the same text attributes, including language, bold, italics, font attributes (if they're being outputted). Any given page is likely to only have a few combinations of any of these.

The next most voluminous attribute is probably the per-word `lang` attribute, so perhaps I'll see if I can address that as well...

**Comment by tfmorris** [comment]
PR #224 has a patch to generate fewer `lang` attributes.
