### ISSUE TITLE
lt-lstmtraining: genericvector.h:720: T& GenericVector<T>::operator[](int) const [with T = char]: Assertion `index >= 0 && index < size_used_' failed.

### ISSUE THREAD

**Issue by khosrobeygizohre** [tesseract-ocr/tesseract#2081]
Hi,
I have been runnig about 130G data which are 4000 files. My command is

/home/kddlab/Desktop/tesseract-master/src/training/lstmtraining   \
  --traineddata /home/kddlab/Desktop/tesseract-master/src/training/langdata/fas/fas/fas.traineddata   --net_spec '[1,48,0,1Ct3,3,16Mp3,3Lfys64Lfx96Lrx96Lfx192O1c165]' \
  --model_output /home/kddlab/Desktop/tesseract-master/src/training/langdata/fas/Out_Checkpoint/base --learning_rate 0.001 \
  --train_listfile /home/kddlab/Desktop/tesseract-master/src/training/langdata/fas/fas.training_files.txt \
  --eval_listfile /home/kddlab/Desktop/tesseract-master/src/training/langdata/fas/v/fas.training_files.txt \ --max_iterations 150000 &>/home/kddlab/Desktop/tesseract-master/src/training/langdata/fas/Out_Checkpoint/basetrain.log

but after reading some files the tesseract gives the error and stop training:

Loaded 821/10179 pages (1-821) of document /home/kddlab/Desktop/tesseract-master/src/training/langdata/fas/AllLstm/fas.B_Lotus.exp2778.lstmf
lt-lstmtraining: genericvector.h:720: T& GenericVector<T>::operator[](int) const [with T = char]: Assertion `index >= 0 && index < size_used_' failed.
Could you please help me?

**Comment by zdenop** [comment]
reference: https://groups.google.com/d/msg/tesseract-ocr/FC8eb6ji3sY/DQtidKDACwAJ
