### ISSUE TITLE
Issue with unicode lib in compiling Tesseract source 

### ISSUE THREAD

**Issue by Steven-Soon** [tesseract-ocr/tesseract#2085]
I have a similar issue with this one https://github.com/tesseract-ocr/tesseract/issues/592. To be exact, the compilation process of Tesseract from source failed with Linker error related to pvt.cppan.demo.unicode.icu.i18n-63.1.0.

Here is my development environment 
**Tesseract Version**: https://github.com/tesseract-ocr/tesseract (main repository)
**OS**: Microsoft Windows 10 64 bits Build 17134
**IDE**: Microsoft Visual Studio Enterprise 2015 64 bits version 14.0.25431.01 update 3
**Others**: CMAKE version 3.11.3, CPPAN version latest (I have done the --self-upgrade thingy)

Steps I used (similar to the wiki in this https://github.com/tesseract-ocr/tesseract/wiki/Compiling)
cd tesseract-master
mkdir win64 && cd win64
cppan ..
cmake .. -G "Visual Studio 14 2015 Win64"

Then I proceed to build the INSTALL in release mode in VS2015.

CPPAN output: https://gist.github.com/Steven-Soon/572a7fccfe9955dd43d639505ff4bd35
CMAKE output: https://gist.github.com/Steven-Soon/59694ba1f35fc0eb3af7df4242a73d46
VS2015 output: https://gist.github.com/Steven-Soon/781f0401033d9f63a8332b312875a4db

any help is appreciated, thanks.

**Comment by egorpugin** [comment]
First thing.

Try to run cmake as follows:
```
cmake .. -G "Visual Studio 14 2015 Win64" -DBUILD_TRAINING_TOOLS=Off
```

---

If above does not help.

Is it possible to test your commands with VS2017?
The problem there is in glib compilation which may not work under VS2015 (not 100% sure).

**Comment by Steven-Soon** [comment]
> First thing.
> 
> Try to run cmake as follows:
> 
> ```
> cmake .. -G "Visual Studio 14 2015 Win64" -DBUILD_TRAINING_TOOLS=Off
> ```

With -DBUILD_TRAINING_TOOLS=Off, the compilation still failed but with no linker error
Output: https://gist.github.com/Steven-Soon/780693f89923e37dcb08b4e22fec8f7d 

> If above does not help.
> 
> Is it possible to test your commands with VS2017?
> The problem there is in glib compilation which may not work under VS2015 (not 100% sure).

I don't have VS2017 in my workstation, but I have MinGW installed

**Comment by egorpugin** [comment]
Actually VS2015 passes on appveyor.
https://ci.appveyor.com/project/zdenop/tesseract

I've made a new cppan build (I'm the author), could you check tess build with it?
Just replace binary and re-run these commands (and build after).
```
cppan ..
cmake .. -G "Visual Studio 14 2015 Win64"
```
[cppan.zip](https://github.com/tesseract-ocr/tesseract/files/2636933/cppan.zip)

**Comment by Steven-Soon** [comment]
Hi, 

Sorry for the late response,  I was busy. 

**Update**
The build still fails with custom cppan (i've clean the storage and start everything clean) and above commands. particularly with build related to pvt.cppan.demo.unicode.icu.i18n-63.1.0.lib and pvt.cppan.demo.gnome.pango.pangocairo-1.42.3.lib.

Digging deep into the build output revealed a bunch of errors (code c2001) which I suspect it is encoding related issue.

Few approaches I took to solve the issue
1) Project setting - character set to Unicode instead of multi-byte (doesn't work)
2) Control panel - Language setting - non-unicode program (Chinese PRC -> English) (work)

Build output after changing language setting: https://gist.github.com/Steven-Soon/a864fc3110431de717054f836f19b875

With the last issue related to administrative privileges in creating a directory in program files.. (not a big deal).

**Comment by zdenop** [comment]
Closing as solved. In any case can you please check [cmake build without cppan](http://www.sk-spell.sk.cx/building-tesseract-and-leptonica-with-cmake-and-clang-on-windows) (you can use VS instead of clang - see Conclusion there) and changing language setting?
