### ISSUE TITLE
using DISABLED_LEGACY_ENGINE disables all other PSM

### ISSUE THREAD

**Issue by crivas** [tesseract-ocr/tesseract#2087]
### Environment

* **Tesseract Version**: Master
* **Commit Number**:9e49539429261cbb97a03dc6a94e3d974482878f
* **Platform**: Windows

### Suggested Fix: 
find this line in tesseractmain.cpp

` } else if (tesseract::PSM_SPARSE_TEXT_OSD) {
`

replace with

`if (cur_psm == tesseract::PSM_SPARSE_TEXT_OSD)`

**Comment by crivas** [comment]
Environment
Tesseract Version: Master
Commit Number: 9e49539429261cbb97a03dc6a94e3d974482878f
Platform: Windows
Current Behavior: define DISABLED_LEGACY_ENGINE when checking cur_psm the default one always is PSM_SPARSE_TEXT
Expected Behavior: allow to use the other psm
Suggested Fix: `if (**cur_psm ==** tesseract::PSM_SPARSE_TEXT_OSD)`

**Comment by amitdo** [comment]
>Platform: Windows

MSVC/MinGW-w64/Cygwin ?

What's the full command you used?

What's the output in the terminal?

**Comment by crivas** [comment]
Platform: **Windows MSVC 2015 using CPPAN and cmake ..  -G "Visual Studio 14 2015"**
Command: **tesseract.exe Sample.jpeg - --tessdata-dir tessdata --psm 4 -l eng**
Output: **Warning: The page segmentation mode 12 (Sparse text + OSD) is currently disabled. Using PSM 11 (Sparse text) instead.
ABC123**

**Comment by amitdo** [comment]
@egorpugin

https://github.com/tesseract-ocr/tesseract/blob/92b88338384e2b247f0070cb856440e86088d446/configure.ac#L161

Can you add an equivalent option to CMake?

**Comment by egorpugin** [comment]
`-DENABLE_LEGACY=On/Off` ?

**Comment by crivas** [comment]
Please open this link and go to line 655

https://github.com/tesseract-ocr/tesseract/blob/3d508a65a7d6600689b99f99a2d81b224f5e023d/src/api/tesseractmain.cpp

there is this block of code

```
  } else if (tesseract::PSM_SPARSE_TEXT_OSD) {    <--should be cur_psm == tesseract::PSM_AUTO_OSD
      api.SetPageSegMode(tesseract::PSM_SPARSE_TEXT);
      osd_warning +=
          "\nWarning: The page segmentation mode 12 (Sparse text + OSD) is currently disabled. "
          "Using PSM 11 (Sparse text) instead.\n\n";
  }

```

**Comment by egorpugin** [comment]
Fixed in https://github.com/tesseract-ocr/tesseract/commit/685b136d89178ec49b723fabebea88bdb5885f98, thanks!

**Comment by zdenop** [comment]
Can you please check if issue is solved? If yes, please close issue or provide your results.
