### ISSUE TITLE
Binaries for windows

### ISSUE THREAD

**Issue by VanKurt** [tesseract-ocr/tesseract#209]
Where can I download Tesseract for Windows?
All Links point to code.google.com, but since Tesseract has moved here all links are dead.

Also I would like to downoad different versions (2.x, 3.x) to see if any of them works.
The version I have right now (3.05 Setup) does not read any images but produces errors instead.

**Comment by stweil** [comment]
That might be caused by missing permissions: all but the latest versions try to create temporary files in the root directory c:\.(that's caused by the code coming from Leptonica).

**Comment by egorpugin** [comment]
Leptonica can be built on windows. But by default it is built without any image libraries (i.e. cannot load/save images). So, no png,gif,tiff functions available.
In such mode tesseract will only handle raw image input from api, not any exe calls.

**Comment by VanKurt** [comment]
OK, thanks for the replies. Can I download a version somewhere that
a) Does not have the bug mentioned by stweil
b) Includes the image loading functionality

On https://github.com/tesseract-ocr/tesseract/wiki/Downloads it says "Currently, there is no official Windows installer for newer versions." :-(
The 3.05 setup from https://github.com/UB-Mannheim/tesseract/wiki does also not work (as mentioned above).

**Comment by egorpugin** [comment]
Try these binaries compiled by me.
https://dl.dropboxusercontent.com/u/19622060/tesseract-3.05.00dev-win32-vc19.zip
You have to install VC2015 x86 redist from microsoft.com

**Comment by amitdo** [comment]
> Also I would like to downoad different versions (2.x, 3.x) to see if any of them works.

http://sourceforge.net/projects/tesseract-ocr-alt/files/

**Comment by bantilan** [comment]
Hi, I made a step by step guide how to compile Tesseract on Windows.. You can check my guide's here: http://gensanblog.com/2016/01/28/how-to-compile-tesseract-git-project-on-windows/

You can also download the compiled version..

**Comment by zdenop** [comment]
@bantilan: please add it https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows (every github used can modify it)

**Comment by egorpugin** [comment]
It's a bad guide. Do not add it anywhere.
1. Windows binaries should be made with MSVC, not cygwin. Why do you install Visual Studio and do not use it? You use only cygwin stuff. Which won't run if you distribute it without cygwin.
2. https://github.com/egorpugin/leptonica.git is not correct leptonica distributive anymore. Use official https://github.com/DanBloomberg/leptonica/releases 1.73+ release.

**Comment by egorpugin** [comment]
I uploaded my local branch with almost all leptonica's deps sources to https://github.com/egorpugin/leptonica/tree/with_libs. You can find them in /dep. Most of those were taken from opencv distribution. They can be somewhere misconfigured etc. Also that branch is following master branch of leptonica, so probably not so stable as release.
When you build this leptonica branch, result library will support many image libraries, therefore tesseract does too when linked with it.

**Comment by bantilan** [comment]
Hi Egor, thank you for correcting.. I am new to this and I made lots of edit's on the guide.. I will edit my post and focus on cygwin, I also added dll's so that it can run without cygwin.. I'll create a new guide for MSVC..

**Comment by Shreeshrii** [comment]
@egorpugin : Could you also build the training program - text2image for windows

**Comment by egorpugin** [comment]
No, I can't.
That's the single binary that cannot be easily built with MSVC.

**Comment by Shreeshrii** [comment]
@egorpugin: OK.

@zdenop : There are a number of older requests/issues for windows build. I'll add a comment to refer to this issue and you could close them. Thanks!

**Comment by Shreeshrii** [comment]
@egorpugin - Are the windows binaries at 
https://www.dropbox.com/s/8t54mz39i58qslh/tesseract-3.05.00dev-win32-vc19.zip?dl=1

**Comment by egorpugin** [comment]
They are from master branch. Probably on this commit ec44221e336dd9

**Comment by Shreeshrii** [comment]
Thanks for clarifying, @egorpugin .

I was confused after seeing the following on the releases page:
```
on Jul 22, 2015 
3.05.00dev  …
increase version number
 71e226c   zip   tar.gz
```

**Comment by nickbe** [comment]
This build does not create PDFs, but the cygwin build does.

**Comment by amitdo** [comment]
@egorpugin, can you confirm this?

**Comment by egorpugin** [comment]
Did not run tests on my binaries, so it's possible.

**Comment by amitdo** [comment]
@nickbe, one more (unofficial) option for Windows:
https://github.com/UB-Mannheim/tesseract

**Comment by stweil** [comment]
The installers (made with MinGW-w64) are at https://github.com/UB-Mannheim/tesseract/wiki.

**Comment by amitdo** [comment]
Yeah. For some reason I omitted the 'wiki' part from the link.

**Comment by nickbe** [comment]
https://github.com/UB-Mannheim/tesseract doesn't seem to provide binaries right now.

**Comment by stweil** [comment]
@nickbe, just add `/wiki` to that URL...

**Comment by nickbe** [comment]
But these do not seem to be the VC binaries, or are they? There's only a problem with generating PDFs with the VC runtimes.

**Comment by stweil** [comment]
That's right, the UB Mannheim executables are built with [Mingw-w64](http://mingw-w64.org/).

**Comment by jbreiden** [comment]
What is this business about certain builds not supporting PDF output? There is nothing special or weird with that section of code. Are they just old builds from before the feature was created, or is there something else going on?

**Comment by egorpugin** [comment]
Is there a simple command to check pdf generation?
I'll try to debug the issue (if any).

**Comment by amitdo** [comment]
The discussion about the PDF issue in egor build should be continued in #338

**Comment by Shreeshrii** [comment]
Latest VC binaries by @egorpugin with PDF generation are at following link, as per  [#338](https://github.com/tesseract-ocr/tesseract/issues/338): https://www.dropbox.com/s/pxu2hp6mg1a64zj/tesseract-3.05.00dev-win32-vc19-2016-jun-03.zip?dl=1

**Comment by nickbe** [comment]
Great. Thanks !

**Comment by egorpugin** [comment]
Hi!

I'd like to share one more way of building tesseract(+leptonica+other_image_libraries) on Windows. Linux probably will work too.

1. Download and install Git, CMake and put them in PATH.
2. Download the latest CPPAN (C++ Archive Network https://cppan.org/) client from https://cppan.org/client/. CPPAN is a source package distribution system. (Like biicode or conan but for sources. Also the idea came from CPAN/CTAN/CRAN.) Add CPPAN client in PATH too. (VS2015 redist is required.)
3. Run
```
git clone https://github.com/tesseract-ocr/tesseract tesseract
cd tesseract
cppan
mkdir build && cd build
cmake .. -DSTATIC=1
```
4. Build a solution in VS tesseract.sln

So, the build should be pretty straightforward and available for everyone with installed Visual Studio. You can try it on any version supported by tesseract.

If you like the way of building tesseract with CPPAN, I could implement such easy way of integration of tesseract into user (your) apps.

Sorry for the noise.

**Comment by zdenop** [comment]
@egorpugin: thanks! I tried it in VS2010 and I face one problem: 
this version of giflib can not be built by VS2010 (Cannot open include file: 'stdbool.h': No such file or directory). Is it possible to make it optionable (to ignore gif library) or to use other version of library (older 4.? was possible to build with VS2010)?

**Comment by egorpugin** [comment]
During normal workflow this is not possible.

Because of the following:
tesseract is binded to leptonica (some version, e.g. future 1.74);
leptonica is binded to giflib (e.g. v5.1.2).

So you cannot control leptonica's dependencies.
And you must use appropriate and supported compilers of these libraries to compile your project.
Now you'd like to use an older version of giflib. The idea is clear, I understand this, you want to work on older compiler. But using old version of libraries can bring (and it does) potential security breaches.

But now  it's possible to introduce some changes to **demo** giflib itself. I've added some ifdefs to control usage of stdbool.h, so you can check if it works. Just re-run cppan command in tesseract dir and try to build a VS solution.

**Comment by M1chae1** [comment]
@egorpugin I have following the instruction. 

However CPPAN returns
> Requesting dependency list
> SSL connect error

Is that any configuration I am missing?

**Comment by egorpugin** [comment]
Usually it means that you don't have a letsencrypt certificate installed on your system (old ubuntu etc.). I've added an option ('-k' or '--ignore-ssl-checks') to skip strict ssl checks. Please, re-download the client and run 'cppan -k'. For more info see 'cppan -h'. On windows you can upgrade the client with 'cppan --self-upgrade' (only if this option is available, check 'cppan -h').

**Comment by egorpugin** [comment]
FYI I've added simple guide how to build tesseract on Windows https://github.com/tesseract-ocr/tesseract/wiki/Compiling#master-branch-305-and-later
Also the simple user app example with tesseract (using cmake+cppan) is available here https://github.com/tesseract-ocr/tesseract/wiki/User-App-Example

**Comment by avestnik** [comment]
@egorpugin I tried your way for getting static lib with -DSTATIC=1

> I'd like to share one more way of building tesseract(+leptonica+other_image_libraries) on Windows. Linux probably will work too.

I built && installed it w/o any issues but linking my app with it failed with two issues:
* Error LNK1104	cannot open file 'tesseract.lib'	
I fixed it in [install-folder]/cmake/TesseractConfig.cmake 
set(Tesseract_LIBRARIES tesseract) => set(Tesseract_LIBRARIES **lib**tesseract)

* Error LNK1104	cannot open file 'pvt.cppan.demo.danbloomberg.leptonica.lib'
I fixed it by editing [install-folder]/cmake/TesseractTargets-debug.cmake and removing the following line

  set_target_properties(libtesseract PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
    ~~IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Ws2_32;pvt.cppan.demo.danbloomberg.leptonica"~~
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/tesseract400d.lib"
    )

please advise if it is correct

**Comment by egorpugin** [comment]
This guide is quite old. I think it's about tesseract building, not linking to your app. It's quite different or might have additional steps.
