### ISSUE TITLE
-Wtautological-undefined-compare warning in tabvector.cpp

### ISSUE THREAD

**Issue by rmtheis** [tesseract-ocr/tesseract#21]
Another `-Wtautological-undefined-compare` warning when building for Android using clang and tess-two:

    jni/com_googlecode_tesseract_android/src/textord/tabvector.cpp:526:7: warning: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to false [-Wtautological-undefined-compare]
      if (this == NULL) {
          ^~~~    ~~~~

**Comment by tfmorris** [comment]
Both #21 and #22 are caused by something buried inside the tprintf() macro expansion.

**Comment by rmtheis** [comment]
This was fixed in 4fdf272ffa2897648d6899ea014cf79d76e509aa.
