### ISSUE TITLE
tesseract 4.00 exit 1 with several different tiffs

### ISSUE THREAD

**Issue by clarkk** [tesseract-ocr/tesseract#2103]
I get the below error when passing several different images to tesseract

```
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x1efe4f0 still has count 1 (id /usr/local/share/tessdata/dan.traineddatalstm-punc-dawg)
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x1ce7610 still has count 1 (id /usr/local/share/tessdata/dan.traineddatalstm-word-dawg)
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x1ef08c0 still has count 1 (id /usr/local/share/tessdata/dan.traineddatalstm-number-dawg)
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x3465870 still has count 1 (id /usr/local/share/tessdata/eng.traineddatalstm-punc-dawg)
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x298c100 still has count 1 (id /usr/local/share/tessdata/eng.traineddatalstm-word-dawg)
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x1ef0240 still has count 1 (id /usr/local/share/tessdata/eng.traineddatalstm-number-dawg)
```

I use a modification of this example from the wiki.. It works on most images but some images makes tesseract program return exitcode `1`

I use `OEM_LSTM_ONLY`

tesseract::TessBaseAPI.Version() => `4.0.0-86-gbee8`

Here are the images
https://imgur.com/a/e5vyzLL

```
  Pix *image = pixRead("/usr/src/tesseract/testing/phototest.tif");
  tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
  api->Init(NULL, "eng");
  api->SetImage(image);
  api->Recognize(0);
  tesseract::ResultIterator* ri = api->GetIterator();
  tesseract::PageIteratorLevel level = tesseract::RIL_WORD;
  if (ri != 0) {
    do {
      const char* word = ri->GetUTF8Text(level);
      float conf = ri->Confidence(level);
      int x1, y1, x2, y2;
      ri->BoundingBox(level, &x1, &y1, &x2, &y2);
      printf("word: '%s';  \tconf: %.2f; BoundingBox: %d,%d,%d,%d;\n",
               word, conf, x1, y1, x2, y2);
      delete[] word;
    } while (ri->Next(level));
  }
```

# install
```
- Install Leptonica
# apt-get install libleptonica-dev

- Install 4.00 from source
# apt-get install autoconf automake libtool pkg-config
# cd /var/bin && git clone https://github.com/tesseract-ocr/tesseract.git tesseract-4.00
# cd tesseract-4.00 && ./autogen.sh && ./configure && make -j $(nproc) && make install && ldconfig

- Install language fastest (4.00 - only works with OEM_LSTM_ONLY)
# cd /usr/local/share/tessdata && wget https://github.com/tesseract-ocr/tessdata_fast/raw/master/eng.traineddata && wget https://github.com/tesseract-ocr/tessdata_fast/raw/master/dan.traineddata
```

**Comment by zdenop** [comment]
I already asked you to respect guidelines! Use tesseract user forum for asking support.

**Comment by clarkk** [comment]
This must be a bug...?

**Comment by zdenop** [comment]
Probably yes - in your code unless you prove it with tesseract executable ;-)
We DO NOT SUPPORT 3d party projects.

**Comment by clarkk** [comment]
Ok

I have now copy/pasted the example directly from the wiki.. and it produce the extact same error with exitcode `1`

This must be a bug in the API

```
#include <tesseract/baseapi.h>
#include <leptonica/allheaders.h>

/*
	g++ -rdynamic -O2 -std=c++11 test.cpp -o test -llept -ltesseract
*/

int main()
{
  Pix *image = pixRead("/root/test/003.tif");
  tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
  api->Init(NULL, "eng");
  api->SetImage(image);
  api->Recognize(0);
  tesseract::ResultIterator* ri = api->GetIterator();
  tesseract::PageIteratorLevel level = tesseract::RIL_WORD;
  if (ri != 0) {
    do {
      const char* word = ri->GetUTF8Text(level);
      float conf = ri->Confidence(level);
      int x1, y1, x2, y2;
      ri->BoundingBox(level, &x1, &y1, &x2, &y2);
      printf("word: '%s';  \tconf: %.2f; BoundingBox: %d,%d,%d,%d;\n",
               word, conf, x1, y1, x2, y2);
      delete[] word;
    } while (ri->Next(level));
  }
}
```

**Comment by clarkk** [comment]
This example is used as is and it produce the same error.. so this must be a bug somewhere in the API

https://github.com/tesseract-ocr/tesseract/wiki/APIExample#result-iterator-example

**Comment by zdenop** [comment]
It is just short example what you can do with API - not how to program and handle all possible issue!

**Comment by clarkk** [comment]
The error occurs at this line

```
api->Init(NULL, "eng");
```

Can't see how you can handle an issue when the API is initiated?

**Comment by clarkk** [comment]
The code works fine for the most images.. but for some the program exit with `1`

**Comment by amitdo** [comment]
>ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK!

To avoid the leaks, you should do what tesseract does here:
https://github.com/tesseract-ocr/tesseract/blob/f0a4d04187da58883dc86e7855b6f520b384d9eb/src/api/tesseractmain.cpp#L572-L578

**Comment by clarkk** [comment]
Thanks :)

This should be a part of the examples..

But which file do I have to include?

```
test.cpp: In function ‘int main()’:
test.cpp:11:3: error: incomplete type ‘tesseract::Dict’ used in nested name spec                  ifier
   tesseract::Dict::GlobalDawgCache();
   ^

```

**Comment by clarkk** [comment]
#include <tesseract/dict.h>

test.cpp:2:28: fatal error: tesseract/dict.h: No such file or directory

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/f0a4d04187da58883dc86e7855b6f520b384d9eb/src/dict/Makefile.am#L12-L13

@stweil, I think we should install the `dict.h` header.

**Comment by clarkk** [comment]
How can I manually install the headers? :) And do I only need `dict.h` ?

**Comment by clarkk** [comment]
When adding `dict.h` I get a new error

```
In file included from test.cpp:2:0:
/usr/local/include/tesseract/dict.h:22:20: fatal error: ambigs.h: No such file or directory
 #include "ambigs.h"
                    ^

```

**Comment by amitdo** [comment]
Copy it to the dir where the other tesseract headers live in your system.

Probably to `/usr/local/tesseract`.

**Comment by amitdo** [comment]
You already did so (I missed your last message).

**Comment by amitdo** [comment]
Which error are you referring now?

**Comment by clarkk** [comment]
The one from the first post

```
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x1efe4f0 still has count 1 (id /usr/local/share/tessdata/dan.traineddatalstm-punc-dawg)
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x1ce7610 still has count 1 (id /usr/local/share/tessdata/dan.traineddatalstm-word-dawg)
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x1ef08c0 still has count 1 (id /usr/local/share/tessdata/dan.traineddatalstm-number-dawg)
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x3465870 still has count 1 (id /usr/local/share/tessdata/eng.traineddatalstm-punc-dawg)
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x298c100 still has count 1 (id /usr/local/share/tessdata/eng.traineddatalstm-word-dawg)
ObjectCache(0x7f3b07159740)::~ObjectCache(): WARNING! LEAK! object 0x1ef0240 still has count 1 (id /usr/local/share/tessdata/eng.traineddatalstm-number-dawg)
```

**Comment by amitdo** [comment]
>but why is the reason for the error?

In short: 'Object Lifetime'.

>is it because the OCR result is empty or something?

No.

**Comment by clarkk** [comment]
@zdenop The mix of `dan` and `eng` is becauase I made a copy/paste to prove that there was an issue

The last code example is a direct copy/paste of an examaple from the wiki..

If it's not a bug why does it not come clear of the examples how to handle this? From the comments in the code it looks like a hack to solve an issue

**Comment by amitdo** [comment]
I don't see how someone using the API can handle the dawgs caching like tesseact does.

@stweil, can you say what you think about this issue?

**Comment by stweil** [comment]
The current code in tesseractmain.cpp is a hack, and we should not force users of the API to understand and use the same kind of hack in their code. So we need a better solution for the DawgCache object in the future.

Until that solution is available, there will be a memory leak for applications using the API. I don't think that this is a big problem as memory usage does not grow over time.

**Comment by clarkk** [comment]
@stweil thanks for the confimation :)

looking forward to a solution..

**Comment by zdenop** [comment]
This is not bug (at least not proved).
Solution is to use correctly API (which you did not). 
If you do not how, asks at right place - use forum.

**Comment by clarkk** [comment]
@amitdo @stweil

**Comment by clarkk** [comment]
So how is the "correct" way to use the API?

Can't see anything from the examples?

https://github.com/tesseract-ocr/tesseract/wiki/APIExample
