### ISSUE TITLE
what is the output of TF convention?

### ISSUE THREAD

**Issue by khosrobeygizohre** [tesseract-ocr/tesseract#2105]
I'm training tesseract from scratch for the Persian Language. But I need to know about the output of TF convention because it is the input of lstm. Wiki says, for example, ct5,5,32. I couldn't understand the number of output. In this case,32 is depth. but how about the number of output. Besides, somewhere say, 32 is the number of the filter. Can anyone describe it to me?
In summary, when the network is:
[1,48,0,1[C3,3Ft16]Mp3,3Lfys64Lfx96Lrx96Lfx192Fc165]
what are the numbers of inputs?

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesseract/wiki/VGSLSpecs
