### ISSUE TITLE
lstmeval give me perfect result but tesseract command failed

### ISSUE THREAD

**Issue by bredalas** [tesseract-ocr/tesseract#2112]
### Environment

* **Tesseract Version**: tesseract 4.0.0-38-gec47
* **Commit Number**: 
* **Platform**: mac osx

### Current Behavior:

I trained a model from scratch : 

I generated .box .tiff files 

I generated lstmf files with .box and .tiff files

```
for file in *.tiff; do
  echo $file
  base=`basename $file .tiff`
  tesseract --psm 7 --oem 1 $file $base ./tessdata/configs/lstm.train 
done
```

I generated unicharset with unicharset_extractor
`unicharset_extractor *.tiff`

I generated .traineddata with combine_lang_model
```
combine_lang_model \
  --input_unicharset unicharset \
  --script_dir ./tesseract/langdata_lstm-master \
  --output_dir output \
  --pass_through_recoder \
  --lang_is_rtl \
  --lang XXX
```

Then i trained a new model with lstmtraining
```
lstmtraining \
  --traineddata XXX.traineddata \
  --debug_interval -1 \
  --net_spec '[1,40,0,1 Ct5,5,64 Mp3,3 Lfys128 Lbx256 Lbx256 O1c36]' \
  --model_output ../output/ \
  --train_listfile list.train \
  --eval_listfile list.eval
```

At the end of the training at iteration 3599 : Finished! Error rate = 0

I generated the model with the last checkpoint 

```
lstmtraining --stop_training \
  --continue_from model0.086_544.checkpoint \
  --traineddata XXX.traineddata \
  --model_output model/XXX.traineddata
```

I put XXX.traineddata to tessdata and with tesseract command -l XXX i have bad results. 

For example with plateN836.lstmf lstmeval give me : 

Truth:SM363XT
OCR  :SM363XT

With with tesseract command -l XXX on plateN836.tiff i have HPYPPY9P44T.

What's wrong ? I don't understand why i have different result with lstmeval and tesseract command.

Thank you for your help.

Best regards

### Expected Behavior:
To have the same results of lstmeval

**Comment by zdenop** [comment]
Please use tesseract user forum for asking questions/support.
We do not have enough capacity to support custom training.
