### ISSUE TITLE
How to set the number of recognized characters?How to skip identifying spaces?

### ISSUE THREAD

**Issue by BigYellowHsw** [tesseract-ocr/tesseract#2114]
I have some questions. First, how to set the number of recognized characters? Second, "tessedit_char_whitelist=0123456789abcdefghijklmnopqrstuvwxyz", I have set the character set, why do I still recognize spaces? I hope anyone can help.

**Comment by stweil** [comment]
Please respect the rules and use the [user forum](https://github.com/tesseract-ocr/tesseract/wiki#support) for questions.
