### ISSUE TITLE
read_params_file: Can't open XXX

### ISSUE THREAD

**Issue by idevelopthings11** [tesseract-ocr/tesseract#2116]
### Environment

Tesseract 4.0
CentOS 7 with Tesseract installed from the repositories from here.

### Current Behavior:

 [THIS IS USING PHP]

```
Generated command:
"tesseract" "/home/admin/tmp/phpEHnJVI" -c "load_system_dawg=0" -c "page_separator=" -c "tessedit_char_whitelist=abcdefghijklmnopqrstuvwxyz0123456789-_@/:.ABCDEFGHIJKLMNOPQRSTUVWXYZ" --psm 3 --oem 1

Returned message:
read_params_file: Can't open load_system_dawg=0
read_params_file: Can't open c
read_params_file: Can't open page_separator=
read_params_file: Can't open c
read_params_file: Can't open tessedit_char_whitelist=abcdefghijklmnopqrstuvwxyz0123456789-_@/:.ABCDEFGHIJKLMNOPQRSTUVWXYZ
read_params_file: Can't open -psm
read_params_file: Can't open 3
read_params_file: Can't open -oem
read_params_file: Can't open 1
Tesseract Open Source OCR Engine v4.0.0 with Leptonica

```
The command works fine on Debian/Ubuntu but I get this error even directly on command line with CentOS 7.

### Expected Behavior:

To work.

### Suggested Fix:
IDK

**Comment by stweil** [comment]
That command won't work on any platform. Check the command line syntax!

**Comment by idevelopthings11** [comment]
The command is working on Debian/Ubuntu with no problems because it is generated automatically by https://github.com/thiagoalessio/tesseract-ocr-for-php

**Comment by stweil** [comment]
That command does not work on Debian/Ubuntu. Maybe your software generates another command there, and that other command is not buggy.

**Comment by idevelopthings11** [comment]
ok, thanks, yes, indeed is not an issue from tesseract itself but from php side and temp folders.
