### ISSUE TITLE
Tesseract 4.0.0 works very slow in Debian Jessie

### ISSUE THREAD

**Issue by bagas433** [tesseract-ocr/tesseract#2119]
### Environment

* **Tesseract Version**: tesseract 4.0.0-95-g5b65
* **Commit Number**: 
* **Platform**: Debian GNU/Linux 8 (jessie)

Hello guys, so lately i just install tesseract ocr for my linux server with specification listed above, i install tesseract ocr refer to this link https://github.com/tesseract-ocr/tesseract/wiki and since my server using Debian Jessie, then i redirect to this link https://notesalexp.org/tesseract-ocr/.

After i followed all steps to install ocr on the link above(notesalexp), i tried to recognize a picture, but unfortunately the time that used to recognize the picture is very long, for 1 image it takes 100 second maximal and about 30second mininum , I try used english and indonesian language training data.

what is the cause of this problem? I really appreciate all the answers and thank you very much!

**Comment by jbreiden** [comment]
The official answer is to use the official Debian packages from a supported
version of Debian.

>

**Comment by stweil** [comment]
A known reason is the official Linux kernel which is provided by Debian Jessie. Tesseract is much faster with a newer kernel from Debian backports or Debian Buster.
