### ISSUE TITLE
Arabic Language output is reversed

### ISSUE THREAD

**Issue by lisaied** [tesseract-ocr/tesseract#212]
Hello,

Refer to issue #169, I spend long time trying to modified language files.
Do you have a plan to update Arabic Language files in the coming releases.

Many Thanks in Advance

**Comment by amitdo** [comment]
@lisaied

>Do you have a plan to update Arabic Language files in the coming releases.

There is a plan to add a new ocr engine to tesseract in this year. There is a good chance that the accuracy of arabic recognition will be improved.
