### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by johnght** [tesseract-ocr/tesseract#2124]
Build process
1. with the .zip 4.0.0
2. cppan the unzipped directory
3. cmake-gui
4. mingw32-make
------------------------

### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**: github tag 4.0.0
* **Platform**: Windows 64-bit

### Current Behavior:
consistent compilation error:
[ 98%] Building RC object cppan/17afdf2a/CMakeFiles/17afdf2a.dir/version.rc.ob
...
version.rc:10: syntax error

c:\Users\ADP2013\Desktop\build_tess400>mingw32-make
Scanning dependencies of target cppan-d-b-d
Scanning dependencies of target 1f16f783-b-d
Scanning dependencies of target 17afdf2a
[  1%] Building C object cppan/17afdf2a/CMakeFiles/17afdf2a.dir/src/common/tuklib_cpucores.c.obj
[  2%] Building C object cppan/17afdf2a/CMakeFiles/17afdf2a.dir/src/common/tuklib_exit.c.obj
[  3%] Building C object cppan/17afdf2a/CMakeFiles/17afdf2a.dir/src/common/tuklib_mbstr_fw.c.obj
...
[ 97%] Building C object cppan/17afdf2a/CMakeFiles/17afdf2a.dir/src/liblzma/simple/x86.c.obj
[ 98%] Building RC object cppan/17afdf2a/CMakeFiles/17afdf2a.dir/version.rc.obj
C:\PROGRA~1\MINGW-~1\X86_64~1.0-P\mingw64\bin\windres.exe: C:\\Users\\ADP2013\\.cppan\\storage\\obj\\17\\af\\df2a\\build\\d9e4e86b\\cppan\\17afdf2a\\version.rc:10: syntax error
mingw32-make.exe[8]: *** [cppan\17afdf2a\CMakeFiles\17afdf2a.dir\build.make:1154: cppan/17afdf2a/CMakeFiles/17afdf2a.dir/version.rc.obj] Error 1
mingw32-make.exe[7]: *** [CMakeFiles\Makefile2:108: cppan/17afdf2a/CMakeFiles/17afdf2a.dir/all] Error 2
mingw32-make.exe[6]: *** [Makefile:83: all] Error 2
CMake Error at C:/Users/ADP2013/.cppan/storage/etc/static/functions.cmake:689 (message):
  Last execute_process() with message '' failed with error: 2
Call Stack (most recent call first):
  C:/Users/ADP2013/.cppan/storage/etc/static/build.cmake:203 (check_result_variable)
  C:/Users/ADP2013/.cppan/storage/obj/17/af/df2a/build.cmake:34 (include)

mingw32-make.exe[5]: *** [cppan\1f16f783\CMakeFiles\1f16f783-b-d.dir\build.make:56: cppan/1f16f783/CMakeFiles/1f16f783-b-d] Error 1
mingw32-make.exe[4]: *** [CMakeFiles\Makefile2:146: cppan/1f16f783/CMakeFiles/1f16f783-b-d.dir/all] Error 2
mingw32-make.exe[3]: *** [Makefile:83: all] Error 2
CMake Error at C:/Users/ADP2013/.cppan/storage/etc/static/functions.cmake:689 (message):
  Last execute_process() with message '' failed with error: 2
Call Stack (most recent call first):
  C:/Users/ADP2013/.cppan/storage/etc/static/build.cmake:203 (check_result_variable)
  C:/Users/ADP2013/.cppan/storage/obj/1f/16/f783/build.cmake:34 (include)

mingw32-make[2]: *** [.cppan\CMakeFiles\cppan-d-b-d.dir\build.make:56: .cppan/CMakeFiles/cppan-d-b-d] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:244: .cppan/CMakeFiles/cppan-d-b-d.dir/all] Error 2
mingw32-make: *** [Makefile:129: all] Error 2

c:\Users\ADP2013\Desktop\build_tess400>

### Expected Behavior:
full compilation then make install the .dll and .h (this build process works well in other projects e.g. opencv where dependencies are included in the source, not cppan)

### Suggested Fix:
Seems to be a cppan problem.

**Comment by zdenop** [comment]
Please report it at cppan https://github.com/cppan/cppan, because problem is not tesseract project.
