### ISSUE TITLE
Erro while running `brew insatll --with-all-languages`

### ISSUE THREAD

**Issue by ReinaSuo** [tesseract-ocr/tesseract#2125]
### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**: `brew install --with-all-languages`
* **Platform**: Mac OS X 10.14 

### Current Behavior:
```
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "tesseract--tessdata"
Download failed: https://github.com/tesseract-ocr/tessdata_fast/archive/4.0.0.tar.gz
```

### Expected Behavior:
No erro.

### Suggested Fix:
I am not sure. New here. Is there someone can help me? #

**Comment by zdenop** [comment]
This is  not tesseract error - please consult some Mac OS or brew support how to fix it.
