### ISSUE TITLE
engtrain cannot generatee

### ISSUE THREAD

**Issue by vivienftw** [tesseract-ocr/tesseract#2126]
HI, i am currently training tesseract 4.0, and i know i am supposed to train for language, however when i key in 
src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only \
  --noextract_font_properties --langdata_dir ../langdata \
  --tessdata_dir ./tessdata --output_dir ~/tesstutorial/engtrain
and run it, it did not give me the output_dir and did not complete running, may i know how do i solve this issue 

![issue1](https://user-images.githubusercontent.com/45947209/50103786-66217f80-0263-11e9-9118-cbf1bfa6e587.PNG)

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support.
