### ISSUE TITLE
No recognition

### ISSUE THREAD

**Issue by bostjanlaba** [tesseract-ocr/tesseract#2128]
### Environment

* **4.0.0**: 
* **Commit Number**: 
* **Windows 32 bit**: 

### Suggested Fix: no idea

Attached is the image I'm trying to get the bottom number in RED color OCRed and it's far from happening. 
I've tried grayscale, bw, contrast up, down. Nothing works. I'm supposed to scan this document and extract the number below but seems impossible. Any thoughts?
![test5](https://user-images.githubusercontent.com/24858329/50170998-7bdd8600-02f1-11e9-9b2b-c3e5cd609ade.png)

TIA

Bostjan

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
