### ISSUE TITLE
Tesseract + Music = ?

### ISSUE THREAD

**Issue by littlekai13** [tesseract-ocr/tesseract#213]
Can Tesseract be used for music sheet recognition?

**Comment by jimregan** [comment]
No, but it is used by Audiveris (https://audiveris.kenai.com/) which can.

**Comment by ultrasounder** [comment]
Didn't know that Tesseract can be used for recognizing notations!. Just what I needed.

**Comment by stweil** [comment]
> Audiveris is developed in Java, and invokes Google Tesseract (C++) for text OCR.

Tesseract is not used for recognizing the musical notations.

**Comment by ultrasounder** [comment]
So what is OCR used in Audiveris for?
Thanks 🙏🏿 
Ananth

**Comment by stweil** [comment]
Sheet music (songs) also include ordinary text. Tesseract OCR is used for that song text (or any other text like headers, page counts, name of composer, ...).

**Comment by ultrasounder** [comment]
Got it! Many Thanks. So is OpenCV my best option? What about other deep learning frameworks such as TensorFlow?
Cheers
Ananth
