### ISSUE TITLE
32bit Windows installation problem with msvcrt.dll entry point

### ISSUE THREAD

**Issue by CanadianHusky** [tesseract-ocr/tesseract#2131]
Hello
What additional runtime library is required for the 32 bit version ?

![image](https://user-images.githubusercontent.com/35332003/50286107-65f5cf80-046f-11e9-8031-0e5798506a72.png)

I am using 32bit windows installer from 
https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v4.0.0.20181030.exe

I have uninstalled and reinstalled vc_redist_86.exe for VS 2008, 2010, 2012, 2013, 2015 each with the latest available update hoping to find the right runtime by trial and error but the exe still cannot be launched.

I must be doing something wrong.
thanks

**Comment by zdenop** [comment]
We do not provide binary installers/packages, so this is not tesseract project issue.
You need to contact your package manager directly.
@stweil : Is there any support page?

**Comment by stweil** [comment]
The support page is [UB-Mannheim/tesseract/issues](https://github.com/UB-Mannheim/tesseract/issues). `_splitpath_s` should be found without any extra installation.
