### ISSUE TITLE
Configure error in Amazon Linux 

### ISSUE THREAD

**Issue by vfjhanashima** [tesseract-ocr/tesseract#2141]
* Tesseract Version: master 4.0.0 (2019-01-03)
* Commit Number: 3377ed2
* Platform: Amazon Linux AMI release 2018.03

During configure, error occurs.

>checking for LEPTONICA... no
>configure: error: Leptonica 1.74 or higher is required. Try to install libleptonica-dev package.

But, I have installed leptonica-1.77.0.

Issude command
>export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
>export LIBLEPT_HEADERSDIR=/usr/local/include/leptonica
>export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
>export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
 ./configure  --with-extra-libraries=/usr/local/lib

Why ??

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by vfjhanashima** [comment]
Sorry,
I got it
