### ISSUE TITLE
Degrees and Meridians not OCR..ed

### ISSUE THREAD

**Issue by rajeshkalpathi** [tesseract-ocr/tesseract#2149]
### Environment

* **Tesseract Version**: 4.0.0 Alpha TesseractEngine c# Wrapper
* **Commit Number**: NA
* **Platform**: Windows 10, 64 Bit

### Current Behavior:

I am trying to process a pdf with text in Degrees and Meridians as given in the uploaded image. In some cases, the degree symbol gets ocr..ed correctly, but the Single Quote also gets ocr..ed as degree symbol. 

eg: 84°16’00” is successfully extracted but 81°33°45” is the result which should be 81°33'45”

What could be going wrong?

I tried the same image that i pass to tesseract,  to a onlineocr.net to compare results, and the online ocr is doing getting me the right output.

![sample 2](https://user-images.githubusercontent.com/42106734/50773728-98009180-12b7-11e9-983a-4a38d5b43f45.png)

![sample 1](https://user-images.githubusercontent.com/42106734/50773479-f4af7c80-12b6-11e9-824e-bda84e22613c.png)

### Expected Behavior:

Degrees, feet and inches should be extracted correctly.

**Comment by rajeshkalpathi** [comment]
> That's a good example where the "best" LSTM recognizer currently fails:
> 
> ```
> $ tesseract /tmp/test.png - -l tessdata/eng --psm 7 --oem 0
> 81°33’4S”
> 
> $ tesseract /tmp/test.png - -l tessdata/eng --psm 7 --oem 1
> 8193345”
> 
> $ tesseract /tmp/test.png - -l tessdata/deu --psm 7 --oem 0
> 81°33’45”
> 
> $ tesseract /tmp/test.png - -l tessdata/deu --psm 7 --oem 1
> 81°337’45”
> ```
> The legacy OCR engine nearly gets it right. It's a known issue that LSTM is not so good in reading short lines – maybe because it was trained with longer lines only?

Thanks for your response. I am trying to see if I can reprocess that portion of the image using the legacy mode oem -0 with tesseract 4, if i find symbols in text. But in the mean time if there is a way we can make LTSM handle symbols it would be great. 

It is not just with shorter lines, the above image is part of a longer line. I also tried the VietOCR tool. If I pass the entire page or just the above 2 images, it produces the same wrong result.

**Comment by amitdo** [comment]
If you'll train (fine tune) Tesseract with enough textlines that contain a similar pattern it should latter recognize your test image more accurately.

Training Tesseract is not an easy task.
