### ISSUE TITLE
ffmpeg builders script on https://github.com/tesseract-ocr/tesseract.git error compiling

### ISSUE THREAD

**Issue by crazybytes** [tesseract-ocr/tesseract#2154]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by crazybytes** [comment]
Part of last output when compiling https://github.com/tesseract-ocr/tesseract.git tesseract_git a2e72f258a3bd6811cae226a01802d
------>
checking whether make supports nested variables... yes
checking dependency style of x86_64-w64-mingw32-g++... gcc3
./configure: line 3971: AX_SPLIT_VERSION: command not found
./configure: line 3972: s/^[^0-9]*//: No such file or directory
./configure: line 3974: s/^\([0-9][0-9]*\).*/\1/: No such file or directory
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-w64-mingw32
./configure: line 4220: syntax error near unexpected token `-mavx,'
./configure: line 4220: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'
root@WAKKAWAKKA:/opt#

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+is%3Aclosed+AX_CHECK_COMPILE_FLAG

**Comment by rboy1** [comment]
This link comes back to this ticket. What's the solution here?
