### ISSUE TITLE
After downloading libtiff and compiling leptonica 1.74 still I am getting Error in findTiffCompression: function not present

### ISSUE THREAD

**Issue by munishjuneja** [tesseract-ocr/tesseract#2157]
Tesseract Version - 3.05.01
Leptonica version - 1.74 
Platform - Rhel 7.4 

Current Behavior: - When i try to run tesseract it' s giving me error Error in findTiffCompression: function not present

### Expected Behavior: It should give me extracted value . 

Attached the script which I am using. Please suggest.

[install-tesseract_RHEL_CENTOS.txt](https://github.com/tesseract-ocr/tesseract/files/2755089/install-tesseract_RHEL_CENTOS.txt)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
