### ISSUE TITLE
No error on configure, make and install; but doesn't work out of the box

### ISSUE THREAD

**Issue by teo1978** [tesseract-ocr/tesseract#216]
```
./autogen.sh
./configure
make
make install
```
all ran without errors (unless error messages are somewhere in the flood of output).

But when I run:
```
$ tesseract -v
tesseract: error while loading shared libraries: libtesseract.so.3: cannot open shared object file: No such file or directory
```

Either something is broken, or some informative error message is missing in the configure and/or make and/or install phase.

**Comment by zdenop** [comment]
Try to follow wiki [1] 
Note: This wiki expects you to be familiar with compiling software on your operation system.[1]
https://github.com/tesseract-ocr/tesseract/wiki/Compiling
