### ISSUE TITLE
Incorrect line segmentation with differing font sizes

### ISSUE THREAD

**Issue by tailsu** [tesseract-ocr/tesseract#2166]
### Environment

* **Tesseract Version**:
```
tesseract 4.0.0
 leptonica-1.76.0
  libjpeg 9c : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found SSE
```
* **Platform**: `Darwin Kernel Version 18.2.0`
* Installed languages: eng, deu, lat and osd from `tessdata_fast` repo. The language used is eng.

### Current Behavior:

Tesseract doesn't seem to like words of differing font size on the same line. When two words that have different font sizes are juxtaposed on the same line, the recognition quality of the smaller text drops drastically.

Separate lines - good:
![rechnung-60141-1](https://user-images.githubusercontent.com/730130/51391083-6b5b3e00-1b31-11e9-89ea-ca26709a1dc8.jpg)
```
~/Downloads $ tesseract rechnung-60141-1.jpg stdout
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 527
60141

RECHNUNG
```
In the same vertical range - worse:
![rechnung-60141-2](https://user-images.githubusercontent.com/730130/51391084-6b5b3e00-1b31-11e9-8eb9-b113edef24d6.jpg)
```
~/Downloads $ tesseract rechnung-60141-2.jpg stdout
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 527
RECHNUNG) ©1421
```
In the same vertical range again - actually 100% accurate:
![rechnung-60141-3](https://user-images.githubusercontent.com/730130/51391085-6b5b3e00-1b31-11e9-8a31-4f187fd408a1.jpg)
```
~/Downloads $ tesseract rechnung-60141-3.jpg stdout
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 527
RECHNUNG 60141
```
Both words are on the same baseline - worst behavior:
![rechnung-60141-4](https://user-images.githubusercontent.com/730130/51391086-6bf3d480-1b31-11e9-80e6-1f74515898a6.jpg)
```
~/Downloads $ tesseract rechnung-60141-4.jpg stdout
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 527
RECHNUNG coos
```

The incorrect behavior itself in the last example is very unstable. If I nudge the number in the last image left or right, I get radically different results, half the time correct:
Number moved 1px to the right (suddenly the result is correct!):
![rechnung-60141-4p1](https://user-images.githubusercontent.com/730130/51392220-a874ff80-1b34-11e9-9646-bbc33bce7dec.jpg)
```
RECHNUNG 60141
```
2px leftward (correct result):
![rechnung-60141-4m2](https://user-images.githubusercontent.com/730130/51392262-c17db080-1b34-11e9-8b75-082c24cab7f3.jpg)
```
RECHNUNG 60141
```
4px leftward (correct result):
![rechnung-60141-4m4](https://user-images.githubusercontent.com/730130/51392296-dbb78e80-1b34-11e9-8ced-4dfa6c65deb2.jpg)
```
RECHNUNG 60141
```
5px leftward (incorrect):
![rechnung-60141-4m5](https://user-images.githubusercontent.com/730130/51392345-04d81f00-1b35-11e9-8c7f-9508b0e9e819.jpg)
```
RECHNUNG - coisa
```
6px leftward (incorrect):
![rechnung-60141-4m6](https://user-images.githubusercontent.com/730130/51392390-2a652880-1b35-11e9-9549-406fd751bb75.jpg)
```
RECHNUNG - coos
```
8px leftward (correct result):
![rechnung-60141-4m8](https://user-images.githubusercontent.com/730130/51392488-7617d200-1b35-11e9-8a5e-2252c3d32de6.jpg)
```
RECHNUNG 60141
```
10px leftward (incorrect):
![rechnung-60141-4m10](https://user-images.githubusercontent.com/730130/51392491-7adc8600-1b35-11e9-9d9f-de77a288e9cd.jpg)
```
RECHNUNG - oo1ai
```

### Expected Behavior:
Essentially invisible changes like the above should not haphazardly impact the OCR accuracy.

**Comment by tailsu** [comment]
The issue title is likely very misleading, please change it as you see fit :)

**Comment by ibaxx** [comment]
Same Problems seen on some Documents

**Comment by abhi98khandelwal** [comment]
Any solution to overcome this issue ?

**Comment by zdenop** [comment]
Default psm is good for page image not short text. Several years there is available [information](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality) how to get better results:

```
tesseract 51392491-7adc8600-1b35-11e9-9d9f-de77a288e9cd.jpg - --psm 12
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 527
Too few characters. Skipping this page
OSD: Weak margin (0.00) for 10 blob text block, but using orientation anyway: 0
RECHNUNG

60141
```

**Comment by zdenop** [comment]
PS: I used tessdata_best
