### ISSUE TITLE
Incorrect 4.0 Windows compilation instructions on wiki.

### ISSUE THREAD

**Issue by tdhintz** [tesseract-ocr/tesseract#2177]
I could not get the instructions on the wiki to work anymore.  I successfully used these instead: [Build instructions](https://github.com/charlesw/tesseract/wiki/Compiling-Tesseract-and-Leptonica)

**Comment by zdenop** [comment]
This is no correct issues report.
If you need support use tesseract user forum.

**Comment by tdhintz** [comment]
I don’t need help.  Just letting you know.

**Comment by tdhintz** [comment]
I reran the Wiki instructions with no problem today.  Obviously a short between the chair and keyboard.
