### ISSUE TITLE
Tesseract give wrong result for this low quality image

### ISSUE THREAD

**Issue by dviettu134** [tesseract-ocr/tesseract#2182]
### Environment

* **Tesseract Version**:  tesseract v4.0.0.20181030
* **Platform**:  Windows 8.1 64 bit

### Current Behavior:
I run tesseract for the blow image and get the result "ais"
![test](https://user-images.githubusercontent.com/7239009/51588583-40009680-1f17-11e9-9cd2-0e53141cd1df.png)
![image](https://user-images.githubusercontent.com/7239009/51588677-6faf9e80-1f17-11e9-8765-4afc3abbc096.png)

### Expected Behavior:
The expected result should be:
"CTx2
40/5A"

### Suggested Fix:
Unknown

**Comment by PranavArora018** [comment]
You should try by changing the tesseract config and applying some pre processing.
This is what I got 
"Ctx
auy5n"

I know it is not perfect but still can be related.


my config: l-eng oem-3 psm-6
(oem-3 Default, based on what is available.
psm-6    Assume a single uniform block of text.)

Image processing: blurring, dilating, and normalizing

Tesseract Version:  tesseract v4.0.0.20181030
Platform:  Windows 10 64 bit

Cheers! :)

**Comment by dviettu134** [comment]
Hi [PranavArora018](/PranavArora018),
Thanks for your suggestions.

Actually I'm having to perform OCR on a larger image with text segments in this quality (sorry that I could not provide the whole image here due to confidential problem).
So the config psm=6 may not work here.

Do you think retrain the tesseract model may help in this case?

**Comment by rajeshkalpathi** [comment]
Did you try image pre-processing. Looking at the image, you might use one of the following EmguCV methods 
1. Dilation to sharpen the image. 
2. Threshold the image so that grey soft areas become white and black areas are well defined.

Try with different parameters. 

Please post the result if possible.

**Comment by zdenop** [comment]
I am afraid it is not realist expectation to get correct output from bad input.
Even I am not sure if I see there 5A or SA...
When I check how tesseract segmented your image to symbols I got 3 overlapping boxes:
![image](https://user-images.githubusercontent.com/574156/53498092-e9522380-3aa5-11e9-8b7b-0e1e567378f9.png)

So there is not enough space to correctly split input image to symbols. Anyway with psm 11 and tessdata_bestI got output: `40/5` rest of image is ignored...
