### ISSUE TITLE
PSM_SINGLE_WORD detects only letters with the LSTM engine

### ISSUE THREAD

**Issue by tailsu** [tesseract-ocr/tesseract#2183]
### Environment

* **Tesseract Version**: 
```
tesseract 4.0.0
 leptonica-1.76.0
  libjpeg 9c : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found SSE
```
* **Platform**: `Darwin Kernel Version 18.2.0`

### Current Behavior:
Running tesseract on the image below with the eng traineddata from tessdata_fast:
![textbox3](https://user-images.githubusercontent.com/730130/51603898-66b8d000-1f0b-11e9-8814-95efa62eba14.jpg)
```
$ tesseract Textbox3.jpg  stdout
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 447
20.11.17
```
works fine. But in `--psm 8` mode, that is single word mode, it outputs non-sense:
```
$ tesseract Textbox3.jpg  stdout --psm 8
Warning: Invalid resolution 0 dpi. Using 70 instead.
Pret eet
```

### Expected Behavior:
Using the legacy engine eng.traineddata  together with --psm 8 produces the correct result:
```
TESSDATA_PREFIX=/path/to/legacy/tessdata tesseract Textbox3.jpg  stdout --psm 8
Warning: Parameter not found: enable_new_segsearch
Warning: Parameter not found: save_raw_choices
Warning: Invalid resolution 0 dpi. Using 70 instead.
20.11.17
```

Using --psm 7, that is single-line mode, works equally well with both the legacy and LSTM engines, so this is the workaround that we'll use for now in this case.

### Suggested Fix:
If this change in behavior is a bug then the old behavior should be reinstated. If not, maybe document it? Or maybe clarify what a "single word" is. I have always assumed that it means a row of characters without whitespace.

**Comment by amitdo** [comment]
Try to crop the image so it will contain only the string with no top, bottom, left, right margins.

Does it change the result?

**Comment by tailsu** [comment]
Here is the cropped image:
![tesseract-date-cropped](https://user-images.githubusercontent.com/730130/51612047-f7e67180-1f20-11e9-9b65-8150a74d74af.jpg)
```
$ tesseract tesseract-date-cropped.jpg stdout --psm 8
Warning: Invalid resolution 0 dpi. Using 70 instead.
20.11.17
```
It works!

**Comment by amitdo** [comment]
I don't think there is a real issue here. Tesseract with 
`PSM_SINGLE_WORD` expects the input image to be a word to be without any padding.
