### ISSUE TITLE
Bengali OCR 

### ISSUE THREAD

**Issue by jayantanth** [tesseract-ocr/tesseract#219]
When we got a better OCR for Bengali language?

**Comment by amitdo** [comment]
See #212.

**Comment by zdenop** [comment]
1. Langdata/tessdata  issues should be reportoed at relevant part of project (https://github.com/tesseract-ocr/tessdata/issues or https://github.com/tesseract-ocr/langdata/issues)
2. Issue tracker should be use for reporting issues and not for asking questions.
