### ISSUE TITLE
imagedata_test fails some times with exit status: 139

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#2191]
```
../config/test-driver: line 107: 19818 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: imagedata_test
```

```
[----------] 2 tests from ImagedataTest (29338 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (29338 ms total)
[  PASSED  ] 2 tests.
FAIL imagedata_test (exit status: 139)
```

**Comment by stweil** [comment]
I noticed that, too, but cannot reproduce it.

**Comment by Shreeshrii** [comment]
Remove the tmp files (documentdata*.lstmf) and then run it again.  Sometimes that reproduces the error.

**Comment by stweil** [comment]
Could the error be caused by running more than one imagedata_test at the same time? This is a general problem, because each instance will create and use the same files, so this scenario won't work. To fix this, each test program would have to create a private directory for temporary files and remove that directory when it terminates.

**Comment by Shreeshrii** [comment]
I did not intentionally run more than one imagedata_test at the same time. However, I did try a couple of runs with --disable-openmp. 

Is it possible that googletest runs multiple instances of tests?

**Comment by stweil** [comment]
It won't parallelize tests by itself, but of course you can have multiple tests running at the same time by other means (background jobs, make -j, ...).

**Comment by Shreeshrii** [comment]
Possibly related issue
https://github.com/tesseract-ocr/tesseract/issues/1168

```
At iteration 10000/10000/10000, Mean rms=4.264%, delta=50.364%, char train=99.569%, word train=99.92%, skip ratio=0%,  New best char error = 99.569 wrote checkpoint.

Finished! Error rate = 99.569
num_docs > 0:Error:Assert failed:in file imagedata.cpp, line 651
```

**Comment by zdenop** [comment]
is this fixed?

**Comment by stweil** [comment]
No, it isn't. It got it yesterday:

    ../config/test-driver: line 107:  6764 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
    FAIL: imagedata_test

**Comment by stweil** [comment]
Here is a stack trace of the crash:

    (gdb) i s
    #0  0x00005636193e73f4 in tesseract::PointerVector<tesseract::ImageData>::truncate (size=0, this=0x56361aa749b8) at ../../src/ccutil/genericvector.h:477
    #1  tesseract::DocumentData::ReCachePages (this=0x56361aa749b0) at imagedata.cpp:531
    #2  0x00005636193e7769 in tesseract::ReCachePagesFunc (data=<optimized out>) at imagedata.cpp:379
    #3  0x00007fdce4298fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
    #4  0x00007fdce3e754cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

A second thread shows that the test is already finished. `ReCachePagesFunc` is indeed run in a separate thread, and obviously it depends on the order how main thread and that new thread are running whether the code crashes or not. So this looks like a general problem, and issue #1168 is related with a high probability.

**Comment by stweil** [comment]
This is still open and happens randomly with git master.

**Comment by stweil** [comment]
Pull request #3016 hopefully fixes this.
