### ISSUE TITLE
*** [all-recursive] Error 1 Tesseract 4.0.0

### ISSUE THREAD

**Issue by kyle-redyeti** [tesseract-ocr/tesseract#2195]
### Environment

* **Tesseract Version**:4.0.0 release
* **Commit Number**: 
* **Platform**: linux-arm64 Ubuntu 16.04

### Current Behavior:
When I attempt to do make it ends up stopping with the error:
make[2]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/wordrec'
make[2]: *** No rule to make target 'gradechop.h', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/wordrec'
Makefile:482: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0'
Makefile:390: recipe for target 'all' failed
make: *** [all] Error 2

### Expected Behavior:
I am not sure what is causing the error or if there is something that this install of Linux was pretty minimal not sure if it is missing something. It does seem to find the version of leptonica that I built successfully.
### Suggested Fix:
If you could give me any suggestions on what I am doing wrong I would greatly appreciate it. I loved using tesseract-ocr on another system and hope that I can get it to build for this system

Thanks!

Not sure if you need it but here is the whole output from it building...
nvidia@tegra-ubuntu:~/Documents/Git/javacpp-presets/tesseract$ sudo ./cppbuild.sh -platform linux-arm64 install
~/Documents/Git/javacpp-presets ~/Documents/Git/javacpp-presets/tesseract
Detected platform "linux-arm64"
Building for platform "linux-arm64"
Installing "tesseract"
~/Documents/Git/javacpp-presets/tesseract/cppbuild ~/Documents/Git/javacpp-presets
Decompressing archives...
Total bytes read: 10352640 (9.9MiB, 75MiB/s)
The next patch would create the file Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file aclocal.m4,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file config/config.guess,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file config/config.h.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file config/config.sub,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file config/depcomp,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file config/install-sh,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file config/ltmain.sh,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file config/missing,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file config/test-driver,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file configure,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file doc/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file java/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file java/com/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file java/com/google/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file java/com/google/scrollview/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file java/com/google/scrollview/events/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file java/com/google/scrollview/ui/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file langtests/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file m4/libtool.m4,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file m4/ltoptions.m4,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file m4/ltsugar.m4,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file m4/ltversion.m4,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file m4/lt~obsolete.m4,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
patching file src/api/Makefile.am
The next patch would create the file src/api/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
patching file src/api/baseapi.cpp
Hunk #1 succeeded at 206 (offset 6 lines).
The next patch would create the file src/arch/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/ccmain/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/ccstruct/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/ccutil/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/classify/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/cutil/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/dict/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/lstm/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/opencl/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/textord/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/training/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/viewer/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file src/wordrec/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file tessdata/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file tessdata/configs/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file tessdata/tessconfigs/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file unittest/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file unlvtests/Makefile.in,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether aarch64-linux-gnu-g++ accepts -g... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of aarch64-linux-gnu-g++... gcc3
checking for a sed that does not truncate output... /bin/sed
checking Major version... 4
checking Minor version... 0
checking Point version... 0-rc2
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking whether C++ compiler accepts -mavx... no
checking whether C++ compiler accepts -mavx2... no
checking whether C++ compiler accepts -msse4.1... no
checking --enable-graphics argument... 
checking --enable-legacy argument... 
checking --enable-embedded argument... 
checking for aarch64-linux-gnu-g++ option to support OpenMP... -fopenmp
checking how to run the C++ preprocessor... aarch64-linux-gnu-g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking tiffio.h usability... yes
checking tiffio.h presence... yes
checking for tiffio.h... yes
checking --enable-opencl argument... 
checking --enable-visibility argument... 
checking whether to use tessdata-prefix... yes
checking whether to enable debugging... 
checking whether byte ordering is bigendian... no
checking how to print strings... printf
checking for aarch64-linux-gnu-gcc... aarch64-linux-gnu-gcc
checking whether we are using the GNU C compiler... yes
checking whether aarch64-linux-gnu-gcc accepts -g... yes
checking for aarch64-linux-gnu-gcc option to accept ISO C89... none needed
checking dependency style of aarch64-linux-gnu-gcc... gcc3
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by aarch64-linux-gnu-gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert aarch64-unknown-linux-gnu file names to aarch64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for aarch64-linux-gnu-objdump... aarch64-linux-gnu-objdump
checking how to recognize dependent libraries... pass_all
checking for aarch64-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for aarch64-linux-gnu-ar... aarch64-linux-gnu-ar
checking for archiver @FILE support... @
checking for aarch64-linux-gnu-strip... aarch64-linux-gnu-strip
checking for aarch64-linux-gnu-ranlib... aarch64-linux-gnu-ranlib
checking command to parse /usr/bin/nm -B output from aarch64-linux-gnu-gcc object... ok
checking for sysroot... no
checking for aarch64-linux-gnu-mt... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if aarch64-linux-gnu-gcc supports -fno-rtti -fno-exceptions... no
checking for aarch64-linux-gnu-gcc option to produce PIC... -fPIC -DPIC
checking if aarch64-linux-gnu-gcc PIC flag -fPIC -DPIC works... yes
checking if aarch64-linux-gnu-gcc static flag -static works... yes
checking if aarch64-linux-gnu-gcc supports -c -o file.o... yes
checking if aarch64-linux-gnu-gcc supports -c -o file.o... (cached) yes
checking whether the aarch64-linux-gnu-gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... aarch64-linux-gnu-g++ -E
checking for ld used by aarch64-linux-gnu-g++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the aarch64-linux-gnu-g++ linker (/usr/bin/ld) supports shared libraries... yes
checking for aarch64-linux-gnu-g++ option to produce PIC... -fPIC -DPIC
checking if aarch64-linux-gnu-g++ PIC flag -fPIC -DPIC works... yes
checking if aarch64-linux-gnu-g++ static flag -static works... yes
checking if aarch64-linux-gnu-g++ supports -c -o file.o... yes
checking if aarch64-linux-gnu-g++ supports -c -o file.o... (cached) yes
checking whether the aarch64-linux-gnu-g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking if compiling with clang... no
checking whether compiler supports C++11... yes
checking for snprintf... yes
checking for library containing sem_init... -lpthread
checking for ANSI C header files... (cached) yes
checking whether time.h and sys/time.h may both be included... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking sys/ipc.h usability... yes
checking sys/ipc.h presence... yes
checking for sys/ipc.h... yes
checking sys/shm.h usability... yes
checking sys/shm.h presence... yes
checking for sys/shm.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for asciidoc... true
checking for wchar_t... yes
checking for long long int... yes
checking for off_t... yes
checking for mbstate_t... yes
checking for aarch64-linux-gnu-pkg-config... /usr/bin/aarch64-linux-gnu-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LEPTONICA... yes
checking for ICU_UC... yes
checking for ICU_I18N... yes
checking for pango... yes
checking for cairo... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tesseract.pc
config.status: creating langtests/Makefile
config.status: creating src/api/Makefile
config.status: creating src/api/tess_version.h
config.status: creating src/arch/Makefile
config.status: creating src/ccmain/Makefile
config.status: creating src/opencl/Makefile
config.status: creating src/ccstruct/Makefile
config.status: creating src/ccutil/Makefile
config.status: creating src/classify/Makefile
config.status: creating src/cutil/Makefile
config.status: creating src/dict/Makefile
config.status: creating src/lstm/Makefile
config.status: creating src/textord/Makefile
config.status: creating src/viewer/Makefile
config.status: creating src/wordrec/Makefile
config.status: creating tessdata/Makefile
config.status: creating tessdata/configs/Makefile
config.status: creating tessdata/tessconfigs/Makefile
config.status: creating unlvtests/Makefile
config.status: creating unittest/Makefile
config.status: creating java/Makefile
config.status: creating java/com/Makefile
config.status: creating java/com/google/Makefile
config.status: creating java/com/google/scrollview/Makefile
config.status: creating java/com/google/scrollview/events/Makefile
config.status: creating java/com/google/scrollview/ui/Makefile
config.status: creating doc/Makefile
config.status: creating src/training/Makefile
config.status: creating config_auto.h
config.status: config_auto.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

Configuration is done.
You can now build and install tesseract by running:

$ make
$ sudo make install
$ sudo ldconfig

This will also build the documentation.

Training tools can be built and installed with:

$ make training
$ sudo make training-install

 cd . && : --foreign
make  all-recursive
make[1]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0'
 cd . && : --foreign
Making all in src/arch
make[2]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/arch'
make[3]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/arch'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/arch'
make[2]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/arch'
Making all in src/ccutil
make[2]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/ccutil'
make[3]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/ccutil'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/ccutil'
make[2]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/ccutil'
Making all in src/viewer
make[2]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/viewer'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/viewer'
Making all in src/cutil
make[2]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/cutil'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/cutil'
Making all in src/opencl
make[2]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/opencl'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/opencl'
Making all in src/ccstruct
make[2]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/ccstruct'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/ccstruct'
Making all in src/dict
make[2]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/dict'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/dict'
Making all in src/classify
make[2]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/classify'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/classify'
Making all in src/wordrec
make[2]: Entering directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/wordrec'
make[2]: *** No rule to make target 'gradechop.h', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0/src/wordrec'
Makefile:482: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/nvidia/Documents/Git/javacpp-presets/tesseract/cppbuild/linux-arm64/tesseract-4.0.0'
Makefile:390: recipe for target 'all' failed
make: *** [all] Error 2
~/Documents/Git/javacpp-presets/tesseract

**Comment by stweil** [comment]
`gradechop.h` no longer exists in latest Tesseract. Re-run `./autogen.sh` to update your build rules.

**Comment by zdenop** [comment]
...and we do not provide support for 3rd party project (`sudo ./cppbuild.sh -platform linux-arm64 install`)...
