### ISSUE TITLE
-Wtautological-undefined-compare warning in split.cpp

### ISSUE THREAD

**Issue by rmtheis** [tesseract-ocr/tesseract#22]
I get a `-Wtautological-undefined-compare` warning when building for Android using clang and tess-two:

    jni/com_googlecode_tesseract_android/src/ccstruct/split.cpp:223:7: warning: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to true [-Wtautological-undefined-compare]
      if (this != NULL) {
          ^~~~    ~~~~

**Comment by tfmorris** [comment]
Both #21 and #22 are caused by something buried inside the tprintf() macro expansion.

**Comment by rmtheis** [comment]
This was fixed in 4fdf272ffa2897648d6899ea014cf79d76e509aa.
