### ISSUE TITLE
Significant slow down of Windows Tesseract built with cppan

### ISSUE THREAD

**Issue by OpaitSoftware** [tesseract-ocr/tesseract#2205]
I have noticed that Tesseract processing takes longer with new changes since the release. 

Below, I am comparing two similar builds (12-14-2018 and 1-27-2019). The older version performance is comparable to the released code but the new version is slow. 

The reason for not using the released version was to reduce the time gap and hence the number of changes that caused the slowdown. 

Older Version (12-24-18):
-------------------------
D:\Dev\Attic\tesseract>git show
commit b2ab772016f2caf22b65e87112e3ba3738e9e68a (HEAD -> feature/321-Tesseract-4, origin/feature/321-Tesseract-4)
Merge: 660766f6 231992a9
Author: Charles Weld <charles.weld@gmail.com>
Date:   Thu Jul 5 16:25:55 2018 +1000

    Merge pull request #414 from nguyenq/feature/321-Tesseract-4

    Feature/321 tesseract 4
	
Newer Version (1-27-19):	
------------------------
D:\Dev\tesseract>git show
commit 44038cb5e86a2a89d937c3bc86fa86ff00e58275 (HEAD -> master, origin/master, origin/HEAD)
Merge: 8f87ebb4 4d9bc11f
Author: zdenop <zdenop@gmail.com>
Date:   Sun Jan 27 08:24:41 2019 +0100

    Merge pull request #2200 from Shreeshrii/master

    fix and enable more unittests
	
	
Test run using a 7-page TIFF file:
----------------------------------
D:\TessTest>Run

D:\TessTest>cd Tess_12_14

D:\TessTest\Tess_12_14>echo  9:53:06.35
 9:53:06.35

D:\TessTest\Tess_12_14>tesseract ..\Page7.tif .
Tesseract Open Source OCR Engine v4.0.0 with Leptonica
Page 1
Page 2
Page 3
Page 4
Page 5
Page 6
Page 7

D:\TessTest\Tess_12_14>echo  9:54:46.30
 9:54:46.30

D:\TessTest\Tess_12_14>cd ..\Tess_1_27

D:\TessTest\Tess_1_27>tesseract ..\Page7.tif .
Tesseract Open Source OCR Engine v4.0.0 with Leptonica
Page 1
Page 2
Page 3
Page 4
Page 5
Page 6
Page 7

D:\TessTest\Tess_1_27>echo  9:57:32.28
 9:57:32.28

Summary of the test run:
------------------------
12-24-18 version time: ~100 seconds
1-27-19 version time:  ~162 seconds

Source files that changed:
--------------------------
.\api\altorenderer.cpp
.\api\baseapi.cpp
.\api\capi.cpp
.\api\makefile.am
.\api\renderer.cpp
.\api\renderer.h
.\api\tesseractmain.cpp

.\arch\dotproductavx.cpp
.\arch\dotproductsse.cpp
.\arch\dotproductsse.h
.\arch\intsimdmatrix.cpp
.\arch\intsimdmatrix.h
.\arch\intsimdmatrixavx2.cpp
.\arch\intsimdmatrixsse.cpp
.\arch\makefile.am
.\arch\simddetect.cpp

.\ccmain\control.cpp
.\ccmain\tesseractclass.cpp
.\ccmain\tesseractclass.h
.\ccmain\thresholder.cpp

.\ccstruct\otsuthr.cpp

.\classify\cluster.cpp
.\classify\protos.cpp

.\cutil\oldlist.cpp
.\cutil\oldlist.h

.\lstm\networkio.cpp
.\lstm\networkio.h
.\lstm\tfnetwork.cpp
.\lstm\tfnetwork.h
.\lstm\weightmatrix.cpp
.\lstm\weightmatrix.h

.\opencl\makefile.am
.\opencl\oclkernels.h
.\opencl\openclwrapper.cpp
.\opencl\openclwrapper.h

.\textord\linefind.cpp

.\training\commontraining.h
.\training\pango_font_info.cpp
.\training\tesstrain.sh
.\training\tesstrain_utils.sh
.\training\text2image.cpp
.\training\validate_grapheme.cpp
.\training\validate_indic.cpp
.\training\validate_javanese.cpp
.\training\validate_khmer.cpp
.\training\validate_myanmar.cpp
.\training\validator.h

**Comment by stweil** [comment]
So you are obviously using a Windows binary. How did you build it / where did you get it from?

**Comment by OpaitSoftware** [comment]
@stweil 
We build the DLL from source using the following steps:
1. Clone the source using Git
2. Edit cppan.yml to remove leptonica dependencies (we build leptonica separately)
3. Run cppan
4. Run cmake to generate VS project files
5. Edit project files to fix include and lib directories to point to our version of leptonica.
6. Build MinSizeRel configuration which generates tesseract40.dll and tesseract.exe

**Comment by stweil** [comment]
cppan recently disabled OpenMP, see commit b30e92fb8a968287ff387ef9501b41e187491b08. This means Tesseract now needs less CPU time, but the absolute time for a single page increases because it no longer uses up to 4 CPU cores. If you run 4 images parallel, the new version will be faster than the old one.

**Comment by OpaitSoftware** [comment]
Both of these version were built with OpenMP disabled. Prior to cppan change, we were disabling OpenMP in VS2017 as it was affecting our application that processes multiple pages (up to number of cores in computer) simultaneously. We see the same slowdown there with similar times. Out application is called TesseractStudio.Net and is freely available.

**Comment by stweil** [comment]
Then please try to narrow down the exact commit which caused the slow down.
You should also report which traineddata file you are using in both test runs.

**Comment by OpaitSoftware** [comment]
We are using fast English training data in both cases. I will try to narrow down the gap between the two versions to, hopefully, identify changes that might have caused this. I am hoping that regression testing includes a comparative test of performance to catch any degradation early. It gets harder to diagnose as changes pile up.

**Comment by zdenop** [comment]
@stweil: I already recognized, that cmake/cppan windows build has no support for SSE and AVX:
```
tesseract.exe -v
tesseract 4.0.0
 leptonica-1.76.0 (Dec 14 2018, 15:34:47) [MSC v.1916 LIB Release x64]
  libgif 5.1.4 : libjpeg 9b : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
```

**Comment by zdenop** [comment]
sure this could be problem. Can you please try revert (localy) commit
https://github.com/tesseract-ocr/tesseract/commit/b9a34d741d59412b30182fe703c06eb33d06a85b?
I gues this could be source of problem...

**Comment by stweil** [comment]
@OpaitSoftware, @zdenop, I'm afraid that a small typo in my commit 5f96ac1a71f27994c7720ecd526310cd8d4dddcb caused this regression for CMake based builds. It's fixed now in Git master, see commit 394839cdd7c9611f08407092e3bb0b02f2331249. Sorry for that.

@OpaitSoftware, could you please confirm that the latest code shows the expected performance again?

**Comment by OpaitSoftware** [comment]
@stweil, @zdenop, The latest commit solved the problem. AVX and SSE are detected, Open MP is off by default, as expected, and the processing time is the same as the release code (with Open MP disabled). Thank you!

**Comment by stweil** [comment]
That's good news. I have more good news for you: You can get even better performance by fixing the AVX2 support. Many modern Intel CPUs have AVX2, but Tesseract's MSC code does not include the necessary lines which detect and enable AVX2, so those builds always use SSE code for traineddata_fast.

**Comment by stweil** [comment]
https://github.com/stweil/tesseract/commit/a69cb62442d62c1bb1a03c7904a97b485c8d34cf is an untested implementation for AVX2 detection with MSC. Maybe you want to give it a try and report whether it builds and improves the performance in you test.

**Comment by zdenop** [comment]
@stweil : maybe we should include https://github.com/VcDevel/Vc/blob/master/cmake/OptimizeForArchitecture.cmake to our configuration

**Comment by stweil** [comment]
Did you test it, and does it improve the performance?

**Comment by zdenop** [comment]
Not yet (lack of time), but is should detect availability of sse, avx support based on cpu in cmake...

**Comment by stweil** [comment]
It's not a replacement for my commit.

**Comment by OpaitSoftware** [comment]
I will take a look at AVX2, anything to improve performance is great. The test file I use is a dense 2 column article with 7 pages and it takes about 100 seconds to process sequentially and 35 seconds in parallel. I also have a 2100 page version (7 pages x 300 in one PDF), which I run periodically to make sure memory is properly managed. That one takes a couple of hours to run.

On a related note, is it possible to generate relative rather than absolute paths in VS project files? Absolute paths make the solution non-portable. I am not very familiar with cmake scripts but can research if needed.
