### ISSUE TITLE
Same image giving different results on local and on docker

### ISSUE THREAD

**Issue by santhoshav15** [tesseract-ocr/tesseract#2222]
Same Image
![tmpy6s8p6m1](https://user-images.githubusercontent.com/45348951/52256576-3d516880-293d-11e9-8755-19bdd455a62a.jpg)

Local Machine, Ubuntu 16.04, python 3.6.7 
Tesseract version 4.0.0-115-ge3a3

Command:
tesseract tmpy6s8p6m1.jpg stdout --oem 2 --psm 6

Result: 
19AAXCS8821M1Z8

Docker Image, Ubuntu 16.04, python 3.6.7 
Tesseract version 4.0.0-274-gc999

Command:
tesseract tmpy6s8p6m1.jpg stdout --oem 2 --psm 6

Result: 
roaaxcossoimize

Even posted the issue on google groups
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/tesseract-ocr/shniQn52lPs

Trying a solution suggested but not sure it will work. Any help would be great.

**Comment by Shreeshrii** [comment]
Are you using the same traineddata file in both cases?

Check the file location and size.

**Comment by Shreeshrii** [comment]
Also, compare same version of tesseract. I am getting the following

ubuntu@tesseract-ocr:~/TEST$  tesseract 2222.jpg stdout --psm 6 --tessdata-dir ../tessdata_fast
Warning: Invalid resolution 0 dpi. Using 70 instead.
1 GAAXCS8821M1Z8
ubuntu@tesseract-ocr:~/TEST$  tesseract 2222.jpg stdout --psm 6 --tessdata-dir ../tessdata_best
Warning: Invalid resolution 0 dpi. Using 70 instead.
19AAXCSB8821M1Z8
ubuntu@tesseract-ocr:~/TEST$  tesseract 2222.jpg stdout --psm 6 --tessdata-dir ../tessdata
Warning: Invalid resolution 0 dpi. Using 70 instead.
19AAXCSB8821M1Z8
ubuntu@tesseract-ocr:~/TEST$ tesseract -v
tesseract 4.0.0-333-gb3bd
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0
ubuntu@tesseract-ocr:~/TEST$

**Comment by zdenop** [comment]
1. You are not using the same tesseract version
2. As Shree pointed it is not clear it you use the same traineddata (and from witch repository)
3. We do not support docker (no capacity). Based on your test result from local machine is correct, but result from docker is wrong, so in docker must be something that has influenced results. Feel free continue in tesseract user forum, but asking on some docker forum could be more useful.

**Comment by adekability** [comment]
I am stucked with such issue. My tesseract version is the same, repository from which I took traineddata is the same, the size is the same, but the results are different. When I use kaz.traineddata locally - it works fine, but in docker it seems like it uses eng.traineddata. Anyone knows how to solve this problem?

**Comment by wollmers** [comment]
@adekability Did you take checksums of the involved components to be sure they are the same?
