### ISSUE TITLE
Compilling Tesseract-ocr using git or other compilation

### ISSUE THREAD

**Issue by alucard079** [tesseract-ocr/tesseract#2225]
After the command "make"

this error has been generated.

IOError: [Errno 32] Broken pipe
Makefile:616: recipe for target 'combine_lang_model.1' failed
make[2]: *** [combine_lang_model.1] Error 127
make[2]: Leaving directory '/home/nigel/tesseract/doc'
Makefile:495: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/nigel/tesseract'
Makefile:404: recipe for target 'all' failed
make: *** [all] Error 2

What should I do? I followed the instructions very carefully.

**Comment by stweil** [comment]
That might be caused by missing required packages. See https://github.com/tesseract-ocr/tesseract/pull/2212#issuecomment-459834395 for the Debian packages which are needed to build `combine_lang_model.1`. Could you please update the Wiki if that works for you?

**Comment by zdenop** [comment]
@alucard079:  did you check the latest code?

**Comment by zdenop** [comment]
Closed because of missing input from reporter.
