### ISSUE TITLE
POSIX make compatibility

### ISSUE THREAD

**Issue by rrrapha** [tesseract-ocr/tesseract#2226]
The rules in doc/Makefile.am are not compatible with BSD/POSIX make:

```
make: don't know how to make combine_lang_model.1 (prerequisite of: all-am)
Stop in /tmp/tesseract/doc
```

### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**: 
* **Platform**: OpenBSD

**Comment by stweil** [comment]
OpenBSD allows using `gmake`. Wouldn't that be the simplest solution for this issue?

**Comment by rrrapha** [comment]
Sure, it would just be nice to not have this build dependency. 
(the whole program builds fine without gmake, only `doc/` needs gmake)
