### ISSUE TITLE
Wrong bounding box coordinates reported (regression from 4.0.0)

### ISSUE THREAD

**Issue by lorenzob** [tesseract-ocr/tesseract#2240]
* **Tesseract Version**: 

tesseract 4.0.0-279-gec8f
 leptonica-1.77.0
  libjpeg 6b (libjpeg-turbo 1.2.90) : libpng 1.5.13 : libtiff 4.0.3 : zlib 1.2.7
 Found AVX2
 Found AVX
 Found SSE

* **Commit Number**: 

b67ff533cd9f06437b28d83fe01fafb266f76cab

* **Platform**: 

Linux ip-xxx-xx-xx-xxx.eu-west-1.compute.internal 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:

Space len is reported as -470

Space len is computed as the distance between the right side of previous box and the left side of the one containing the symbol.

### Expected Behavior:

Should be about 17  (as in version 4.0.0 and as from pixel inspection)

Test img:

![napoleone_ocr_13](https://user-images.githubusercontent.com/85481/52795095-5bbc1000-3071-11e9-897d-1ce8aba2a110.png)

This is a comparison of the app log:

[tess-diff.txt](https://github.com/tesseract-ocr/tesseract/files/2865526/tess-diff.txt)

"DEBUG:root:# Spazio troppo breve -470 lo ignoro"

This means "space too short, ignoring it" and the computed distance is -470.

Many other "space len" are reported as negative values.

I think is a new one, not the same as in https://github.com/tesseract-ocr/tesseract/issues/2024 and the two referenced issues.

**Comment by stweil** [comment]
Could you please try to find out when this regression occurred first, maybe by using `git bisect`? If 4.0.0 was fine, are there other later revisions which still are fine?

**Comment by amitdo** [comment]
Does this also occur with commit ce88adbf326a?

**Comment by lorenzob** [comment]
Same problem with ce88adbf326a40b08de32e35eafffd29ef43290e.

Later I'll try git bisect to find the commit.

**Comment by amitdo** [comment]
Please try commit 724957167e4f

**Comment by lorenzob** [comment]
Commit 724957167e4f7c7d4d5a88f52ca3a21e1e3e031c works as 4.0.0  (tesseract 4.0.0-29-g7249)

Here is a comparison of the bounding boxes.

4.0.0:

![4 0 0](https://user-images.githubusercontent.com/85481/52879144-bf703700-315e-11e9-83f1-6f0aa9faf107.png)

Others:

![latest](https://user-images.githubusercontent.com/85481/52879171-cdbe5300-315e-11e9-9822-6e6642ca2b3d.png)

The boxes visually look fine, even better than the old version. Please let me check my code before spending time on this, maybe the problem is on my side.

**Comment by zdenop** [comment]
Did you have change to check your code?

**Comment by lorenzob** [comment]
Not yet. If you want we can close this and I will reopen it as soon as I have more details.

**Comment by zdenop** [comment]
With Tesseract-ocr version 4.1.0-rc1-21-g8e83 I got this result:
![image](https://user-images.githubusercontent.com/574156/53471673-bee07600-3a65-11e9-832e-191a25f10413.png)
so I expect problem should be in your code.
