### ISSUE TITLE
Use of Tessract 4 with ROS (Catkin_make error)

### ISSUE THREAD

**Issue by RatheeshRK** [tesseract-ocr/tesseract#2243]
### Environment

* **Tesseract Version**:  4
* **Commit Number**:  
* **Platform**:  Ubuntu 16.04 with ROS kinetic

### Current Behavior: 
The Cmake list was added with the below statements
find_package(Tesseract REQUIRED)
include_directories(${Tesseract_INCLUDE_DIRS})
target_link_libraries(image_converter ${Tesseract_LIBRARIES})

But cannot compile with catkin_make.

**The following error occours**
CMake Error at image_converter/CMakeLists.txt:19 (find_package):
  By not providing "FindTesseract.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Tesseract", but CMake did not find one.

  Could not find a package configuration file provided by "Tesseract" with
  any of the following names:

    TesseractConfig.cmake
    tesseract-config.cmake

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.

**Comment by Jdebree98** [comment]
@RatheeshRK  You need to set your CMAKE_PREFIX_PATH. This path needs to be the path to the given .cmake files that the error describes. For the basic OpenCV CMAKE_PREFIX_PATH, the path usually is something like: /home/[user]/installation/OpenCV-4.1.1/lib/cmake/opencv4/ 

If you can find the .cmake files for Tesseract, simply add them by typing this in your cmakelist.txt:

SET(CMAKE_PREFIX_PATH "/home/[user]/path/to/tesseract/cmake")
