### ISSUE TITLE
Makefile:495 error

### ISSUE THREAD

**Issue by ajinkya933** [tesseract-ocr/tesseract#2245]
### Environment

* **Tesseract Version**: 4.0.0-324-gb67f
* **Commit Number**: 
* **Platform**: Ubuntu16.04 64-bit -->

### Current Behavior:
I want to retrain tesseract and I am referring to Googles  documentation at https://github.com/tesseract-ocr/tesseract/blob/master/INSTALL.  Here are the steps that I am following

1) git pull https://github.com/tesseract-ocr/tesseract.git
2) cd tesseract/
3) ./autogen.sh
4) ./configure
5) make
6) make check

After doing make check I am observing this error, How do I fix this (so far I tried removing libicu and reinstalling from source) but this dosent seem to solve this error : the error is:

`ajinkya@ajinkya-H310M-S2:~/Documents/tesseract$ make check
Making check in src/arch
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/arch'
make[2]: Entering directory '/home/ajinkya/Documents/tesseract/src/arch'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/home/ajinkya/Documents/tesseract/src/arch'
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/arch'
Making check in src/ccutil
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/ccutil'
make[2]: Entering directory '/home/ajinkya/Documents/tesseract/src/ccutil'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/home/ajinkya/Documents/tesseract/src/ccutil'
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/ccutil'
Making check in src/viewer
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/viewer'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/viewer'
Making check in src/cutil
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/cutil'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/cutil'
Making check in src/opencl
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/opencl'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/opencl'
Making check in src/ccstruct
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/ccstruct'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/ccstruct'
Making check in src/dict
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/dict'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/dict'
Making check in src/classify
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/classify'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/classify'
Making check in src/wordrec
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/wordrec'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/wordrec'
Making check in src/textord
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/textord'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/textord'
Making check in src/lstm
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/lstm'
make[2]: Entering directory '/home/ajinkya/Documents/tesseract/src/lstm'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/home/ajinkya/Documents/tesseract/src/lstm'
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/lstm'
Making check in src/ccmain
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/ccmain'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/ccmain'
Making check in src/api
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/src/api'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/src/api'
Making check in .
make[1]: Entering directory '/home/ajinkya/Documents/tesseract'
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract'
Making check in tessdata
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/tessdata'
Making check in configs
make[2]: Entering directory '/home/ajinkya/Documents/tesseract/tessdata/configs'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/ajinkya/Documents/tesseract/tessdata/configs'
Making check in tessconfigs
make[2]: Entering directory '/home/ajinkya/Documents/tesseract/tessdata/tessconfigs'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/ajinkya/Documents/tesseract/tessdata/tessconfigs'
make[2]: Entering directory '/home/ajinkya/Documents/tesseract/tessdata'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/home/ajinkya/Documents/tesseract/tessdata'
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/tessdata'
Making check in doc
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/doc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/doc'
Making check in unittest
make[1]: Entering directory '/home/ajinkya/Documents/tesseract/unittest'
make  libgtest.la libgtest_main.la libgmock.la libgmock_main.la libabseil.la apiexample_test applybox_test baseapi_test bitvector_test cleanapi_test colpartition_test dawg_test denorm_test fileio_test heap_test imagedata_test indexmapbidi_test intfeaturemap_test intsimdmatrix_test lang_model_test layout_test linlsq_test loadlang_test mastertrainer_test matrix_test nthitem_test osd_test paragraphs_test progress_test qrsequence_test recodebeam_test rect_test resultiterator_test shapetable_test stats_test stringrenderer_test tablefind_test tablerecog_test tabvector_test tfile_test commandlineflags_test lstm_recode_test lstm_squashed_test lstm_test lstmtrainer_test unichar_test unicharcompress_test unicharset_test validate_grapheme_test validate_indic_test validate_khmer_test validate_myanmar_test validator_test
make[2]: Entering directory '/home/ajinkya/Documents/tesseract/unittest'
make[2]: *** No rule to make target '../googletest/googletest/src/gtest-all.cc', needed by '../googletest/googletest/src/libgtest_la-gtest-all.lo'.  Stop.
make[2]: Leaving directory '/home/ajinkya/Documents/tesseract/unittest'
Makefile:2207: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/ajinkya/Documents/tesseract/unittest'
Makefile:495: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
`

**Comment by stweil** [comment]
Simple fix: don't run `make check`. You don't need it.
