### ISSUE TITLE
Sometimes stops reading the text from image, after sometime it starts reading. 

### ISSUE THREAD

**Issue by parulsngh** [tesseract-ocr/tesseract#2253]
I am using the tess-two:9.0.0 in my android project to read the MRZ code. It's working fine, but some time it stops reading the text from image. Then after some time it again starts reading the text.
------------------------

### Environment

* **Tesseract Version**: tess-two:9.0.0
* **Commit Number**: 
* **Platform**: android

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.
