### ISSUE TITLE
Feature Request: Timeout

### ISSUE THREAD

**Issue by M-Fabian** [tesseract-ocr/tesseract#2254]
### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**: 51316994ccae0b48692d547030f26c0969308214 [5131699]
* **Platform**: Windows 7, 32-bit

### Current Behavior:

I use Tesseract via the C interface. The main process consists of calling TessBaseAPISetImage() and then receiving the results using TessBaseAPIGetUTF8Text() and TessBaseAPIGetIterator() and the other result iterator functions.

I miss the feature to set a timeout because the Tesseract can take quite long on some input images. I see that TessBaseAPIProcessPage() accepts a timeout, so it seems to me that timeouts are supported in the recognition part of the Tesseract.

### Expected Behavior:

I would like to set a timeout when using the aforementioned functions to call Tesseract.

### Suggested Fix:

I am not experienced enough to suggest a good solution. One could make a parameter `tessedit_timeout_max` so set a global timeout but maybe controlling it for each call of TessBaseAPISetImage() is a better way.

**Comment by zdenop** [comment]
Do you mean something like this:
https://github.com/tesseract-ocr/tesseract/wiki/APIExample#example-of-monitoring-ocr-progress-in-c

**Comment by M-Fabian** [comment]
Yes, this is it. I need to call TessBaseAPIRecognize() explicitly (instead of implicitly using TessBaseAPIGetUTF8Text()) with a monitor which I can configure with a timeout or with a callback to check for cancel. Thank you, I will try it.
