### ISSUE TITLE
Unable to extract fractions

### ISSUE THREAD

**Issue by rajeshkalpathi** [tesseract-ocr/tesseract#2274]
### Environment

* **Tesseract Version**: 4.00 LSTM and also tried with TrsseractOnly option
* **Commit Number**: 
* **Platform**: Windows 10 64 Bit

### Current Behavior:

Unable to extract fractions from TextOnImage. The result I get is either Yi or 1A for the fractions. 

Sample Images
![1_4 1](https://user-images.githubusercontent.com/42106734/53481081-7a270000-3aa2-11e9-9a90-fce294ecf96e.png)
![1_4 2](https://user-images.githubusercontent.com/42106734/53481083-7a270000-3aa2-11e9-8542-4f069029cc7c.png)
![1_4 3](https://user-images.githubusercontent.com/42106734/53481086-7a270000-3aa2-11e9-953a-3f2f51797fb3.png)
![3_4 1](https://user-images.githubusercontent.com/42106734/53481087-7abf9680-3aa2-11e9-9baf-f101100ff019.png)
![5_8 1](https://user-images.githubusercontent.com/42106734/53481088-7abf9680-3aa2-11e9-8536-5a425263d073.png)
![5_8 2](https://user-images.githubusercontent.com/42106734/53481089-7abf9680-3aa2-11e9-9d81-69f10caedf70.png)
![5_8 3](https://user-images.githubusercontent.com/42106734/53481090-7b582d00-3aa2-11e9-8c5b-6f36c0ad099f.png)

### Expected Behavior:

Fractions must be extracted as 1/4, 5/8, 3/4

**Comment by amitdo** [comment]
Someone has already reported about this issue. Can't find the issue right now.

**Comment by Shreeshrii** [comment]
You can finetune the traineddata to recognize fractions.

Please see https://github.com/Shreeshrii/tess4training#additional-training-scripts---replace-top-layer-bash

You can test withe the test traineddata from the tutorial -

https://github.com/Shreeshrii/tess4tutorial/raw/master/eng_layer_eng/eng_layer.traineddata

**Comment by Shreeshrii** [comment]
You will need to resize images to at least 36x36px at 300 dpi for best results.

```
 *****  ./onefourth-1.png LANG eng_layer TESSDATA tessdata_best OEM 1 PSM 6 ****
¼

real    0m0.320s
user    0m0.364s
sys     0m0.008s

 *****  ./onefourth-2.png LANG eng_layer TESSDATA tessdata_best OEM 1 PSM 6 ****
¼

real    0m0.452s
user    0m0.448s
sys     0m0.020s

 *****  ./onefourth-3.png LANG eng_layer TESSDATA tessdata_best OEM 1 PSM 6 ****
¼

real    0m0.227s
user    0m0.208s
sys     0m0.012s

 *****  ./threefourth.png LANG eng_layer TESSDATA tessdata_best OEM 1 PSM 6 ****
¾

real    0m0.393s
user    0m0.456s
sys     0m0.004s

```
![onefourth-1](https://user-images.githubusercontent.com/5095331/55866049-3218f400-5b9d-11e9-80bc-3bf6859e2e40.png)
![onefourth-3](https://user-images.githubusercontent.com/5095331/55866050-3218f400-5b9d-11e9-95a2-ab4fa1013be7.png)
![onefourth-2](https://user-images.githubusercontent.com/5095331/55866052-32b18a80-5b9d-11e9-867f-1d457faafc27.png)
![threefourth](https://user-images.githubusercontent.com/5095331/55866125-54ab0d00-5b9d-11e9-9048-d4a6e211f3de.png)

**Comment by amitdo** [comment]
This is an issue with the trained model.

See https://github.com/tesseract-ocr/langdata/issues/69.
