### ISSUE TITLE
editing the wiki

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#2276]
I am able to edit it online but try to do so locally and then commit via git is not working.

Error is

remote: Permission to tesseract-ocr/tesseract.wiki.git denied to Shreeshrii.
fatal: unable to access 'https://github.com/tesseract-ocr/tesseract.wiki.git/': The requested URL returned error: 403

**Comment by stweil** [comment]
That is the normal behaviour of the GitHub wikis. They are read only for normal users.

**Comment by Shreeshrii** [comment]
But I am able to change the page via Web interface. I thought by submitting via git it would inform the maintainers to review the changes.

I added a section on setup of files and directories for lstmtraining. Would be good if page was reviewed. Thanks.
