### ISSUE TITLE
[4.00] Extra symbols produced 

### ISSUE THREAD

**Issue by akiskin** [tesseract-ocr/tesseract#2278]
Gday.

Using 4.00, compiled from release src, Linux env, LTSM engine.

I have pages produced from PDFs (ghostscript) with 300 dpi, then greyscaled with opencv.

Found an issue when ocr output for some specific region has more symbols than there is in the image.

Example: there is an outstanding "word" with "15" in it (actually, it is a part of date - like "15 OCT", identified as two words - which is correct).
Box coords are correct, no other symbols fit in, but output from running tesseract .. --psm 11 --dpi 300 is "156" (instead of "15").

If I cut that part of the image and save it as a separate file, them ocr it with psm=6 (or 7) - output is "15" (correct).

I encountered such behavior only on several symbol combinations - like "15"->"156", "08"->"0O8". Looks like when confidence level between top two identified symbols is very close - both symbols go to output, instead of one.

Did anyone have same issues?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
