### ISSUE TITLE
Use VS2015 to compile tesseract4.1 with OpenCL Error 

### ISSUE THREAD

**Issue by Jesson029** [tesseract-ocr/tesseract#2293]
VS2015 show error messages:
 fatal error C1083:  “CL/cl.h”: No such file or directory
.....

Is project missing files？

**Comment by Jesson029** [comment]
![error](https://user-images.githubusercontent.com/39691950/53862804-70157c00-4023-11e9-8ca1-64c7a6e42d39.png)

**Comment by Jesson029** [comment]
![error](https://user-images.githubusercontent.com/39691950/53864234-eebfe880-4026-11e9-9a2f-f30ebf593224.png)

cmake cannot find the files.
Is cppan not download the files?

**Comment by stweil** [comment]
Just don't compile with OpenCL (unless you want to improve the code). In the best case it will not make your Tesseract faster. In the worst case you will get lots of problems (like the build problem).

**Comment by Jesson029** [comment]
@stweil Thank you for your reply.

But  I want  to test acceleration effect of GPU.
Even if there has problems，the problems gives direction for improvement.
I still plan to try it.

**Comment by zdenop** [comment]
@Jesson029: Do you have installed OpenCL?

**Comment by Jesson029** [comment]
@zdenop   Oh！！！
sorry，I thought the project will include automatically.
Do the project has edition requirements of OpenCL?
Please provide a download URL of OpenCL. 
thank u

**Comment by zdenop** [comment]
No OpenCL is dependency as any other (png, leptonica, tiff...) 
Download link depends on you graphics cards (once upon a time I test build on linux with AMD and on windows with INTELL). IMO you will not get any significant speed improvement: AFAIR OpenCL was used in tiff tresholding, so if I used other image format it was not used...
