### ISSUE TITLE
tesstrain.sh doesn't work on MacOS X

### ISSUE THREAD

**Issue by christianmahnke** [tesseract-ocr/tesseract#2296]
### Environment

* **Tesseract Version**: Current git master as of 7. of March 19 on Mac
* **Commit Number**: 
* **Platform**: ` 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

### Current Behavior:
When calling `tesstrain.sh` with `bash -x`:
``` 
$ bash -x /usr/local/bin/tesstrain.sh --lang frk --langdata_dir langdata
++ dirname /usr/local/bin/tesstrain.sh
+ source /usr/local/bin/tesstrain_utils.sh
++ '[' -n '5.0.2(1)-release' ']'
++ set -u
++ set -eo pipefail
+++ uname -s
+++ tr A-Z a-z
++ UNAME=darwin
++ LANG_CODE=ENG
+++ date +%Y-%m-%d
++ TIMESTAMP=2019-03-07
++ case $UNAME in
+++ mktemp -d -t
mktemp: option requires an argument -- t
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
++ MKTEMP_DT=
```
### Expected Behavior:
It should work 

### Suggested Fix:
The test for the right `mktmp` command is wrong, maybe check only if it's actually required? This way the command fails to early.

**Comment by zdenop** [comment]
Can you please check the current master or 4.1

**Comment by stweil** [comment]
See also issues #1453 and #2578, so I close this issue here.
