### ISSUE TITLE
Issue 13589: tesseract-ocr/fuzzer-api: Undefined-shift in IntegerMatcher::UpdateTablesForFeature

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#2297]
Issue reported by OSS Fuzz:

    intmatcher.cpp:824:59: runtime error: left shift of negative value -18
     #0 0x609e27 in IntegerMatcher::UpdateTablesForFeature(INT_CLASS_STRUCT*, unsigned int*, unsigned int*, int, INT_FEATURE_STRUCT const*, ScratchEvidence*, int) tesseract/src/classify/intmatcher.cpp:824:59

The same issue is also reported when code is built with GCC sanitizers (for example when running the `stringrenderer_test`), see [Wiki](https://github.com/tesseract-ocr/tesseract/wiki/Compiling-%E2%80%93-GitInstallation#debug-builds) for build instructions.

**Comment by stweil** [comment]
This issue is addressed in pull request #2309.

**Comment by zdenop** [comment]
Is this fixed?

**Comment by stweil** [comment]
This issue is fixed, see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13589.
