### ISSUE TITLE
Missing information on text orientation (hOCR property textangle) with LSTM

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#2303]
Tesseract 4 generates the required property `textangle` with the old OCR engine, not when using LSTM. See https://github.com/tmbdev/hocr-tools/issues/148 for examples and more details.

**Comment by stweil** [comment]
The property should be written [here](https://github.com/tesseract-ocr/tesseract/blob/master/src/api/hocrrenderer.cpp#L50).

**Comment by GSATHYANARAYANA** [comment]
Hi,
I am using Tesseract version 4.1.0,
I got confidence score for each character by using HOCR
but it's accuracy is low, so I want know

1. How the HOCR algorithm works and how it will calculate the confidence scores for each character
2. Can I changing any thing to improve the HOCR performance

**Comment by stweil** [comment]
@bertsky, the information is missing in the ALTO XML (which has a `ROTATION` tag) as well.

**Comment by bertsky** [comment]
Interesting. This should __already__ write the orientation angle (i.e. multiple of 90°) on current master. And it uses `PageIterator.Orientation()`, which is _not_ related to (legacy) OSD, but the normal page segmentation included in `PSM_AUTO`, `PSM_AUTO_OSD`, `PSM_AUTO_ONLY` and `PSM_SPARSE_TEXT_OSD`. So it should work with any LSTM model loaded. I wonder why this issue even exists. (Have not tried it myself yet.)

But then, why does the code only use orientation value, but not add the skew angle?

@stweil Sure I'll do the same thing in #2815 as well.

**Comment by stweil** [comment]
> This should already write the orientation angle (i.e. multiple of 90°) on current master.

Indeed, it is fixed in 4.1.1 and master which write the `textangle` tag, so I close this issue.
