### ISSUE TITLE
Roman numerals in Russian text

### ISSUE THREAD

**Issue by darkblaze69** [tesseract-ocr/tesseract#2307]
### Environment
tesseract from ppa on ubuntu 18.04:
https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr
tesseract 4.1.0-rc1-56-g7fbd

### Current Behavior:
Tesseract cannot recognize Roman numerals for example in Russian language mode

### Expected Behavior:
It should recognize at least Roman numerals for example XX XIX III XIV XXVIII etc. 
Instead it tries to substitute similar looking Cyrillic letters like ХПГ ХШ ХГ/-ХУ ХИ] etc

Even if I option for lang = rus+lat it doesn't help.

**Comment by amitdo** [comment]
Try with best1/fast `Cyrillic.traineddata`
