### ISSUE TITLE
Modify existing traineddata 

### ISSUE THREAD

**Issue by 9tontruck** [tesseract-ocr/tesseract#231]
Hi,

I have test set that only has "uppercase English alphabets" and "numbers".
Is there a way to modify the existing traineddata file so that it only reads upper case alphabets and numbers?

thanks in advance

**Comment by amitdo** [comment]
There is a config parameter for that purpose: `tessedit_char_whitelist`.

Next time, please use the forum to ask questions about this software.
https://groups.google.com/d/forum/tesseract-ocr
