### ISSUE TITLE
tesseract 4.0 trained eng.traineddata model not working in legacy mode

### ISSUE THREAD

**Issue by mohamed0123** [tesseract-ocr/tesseract#2315]
I have trained a model on tesseract v 4.0, it works fine when I use `--oem 1` yet when I try `--oem 0` it throws `Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract`

note : un-trained model worked in both legacy and LSTM modes

**Comment by Shreeshrii** [comment]
LSTM training will only create the LSTM model. If you want the legacy mode, use combine_tessdata to unpack from the old version and add to your newly traineddata with LSTM model.

**Comment by jungaria** [comment]
Shreeshrii

> LSTM training will only create the LSTM model. If you want the legacy mode, use combine_tessdata to unpack from the old version and add to your newly traineddata with LSTM model. OR you can train a new legacy model separately and add to your new traineddata.

Could you please explain how to "use combine_tessdata to unpack from the old version"  ?
