### ISSUE TITLE
ERROR: Could not parse int32_t from --traineddata

### ISSUE THREAD

**Issue by ameera3** [tesseract-ocr/tesseract#2318]
### Environment

* **Tesseract Version**: 
tesseract 4.0.0-beta.1
leptonica-1.75.3
libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found SSE

* **Platform**: `uname -a` output: Linux CUDA1 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

### Current Behavior:  The output of 

lstmtraining --debug_interval \
--traineddata ./dottrain/eng/eng.traineddata \
--net_spec '[1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx96 Lrx96 Lfx256 O1c111]' \
--model_output ./dotoutput/base --learning_rate 20e-4 \
--train_listfile ./dottrain/eng.training_files.txt \
--eval_listfile ./doteval/eng.training_files.txt \
--max_iterations 100000 

is ERROR: Could not parse int32_t from --traineddata

**Comment by Shreeshrii** [comment]
You have to specify a number for debug_interval. Use 0 to get msgs every 100 iterations.

**Comment by ameera3** [comment]
Thanks Shree!  That worked.  It's training now, but I am getting a lot of errors like Compute CTC targets failed.
