### ISSUE TITLE
Improve codebase with modern C++

### ISSUE THREAD

**Issue by egorpugin** [tesseract-ocr/tesseract#2320]
Assuming we have minimal C++14 (or 17?), there's a worthy task to improve tesseract codebase.
C++14 is on by default since g++-6, clang-5 (or 6), msvc since VS2015? (VS2019 release is on April 2).

This is not immediate task, so we could do this over time slowly.

1. Update complex types (iterators etc.) with `auto` keyword.
https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/
https://steveire.wordpress.com/2016/03/19/aaargh-aaa-right-good-and-hygenic/
https://github.com/tesseract-ocr/tesseract/commit/4c2bbebeccf28bac747fa1e567893906ccdfe8a2#comments (for reference).

2. Start using range-for loops.
https://github.com/tesseract-ocr/tesseract/commit/631882a346e465e23b81f8fc3c8a53ffa0cb9dcd#r32894610 (for reference).

**Comment by amitdo** [comment]
I think we should start requiring use of compiler that supports C++14.

https://clang.llvm.org/extra/clang-tidy/checks/list.html

https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-auto.html
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-override.html
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-default.html
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-delete.html

**Comment by amitdo** [comment]
https://clang.llvm.org/extra/clang-tidy/checks/modernize-make-unique.html

**Comment by egorpugin** [comment]
2. Range for loops (first post updated).

**Comment by amitdo** [comment]
https://clang.llvm.org/extra/clang-tidy/checks/modernize-loop-convert.html

**Comment by zdenop** [comment]
I do not think we need to keep open issue for this. Better would be to send PR or create separate branch to be safe: at the moment we have wide range of OS/devices supported (mobile, BDS, linux, Windows  Mac, Rasbery PI...)  and would prefer to keep support until it make sense.
