### ISSUE TITLE
Generating data with more than 8 fonts problem

### ISSUE THREAD

**Issue by ltphy** [tesseract-ocr/tesseract#2321]
### Environment

* **Tesseract Version**:  tesseract 4.0.0-beta.1 
* **Platform**: Ubuntu 18.04 64 bit

### Current Behavior:
I try to train for more than 10 fonts. However, whenever the process generates till the fonts number 8th, it does not continue.
I using the following command to generate data. 
`./tesstrain.sh --lang vie --linedata_only --langdata_dir ../langdata --noextract_font_properties --tessdata_dir ../../tessdata --output_dir ../../vietrain/test_many_fonts --fonts_dir /usr/share/fonts --fontlist  "Verdana Regular" "Verdana Bold"  "Courier New Italic" "Courier New Regular" "Liberation Serif Bold" "Liberation Sans Bold"  "Courier New Bold Italic" "Liberation Sans Bold" "Liberation Sans Bold Italic" "Liberation Sans Italic" --exposures "0" --save_box_tiff`

![generate_data_problem](https://user-images.githubusercontent.com/32784614/54362665-ef4a2600-469b-11e9-9c0d-4c8d8fda5164.png)

It should not have any error because i can generate data successfully with the number of fonts lower than 8. 

### Expected Behavior:
It is stated that there is no limit to the number of fonts to generate data. It should generate all the given fonts in the command line.

**Comment by Shreeshrii** [comment]
> tesseract 4.0.0-beta.1

Please update your version of tesseract. You can either build from source using master branch on github or install a PPA from https://github.com/tesseract-ocr/tesseract/wiki#ubuntu---ppa--packages-from-notesalexporg

**Comment by ltphy** [comment]
After building tesseract from source, there are no more issues.
