### ISSUE TITLE
--disable-openmp still builds with openmp

### ISSUE THREAD

**Issue by dagnelies** [tesseract-ocr/tesseract#2323]
Building `master` on Ubuntu:
```
> ./configure --disable-openmp
...
>  make | grep -i openmp
libtool: link: g++  ...   ***-fopenmp*** -Wl,-soname -Wl,libtesseract.so.4 -o .libs/libtesseract.so.4.0.1
...
libtool: link: g++ -g -O2 -std=c++14 -o .libs/tesseract tesseract-tesseractmain.o  ./.libs/libtesseract.so -llept -lrt -lpthread ***-fopenmp***
```

I'm a total noob regarding C++/Makefiles, so I don't really know what could be wrong or how to really disable it.

**Comment by zdenop** [comment]
Please provide more details (at lease configure output and config.log)

**Comment by dagnelies** [comment]
Here is the output of `./configure --disable-openmp`

[configure.txt](https://github.com/tesseract-ocr/tesseract/files/2971219/configure.txt)

And here is `config.log`

[config.log](https://github.com/tesseract-ocr/tesseract/files/2971228/config.log)

**Comment by zdenop** [comment]
There is nothing in log that instruct tesseract to use `-fopenmp`.
Can you provide also make log (`make 2>&1 | tee make.log`)?

**Comment by iragerasimov** [comment]
In my case tesseract-4.0.0 was built on CentOS 6 as $ ./configure --disable-openmp as well.
However when I run lstmtraining I get:
lstmtraining: symbol lookup error: /usr/local/lib/libtesseract.so.4: undefined symbol: GOMP_parallel
ldd /usr/local/lib/libtesseract.so.4
	linux-vdso.so.1 =>  (0x00007ffff6cbc000)
	liblept.so.5 => /usr/local/lib/liblept.so.5 (0x00007fee72364000)
	libpng12.so.0 => /usr/lib64/libpng12.so.0 (0x00007fee72114000)
	libjpeg.so.62 => /usr/lib64/libjpeg.so.62 (0x00007fee71ebc000)
	libtiff.so.3 => /usr/lib64/libtiff.so.3 (0x00007fee71c54000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fee71a34000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fee71814000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fee71504000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fee7127c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fee70ee4000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fee70cc4000)
	/lib64/ld-linux-x86-64.so.2 (0x000055c53e44f000)

**Comment by zdenop** [comment]
Please use recent git code when reporting issue.

**Comment by stweil** [comment]
@iragerasimov, maybe `/usr/local/lib/libtesseract.so.4` is not the result of your build, but another version which was built with OpenMP?

**Comment by iragerasimov** [comment]
Thanks! Looked more closely at /usr/local/lib/libtesseract.so.4 and after re-build got training tools working

**Comment by newmediaagency** [comment]
Thank you!

**Comment by dagnelies** [comment]
In my case, it appears something was not "clean" during the build.

After I deleted everything, checked out again and re-run everything, it built fine, without open-mp.
