### ISSUE TITLE
OMP_THREAD_LIMIT has no effect

### ISSUE THREAD

**Issue by inzanez** [tesseract-ocr/tesseract#2325]
Hi

I'm using Tesseract built on Windows using CPPAN. I tried pre-built versions and custom built versions, and it seems to that the environment variable OMP_THREAD_LIMIT does not have any effect. I set it to 1, but still the tesseract.exe is using 4 cores to 100%.

I also tried developing an own executable against the DLL and set the variable directly, but that doesn't help either.

Is there any way to restrict one tesseract engine to a single core?

**Comment by dagnelies** [comment]
May it be the same issue as #1081 ?

**Comment by inzanez** [comment]
For the issue you mentioned, the SET OMP_THREAD_LIMIT to 1 does the trick. Somehow. With the current version / my windows version(s) it does not. That's a bit confusing.

**Comment by zdenop** [comment]
@inzanez : what is output for `tesseract -v`?

**Comment by stweil** [comment]
@inzanez, how exactly did you set `OMP_THREAD_LIMIT`? Did you set it in the same shell before running `tesseract`?

**Comment by zdenop** [comment]
@stweil : current cppan (cmake) build should have omp [turned off ](https://github.com/tesseract-ocr/tesseract/blob/29389f7145c6d4d387c98aa6460ee1bd26b77948/CMakeLists.txt#L72)by default. That why I asked  for version output.

**Comment by inzanez** [comment]
@zdenop: One version I compiled is showing version 4.0.0 (vcpkg build). I don't have the compiled CPPAN build ready anymore, but I will test and get back. I tried both by the way.

@stweil: Yes, I know that setting the variable is only valid for the current CMD window when setting it directly in the console.

**Comment by zdenop** [comment]
;-) you wrote:
> I'm using Tesseract built on Windows using CPPAN

Next: I am not interesting in version number only, but for full output

**Comment by inzanez** [comment]
@zdenop: my bad.
tesserract.exe -v
tesseract 4.0.0
 leptonica-1.76.0 (Mar 15 2019, 07:57:55) [MSC v.1916 LIB Release x64]
  libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.3) : libpng 1.6.36 : libtiff 4.0.
10 : zlib 1.2.11
 Found AVX
 Found SSE

**Comment by zdenop** [comment]
try to use the latest code from git hub.

**Comment by inzanez** [comment]
Oh, I did:
tesseract -v
tesseract local
 leptonica-1.76.0 (Mar 15 2019, 13:28:31) [MSC v.1916 LIB Release x86]
  libgif 5.1.4 : libjpeg 9b : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libw
ebp 0.6.1 : libopenjp2 2.3.0
 Found OpenMP 200203
 Found libarchive 3.3.2 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.6 liblz4/1.8.3

No difference though...

**Comment by zdenop** [comment]
Can you build it with cppan? It seems you build it with sw....

**Comment by inzanez** [comment]
I did, and you were right. That resolved the problem. Could you elaborate on why that makes a difference? :-)

**Comment by zdenop** [comment]
Different build system use different configuration => different results. Easy right?
