### ISSUE TITLE
Does anyone use/benefit from OpenMP?

### ISSUE THREAD

**Issue by dagnelies** [tesseract-ocr/tesseract#2326]
...sorry in advance if this is off topic.

Everywhere, you read tickets and wiki articles about disabling OpenMP for better performance. Whether directly during build or by setting `OMP_THREAD_LIMIT=1`.

*So, here comes the dumb question: does anyone use it / has any benefit from it?* From my experience, it just burns CPU for nothing.

I have more and more the feeling that removing the OpenMP stuff as a whole would be beneficial.

Alternatively, IMHO, it would be much more advantageous if parallelism occurred at page level, not in some tiny inner loop. That would lead to a real boost for multi-page documents.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
