### ISSUE TITLE
Not able to extract text from image

### ISSUE THREAD

**Issue by bhasinnaik** [tesseract-ocr/tesseract#2330]
Hi,

I am trying to extract text from image but every time it returns warning Warning:
 Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 463
Empty page!!
Estimating resolution as 463
Empty page!!

Here is the image.
![3637](https://user-images.githubusercontent.com/2960160/54472031-fb42fe80-47e7-11e9-82c2-619412ad4d86.png)

**Comment by zdenop** [comment]
Captcha image are designed to not work  with OCR. So everything is working as expected/designed.
