### ISSUE TITLE
Define minimal tesseract dependancies

### ISSUE THREAD

**Issue by zdenop** [tesseract-ocr/tesseract#2333]
I tried to build (cmake&clang) tesseract with minimal dependencies, so I build leptonica without any dependencies (not even zlib). Build finished fine, ` tesseract -v` produced:
```
tesseract 4.1.0-rc1-97-g681e
 leptonica-1.78.0 (Mar 13 2019, 19:12:40) [MSC v.1915 LIB Release x64]
  (null)
 Found AVX2
 Found AVX
 Found SSE
```

But when I run `tesseract test.pnm -`  it produced following error messages and than it crashed:
```
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 333
Error in pixWriteMemPng: function not present
```
These indicates that there are several **must dependencies** for running tesseract (tiff, png and therefore zlib...) and they have to be checked (bmfCreate and pixReadMem)  during configuring build.

More advance approach would to analyze if relevant code could be skipped - but than we should somehow distribute information about not available API (e.g. [`ProcessPagesMultipageTiff`](https://github.com/tesseract-ocr/tesseract/blob/ea3b806357f5e23097f4ae9ac8c5b7d756b02e3e/src/api/baseapi.cpp#L1036)).

**Comment by amitdo** [comment]
Looks like a bug in baseapi.cpp.

**Comment by stweil** [comment]
Leptonica is normally used as a shared library. So it is possible to provide a minimal `liblept.so` which obviously causes a crash or to use a full `liblept.so` which will work fine.

Therefore I think it is not a build problem, but a problem of the error handling at runtime (which should also be fixed, of course).

**Comment by amitdo** [comment]
Leponica can handle pnm format without any dependency.

**Comment by Shreeshrii** [comment]
what about adding minimum versions of python (3.6) and bash (4.4) for training tools?

**Comment by zdenop** [comment]
@Shreeshrii: we can put  info about minimum dependencies to README,md. 
Maybe I found some time to rewrite python script to 3.5 compatible version (it should not be a big issue) or at least to check python version at the begin...

**Comment by zdenop** [comment]
@amitdo : this was exactly reason why I use pnm format: I guess this minimal tesseract&leptonica version is needed by tesseract wrapper (python, java maybe C#) that will use its standard way for opening files and pass only image data to tesseract.

**Comment by zdenop** [comment]
@stweil : you are right - I did not calculate with scenario with replacing shared leptonica with version with less features (which I did yesterday on linux "successfully"). 
But to do check at build time is IMO first step (that can actually hide this bug). 
Anyway to have working tesseract and leptonica library without any other dependency should be finale target.

**Comment by bertsky** [comment]
> what about adding minimum versions of python (3.6) and bash (4.4) for training tools?

Why bash `>= 4.4`, has that actually been ascertained?

**Comment by zdenop** [comment]
Here are more details if anybody would like to help it:
*  **Building leptonica with libpng (and therefore zlib) support is sufficient to avoid crash**.
*  Just `api->Init("./tessdata", nullptr);` will cause error messages (but not crash):
```
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
```
*  `api->SetImage(pixs)` is working ok (at least `PIX* check = api->GetInputImage()` confirm it)
*  cash will be caused by calling `outText = api->GetUTF8Text()` (without png support):
```
Warning: Invalid resolution 0 dpi. Using 70 instead.
Error in pixWriteMemPng: function not present
Error in pixReadMem: Unknown format: no pix returned
src_pix != nullptr:Error:Assert failed:in file imagedata.cpp, line 232
```
Assert is because [GetPixInternal](https://github.com/tesseract-ocr/tesseract/blob/90aef80dd7ab61fda7f9db1b79bfdef49dd11b25/src/ccstruct/imagedata.cpp#L337) did not return pix because [pixReadMem](https://github.com/tesseract-ocr/tesseract/blob/90aef80dd7ab61fda7f9db1b79bfdef49dd11b25/src/ccstruct/imagedata.cpp#L343) did not find format of image_data_. Reason for it that image_data_  should be [stored with png format](https://github.com/tesseract-ocr/tesseract/blob/90aef80dd7ab61fda7f9db1b79bfdef49dd11b25/src/ccstruct/imagedata.cpp#L329) which is not available...

**Comment by zdenop** [comment]
Crash is fixed. `Init` is open for improvement.
