### ISSUE TITLE
Tesseract with Alfresco Communities

### ISSUE THREAD

**Issue by momaydopod** [tesseract-ocr/tesseract#2338]
I configured already.  when I upload image to alfresco but txt file is empty.  I try manual run tesseract can convert image to txt file.

<img width="856" alt="2019-03-20 15_55_42-10 50 30 37 - Remote Desktop Connection" src="https://user-images.githubusercontent.com/36228338/54674886-ee981080-4b2f-11e9-87a9-a76b52f5e59d.png">

**Comment by zdenop** [comment]
I am sorry but we do not provide support for 3rd party project
