### ISSUE TITLE
[C API] Missing function to get "struct Pix" instances

### ISSUE THREAD

**Issue by jflesch** [tesseract-ocr/tesseract#234]
Hello,

I've been trying to use the C API of Tesseract for [PyOCR](https://github.com/jflesch/pyocr) (and so, indirectly, [Paperwork](https://github.com/jflesch/paperwork/)).

To do so, I've been looking for a way to pass an in-memory image to Tesseract (to avoid the use of temporary files). There is a function ```TessBaseAPIProcessPage()```, but I've found no way to create the ```struct Pix``` it requires.

There is a C++ function ```ProcessPagesFileList``` that appears to do the job, but C functions are much  much easier to bind with Python than C++ ones.

Thanks in advance for your help,

**Comment by zdenop** [comment]
First of all: Please use tesseract forum for asking support - see [FAQ](https://github.com/tesseract-
ocr/tesseract/wiki/FAQ#rules-and-advice)
Next PIX is leptonica structure - you can get it with leptonica.pixRead(filename)

**Comment by jflesch** [comment]
Sorry, my bad.
