### ISSUE TITLE
Brew install version 3

### ISSUE THREAD

**Issue by steakchaser** [tesseract-ocr/tesseract#2343]
I'd like to use version 3.x of `tesseract`.  Attempting to install from a 3.x git sha results in an error though:

`> brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/5df6eb919506a097b2efb1df34a16e3a147c8731/Formula/tesseract.rb`

> Error: tesseract: "cxx11" is not a recognized standard

Any ideas?

**Comment by zdenop** [comment]
We do provide support only for installing from source. You use any other tool (e.g. package manager) you to contact those providers (e.g. Homebrew) for support.

**Comment by Jamxscape** [comment]
> I'd like to use version 3.x of `tesseract`. Attempting to install from a 3.x git sha results in an error though:
> 
> `> brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/5df6eb919506a097b2efb1df34a16e3a147c8731/Formula/tesseract.rb`
> 
> > Error: tesseract: "cxx11" is not a recognized standard
> 
> Any ideas?

have you soled this problem? I will be crazy for this problem
