### ISSUE TITLE
Link openalpr-opencv4 error, libtesseract.so: undefined reference to operator delete(void*, unsigned long)@CXXABI_1.3.9'

### ISSUE THREAD

**Issue by geyungjen** [tesseract-ocr/tesseract#2346]
I have centos7 and installed:

opencv 4.0.1
Tesseract Version: 4.1.0-rc1-54-g5de2
Leptonica 1.78

Following is cmake, make,

But error at linking

/usr/local/lib/libtesseract.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'

Any suggestions? Thanks.

[root@localhost build]# cmake -DCMAKE_CXX_FLAGS=-std=c++11 ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Tesseract
-- Found OpenCV: /usr/local/OpenCV-4.0.1 (found version "4.0.1")
-- Found CURL: /usr/local/lib/libcurl.so (found version "7.29.0")
-- Found log4cplus
-- Found JNI: /usr/lib/jvm/java/jre/lib/amd64/libjawt.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/megan/git/openalpr-opencv4/src/build
[root@localhost build]# make 2> /tmp/make.txt
Scanning dependencies of target support
[ 1%] Building CXX object openalpr/support/CMakeFiles/support.dir/filesystem.cpp.o
[ 1%] Building CXX object openalpr/support/CMakeFiles/support.dir/timing.cpp.o
[ 2%] Building CXX object openalpr/support/CMakeFiles/support.dir/tinythread.cpp.o
[ 3%] Building CXX object openalpr/support/CMakeFiles/support.dir/platform.cpp.o
[ 3%] Building CXX object openalpr/support/CMakeFiles/support.dir/utf8.cpp.o
[ 4%] Building CXX object openalpr/support/CMakeFiles/support.dir/version.cpp.o
[ 5%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/bitstate.cc.o
[ 5%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/compile.cc.o
[ 6%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/dfa.cc.o
[ 7%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/filtered_re2.cc.o
[ 7%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/mimics_pcre.cc.o
[ 8%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/nfa.cc.o
[ 9%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/onepass.cc.o
[ 9%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/parse.cc.o
[ 10%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/perl_groups.cc.o
[ 11%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/prefilter.cc.o
[ 11%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/prefilter_tree.cc.o
[ 12%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/prog.cc.o
[ 13%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/re2.cc.o
[ 13%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/regexp.cc.o
[ 14%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/set.cc.o
[ 14%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/simplify.cc.o
[ 15%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/stringpiece.cc.o
[ 16%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/tostring.cc.o
[ 16%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/unicode_casefold.cc.o
[ 17%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/unicode_groups.cc.o
[ 18%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/util/hash.cc.o
[ 18%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/util/stringprintf.cc.o
[ 19%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/util/rune.cc.o
[ 20%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/util/strutil.cc.o
[ 20%] Building CXX object openalpr/support/CMakeFiles/support.dir/re2/util/valgrind.cc.o
[ 21%] Linking CXX static library libsupport.a
[ 21%] Built target support
Scanning dependencies of target video
[ 22%] Building CXX object video/CMakeFiles/video.dir/videobuffer.cpp.o
[ 23%] Linking CXX static library libvideo.a
[ 23%] Built target video
Scanning dependencies of target openalpr
[ 24%] Building CXX object openalpr/CMakeFiles/openalpr.dir/alpr.cpp.o
[ 24%] Building CXX object openalpr/CMakeFiles/openalpr.dir/alpr_impl.cpp.o
[ 25%] Building CXX object openalpr/CMakeFiles/openalpr.dir/alpr_c.cpp.o
[ 26%] Building CXX object openalpr/CMakeFiles/openalpr.dir/config.cpp.o
[ 26%] Building CXX object openalpr/CMakeFiles/openalpr.dir/config_helper.cpp.o
[ 27%] Building CXX object openalpr/CMakeFiles/openalpr.dir/detection/detector.cpp.o
[ 28%] Building CXX object openalpr/CMakeFiles/openalpr.dir/detection/detectorcpu.cpp.o
[ 28%] Building CXX object openalpr/CMakeFiles/openalpr.dir/detection/detectorcuda.cpp.o
[ 29%] Building CXX object openalpr/CMakeFiles/openalpr.dir/detection/detectorocl.cpp.o
[ 30%] Building CXX object openalpr/CMakeFiles/openalpr.dir/detection/detectorfactory.cpp.o
[ 30%] Building CXX object openalpr/CMakeFiles/openalpr.dir/detection/detectormorph.cpp.o
[ 31%] Building CXX object openalpr/CMakeFiles/openalpr.dir/detection/detectormask.cpp.o
[ 31%] Building CXX object openalpr/CMakeFiles/openalpr.dir/licenseplatecandidate.cpp.o
[ 32%] Building CXX object openalpr/CMakeFiles/openalpr.dir/utility.cpp.o
[ 33%] Building CXX object openalpr/CMakeFiles/openalpr.dir/ocr/tesseract_ocr.cpp.o
[ 33%] Building CXX object openalpr/CMakeFiles/openalpr.dir/ocr/ocr.cpp.o
[ 34%] Building CXX object openalpr/CMakeFiles/openalpr.dir/ocr/ocrfactory.cpp.o
[ 35%] Building CXX object openalpr/CMakeFiles/openalpr.dir/postprocess/postprocess.cpp.o
[ 35%] Building CXX object openalpr/CMakeFiles/openalpr.dir/postprocess/regexrule.cpp.o
[ 36%] Building CXX object openalpr/CMakeFiles/openalpr.dir/binarize_wolf.cpp.o
[ 37%] Building CXX object openalpr/CMakeFiles/openalpr.dir/ocr/segmentation/charactersegmenter.cpp.o
[ 37%] Building CXX object openalpr/CMakeFiles/openalpr.dir/ocr/segmentation/histogram.cpp.o
[ 38%] Building CXX object openalpr/CMakeFiles/openalpr.dir/ocr/segmentation/histogramvertical.cpp.o
[ 39%] Building CXX object openalpr/CMakeFiles/openalpr.dir/ocr/segmentation/histogramhorizontal.cpp.o
[ 39%] Building CXX object openalpr/CMakeFiles/openalpr.dir/edges/edgefinder.cpp.o
[ 40%] Building CXX object openalpr/CMakeFiles/openalpr.dir/edges/platecorners.cpp.o
[ 41%] Building CXX object openalpr/CMakeFiles/openalpr.dir/edges/platelines.cpp.o
[ 41%] Building CXX object openalpr/CMakeFiles/openalpr.dir/edges/textlinecollection.cpp.o
[ 42%] Building CXX object openalpr/CMakeFiles/openalpr.dir/edges/scorekeeper.cpp.o
[ 43%] Building CXX object openalpr/CMakeFiles/openalpr.dir/colorfilter.cpp.o
[ 43%] Building CXX object openalpr/CMakeFiles/openalpr.dir/prewarp.cpp.o
[ 44%] Building CXX object openalpr/CMakeFiles/openalpr.dir/transformation.cpp.o
[ 44%] Building CXX object openalpr/CMakeFiles/openalpr.dir/textdetection/characteranalysis.cpp.o
[ 45%] Building CXX object openalpr/CMakeFiles/openalpr.dir/textdetection/platemask.cpp.o
[ 46%] Building CXX object openalpr/CMakeFiles/openalpr.dir/textdetection/textcontours.cpp.o
[ 46%] Building CXX object openalpr/CMakeFiles/openalpr.dir/textdetection/textline.cpp.o
[ 47%] Building CXX object openalpr/CMakeFiles/openalpr.dir/textdetection/linefinder.cpp.o
[ 48%] Building CXX object openalpr/CMakeFiles/openalpr.dir/pipeline_data.cpp.o
[ 48%] Building C object openalpr/CMakeFiles/openalpr.dir/cjson.c.o
[ 49%] Building CXX object openalpr/CMakeFiles/openalpr.dir/motiondetector.cpp.o
[ 50%] Building CXX object openalpr/CMakeFiles/openalpr.dir/result_aggregator.cpp.o
[ 50%] Linking CXX shared library libopenalpr.so
[ 50%] Built target openalpr
Scanning dependencies of target alpr
[ 50%] Building CXX object CMakeFiles/alpr.dir/main.cpp.o
[ 51%] Linking CXX executable alpr
[root@localhost build]# cat /tmp/make.txt
/usr/local/lib/libtesseract.so: undefined reference to vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21' /usr/local/lib/libtesseract.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits, std::allocator >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'
/usr/local/lib/libtesseract.so: undefined reference to std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21' /usr/local/lib/libtesseract.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits, std::allocator >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/local/lib/libtesseract.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21' /usr/local/lib/libtesseract.so: undefined reference to vtable for std::__cxx11::basic_stringstream<char, std::char_traits, std::allocator >@GLIBCXX_3.4.21'
/usr/local/lib/libtesseract.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21' /usr/local/lib/libtesseract.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits, std::allocator >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/local/lib/libtesseract.so: undefined reference to operator delete[](void*, unsigned long)@CXXABI_1.3.9' /usr/local/lib/libtesseract.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits, std::allocator >::swap(std::__cxx11::basic_string<char, std::char_traits, std::allocator >&)@GLIBCXX_3.4.21'
/usr/local/lib/libtesseract.so: undefined reference to VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21' /usr/local/lib/libtesseract.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits, std::allocator >::_M_assign(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&)@GLIBCXX_3.4.21'
/usr/local/lib/libtesseract.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21' /usr/local/lib/libtesseract.so: undefined reference to __cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/usr/local/lib/libtesseract.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21' /usr/local/lib/libtesseract.so: undefined reference to operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
make[2]: *** [alpr] Error 1
make[1]: *** [CMakeFiles/alpr.dir/all] Error 2
make: *** [all] Error 2

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.
