### ISSUE TITLE
pdftohtml fails to parse an OCRed PDF by tesseract

### ISSUE THREAD

**Issue by VasLem** [tesseract-ocr/tesseract#2347]
### Environment

* **Tesseract Version**: 4.0.1b
* **Platform**: Ubuntu 18.04, kernel: 4.15.0-47-generic

### Current Behavior: 
Poppler-utils 0.75.0 cannot parse the OCRed pdf and retrieve the text layer

### Expected Behavior:
 Poppler-utils pdftohtml is currently the most accurate opensource PDF parser in Linux environments, it should have been able to parse the OCRed pdf

### Suggested Fix:
 A bad rendering during conversion from HOCR to PDF might have caused the error, I have also made an issue in [freedesktop gitlab](https://gitlab.freedesktop.org/poppler/poppler/issues/745) explaining the situation, if anyone has any idea why this is happening, please share it and I will participate in the fix if needed.

**Comment by stweil** [comment]
https://gitlab.freedesktop.org/poppler/poppler/issues/745 shows a wrong call `pdftohtml test.jpg`. You cannot blame `pdftohtml` that it refuses to parse a JPEG image. `pdftohtml` has no problems with extracting the text from the PDF file which is generated by Tesseract, but it requires the command line option `-hidden`.

**Comment by stweil** [comment]
Using `convert pdf-test.pdf test.jpg` creates a JPEG image with 72 DPI. Tesseract does a surprisingly good job to find the correct text although the resolution is not great. Try `convert -density 300x300 pdf-test.pdf test.jpg` to get better results.

**Comment by VasLem** [comment]
> https://gitlab.freedesktop.org/poppler/poppler/issues/745 shows a wrong call `pdftohtml test.jpg`. You cannot blame `pdftohtml` that it refuses to parse a JPEG image. `pdftohtml` has no problems with extracting the text from the PDF file which is generated by Tesseract, but it requires the command line option `-hidden`.

It was a typo, I have corrected the issue description

**Comment by Shreeshrii** [comment]
>A bad rendering during conversion from HOCR to PDF might have caused the error,

How did you create the OCRed pdf?

**Comment by VasLem** [comment]
Using `tesseract test.jpg pdf`

**Comment by zdenop** [comment]
Closing is this because there is nothing we can fix (at the moment) on tesseract side.
