### ISSUE TITLE
googletest submodule needs update

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#2349]
```
mv -f $depbase.Tpo $depbase.Po
../../unittest/applybox_test.cc: In member function ‘void {anonymous}::ApplyBoxTest::VerifyBoxesAndText(const char*, const char*, const char*, bool)’:
../../unittest/applybox_test.cc:65:18: error: ‘GTEST_SKIP’ was not declared in this scope
       GTEST_SKIP();
                  ^
Makefile:1584: recipe for target 'applybox_test.o' failed
make[2]: *** [applybox_test.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Error fixed by pulling the latest code from master branch of GoogleTest and then running `make check`.

**Comment by stweil** [comment]
Support for `GTEST_SKIP` was added in commit 37b0c36e32b4b58357af225ef0e74260813a8745.
Commit 37b0c36e32b4b58357af225ef0e74260813a8745 reverted that which caused the regression.
It's now fixed, see commit 59b90bd4663d9be9de597884bb37d0ea27331202.
