### ISSUE TITLE
Russian text recognition problem

### ISSUE THREAD

**Issue by EfimenkoAndrew** [tesseract-ocr/tesseract#2351]
I tried to recognize text from picture, using this code  (repo link https://github.com/EfimenkoAndrew/TesseractIssue) 
#include <tesseract/baseapi.h>
#include <leptonica/allheaders.h>
#include <iostream>
int main()
{
	char* outText = "";

	tesseract::TessBaseAPI api;
	// Initialize tesseract-ocr with English, without specifying tessdata path
	if (api.Init(NULL, "eng+rus")) 
	{
		fprintf(stderr, "Could not initialize tesseract.\n");
		std::cout << GetLastError() << "\n";
		exit(1);
	}

	// Open input image with leptonica library
	Pix *image = pixRead("tTest1.png");
	api.SetImage(image);
	// Get OCR result
	outText = api.GetUTF8Text();
	//printf("OCR output:\n%s", outText);
	std::cout << "OCR output:\n" << outText << '\n';

	// Destroy used object and release memory
	api.End();
	delete[] outText;
	pixDestroy(&image);

	return 0;
}

TESSDATA_PREFIX is set to standard test data. 
Pictures :
![tTest1](https://user-images.githubusercontent.com/26180535/54988968-34d1f180-4fc0-11e9-86e3-c8cfaccc09b2.png)

It works okay with English text, but Russian text returns trash
------------------------

### Environment

* **Tesseract Version**: 4 ( from vcpkg )
* **Platform**: Windows 10 Enterprise 64-bit, Visual Studio 2015/2017 Enterprise

### Current Behavior:
Output 
![image](https://user-images.githubusercontent.com/26180535/54989047-6ba80780-4fc0-11e9-86dd-2db5de633e03.png)

### Expected Behavior:
Hello world!
Привет мир!
### Suggested Fix:
No ideas

**Comment by zdenop** [comment]
Did you try to save result to text file?
I guess problem is that you do send UTF-8 output to windows console that is not able to process it.

**Comment by EfimenkoAndrew** [comment]
It works, thank you! But why I failed to view string in debug mode? Even with std::string data type

**Comment by EfimenkoAndrew** [comment]
![image](https://user-images.githubusercontent.com/26180535/54998333-8ab19400-4fd6-11e9-98aa-9f88ea836348.png)
 Without "Wrap" it is still impossible to read it

**Comment by EfimenkoAndrew** [comment]
![image](https://user-images.githubusercontent.com/26180535/54998428-c77d8b00-4fd6-11e9-9d81-ef87ea5c5481.png)
Here it is

**Comment by zdenop** [comment]
This is not tesseract issue, but general problem of tools/OS you choose to use (to display utf-8 encoded strings).

**Comment by akulik512** [comment]
I think it is because you use Russian and English languages at the same time. Try to do it only for Russian.
