### ISSUE TITLE
 ERROR: Non-existent flag --distort_image=True while running this command in command prompt in cmd  : "C:/Program Files (x86)/Tesseract-OCR/tesseract-master/src/training/tesstrain.py" --fonts_dir "C:/Windows/Fonts" --lang eng --linedata_only --noextract_font_properties --langdata_dir "C:/Program Files (x86)/Tesseract-OCR/tesstutorial/langdata" --tessdata_dir "C:/Program Files (x86)/Tesseract-OCR/tessdata" --output_dir "C:/Program Files (x86)/Tesseract-OCR/tesstutorial/engtrain" --fontlist "Arial Bold"

### ISSUE THREAD

**Issue by X0-100** [tesseract-ocr/tesseract#2353]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by X0-100** [comment]
"C:/Program Files (x86)/Tesseract-OCR/tesseract-master/src/training/tesstrain.py" --fonts_dir "C:/Windows/Fonts" --lang eng --linedata_only --noextract_font_properties --langdata_dir "C:/Program Files (x86)/Tesseract-OCR/tesstutorial/langdata" --tessdata_dir "C:/Program Files (x86)/Tesseract-OCR/tessdata" --output_dir "C:/Program Files (x86)/Tesseract-OCR/tesstutorial/engtrain" --fontlist "Arial Bold" - Runn the command in cmd prompt for windows then getting error for tesseract 4.0

**Comment by Shreeshrii** [comment]
use the latest git master.

**Comment by Shreeshrii** [comment]
```
 ~/tesseract/src/training/tesstrain.py --fonts_dir ~/.fonts --lang eng --linedata_only --noextract_font_properties --langdata_dir ~/langdata --tessdata_dir ~/tessdata --output_dir ~/tesstutorial/engtrain --fontlist "Arial Bold"
[08:50:37] INFO - Log file location: /tmp/eng-2019-03-29v28mvtok/tesstrain.log
[08:50:37] INFO - === Starting training for language eng
[08:50:37] INFO - Testing font: Arial Bold
```

**Comment by Shreeshrii** [comment]
`tesseract/src/training/tesstrain.py` is working fine . Looks like you are using an older version.

Check against - https://github.com/tesseract-ocr/tesseract/blob/master/src/training/tesstrain_utils.sh

**Comment by Shreeshrii** [comment]
Looks like there was some difference between my local file and master branch.

Please test with
**https://github.com/tesseract-ocr/tesseract/blob/6f95dd8ef42dbb7ae241cc9fcb96e758c1f80ded/src/training/tesstrain_utils.py**
