### ISSUE TITLE
No output at all for a subject line

### ISSUE THREAD

**Issue by pevogam** [tesseract-ocr/tesseract#2354]
### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**:  5131699
* **Platform**: Fedora 29

### Current Behavior:

The LSTM OCR outputs no text at all on the image:

![subject_line](https://user-images.githubusercontent.com/1969979/55054280-37087e80-509a-11e9-9662-e79bb36b7ad3.png)

### Expected Behavior:

The closest guess is what I would expect. The LSTM behaves as if the image is a blank background which should be considered a BUG in my opinion. I usually get wrong but some outputs and no output at all doesn't indicate anything about the recognition result and what could possibly be tweaked to improve it.

### Suggested Fix:

Not sure if a fix should involve training or at least providing more debugging information from what is wrong with the recognition. Of course there are reasonable cases where no output is expected from the network (blank spaces for instance) but it still makes no sense why the above case would output nothing at all.

**Comment by zdenop** [comment]
Please use the latest code when you report issue.

**Comment by Shreeshrii** [comment]
Also note which traineddata and --psm you used.

Test with traineddata from tessdata_best and --psm 6

**Comment by dagnelies** [comment]
This looks like similar to #2221. Apparently, many tesseract models (but not all), are not able to recognize white text on black background. Although inverting the image is a workaround, it's often not practical.

**Comment by Shreeshrii** [comment]
Works with tessdata_best and tessdata without any change to image

```
 wget -O invert.png https://user-images.githubusercontent.com/1969979/55054280-37087e80-509a-11e9-9662-e79bb36b7ad3.png


ubuntu@tesseract-ocr:~/TEST$ tesseract invert.png - --dpi 300 --tessdata-dir ~/tessdata_fast
eae Ate ee ed
ubuntu@tesseract-ocr:~/TEST$ tesseract invert.png - --dpi 300 --tessdata-dir ~/tessdata
Fe: Wichtiges Wort
ubuntu@tesseract-ocr:~/TEST$ tesseract invert.png - --dpi 300 --tessdata-dir ~/tessdata_best
Fe: Wichtiges Wort
```

**Comment by pevogam** [comment]
@zdenop We are usually relying on stable releases for our own use cases.

@Shreeshrii I used the best tessdata with `--psm 3`. However, now it seems that tesseract is at least outputting something:

```
tesseract test.png stdout --oem 1 --tessdata-dir tessdata/ -l deu --psm 6
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 1177
AN!
```

and the output is not really missing. Since at least we have an output and the remaining diffculty is related to the trained LSTM I am closing this issue.

**Comment by zdenop** [comment]
@pevogam : For submitting issue is reasonable to check if issue is not solved in the latest code.  If somebody is not willing to do it, then tesseract-ocr user forum should be used instead of posting issue.

**Comment by pevogam** [comment]
@zdenop I am fine with that.

@dagnelies Actually, we have trouble with more inverted images like this and indeed specifically on inverted images.

@Shreeshrii The text is in German and we are respectively using "deu" language data. I assume the reason it works better on inverted images is that the English model is trained much more.

**Comment by gesilavsaoteman** [comment]
> @zdenop I am fine with that.
> 
> @dagnelies Actually, we have trouble with more inverted images like this and indeed specifically on inverted images.
> 
> @Shreeshrii The text is in German and we are respectively using "deu" language data. I assume the reason your runs work better on inverted images is that the English model is trained much more.

**Comment by gesilavsaoteman** [comment]
@pevogam   i get same problem，i  build  it in  centos7.2   ，but only  the    testdata_best  have  outpus， the testdata_fast  don't any outpus........     so, how you slove this problem?

**Comment by pevogam** [comment]
Hi @gesilavsaoteman, we defaulted to using "eng" because the model is simply trained better and performs better when it comes to latin characters. I still believe in the future the situation with the "deu" model will improve and we will be able to use it. Notice that this problem happens mostly on inverted images (e.g. grayscale with white words on black background) so the model might still perform better on more regular input.

**Comment by gesilavsaoteman** [comment]
oh  ，i know，thank you very much！




------------------ 原始邮件 ------------------
发件人: "Plamen Dimitrov"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 下午2:27
收件人: "tesseract-ocr/tesseract"<tesseract@noreply.github.com>;
抄送: "蓝色日出"<604976301@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [tesseract-ocr/tesseract] No output at all for a subject line(#2354)




Hi @gesilavsaoteman, we defaulted to using "eng" because the model is simply trained better and performs better when it comes to latin characters. I still believe in the future the situation with the "deu" model will improve and we will be able to use it. Notice that this problem happens mostly on inverted images (e.g. grayscale with white words on black background) so the model might still perform better on more regular input.
