### ISSUE TITLE
Speed ocr

### ISSUE THREAD

**Issue by nnthero001** [tesseract-ocr/tesseract#236]
I using tessract Android (tess-two) on nexus 7 and pc(core i5), with 1 image 1024x200
nexus 7:  10s and pc: 1s, what happen? Is there any way improve speed ocr when using in Android? Please help me! Thank.

**Comment by zdenop** [comment]
Please use tesseract forum for asking support - see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice).

**Comment by AdeleB** [comment]
Some things that might make it faster are:
Select a smaller region from mGray where your text is, before createBitmap - so the more heavy methods that follow process a smaller image.
Changing Bitmap.Config.ARGB_8888 to Bitmap.Config.RGB_565 - your image is grayscale, it will not need a ARGB bitmap.
more may help: [OCR technology: ](http://www.myknown.com/ocr/)[improve OCR speed](http://www.myknown.com/ocr/improve-ocr-speed/)
