### ISSUE TITLE
Tesseract 4.0.0 performance for android

### ISSUE THREAD

**Issue by DorisGM** [tesseract-ocr/tesseract#2367]
Hi， I  used tesseract 4.0.0(OEM_LSTM_ONLY) and 3.0.5 to recognition a same picture. The result is  tesseract 4.0.0 spend more time than 3.0.5.  
It's wired. Tessaract 4.0 performance should be better than 3.0.5 , is it right?
Maybe Because of the 4.0.0 used LSTM ，It is so heavy for Android CPU that need spend more time to recognition ?

Look forward yours help!

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support. 
And please - do a simple internet search before posting question.
