### ISSUE TITLE
Please teach me What is improved ver. 3.04.

### ISSUE THREAD

**Issue by kiokju** [tesseract-ocr/tesseract#237]
I wonder what is improved ver. 3.04. more detail especially these list.

* Improved font identification
* Fixed problems with shifted baselines so recognition can recover from layout analysis errors.
* Improved single column layout analysis
* Many bug fixes.

thanks!!

**Comment by zdenop** [comment]
Please use tesseract forum for asking questions/support - see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice).
