### ISSUE TITLE
Phase I: Generating training images === ERROR: Could not find training text file /tesstutorial/langdata/tam/tam.training_text

### ISSUE THREAD

**Issue by nijanthan0** [tesseract-ocr/tesseract#2373]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by Shreeshrii** [comment]
> Could not find training text file /tesstutorial/langdata/tam/tam.training_text 

tesstutorial setup has files only for eng.

If you want to run for Tamil, you need to download the required file.

https://github.com/tesseract-ocr/langdata/tree/master/tam

**Comment by nijanthan0** [comment]
Yes, i got it but it shows further error. Correct --font-args

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by nijanthan0** [comment]
Sorry tesseract forum means?

**Comment by zdenop** [comment]
Are you able to to simple internet search? Or read the guidelines for posting issue???
