### ISSUE TITLE
I got problem in fonts. I used font website but I can't 

### ISSUE THREAD

**Issue by nijanthan0** [tesseract-ocr/tesseract#2375]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**: 

### Suggested Fix:

surasystem@surasystem:~$ tesseract/src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang tam --linedata_only --noextract_font_properties --exposures "0" --langdata_dir ~/tesseract/langdata/ --tessdata_dir ~/tesseract/tessdata/ --training_text ~/tesstutorial/langdata/ --output_dir /tessstutorial/tamtrain

=== Starting training for language 'tam'
[Fri Apr 5 16:09:24 IST 2019] /usr/local/bin/text2image --fonts_dir=/usr/share/fonts --font=TAMu_Kadambri --outputbase=/tmp/font_tmp.ZJZNQEafTc/sample_text.txt --text=/tmp/font_tmp.ZJZNQEafTc/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc
Rendered page 0 to file /tmp/font_tmp.ZJZNQEafTc/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using TAMu_Kadambri
[Fri Apr 5 16:09:31 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.TAMu_Kadambri.exp0 --max_pages=0 --font=TAMu_Kadambri --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
ERROR: /tmp/tam-2019-04-05.vFg/tam.TAMu_Kadambri.exp0.tif does not exist or is not readable
Rendering using TAMu_Kalyani
[Fri Apr 5 16:09:32 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.TAMu_Kalyani.exp0 --max_pages=0 --font=TAMu_Kalyani --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
ERROR: /tmp/tam-2019-04-05.vFg/tam.TAMu_Kalyani.exp0.tif does not exist or is not readable
Rendering using TAMu_Maduram
[Fri Apr 5 16:09:33 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.TAMu_Maduram.exp0 --max_pages=0 --font=TAMu_Maduram --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
ERROR: /tmp/tam-2019-04-05.vFg/tam.TAMu_Maduram.exp0.tif does not exist or is not readable
Rendering using TSCu_Paranar
[Fri Apr 5 16:09:34 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.TSCu_Paranar.exp0 --max_pages=0 --font=TSCu_Paranar --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'TSCu_Paranar'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using TSCu_Times
[Fri Apr 5 16:09:35 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.TSCu_Times.exp0 --max_pages=0 --font=TSCu_Times --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'TSCu_Times'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using TSCu_Paranar Bold
[Fri Apr 5 16:09:36 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.TSCu_Paranar_Bold.exp0 --max_pages=0 --font=TSCu_Paranar Bold --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'TSCu_Paranar Bold'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using FreeSans
[Fri Apr 5 16:09:37 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.FreeSans.exp0 --max_pages=0 --font=FreeSans --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
ERROR: /tmp/tam-2019-04-05.vFg/tam.FreeSans.exp0.tif does not exist or is not readable
Rendering using FreeSerif
[Fri Apr 5 16:09:38 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.FreeSerif.exp0 --max_pages=0 --font=FreeSerif --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
ERROR: /tmp/tam-2019-04-05.vFg/tam.FreeSerif.exp0.tif does not exist or is not readable
Rendering using Lohit Tamil
[Fri Apr 5 16:09:40 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Lohit_Tamil.exp0 --max_pages=0 --font=Lohit Tamil --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
ERROR: /tmp/tam-2019-04-05.vFg/tam.Lohit_Tamil.exp0.tif does not exist or is not readable
Rendering using Arial Unicode MS Bold
[Fri Apr 5 16:09:41 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Arial_Unicode_MS_Bold.exp0 --max_pages=0 --font=Arial Unicode MS Bold --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Arial Unicode MS Bold'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Ascender Uni
[Fri Apr 5 16:09:42 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Ascender_Uni.exp0 --max_pages=0 --font=Ascender Uni --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Ascender Uni'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Droid Sans Tamil Bold
[Fri Apr 5 16:09:43 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Droid_Sans_Tamil_Bold.exp0 --max_pages=0 --font=Droid Sans Tamil Bold --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Droid Sans Tamil Bold'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Droid Sans Tamil
[Fri Apr 5 16:09:44 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Droid_Sans_Tamil.exp0 --max_pages=0 --font=Droid Sans Tamil --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Droid Sans Tamil'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Karla Tamil Inclined Bold Italic
[Fri Apr 5 16:09:45 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Karla_Tamil_Inclined_Bold_Italic.exp0 --max_pages=0 --font=Karla Tamil Inclined Bold Italic --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Karla Tamil Inclined Bold Italic'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Karla Tamil Inclined Italic
[Fri Apr 5 16:09:46 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Karla_Tamil_Inclined_Italic.exp0 --max_pages=0 --font=Karla Tamil Inclined Italic --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Karla Tamil Inclined Italic'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Karla Tamil Upright Bold
[Fri Apr 5 16:09:47 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Karla_Tamil_Upright_Bold.exp0 --max_pages=0 --font=Karla Tamil Upright Bold --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Karla Tamil Upright Bold'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Karla Tamil Upright
[Fri Apr 5 16:09:48 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Karla_Tamil_Upright.exp0 --max_pages=0 --font=Karla Tamil Upright --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Karla Tamil Upright'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Noto Sans Tamil Bold
[Fri Apr 5 16:09:49 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Noto_Sans_Tamil_Bold.exp0 --max_pages=0 --font=Noto Sans Tamil Bold --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Noto Sans Tamil Bold'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Noto Sans Tamil
[Fri Apr 5 16:09:50 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Noto_Sans_Tamil.exp0 --max_pages=0 --font=Noto Sans Tamil --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Noto Sans Tamil'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Noto Sans Tamil UI Bold
[Fri Apr 5 16:09:51 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Noto_Sans_Tamil_UI_Bold.exp0 --max_pages=0 --font=Noto Sans Tamil UI Bold --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Noto Sans Tamil UI Bold'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Noto Sans Tamil UI
[Fri Apr 5 16:09:52 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Noto_Sans_Tamil_UI.exp0 --max_pages=0 --font=Noto Sans Tamil UI --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Noto Sans Tamil UI'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using TSCu_Comic Normal
[Fri Apr 5 16:09:53 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.TSCu_Comic_Normal.exp0 --max_pages=0 --font=TSCu_Comic Normal --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'TSCu_Comic Normal'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
Rendering using Lohit Tamil Classical
[Fri Apr 5 16:09:54 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.ZJZNQEafTc --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tam-2019-04-05.vFg/tam.Lohit_Tamil_Classical.exp0 --max_pages=0 --font=Lohit Tamil Classical --text=/home/surasystem/tesstutorial/langdata/ --char_spacing=0.5
Could not find font named 'Lohit Tamil Classical'.
Pango suggested font 'FreeMono'.
Please correct --font arg.
ERROR: /tmp/tam-2019-04-05.vFg/tam.TAMu_Kadambri.exp0.tif does not exist or is not readable

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
