### ISSUE TITLE
[MacOS] mojave 10.14.4 training tools can't be build.(text2image stopped)

### ISSUE THREAD

**Issue by luvwinnie** [tesseract-ocr/tesseract#2377]
I have ran 
<pre>
brew install automake autoconf autoconf-archive libtool
brew install pkgconfig
brew install icu4c
brew install leptonica
brew install gcc
brew install pango
brew install cairo

PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig
./autogen.sh
./configure CC=gcc-8 CXX=g++-8 CPPFLAGS=-I/usr/local/opt/icu4c/include LDFLAGS=-L/usr/local/opt/icu4c/lib
make -j 4
make training
</pre>
Text2Image can't be compile which keep shows libpng16.la not found.
<pre>
Tesseract version: 4.10-rc1
platform:
Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin
</pre>
CurrentBehavior:
<pre>
libtool:   error: cannot find the library '/Users/username/.conda/envs/tensorflow-env/lib/libpng16.la' or unhandled argument '/Users/username/.conda/envs/tensorflow-env/lib/libpng16.la'
make[1]: *** [Makefile:923: text2image] Error 1
make[1]: Leaving directory '/Users/username/tesseract/src/training'
make: *** [Makefile:924: training] Error 2
</pre>

I don't know why it keep searching for my anaconda environment libpng16.la which compile with source.

libpng16.la -> /Users/username/libpng-1.6.36/libpng16.la

it stopped at 
how can I fixed this?

**Comment by zdenop** [comment]
This is not tesseract bug, but setting of your (system) environment.  We can do nothing with it.
If you want to compile ANY sw from source you need to be familiar with your OS and YOUR setting.
