### ISSUE TITLE
Expression: ("Invalid file open mode", 0) debug assert is occured in Visual Studio 2015

### ISSUE THREAD

**Issue by prodeveloper0** [tesseract-ocr/tesseract#2380]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment
* **Tesseract Version**: 4.1.0

* **Commit Number**: 332a1a9

* **Platform**:
Windows 10 Pro Build 1809 x64
Microsoft Visual Studio 2015
leptonica-1.74.4
CMake 3.14.0
Build target is VC14 x86

### Current Behavior:
```cpp
static tesseract::TessBaseAPI tess;
tess.Init("C:\tessdata", "eng");
```
in debug mode

### Expected Behavior:
returning zeo if success

but when Init is called, debug assert is occured

![1](https://user-images.githubusercontent.com/7126311/55692407-a8bdc200-59e2-11e9-9bbe-2843e1bcd21e.PNG)

### Suggested Fix:
Change file mode `"rbe"` to `"rb"`.
https://github.com/tesseract-ocr/tesseract/blob/332a1a980970b71bff1d97058c5ae926318492a3/src/ccutil/genericvector.h#L377

Also change `"wbe"` to `"wb"`.
https://github.com/tesseract-ocr/tesseract/blob/332a1a980970b71bff1d97058c5ae926318492a3/src/ccutil/genericvector.h#L403

msvc14 may not support file mode `e`.
but, No error is occured in release mode.

**Comment by Shreeshrii** [comment]
Fixed via https://github.com/tesseract-ocr/tesseract/pull/2383

**Comment by stweil** [comment]
See also commit 12ca2513d41b425f1b325dc12c6d2d2e2b5d67f9.
