### ISSUE TITLE
chi_tra fails to recognize clean image

### ISSUE THREAD

**Issue by aaronshieh** [tesseract-ocr/tesseract#2381]
### Environment

* **Tesseract Version**: 4.0.0.20190314
* **Platform**: Windows 10 64-bit

### Current Behavior: 
tesseract fails to recognize text in clean image: https://i.imgur.com/sR9CkNk.png
I tried --oem 1 and --psm 1 through 13, all with no luck, except for psm 5 which gives result in reverse "宜家王"

### Expected Behavior: 
the output I am expecting:
"王家宜"

**Comment by Shreeshrii** [comment]
Works fine, except for tessdata_fast and --psm3.


tesseract 4.1.0-rc1-250-g95a1
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0

 *****  ./2381.png LANG chi_tra TESSDATA tessdata OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 484
王 家 定

 *****  ./2381.png LANG chi_tra TESSDATA tessdata OEM 1 PSM 4 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 484
王 家 定

 *****  ./2381.png LANG chi_tra TESSDATA tessdata OEM 1 PSM 5 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
砸
煲
山

 *****  ./2381.png LANG chi_tra TESSDATA tessdata OEM 1 PSM 6 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
王 家 定

 *****  ./2381.png LANG chi_tra TESSDATA tessdata_fast OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 484
Empty page!!
Estimating resolution as 484
Empty page!!

 *****  ./2381.png LANG chi_tra TESSDATA tessdata_fast OEM 1 PSM 4 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 484
王家宣

 *****  ./2381.png LANG chi_tra TESSDATA tessdata_fast OEM 1 PSM 5 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
個
以
出

 *****  ./2381.png LANG chi_tra TESSDATA tessdata_fast OEM 1 PSM 6 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
王家宣

 *****  ./2381.png LANG chi_tra TESSDATA tessdata_best OEM 1 PSM 3 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 484
王家 宣

 *****  ./2381.png LANG chi_tra TESSDATA tessdata_best OEM 1 PSM 4 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 484
王家 宣

 *****  ./2381.png LANG chi_tra TESSDATA tessdata_best OEM 1 PSM 5 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
宜
家
王

 *****  ./2381.png LANG chi_tra TESSDATA tessdata_best OEM 1 PSM 6 ****
Warning: Invalid resolution 0 dpi. Using 70 instead.
王家 宣

**Comment by aaronshieh** [comment]
Thanks for the reply, could you point me to the "chi_tra" model file you are using?

**Comment by Shreeshrii** [comment]
I have used them from the three repos tessdata, tessdata_fast and tessdata_best:

https://github.com/tesseract-ocr/tessdata_best
https://github.com/tesseract-ocr/tessdata_fast
https://github.com/tesseract-ocr/tessdata

The traineddata files provided by linux distributions is from tessdata_fast. See https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400-september-15-2017

**Comment by aaronshieh** [comment]
Ok I tried using the models from link you provided, and I'm still not getting the same results as you. Could it be my version of Tesseract and/or Windows build? I'm using the UB Mannheim build.

**Comment by Shreeshrii** [comment]
I am using the latest code from github. The windows build might be older.

@stweil Any chance of updating the binaries with the new changes?

**Comment by Shreeshrii** [comment]
>Experts can also get binaries build with Visual Studio from the build artifacts of the Appveyor Continuous Integration.

https://ci.appveyor.com/project/zdenop/tesseract/history

**Comment by stweil** [comment]
Which recent changes are needed? I made the [latest binaries](https://digi.bib.uni-mannheim.de/tesseract/?C=M;O=A) on 2019-03-14 and 2019-03-17. Is that too old?

**Comment by Shreeshrii** [comment]
>Tesseract Version: 4.0.0.20190314
>Platform: Windows 10 64-bit

These are the ones from the original issue report. Could there be a difference between the 32 bit and 64 bit versions?

**Comment by stweil** [comment]
In theory there could be a difference between 32 bit and 64 bit Tesseract, but in practice I know none.

**Comment by Shreeshrii** [comment]
OK. I downloaded the 64 bit program for a test. On the console I do not see correct output - I guess it is a locale issue. I tried with different `chcp` settings.

```
C:\Program Files\Tesseract-OCR>chcp 1253
Active code page: 1253

C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png - -l chi_tra --dpi 300 --psm 6
η‹ε®¶ε®£

C:\Program Files\Tesseract-OCR>chcp 50229
Active code page: 50229

C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png - -l chi_tra --dpi 300 --psm 6
çŽ‹å®¶å®£

C:\Program Files\Tesseract-OCR>chcp 850
Active code page: 850

C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png - -l chi_tra --dpi 300 --psm 6
þÄïÕ«ÂÕ«ú

C:\Program Files\Tesseract-OCR>chcp 65001
Active code page: 65001

C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png - -l chi_tra --dpi 300 --psm 6
Error during processing.

```
 But saving as a file and opening in notepad++ works.

**Comment by Shreeshrii** [comment]
So, the actual issues from this report are:

1. For a small image such as this, psms 0-3 give output of empty page with tessdata_fast.

```
C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png -
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 484
Empty page!!
Estimating resolution as 484
Empty page!!

C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png - -l chi_tra
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 484
Empty page!!
Estimating resolution as 484
Empty page!!

C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png - -l chi_tra --dpi 300
Empty page!!
Empty page!!

C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png - -l chi_tra --dpi 300 --psm 0
Warning, detects only orientation with -l chi_tra
Too few characters. Skipping this page
Warning. Invalid resolution 0 dpi. Using 70 instead.
Too few characters. Skipping this page
Error during processing.

C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png - -l chi_tra --dpi 300 --psm 1
Too few characters. Skipping this page
OSD: Weak margin (0.00) for 3 blob text block, but using orientation anyway: 0
Empty page!!
Too few characters. Skipping this page
OSD: Weak margin (0.00) for 3 blob text block, but using orientation anyway: 0
Empty page!!

C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png - -l chi_tra --dpi 300 --psm 2
Empty page!!

C:\Program Files\Tesseract-OCR>tesseract.exe 2381.png - -l chi_tra --dpi 300 --psm 3
Empty page!!
Empty page!!
```

2. The output with --psm 5 for vertical text is reversed bottom to top (image is horizontal, so not sure if this is really an issue with vertical text).

```
個
以
出
```

**Comment by aaronshieh** [comment]
The issue seems to be the chi_tra_vert.traindata that I'm using, the one I was using previously was around 2 MB, the one that seems to work best is around 12 MB. 

The last character is still wrongly recognized, but at least my results are similar to yours now. 

Another thing I noticed is that I installed the tesseract-ocr-w64-setup-v4.1.0.20190314 (rc1) (64 bit) resp. from UB Mannheim, but tesseract -v shows v4.0.0.20190314.

**Comment by Shreeshrii** [comment]
>The issue seems to be the chi_tra_vert.traindata that I'm using, the one I was using previously was around 2 MB, the one that seems to work best is around 12 MB.

chi_tra_vert.traindata is used as a sub language in chi_tra.traineddata. The smaller file maybe from tessdata_fast.

One more reason for checking traineddata file versions - related issue https://github.com/tesseract-ocr/tesseract/issues/293

**Comment by aaronshieh** [comment]
Thanks, I guess this issue can be closed.
