### ISSUE TITLE
Tesseract preprocessing -- Performance and Speed

### ISSUE THREAD

**Issue by Peritos09** [tesseract-ocr/tesseract#2386]
Hey community,
i use tesseract for Text extraction but the i find it slow, so i have some questions to find out where can i contribute to make it faster :

- Did Tesseract process some Image traitement and preprocessing/cleanup at the start (need of Leptonica )? if it is the case what are those traitements? how much time do you think they consume ? and how could we disable them ?
- Is Tesseract convert all the image to tiff then process them ?
- Which part of Tesseract is the much time consuming ? and what are functions that you think we can remove or disable to make it faster ?
-  I find this article which propose some parallelisation in some functions to speed it up **[Performance Characterization and Parallelization of Tesseract Optical Character
Recognition on Multicore Architectures](https://pdfs.semanticscholar.org/dab1/23de2a9c25eaeaf7b6456116cea1e509f3f7.pdf)**, is it implemented ?

Thanks

**Comment by adfindlater** [comment]
These are the only omp pragmas in the code (at least that grep found for me):

`➜  tesseract-ocr git:(master) grep -r 'pragma omp' *
src/lstm/fullyconnected.cpp:#pragma omp parallel for num_threads(kNumThreads)
src/lstm/fullyconnected.cpp:#pragma omp parallel for num_threads(kNumThreads)
src/lstm/parallel.cpp:#pragma omp parallel for num_threads(stack_size)
src/lstm/parallel.cpp:#pragma omp parallel for num_threads(stack_size)
src/lstm/lstm.cpp:#pragma omp parallel for num_threads(GFS) if (!Is2D())
src/lstm/weightmatrix.cpp:#pragma omp parallel for num_threads(4) if (in_parallel)
src/ccmain/par_control.cpp:#pragma omp parallel for num_threads(10)
`

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
And search tesseract user forum and issue tracker for more details.

**Comment by Peritos09** [comment]
Link for the forum

**Comment by zdenop** [comment]
3rd item in [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ)
