### ISSUE TITLE
Issue using tesseract

### ISSUE THREAD

**Issue by enjoykcc** [tesseract-ocr/tesseract#2387]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by enjoykcc** [comment]
Hello,

Currently i am facing some issue whereby my scripts will run tesseract (with thread) on the video frame every 6 secs to extract the information on the video frame. 
But, everytime when the video almost ends, the process will slow down significantly and all the cpu cores usage will suddenly spike to 100%. Then, there will be processes
produced (as shown in the attached picture) and a lot of xxx.png and xxx_out.txt produced in the /tmp directory. Does anyone ever face this issue? Hope to hear from you guys soon.

Tesseract version: 4.1.0-rc1-95-g3baf
leptonica-1.76.0

![Screenshot from 2019-04-12 14-44-31](https://user-images.githubusercontent.com/39821546/56075874-e87a1480-5dfb-11e9-80c7-77d26a2ef0d4.png)


Thanks in advance and have a nice day.

Regards,
Gordon

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. Use tesseract user forum.
