### ISSUE TITLE
Reading a 8inches by 11 inches document is too slow

### ISSUE THREAD

**Issue by ychtioui** [tesseract-ocr/tesseract#239]
I have an image with barely 20 lines of text (I have the image that I can provide), and it's taking seconds and seconds to read the text.
I'm using VS2010.
I provided the binary image (very clean) to Tesseract. Tesseract works fine but it's too too slow.

I'm impressed by the accuracy of Tesseract, but the speed is a disaster!
I used other commercial OCR engines: accuracy less but speed much faster.

how to improve the speed of tesseract? anyway to read an image in few 100s of milliseconds.

thanks

**Comment by amitdo** [comment]
The right place to asking questions is:
https://groups.google.com/d/forum/tesseract-ocr

**Comment by ychtioui** [comment]
I posted my message on the google groups,
