### ISSUE TITLE
Tesseract min and max macro

### ISSUE THREAD

**Issue by Bleach665** [tesseract-ocr/tesseract#2390]
Windows 10 x64, CMake 3.14, VS 2017, Tesseract rev 332a1a980970b71bff1d97058c5ae926318492a3.
Tesseract redefine min and mac macro, therefore after including baseapi.h we receive errors like

````
1>e:\0_localwork\improcqcv\improcqcv\imgcoreqcv.cpp(581): error C2589: '(': illegal token on right side of '::'
1>e:\0_localwork\improcqcv\improcqcv\imgcoreqcv.cpp(581): error C2062: type 'unknown-type' unexpected
1>e:\0_localwork\improcqcv\improcqcv\imgcoreqcv.cpp(581): error C2059: syntax error: ')'
1>e:\0_localwork\improcqcv\improcqcv\imgcoreqcv.cpp(582): warning C4003: not enough arguments for function-like macro invocation 'max'
1>e:\0_localwork\improcqcv\improcqcv\imgcoreqcv.cpp(582): error C2589: '(': illegal token on right side of '::'
1>e:\0_localwork\improcqcv\improcqcv\imgcoreqcv.cpp(582): error C2062: type 'unknown-type' unexpected
1>e:\0_localwork\improcqcv\improcqcv\imgcoreqcv.cpp(582): error C2059: syntax error: ')'
````

when we use default std min and max macro. 
Also this errors received when other lib (opencv) was build with Tesseract.
Adding 
````
#undef min
#undef max
````
to the end of baseapi.h fix it.
Create appropriate pull request?

**Comment by stweil** [comment]
It's not Tesseract, but the Windows header files which define `min` and `max` macros. We have to fix the public Tesseract headers to avoid including `windows.h`.

**Comment by zdenop** [comment]
@Bleach665: Errors comes from your code... Can you provide us test code that demonstrate this problem?

**Comment by Bleach665** [comment]
@zdenop. Just try to use std min or max macro after tesseract/baseapi.h.
`std::min(2, 3);`

**Comment by Bleach665** [comment]
@zdenop. Just try to use std min or max after include tesseract/baseapi.h

**Comment by zdenop** [comment]
try to add `#include <tesseract/host.h>` after `#include <tesseract/baseapi.h>`

**Comment by stweil** [comment]
That might work because `host.h` undefines both macros, but I consider that a hack.

**Comment by zdenop** [comment]
Well `host.h` is part tesseract installed header files and I guess its purpose is to fix (or hack) platform specific problems...

**Comment by Bleach665** [comment]
@zdenop.
`#include <tesseract/host.h>`
resolve this bug.

**Comment by stweil** [comment]
Pull request #2401 removes one of the include statements for `windows.h` in the public API.

The last `windows.h` is in `host.h`. As that file is not referenced elsewhere, I suggest to remove it from the public API.

In addition, `platform.h` should be reduced to the minimum required for the public API. All other definitions can be moved from `platform.h` to `host.h`.

**Comment by zdenop** [comment]
thank Stefan.
