### ISSUE TITLE
Build error when run  ./autogen.sh 

### ISSUE THREAD

**Issue by milinlin** [tesseract-ocr/tesseract#2392]
Running aclocal
configure.ac:544: warning: macro `AM_COND_IF' not found in library
configure.ac:558: warning: macro `AM_COND_IF' not found in library
Running libtoolize
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
Running autoheader
Running automake --add-missing --copy
configure.ac:69: installing `config/missing'
api/Makefile.am: installing `config/depcomp'
Running autoconf
configure.ac:521: error: possibly undefined macro: AC_CONFIG_FILES
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:546: error: possibly undefined macro: AM_COND_IF

  Something went wrong, bailing out!

-----------
GCC 4.8.5

------------------------

### Environment

* **3.04**: 
* **Commit Number**: 
* **suse 11 SP4 64-bit**:

**Comment by stweil** [comment]
Your autotools are too old. Which versions of autoconf / automake do you use?

**Comment by zdenop** [comment]
And tesseract 3.04 version is also old. Please use recent tools.
