### ISSUE TITLE
TESSDATA_PREFIX

### ISSUE THREAD

**Issue by nathan30** [tesseract-ocr/tesseract#2393]
### Environment

* **Tesseract Version**: 4.0.0
* **Platform**: Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

### Current Behavior:
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file ./fra.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'fra\' Tesseract couln\'t load any languages! Could not initialize tesseract.')

Reading the wiki I found this command : 

export TESSDATA_PREFIX=/usr/share/tesseract-ocr/

but It's not working at all. I tried to add it to PATH, into ~/.profile file but not working :/ 

Any ideas ? 

Thanks in advance

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.
