### ISSUE TITLE
Libraries for Windows

### ISSUE THREAD

**Issue by albertgarcias** [tesseract-ocr/tesseract#240]
I've tried to compile the main vs2010 project and even with x32 it doesn't work. requires 
allheaders.h file. 
Error	2	error C1083: Cannot open include file: 'allheaders.h': No such file or directory	

If I'm not wrong this file is a leptonica file, but leptonica is not provided in the solution. Why is this dependency still needed to compile only tesseract libraries?

**Comment by amitdo** [comment]
The right place for asking questions is:
https://groups.google.com/d/forum/tesseract-ocr

**Comment by albertgarcias** [comment]
Tnx, I will edit the issue so it only have the issue.

**Comment by zdenop** [comment]
Tesseract does not work without leptonica.
