### ISSUE TITLE
Vowel "o" replaced by ordinal indicators "o".

### ISSUE THREAD

**Issue by chinicuin** [tesseract-ocr/tesseract#2405]
### Environment

* **Tesseract Version**: 4.0.0 Release, language spanish (leptonica-1.74.4, libjpeg-turbo 1.4.2, libpng 1.2.54, libtiff 4.0.6, zlib 1.2.8).
* **Commit Number**: 51316994ccae0b48692d547030f26c0969308214
* **Platform**: ubuntu 16.04 LTS

### Current Behavior:
All the vowels "o" are translated as the ordinal indicator "º" similar to what's mentioned in this bug report https://github.com/tesseract-ocr/tesseract/issues/1084 (now closed)

### Expected Behavior:
All vowels "o" as is.

### Suggested Fix:
This happens when I use version 4.0.0-Release, if I use version 4.0.0-alpha the document is translated correctly. The thing is: I want to update to 4.0.0 stable release to mitigate possible problems.
This is the original text (pdf to jpg using imagemagik):
![texto-original](https://user-images.githubusercontent.com/7343225/56611771-4666e300-65d8-11e9-87cb-d6d0c099ee0d.jpg)

This is the resulting text using version 4.0.0-alpha:
[texto-alpha.txt](https://github.com/tesseract-ocr/tesseract/files/3109353/texto-alpha.txt)

This is the resulting text using version 4.0.0-release:
[texto-release.txt](https://github.com/tesseract-ocr/tesseract/files/3109359/texto-release.txt)

Thank you in advance.

**Comment by zdenop** [comment]
Which language data you used?

**Comment by chinicuin** [comment]
Sorry I forgot to mention.
For version alpha I used the spanish data file (spa.traineddata) located here https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-400-november-29-2016

And for version release I used the spanish data file (spa.traineddata) located here https://github.com/tesseract-ocr/tessdata

**Comment by zdenop** [comment]
Try this data: https://github.com/tesseract-ocr/tessdata_best

**Comment by chinicuin** [comment]
Thanks a lot. The recommended data file solved the problem.

**Comment by rjgarciar** [comment]
I have the same problem with "o" vowel. 

I'm using 5.0.0 in windows, and tried with 

- https://github.com/tesseract-ocr/tessdata
- https://github.com/tesseract-ocr/tessdata_best
- https://github.com/tesseract-ocr/tessdata_fast

with no difference.
