### ISSUE TITLE
Error Compiling :  fopenmp  ./.libs/libtesseract.so -llept -lrt -lpthread -fopenmp

### ISSUE THREAD

**Issue by ghsama** [tesseract-ocr/tesseract#2406]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Hey,
I'm trying to compile tesseract, i get a bug in the MAKE stage.

### Environment

* **Tesseract Version**: 4.00
* **Commit Number**: 
* **Platform**:  Ubuntu 18.04 

### Current Behavior:
Here is the start of the bug, you can find it all in the [Pastbin](https://pastebin.com/ptnuJAEV) : 
`
li.libs/libtesseract.lax/libtesseract_sse.a/libtesseract_sse_la-dotproductsse.o .libs/libtesseract.lax/libtesseract_sse.a/libtesseract_sse_la-intsimdmatrixsse.o 
ar: 'u' modifier ignored since 'D' is the default (see 'U')
libtool: link: ranlib .libs/libtesseract.a
libtool: link: rm -fr .libs/libtesseract.lax
libtool: link: ( cd ".libs" && rm -f "libtesseract.la" && ln -s "../libtesseract.la" "libtesseract.la" )
`

### Log :
I run configuration with the following parameters to get the conf log :
./configure --prefix=/usr/local | tee configure.log

Here is the ***LOG*** in a [Pastbin](https://pastebin.com/nF0q1ZfN)

`

**Comment by zdenop** [comment]
there is no error just warning. What is problem?

**Comment by ghsama** [comment]
After the install and When i launch tesseract i get the error : 
`
tesseract: error while loading shared libraries: libtesseract.so.5: cannot open shared object file: No such file or directory
`

**Comment by zdenop** [comment]
So where is log if your installing process?

**Comment by ghsama** [comment]
Here is the installing process in the [Pastbin](https://pastebin.com/LCLe6vfz)
and Here is the config.log : [Pastbin](https://pastebin.com/nZBJqU1p)

**Comment by ghsama** [comment]
I resolve the problem by running after the install :
`
sudo ldconfig
`
