### ISSUE TITLE
Error:Assert failed:in file ../../../../ccmain/tessedit.cpp, line 193

### ISSUE THREAD

**Issue by indramal** [tesseract-ocr/tesseract#2410]
I try to get output from text image using the following command.

`tesseract ocrsi1.jpg 'text1' -l eng`

I get perfect output. But I tried the following code with Sinhalese but I did not get output.

`tesseract ocrsi2.jpg 'text2' -l sin`

Error Message:

`lstm_recognizer_->DeSerialize(&fp):Error:Assert failed:in file ../../../../ccmain/tessedit.cpp, line 193`

How to solve this error? 

I am using new v4 with python 3.6. 

I also download tessdata and langdata and put into tesseract installed folder. 

This is ocrsi2.jpg image file.

![ocrsi2](https://user-images.githubusercontent.com/28696256/56846929-bdf78380-68f2-11e9-84d8-7de4fcf0d78e.jpg)

How to solve this error? I tried other languages also but I get the same error.

**Comment by Shreeshrii** [comment]
ubuntu@tesseract-ocr:~/TEST$ tesseract sinhala.jpg - -l sin --oem 1 --psm 6
සිංහල
ubuntu@tesseract-ocr:~/TEST$ tesseract sinhala.jpg - -l sin --oem 1 --psm 3
සිංහල
ubuntu@tesseract-ocr:~/TEST$ tesseract sinhala.jpg - -l sin --oem 1 --psm 4
සිංහල
ubuntu@tesseract-ocr:~/TEST$ tesseract sinhala.jpg - -l sin --oem 1 10
read_params_file: Can't open 10
සිංහල
ubuntu@tesseract-ocr:~/TEST$

**Comment by Shreeshrii** [comment]
> I tried other languages also but I get the same error.

What is the output of?

`tesseract --list-langs`

**Comment by zdenop** [comment]
Closing as issue can not be reproduced.

**Comment by UBISOFT-1** [comment]
I have the same Issue here so, you should not close this

**Comment by stweil** [comment]
To anyone getting this error: Please check that you use a supported version of Tesseract (4.1.1 or newer).

**Comment by stweil** [comment]
See also issues #1680.
