### ISSUE TITLE
Tesseract 4 skipping lines

### ISSUE THREAD

**Issue by TheSeiko** [tesseract-ocr/tesseract#2412]
### Environment

* **Tesseract Version**: 
tesseract v4.0.0.20190314
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.2.0
 Found AVX2
 Found AVX
 Found SSE
---
happens also in older versions
* **Commit Number**: 
UB Mannheim: tesseract-ocr-w64-setup-v4.1.0.20190314 (rc1) (64 bit) resp
* **Platform**: 
Windows 7 64bit
Windows 10 64bit
latest update for both

### Current Behavior:
lines are skipped

<img width="768" alt="output_2019-04-29_104651" src="https://user-images.githubusercontent.com/30631253/56885248-49485480-6a6c-11e9-999c-3f4531d0e230.png">
![20190429101946273_1550929792281_bottom](https://user-images.githubusercontent.com/30631253/56885260-51a08f80-6a6c-11e9-869c-2095810b1b09.png)

### Expected Behavior:
lines are not skipped

### Additional question:
Is there a way that I can analyze the output by myself?

**Comment by TheSeiko** [comment]
![20190429101946273_1550929792281_bottom](https://user-images.githubusercontent.com/30631253/56885554-fde27600-6a6c-11e9-8b6e-7bc073f40224.png)

Reload input image

**Comment by Shreeshrii** [comment]
What psm did you use?

**Comment by TheSeiko** [comment]
Used the standard page segmention mode, which is normally working for all the other frames.
The tesseract call can be seen in the output screenshot.

**Comment by TheSeiko** [comment]
Did some testing:
psm 6/12/13: shows all text
psm 7/9: shows only the skipped line
alls other psm are skipping the line or doing charcater output

**Comment by behel33** [comment]
I had same problems (tessseract v4. It  skip lines (here facture)
![facture-n](https://user-images.githubusercontent.com/22028124/56898701-ff726500-6a91-11e9-9aaf-6e87a6139369.png)
Image is a cut of my fature (300dpi).
What can Id do to avoid this ?
I had try with : 
tesseract 4.1.0-rc1-3-g24a8
```
 leptonica-1.76.0 (Nov 24 2018, 21:28:43) [MSC v.1900 LIB Release x64]
  libgif 5.1.4 : libjpeg 9b : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE
```
and width 👍 
```
tesseract 4.1.0-rc1-3-g24a8
 leptonica-1.76.0 (Nov 24 2018, 21:28:43) [MSC v.1900 LIB Release x64]
  libgif 5.1.4 : libjpeg 9b : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE
```
exemple on cmd :
tesseract.exe facture-n.png TEXT  --psm 3 --oem 1 TXT

**Comment by zdenop** [comment]
@TheSeiko: default psm expect page (A4) where can be present graphics, which is skipped. Using correct psm (e.g. 6) is solving you issue:
```
>tesseract i2412.png - --dpi 400 --psm 6 -l deu
Gedenken
Die Lawinen-Katastrophe von Galtür jährt
sich zum 20. Mal.
```
Using wrong psm leads to problems. So solution for this issue is: use correct tesseract parameters.

PS: I doubt your image has 70 dpi ;-)
