### ISSUE TITLE
Some recognition is botched in German.

### ISSUE THREAD

**Issue by oltodosel** [tesseract-ocr/tesseract#2417]
### Environment

* **Tesseract Version**: tesseract 4.0.0
* **Platform**: Linux 5.0.9-arch1-1-ARCH x86_64 GNU/Linux
* **Language**: tesseract-data-deu 4.0.0

![z](https://user-images.githubusercontent.com/10230453/57010225-513afc80-6c04-11e9-91da-33007c496af4.png)

### Result:
El e ST
DE T UE

**Comment by zdenop** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality#inverting-images
