### ISSUE TITLE
Unwanted extra paragraph breaks in pdf output

### ISSUE THREAD

**Issue by zbgns** [tesseract-ocr/tesseract#2426]
### Environment

* **Tesseract Version**:
```
tesseract 4.0.0-beta.1
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
```
* **Platform**: 
Ubuntu 18.04
### Current Behavior:
In case of pdf files created by Tesseract I found that Moon+ Reader Pro Android App is able to visualize them in two modes:
1.  'graphic' where raster image layer is visible or
2. plain text originating from text layer.
In the latter mode the app reflows the text but tries to preserve the structure and divides block of text into paragraphs. It usually works fine, however form time to time there are additional unwanted paragraph breaks. It look like this:
![Screenshot_20190509-012210_Moon+ Reader Pro](https://user-images.githubusercontent.com/24705368/57415907-38cb7300-71fe-11e9-8a6c-afd1583fd455.jpg)
There are 4 places where unwanted 'paragraph breaks' were inserted. For comparison below is scanned image in the 'graphic' mode.
![Screenshot_20190509-012217_Moon+ Reader Pro](https://user-images.githubusercontent.com/24705368/57415908-3b2dcd00-71fe-11e9-80ee-1214051f70a4.jpg)
I'm aware that pdf file doesn't contain direct information on structure of the text, so there must be some heuristic method that allow to recreate paragraphs. Nevertheless it apparently uses data included in the input pdf file. Thus the question is whether these extra breaks are result of any incorrect work of Tesseract or everything with pdf output is fine and the issue is fully Moon+ Reader Pro related.
I need to add, that it has probably nothing to do with psm mode. I tried options 1, 3, 4 and 6 and it looks the same in any case.
I attach input tiff file
[09.tif.zip](https://github.com/tesseract-ocr/tesseract/files/3159764/09.tif.zip)
 and output pdf created by:
`tesseract -l pol --psm 1 09.tif psm1 pdf`
[psm1.pdf](https://github.com/tesseract-ocr/tesseract/files/3159759/psm1.pdf)

  
### Expected Behavior:
Text included in pdf files created by Tesseract is correctly divided into paragraphs in reflow mode.

**Comment by zdenop** [comment]
This is not tesseract bug. If you open pdf in firefox, chrome or acrobat read, you will see that tesseract place words above words in image:
![image](https://user-images.githubusercontent.com/574156/57432634-ad220880-7236-11e9-86c5-3f6c1e91e089.png)

Also if you do copy&paste from psm1.pdf you will get this output:
```
karnie, stanowiące ośrodki propagandowe nowej
wiary. Przerażony tym, co zastał, nuncjusz papieski,
Alojzy Lippomano, radził w roku 1555
Zygmuntowi Augustowi, aby ściął ośmiu do
dziesięciu wybitniejszych „heretyków”, a powstrzyma
szerzenie się reformacji.
Ale przybyły z dalekich Włoch legat nie zdawał
sobie sprawy, iż rada ta w polskich warunkach
nie na wiele się przyda, a może za sobą
pociągnąć jedynie krwawe zaburzenia w całym
raństwie. Nie bardzo się zresztą kwapił łagodhy
król, z powodu znanej skłonności do odwlekania
decyzji „dojutrkiem” zwany, do jej realizacji.
Tym ogniem reformacji (jak się zresztą później
okazało, słomianym raczej niż prawdziwym)
nie zapłonęła ani na chwilę jedna tylko dzielnica,
mianowicie Mazowsże. Nie powstał tu żaden
zbór „heretycki”, a zwolennicy protestantyzmu
z wielkim tylko trudem przenikali do
Warszawy, która za pomocą różnych ustaw starała
się jeśli nie pozbyć zwolenników Lutra, to
przynajmniej obrzydzić im życie.
Tę odporność Mazowsza na wpływy reforma-
```
So the tesseract output represent input image faithfully.

**Comment by zbgns** [comment]
I do not question this. However, it depends on a pdf viewer used for copy&paste. It works as presented in case of Adobe software (hyphenated words are joined, by the way). However, it looks definitely worse in case on programs based on poppler, e.g. Evince. Especially, output of pdftotxt looks messy. The characteristic thing is that those additional breaks are in random places. I do not see any pattern here. Thus I suspect that it may have something to do with the internal structure of pdf files created by Tesseract.

**Comment by zdenop** [comment]
Please stop with this "suspects". Here is output from `pdftotext` (poppler - pdftotext version 4.00, windows version) and you can see  that it can correctly identify paragraph breaks:

```
karnie, stanowice orodki propagandowe nowej wiary. Przeraony tym, co zastal, nuncjusz papieski, Alojzy Lippomano, radzil w roku 1555 Zygmuntowi Augustowi, aby cil omiu do dziesiciu wybitniejszych ,,heretyków", a powstrzyma szerzenie si reformacji.
Ale przybyly z dalekich Wloch legat nie zdawal sobie sprawy, i rada ta w polskich warunkach nie na wiele si przyda, a moe za sob pocign jedynie krwawe zaburzenia w calym rastwie. Nie bardzo si zreszt kwapil lagodhy król, z powodu znanej sklonnoci do odwlekania decyzji ,,dojutrkiem" zwany, do jej realizacji.
Tym ogniem reformacji (jak si zreszt póniej okazalo, slomianym raczej ni prawdziwym) nie zaplonla ani na chwil jedna tylko dzielnica, mianowicie Mazowse. Nie powstal tu aden zbór ,,heretycki", a zwolennicy protestantyzmu z wielkim tylko trudem przenikali do Warszawy, która za pomoc rónych ustaw starala si jeli nie pozby zwolenników Lutra, to przynajmniej obrzydzi im ycie.
T odporno Mazowsza na wplywy reforma-
9

```

**Comment by zbgns** [comment]
My appologies. I did not ment to offend anyone.
Where this the poppler - pdftotext version 4.00 is available from? I checked in the repository poppler and apparently there is nothing like this available.
I also used the windows version of  pdftotext (from poppler 0.68) and the output is deffinitelly worse. I have the same effect under linux. Maybe the version is too old. I will check it later on.

`D:\>C:\Temp\poppler-0.68.0\bin\pdftotext.exe psm1.pdf psm1.txt`

```
karnie, stanowiące ośrodki propagandowe nowej
wiary. Przerażony tym, co zastał, nuncjusz pa-

pieski, Alojzy Lippomano, radził w roku 1555
Zygmuntowi

dziesięciu

Augustowi,

wybitniejszych

aby

ściął

ośmiu do

„heretyków”, a po-

wstrzyma szerzenie się reformacji.

Ale przybyły z dalekich Włoch legat nie zdawał sobie sprawy, iż rada ta w polskich warunkach nie na wiele się przyda, a może za sobą

pociągnąć jedynie krwawe zaburzenia w całym
raństwie. Nie bardzo się zresztą kwapił łagod-

hy król, z powodu znanej skłonności do odwlekania decyzji „dojutrkiem” zwany, do jej realizacji.

Tym ogniem reformacji (jak się zresztą później okazało, słomianym raczej niż prawdziwym)
nie zapłonęła ani na chwilę jedna tylko dzielnica, mianowicie Mazowsże. Nie powstał tu ża-

den zbór „heretycki”, a zwolennicy protestantyzmu z wielkim tylko trudem
przenikali do
Warszawy, która za pomocą różnych ustaw sta-

rała się jeśli nie pozbyć zwolenników Lutra, to
przynajmniej obrzydzić im życie.
Tę odporność Mazowsza na wpływy reforma9
```

**Comment by zdenop** [comment]
Use the latest version of poppler - 0.76 (https://poppler.freedesktop.org/poppler-0.76.1.tar.xz)

**Comment by zbgns** [comment]
I used the latest version of poppler:
```
zbgns@zbgns:~/Install/poppler-0.76.1/build/utils$ ./pdftotext -v
pdftotext version 0.76.1
Copyright 2005-2019 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC

```
But the output is still messy:
```
$ ~/Install/poppler-0.76.1/build/utils/pdftotext psm1.pdf -
karnie, stanowiące ośrodki propagandowe nowej
wiary. Przerażony tym, co zastał, nuncjusz pa-

pieski, Alojzy Lippomano, radził w roku 1555
Zygmuntowi

dziesięciu

Augustowi,

wybitniejszych

aby

ściął

ośmiu do

„heretyków”, a po-

wstrzyma szerzenie się reformacji.

Ale przybyły z dalekich Włoch legat nie zdawał sobie sprawy, iż rada ta w polskich warunkach nie na wiele się przyda, a może za sobą

pociągnąć jedynie krwawe zaburzenia w całym
raństwie. Nie bardzo się zresztą kwapił łagod-

hy król, z powodu znanej skłonności do odwlekania decyzji „dojutrkiem” zwany, do jej realizacji.

Tym ogniem reformacji (jak się zresztą później okazało, słomianym raczej niż prawdziwym)
nie zapłonęła ani na chwilę jedna tylko dzielnica, mianowicie Mazowsże. Nie powstał tu ża-

den zbór „heretycki”, a zwolennicy protestantyzmu z wielkim tylko trudem
przenikali do
Warszawy, która za pomocą różnych ustaw sta-

rała się jeśli nie pozbyć zwolenników Lutra, to
przynajmniej obrzydzić im życie.
Tę odporność Mazowsza na wpływy reforma9
```
 I must admit I'm confused. I would appreciate any suggestion what to do to have the output as yours.

**Comment by zdenop** [comment]
I made some investigations and I find out I have 2 programs pdftotext:
```
"C:\Program Files\Git\mingw64\bin\pdftotext.exe" -v
pdftotext version 4.00
Copyright 1996-2017 Glyph & Cog, LLC
```
and 
```
F:\win64_llvm\bin\pdftotext.exe -v
pdftotext version 0.76.1
Copyright 2005-2019 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
```
First one (part of _git for windows_!?) creates correct output as I posted above. This `pdftotext` seem to be older (2017),
Second one (the latest code from poppler) produces wrong output as you show.

This confirms my opinion there is no problem in tesseract (unless somebody give prove that tesseract breaks some pdf specification or standard), but there is problem in pdf interpreter (poppler)

**Comment by zbgns** [comment]
Thanks for your patience and explanations. The 4.00 version apparently comes from xpdf suite.
```
C:\Temp\xpdf-tools-win-4.01.01\bin64\pdftotext.exe -v
pdftotext version 4.01.01
Copyright 1996-2019 Glyph & Cog, LLC
```
The segmentation into paragraphs in the output file is correct (but there is some issue with diacritics):
`D:\>C:\Temp\xpdf-tools-win-4.01.01\bin64\pdftotext.exe psm1.pdf xpdf.txt`

```
karnie, stanowice orodki propagandowe nowej wiary. Przeraony tym, co zastal, nuncjusz papieski, Alojzy Lippomano, radzil w roku 1555 Zygmuntowi Augustowi, aby cil omiu do dziesiciu wybitniejszych ,,heretyków", a powstrzyma szerzenie si reformacji.
Ale przybyly z dalekich Wloch legat nie zdawal sobie sprawy, i rada ta w polskich warunkach nie na wiele si przyda, a moe za sob pocign jedynie krwawe zaburzenia w calym rastwie. Nie bardzo si zreszt kwapil lagodhy król, z powodu znanej sklonnoci do odwlekania decyzji ,,dojutrkiem" zwany, do jej realizacji.
Tym ogniem reformacji (jak si zreszt póniej okazalo, slomianym raczej ni prawdziwym) nie zaplonla ani na chwil jedna tylko dzielnica, mianowicie Mazowse. Nie powstal tu aden zbór ,,heretycki", a zwolennicy protestantyzmu z wielkim tylko trudem przenikali do Warszawy, która za pomoc rónych ustaw starala si jeli nie pozby zwolenników Lutra, to przynajmniej obrzydzi im ycie.
T odporno Mazowsza na wplywy reforma-
9
```

So the matter is rather more poppler related than Tesseract related. I found also additional presupposition for that. If the same tiff source image is converted to a searchable pdf with different OCR software (Acrobat Pro DC in my case - two layer output, no "clearscan"), the issue also exists, although is less intensive.
```
D:\>C:\Temp\poppler-0.68.0\bin\pdfinfo.exe Binder1.pdf
Title:
Creator:        Adobe Acrobat 15.6
Producer:       Adobe Acrobat Pro DC 15 Paper Capture Plug-in
CreationDate:   05/10/19 09:22:14 Central European Daylight Time
ModDate:        05/10/19 09:23:36 Central European Daylight Time
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      324 x 404.64 pts
Page rot:       0
File size:      30941 bytes
Optimized:      yes
PDF version:    1.6
```
`D:\>C:\Temp\poppler-0.68.0\bin\pdftotext.exe Binder1.pdf binder.txt`

```
karnie, stanowiące ośrodki propagandowe nowej
wiary. Przerażony tym, co zastał, nuncjusz papieski, Alojzy Lippomano, radził w roku 1555
Zygmuntowi Augustowi, aby ściął ośmiu do
dziesięciu
wybitniejszych „heretyków", a powstrzyma szerzenie się reformacji.
Ale przybyły z dalekich Włoch legat nie zdawał sobie sprawy, iż rada ta w polskich warunkach nie na wiele się przyda, a może za sobą
pociągnąć jedynie krwawe zaburzenia w całym
państwie. Nie bardzo się zresztą kwapił łagod­
ny król, z powodu znanej skłonności do odwlekania decyzji „dojutrkiem" zwany, do jej realizacji.
Tym ogniem reformacji (jak się zresztą pozniej okazało, słomianym raczej niż prawdziwym)
nie zapłonęła ani na chwilę jedna tylko dzielnica, mianowicie Mazowsze. Nie powstał tu ża­
den zbór „heretycki", a zwolennicy protestantyzmu z wielkim tylko trudem przenikali do
Warszawy, która za pomocą różnych ustaw starała się jeśli nie pozbyć zwolenników Lutra, to
przynajmniej obrzydzić im życie.
Tę odporność

Mazowsza na

wpływy

reforma9
```

**Comment by zbgns** [comment]
One additional comment to poppler's pdftotext output. If option `-layout` is used it looks correctly (only multiplied spaces from time to time). There are difficulties with default "reflow" mode.
```
karnie, stanowiące ośrodki propagandowe nowej
wiary. Przerażony tym, co zastał, nuncjusz pa-
pieski, Alojzy Lippomano, radził w roku 1555
Zygmuntowi     Augustowi,     aby   ściął   ośmiu do
dziesięciu   wybitniejszych     „heretyków”, a po-
wstrzyma szerzenie się reformacji.
  Ale przybyły z dalekich Włoch legat nie zda-
wał sobie sprawy, iż rada ta w polskich warun-
kach nie na wiele się przyda, a może za sobą
pociągnąć jedynie krwawe zaburzenia w całym
raństwie. Nie bardzo się zresztą kwapił łagod-
hy król, z powodu znanej skłonności do odwle-
kania decyzji „dojutrkiem” zwany, do jej rea-
lizacji.
  Tym ogniem reformacji (jak się zresztą póź-
niej okazało, słomianym raczej niż prawdziwym)
nie zapłonęła ani na chwilę jedna tylko dzielni-
ca, mianowicie Mazowsże. Nie powstał tu ża-
den zbór „heretycki”, a zwolennicy protestan-
tyzmu z wielkim tylko trudem     przenikali do
Warszawy, która za pomocą różnych ustaw sta-
rała się jeśli nie pozbyć zwolenników Lutra, to
przynajmniej obrzydzić im życie.
  Tę odporność Mazowsza na wpływy reforma-

                                                   9
```
