### ISSUE TITLE
Ubuntu repos install 3.x series, not 4.0 as said in the wiki

### ISSUE THREAD

**Issue by mlissner** [tesseract-ocr/tesseract#2427]
In the wiki, here:

https://github.com/tesseract-ocr/tesseract/wiki#linux

It says:

> ...you can install Tesseract 4.x and it's developer tools on Ubuntu 18.x bionic by simply running:

>     sudo apt install tesseract-ocr
>     sudo apt install libtesseract-dev

However, I'm running Bionic and I got version 3.x installed:

```
↪ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

↪ tesseract -v
tesseract 3.04.01
 leptonica-1.73
  libjpeg 6b : libpng 1.6.34 : zlib 1.2.11
```

**Comment by Shreeshrii** [comment]
https://packages.ubuntu.com/bionic/tesseract-ocr

**Comment by mlissner** [comment]
My mistake, I had an old version lingering around. Sorry about that.
