### ISSUE TITLE
Running tesseract on multiple images at a time

### ISSUE THREAD

**Issue by Raviteja1996** [tesseract-ocr/tesseract#2431]
### Environment

* **Tesseract Version**:  5.0.0-alpha-50-g3f4dc
* **Platform**: Ubuntu

Hi can i know how to run tesseract on multiple images. I saw a post somewhere telling that keep all the image names in one file and run that text file. But its telling that image was not found. I kept that text file containing the names of images and images in the same folder so that their path would be same. But when I run, its showing image is not found. please help if I am doing anything wrong.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
