### ISSUE TITLE
Failed loading language 'eng' - Windows Server 2016

### ISSUE THREAD

**Issue by capedrolima** [tesseract-ocr/tesseract#2433]
### Environment:

- I am getting this error in one specific server (Windows Server 2016 x64) when I try to use tesseract. **Failed loading language 'eng'** 

**_**Can** someone help me_?**

### Tesseract Version:

- tesseract-ocr-w64-setup-v4.1.0.20190314 (rc1) (64 bit) resp.

### Platform: 

- Windows Server 2016 Standard 64x

### Test:
cmd: Tesseract-OCR>tesseract tessert\IMAGE.jpg test
**Error opening data file C:\Program Files\Tesseract-OCR\eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.**

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
And spent at least 1 second for searching on internet.
