### ISSUE TITLE
Error param ALTO when using tessdata-dir param

### ISSUE THREAD

**Issue by M3ssman** [tesseract-ocr/tesseract#2436]
### Environment

* **Tesseract Version**:  4.1.0-rc2-48-g5320
* **Commit Number**: 
* **Platform**: Ubuntu 18.04 LTS

### Current Behavior:

Call `tesseract` from Bash with explicite `tessdata-dir` leads to improper processing of last Parameter `alto`:

```
tesseract --dpi 500 --tessdata-dir <path> <path-to-some-image> <output-name> -l deu_frak alto

=>

read_params_file: can't open alto
```
Whereas calling without `tessdata-dir`works fine

```
tesseract --dpi 500 <path-to-some-image> <output-name> -l deu_frak alto
```
which in turn works only if Language-Model-File was moved into `/usr/share/tesseract/4.00/tessdata`

### Expected Behavior:

No difference in order or number of parameters, no side-effect from parameter `tessdata-dir` to any other parameters or their placements.

### Suggested Fix:

Adjust Parameter-Processing, introduce explicite output-format parameter, like `--output-format alto`

**Comment by zdenop** [comment]
`tessdata-dir` specified where are tesseract data located (language data & config).
If you specified to use config alto and it is not presented in tessdata-dir, it fails. It is correct and expected behavior.

**Comment by M3ssman** [comment]
Thanks for your explanation. I wasn't aware of this relationship, I didn't expect configurations inside a data Directory, sorry.

**Comment by stweil** [comment]
> Adjust Parameter-Processing, introduce explicite output-format parameter, like --output-format alto

@M3ssman, `-c tessedit_create_alto=1` can be used in your case, so there is already an explicit parameter for the output format.
