### ISSUE TITLE
wordlist2dawg not creating the word-dawg file. i use tesseract 3.0.2 in windows 10

### ISSUE THREAD

**Issue by vineemike** [tesseract-ocr/tesseract#2438]
Hi,
I am trying to create the dawg file in tessseract. All i get is the Failed to open dawg file eng.word-dawg. the command is used is "wordlist2dawg.exe eng_dict1.txt eng.word-dawg eng.unicharset" 
i have attached the files (eng.unicharset and eng_dict1.txt) i used.  the error i am getting is Dawg is empty, skip producing the output file and Failed to open dawg file eng.word-dawg. kindly assist

**Comment by vineemike** [comment]
this is what present in the eng_dict1.txt file. 
Note
the
file
names 
of 
the 
files 
to 
extract 
to 
and 
to 
overwrite 
from 
should 
have 
the 
appropriate 
file 
suffixes 
extensions 
indicating 
their 
tessdata 
component 
type 
unicharset 
for 
the 
unicharset 
unicharambigs 
unichar 
ambigs
etc 
See  
File
Suffix 
variable 
in 
ccutil 
tessdata
manager

**Comment by vineemike** [comment]
this is what present in my eng.unicharset file
1
NULL 0 NULL 0

**Comment by zdenop** [comment]
tessect 3.0 is very old not supported version.
