### ISSUE TITLE
tesseract-ocer training issue

### ISSUE THREAD

**Issue by ukirdeankush** [tesseract-ocr/tesseract#2442]
### Environment

* **Tesseract Version**: tesseract-ocr-w64-setup-v4.1.0.20190314

* **Platform**:Windows10 and  64-bit -->

**Comment by Shreeshrii** [comment]
>icuin63.dll was not found

@stweil Is this packaged with the Windows version?

@ukirdeankush I don't think you will be able to train for the handwriting on the attached image.

**Comment by stweil** [comment]
@ukirdeankush, please report future problems with the Windows installer from UB-Mannheim at https://github.com/UB-Mannheim/tesseract/issues.

https://github.com/UB-Mannheim/tesseract/wiki has two newer installers. Please try those. The ICU DLL files are included in the installers. If they are missing or don't work, that can be reported and I'll try to fix it in a newer version.
