### ISSUE TITLE
bug causing Inverted color output still present in the current version

### ISSUE THREAD

**Issue by peckstein** [tesseract-ocr/tesseract#2443]
Earlier, there were reports about a bug causing inverted color outputs, however, the bug is still present in the current stable version, at least on macOS 10.13.6 using png files:

`tesseract input.png output.pdf -l eng PDF`

I have uploaded the input file, so feel free to check the behaviour yourself.

![](https://i.ibb.co/87P5ypx/test2-001.png)

tessertact version:

`tesseract 4.0.0
leptonica-1.78.0
libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE`

**Comment by zdenop** [comment]
Please use the latest code when reporting bug.
