### ISSUE TITLE
Tesseract creates PDF with no spaces for Arabic

### ISSUE THREAD

**Issue by yregaieg** [tesseract-ocr/tesseract#2446]
I am trying Tesseract with arabic document, and I noticed that text recognition works extremely well (I am actually quite surprised by the accuracy of it).
However, when I try to generate a PDF with a text overlay on top of the image using : `tesseract -l ara test-ocr.jpg result pdf` the document generated doesn't contain any spaces in it.
Here is a snippet of the extracted TXT using `tesseract -l ara test-ocr.jpg result` : 
```
الموضوع : حول تنفيذ مشروع انتزاع للمصلحة العامة
```

Here is the same snippet, but copied from the PDF generated with this command `tesseract -l ara test-ocr.jpg result pdf` :
```
الموضوع:حولتنفيذمشروعانتزاعللمصلحةالعامة
```

Sample image to test this out : https://imgur.com/a/TsfudZ6

------------------------

### Environment

* **Tesseract Version**: 
```
09:50 $ tesseract --version
tesseract 4.0.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
```

* **Platform**: 
```
Darwin XXXX 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

**Comment by zdenop** [comment]
Please use the latest code when reporting issue.

**Comment by Shreeshrii** [comment]
@zdenop Please consider releasing 4.1 RC2.

**Comment by amitdo** [comment]
Also test with other pdf viewers. The default pdf viewer in macOS is not so good at displaying Tesseract's output. The built-in pdf viewer in Google's Chrome browser is recommended.

**Comment by yregaieg** [comment]
Tried both actually, along with pdfJS and tika parsers inside Alfresco Content Services.

**Comment by yregaieg** [comment]
Just an update : Following the recommendation from @zdenop I have built tesseract from sources (5.0 alpha) and retried. And I can confirm that I still get the same results as with 4.0.0.
I have also tried out all possible `--psm` options (read somewhere that it made a difference with Japanese) but it doesn't seem to help in my case !

**Comment by jbreiden** [comment]
I'll take a look but no promises.

>

**Comment by yregaieg** [comment]
That would be highly appreciated. I have been working for this pro-bono project for a couple of months, and it would be a shame to abandon at this stage due to this bug.
@jbreiden Also if you manage to locate the culprit but you don't have enough time to fine-tune/experiment I would be more than happy to help :)

**Comment by jbreiden** [comment]
Source image is great, but please also attach a problematic PDF to bug.

>

**Comment by jbreiden** [comment]
Tried with stock Tesseract shipping with Debian, which is a pretty recent
build.
Did not reproduce the problem. Seeing all sorts of spaces in Chrome's PDF
viewer during highlight and copy-paste operations.

http://metadata.ftp-master.debian.org/changelogs/main/t/tesseract/unstable_changelog

# tesseract -v
tesseract 4.0.0
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.2) : libpng 1.6.36 : libtiff
4.0.10 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX
 Found SSE

There was a really recent change to spacing in PDF about 25 days ago which
conceivably could
mess things up. If older Tesseract works and newer Tesseract fails, that's
the most obvious possible
culprit.

https://github.com/tesseract-ocr/tesseract/issues/1900

**Comment by yregaieg** [comment]
Getting back to this issue, Indeed I do see space now, at least on Adobe Acrobat Reader DC, not sure what did I miss when I first raised this issue, in Alfresco and PDFJS though I was searching for a word and I assumed I had the same issue as in the MacOS preview app, but it turns out I was stumbling on  #238 which is even more annoying !
Thanks guys and sorry for the wrong Alarm
