### ISSUE TITLE
detecting special characters (bullets) in tesseract, also accuracy is very poor. misintrepreting words 

### ISSUE THREAD

**Issue by vineemike** [tesseract-ocr/tesseract#2447]
hi, 
I am trying to train the tesseract OCR for English language with good accuracy. The version I used in 4.00.00alpha, leptonica 1.74.1. I have few issues like the special characters (especially bullets) are not recognized. and also the 'm' is recognized as 'rn'. also many words are not recognized properly. my eng.DangAmbigs txt file contains the below text 
1    m   2    rn
3   i i i  1    m
I also added a set of words along with the special characters in the word list and freq word list(I created 2 txt files and created the dawg files using commands).  
My initial step was to create 2 txt files with alphabets in one file and a set of words in another file and created the box file and tiff file using the software jtessbox editor. 
also the images i give is clear, but i get different words in between. I don't understand where is the error.
kindly assist, what makes the accuracy increase.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
