### ISSUE TITLE
Failed to read data from: ./langdata/eng/eng.config

### ISSUE THREAD

**Issue by yilanwanglu** [tesseract-ocr/tesseract#2449]
###Environment
 Platform64 bit Ubuntuu 16.04
 tesseract 5.0.0-alpha-56-gb9b74
 leptonica-1.79.0
 libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8
 Found AVX2
 Found AVX
 Found SSE
### Current Behavior:
src/training/tesstrain.sh --fonts_dir /usr/share/fonts --training_text ./training_data/model_tt.txt --langdata_dir ./langdata --tessdata_dir ./tessdata --lang eng --linedata_only --noextract_font_properties  --fontlist "FreeMono" --output_dir ~/tesstutorial/engtrain

In the training eng execution script tesstrain.sh, the following problems occurred:
Setting script properties
Config file is optional, continuing...
Failed to read data from: ./langdata/eng/eng.config
Null char=2
Reducing Trie to SquishedDawg

### Expected Behavior:
=== Phase I: Generating training images ===
Rendering using FreeMono
[2019年 05月 21日 星期二 09:40:26 CST] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.8ZKXwRt3RY --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0 --max_pages=0 --font=FreeMono --text=./training_data/model_tt.txt
Rendered page 0 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 1 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 2 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 3 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 4 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 5 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 6 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 7 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 8 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 9 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 10 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 11 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 12 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 13 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 14 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 15 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 16 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 17 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 18 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 19 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 20 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 21 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif
Rendered page 22 to file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif

=== Phase UP: Generating unicharset and unichar properties files ===
[2019年 05月 21日 星期二 09:40:39 CST] /usr/local/bin/unicharset_extractor --output_unicharset /tmp/eng-2019-05-21.RQa/eng.unicharset --norm_mode 1 /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.box
Extracting unicharset from box file /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.box
Other case M of m is not in unicharset
Other case O of o is not in unicharset
Other case E of e is not in unicharset
Other case L of l is not in unicharset
Other case J of j is not in unicharset
Other case k of K is not in unicharset
Other case f of F is not in unicharset
Other case y of Y is not in unicharset
Other case h of H is not in unicharset
Other case r of R is not in unicharset
Other case b of B is not in unicharset
Other case n of N is not in unicharset
Other case a of A is not in unicharset
Wrote unicharset file /tmp/eng-2019-05-21.RQa/eng.unicharset
[2019年 05月 21日 星期二 09:40:39 CST] /usr/local/bin/set_unicharset_properties -U /tmp/eng-2019-05-21.RQa/eng.unicharset -O /tmp/eng-2019-05-21.RQa/eng.unicharset -X /tmp/eng-2019-05-21.RQa/eng.xheights --script_dir=./langdata
Loaded unicharset of size 38 from file /tmp/eng-2019-05-21.RQa/eng.unicharset
Setting unichar properties
Other case M of m is not in unicharset
Other case O of o is not in unicharset
Other case E of e is not in unicharset
Other case L of l is not in unicharset
Other case J of j is not in unicharset
Other case k of K is not in unicharset
Other case f of F is not in unicharset
Other case y of Y is not in unicharset
Other case h of H is not in unicharset
Other case r of R is not in unicharset
Other case b of B is not in unicharset
Other case n of N is not in unicharset
Other case a of A is not in unicharset
Setting script properties
Writing unicharset to file /tmp/eng-2019-05-21.RQa/eng.unicharset

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=./tessdata
[2019年 05月 21日 星期二 09:40:40 CST] /usr/local/bin/tesseract /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.tif /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0 --psm 6 lstm.train
Tesseract Open Source OCR Engine v5.0.0-alpha-56-gb9b74 with Leptonica
Page 1
Page 2
Loaded 56/56 lines (1-56) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 3
Loaded 112/112 lines (1-112) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 4
Loaded 168/168 lines (1-168) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 5
Loaded 224/224 lines (1-224) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 6
Loaded 280/280 lines (1-280) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 7
Loaded 336/336 lines (1-336) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 8
Loaded 392/392 lines (1-392) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 9
Loaded 448/448 lines (1-448) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 10
Loaded 504/504 lines (1-504) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 11
Loaded 560/560 lines (1-560) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 12
Loaded 616/616 lines (1-616) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 13
Loaded 672/672 lines (1-672) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 14
Loaded 728/728 lines (1-728) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 15
Loaded 784/784 lines (1-784) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 16
Loaded 840/840 lines (1-840) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 17
Loaded 896/896 lines (1-896) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 18
Loaded 952/952 lines (1-952) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 19
Loaded 1008/1008 lines (1-1008) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 20
Loaded 1064/1064 lines (1-1064) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 21
Loaded 1120/1120 lines (1-1120) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 22
Loaded 1176/1176 lines (1-1176) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf
Page 23
Loaded 1232/1232 lines (1-1232) of document /tmp/eng-2019-05-21.RQa/eng.FreeMono.exp0.lstmf

=== Constructing LSTM training data ===
Creating new directory /home/ge/tesstutorial/engtrain6
[2019年 05月 21日 星期二 09:40:49 CST] /usr/local/bin/combine_lang_model --input_unicharset /tmp/eng-2019-05-21.RQa/eng.unicharset --script_dir ./langdata --words ./langdata/eng/eng.wordlist --numbers ./langdata/eng/eng.numbers --puncs ./langdata/eng/eng.punc --output_dir /home/ge/tesstutorial/engtrain6 --lang eng
Loaded unicharset of size 38 from file /tmp/eng-2019-05-21.RQa/eng.unicharset
Setting unichar properties
Other case M of m is not in unicharset
Other case O of o is not in unicharset
Other case E of e is not in unicharset
Other case L of l is not in unicharset
Other case J of j is not in unicharset
Other case k of K is not in unicharset
Other case f of F is not in unicharset
Other case y of Y is not in unicharset
Other case h of H is not in unicharset
Other case r of R is not in unicharset
Other case b of B is not in unicharset
Other case n of N is not in unicharset
Other case a of A is not in unicharset
Setting script properties
Config file is optional, continuing...
Failed to read data from: ./langdata/eng/eng.config
Null char=2
Reducing Trie to SquishedDawg
Reducing Trie to SquishedDawg
Reducing Trie to SquishedDawg
### Suggested Fix:

**Comment by Shreeshrii** [comment]
>Config file is optional, continuing...
Failed to read data from: ./langdata/eng/eng.config

This is only a warning, since config file is optional.

**Comment by yilanwanglu** [comment]
OK，thank you！

**Comment by nihitjain11** [comment]
@Shreeshrii 
Can you please tell what does the eng.config file do?
And how or where can I get that file from?

**Comment by Shreeshrii** [comment]
There is no eng.config file. You can safely ignore this message. Very few languages use config files.

**Comment by eravallirao** [comment]
Hi, I am getting the below error. Can you please help me. I am using the below command where I am asking to generating 4000 pages but it is able to generate 2 pages in .tif format
**tesstrain.sh --fonts_dir /usr/local/share/fonts --fontlist 'calibri' --lang eng --linedata_only --langdata_dir langdata_lstm --tessdata_dir tessdata --save_box_tiff --maxpages 4000 --output_dir train**


=== Starting training for language 'eng'
[Wed Jul 3 11:32:45 IST 2019] /usr/local/bin/text2image --fonts_dir=/usr/local/share/fonts --font=calibri --outputbase=/var/folders/jk/5jhgxsjn76b_d5vmvm91hl8r0000gn/T/font_tmp.XXXXXXXXXX.xowjqO3i/sample_text.txt --text=/var/folders/jk/5jhgxsjn76b_d5vmvm91hl8r0000gn/T/font_tmp.XXXXXXXXXX.xowjqO3i/sample_text.txt --fontconfig_tmpdir=/var/folders/jk/5jhgxsjn76b_d5vmvm91hl8r0000gn/T/font_tmp.XXXXXXXXXX.xowjqO3i
Fontconfig warning: ignoring UTF-8: not a valid region tag
Rendered page 0 to file /var/folders/jk/5jhgxsjn76b_d5vmvm91hl8r0000gn/T/font_tmp.XXXXXXXXXX.xowjqO3i/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using calibri
[Wed Jul 3 11:32:47 IST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/var/folders/jk/5jhgxsjn76b_d5vmvm91hl8r0000gn/T/font_tmp.XXXXXXXXXX.xowjqO3i --fonts_dir=/usr/local/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/var/folders/jk/5jhgxsjn76b_d5vmvm91hl8r0000gn/T/eng-2019-07-03.XXX.KGXPtv9Z/eng.calibri.exp0 --max_pages=4000 --font=calibri --text=langdata_lstm/eng/eng.training_text
Fontconfig warning: ignoring UTF-8: not a valid region tag
Rendered page 0 to file /var/folders/jk/5jhgxsjn76b_d5vmvm91hl8r0000gn/T/eng-2019-07-03.XXX.KGXPtv9Z/eng.calibri.exp0.tif
Rendered page 1 to file /var/folders/jk/5jhgxsjn76b_d5vmvm91hl8r0000gn/T/eng-2019-07-03.XXX.KGXPtv9Z/eng.calibri.exp0.tif

**Comment by Shreeshrii** [comment]
How big is your langdata_lstm/eng/eng.training_text?

**Comment by eravallirao** [comment]
It is 7kb

**Comment by eravallirao** [comment]
Hi @Shreeshrii  

I added extra lines into the training_text file randomly. And now I am able to get multiple pages. I have other doubt, Is there a way to integrate the model(**Checkpoint**) which we trained into **Gosseract**. Or can we test the model directly using a random image which contains text.
