### ISSUE TITLE
Why are there redundant spaces in the generated documents after Tesseract 4.0?(As shown in the following figure)

### ISSUE THREAD

**Issue by xiaohenian** [tesseract-ocr/tesseract#2450]
![1558424853(1)](https://user-images.githubusercontent.com/37136059/58077815-e2880800-7bdf-11e9-9664-edf1e6978a6c.jpg)

**Comment by Shreeshrii** [comment]
Please mention O/s, tesseract version and which tessdata file you used. 

See https://github.com/tesseract-ocr/tessdata_fast/commit/80d92b7db61cb6ddc519049990be34e4c913566f

**Comment by xiaohenian** [comment]
tesseract-ocr4.0 and https://github.com/tesseract-ocr/tessdata

**Comment by Shreeshrii** [comment]
try command with

`-c preserve_interword_spaces 1`

@stweil The config files need changes in tessdata_best and tessdata (similar to tessdata_fast). The files are too big for me to commit.

**Comment by xiaohenian** [comment]
Thank you！After I used tessdata_fast, the problem was solved.
