### ISSUE TITLE
Version mentioned in 4.0 seems wrong

### ISSUE THREAD

**Issue by codecolony** [tesseract-ocr/tesseract#2457]
Hi,

I have built 4.0 version from 4.0 branch but version file mentions 5.0.0-alpha. Can someone please clarify what is wrong here?

Thanks and Regards,
codec

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by Shreeshrii** [comment]
master branch is 5.0.0-alpha. If you need 4.ox, clone 4.1 branch

**Comment by stweil** [comment]
The `VERSION` file in the 4.0 branch was indeed wrong. I now fixed it in commit c69859cacb040a518cd64206ab1a2d6e48d17854.

@codecolony, thank you for reporting this.

**Comment by codecolony** [comment]
@stweil Thanks a lot for clarifying. Appreciate your effort.
