### ISSUE TITLE
Cannot set TESSDATA_PREFIX when building tesseract-4.0.0

### ISSUE THREAD

**Issue by juanitotc** [tesseract-ocr/tesseract#2458]
I am unable to set -DTESSDATA_PREFIX=/usr/local/share/tesseract-ocr/4.00/tessdata with cmake or  TESSDATA_PREFIX="/usr/local/share/tesseract-ocr/4.00/tessdata" ./configure --prefix=/usr/local --enable-tessdata-prefix with autotools.

Are users meant to be able to do this?

**Comment by zdenop** [comment]
No, it not possible. And IMO it does not make sense nowadays.

**Comment by juanitotc** [comment]
Thanks for the reply, but it's kind of inconvienient to have to set TESSDATA_PREFIX and also means, for example, that gImageReader looks in "/" for the data files...

**Comment by zdenop** [comment]
You can use `--tessdata-dir` to specify data path or use tesseract API to specify data path at init...
Regarding gImageReader we can do nothing - it is external project.

**Comment by stweil** [comment]
@juanitotc, try `./configure --datadir=/usr/local/share/tesseract-ocr/4.00 [...]`.

**Comment by zdenop** [comment]
@stweil: I am not sure if 4.0 branch make sense...

**Comment by stweil** [comment]
It was there, so it should be in an acceptable state. Removing that branch would be another option, but I don't think that would be good.

**Comment by zdenop** [comment]
We should check if all commits in 4.0 are in also in master and 4.1...

**Comment by zdenop** [comment]
@juanitotc: try master code now (`cmake .. -DTESSDATA_PREFIX=/usr/local/share/tesseract-ocr/4.00/tessdata`)

**Comment by juanitotc** [comment]
Thanks for that - there is a slight problem in that "cmake .. -DTESSDATA_PREFIX=/usr/local/share/tesseract-ocr/4.00/tessdata" will cause tesseract to look in "/usr/local/share/tesseract-ocr/4.00/tessdata/tessdata" i.e. "tessdata" is repeated in the path.

**Comment by zdenop** [comment]
@juanitotc: you miss the point: I just used your example - you can specify whatever path you want. It is not tesseract problem, but your decision.
