### ISSUE TITLE
building latest git with -DOPENMP_BUILD=ON fails

### ISSUE THREAD

**Issue by juanitotc** [tesseract-ocr/tesseract#2462]
Using -DOPENMP_BUILD=ON causes "/openmp" to be used rather than "-fopenmp".

Using:
find . -name flags.make -type f -exec sed -i 's/\/openmp/-fopenmp/g' {} \;
find . -name build.make -type f -exec sed -i 's/\/openmp/-fopenmp/g' {} \;
find . -name link.txt -type f -exec sed -i 's/\/openmp/-fopenmp/g' {} \;

..the build succeeds.

**Comment by zdenop** [comment]
believe me: you do not want to have openmp on....

**Comment by juanitotc** [comment]
In the few tests I've done with tesseract-4.0.0 things seem to work fine

**Comment by zdenop** [comment]
search forum/issue tracker why decide to turn it off in all builds...

**Comment by stweil** [comment]
This is now fixed with commit 7093727da1e25e2e5202169d2ab210e617db93b2.

**Comment by zdenop** [comment]
There could/should be done more regarding OPENMP if we will support it (using cmake detection, or at least move [this section](https://github.com/tesseract-ocr/tesseract/blob/7093727da1e25e2e5202169d2ab210e617db93b2/CMakeLists.txt#L415) to line 129, to have all OPENMP setting on one place).

**Comment by stweil** [comment]
As you already mentioned above, turning OpenMP off is typically the best option. I did that in the latest Tesseract installer for Windows, and it made OCR processing even of a single image very much faster.

**Comment by zdenop** [comment]
I heard that during training OPENMP helps ;-). But I did not test it...
