### ISSUE TITLE
building latest git fails with -DTARGET_ARCHITECTURE=auto

### ISSUE THREAD

**Issue by juanitotc** [tesseract-ocr/tesseract#2463]
if -DTARGET_ARCHITECTURE=auto (correctly detects haswell) or -DTARGET_ARCHITECTURE=haswell is used, the build fails. Using -DTARGET_ARCHITECTURE=generic succeeds.

[ 94%] Building CXX object CMakeFiles/libtesseract.dir/src/arch/dotproductavx.cpp.o
/usr/local/bin/c++  -DHAVE_CONFIG_H -DTESSDATA_PREFIX=/usr/local/share/tesseract-ocr/4.00 -DTESS_EXPORTS -D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS=1 -Dlibtesseract_EXPORTS -I/usr/local/include -I/usr/local/include/leptonica -I/usr/src/tesseract/build -I/usr/src/tesseract/src/api -I/usr/src/tesseract/build/api -I/usr/src/tesseract/src/arch -I/usr/src/tesseract/src/ccmain -I/usr/src/tesseract/src/ccstruct -I/usr/src/tesseract/src/ccutil -I/usr/src/tesseract/src/classify -I/usr/src/tesseract/src/cutil -I/usr/src/tesseract/src/dict -I/usr/src/tesseract/src/lstm -I/usr/src/tesseract/src/opencl -I/usr/src/tesseract/src/textord -I/usr/src/tesseract/src/viewer -I/usr/src/tesseract/src/wordrec  -fopenmp --std=c++11 -flto -fuse-linker-plugin -Os -pipe -fno-exceptions -fno-rtti -fPIC   -std=c++14  -fopenmp --std=c++11  -DSSE2 -DSSE3 -DSSSE3 -DSSE4_1 -DSSE4_2 -DAVX -DFMA -DBMI2 -DAVX2 -o CMakeFiles/libtesseract.dir/src/arch/dotproductavx.cpp.o -c /usr/src/tesseract/src/arch/dotproductavx.cpp
/usr/src/tesseract/src/arch/dotproductavx.cpp:20:2: error: #error Implementation only for AVX capable architectures
 #error Implementation only for AVX capable architectures
  ^~~~~
/usr/src/tesseract/src/arch/dotproductavx.cpp: In function 'double tesseract::DotProductAVX(const double*, const double*, int)':
/usr/src/tesseract/src/arch/dotproductavx.cpp:34:34: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
   __m256d t0 = _mm256_setzero_pd();

**Comment by zdenop** [comment]
Solution: use autotools on linux. cmake build is focused on windows users.

**Comment by juanitotc** [comment]
Yes, it works and seems to compile tesseract signifcantly differently than cmake.

It might be good to highlight the linux/autotools windows/cmake issue in the readme?

$ tesseract test_scan.png ~
[DS] Profile read from file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 1:Intel(R) HD Graphics Haswell Ultrabook GT2 Mobile score is 4.755380
[DS] Device[2] 0:(null) score is 0.415914
[DS] Selected Device[2]: "(null)" (Native)
Tesseract Open Source OCR Engine v5.0.0-alpha-104-ge44c with Leptonica

**Comment by zdenop** [comment]
Suggested compiling process is already described on relevant wiki: https://github.com/tesseract-ocr/tesseract/wiki/Compiling.

**Comment by stweil** [comment]
I could not reproduce this issue with latest code.
