### ISSUE TITLE
Unable to get accuracy on tesseract 4.0 for engraved or stamped metal plate recognition

### ISSUE THREAD

**Issue by harshalcse** [tesseract-ocr/tesseract#2467]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).
Hi,
please find attached images to OCR stamped or engraved VIN images.

![1](https://user-images.githubusercontent.com/5838252/58402045-0aaeb580-807d-11e9-830a-9d7b481d89ba.png)
![IMG_0588](https://user-images.githubusercontent.com/5838252/58402049-100c0000-807d-11e9-9465-bc6c2f9e150e.PNG)
![4](https://user-images.githubusercontent.com/5838252/58402169-506b7e00-807d-11e9-8966-aa804301c9b7.png)

### Environment

* **Tesseract Version**: 4.0.0.20190314 

* **Platform**: Windows, 10 64-bit 

### Suggested Fix:
how to achieve to recognise all VIN or engine number stamped characters.
Also suggeest how to convert it like printed text on white paper.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by harshalcse** [comment]
@zdenop sir please help me on pre-processing of images so that we can easily recognise image .

**Comment by ravitejarj** [comment]
bro did u solved this issues please reply

**Comment by ravitejarj** [comment]
I am also having same issues if u find out please reply that will help me.
how to solve this issue

**Comment by ajasadel** [comment]
i have also same question if you have solution please help me
