### ISSUE TITLE
wiki home page has no info

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#2469]
https://github.com/tesseract-ocr/tesseract/wiki

It is only showing the following

```
Home
artmortal93 edited this page 13 minutes ago · 94 revisions
```

**Comment by bhaveshvyas007** [comment]
please fix this... 

Mean while can someone share info on how to install a particular tesseract version on ubuntu

**Comment by Shreeshrii** [comment]
See  https://github.com/tesseract-ocr/tesseract/wiki/Home/ff9f0ff02d7098c3b5e2e4e76244ef49a5ff4234

Page edited by @stweil 3 days ago

**Comment by zdenop** [comment]
user JesiDream blocked and reported to github support for vandalizing wiki.
Wiki reverted to last correct version:
![image](https://user-images.githubusercontent.com/574156/58551514-77a68480-8210-11e9-94a2-003f28453277.png)

**Comment by stweil** [comment]
Thank you, @zdenop.
