### ISSUE TITLE
unicharset_extractor:./.libs/lt-unicharset_extractor.c:233: FATAL: couldn't find unicharset_extractor.

### ISSUE THREAD

**Issue by mihirjoshi21** [tesseract-ocr/tesseract#247]
`unicharset_extractor *.box`  giving an error in version 3.05.00 so does `mftraining `and `shapetraining`. Works fine in version 3.02.
`

**Comment by amitdo** [comment]
You need to install the training tools.
https://github.com/tesseract-ocr/tesseract/wiki/Compiling

**Comment by zdenop** [comment]
It seem you did not install tesseeract training tool...

**Comment by alenave** [comment]
@zdenop I have installed the tesseract training tool, but how can I install `unicharset_extractor *.box`, `mftraining` `shapetraining`. Can you provide with the necessary links?

**Comment by zdenop** [comment]
For asking support please use [tesseract user forum](https://groups.google.com/forum/#!forum/tesseract-ocr) - see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice)
