### ISSUE TITLE
error in running lstm_training

### ISSUE THREAD

**Issue by Naojen** [tesseract-ocr/tesseract#2471]
lstmtraining --model_output ~/tesstutorial/train_wa/wa \
    --continue_from ~/tesstutorial/train_wa/ben.lstm \
    --traineddata ~/tesstitorial/train_wa/ben/ben.traineddata \
     --old_traineddata tessdata/best/ben.traineddata \
     --train_listfile ~/tesstutorial/train_wa/ben.training_files.txt \
     --max_iterations 3600

mgr_.Init(traineddata_path.c_str()):Error:Assert failed:in file ../../src/lstm/lstmtrainer.h, line 110
Illegal instruction (core dumped)

i have done the same thing as described in the training (for fine tuning), any suggestion, how to fix this???

**Comment by Shreeshrii** [comment]
It is a path error

Means your file is not found.

Make sure u use correct spelling

ls filename
