### ISSUE TITLE
Deserialize header failed: /home/VineethAmalrajS/tesstutorial/engtrain/eng.Tahoma.exp0.lstmf

### ISSUE THREAD

**Issue by vineemike** [tesseract-ocr/tesseract#2472]
I am getting the above error when doing the lstm training. the link I followed is https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#tutorial-guide-to-lstmtraining. The tesseract version used is tesseract v4.0.0.20181030 leptonica-1.76.0. I am unable to find where is the error. what is the mismatch. i just followed the link (from TessTutorial paragraph)

**Comment by Shreeshrii** [comment]
Did you do - https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#one-time-setup-for-tesstutorial?

Does /home/VineethAmalrajS/tesstutorial/engtrain/eng.Tahoma.exp0.lstmf  file exist?

**Comment by Shreeshrii** [comment]
Please close issue, if problem is solved.
