### ISSUE TITLE
Invalid start of grapheme sequence and normalization failed for Bengali Script

### ISSUE THREAD

**Issue by Sanaj2060** [tesseract-ocr/tesseract#2480]
tesseract 4.0.0-beta.1
leptonica-1.75.3
libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX2
 Found AVX
 Found SSE

Extracting unicharset from box file /tmp/tmp.hT7TmqZnPN/ben/ben.Bangla_Medium.exp0.box
Invalid start of grapheme sequence:D=0x983
Normalization failed for string '৩ঃ'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Invalid start of grapheme sequence:D=0x983
Normalization failed for string '৩ঃ'
Invalid start of grapheme sequence:D=0x983
Normalization failed for string '৯ঃ'
Invalid start of grapheme sequence:D=0x983
Normalization failed for string '৯ঃ'
Invalid start of grapheme sequence:D=0x983
Normalization failed for string '৯ঃ'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Invalid start of grapheme sequence:D=0x983
Normalization failed for string '৮ঃ'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Badly formed Indic vowel sequence:0x985 0x9be
Normalization failed for string 'অা'
Extracting unicharset from box file /tmp/tmp.hT7TmqZnPN/ben/ben.Lohit_Bengali.exp0.box
Word started with a combiner:0x9c1
Normalization failed for string 'ু'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9c1
Normalization failed for string 'ু'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9c0
Normalization failed for string 'ী'
Word started with a combiner:0x9cd
Normalization failed for string '্য'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x981
Normalization failed for string 'ঁ'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x982
Normalization failed for string 'ং'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9c0
Normalization failed for string 'ী'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9cb
Normalization failed for string 'ো'
Word started with a combiner:0x9c1
Normalization failed for string 'ু'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9cb
Normalization failed for string 'ো'
Word started with a combiner:0x9c1
Normalization failed for string 'ু'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9c0
Normalization failed for string 'ী'
Word started with a combiner:0x9cd
Normalization failed for string '্য'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be
Normalization failed for string 'া'
Word started with a combiner:0x9be

**Comment by zdenop** [comment]
Please provide full details and data for reproducing problem.

**Comment by Sanaj2060** [comment]
`usr/share/tesseract-ocr/tesstrain.sh --fonts_dir /usr/share/fonts --lang ben --linedata_only --noextract_font_properties --langdata_dir /home/jaoba/langdata_lstm_plus --exposures "0" --tessdata_dir /usr/share/tesseract-ocr/4.00/tessdata --training_text /home/jaoba/langdata_lstm_plus/ben/ben.training_text --output_dir /home/jaoba/tesstutorial/ben_lstm --fontlist "Lohit Bengali" "Bangla Medium" "Mukti Narrow"`

I'm trying to fine tune ben
[data.zip](https://github.com/tesseract-ocr/tesseract/files/3247137/data.zip)

**Comment by Shreeshrii** [comment]
@Sanaj2060  I converted your error messages from bengali to devanagari - please confirm.

Three main kind of normalization errors are seen.

1. Visarga is being used after numbers instead of colon. 
Normalization failed for string '৩ঃ'
Normalization failed for string '৯ঃ'

2. a + aa maatraa is being used instead of the independent vowel aa.
Normalization failed for string 'অা'

3. Words are starting with maatraa.

If there a lot of errors, fix the training text.

If you feel these errors are not correct, then we can look further at the validation rules.

I haven't looked at your zip file.

**Comment by Shreeshrii** [comment]
@Sanaj2060  I ran tesstrain.sh with the text from `tobeadded.odt` and got the normalization errors. All those errors are removed after the text is fixed as per my earlier suggestions. There was an additional case where multiple maatraas were used.

Attached is the modified text.

[ben.tobeadded.txt](https://github.com/tesseract-ocr/tesseract/files/3410962/ben.tobeadded.txt)

Normalization rules for Bengali seem ok.

@zdenop The issue can be closed.
