### ISSUE TITLE
How to solve the Warning: properties incomplete for index

### ISSUE THREAD

**Issue by Bunny22222** [tesseract-ocr/tesseract#2481]
Warning: properties incomplete for index 20745 = 鹲
Warning: properties incomplete for index 20746 = 鹳
Warning: properties incomplete for index 20747 = 鹴
Warning: properties incomplete for index 20748 = 鹵
I've already modified the .unicharset file. Some are successful, but these characters do not work.
How to solve this issue?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by Mostafa-Elmenbawy** [comment]
https://github.com/tesseract-ocr/tesseract/issues/553

**Comment by Mostafa-Elmenbawy** [comment]
https://github.com/tesseract-ocr/tesseract/issues/553
