### ISSUE TITLE
properties imcomplete

### ISSUE THREAD

**Issue by Bunny22222** [tesseract-ocr/tesseract#2482]
### Environment

***Tesseract Version**: Tesseract 4.1
***Platform**: 64-bit

>  Current Behavior:

> Warning: properties incomplete for index 11028 = 熷
> Warning: properties incomplete for index 11029 = 熸

In the chi_sim.unicharset, I edit these two characters like this:
> 熷 1 0,255,0,255,0,0,0,0,0,0 Han 13087 0 13087 熷	# 熷 [71b7 ]x
> 熸 1 0,255,0,255,0,0,0,0,0,0 Han 13088 0 13088 熸	# 熸 [71b8 ]x

###Expected Behavior:
I want no Warning properties incomplete, How to fix it？

**Comment by zdenop** [comment]
I already wrote you you must respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by Bunny22222** [comment]
Where can I find the tesseract user forum?

**Comment by zdenop** [comment]
try to google for it or read https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md ;-)
