### ISSUE TITLE
Error in pixWriteTiff: function not present

### ISSUE THREAD

**Issue by DENV3UR** [tesseract-ocr/tesseract#2483]
Hi I'm trying to create training data through Cygwin with this command :

src/training/tesstrain.sh --fonts_dir /usr/share/fonts/microsoft --fontlist "Arial" --lang eng --linedata_only \
  --noextract_font_properties --langdata_dir ../langdata \
  --tessdata_dir ./tessdata --output_dir ~/tesstutorial/engtrain --training_text ~/tesstutorial/langdata/eng/eng.training_text

But I'm getting this error :

Error in pixWriteTiff: function not present
Rendered page 0 to file /tmp/tmp.Ke0e2PB5Hc/sample_text.txt.tif

Leptonica 1.78 and tesseract 4.0 are both installed and I when i run the config of leptonica i get :
checking for LIBTIFF... yes

I don't know why printWriteTiff is not present.

Thanks for reading.

**Comment by zdenop** [comment]
Hi,

1. This is not support portal - please use tesseract user forum.
2. This is not tesseract issue, but leptonica (if you compiled leptonica wrong way, tesseract can not do anything with it).
3. Maybe you have installed multiple version of leptonica => it is your responsibility to keep your system in working state or to setup environment correctly. tesseract can do nothing with it.
4. If leptonica reports "function not present", it is right. Running configure does not mean you build it. Building it, does not mean you installed it. Even if you installed it you can still have problem described in point 3.

**Comment by DENV3UR** [comment]
Ok, Thanks for taking the time to respond anyway.
