### ISSUE TITLE
Russian Text Recognation did not work

### ISSUE THREAD

**Issue by LaAlkemiisto** [tesseract-ocr/tesseract#2484]
------------------------

### Environment

* **Tesseract Version**: v3
* **Commit Number**: 
* **Platform**:  Windows 10,  64-bit

**Comment by LaAlkemiisto** [comment]
Hi! I'm new here.
About three years ago I did the recognization of russian characters by FreeOcr under Win XP, without problem.
But today I tried to recognize russian caracters in FreeOcr under win 10 and I did not sucess to do it.
When I tried a english text it did work. Please, is there any problem with rus.traineddata?
Thanks in advance.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.
