### ISSUE TITLE
Can you help me get text from the similar following images, with tesseract?

### ISSUE THREAD

**Issue by NabiKAZ** [tesseract-ocr/tesseract#2489]
Can you help me get text from the similar following images, with tesseract?

![](https://user-images.githubusercontent.com/246721/59351360-7e1a1d80-8d33-11e9-964a-b77db534cf13.png)
![](https://user-images.githubusercontent.com/246721/59351362-7e1a1d80-8d33-11e9-8893-dc8eaf86134d.png)
![](https://user-images.githubusercontent.com/246721/59351363-7eb2b400-8d33-11e9-83c5-f597363ccdb1.png)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support

**Comment by NabiKAZ** [comment]
I firstly tried `GSA Captcha Breaker` software with use brute force find best solutions.
Then I found any image filter needed.
Then I deploy it with `magick convert` and `tesseract`.
This solution was about 90% efficient and accurate.

See:

```
magick convert -fuzz 5% -fill "#FFFFFF" -opaque "#000000" -opaque "#101010" -opaque "#242424" -opaque "#3b3b3b" -opaque "#b9b9b9" -opaque "#ababab" -opaque "#505050" -opaque "#f4f4f4" -opaque "#949494" -opaque "#787878" -threshold 60% -blur 1 -sharpen 1 -blur 1 -sharpen 1 -blur 1 -sharpen 1 -blur 1 -sharpen 1 image.jpg dest.jpg
 
tesseract -l eng -c tessedit_char_whitelist=0123456789 --psm 7 --oem 3 --dpi 70 dest.jpg result.txt
```


I also wrote a PHP sample code for testing here:

```
<?php
$count = 0;
$correct = 0;
foreach (glob("captchas/*.png") as $filename) {
 $count++;
 
 $answer = pathinfo($filename, PATHINFO_FILENAME);
 $convert_file = 'converted' . DIRECTORY_SEPARATOR . pathinfo($filename, PATHINFO_BASENAME);
 
 shell_exec('"C:\Program Files\ImageMagick-7.0.8-Q16\magick" convert -fuzz 5% -fill "#FFFFFF" -opaque "#000000" -opaque "#101010" -opaque "#242424" -opaque "#3b3b3b" -opaque "#b9b9b9" -opaque "#ababab" -opaque "#505050" -opaque "#f4f4f4" -opaque "#949494" -opaque "#787878" -threshold 60% -blur 1 -sharpen 1 -blur 1 -sharpen 1 -blur 1 -sharpen 1 -blur 1 -sharpen 1 ' . $filename . ' ' . $convert_file);
 
 $result = shell_exec('"C:\Program Files\Tesseract-OCR\tesseract.exe" --tessdata-dir "C:\Program Files\Tesseract-OCR\tessdata" -l eng -c tessedit_char_whitelist=0123456789 --psm 7 --oem 3 --dpi 70 ' . $convert_file . ' stdout');
 
 $result = substr($result, 0, -2);
 
 if ($answer == $result) {
 $matched = 'Matched';
 $correct++;
 } else {
 $matched = '';
 }
 
 echo $answer . ' > ' . $result . ' : ' . $matched . "\n";
 
}
echo 'Percent matched: %' . $correct*100/$count;
?>
```

![GSA Captcha Breaker](https://user-images.githubusercontent.com/246721/60022867-e52bc080-96a9-11e9-9856-4da24339022b.png)

![sample_captcha](https://user-images.githubusercontent.com/246721/60022878-ed83fb80-96a9-11e9-9d19-95454aa5ec89.png)

![php_test_captcha](https://user-images.githubusercontent.com/246721/60022894-f543a000-96a9-11e9-9c13-f88127375f2e.png)
