### ISSUE TITLE
There is a function main being exported in the library

### ISSUE THREAD

**Issue by deltanu** [tesseract-ocr/tesseract#249]
Hi,
There is a function **main()** at the end of [viewer/svpaint.cpp](https://github.com/tesseract-ocr/tesseract/blob/d7b089fbcf8f1582e8e897f7c8572433b662f533/viewer/svpaint.cpp#L221), which is compiled and exported when building the library. I think it shouldn't be there, or it should be protected by some define so you only compile it when you need it

**Comment by zdenop** [comment]
Did you oversaw #ifndef GRAPHICS_DISABLED ?

**Comment by deltanu** [comment]
I saw it, but as graphics is enabled by default, and as it enables more functions (apart from main), I thought that disabling graphics would also disable more functions and disable some functionality (perhaps all those functions are only used by that main() so it doesn't matter, but I don't know)

So, by default the library is compiled with a main() function, I could --disable-graphics. However, I don't think it's a good idea to put main inside a library or, if needed (why?), to be the default behavior.

Could it be that main() is used by some the executable and it is also included in the library by mistake? 

Cheers.
