### ISSUE TITLE
Error while building on  ppc64-redhat-linux

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#2496]
uname -a
Linux rh-power-vm61.fit.vutbr.cz 4.16.3-301.fc28.ppc64 #1 SMP Mon Apr 23 21:44:46 UTC 2018 ppc64 ppc64 ppc64 GNU/Linux

c++ --version
c++ (GCC) 8.0.1 20180324 (Red Hat 8.0.1-0.20)

c++ -v
Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/ppc64-redhat-linux/8/lto-wrapper
Target: ppc64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --build=ppc64-redhat-linux
Thread model: posix
gcc version 8.0.1 20180324 (Red Hat 8.0.1-0.20) (GCC)

git log -1
commit 73e5241004135caeda22f1b795ec15a9874ba420 (HEAD -> master, origin/master, origin/HEAD)
Author: Stefan Weil 
Date:   Fri Jun 14 17:22:24 2019 +0200

unittest: Fix and enable textlineprojection_test

Error
==

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -DNDEBUG -I../../src/ccutil -I../../src/ccstruct -I../../src/arch -I../../src/lstm -I../../src/viewer -I../../src/classify -I../../src/dict -I../../src/wordrec -I../../src/cutil -I../../src/textord -I../../src/opencl -DDISABLED_LEGACY_ENGINE -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -g -O2 -std=c++17 -MT control.lo -MD -MP -MF .deps/control.Tpo -c control.cpp -o control.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -DNDEBUG -I../../src/ccutil -I../../src/ccstruct -I../../src/arch -I../../src/lstm -I../../src/viewer -I../../src/classify -I../../src/dict -I../../src/wordrec -I../../src/cutil -I../../src/textord -I../../src/opencl -DDISABLED_LEGACY_ENGINE -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -g -O2 -std=c++17 -MT control.lo -MD -MP -MF .deps/control.Tpo -c control.cpp -o control.o
control.cpp: In member function ‘ACCEPTABLE_WERD_TYPE tesseract::Tesseract::acceptable_word_string(const UNICHARSET&, const char*, const char*)’:
control.cpp:1773:52: internal compiler error: in build_over_call, at cp/call.c:8240
   if (s[offset] != '\0' && STRING(chs_leading_punct).contains(s[offset]))
                                                    ^
control.cpp: In member function ‘ACCEPTABLE_WERD_TYPE tesseract::Tesseract::acceptable_word_string(const UNICHARSET&, const char*, const char*)’:
control.cpp:1773:52: internal compiler error: in build_over_call, at cp/call.c:8240
   if (s[offset] != '\0' && STRING(chs_leading_punct).contains(s[offset]))
                                                    ^
Please submit a full bug report,
with preprocessed source if appropriate.
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/ccAxslpj.out file, please attach this to your bugreport.
Preprocessed source stored into /tmp/cc5kXfWj.out file, please attach this to your bugreport.


```

**Comment by zdenop** [comment]
> internal compiler error: in build_over_call, at cp/call.c:8240
seems like not tesseract issue...

**Comment by Shreeshrii** [comment]
Yes, you are right. It is ` internal compiler error` but I wanted to document it for reference.

**Comment by Shreeshrii** [comment]
This used to build ok with c++14. 

Is there anyway for me to specify that during build - to not use c++17 even though it may be reported as being supported.

**Comment by Shreeshrii** [comment]
```
./configure --disable-shared --disable-opencl --disable-graphics --disable-openmp --disable-debug --disable-legacy CXXFLAGS="-std=c++14"
```
did not work, as the script added c++17

So I commented the line regarding the check in configure.ac

```
CPLUSPLUS=
AX_CHECK_COMPILE_FLAG([-std=c++11], [CPLUSPLUS=11], [], [$WERROR])
AX_CHECK_COMPILE_FLAG([-std=c++14], [CPLUSPLUS=14], [], [$WERROR])
#AX_CHECK_COMPILE_FLAG([-std=c++17], [CPLUSPLUS=17], [], [$WERROR])
#AX_CHECK_COMPILE_FLAG([-std=c++20], [CPLUSPLUS=20], [], [$WERROR])
```

Building ok now.

**Comment by zdenop** [comment]
if compiler confirms it support c++17 but actually not, it is problem of compiler...

**Comment by stweil** [comment]
I also have sporadic internal compiler errors with ppc64-redhat-linux-g++. My compiler version is g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36). Typically it works when I run make again.

**Comment by Shreeshrii** [comment]
@stweil Thank you for looking into this.

I do not have enough rights on that machine to upgrade the compiler and there has been no response from admin. I use it rarely for testing big-endian once in a while.
