### ISSUE TITLE
"Latin.unicharset" and "Latin.xheights" missing for "One-time Setup for TessTutorial"

### ISSUE THREAD

**Issue by ozdefir** [tesseract-ocr/tesseract#2498]
### Environment:

* **Tesseract Version**: 4.0.0
* **Platform**: Debian Stretch
### Current Behavior:
These two files, "Latin.unicharset" and "Latin.xheights", which are necessary for the "One-time Setup for TessTutorial" aren't available in the langdata_lstm repository anymore.

**Comment by zdenop** [comment]
What is "One-time Setup for TessTutorial"?

**Comment by Shreeshrii** [comment]
I had added it to the training wiki page.
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#one-time-setup-for-tesstutorial

It downloaded minimal set of files used for training tutorial.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/langdata_lstm/commit/02cc8f028532367dd44ba5fb3cbb6ac0bf73d6ad has moved the xheights and unicharset files also. These are referred during training process for languages also.

 (I haven't tested with new version of repo).

**Comment by Shreeshrii** [comment]
@ozdefir You can download them from https://github.com/tesseract-ocr/langdata_lstm/tree/master/script
