### ISSUE TITLE
Read only 3 tiff pages from the ben.training_text

### ISSUE THREAD

**Issue by Sanaj2060** [tesseract-ocr/tesseract#2501]
> tesseract 4.0.0-beta.1
>  leptonica-1.75.3
>   libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
> 
>  Found AVX2
>  Found AVX
>  Found SSE

I try to fine tune the Ben model by adding few Manipuri words (Bengali Script) to the ben.training_text.

`usr/share/tesseract-ocr/tesstrain.sh --fonts_dir /usr/share/fonts --lang ben --linedata_only --noextract_font_properties --langdata_dir /home/jaoba/langdata_lstm_master_ft --exposures "0" --tessdata_dir /usr/share/tesseract-ocr/4.00/tessdata --training_text /home/jaoba/langdata_lstm_master_ft/ben/ben.training_text --output_dir /home/jaoba/tesstutorial/ben_170619_2 --fontlist "Lohit Bengali" "Bangla Medium"`

Now I get new ben.unicharset of only 73 char. When I check the box files and the tiff (ben.Bangla_Medium.exp0.tif, ben.Lohit_Bengali.exp0.tif) I found out that there are only 3 pages in the tiff file which is incomplete compared to my modified training_text.

**My question is how to make the tesseract read all the words in the training_text file to produce a complete unicharset.**

**Comment by Sanaj2060** [comment]
@Shreeshrii Please help me out.

**Comment by Shreeshrii** [comment]
Use the following flag with your command:

  --maxpages 0

(0 means ALL pages or you can give a number).

You are using tesseract 4.0.0-beta.1 - you should update to latest version otherwise it may not work.
