### ISSUE TITLE
Training with intermediate checkpoints

### ISSUE THREAD

**Issue by kamrapooja** [tesseract-ocr/tesseract#2504]
Hi, 
My training went into divergence. I am trying to train using intermediate checkpoints.
Command used is :
lstmtraining --stop_training --continue_from /home/administrator/pooja/training_output/training_changed3.118_1971.checkpoint --traineddata /home/administrator/pooja/training_changed_lstmf/eng/eng.traineddata --model_output /home/administrator/pooja/training_output/test.traineddata

But it is giving error:
mgr_.Init(traineddata_path.c_str()):Error:Assert failed:in file ../../src/lstm/lstmtrainer.h, line 110
Illegal instruction (core dumped)

Please help

**Comment by kamrapooja** [comment]
Issue resolved.

**Comment by AhmadHakami** [comment]
how did you solve it? 

> Issue resolved.
