### ISSUE TITLE
WRITING_DIRECTION_TOP_TO_BOTTOM for English text

### ISSUE THREAD

**Issue by bolyachevets** [tesseract-ocr/tesseract#2506]
**Tesseract Version**: v4.0.0.20181030
**Platform**: Windows 64-bit
**OcrEngineMode**: OEM_LSTM_ONLY 

Does not handle English text with WRITING_DIRECTION_TOP_TO_BOTTOM correctly: treats such text as having ORIENTATION_PAGE_LEFT instead.

![vert_eng](https://user-images.githubusercontent.com/22973013/59811683-e0d56100-92bf-11e9-8899-4652804da779.png)

**Comment by tanyapohn** [comment]
Hi, can you show your output?

**Comment by amitdo** [comment]
To support top to bottom writing in English, a new model need to be trained from scratch using top to bottom writing English images like what was done for Japanese and Chinese.

**Comment by amitdo** [comment]
The issue is not with the program/library itself.
