### ISSUE TITLE
Requisition visual studio 2015 tesseract 3.0 api source

### ISSUE THREAD

**Issue by SangeethaJothi** [tesseract-ocr/tesseract#2508]
Hi, 
We required visual studio 2015 tesseract 3.0 c#.net api source.  We tried with in the following link project files https://github.com/charlesw/tesseract. But we unable to open this project in visual studio 2015 application. Please advice. 

------------------------

### Environment
* **Tesseract Version**: 3.0
* **Platform**:  Windows, version  64-bit

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support
