### ISSUE TITLE
Tesseract 4.00 doesn't recognize "@" in POL language

### ISSUE THREAD

**Issue by FlashT** [tesseract-ocr/tesseract#2509]
### Environment

* **Tesseract Version**: tesseract 4.0.0
* **Platform**: Debian Stretch

### Current Behavior:
Recognizes all "@" as "G", even when it's a screenshot of a text from computer. Only when using POL language. When using ENG, it recognizes it correctly.

### Expected Behavior:
To recognize "@" correctly.

### Suggested Fix:
You tell me :)

**Comment by Shreeshrii** [comment]
You can try https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for--a-few-characters

Read the complete page on training.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/langdata_lstm/blob/master/pol/pol.unicharset

The pol.traineddata does not include `@`, so tesseract can't recognize this symbol.

**Comment by Shreeshrii** [comment]
@FlashT Please try recognition with `-l pol+eng` and check whether it recognizes @ correctly without impacting accuracy for rest of the text.

**Comment by stweil** [comment]
I close this issue because it is not a problem of the tesseract code but a problem of the traineddata.
