### ISSUE TITLE
combine_lang_model crashes sometimes (when called from tesstrain.sh)

### ISSUE THREAD

**Issue by yaroncaspi** [tesseract-ocr/tesseract#2518]
In my training I try to limit the set of punc to almost minimal {, .} 
lang = ara or heb  
------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**: 

### Current Behavior:
combine_lang_model crashes in some cases 

### Suggested Fix:
tesstrain_utils.sh  line 565 uses a temporary  unicharset:

# Build the starter traineddata from the inputs.
  run_command combine_lang_model \
    --input_unicharset "${TRAINING_DIR}/${LANG_CODE}.unicharset" \

In my view a provided unicharset file may work more generally 
i..e  use LANGDATA_ROOT and not TRAINING_DIR

**Comment by zdenop** [comment]
Please provide test case for demonstrating problem. Otherwise your report is not useful. Also report on 1 problem in 1 issue report.

**Comment by stweil** [comment]
@yaroncaspi, could you please answer.
