### ISSUE TITLE
Can't run tesstrain.sh using script/Bengali.traineddata as --lang

### ISSUE THREAD

**Issue by MaRauder111** [tesseract-ocr/tesseract#2519]
> tesseract 4.1.0-rc4
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE

> `/home/j1/tesseract-4.1.0-rc4/src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang Bengali --linedata_only --noextract_font_properties --langdata_dir /home/j1/Intern/langdata-master --tessdata_dir /usr/local/share/tessdata --output_dir /home/j1/Intern/tesstutorial/Bengali --fontlist "Lohit Bengali" "Bangla Medium"`

> `=== Starting training for language 'Bengali'
ERROR: Error: Bengali is not a valid language code
`

**Comment by Shreeshrii** [comment]
Please use `--lang ben` - you can still use script/Bengali later for the starting lstm file.
