### ISSUE TITLE
pdf.ttx is missing 

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#252]
from
https://github.com/tesseract-ocr/tesseract/tree/master/tessdata

**Comment by zdenop** [comment]
And the error message/problem is???

**Comment by Shreeshrii** [comment]
I had problems earlier while opening pdf files that were created without pdf.ttx being present in tessdata. 

But that seems to have been fixed and looks like pdf.ttx is no longer required (I looked at the history ..https://github.com/tesseract-ocr/tesseract/commits/master/tessdata/Makefile.am

**Comment by jbreiden** [comment]
Problem report is incorrect. `pdf.ttx` has never been involved with Tesseract PDF generation. 

`pdf.ttx` is simply a human readable representation of the invisible font. I only use it when trying to figure out font related problems. And I typically generate it when needed; there is no need to distribute with Tesseract at all.

**Comment by amitdo** [comment]
>pdf.ttx has never been required for Tesseract PDF generation... there is no need to distribute with Tesseract at all.

So why we keep GlyphLessFont.h|cpp? It's not even in sync with the updated pdf.ttf.

**Comment by jbreiden** [comment]
You are right, `GlyphLessFont.h|cpp` should be removed. They were important at one time, but are no longer relevant or useful. (Back in the old days, two months ago, the software that converts ttx to ttf and back was not smart enough to handle our font. Now it is.)

**Comment by amitdo** [comment]
@zdenop, could you remove these two files?

**Comment by zdenop** [comment]
Done. See cab6de17400f8147fbbd2a56125ba8c23a730e7a
