### ISSUE TITLE
Exception in thread "main" java.lang.Error: Invalid memory access问题所需的invoke.dll文件如何获取

### ISSUE THREAD

**Issue by yangle9567** [tesseract-ocr/tesseract#2520]
运行TesseractDemo.java报错，Exception in thread "main" java.lang.Error: Invalid memory access改问题经查知需要invoke.dll文件，请问哪位朋友有请提交分享一下，如果有别的解决方案也请跟帖回复，谢谢

**Comment by ymt30** [comment]
Friend how do you solve it
