### ISSUE TITLE
Branch "4.0" provides 5.0.0-alpha

### ISSUE THREAD

**Issue by ponchofiesta** [tesseract-ocr/tesseract#2524]
### Environment

* **Tesseract Version**: 4.0
* **Platform**: Linux XXX 4.4.0-151-generic #178-Ubuntu SMP Tue Jun 11 08:30:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
When checking out Git branch "4.0" I get 5.0.0-alpha. The compiled binary tries to find libtesseract.so.5, which can not be found. Also I build Debian packages from compiled source using checkinstall. Checkinstall says it's version 5.0.0-alpha-29-gc6985.

(Tag "4.0.0" gets version 4 correctly but it misses ALTO support and I need it. Version 4.1 randomly crashes, thus I want to try the hopefully more stable 4.0)

### Expected Behavior:
I should get version 4.0 and it should use and find libtesseract.so.4.

### Suggested Fix:
?

**Comment by stweil** [comment]
Branch 4.0 is unsupported and was superseded by branch 4.1. I suggest to use that one.

**Comment by ponchofiesta** [comment]
Thanks. I should create a new issue focusing the crashes than. At the moment I'm testing a version in between: the last commit by you related to ALTO support from December. If it doesn't crash, the cause is in the following commits.
