### ISSUE TITLE
./configure.ac: line 8: syntax error near unexpected token `[2.63]' ./configure.ac: line 8: `AC_PREREQ([2.63])'

### ISSUE THREAD

**Issue by eravallirao** [tesseract-ocr/tesseract#2529]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract4.00**: 
* **Commit Number**: 
* **MacOS**:

**Comment by eravallirao** [comment]
I am getting this error while running both on Mac OS and Even on Debian platform, Can someone help me

**Comment by stweil** [comment]
Don't run `configure.ac`. It will always fail with that error. Run `autogen.sh` and `configure`. See the [Wiki](https://github.com/tesseract-ocr/tesseract/wiki/Compiling-%E2%80%93-GitInstallation) for details.

**Comment by eravallirao** [comment]
Yeah got it, thank you so much.
