### ISSUE TITLE
Second Guess from LTSM 

### ISSUE THREAD

**Issue by johnnydept** [tesseract-ocr/tesseract#2536]
`api->SetImage(image); 
api->Recognize(0);
api->GetIterator()->GetBestLSTMSymbolChoices(); //get size zero every time..
`

the API returns size 0.
Am i using it correctly?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by noahmetzger** [comment]
try after `api->SetImage(image);`
`api->SetVariable("lstm_choice_mode", "2");`

**Comment by Shreeshrii** [comment]
Thanks. I added it as an example in wiki at

https://github.com/tesseract-ocr/tesseract/wiki/APIExample#new-example-to-get-hocr-ouput-with-alternative-symbol-choices--per-character

**Comment by zdenop** [comment]
I don't think that people using API would bother with hocr (e.g. parsing
xml)...


Zdenko


st 3. 7. 2019 o 11:55 Shreeshrii <notifications@github.com> napísal(a):

**Comment by Shreeshrii** [comment]
@zdenop Please change the example as needed for API to show how to get the alternative confidence values for the symbols.

**Comment by johnnydept** [comment]
Thanks @noahmetzger  @Shreeshrii

**Comment by johnnydept** [comment]
@Shreeshrii 
Thanks for the Example you put on the Wiki there. 
I found something weird.
The Conf given is more than 100 (i get 200)
Also, I assume Whitelist/BlackList Characters are still not supported in tess4.0?

**Comment by Shreeshrii** [comment]
Please crosscheck the results against the HOCR output with same lstm_choice_mode from command line.

The bounding box info is at the WORD level. I don't think that it is available at symbol level in this mode.

@noahmetzger please confirm. Thanks.

**Comment by johnnydept** [comment]
@Shreeshrii 
Somehow i manage to get the Bounding box info through switching iteration (word/symbols)
As for the Conf, I will keep trying. Thanks !

**Comment by Shreeshrii** [comment]
Please share the image for testing.

**Comment by johnnydept** [comment]
Sure ! 
![12](https://user-images.githubusercontent.com/32569157/60641578-f9687e00-9e5e-11e9-80c7-4ffdb2ed6764.jpg)

**Comment by Shreeshrii** [comment]
>The Conf given is more than 100 (i get 200)

I am not able to reproduce that. I get the following output:

```
0  symbol: 'B';  	conf: 100.00; BoundingBox: 6,9,196,61;

1  symbol: 'A';  	conf: 100.00; BoundingBox: 6,9,196,61;

2  symbol: 'S';  	conf: 100.00; BoundingBox: 6,9,196,61;

3  symbol: 'O';  	conf: 90.00; BoundingBox: 6,9,196,61;
3  symbol: '0';  	conf: 9.00; BoundingBox: 6,9,196,61;

4  symbol: 'B';  	conf: 100.00; BoundingBox: 6,9,196,61;

5  symbol: 'C';  	conf: 100.00; BoundingBox: 6,9,196,61;

0  symbol: ' ';  	conf: 100.00; BoundingBox: 233,8,260,58;

1  symbol: '6';  	conf: 82.00; BoundingBox: 233,8,260,58;
1  symbol: 'G';  	conf: 15.00; BoundingBox: 233,8,260,58;
1  symbol: '©';  	conf: 1.00; BoundingBox: 233,8,260,58;
```

**Comment by noahmetzger** [comment]
The 200% indicates the choice that tesseract actually made. It's not always the one with the highest percentage so this can be interesting. I'm currently building a better version of the choice_mode based on the CTC ratings. in this new version the 200% artifact won't be in, as you can also just check the Resultiterator to find out what tesseract has actually chosen.

**Comment by johnnydept** [comment]
@Shreeshrii  @noahmetzger  Thank you for the clarification.

**Comment by Shreeshrii** [comment]
>The 200% indicates the choice that tesseract actually made. It's not always the one with the highest percentage so this can be interesting.

@noahmetzger Do you know whether there are any parameters which control what choice tesseract actually makes?

e..g. An ID may have random letters and numbers in same word. If tesseract gives extra weight to letters in the middle of words then O letter would be preferred to 0 number zero. 

If that is indeed the case, then it would nice to have a parameter (if it does not already exists)  to override this kind of correction.

**Comment by noahmetzger** [comment]
Tesseract does not do choices on single letters. After CTC and Beamsearch there are several paths through the graph of possible nodes. Tesseract chooses the overall best path which also takes dictionary into account. So i don't think theres is an option for inter symbol decisions right now.

**Comment by johnnydept** [comment]
Hi, @noahmetzger ,
is your latest pr, fix the bounding boxes issue?
