### ISSUE TITLE
Issue using "-c tessedit_page_number=1" to process only second page of a multipage tiff G3/G4 compression

### ISSUE THREAD

**Issue by lsabouri74** [tesseract-ocr/tesseract#2537]
### Environment

* **Tesseract Version**: 
tesseract 4.0.0
 leptonica-1.76.0 (May 30 2019, 11:18:56) [MSC v.1916 LIB Release x86]
  libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 2.0.1) : libpng 1.6.37 : libtiff 4.0.10

* **Platform**: 
Windows 10 Enterprise 1903 10.0.18362.175 Client

### Current Behavior:
I am using tesseract to extract text from a multi page tiff image (G3 or G4), but I only want to process the second page. I am using the following command:

tesseract.exe FILE.TIF OUT --tessdata-dir ."\tessdata" -l eng --psm 1 --oem 1 -c tessedit_page_number=1

For some reason it always processes the first page no matter what page number I put in the option. If I remove that option, it processes all the pages. I am attaching a zipped sample tiff file that reproduces the issue.

### Expected Behavior:
I would expect the page I am selecting in the option to be processed.
[18.zip](https://github.com/tesseract-ocr/tesseract/files/3355049/18.zip)

**Comment by stweil** [comment]
The problem already exists in Tesseract 4.0.0.

**Comment by lsabouri74** [comment]
Ok, 
I first asked a question on user forum ([here](https://groups.google.com/forum/#!topic/tesseract-ocr/B1hyeT6OasM)). I was asked to enter an issue here. Should I close it?

**Comment by zdenop** [comment]
No. It should be fixed.

**Comment by stweil** [comment]
My comment regarding 4.0.0 simply should narrow down in which versions of Tesseract the problem exists. A next test is needed with 3.05 or even 3.04 to find out whether some old version worked fine. Maybe someone has an old installation and can test it? If we know that older versions worked, we can find out which code modifications introduced the bug. As @zdenop said, the goal is fixing this issue at least in the latest release.

**Comment by lsabouri74** [comment]
I also reproduced it with 3.05.02. Here is version output:
tesseract 3.05.02
 leptonica-1.74.4 (Aug 27 2018, 16:26:07) [MSC v.1915 LIB Release x86]
  libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.3) : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11

**Comment by lsabouri74** [comment]
It seems to be working fine with 3.04.00. Here is version output:
tesseract 3.04.00
 leptonica-1.71 (Mar 19 2016, 22:28:52) [MSC v.1600 DLL Release x86]
  libgif 4.1.6(?) : libjpeg 8c : libpng 1.4.3 : libtiff 3.9.4 : zlib 1.2.8

Unfortunatelly I don't have other versions at hand.

**Comment by lsabouri74** [comment]
Same issue with 3.05.01. Here is output version:
tesseract 3.05.01
 leptonica-1.74.1
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.5.0) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0

**Comment by lsabouri74** [comment]
It is working with an early 3.05.00dev. Here is output version:
tesseract 3.05.00dev
 leptonica-1.72
  libjpeg 9 : libpng 1.5.14 : libtiff 4.0.3 : zlib 1.2.5 : libopenjp2 2.1.0
