### ISSUE TITLE
Silent ABI change in 3.04.x

### ISSUE THREAD

**Issue by innir** [tesseract-ocr/tesseract#254]
Hi,

if seems, that moving PageIterator* AnalyseLayout() to api/baseapi.h[1] causes a silent ABI breakage. Could you please move it back to api/baseapi.cpp? Please see the corresponding Debian bugs for reference [2], [3].
I could prepare a PR if you prefer. 

Thanks,
Philip

[1] https://github.com/tesseract-ocr/tesseract/blob/master/api/baseapi.h#L500
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816857
[3] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815056#24

**Comment by jbreiden** [comment]
See also the tail end of https://groups.google.com/forum/#!topic/tesseract-dev/8e0F2cK2YzU

**Comment by zdenop** [comment]
Please create PR. Thanks.

**Comment by innir** [comment]
Here you go: PR #259

**Comment by zdenop** [comment]
thanks.

**Comment by jbreiden** [comment]
Please make sure this reaches the 3.04 branch.

**Comment by zdenop** [comment]
done.

Zdenko
