### ISSUE TITLE
RAM is not released when use tesseract in windows 10

### ISSUE THREAD

**Issue by mesajflaviu** [tesseract-ocr/tesseract#2541]
------------------------
If I use tesseract 4.0.0 in VC++/MFC app on Windows 10 and read images, the RAM memory is not released after these images are successfully read.

#246 # Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**: 
* **Platform**: Windows 10, 64bit

### Current Behavior:
Reading images with an VC++ app on and on, the RAM occupied by app that use tesseract is not freed. 

### Expected Behavior:
After images are read, the RAM eaten by app that use tesseract should be freed.

    This issue could easily reproduced by simply use tesseract library to read images on and on. I have made it a simple VS2017 test app that show the bug, and I made an release. Just start the test app (called Tesst.exe), go in File menu, and Load Images item, and choose some images from your PC, and read several images, but do not close the app .. check the RAM.
    Condition: have **tessdata-master** folder in C: (e.g. **C:\\tessdata-master\\**). That is all.

You can find here the source code and release of the test project:
https://onedrive.live.com/?authkey=%21AJAfPxEA6Mmrx94&id=DEDCB6EF190B8FD4%21398&cid=DEDCB6EF190B8FD4

**Comment by zhuangzhuang** [comment]
```cpp
PIX* pix = NULL;
do
{
	// read image
	PIX* pix = pixRead(sFileName);  // <--  this hide pix variable
	if (!pix)
	{
		m_sError.Format(_T("Cannot open input file: %s."), sFileName);
		break;
	}
	// recognize
	m_Tess.SetImage(pix);
} while (FALSE);
pixDestroy(&pix);
```

**Comment by stweil** [comment]
I suggest to enable compiler warnings, then the compiler will tell you what is wrong with your code.

**Comment by mesajflaviu** [comment]
Yes, that was the problem.
