### ISSUE TITLE
Accuracy difference between Tesseract and other 

### ISSUE THREAD

**Issue by Gaploid** [tesseract-ocr/tesseract#2552]
#Environment

* **Tesseract Version**: 4.1

* **Platform**: Windows 10 and Ubuntu 16

I'm using tesseract for a long time and really super thankful for all who supporting and developing it. That's not a post about complaining or something about that. It's more to understand how the results with tesseract can be improved. 

I've tried to compare some output from different OCR providers based on their private tech and it seems the difference currently is huge. Please check it. 

That's a Tesseract result without any preprocessing:
![tesseract_without_preprocess](https://user-images.githubusercontent.com/6171245/60886462-c0fbe200-a25a-11e9-9722-e34f5f3985c8.JPG)

That's a result of Azure OCR service **without** any preprocessing:
![azure_without_preproccess](https://user-images.githubusercontent.com/6171245/60886544-f0aaea00-a25a-11e9-99a8-ce3d75bb2e10.JPG)

That's a Tesseract result **with** any preprocessing:
![tesseract_with_preproccess](https://user-images.githubusercontent.com/6171245/60886568-04565080-a25b-11e9-9cb4-b2419dce1fac.JPG)

Yeah with binarization and some tweaks that result is much better but still, there is a lot of mistakes. 

I see that you guys collecting ideas for version 5.0 and there are my suggestions:
1. It seems tesseract needs some kind of build-in preprocessing of image: binarization, white balancing. noise reduction using OpenCV cause that's the biggest gap comparing to others.   
2. Even with pre-processing, the accuracy is lower compared to other providers. I don't know what's the reason here but definitely should be addressed in future releases.     

Meanwhile, If somebody has ideas about how I can improve accuracy with tesseract you are more then welcome.

**Comment by zdenop** [comment]
IMO you are mixing here several topics. So first let me explain you why your comparison is not correct:
* comparing tesseract to Azure: you are comparing OCR engine (tesseract) with complex [computer vision solution](https://azure.microsoft.com/en-in/services/cognitive-services/computer-vision/). If you want to be faire, you need to compare Azure computer vision with [Google vision](https://cloud.google.com/vision/). Or compare tesseract with other opensource OCR libraries, if you want to get correct picture.
* you are comparing opensource solution with proprietary solution => everybody can use tesseract know-how for free (it use very permissive licence), but nobody has access to proprietary solution for free or under permissive licence.
* you are comparing solution with limited resources (tesseract) with solution of multibilion company with large portfolio of patents, financing a lof of research etc.
* you are comparing solution that you can run localy on your computer with cloud based solution. This has several consequences:
 a) you can get much better computer power/performance on cloud than on local computer
 b) you have absolutely no control (in cloud) of your data and information you asked for analyze.
 
Next topic is about philosophy: tesseract is OCR engine/library. It does one thing and best way as possible. That was reason why image opening and some image processing was changed from own solution to leptonica. There is no aim (and capacity) to extend focus from OCR to image processing. There are other tools for it (e.g. Scantailor for book/documents, or OpenCV). Integration should be done outside of tesseract => as new project.

IMHO here are much more needed tasks like table reconstruction, formatting reconstruction or better document layout  analyze (header, footer, footnotes, titles..)

**Comment by kalai2033** [comment]
@Gaploid Hi, Im also working on preprocessing the images to pass it to Tesseract ocr for improving the accuracy. Would you like to share some knowledge with me? I have done some preprocessing steps like resizing, converting2gray, binarization(otsu+adaptive+binary) in different combinations and i did smoothening and noise removal. Still i couldnt achieve the desired accuracy.
