### ISSUE TITLE
FAIL: ligature_table_test

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#2553]
```
 tesseract -v
tesseract 5.0.0-alpha-258-g7fab
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.4.4 : libopenjp2 2.3.0
```

```
[ RUN      ] LigatureTableTest.DoesAddLigaturesWithSupportedFont
1:ﬁdelity efﬁgy ſteep
2:fidelity effigy ſteep
../../unittest/ligature_table_test.cc:66: Failure
Expected equality of these values:
  kRenderableEngLigatureText
    Which is: "\xEF\xAC\x81" "delity ef\xEF\xAC\x81gy \xC5\xBFteep"
    As Text: "ﬁdelity efﬁgy ſteep"
  lig_table_->AddLigatures(kEngNonLigatureText, &font).c_str()
    Which is: "fidelity effigy \xC5\xBFteep"
    As Text: "fidelity effigy ſteep"
[  FAILED  ] LigatureTableTest.DoesAddLigaturesWithSupportedFont (1 ms)
```

**Comment by Shreeshrii** [comment]
After adding verdana.ttf to tesseract/test/testing, error has changed:

```
[ RUN      ] LigatureTableTest.DoesAddLigaturesWithSupportedFont
1:ﬁdelity efﬁgy ſteep
2:ﬁdelity eﬃgy ſteep
../../unittest/ligature_table_test.cc:66: Failure
Expected equality of these values:
  kRenderableEngLigatureText
    Which is: "\xEF\xAC\x81" "delity ef\xEF\xAC\x81gy \xC5\xBFteep"
    As Text: "ﬁdelity efﬁgy ſteep"
  lig_table_->AddLigatures(kEngNonLigatureText, &font).c_str()
    Which is: "\xEF\xAC\x81" "delity e\xEF\xAC\x83gy \xC5\xBFteep"
    As Text: "ﬁdelity eﬃgy ſteep"
[  FAILED  ] LigatureTableTest.DoesAddLigaturesWithSupportedFont (79 ms)
```

**Comment by stweil** [comment]
You'll need these fonts:

    lrwxrwxrwx 1 debian debian    52 Jan 26 20:42 test/testing/ae_Arab.ttf -> /usr/share/fonts/truetype/fonts-arabeyes/ae_Arab.ttf
    lrwxrwxrwx 1 debian debian    61 Jun 24 10:36 test/testing/Arial_Bold_Italic.ttf -> /usr/share/fonts/truetype/msttcorefonts/Arial_Bold_Italic.ttf
    lrwxrwxrwx 1 debian debian    58 Jun 24 10:52 test/testing/DejaVuSans-ExtraLight.ttf -> /usr/share/fonts/truetype/dejavu/DejaVuSans-ExtraLight.ttf
    -rw-r--r-- 1 debian debian 81484 Sep  9  2009 test/testing/Lohit-Hindi.ttf
    lrwxrwxrwx 1 debian debian    59 Jun 24 10:37 test/testing/Times_New_Roman.ttf -> /usr/share/fonts/truetype/msttcorefonts/Times_New_Roman.ttf
    lrwxrwxrwx 1 debian debian    51 Jan 26 20:41 test/testing/UnBatang.ttf -> /usr/share/fonts/truetype/unfonts-core/UnBatang.ttf
    lrwxrwxrwx 1 debian debian    51 Jan 26 20:38 test/testing/Verdana.ttf -> /usr/share/fonts/truetype/msttcorefonts/Verdana.ttf

Most of them are available as Debian / Ubuntu packages, so symbolic links are sufficient.
Ideally the unit tests should check whether required fonts are available, and `make check` should install missing fonts or create the links. That's still on my to-do list.

**Comment by Shreeshrii** [comment]
Thank you. That worked.
