### ISSUE TITLE
Can anyone recognize this clear Chinese text?

### ISSUE THREAD

**Issue by xwlcn** [tesseract-ocr/tesseract#2557]
version:
tesseract 4.1.0
 leptonica-1.79.0
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8
 Found AVX2
 Found AVX
 Found SSE

![kkkk](https://user-images.githubusercontent.com/15356897/61001123-92345780-a391-11e9-8369-b9a7256b211b.jpg)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Make sure you read fist relevant wiki and searched forum for similar topics.

**Comment by johnnydept** [comment]
> e

not sure if im correct, you need to invert the image ? 
Tess 4 takes dark word\white background.

**Comment by Shreeshrii** [comment]
tesseract  chi_zoe.jpg - -l chi_sim --psm 6 --oem 1

祖 伊 该 上 学 了
Zoe, time for schooll
