### ISSUE TITLE
Giving output as binary data

### ISSUE THREAD

**Issue by swamyaddala** [tesseract-ocr/tesseract#2559]
Tesseract Version : tesseract 4.0.0
                               leptonica-1.76.0
  Platform: Linux kali 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux

Current Behavior: Giving output as following 
                            గౌ॥ శ్రీ యన్‌. కిరణ్‌కుమార్‌ రెడ్డి,
ఆంధ్రప్రదేశ్‌ ముఖ్యమం
I'm using teeseract to identify text for telugu laguage. I have installed telugu for tesseract.

**Comment by Shreeshrii** [comment]
To me it looks like Telugu script. Displays ok in my browser and email on windows 10.

Are you sure you have a Telugu Unicode font installed?

**Comment by swamyaddala** [comment]
> To me it looks like Telugu script. Displays ok in my browser and email on windows 10.
> 
> Are you sure you have a Telugu Unicode font installed?

Thanks it is working now
