### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by prateakb** [tesseract-ocr/tesseract#2564]
[tesseract-Build-20190703-144816.pdf](https://github.com/tesseract-ocr/tesseract/files/3390234/tesseract-Build-20190703-144816.pdf)

I am trying to integrate tesseract into an enterprise workflow and had to a scan for vulnerabilities. I tried scanning tesseract build through nexus vulnerability scanner and got security issues related to:

jquery 1.6.2
bundler 2.0.2
simplecov-html 0.10.2

Have attached the security issues in attached pdf. 

Any idea on what these threats could be? How to resolve them?

**Comment by zdenop** [comment]
Are you serious??? If you want to "integrate" tesseract do you understand what tools/libraries it use.
Hit: it does not use jquery or bundler or simplecov-html...
