### ISSUE TITLE
Adding confidential threshold on output

### ISSUE THREAD

**Issue by zguoguo** [tesseract-ocr/tesseract#2566]
Where can I obtain the degree of confidence that every word tesseract recognized?
------------------------
 I'm dealing with important messages that would better be left as blank than mistakenly translated. I want to set up a threshold to let tesseract output "?" if the degree of confidence for a given word/character is low. Is it possible?

### Environment

* **Tesseract 4.0**
* **ubuntu 64-bit**

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
