### ISSUE TITLE
 Undetection of some characters

### ISSUE THREAD

**Issue by shwandere** [tesseract-ocr/tesseract#257]
Hi,

I am currently working on license plate recognition and for that i am using tesseract3.03 on windows. For the same purpose I have trained the tesseract with 1500 images of alpha numeric characters.When I am testing tesseract for same images then GetUTF8Text returns NULL.Specially mostly for N,M, and W characters.I have attached 3 images as samples. 

As detail, I have set the vaiable PageSegMode="PSM_SINGLE_CHAR".Besides,I have already tried preprocessing and resolution techniques for input image to resolve the problem.

PLEASE HELP!!!

It would be helpful even if I can know the roll of GetUTF8Text in giving the NULL output for an images.
![696](https://cloud.githubusercontent.com/assets/10992866/13593034/c0173e96-e51d-11e5-846e-12a3b46de8d1.jpg)
![742](https://cloud.githubusercontent.com/assets/10992866/13593032/c0129f62-e51d-11e5-833a-89add68d42f8.jpg)
![1022](https://cloud.githubusercontent.com/assets/10992866/13593033/c016d622-e51d-11e5-8bdb-0b335026a415.jpg)

**Comment by zdenop** [comment]
Please use [tesseract user forum](https://groups.google.com/forum/#!forum/tesseract-ocr) for asking support (see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice) )
