### ISSUE TITLE
Tesserct not able to detect text from images containing few letters (2 or 3)

### ISSUE THREAD

**Issue by gtambi143** [tesseract-ocr/tesseract#2570]
For single letter image we have a option "--psm 10" but what about the images which have few letters and that too separated by some space.
Example:
|--------|
| Y     Y  |
|--------|
expected_output = "Y Y"

|-------------|
| Y     Y      Y |               
|-------------|
expected_output = "Y Y Y"

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
And use real images not ascii drawings.
