### ISSUE TITLE
--oem 2 doesnot work with eng.traineddata

### ISSUE THREAD

**Issue by QuickLearner171998** [tesseract-ocr/tesseract#2573]
### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**: 

### Current Behavior: 
D:\OCR\demo_images>tesseract --psm 7 --oem 2 05_02_2019_16_09_0015.jpg 15
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.

**Comment by stweil** [comment]
Maybe we can improve the error message.

**Comment by tandelDipak** [comment]
@QuickLearner171998  found the solution in forum. Check out this discussion https://groups.google.com/g/tesseract-ocr/c/KKTiag0VCFE/m/A4jpS6i6CwAJ

Let me know whether it solves your issue or not.
