### ISSUE TITLE
Training on new fonts without changing the lstm model using finetunned model 

### ISSUE THREAD

**Issue by Idolized22** [tesseract-ocr/tesseract#2575]
* **Tesseract Version**: 4 
* **Commit Number**:  I assume the default one 
* **Platform**: <!-- linux ubuntu 18.04 

I have finetuned  the Hebrew LSTM model and used tesstrain.sh to train  for approximately  3 fonts. 
I am not sure about few things mentioned below: 

1. does the default model  Hebrew model has been trained on the fonts listed in the file [okfonts](https://github.com/tesseract-ocr/langdata_lstm/blob/master/heb/okfonts.txt)?  
2. Is there a way to continue training the model on fonts only keeping the work the lstm achieved   
3. given that i specified my own custom word list while I was  fine tuning the lstm model  has the default word dict been overridden?  
4. while  testing the model,  given that I have specified my own training test and word list during  the lstm training, is it necessary to specify my word custom word_dict  if i want to toggle language_model_penalty_non_dict_word to be true. 

Thanks in Advance

**Comment by Shreeshrii** [comment]
>does the default model Hebrew model has been trained on the fonts listed in the file okfonts?

The models in tessdata_fast and tessdata_best should be trained on the okfonts in langdata_lstm.

>Is there a way to continue training the model on fonts only keeping the work the lstm achieved

I think the option of 'finetune for impact' keeps the original traineddata and makes minimal changes required for a new font.

>given that i specified my own custom word list while I was fine tuning the lstm model has the default word dict been overridden?

The `plusminus` and `replace layer` training allow for custom word lists, and so the original word list will be overridden.

>while testing the model, given that I have specified my own training test and word list during the lstm training, is it necessary to specify my word custom word_dict if i want to toggle language_model_penalty_non_dict_word to be true.

That parameter was effective with Legacy Tesseract. I am not sure how useful it will be with the LSTM models.

**Comment by Shreeshrii** [comment]
@zdenop Please label as question and close.
