### ISSUE TITLE
Error: run sample command for tesstrain.sh on macOS

### ISSUE THREAD

**Issue by wlhjkl** [tesseract-ocr/tesseract#2578]
### Environment

* **Tesseract Version**: 4.1
* **Commit Number**: c8374cc5
* **Platform**: macOS Mojave 10.14.5

### Current Behavior:
run this sample command  : 
$ tesstrain.sh --fonts_dir /Library/Fonts --lang eng --linedata_only   --noextract_font_properties --langdata_dir ../langdata   --tessdata_dir ./tessdata --output_dir ~/tesstutorial/engtrain
my Terminal show ：/usr/local/bin/tesstrain_utils.sh: line 80: syntax error near unexpected token `&'
It looks like a grammatical error. But I delete this token '&' and run again，the command line show ：

![image](https://user-images.githubusercontent.com/4336142/61347814-ea3af480-a890-11e9-9928-d012841b42d5.png)

Floating point exception???

### Expected Behavior:
Can be running...
### Suggested Fix:
None

**Comment by wlhjkl** [comment]
Gcc version:
![image](https://user-images.githubusercontent.com/4336142/61348331-caa4cb80-a892-11e9-9119-f0ab7dc0d0fb.png)

**Comment by stweil** [comment]
The problem with `tesstrain_utils.sh` on macOS is fixed now in Git master,
see commit 467f8f41407e6ea850b0fec998e1a0972c7c1822.
