### ISSUE TITLE
unicharset_extractor error in Centos7.

### ISSUE THREAD

**Issue by andresallo** [tesseract-ocr/tesseract#2582]
Hi, I go to the point, I built the package on a disk with Linux in which the program worked perfectly, then I wanted to implement it on another disk with CentOS 7 minimal and started to give problems, mainly related to the installation of leptonica and tesseract. After advancing I went to fix them I found the main failure, the tesseract can not execute the make install training, because it is commented on the Makefile, because the autogen and the configure that generates it should comment.

I tried to install tesseract as they said in the Wiki (to install it from a repository, but in version 3.04) and now I create the functions that it needs, but it stays in an infinite loop.

`make training`
`unicharset_extractor --output_unicharset "data/unicharset" --norm_mode 1 "data/all-boxes"`

Any ideas?

**Comment by stweil** [comment]
Please use the Tesseract user forum for asking questions. The GitHub issues are the wrong place for this.
