### ISSUE TITLE
Question: Regarding  Error in tessatrain  and Resuming from whre it stopped 

### ISSUE THREAD

**Issue by Idolized22** [tesseract-ocr/tesseract#2585]
* **Tesseract Version**:  Tesseract 4 
* **Commit Number**: 
* **Platform**: linux 18.04 

### Description  and Intro:
I am trying to train tesseract using both tesstrain.sh  and lstmtraining  
my  question is about an error while training using **tesstrain.sh** : 
I have  tried to train the Hebrew model language for a large amount of fonts from [A list of Hebrew fonts from the Open Siddur Project](http://opensiddur.org/tools/fonts/)  which is mentioned under [fonts](https://github.com/tesseract-ocr/tesseract/wiki/Fonts) 
I am running the tesstrain.sh with the following parameters on :  extract_font_properties . 
without --line_data_only  
the command looks like this: 
```
src/training/tesstrain.sh \
--fonts_dir $FONTS_PATH --lang $LANG \
--langdata_dir $LANG_DATA \
--tessdata_dir $TESSDATA \
--output_dir $TRAIN_DATA \
--save_box_tiff \
--training_text $TrainText \
--wordlist $WORDLIST_Train \
--fontlist ["  some fonts as string "]
```

 
I  sorted only good ones in two stages 
 1.  I used python PIllow Model two create an Image of the Hebrew Alphabeth of  all the fonts and removed fonts which there was error In 
 2.  I have used text2image two create a list of valid fonts to use  based on @Shreeshrii  response to [text2image fails to generete box file when enable --find_fonts, not supported on multilingual text #1685](https://github.com/tesseract-ocr/tesseract/issues/1685#issuecomment-398663828)   
Running tesstrain.sh has  resulted  the following error: 

```
> Generated training data for 154 words
> Page 540
> Error during processing.
> ERROR: Program tesseract failed. Abort
```

the error occurred  during  === Phase E: Generating tr files ===
it worth noticing that it  failed to apply some bboxes: with the following massage: 
```
APPLY_BOXES: boxfile line 146/ה ((2030,4563),(2057,4592)): FAILURE! Couldn't find a matching blob
FAIL!
```
though it failed for relatively small amount of bboxes  

My Question is what could have caused this problem ? 

My First Guess was that it was the fonts as 2 fonts has resulted a white page tif image so I removed them from the list then  tried again to train using tesstrain.sh but the exact same error occurred

**Comment by Shreeshrii** [comment]
Are you trying to train for legacy tesseract or the new neuralnet based LSTM?

**Comment by Idolized22** [comment]
> Are you trying to train for legacy tesseract or the new neuralnet based LSTM?

@Shreeshrii  Thanks for the Quick response I am trying to train the new neuarlnet based LSTM , 
But I am also trying to maintain the ability to train for new fonts only  without changing the language model.

**Comment by Shreeshrii** [comment]
>the error occurred during === Phase E: Generating tr files ===

That is part of Legacy model training.

For neuralnet based LSTM models, training is two steps. Use tesstrain.sh to create box/tiff and lstmf files and then run lstmtraining.

https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for-impact
is the option which can train for a new font with minimal change to language model.

**Comment by Idolized22** [comment]
> > the error occurred during === Phase E: Generating tr files ===
> 
> That is part of Legacy model training.
> 
> For neuralnet based LSTM models, training is two steps. Use tesstrain.sh to create box/tiff and lstmf files and then run lstmtraining.
> 
> https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for-impact
> is the option which can train for a new font with minimal change to language model.

@Shreeshrii  Thanks a lot again.
 At  first I am willing to train  the language model  using  approximately 22k lines just for train and approximately 2k lines for validation. 
Based  on your responses I assume that In order to change the language model I need to use  that Option: [fine-tuning-for--a-few-characters](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for--a-few-characters)  or the  [training-just-a-few-layers](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#training-just-a-few-layers) 
I wonder which option is more suitable with respect to my available training  data.    

other then using [fine-tuning-for-impact](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for-impact) method is there a method to train only the first few layer of the network, without in order to improve it's performance on  different fonts  ? 

about the usage of the tesstrain in  [Tesstoutorail](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#tesstutorial) (with respect to all method in the tutorial ) is it necessary to split the data into train and validation ahead or is it done by the tesstrain script automatically  ? 

in order to train  the model for fonts only , when using tesstrain.sh the     --linedata_only ,   should be passed  does  --noextract_font_properties flag should be passed in addtion to the  --linedata_only flag ?

**Comment by Shreeshrii** [comment]
> is it necessary to split the data into train and validation ahead or is it done by the tesstrain script automatically ?

Tesstrain.sh does not do it automatically. You have to split the data.

> when using tesstrain.sh the --linedata_only , should be passed does --noextract_font_properties flag should be passed in addtion to the --linedata_only flag ?

You need both for LSTM training.

```
 --linedata_only \
 --noextract_font_properties \
```

>other then using fine-tuning-for-impact method is there a method to train only the first few layer of the network, without in order to improve it's performance on different fonts ?

No.

**Comment by Idolized22** [comment]
@Shreeshrii  
Thank you very much!
