### ISSUE TITLE
Questrion: How to  Resume Data Creation with Tesstrain  if it get stuck 

### ISSUE THREAD

**Issue by Idolized22** [tesseract-ocr/tesseract#2587]
Version Tesseract 4 
Platform: Linux 18.04
I am trying to create  LSTM Training data with tesstrain.sh and the computer get stuck during that process. 
Is there a way resume from the place it stopped before. so it will not have to render the file each time from the beginning  ? 

Thanks in advance 
Ido

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
