### ISSUE TITLE
Feature Request: Support for New Reiwa Era Character ㋿ in Japanese

### ISSUE THREAD

**Issue by prateek4sep** [tesseract-ocr/tesseract#2588]
With the new Japanese Reiwa Era, there's a new character introduced ㋿ (U+32FF). Support for this character is required.

------------------------

### Environment

* **Tesseract Version**: 4.0
* **Commit Number**: 
* **Platform**: Windows 

### Suggested Fix: Train and Update the current jpn.traineddata file with the new jpn character.

Attached:
1. The input file I used.
2. The character in 6 different fonts for training.
[Reiwa.docx](https://github.com/tesseract-ocr/tesseract/files/3429996/Reiwa.docx)
<img width="604" alt="Reiwa" src="https://user-images.githubusercontent.com/15611237/61850552-3827ac00-aed2-11e9-86f3-d69d683d7343.png">

**Comment by zdenop** [comment]
This is issue tracker for tesseract engine, not for tessdata. Post it to right issue tracker. 
Or do it by yourself:
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for--a-few-characters
