### ISSUE TITLE
In windows10, vs2015 64, to cmake the project  cmake error! 

### ISSUE THREAD

**Issue by xinsuinizhuan** [tesseract-ocr/tesseract#2589]
Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
The C compiler identification is MSVC 19.0.24215.1
The CXX compiler identification is MSVC 19.0.24215.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Configuring tesseract version 5.0.0-alpha...
Checking for module 'lept>=1.74'
  
CMake Error at E:/Program Files/CMake/share/cmake-3.11/Modules/FindPkgConfig.cmake:418 (message):
  A required package was not found
Call Stack (most recent call first):
  E:/Program Files/CMake/share/cmake-3.11/Modules/FindPkgConfig.cmake:585 (_pkg_check_modules_internal)
  CMakeLists.txt:189 (pkg_check_modules)

Configuring incomplete, errors occurred!
See also "I:/OCR/tesseract/tesseract-master/build/CMakeFiles/CMakeOutput.log".

**Comment by stweil** [comment]
Then I suggest to read the error message and install the required package.

**Comment by zdenop** [comment]
actually [current code](https://github.com/tesseract-ocr/tesseract/blob/25f2af9d1d8a7a1fb66fd71ab8d709f5d95ee4f8/CMakeLists.txt#L187) nor l[atest stable release](https://github.com/tesseract-ocr/tesseract/blob/5280bbcade4e2dec5eef439a6e189504c2eadcd9/CMakeLists.txt#L161) should not require PkgConfig...

**Comment by xinsuinizhuan** [comment]
@zdenop do you have a try? when i use current code to compile by cmakes.The errors is still, like below
![1564104434(1)](https://user-images.githubusercontent.com/40679769/61919472-5b149780-af88-11e9-80cb-3680b642e882.jpg)

how to install the find_package modles in windows cmake?

**Comment by zdenop** [comment]
Sorry I expected problem is missing pkg_config is missing.
Your screenshot is showing pkg_config can not find lept library (leptonica), so stopping configuration is correct status.
