### ISSUE TITLE
Non existing Font type error

### ISSUE THREAD

**Issue by PUYANG123** [tesseract-ocr/tesseract#2593]
Current Behavior:
I am running the tutorial (ttps://github.com/tesseract-ocr/tesseract)
I am following these steps:

1.git pull https://github.com/tesseract-ocr/tesseract.git
2.cd tesseract/
3. ./autogen.sh
4. ./configure
5.make
6.sudo make install
7.make training
8.sudo make training-install
After this I am using the training script:
src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only 
--noextract_font_properties --langdata_dir ../langdata 
--tessdata_dir ./tessdata --output_dir ~/tesstutorial/engtrain

I am observing a error as Follows:
[Mon Jul 29 11:09:31 CST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.g8WL54Au6a --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2019-07-29.iDG/eng.URW_Bookman_L_Bold.exp0 --max_pages=0 --font=URW Bookman L Bold --text=./langdata/eng/eng.training_text
Could not find font named 'URW Bookman L Bold'.
Pango suggested font 'Arial'.
Please correct --font arg.
ERROR: Program text2image failed. Abort.
Rendered page 0 to file /tmp/eng-2019-07-29.iDG/eng.Verdana_Bold_Italic.exp0.tif
Rendered page 1 to file /tmp/eng-2019-07-29.iDG/eng.Verdana_Bold_Italic.exp0.tif
Rendering using URW Bookman L Italic
[Mon Jul 29 11:09:32 CST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.g8WL54Au6a --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2019-07-29.iDG/eng.URW_Bookman_L_Italic.exp0 --max_pages=0 --font=URW Bookman L Italic --text=./langdata/eng/eng.training_text
Could not find font named 'URW Bookman L Italic'.
Pango suggested font 'Arial'.
Please correct --font arg.
ERROR: Program text2image failed. Abort.
Rendering using URW Bookman L Bold Italic
[Mon Jul 29 11:09:33 CST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.g8WL54Au6a --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2019-07-29.iDG/eng.URW_Bookman_L_Bold_Italic.exp0 --max_pages=0 --font=URW Bookman L Bold Italic --text=./langdata/eng/eng.training_text
Could not find font named 'URW Bookman L Bold Italic'.
Pango suggested font 'Arial'.
Please correct --font arg.
ERROR: Program text2image failed. Abort.
Rendering using Century Schoolbook L Bold
[Mon Jul 29 11:09:34 CST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.g8WL54Au6a --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2019-07-29.iDG/eng.Century_Schoolbook_L_Bold.exp0 --max_pages=0 --font=Century Schoolbook L Bold --text=./langdata/eng/eng.training_text
Could not find font named 'Century Schoolbook L Bold'.
Pango suggested font 'Arial'.
Please correct --font arg.
ERROR: Program text2image failed. Abort.
Rendering using Century Schoolbook L Italic
[Mon Jul 29 11:09:35 CST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.g8WL54Au6a --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2019-07-29.iDG/eng.Century_Schoolbook_L_Italic.exp0 --max_pages=0 --font=Century Schoolbook L Italic --text=./langdata/eng/eng.training_text
Could not find font named 'Century Schoolbook L Italic'.
Pango suggested font 'Arial'.
Please correct --font arg.
ERROR: Program text2image failed. Abort.
Rendering using Century Schoolbook L Bold Italic
[Mon Jul 29 11:09:36 CST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.g8WL54Au6a --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2019-07-29.iDG/eng.Century_Schoolbook_L_Bold_Italic.exp0 --max_pages=0 --font=Century Schoolbook L Bold Italic --text=./langdata/eng/eng.training_text
Could not find font named 'Century Schoolbook L Bold Italic'.
Pango suggested font 'Arial'.
Please correct --font arg.
ERROR: Program text2image failed. Abort.
Rendering using Century Schoolbook L Medium
[Mon Jul 29 11:09:37 CST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.g8WL54Au6a --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2019-07-29.iDG/eng.Century_Schoolbook_L_Medium.exp0 --max_pages=0 --font=Century Schoolbook L Medium --text=./langdata/eng/eng.training_text
Could not find font named 'Century Schoolbook L Medium'.
Pango suggested font 'Arial'.
Please correct --font arg.
ERROR: Program text2image failed. Abort.
Rendering using DejaVu Sans Ultra-Light
[Mon Jul 29 11:09:38 CST 2019] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.g8WL54Au6a --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2019-07-29.iDG/eng.DejaVu_Sans_Ultra-Light.exp0 --max_pages=0 --font=DejaVu Sans Ultra-Light --text=./langdata/eng/eng.training_text
Rendered page 0 to file /tmp/eng-2019-07-29.iDG/eng.DejaVu_Sans_Ultra-Light.exp0.tif
Rendered page 1 to file /tmp/eng-2019-07-29.iDG/eng.DejaVu_Sans_Ultra-Light.exp0.tif
ERROR: /tmp/eng-2019-07-29.iDG/eng.URW_Bookman_L_Bold.exp0.box does not exist or is not readable

**Comment by zdenop** [comment]
What is not clear on messages like:
```
Could not find font named 'URW Bookman L Italic'.
Could not find font named 'Century Schoolbook L Italic'.
...
```
Do you have installed these font in /usr/share/fonts???

**Comment by PUYANG123** [comment]
how to install  URW Bookman L Italic and Century Schoolbook L Italic

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#one-time-setup-for-tesstutorial

**Comment by PUYANG123** [comment]
I just did it according to that document. I always report missing font types.

> https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#one-time-setup-for-tesstutorial

I just did it according to that document. I always report missing font types as above.

**Comment by zdenop** [comment]
Well, you are responsible for installing  fonts (and respecting its licences) on your system. We are not distributing anything else then tesseract source code.
