### ISSUE TITLE
Pango 1.44 build is broken

### ISSUE THREAD

**Issue by egorpugin** [tesseract-ocr/tesseract#2599]
```
When executing: "[google.tesseract.text2image-master]/src/training/pango_font_info.cpp"
D:/dev/tesseract/src/training/pango_font_info.cpp(330): error C3861: 'pango_fc_font_get_glyph': identifier not found
```

See https://gitlab.gnome.org/GNOME/pango/issues/394
See: https://gitlab.gnome.org/GNOME/pango/blob/master/pango/pangofc-font-private.h#L134

**Comment by amitdo** [comment]
Matthias Clasen @matthiasc

>Looking briefly at the code, it would be better and more correct to use **pango_shape()** to go from a Unicode string to a glyph string that can be measured. But I'll turn this into a deprecation for now


Someone actually contributed code that uses pango_shape(), but Ray didn't like it and disabled it for Linux/BSD/macOS.

https://github.com/tesseract-ocr/tesseract/blob/c58efee4ba991551d0eae801cc33d1b79d8b11cb/src/training/pango_font_info.cpp#L405

**Comment by amitdo** [comment]
>Leaks memory
 
The _WIN32 code uses `pango_glyph_string_new()`
in a loop but never call `pango_glyph_string_free()`

**Comment by amitdo** [comment]
Also, `sizeof(s)` should be replaced with `strlen(s)`.

**Comment by zdenop** [comment]
@egorpugin : is this still valid? I was able to build tesseract with pango 1.44.6 on linux.

**Comment by zdenop** [comment]
@amitdo : IMO if there will be `pango_glyph_string_free()` there is no reason to use `pango_fc_font_get_glyph()` - based on fixme comment it was used because of memory leak.

**Comment by amitdo** [comment]
Probably, unless there are other sources for leaked memory in that code.

**Comment by amitdo** [comment]
>#ifdef _WIN32 // Fixme! Leaks memory **and breaks unittests***.

So it not just a memory leak issue.

**Comment by zdenop** [comment]
Unfortunately he did not specify which test failed because of this. I tried to (setup and) run available unittests without this change, still some of them fails...

**Comment by stweil** [comment]
Failing unittests are usually caused by missing fonts. See here all required fonts:

    $ ls -l test/testing/*ttf
    lrwxrwxrwx 1 debian debian    52 Jan 26  2019 test/testing/ae_Arab.ttf -> /usr/share/fonts/truetype/fonts-arabeyes/ae_Arab.ttf
    lrwxrwxrwx 1 debian debian    61 Jun 24 10:36 test/testing/Arial_Bold_Italic.ttf -> /usr/share/fonts/truetype/msttcorefonts/Arial_Bold_Italic.ttf
    lrwxrwxrwx 1 debian debian    58 Jun 24 10:52 test/testing/DejaVuSans-ExtraLight.ttf -> /usr/share/fonts/truetype/dejavu/DejaVuSans-ExtraLight.ttf
    -rw-r--r-- 1 debian debian 81484 Sep  9  2009 test/testing/Lohit-Hindi.ttf
    lrwxrwxrwx 1 debian debian    59 Jun 24 10:37 test/testing/Times_New_Roman.ttf -> /usr/share/fonts/truetype/msttcorefonts/Times_New_Roman.ttf
    lrwxrwxrwx 1 debian debian    51 Jan 26  2019 test/testing/UnBatang.ttf -> /usr/share/fonts/truetype/unfonts-core/UnBatang.ttf
    lrwxrwxrwx 1 debian debian    51 Jan 26  2019 test/testing/Verdana.ttf -> /usr/share/fonts/truetype/msttcorefonts/Verdana.ttf

**Comment by zdenop** [comment]
I am going step by step and at the moment only 3 tests failed: ligature_table_test,  apiexample_test and stringrenderer_test.

**Comment by stweil** [comment]
Both need those fonts.

**Comment by stweil** [comment]
> Also, sizeof(s) should be replaced with strlen(s).

`sizeof(s)` was fine here.

**Comment by zdenop** [comment]
@stweil : I look at internet and  I found [`g_unichar_to_utf8`](https://github.com/adobe/webkit/blob/067e0a8adb3c27c682d894072098c405fb5ca386/Source/WebCore/platform/graphics/pango/GlyphPageTreeNodePango.cpp#L45R) is used for calculating length for pango_shape. It returns the same length as `strlen(s)`, but I prefer strlen instead of g_unichar_to_utf8...

**Comment by stweil** [comment]
`ligature_table_test` passes when I use the WIN32 code on Linux (but still has memory leaks like before).

`pango_font_info_test` fails in PangoFontInfoTest.CannotRenderInvalidString.

**Comment by zdenop** [comment]
Why is [`pango_font_info_test`](https://github.com/tesseract-ocr/tesseract/blob/master/unittest/pango_font_info_test.cc) build guarded by [TENSORFLOW definition](https://github.com/tesseract-ocr/tesseract/blob/fc629eae3bc7f947e80abfd1f168fd3cbf130d01/unittest/Makefile.am#L169)?

**Comment by stweil** [comment]
It depends (indirectly) on Tensorflow include files:

    unittest/syntaxnet/base.h:28:10: fatal error: tensorflow/core/lib/core/status.h: No such file or directory

**Comment by stweil** [comment]
`pango_fc_font_get_glyph` causes a crash with MacOS on M1. Casting `PangoFont`to `PangoFcFont` does not produce a usable pointer.

I then compared the WIN32 and the Linux code in `PangoFontInfo::CanRenderString` on Linux by running the WIN32 code, too. They give different results for `dotted_circle_glyph`. Only the WIN32 implementation (based on `pango_shape`) finds a dotted circle glyph.

**Comment by stweil** [comment]
I could run `pango_font_info_test`. It passed with the Linux implementation, buts fails with the WIN32 implementation.
