### ISSUE TITLE
Dropped Characters

### ISSUE THREAD

**Issue by johntaves** [tesseract-ocr/tesseract#260]
I am trying to recognize a flawless image. I created the image from a pdf that is all vector, not image. It has no noise, no skew, flawless characters in any DPI that I want.

The recognition from Tesseract sucks. Generally the problem is dropped characters. It seems to randomly ignore perfectly good looking characters.

The screen shot shows the text results in the upper left and the image in the background (only the upper left of the image is visible). The bounding boxes of the results are shown in red on that image. Notice all the missing characters. On this particular image all the characters to the right of what you can see are found and recognized properly. The image consists of a table of information (rows of item #, size, description, and qty). The columns are not nicely aligned (although this example is pretty good). Some rows are separated by a line (this example has a line for each row, and notice that tesseract gives me a bounding box for some of the lines, but not all). I tried removing the lines, but that just changed the set of dropped characters with no rhyme or reason to it. Other images from this same set are very similar but tesseract will drop characters on the right, or whole lines will be missing. I have tried different DPI from 75 to 300, but the results were just as disappointing. 

Can anyone suggest how this might be solved?

![badocr](https://cloud.githubusercontent.com/assets/353400/13625650/bb6524b6-e56e-11e5-9e43-39140ee796c3.png)

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support (see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice)).
Hint: Provide original image you try to OCR not screenshot from you app.
