### ISSUE TITLE
tesstrain.sh

### ISSUE THREAD

**Issue by jayanthnarayana** [tesseract-ocr/tesseract#2601]
Hi,
When i run:
tesseract/src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only --noextract_font_properties --langdata_dir ./langdata --tessdata_dir ./tessdata --fontlist Arial --output_dir ./tesstutorial/engtrain

Ii am getting the error as below
ERROR: /tmp/eng-2019-08-02.hxh/eng.Arial.exp0.tif does not exist or is not readable

can you please help me with this.

**Comment by Shreeshrii** [comment]
Please use forum for asking questions.

Most probably you do not have the font Arial in /usr/share/fonts
