### ISSUE TITLE
blink cmd dialog all the time

### ISSUE THREAD

**Issue by githubyong** [tesseract-ocr/tesseract#2605]
------------------------

### Environment

* **Tesseract Version**:tesseract-ocr-w32-setup-v5.0.0-alpha.20190708
* **Commit Number**: 
* **Platform**:  Windows, 64-bit

### Current Behavior: 
when i cmd "tesseract.exe --help",it resize the cmd dialog and cmd front family;then recoverd after a blink.

**Comment by zdenop** [comment]
What you mean with 

> when i cmd
Do you know, how to work with command line on windows???
