### ISSUE TITLE
Is there any option that the lan.training_text is in the form of imgae?

### ISSUE THREAD

**Issue by Naojen** [tesseract-ocr/tesseract#2607]
I did fine-tuning by adding some words that contained the new characters that I want. Now what I want to know is when we OCRed the document which is not computerized printed but scan image, the accuracy drops. so I thought if we trained the engine even in scan image then the accuracy won't be dropping so much. any suggestion?
And if there is any way that we can feed image instead of lan.training_text, please send me the link

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
