### ISSUE TITLE
PDF generated using tesseract has invalid Xref table. we are unable to open the PDF using PDFSharp.

### ISSUE THREAD

**Issue by arunaktsp** [tesseract-ocr/tesseract#2608]
![current_file_jpeg](https://user-images.githubusercontent.com/53936160/62768691-0824ff00-bab5-11e9-9a68-306c90fe6d70.jpg)

PDF generated using tesseract has invalid Xref table. we are unable to open the PDF using PDFSharp.
The file structure is actually valid per the spec. There are a few things that are odd or unnecessary but it does conform — which is why readers are able to display it.

Here’s what I mean:
At the end of the file we should expect to see a cross reference table (xref)
This should consist of: 
xref open tag
First ObjectId (always 0), object count
List of objects by byte offset and generation number, with an indicator if they are in use (n for used, f for free)
trailer open tag
Size attribute
Reference to the root object
Reference to the info object
startxref open tag
xref byte offset
%%EOF marker
We are seeing exactly this structure, however it is repeated twice:
Tesseract writes objectId 2 which is always the Page list, next it writes the info object, finally the xref/trailer/EOF
For some reason, Tesseract then writes all of this again, repeating the Page list with same ObjectId (2), but creating a new info object and then finishing it off with a new xref/trailer

I believe the problem here is that this would normally be considered an incremental update: the new version of objectId 2 (Pages) would be written into the later xref table, with it’s new offset (which it has been), and the new objects (the info object in the update) would be given a new identifier and included in the updated xref table (again, this has been done).

What’s not clear to me: The pages object and the info object are the same in both cases — there’s no reason tesseract should be writing them twice.
[searchablePDF.pdf](https://github.com/tesseract-ocr/tesseract/files/3485634/searchablePDF.pdf)

There’s also no reason I can see that PdfSharp should be throwing an exception here. Based on the text they provide, I suspect there’s a bug in PdfSharp where they are looking at the first xref table (in my file it contains 319 objects), getting that count and processing the table from the second trailer (which has 320 objects) — and then they run into unexpected characters.

Aside from that I have no idea — both pieces of code are doing odd/wrong things. PdfSharp should be able to handle the incremental update correctly, Tesseract really shouldn’t be writing the second section as it serves no purpose that I can discern, however if you remove the update section, the byte offsets are clearly wrong as the image data becomes corrupted — it may be worthwhile to extract the xref tables side by side and do a comparison to see where they [change.[](url)](url)

**Comment by arunaktsp** [comment]
there were two issue in the generated searchable PDF ,
1. There were two Xref table with invalid byte offset for invalid object,
eg 0000001990 00000 n  this does not have any object in 9th position
2. There were duplicate indirect object found in the file from 1 * 7 we have two entry in the file for each object.

**Comment by jbreiden** [comment]
Completely unexpected. Will take a look. Is it happening with every PDF?

>

**Comment by arunaktsp** [comment]
@jbreiden Yes, it occurs in all the PDF generated using both Version 4.0.0 and 4.1.0

**Comment by jbreiden** [comment]
Hmmm... not observing this problem. Please provide a complete recipe for
reproducing including input files.

Not reproducing with Tesseract 4.0.0 as shipping on Debian.

$ tesseract --version | head -1
tesseract 4.0.0
$ tesseract ./test/testing/phototest.tif /tmp/foo pdf
$ grep -a xref /tmp/foo.pdf
xref
startxref

Not reproducible with Tesseract 4.1.0 which will soon ship with Debian.

$ tesseract --version | head -1
tesseract 4.1.0
$ tesseract ./test/testing/phototest.tif /tmp/bar pdf
$ grep -a xref /tmp/bar.pdf
xref
startxref

Not reproducible with multi-page document.

$ tiffcp phototest.tif phototest.tif multi.tif
$ tesseract multi.tif /tmp/baz pdf
$ grep -a xref /tmp/baz.pdf
xref
startxref

**Comment by jbreiden** [comment]
Looking at  the fax cover sheet example provided, there's a ton of
duplicated objects in there.
Looks like two separate PDF files are jumbled together. When I run
Tesseract from the command
line, I get completely sane results.

$ grep -a obj searchablePDF.pdf  | sort | uniq -c
      2 1 0 obj
      1 18 0 obj
      1 19 0 obj
      1 20 0 obj
      2 2 0 obj
      1 21 0 obj
      1 22 0 obj
      1 23 0 obj
      1 24 0 obj
      1 25 0 obj
      1 26 0 obj
      1 27 0 obj
      1 28 0 obj
      2 3 0 obj
      2 4 0 obj
      2 5 0 obj
      2 6 0 obj
      2 7 0 obj
      2 8 0 obj
     27 endobj

**Comment by jbreiden** [comment]
Best guess is the bad results are coming from someone calling the Tesseract
API
incorrectly. Please try to reproduce the problem with the command line
utility.

**Comment by jbreiden** [comment]
Almost certainly a double call to both BeginDocument() and EndDocument()

**Comment by arunaktsp** [comment]
@jbreiden yes there is problem having both BeginDocument() and EndDocument() in PDFrendered. We have removed the same and PDF is generated as expected without any invalid trailers and Xref tables
