### ISSUE TITLE
Two tesseract commands at the same time blocks each other from finishing

### ISSUE THREAD

**Issue by MoxBe** [tesseract-ocr/tesseract#2609]
### Environment

* **Tesseract Version**:  4.1.0
* **Platform**:  Ubuntu 18.04 

### Current Behavior:
Running two tesseract commands at the same time blocks each other from finishing.
If I run just one tesseract command it finishes in 2 seconds.
If I run two at the same time it doesn't finish for more then 20 seconds, if I cancel one then the other finishes immediately.

### Expected Behavior:
Not to block each other from execution.

### Suggested Fix:
Don't know.

**Comment by Shreeshrii** [comment]
Try running it as

```
OMP_THREAD_LIMIT=1  tesseract  
```

I have found that while openmp is useful during `lstmtraining` it slows down `lstmeval` and `tesseract` on my system. My workaround has been to use `OMP_THREAD_LIMIT=1` before the command.

 If you don't plan to do training, you can try to build tesseract with `--disable-openmp` config option.

**Comment by Shreeshrii** [comment]
Also see https://github.com/tesseract-ocr/tesseract/issues/943

**Comment by MoxBe** [comment]
OMP_THREAD_LIMIT=1 seems to be solution, thank you.
