### ISSUE TITLE
Invalid link in the Wiki.

### ISSUE THREAD

**Issue by Yaoshicn** [tesseract-ocr/tesseract#261]
Hi!
I just found that there is an invalid link in the wiki(Page Home -> Installation -> Linux）
And here is the link:**http://code.google.com/p/tesseract-ocr/downloads/list**
> ## Linux
>
>Tesseract is available directly from many Linux distributions. The package is generally called 'tesseract' >or 'tesseract-ocr' - search your distribution's repositories to find it. Packages are also generally available >for language training data (search the repositories,) but if not you will need to [download the appropriate >training data](http://code.google.com/p/tesseract-ocr/downloads/list), unpack it, and copy the >.traineddata file into the 'tessdata' directory, probably `/usr/share/tesseract-ocr/tessdata` or >`/usr/share/tessdata`.
>
>If Tesseract isn't available for your distribution, or you want to use a newer version than they offer, you >can [compile your own](Compiling). Note that older versions of Tesseract only supported processing .tiff >files.
>

Thanks.

**Comment by zdenop** [comment]
thanks. Fixed
