### ISSUE TITLE
RFC: Remove pages pertaining to old versions of tesseract from wiki

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#2610]
I suggest removing pages pertaining to old versions of tesseract from wiki.

eg. There are multiple pages with instructions for creating box files for tesseract 3.x. These instructions do not apply to tesseract4 and above. Users who follow these and then try to run lstmtraining get unexpected errors.

Here is the current list of wiki pages:

```
Home
4.0 Accuracy and Performance
4.0 Docker Containers
4.0 with LSTM
4.0x Changelog
4.0x Common Errors and Resolutions
AddOns
APIExample
APIExample user_patterns
Command Line Usage
Compiling
Compiling – GitInstallation
ControlParams
Data Files
Data Files Contributions
Data Files in different versions
Data Files in tessdata_fast
Documentation
Downloads
FAQ
FAQ Old
Fix footer
Fonts
ImproveQuality
Make Box Files
Making Box Files 4.0
NeuralNetsInTesseract4.00
Planning
ReadMe
ReleaseNotes
Technical Documentation
TesseractOpenCL
TestingTesseract
The Hallucination Effect
Training Tesseract
Training Tesseract 3.00–3.02
Training Tesseract 3.03–3.05
Training Tesseract – Make Box Files
Training Tesseract – tesstrain.sh
TrainingTesseract
TrainingTesseract 4.00
TrainingTesseract 4.00 Finetune
TrainingTesseract2
UNLV Testing of Tesseract
User App Example
User Projects – 3rdParty
VGSLSpecs
ViewerDebugging
```

**Comment by amitdo** [comment]
An alternative option is to move these pages to a new repo 'legacy-docs'.

**Comment by Shreeshrii** [comment]
@amitdo That is a good idea.

**Comment by stweil** [comment]
The current Wiki uses 5.4 MiB: 2.8 MiB for Git, 2.6 MiB for the current pages, so it is quite small.

What about duplicating the pages into the Tesseract source tree (for example into `doc/wiki`)? We could do that for the master and 3.05 branches, remove non relevant pages, synchronize the pages for releases and get a documentation which hopefully matches the code.

**Comment by Shreeshrii** [comment]
>What about duplicating the pages into the Tesseract source tree (for example into doc/wiki)?

Duplication means that there is possibility of the pages being out of sync with each other. 

I do agree with rest of the suggestion. 

What about moving instead of duplicating the pages ?

**Comment by amitdo** [comment]
As long as the legacy ocr code is not removed, pages like 'Make Box Files' are still relevant.

The question is - should we separate any information about the legacy ocr from the information about lstm, and place them in different location?

**Comment by Shreeshrii** [comment]
[Efficient and effective OCR engine training](https://link.springer.com/article/10.1007/s10032-019-00347-8) could be added to documentation.

International Journal on Document Analysis and Recognition (IJDAR)

pp 1–16| Cite as

Efficient and effective OCR engine training
Authors
Authors and affiliations
Christian ClausnerEmail authorApostolos AntonacopoulosStefan Pletschacher
1.
Open AccessOriginal Paper
First Online: 30 October 2019
175
Downloads

**Comment by Shreeshrii** [comment]
@zdenop 
Please see https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM/_history
The content on 4.0-with-LSTM page has been deleted.

There should be some control or moderation of changes to wiki.

**Comment by Shreeshrii** [comment]
I would also suggest using https://github.com/apps/stale bot to prune out inactive\old issues, though number of days of inactivity can be larger than default of 60.

**Comment by zdenop** [comment]
@Shreeshrii : wiki editing is limited now. I tried to restore page - please check...

**Comment by Shreeshrii** [comment]
Further discussion and next steps at https://github.com/tesseract-ocr/tesseract/issues/2873
