### ISSUE TITLE
Error: the latest tesseract have compilation error on centos7

### ISSUE THREAD

**Issue by Li-Xiao-Yu** [tesseract-ocr/tesseract#2618]
### Environment:

* **Tesseract Version**: the lastest tesseract (git clone from master branch )
* **Commit Number**: 
* **Platform**: uname -a
Linux bogon 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
I am installing Tesseract from source. The platform is centos7 :

          cat  /proc/version
          Linux version 3.10.0-957.21.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc 
          version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Tue Jun 18 16:35:19 UTC 2019

I follow the wiki "Compilation guide for various platforms" steps, and have already installed the dependent librariesthe and the leptonica-1.78.0. But when I started to install tesseract, the step1:  ./autogen.sh, step2:./configure have no mistakes, the step3: make, show the error following:

          /usr/include/c++/4.8.2/functional: In instantiation of '_Res std::function<_Res(_ArgTypes 
          ...)>::operator()(_ArgTypes ...) const [with _Res = void; _ArgTypes = 
          {tesseract::KDPtrPairDec<float, SEAM>}]':
          ../../src/ccutil/genericvector.h:880:7:   required from 'void GenericVector<T>::clear() [with T 
         = tesseract::KDPtrPairDec<float, SEAM>]'
         ../../src/ccutil/genericvector.h:693:9:   required from 'GenericVector<T>::~GenericVector() 
         [with T = tesseract::KDPtrPairDec<float, SEAM>]'
         ../../src/ccutil/genericheap.h:58:7:   required from here
         /usr/include/c++/4.8.2/functional:2471:71: error: no matching function for call to 
         'tesseract::KDPtrPairDec<float, SEAM>::KDPtrPairDec(tesseract::KDPtrPairDec<float, 
         SEAM>)'
         return _M_invoker(_M_functor, std::forward<_ArgTypes>(__args)...);
         ......

                 from /usr/include/c++/4.8.2/algorithm:62,
                 from ../../src/ccutil/genericvector.h:22,
                 from ../../src/ccstruct/blobs.h:30,
                 from ../../src/ccstruct/seam.h:30,
                 from findseam.h:27,
                 from findseam.cpp:22:
        /usr/include/c++/4.8.2/functional:2471:71: error: return-statement with a value, in function  
        returning 'void' [-fpermissive]
        return _M_invoker(_M_functor, std::forward<_ArgTypes>(__args)...);
        ......

         make[2]: *** [findseam.lo] 错误 1
         make[2]: 离开目录“/home/lxy/tesseract/src/wordrec”
         make[1]: *** [all-recursive] 错误 1
         make[1]: 离开目录“/home/lxy/tesseract”
         make: *** [all] 错误 2

I created a new centos7 virtual machine, download source code from https://github.com/tesseract-ocr/tesseract/releases/tag/4.1.0 (4.1.0 Release), successfully installed tesseract-4.1.0 with the same process. 
At the same time, I created a new ubuntu-18.04.2 virtual machine, successfully installed the latest tesseract by git clone from master branch.

I would like to know why the latest tesseract (git clone from master branch) has the above compilation error on centos7.

**Comment by stweil** [comment]
Your compiler is too old. Did you use autoconf or cmake for building?

**Comment by Li-Xiao-Yu** [comment]
> Your compiler is too old. Did you use autoconf or cmake for building?

I have run the command "sudo yum install autoconf automake libtool", it shows:
autoconf-2.69-11.el7.noarch already installed and latest version
automake-1.13.4-3.el7.noarch already installed and latest version
libtool-2.4.2-22.el7_3.x86_64 already installed and latest version

**Comment by Li-Xiao-Yu** [comment]
> Your compiler is too old. Did you use autoconf or cmake for building?

Do you mean the centos7  gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)is too old, I need to update it?

**Comment by zhangdaoyin** [comment]
I also encountered this problem, looking forward to solving it.

**Comment by Shreeshrii** [comment]
Have you tried instructions at https://github.com/tesseract-ocr/tesseract/wiki#centos-fedora-scientificlinux-opensuse-rhel-packages

**Comment by Li-Xiao-Yu** [comment]
I am in a closed Linux environment and cannot update the yum source. @Shreeshrii

**Comment by zdenop** [comment]
@Li-Xiao-Yu: this is not tesseract problem. If you can not use recent compiller, you can not use the latest software...

**Comment by labidashi** [comment]
请问解决了吗,我这也是这个问题

**Comment by Li-Xiao-Yu** [comment]
最新版的不行，之前的版本可以编译安装



发自我的iPhone


------------------ Original ------------------

**Comment by labidashi** [comment]
看来只有用4.1版本了



---Original---

**Comment by herobd** [comment]
The README says GCC 4.8 and above are supported, but I needed to upgrade from 4.8.5.

**Comment by nikhilcms** [comment]
Facing same issue while installation of latest version of tesseract on (gcc version 4.8.5) https://thelinuxcluster.com/2020/02/04/compiling-tesseract-5-0-on-centos-7/.  looking forward to solving it.
