### ISSUE TITLE
Why the chi_sim.charset_size is not equal to my charset size

### ISSUE THREAD

**Issue by yixinuestc** [tesseract-ocr/tesseract#2619]
[remark_layer_training_text.ZIP](https://github.com/tesseract-ocr/tesseract/files/3507818/remark_layer_training_text.ZIP)
[chi_sim.ZIP](https://github.com/tesseract-ocr/tesseract/files/3507819/chi_sim.ZIP)

Environment
Tesseract Version: Tesseract v4.0.0
Commit Number: b498067
Platform: uBuntu 16.04 64bits
Current Behavior:
My unicharset contains some English letters and some Chinese characters, the total number of characters is 71 ( including the space).

I tried to generate the training data in the following ways:

 src/training/tesstrain.sh --fonts_dir /usr/share/fonts --training_text ../training_data/remark_layer_training_text \
--langdata_dir ../langdata_lstm --tessdata_dir ./tessdata --lang chi_sim --linedata_only --exposures "0" \
        --fontlist  "NSimSun" \
        "Times New Roman" \
       "Arial Unicode MS" \
       "SimSun" \
       "Noto Sans CJK SC" \
"Noto Sans Mono CJK SC" \
--workspace_dir ~/share/workspace/tmp \
--save_box_tiff \
--noextract_font_properties --output_dir ~/tesstutorial/remarktrain \
--overwrite

After finished, I found a chi_sim.charset_size=85.txt file,that means the total number of my charset is 85, but my charset number is 71(including space) ,and open the chi_sim.charset_size=85.txt file ,I see the charset number is really 71. I don't know why the  file name indicate the charset number is 85.

I upload the training text file and output folder in the attach files.

Expected Behavior:
The output file  name should be chi_sim.charset_size=71.txt
Suggested Fix:

**Comment by Shreeshrii** [comment]
For CJK scripts, the unicharset is recoded using the file https://github.com/tesseract-ocr/langdata_lstm/blob/master/radical-stroke.txt

In most cases with large unicharsets it will compress the char set to a smaller set.

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesseract/blob/master/src/ccutil/unicharcompress.h#L103

**Comment by yixinuestc** [comment]
You mean it is not effect my final training results?

**Comment by Shreeshrii** [comment]
Thanks for sharing the zip files. I will see if I can reproduce the results.

**Comment by Shreeshrii** [comment]
>I found a chi_sim.charset_size=85.txt file,that means the total number of my charset is 85, but my charset number is 71(including space) ,and open the chi_sim.charset_size=85.txt file ,I see the charset number is really 71. I don't know why the file name indicate the charset number is 85.

For CJK languages the characterset is recoded (unichar compression). For a large number of characters, the recoded characterset will be smaller. In your tests:

original layer training
unicharset 109
charset 106

remark layer training
unicharset 73
charset 85

I tested by combining your original layer text and remark layer text:
combined layer training
unicharset 117
charset 110

So, for CJK languages unicharset and charset will be usually different.

**Comment by Shreeshrii** [comment]
```
0	 
109	<nul>
1	0
2	9
3	8
51,56,78,102	卷
43,67,97	边
4	3
5	m
6	1
7	6
39,59,88	一
51,64,80,105	端
36,58,100	压
54,65,89,101	扁
...
etc
```

The charset file is a readable version of the recoder in the traineddata which shows the mapping between the codes vs actual unicharsets.

eg.  51,64,80,105	端
means that 端 is recoded as multiple codes -  51,64,80,105

**Comment by Shreeshrii** [comment]
This issue can be marked as question and closed.

**Comment by Shreeshrii** [comment]
@stweil unicharcompress.h says

```
// 1 (CJK): Ids of a unicharset with a large number of classes are expressed as
//          a sequence of 3 codes with much fewer values.
//          This is achieved using the Jamo coding for Hangul and the Unicode
//          Radical-Stroke-index for Han.
```

but the generated charset file which is supposed to represent the recoder has sequence of 4 codes at time. See attached samples.

Is it possible to generate a readable version of recoder from the traineddata files to see whether `best` and `f

**Comment by yixinuestc** [comment]
OK.Thank you very much.
