### ISSUE TITLE
error make

### ISSUE THREAD

**Issue by agustoklik** [tesseract-ocr/tesseract#262]
i follow this step,
./autogen.sh
./configure
make
sudo make install
sudo ldconfig

but when i run make, i got error, then i run _autoreconf -i_ after ./autogen.sh , but i got same result
![tesseract](https://cloud.githubusercontent.com/assets/11517390/13629164/3ae1a9be-e612-11e5-9fd5-1b5f7054ce7e.JPG)

what's wrong with this step ?

**Comment by tfmorris** [comment]
Sounds the same as #41

**Comment by zdenop** [comment]
That error means that you are not linking against wrong version of leptonica  library (<1.71). You need to fix your leptonica instalation

**Comment by agustoklik** [comment]
thnks tfmorris and zdenop for the reply, it's very helpful
