### ISSUE TITLE
How can i train pair (text,image), i want training single text with multiple image. How can i do that?

### ISSUE THREAD

**Issue by itsmenmd** [tesseract-ocr/tesseract#2621]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by stweil** [comment]
Please use the user forum for questions.
