### ISSUE TITLE
Tesseract can't read simple text captcha

### ISSUE THREAD

**Issue by DuySexy** [tesseract-ocr/tesseract#2622]
![captcha](https://user-images.githubusercontent.com/24568107/63259027-8cdafe80-c2a7-11e9-8424-c114b634d008.png)

help me. i setup success tesseract on centos 6. but cannot sovle captcha above!

**Comment by DuySexy** [comment]
command: tesseract captcha.png out -l eng --dpi 300 --psm 13 digits

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
