### ISSUE TITLE
OCR not extracting correctly when there are table like structure or grid lines as part of the PDF (Converted Image)

### ISSUE THREAD

**Issue by Badrinp** [tesseract-ocr/tesseract#2623]
Hi,
In my Project we have lots of PDFs, where we need to extract information. So we convert the PDF to Image, then run tesseract OCR to extract the information from Image files.
We have observed, when the information is present in table kind of format or having grid lines, then tesseract output is very unpredictable,

- Many times information doesn't come at all as output
- Many time in output, junk character comes

We are using PSM - 6 while doing tesseract. Do we have any other setting in Tesseract to get the right output or do we need to pre-process images further before feeding it to tesseract engine?

Please suggest.

**Comment by zdenop** [comment]
First of all: creating issue without example files is useless => will be ignored.
Next: How is your issue different to already reported issues?

**Comment by zdenop** [comment]
Duplicate to #1979
