### ISSUE TITLE
Making Box Files problem

### ISSUE THREAD

**Issue by daniel-szwed** [tesseract-ocr/tesseract#2624]
### Environment

* **Tesseract Version**: 4.0.0
* **Platform**: Linux zbierak 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

`tesseract image.png image lstmbox` command gives unexpected output

### Current Behavior:

```
read_params_file: Can't open lstmbox
Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica
Page 1
```

**Comment by zdenop** [comment]
Please use recent tesseract version when reporting issue,

**Comment by krunduev** [comment]
tesseract eng.dict.exp011.tiff eng.dict.exp011 -l eng+rus --oem 1 lstmbox 
read_params_file: Can't open lstmbox
read_params_file: Can't open lstmbox
Tesseract Open Source OCR Engine v5.0.0-alpha-843-g6617 with Leptonica
Page 1

**Comment by zdenop** [comment]
> read_params_file: Can't open lstmbox 
fix your installation.
