### ISSUE TITLE
Install new language to be recognized by Tesseract 

### ISSUE THREAD

**Issue by argideritzalpea** [tesseract-ocr/tesseract#2628]
I cannot find documentation with regard to installing a new language that I have trained.

My languages are installed at the path: `/usr/local/Cellar/tesseract-lang/4.0.0/share/tessdata`
This is where `brew install tesseract-lang` installs languages.

When I type `tesseract --list-langs`, I do indeed see a list of all the officially released languages. 

However, I have made a folder for a custom prefixed language I have trained ("men" for Mende) containing `men.traineddata` at the path `/usr/local/Cellar/tesseract-lang/4.0.0/share/tessdata`. However, `tesseract --list-langs` does not register the new language.

What additional steps do I need to do to get tesseract to register this new language? My brew-installed `tesseract` is called from `/usr/local/Cellar/tesseract/4.1.0`. Is there a file in here I must change to get it to register the newly added language?

**Comment by stweil** [comment]
Install in `/usr/local/share/tessdata`. And please use the Tesseract user forum for asking questions, not the GitHub issues.
