### ISSUE TITLE
Release 4.1.0 does not build on Alpine due to 'timeval'

### ISSUE THREAD

**Issue by gamma** [tesseract-ocr/tesseract#2632]
### Environment

* **Tesseract Version**: 4.1.0
* **Commit Number**: 5280bbcade4e2dec5eef439a6e189504c2eadcd9
* **Platform**: alpine 3.8

### Current Behavior:

    In file included from control.cpp:37:0:
    ../../src/ccutil/ocrclass.h:117:18: error: field 'end_time' has incomplete type 'timeval'
       struct timeval end_time;

The 'timeval' seems to be part of WIN32 as per

    #ifdef _WIN32
    #include <winsock2.h> // for timeval

### Expected Behavior:

It builds.

### Suggested Fix:

There is already a fix in place which is not part of the 4.1.0 release. see 1948f0d520b712e13820acc28024f949dead2b01

**Comment by stweil** [comment]
That fix cannot be used for 4.1 because it changes the API.

**Comment by zdenop** [comment]
Tesseract builds without any problem on most used linux distribution(Debian, Ubuntu, openSUSE...), + Mac and Windows OS.  
As far as I understand you use [alpinelinux](https://www.alpinelinux.org/). timeval is [standard part of linux](https://pubs.opengroup.org/onlinepubs/7908799/xsh/systime.h.html) and it seems that alpinelinux did some modification so  the relevant header file is not used automatically (comparing to above mention linux distribution). Similar problems have other [alpinelinux users](https://stackoverflow.com/questions/35614923/errors-compiling-mesos-on-alpine-linux) (just search "alpinelinux timeval").

**Comment by gamma** [comment]
Thanks for pointing that out. I create a patch for my build environment.
