### ISSUE TITLE
ERROR: Could not find training text file langdata_lstm/fra/fra.training_text

### ISSUE THREAD

**Issue by Bech007** [tesseract-ocr/tesseract#2633]
hi 
i want to train tesseract on the new fonts Dot Matrix but i have this error 
plz any one help me what is this error and how i can fix it 
thank 
ERROR
#############
[root@fe1f07b2e114 langdata_lstm]# sh /home/OCR_TESS/generate_training_data.sh

=== Starting training for language 'fra'
[Fri Aug 30 11:04:58 UTC 2019] /usr/bin/text2image --fonts_dir=/usr/share/fonts/default/Type1/ --font=DotMatrix weight=101 --outputbase=/tmp/font_tmp.7LVcGUEM7J/sample_text.txt --text=/tmp/font_tmp.7LVcGUEM7J/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.7LVcGUEM7J
Rendered page 0 to file /tmp/font_tmp.7LVcGUEM7J/sample_text.txt.tif
Rtl = 0 ,vertical=0

=== Phase I: Generating training images ===
ERROR: Could not find training text file langdata_lstm/fra/fra.training_text
#############

![Capture](https://user-images.githubusercontent.com/17314477/64016891-7135ea80-cb28-11e9-8e5d-f1a3fd0cc77e.JPG)
@Shreeshrii  @amitdo

**Comment by Shreeshrii** [comment]
You are using a custom script for training - sh /home/OCR_TESS/generate_training_data.sh
We do not support 3rd party sw.

Follow the tutorial - https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for-impact

**Comment by Bech007** [comment]
thank you @Shreeshrii 
an other think please,
 how i can create the paire box/tiff with the font dotmatrix  from text file ??

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by Bech007** [comment]
@zdenop  
give me the link of tesseract user forum plz
