### ISSUE TITLE
ERROR: /tmp/eng-2019-09-02.1pC/eng.Dot Matrix.exp0.lstmf does not exist or is not readable

### ISSUE THREAD

**Issue by Bech007** [tesseract-ocr/tesseract#2637]
Hi i have this error when i want to train tesseract new font how fix them plz
thank !
![Capture](https://user-images.githubusercontent.com/17314477/64127598-9d649c00-cdb2-11e9-85b4-82fa539024a9.JPG)

**Comment by Shreeshrii** [comment]
You need https://github.com/tesseract-ocr/tesseract/blob/master/tessdata/configs/lstm.train

**Comment by Shreeshrii** [comment]
@stweil I thought some recent changes had made the configs easily accessible via submodule.

Missing lstm.train is a recurring error in many problem reports. How do we fix it?

**Comment by stweil** [comment]
The `tessconfigs` submodule was added for `tessdata_fast`, but not for `tessdata` and `tessdata_best`. This is fixed now. Users still have to make sure that they got the submodule.

**Comment by stweil** [comment]
The question was answered, so I close this issue. Please use the user forum for additional questions.
