### ISSUE TITLE
Differing output when using config file from print-parameters

### ISSUE THREAD

**Issue by jtlz2** [tesseract-ocr/tesseract#2638]
### Environment

* **Tesseract Version**: 4.1.0
* **Commit Number**: [executed: brew install tesseract]
* **Platform**: macOS High Sierra 10.13.6 / Darwin redacted.office 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64

### Current Behaviour:

For the small png [here](https://filebin.net/goyhpfrugggw59sa), output differs between the following two operations, with (A) better than (B). (B) is required, but at (A)'s performance.

Ground Truth:

`Account`

**Case A (no config file):**

`tesseract -v test.png test`

```
tesseract 4.1.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.3 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
Tesseract Open Source OCR Engine v4.1.0 with Leptonica
```

`cat test.txt`

```
Account
^L
```

**Case B (using config file, which is obviously desirable):**

```
tesseract --print-parameters > tess_default.cfg
tesseract -v test.png test test_default.cfg
```

```
ccot
^L      Page separator (default is form feed control character)
```

### Expected Behaviour:

I believe the output should be the same in both cases, but it is not. **Case A** is correct, but **Case B** is not.

### Suggested Fix:

That's why I'm posting....

**Comment by zdenop** [comment]
Closing as tesseract works as expected and issue reporter expect something that does not work (and was never plan to work neither documented)

**Comment by jtlz2** [comment]
@zdenop Why, then, are the results different, and how does one discover what parameters (of the 660) Tesseract is using at any given time?
