### ISSUE TITLE
Compiled 3.03 and 3.04 with VS2013, Memory Leaks detected

### ISSUE THREAD

**Issue by nj96** [tesseract-ocr/tesseract#264]
I've worked with the library in the past when I was working with VS2008 and the precompiled binaries but now that I've been using VS2013 I cannot seem to get the library to work without some sort of memory leak detected at the end of my application's runtime.

Run the application with no calls to the library and no leaks detected.

Run the application with this code:

---

tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI;
delete api;

---

And here is the output when the application wraps up:

---

Detected memory leaks!
Dumping objects ->
{65747} normal block at 0x035DC108, 512 bytes long.
 Data: <0 3   3   3   3 > 30 D3 33 01 D8 E3 33 01 C0 E4 33 01 C0 E9 33 01 

{65746} normal block at 0x035DBEC8, 512 bytes long.
 Data: <  3 x 3   3 < 3 > 8C D0 33 01 78 D0 33 01 F4 D1 33 01 3C D8 33 01 

{203} normal block at 0x00BDAFD0, 32 bytes long.
 Data: <  3   3  x6  w6 > F8 D3 33 01 F8 E2 33 01 14 78 36 01 C0 77 36 01 

{198} normal block at 0x00BDADE0, 256 bytes long.
 Data: <  3   3   3 ` 3 > EC CF 33 01 B0 CF 33 01 08 D0 33 01 60 D0 33 01 

{170} normal block at 0x00BDA9C8, 80 bytes long.
 Data: <    @           > 00 00 00 00 40 00 00 00 E0 AD BD 00 00 00 00 00 

Object dump complete.

---

The block sizes are consistent for this test each time it runs.  If I make calls to the library the number of leaks increases with varying block sizes.

Any help is greatly appreciated.  I would hate to have to go back to VS2008 just to be able to use the precompiled binaries.

Thanks a bunch!

**Comment by zdenop** [comment]
Which version/commit you use?
Can you do more analysis and send a fix/patch)?
Main development is done on linux and windows developer is needed

**Comment by desteban1976** [comment]
I followed the directions here: [http://vorba.ch/2014/tesseract-3.03-vs2013.html](http://vorba.ch/2014/tesseract-3.03-vs2013.html).  Everything compiled smoothly but same result.

I would love to help with the development but I've been working on this for a few weeks and I just really can't put any more time into it due to family obligations.  Sorry.

I think I'm going to have to end up using the tesseract-dll.exe cmd line application to do the dirty work (seems to not have the issues I am having with the windows app) and move on.

**Comment by vanillycpp** [comment]
Hi have the saim problem but only in mfc project
in console project no leaks detected

here is the VLD log

`---------- Block 65682 at 0x05A705C8: 512 bytes ----------
  Leak Hash: 0xB9C6E0DA, Count: 1, Total 512 bytes
  Call Stack (TID 25176):
    ntdll.dll!RtlAllocateHeap()
    f:\dd\vctools\vc7libs\ship\atlmfc\src\mfc\afxmem.cpp (336): PokeGuiManage.exe!operator new[]() + 0x9 bytes
    c:\vanilly\dev\tesseract1\ccutil\genericvector.h (626): PokeGuiManage.exe!GenericVector<tesseract::BoolParam *>::reserve() + 0x19 bytes
    c:\vanilly\dev\tesseract1\ccutil\genericvector.h (642): PokeGuiManage.exe!GenericVector<tesseract::BoolParam *>::double_the_size()
    c:\vanilly\dev\tesseract1\ccutil\genericvector.h (741): PokeGuiManage.exe!GenericVector<tesseract::BoolParam *>::push_back()
    c:\vanilly\dev\tesseract1\ccutil\params.h (175): PokeGuiManage.exe!tesseract::BoolParam::BoolParam()
    c:\vanilly\dev\tesseract1\textord\oldbasel.cpp (39): PokeGuiManage.exe!`dynamic initializer for 'textord_oldbl_debug''() + 0x21 bytes
    d:\th\minkernel\crts\ucrt\src\appcrt\startup\initterm.cpp (22): PokeGuiManage.exe!_initterm()
    f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (221): PokeGuiManage.exe!__scrt_common_main_seh() + 0xF bytes
    f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (300): PokeGuiManage.exe!__scrt_common_main()
    f:\dd\vctools\crt\vcstartup\src\startup\exe_wwinmain.cpp (17): PokeGuiManage.exe!wWinMainCRTStartup()
    kernel32.dll!BaseThreadInitThunk() + 0x12 bytes
    ntdll.dll!RtlInitializeExceptionChain() + 0xEF bytes
    ntdll.dll!RtlInitializeExceptionChain() + 0xC2 bytes
  Data:
    C4 0F B5 01    9C C0 B8 01    D4 C0 B8 01    68 C1 B8 01     ........ ....h...
    7C C2 B8 01    20 C2 B8 01    64 C2 B8 01    3C C2 B8 01     |....... d...<...
    1C C7 B8 01    E8 C6 B8 01    C8 D1 D0 01    A4 D5 D0 01     ........ ........
    FC D5 D0 01    D0 D7 D0 01    88 D7 D0 01    74 D7 D0 01     ........ ....t...
    EC D7 D0 01    48 D7 D0 01    74 E3 D0 01    54 E6 D0 01     ....H... t...T...
    B8 E7 D0 01    64 EA D0 01    8C E7 D0 01    24 E9 D0 01     ....d... ....$...
    CC E7 D0 01    24 E8 D0 01    30 EB D0 01    1C EC D0 01     ....$... 0.......
    FC E9 D0 01    F0 EB D0 01    F8 EA D0 01    E0 EA D0 01     ........ ........
    50 EA D0 01    CC EA D0 01    3C E9 D0 01    74 EB D0 01     P....... <...t...
    10 EA D0 01    80 EC D0 01    34 EE D0 01    10 EE D0 01     ........ 4.......
    5C EE D0 01    DC EF D0 01    F4 EF D0 01    48 F1 D0 01     \....... ....H...
    68 F2 D0 01    00 F3 D0 01    E4 F2 D0 01    14 F3 D0 01     h....... ........
    40 F3 D0 01    CC F2 D0 01    4C F6 D0 01    68 F6 D0 01     @....... L...h...
    7C F6 D0 01    E8 F8 D0 01    6C FB D0 01    EC FA D0 01     |....... l.......
    40 FB D0 01    7C FA D0 01    D0 FA D0 01    08 FB D0 01     @...|... ........
    BC FA D0 01    24 FB D0 01    84 FB D0 01    14 FE D0 01     ....$... ........


Visual Leak Detector detected 5 memory leaks (1572 bytes).
Largest number used: 3188036 bytes.
Total allocations: 3297978 bytes.
Visual Leak Detector is now exiting.`

**Comment by amitdo** [comment]
Fixed in #449
