### ISSUE TITLE
Tesseract often recognizes a character incorrectly with the previous character in the ascii table

### ISSUE THREAD

**Issue by AyushP123** [tesseract-ocr/tesseract#2640]
Tesseract Version: 4.1.0

I fine tuned Tesseract on a custom dataset. While testing the new "eng.traineddata" model I observed that often 'F' is being recognized as 'E', 'N' is being recognized as 'M' and 9 is being recognized as 8. I unpacked the traineddata and saw that the corresponding 'eng.lstm-unicharset' contains all the latin characters. I am confused on how to solve this.

**Comment by zdenop** [comment]
First of all: we do not support custom training here - use tesseract user forum for asking support.
Next: nobody will help you with such report - nobody can reproduce it, there is no test case...

**Comment by stweil** [comment]
@zdenop, training Tesseract is very important as we all know that the current official models can be improved. You are right: we need reproducible training processes, especially to examine bug reports like the above one. @AyushP123, is it possible to publish your data set and the details of the training?

**Comment by Shreeshrii** [comment]
Related post by @AyushP123 in forum - https://groups.google.com/forum/#!topic/tesseract-ocr/be4-rjvY2tQ

**Comment by zdenop** [comment]
@stweil: IMO unless it is proved that error is in tesseract or its docs, there is no reason to create issue.

**Comment by amitdo** [comment]
Tesseract often recognizes a character incorrectly with the previous character in the ascii table

 >often 'F' is being recognized as 'E', 'N' is being recognized as 'M' and 9 is being recognized as 8.

It's unlikely that the misrecognition is caused by alphabetic order. The symbols you mentioned are just similar. If you have too many OCR errors it's a sign that something in your training process is wrong (data or parameters).

**Comment by AyushP123** [comment]
@zdenop: Sorry for posting this question here, will make sure that I post my questions to the tesseract-ocr google group.

@Shreeshrii, @amitdo, @stweil: Thanks for your responses. The issue indeed was about over-fitting on the training data.
