### ISSUE TITLE
Tesseract is very poor on single line images

### ISSUE THREAD

**Issue by Mohamed209** [tesseract-ocr/tesseract#2644]
i am running tesseract on some images to extract text in it , although images preprocessing seems optimal , tesseract cant detect any character in these images although i have tried different PSM and resizing options and i tried to finetune the model with such images type but also no results
check images below 
![0crp](https://user-images.githubusercontent.com/12018493/64711738-69782d80-d4ba-11e9-80d2-23184f8c287b.jpg)
![2crp](https://user-images.githubusercontent.com/12018493/64711740-69782d80-d4ba-11e9-8d92-10b024160508.jpg)
![3crp](https://user-images.githubusercontent.com/12018493/64711742-6a10c400-d4ba-11e9-934f-b0e8a034e78c.jpg)
![4crp](https://user-images.githubusercontent.com/12018493/64711747-6a10c400-d4ba-11e9-9201-24bf3065faa4.jpg)
![5crp](https://user-images.githubusercontent.com/12018493/64711750-6aa95a80-d4ba-11e9-9493-9b6e68b07205.jpg)
![6crp](https://user-images.githubusercontent.com/12018493/64711751-6aa95a80-d4ba-11e9-8462-3192791256c6.jpg)
![7crp](https://user-images.githubusercontent.com/12018493/64711752-6b41f100-d4ba-11e9-80b6-b8ba4ac3c71b.jpg)
does this issue related to inverting the image , because the original images were something like that
![6](https://user-images.githubusercontent.com/12018493/64712155-08048e80-d4bb-11e9-8666-eca1589e9f3d.jpg)
![IMG_20190215_225818](https://user-images.githubusercontent.com/12018493/64712166-0c30ac00-d4bb-11e9-98f3-97e862ac1dd7.jpg)
tesseract 4 and newer doesnot detect white text on black background , so i crop the black part invert it and send it to the engine , but no results

**Comment by stweil** [comment]
Well, at least some characters are recognized:

    $ tesseract 64711738-69782d80-d4ba-11e9-80d2-23184f8c287b.jpg - --psm 7 -l tessdata_best/script/Latin
    Warning: Invalid resolution 0 dpi. Using 70 instead.
    w Tota e R

**Comment by Mohamed209** [comment]
@stweil i was thinking that the image is to easy , the application that i am working on needs all characters to be extracted correctly

**Comment by zdenop** [comment]
I am affraid tesseract works according rule: "Bad in - bad out":
![cropped_total](https://user-images.githubusercontent.com/574156/64723352-abac6980-d4d0-11e9-9093-b27b9e798e45.png)
```
tesseract cropped_total.png - --psm 6
Total Due: 60.
```

![cropped_total2](https://user-images.githubusercontent.com/574156/64723385-bd8e0c80-d4d0-11e9-9c5b-e2ef43d0519e.png)
```
tesseract cropped_total2.png - --psm 6
Total Due: 297.50
```

**Comment by zdenop** [comment]
I used tesseract 5.0.0-alpha-329-gc5a50 and tessdata_best.
IMO preprocessing is more useful than training (especially if you are able to do text detection outside of tesseract is cases like you shown here)

**Comment by Mohamed209** [comment]
@zdenop but it is not practical to just fit the text without any borders , although after many preprocessing some horizontal or vertical lines / blobs may residue in the image 
do you see downgrading to versions that supports white text on black background may help

**Comment by zdenop** [comment]
Then tesseract is not right tool for you task. Tesseract needs straight text without border& graphics elements (+ 4.x version need black text on white background after thresholding) to provide good result. It is not bug, it is requirement.

**Comment by NguyenThaiHoc1** [comment]
@zdenop  you can share which your code preprocess I would like to learn more from your code
Thank you for reading
Thai Hoc

**Comment by Mohamed209** [comment]
@NguyenThaiHoc1 i have made all preprocessing , he just manually cropped the image to remove black borders
