### ISSUE TITLE
Changelog not updated after  2014-02-04 v3.03

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#265]
https://github.com/tesseract-ocr/tesseract/blob/master/ChangeLog
is updated only till 2014-02-04 v3.03

Should the changelog also reflect the changes in the current development (master branch) eg. TSV output as new features are added?

**Comment by zdenop** [comment]
fixed with ddd3cad8c6802d016a48aa21e6303e8004d50955
