### ISSUE TITLE
text2image - Error: Call PrepareToWrite before WriteTesseractBoxFile!!

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#2656]
In cases where the font does not have full coverage for the training_text, text2image fails to write in box file in some cases. It seems to depend on the number of characters rendered.

For example for following text line, tifs are created for all 3 but box file is not created for Font Unikurd Web.

` … ḍāhāḽiyā -- kā vajrakīṭa cārlsa, |`

Font Unikurd Web

![eng errors Unikurd_Web exp0](https://user-images.githubusercontent.com/5095331/65045706-ebfe6280-d97c-11e9-8dfd-3b7c3577fe53.png)

Font Lohit Hindi

![eng errors Lohit_Hindi exp0](https://user-images.githubusercontent.com/5095331/65045717-ef91e980-d97c-11e9-9299-210fbd886528.png)

Font Arial

![eng errors Arial exp0](https://user-images.githubusercontent.com/5095331/65045726-f3257080-d97c-11e9-8cd2-c6f2b4d61dad.png)

Error is:

```
ubuntu@tesseract-ocr:~/Sorani$ fontname="Unikurd Web"
ubuntu@tesseract-ocr:~/Sorani$ OMP_THREAD_LIMIT=1   text2image  --strip_unrenderable_words --xsize=3000 --ysize=300  --leading=32 --margin=12  --char_spacing=0.0 --exposure=0  --max_pages=0  --fonts_dir=/home/ubuntu/.fonts --font="$fontname" --text="$f".training_text  --outputbase="$f.${fontname// /_}.exp0"
Stripped 5 unrenderable words
Rendered page 0 to file eng.errors.Unikurd_Web.exp0.tif
Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!
```

[eng.errors.zip](https://github.com/tesseract-ocr/tesseract/files/3621613/eng.errors.zip)

**Comment by Shreeshrii** [comment]
[eng.errors.zip](https://github.com/tesseract-ocr/tesseract/files/3621554/eng.errors.zip)

zip file attached.

**Comment by Shreeshrii** [comment]
A larger text file gets the error with Lohit Hindi also.

text
```
Blog between its (€ was Travel would (Cited) Help (Fig. NEWS Shopping not not 15¢ PC of MySQL
De Civitate.
S﻿ãcta dei ſpernãt poſita decreta pauoꝛe:
laḽā vīrudha¹⁴ cāmuṇḍe sarvajanān rājño 
were was Information NY site 4, Wikipedia such {/if} up have Please » > years is I FREE was <a
… ḍāhāḽiyā -- kā vajrakīṭa cārlsa, |
```

error
```
ubuntu@tesseract-ocr:~/Sorani$ OMP_THREAD_LIMIT=1   text2image  --strip_unrenderable_words --xsize=3000 --ysize=600  --leading=12 --margin=12  --char_spacing=0.0 --exposure=0  --max_pages=0  --fonts_dir=/home/ubuntu/.fonts --font="$fontname" --text="$f".training_text  --outputbase="$f.${fontname// /_}.exp0"
Stripped 52 unrenderable words
Rendered page 0 to file eng.errors.Lohit_Hindi.exp0.tif
Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!
```

generated image

![eng errors Lohit_Hindi exp0](https://user-images.githubusercontent.com/5095331/65047205-abecaf00-d97f-11e9-9cb8-b77dce701097.png)

**Comment by Shreeshrii** [comment]
Duplicate https://github.com/tesseract-ocr/tesseract/issues/1902

**Comment by Ganesh9100** [comment]
**Its just a page error, increase the max_page to some high positive integers... in this command**, ( !rm -rf train/*
! /content/drive/MyDrive/train_tesseract/hindi/tesseract/src/training/tesstrain.sh --fonts_dir fonts \
	--fontlist '{font_name}' \
	--lang hin \
	--linedata_only \
	--langdata_dir /content/drive/MyDrive/train_tesseract/hindi/langdata_lstm \
	--tessdata_dir /content/drive/MyDrive/train_tesseract/hindi/tesseract/tessdata \
	--save_box_tiff \
	--maxpages 10000 \
	--output_dir train ) **the default is 10**
