### ISSUE TITLE
Is there any way to load custom tesseract model in "In-Memory"?

### ISSUE THREAD

**Issue by 24121987** [tesseract-ocr/tesseract#2658]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment 

* **Tesseract Version**: release 4.1.0 from 07 July 2019
* **Commit Number**: 
* **Platform**: Linux 64 bit Ubuntu

### Current Behavior: eng., tessdata_Best
Is there any way to load model(tesseract custom model) at ones instead of loading every time? 
### Expected Behavior: 
We have pass every time model name while predicating the text from images. So I want to know any way to load tesseract custom generated model  in "in-Memory" and predict faster

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by 24121987** [comment]
thank you.
