### ISSUE TITLE
text recognition failed after installed torch and torchvision

### ISSUE THREAD

**Issue by cloudhuang** [tesseract-ocr/tesseract#2659]
### Environment

* **Tesseract Version**: Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica
* **Platform**: Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica
* **Python Version**: Python 3.7.3
* **torch and torchvision Version**:
```
$ pip list | grep torch
torch                              1.2.0      
torchvision                        0.4.0    
```

**This really interestion as I can use tessearct success before I install the torch and torchvision, but after install the torch and trochvision, it throw no module named torchvision, but actually I can import the torchvision in python env **

### Current Behavior:
I add the logs as below:
```
# lhuang @ thinkcentre in ~/Development/Research/ocr (base) [17:09:44] 
$ tesseract image_screenshot_18.09.2019.png output       
Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica

# lhuang @ thinkcentre in ~/Development/Research/ocr (base) [17:09:56] 
$ more output.txt 
ImportError: No module named torchvision

```

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects (tesseract ocr process run without python)
