### ISSUE TITLE
I still have "a" and "o" vowels replaced by unicode ordinal indicators for Portuguese language 

### ISSUE THREAD

**Issue by jurusbr** [tesseract-ocr/tesseract#2664]
**Environment**: 
Tesseract Version: 4.0.0 
leptonica-1.76.0
Platform: ubuntu 19.04
Data: por.traineddata from https://github.com/tesseract-ocr/tessdata_best

**Current Behavior:**
All the vowels "o" and "a" are translated as the ordinal indicator "º" and  "ª"  similar to what's mentioned in this bug report #1084 and #2405 (now closeds)

**Expected Behavior:**
All vowels "o" and"a" as is.

_If I use english language the behavior is ok_

**Comment by zdenop** [comment]
Use the latest tesseract version as stated in https://github.com/tesseract-ocr/tesseract/issues/1084#issuecomment-323086881
