### ISSUE TITLE
Stop GetUTF8Text

### ISSUE THREAD

**Issue by nnthero001** [tesseract-ocr/tesseract#267]
char* GetUTF8Text(struct ETEXT_DESC* monitor);
I write method GetUTF8Text with ETEXT_DESC but error when debug. How stop ocring.
char* TessBaseAPI::GetUTF8Text(struct ETEXT_DESC* monitor) {
  if (tesseract_ == NULL ||
      (!recognition_done_ && Recognize(monitor) < 0))
    return NULL;
  STRING text("");
  ResultIterator *it = GetIterator();
  do {
    if (it->Empty(RIL_PARA)) continue;
    char *para_text = it->GetUTF8Text(RIL_PARA);
    text += para_text;
    delete []para_text;
  } while (it->Next(RIL_PARA));
  char* result = new char[text.length() + 1];
  strncpy(result, text.string(), text.length() + 1);
  delete it;
  return result;
}

ETEXT_DESC monitor;
monitor.cancel = NULL;
monitor.cancel_this = NULL;
char *text = nat->api.GetUTF8Text(&monitor);

**Comment by zdenop** [comment]
Please use [tesseract user forum](https://groups.google.com/forum/#!forum/tesseract-ocr) for asking support (see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice) )
