### ISSUE TITLE
tesseract parameter/cmd to reduce noise in the image

### ISSUE THREAD

**Issue by jayanthnarayana** [tesseract-ocr/tesseract#2670]
I am using tesseract for 2 months now and using opencv for reducing the dots/noise in the images. But I am trying to solve this issue at tesseract level. Is there any tesseract parameter to remove the background dots? or can i tell the tesseract not to recognize the dots(depending on the size)?

Thank you in advance.

For the image attached: 
![tst9](https://user-images.githubusercontent.com/47178580/65407966-b7b5f680-de01-11e9-95a1-8ee51b61cbbd.PNG)

I am getting the output like below.

lb ane a a a ee ee Ee ah Tani ANOTES tsi Ca Ee RR RAT TE CORRE NE Re ele TTR a ee Tol a te es see Â© Students should schedile 21 points of work sech years... fen Es ee EE i ea | fdvenced Coreral Sciemes Â©. |. eroral Home Feonomits (limited to. Co mlgebras i ULE LE cl BE unions andi sentors) Dh 7od 1 Artâ€™ SpeelaliAvt [for those tC meman Ta GET Lhd recommended by Art Supervisor. ii Industrial Arts hal

I am using below command to run tesseract: tesseract --psm 6 --oem 1 image.png output_text_file

tesseract

**Comment by zdenop** [comment]
Tesseract is OCR engine. For image processing you have to use image processing library like opencv or leptonica or other.
