### ISSUE TITLE
undefined reference to `UNICHARSET::CleanupString[abi:cxx11](char const*, unsigned long)'

### ISSUE THREAD

**Issue by syupo** [tesseract-ocr/tesseract#2671]
os: centos7
leptonica: 1.78.0
tesseract : master branch

run these below，every thing is ok：
> git clone https://github.com/tesseract-ocr/tesseract.git
> ./autogen.sh
> ./configure --prefix=/usr/local/ --with-extra-libraries=/usr/local/lib

but，run make  an error raised like this：

> ......
> /bin/sh ../../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++17   -o tesseract tesseract-tesseractmain.o libtesseract.la -L/usr/local/lib -llept   -fopenmp    -lrt -lpthread 
> libtool: link: g++ -g -O2 -std=c++17 -o .libs/tesseract tesseract-tesseractmain.o -fopenmp  ./.libs/libtesseract.so -L/usr/local/lib /usr/local/lib/../lib64/libstdc++.so /usr/local/lib/liblept.so -lm -lrt -lpthread -fopenmp -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib/../lib64
> ./.libs/libtesseract.so: undefined reference to `UNICHARSET::CleanupString[abi:cxx11](char const*, unsigned long)'
> collect2: error: ld returned 1 exit status
> make[2]: *** [tesseract] Error 1
> make[2]: Leaving directory `/tmp/tesseract/tesseract/src/api'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory `/tmp/tesseract/tesseract'
> make: *** [all] Error 2

**Comment by zdenop** [comment]
Please provide full output of configure process and make process. 
`-std=c++17` and `[abi:cxx11]` indicate that something strange must happen to at your system.

**Comment by syupo** [comment]
i'm sorry to reply you so late, i resolve this issue by reinstall once again. I think it's my c++ compiler did not work.
