### ISSUE TITLE
Any docs on training tesseract with tensorflow in GPU?

### ISSUE THREAD

**Issue by balachandarsv** [tesseract-ocr/tesseract#2675]
I came across this #263 and #2461 , but couldn't find any docs for training with tensorflow in GPUs. 

It would be great if someone can shed some light here. 

Thanks.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by stweil** [comment]
Training Tesseract with TensorFlow is not implemented.
