### ISSUE TITLE
Tesseract doesn’t accept pre-defined img

### ISSUE THREAD

**Issue by lwardlegit** [tesseract-ocr/tesseract#2676]
Hi all,

I’m working with Tesseract js in the chrome browser. I am trying to submit a png that is already inside my project using an onclick call to Tesseract via a “demo” button as opposed to using an input element to submit an img file from my computer. How should I do this properly? 

Is there a common convention that I am missing?

When I attempt to do this I don’t get any errors but nothing happens inside the console as if Tesseract is simply not being called. I will include code as a follow up very soon. 

Thank you!

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.
