### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory when performing OCR Extraction on pdf files

### ISSUE THREAD

**Issue by divyangashah** [tesseract-ocr/tesseract#2680]
Hi team,

When we are calling:

> string getContent = currentPage.GetText();

It gives error below mentioned in some of the pdf documents when trying to perform OCR Text Extraction.
Please update the solution if it is available.

**Environment**

Tesseract Version: **4.0.0.0-beta3**
Platform: **Windows 64-bit**

Current Behavior:
giving below error in some documents:

**[ERROR] 2019-09-30 14:14:51.43,Attempted to read or write protected memory. This is often an indication that other memory is corrupt.,(:0)
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Imaging.OCR.TExtraction.RecognizeandExtractText(String inputFile, String outputFile, Boolean isReduceToBitonal)
   at Imaging.IG.ConsumerTest.FormMain.OCRExtraction()**

Expected Behavior:
It should give text content available in pdf file when perform OCR Text Extraction.

Suggested Fix:
**Same issue was in tesseract 3.0v which was resolved in 3.0.2-alpha1**

**Comment by stweil** [comment]
Please use a current Tesseract version, either 4.1.0 or the latest version from Git master.

Your error report also indicates that you don't run the Tesseract executable, but some third party software, so you should report any problems there.

Please use the user forum for additional questions.

**Comment by stweil** [comment]
https://github.com/tesseract-ocr/tesseract

**Comment by divyangashah** [comment]
Thanks @stweil 
actually, I am looking for Tesseract.dll for .net c#
Please share if any available.

**Comment by zdenop** [comment]
We provide only source code. You need to create binary file for yourself or take it from other projects.
