### ISSUE TITLE
Weird coordinates under chi_tra_vert.traineddata

### ISSUE THREAD

**Issue by MORzyuan** [tesseract-ocr/tesseract#2681]
Hi, many thanks to this fantastic work and all of you!
I am here to report some wired situations about coordinates when chi_tra_vert_*.traineddata is used. 

> tesseract 4.1.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
 Found libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.6

> ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

1. tesseract with makebox set all characters' X coordinates and their width to zero
`tesseract [--oem 1] chi_tra_vert_test_1.jpg chi_tra_vert_1_test -l chi_tra_vert makebox`
![chi_tra_vert_test_1_result](https://user-images.githubusercontent.com/16359969/65953049-bcb81d00-e475-11e9-826e-44eb62b25705.jpg)

2. tesseract with lstmbox failed
`tesseract [--oem 1] chi_tra_vert_test_2.jpg chi_tra_vert_2_test -l chi_tra_vert lstmbox`
![chi_tra_vert_test_2_result](https://user-images.githubusercontent.com/16359969/65953324-4bc53500-e476-11e9-8c14-898dd79f36a6.jpg)

And here are my questions:
1. Why I got wrong coordinates?
2. Why the OCR characters results are right while their coordinates are wrong?
3. _Though nothing related to the wired  cases_. Noticed that the vertical Chinese characters are only supported by 4.x versions, and 4.x versions only have the line-level bounding-boxs as their labeled data. How can the tesseract recognize the single character in the line?
4. Noticed that there is not GPUs training method, it's a little disturbing to train a lstm-based nerual network with CPUs, any experience(datasets amount and the time cost, etc) would really help!

Best!

**Comment by stweil** [comment]
@amitdo, I transferred it now.

**Comment by amitdo** [comment]
Thanks!

**Comment by amitdo** [comment]
Now I See that the OP already posted this issue with different title here:
#2679

**Comment by stweil** [comment]
So let's close the current one as a duplicate.
