### ISSUE TITLE
Contents should not occur and overlaps when use text2image with vertical

### ISSUE THREAD

**Issue by MORzyuan** [tesseract-ocr/tesseract#2682]
Hi, I am here to present a confusing result when use text2image to render .tif images.
### Environment

* **Tesseract Version**: 
tesseract 4.1.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
 Found libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.6

* **Commit Number**: 
* **Platform**: 
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

### Current Behavior:
`text2image --text=training_test.txt --outputbase=chi_tra_test --fonts_dir=../font/ --find_fonts --writing_mode vertical`
Total chars = 202
STSong Light : 202 hits = 100.00%, raw = 33 = 100.00%
Rendered page 0 to file chi_tra_test.STSong_Light.tif
Songti SC : 202 hits = 100.00%, raw = 33 = 100.00%
Rendered page 1 to file chi_tra_test.Songti_SC.tif
Songti SC Bold : 202 hits = 100.00%, raw = 33 = 100.00%
Rendered page 2 to file chi_tra_test.Songti_SC_Bold.tif
Songti SC Heavy : 202 hits = 100.00%, raw = 33 = 100.00%
Rendered page 3 to file chi_tra_test.Songti_SC_Heavy.tif
Songti SC Light : 202 hits = 100.00%, raw = 33 = 100.00%
Rendered page 4 to file chi_tra_test.Songti_SC_Light.tif
Songti TC : 202 hits = 100.00%, raw = 33 = 100.00%
Rendered page 5 to file chi_tra_test.Songti_TC.tif
Songti TC Bold : 202 hits = 100.00%, raw = 33 = 100.00%
Rendered page 6 to file chi_tra_test.Songti_TC_Bold.tif
Songti TC Light : 202 hits = 100.00%, raw = 33 = 100.00%
**Error in boxCreate: y < 0 and box off +quad
Error in boxaAddBox: box not defined
Error in boxaGetBox: index not valid**

![chi_tra_test Songti_SC](https://user-images.githubusercontent.com/16359969/65969679-ca7e9a00-e497-11e9-83db-1b6d65fb53a5.png)

### Expected Behavior:
Please notice the right corner of the rendered image above, the information about font and something I don't really understand should not occurs.
And the **BOLD** parts of the terminal printed informations above should not occurs.

### Suggested Fix:
There may be something wrong in training/text2image.cpp.

**Comment by stweil** [comment]
Did it work with other versions? And could you please provide all necessary information and data which is needed to reproduce this issue? Attach for example `training_test.txt` to the issue.

**Comment by stweil** [comment]
Is the list of fonts relevant, or can I use other fonts as well to get the problem?

**Comment by MORzyuan** [comment]
> Did it work with other versions? And could you please provide all necessary information and data which is needed to reproduce this issue? Attach for example `training_test.txt` to the issue.

Thanks!
I have tried with 3.05 with the same test files, the same thing occurs.
The training_test.txt is just a toy file with Chinese characters. Here is it.
[training_test.txt](https://github.com/tesseract-ocr/tesseract/files/3677478/training_test.txt)

**Comment by MORzyuan** [comment]
> Is the list of fonts relevant, or can I use other fonts as well to get the problem?

Good point! Thanks!
And I just have something new related to your reply to report, just as below.

### Environment 1

* **Tesseract Version**: 
tesseract 4.1.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 9c : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
 Found libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.6

* **Commit Number**: 
* **Platform**: 
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

### Environment 2

* **Tesseract Version**: 
tesseract 3.05.02
 leptonica-1.78.0
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8

* **Commit Number**: 
* **Platform**: 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

The cases reported below have been tested under both of these two enviroments.
And the font files are too large to be attached here, I think the same things could happen with other fonts.

### Current Behavior:

I added the font file `Arial Unicode.ttf` 
to the `/path/of/my/fonts` 
and then ran the same code 
`text2image --text=training_test.txt --outputbase=chi_tra_test_vert --fonts_dir=../font  --find_fonts --writing_mode vertical`, 
**just** got the output file `chi_tra_test_vert.Arial_Unicode_MS.tif` with the same problem, and **didn't get** the .box files
![image](https://user-images.githubusercontent.com/16359969/65983796-f35f5900-e4b0-11e9-8396-f25c10d53ae8.png)
![image](https://user-images.githubusercontent.com/16359969/65981974-d032aa80-e4ac-11e9-94bd-d7298b417ef1.png)

Noticed one interesting thing here, the font file is named as `Arial Unicode.ttf`, and it's shown as below.
![image](https://user-images.githubusercontent.com/16359969/65982137-3ae3e600-e4ad-11e9-9a0b-05887c9608bf.png)
But the font name generated by the tesseract is `Arial_Unicode_MS`.

Also, I have tried the code which directly assign the font file with `--font` rather than use `--find_fonts`.
`text2image --text=training_test.txt --outputbase=chi_tra_test.STSongLightSoloVert.exp0 --font='STSong Light' --fonts_dir=../font --writing_mode vertical`
This time **I got the right output**, the tif/box pair with the right form!
![image](https://user-images.githubusercontent.com/16359969/65982449-f7d64280-e4ad-11e9-9622-b2dadaa6b7c4.png)
![image](https://user-images.githubusercontent.com/16359969/65982506-10def380-e4ae-11e9-8efe-3b06c4286c99.png)
![image](https://user-images.githubusercontent.com/16359969/65982540-28b67780-e4ae-11e9-9ff2-e312649493ed.png)

With these attempts, I got another wired case, similar to the name of font file mentioned above.
When I used
`text2image --text=training_test.txt --outputbase=chi_tra_test.ArialUnicodeSoloVert.exp0 --font='Arial Unicode' --fonts_dir=../font --writing_mode vertical`
I got the follow terminal outputs:
`Could not find font named Arial Unicode.`
`Pango suggested font Arial Unicode MS.`
`Please correct --font arg.`
Though I surely have `Arial Unicode.ttf` in the `fonts_dir`

Many thanks!
Best!

**Comment by amitdo** [comment]
font filename != font actual name

The font name is declared inside the font file.

**Comment by amitdo** [comment]
Try this:

```
text2image --text=training_test.txt --outputbase=chi_tra_test.ArialUnicodeSoloVert.exp0 --font='Arial Unicode MS' --fonts_dir=../font --writing_mode vertical
```

**Comment by amitdo** [comment]
When you use the --find_fonts option, also add the option --render_per_font=false.

The output is list of fonts names.

**Comment by MORzyuan** [comment]
> Try this:
> 
> ```
> text2image --text=training_test.txt --outputbase=chi_tra_test.ArialUnicodeSoloVert.exp0 --font='Arial Unicode MS' --fonts_dir=../font --writing_mode vertical
> ```

Yes, use text2image with `--font` directly rather than `--find_fonts` could get the expected tif/box pair, but `--find_fonts` returns the wrong output, saying that the overlaps in `.tif` and miss the `.box` files.



> When you use the --find_fonts option, also add the option --render_per_font=false.
> 
> The output is list of fonts names.

Yes, I see it! Thanks!

**Comment by amitdo** [comment]
> but --find_fonts ... miss the .box files.

The purpose of text2image with the --find_fonts option is to give you fonts list, not to render box files.

**Comment by MORzyuan** [comment]
> > but --find_fonts ... miss the .box files.
> 
> The purpose of text2image with the --find_fonts option is to give you fonts list, not to render box files.

😂 My bad, thanks a lot!
