### ISSUE TITLE
Tesseract does not detect fairly clean and obvious text in this image.

### ISSUE THREAD

**Issue by StScAllen** [tesseract-ocr/tesseract#2683]
![checktest](https://user-images.githubusercontent.com/5774645/65982203-65e42080-e440-11e9-9738-80e900e8e0f6.jpg)

------------------------

### Environment

* **Tesseract Version**:  4.1.0
* **Commit Number**:  NA
* **Platform**:  Windows 10 

### Current Behavior:
When OCR is applied to image the 3rd form section containing the data 
"6. Item   7. Description  8. Part Number: ..." 
section is not seen by Tesseract.  The test looks fairly clean and straight forward, why can't Tesseract detect it?  There is far worse text on this page and Tesseract can read it.

### Expected Behavior:
Properly detect the text in row 3. 

### Suggested Fix:
Not sure why the text is ignored.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue and read other issues and wiki and forum before posting issue.
