### ISSUE TITLE
tesseract: symbol lookup error: tesseract: undefined symbol: archive_version_details

### ISSUE THREAD

**Issue by varun-gagneja** [tesseract-ocr/tesseract#2692]
Hi,

I am trying to setup tesseract in Docker on ubuntu 16 by following method given in [tesseract-ocr-re](https://github.com/tesseract-shadow/tesseract-ocr-re/blob/master/Dockerfile).

Below is how my docker file looks like
```
FROM ubuntu:16.04
RUN apt-get update && apt-get upgrade -y && apt-get install -y software-properties-common && add-apt-repository -y ppa:alex-p/tesseract-ocr
RUN apt-get update && apt-get install -y tesseract-ocr-all
```
I'm not getting any error while making the docker image. But when I am trying to run tesseract from the shell of my container I am getting this weird error.
```
root@760677a9c7c4:/# tesseract 
tesseract: symbol lookup error: tesseract: undefined symbol: archive_version_details
```
I also tried to manually install some of the packages like -
```
apt-get install g++ autoconf automake libtool pkg-config libpng-dev
```
But still getting the same error. Any help would be much appreciated.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. Use tesseract user forum for asking questions/support for your project.

**Comment by amitdo** [comment]
>tesseract: symbol lookup error: tesseract: undefined symbol: archive_version_details

The error is related to an optional curl dependency.

https://github.com/tesseract-ocr/tesseract/blob/8095e6c1c3726d8381e0dde74b0f3443f422e1e7/src/api/tesseractmain.cpp#L146

**Comment by stweil** [comment]
s/curl/libarchive/

**Comment by amitdo** [comment]
Yes, I just did the replacement (before seeing your message).
:-)

**Comment by varun-gagneja** [comment]
Thanks @amitdo @stweil after installing `libarchive-dev` dependency I was able to install the tesseract

**Comment by amitdo** [comment]
Did you use this PPA?
https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr

**Comment by amitdo** [comment]
@stweil,

Should the PPA **require** libarchive? 

CC: @AlexanderP'

**Comment by AlexanderP** [comment]
No.
I disabled backports dependency in ppa:alex-p/tesseract-ocr

The problem was in libarchive versions
main xenial - 3.1.2-11ubuntu0.16.04.6
xenial-backports - 3.2.1-2~ubuntu16.04.1

The package was compiled with **libarchive 3.2.1**
docker installed **libarchive 3.1.2**

5 hours ago I started tesseract rebuilding in ppa with xenial-backports disabled

**Comment by amitdo** [comment]
OK, thanks.
