### ISSUE TITLE
Windows Error running tesseract 4.1 x86

### ISSUE THREAD

**Issue by NicolasPasc** [tesseract-ocr/tesseract#2699]
Hi,

_* **Tesseract Version 4.1 (latest)
tesseract.exe --version
tesseract 4.1.0
 leptonica-1.79.0 (Sep 26 2019, 10:11:48) [MSC v.1916 LIB Release x86]
  libgif 5.1.4 : libjpeg 9b : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE_

Built with Microsoft _Visual Studio 2017 x86_.
Used cppan to build leptonica.

I am using tesseract successfully on various environments (Windows Server, Windows 10), and it usually works. But on other environments (still Windows Server), with the same files, it crashes and throws an error.

(Event Viewer)
_Faulting application name: zTestOCR.exe, version: 1.0.0.0, time stamp: 0x5d976077
Faulting module name: tesseract41.dll, version: 4.1.0.0, time stamp: 0x5d947b3c
Exception code: 0xc000001d
Fault offset: 0x00001af5
Faulting process id: 0xe834
Faulting application start time: 0x01d57dbe15abf8cd
Faulting application path: C:\Users\slext\Desktop\zTestOCR\zTestOCR.exe
Faulting module path: C:\Users\slext\Desktop\zTestOCR\tesseract41.dll
Report Id: 0b54ae33-dc7f-45ff-9194-ee097ff21a6d
Faulting package full name: 
Faulting package-relative application ID:_ 

Windows Error running compiled tesseract.exe :
_tesseract.exe - Application Error
The application was unable to start correctly (0xc0000142). Click OK to close the application._ 

(Libs):
_leptonica-1.79.0.lib
pvt.cppan.demo.gif-5.1.4.lib
pvt.cppan.demo.jpeg-9.2.0.lib
pvt.cppan.demo.png-1.6.35.lib
pvt.cppan.demo.tiff-4.0.9.lib
pvt.cppan.demo.webmproject.webp-1.0.0.lib
pvt.cppan.demo.openjpeg.openjp2-2.3.0.lib
pvt.cppan.demo.madler.zlib-1.2.11.lib
pvt.cppan.demo.xz_utils.lzma-5.2.4.lib_

(Files)
_leptonica-1.79.0.dll
pvt.cppan.demo.jpeg-9.2.0.dll
pvt.cppan.demo.png-1.6.35.dll
pvt.cppan.demo.tiff-4.0.9.dll
pvt.cppan.demo.webmproject.webp-1.0.0.dll
pvt.cppan.demo.openjpeg.openjp2-2.3.0.dll
pvt.cppan.demo.madler.zlib-1.2.11.dll
pvt.cppan.demo.xz_utils.lzma-5.2.4.dll_

I am tring to figure out what is missing on these machines but I don't have a clue. 
C++ Redistribuable package 2015-2019 x86 and x64 are installed.

I don't have these issues when I run tesseract 4.0, but I have more accurate results with 4.1.
Am I missing something?

Thanks & Regards
Nicolas

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects (zTestOCR.exe).

**Comment by Dianarose69** [comment]
ljackie631@gmail.com
On Oct 8, 2019 6:34 PM, "NicolasPasc" <notifications@github.com> wrote:
>
> Hi,
>
> * **Tesseract Version 4.1 (latest)
> tesseract.exe --version
> tesseract 4.1.0
> leptonica-1.79.0 (Sep 26 2019, 10:11:48) [MSC v.1916 LIB Release x86]
> libgif 5.1.4 : libjpeg 9b : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 :
libwebp 1.0.0 : libopenjp2 2.3.0
> Found AVX2
> Found AVX
> Found SSE
>
> Built with Microsoft Visual Studio 2017 x86.
> Used cppan to build leptonica.
>
> I am using tesseract successfully on various environments (Windows
Server, Windows 10), and it usually works. But on other environments (still
Windows Server), with the same files, it crashes and throws an error.
>
> (Event Viewer)
> Faulting application name: zTestOCR.exe, version: 1.0.0.0, time stamp:
0x5d976077
> Faulting module name: tesseract41.dll, version: 4.1.0.0, time stamp:
0x5d947b3c
> Exception code: 0xc000001d
> Fault offset: 0x00001af5
> Faulting process id: 0xe834
> Faulting application start time: 0x01d57dbe15abf8cd
> Faulting application path: C:\Users\slext\Desktop\zTestOCR\zTestOCR.exe
> Faulting module path: C:\Users\slext\Desktop\zTestOCR\tesseract41.dll
> Report Id: 0b54ae33-dc7f-45ff-9194-ee097ff21a6d
> Faulting package full name:
> Faulting package-relative application ID:
>
> Windows Error running compiled tesseract.exe :
> tesseract.exe - Application Error
> The application was unable to start correctly (0xc0000142). Click OK to
close the application.
>
> (Libs):
> leptonica-1.79.0.lib
> pvt.cppan.demo.gif-5.1.4.lib
> pvt.cppan.demo.jpeg-9.2.0.lib
> pvt.cppan.demo.png-1.6.35.lib
> pvt.cppan.demo.tiff-4.0.9.lib
> pvt.cppan.demo.webmproject.webp-1.0.0.lib
> pvt.cppan.demo.openjpeg.openjp2-2.3.0.lib
> pvt.cppan.demo.madler.zlib-1.2.11.lib
> pvt.cppan.demo.xz_utils.lzma-5.2.4.lib
>
> (Files)
> leptonica-1.79.0.dll
> pvt.cppan.demo.jpeg-9.2.0.dll
> pvt.cppan.demo.png-1.6.35.dll
> pvt.cppan.demo.tiff-4.0.9.dll
> pvt.cppan.demo.webmproject.webp-1.0.0.dll
> pvt.cppan.demo.openjpeg.openjp2-2.3.0.dll
> pvt.cppan.demo.madler.zlib-1.2.11.dll
> pvt.cppan.demo.xz_utils.lzma-5.2.4.dll
>
> I am tring to figure out what is missing on these machines but I don't
have a clue.
> C++ Redistribuable package 2015-2019 x86 and x64 are installed.
>
> I don't have these issues when I run tesseract 4.0, but I have more
accurate results with 4.1.

**Comment by NicolasPasc** [comment]
Sorry but when I run directly tesseract.exe, it also throws an error (The application was unable to start correctly (0xc0000142). Click OK to close the application.)

I included the Event Viewer with my project to guide you.. because there is no additionally details on the Windows Error while I run tesseract.exe.

**Comment by zdenop** [comment]
But you wrote:

> tesseract.exe --version
> tesseract 4.1.0
> leptonica-1.79.0 (Sep 26 2019, 10:11:48) [MSC v.1916 LIB Release x86]
> libgif 5.1.4 : libjpeg 9b : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0 : libopenjp2 2.3.0
> Found AVX2
> Found AVX
> Found SSE

Now you wrote:

> Sorry but when I run directly tesseract.exe, it also throws an error

So? it there crash where you run tesseract.exe or not?
Also check other issues before posting issue. E.g. #2674

**Comment by NicolasPasc** [comment]
Yes it crashes on some machines, others don't... I can't figure out why.
I extracted the details on a working machine.

**Comment by NicolasPasc** [comment]
Thank you for the link, I will try these suggestions.

**Comment by NicolasPasc** [comment]
For the record, I don't have the issue using Tesseract 5.0.0-alpha-476-g8b69.
I don't know what append with my 4.1 version, but 4.0 and 5.0 run fine.
Thank you for support.

**Comment by PCITBoy** [comment]
I have the same problem，how to sole it?

**Comment by NicolasPasc** [comment]
I now use the master branch (Tesseract 5.0.0-alpha-476-g8b69) as **zdenop** indicated, and this works on the machines that didn't with the 4.1 [#2674](https://github.com/tesseract-ocr/tesseract/issues/2674)
