### ISSUE TITLE
STRING removed from genericvector.h but still present in baseapi.h

### ISSUE THREAD

**Issue by stxcompton** [tesseract-ocr/tesseract#2703]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**: 

### Current Behavior:
Trying to use 

int tesseract::TessBaseAPI::Init | ( | const char * datapath, const char * language, OcrEngineMode oem, char ** configs, int configs_size, const GenericVector< STRING > *, vars_vec, const GenericVector< STRING > * vars_values, bool | set_only_non_debug_params )

is impossible since the STRING template type has been removed from GenericVector.h in commit a730b5c 

### Expected Behavior:

All the forms of the Init function should require functional data types. 

### Suggested Fix:

Restore STRING or alter the required data type in this form of TessBaseApi::Init

**Comment by stweil** [comment]
I see no error. It is possible to include `baseapi.h`, and if your code needs the full declaration of `STRING`, you should include `strngs.h`.

**Comment by stweil** [comment]
> is impossible since the STRING template type has been removed from GenericVector.h in commit a730b5c

Which line are you referring to? I don't see a `STRING` template type in the old code. Nor is there a file named `GenericVector.h`, there is only a `genericvector.h`.

**Comment by stxcompton** [comment]
My mistake, I misunderstood the requirement to include strngs.h
