### ISSUE TITLE
Can tesseract Extract text from a photo?

### ISSUE THREAD

**Issue by johneakin** [tesseract-ocr/tesseract#2706]
Hi,
I have a photo from a game of soccer.
I want tesseract to extract the info from the top left

e.g in the below photo:

17:50 POR 1 - 0 LUX
https://ibb.co/wBn46ZD

Is this possible?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

When posting question, please describe what technique from documentation you already tried.
