### ISSUE TITLE
after tesseract4.1 compile to 32bit, run tesseract.exe  tesseract41.dll  error  on win7, but tesseract4.1 compile to 64bit Run normally

### ISSUE THREAD

**Issue by PCITBoy** [tesseract-ocr/tesseract#2713]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by zdenop** [comment]
This is not correct issue report.
