### ISSUE TITLE
Assertion `ClassTemplate->ProtoLengths[ActualProtoNum] < MAX_PROTO_INDEX' failed

### ISSUE THREAD

**Issue by xploiter-projects** [tesseract-ocr/tesseract#2716]
My setup:
```
tesseract 4.0.1
 leptonica-1.78.0
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8
```

I have tried with command line tesseract and getting the error. command used:

`tesseract img.png out --oem 0 -l eng`

Error trace:

`Trace: Tesseract Open Source OCR Engine v4.0.1 with Leptonica Warning: Invalid resolution 0 dpi. Using 70 instead. Estimating resolution as 389 tesseract: intmatcher.cpp:1160: void ScratchEvidence::UpdateSumOfProtoEvidences(INT_CLASS, BIT_VECTOR): Assertion ClassTemplate->ProtoLengths[ActualProtoNum] < MAX_PROTO_INDEX' failed. Aborted (core dumped)`

I have used Tessdata files given on this link: https://github.com/tesseract-ocr/tessdata
As well as, given here: https://github.com/tesseract-ocr/tesseract/wiki/Data-Files , both 4.00 and 3.04/3.05

**Comment by xploiter-projects** [comment]
Using different traineddata files, same error occurs on different images. In both cases, it works perfectly on most of the images, but produces the above error on some images.

**Comment by zdenop** [comment]
There is nothing like `Tesseract Open Source OCR Engine v4.0.1`. For issue posting use official releases or master code  and tesseract executable not wrapper (we do not support 3rd party projects).

**Comment by xploiter-projects** [comment]
> There is nothing like `Tesseract Open Source OCR Engine v4.0.1`. For issue posting use official releases or master code and tesseract executable not wrapper (we do not support 3rd party projects).

@zdenop  I have updated my tesseract and now I am using official release 4.1.0. I am still getting the same error.

**Comment by stweil** [comment]
Please provide all information which is needed to reproduce your problem. Without that, nobody can help you. Windows? Linux?`Self-built executable or package from distribution? Image?

**Comment by stweil** [comment]
Possibly related: issue #444.

**Comment by xploiter-projects** [comment]
> Possibly related: issue #444. @xploiter-projects, one or two of the images which trigger the problem would be really helpful. You can attach them here.

@stweil I have attached the sample image. and also updated my system info in the issue

**Comment by stweil** [comment]
I tested that sample image with Debian package tesseract-ocr 4.1.0-2 and with Tesseract 5.0.0-alpha-337-gc757b (both using tessdata/eng.traineddata) and had no problem.

**Comment by zdenop** [comment]
Please check that you use the latest version of tessdata/eng.traineddata and that the file is not corrupted.  With >4.0 you can try also best and fast repository.

BTW: it seems like your system has not support for AVX, SSE instruction.  Can you provide details how did you build tesseract?

**Comment by xploiter-projects** [comment]
@stweil I actually uploaded cropped image since I didn't want to expose the header. 
Anyways, I tested on that cropped image too and it worked fine.
So, this is shape of my image (which is causing error):
![image](https://user-images.githubusercontent.com/20368350/67080118-fa26e500-f1ad-11e9-9b3f-26fca6d0c370.png)
and I cropped the image (removed first 300 rows), new shape:
![image](https://user-images.githubusercontent.com/20368350/67080204-26dafc80-f1ae-11e9-939f-0d82d241be72.png)
Tesseract is working fine with the cropped image. The area which was cropped didn't contain any text. And it doesn't matter if I crop from bottom or top, it works fine.

But
tesseract works fine with most of the images without cropping/ reducing dimensions. Provided that all of my test images are of same shape (width = 2550, height = 3301)

**Comment by xploiter-projects** [comment]
> Please check that you use the latest version of tessdata/eng.traineddata and that the file is not corrupted. With >4.0 you can try also best and fast repository.
> 
> BTW: it seems like your system has not support for AVX, SSE instruction. Can you provide details how did you build tesseract?

@zdenop I cloned this branch: https://github.com/tesseract-ocr/tesseract/tree/4.1
and used following commands to build the tesseract:

`./autogen.sh`
`./configure --enable-debug`
`make`
`sudo make install`
`sudo ldconfig`

**Comment by stweil** [comment]
@xploiter-projects, I am confused. Which image can I use to reproduce the problem?

**Comment by stweil** [comment]
> With >4.0 you can try also best and fast repository.

Those won't work because of `--oem 0`.

**Comment by zdenop** [comment]
@stweil : I know, but I would like to know if problem is in lang model or somewhere else. 
@xploiter-projects : if problem is in image, maybe there is problem with memory. What is your hardware specification?

**Comment by zdenop** [comment]
@xploiter-projects : `--enable-debug` is useful only for developers and it "enable" asserts when specified conditions are met. Unless you understand tesseract code -  do not use this option for build (and you will not see this crash).

**Comment by stweil** [comment]
@xploiter-projects, if you cannot upload the uncropped image, maybe you can send it per e-mail to me? As @zdenop said, this assertion is not enabled in release code. It is nevertheless an indicator that something possibly goes wrong. Therefore it would be good to examine that case.

**Comment by xploiter-projects** [comment]
@zdenop  @stweil 
I built with same method on another system and it seems working fine. I am not sure yet what was the problem. For now, I am closing the issue and I apologize for any inconvenience.  If I encounter this problem again, I will get  back here. Thanks a lot

> > Please check that you use the latest version of tessdata/eng.traineddata and that the file is not corrupted. With >4.0 you can try also best and fast repository.
> > BTW: it seems like your system has not support for AVX, SSE instruction. Can you provide details how did you build tesseract?
> 
> @zdenop I cloned this branch: https://github.com/tesseract-ocr/tesseract/tree/4.1
> and used following commands to build the tesseract:
> 
> `./autogen.sh`
> `./configure --enable-debug`
> `make`
> `sudo make install`
> `sudo ldconfig`
