### ISSUE TITLE
Got Error in pixWriteMemPng: function not present when using tesseract

### ISSUE THREAD

**Issue by SuperChenSSS** [tesseract-ocr/tesseract#2717]
### Environment

* **Tesseract Version**: 4.0.0
* **leptonica**: 1.76.0
* **Platform**: Darwin Kernel Version 19.0.0 macOS

### Current Behavior:
I used Tesseract for OCR, but it just failed when running command line.
My command is: 
```bash
$ tesseract --tessdata-dir ./tessdata/ img/test_bw.jpg ./output-chi -l chi_sim
```
And the error messages I got:
```
Tesseract Open Source OCR Engine v4.0.0 with Leptonica
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 608
Error in pixWriteMemPng: function not present
[1]    50767 segmentation fault  tesseract --tessdata-dir ./tessdata/ img/test_bw.jpg ./output-chi -l chi_sim
```
Please let me know how to proceed.

**Comment by zdenop** [comment]
Please provide output of `tesseract -v`.

**Comment by SuperChenSSS** [comment]
$ tesseract -v
tesseract 4.0.0
 leptonica-1.76.0
  libjpeg 9c : libtiff 4.0.10 : zlib 1.2.11
 Found AVX2
 Found AVX
 Found SSE

**Comment by zdenop** [comment]
Which means that you build leptonica without png support. You can:

1. rebuild leptonica with png support
2. use the recent tessseract version (4.1) (see #2333)
