### ISSUE TITLE
Android tesseract no text output 

### ISSUE THREAD

**Issue by scubess** [tesseract-ocr/tesseract#2719]
I compiled tesseract 4.0.0 for android and produce shared libraries  as mentioned in [Compilation Guide](https://github.com/tesseract-ocr/tesseract/wiki/Compiling#android) using [Building for Android with Docker file ](https://github.com/rhardih/bad/blob/master/tesseract/tesseract-4.0.0.Dockerfile) 

I wrote a simple JNI wrapper and  using`ndk-build` with `android.mk` file, i build a shared library that goes into my application.  I can see, tesseract has been initialised and can get the version 4.0.0 with no issue.  I am not seeing any crashes but at the same time, I can't see any text has been recognised or no error is thrown.

I followed the instructions and I am sure, I downloaded the right version of `trained data` file into tessdata folder. Even I tried with different versions of ` .traineddata`,  didn't make any difference. 

To note, when I use tesseract 3.05, I can see the code runs with no issues. I can't understand what's going wrong here. I have been trying for days and I couldn't find the issue. 
 ### Environment: Tesseract 

* **Tesseract Version**: tesseract 4.0.0
* **Platform**:  GNU/Linux Ubuntu / android arm64-v8a 

### Current Behavior:
No text recogned at  in `api->GetUTF8Text()`
### Expected Behavior:
returns recognised text from the image

I attached the sample app with JNI  wrapper please [click the link for sample app](https://github.com/scubess/tesseracttest.git) 

Look forward yours help!

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. Try to use tesseract user forum.
