### ISSUE TITLE
Spelling mistakes in man pages

### ISSUE THREAD

**Issue by richardjsimkins** [tesseract-ocr/tesseract#272]
In version 3.03

In the man page for TESSERACT(1) under the title Languages the following items are misspelt.

"Croation" should be "Croatian" (https://en.wikipedia.org/wiki/Croatian_language)
"Slovakian" should be "Slovak" (https://en.wikipedia.org/wiki/Slovak_language)

**Comment by zdenop** [comment]
Please check [the source](https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc#languages) before writing issue.
BTW: current version is 3.04.01.
