### ISSUE TITLE
Malware from source download link

### ISSUE THREAD

**Issue by mathan1312** [tesseract-ocr/tesseract#2720]
When i tried to download the VietOCR tool from below link . My system got infected by trojan virus while installing this exe  " Visual C++ Redistributable for Visual Studio 2015 runtime - vc_redist.x86.exe " from this https://www.microsoft.com/en-us/download/details.aspx?id=48145

https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM#400-alpha-for-windows

**Comment by zdenop** [comment]
IMO your assumption is wrong: if you installed vc_redist.x86.exe from microsoft.com than most (all?) of windows computer would got malware too... Which is obviously not true.
