### ISSUE TITLE
Remove all TESS_CALL

### ISSUE THREAD

**Issue by egorpugin** [tesseract-ocr/tesseract#2725]
@stweil @zdenop 
Do you agree? If yes, I'll remove them.
x64 does not need calling conventions, on x86 win - default must be used.

**Comment by stweil** [comment]
I agree. Of course the resulting DLL for Windows will be incompatible with old code, but for 5.0.0 and master that's ok.

**Comment by egorpugin** [comment]
#2728

**Comment by egorpugin** [comment]
Second PR will remove TESS_API from capi.cpp, because it is only needed in .h.

**Comment by egorpugin** [comment]
> Of course the resulting DLL for Windows will be incompatible with old code

There was __cdecl for win by default. And it is used by default on win, so no incompatibles.

**Comment by zdenop** [comment]
@troplin : Any comments about this? AFAIR you are author of C-API...

**Comment by troplin** [comment]
I think that should be fine.
IIRC my first version used `__stdcall`, which is why the macro is there in the first place. But it was later changed to `__cdecl`.
