### ISSUE TITLE
Build on windows 10 from source using cppan and latest dependencies 

### ISSUE THREAD

**Issue by essamzaky** [tesseract-ocr/tesseract#2733]
I used the following steps to build tesseract from source
1-delete the following folders "C:\Users\emz\tesseract" , "C:\Users\emz.cppan".
2-git clone https://github.com/tesseract-ocr/tesseract.git
3-cd tesseract
4-cppan
5-mkdir build32
6-cd build32
7-cmake .. -G "Visual Studio 15 2017" -DCPPAN_USE_CACHE=0 

Tesseract builds successfully but the dependencies are old specially leptonica the version comes with Tesseract is 1.76 while the current version is 1.79 , there is a lot of updates the latest version of leptonica , would you update to latest version of leptonica and other libraries

thanks
------------------------

### Environment

* **Tesseract Version**: <5.0>
* **Commit Number**: 
* **Platform**: <Windows10 32 -->

### Current Behavior:
Old dependencies comes with the build
### Expected Behavior:
latest dependencies expected to be build with Tesseract
### Suggested Fix:
Use latestest dependncies

**Comment by zdenop** [comment]
We do not provide tesseract dependencies for any platform. You can build them by yourself or use tool chain that meets your requirements.
