### ISSUE TITLE
oem and psm options not mentioned in wiki

### ISSUE THREAD

**Issue by ORESoftware** [tesseract-ocr/tesseract#2734]
https://github.com/tesseract-ocr/tesseract/wiki/FAQ

I am looking for explanation for these options

```js
const tesseract = require("node-tesseract-ocr");

const config = {
  lang: "eng",
  oem: 1,  // ?
  psm: 3,  // ?
};
```

**Comment by whatohyou** [comment]
https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects and use tesseract user forum for asking questions/support.
