### ISSUE TITLE
Do ocr on mongodb

### ISSUE THREAD

**Issue by vijayalangaram** [tesseract-ocr/tesseract#2739]
Hi everyone

Based on tessaract doocr , Is it possible to store an image in mongodb with it's text[ocr] . I was unable to found any example do that. How to perform a doocr on image and store that image in mongodb with it's text extract from that image. I was follwed below url but unable to hit through it's encode details in a postman.

https://github.com/arun0009/ocr-tess4j-rest

[ERROR 1.pdf](https://github.com/tesseract-ocr/tesseract/files/3792649/ERROR.1.pdf)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.

**Comment by vijayalangaram** [comment]
> Please respect guidelines for posting issue: we do not provide support for 3rd party projects.

Ok i understood that. Is tessract supports to perform doocr on  mongodb collection images. Or we hit doocr for every image. While using doocr() the argument expected that file path location , datapath, or image. Is is possible do ocr after store in a mongodb. i was tried with some of my code but not works.
