### ISSUE TITLE
Force tesseract to use a dictionnary

### ISSUE THREAD

**Issue by Emma04** [tesseract-ocr/tesseract#274]
Hello everyone
I'm new with tesseract and I was wondering if I could force Tesseract to use a small dictionnary and to return the word which is the most similaire from the dictionnary
Thx

**Comment by zdenop** [comment]
Please use [tesseract user forum](https://groups.google.com/forum/#!forum/tesseract-ocr) for asking support (see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice) )
