### ISSUE TITLE
Can i use the Data Files for Version 4.00 in tesseract 4.1.0

### ISSUE THREAD

**Issue by webenters** [tesseract-ocr/tesseract#2742]
Can i use the Data Files for Version 4.00 in tesseract 4.1.0

[https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400-september-15-2017](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400-september-15-2017)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
