### ISSUE TITLE
Linking error when building  txt2image in 5.0.0-alpha-546-g41c3

### ISSUE THREAD

**Issue by oberw** [tesseract-ocr/tesseract#2747]
------------------------

### Environment

5.0.0-alpha-546-g41c3
Linux nico 5.3.7-1-default #1 SMP Mon Oct 21 06:03:17 UTC 2019 (3eea5a9) x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior: Linking error for txt2image
[ 96%] Linking CXX executable ../../bin/text2image
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/text2image.dir/pango_font_info.cpp.o: undefined reference to symbol 'g_free'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libglib-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[ 99%] Built target text2image
Scanning dependencies of target mftraining

**Comment by zdenop** [comment]
Posting just last part off error is useless. Please provide full information (from configuration, build system, system info)

**Comment by oberw** [comment]
Here is the whole kid and kaboodle in its full glory:

walter@nico:tesseract>git pull
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 100 (delta 73), reused 93 (delta 73), pack-reused 7
Empfange Objekte: 100% (100/100), 23.66 KiB | 605.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (73/73), abgeschlossen mit 32 lokalen Objekten.
Von https://github.com/tesseract-ocr/tesseract
   41c3e93c..2d6f38ee  master     -> origin/master
   d423fb16..21c83b80  4.1        -> origin/4.1
Aktualisiere 41c3e93c..2d6f38ee
Fast-forward
 doc/lstmeval.1.asc           |  4 ++--
 src/api/pdfrenderer.cpp      |  2 +-
 src/ccmain/linerec.cpp       |  2 +-
 src/ccstruct/imagedata.h     |  3 +++
 src/ccutil/params.cpp        | 37 ++++++++++++++++++++++---------------
 src/textord/colpartition.h   |  2 +-
 src/training/lstmtrainer.cpp |  6 ++++--
 7 files changed, 34 insertions(+), 22 deletions(-)
walter@nico:tesseract>
walter@nico:tesseract>
walter@nico:tesseract>cd build-linux/
walter@nico:build-linux>cmake .
Configuring tesseract version 5.0.0-alpha-552-g2d6f...
-- Could NOT find LibArchive (missing: LibArchive_LIBRARY LibArchive_INCLUDE_DIR) 
-- 
-- General configuration for Tesseract 5.0.0-alpha-552-g2d6f
-- --------------------------------------------------------
-- Build type: Release
-- Compiler: GNU
-- Used standard: C++17
-- CXX compiler options:  -O3 -DNDEBUG
-- Linker options:  
-- Install directory: /usr/local
-- Architecture flags: -march=nehalem;-msse2;-msse3;-mssse3;-msse4.1;-msse4.2;-mno-sse4a;-mno-avx;-mno-fma;-mno-bmi2;-mno-avx2;-mno-xop;-mno-fma4;-mno-avx512f;-mno-avx512vl;-mno-avx512pf;-mno-avx512er;-mno-avx512cd;-mno-avx512dq;-mno-avx512bw;-mno-avx512ifma;-mno-avx512vbmi
-- Vector unit list: sse2;sse3;ssse3;sse4.1;sse4.2
-- AVX_OPT: OFF
-- AVX2_OPT: OFF
-- FMA_OPT: OFF
-- SSE41_OPT: ON
-- MARCH_NATIVE_OPT: ON
-- sim_flags:  -DSSE2 -DSSE3 -DSSSE3 -DSSE4_1 -DSSE4_2
-- --------------------------------------------------------
-- Build with sw [SW_BUILD]: OFF
-- Build with openmp support [OPENMP_BUILD]: OFF
-- Disable disable graphics (ScrollView) [GRAPHICS_DISABLED]: OFF
-- Disable the legacy OCR engine [DISABLED_LEGACY_ENGINE]: OFF
-- Build training tools [BUILD_TRAINING_TOOLS]: ON
-- Build tests [BUILD_TESTS]: ON
-- Use system ICU Library [USE_SYSTEM_ICU]: OFF
-- --------------------------------------------------------
-- 
-- Found the following ICU libraries:
--   uc (required)
--   i18n (required)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/users/walter/Software/tesseract/build-linux
walter@nico:build-linux>make
Scanning dependencies of target libtesseract
[  1%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/adaptions.cpp.o
[  1%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/applybox.cpp.o
[  1%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/control.cpp.o
[  2%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/docqual.cpp.o
[  2%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/equationdetect.cpp.o
[  3%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/fixspace.cpp.o
[  3%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/fixxht.cpp.o
[  3%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/linerec.cpp.o
[  4%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/ltrresultiterator.cpp.o
[  4%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/osdetect.cpp.o
[  5%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/output.cpp.o
[  5%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/pageiterator.cpp.o
[  5%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/pagesegmain.cpp.o
[  6%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/pagewalk.cpp.o
[  6%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/par_control.cpp.o
[  7%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/paramsd.cpp.o
[  7%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/pgedit.cpp.o
[  7%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/recogtraining.cpp.o
[  8%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/reject.cpp.o
[  8%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/resultiterator.cpp.o
[  8%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/superscript.cpp.o
[  9%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/tessbox.cpp.o
[  9%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/tessedit.cpp.o
[  9%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/tesseractclass.cpp.o
[  9%] Building CXX object CMakeFiles/libtesseract.dir/src/ccmain/tfacepp.cpp.o
[  9%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/blobbox.cpp.o
[ 10%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/blobs.cpp.o
[ 11%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/coutln.cpp.o
[ 11%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/imagedata.cpp.o
[ 11%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/ocrrow.cpp.o
[ 11%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/pageres.cpp.o
[ 12%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/pdblock.cpp.o
[ 13%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/polyblk.cpp.o
[ 13%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/quspline.cpp.o
[ 14%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/ratngs.cpp.o
[ 14%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/rect.cpp.o
[ 15%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/seam.cpp.o
[ 15%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/split.cpp.o
[ 16%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/statistc.cpp.o
[ 16%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/stepblob.cpp.o
[ 16%] Building CXX object CMakeFiles/libtesseract.dir/src/ccstruct/werd.cpp.o
[ 16%] Building CXX object CMakeFiles/libtesseract.dir/src/ccutil/params.cpp.o
[ 16%] Building CXX object CMakeFiles/libtesseract.dir/src/ccutil/scanutils.cpp.o
[ 16%] Building CXX object CMakeFiles/libtesseract.dir/src/ccutil/tessdatamanager.cpp.o
[ 17%] Building CXX object CMakeFiles/libtesseract.dir/src/ccutil/tprintf.cpp.o
[ 17%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/adaptive.cpp.o
[ 17%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/adaptmatch.cpp.o
[ 18%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/blobclass.cpp.o
[ 18%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/classify.cpp.o
[ 18%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/cutoffs.cpp.o
[ 18%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/float2int.cpp.o
[ 18%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/intfx.cpp.o
[ 18%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/intmatcher.cpp.o
[ 19%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/intproto.cpp.o
[ 19%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/mfoutline.cpp.o
[ 19%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/normmatch.cpp.o
[ 20%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/outfeat.cpp.o
[ 20%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/picofeat.cpp.o
[ 20%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/protos.cpp.o
[ 21%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/shapeclassifier.cpp.o
[ 21%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/tessclassifier.cpp.o
[ 22%] Building CXX object CMakeFiles/libtesseract.dir/src/classify/trainingsample.cpp.o
[ 22%] Building CXX object CMakeFiles/libtesseract.dir/src/cutil/callcpp.cpp.o
[ 22%] Building CXX object CMakeFiles/libtesseract.dir/src/lstm/input.cpp.o
[ 23%] Building CXX object CMakeFiles/libtesseract.dir/src/lstm/lstmrecognizer.cpp.o
[ 23%] Building CXX object CMakeFiles/libtesseract.dir/src/lstm/network.cpp.o
[ 23%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/alignedblob.cpp.o
[ 24%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/baselinedetect.cpp.o
[ 24%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/ccnontextdetect.cpp.o
[ 24%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/colfind.cpp.o
[ 24%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/colpartition.cpp.o
[ 25%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/colpartitiongrid.cpp.o
[ 25%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/colpartitionset.cpp.o
[ 25%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/devanagari_processing.cpp.o
[ 26%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/drawtord.cpp.o
[ 26%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/edgblob.cpp.o
[ 26%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/edgloop.cpp.o
[ 26%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/fpchop.cpp.o
[ 27%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/imagefind.cpp.o
[ 27%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/linefind.cpp.o
[ 27%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/makerow.cpp.o
[ 28%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/oldbasel.cpp.o
[ 28%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/strokewidth.cpp.o
[ 29%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/tabfind.cpp.o
[ 29%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/tablefind.cpp.o
[ 29%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/tablerecog.cpp.o
[ 30%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/tabvector.cpp.o
[ 30%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/textlineprojection.cpp.o
[ 31%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/textord.cpp.o
[ 31%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/topitch.cpp.o
[ 31%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/tordmain.cpp.o
[ 32%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/tospace.cpp.o
[ 33%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/wordseg.cpp.o
[ 33%] Building CXX object CMakeFiles/libtesseract.dir/src/textord/workingpartset.cpp.o
[ 33%] Building CXX object CMakeFiles/libtesseract.dir/src/viewer/scrollview.cpp.o
[ 34%] Building CXX object CMakeFiles/libtesseract.dir/src/viewer/svmnode.cpp.o
[ 34%] Building CXX object CMakeFiles/libtesseract.dir/src/viewer/svpaint.cpp.o
[ 34%] Building CXX object CMakeFiles/libtesseract.dir/src/viewer/svutil.cpp.o
[ 35%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/associate.cpp.o
[ 35%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/chop.cpp.o
[ 35%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/chopper.cpp.o
[ 36%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/drawfx.cpp.o
[ 36%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/findseam.cpp.o
[ 36%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/gradechop.cpp.o
[ 37%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/language_model.cpp.o
[ 37%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/lm_consistency.cpp.o
[ 37%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/lm_pain_points.cpp.o
[ 38%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/lm_state.cpp.o
[ 38%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/outlines.cpp.o
[ 39%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/pieces.cpp.o
[ 39%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/plotedges.cpp.o
[ 39%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/render.cpp.o
[ 40%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/segsearch.cpp.o
[ 40%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/tface.cpp.o
[ 41%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/wordclass.cpp.o
[ 41%] Building CXX object CMakeFiles/libtesseract.dir/src/wordrec/wordrec.cpp.o
[ 41%] Building CXX object CMakeFiles/libtesseract.dir/src/api/baseapi.cpp.o
[ 42%] Building CXX object CMakeFiles/libtesseract.dir/src/api/capi.cpp.o
[ 42%] Building CXX object CMakeFiles/libtesseract.dir/src/api/renderer.cpp.o
[ 42%] Building CXX object CMakeFiles/libtesseract.dir/src/api/altorenderer.cpp.o
[ 43%] Building CXX object CMakeFiles/libtesseract.dir/src/api/hocrrenderer.cpp.o
[ 43%] Building CXX object CMakeFiles/libtesseract.dir/src/api/lstmboxrenderer.cpp.o
[ 43%] Building CXX object CMakeFiles/libtesseract.dir/src/api/pdfrenderer.cpp.o
[ 44%] Building CXX object CMakeFiles/libtesseract.dir/src/api/wordstrboxrenderer.cpp.o
[ 45%] Linking CXX shared library libtesseract.so
[ 78%] Built target libtesseract
Scanning dependencies of target tesseract
[ 79%] Building CXX object CMakeFiles/tesseract.dir/src/api/tesseractmain.cpp.o
[ 79%] Linking CXX executable bin/tesseract
[ 79%] Built target tesseract
[ 80%] Built target tessopt
Scanning dependencies of target common_training
[ 80%] Building CXX object src/training/CMakeFiles/common_training.dir/commandlineflags.cpp.o
[ 81%] Building CXX object src/training/CMakeFiles/common_training.dir/commontraining.cpp.o
[ 81%] Building CXX object src/training/CMakeFiles/common_training.dir/mastertrainer.cpp.o
[ 82%] Linking CXX static library libcommon_training.a
[ 84%] Built target common_training
Scanning dependencies of target unicharset_training
[ 84%] Building CXX object src/training/CMakeFiles/unicharset_training.dir/lstmtester.cpp.o
[ 85%] Building CXX object src/training/CMakeFiles/unicharset_training.dir/lstmtrainer.cpp.o
[ 86%] Linking CXX static library libunicharset_training.a
[ 89%] Built target unicharset_training
Scanning dependencies of target unicharset_extractor
[ 90%] Building CXX object src/training/CMakeFiles/unicharset_extractor.dir/unicharset_extractor.cpp.o
[ 90%] Linking CXX executable ../../bin/unicharset_extractor
[ 90%] Built target unicharset_extractor
Scanning dependencies of target set_unicharset_properties
[ 90%] Building CXX object src/training/CMakeFiles/set_unicharset_properties.dir/set_unicharset_properties.cpp.o
[ 91%] Linking CXX executable ../../bin/set_unicharset_properties
[ 91%] Built target set_unicharset_properties
Scanning dependencies of target lstmtraining
[ 92%] Building CXX object src/training/CMakeFiles/lstmtraining.dir/lstmtraining.cpp.o
[ 92%] Linking CXX executable ../../bin/lstmtraining
[ 92%] Built target lstmtraining
Scanning dependencies of target lstmeval
[ 92%] Building CXX object src/training/CMakeFiles/lstmeval.dir/lstmeval.cpp.o
[ 92%] Linking CXX executable ../../bin/lstmeval
[ 92%] Built target lstmeval
Scanning dependencies of target combine_lang_model
[ 92%] Building CXX object src/training/CMakeFiles/combine_lang_model.dir/combine_lang_model.cpp.o
[ 92%] Linking CXX executable ../../bin/combine_lang_model
[ 92%] Built target combine_lang_model
Scanning dependencies of target combine_tessdata
[ 93%] Building CXX object src/training/CMakeFiles/combine_tessdata.dir/combine_tessdata.cpp.o
[ 93%] Linking CXX executable ../../bin/combine_tessdata
[ 93%] Built target combine_tessdata
Scanning dependencies of target classifier_tester
[ 94%] Building CXX object src/training/CMakeFiles/classifier_tester.dir/classifier_tester.cpp.o
[ 94%] Linking CXX executable ../../bin/classifier_tester
[ 94%] Built target classifier_tester
Scanning dependencies of target ambiguous_words
[ 94%] Building CXX object src/training/CMakeFiles/ambiguous_words.dir/ambiguous_words.cpp.o
[ 94%] Linking CXX executable ../../bin/ambiguous_words
[ 94%] Built target ambiguous_words
Scanning dependencies of target wordlist2dawg
[ 94%] Building CXX object src/training/CMakeFiles/wordlist2dawg.dir/wordlist2dawg.cpp.o
[ 95%] Linking CXX executable ../../bin/wordlist2dawg
[ 95%] Built target wordlist2dawg
Scanning dependencies of target cntraining
[ 95%] Building CXX object src/training/CMakeFiles/cntraining.dir/cntraining.cpp.o
[ 96%] Linking CXX executable ../../bin/cntraining
[ 96%] Built target cntraining
Scanning dependencies of target dawg2wordlist
[ 96%] Building CXX object src/training/CMakeFiles/dawg2wordlist.dir/dawg2wordlist.cpp.o
[ 96%] Linking CXX executable ../../bin/dawg2wordlist
[ 96%] Built target dawg2wordlist
Scanning dependencies of target text2image
[ 96%] Building CXX object src/training/CMakeFiles/text2image.dir/text2image.cpp.o
[ 96%] Building CXX object src/training/CMakeFiles/text2image.dir/pango_font_info.cpp.o
[ 96%] Linking CXX executable ../../bin/text2image
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/text2image.dir/pango_font_info.cpp.o: undefined reference to symbol 'g_free'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libglib-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/training/CMakeFiles/text2image.dir/build.make:210: bin/text2image] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:615: src/training/CMakeFiles/text2image.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2
walter@nico:build-linux>make -i
[ 78%] Built target libtesseract
[ 79%] Built target tesseract
[ 80%] Built target tessopt
[ 84%] Built target common_training
[ 89%] Built target unicharset_training
[ 90%] Built target unicharset_extractor
[ 91%] Built target set_unicharset_properties
[ 92%] Built target lstmtraining
[ 92%] Built target lstmeval
[ 92%] Built target combine_lang_model
[ 93%] Built target combine_tessdata
[ 94%] Built target classifier_tester
[ 94%] Built target ambiguous_words
[ 95%] Built target wordlist2dawg
[ 96%] Built target cntraining
[ 96%] Built target dawg2wordlist
[ 96%] Linking CXX executable ../../bin/text2image
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/text2image.dir/pango_font_info.cpp.o: undefined reference to symbol 'g_free'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libglib-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[ 99%] Built target text2image
Scanning dependencies of target mftraining
[ 99%] Building CXX object src/training/CMakeFiles/mftraining.dir/mftraining.cpp.o
[ 99%] Linking CXX executable ../../bin/mftraining
[100%] Built target mftraining
Scanning dependencies of target shapeclustering
[100%] Building CXX object src/training/CMakeFiles/shapeclustering.dir/shapeclustering.cpp.o
[100%] Linking CXX executable ../../bin/shapeclustering
[100%] Built target shapeclustering

**Comment by zdenop** [comment]
What is OS version, pango version? 
`cmake .` does not work, but according your info it works ;-) Can you explain it please?
What is output of `pkg-config pango --libs` and `pkg-config pango --cflags`?
Can you try autotools build (which is the primary build system for linux system)?

**Comment by oberw** [comment]
...... cutting edge (almost)...
walter@nico:tesseract>cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20191027"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20191027"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20191027"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"

walter@nico:~> pkg-config pango --libs
-lpango-1.0 

pkg-config pango --cflags
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 

>Can you try autotools build (which is the primary build system for linux system)?
./configure fails, because there is no leptonica (1.74) pkg file, when you build libleptonica from source (opensuse does not provide a libleptonica-dev package)....

.....many ./configure checks deleted...
checking for mbstate_t... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libcurl... no
checking for LEPTONICA... no
configure: error: Leptonica 1.74 or higher is required. Try to install libleptonica-dev package.

but cmake actually works (modulo the text2image build issue).

**Comment by zdenop** [comment]
It seems that your system is in your system or (at least) you have problem with installed of tesseract dependencies. I have experience with opensuse 15.1 and there is no problem to find leptonica with autotools. Correct installation of leptonica provides pc file for pkg-config.

Also your output of `pkg-config pango --libs` is problem (this output is used for tesseract build). My output on opensuse is `-lpango-1.0 -lgobject-2.0 -lglib-2.0` (I got the same output on Raspberry pi which use debian), so you need to fix your pango installation.

Non of above mention problems can be fixed in tesseract.
