### ISSUE TITLE
getting error: ERROR: Program tesseract failed. Abort while lstm training

### ISSUE THREAD

**Issue by Prashantptnk** [tesseract-ocr/tesseract#2754]
I am following the page https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#creating-starter-traineddata to train tesseract 

when I am executing the following command
src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng --linedata_only \
  --noextract_font_properties --langdata_dir ../langdata \
  --tessdata_dir ./tessdata --output_dir ~/tesstutorial/engtrain

I am getting an error like 
Failed to read pages from /tmp/eng-2019-11-11.zCi/eng.Century_Schoolbook_L_Medium.exp0.tif
Error during processing.
Failed to read pages from /tmp/eng-2019-11-11.zCi/eng.Century_Schoolbook_L_Italic.exp0.tif
Failed to read pages from /tmp/eng-2019-11-11.zCi/eng.Arial.exp0.tif
Error during processing.
Error during processing.
Failed to read pages from /tmp/eng-2019-11-11.zCi/eng.Century_Schoolbook_L_Bold.exp0.tif
Error during processing.
Failed to read pages from /tmp/eng-2019-11-11.zCi/eng.Arial_Bold.exp0.tif
Error during processing.
ERROR: Program tesseract failed. Abort.
ERROR: Program tesseract failed. Abort.

![train error](https://user-images.githubusercontent.com/57214369/68565563-efdccb80-0479-11ea-84aa-b7ec3161cfa0.jpg)

Any idea how to fix this?

**Comment by Shreeshrii** [comment]
see https://github.com/tesseract-ocr/tesseract/issues/2748

**Comment by Shreeshrii** [comment]
please close the issue - https://github.com/tesseract-ocr/tesseract/issues/2748#issuecomment-552836635
