### ISSUE TITLE
Illegal instruction on run

### ISSUE THREAD

**Issue by don41382** [tesseract-ocr/tesseract#2757]
### Environment

* **Tesseract Version**: 4.1.0
* **Commit Number**: Release 4.1.0 (5280bbc)
* **Platform**: Raspberry PI - Raspbian 9 (stretch)

```
# teseract -v
tesseract 4.1.0
 leptonica-1.77.0
  libjpeg 6b (libjpeg-turbo 1.5.1) : libpng 1.6.28 : libtiff 4.0.8 : zlib 1.2.8 : libwebp 0.5.2 : libopenjp2 2.1.2
```

### Current Behavior:
After building Tesseract from scratch (like explained in the Wiki on my Raspberry PI) I'll get the following error:
```
# tesseract --list-langs
Illegal instruction
```

Listing the help or the version works. I also tried the last recent version from master and that didn't work either. I think, it must be something with my setup. Any Ideas?

### Expected Behavior:
Not to crash

**Comment by zdenop** [comment]
I have no problem to build and run `tesseract --list-langs` on raspberry pi. Does it mean
`tesseract -v` does not crash?
With information you provide it is not possible to help you. (e.g. exact build information and configuration logs would help). Also try to use the latest code from git...

**Comment by don41382** [comment]
Hey @zdenop,

yes ```tesseract -v``` does not crash, but ```tesseract --list-langs``` does.

I switched from my Raspberry Pi 2 to Raspberry Pi 3 B and now it works.

Seems like the Pi 2 is not supported anymore?!

**Comment by zdenop** [comment]
IMO if you compile it on Raspberry Pi 2, it should run... Maybe you can try to build debug version and run it in gdb to see where exactly it crash...
But tesseract 4 use lstm, so new hardware is better solution...

**Comment by amitdo** [comment]
@don41382,

Does the issue still exist with the latest code on the master branch?

**Comment by stweil** [comment]
@don41382, if you compiled 4.1.0 with cmake, it might have used compiler options which generate code optimized for RPi 3 (similar issues exist for Intel hardware and AVX2). You could try an autotools build, or better use the latest code.

**Comment by amitdo** [comment]
No response from the OP.
