### ISSUE TITLE
old version

### ISSUE THREAD

**Issue by dzz10** [tesseract-ocr/tesseract#2758]
How do I install the old version of the library?

For example: tesseract3.0.5 tesseract4.1.0.

I want to use 3.0.5, which was available before, but it has been updated to 4.1.0 recently.

**Comment by Jamxscape** [comment]
> How do I install the old version of the library?
> 
> For example: tesseract3.0.5 tesseract4.1.0.
> 
> I want to use 3.0.5, which was available before, but it has been updated to 4.1.0 recently.

have you solved this problem? I want to use 3.05.00 in MAC OSX, but i didn't find a right way to install

**Comment by dzz10** [comment]
我用的Windows
MAC 应该是直接源码编译



At 2020-05-11 01:56:03, "马元" <notifications@github.com> wrote:

How do I install the old version of the library?

For example: tesseract3.0.5 tesseract4.1.0.

I want to use 3.0.5, which was available before, but it has been updated to 4.1.0 recently.

have you solved this problem? I want to use 3.05.00 in MAC OSX, but i didn't find a right way to install
