### ISSUE TITLE
Can`t open file 'text_recognition.py' No such file or directory

### ISSUE THREAD

**Issue by GhadeerAlanazi** [tesseract-ocr/tesseract#2759]
![image](https://user-images.githubusercontent.com/38314036/68693035-982c8600-0587-11ea-9e7a-778e90ecc8c3.png)

I am trying to follow this guide to use tesseract on raspberry pi. 
https://www.pyimagesearch.com/2018/09/17/opencv-ocr-and-text-recognition-with-tesseract/

**Comment by stweil** [comment]
That's third party software, so you are completely wrong here.

**Comment by stweil** [comment]
Please use the user forum for questions.
