### ISSUE TITLE
Tesseract 4.1 Crash 

### ISSUE THREAD

**Issue by zhao-lun** [tesseract-ocr/tesseract#2761]
-----------------------
### Environment
Windows 7 Professional 64BIT
* **Tesseract Version**:  4.1.0
* **Commit Number**: not sure, from vcpkg
* **Platform**: Windows

Hardware
CPU: i7-3770 (Intel official website indicates it has AVX,SSE supported)

### Current Behavior:
It crashed when it tried to init. 
(new tesseract::TessBaseAPI())
Crash Code: C000001D, illegal instruction set. 
Have tried to disable avx flag. 
`avx2_available_ = false; `
but its not working either.
*Edit: Tried debug the app, found out it crashed at instruction 
**vpxor mm mm** which is an AVX2 instruction. 
### Expected Behavior:
Works on every other machine i have. i5 8250U, intel xeon.

**Comment by zdenop** [comment]
Please test tesseract executable instead your own custom code where reporting issue.

**Comment by zhao-lun** [comment]
Hi @zdenop , yes. i have tried that too. Same thing. 
I use the windows pre-built binary on the machine. 
It crashed.

**Comment by zdenop** [comment]
Try the latest windows binary from [UB Mannheim](https://github.com/UB-Mannheim/tesseract/wiki) and if it works try the latest git code.

**Comment by zhao-lun** [comment]
Yes. My bad. Should have mentioned this.
The binary is from UB Mannheim.

**Comment by zdenop** [comment]
The latest or 4.1.0?

**Comment by stweil** [comment]
@zhao-lun, please post the full command line which you used and all output from the program.

**Comment by zhao-lun** [comment]
@zdenop 4.1.0 
@stweil  tesseract.exe -v

**Comment by zdenop** [comment]
Try the latest  version + provide full test case (code + how you compile it)

**Comment by stweil** [comment]
No other output? Please use https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.0-alpha.20191030.exe.

**Comment by stweil** [comment]
@zhao-lun, your issue report is not consistent. You write that your binary is from vcpkg, but you also write it is from UB Mannheim. UB Mannheim does not provide versions which only say `4.1`, and their executable does not execute AVX instructions when running `tesseract -v`. There are also no AVX instructions in the constructor of `TessBaseAPI`.

**Comment by zhao-lun** [comment]
Hi @zdenop, @stweil . I made a mistake. Apparently, i use the wrong binary, it's from the vcpkg installed\tesseract\x64-windows-rel\bin. 
Anyway, i tested out pre-built binary from UB Mannheim, 4.1.0, 5.0.0 alpha it works.
It seem something wrong with the vcpkg built that caused the crash. 
Im using the latest rev of vcpkg. which is the rev 4.1.0-3 port. 
I have tried running both `tesseract -v` and launch tesseract.exe alone. 
It access to AVX instructions (vpbroadcastid) even though i manually disable all the avx/avx2 flag. 
`avx2_available_ = false;` *in SIMDDETECT.cpp

**Comment by zdenop** [comment]
You  need to pass `-DSW_BUILD=OFF` to vcpkg  or maybe to build tesseract just with cmake, so you can have better control over build. It should be not big issue if you have leptonica build already.

**Comment by whatohyou** [comment]
> You need to pass `-DSW_BUILD=OFF` to vcpkg or maybe to build tesseract just with cmake, so you can have better control over build. It should be not big issue if you have leptonica build already.

How do you pass `-DSW_BUILD=OFF` to vcpkg?

**Comment by zdenop** [comment]
See https://github.com/microsoft/vcpkg/issues/8991. There is also nice how to [Compiling Tesseract and Libleptonica (using vcpkg)](https://github.com/charlesw/tesseract/wiki/Compiling-Tesseract-and-Libleptonica-(using-vcpkg)).
