### ISSUE TITLE
missing dependency error when installing for tensorflow.

### ISSUE THREAD

**Issue by Prashantptnk** [tesseract-ocr/tesseract#2762]
![tensorflow error](https://user-images.githubusercontent.com/57214369/68758334-a506b380-0633-11ea-96fd-cb0a08a209d9.jpg)
![tensorflow error](https://user-images.githubusercontent.com/57214369/68758351-adf78500-0633-11ea-9ab7-eac8dfffb0d2.jpg)

### Environment: Ubuntu 18.04

* **Tesseract Version**: 3.05.02
* **Commit Number**: 
* **Platform**:  Linux (Ubuntu 18.04 bionic)

### Current Behavior: While trying to build tesseract with tensorflow, I am using the command
**apt-get install libprotoc-dev libtensorflow-dev**

But I am getting an error 
**(base) prashant1@ubuntu:~/Downloads$** sudo apt-get install libprotoc-dev libtensorflow-dev
[sudo] password for prashant1: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtensorflow-dev is already the newest version (1.10.1+dfsg-A1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libprotoc-dev : Depends: libprotobuf-dev (= 3.0.0-9.1ubuntu1) but 3.10.1-1 is to be installed
E: Unable to correct problems, you have held broken packages._

Please let me know if there is any fix for this

**Comment by zdenop** [comment]
I am sorry, but this is not tesseract error.

**Comment by Prashantptnk** [comment]
> I am sorry, but this is not tesseract error.

Apologies Sir, But the command I am trying to execute comes from a page  
https://github.com/tesseract-ocr/tesseract/wiki/Compiling-%E2%80%93-GitInstallation#build-with-tensorflow

So either the information provided on the page is incorrect or I am making some mistakes while executing the command.

Requesting you to please keep the thread open so that newbies like me who are struggling with the same issue will get help.

**Comment by stweil** [comment]
We expect that people who build Tesseract from source - especially with features marked as new or experimental like the support for Tensorflow - are also able to solve the usual problems on their own. Only real issues should be reported here, or even better, you find a solution and update the Wiki or send a pull request.

Please use the user forum for questions.
