### ISSUE TITLE
Tesseract fails to recognize lines! 

### ISSUE THREAD

**Issue by ShroukMansour** [tesseract-ocr/tesseract#2763]
### Environment

Tesseract Version: tesseract 4.1.0

Platform: Linux shrouk-Precision-T3600 4.15.0-66-generic #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
I give tesseract this cropped line with parameter `--psm 7` and `lang='ara'`, but the resulted dataframe is empty, having only one row with conf = -1.
![missing_line](https://user-images.githubusercontent.com/18499889/68864867-7acbf900-06fa-11ea-9ac8-789245f9ee13.jpg)

### Expected Behavior:

I've tested tesseract with many many lines with exact conditions like this and it succeeded in all! 
Also when I try to crop this line into two portions it succeeds in one but fails in the other. I really can not understand why this is happening! 

@ismail  @ryanfb  @icblenke  @kant  @devurandom  Would you please help me as I really have spent too much time trying to understand why this is happening!

**Comment by Shreeshrii** [comment]
tesseract -v
tesseract 5.0.0-alpha-550-g944c1
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.4.4 : libopenjp2 2.3.0

TESSDATA_PREFIX=/home/ubuntu/tessdata_best

```
ubuntu@tesseract-ocr:~/TEST$ tesseract  2763.jpg - -l ara
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 639
الحركة الوطنية المغربية هى امتداد لحركات الجهاد التى كانت تنطلق من المساجد والزوايا والرباطات لصد الغزو الإسباني
ubuntu@tesseract-ocr:~/TEST$ tesseract  2763.jpg - -l ara --psm 7
Warning: Invalid resolution 0 dpi. Using 70 instead.
الحركة الوطنية المغربية هى امتداد لحركات الجهاد التى كانت تنطلق من المساجد والزوايا والرباطات لصد الغزو الإسباني
ubuntu@tesseract-ocr:~/TEST$ tesseract  2763.jpg - -l ara --psm 6
Warning: Invalid resolution 0 dpi. Using 70 instead.
الحركة الوطنية المغربية هى امتداد لحركات الجهاد التى كانت تنطلق من المساجد والزوايا والرباطات لصد الغزو الإسباني
```

**Comment by zdenop** [comment]
Tesseract does not output dataframe, so please respect guidelines for posting issue: we do not provide support for 3rd party projects.
