### ISSUE TITLE
What lang.trainddata is used to detect unlearned characters?

### ISSUE THREAD

**Issue by ShinhwanKim** [tesseract-ocr/tesseract#2764]
Hi, 
I made a traineddata that learned new fonts.
At this time, I didn't learn many letters, but I only learned about 'abcde'.
And to make sure it's learned, I've detected an 'abcde' image made of the same font.
The result was good.
And then we did it again by mixing the sequence and increasing the amount, just like 'baced'.
But this time, the results were not good.
There were some letters that could not be detected properly.
And the most incomprehensible part is that I've learned only 'abcde'.
Tesseract has printed letters that Tesseract don't learn, such as 'lmnop'.
When using the trained data that I've learned directly from Tesseract, do I detect unlearned characters with the Lang.trained data that is set by default in Tesseract?

### Environment
Tesseract Version : 4.0.0
Windows 10  64-bit -->

Current Behavior:

### Expected Behavior:
I want to know which Lang.trinddata is used to detect unlearned characters.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
For issue tracker you must provide all detail for preproducing of issue, otherwise it does not make sense.

**Comment by ShinhwanKim** [comment]
So sorry, my mistake
