### ISSUE TITLE
Tesseract deosn't give good results

### ISSUE THREAD

**Issue by Diaislam** [tesseract-ocr/tesseract#2765]
i tried tesseract 3.04.1 and 4 for this images
![image](https://user-images.githubusercontent.com/33395350/68934539-2460c800-0797-11ea-84ef-f38b03f9cc5f.png)
as you see it confuses zeros with 6 and sometimes 8

**Comment by stweil** [comment]
Such images need preprocessing before handling them to Tesseract. Try to get a good looking binarized or gray image.

This is not an issue. Tesseract does not claim that it can handle all cases of images equally good.

**Comment by Diaislam** [comment]
i preprocessed the images and tried with all filter it sill doesn't give good results , the problem is with the zero , i though tesseract was trained with all types of digits
