### ISSUE TITLE
Retain all bounding box levels in Alto output

### ISSUE THREAD

**Issue by marma** [tesseract-ocr/tesseract#2766]
Comparing Alto output from our digitization and from Tesseract I noticed that the ComposedBlock level is "missing".

Currently generated Alto contains three levels (RIL_BLOCK, RIL_LINE and RIL_WORD) skipping over RIL_PARA. However, Alto has two block levels, TextBlock and ComposedBlock where the former seem to map to RIL_PARA and the latter to RIL_BLOCK.

Here is a file generated by Zissor: https://data.kb.se/datasets/2014/10/aftonbladet/1862/01/urn%253Anbn%253Ase%253Akb%253Adark-29967/bib4345612_18620103_0_s_0001_alto.xml

### Environment

* **Tesseract Version**: 4.1
* **Commit Number**: 2d6f38e
* **Platform**: Ubuntu 19.10

### Current Behavior:
Alto generation outputs RIL_BLOCK, RIL_LINE and RIL_WORD as TextBlock, TextLine and String respectively.

### Expected Behavior:
Generation of all levels in Alto, i.e ComposedBlock, TextBlock, TextLine and String from RIL_BLOCK, RIL_PARA, RIL_LINE and RIL_WORD

### Suggested Fix:
Add support for ComposedBlock. Possibly through a command line or config parameter to avoid breaking changes?

I made a fix that works for me over here https://github.com/marma/tesseract/commit/2617bea38c7fde7d4073e5248c17a6fdf3e80e6c

**Comment by stweil** [comment]
Thank you for reporting and fixing this. Do you want to send a pull request?

Unrelated: A pull request which adds you to https://github.com/hbunke/BibsOnGitHub/blob/master/list.md would also be nice.

**Comment by stweil** [comment]
> Possibly through a command line or config parameter to avoid breaking changes?

I don't think that is necessary. `ComposedBlock` should be added unconditionally.

**Comment by marma** [comment]
Great! I'll send a pull request once the commit has passed all the tests. And I'll add myself to the BibsOnGit :)

**Comment by stweil** [comment]
Maybe you can also comment on issue #2700 (is the image filename desired in ALTO output).

**Comment by marma** [comment]
@stweil I'm having some problems with running `make check` even on a freshly cloned repo from the 4.1 branch. On Ubuntu 19.10 and a clean Ubuntu 18.04 (using Docker) I end up with the following:

/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++17   -o applybox_test applybox_test.o libgtest.la libgtest_main.la -lpthread ../src/api/libtesseract.la   -llept -lpthread
libtool: link: g++ -g -O2 -std=c++17 -o .libs/applybox_test applybox_test.o  ./.libs/libgtest.a ./.libs/libgtest_main.a ../src/api/.libs/libtesseract.so -llept -lpthread -fopenmp
applybox_test.o: In function `(anonymous namespace)::ApplyBoxTest::VerifyBoxesAndText(char const*, char const*, char const*, bool)':
/tesseract/unittest/include_gunit.h:44: undefined reference to `tesseract::File::JoinPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tesseract/unittest/include_gunit.h:44: undefined reference to `tesseract::File::JoinPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tesseract/unittest/include_gunit.h:44: undefined reference to `tesseract::File::JoinPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Makefile:1389: recipe for target 'applybox_test' failed

Any hints?

**Comment by stweil** [comment]
Did you try that only with tesseract-4.1 or also with Git master? I just tested it with Ubuntu Bionic and `make check` builds all tests (it fails when running the tests because of missing data).

The linker statement for `applybox_test` looks like this:

    /bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++17   -o applybox_test applybox_test.o ../src/training/libtesseract_training.la ../src/training/libtesseract_tessopt.la libgtest.la libgtest_main.la -lpthread ../src/api/libtesseract.la   -llept -lpthread 
    libtool: link: g++ -g -O2 -std=c++17 -o .libs/applybox_test applybox_test.o  ../src/training/.libs/libtesseract_training.a ../src/training/.libs/libtesseract_tessopt.a ./.libs/libgtest.a ./.libs/libgtest_main.a ../src/api/.libs/libtesseract.so -llept -lpthread -fopenmp

**Comment by stweil** [comment]
Does it work with this patch?

    diff --git a/unittest/include_gunit.h b/unittest/include_gunit.h
    index 0cacaa9f..8982b186 100644
    --- a/unittest/include_gunit.h
    +++ b/unittest/include_gunit.h
    @@ -41,7 +41,7 @@ public:
       }
     
       static std::string JoinPath(const std::string& s1, const std::string& s2) {
    -    return tesseract::File::JoinPath(s1, s2);
    +    return File::JoinPath(s1, s2);
       }
     
       static std::string JoinPath(const std::string& s1, const std::string& s2,

**Comment by marma** [comment]
It seems that this was fixed while I did something else :)

The tests build and I get at least the same errors with or without the change to altorenderer.cpp. Should I create a pull request to master or 4.1 branch?

**Comment by stweil** [comment]
We need it for both, but master has first priority.

**Comment by stweil** [comment]
Pull request #2768 added `ComposedBlock`, so I think this issue can be closed.

When I look at the resulting ALTO file, I wonder whether we should replace the tabs used for indentation by groups of two spaces (similar to the hOCR output). Maybe this can even be a config variable `xml_indent`, so users can chose to omit indentation to minimize the file size by passing `-c xml_indent=""`.

**Comment by marma** [comment]
I've made pull requests for both.

I think adding both variables for both xml_indent and an alto_composedblock that turns ComposedBlocks on or off might be a good idea and might make the feature less obtrusive if it is off by default in 4.x and on by default in 5.x. I could look into it?

**Comment by stweil** [comment]
I think that `ComposedBlock` in 4.1 is a bug fix and don't think that it is necessary to add a config variable to switch it off. We already have more config variables than most users can handle.

If you want to add `xml_indent` that would be very nice.
