### ISSUE TITLE
LSTM:Deserialize failed

### ISSUE THREAD

**Issue by Prashantptnk** [tesseract-ocr/tesseract#2767]
### Ubuntu

* **Tesseract Version**: 5.0 Alpha
* **Commit Number**: 
* **Platform**: Ubuntu 18.04

### Current Behavior:
When trying to finetune the training I am using 
lstmeval --model ~/tesstutorial/engtrain/eng/eng.traineddata   --eval_listfile ~/tesstutorial/engeval/eng.training_files.txt --traineddata ~/tesstutorial/engtrain/eng/eng.traineddata 

I am getting an error 

Loaded 72/72 lines (1-72) of document /home/prashant1/tesstutorial/engeval/eng.Impact_Condensed.exp0.lstmf
Deserialize failed

I tried referring issue #792 but couldn't find helpful.

please let me know what could be the fix.

**Comment by Shreeshrii** [comment]
Does the file exist?

**Comment by Prashantptnk** [comment]
No, just noticed, the file eng.Impact_Condensed.exp0.lstmf doesn't exist. How can I generate the file?

**Comment by Shreeshrii** [comment]
What is the file size? How did you generate it? Did you copy it between different platforms?

**Comment by Prashantptnk** [comment]
the file is auto-generated. I have not copied it. The size is around 403.9 kb.

**Comment by Shreeshrii** [comment]
Please see https://github.com/Shreeshrii/tess4training/blob/master/4-impact_from_full.log for log from a successful run of tesstutorial from a few months ago. If you follow the instructions then there should be no errors.

**Comment by amitdo** [comment]
Old issue, probably a user error.
