### ISSUE TITLE
Regression: inverted image with pdf output mode and monochrome input TIFF

### ISSUE THREAD

**Issue by callegar** [tesseract-ocr/tesseract#2771]
### Environment

* **Tesseract Version**: 5.0.0-alpha-546
* **Commit Number**: g41c3
* **Platform**: Linux X86-64 (Kubuntu disco)

### Current Behavior:

Suppose that I have a monochrome file a.tiff. Doing
```
tesseract -l ita a.tiff a pdf
```
returns a pdf where the image colors are inverted (black for white and viceversa)

### Expected Behavior:

Colors should remain the same as in the original tiff.

**Comment by callegar** [comment]
Tesseract 4.1 does not have the issue on the same file.

**Comment by zdenop** [comment]
Please respect guidance for posting issue!
1. When reporting issue use the lastest source code.
2. When reporting issue search if it was not already reported or solved #2059
3. When reporting issue provide test case for replicating problem. Otherwise your report is useless.

**Comment by callegar** [comment]
Sorry for the non-conforming report.
1. git version g41c3 is really the newest I can test installing from a deb...
2. I tried to search but I missed #2059 that doesn't really have a very helpful title for searching (no word about color inversion)
3. Will try to provide a test case next time I encounter an issue.

Thanks for fixing my poor duplicate search.

**Comment by zdenop** [comment]
If you have this problem with the latest code, provide information (in 2059) for reproducing problem.

**Comment by stweil** [comment]
@callegar, I updated the title for #2059, so hopefully it will be easier to find in the future.

Could you please update your TIFF as an example for #2059? You report that this problem did not happen with 4.1, so it should be possible to find the commit which introduced it by using git bisect. That information would help in fixing the problem.

**Comment by stweil** [comment]
Sorry, I missed commit 2d6f38e where @zdenop fixed the problem. @callegar, so you can try the latest code which should work for you.
