### ISSUE TITLE
train tesseract from scratch but have to add some my own training data

### ISSUE THREAD

**Issue by Bipin8469** [tesseract-ocr/tesseract#2774]
### Environment
* **Tesseract Version**: tesseract 4.1.1-rc2-16-g42ec ,  leptonica-1.79.0
* **Platform**: Ubuntu 16.04.6 LTS xenial 

I've trained tesseract from scratch using LSTM and created training data using tesstrain.sh ttf file. 
it gives me perfect OCR on simple text, not the noisy PDF text.

Tesseract Documentation says that it is not possible to train with your own tif and box file. but,
Is there any other option  or jugaad to give my training files for training at the time of tesstrain method with the ttf training files?
As right now it is affecting my accuracy in result without my training data.
Training files i want to use are tiff and box files.

Can anyone please guide, me what should i do?

thank you.

**Comment by stweil** [comment]
Please use the user forum for questions. A look at https://github.com/tesseract-ocr/tesstrain/wiki/ should answer your question.

**Comment by stweil** [comment]
> Tesseract Documentation says that it is not possible to train with your own tiff and box file.

That information is old and no longer valid then. Were did you find it? It should be updated.

**Comment by Bipin8469** [comment]
thank you  for your response. 

I've read it in one of the issues.
