### ISSUE TITLE
TessBaseAPIInit3 weird behaviour when calling multiple times

### ISSUE THREAD

**Issue by svebert** [tesseract-ocr/tesseract#2780]
### Environment

* **Tesseract Version**:  5 alpha, 27.10.2019
* **Commit Number**: cede5b34
* **Platform**: Windows x64

### Current Behavior:
Hi everyone!

I am calling TessBaseAPIInit3 multiple times on program start with different path to find the correct location with the traineddata files. I check the return value of TessBaseAPIInit3 and if it is not equal to 0 i check for the next path.

Example:
```
int MyInit()
{
 std::string path1("tessdata");
 std::string path2("../Wrapper/tessdata");
 std::string path3("../../tessdata");
 std::string lang("ocrb_int");

 TessAPI* handle = TessBaseAPICreate();
 if(TessBaseAPIInit3(handle, path1.c_str(), lang.c_str()) == 0)
 {
  std::cout << "ok, found traineddata" <<std::endl;
  return 0;
 }
 if(TessBaseAPIInit3(handle, path2.c_str(), lang.c_str()) == 0)
 {
  std::cout << "ok, found traineddata" <<std::endl;
  return 0;
 }
 if(TessBaseAPIInit3(handle, path3.c_str(), lang.c_str()) == 0)
 {
  std::cout << "ok, found traineddata" <<std::endl;
  return 0;
 }
 return -1;
}
```

this works fine, if the first call is successful. **BUT** if e.g. the second or third call is successful (I get 0 as return value) the call of `TessBaseAPIGetUTF8Text(handle)` always returns an empty string. It does not matter what kind of image I set with `TessBaseAPISetImage`
### Expected Behavior:
I expect either an error from the second or third call of `TessBaseAPIInit3 ` or that `TessBaseAPIGetUTF8Text ` returns something, not empy strings.

### Suggested Fix:
I fixed this by calling `TessBaseAPIEnd ` before each `TessBaseAPIInit3 ` call.

**Comment by amitdo** [comment]
Did you try to test with the C++ API?

I wonder why you use the C API when your program is written in C++.

**Comment by zdenop** [comment]
API init must be finished appropriately with `api->End()`/`TessBaseAPIEnd` (see relevant wiki example). Calling init multiple times without calling `api->End()` is just bad usage of API.

**Comment by amitdo** [comment]
@zdenop, the C++ API docstring disagree with you :- )  

https://github.com/tesseract-ocr/tesseract/blob/master/include/tesseract/baseapi.h#L195-196

**Comment by svebert** [comment]
> Did you try to test with the C++ API?
> 
> I wonder why you use the C API when your program is written in C++.

Sorry, but my project is a little bit more complex. Actually I wrap the C-API myself and use it in C++; Using the C++ API directly is not an option for me.
