### ISSUE TITLE
OCR on strikeout text 

### ISSUE THREAD

**Issue by Bharathsh36** [tesseract-ocr/tesseract#2783]
I have images of texts like in 
![Image 1 ](https://i.stack.imgur.com/fg1M2.jpg) 

and 

![Image 2](https://i.stack.imgur.com/1Y1z5.jpg). 

Tesseract is unable to detect the numbers. What are the methods that can be employed in order to get numbers from images like above. Please help.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Also read relevant wiki before posting to forum (e.g. describe what you already tried).
