### ISSUE TITLE
Using cmake to build standalone executable ?

### ISSUE THREAD

**Issue by jkang-eng** [tesseract-ocr/tesseract#2786]
### Environment

* **Tesseract Version**: tesseract 5.0.0-alpha-476-g8b69
* **Commit Number**: unknown
* **Platform**: Windows 64bit

### Current Behavior:
I'm currently using cmake following to build tesseract
```
cmake tesseract
cmake --build . --config Release
```
Is there anyway to build a standalone executable? (statically-linked libraries)

**Comment by stweil** [comment]
Please use the user forum for questions.
