### ISSUE TITLE
"Failed to begin document " occurs when want to create searchable pdf from an image 

### ISSUE THREAD

**Issue by grigvardanyan** [tesseract-ocr/tesseract#2787]
Hi,

I want to create pdf from an input image with C#, but during converting it throws exception "Failed to begin document ".
![image](https://user-images.githubusercontent.com/26326278/69794784-5553ea80-11e4-11ea-8cc1-823226aafa15.png)

**Comment by grigvardanyan** [comment]
I missed pdf.ttf file

**Comment by Ayonija** [comment]
I am still getting the same problem, even adding the pdf.ttf file, do you have any idea to solve it?
