### ISSUE TITLE
build system: fix tags / ctags / cscope

### ISSUE THREAD

**Issue by bertsky** [tesseract-ocr/tesseract#2794]
At some point, we lost the automatic identifier tag generation for vi/Emacs source viewing (`make tags ctags`):

```
mkdir build
cd build && ../configure
make tags
Making tags in .
make[1]: Entering directory '~tesseract/build'
make[1]: *** No rule to make target 'dummy.cxx', needed by 'tags-am'.  Stop.
make[1]: Leaving directory '~tesseract/build'
Makefile:4392: recipe for target 'tags-recursive' failed
```

The cause of that is in 
https://github.com/tesseract-ocr/tesseract/blob/14c6e387239a679ac5b58f126ab96e851a5e6624/Makefile.am#L137 
This dummy source file is necessary to get the C++ linker to combine the libtool convenience libraries of all subdirectories. This practise is even recommended by the Automake manual:

https://www.gnu.org/software/automake/manual/html_node/Libtool-Convenience-Libraries.html

But how do we get automatic tagging back?

**Comment by stweil** [comment]
It should be fixed with https://github.com/stweil/tesseract/commit/c7a6ddf38e34fdac890132683bdbf4eb540f644f (still needs to be rebased before merging).

**Comment by bertsky** [comment]
> It should be fixed with [stweil@c7a6ddf](https://github.com/stweil/tesseract/commit/c7a6ddf38e34fdac890132683bdbf4eb540f644f) (still needs to be rebased before merging).

Excellent!

**Comment by stweil** [comment]
It looks like this is an old problem which already existed with Tesseract 4.0.0.

Pull request #2795 fixes it.

**Comment by bertsky** [comment]
> It looks like this is an old problem which already existed with Tesseract 4.0.0.
> 
> Pull request #2795 fixes it.

Thanks!
