### ISSUE TITLE
GitHub recognizes 5.5% of the codebase as written in C

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#2796]
https://github.com/tesseract-ocr/tesseract/search?l=c

For all the .cpp files and for some of the .h files the reason for the wrong detection is this comment in their first line:

https://github.com/tesseract-ocr/tesseract/blob/4e0c726d6c6b5687d0dd826061ecdb230ab55cbc/src/wordrec/chopper.cpp#L1

**Comment by amitdo** [comment]
https://github.com/github/linguist

**Comment by stweil** [comment]
Does anybody still need those hints (I think they were used by editors like Emacs)? If not, I could simply remove them all.

**Comment by stweil** [comment]
We could also replace them by `-*- c++ -*-`.

**Comment by amitdo** [comment]
>We could also replace them by -*- c++ -*-.

For the .cpp files at least, I don't think it's needed. The modeline should be removed.

**Comment by stweil** [comment]
And what about the .h files?

**Comment by amitdo** [comment]
All our headers files should be considered as C++ files.

I think vim recognizes .h files as C++ files by default.

If some IDE recognizes them as C files, usually there's a way to override the default setting per project or directory.

Currently the modelines are wrong and nobody ever complained...

IMO the modelines should be removed from all our files.

**Comment by stweil** [comment]
See pull request #2807.

**Comment by amitdo** [comment]
Thanks!

**Comment by amitdo** [comment]
It's 1.7% now. For some reason some .h files are still recognized as C files. 

https://github.com/tesseract-ocr/tesseract/search?l=c

**Comment by stweil** [comment]
Those .h files only contain C code (I did not check all, but a large part), so there is a good reason to recognize them like that.
