### ISSUE TITLE
I am new here, May I ask How can I compile tesseract 5a on cmake ,it appears ICU and SW issues

### ISSUE THREAD

**Issue by newsblue** [tesseract-ocr/tesseract#2799]

**Comment by newsblue** [comment]
The following ICU libraries were not found:
  uc (required)
  i18n (required)
Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY _ICU_REQUIRED_LIBS_FOUND) (Required is at least version "52.1")
Configuring incomplete, errors occurred!

**Comment by newsblue** [comment]
I use cmake 3.16 gui

**Comment by stweil** [comment]
Please use the user forum for questions.
