### ISSUE TITLE
Compiling latest(master) tesseract branch

### ISSUE THREAD

**Issue by jkang-eng** [tesseract-ocr/tesseract#2801]
Hi team,

I'm currently using "vcpkg install" method to compile tesseract.
It seems to download "https://github.com/tesseract-ocr/tesseract/archive/4.1.0.tar.gz" and compile.

However, I'd like to build from the latest master branch, is this even possible?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support
