### ISSUE TITLE
build system: shared library is gone

### ISSUE THREAD

**Issue by bertsky** [tesseract-ocr/tesseract#2803]
I believe that the recent improvements in the build system brought a major regression: `make install` does not (build and) install libtesseract.so anymore.

This is a huge problem for other software that wants to link to Tesseract (like `tesserocr`). Their build will fall back to the static library, but this can fail by not pulling in Tesseract's dependencies (like `-llept`), or by missing things like `-fsanitize=address`.

@stweil do you want me to give detailed error messages?

**Comment by stweil** [comment]
I cannot confirm this. This is what I just tested:

    ./autogen.sh clean
    mkdir test
    cd test
    nohup ../configure
    nohup make
    make install prefix=$PWD/usr
    ls -l usr/lib/
    insgesamt 213396
    -rw-r--r-- 1 debian debian 163296074 Dez  5 07:13 libtesseract.a
    -rwxr-xr-x 1 debian debian      1075 Dez  5 07:13 libtesseract.la
    lrwxrwxrwx 1 debian debian        21 Dez  5 07:13 libtesseract.so -> libtesseract.so.5.0.0
    lrwxrwxrwx 1 debian debian        21 Dez  5 07:13 libtesseract.so.5 -> libtesseract.so.5.0.0
    -rwxr-xr-x 1 debian debian  55202672 Dez  5 07:13 libtesseract.so.5.0.0
    drwxr-xr-x 2 debian debian      4096 Dez  5 07:13 pkgconfig

**Comment by bertsky** [comment]
False alert – sorry!
