### ISSUE TITLE
Image Size issue

### ISSUE THREAD

**Issue by joshconz** [tesseract-ocr/tesseract#281]
I'm having issues with getting Tesseract to read text out of an image.  Its seems to not read the text in the image in its original size.

![bowenpeak](https://cloud.githubusercontent.com/assets/17915164/13863515/410b1a02-ecff-11e5-9c93-f63825576e21.png)

But when I increase the canvas size it then picks up the text.  Any Ideas on what maybe causing this?

![bowenpeak_lrg](https://cloud.githubusercontent.com/assets/17915164/13863517/47b6f010-ecff-11e5-91a0-7b2c7548f493.png)

**Comment by zdenop** [comment]
Please use [tesseract user forum](https://groups.google.com/forum/#!forum/tesseract-ocr) for asking support (see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice) )
