### ISSUE TITLE
Unable to build master/head with vcpkg

### ISSUE THREAD

**Issue by bleze** [tesseract-ocr/tesseract#2810]
Not sure who maintains package for vcpkg, but here goes...

### Environment

Master
Windows 10, x64

### Current Behavior:

I can build 4.1 find, but --head parameter gives me;
`-- Package does not specify HEAD_REF. Falling back to non-HEAD version`

### Expected Behavior:

That it would get the source for master and build that.

### Suggested Fix:

Add HEAD_REF that is missing from package.

**Comment by zdenop** [comment]
We do not manage vcpkg - you need to rise issue at their project.
