### ISSUE TITLE
Failed loading language 'eng'

### ISSUE THREAD

**Issue by victor713** [tesseract-ocr/tesseract#2811]
Operating System: Debian 9

### Environment

* **Tesseract Version**: tesseract 4.1.1-rc1
* **Platform**: Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

### Current Behavior:
If I execute the command:
`$tesseract test.jpg -l eng pdf`

The error is displayed:

> Error opening data file /usr/local/share/tessdata/eng.traineddata
> Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
> Failed loading language 'eng'
> Tesseract couldn't load any languages!
> Could not initialize tesseract.

I initialised the variable TESSDATA_PREFIX to this path: /opt/tesseract-4.1/tessdata which contains:

> configs  eng.user-patterns  eng.user-words  Makefile  Makefile.am  Makefile.in	pdf.ttf  tessconfigs

### Expected Behavior:
The image file is converted to pdf using OCR

### Suggested Fix:
Why is the English language is not loaded?

**Comment by zdenop** [comment]
duplicate #2770
