### ISSUE TITLE
Status of OpenCL support?

### ISSUE THREAD

**Issue by NetwarSystem** [tesseract-ocr/tesseract#2812]
Can anyone comment on the use of OpenCL with Tesseract in order to speed OCR? There is eighteen month old information that seems promising, nothing more current. Is it now mature?

I have a number of HP workstations with Nvidia GT710 in them - 2 gig, 192 CUDA cores. They have no video related load, I'm wondering how much gain I would see configuring OpenCL. My use case is small work groups with access to Open Semantic Search.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/suppor

**Comment by stweil** [comment]
The OpenCL code exists and should work, but currently does not give a performance gain because still too much work is done on the CPU. Anyone who wants to improve that is invited to do so and provide a pull request.
