### ISSUE TITLE
An enormous amount of compiler warnings in Debug build

### ISSUE THREAD

**Issue by db4** [tesseract-ocr/tesseract#2816]
### Environment

* **Tesseract Version**: 4.1.1-rc2
* **Commit Number**: 0c5995568f203009866864c38cf8d1bb11398ca2
* **Platform**: Windows x86_64

I'm trying to build tesseract 4.1.1-rc2 from sources using MSVC 2017. Release build succeeds in an acceptable time, but Debug one takes ages and generates ~170 Mbytes of compiler warnings. It's due to `/Wall` in
https://github.com/tesseract-ocr/tesseract/blob/60b07d5dd85ebd279e43452c0eedee00bb8a3cc7/CMakeLists.txt#L141

To fix this either tesseract sources should be cleaned up to get rid of compiler warnings or `/Wall` should be removed from `CMakeLists.txt` (of course, the latter solution is slightly simpler than the former one :-) )

**Comment by stweil** [comment]
See issue #1036.

**Comment by db4** [comment]
I'm not sure it's a duplicate of #1036. The current behavior was introduced 01-Nov-2019 14:30:15 in 5e3772cad82eaca8174c8ddb25f925a006af470e and is specific to MSVC (while old #1036 mostly addresses gcc/clang). And it should be fixed before 4.1.1 release (in my case it's a real show-stopper: travis CI build job cannot complete in 1 hour)

**Comment by stweil** [comment]
Let's discuss it nevertheless at #1036.
