### ISSUE TITLE
Windows: SIMD code not speeding tesseract?

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#2817]
From #2064

@stweil commented on Nov 19, 2018

>On Windows @noahmetzger recently reported that not using SSE or AVX is faster than using AVX.

@amitdo commented on Sep 5

>Is there a separate issue for this?

@stweil commented on Sep 5

>I am not sure whether this is still true and will ask @noahmetzger on Monday or test it myself.

**Comment by stweil** [comment]
There is a simple explanation: a good compiler with the right compiler options will use SIMD code for the simple C++ code which implements the dot product. And that optimized code can be better than the hand-made SIMD implementation which is used normally in Tesseract.

We already discussed that in another issue. That discussion was focused on Power8 with Altivec, but gcc can also produce really good SIMD code for normal C++ code. That's one to-do on my list of open tasks.

**Comment by amitdo** [comment]
I assume your are talking about auto-vectoring.
