### ISSUE TITLE
Is there an example file to run tesseract console by c# from win10

### ISSUE THREAD

**Issue by whatohyou** [tesseract-ocr/tesseract#2819]
I want to use tesseract 4.1.0 windows 10 binary version in c# forms application.

Can I get the ocr result directly by string variable?(not the text file)

Is there an example for it?

or maybe is there a better way to use it for ocr in c#?
Is there a method to import tesseract 4.1.0 to c#?

**Comment by stweil** [comment]
Please use the user forum for questions.
