### ISSUE TITLE
Need help in train tesseract with images of application

### ISSUE THREAD

**Issue by pp1609** [tesseract-ocr/tesseract#2827]
Hi,

We are using tesseract to perform actions and verifications for our application.  But we are facing issues for some of the characters. As i have never tried training if any one can help with this. 
1. Any link for how to train with application image. 
2. how to prepare training data.
3. How to do the training in windows if possible.

Thanks
Preeti

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support
