### ISSUE TITLE
Issue building 4.1

### ISSUE THREAD

**Issue by devolution2409** [tesseract-ocr/tesseract#2828]
### Environment

* **Tesseract Version**:  4.1
* **Commit Number**: master from 4.1 branch
* **Platform**: Linux a7a2487ae674 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior: Can't build Tesseract. Error happening
/usr/bin/ld: /usr/local/lib/libleptonica.a(binreduce.c.o): relocation R_X86_64_PC32 against symbol `LeptMsgSeverity' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
### Expected Behavior:
Linker able to link.
### Suggested Fix:
Maybe something to do with configure script?
### Build info:
I ran autogen.sh and then configure.

Make stderr and stdout: https://transfer.sh/v5QJn/make.log
configure stderr and stdout: https://transfer.sh/tvotI/configure_output.log

**Comment by stweil** [comment]
Why don't you use the Leptonica library which is provided by Ubuntu? This is not a Tesseract problem, but a problem of your local settings, so I close this issue.

Please use the user forum for additional questions.
