### ISSUE TITLE
accerlation of GPU

### ISSUE THREAD

**Issue by RichardHwang163** [tesseract-ocr/tesseract#2829]
------------------------

### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**: 
* **Platform**: Unix 18.04

**Comment by stweil** [comment]
Obviously we can't. This is Open Source, so feel free to provide the necessary code.

**Comment by satishsojitra** [comment]
@RichardHwang163 It would be great if you can share some details about changes in GPU version of tesseract you made to able to work it with GPU.
