### ISSUE TITLE
Compiling in linux with OpenCL and leptonica

### ISSUE THREAD

**Issue by dthrock** [tesseract-ocr/tesseract#283]
The goal is to run an AWS Amazon instance (Ubuntu 14.04) with GPU support to test the difference in OCR speed with a large GPU.   I have Nvidia drivers and OpenCL installed.
  Ive downloaded, compiled and installed leptonica 1.73 (latest version), downloaded the latest tesseract source.  I run autogen then ./configure --enable-opencl but get the following error.

checking for leptonica... yes
checking for l_generateCIDataForPdf in -llept... no
configure: error: leptonica library with pdf support (>= 1.71) is missing

Ive searched for at least 4 hours for the answer to this but have had no luck.  Im not a programmer so am not that familiar with the use or locations of lib files.    This is probably just a variable problem but I cant find any reference to it.

**Comment by zdenop** [comment]
Message is IMO clear: there is no leptonica >= 1.71 in standard location. This is not tesseract problem.

**Comment by nguyendv** [comment]
Hello @dthrock ,

I've got exactly the same proble, on Ubuntu 14.04.

I had to go to leptonica site, download the source and build it.

After that, I run ./configure --with-extra-includes=/usr/local/include and --with-extra-libaries=/usr/local/lib

Hope it would help you.

**Comment by vitamin** [comment]
I have the same problem, while leptonica-1.74.1

localhost:tesseract-4.00.00alpha didi$ brew install leptonica
Updating Homebrew...
Warning: leptonica-1.74.1 already installed

**Comment by jackey** [comment]
@vitamin thank u. your suggestion solved my issue too .

**Comment by ic** [comment]
@vitamin's suggestion works for MacPorts users too. For example if you are using the default installation:

    CPPFLAGS="-I/opt/local/include" LDFLAGS="-L/opt/local/lib" ./configure
