### ISSUE TITLE
Issue building for arm-apple-darwin64

### ISSUE THREAD

**Issue by ryanduffyegov** [tesseract-ocr/tesseract#2830]
### Environment

* **Tesseract Version**: 4.1 and Greater (below output is for commit #79f191f)
* **Platform**: Mac 10.14.06

### Current Behavior:

Building crashes when trying to build for arm-apple-darwin64

### Expected Behavior:

According to building instructions I should be able to build for apple arm64.  When I try to build from the master, I get the following error messages.  It builds just fine for x86_64-apple-darwin.

```
libtool: compile:  g++ --target=arm-apple-darwin64 -DHAVE_CONFIG_H -I. -O2 -DNDEBUG -I./include -I./include -I./src/arch -I./src/ccmain -I./src/ccstruct -I./src/ccutil -I./src/classify -I./src/cutil -I./src/dict -I./src/lstm -I./src/opencl -I./src/textord -I./src/training -I./src/viewer -I./src/wordrec -I/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/include -L/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/lib -Qunused-arguments -arch arm64 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=10.0 -O2 -fembed-bitcode -I/Users/ryand/Documents/TowerDefault/BuildTesseract/tesseract/arm-apple-darwin64/ -I/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/include -L/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/lib -Qunused-arguments -arch arm64 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=10.0 -O2 -fembed-bitcode -I/Users/ryand/Documents/TowerDefault/BuildTesseract/archs/leptonica/arm-apple-darwin64/include/leptonica -I/Users/ryand/Documents/TowerDefault/BuildTesseract/tesseract -I/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/include -L/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/lib -Qunused-arguments -arch arm64 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=10.0 -O2 -fembed-bitcode -Wno-deprecated-register -std=c++17 -MT src/arch/libtesseract_la-simddetect.lo -MD -MP -MF src/arch/.deps/libtesseract_la-simddetect.Tpo -c src/arch/simddetect.cpp -o src/arch/libtesseract_la-simddetect.o
In file included from src/arch/simddetect.cpp:32:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/cpuid.h:25:2: error: this header
      is for x86 only
#error this header is for x86 only
 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/cpuid.h:281:5: error: invalid
      output constraint '=a' in asm
    __cpuid(__leaf, __eax, __ebx, __ecx, __edx);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/cpuid.h:246:11: note: expanded
      from macro '__cpuid'
        : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/cpuid.h:296:5: error: invalid
      output constraint '=a' in asm
    __cpuid(__leaf, *__eax, *__ebx, *__ecx, *__edx);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/cpuid.h:246:11: note: expanded
      from macro '__cpuid'
        : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/cpuid.h:310:5: error: invalid
      output constraint '=a' in asm
    __cpuid_count(__leaf, __subleaf, *__eax, *__ebx, *__ecx, *__edx);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/cpuid.h:253:11: note: expanded
      from macro '__cpuid_count'
        : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
          ^
src/arch/simddetect.cpp:111:7: error: invalid output constraint '=a' in asm
      __cpuid_count(7, 0, eax, ebx, ecx, edx);
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/cpuid.h:253:11: note: expanded
      from macro '__cpuid_count'
        : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
          ^
5 errors generated.
```

**Comment by stweil** [comment]
> According to building instructions I should be able to build for apple arm64.

Which build instructions did you use?

**Comment by ryanduffyegov** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/Compiling#macos At the bottom of that section, it says I can build by adding the ./configure CXX="g++ --target=arm-apple-darwin64" CC="gcc --target=arm-apple-darwin64" when creating the make files, but that doesn't seem to work.

**Comment by ryanduffyegov** [comment]
Some additional information found while debugging.
If I try to build v4.1 I get this error message:
`
libtool: link: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib .libs/libtesseract_native.a
libtool: link: ( cd ".libs" && rm -f "libtesseract_native.la" && ln -s "../libtesseract_native.la" "libtesseract_native.la" )
libtool: compile:  g++ --target=arm-apple-darwin64 -DHAVE_CONFIG_H -I. -I../.. -O2 -DNDEBUG -I../../src/ccstruct -I../../src/ccutil -I../../src/viewer -I/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/include -L/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/lib -Qunused-arguments -arch arm64 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=10.0 -O2 -fembed-bitcode -I/Users/ryand/Documents/TowerDefault/BuildTesseract/tesseract/arm-apple-darwin64/ -I/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/include -L/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/lib -Qunused-arguments -arch arm64 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=10.0 -O2 -fembed-bitcode -I/Users/ryand/Documents/TowerDefault/BuildTesseract/archs/leptonica/arm-apple-darwin64/include/leptonica -I/opt/local/include -I/opt/local/include -mavx -I/Users/ryand/Documents/TowerDefault/BuildTesseract/tesseract -I/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/include -L/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/lib -Qunused-arguments -arch arm64 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=10.0 -O2 -fembed-bitcode -Wno-deprecated-register -std=c++17 -MT libtesseract_avx_la-dotproductavx.lo -MD -MP -MF .deps/libtesseract_avx_la-dotproductavx.Tpo -c dotproductavx.cpp -o libtesseract_avx_la-dotproductavx.o
dotproductavx.cpp:19:2: error: Implementation only for AVX capable architectures
#error Implementation only for AVX capable architectures
 ^
In file included from dotproductavx.cpp:22:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/immintrin.h:28:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/mmintrin.h:47:5: error: use of
      undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/mmintrin.h:47:5: note: 
      '__builtin_isless' declared here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/mmintrin.h:47:25: error: too few
      arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/mmintrin.h:64:19: error: use of
      undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
...
`

This seems to come from the same part of the simddetect.cpp.  If I change this part of the code in master, I will get the same output of 4.1:

```
#if defined(HAS_CPUID)
#if defined(__GNUC__)
# include <cpuid.h>
#elif defined(_WIN32)
# include <intrin.h>
#endif
#endif
```

**Comment by stweil** [comment]
I tried to reproduce this problem, but on my Mac configure already fails:

    % ./configure CXX="g++ --target=arm-apple-darwin64"              
    checking whether the C++ compiler works... no
    configure: error: in `/Users/stweil/src/github/tesseract-ocr/tesseract':
    configure: error: C++ compiler cannot create executables
    See `config.log' for more details

Do you use a special g++? Which one (output from `g++ --version`)?

**Comment by ryanduffyegov** [comment]
**Without the target:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**With the Target** (g++ --target=arm-apple-darwin64 --version)
```
Apple clang version 11.0.0 (clang-1100.0.33.16)
Target: arm-apple-darwin64
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by stweil** [comment]
Strange. That's exactly the same version which I see. Why does it fail for me and work for you?

I tried to compile a small hello.cpp using `g++ --target=arm-apple-darwin64 -v hello.cpp`. It compiles, but fails when linking:

     "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -no_deduplicate -dynamic -arch armv4t -macosx_version_min 10.15.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -o a.out /var/folders/hq/0_wbl7dx5jx_17p0zwzv4wfr0000gr/T/conftest-520036.o -L/usr/local/lib -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.osx.a
    ld: unknown/unsupported architecture name for: -arch armv4t
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do I have to install or enable ARM support for linking?

**Comment by ryanduffyegov** [comment]
It could be the  -arch armv4t, I am using -arch arm64.

**Comment by stweil** [comment]
What must I do to get `-arch arm64`, too, without specifying it explicitly?

**Comment by ryanduffyegov** [comment]
I am passing it in with the CFLAGS.
```
export CFLAGS="-I$DEPENDENT_LIBRARY_INCLUDES -L$DEPENDENT_LIBRARY_LIBS -Qunused-arguments -arch $ARM64_SHORT -pipe -no-cpp-precomp -isysroot $IPHONE_DEVELOPMENT_SDK -miphoneos-version-min="$MIN_PHONE_VERSION" -O2 -fembed-bitcode";
```

**Comment by stweil** [comment]
Ah. So you should mention that in your issue report. I also need all macros used in that statement (`DEPENDENT_LIBRARY_INCLUDES`, ...).

**Comment by ryanduffyegov** [comment]
**Setup**
```
export CFLAGS="-I/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/include -L/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/lib -Qunused-arguments -arch arm64 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=10.0 -O2 -fembed-bitcode"
export CPPFLAGS="-I/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/include -L/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/lib -Qunused-arguments -arch arm64 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=10.0 -O2 -fembed-bitcode"
export CXXFLAGS="-I/Users/ryand/Documents/TowerDefault/BuildTesseract/tesseract -I/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/include -L/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/lib -Qunused-arguments -arch arm64 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=10.0 -O2 -fembed-bitcode -Wno-deprecated-register"
export LDFLAGS="-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/lib/ -L/Users/ryand/Documents/TowerDefault/BuildTesseract/archs/leptonica/arm-apple-darwin64/lib"
export LEPTONICA_CFLAGS="-I/Users/ryand/Documents/TowerDefault/BuildTesseract/tesseract/arm-apple-darwin64/ -I/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/include -L/Users/ryand/Documents/TowerDefault/BuildTesseract/libraries/lib -Qunused-arguments -arch arm64 -pipe -no-cpp-precomp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -miphoneos-version-min=10.0 -O2 -fembed-bitcode -I/Users/ryand/Documents/TowerDefault/BuildTesseract/archs/leptonica/arm-apple-darwin64/include/leptonica"
export LIBLEPT_HEADERSDIR="/Users/ryand/Documents/TowerDefault/BuildTesseract/archs/leptonica/arm-apple-darwin64/include/leptonica"
export LIBS="-lz -lpng -ljpeg -ltiff"
export LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld"
export CC="/Applications/Xcode.app/Contents/Developer/usr/bin/gcc --target=arm-apple-darwin64"
export CXX="/Applications/Xcode.app/Contents/Developer/usr/bin/g++ --target=arm-apple-darwin64"
export SDKROOT="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk"
export LEPTONICA_LIBS="-llept"
export AR="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar"
export RANLIB="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib"
```
**Then I run:**
```
./autogen.sh;
./configure CXX="g++ --target=arm-apple-darwin64" CC="gcc --target=arm-apple-darwin64" --host=arm-apple-darwin64 --enable-shared=no --disable-graphics;
```

**Comment by stweil** [comment]
Using `-Qunused-arguments` breaks the checks in `configure`. Remove that from your settings.

Setting `CC` is not needed for Tesseract.

**Comment by ryanduffyegov** [comment]
When I take it out I get:
```
checking whether the g++ --target=arm-apple-darwin64 linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin64 dyld
checking how to hardcode library paths into programs... immediate
checking whether C++ compiler accepts -std=c++11... no
checking whether C++ compiler accepts -std=c++14... no
checking whether C++ compiler accepts -std=c++17... no
configure: error: Your compiler does not have the necessary C++11 support! Cannot proceed.
```

**Comment by stweil** [comment]
That is caused by more wrong settings (probably in `CPPFLAGS` or `CXXFLAGS`) which must be removed. Look into `config.log` to find those settings.

**Comment by ryanduffyegov** [comment]
Thank you for your help.  I finally got back to working on this and got it to compile.
