### ISSUE TITLE
Inconsistency in APIExample wiki page

### ISSUE THREAD

**Issue by NilsIrl** [tesseract-ocr/tesseract#2832]
### Current Behavior:

The the wiki page [APIExample](https://github.com/tesseract-ocr/tesseract/wiki/APIExample), for the python example, the handle api is is run through the `TessBaseAPIDelete` funciton if the api failed to be initialized whereas for the C example below, this is not the case.

python:

```python
rc = tesseract.TessBaseAPIInit3(api, TESSDATA_PREFIX, lang)
if (rc):
    tesseract.TessBaseAPIDelete(api)
    print("Could not initialize tesseract.\n")
    exit(3)
```

```c
if(TessBaseAPIInit3(handle, NULL, "eng") != 0)
    die("Error initializing tesseract\n");
```

### Expected Behavior:

Either the python example doesn't destroy the api handle or the api handle is destroyed in the c example.

### Suggested Fix:

Chose one the behaviour. I do not know tesseract enough to be able to tell which one to choose though I feel like the correct one would be to add `TessBaseAPIDelete` to the C example as it seems to be an omission. Also I was unable to find the documentation of the function `TessBaseAPIDelete` so I cannot give more information.

**Comment by lililala6868** [comment]
[福彩3D](https://1680380.com/view/fc3D/index.html)

**Comment by Olaoluw003** [comment]
I don't understand

**Comment by NilsIrl** [comment]
Moved to https://github.com/tesseract-ocr/tessdoc/issues/14
