### ISSUE TITLE
It can't figure the big white text

### ISSUE THREAD

**Issue by c0debreaker** [tesseract-ocr/tesseract#2833]
This is the image I'm trying but I can't get it to work. It has big texts. I'm really only interested in the lower left corner, the LAT and LON

<img width="1134" alt="frame2" src="https://user-images.githubusercontent.com/3783931/71449464-b0f59300-2712-11ea-94b7-67473b7a8d18.png">

The output I'm getting is below. The command I executed was `tesseract frame2.png out3 --oem 3`
```
'
~~
_ -
72 a rm ~ -

he mes ot + a
tie ae ee a % ‘
yi

ar

Lea ieee eae

te PEEL Ty ys
rt:1- 3 “catt §,"¢
```

**Comment by zdenop** [comment]
Please read the docs before posting issue. E.g. https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

**Comment by c0debreaker** [comment]
Thanks.

**Comment by c0debreaker** [comment]
It 95% improved after I converted it to black and white and changed levels.

Output is now
```
Ye. 1633808
-88 .39335793
```

![frame2origbw](https://user-images.githubusercontent.com/3783931/71449711-60813400-2718-11ea-90ff-31084ec98f4e.png)

Any thoughts on how to fix the remaining issue?

**Comment by balmma** [comment]
You can try to scale down your image so that the height of a number is about 20 px height.

**Comment by balmma** [comment]
And using LSTM you might also want to invert you image.
