### ISSUE TITLE
Not able to extract text from a high resolution image. 

### ISSUE THREAD

**Issue by Purva96** [tesseract-ocr/tesseract#2834]
* **Tesseract Version** :  4.00.00alpha
* **Platform**:  Windows 10 64 bit

### Current Behavior: I am getting the following error while reading a high resolution image(.png file) and saving the text in a text file.

**ERROR:**
Traceback (most recent call last):
  File "textOfCompImage.py", line 8, in <module>
    text=pt.image_to_string(Image.open(filename),config=tessdata_dir_config)
  File "C:\Users\H373302\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 345, in image_to_string
    }[output_type]()
  File "C:\Users\H373302\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 344, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\H373302\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 253, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\H373302\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 229, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica Error in pixCreateNoInit: pix_malloc fail for data Error in pixCreate: pixd not made Error in pixReadStreamPng: pix not made Error in pixReadStream: png: no pix returned Error in pixRead: pix not read Error during processing. ObjectCache(656B5A88)::~ObjectCache(): WARNING! LEAK! object 0218EF98 still has count 1 (id C:\\Program Files\\Tesseract-OCR\\tessdata/eng.traineddatalstm-punc-dawg) ObjectCache(656B5A88)::~ObjectCache(): WARNING! LEAK! object 02140C68 still has count 1 (id C:\\Program Files\\Tesseract-OCR\\tessdata/eng.traineddatalstm-word-dawg) ObjectCache(656B5A88)::~ObjectCache(): WARNING! LEAK! object 02140D68 still has count 1 (id C:\\Program Files\\Tesseract-OCR\\tessdata/eng.traineddatalstm-number-dawg) ObjectCache(656B5A88)::~ObjectCache(): WARNING! LEAK! object 03235600 still has count 1 (id C:\\Program Files\\Tesseract-OCR\\tessdata/eng.traineddatapunc-dawg) ObjectCache(656B5A88)::~ObjectCache(): WARNING! LEAK! object 032355A8 still has count 1 (id C:\\Program Files\\Tesseract-OCR\\tessdata/eng.traineddataword-dawg) ObjectCache(656B5A88)::~ObjectCache(): WARNING! LEAK! object 0218C760 still has count 1 (id C:\\Program Files\\Tesseract-OCR\\tessdata/eng.traineddatanumber-dawg) ObjectCache(656B5A88)::~ObjectCache(): WARNING! LEAK! object 03235808 still has count 1 (id C:\\Program Files\\Tesseract-OCR\\tessdata/eng.traineddatabigram-dawg) ObjectCache(656B5A88)::~ObjectCache(): WARNING! LEAK! object 032358B0 still has count 1 (id C:\\Program Files\\Tesseract-OCR\\tessdata/eng.traineddatafreq-dawg)')

### Expected Behavior: 
It should have read the text correctly.
I am not understanding how to solve this error. Can anyone suggest how to solve this error?

**Comment by zafalija** [comment]
Could you share your image?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. You have to reproduce you problem with resent version of tesseract executable.
