### ISSUE TITLE
recognition of an image

### ISSUE THREAD

**Issue by barron9** [tesseract-ocr/tesseract#2836]
![354_cropedoutput](https://user-images.githubusercontent.com/27488285/71575976-ef959f80-2abc-11ea-9499-ff572513a2d3.png)
[out.txt](https://github.com/tesseract-ocr/tesseract/files/4009386/out.txt)

 I am trying to get the text bur its not possible

tesseract 354_cropedoutput.png  out -l tur --psm 1 --oem

**Comment by stweil** [comment]
Please use the user forum for questions.

**Comment by barron9** [comment]
where is that?

**Comment by stweil** [comment]
See https://github.com/tesseract-ocr/tesseract/wiki#support.
