### ISSUE TITLE
kMaxImageWidth = 2560，but xsize is 3600 (default)

### ISSUE THREAD

**Issue by asysbang** [tesseract-ocr/tesseract#2837]
./lstm/lstmrecognizer.cpp:269: 
          const int kMaxImageWidth = 2560

tesstrain_utils.sh  
          X_SIZE=3600

so , i think should set X_SIZE=2560 by default in tesstrain_utils.sh

**Comment by amitdo** [comment]
See #590

**Comment by asysbang** [comment]
i still think the default value of X_SIZE should be 2560  but not 3600 
because for most of people who use training will use the default value
it is just ok for any default value
