### ISSUE TITLE
Tesseract 4.x and 5.x ignores indentation with "preserve_interword_spaces=1"

### ISSUE THREAD

**Issue by AlessandroCorradini** [tesseract-ocr/tesseract#2843]
I have a blood examination image, it has a table with indentation. Although tesseract recognizes the characters perfectly, its structure isn't preserved in the final output. After reading a lot, I found the option `preserve_interword_spaces=1`. The result became slightly better but it isn't perfect.

Are there a sort of bug/issue related to the `preserve_interword_spaces=1` flag, which does not make it work properly?

```
from PIL import Image
import pytesseract

# Preserve interword spaces is set to 1, oem = 1 is LSTM, 
# PSM = 1 is Automatic page segmentation with OSD - Orientation and script detection

custom_config = r'-c preserve_interword_spaces=1 --oem 1 --psm 1 -l eng+ita'

# default_config = r'-c -l eng+ita'

extracted_text = pytesseract.image_to_string(Image.open('referto-1.jpg'), config=custom_config)

print(extracted_text)

# saving to a txt file

with open("referto.txt", "w") as text_file:
    text_file.write(extracted_text)`
```

![Blood examination image](https://i.stack.imgur.com/gSvYj.jpg)

[StackOverflow Discussion](https://stackoverflow.com/questions/59582008/preserving-original-text-indentation-structure-with-tesseract-ocr-4-x)
[Github](https://github.com/AlessandroCorradini/Blood-Examination-Text-Extraction-from-Image) repository if you want to try it yourself.

Thanks for your help and your time

* **Tesseract Version**: I've tested 4.0, 4.1 and 5.0 in conjunction with pytesseract
* **Platform**: Windows 10 PRO 64bit with ALL updates installed

**Comment by zdenop** [comment]
This is not bug, but not meeting your expectation.
Tesseract is OCR engine and it does not focused on layout reconstruction. 
Its biggest aspiration to reproduce text location is in hocr and pdf where format definition allows to place to certain position. This is not true with txt.
If you need to persevere original layout you have to post-process tesseract output (hocr) or create you own renderer (via tesseract API)

**Comment by apatel29** [comment]
> This is not bug, but not meeting your expectation.
> Tesseract is OCR engine and it does not focused on layout reconstruction.
> Its biggest aspiration to reproduce text location is in hocr and pdf where format definition allows to place to certain position. This is not true with txt.
> If you need to persevere original layout you have to post-process tesseract output (hocr) or create you own renderer (via tesseract API)

Can you please provide some more details on how to approach this requirement of retaining the layout by  post-process tesseract output (hocr) or create you own renderer (via tesseract API)

**Comment by msmith17** [comment]
I understand this is closed.  But I fail to see the utility of preserving interword spacing and at the same time eliminating the initial space from the beginning of the line and the first text.  I guess Tesseract just likes left adjusted text.  I went through the pain of implementing an hocr solution but it would have been much simpler if 'preserve space' mean preserve space.
