### ISSUE TITLE
Seg Fault

### ISSUE THREAD

**Issue by dthrock** [tesseract-ocr/tesseract#285]
tesseract -v
tesseract 3.05.00dev
 leptonica-1.73
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8

 OpenCL info:
  Found 1 platforms.
  Platform name: NVIDIA CUDA.
  Version: OpenCL 1.1 CUDA 7.0.28.
  Found 1 devices.
    Device 1 name: GRID K520.
root@ip-172-31-35-3:~# tesseract 1.tiff output
[DS] Profile file not available (tesseract_opencl_profile_devices.dat); performing profiling.

[DS] Device: "GRID K520" (OpenCL) evaluation...
[OD] write binary[kernel-GRID_K520.bin] successfully
[DS] Device: "GRID K520" (OpenCL) evaluated
[DS]          composeRGBPixel: 0.021918 (w=1.2)
[DS]            HistogramRect: 0.008381 (w=2.4)
[DS]       ThresholdRectToPix: 0.010258 (w=4.5)
[DS]        getLineMasksMorph: 0.005291 (w=5.0)
[DS]                    Score: 0.119031

[DS] Device: "(null)" (Native) evaluation...
[DS] Device: "(null)" (Native) evaluated
[DS]          composeRGBPixel: 0.021650 (w=1.2)
[DS]            HistogramRect: 0.072183 (w=2.4)
[DS]       ThresholdRectToPix: 0.041287 (w=4.5)
[DS]        getLineMasksMorph: 0.151936 (w=5.0)
[DS]                    Score: 1.144687
[DS] Scores written to file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 1:GRID K520 score is 0.119031
[DS] Device[2] 0:(null) score is 1.144687
[DS] Selected Device[1]: "GRID K520" (OpenCL)
fseek(data_file_, static_cast<size_t>(offset_table_[tessdata_type]), SEEK_SET) == 0:Error:Assert failed:in file ../ccutil/tessdatamanager.h, line 173
Segmentation fault (core dumped)

**Comment by zdenop** [comment]
Please google and read [forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/JZ9G3D5HHNM/A--DXmm2BgAJ) before writing issue

**Comment by ericovva** [comment]
wtf, what a shit answer, where is a link!?
