### ISSUE TITLE
tesseract ocr no valid output result from plate number

### ISSUE THREAD

**Issue by cecepnrhya** [tesseract-ocr/tesseract#2850]
### Environment

* **Tesseract Version**: 0.4.1
* **Commit Number**: 
* **Platform**: Raspberry pi4

how to valid result tesseract ocr from plate number, i 'd use theresholding and gray but result no valid ?

![2020-01-07-044124_1366x768_scrot](https://user-images.githubusercontent.com/46098300/71968832-32cbdd00-3238-11ea-85c0-77aa8d5104a6.png)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Make sure you read docs (wiki) first and search forum for similar topics.
