### ISSUE TITLE
Autoconf Failure for 4.1.1-rc1

### ISSUE THREAD

**Issue by M3ssman** [tesseract-ocr/tesseract#2851]
-------
### Use Case

To estimate Impact of different Versions on OCR-QA, use different Tesseract-4.x-Versions to compare ALTO-output. Checkout provided Releases or checkout different Release-Tags from Repo

### Environment

* **Tesseract Version**: https://github.com/tesseract-ocr/tesseract/archive/4.1.1-rc1.zip
* **Platform**: Linux tuxedo 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:

```
./autoconf.sh

Running aclocal
Running /usr/bin/libtoolize
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
Running autoconf
Running autoheader
Running automake --add-missing --copy
configure.ac:349: installing 'config/compile'
configure.ac:86: installing 'config/config.guess'
configure.ac:86: installing 'config/config.sub'
configure.ac:27: installing 'config/install-sh'
configure.ac:27: installing 'config/missing'
src/api/Makefile.am: installing 'config/depcomp'
unittest/Makefile.am:117: error: endif without if
parallel-tests: installing 'config/test-driver'

  Something went wrong, bailing out!

```

### Expected Behavior:
Run `autoconf` with success.

### Suggested Fix:
Do `unittest/Makefile.am`like in Release 4.1.1-rc2.

**Comment by zdenop** [comment]
this is old version. use the latest when you try to report issue.

**Comment by stweil** [comment]
@M3ssman, I suggest to use `git bisect` in the 4.1 branch to find the commits which introduced different results. Then commits which fail to build can simply be skipped.

**Comment by stweil** [comment]
There were not many code changes in the last year which changed the OCR results. If you noticed a deterioration, publishing the image, command line and old / new results would help.
