### ISSUE TITLE
Tesseract limitations

### ISSUE THREAD

**Issue by Mooeeezzzz** [tesseract-ocr/tesseract#2852]
### Environment

* **Tesseract Version**: 4.1.0
* **Platform**: linux 
* **Cmd**: tesseract input outputDir -l eng  -c hocr_char_boxes=1 hocr
### Current Behavior:
  Tesseract is unable to detect multiple angle rotated text . bedsides that hocr output has wrong x_bboxes on characters level for example check out word_1_2 in hocr output
![Untitled drawing (16)](https://user-images.githubusercontent.com/48438016/72146756-67a57480-339d-11ea-8260-9543b3ea6393.png)

[hocr-output.txt](https://github.com/tesseract-ocr/tesseract/files/4045180/output.txt)

### Expected Behavior:
   i don't know if this is a limitation or could be fixed by some config

**Comment by zdenop** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

**Comment by Mooeeezzzz** [comment]
@zdenop  i read improve quality nothing mention why boudingbox are incorrect ?
