### ISSUE TITLE
tesseract is not working with window 10.

### ISSUE THREAD

**Issue by shamsher786** [tesseract-ocr/tesseract#2856]
Code :
import textract
filename = 'pythonInterviewExperienced.pdf'
#filename = "D:/myproject/PythonQAChatBot/pythonTop41.pdf"
text = textract.process(filename, method='tesseract',language='eng')

Error :
ShellError: The command tesseract C:\Users\sa_kh\AppData\Local\Temp\tmpvijibwz2\conv-000001.ppm stdout -l eng failed with exit code 3
------------- stdout -------------
b''------------- stderr -------------
b"Warning. Invalid resolution 0 dpi. Using 70 instead.\r\nDotProductAVX can't be used on Android\r\nDotProductAVX can't be used on Android\r\nDotProductAVX can't be used on Android\r\nDotProductAVX can't be used on Android\r\nObjectCache(64BD0A88)::~ObjectCache(): WARNING! LEAK! object 028BF670 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatalstm-punc-dawg)\r\nObjectCache(64BD0A88)::~ObjectCache(): WARNING! LEAK! object 03718790 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatalstm-word-dawg)\r\nObjectCache(64BD0A88)::~ObjectCache(): WARNING! LEAK! object 03718830 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatalstm-number-dawg)\r\nObjectCache(64BD0A88)::~ObjectCache(): WARNING! LEAK! object 030C6040 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatapunc-dawg)\r\nObjectCache(64BD0A88)::~ObjectCache(): WARNING! LEAK! object 028BF590 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddataword-dawg)\r\nObjectCache(64BD0A88)::~ObjectCache(): WARNING! LEAK! object 037EEC00 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatanumber-dawg)\r\nObjectCache(64BD0A88)::~ObjectCache(): WARNING! LEAK! object 030C9AF0 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatabigram-dawg)\r\nObjectCache(64BD0A88)::~ObjectCache(): WARNING! LEAK! object 030C9B98 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatafreq-dawg)\r\n"

I have installed tesseract version: tesseract-ocr-setup-4.0.0dev-20170130.exe
https://www.xpdfreader.com/download.html and Xpdfreader as well.

![Screenshot_3](https://user-images.githubusercontent.com/20358682/72424985-e8ed7480-37ac-11ea-95e8-ac7e82d2e3c0.png)
![Screenshot_4](https://user-images.githubusercontent.com/20358682/72424986-e8ed7480-37ac-11ea-848c-36b3a365cbad.png)

**Comment by zdenop** [comment]
duplicate #2855
