### ISSUE TITLE
tesseract.exe not flushing stdout 

### ISSUE THREAD

**Issue by jkang-eng** [tesseract-ocr/tesseract#2859]
### Environment
* **Tesseract Version**: latest master
* **Platform**: Windows 32/64 bit

### Current Behavior:
In my application, I spawn tesseract.exe from java and continuously send request (path to image) / receive response  (tokens) through standard pipe-stdio.
For example, tesseract is launched with following args.
```
tesseract.exe stdin stdout -c stream_filelist=true
```

Problem with the existing code, **tokens are never flushed from  tesseract.exe** when OCR is finished for the image (token is fully-buffered).  In other words, tokens will not be flushed until tesseract.exe is killed, because they are only buffered.

Based on research, this is due to the way buffering behaves differently for following streams:
![buffering](https://user-images.githubusercontent.com/55756666/72619873-3af8dc00-390c-11ea-8e22-d0f1fb21de69.png)
Since Java communicates with the child process over a pipe, it falls into the “stdout (not a TTY)” category.
More ref: https://eklitzke.org/stdout-buffering

I was able to resolve by adding flush command in source code. (see below)

### Expected Behavior:
tesseract.exe flushes tokens to stdout when finished OCR for the given image.

### Suggested Fix:
1.  Add ``fflush(fout_);`` at the end of ``TessResultRenderer::AppendData(const char* s, int len)`` (_src/api/renderer.cpp_)
2.  Add ``fflush(stderr);`` after line 1017 (_src/api/renderer.cpp_) - https://github.com/tesseract-ocr/tesseract/blob/master/src/api/baseapi.cpp#L1017

**Comment by stweil** [comment]
Do you want to send a pull request which adds the missing `fflush` in `TessResultRenderer::AppendData`?

Is flushing for `stderr` really needed? Do you have a practical example which fails without that?

**Comment by jkang-eng** [comment]
> Do you want to send a pull request which adds the missing `fflush` in `TessResultRenderer::AppendData`?
> 
> Is flushing for `stderr` really needed? Do you have a practical example which fails without that?

Sure, I can do that.

Regarding ``stderr``, I can't recall top of my head, but there was an issue with specific image if without flush command.  (I think it hanged..)

**Comment by jkang-eng** [comment]
> Do you want to send a pull request which adds the missing `fflush` in `TessResultRenderer::AppendData`?

Hi @stweil,
I'm trying to push changes to remote branch, but getting following messages.
```
jkang@49S5NV2 MINGW64 /c/users/jkang/Desktop/temp/tesseract (issues_2859)
$ git push origin issues_2859
remote: Permission to tesseract-ocr/tesseract.git denied to jkang-eng.
fatal: unable to access 'https://github.com/tesseract-ocr/tesseract.git/': The requested URL returned error: 403
```
seems like permission level issue?

**Comment by stweil** [comment]
@jkang-eng, you cannot directly push to https://github.com/tesseract-ocr/tesseract.git.

For a pull request, you start with a fork of that repository on GitHub. So you should get https://github.com/jkang-eng/tesseract.git. Then clone that repository, change the files, commit your change and push it. This will work then because the push goes to your repository. After pushing, you can create the pull request.
