### ISSUE TITLE
Two bugs when building against Visual Studio C++.

### ISSUE THREAD

**Issue by jiapei100** [tesseract-ocr/tesseract#286]
Check my previous summary here http://www.visionopen.com/forums/topic/bugs-in-current-tesseract/
Solutions are provided as follows:

1) LIST -> LIST_TESSERACT
in all files

2) remove_reference -> remove_reference_Tesseract
in all files

How can I become a developer of tesseract on github?

Cheers
Pei

**Comment by amitdo** [comment]
HI,

You should give more details:
* Version of Visual Studio C++.
* Version of Tesseract.
* If this happens with your code, but not with 'tesseract.exe' command line tool, you should provide a sample code that invokes the bug. 
* Output of compiler errors.

**Comment by amitdo** [comment]
>How can I become a developer of tesseract on github?

You should learn how to use 'pull request' on github.
https://help.github.com/

**Comment by zdenop** [comment]
>How can I become a developer of tesseract on github?

You can start with creating correct issue report.
It is known that tesseact can be build with problem with VS2010, VS2013 and VS2015.

**Comment by amitdo** [comment]
http://stackoverflow.com/questions/23740431/tesseract-remove-reference-ambiguous-symbol-in-project-on-visual-studio-2012

**Comment by zdenop** [comment]
@amitdo: it confirms that it is not tesseract problem but bad practice of writing code using ["namespace std"](http://stackoverflow.com/questions/1452721/why-is-using-namespace-std-in-c-considered-bad-practice) which is real root of ambiguity.

**Comment by jiapei100** [comment]
Oh, yes zdenop.
You are correct. I met this problem 2 years ago. At that time, I used to use a "global namespace", something like 
**using namespace std;** instead of **std::**

It looks like tesseract is using the SAME key words as in C++ compiler.

Thank you...
