### ISSUE TITLE
Not working on fresh wordpress

### ISSUE THREAD

**Issue by alexlii1971** [tesseract-ocr/tesseract#2862]
Hello,

In Wordpress FAQ:

How do I know if / where I have Tesseract installed on my server?
Linux:

> SSH into your server and type which tesseract.
> If Tesseract is installed and in your shell environment PATH the terminal should return a path similar to /opt/local/bin/tesseract.
> Place this path in the configuration of the OCR plugin through the Settings > Tesseract link in the sidebar menu in WordPress

Return path not found, and here are the full info:

> The following NEW packages will be installed:
> libgif7 libicu60 liblept5 libopenjp2-7 libtesseract4 tesseract-ocr tesseract-ocr-eng
> tesseract-ocr-osd
> 0 upgraded, 8 newly installed, 0 to remove and 4 not upgraded.
> Need to get 15.1 MB of archives.
> After this operation, 53.9 MB of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Get:1 http://mirrors.digitalocean.com/ubuntu bionic/main amd64 libicu60 amd64 60.2-3ubuntu3 [8054 kB]
> Get:2 http://mirrors.digitalocean.com/ubuntu bionic-updates/main amd64 libgif7 amd64 5.1.4-2ubuntu0.1 [30.9 kB]
> Get:3 http://mirrors.digitalocean.com/ubuntu bionic-updates/universe amd64 libopenjp2-7 amd64 2.3.0-2build0.18.04.1 [145 kB]
> Get:4 http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 liblept5 amd64 1.75.3-3 [929 kB]
> Get:5 http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 libtesseract4 amd64 4.00~git2288-10f4998a-2 [1163 kB]
> Get:6 http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 tesseract-ocr-eng all 4.00~git24-0e00fe6-1.2 [1588 kB]
> Get:7 http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 tesseract-ocr-osd all 4.00~git24-0e00fe6-1.2 [2989 kB]
> Get:8 http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 tesseract-ocr amd64 4.00~git2288-10f4998a-2 [218 kB]
> Fetched 15.1 MB in 1s (25.2 MB/s)
> Selecting previously unselected package libicu60:amd64.
> (Reading database … 102903 files and directories currently installed.)
> Preparing to unpack …/0-libicu60_60.2-3ubuntu3_amd64.deb …
> Unpacking libicu60:amd64 (60.2-3ubuntu3) …
> Selecting previously unselected package libgif7:amd64.
> Preparing to unpack …/1-libgif7_5.1.4-2ubuntu0.1_amd64.deb …
> Unpacking libgif7:amd64 (5.1.4-2ubuntu0.1) …
> Selecting previously unselected package libopenjp2-7:amd64.
> Preparing to unpack …/2-libopenjp2-7_2.3.0-2build0.18.04.1_amd64.deb …
> Unpacking libopenjp2-7:amd64 (2.3.0-2build0.18.04.1) …
> Selecting previously unselected package liblept5.
> Preparing to unpack …/3-liblept5_1.75.3-3_amd64.deb …
> Unpacking liblept5 (1.75.3-3) …
> Selecting previously unselected package libtesseract4.
> Preparing to unpack …/4-libtesseract4_4.00~git2288-10f4998a-2_amd64.deb …
> Unpacking libtesseract4 (4.00~git2288-10f4998a-2) …
> Selecting previously unselected package tesseract-ocr-eng.
> Preparing to unpack …/5-tesseract-ocr-eng_4.00~git24-0e00fe6-1.2_all.deb …
> Unpacking tesseract-ocr-eng (4.00~git24-0e00fe6-1.2) …
> Selecting previously unselected package tesseract-ocr-osd.
> Preparing to unpack …/6-tesseract-ocr-osd_4.00~git24-0e00fe6-1.2_all.deb …
> Unpacking tesseract-ocr-osd (4.00~git24-0e00fe6-1.2) …
> Selecting previously unselected package tesseract-ocr.
> Preparing to unpack …/7-tesseract-ocr_4.00~git2288-10f4998a-2_amd64.deb …
> Unpacking tesseract-ocr (4.00~git2288-10f4998a-2) …
> Setting up libicu60:amd64 (60.2-3ubuntu3) …
> Setting up libopenjp2-7:amd64 (2.3.0-2build0.18.04.1) …
> Setting up libgif7:amd64 (5.1.4-2ubuntu0.1) …
> Setting up liblept5 (1.75.3-3) …
> Setting up tesseract-ocr-osd (4.00~git24-0e00fe6-1.2) …
> Setting up tesseract-ocr-eng (4.00~git24-0e00fe6-1.2) …
> Setting up libtesseract4 (4.00~git2288-10f4998a-2) …
> Setting up tesseract-ocr (4.00~git2288-10f4998a-2) …
> Processing triggers for man-db (2.8.3-2ubuntu0.1) …
> Processing triggers for libc-bin (2.27-3ubuntu1) …
> root@ubuntu-s-2vcpu-4gb-lon1-01:~#

and I found  the file of tesseract is at /usr/bin/tesseract, and English is installed: https://prnt.sc/qqo3r7

> Where is the detected text stored?
> The text detected by the OCR plugin is added as a new post, named after the image file.

Sorry, I did not find the text post, please check the screenshot:
http://prntscr.com/qqnx6f
http://prntscr.com/qqny2d

and I insert that image into a test post, but still not found any covert text content.
http://prntscr.com/qqny9z
http://prntscr.com/qqnyw3

What did I missed please?

Thanks

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. You have to reproduce you problem with resent version of tesseract executable.
