### ISSUE TITLE
Not working in wordpress

### ISSUE THREAD

**Issue by alexlii1971** [tesseract-ocr/tesseract#2863]
------------------------

### Environment

* **Tesseract Version**: 
root@ubuntu-s-2vcpu-4gb-lon1-01:~# tesseract --version
tesseract 4.0.0-beta.1
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found SSE
* **Commit Number**: 
* **Platform**: 
root@ubuntu-s-2vcpu-4gb-lon1-01:~# uname -a
Linux ubuntu-s-2vcpu-4gb-lon1-01 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
WP Tesseract is installed https://wordpress.org/plugins/wp-tesseract/#description
By the way, is it official plugin, right?

I test it on subsite of multisite, but I did not find any covert text post as FAQ:

> Where is the detected text stored?
> The text detected by the OCR plugin is added as a new post, named after the image file. 

### Expected Behavior:

Expect work in wordpress.

### Suggested Fix:

Fix it

Thanks

**Comment by stweil** [comment]
This is the wrong place for your report. See also issue #2862.
