### ISSUE TITLE
cmake fail to configure current tesseract GIT? 

### ISSUE THREAD

**Issue by jiapei100** [tesseract-ocr/tesseract#287]
>  CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
   A required package was not found
 Call Stack (most recent call first):
   /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
   CMakeLists.txt:51 (pkg_check_modules)

I installed my own leptonica from github... As such, NO pkgconfig comes along with leptonica installation. Is this the possible reason why "A required package was not round" ?

Cheers
Pei

**Comment by llhhbc** [comment]
Have you solve this problem?
