### ISSUE TITLE
Clear text not recognized in processed image.

### ISSUE THREAD

**Issue by HamsterSophie** [tesseract-ocr/tesseract#2870]
### Environment

* **Tesseract Version**: 4.0.0
* **Platform**: Linux x86_64

### Current Behavior:
Cannot recognize text "Log In" which is in the center of the image and very clearly displayed.
### Expected Behavior:
Recognize "Log In" and return
### Suggested Fix: NA

![fb-bw](https://user-images.githubusercontent.com/17467201/73029291-1b6e2180-3dec-11ea-9b20-de100885b82b.png)

Checked tesseract processed input image by set "tessedit_write_images true" in config file. The tesseractInput image has "Log In" clearly displayed in the center of the image.

**Comment by zdenop** [comment]
It is not clear text - it is image full of graphics => not suitable for OCR by tesseract.
Read https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality
