### ISSUE TITLE
arabic language not detect get some error like

### ISSUE THREAD

**Issue by kkkabariya** [tesseract-ocr/tesseract#2872]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 9.1.0
* **Commit Number**: 
* **Platform**: unix

### Current Behavior: when i uses ara.traineddata get error "cube data not found" after i can add are.cube.params after something like this 
"com.example.ocrr A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 15035 (om.example.ocrr), pid 15035 (om.example.ocrr)"

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. You have to reproduce you problem with resent version of tesseract executable.
