### ISSUE TITLE
Resolution dpi 0 not found

### ISSUE THREAD

**Issue by OmarJabri7** [tesseract-ocr/tesseract#2874]
### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**: 
* **Platform**: Windows 10 64 bit

### Current Behavior: Whenever I try to use pytesseract.image_to_osd, I sometimes get an error on images and sometimes not. The error is the following: "raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Tesseract Open Source OCR Engine v4.1.0-bibtag19 with Leptonica Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')". I have tested it with several images, some work some don't.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Make sure you provide all information to reproduce problem (description like above useless)
