### ISSUE TITLE
Can not build Tesseract with SW and Cmake.

### ISSUE THREAD

**Issue by LuckyLeeee** [tesseract-ocr/tesseract#2882]
### Environment

* **Tesseract Version**:  Tesseract 4.1.1 
* **Commit Number**: 
* **Platform**: Window 10 64bit

### Current Behavior:
I can not build Tesseract with SW and Cmake.
I had download SW client and save it at "D:\SW" then add to Path
This is my SW information
sw.client.sw version 1.0.0
git revision df126bc667375de822ef38bb4ba932f4c3801912
assembled on 10.02.2020 09:08:00 SE Asia Standard Time
I had download Leptonica-1.79.0 and Tesseract-4.1.1
Then I built Leptonica with SW and Cmake, generated and Build the solution in Visual Studio 2017, it's works well.
But when I build Tesseract, things don't go so well.
I got an error:
Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
Configuring tesseract version 4.1.1...
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at D:/TESSERACT/leptonica-1.79.0/build/LeptonicaTargets.cmake:1 (include):
  include could not find load file:

    D:/TESSERACT/leptonica-1.79.0/build/cppan.cmake
Call Stack (most recent call first):
  D:/TESSERACT/leptonica-1.79.0/build/LeptonicaConfig.cmake:23 (include)
  CMakeLists.txt:230 (find_package)

Could NOT find LibArchive (missing: LibArchive_LIBRARY LibArchive_INCLUDE_DIR) 

General configuration for Tesseract 4.1.1
--------------------------------------------------------
Build type: Release
Compiler: MSVC
Used standard: C++17
CXX compiler options: /DWIN32 /D_WINDOWS /W3 /GR /EHsc /utf-8 /MP /MD /O2 /Ob2 /DNDEBUG
Linker options: /machine:x64 
Install directory: C:/Program Files (x86)/tesseract
Architecture flags: /arch:AVX2
Vector unit list: sse2;sse3;ssse3;sse4.1;sse4.2;avx;fma;bmi2;avx2
AVX_OPT: ON
AVX2_OPT: ON
FMA_OPT: ON
SSE41_OPT: ON
MARCH_NATIVE_OPT: OFF
simd_flags:  -DSSE2 -DSSE3 -DSSSE3 -DSSE4_1 -DSSE4_2 -DAVX -DFMA -DBMI2 -DAVX2
--------------------------------------------------------
Build with cppan [CPPAN_BUILD]: OFF
Build with sw [SW_BUILD]: OFF
Build with openmp support [OPENMP_BUILD]: OFF
Disable disable graphics (ScrollView) [GRAPHICS_DISABLED]: OFF
Disable the legacy OCR engine [DISABLED_LEGACY_ENGINE]: OFF
Build training tools [BUILD_TRAINING_TOOLS]: OFF
Build tests [BUILD_TESTS]: OFF
--------------------------------------------------------

Configuring incomplete, errors occurred!
See also "D:/TESSERACT/tesseract-4.1.1/build/CMakeFiles/CMakeOutput.log".
See also "D:/TESSERACT/tesseract-4.1.1/build/CMakeFiles/CMakeError.log".

I turn off the CPPAN_BUILD (its default is ON) but I still got that problem and I don't know how to fix it. Last time, I build Leptonica-1.78.0 and Tesseract-4.1.0 it seems like there is no such file as cppan,cmake. This is the log file attached
[CMakeError.log](https://github.com/tesseract-ocr/tesseract/files/4185068/CMakeError.log)
[CMakeOutput.log](https://github.com/tesseract-ocr/tesseract/files/4185069/CMakeOutput.log)

### Expected Behavior:
Build tesseract-4.1.1 solution.

**Comment by Moldoteck** [comment]
Shouldnt Build with sw [SW_BUILD]: be on?

**Comment by Shreeshrii** [comment]
@egorpugin any suggestions?

**Comment by egorpugin** [comment]
Hi,

In general you should not build lept separately.
When you build tess, sw downloads and builds lept package.

If you need to use tess in your app, check out this simple example.
https://github.com/SoftwareNetwork/sw/blob/master/test/integrations/cmake/tess/CMakeLists.txt

---

If you still need to build tess with SW, you must pass `-DSW_BUILD=1` to cmake.
Try it, feel free to ask further.

**Comment by LuckyLeeee** [comment]
@egorpugin I tried it and its work well.  Many thank ^^

**Comment by matzefriedrich** [comment]
Having the same issue, but the setting -DSW_BUILD=1 does not fix it entirely. I am getting an error C3688: invalid literal suffix '_l'; literal operator or literal operator template 'operator ""_l' not found, that relates to sw.cpp

**Comment by egorpugin** [comment]
What is your compiler and version? Also try to update sw `sw --self-upgrade` before your actions.

**Comment by matzefriedrich** [comment]
> What is your compiler and version? Also try to update sw `sw --self-upgrade` before your actions.

I use Visual Studio 16.4 (2019), and CMake 3.15.3 (that is bundled with CLion). The build works for the master branch, but since version 5 is still alpha I am interested in building the 4.1 branch. That one fails (master builds without any issues).

**Comment by egorpugin** [comment]
I did not actually support 4.1.
Try to find that line and replace `_l` with `_lib`.
Or show me that place, I'll try to help.

**Comment by egorpugin** [comment]
I do not see _l in 4.1, only in 4.0.
Replace it with `_slib`.
