### ISSUE TITLE
consistent crash at block_edges function on Mac

### ISSUE THREAD

**Issue by sureshyerva87** [tesseract-ocr/tesseract#2887]
Hi, I am using tesseract 4.1.0 version release build on Mac OS 10.15.3. While using the build in application, I am getting consistent crash. The crash report is as follows:

0   libtesseract.4.1.0.dylib      	0x000000012abea3cd block_edges(Pix*, PDBLK*, C_OUTLINE_IT*) + 1165
1   libtesseract.4.1.0.dylib      	0x000000012abb87bd extract_edges(Pix*, BLOCK*) + 77
2   libtesseract.4.1.0.dylib      	0x000000012ac33b38 tesseract::Textord::find_components(Pix*, BLOCK_LIST*, TO_BLOCK_LIST*) + 264
3   libtesseract.4.1.0.dylib      	0x000000012ac28e39 tesseract::Textord::TextordPage(tesseract::PageSegMode, FCOORD const&, int, int, Pix*, Pix*, Pix*, bool, BLOBNBOX_LIST*, BLOCK_LIST*, TO_BLOCK_LIST*) + 217
4   libtesseract.4.1.0.dylib      	0x000000012a9f947d tesseract::Tesseract::SegmentPage(STRING const*, BLOCK_LIST*, tesseract::Tesseract*, OSResults*) + 1981
5   libtesseract.4.1.0.dylib      	0x000000012ac7ecee tesseract::TessBaseAPI::FindLines() + 1406
6   libtesseract.4.1.0.dylib      	0x000000012ac7eefb tesseract::TessBaseAPI::Recognize(ETEXT_DESC*) + 59
7   libApp.dylib                 	0x000000012a863f56 Tesseract::Detect(RegionOfInterest const&, cv::Mat const&, cv::Rect_<int>, DetectionConfig const&) + 326

Kindly suggest how to fix this crash?

**Comment by stweil** [comment]
How can this issue be reproduced (image, command line)?

**Comment by sureshyerva87** [comment]
Sorry for delayed response. Since I was working on a borrowed system and also took time to repro the crash to grab a sample image, I am replying late. I am using tesseract on videos which sometimes contain text and sometimes doesn't. If there is no text, the binarized input is plain white. The crash occurs in such scenario. I've added image along with this comment. I've used only default parameters. 
![imdump](https://user-images.githubusercontent.com/58263316/75439807-83320200-5980-11ea-8dc7-58d026d4ba63.png)

**Comment by stweil** [comment]
I cannot reproduce the crash with latest Tesseract. Did you build Tesseract 4.1.0 yourself or did you use a precompiled binary (if yes: which one)?

**Comment by sureshyerva87** [comment]
I built tesseract 4.1.0 myself with font training being turned off

**Comment by stweil** [comment]
As you build it yourself on macOS, it should be possible to reproduce for me. Could you please provide the commands which you used for all steps (getting source, configure, make, run test)?

**Comment by stweil** [comment]
Tesseract binaries for macOS are available with [Homebrew](https://brew.sh/) for example.

**Comment by sureshyerva87** [comment]
I have turned off training tools via CMakeLists.txt (ie. BUILD_TRAINING_TOOLS to OFF). Then followed typical cmake steps ie. 
mkdir build && cd build
cmake ..
make

**Comment by sureshyerva87** [comment]
using leptonica version: 1.76.0

**Comment by stweil** [comment]
My cmake build of tesseract-4.1.0 with leptonica-1.79.0 does not show this issue.

**Comment by sureshyerva87** [comment]
It took me quite long time to root cause it to some extent. This is reproducible with systems having AVX support, but not AVX2 support. (For ex: MacBook early 2013 & catalina OS)

**Comment by stweil** [comment]
It's a known issue that 4.1 cmake builds with AVX2 compiler options, so the resulting code requires machines with AVX2 support.

**Comment by amitdo** [comment]
The solution is to upgrade to version 5.1.0.
