### ISSUE TITLE
tesseract creates error when running on command line with --oem 1

### ISSUE THREAD

**Issue by alex4200** [tesseract-ocr/tesseract#2888]
### Environment

* **Tesseract Version**: v3.04.01
* **Platform**: Ubuntu 16.04.6

### Current Behavior:

Running tesseract as follows creates an error message

```
> tesseract test.png  out --oem 1
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
read_params_file: Can't open 1
```

Is `tesseract` trying to open something? That does not make sense. That should work according to the [documentation](https://tesseract-ocr.github.io/tessdoc/Command-Line-Usage.html). 

### Expected Behavior:

Output

```
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
```

### Suggested Fix:

Fix the code or the documentation.

**Comment by zdenop** [comment]
You are using old sw and new docs. We can not fix that. You have to align your sw with docs.

**Comment by alex4200** [comment]
@zdenop  I was installing the software according to the [documentation](https://tesseract-ocr.github.io/tessdoc/Home.html)! I did

    sudo apt install tesseract-ocr

That installed the version 3 of the software. 

So then the documentation is old/incorrect?

**Comment by zdenop** [comment]
Please read my comment once again. And again.

**Comment by alex4200** [comment]
How do I know that I use old sw and new docs? I was following the documentation!

So at least there is a usability issue in the documentation somewhere. Maybe I open another ticket on that?

**Comment by stweil** [comment]
@alex4200, you are using Ubuntu xenial, a 4 years old version of Ubuntu, so you'll get a 4 years old version of Tesseract. Look for Tesseract 3 to find matching documentation. And don't expect to get the latest improvements with that old version. If you want to use the latest and best releases of Tesseract, you will have to update to a recent Ubuntu version.

**Comment by alex4200** [comment]
@stweil  Thank you for that clarification. 

Was not obvious from the documentation ;-)

**Comment by Shreeshrii** [comment]
Alternately you can install tesseract from ppa
