### ISSUE TITLE
not reading text from image, showing empty page

### ISSUE THREAD

**Issue by alpitabrol** [tesseract-ocr/tesseract#2889]
I was trying to make code from extracting text (digits particularly) from the stickers attached to the fruits and vegetables. But when I am running the image with tesseract it's showing that there is no text to be converted (Empty Page!)
 I have attached three test images, which I am trying to convert.

It would be great if anyone can help with the c/c++ code to extract text from the images.

Thanks.
![x](https://user-images.githubusercontent.com/55200468/74949057-3459fa80-53cb-11ea-887a-f6d52b4ca158.jpeg)
![a](https://user-images.githubusercontent.com/55200468/74949066-36bc5480-53cb-11ea-8113-bc5c39583b63.jpeg)
![test_image](https://user-images.githubusercontent.com/55200468/74949072-391eae80-53cb-11ea-9dcf-2ac3b5c58ed7.jpg)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Make sure you [read docs](https://tesseract-ocr.github.io/tessdoc/) first, search forum and describe what you already tried.
