### ISSUE TITLE
Best filter/preprocess for these type of image?

### ISSUE THREAD

**Issue by jdahan91** [tesseract-ocr/tesseract#2891]
Hi, I would love to know which type of preprocessing these images would be the best in order to successfully read them all. Note that the filter/preprocess needs to be generic which means to work across all four images.

[Normal](https://i.stack.imgur.com/4N62x.png)
[Grayscale](https://i.stack.imgur.com/3upPM.png)
[Inverted](https://i.stack.imgur.com/WcrGU.png)
[Inverted](https://i.stack.imgur.com/ymhv6.png)

Thanks.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by jdahan91** [comment]
> Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

I don't have an account there, I just want help on this one little thing.

**Comment by jdahan91** [comment]
> Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

People are more active here rather there. Come on, open this issue to I can get help faster.

**Comment by jdahan91** [comment]
asd
