### ISSUE TITLE
eng.traineddata is used when runnig tesstrain.sh for swedish language

### ISSUE THREAD

**Issue by karlc1** [tesseract-ocr/tesseract#2892]
### Environment

* **Tesseract Version**:tesseract 4.1.1
* **Commit Number**: 
* **Platform**: Linux arch 5.5.5-arch1-1

### Current Behavior:

I'm trying to generate training data for a specific font using swedish language with `tesstrain.sh`. My argument looks like follows: 

```
tesstrain.sh --fonts_dir fonts \
             --fontlist 'TratexSvart' \
             --lang swe \
             --linedata_only \
             --langdata_dir langdata_lstm \
             --tessdata_dir tesseract/tessdata \
             --save_box_tiff \
             --maxpages 10 \
             --output_dir train
```

I have downloaded the `swe.traineddata`  file from tessdata_best to my tesseract/tessdata directory. However, upon running the script, I get the following output: 

```
Error opening data file tesseract/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
```
When I download `eng.traineddata` to tesseract/tessdata directory, the script does run, but I get a lot of output like this:

```
Stripped 53 unrenderable words
Rendered page 0 to file /tmp/swe-2020-02-23.6ab/swe.TratexSvart.exp0.tif
Stripped 43 unrenderable words
Rendered page 1 to file /tmp/swe-2020-02-23.6ab/swe.TratexSvart.exp0.tif
```

My question is, why do I need the eng.traineddata at all when training for swedish, and is that related to the many unrenderable words that gets reported? Should not `swe.traineddata` be used for feature extraction here? Am I using this script wrong?
Thanks

**Comment by Shreeshrii** [comment]
Usually unrenderable words is related to the font not being able to render the text. Take a look at the training text in your font and check.

**Comment by karlc1** [comment]
I'm not sure what you mean by 'training text in my font' (sorry i'm pretty new to this), but the generated .tif file looks like I would expect.

**Comment by Shreeshrii** [comment]
The tif is generated without the unrenderable words, so it will be ok. 
If you are curious as to what is being dropped, You can open the text in an editor, apply the font for viewing and see if some letters show up as square boxes

**Comment by Shreeshrii** [comment]
tesstrain.sh uses the default language `eng` on a sample text before starting `Phase I: Generating training images`. Hence, eng.traineddata is required, even when training for other languages.

```
[Sun Nov 24 12:27:33 UTC 2019] /usr/local/bin/text2image --fonts_dir=/usr/share/fonts --font=Arial Bold --outputbase=/tmp/font_tmp.qCvjIpRZ1P/sample_text.txt --text=/tmp/font_tmp.qCvjIpRZ1P/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.qCvjIpRZ1P
Rendered page 0 to file /tmp/font_tmp.qCvjIpRZ1P/sample_text.txt.tif

=== Phase I: Generating training images ===
```
