### ISSUE TITLE
Some Arabic-Indic  numbers are being reversed 

### ISSUE THREAD

**Issue by ShroukMansour** [tesseract-ocr/tesseract#2897]
### Environment

* **Tesseract Version**:tesseract 4.1.1-rc2-21-gf4ef
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0
 Found AVX
 Found SSE
 Found libarchive 3.1.2

Hi, I've done plusminus training using tesstrain.sh on the ara.traineddata best model for adding arabic-indic characters. The problem is the model is recognizing some arabic-indic numbers correctly but others are incorrectly reversed. 
here is the result with <<<num>>> around the reversed number 
```
والعشرين من يوليو عام ‎،١٨٧٦‏ وقضت أيامها المدرسية الأولى
هناك. ثم ارتادت في وقت لاحق مدرسة ليدي جين غري بنغهامتن/
نيويورك، وتخرجت فيها عام<<<٦٩٨١>>>.‏ وأثبتت جدارتها بوصفها طالبة
متميزة في كلية أفاسار التي حصلت منها على شهادتها عام ‎٤١٩٠١
```
and this is the image 

![issue](https://user-images.githubusercontent.com/18499889/75140861-6c797a00-56f8-11ea-8d5a-fbc4ba3292e4.png)

Do I need to change any parameters? I've found several issues for this problem but I didn't get what is the final solution

**Comment by ShroukMansour** [comment]
@amitdo @Shreeshrii Any help!

**Comment by Shreeshrii** [comment]
This is a known issue. Please see https://github.com/tesseract-ocr/tesseract/issues/1193

**Comment by amitdo** [comment]
There are some minor issues with RTL languages related to the the bidi handling in Tesseract. 

There is no known solution in Tesseract itself. 

However, if you can find a repeated pattern of errors you might be able to post process the output with a script (in Python or another language) and fix the errors. Does it always reversed when there is a dot in the end of a number? If so, you can reverse all such cases.

**Comment by ShroukMansour** [comment]
@amitdo  @Shreeshrii I've discovered the problem 
For any Arabic-indic number, tesseract output an ltr and rtl Unicodes before and after it 
The problem is tesseract sometimes doesn't output the ltr code before it, so a script can be made to handle this manually

**Comment by MohammedNoseir** [comment]
are you found solution ?
