### ISSUE TITLE
make fail on cygwin64

### ISSUE THREAD

**Issue by llhhbc** [tesseract-ocr/tesseract#290]
make fail on cygwin64 when I have changed the file 'opencl/openclwrapper.h'  on line 67 : #define PERF_COUNT_VERBOSE 3,   

Then I change the file 'opencl/openclwrapper.h' on line 13: defined( __CYGWIN__ ),  more problems come.

**Comment by zdenop** [comment]
1. Do not change source code unless you are willing to fix consequences by yourself.
2. Make sure that cygwin64 is supported by your opencl provider.
3. Opencl is experimental feature. It was tested on linux and partially on VS2010. Other compilers are not supported - but you can try tesseract user forum for support.

**Comment by llhhbc** [comment]
Thanks.  But  in cygwin, The define of __CYGWIN32__ is no longer used, replaced by __CYGWIN__

**Comment by zdenop** [comment]
Thank. Changed

**Comment by llhhbc** [comment]
Excuse me, I had met a problem when I used the cmake 
pkg_check_modules(Leptonica REQUIRED lept)       this package didn't found, How can I solved it? 
By the way, I have installed the lib leptonica already, and  I finished making the tesseract by ' configure && make '. 

Thanks.

**Comment by zdenop** [comment]
follow instrustruction for cmake ;-)

**Comment by llhhbc** [comment]
Thanks, I have solved this problem.
