### ISSUE TITLE
Is there a way to build a stripped-down version of Tesseract?

### ISSUE THREAD

**Issue by rishabhsinghvi** [tesseract-ocr/tesseract#2900]
Not really a technical question.

I want to use this library in a micro-controller which has about 320KB of SRAM available with no MMU. Is there a way to build a stripped-down version of this library? I don't need many of the features available, such as PDF output, PNG support, non-English language packs.

Thanks.

**Comment by stweil** [comment]
320 KB? I'd say there is no chance to strip the library to that size.
