### ISSUE TITLE
Using OpenCL wth lstmtraining

### ISSUE THREAD

**Issue by victornguyen18** [tesseract-ocr/tesseract#2901]
### Environment

* **Tesseract Version**: 4.0.0 
* **Commit Number**: 
* **Platform**: Windows 10 64 bits

### Current Behavior:
  Currently, `lstmtraining` use CPU to run. In some cases, i worry it will make crack in some services in the same system?

### Expected Behavior:
  We have any support for GPU to run `lstmtraining` and any training tool. It will improve timing or any else?

**Comment by amitdo** [comment]
IMO, this is very unlikely to happen. 

You can use [kraken](https://github.com/mittagessen/kraken) or [Calamari](https://github.com/Calamari-OCR/calamari). They support GPU acceleration for inference and training.
