### ISSUE TITLE
Tesseract failing to build in Docker

### ISSUE THREAD

**Issue by minusdavid** [tesseract-ocr/tesseract#2907]
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- travis/support (LoadError)
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /root/.travis/travis-build/lib/travis/build.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /root/.travis/travis-build/init.rb:11:in `setup'
        from /var/lib/gems/2.5.0/gems/travis-1.8.10/lib/travis/cli/command.rb:197:in `execute'
        from /var/lib/gems/2.5.0/gems/travis-1.8.10/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.5.0/gems/travis-1.8.10/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'

**Comment by tranzmatt** [comment]
This is still a thing. :\

**Comment by amitdo** [comment]
The repoeted issue seems to be in travis which uses Docker. Our own travis build has no issues currently.

**Comment by casperbh96** [comment]
For anyone searching for this, I recently compiled a Tesseract base image with Conda installed (could be switched to another base). This is the Dockerfile (downloads English and Danish trained data files):

```dockerfile
# Set docker image
FROM continuumio/miniconda3

# archived version and tessdata version (fast or best)
ENV TESS_VERSION=5.0.0-rc2
ENV TESSDATA_VERSION=best

# Update and install depedencies
RUN apt-get update && \
    apt-get install -y wget unzip bc vim python3-pip libleptonica-dev git

# Packages to complie Tesseract
RUN apt-get install -y --reinstall make && \
    apt-get install -y g++ autoconf automake libtool pkg-config \
     libpng-dev libjpeg62-turbo-dev libtiff5-dev libicu-dev \
     libpango1.0-dev autoconf-archive poppler-utils

# Install Tesseract
WORKDIR /app
RUN mkdir src && \
    cd /app/src && \
    wget "https://github.com/tesseract-ocr/tesseract/archive/${TESS_VERSION}.zip" && \
    unzip "${TESS_VERSION}" && \
    cd "/app/src/tesseract-${TESS_VERSION}" && \
    ./autogen.sh && \
    ./configure && \ 
    make -j$(nproc) && \ 
    make install && \
    ldconfig && \
    make training && \
    make training-install && \
    cd /usr/local/share/tessdata && \
    wget "https://github.com/tesseract-ocr/tessdata_${TESSDATA_VERSION}/raw/main/eng.traineddata" && \
    wget "https://github.com/tesseract-ocr/tessdata_${TESSDATA_VERSION}/raw/main/dan.traineddata"

# Setting the data prefix
ENV TESSDATA_PREFIX=/usr/local/share/tessdata

RUN tesseract --version
```

**Comment by zdenop** [comment]
+ https://tesseract-ocr.github.io/tessdoc/Docker-Containers.html
So it seem to me like solved...
