### ISSUE TITLE
Tesseract v5.00 tessdata

### ISSUE THREAD

**Issue by suravijayjilla** [tesseract-ocr/tesseract#2912]
Hi,

I installed tesseract v5.00 alpha in my windows 64-bit machine.
I need tessdata for tesseract v5 to train and improve OCR accuracy.

https://tesseract-ocr.github.io/tessdoc/Data-Files#special-data-files

In this link, I didn't get that tessdata.
Please help me, where to download the tesseract v5.00 alpha tessdata.

**Comment by amitdo** [comment]
There're no newer data files for 5.0. The data files for 4.x (best / fast / tessdata) should work fine with tesseract 5.x.

We have a [forum](https://groups.google.com/d/forum/tesseract-ocr). Please use it next time you have a question about Tesseract.
