### ISSUE TITLE
Orientation confidence in TessBaseAPIDetectOrientationScript

### ISSUE THREAD

**Issue by kamrapooja** [tesseract-ocr/tesseract#2913]
Hi,
We are using TessBaseAPIDetectOrientationScript to get orientation of image.
The api is giving confidence for each image.
What is the range of good, bad or better confidence?
For some images confidence is 5 and for some 10 and so on.
So can 10 be considered good or average confidence?

**Comment by amitdo** [comment]
I think the score depends on the number of glyphs in the document. More glyphs will give you higher confidence.

**Comment by kamrapooja** [comment]
Ok. But how can i confirm orientation given by API is correct or not?

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/2a37f5dd6226156bf32e60d1ae0209a383af4843/src/ccmain/osdetect.cpp#L187-L191

I think that the number of blobs might be useful information together with the confidence score.

Currently, this number is not exposed to  DetectOrientationScript (C++)  / TessBaseAPIDetectOrientationScript (C API) callers.

**Comment by amitdo** [comment]
>So can 10 be considered good or average confidence?

Even with the extra info, you'll need to evaluate hundreds of images that represents the images that you will later use on production to gather statistics and calculate the good range and the average.

**Comment by FarhadKhalafi** [comment]
We also had a requirement for detecting and correcting page orientation in scanned images. We tried this functions, as well as, TessPageIteratorOrientation and Leptonica's pixUpDownDetect without much success. There were a lot of errors specifically with mono-spaced text and less than ideal OCR quality. What we ended up doing was to run full OCR at orthogonal orientations and evaluate a confidence score based on the detected English words (in our case), their frequencies, confidence levels, whether they appeared in a dictionary and their lengths. We added some weights and biases for certain patterns for our specific data. We turned off OSD. If confidence was below a threshold, we kept rotating the image in 90 degrees and re-running the OCR engine. We then picked the orientation that gave best results. This, obviously, is a bit wasteful, but was the only approach that kind of worked.

**Comment by amitdo** [comment]
@FarhadKhalafi, 

Yes, what you discribes is the classic way to do orientation detection.

**Comment by kamrapooja** [comment]
Closed

**Comment by samuel-rogers-data** [comment]
> We also had a requirement for detecting and correcting page orientation in scanned images. We tried this function, as well as, TessPageIteratorOrientation and Leptonica's pixUpDownDetect without much success. There were a lot of errors specially with mono-spaced text and less than ideal image quality.
> 
> What we ended up doing was to run full OCR at orthogonal orientations and evaluate a confidence score based on detected English words (in our case), their frequencies, confidence levels, whether they appeared in a dictionary and their lengths. We added some weights and biases for certain patterns for our specific data. We also turned off OSD.
> 
> If confidence was below a threshold, we kept rotating the image in 90 degrees and re-running the OCR engine. We then picked the orientation that gave the best result. This approach is obviously a bit wasteful, but was the only one that kind of worked.
> 
> The project has over 16 million images and we are processing about 10,000 per hour with 4 VMs. We have processed 3 million pages already, even with this rather brute force approach, and knowing that we will miss-classify the orientation occasionally, but hopefully, not too often.

Wow thank you! So what confidence interval range did you see on your production?
