### ISSUE TITLE
misreported char_left coordinate

### ISSUE THREAD

**Issue by walied-bci** [tesseract-ocr/tesseract#2915]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 4.0.0-beta.1
* **Platform**: Linux 03f1d478a023 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior: 
![17_color PNG,1,0,83,218,102](https://user-images.githubusercontent.com/61854477/76040297-f1cb1d00-5f89-11ea-9e4f-7870eef12764.PNG)
The above image ocrs correctly with the command
```tesseract 17_color.PNG,1,0,83,218,102.PNG tsv --oem 1 --psm 6 -l ind -c tessedit_create_tsv=1 -c tessedit_pageseg_mode=7```
, but the tsv shows a left coordinate for the character M that is way too far to the left, character width and top appear wrong as well.

### Expected Behavior:
correct tsv output

### Suggested Fix:
No suggestion

**Comment by amitdo** [comment]
This issue was reported many times before. 

Bounding boxes of character are not accurate when using the lstm engine. The word boxes should be more accurate.

**Comment by amitdo** [comment]
>Tesseract Version: 4.0.0-beta.1

You are using an old version we do not support.

There were some improvements related to the characters bounding boxes issue, which somewhat improved the accuracy. It is still not accurate enough for most users.
