### ISSUE TITLE
Fails to stop text retrieving process when timeout hits before completing text retrieving process.

### ISSUE THREAD

**Issue by divyangashah** [tesseract-ocr/tesseract#2916]
Environment

**Tesseract Version:** 4.0.0.0-beta3
**Platform:** 64-bit

**Current Behavior:** we are providing timeout at page level for tesseract ocr operation for pdf/image files. It works fine when timeout=0. but, apart from that for ex., 2 mins. or 5 mins. it fails with unexpected error and crashed whole application

**Expected Behavior:** If we provide a timeout and page is not able to processed within timeout limit it should stop retrieving text for that page and go further for the next page.

**Comment by amitdo** [comment]
We only support the command line tool, the C++ API and the C API.

Unless you can reproduce this issue with one of the above, you should move this report to the forum. Maybe someone will able to help you there.
