### ISSUE TITLE
the recognition efficiency of the same picture is reduced by 10 times

### ISSUE THREAD

**Issue by iori2882** [tesseract-ocr/tesseract#2917]
Without changing any settings, the recognition efficiency of the same picture is reduced by 10 times.
Before time 300ms,current time 3500ms,And typing the command tesseract -v also takes more than 3 seconds to display the result!What causes this to happen? The same picture, the same settings, Memory and CPU resources are normal,the recognition efficiency of yesterday and today is much worse!
When I tried to restart the computer, the recognition speed was restored. Can this be avoided?
Thank you for your answer!!

**Comment by amitdo** [comment]
My guess is that it was caused by one of these:
1) Your computer started using the virtual memory, which is much slower than real memory. 
2) You ran 2 or more apps at the same time which were competing with each other on resource consumption (CPU, RAM).

It's probably not Tesseract fault (unless you can prove otherwise).

**Comment by amitdo** [comment]
Sorry, I missed this part: 

>Memory and CPU resources are normal

How did you measured them?

Anyway, without an example that can be reproduced on a developer machine, we really can't help you.

**Comment by stweil** [comment]
@iori2882, please add the output from `tesseract -v` to this issue. Which operating system do you use?

**Comment by iori2882** [comment]
> Sorry, I missed this part:
> 
> > Memory and CPU resources are normal
> 
> How did you measured them?
> 
> Anyway, without an example that can be reproduced on a developer machine, we really can't help you.

The project is currently under development, and this issue only occurred once during the development process. Also, after restarting the computer, it returned to its normal state and currently cannot reproduce the problem. If it appears again next time, I will sort out a detailed report.

**Comment by iori2882** [comment]
> @iori2882, please add the output from `tesseract -v` to this issue. Which operating system do you use?
tesseract -v:
![image](https://user-images.githubusercontent.com/1480587/76146882-ef73da80-60d1-11ea-9771-bc94da932f4b.png)


Development environment:
Operating System: Windows 7
Development Tools: node12
Computer: 16GB memory and i7 CPU 8 cores
