### ISSUE TITLE
Can't build on Windows using SW

### ISSUE THREAD

**Issue by lucaszanella** [tesseract-ocr/tesseract#2918]
Tried

  ```
  Download the latest SW (Software Network https://software-network.org/) client from https://software-network.org/client/.
    Run sw setup (may require administrator access)
    Run sw build org.sw.demo.google.tesseract.tesseract-master.

```
and got
```
[199/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.cd4831-local.dll
[200/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.9d8de4-local.dll
[201/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.5b0f86-local.dll
[202/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.3de3c8-local.dll
[203/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.32c803-local.dll
[204/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.1ae36c-local.dll
[205/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.b611e2-local.dll
[206/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.39c9ce-local.dll
[207/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.bcba3a-local.dll
[208/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.6ad19c-local.dll
[209/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.9e5c84-local.dll
[210/211] C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.21b188-local.dll
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:595, function execute1: When executing: C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.9d8de4-local.dll
Creating library C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.9d8de4-local.lib and object C:/Users/LZ/.sw/storage/tmp/cfg/270246/loc.sw.self.9d8de4-local.exp
sw.cpp.fecc5646.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: struct sw::driver::CommandBuilder __cdecl sw::NativeCompiledTarget::addCommand(class std::shared_ptr<struct sw::builder::Command> const &)const " (__imp_?addCommand@NativeCompiledTarget@sw@@QEBA?AUCommandBuilder@driver@2@AEBV?$shared_ptr@UCommand@builder@sw@@@std@@@Z) referenced in function "void __cdecl build(struct sw::Build &)" (?build@@YAXAEAUBuild@sw@@@Z)
C:\Users\LZ\.sw\storage\tmp\cfg\270246\loc.sw.self.9d8de4-local.dll : fatal error LNK1120: 1 unresolved externals      command failed: exit code = 1120 (0x460)
PS C:\Users\LZ\sw\test\integrations\cmake\tess>
```

**Comment by Moldoteck** [comment]
It's problem of sw. Try sw --self-upgrade , maybe it is solved

**Comment by lucaszanella** [comment]
@Moldoteck yes, thanks, it worked.
By the way, do you have or know anyone that can provide me MinGW modern builds of tesseract? SW isn't, yet, compatible with MinGW (talked with the guy who mantains it). But I needed to compile my project with MinGW.

**Comment by stweil** [comment]
https://github.com/UB-Mannheim/tesseract/wiki provides builds made with Mingw-w64.

**Comment by lucaszanella** [comment]
@stweil these are .dll only, not for development, can't link them on my project

**Comment by stweil** [comment]
Maybe you can use their [build script](https://github.com/UB-Mannheim/tesseract/blob/windows/.github/workflows/build.sh) as a starting point for your own work.

**Comment by lucaszanella** [comment]
Thanks @stweil, I dockerized the script.

Anyone can test by doing

```
git clone https://github.com/lucaszanella/tesseract
cd tesseract
git checkout windows
git checkout ed2f849
cd docker
./build.sh
./run.sh
./docker/static_build.sh 
```
I'm planning to automate the last step to build the fles directly to a volume and then exit, thus not requiring `./docker/static_build.sh `. I also added commit 9d4a4b9 so people seeing this some hours after I post still see what I'm talking about now

However, I don't understand where and which files are being built. I see some things like `libtesseract.la`. What's an `la` file?
Can somebody explain to me how I get binaries + include files for windows to be used in my MinGW build? What can I pass to configure to make the static libraries available in a pre defined folder?
Is is possible to compile the files with cmake support so cmake automatically find them? (that is, compile with `FindTesseract.cmake` etc)

I'm gonna provide binaries when it's done, and also make it more easy to search for this builder and/or binaries for Windows, because it's been 10 days that I'm on this quest. I tested some mingw binaries from msys2 but they're too slow, maybe they're old or compiled with debug mode. I'm also having problems with SW builder.

Please anyone feel free to do a pull request, the hardest part (dockerizing everything) is already done :)

**Comment by 1480c1** [comment]
> What's an `la` file?

https://stackoverflow.com/questions/1238035/what-are-libtools-la-file-for

**Comment by lucaszanella** [comment]
@1480c1 

I found this link minutes ago, but I couldn't find how to convert .la to .dll, so I opened: https://stackoverflow.com/questions/60647403/ive-compiled-a-library-to-a-bunch-of-la-files-how-to-get-dll-from-them 

Do you have an idea?

mingw-w64 isn't just mingw 64 bits version of mingw? (although mainained by different teams)

**Comment by 1480c1** [comment]
> I found this link minutes ago, but I couldn't find how to convert .la to .dll, so I opened: https://stackoverflow.com/questions/60647403/ive-compiled-a-library-to-a-bunch-of-la-files-how-to-get-dll-from-them

You can essentially ignore and trash the la files since they aren't actively used anymore by a lot of projects. You cannot generate a dll file from the la file since the la file is a text file that only helps libtool to find the right names when searching for a library on platforms other than the generic linux distro



> mingw-w64 isn't just mingw 64 bits version of mingw? (although mainained by different teams)

Not really, they might achieve similar goals (compiling windows binaries), they have different source code and capabilities
https://en.wikipedia.org/wiki/Mingw-w64#History

**Comment by lucaszanella** [comment]
Ok, I'll ignore them. But I don't see .dll files being generated. Did I do something wrong? I've only seen .la files at the output, and an include folder.

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 12 de mar de 2020 01:51, Christopher Degawa escreveu:

**Comment by 1480c1** [comment]
Perhaps the `--enable-static` flag is causing it to only generate a `.a` static library, try running `find * -name "*.a"` and see if you find anything

**Comment by lucaszanella** [comment]
No, there's just .la, however it looks like it installed  libtesseract.a elsewhere, take a look:

```
make[2]: Entering directory '/home/project'
 /bin/mkdir -p '/usr/x86_64-w64-mingw32/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libtesseract.la '/usr/x86_64-w64-mingw32/lib'
libtool: install: /usr/bin/install -c .libs/libtesseract.lai /usr/x86_64-w64-mingw32/lib/libtesseract.la
libtool: install: /usr/bin/install -c .libs/libtesseract.a /usr/x86_64-w64-mingw32/lib/libtesseract.a
libtool: install: chmod 644 /usr/x86_64-w64-mingw32/lib/libtesseract.a
libtool: install: x86_64-w64-mingw32-ranlib /usr/x86_64-w64-mingw32/lib/libtesseract.a
libtool: warning: remember to run 'libtool --finish /home/install_prefix/lib'
 /bin/mkdir -p '/usr/x86_64-w64-mingw32/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c tesseract.exe '/usr/x86_64-w64-mingw32/bin'
libtool: install: /usr/bin/install -c tesseract.exe /usr/x86_64-w64-mingw32/bin/tesseract.exe
 /bin/mkdir -p '/usr/x86_64-w64-mingw32/lib/pkgconfig'
 /usr/bin/install -c -m 644 tesseract.pc '/usr/x86_64-w64-mingw32/lib/pkgconfig'
 /bin/mkdir -p '/usr/x86_64-w64-mingw32/include/tesseract'
 /usr/bin/install -c -m 644 ./include/tesseract/version.h include/tesseract/apitypes.h include/tesseract/baseapi.h include/tesseract/capi.h include/tesseract/genericvector.h include/tesseract/helpers.h include/tesseract/ltrresultiterator.h include/tesseract/ocrclass.h include/tesseract/osdetect.h include/tesseract/pageiterator.h include/tesseract/platform.h include/tesseract/publictypes.h include/tesseract/renderer.h include/tesseract/resultiterator.h include/tesseract/serialis.h include/tesseract/strngs.h include/tesseract/thresholder.h include/tesseract/unichar.h '/usr/x86_64-w64-mingw32/include/tesseract'
make[2]: Leaving directory '/home/project'

```

Can this .a be used with mingw on windows?

**Comment by 1480c1** [comment]
Yes, that's the static library

**Comment by lucaszanella** [comment]
I got these files on the compilation:

```
libtesseract.a
libtesseract_avx.a
libtesseract_avx2.a
libtesseract_ccutil.a
libtesseract_fma.a
libtesseract_lstm.a
libtesseract_native.a
libtesseract_opencl.a
libtesseract_sse.a
```

I linked my project to `libtesseract.a` only, and I got undefined references to `libjpeg, libpng, libtiff`, and socket related things. Tesseract does not build them statically into the library? I don't think these libs are on the other .a files.

Can somebody help me?

**Comment by stweil** [comment]
Did you try to add those libraries to your linker command? That would solve those undefined references.

**Comment by lucaszanella** [comment]
Just tried now:

```
target_link_libraries(roseek
        ctmedia_codec ctstream maincore
        Qt5::Core Qt5::Quick
        opencv_core411
        opencv_imgcodecs411
        tesseract
        tesseract_avx
        tesseract_avx2
        tesseract_ccutil
        tesseract_fma
        tesseract_lstm
        tesseract_native
        tesseract_opencl
        tesseract_sse)
```
and none of the linker erros gone away.

**Comment by Shreeshrii** [comment]
> I got undefined references to libjpeg, libpng, libtiff,

Usually these are linked via leptonica.

**Comment by lucaszanella** [comment]
@Shreeshrii I linked leptonica also, but I still get these. Maybe my leptonica doesn't link them? Couldn't find one that links

**Comment by Shreeshrii** [comment]
If you followed the build script referred by @stweil, you should have leptonica with all the image libs.

See https://github.com/UB-Mannheim/tesseract/blob/windows/.github/workflows/build.sh#L31

I don't build on Windows, so can't help more than this.

```
tesseract -v
tesseract 5.0.0-alpha-595-gccb9
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found OpenMP 201511
```

**Comment by 1480c1** [comment]
You would have to link `-ljpeg -lpng -ltiff` with the final executable since those libraries aren't included in the final libtesseract.a

**Comment by lucaszanella** [comment]
@Shreeshrii yes I totally followed it. However, I think it used those libs as dynamic ones just to compile tesseract. 
Or maybe you're telling me to extract their .a files and use? @1480c1 I think you're telling me the same thing

Isn't ther a way to build with these libraries linked into libtesseract?

**Comment by 1480c1** [comment]
what file are you exactly looking for? dll, a, lib, or exe? All of them?

**Comment by lucaszanella** [comment]
@1480c1 I just want .a files to link them statically to my project.

**Comment by stweil** [comment]
@lucaszanella, some clarification: you only need `tesseract`, not `tesseract_avx` and so on in your linker command. `libtesseract.a` contains all required parts of Tesseract.

Tesseract requires Leptonica, and Leptonica requires several other libraries for different image formats. Those libraries are DLLs, but you have to link against the corresponding .dll.a files. If you want to link them statically, you must build them all from source (including Leptonica). That is a certain challenge.

**Comment by zdenop** [comment]
IMO this is part of problem is outside of tesseract issue report. So I closing it (in generally it is about static linking of any libraries with dependencies).
