### ISSUE TITLE
Tesseract unable to read simple image correctly

### ISSUE THREAD

**Issue by velectico** [tesseract-ocr/tesseract#2920]
### Environment

* **Tesseract Version**: tesseract v5.0.0-alpha.20200223
* **Commit Number**: -
* **Platform**: Windows 64-bit 

### Current Behavior: The attached image below is not read correctly with language as English. Not being a pro, I tried some prepossessing of the image as suggested in the following link but it did not help. 
https://www.freecodecamp.org/news/getting-started-with-tesseract-part-ii-f7f9a0899b3f/
 
![Testing_Sample](https://user-images.githubusercontent.com/61957700/76184623-a23b5a00-61f2-11ea-9e34-129106878143.jpg)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
**Make sure you read docs first, search forum and describe what you already tried.**
