### ISSUE TITLE
From original is not recognized, but perfectly from tessinput.tif

### ISSUE THREAD

**Issue by rotacak** [tesseract-ocr/tesseract#2924]
### Environment

* **Tesseract Version**: tesseract v5.0.0-alpha.20200223
* **Platform**: Windows 10 64bit

### Current Behavior:
This is ok:
```
e:\prog\teseract>tesseract.exe resized_good.bmp - --psm 6 myconfig
Warning: Invalid resolution 0 dpi. Using 70 instead.
I think that's all we can carry.
```

This is ok:
```
e:\prog\teseract>tesseract.exe tessinput.tif - --psm 6 myconfig
Page 1
I think that's all we can carry.
```

Why result is total garbage when source images are almost identical?
```
e:\prog\teseract>tesseract.exe resized_bad.bmp - --psm 6 myconfig
Warning: Invalid resolution 0 dpi. Using 70 instead.
esha eeitciace iM ime bi melee
```

How this can be correct when previous bad example generated this .tif and should use it for OCR?
```
e:\prog\teseract>tesseract.exe tessinput.tif - --psm 6 myconfig
Page 1
I think that's all we can carry.
```

### Expected Behavior:
1) Almost same images should give almost same results, not totally different.
2) Result from original image or from tessinput.tif generated from that original image, should be same.

### Suggested Fix:
tessinput.tif should be used as source for OCR.

myconfig contains:
```
tessedit_char_whitelist abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ .,-"':$?!
tessedit_write_images true
```

Files: http://www.aaagames.cz/ocr/

**Comment by zdenop** [comment]
First of all read the doc:
https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html#page-segmentation-method

Next:
tesseract resized_bad_preprocessed.png - --psm 7 myconfig
I think that's all we can carry.
![resized_bad_preprocessed](https://user-images.githubusercontent.com/574156/76689516-f9985a80-6636-11ea-9ab9-3aaf7bfa54e1.png)

**Comment by rotacak** [comment]
zdenop: 
It looks like inverted images works, atleast for now. But that will not explains why from my image of white text on black background will produce **tessinput.tif** with correct colors (black text on white background). I throught that text is detected from tessinput.tif. That was reason why I not inverted the source images.

**Comment by zdenop** [comment]
> While tesseract version 3.05 (and older) handle inverted image (dark background and light text) without problem, for 4.x version use dark text on light background.

If you ignore documentation you are alone with your problems.

**Comment by rotacak** [comment]
zdenop:
You don't want to understand me. Why the content of tessinput.tif is not used as source for OCR?
