### ISSUE TITLE
The buffer unicode_repr in tesseract-4.1/src/api/baseapi.cpp at line 2486 does not have a null terminator

### ISSUE THREAD

**Issue by agarwlanurag** [tesseract-ocr/tesseract#2926]
Got this feedback when tried to use this source code.

The buffer unicode_repr in tesseract-4.1/src/api/baseapi.cpp at line 2486 does not have a null terminator

Can you please let me know how can i remediate it.

**Comment by agarwlanurag** [comment]
![image](https://user-images.githubusercontent.com/14285773/76973126-e5d64800-6905-11ea-8cec-e3e0f41a2cab.png)

**Comment by amitdo** [comment]
Why do you ignore the instructions given to everyone when posting issues?

**Comment by amitdo** [comment]
Tesseract itself (the command line tool) does not use this code since at least 2011.

`TesseractExtractResult` that uses this code is also not used by tesseract. It is obsolete. Don't use it. 

Use this instead:

`ResultIterator *it = GetIterator();`

**Comment by amitdo** [comment]
https://groups.google.com/forum/?hl=en#!searchin/tesseract-dev/TesseractExtractResult%7Csort:date/tesseract-dev/l2ZFrpgYkSc/GFkYhng64yEJ



>Ray 3/4/12
>
>PageIterator and ResultIterator should *definitely* be added to the list of exported/visible classes.
These classes provide the main API to get at detailed recognition results.
Conversely, forget TesseractExtractResult and everything else below the OCROpus cut-line.

**Comment by amitdo** [comment]
@zdenop, @stweil,

Can we remove "everything else below the OCROpus cut-line"?

**Comment by zdenop** [comment]
AFAIK OCROpus  does not use tesseract  anymore, so from this point it could be removed.

**Comment by stweil** [comment]
I'll prepare a pull request.

**Comment by stweil** [comment]
See PR #2957.
