### ISSUE TITLE
Text Direction Error in Tesseract 5.0.0-alpha

### ISSUE THREAD

**Issue by AdriiDev** [tesseract-ocr/tesseract#2929]
### Environment

* **Tesseract Version**: 5.0.0-alpha
* **Commit Number**: 916875d74a340e78be4f068d334a3a2d03986a0e
* **Platform**: Windows 10, 64-bit 

### Current Behavior:
While using the api to get the "tsv" text from the file with PSM 12 mode (i need this mode because the documents have vertical and horizontal text), I am getting the output text like arabic writing (from right to left) and the original is written from left to right.

I am using spa.trainneddata from best tranning data dictionaries.

* Original:
![ErrorTesseract_textoriginal](https://user-images.githubusercontent.com/55152621/77172175-db5eae80-6abd-11ea-96d1-1c27a5b40fc8.png)

* Output:
![ErrorTesseract_textsalida](https://user-images.githubusercontent.com/55152621/77172216-e87b9d80-6abd-11ea-92a1-39805eeb0381.png)

### Expected Behavior:

Output text in same direction as the originial text (left to right writing).

### Suggested Fix:

* Let to force text direction on api.
* Solve the bug (if it is a bug and not a dictionary problem).

**Comment by amitdo** [comment]
Where is the tsv file?

Also, post tsv output you get by running tesseract from the command line.

>with PSM 12 mode (i need this mode because the documents have vertical and horizontal text)

Try with psm 1.
