### ISSUE TITLE
Poor character / numbers recognition in table

### ISSUE THREAD

**Issue by baryluk** [tesseract-ocr/tesseract#2937]
### Environment

```
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.1.9 : libjpeg 6b (libjpeg-turbo 1.5.2) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4
```

```
$ dpkg -l | grep tesseract
ii  libtesseract4:amd64                       4.1.1-2                              amd64        Tesseract OCR library
ii  tesseract-ocr                             4.1.1-2                              amd64        Tesseract command line OCR tool
ii  tesseract-ocr-eng                         1:4.00~git30-7274cfa-1               all          tesseract-ocr language files for English
ii  tesseract-ocr-fra                         1:4.00~git30-7274cfa-1               all          tesseract-ocr language files for French
ii  tesseract-ocr-osd                         1:4.00~git30-7274cfa-1               all          tesseract-ocr language files for script and orientation
```

### Current Behavior:

Trying to OCR this table:

![-001](https://user-images.githubusercontent.com/110322/78068185-80636c00-7387-11ea-8e7e-4d840b45c918.png)

```
$ tesseract -l fra --psm 11 --oem 1 ./-001.png stdout
PORC RIENIONCT

AVR

PILCNIDNES RUE

soins intensifs

URRE VIE JUNE

LU VILTLZ

Ur HIVSPVILONISOLIUEE

hospitalisés

30.03

250 À 26 À 2 À 57 À Sa 2 À 301 | 382 | 40 À 216 | 48 | 5

31.03

2451 | 1 À 20 À 64 À à À À 821 À 40 | 28 | 2412 | 49 | 6
```

It has a lot of obvious mistakes, and it is a bit depressing. :/

### Expected Behavior:

```
...

30.03 | 2450 | 165 | 24 | 57 | 54 | 2 | 301 | 382 | 40 | 216 | 43 | 5

31.03 | 2451 | 1 | 20 | 64 | 49 | - | 321 | 405 | 28 | 241 | 49 | 6
```

Best regards and thanks for all your work,
Witold

**Comment by baryluk** [comment]
Could somebody confirm the issue on their installation of tesseract (possibly from master)? Thank you, very much appreciated!!!

**Comment by amitdo** [comment]
https://github.com/openZH/covid_19/issues/327#issuecomment-607377811

**Comment by baryluk** [comment]
@amitdo Why would you close it? It is still not fixed.

**Comment by zdenop** [comment]
Beucase it is duplicate report (e.g. #1979). Did you tried https://github.com/tesseract-ocr/tesseract/issues/1714#issuecomment-588180969

**Comment by amitdo** [comment]
>@amitdo Why would you close it? It is still not fixed.

>cc @baryluk this works for me:
> ```
>gs -o cropped.pdf -sDEVICE=pdfwrite -c >"[/CropBox [24 600 800 650]" -c "/PAGES >pdfmark" -f covid-19_ge_situation_01_04_20-s.pdf
>    convert -density 500 cropped.pdf baryluk.png
>    /tmp> pytesseract baryluk.png 2702 provisoire 45 provisoire
>```
>
>If I go below/above 500 with convert -density 500 pytesseract will not give a good result.
>
>This could be a good solution for other PDFs as well.

This sound like "problem (mostly) solved" to me.
You didn't reply to this suggestion which to me was another indication to "issue was solved".
