### ISSUE TITLE
tesseract v 4.xx  has a problem getting "1" instead of "I"

### ISSUE THREAD

**Issue by solidmaple** [tesseract-ocr/tesseract#2938]
https://x0.at/JXj.zip here is a zip file with jpg files with timecodes in it

you will notice you will get 1 instead of I using tesseract 4.xxx

tesseract version 3.xxx does NOT have this issue

**Comment by zdenop** [comment]
Tesseract 4 had different approach to training and OCR than 3.x. It will not change.
Are you serious that we should look for problematic files with in 198 image?
Also this "report" miss other import information for serious consideration like OS info, exact version of tesseract and its dependencies, who OCR was run...
