### ISSUE TITLE
Using different set of fonts for Persian

### ISSUE THREAD

**Issue by ebraminio** [tesseract-ocr/tesseract#294]
First of all, thanks for adding support to tesseract finally. From quickly inspecting Persian related codes on tesseract I reached to https://github.com/tesseract-ocr/tesseract/blob/master/training/language-specific.sh#L520 which I can say speculatively is not a good set of fonts for training Persian printed text and can result in poor performance of OCR quality as most Persian fonts don't have the style these fonts have. On ["Font recognition using Variogram fractal dimension"](http://files.matlabsite.com/docs/papers/icee2012/2/icee2012-174.pdf), a good set of Persian fonts is introduced (second page, at the bottom) which as you can see there also, it is different from favorites Arabic language fonts (even the fact both are using Arabic script). So for training Persian OCR for tesseract I suggest adding or replacing current fonts with these free fonts, Nazli (i.e. Nazanin as indicated on that article) and Titr from Debian [fonts-farsiweb](https://packages.debian.org/search?keywords=fonts-farsiweb) package and also XB Zar and XB Yaghut from OFL licensed [xfonts](http://wiki.irmug.com/index.php/X_Series_2). I think also @roozbehp @behdad from Google can help you on this. Thank you.

**Comment by amitdo** [comment]
I suggest you repost this here:
https://github.com/tesseract-ocr/langdata
and then close this issue.

but don't repeat calling/mentioning those 2 people.
