### ISSUE TITLE
equ.traineddata: detection result gibberish

### ISSUE THREAD

**Issue by sedaylmz64** [tesseract-ocr/tesseract#2942]
I am developing android project for graduation project.I added `implementation 'com.rmtheis:tess-two:9.1.0'` in build.gradle file. I am using eng+equ traineddata like this `mTess.init(datapath,"eng+equ")` .equ and eng traineddata are available on my android device inside tessdata folder. But equ.traineddata cannot recognize correctly mathematical expressions,symbols like  3x ÷ 7 = 11 , x^2 – 4 = 0 , integral symbol etc. What can i do for fix it? Can you help me please.So important for me.

**Comment by amitdo** [comment]
You need totextord_equation_detect set the parameter `textord_equation_detect` to `true`

>eng+equ

The +equ is not needed.

**Comment by sedaylmz64** [comment]
@amitdo How can i set textord_equation_detect true. Can you help me please

**Comment by amitdo** [comment]
Please use the forum for asking questions.

**Comment by sedaylmz64** [comment]
I've already asked.But i didn't find.If you know how to do please help me

**Comment by amitdo** [comment]
`api.SetVariable("textord_equation_detect", "true");`

https://github.com/rmtheis/tess-two/blob/f4653604ab0f83dcbb8ea99c8de5dadf20d98a7f/tess-two/src/com/googlecode/tesseract/android/TessBaseAPI.java#L407

**Comment by sedaylmz64** [comment]
@amitdo Thank you.I tried the way you showed, but it still didn't work right. Do you have any other suggestions?

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tessdata_fast/issues/4#issuecomment-572740279

>Do you have any other suggestions?

No, sorry.

**Comment by Datapirate-98** [comment]
I have the same problem if any one got the solution please post it
