### ISSUE TITLE
Can anyone try to compile the latest OCR file for iOS system?

### ISSUE THREAD

**Issue by lqhart** [tesseract-ocr/tesseract#2943]
I have found that it is impossible to compile the latest  OCR file for iOS system.
I am struggling to compile the OCR file to support arm64 for iOS system. but I found that there are a lot of functions \api or libraries that we can't find in the iOS system.

is any branch/version of OCR friendly with iOS ? can anyone give me some idea  for exploring this job?

Thank you,

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.

**Comment by lqhart** [comment]
@zdenop  how to access the  tesseract user forum for asking question?

**Comment by zdenop** [comment]
https://github.com/tesseract-ocr/tesseract#support

**Comment by lqhart** [comment]
@zdenop The main blocker is that accessing Support  with any Google link is blocked by China Government.

Thank you,
