### ISSUE TITLE
2 min on 1 page TIFF using Fast trained data

### ISSUE THREAD

**Issue by Molochnik** [tesseract-ocr/tesseract#2946]
I have my own simple Windows dll based on tesseractmain,cpp code. It works fine since Tesseract 3x (now I moved it the latest 5 build) and the only issue still persists is its low speed - 1 page TIFF takes around 2 minutes even with the Fast version of tessdata ('eng+rus'). Is this how it actually works or there is something I don't understand?
Almost all the time takes this line: `api.ProcessPages("c:\\1.tif", NULL, 0, NULL);`
Sample file is attached [1.tif.zip](https://github.com/tesseract-ocr/tesseract/files/4466297/1.tif.zip)

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support. And:
1. Please use official build of tesseract testing.
2. Read issue related to performance
3. Report details about you machine, OS version etc...
