### ISSUE TITLE
[For the record] Tesseract 3.01 crash on specific table like columns

### ISSUE THREAD

**Issue by vidiecan** [tesseract-ocr/tesseract#295]
Version: tesseract **3.01**
Other version: the master branch contains updated code and has not been tested
Result: ASSERT failure
Input: specific image (cannot be shared) with table like structure
Keytext: `bb_it.data()->owner() == this:Error:Assert failed:in file colpartition.cpp, line 205`

(Mixing blobs/bboxes etc. for easier reading)

ColPartitions are created from bboxes that were placed on a grid (see `colpartition.cpp::void ColPartition::AddBox(BLOBNBOX* bbox)`). It is normal that one bbox is in multiple positions (that are subsequent) and there can be multiple bboxes in one position on the grid. It can happen, that more ColPartitions are created from the same bbox (the bbox iteration returns bbox1 from [x,y] and a new ColPartition is created, then a different bbox2 is returned from the same [x,y] and another ColPartition is created, afterwards we move to [x+1, y] and get bbox1 again and yet another new ColPartition is created (see `colfind.cpp::ColPartitionSet* ColumnFinder::PartitionsAtGridY(int grid_y)`).
So far so good, we have two ColPartitions with the same bbox and we move on to merging.

These two ColPartitions are correctly selected for merging to another one (see `colpartition.cpp::bool ColPartition::Unique(ColPartition* other, WidthCallback* cb)`) BUT it can happen that `void ColPartition::AddBox(BLOBNBOX* bbox)` does _add_ them twice under very specific conditions. The result is a crash/assert (whatever you call it) in `colpartition.cpp::void ColPartition::ClaimBoxes(WidthCallback* cb)` where the list is iterated and owner is chosen. Now, if there is an item after the second position of the specific bbox, the assert (`ASSERT_HOST(bb_it.data()->owner() == this);`) is triggered because the first time it encounters the bbox the owner is set to `null` and the second time the assert `expects ==this`).

How can the box be added twice?
The specific bbox is
`
{bot_left={xcoord=1201 ycoord=1158 } top_right={xcoord=1303 ycoord=1251 } }
`
The first merge calls
`void ColPartition::AddBox(BLOBNBOX* bbox)` -> `boxes_.add_sorted(SortByBoxBottom<BLOBNBOX>, true, bbox);` (it is a vertical box). 
and it will be added to the end by

```
  // Check for adding at the end.
  if (last == NULL || comparator(&last->data, &new_data) < 0) {
```

which _can_ still be correct (`{bot_left={xcoord=1306 ycoord=1157 } top_right={xcoord=1494 ycoord=1347 } }`). 

But the second call should discard adding because of the `unique` parameter. But because there are bboxes at the beginning and only bottom is checked 

```
int SortByBoxBottom(const void* void1, const void* void2) {
  // The void*s are actually doubly indirected, so get rid of one level.
  const BBC* p1 = *reinterpret_cast<const BBC* const *>(void1);
  const BBC* p2 = *reinterpret_cast<const BBC* const *>(void2);
  int result = p1->bounding_box().bottom() - p2->bounding_box().bottom();
```

it is added again before the other value is encountered (`box = {bot_left={xcoord=1405 ycoord=1209 } top_right={xcoord=1475 ycoord=1259 } }`).

The iteration compares it with the following:

```
{bot_left={xcoord=1408 ycoord=1293 } top_right={xcoord=1440 ycoord=1337 } }
{bot_left={xcoord=749 ycoord=1142 } top_right={xcoord=933 ycoord=1258 } }
-->>{bot_left={xcoord=1405 ycoord=1209 } top_right={xcoord=1475 ycoord=1259 } }
```

Solution:
One possible solution is to iterate the other bboxes as well if `unique` is set and discard adding if it finds the same data

```
--- a/tesseract/ccutil/clst.cpp
+++ b/tesseract/ccutil/clst.cpp
@@ -252,8 +252,23 @@ bool CLIST::add_sorted(int comparator(const void*, const void*),
     }
     if (it.cycled_list())
       it.add_to_end(new_data);
     else
+    {
+        // well, it can happen that sorting is not unique because of the condition above
+        if (unique)
+        {
+            CLIST_ITERATOR it_cont(it);
+            for (; !it_cont.cycled_list(); it_cont.forward())
+            {
+              void* data = it_cont.data();
+              if (data == new_data) {
+                return false;
+              }
+            }
+        }
+
       it.add_before_then_move(new_data);
+    }
     return true;
   }
   return false;
```

**Comment by vidiecan** [comment]
Unless someone wants to check the current master, feel free to close the issue.

**Comment by zdenop** [comment]
Can you please provide image for testing?

**Comment by vidiecan** [comment]
as mentioned above, the specific image cannot be made publicly available

**Comment by zdenop** [comment]
I understand. But can you modified or create similar image that can demonstrate issue?

**Comment by stweil** [comment]
@vidiecan, if it is not possible to create a public demo image, maybe you can nevertheless provide a code patch which fixes the problem? Or is it possible to send the problematic image privately to one of the developers working an tesseract, so that he / she can fix the problem?

**Comment by amitdo** [comment]
@vidiecan, please, can you respond to @zdenop and @stweil?
