### ISSUE TITLE
best optimal font for OCR with tesseract?

### ISSUE THREAD

**Issue by monperrus** [tesseract-ocr/tesseract#2951]
Hi all,

I'd like to know the optimal font that maximizes the [recogition accuracy](https://tesseract-ocr.github.io/tessdoc/4.0-Accuracy-and-Performance) of tesseract.

Here is the idea:

* Generate a document with random 6000 characters from the base 64 character sets (basically all letters upper and lower case + digits).
* For each font on my system (a Linux box), generate an image with the same content
* Give it to Tesseract
* Measure the error rate / accuracy

Here are the results for Tesseract v4.1.1, I give the top performing fonts, the number is the error rate, lower is better:

* TeX_Gyre_DejaVu_Math 0.05850362557679631
* TeX_Gyre_Bonum 0.06888595912986156
* DejaVu_Math_TeX_Gyre 0.07003955174686882
* TeX_Gyre_Bonum_Math 0.07201713909030982
* DejaVu_Serif 0.07498352010547132
* TeX_Gyre_Schola_Math  0.07877389584706658
* Roboto 0.08206987475280159
* Cantarell 0.08404746209624259
* Arial_Black 0.08635464733025709
* Loma 0.08750823994726434
* C059 0.08767303889255108
* TeX_Gyre_Schola 0.08899143045484509
* Umpush 0.09063941990771258

What do you think?

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/langdata_lstm/blob/master/eng/okfonts.txt

Please use the forum for asking questions.

**Comment by monperrus** [comment]
Thanks for your answer!

By forum, do you mean the Google group https://groups.google.com/forum/#!forum/tesseract-ocr?

**Comment by amitdo** [comment]
Yes.
