### ISSUE TITLE
Using tesseract on MNIST returns an empty string

### ISSUE THREAD

**Issue by CommunicativeEngineer** [tesseract-ocr/tesseract#2953]
I want to recognise digits in MNIST. The scale of MNIST image is 28*28. I have the images in csv file, each row is an image. It is a flatten image (scale 784).

I tried this code but the string returned by Tesseract is empty.

import numpy as np
import matplotlib.pyplot as pt
import pandas as pd

data  = pd.read_csv("train.csv").to_numpy()

#training dataset
xtrain=data[0:7000, 1:]
train_label=data[0:7000, 0]

#testing data
xtest= data[7000:, 1:]
actual_label = data[7000:, 0]

d=xtest[10]
d.shape=(28,28) 
pt.imshow(d, cmap='gray')
pt.show()

import pytesseract
from PIL import Image

im = Image.fromarray((d).astype(np.uint8))

pt.imshow(im)

import cv2

#Grayscale image
ret,img = cv2.threshold(np.array(im), 125, 255, cv2.THRESH_BINARY)
pt.imshow(img)
text = pytesseract.image_to_string(img)

print(text)

I tried also to capture the image and i tried to read it as a png, but still Tesseract gives an empty string.

How can i correct the code to get the digits from MNIS

**Comment by amitdo** [comment]
First issue: tesseract was trained on rendered fonts. The MNIST dataset contains a large collection of **handwritten** single digits (0-9).

Second issue: tesseract was trained on text lines containing mostly words and not too many numbers.

Basically, you need to use images in the dataset to train a new model. I don't know the right parameters and how well it will work.

**Comment by CommunicativeEngineer** [comment]
Thanks a lot for your answer!

**Comment by nebiyebln** [comment]
Were you able to use tesseract and mnist dataset together? @amitdo @CommunicativeEngineer
