### ISSUE TITLE
Installation of tesseract version 4 fails after installing tesseract 5 and uninstalling it

### ISSUE THREAD

**Issue by himanshuchawla009** [tesseract-ocr/tesseract#2959]
-

### Environment
tesseract 5.0.0-alpha-647-g4a00
* **Platform**:  x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:

I installed tesseract version 5.0.0-alpha-647-g4a00 using link given below:

https://notesalexp.org/tesseract-ocr/

It was working perfectly. After then i decided to move back to version 4 to compare benchmarks.

I removed tesseract version  5.0.0-alpha-647-g4a00 using command given below:

`sudo apt-get purge --auto-remove tesseract-ocr`

I installed tesseract version 4.1 using the same link give above. But when i try to run **tesseract** command in terminal it fails with following error:

> tesseract: symbol lookup error: tesseract: undefined symbol: _ZN9tesseract10SIMDDetect15avx2_available_E

So i removed tesseract version 4.1 again and moved back to 5 alpha version. 

### Expected Behavior:
tesseract version 4.1 should work without symbol lookup error.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support. It is not tesseract issue that you mixed up your system. We can not do nothing with it.
