### ISSUE TITLE
Feature Request: Reading PDF for OCR

### ISSUE THREAD

**Issue by specter78** [tesseract-ocr/tesseract#2961]
Tesseract doesn't currently support reading from pdf for the purpose of OCR.

**Comment by stweil** [comment]
I can understand this request, but am afraid that it won't be realized unless someone is sufficiently motivated to implement it.

- There exist already several solutions which make Tesseract OCR for PDF files.
- Direct PDF support would ideally be supported by Leptonica (which is used by Tesseract to read different input formats). It requires a PDF library with a compatible license.

**Comment by amitdo** [comment]
>There exist already several solutions which make Tesseract OCR for PDF files.

For example: [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF)

>Direct PDF support would ideally be supported by Leptonica (which is used by Tesseract to read different input formats). It requires a PDF library with a compatible license.

An example for a pdf library: [qpdf](https://github.com/qpdf/qpdf)

**Comment by CanadianHusky** [comment]
Personally, I do not think that it should be within the scope of Tesseract to interpret and render a PDF file as an Image. There are plenty of other libraries (Ghostscript, XPDF, Poppler, MuPDF...) that have many options how to turn a PDF into an Image that can be fed into Tesseract. 
The Tesseract Teams development time would be far better invested in features that are directly OCR and accuracy related.

**Comment by zdenop** [comment]
1. pdf is DOCUMENT format - not an image format. So for OCR it should be converted to bitmap image. 
2. tesseract use for image opening/processing leptonica, so this is wrong place for such feature request

**Comment by jbarlow83** [comment]
Perhaps if Tesseract is given a PDF as an input file (going by file extension), it could exit with an explanation that it cannot process PDFs and print a link to:
https://tesseract-ocr.github.io/tessdoc/User-Projects-%E2%80%93-3rdParty.html
(Or perhaps a more specific page would be more suitable.)

This question does come up fairly often.

**Comment by amitdo** [comment]
@jbarlow83, that's a good idea.

**Comment by Chealer** [comment]
Thank you @specter78 for this request. I don't know your exact use case, but in our case, we are writing PDF files. Allowing to read PDF-s would allow us an "in-place" addition without needlessly converting to a different format first.

Thank you very much @amitdo for mentioning OCRmyPDF. I certainly think that adding OCR metadata to PDF files is a common use case which should be addressed by off-the-shelf software. However, there should also be a low-level OCR software component which doesn't attempt to do too much. I do not know Tesseract nor OCR software enough to give a valuable opinion about whether such functionality goes beyond Tesseract's scope due to its extra complexity / size / maintenance costs. I am not convinced that the current situation of supporting PDF creation but not recognition is completely coherent.

But I do agree that without such a feature, the documentation could at least mention that other software facilitates such use cases.

**Comment by amitdo** [comment]
@jbarlow83 commented on 23 May 2020

>Perhaps if Tesseract is given a PDF as an input file (going by file extension), it could exit with an explanation that it cannot process PDFs and print a link to:
https://tesseract-ocr.github.io/tessdoc/User-Projects-%E2%80%93-3rdParty.html
(Or perhaps a more specific page would be more suitable.)

@zdenop, @!stweil

Do you agree with this proposal?

My tweaked suggestion is to do one these options:
1) Link directly to https://ocrmypdf.readthedocs.io/en/latest/ istead of https://tesseract-ocr.github.io/tessdoc.
2) Create a new file in tessdoc and link to it: `PDF.md `.

**Comment by zdenop** [comment]
I am not sure about this. Should we do it also for other format like doc, docx, odt, xps, ps...
Anyway I think 2. option is better especially if there would be more available solutions or we can provide more detailed solution for unsupported formats.

**Comment by amitdo** [comment]
>Should we do it also for other format like doc, docx, odt

I've never seen anyone ask about using OCR for one of these formats, while OCR for PDFs is a very common request (not just with Tesseract).

>xps

I've never seen it used any website, while PDFs are extremely common in the web.

>ps...
Tiny 'market share' compared to PDF.

PDF is a common output format used by document scanners.

**Comment by amitdo** [comment]
>Direct PDF support would ideally be supported by Leptonica (which is used by Tesseract to read different input formats).

[Won't happen](https://github.com/DanBloomberg/leptonica/issues/586#issuecomment-902303648)

**Comment by amitdo** [comment]
As a first step, I'll send a PR to the tessdoc repo with a new file:`Input formats`, which will have a section `Supported input formats` and another section `Unsupported input formats` which will mention PDF and animated GIF.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tessdoc/blob/master/InputFormats.md

**Comment by amitdo** [comment]
We don't plan to implement this feature request.
