### ISSUE TITLE
Co-ordinates received by GetWordStrBoxText sequence does not match with WordStr start and end co-ordinates.

### ISSUE THREAD

**Issue by PratapMehra** [tesseract-ocr/tesseract#2967]
Co-ordinates received by GetWordStrBoxText sequence does not match with WordStr start and end co-ordinates. As moved from top to bottom Y co-ordinate decreases but in single WordStr start point Y is smaller than end point Y.
Example:
WordStr 1922 2871 2196 2893 0 # ...
	 2197 2871 2201 2893 0
WordStr 177 2828 568 2854 0 # ...
	 569 2828 573 2854 0
WordStr 1474 2827 1719 2855 0 # ...
	 1720 2827 1724 2855 0
WordStr 1921 2834 2231 2856 0 # ...
	 2232 2834 2236 2856 0

**Comment by amitdo** [comment]
You should post an image and the commands you used to produce the two different output. Also add the output of `tesseract -v` command.

**Comment by PratapMehra** [comment]
Its my mistake. 
![WordStrBox](https://user-images.githubusercontent.com/9975980/81476556-24b2bb00-9230-11ea-9458-7ca420dcce20.PNG)
It seems the two co-ordinates received from the string box is from lower left and upper top.
