### ISSUE TITLE
Recognize only complete dictionary words only

### ISSUE THREAD

**Issue by dong77** [tesseract-ocr/tesseract#297]
A related stackoverflow question is here: http://stackoverflow.com/questions/20599768/tesseract-ocr-recognize-complete-dictionary-words-only. 

Basically what I want to achieve is to ask Tesseract to recognize only complete words included in my custom dictionary (lang: chi_sim), or to find the best match. 

Following the instruction in https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc#languages, I applied a config file with the following content:
```
load_system_dawg     F
load_freq_dawg       F
user_words_file      /path/to/my/dictonary.user-words
```

But this doesn't seem to work: when I ask Tesseract to recognize word from this image

 ![x](https://cloud.githubusercontent.com/assets/1710087/14453308/a897e3dc-00c6-11e6-9637-2419cddace49.jpg),

`$ tesseract /path/to/the/above/image.jpg stdout -l chi_sim /path/to/my/config_file`

 it gives me `硝酸嘛庸喹瓢膏` which is not in the dictionary at all. The best match is supposed to be `硝酸咪康唑乳膏` which is included in the dictionary.

I searched around and couldn't find a solution. Please help me out. Thank you.

**Comment by amitdo** [comment]
>Basically what I want to achieve is to ask Tesseract to recognize only complete words included in my custom dictionary (lang: chi_sim), or to find the best match.

Tesseract can't do this. The dictionaries are just a hint for Tesseract.

**Comment by tfmorris** [comment]
You could try playing with some of the dictionary related parameters to see if you can achieve the results that you want:

    $ tesseract --print-parameters | grep dic

In particular, these two look like they might have promise:

    language_model_penalty_non_freq_dict_word	0.1	Penalty for words not in the frequent word dictionary
    language_model_penalty_non_dict_word	0.15	Penalty for non-dictionary words

**Comment by dong77** [comment]
Thank you, @amitdo and @tfmorris. I tried both `language_model_penalty_non_freq_dict_word` and `language_model_penalty_non_dict_word` but had no luck.

**Comment by zdenop** [comment]
AFAIK it is not possible within tesseract.
In some extent you can implement it by yourself. E.g. in first stage you do OCR by tesseract and then you can correct recognized text by other tool (e.g. spellchecker with custom dictionary).

**Comment by amitdo** [comment]
I found a parameter that may match what you wants:  
`tessedit_enable_dict_correction`

According to commit 09b439b05a it is 'disabled due to making accuracy worse'.

**Comment by jeremycurrygit** [comment]
Could you have any method to solve the problem?@dong77
