### ISSUE TITLE
Increase INACTIVITY_TIMEOUT (60) or make it configurable

### ISSUE THREAD

**Issue by AlexanderSamoilov** [tesseract-ocr/tesseract#2972]
### Environment
Windows 10 64bit

### Current Behavior:
Build of tesseract fails due to ICU zipfile downloading timeout.
Log:
-- Downloading latest ICU binaries
-- [download 22% complete]
-- [download 23% complete]
...
[CMake Error at src/training/CMakeLists.txt:39 (file):
  ?file DOWNLOAD HASH mismatch

    ?fo file: [E:/build01/workspace/module-tesseract_maintennce_1.0@2/tesseract/bin/src/training/icu/icu64.zip]
      ?exected hash: [480c72491576c048de1218c3c5519399]
        ?actual hash: [ab483d102e149e470bb2bf2a5680381a]
             ?status: [28;"Timeout was reached"]

### Expected Behavior:
No failure due to timeout.

### Suggested Fix:
File : https://github.com/tesseract-ocr/tesseract/blob/master/src/training/CMakeLists.txt.
Please, increase the default value of INACTIVITY_TIMEOUT constant from 60 to 300, or provide a command line parameter to configure this value.

Without it we have in 60-70% cases builds failed due to this timeout.
60 seconds is too little for our network. According to my observations the icu64.zip download lasts about 3-4 minutes quite often.

**Comment by amitdo** [comment]
CC: @egorpugin

**Comment by egorpugin** [comment]
Fixed, thanks.

**Comment by AlexanderSamoilov** [comment]
Thank you for the quick fix! I wanted to test it and give a feedback, but unfortunately the server download-icu-project.org (66.34.208.13) became permanently unreachable and I cannot build tesseract at all now due to that. If this URL is no longer valid I hope that you know about this.
--
Best Regards,
Alexander

**Comment by amitdo** [comment]
@egorpugin,

http://site.icu-project.org/download/66#TOC-ICU4C-Download

>Source and binary downloads are available on the git/GitHub tag page: https://github.com/unicode-org/icu/releases/tag/release-66-1

**Comment by egorpugin** [comment]
@AlexanderSamoilov You can try links provided by @amitdo, select working and open PR with this change or post it here.

**Comment by AlexanderSamoilov** [comment]
I could not create a PR, because I cannot push. Perhaps I don't have enough permissions:
~/tesseract (iculib-new-download-url)
$ git push --set-upstream origin iculib-new-download-url
remote: Permission to tesseract-ocr/tesseract.git denied to AlexanderSamoilov.
fatal: unable to access 'https://github.com/tesseract-ocr/tesseract.git/': The requested URL returned error: 403

I would just post my patch here:

```
diff --git a/src/training/CMakeLists.txt b/src/training/CMakeLists.txt
index 8f6c03db..fdc1aec7 100644
--- a/src/training/CMakeLists.txt
+++ b/src/training/CMakeLists.txt
@@ -37,7 +37,7 @@ if (MSVC AND NOT SW_BUILD AND NOT USE_SYSTEM_ICU)
     message(STATUS "Downloading latest ICU binaries")

     file(DOWNLOAD
-        "http://download.icu-project.org/files/icu4c/56.1/icu4c-56_1-Win${ARCH_DIR_NAME}-msvc10.zip"
+        "https://github.com/unicode-org/icu/releases/download/release-56-1/icu4c-56_1-Win${ARCH_DIR_NAME}-msvc10.zip"
         "${icu_archive}"
         SHOW_PROGRESS
         INACTIVITY_TIMEOUT 300 # seconds
```

I tested the new URL and made sure that I get the same file (with the same md5sum 480c72491576c048de1218c3c5519399). Can you please try this patch?

**Comment by egorpugin** [comment]
Done.

**Comment by AlexanderSamoilov** [comment]
Successfully tested the fix on my build system. Thank you!
