### ISSUE TITLE
Tesseract and ocrmypdf: High CPU Usage and memory RAM

### ISSUE THREAD

**Issue by jrbrasil** [tesseract-ocr/tesseract#2973]
Hello,
Tesseract and ocrmypdf are consuming a lot of processing and RAM in Alfresco.
Can you tell me, if there is any configuration I need to do?
Alfresco version: 6.1.1
With best regards,
José Roberto

**Comment by stweil** [comment]
I'm afraid nobody here can help you as we don't know that third party software. Please ask the Alfresco people or try to find the answer yourself.
