### ISSUE TITLE
Compile error in file dawg2wordlist.cpp with "ambiguous call to overloaded function"

### ISSUE THREAD

**Issue by Zlinking** [tesseract-ocr/tesseract#2983]
I just clone the latest code to compile in visual studio, but it failed.

I didn't modify any code, so I think maybe some mistake with the code, although I am not very clear with the detail.

Output in visual studio is:

1>tesseract-master\src\training\dawg2wordlist.cpp(65): error C2668: 'tesseract::Dawg::iterate_words': ambiguous call to overloaded function
1>  tesseract-master\src\dict\dawg.h(149): note: could be 'void tesseract::Dawg::iterate_words(const UNICHARSET &,std::function<void (const char *)>) const'
1>  tesseract-master\src\dict\dawg.h(144): note: or       'void tesseract::Dawg::iterate_words(const UNICHARSET &,std::function<void (const WERD_CHOICE *)>) const'
1>  tesseract-master\src\training\dawg2wordlist.cpp(65): note: while trying to match the argument list '(const UNICHARSET, std::_Binder<std::_Unforced,void (__cdecl WordOutputter::* )(const char *),const char *,const std::_Ph<1> &>)'

**Comment by zdenop** [comment]
What does it mean "to compile in visual studio, but it failed"? 
What did you do?
Provide all steps to reproduce problem not only "last" line of error.

**Comment by Zlinking** [comment]
Hi,


I download all code from master branch, get sln file via compiling MAKEFILE, and compile the project with VisulStudio, then I get the error.




















At 2020-05-17 03:10:06, "zdenop" <notifications@github.com> wrote:

What does it mean "to compile in visual studio, but it failed"?
What did you do?
Provide all steps to reproduce problem not only "last" line of error.

**Comment by zdenop** [comment]
I have no clue what do you mean with "get sln file via compiling MAKEFILE" (e.g. there is no MAKEFILE) - this is definitely not [according doc](https://tesseract-ocr.github.io/tessdoc/Compiling-%E2%80%93-GitInstallation.html).
We do not provide support for unofficial/alternative build process, so you have to solve it by yourself, or you can try to get support from tesseract use forum.
