### ISSUE TITLE
Version 3.3.0 can not deploy with Visual Studio 2019

### ISSUE THREAD

**Issue by CHIPSNetwork** [tesseract-ocr/tesseract#2984]
------------------------

### Environment

* **Tesseract Version**: 3.3.0

* **Platform**: Windows 10 32-BIT

### Current Behavior:  Runs fine in debugger.   Deployed application reports:
Failed to find library "liblept1753.dll" for platform x86.

### Suggested Fix:
Problem with manifest or script?

**Comment by stweil** [comment]
That version is no longer supported.

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
