### ISSUE TITLE
How to set multiple languages in c++

### ISSUE THREAD

**Issue by Shaunlipy** [tesseract-ocr/tesseract#2985]
Hi, I'm using c++, I find if I init with `api->Init("../model", "eng+chi_sim");` the program won't yield any ocr result. However, if I init with either `api->Init("../model", "eng");` or `api->Init("../model", "chi_sim");`, both works.

So I'm wondering how should I init with multiple languages?

**Comment by zdenop** [comment]
Have o look how it is done in tesseract executable:

https://github.com/tesseract-ocr/tesseract/blob/395f2315bc9ddd4434e2ad30a178ea3f28226d55/src/tesseract.cpp#L694-L700
