### ISSUE TITLE
Language assert error (lstm_recognizer_->Deserialize(&fp)...line 193)

### ISSUE THREAD

**Issue by ertankucukoglu** [tesseract-ocr/tesseract#2988]
### Environment
* **Tesseract Version**: tesseract 4.00.00alpha
 leptonica-1.74.1
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.5.0) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0
* **Platform**: Windows 10 Pro x64 OS Latest version all updates installed.

### Current Behavior:
```
C:\Program Files (x86)\Tesseract-OCR>tesseract.exe --list-langs
List of available languages (4):
eng
equ
osd
tur

C:\Program Files (x86)\Tesseract-OCR>tesseract.exe c:\Users\Ertan\Desktop\Capture.PNG c:\Users\Ertan\Desktop\Capture.txt -l tur -psm 3
lstm_recognizer_->DeSerialize(&fp):Error:Assert failed:in file ../../../../ccmain/tessedit.cpp, line 193

C:\Program Files (x86)\Tesseract-OCR>tesseract.exe c:\Users\Ertan\Desktop\Capture.PNG c:\Users\Ertan\Desktop\Capture.txt -l eng -psm 3
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica

C:\Program Files (x86)\Tesseract-OCR>tesseract.exe c:\Users\Ertan\Desktop\Capture.PNG c:\Users\Ertan\Desktop\Capture.txt -psm 3
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
```

(Problem is in the Turkish output request, second command from top)

### Expected Behavior:
No errors to be produced as it is listed Turkish in available languages.

**Comment by zdenop** [comment]
Please use the latest code when reporting issue. Using version from 2016 in 2020 is not useful.

**Comment by ertankucukoglu** [comment]
Where can I download latest code compiled for Windows?
I got my copy from here: https://github.com/tesseract-ocr/tessdoc/blob/master/Downloads.md

**Comment by Shreeshrii** [comment]
Use the latest version linked from https://github.com/UB-Mannheim/tesseract/wiki

**Comment by stweil** [comment]
See also issues #1680.
