### ISSUE TITLE
os.environ['OMP_THREAD_LIMIT'] = '1' still leading to usage of mutiple CPU cores

### ISSUE THREAD

**Issue by ShaheenPerveen** [tesseract-ocr/tesseract#2998]
As per tesseract source code, setting 'OMP_THREAD_LIMIT=1' should lead to usage of only single CPU core. Below is the snippet from tesseract.1.asc file from https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc
However, I still see multi core usage even after I set the variable in my python script. Anyone else facing similar issue?
ENVIRONMENT VARIABLES
---------------------
*`TESSDATA_PREFIX`*::
  If the `TESSDATA_PREFIX` is set to a path, then that path is used to
  find the `tessdata` directory with language and script recognition
  models and config files.
  Using <<TESSDATADIR,*--tessdata-dir* 'PATH'>> is the recommended alternative.
*`OMP_THREAD_LIMIT`*::
  If the `tesseract` executable was built with multithreading support,
  it will normally use four CPU cores for the OCR process. While this
  can be faster for a single image, it gives bad performance if the host
  computer provides less than four CPU cores or if OCR is made for many images.
  Only a single CPU core is used with `OMP_THREAD_LIMIT=1`

I have installed Tesseract using conda-forge:
tesseract 4.1.0
leptonica-1.78.0
libgif 5.1.4 : libjpeg 9d : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 1.1.0 : libopenjp2 2.3.1
Found AVX2
Found AVX
Found SSE
I am using pytesseract[python wrapper] to create a solution which is using conda tesseract. I am working on Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux with 7 cores

**Comment by zdenop** [comment]
duplicate #2996

**Comment by ShaheenPerveen** [comment]
This is not a duplicate issue, although it is related to query before and the system specification is same. I tried setting the environment variable and it did not work. Wanted to know what could be the reason

**Comment by stweil** [comment]
This is not an issue at all, but a user question. Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by ShaheenPerveen** [comment]
Okay. Thank you

**Comment by objectisliper** [comment]
So, any answers?

**Comment by ShaheenPerveen** [comment]
> So, any answers?

@objectisliper I was able to achieve it using the following line of command in the beginning on my python script:
`import os
os.environ["OMP_NUM_THREADS"]= '1'
os.environ["OMP_THREAD_LIMIT"] = '1'
os.environ["MKL_NUM_THREADS"] = '1'
os.environ["NUMEXPR_NUM_THREADS"] = '1'
os.environ["OMP_NUM_THREADS"] = '1'
os.environ["PAPERLESS_AVX2_AVAILABLE"]="false"
os.environ["OCR_THREADS"] = '1'`

Please note that you have to ensure that the above code should be present at the beginning of your python script, all other imports and line of codes should follow this for example:
`import os
os.environ["OMP_NUM_THREADS"]= '1'
os.environ["OMP_THREAD_LIMIT"] = '1'
os.environ["MKL_NUM_THREADS"] = '1'
os.environ["NUMEXPR_NUM_THREADS"] = '1'
os.environ["OMP_NUM_THREADS"] = '1'
os.environ["PAPERLESS_AVX2_AVAILABLE"]="false"
os.environ["OCR_THREADS"] = '1'

import pandas as pd
import numpy as np
import json
import requests
import pytesseract`

This should work
