### ISSUE TITLE
tesseract ocr throwing error

### ISSUE THREAD

**Issue by esatheeshkumar** [tesseract-ocr/tesseract#2999]
import pytesseract
from PIL import Image
pytesseract.pytesseract.tesseract_cmd="C:\Program Files\Tesseract-OCR\tesseract.exe"
text = pytesseract.image_to_string(Image.open('C:\Users\Hp\Desktop\Test_Image.jpg'))
print image_to_string(Image.open('C:\Users\Hp\Desktop\Test_Image.jpg'))

Getting the following error
File "C:\Users\Hp\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
exec(compile(f.read(), filename, 'exec'), namespace)

File "C:/Users/Hp/Image_Conversion.py", line 12
print image_to_string(Image.open('C:\Users\Hp\Desktop\Test_Image.jpg'))
^
SyntaxError: invalid syntax

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. You have to reproduce you problem with resent version of tesseract executable.
