### ISSUE TITLE
splitter_.orig_pix():Error:Assert failed:in file tesseractclass.cpp, line 681

### ISSUE THREAD

**Issue by RussiaVk** [tesseract-ocr/tesseract#3002]
------------------------

### Environment

* **Tesseract Version**: tesseract 4.1.1
* **Commit Number**:
* **Platform**: Debian 4.19.98-1+deb10u1

### Expected Behavior:
`splitter_.orig_pix():Error:Assert failed:in file tesseractclass.cpp, line 681
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f14b5ae0bda, pid=31896, tid=32040
#
# JRE version: Java(TM) SE Runtime Environment (14.0+36) (build 14+36-1461)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (14+36-1461, mixed mode, sharing, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# C  [libtesseract.so+0x2a4bda]  ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const+0x17a
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
`

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. You have to reproduce you problem with resent version of tesseract executable.
