### ISSUE TITLE
4.1 version crashes for SIMD instructions for old mac hardware

### ISSUE THREAD

**Issue by sureshyerva87** [tesseract-ocr/tesseract#3003]
0 libtesseract.4.1.0.dylib GlobalParams() + 42
1 libtesseract.4.1.0.dylib __cxx_global_var_init + 13
2 libtesseract.4.1.0.dylib _GLOBAL__sub_I_simddetect.cpp + 9
3 dyld ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 420
4 dyld ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
5 dyld ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 330
6 dyld ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 221
7 dyld ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 134
8 dyld ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 74
9 dyld dyld::runInitializers(ImageLoader*) + 82
10 dyld dlopen + 527
11 libdyld.dylib dlopen + 86

please suggest how to fix it

**Comment by amitdo** [comment]
Does it crash with `tesseract -v`?

>Old mac hardware

Which CPU model?

What's the version of macOS?

**Comment by sureshyerva87** [comment]
MacBook Pro (early 2011 or late 2011)

**Comment by sureshyerva87** [comment]
Also, on following
  Model Name:	MacBook Air
  Model Identifier:	MacBookAir3,2
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	1.86 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache:	6 MB
  Memory:	4 GB

**Comment by hglee** [comment]
MBP mid 2010 (Core 2 Duo)
macOS High Sierra

No crash with homebrew binary: both v4.1.0, v4.1.1

Would you try to downgrade your OS to supported one?

Because Catalina does not supports MBP 2011.

**Comment by amitdo** [comment]
@sureshyerva87, 

First you said: 

>Macbook Pro 9.1

but after that, you said:

>Model Name: MacBook Air
>Model Identifier: MacBookAir3,2

You should decide...

MacbookAir3.2 is not supported by Catalina.

* https://support.apple.com/en-il/HT210222
* https://support.apple.com/en-il/HT201862
* https://support.apple.com/en-il/HT201300

**Comment by amitdo** [comment]
No feedback from the OP.
