### ISSUE TITLE
 JVM were crashed after run tesseract  few times in debian

### ISSUE THREAD

**Issue by RussiaVk** [tesseract-ocr/tesseract#3004]
**I installed tesseract 4.1.1 on my servers (Debian 4.19.98-1).
JVM aways crashed when execute tesseract  in my java project.
These exception is a part of tomcat log file(hs_err_pid20064):**

`# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fccab39343f, pid=20064, tid=20176
#
# JRE version: Java(TM) SE Runtime Environment (14.0+36) (build 14+36-1461)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (14+36-1461, mixed mode, sharing, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# C  [libtesseract.so+0xd643f]  tesseract::Tesseract::recog_all_words(PAGE_RES*, ETEXT_DESC*, TBOX const*, char const*, int)+0x39f
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Djava.util.logging.config.file=/etc/apache-tomcat-9.0.30/conf/logging.properties -Xms128m -Xmx512m -Xss1024K -XX:MaxNewSize=256m -Djava.awt.headless=true --enable-preview -Djava.security.egd=file:/dev/./urandom -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8 -Xms128m -Xmx512m -Xss1024K -XX:MaxNewSize=256m -Djava.awt.headless=true --enable-preview -Djava.security.egd=file:/dev/./urandom -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -Dcatalina.base=/etc/apache-tomcat-9.0.30 -Dcatalina.home=/etc/apache-tomcat-9.0.30 -Djava.io.tmpdir=/etc/apache-tomcat-9.0.30/temp org.apache.catalina.startup.Bootstrap start

Host: Virtual CPU 523cbcdd6ca4, 1 cores, 987M, Debian GNU/Linux 10 (buster)
Time: Thu Jun  4 03:41:57 2020 UTC elapsed time: 811 seconds (0d 0h 13m 31s)

---------------  T H R E A D  ---------------

Current thread (0x00007fccc0555000):  JavaThread "pool-2-thread-6" [_thread_in_native, id=20176, stack(0x00007fccb0ed5000,0x00007fccb0fd6000)]

Stack: [0x00007fccb0ed5000,0x00007fccb0fd6000],  sp=0x00007fccb0fd2f90,  free space=1015k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libtesseract.so+0xd643f]  tesseract::Tesseract::recog_all_words(PAGE_RES*, ETEXT_DESC*, TBOX const*, char const*, int)+0x39f

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.invokePointer(Lcom/sun/jna/Function;JI[Ljava/lang/Object;)J+0
J 8045 c1 com.sun.jna.Function.invoke([Ljava/lang/Object;Ljava/lang/Class;ZI)Ljava/lang/Object; (769 bytes) @ 0x00007fccd19f1f54 [0x00007fccd19f11e0+0x0000000000000d74]
J 6432 c1 com.sun.jna.Function.invoke(Ljava/lang/reflect/Method;[Ljava/lang/Class;Ljava/lang/Class;[Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object; (548 bytes) @ 0x00007fccd17ee004 [0x00007fccd17ec9a0+0x0000000000001664]
J 7943 c1 com.sun.jna.Library$Handler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object; (394 bytes) @ 0x00007fccd19e4464 [0x00007fccd19e0e80+0x00000000000035e4]
j  com.sun.proxy.$Proxy13.TessBaseAPIGetUTF8Text(Lnet/sourceforge/tess4j/ITessAPI$TessBaseAPI;)Lcom/sun/jna/Pointer;+16
j  net.sourceforge.tess4j.Tesseract.getOCRText(Ljava/lang/String;I)Ljava/lang/String;+269
j  net.sourceforge.tess4j.Tesseract.doOCR(Ljavax/imageio/IIOImage;Ljava/lang/String;Ljava/awt/Rectangle;I)Ljava/lang/String;+18
j  net.sourceforge.tess4j.Tesseract.doOCR(Ljava/io/File;Ljava/awt/Rectangle;)Ljava/lang/String;+126
j  net.sourceforge.tess4j.Tesseract.doOCR(Ljava/io/File;)Ljava/lang/String;+3
j  russiavk.module.ocr.api.TesseractExample.OCRByLocal(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;+39
j  russiavk.module.ocr.base.OCRBase.doOCR(ILjava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;+38
j  russiavk.module.ocr.base.OCRUtil.lambda$0(Lrussiavk/module/ocr/base/OCRBase;)Ljava/lang/String;+127
j  russiavk.module.ocr.base.OCRUtil$$Lambda$230.operate()Ljava/lang/Object;+8
J 8040 c1 com.github.johnsonmoon.util.Retry$$Lambda$227.call()Ljava/lang/Object; (12 bytes) @ 0x00007fccd106ae2c [0x00007fccd106acc0+0x000000000000016c]
J 7611 c1 java.util.concurrent.FutureTask.run()V java.base@14 (123 bytes) @ 0x00007fccd158fbcc [0x00007fccd158f500+0x00000000000006cc]
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+92 java.base@14
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5 java.base@14
j  java.lang.Thread.run()V+11 java.base@14
v  ~StubRoutines::call_stub`

**blow is my java project code:**

`import net.sourceforge.tess4j.*;
import net.sourceforge.tess4j.util.LoadLibs;
import russiavk.module.ocr.base.OCRBase;

public class TesseractExample extends OCRBase {
	static ITesseract instance = new Tesseract(); // JNA Interface Mapping
	// ITesseract instance = new Tesseract1(); // JNA Direct Mapping

//	public TesseractExample() {
//		System.setProperty("jna.library.path",
//				"32".equals(System.getProperty("sun.arch.data.model")) ? "lib/win32-x86" : "lib/win32-x86-64");

//	}

	@Override
	public TesseractExample initAccountData(String... args) {
		File tessDataFolder = LoadLibs.extractTessResources("tessdata"); // Maven build bundles English data
		instance.setDatapath(tessDataFolder.getPath());
		instance.setLanguage(args.length == 0 ? "eng" : args[0]);
		instance.setTessVariable("user_defined_dpi", args.length < 2 ? "300" : args[1]);
		return this;
	}

	@Override
	public String OCRByLocal(String filePath, Object options) {
		if (options instanceof String[]) {
			initAccountData((String[]) options);
		} else {
			initAccountData();
		}

		try {
			return instance.doOCR(new File(filePath));
		} catch (TesseractException e) {
			return null;
		}
	}
}`

**where the problem is ???**

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. You have to reproduce you problem with resent version of tesseract executable.

**Comment by pavelorehov** [comment]
Have same issue on Ubuntu with tesseract 4.0.0-beta.1 and tess4j 4.5.5

**Comment by RussiaVk** [comment]
> Have same issue on Ubuntu with tesseract 4.0.0-beta.1 and tess4j 4.5.5

Fixed after set "synchronized" keyword in method

**Comment by ken4ward** [comment]
@RussiaVk how did you fix this issue, or how did you add a synchronized keyword. Please help. I have been on this for over a week
