### ISSUE TITLE
How can I use lang=xxx on window powershell 7.0.1

### ISSUE THREAD

**Issue by huhuang03** [tesseract-ocr/tesseract#3005]
### Environment

* **Tesseract Version**: 
v5.0.0-alpha 20200328
* **Commit Number**: 
No, install from github relase.
* **Platform**: 
Windows 10 64-bit run in powershell 7.0.1
### Current Behavior:
I use the command `text = pytesseract.image_to_string(img, lang="chi_sim", config=r'--oem 3')`. The error msg is:

pytesseract.pytesseract.TesseractError: (1, "Error: Tesseract (legacy) engine requested, but components are not present in D:\\Program Files\\Tesseract-OCR/tessdata/chi_sim.traineddata!! Failed loading language 'chi_sim' Tesseract couldn't load any languages! Could not initialize tesseract.")

### Expected Behavior:
Please notice the search path `D:\\Program Files\\Tesseract-OCR/tessdata/chi_sim.traineddata!!`, I think it use wrong `File.sperator`.
### Suggested Fix:
I don't know how to fix, but how to config to use the right `File.sperator`. Maybe I don't need to look in to the source code.

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by huhuang03** [comment]
But I think it's a bug, because I run `tesseract --list-langs`, it output `chi_sim eng osd`. Why can't find chis_sim.traineddata, strange.

**Comment by huhuang03** [comment]
Ok, I'm sorry. After read the source, I find out it's chi_sim.triandata issue which only contains LSTM data.
