### ISSUE TITLE
Method image_to_osd

### ISSUE THREAD

**Issue by Prabh95** [tesseract-ocr/tesseract#3007]
I have been using the the method **pytesseract.image_to_osd(img)** for detecting **orientation angles** of my images. It works fine for images rotated at angles 90,180, 270 and for upright(0deg) images. But if I pass an image lets say rotated at 45deg then I get this following error:

TesseractError: (1, 'Tesseract Open Source OCR Engine v5.0.0-alpha.20200328 with Leptonica Warning: Invalid resolution 0 dpi. Using 70 instead. Estimating resolution as 166 Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')

**Note:** The image has enough characters/text for it to detect the orientation angle. The function is able to correctly detect the angle when the same image is rotated at 90.

**Can I use this function for angles other than 0, 90, 270, 180?**

**Comment by amitdo** [comment]
The OSD module is design to cope with pages rotated at angles 90,180, 270 degrees.

Tesseract can cope with a small skew of a few degrees. skew of 45 degrees is too much for it, and it will fail to detect correctly all/most characters.
