### ISSUE TITLE
Tesseract read nothing in tif files

### ISSUE THREAD

**Issue by infoboadella** [tesseract-ocr/tesseract#3008]
I use Tesseract in OpenKM to read tif documents, but when execute reads nothing.

![image](https://user-images.githubusercontent.com/60875735/84025282-9135ec80-a98b-11ea-88ae-92924a19524d.png)
![image](https://user-images.githubusercontent.com/60875735/84025300-98f59100-a98b-11ea-80b9-6a9f50e6405e.png)

Someone have any idea?
Thanks

**Comment by zdenop** [comment]
1. Please respect guidelines for posting issue: use tesseract user forum for asking questions/support. 
2. From details you provided nobody is able to reproduce problem. Nobody can help you if you do not provide testing image.

**Comment by infoboadella** [comment]
Good morning, I think this is a bug, because from old version of tesseract works fine!
I attach I file to test.
Please if this comment not write to correct site please respon me.
Thanks.
[test.zip](https://github.com/tesseract-ocr/tesseract/files/4757836/test.zip)

**Comment by zdenop** [comment]
1. Tesseract is using for opening image leptonica
2. I used `leptonica-1.80.0 (May 16 2020, 13:24:45) [MSC v.1916 LIB Release x64]`, and the message is: `Error in pixReadFromTiffStream: old style jpeg format is not supported`

Solution is: use supported input image.
