### ISSUE TITLE
Deserialized Header Failed Mac OS X

### ISSUE THREAD

**Issue by MichaelLLi** [tesseract-ocr/tesseract#3012]
### Environment

* **Tesseract Version**: 4.1.1
* **Commit Number**: 75103040c94ffd7fe5e4e3dfce0a7e67a8420849
* **Platform**: Mac OS X 10.14

### Current Behavior:

So I installed 4.1.1 along with the training tools from source and decided to try out the whole training process. I downloaded a sample TIFF file from the internet (CCITT_1.tiff) and then created the box/tiff file pair as:

`tesseract CCITT_1.TIFF CCITT lstmbox`

This gave:

> Tesseract Open Source OCR Engine v4.1.1 with Leptonica
> Page 1

With no error. 

Then I created the lstmf files as:

`tesseract CCITT_1.TIFF lstmf/valid1 lstm.train`

And it gave me the same as above with no error. Finally, I ran a dummy training script with just this one picture:

lstmtraining --model_output models/test --continue_from models/eng.lstm --traineddata data/eng-best.traineddata --train_listfile dataset/annotated/training_files.txt --max_iterations 100

And I get:

```
Loaded file models/eng.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Continuing from models/eng.lstm
Deserialize header failed: /Users/Mlli/Documents/GitHub/LineageEyeMachineLearning/ocr/lstmf/valid1.lstmf
Load of page 0 failed!
Load of images failed!!
```
I have made sure that the files do actually exist at the location, and the eng-best.traineddata is the LSTM only one. What could be wrong here? Thanks!

**Comment by MichaelLLi** [comment]
[Archive.zip](https://github.com/tesseract-ocr/tesseract/files/4757064/Archive.zip)

The relevant files are attached here.

**Comment by Shreeshrii** [comment]
Is the file there at the path specified. What's the output of 

```
ls -l /Users/Mlli/Documents/GitHub/LineageEyeMachineLearning/ocr/lstmf/valid1.lstmf
```

In the zipfile that you have attached, the lstmf file is in the main directory (not in subdirectory called lstmf).

**Comment by amitdo** [comment]
No response from OP.
