### ISSUE TITLE
System.AccesViolationException

### ISSUE THREAD

**Issue by nouxuha** [tesseract-ocr/tesseract#3015]
Hello,
I am using tesseract v3.2.0-alpha2.
When I processed a file using tesseract engine and saving the output using IResultRenderer.AddPage All thing became good and ran successfully, but when I used multi-Task, a system access violation exception was firing ! 
Note that I created at each task an instance of the engine.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. You have to reproduce you problem with resent version of tesseract executable.
