### ISSUE TITLE
5.0&4.0  SetVariable invalid

### ISSUE THREAD

**Issue by Abraverman666** [tesseract-ocr/tesseract#3017]
5.0&4.0  SetVariable invalid
5.0和4.0版本中  SetVariable无效 也没有找到官方文档  我是用的c++调用接口  想实现白名单tessedit_char_whitelist  but  this setting is  invalid  Please help me 请问有解决办法吗

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Use English, read forum/issue tracker etc in advance.
