### ISSUE TITLE
An unknown error occurred in the cntraining command

### ISSUE THREAD

**Issue by lonely2099** [tesseract-ocr/tesseract#3018]
* **Tesseract Version**:  v5.0.0-alpha.20200328

* **Platform**: win10 64-bit

![image](https://user-images.githubusercontent.com/59019164/84691588-ffc00f00-af76-11ea-9a77-e8278bf831fb.png)

exp:
tesseract chi.test.exp0.tif chi.test.exp0 -l chi_sim --psm 6 batch.nochop makebox
echo test 0 0 0 0 0 >font_properties
tesseract chi.test.exp0.tif chi.test.exp0 nobatch box.train
unicharset_extractor chi.test.exp0.box
shapeclustering -F font_properties -U unicharset -O chi.test.exp0.tr
mftraining -F font_properties -U unicharset -O chi.unicharset chi.test.exp0.tr
cntraining chi.test.exp0.tr

**Comment by amitdo** [comment]
>shapeclustering -F font_properties -U unicharset -O chi.test.exp0.tr

https://tesseract-ocr.github.io/tessdoc/Training-Tesseract-3.03%E2%80%933.05.html#clustering

>shapeclustering **should not normally be used except for the Indic languages**.

**Comment by amitdo** [comment]
No Response from the OP.
