### ISSUE TITLE
Segmentation fault while trying to run orientation with arabic script

### ISSUE THREAD

**Issue by Omnipresent** [tesseract-ocr/tesseract#302]
On Tesseract 3.04.00 I get a segmentation fault while trying to get the orientation information for the image with arabic text.

Sample Image: http://i.imgur.com/DdLr39z.jpg

Tesseract Version:

```
$ tesseract --version
tesseract 3.04.00
 leptonica-1.72
  libjpeg 8d : libpng 1.6.18 : libtiff 4.0.6 : zlib 1.2.5
```

Ara langs in TESSDATA:

```
$ ls ara*
ara.cube.bigrams   ara.cube.lm        ara.cube.params    ara.cube.word-freq 
ara.cube.fold      ara.cube.nn        ara.cube.size      ara.traineddata
```

Segmentation Fault:

```
$ tesseract arabic_4.jpg stdout -psm 0 -l ara
[1]    3721 segmentation fault  tesseract ~/Downloads/arabic_4.jpg stdout -psm 0 -l ara
```

This does not happen when I pass the language as `eng` instead of  `ara` but then ofcourse the results and confidence factor are extremely low. 

```
$ tesseract ~/Downloads/arabic_4.jpg stdout -psm 0 -l eng
Orientation: 0
Orientation in degrees: 0
Orientation confidence: 4.00
Script: 1
Script confidence: 8.08
```

**Comment by amitdo** [comment]
Try this:
`tesseract arabic_4.jpg stdout -psm 0 -l osd`

You will need the `osd.traineddata`.

FYI, Tesseract 3.04.01 will also output the **name** of the detected script instead of useless script number.

**Comment by Omnipresent** [comment]
@amitdo Thanks, that works. On the same topic, Is there a way to get the same information (script, and script confidence) from the [capi](https://github.com/tesseract-ocr/tesseract/blob/master/api/capi.cpp) ?
