### ISSUE TITLE
Tesseract doesn't recognize "0" and "6" in this image

### ISSUE THREAD

**Issue by dream811** [tesseract-ocr/tesseract#3020]
![image](https://user-images.githubusercontent.com/45660446/84747533-f8861900-afe9-11ea-820e-43b1cece51c8.png)

image
0->2
6->5
so my result is "527554"
How can I resolve this issue?
Is there any option to change font?
![image](https://user-images.githubusercontent.com/45660446/84747664-1fdce600-afea-11ea-8feb-424b6cc17777.png)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
