### ISSUE TITLE
lstm_recognizer_->DeSerialize(&fp):Error:Assert failed:in file ../../../../ccmain/tessedit.cpp, line 193

### ISSUE THREAD

**Issue by UBISOFT-1** [tesseract-ocr/tesseract#3024]
I have Installed Tesseract Properly, and it is not working as intended, this is strange, I saw another issue like this that was closed but I have the exact same problem, feel free to use my computer remotely as you could not reproduce it in your system as you said!
Any help will be appreciated! 
------------------------

### Environment

* **Tesseract Version**: 4.0.0 dev
* **Commit Number**: 1
* **Platform**: Windows 10 64-bit Build 1909

### Current Behavior:
PS C:\Users\ahmad\Desktop> tesseract Bravo.jpeg ../Wtest01.txt -l urd
lstm_recognizer_->DeSerialize(&fp):Error:Assert failed:in file ../../../../ccmain/tessedit.cpp, line 193
### Expected Behavior:
Give the Output
### Suggested Fix:
Fix the Error!

# Edit
When I use English the Output is Fine, is it that my other Languages are Broken

**Comment by stweil** [comment]
How did you install urd.traineddata?

**Comment by stweil** [comment]
Please use a supported version of Tesseract. 4.0.0 dev is too old.

**Comment by stweil** [comment]
See also issues #1680.

**Comment by UBISOFT-1** [comment]
Where is 4.1.1 for Windows setup.exe
