### ISSUE TITLE
ImageData::PreScale gives unnecessary errors if pixScale fails

### ISSUE THREAD

**Issue by juliangilbey** [tesseract-ocr/tesseract#3025]
### Current Behavior:

If for whatever reason, `pixScale` fails in the `ImageData::PreScale` function in `src/ccstruct/imagedata.cpp`, it gives an error message after checking `if (pix == nullptr)`.  But if that is the case, then the next lines, calling `pixGetWidth(pix)` and `pixGetHeight(pix)` also give error messages.

### Suggested Fix:

Perhaps immediately `return nullptr` if `pixScale` fails?  I'm not sure what would be best here.  There are still further error messages which will appear here in this case, in any event.

**Comment by zdenop** [comment]
Can you give example/test case how to trigger this problem?

**Comment by juliangilbey** [comment]
Well, I sort of can and I sort of can't.  I have been delving into the code quite deeply, and have written a major patch to the 4.1.1 version to handle low-resolution images (though I'm still not convinced whether it's worth the effort).  There's a case I'd overlooked in my code, so at this point, the pixScale occasionally failed (or actually what I'd replaced the pixScale with).  And this therefore set pix to nullptr, so I got error messages from the next two lines of code.  Now, in the real tesseract code, it is highly unlikely for pixScale to fail, so it is highly unlikely that this bug will show.  But there is already a test for pix == nullptr a couple of lines later anyway; my thought was that it doesn't seem worth generating the extra lines of error messages (about pixGetWidth/Height) in this case.  It is really minor, though!

**Comment by zdenop** [comment]
ok

**Comment by stweil** [comment]
https://github.com/tesseract-ocr/tesseract/issues/590#issuecomment-423772964 mentions the same problem.

**Comment by stweil** [comment]
`pixScale` fails if the scale factor reduces the image size and the resulting image would be less than one pixel high or wide.
