### ISSUE TITLE
Unable to detect simple math equations using pytessract

### ISSUE THREAD

**Issue by NavpreetDevpuri** [tesseract-ocr/tesseract#3028]
Similar to https://github.com/tesseract-ocr/tesseract/issues/2204 and https://github.com/tesseract-ocr/tesseract/issues/1890
### Environment

* **Tesseract Version**: tesseract v5.0.0-alpha.20200328
* **Platform**: Windows 10 64-bit

### Current Behavior:
I download latest traineddata files from [tessdata](https://github.com/tesseract-ocr/tessdata)
I tried following code 
```python 
img = cv2.imread(file_path)
hocr_data = pytesseract.image_to_pdf_or_hocr(img, extension='hocr', lang="eng+equ")
with open("test.html", 'w+b') as f:
     f.write(hocr_data)
```
**Input file**
![006](https://user-images.githubusercontent.com/30471072/85078312-c8a16600-b1e1-11ea-8249-c09f7cb155d6.jpg)

**Output looks something like**
![chrome_k33xFY87or](https://user-images.githubusercontent.com/30471072/85078466-25048580-b1e2-11ea-9cad-6fbbf7edfcf4.png)

### Expected Behavior:
It should detect those equations.
### Suggested Fix:
Use [LaTaX](https://www.latex-project.org/) as a new language to detecting math equations.
Then we can easily put those LaTax math equations into hocr file as mentioned at this [link](https://www.codecogs.com/latex/integration/htmlequations.php#:~:text=Add%20attribute%20lang%3D%22latex%22%20to%20tags&text=creates%3A,same%20line%20at%20the%20text.)

**Comment by zdenop** [comment]
tesseract is not suitable for this king of input text.

**Comment by NavpreetDevpuri** [comment]
@zdenop 
Why not ?
Why not improve tesseract for that kind of text detections ? this is also a part of text detection.

**Comment by zdenop** [comment]
Sure you can. Just send a patch and I will merge it.

**Comment by NavpreetDevpuri** [comment]
can you help me with this 
How ? May be it need some testing data for training ? 
And how to train it ?
Sorry but i am new with tesseract.
Do you have any better approach ?

**Comment by NavpreetDevpuri** [comment]
i found [that](https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00.html)
Let me try !

**Comment by zdenop** [comment]
No training will not help you. There are dedicated solution for such task e.g. 
https://mathpix.com/

**Comment by NavpreetDevpuri** [comment]
> No training will not help you. There are dedicated solution for such task e.g.
> https://mathpix.com/


yes, i looked at it but its not free and open source  

Now i am finding more solutions i got few as far now 
http://www.inftyproject.org/en/software.html
https://github.com/UW-COSMOS/latex-ocr
https://github.com/blaisewang/img2latex-mathpix

Now i am testing those

**Comment by NavpreetDevpuri** [comment]
Leaving it for now may be i will try it later

But i think its much more better if tesseract should have LaTax as an other language option for reseach documents or any kind of documents that have math equations.

**Comment by roostinghawk** [comment]
So until now you still couldn't find solution for detecting math signal?

**Comment by Breakfastisready** [comment]
Hello!

Have you found any alternatives yet @NavpreetDevpuri ? 

I am also interested.

**Comment by varunsawhney8** [comment]
Anyone Found Something for this problem. Please let me know.

**Comment by gulabsagevadiya** [comment]
Anyone has found any solution for this need?
I am also looking for simple math equations to LaTeX

**Comment by daianaszwimer** [comment]
same here, sad to see that there are no answers to this question :(

**Comment by giovannav** [comment]
I added this configuration line of code to the function:
```
myconfig = r"--psm 11 --oem 3"
text = pytesseract.image_to_string(cropped_img_loc, config=myconfig, lang='eng')
```
It doesn't work perfectly, but it does catch most of the most common math symbols.

**Comment by adzcai** [comment]
Any updates? I'm also looking for a tool to identify equations and replace them with LaTeX. It would be enough just to get bounding boxes; then I can crop those and feed them into a different tool.

I noticed [equationdetect.cpp](https://github.com/tesseract-ocr/tesseract/blob/main/src/ccmain/equationdetect.cpp). Is there a convenient way to use that to extract bounding boxes?

**Comment by OskarGruberPR** [comment]
... same question :)

**Comment by Kiranism** [comment]
yo! any workaround

**Comment by Shadow-Alex** [comment]
I've long investigated this area, it's quite hard and few people are working on this, you can always screen through ICDAR papers for any luck :)

**Comment by Hadar933** [comment]
still no workaround huh?

**Comment by Shadow-Alex** [comment]
Try this: https://github.com/lukas-blecher/LaTeX-OCR.

For a full ocr version, try this : https://github.com/breezedeus/Pix2Text

**Comment by BurstingBrain** [comment]
Can't you add training data [equ.traineddata](https://github.com/tesseract-ocr/tessdata_fast/blob/main/equ.traineddata) like this one made for math equation to pytesseract?
