### ISSUE TITLE
Got error after excuting "sw build".

### ISSUE THREAD

**Issue by hereis00** [tesseract-ocr/tesseract#3029]
MINGW64 /d/git/tesseract-master/build
$ sw build ..
Exception in file D:/dev/cppan2/client2/src/sw/driver/compiler/detect.cpp:509, function detectWindowsClang: Cannot get clang-cl installed dir (InstalledDir)
Another way:
$ sw build org.sw.demo.google.tesseract.tesseract-master
Downloading: [org.sw.demo.google.tesseract.tesseract-master]/[Source Archive]
Unpacking  : [org.sw.demo.google.tesseract.tesseract-master]/[Source Archive]
Exception in file D:/dev/cppan2/client2/src/sw/driver/compiler/detect.cpp:509, function detectWindowsClang: Cannot get clang-cl installed dir (InstalledDir)

**Comment by amitdo** [comment]
CC: @egorpugin

**Comment by egorpugin** [comment]
Hi,

Can you run `clang-cl --version` in that mingw console and post output here?

**Comment by hereis00** [comment]
The console is "Git bash":
$ clang-cl --version
clang-cl.exe: warning: unknown argument ignored in clang-cl: '--version' [-Wunknown-argument]
clang-cl.exe: error: no input files

**Comment by hereis00** [comment]
It seems like something was wrong with my clang version, then I install the lastest clang, it works well.
Now, I have another question, where are the generated binaries after excuting "sw build org.sw.demo.google.tesseract.tesseract-master", I can't find any one. I got messages like these:
`[1377/1385]` [org.sw.demo.gnu.nettle.nettle-3.5.1].lib
[1382/1385] [org.sw.demo.libarchive.libarchive-3.4.3].dll
[1383/1385] generate: "C:/Users/Lin/.sw/storage/pkg/1d/13/e4d8/obj/bld/817479/bdp/.sw.symbols.def"
[1384/1385] [org.sw.demo.google.tesseract.libtesseract-master].dll
[1385/1385] [org.sw.demo.google.tesseract.tesseract-master].exe
`
but I don't know where are they("*.lib", "*.dll", "*.exe").

**Comment by egorpugin** [comment]
Those files are in sw storage. Run `sw open org.sw.demo.google.tesseract.libtesseract-master`, go to the `obj` dir and in some subdirs you'll find dll for libtess.
When you build tesseract locally like `sw build` or `sw build ..` target files will be in `.sw/out/some config`.

**Comment by hereis00** [comment]
Got it! Thanks for your time and your patience!

**Comment by DwangDNguyen** [comment]
I have error Exception in file D:/dev/cppan2/client2/src/sw/driver/compiler/detect.cpp:1235, function addSettingsAndSetPrograms: No suitable compilers found.
Please, install one first.
Help me!! Thanks

**Comment by egorpugin** [comment]
Hi, 

Install VS2022 with C++ components.
