### ISSUE TITLE
How to set PSM model in python demo script of tesseract-ocr 3.02 c-api?

### ISSUE THREAD

**Issue by Chrisdy** [tesseract-ocr/tesseract#303]
I am trying to use the tesseract-c_api-demo.py script as follows:
##################################################
import os
import sys
import ctypes

# Demo variables
lang = "eng"
filename = "../phototest.tif"
libpath = "/usr/local/lib64/"
libpath_w = "../vs2010/DLL_Release/"
TESSDATA_PREFIX = os.environ.get('TESSDATA_PREFIX')
if not TESSDATA_PREFIX:
    TESSDATA_PREFIX = "../"
libname = libpath + "libtesseract.so.3.0.2"
tesseract = ctypes.cdll.LoadLibrary(libname)

tesseract.TessVersion.restype = ctypes.c_char_p
tesseract_version = tesseract.TessVersion()[:4]

api = tesseract.TessBaseAPICreate()
rc = tesseract.TessBaseAPIInit3(api, TESSDATA_PREFIX, lang);

text_out = tesseract.TessBaseAPIProcessPages(api, filename, None , 0);
result_text = ctypes.string_at(text_out)
print result_text
##################################################

How can I set the PSM_Model for tesseract?

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support
