### ISSUE TITLE
linux How to install tesseract

### ISSUE THREAD

**Issue by Yuri2** [tesseract-ocr/tesseract#3038]
leptonica-1.74.4 
tesseract5.0.0

report errors：
configure.ac:322: warning: LTSUGAR_VERSION is m4_require'd but not m4_defun'd
m4/libtool.m4:61: LT_INIT is expanded from...
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:322: the top level
configure.ac:322: warning: LTVERSION_VERSION is m4_require'd but not m4_defun'd
m4/libtool.m4:61: LT_INIT is expanded from...
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:322: the top level
configure.ac:322: warning: LTOBSOLETE_VERSION is m4_require'd but not m4_defun'd
m4/libtool.m4:61: LT_INIT is expanded from...
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:322: the top level
Running automake --add-missing --copy
configure.ac:322: warning: LTSUGAR_VERSION is m4_require'd but not m4_defun'd
m4/libtool.m4:61: LT_INIT is expanded from...
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:322: the top level
configure.ac:322: warning: LTVERSION_VERSION is m4_require'd but not m4_defun'd
m4/libtool.m4:61: LT_INIT is expanded from...
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:322: the top level
configure.ac:322: warning: LTOBSOLETE_VERSION is m4_require'd but not m4_defun'd
m4/libtool.m4:61: LT_INIT is expanded from...
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:322: the top level
Running autoconf
configure.ac:322: warning: LTSUGAR_VERSION is m4_require'd but not m4_defun'd
m4/libtool.m4:61: LT_INIT is expanded from...
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:322: the top level
configure.ac:322: warning: LTVERSION_VERSION is m4_require'd but not m4_defun'd
m4/libtool.m4:61: LT_INIT is expanded from...
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:322: the top level
configure.ac:322: warning: LTOBSOLETE_VERSION is m4_require'd but not m4_defun'd
m4/libtool.m4:61: LT_INIT is expanded from...
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:322: the top level
configure:5124: error: possibly undefined macro: m4_ifval
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

  Something went wrong, bailing out!

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Problem is not in tesseract, but in system you select and maybe with your experience.

**Comment by Yuri2** [comment]
Thank you for your reply

Here are my actions：

git clone https://github.com/tesseract-ocr/tesseract.git
ls 
anaconda-ks.cfg  leptonica-1.78.0         original-ks.cfg
install.sh       leptonica-1.78.0.tar.gz  tesseract
tesseract --version
-bash: tesseract: command not found

There's a problem there？Or how to configure Linux？
