### ISSUE TITLE
I want to train my own 'eng.cube.nn' model for cube engine

### ISSUE THREAD

**Issue by SunAriesCN** [tesseract-ocr/tesseract#304]
I want to train my own eng.cube.nn for cube engine, but I cannot find any idea from the trainning directory. What can I do for it?

**Comment by amitdo** [comment]
There is no documented way to train 'Cube', so you can't do it.

**Comment by zdenop** [comment]
Cube training is not supported and cube should be removed in future

**Comment by SunAriesCN** [comment]
But I need to train my cube for my research, have any other way, even not in tesseract, to train the .cube.nn file? I'm so curious about where's the original cube model from, could any one give me some advises about it?

**Comment by jimregan** [comment]
The code for training the neural network was never released, so nobody can help you with this. Sorry.

**Comment by sbarratt** [comment]
What's the best way for one to insert their own single-character recognition algorithm into the overall Tessaract system?
