### ISSUE TITLE
c++ using tesseract api built with visual studio 2019 on windows 10 crashes on windows server 2012

### ISSUE THREAD

**Issue by jonaumann** [tesseract-ocr/tesseract#3048]
Im am using the tesseract api (version 4) in a c++ program and build it using visual studio 2019 on windows 10. The executable runs fine on other windows 10 machines, but on windows server 2012 it crashes. The c++ runtime is correctly installed, other c++ programs work fine.

**Comment by stweil** [comment]
If your Windows server is an older machine which does not support AVX, this might be a duplicate of issue #3044.

**Comment by jonaumann** [comment]
yes, might be the same issue as #3044.
How can I fix this? Can I just swap the tesseract dlls with the ones from
the UB Mannheim binary build for windows? In the related issue it was said
that this version does not have the problem?

Am Mo., 29. Juni 2020 um 19:09 Uhr schrieb Stefan Weil <
notifications@github.com>:

**Comment by stweil** [comment]
I'm afraid that won't work, because UB Mannheim uses the GNU compiler, so the generated DLL is not compatible with MS Visual Studio code. The right solution would require fixing cmake builds and do a fresh build with the MS compiler.

**Comment by jonaumann** [comment]
Ok. How do I change the build? I was using vcpkg tool to install tesseract
dlls. How can I proceed?

Stefan Weil <notifications@github.com> schrieb am Mo., 29. Juni 2020, 20:58:

**Comment by stweil** [comment]
@jonaumann, please try the latest Tesseract code and report your result. Hopefully it has fixed this problem.

**Comment by jonaumann** [comment]
I don't have the expierence to build tesseract from scratch on windows. But thanks for your efforts! Hopefully Microsoft in the future will offer version 5 for vcpkg.
In the meanwhile I use the tesseract.exe from UB Mannheim that works on windows server 2012.
