### ISSUE TITLE
14 read as I4 if inside a long word 

### ISSUE THREAD

**Issue by rolfmertig** [tesseract-ocr/tesseract#305]
In Version v3.04.00 I get a strange behaviour if a non-dictionary word has a certain 
ratio of digits to numbers in it and if there is a non-leading capital "I" involved.
The attached bad.jpg file (same with tif files) should get ocr-ed to NCOR140123020064000000000 and not NCORI4012302006400000000.
If I cut off the last "0" ( good.jpg ) then all is fine.
I played with all kind of options like conflict_set_I_l_1 and rej_1Il_trust_rej_1Il_trust_permuter_type_type and more, but had no success.
I think that it is a bug if the length of the word affects the interpretation of "I".
Or which special setting of the parameters do I have to choose to get this working?

```
rolfm@~/ocr> tesseract -psm 7 good.jpg good ; cat good.txt
Tesseract Open Source OCR Engine v3.04.00 with Leptonica
NCOR14012302006400000000

rolfm@~/ocr> tesseract -psm 7 bad.jpg bad ; cat bad.txt
Tesseract Open Source OCR Engine v3.04.00 with Leptonica
NCORI40123020064000000000
```

bad.jpg :
![bad](https://cloud.githubusercontent.com/assets/1440116/14764199/a3e7cacc-09af-11e6-8a6c-fd881f01b4c8.jpg)
good.jpg : 
![good](https://cloud.githubusercontent.com/assets/1440116/14764200/a7b4288a-09af-11e6-86db-2c58ebe82f37.jpg)

**Comment by amitdo** [comment]
Please see:
https://github.com/tesseract-ocr/tesseract#support

**Comment by rolfmertig** [comment]
Can you be more specific? 
The only "fix" I found was to add " -l deu " and then bad.jpg is read correctly. 
But how can I get this behaviour for " -l eng" ? Turning off dictionaries as suggested in the wiki has not effect.

**Comment by amitdo** [comment]
What I meant was that I think this kind of problem / question should be sent to the mailing list.

**Comment by rolfmertig** [comment]
But isn't it clearly a bug? ocropus-rpred has no problem with bad.jpg.

**Comment by amitdo** [comment]
>But isn't it clearly a bug? ocropus-rpred has no problem with bad.jpg.

There no OCR engine that is 100% accurate. The fact that OCR engine 'A' is more accurate (for a specific input and/or as a whole) than OCR engine 'B' does not make by itself the 'B' a buggy software.

To be fair, I think in this specific case it could be a bug...

**Comment by tfmorris** [comment]
There may be a bug (or possibility for improvement) here, but the general statement

> I think that it is a bug if the length of the word affects the interpretation of "I".

doesn't hold because OCR programs are giant collections of probabilities, thresholds, ratios, and conditions. The code that tries to figure out 1Il and 0O confusion in words, in particular, is a big set of heuristics using counts of various character types and guesses about what the most likely output string is.

and +1 for using the mailing list, not the bug tracker, for asking questions

**Comment by amitdo** [comment]
Very true.
