### ISSUE TITLE
Coverity build broken

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#3051]
Coverity badge reports the build/analysis failed.

@stweil, maybe you can fix this issue.

**Comment by stweil** [comment]
I'm afraid that I cannot fix this. To cite Coverity: "Last Build Status: Failed - No further action needed.. Your build will be added back to the queue for analysis.".

I had sent a fresh build to Coverity some weeks ago, and then that error message appeared. Another build for Leptonica was not accepted at all.

From time to time Coverity scan is in a really bad state, nothing what an ordinary user like me can change.

**Comment by amitdo** [comment]
Ok, thanks for providing this information.

**Comment by amitdo** [comment]
After a long time being broken, I see it works now.

**Comment by stweil** [comment]
Now Coverity Scan for Leptonica is broken ...
