### ISSUE TITLE
unpredictable OCR

### ISSUE THREAD

**Issue by jgfritsch** [tesseract-ocr/tesseract#3053]
------------------------

### Environment

* **Tesseract Version**:  4.0.0-beta.1 leptonica-1.75.3  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
* **Platform**: Ubuntu 18.04/Python 2.3/Opencv2 3.4.0

### Current Behavior:
I am using two different text detection algorithms. They detect the text location with only a small difference of one pixel.  Attached you will find the original image sign.jpg and the 2 cropped pictures  based on the 2 different text detection algorithms. The coordinates of the text box is described in the filename. Before applying the OCR I downscale the cropped image from 80 pixels high to 25 pixels high cv2.resize and proportionally scale the length. However tesseract detects for crop_sign_x1=125_y1=106_x2=318_y2=186.png "Ten" while for the other file crop_sign_x1=124_y1=107_ x2=317_y2=185.png it detects the correct text "ALTO". Pictures are available at the following link and are also attached

in python I execute the following code:
>>> config = ("-l eng --oem 3 --psm 6")
>>>ocr_text = pytesseract.image_to_string('crop_sign_x1=125_y1=106_x2=318_y2=186.png', config=config)
>>>print ocr_text
>>>u'Ten'
>>>ocr_text = pytesseract.image_to_string('crop_sign_x1=124_y1=107_ x2=317_y2=185.png', config=config)
>>>print ocr_text
>>>u'ALTO'

https://drive.google.com/drive/folders/1XenYjZ05zsSrQPvnfhsSynxp0uoZpOHs?usp=sharing

![crop_sign_x1=124_y1=107_ x2=317_y2=185](https://user-images.githubusercontent.com/37520308/86412526-12735d00-bc74-11ea-8b5b-0d6e5bd79e74.png)
![crop_sign_x1=125_y1=106_x2=318_y2=186](https://user-images.githubusercontent.com/37520308/86412531-143d2080-bc74-11ea-8e28-2dcdaf64d3fa.png)
![sign](https://user-images.githubusercontent.com/37520308/86412533-156e4d80-bc74-11ea-90d1-1b794a9dc880.jpg)

### Expected Behavior:
tesseract should return for both images the correct text "ALTO".

### Suggested Fix:
for both pictures tesseract should return the correct text "ALTO"

**Comment by amitdo** [comment]
I get "ALTO" for both images by using an older revision of the tessdata repo.

https://tesseract-ocr.github.io/tessdoc/Data-Files.html#data-files-for-version-400-november-29-2016

**Comment by jgfritsch** [comment]
Thx.  Are you saying I should be be using LSTM instead of EAST oem=0?
Can you please provide a link to instructions on how to install eng.traineddata for tessreact 4.0.0 Beta?
Thx

**Comment by amitdo** [comment]
What you are using currently is `eng.traineddata` from the `tessdata_fast` repo.

With eng.traineddata from the older revision of the `tessdata` repo, you can use `--oem 3`, but oem 0, 1, 2 also outputs "ALTO" for the two images.

With `eng.traineddata` from the **current** revision of the `tessdata repo`, only `--oem 0` outputs "ALTO" for the two images.

This is my observation. I don't know if changing the traineddata will work better than your current traineddata with other images.

Please use the forum to ask about installing another traineddata on your system.

**Comment by jgfritsch** [comment]
Thx. I replaced eng.traineddata and indeed I got the same results
