### ISSUE TITLE
LSTM Box configuration missing documentation for box file generation

### ISSUE THREAD

**Issue by seshubabuarava** [tesseract-ocr/tesseract#3054]
I am trying to understand how to generate box files using tesseract. I am following the Making box files section in the https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00.html#making-box-files link.

I could not find any reference to lstmbox configuration. Can you please provide me some direction?

Can tesseract be trained to ocr english handwritting?

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesstrain/wiki
