### ISSUE TITLE
Image to text only in english

### ISSUE THREAD

**Issue by Kurukshetran** [tesseract-ocr/tesseract#3057]
My image contains English and Tamil text, tesseract converts Tamil text to English in output but English texts are proper. Is there a way to skip other languages text to be scanned?

**Comment by Moldoteck** [comment]
What parameter/language are you passing to tesseract for recognition?

**Comment by Shreeshrii** [comment]
script/Tamil or tam+eng will recognize both Tamil and English.

For Tamil reconition you can'u use the default language, which is English, you have to specify the language.
