### ISSUE TITLE
OSD (Orientation and script detection) in android

### ISSUE THREAD

**Issue by ankitagg** [tesseract-ocr/tesseract#306]
Hi Team,

I am an android developer and i am integrating Tesseract for OCR scanning. for my application i have the requirement to detect the orientation of the Ocr and based and that process the OCR.
I have gone though various post to find the way to get the Orientation but was unable to succeed. As per one of the post it ismentioned to get the orientation using the following logic :

inputfile = "/usr/src/tesseract-3.02/eurotextUpsideDown.png";
    image = pixRead(inputfile);

    api->Init("/usr/src/tesseract-3.02/", "eng");
    api->SetPageSegMode(tesseract::PSM_AUTO_OSD);
    api->SetImage(image);
    api->Recognize(0);

    tesseract::PageIterator* it =  api->AnalyseLayout();
    tesseract::Orientation orientation;
    tesseract::WritingDirection direction;
    tesseract::TextlineOrder order;
    float deskew_angle;

    it->Orientation(&orientation, &direction, &order, &deskew_angle);
    printf("Orientation: %d;\nWritingDirection: %d\nTextlineOrder: %d\n" \
           "Deskew angle: %.4f\n",
           orientation, direction, order, deskew_angle);

But in android I cannot find the supported method AnalyseLayout() in the TessBaseApi.java class. Can some one help me to find the solution for this or can some one tell me the
api or the logic to get this.

Will be a great help for me. 

Thanks,
Ankit

**Comment by zdenop** [comment]
For asking support use tesseract user forum (see [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice))

**Comment by kirantpatil** [comment]
Dear @ankitagg,

Did you resolve the issue ?

Please let me know if it is resolved and the method you used to solve ?

Thanks.

**Comment by coreTruth** [comment]
Hello,
Has this issue been resolved?
How can I use OSD in android tesseract?

Thanks.
Best,
Charles.
