### ISSUE TITLE
Alpha 0 text on pdf output

### ISSUE THREAD

**Issue by Maxime-J** [tesseract-ocr/tesseract#3062]
### Environment

* **Tesseract Version**: 4.1.1 / 5.0.0-alpha

### Current Behavior:
On pdf output, the OCR text has an alpha 0 channel,
which can cause issues with some parsers/tools.

### Expected Behavior:
Apparently, text objects for OCR just need to be created without Fill and Outline.
Here's a quote from a developper of a SDK I used

> The reason for our Conversion engine not being able to recognize fonts extracted by the Tesseract engine is because this engine is not following guidelines on creating Text Content Objects.
> Namely, instead of creating objects without Fill and Outline, they have also added Alpha channel to the Color value of the tokens to 0. This means that most of Adobe-compliant PDF parsers will be ignoring this kind of objects.
> [...]
> So per the advice of the creators of the PDF format, a component of our Conversion SDK product that is reading the content of PDF is ignoring this kind of Text Objects that are transparent.

### Suggested fix:
Doing the Fill and Outline way without the alpha 0
Or at least, making the text visible when textonly_pdf parameter is set.

**Comment by zdenop** [comment]
tesseract use glyphless font, so If you want to make it visible, you have to do it by yourself/with other tools (that is reason for textonly_pdf option - take tesseract output and do wathever you want with it).
I am not expert at pdf, but I wander if problem is related to alpha 0 or that your SDK does not expect/accept glyphless font...
Making glyphless text objects with Fill and Outline sound strange for me.

cc: @jbreiden

**Comment by phymbert** [comment]
Hello, 

I was using and forking the pdfrenderer recently, and it works perfectly fine with text objects - tested with popller and pdfbox.

I don't see any reference to an alpha channel as we are using DeviceRGB color space.
Furthermore, Adobe PDF specification 32000-1:2008 does not have such kind of limitations in Text extraction chapter 9.10.

@zdenop @amitdo I would suggest closing this issue as there is no any reference to reproduce it and reduce the PDF labeled issues list.

**Comment by amitdo** [comment]
Also, none of the current developers has an expertise in the PDF format, so without a patch, there is a very little chance to solve any issue related to PDF.
