### ISSUE TITLE
works for all pics expect for one pic no matter how big it saved

### ISSUE THREAD

**Issue by laocan** [tesseract-ocr/tesseract#3068]
just a simple test demo.
works for all pics expect for this one, with different sizes:
![test](https://user-images.githubusercontent.com/5567783/88039491-37276a00-cb7a-11ea-9627-db504904ee7d.png)
but the screenshot works?!
![test_screen](https://user-images.githubusercontent.com/5567783/88040152-11e72b80-cb7b-11ea-9080-c67acc6357db.png)

**Comment by zdenop** [comment]
Please read the [docs](https://github.com/tesseract-ocr/tessdoc/blob/master/ImproveQuality.md#inverting-images) or consult forum before writing issue.
