### ISSUE TITLE
Update the tesseract-c_api-demo.py to work with 3.04

### ISSUE THREAD

**Issue by Omnipresent** [tesseract-ocr/tesseract#307]
The demo for capi in [c_api-demo.py](https://github.com/tesseract-ocr/tesseract/blob/master/contrib/tesseract-c_api-demo.py) uses 3.02 version and the method `TessBaseAPIProcessPages(api, filename, None , 0)` to get the text from the image. However, in version 3.04 version this method now takes a new parameter `TessResultRenderer`. So the demo does not work with version 3.04. Additionally, the demo uses `TessBaseAPIGetUTF8Text ` to get the text which would not get all the text back from multi page tiff documents. Should be using `TessBaseAPIProcessPages ` to get the text back

This change was made in [this commit](https://github.com/tesseract-ocr/tesseract/commit/19c4c2f0e7e616b4bd418cc920ebb617f1703321#diff-96572cdeee0a43471eaf4745287b9630)

I would be more than happy to send a pull request if I can get some help. 

I have tried the following but it doesn't seem to work:

```
outputbase = ctypes.c_char
renderer = tesseract.TessTextRendererCreate(ctypes.pointer(outputbase))
text_out = tesseract.TessBaseAPIProcessPages(self.api, path, None, 0, renderer)
```

I get an error `_type_: must have storage info`

**Comment by snorfalorpagus** [comment]
See code in this SO answer: https://stackoverflow.com/questions/36871072/segmentation-fault-while-calling-cpp-function-from-python/36876584#36876584
