### ISSUE TITLE
Upcoming book on OCR with Tesseract and OpenCV

### ISSUE THREAD

**Issue by jrosebr1** [tesseract-ocr/tesseract#3075]
Hi Tesseract team -- first of all, I really just want to thank you for all the hard work that goes into supporting a free resource/library such as Tesseract. I understand a very intimate level the amount of effort it requires. _Thank you for it._

My name is Adrian Rosebrock. Some of the maintainers, contributors, and users of Tesseract may already know me from my blog, [PyImageSearch.com](https://www.pyimagesearch.com/), where I provide free tutorials on computer vision, deep learning, and OCR ([my OCR tutorials can be found here](https://www.pyimagesearch.com/category/optical-character-recognition-ocr/)). Some of the Tesseract documentation pages even link to PyImageSearch tutorials, which I want to thank everyone personally for. It's truly an honor to be referenced in such an amazing project!!

Secondly, I want to apologize ahead of time if this is a misuse of the issue tracker. If I am misusing it, please immediately delete this issue. It's not my intention to cause a problem -- I'm here only to help.

The reason I'm posting here is because myself and the rest of the PyImageSearch team are about to author a book on OCR, entitled _OCR with OpenCV, Tesseract, and Python._ **I'm wondering if there are any topics the maintainers would like to see covered in the text?**

- Are there topics here in the issue tracker or mailing list that are consistently asked?
- Are there implementation/accuracy problems that could be addressed in a blog post or book chapter?
- **Are there real-world implementation examples that I could author that would _help reduce the support load_ on your GitHub Issues forum?**

My goal is to author content that will help the OCR community as a whole while at the same time providing tutorials that will help Tesseract users (and help reduce any support requests you receive).

I have more details I can share on the book, but I don't want to self-promote here without a maintainer/admin first authorizing it. If I'm out of line or misusing the issue tracker, again, I apologize -- that is _not_ my intention. I'm just here to author content for the PyImageSearch community which in turn will help the Tesseract community.

**Please let me know if I can be of any help.** And if you would like me to share more details on the upcoming book (previews, table of contents, etc.), please do let me know.

Thank you again for reviewing this and I wish you all the best.

**Comment by amitdo** [comment]
In general, questions like you ask here should be asked in our forum.
