### ISSUE TITLE
Does stdin work with anyone?

### ISSUE THREAD

**Issue by whatohyou** [tesseract-ocr/tesseract#3076]
### Environment
Windows. C#.
* **Tesseract Version**: v5.0.0-alpha.20200328
* **Platform**: Windows 10 64bit.

### Current Behavior:
stdin doesn't work for me.

process.StartInfo.Arguments = "stdin" + " stdout -l " + language + " --psm " + PSM_setting + " -c preserve_interword_spaces=1";
process.StartInfo.RedirectStandardInput = true;
process.StartInfo.RedirectStandardOutput = true;
process.Start();

//To write bmp to stdin
BinaryWriter writer = new BinaryWriter(process.StandardInput.BaseStream);                    
bmp.Save(writer.BaseStream, System.Drawing.Imaging.ImageFormat.Bmp);
//To read the result
StreamReader reader = process.StandardOutput;                    
string output = reader.ReadToEnd();//<-Hangs right here.

### Expected Behavior:
...work?
### Suggested Fix:
Does it work for others? How?

**Comment by zdenop** [comment]
We do not support 3rd program. Replicate problem with tesseract executable to make sure problem is not in your code.

**Comment by whatohyou** [comment]
How do you replicate stdin problem by only using tesseract executable? I am using tesseract executable.

**Comment by zdenop** [comment]
in command line ;-) 
And already got reply at [SO that problem is in your code](https://stackoverflow.com/questions/63444109/how-to-make-process-standardinput-bitmap-stream-work-in-tesseract).

**Comment by whatohyou** [comment]
Yes, thank you. process.StandardInput.BaseStream.close(); was needed. 👍
