### ISSUE TITLE
Image to Text for one image contains different background color 

### ISSUE THREAD

**Issue by Heidernlee** [tesseract-ocr/tesseract#3078]
I was trying to get text from one image that contains different background color
Sample like this :
![129](https://user-images.githubusercontent.com/25810034/90846833-ab347800-e39b-11ea-9eab-c8eec72046c3.png)

Left side is black text whit white background
Right side is white text with black background
I've tried command like [-l jpn --psm 6] or [-l jpn --psm 7], can't get text

But when I tried get text with image **only contains Left side or Right side from this Image**,
It's all 100% got the correct text

Is it any way to get correct text from a Image that 
contains **totally different text-color and background-color** ?
Any option from tesseract-ocr command that I never tried ?

**Comment by zdenop** [comment]
1. Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
2. Make sure you read docs first, search forum.
