### ISSUE TITLE
Outputs garbage sometimes, but not when using the pre-processed image or a different language

### ISSUE THREAD

**Issue by malnvenshorn** [tesseract-ocr/tesseract#3079]
I haven't reported this as a bug because OCR is never perfect, but I observed some strange results. Often the recognition works if I used the preprocessed image generated by tesseract or select a different language.

First example: [input.pgm.zip](https://github.com/tesseract-ocr/tesseract/files/5112170/input.pgm.zip)

```
$ tesseract input.pgm stdout -l deu
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 268
VT CN
war er der beste Cutman der Branche.
```

Running the recognition agains the saved pre-processed image `tessinput.tif` saved using `tessedit_write_images true` results in:

```
$ tesseract tessinput.tif stdout -l deu
Page 1
Als ich ihn kennen lernte,
war er der beste Cutman der Branche.
```

Also interesting is the result when the language is set to English.

```
$ tesseract input.pgm stdout -l eng
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 268
Als ich ihn kennen lernie,
war er der beste Cuitman der Branche.
```

Second example: [input2.pgm.zip](https://github.com/tesseract-ocr/tesseract/files/5112172/input2.pgm.zip)

```
$ tesseract input2.pgm stdout -l deu
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 224
SN
```

```
$ tesseract tessinput.tif stdout -l deu
Page 1
Empty page!!
Empty page!!
```

```
$ tesseract input.pgm stdout -l eng
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 224
Lassen Sie mal sehen.
```

These are examples using German language recognition, but it happens with English too, but less frequently. It's also worth mentioning that the generated pre-processed file is identical to the input when using `tessinput.tif` in the examples above. It almost looks like the pre-processed file is (often) not used for the recognition process.

**Tesseract Version**: 4.1.1
**Platform:** Linux 5.8.1-arch1-1 x86_64 GNU/Linux

**Comment by malnvenshorn** [comment]
No it's not. I still get the same results. The docs say "If the resulting `tessinput.tif` file looks problematic, try some of these image processing operations before passing the image to Tesseract." But the `tessinput.tif` looks fine. Also this doesn't explain why the results of  `tesseract input.pgm stdout -l deu`  and `tesseract tessinput.tif stdout -l deu` are different.

**Comment by zdenop** [comment]
Read the whole docs.
