### ISSUE TITLE
Japanese Italics

### ISSUE THREAD

**Issue by glebm** [tesseract-ocr/tesseract#308]
Doesn't seem to recognize italics in Japanese. I want to help, but there don't seem to be any instruction in https://github.com/tesseract-ocr/langdata.

Examples:

![image0](https://cloud.githubusercontent.com/assets/216339/14833717/8164ad44-0bf8-11e6-8dae-a4efe29a3fe2.png)

![image0](https://cloud.githubusercontent.com/assets/216339/14833805/e8428a36-0bf8-11e6-8b59-5b205e18bde2.png)

**Comment by amitdo** [comment]
Please see:
https://github.com/tesseract-ocr/tesseract#support

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/d8c04e8/training/language-specific.sh#L308

```
JPN_FONTS=( \
    "TakaoExGothic" \
    "TakaoExMincho" \
    "TakaoGothic" \
    "TakaoMincho" \
    "TakaoPGothic" \
    "TakaoPMincho" \
    "VL Gothic" \
    "VL PGothic" \
    "Noto Sans Japanese Bold" \
    "Noto Sans Japanese Light" \
    )
```

These are the font used in the current `jpn.traineddata.`

If you want to train Tesseract, use one of these guides:
https://github.com/tesseract-ocr/tesseract/wiki/tesstrain.sh
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract

For further questions, please use the [Tesseract users forum](https://groups.google.com/d/forum/tesseract-ocr).

**Comment by glebm** [comment]
@amitdo Thanks!

**Comment by Ota-Coder** [comment]
Hi! I'm wondering if the tessdata for italics of Japanese fonts have finished?
