### ISSUE TITLE
Does it need to be coupled with a language classifier if applied to images of unknown languages, assuming each image contains one  language 

### ISSUE THREAD

**Issue by shenglih** [tesseract-ocr/tesseract#3080]
In order to get good accuracies when applying tesseract to a large stream of images that could contain any of the existing languages (let's assume each image contains one language), is it better to pass the image through a language classifier first to find out the lang, rather than using the multilingual tesseract? If the former, is there any off-the-shelf language classifier available? Much appreciated!

**Comment by amitdo** [comment]
Tesseract has script classifier.

You can invoke it like this:
`tesseract in.png out --psm 0`
