### ISSUE TITLE
Tesseract result was not good tried prepossessed image and trained datas

### ISSUE THREAD

**Issue by jeganrajrajan** [tesseract-ocr/tesseract#3081]
Used the serak-tesseract-trainer for font style used this link 'https://github.com/serak/serak-tesseract-trainer'. But the result used these different training font approaches was not give good results. 

Used oem 3, psm --4 and 6  but the result was not good. 

Can you suggest any methods or preprocessing steps to get the tesseract extraction result.

**Comment by Shreeshrii** [comment]
>Can you suggest any methods or preprocessing steps to get the tesseract extraction result.

https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html
