### ISSUE TITLE
Tesseract producing texts when specifying a language other than original language

### ISSUE THREAD

**Issue by sankha90** [tesseract-ocr/tesseract#3084]
I  am trying to detect the language in an image based on the confidence scores , generated by tesseract. I am checking for different languages in each of the images. What I am using : 

    text1 = pytesseract.image_to_data(full_path, lang='eng', config=tessdata_dir_config, output_type='data.frame')
    text1 = pd.DataFrame(text1)
    text1 = text1[text1.conf != -1]
    text1 = text1[~text1.text.str.contains('-')]
    text1 = text1[~text1.text.str.contains(' ')]
    text1 = text1[~text1.text.str.contains("\.")]
    text1 = text1[~text1.text.str.contains("[0-9]")]
    text1 = text1[~text1.text.str.contains("[:,\n,/,%,|,;,!,&,(,),\*,\",\?,\',_,=,é,$,@,#]")]
    
    
    text2 = pytesseract.image_to_data(full_path, lang='hin', config=tessdata_dir_config, output_type='data.frame')
    text2 = pd.DataFrame(text2)
    text2 = text2[text2.conf != -1]
    text2 = text2[~text2.text.str.contains('-')]
    text2 = text2[~text2.text.str.contains(' ')]
    text2 = text2[~text2.text.str.contains("\.")]
    text2 = text2[~text2.text.str.contains("[0-9]")]
    text2 = text2[~text2.text.str.contains("[:,\n,/,%,|,;,!,&,(,),\*,\",\?,\',_,=,é,$,@,#]")]

For English it is generating texts and the respective confidence scores but when I am passing specifying Hindi as the language , I am also getting texts and confidence scores for **Hindi** ,  whereas the image has only **English** language in it. 

Here is the image : [sample](https://rb.gy/rwykes)

What am I doing wrong? 😞

**Comment by stweil** [comment]
> I am trying to detect the language in an image based on the confidence scores.

That won't work. Nearly all models can recognize English text.

**Comment by Moldoteck** [comment]
Tesseract does not have a function to detect the language of the text in the image.
