### ISSUE TITLE
#OpenMP#undefined symbol: GOMP_parallel_start

### ISSUE THREAD

**Issue by Kwei9** [tesseract-ocr/tesseract#3086]
Hi~
I had a java program with tesseract and I got this message when I execute my jar.
> java: symbol lookup error: /usr/lib/libtesseract.so: undefined symbol: GOMP_parallel_start

It looks like libtesseract.so lacked GOMP_parallel_start. Then I tried to [reinstall tesseract with `--disable-openmp`](https://github.com/nguyenq/tess4j/issues/96). I failed again with this:
> libtool: link: g++ -g -O2 -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o -L/usr/local/lib/ ./.libs/libtesseract.so -L/usr/local/lib /usr/local/lib/liblept.so
-lpng12 -ljpeg -ltiff -lm -lz -lrt -lpthread -Wl,-rpath -Wl,/usr/local/lib
./.libs/libtesseract.so: undefined reference to omp_get_thread_num' ./.libs/libtesseract.so: undefined reference to GOMP_sections_end_nowait'
./.libs/libtesseract.so: undefined reference to omp_get_num_threads' ./.libs/libtesseract.so: undefined reference to GOMP_parallel_start'
./.libs/libtesseract.so: undefined reference to GOMP_parallel_end' ./.libs/libtesseract.so: undefined reference to GOMP_sections_next'
./.libs/libtesseract.so: undefined reference to GOMP_parallel_sections_start' collect2: error: ld returned 1 exit status make[2]: *** [tesseract] Error 1 make[2]: Leaving directory /usr/src/tesseract-4.1.1/src/api'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/src/tesseract-4.1.1'
make: *** [all] Error 2

I found Disable OpenMP support by default in your release v4.1.0 and this issue: [error about openmp](https://github.com/tesseract-ocr/tesseract/issues/748). But now I can't solve it. Please help, thx😥
------------------------

### Environment

* **Tesseract Version**: tesseract 4.1.1 and leptonica-1.80.0
* **Platform**: CentOS 6.8

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by Kwei9** [comment]
After clean all of tesseract, it was correct after I reinstalled.
