### ISSUE TITLE
Is it necessary to select each character in LSTM Training?

### ISSUE THREAD

**Issue by iori2882** [tesseract-ocr/tesseract#3088]
Environment
Tesseract Version: tesseract.exe --version
tesseract v5.0.0-alpha.20200223
leptonica-1.78.0
libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
Found AVX2
Found AVX
Found FMA
Found SSE
Found libarchive 3.3.2 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5
Found libcurl/7.59.0 OpenSSL/1.0.2o (WinSSL) zlib/1.2.11 WinIDN libssh2/1.7.0 nghttp2/1.31.0

Commit Number: 2020-09-03

Platform: Windows 7

In LSTM training, do I need to adjust the boundary of each box data?

![a1](https://user-images.githubusercontent.com/1480587/92101827-47389780-ee10-11ea-9415-6da9964cbccb.png)

Change to

![a2](https://user-images.githubusercontent.com/1480587/92101890-5ddeee80-ee10-11ea-8744-141199226c80.png)

**Comment by Shreeshrii** [comment]
>In LSTM training, do I need to adjust the boundary of each box data?

No. If you have correct bounding box for the line, it is ok.
