### ISSUE TITLE
Failure on CMake - Tesseract 5.0.0-alpha-777-g162f3     VC 14 - win32

### ISSUE THREAD

**Issue by tlane-git** [tesseract-ocr/tesseract#3091]
Tesseract 5.0.0-alpha-777-g162f3
VC 14 2015  -  MSVC 19.0.24215.1  (32-bit)
CMake  3.18.2
sw.client.sw version 1.0.0 git revision 932aae3e73efa8a57ebd27b1699637604e80d288
                    assembled on 09.08.2020 11:29:44 UTC     09.08.2020 07:29:44 Eastern Daylight Time
Windows 7 OS 64 bit

After processing thru the sw dependencies, an exception will be returned from tiff 4.1.0 sw.cpp module.  It appears that some basic compile information is not being assigned as the failure is not finding the variable SIZEOF_SIGNED_LONG.  I have added the cmake command line output.   

I have been able to successfully run the a similar cmake with x64 platform (but really need 32 bit).

Thank you.

cmake command line output 
------------------------------------
Setting policy CMP0091 to NEW
The C compiler identification is MSVC 19.0.24215.1
The CXX compiler identification is MSVC 19.0.24215.1
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Configuring tesseract version 5.0.0-alpha-777-g162f3...
Setting build type to 'Release' as none was specified.
IPO / LTO supported
Performing Test COMPILER_SUPPORTS_MARCH_NATIVE
Performing Test COMPILER_SUPPORTS_MARCH_NATIVE - Failed
Performing Test HAVE_AVX
Performing Test HAVE_AVX - Failed
Performing Test HAVE_AVX2
Performing Test HAVE_AVX2 - Failed
Performing Test HAVE_FMA
Performing Test HAVE_FMA - Failed
Performing Test HAVE_SSE4_1
Performing Test HAVE_SSE4_1 - Failed
Performing Test HAVE_NEON
Performing Test HAVE_NEON - Failed
target changed from "" to "auto"
Detected CPU: skylake
Performing Test check_cxx_compiler_flag__arch_AVX2
Performing Test check_cxx_compiler_flag__arch_AVX2 - Success
Found SW: C:/ThirdPartySoftware/pkg-config/bin/sw.exe  
sw: processing dependencies
Downloading database from origin remote

[162/166] C:/Users/10060318/.sw/storage/pkg/67/22/d8fc/src/sdir/sw.cpp

[163/166] C:/Users/10060318/.sw/storage/pkg/75/6a/600e/src/sdir/sw.cpp

[165/166] C:/Users/10060318/.sw/storage/tmp/cfg/132785/loc.sw.self.d47434-0.0.25.dll

[166/166] C:/Users/10060318/.sw/storage/tmp/cfg/132785/loc.sw.self.f423c1-0.0.25.dll

Exception in file D:/dev/cppan2/client2/src/sw/driver/module.cpp:120, function operator (): error in module (C:/Users/10060318/.sw/storage/tmp/cfg/132785/loc.sw.self.4d9d9d-0.0.25.dll): Exception in file C:/Users/10060318/.sw/storage/pkg/f5/fe/083c/src/sdir/sw.cpp:115, function build: no type: 0, 0

sw command: C:/ThirdPartySoftware/pkg-config/bin/sw.exe -shared -platform x86 -compiler msvc-19.0 -d C:/Software/GITHUB/tesseract/build32/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps C:/Software/GITHUB/tesseract/build32/.sw/cmake/sw.txt -cmake-file-version 4
CMake Error at C:/Users/10060318/.sw/storage/etc/sw/static/SWConfig.cmake:232 (message):
  sw: non-zero exit code: 1
Call Stack (most recent call first):
  CMakeLists.txt:318 (sw_execute)

Configuring incomplete, errors occurred!
See also "C:/Software/GITHUB/tesseract/build32/CMakeFiles/CMakeOutput.log".
See also "C:/Software/GITHUB/tesseract/build32/CMakeFiles/CMakeError.log".

------------------------------------

**Comment by Moldoteck** [comment]
@egorpugin , maybe it is related to sw

**Comment by egorpugin** [comment]
Delete `C:/Users/10060318/.sw/storage/etc/checks`.
Upgrade sw running `sw --self-upgrade`.
The issue was fixed in https://github.com/SoftwareNetwork/sw/issues/54.
