### ISSUE TITLE
Fine tune for ± a few characters

### ISSUE THREAD

**Issue by Zengyajunbit** [tesseract-ocr/tesseract#3093]
Hi, guys. I have a question about training a new trainddata. In the eng.trainddata, I want to add a few characters. In the guideline, the steps is on linux. I want to do this on Windows. How can I do this?Thanks.

------------------------

### Environment

* **Tesseract Version**: 5.0
* **Commit Number**: no
* **Platform**: Windows 10, version 64-bit

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
