### ISSUE TITLE
Specify Custom Installation path in silent install

### ISSUE THREAD

**Issue by jfuller2701** [tesseract-ocr/tesseract#3095]
# Environment

Trying to run an unattended install silently (with /S switch) but we need to specify a custom directory and there doesn't seem to be any documentation around exposing which switches are usable. I'm sure I've missed something but I can't find it anywhere so looking for some sort of confirmation either way.

* **Tesseract Version**: 5.0
* **Commit Number**: n/a
* **Platform**: Windows

**Comment by stweil** [comment]
The Tesseract installer for Windows is not part of this repository. Maybe the [NSIS documentation](https://nsis.sourceforge.io/Which_command_line_parameters_can_be_used_to_configure_installers%3F) helps.

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for additional questions.

**Comment by jfuller2701** [comment]
Appreciate the response.

I had a quick look at the NSIS docs and although it does include a /D switch, it doesn't actually work with the tesseract installer :( - I'll keep digging and check the user forum out.

**Comment by qzd1989** [comment]
> Appreciate the response.
> 
> I had a quick look at the NSIS docs and although it does include a /D switch, it doesn't actually work with the tesseract installer :( - I'll keep digging and check the user forum out.

hi, do you fix it? I still don't know how to set specify custom installation path.
here is my issue: https://github.com/tesseract-ocr/tesseract/issues/4360
