### ISSUE TITLE
[  FAILED  ] ResultIteratorTest.ComplexTest with current master

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#3099]
[ RUN      ] ResultIteratorTest.ComplexTest
[INFO]  BBox: [L:76, T:4, R:144, B:15]
[INFO]  BBox: [L:219, T:3175, R:277, B:3191]
[INFO]  BBox: [L:1115, T:368, R:1439, B:376]
[INFO]  BBox: [L:1111, T:387, R:1434, B:424]
[INFO]  BBox: [L:281, T:600, R:1237, B:3137]
[INFO]  BBox: [L:217, T:3192, R:1053, B:3225]
[INFO]  BBox: [L:870, T:1030, R:1682, B:2278]
[INFO]  BBox: [L:1082, T:2319, R:1462, B:2612]
[INFO]  BBox: [L:1311, T:602, R:2267, B:3139]
[INFO]  outfile = ./tmp/failedxor.png
[INFO]  At level 0: pix diff = 2073
../../../unittest/resultiterator_test.cc:117: Failure
Expected: (pixcount) <= (max_diff), actual: 2073 vs 400
[INFO]  BBox: [L:76, T:4, R:144, B:15]

...

[INFO]  BBox: [L:2170, T:3112, R:2188, B:3139]
[INFO]  BBox: [L:2204, T:3113, R:2221, B:3131]
[INFO]  BBox: [L:2223, T:3112, R:2245, B:3131]
[INFO]  BBox: [L:2247, T:3100, R:2267, B:3131]
[INFO]  outfile = ./tmp/failedxor.png
[INFO]  At level 4: pix diff = 2090
../../../unittest/resultiterator_test.cc:117: Failure
Expected: (pixcount) <= (max_diff), actual: 2090 vs 650
[  FAILED  ] ResultIteratorTest.ComplexTest (1710 ms)

**Comment by stweil** [comment]
That changed with @bertsky's commit 65a077d3e9cd3be1f2ef97b84bed9f5649722775.

It is either a regression or an improvement (which needs an update of the test case). That still has to be checked.

**Comment by bertsky** [comment]
Thanks for alerting me – I'll have a look. (Not sure if I ran the regression tests on that one...)

**Comment by Shreeshrii** [comment]
>stweil commented 14 days ago in resultiterator_test fails #3122

>Pull request #3082 improved the layout recognition. This changes the OCR results, so the resultiterator_test currently fails and needs an update.

**Comment by bertsky** [comment]
@Shreeshrii sorry, did not find the time yet.

**Comment by Shreeshrii** [comment]
```
Expected: (pixcount) <= (max_diff), actual: 2073 vs 400
```
and
```
Expected: (pixcount) <= (max_diff), actual: 2090 vs 650
```

Is it enough to just change the expected values to match the results from the current code so that the test passes or is some other change required?
