### ISSUE TITLE
Tesseract version 3.02 not creating txt files from png image

### ISSUE THREAD

**Issue by rahulsngh91** [tesseract-ocr/tesseract#3103]
Hi,
Can anybody please help what would be the possible cause with the tesseract v3.02 which is not generating .txt files from png image in windows system.

**Comment by stweil** [comment]
Nobody will help you with unsupported very old versions like Tesseract v3.02. Use a recent version.
And please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
