### ISSUE TITLE
Tutorial clarification

### ISSUE THREAD

**Issue by RaduStoicescu** [tesseract-ocr/tesseract#3106]
Can someone please explain this step from the [tutorial](https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00)
`To make the tesstrain.sh script work, it will be necessary to either set PATH to include your local training and api directories, or use make install.`

Where is the makefile?

**Comment by Shreeshrii** [comment]
I think it refers to the makefile for building of tesseract and training tools. If you install them, then the commands lstmtraing, lstmeval etc will be available glob

**Comment by Shreeshrii** [comment]
Sorry, accidentally issue was closed.

tesstrain.sh calls tesseract, lstmtraining, lstmeval etc. If you install tesseract and training tools, it shoul work fine.

**Comment by Shreeshrii** [comment]
>Where is the makefile?

Please follow instructions below to build and install tesseract and training tools.

https://tesseract-ocr.github.io/tessdoc/Compiling-%E2%80%93-GitInstallation.html#build-with-training-tools
