### ISSUE TITLE
Process for fine tuning a language with a large amount of fonts

### ISSUE THREAD

**Issue by kamui-7** [tesseract-ocr/tesseract#3108]
Not an issue but some questions since I was a bit confused. How exactly were the models in lstm_best trained? It says its trained on over 5000 fonts for english and spanish. Im trying to train japanese on around 2000 fonts and here are the things I am unsure of:

1. How do you tell tesstrain to train ALL the fonts in a directory rather than listing them one by one?
2. It seems to take around an hour for each font, so it would take alot of time to work on all of the fonts. How long did it take for you guys to train them on such a large amount of fonts?
3. Was any cloud service used to train the model on? How do you make it use all my cores for training, since it only uses one

Sorry for so many questions, I've looked everywhere and there wasnt much on this topic. 
Thanks in advance

**Comment by Shreeshrii** [comment]
1. You have to create a list of fontnames. you can use the `textimage` program to do so. eg:

```

 text2image --find_fonts \
 --fonts_dir /home/ubuntu/.fonts \
 --fontconfig_tmpdir=/home/ubuntu/tmp \
 --text /home/ubuntu/tess5training-iast/langdata/iast/all100.training_text \
 --min_coverage 0.99  \
 --outputbase ~/tmp \
 --render_per_font false \
 |& grep raw \
  | sed -e 's/ :.*//g'  > /home/ubuntu/tess5training-iast/langdata/iast/all100.fonts.txt

```

2. and 3. Official traineddata files were trained by Ray Smith at Google and probably took weeks to train.

Also See

https://tesseract-ocr.github.io/tessdoc/TrainingTesseract-4.00.html#hardware-software-requirements

https://github.com/tesseract-ocr/tesstrain/wiki/GT4HistOCR

**Comment by kamui-7** [comment]
Ah i see. When I run the training on my machine it only seems to be using 1 core. Is there any option that I can specify to make it use all my cores?

**Comment by Shreeshrii** [comment]
Make sure to build tesseract with `--enable-openmp`.
