### ISSUE TITLE
A strange symbol follows the result

### ISSUE THREAD

**Issue by xishanhan** [tesseract-ocr/tesseract#3110]
### Environment

* **Tesseract Version**: tesseract-ocr-w64-setup-v5.0.0.20190623.exe
* **Platform**: Windows8 64-bit

### Current Behavior:
Every time the text in the picture is recognized, the result will be followed by a ♀ symbol. For example, recognized this picture
![1](https://user-images.githubusercontent.com/71965365/94549264-84b00980-0284-11eb-9a28-0135d8c74de1.jpg)

the result is
![2](https://user-images.githubusercontent.com/71965365/94549383-b3c67b00-0284-11eb-9e5d-ab6973a06107.png)

I would like to know how to remove the ♀

Thank you！

**Comment by xishanhan** [comment]
I use strip() to remove the ♀ and successfully remove it, but I still don't know why the result followed by this symbol.

**Comment by stweil** [comment]
Isn't that just the form feed which is used by Tesseract to terminate a page?

**Comment by xishanhan** [comment]
I see, I’m not very familiar with tesseract. Thank you!

**Comment by minhnh25** [comment]
@xishanhan How do u remove this symbol?

**Comment by xishanhan** [comment]
just use strip() or&nbsp;write an if function and remove it if you have it （such as replace('symbol', '')）

---Original---

**Comment by canklot** [comment]
For people who cant remove the ♀ sign use the "\n\x0c" instead

```
ocr = pytesseract.image_to_string(image)
ocr = ocr.replace("\n\x0c", "") 
print(ocr)
```

**Comment by stweil** [comment]
There is no need to remove the linefeed. Just set the parameter `page_separator` to an empty string, then no linefeed character will be added to the result.

**Comment by canklot** [comment]
> There is no need to remove the linefeed. Just set the parameter `page_separator` to an empty string, then no linefeed character will be added to the result.

Thank you so much it worked. And here is more information for others

> **What page separators are used in txt output by Tesseract 4.0.0?**
> Each page will be terminated by the FF character by default for text output.
> 
> Setting page_separator to the LF character would restore the old behavior of adding an empty line at the end of each page.
> 
> Setting page_separator to an empty string would omit page separators.
> 
> In the newer Tesseract (after September 2017) the include_page_breaks config variable has been removed. The default is now to separate pages with the form feed control character. Use -c page_separator="[PAGE SEPARATOR]" to use a different separator, and -c page_separator='' to disable page breaks entirely.

> \x0c is a form feed; it forces a printer to move to the next sheet of paper. It can also be expressed as \f in Python

[source](https://tesseract-ocr.github.io/tessdoc/FAQ.html#what-page-separators-are-used-in-txt-output-by-tesseract-400)

Example using pytesseract
```
ocr = pytesseract.image_to_string(image, lang='tur',config='-c page_separator='' ')
print(ocr)
```

**Comment by stweil** [comment]
I think that should be `ocr = pytesseract.image_to_string(image, lang='tur',config='-c page_separator=')`
