### ISSUE TITLE
Tesseract failing to recognize very simple text from a clean image

### ISSUE THREAD

**Issue by gbersac** [tesseract-ocr/tesseract#3115]
### Environment

**Tesseract Version**:
tesseract 4.0.0
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.2) : libpng 1.6.36 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE

**Platform**: Windows 10 64-bit

### Current Behavior:
For this Image:
![output](https://user-images.githubusercontent.com/6059511/95027806-bc132180-069b-11eb-95dd-11e20ba345fc.png)
If i run the command `tesseract image.png output` the output is empty
If I run the commande `tesseract image.png output --psm 7` the output is `0/7 53 67 19 54`

### Expected Behavior:
The output should be `07 53 62 19 54` (a 2 instead of a 7 at digit 6 and no `\`).

**Comment by amitdo** [comment]
We never guarantee that Tesseract will give you 100% accurate result, so you should not expect such accuracy, especially with numbers.
