### ISSUE TITLE
Two differents image of the same text, a one that perfecly function, the other one absolutly no.

### ISSUE THREAD

**Issue by theofech** [tesseract-ocr/tesseract#3117]
### Environment

* **Tesseract Version**: 4.00.00Alpha
* **Commit Number**: ?
* **Platform**: Windows 64-bit

### Current Behavior:
I have two image with the same text. I think that the first one (Image1) is more complicated that the second one (Image2).

![Image1](https://user-images.githubusercontent.com/70962226/95216602-8c2a6200-07f2-11eb-9cc3-dafdcb7b9232.png)
![Image2](https://user-images.githubusercontent.com/70962226/95216605-8cc2f880-07f2-11eb-8c7d-925f0cbac4de.PNG)

For the first one, tesseract return the perfect text, and for the second one, a full-wrong text.

Image1 return : 
"
The (quick) [brown] {fox} jumps!
Over the $43,456.78 <lazy> #90 dog
& duck/goose, as 12.5% of E-mail
from aspammer@website.com is spam.
Der ..schnelle" braune Fuchs springt
uber den faulen Hund. Le renard brun
«rapide» saute par-dessus le chien
paresseux. La volpe marrone rapida
salta sopra il cane pigro. El zorro
marron rapido salta sobre el perro
perezoso. A raposa marrom rapida
salta sobre o cao preguigoso.
"

Image 2 return : 

"
mm bui mert Teel o i lae ht Tok Cent
E w al 9 Count To arial te Ifo Gr Cao
be fate od" Ct mre tn ns have rar nn t Phe
nits redtt ln anion a ee mom
E i Aimin Tom ania s
"

### Expected Behavior:

I think that the second image should return a more accurate return, isnt'it ?

### Suggested Fix:
A issue of font ? A issue of size ?

**Comment by zdenop** [comment]
1. Read the docs
2, Use the resent version of project
2. Use user forum for asking question.
