### ISSUE TITLE
Tesseract often confusing Chinese 与 and 写

### ISSUE THREAD

**Issue by peterolson** [tesseract-ocr/tesseract#3124]
Tesseract is often confusing the two characters 与 and 写.

### Environment

* **Tesseract Version**: Tesseract Open Source OCR Engine v5.0.0-alpha.20200223 with Leptonica
* **Platform**: Windows 10 64-bit

### Data set

chi_sim (best)

### Input

![sHdooUZCeJE_100](https://user-images.githubusercontent.com/920512/95975753-61668c00-0e38-11eb-9b15-0e7efaea453b.jpg)

### Current Behavior:

Outputs `与 完了 ， 你 呢 ?`

### Expected Behavior:

Should output `写 完了 ， 你 呢 ?`

**Comment by zxcv421** [comment]
![ads](https://user-images.githubusercontent.com/65371220/97100982-9e135e00-1656-11eb-9ac3-db06c28e5a0b.png)
It gives me the correct output with this image. You should try with a clearer image

**Comment by peterolson** [comment]
The image is already pretty clear, the top part of 写 is not hidden or obstructed and should not be confused with 与.

**Comment by amitdo** [comment]
I don't see how we can fix this. Chinese has thousands of symbols and it's much harder to get good OCR accuracy compared to English.

**Comment by peterolson** [comment]
In that case the documentation shouldn't state that tesseract supports Chinese, since it will be completely useless if it can't differentiate common characters.

**Comment by amitdo** [comment]
Tesseract does supports Chinese,  but you can't expect the same accuracy as English or other languages written in a simple script.

It's not 'useless'. If it useless for you, just don't use it.

It's possible that a custom trained model will give you a better accuracy on certain images, but the training process is not trivial.
