### ISSUE TITLE
Install language with HomeBrew

### ISSUE THREAD

**Issue by stoivo** [tesseract-ocr/tesseract#313]
Is there a way to install new languages with HomeBrew. I would like to install norwegian, the code is nor. I tried to do `brew install tessecract-nor` but that didn't work.
On the Wiki there is detail who to do it for MacPort
https://github.com/tesseract-ocr/tesseract/wiki#homebrew

**Comment by amitdo** [comment]
Here is the Tesseract Formula:
https://github.com/Homebrew/homebrew-core/blob/7e36b9d5885fd710eb3139de2acca506dea59301/Formula/tesseract.rb

**Comment by stoivo** [comment]
I got reply on my question here https://github.com/Homebrew/homebrew-core/issues/797.
