### ISSUE TITLE
Add Kubernetes and Helm Support

### ISSUE THREAD

**Issue by bishtsaurabh5** [tesseract-ocr/tesseract#3131]
Idea
------
Add Kubernetes and Helm Support

Why?
------
Tesseract ocr engine could be used by deploying it in a cluster and then external users can use the application as a service

How
------
Helm will be used a package manager to orchestrate and install the Kubernetes Resources

**Comment by stweil** [comment]
What would be needed on the Tesseract side to support Kubernetes and Helm?

**Comment by bishtsaurabh5** [comment]
I think we would need a frontend to display , So that users can upload the images and in the backend the tesseract-ocr would be running and render the output.
With the help of this it would be easier for the users to simply deploy the ocr engine in kubernetes
OR
We could build a simple rest interface to do it avoiding the need of a frontend altogether.
Any Ideas that you may have ?

**Comment by amitdo** [comment]
We don't plan to implement this feature request.
