### ISSUE TITLE
memory leak in opencl?

### ISSUE THREAD

**Issue by gino0717** [tesseract-ocr/tesseract#3133]
### Environment

* **Tesseract Version**: 

tesseract 4.1.1-rc2-22-g088995
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 OpenCL info:
  Found 1 platform(s).
  Platform 1 name: NVIDIA CUDA.
  Version: OpenCL 1.2 CUDA 11.0.197.
  Found 1 device(s).
    Device 1 name: GeForce GTX 1070.
 Found AVX2
 Found AVX
 Found FMA
 Found SSE

* **Platform**: 

ubuntu 18.04  x64

### Current Behavior:

I use a very simple code to send a pure black image (opencv format) to TessBaseAPI() like:

```
int main(int argc, char *argv[])
{
    while(true){
        Mat gray(100,100,CV_8UC1,Scalar(0));
        tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
        api->Init("./", "engBest", tesseract::OEM_DEFAULT);
        api->SetImage((uchar*)gray.data, gray.cols, gray.rows, 1, gray.cols);
        char* out = api->GetUTF8Text();
        delete []out;
        api->End();
        delete  api;
    }
}
```

I built a tesseract with Opencl, switch the device by type

`export TESSERACT_OPENCL_DEVICE=1   ( use GPU )`

and run the program, now I read the  Memory-Usage in nvidia-smi drastically increase like :

Tue Oct 20 15:43:03 2020       :       484MiB /  8118MiB
Tue Oct 20 15:43:48 2020       :      796MiB /  8118MiB
Tue Oct 20 15:46:39 2020       :   1812MiB /  8118MiB

then it crash after a while.

### Expected Behavior:

when I switch to CPU by type

`export TESSERACT_OPENCL_DEVICE=2`

the memory not increased and release fine

### Suggested Fix:

=   =

**Comment by zdenop** [comment]
Did you read issue tracker and usere forum regarding opencl BEFORE making post?

**Comment by stweil** [comment]
@gino0717, thanks for reporting. We are not working on OpenCL support, so any won't be fixed unless you find a solution yourself and send us a pull request.

**Comment by amitdo** [comment]
I don't understand why we still keep this dead code.

**Comment by zdenop** [comment]
* AFAIR somebody reported OpenCL helps to improve tesseract performance (with tif as input files?) - also in this "state of code"
* It is reasonable to expect that OpenCL /GPU support should have positive impact on performance. Current code could be used as starting point instead of starting from scratch.
* Our problem is that we do not have coder for OpenCL , even from time to time somebody popes up to help in this, we never received PR....

**Comment by amitdo** [comment]
If a developers want an OCR  engine with GPU support, they can use kraken(TensorFlow) or Calamari(PyTorch), without a need to actually write GPU code. If they need C++ support, It will be much easier to port kraken/Calamari to C++ than to port Tesseract to CUDA/OpenCL.

I predict that the situation with the OpenCL code in Tesseract will stay as it is now - useless dead code, that invites questions, issues reporting and suggestion to help that never advanced.

**Comment by amitdo** [comment]
>It will be much easier to port kraken/Calamari to C++ than to port Tesseract to CUDA/OpenCL.

i mean, to port kraken/Calamari to C++ using the framework API.

**Comment by stweil** [comment]
There is a certain demand for Tesseract with GPU support, especially for training. OpenCL or [SYCL](https://en.wikipedia.org/wiki/SYCL) could provide a good base for that task.

Other frameworks like those used by Calamari and Kraken create incompatible models. They could be used perhaps if we had converters which convert those models to Tesseract models. This should be possible if they use network specifications which are also supported by Tesseract. Such converters would also allow using existing models for Calamari and Kraken. [ONNX](https://onnx.ai/) tries to provide such converters, but up to now not for Tesseract models.

**Comment by amitdo** [comment]
https://github.com/mittagessen/kraken/issues/152
