### ISSUE TITLE
tesseract is not recognizing the characters properly

### ISSUE THREAD

**Issue by blueray453** [tesseract-ocr/tesseract#3135]
# Environment

* **Tesseract Version**: tesseract 4.1.1

* **Platform**: `Linux blueray-i5 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linuxe -a` 

### Current Behavior:

![input1](https://user-images.githubusercontent.com/855297/96725640-defb4080-13d2-11eb-960d-080a24d61dcd.jpg)

```
$ tesseract input1.jpg stdout
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 158
San caesar
Save URIs
erty yn tay

eeu ey
```

### Expected Behavior:

OCR should work properly.

**Comment by zdenop** [comment]
Please respect [guidelines ](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md )for posting issue.
