### ISSUE TITLE
Improve japanese lstm model

### ISSUE THREAD

**Issue by kamui-7** [tesseract-ocr/tesseract#3138]
It looks like the official lstm model for japanese is only trained on a few fonts. So I collected around 3500 japanese fonts and was wondering if you guys could improve it using those fonts.

**Comment by Shreeshrii** [comment]
ASAIK, developers at Google are not working on training/retraining of language models for tesseract any more. Community contributions are welcome. 

Please see [Japanese Vertical](https://github.com/zodiac3539/jpn_vert) by @zodiac3539 linked from [Traineddata Contributions](https://github.com/tesseract-ocr/tessdoc/blob/master/Data-Files-Contributions.md)

I also remember some forum posts regarding training for 'informal' Japanese for Comic books - please search in tesseract-ocr google group archives.

You can train with the fonts that you have collected and share the imrpved traineddata.

**Comment by kamui-7** [comment]
Oh ok. Ill be sure to look into it
