### ISSUE TITLE
error teaching tesseract new font

### ISSUE THREAD

**Issue by ggdhines** [tesseract-ocr/tesseract#314]
I have the following image of A's which I want to use to teach Tesseract a new font. (When I include the other characters, the page is mostly taken up and the errors are the same so doesn't seem to be an image with a mostly empty page.) (The original image is in tiff format.)

![active_weather basic exp0](https://cloud.githubusercontent.com/assets/6626461/14989143/5c8c5214-114e-11e6-9aa9-e9baf99eda9a.jpeg)

I have the box file contents which appear to be correct and reasonable.
A 35 3926 66 3965 0
A 102 3926 133 3965 0
A 169 3926 200 3965 0
A 236 3926 267 3965 0
A 303 3926 334 3965 0
A 370 3926 401 3965 0
A 437 3926 468 3965 0
A 504 3926 535 3965 0
A 571 3926 602 3965 0
A 638 3926 669 3965 0

and I have font properties file:
basic 0 0 0 0 0

I enter the commands:
tesseract example.basic.exp0.tiff example.basic.exp0 nobatch box.train
unicharset_extractor example.basic.exp0.tiff

I get the following errors:
APPLY_BOXES:
   Boxes read from boxfile:      10
   Found 10 good blobs.
Generated training data for 1 words
Extracting unicharset from active_weather.basic.exp0.jpeg
Bad box coordinates in boxfile string! ����
Box file format error on line 1; ignored
Bad box coordinates in boxfile string! 

Box file format error on line 6; ignored
Bad box coordinates in boxfile string! 

Box file format error on line 7; ignored
Bad box coordinates in boxfile string! ��
Box file format error on line 10; ignored
Bad box coordinates in boxfile string! 
                                       ��
Box file format error on line 11; ignored
Bad box coordinates in boxfile string! ▒▒%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz���������������������������������������������������������������������������
Box file format error on line 12; ignored
Bad box coordinates in boxfile string! (��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(��(�?�����_ٯ��?h�i��މ��~$�mt��K��lmd��!Y�)
                                                                                                                                        襈�r?$���t��?�(��O��������

The question marks are just gibberish. (And the errors keep on coming). I feel I like I didn't have this problem recently but wondering if some upgrade broke things.  

My versions are:
tesseract 3.05.00dev
 leptonica-1.72
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.51 : libtiff 4.0.3 : zlib 1.2.8

**Comment by amitdo** [comment]
`unicharset_extractor example.basic.exp0.tiff`

You are giving `unicharset_extractor`a tiff image as input file, but it expects a box (text) file.
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract

If you have further questions, please see:
https://github.com/tesseract-ocr/tesseract#support

**Comment by ggdhines** [comment]
d'oh - you are right. Cheers
