### ISSUE TITLE
Simple image FAIL!!!

### ISSUE THREAD

**Issue by ashokavarthanan** [tesseract-ocr/tesseract#3142]
when i input simple image only numbers and letter but it FAILs. Nothing happened.
![test](https://user-images.githubusercontent.com/54305413/97242481-ffcff580-1819-11eb-84ea-8a935d7fa671.png)
is this BUG?
Please Any suggestions for me?

Update:
Also Using
"tesseract test.png test.txt -c tessedit_char_whitelist=0123456789"
"tesseract test.png test.txt nobatch digits"
But Failed.

Update:
Also convert image to grayscale 
still Failed.

**Comment by JefferyChiang** [comment]
try add --psm 6

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Make sure you read docs first, search forum and describe what you already tried.
