### ISSUE TITLE
Trying to read numbers with errors

### ISSUE THREAD

**Issue by CatarinaSMorais** [tesseract-ocr/tesseract#3143]
When reading an image with several numbers tesseract should read -1 and reads it like 4.
![img](https://user-images.githubusercontent.com/64542322/97279049-619c5980-1832-11eb-8786-632312823c02.PNG)
![txt](https://user-images.githubusercontent.com/64542322/97279053-6234f000-1832-11eb-862a-e82c6c8271c9.PNG)

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
