### ISSUE TITLE
Tesseract osd retraining for undetected scripts

### ISSUE THREAD

**Issue by omesh-sharma** [tesseract-ocr/tesseract#3145]
# Hey
---------------------
## i am Using Tesseract OCR for the text extraction form the image :

-------------------------

--------------------
## I need your valuable suggestion for the below mentioned points.
-------------------------
- How can i Retrain osd.traindata file for adding Ethiopic and other scripts , because current osd.traindata file unable to detect few scripts name eg:(ethiopic , gujarati, gurmukhi) but script files for them are available in script directory.
------------------------
---------------------
- which is more accurate for text extraction [LANGUAGE TRAIN DATA FILES]  or [SCRIPT TRAIN DATA FILES]
---------------
------------------
- Does it make any difference to use the script for text extraction instead of language.traindata in term of text extraction accuracy.
-----------------------
---------------------------
Please Share your valuable comments and suggestions for above mentioned list as per your experience with tesseract. 
It'll be very helpful for my final year project.

------------------------------
Contact: sharmaomesh0@gmail.com .
---------------------------------------

Thanks and regards
Omesh sharma

**Comment by amitdo** [comment]
There is no documentation for osd training, so I don't know how to do it (the developer from Google is not available for us any more).

For the other questions, please use our forum.

**Comment by omesh-sharma** [comment]
@amitdo Thanks for your reply.

**Comment by amitdo** [comment]
I don't know, I only used the lang version.
