### ISSUE TITLE
Tesseract 4.0 crash with Capture2Text_CLI

### ISSUE THREAD

**Issue by garry-ut99** [tesseract-ocr/tesseract#3147]
I'm new to this issue tracker, this is my first bug report here, I'm not a Tesseract expert, rather reporting only as an user...appologies if my bug report will turn out to be:
- a duplicate as I'm unable to determine whether any of these: https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+in%3Atitle+crash crashes are related / similiar...
- a Capture2Text_CLI's bug rather than a Tesseract's bug as I'm not sure whether this is a Tesseract's bug or Capture2Text_CLI's bug, hence not sure whether this is a proper issue tracker, the other one is here: https://sourceforge.net/p/capture2text/tickets/search/?q=crash, unfortunately I don't have an account on Sourceforge nor I'm gonna create one... (I'm stick / limited to Github).

> Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Reviewed, I hope I haven't missed anything.

> Please report an issue only for a BUG, not for asking questions.

Crash is definately a bug.

> Note that it will be much easier for us to fix the issue if a test case that
> reproduces the problem is provided. Ideally this test case should not have any
> external dependencies. 

> Provide a copy of the image or link to files for the test case.

Unfortunately unable to provide the image, I run Capture2Text_CLI.exe in a batch script processing random images,
a screenshoot is created, then it's ocr'ed, then it's being overwritten with a new screenshoot and so on,
somehow my script overwrites the last screenshoot... I've noticed it just crashes randomly / occasionaly with a frequency of once every several hundred images...it's kinda annoying.

------------------------

### Environment

Intel Core 2 Duo E8400, 2 GB RAM

* **Tesseract Version**: 4.00
* **Commit Number**: 
tesseract400.dll 
size: `3,03 MB (bajtów: 3 186 688)`
modified: ‎`15 ‎października ‎2017, ‏‎21:07:14`
CRC-32: `cfee53ce`
MD4: `ed0e5c6df0c73adadbf8d4bc1aa47109`
MD5: `f7e91c4f7916aa559958ca5503e872be`
SHA-1: `885187dc642feb9d8e4c382617b42c498594de93`

* **Platform**: 
Windows 7 Ultimate SP1 64bit `6.1.7601.2.1.0.256.1` 
Capture2Text_CLI.exe `start /min Capture2Text_CLI.exe -i screenshoot.png -l Polish --clipboard`
http://capture2text.sourceforge.net/
https://sourceforge.net/p/capture2text/tickets/search/?q=crash
size: `204 KB (bajtów: 209 408)`
modified: ‎`11 ‎sierpnia ‎2019, ‏‎00:31:25`
CRC-32: `836bad33`
   MD4: `31d909b760804405d436dc5e4911abc7`
   MD5: `2f4392dbef15eeed99c8efd23e153ed0`
 SHA-1: `b9976ae1bc745b7f7f5db5592ff104da7a4b705e`

### Current Behavior:

It just crashes randomly / occasionaly with a frequency of once every several hundred images:
`blob_count <= 512:Error:Assert failed:in file E:\Dev\cpp\Tess4\tesseract\ccmain\fixspace.cpp, line 696`

![111](https://user-images.githubusercontent.com/72945564/97732245-8d3f6e00-1ad6-11eb-8701-75dfdac32405.gif)

![222](https://user-images.githubusercontent.com/72945564/97732252-903a5e80-1ad6-11eb-9ee5-8bb699b4b9bc.gif)

### Expected Behavior:

No crashing.

### Suggested Fix:

Don't have a clue, as I'm not a Tesseract expert, rather reporting only as an user...

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.
You have to reproduce your problem with resent version of tesseract executable and provide input image for reproducing error.

**Comment by stweil** [comment]
@garry-ut99, please use also software based on a supported release of Tesseract – 4.1.1 or newer.

**Comment by garry-ut99** [comment]
> zdenop :  Please respect guidelines for posting issue: 

- I have been actually trying to respect them, don't you see? 
- but it seems I have failed, as human beings make mistakes
- however it works vice-versa as well, if you want me to respect your rules, please try to respect my rules as well:

- > garry-ut99 : I'm new to this issue tracker
- > garry-ut99 : this is my first bug report here,
- > garry-ut99 : I'm not a Tesseract expert
- > garry-ut99 : rather reporting only as an user
- > garry-ut99 : appologies if my bug report will turn out to be:
- > garry-ut99 : - a duplicate as I'm unable to determine whether any of these: https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+in%3Atitle+crash crashes are related / similiar...
- > garry-ut99 : - a Capture2Text_CLI's bug rather than a Tesseract's bug as I'm not sure whether this is a Tesseract's bug or Capture2Text_CLI's bug, hence not sure whether this is a proper issue tracker, the other one is here: https://sourceforge.net/p/capture2text/tickets/search/?q=crash, unfortunately I don't have an account on Sourceforge nor I'm gonna create one... (I'm stick / limited to Github).

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

>  zdenop : we do not provide support for 3rd party projects.

Fine, but why manipulating Contributing's rules, it's rude...there is no such info..., I've found this only:

> Contributing: For external programs that use Tesseract (including wrappers and your own program, if you are developer), 

I've explained already that:

- > garry-ut99 : I'm not sure whether this is a Tesseract's bug or Capture2Text_CLI's bug, hence not sure whether this is a proper issue tracker, 


> Contributing: report the issue to the developers of that software if it's possible. 

I've explained that as well:

- > garry-ut99 : the other one is here: https://sourceforge.net/p/capture2text/tickets/search/?q=crash, unfortunately I don't have an account on Sourceforge nor I'm gonna create one... (I'm stick / limited to Github).

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

> zdenop : provide input image for reproducing error.

Again rude, as I've explained that as well:

- > garry-ut99 : Unfortunately unable to provide the image, I run Capture2Text_CLI.exe in a batch script processing random images, a screenshoot is created, then it's ocr'ed, then it's being overwritten with a new screenshoot and so on,somehow my script overwrites the last screenshoot...

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

> Contributing : Only report an issue in the latest official release. Optionally, try to check if the issue is not already solved in the latest snapshot in the git repository.
> zdenop : You have to reproduce your problem with resent version of tesseract executable 
> stweil : @garry-ut99, please use also software based on a supported release of Tesseract – 4.1.1 or newer.

Yeah, that's where I've failed, it seems I've misread that, despite trying to not miss anything:

> > Template : Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

> garry-ut99 : Reviewed, I hope I haven't missed anything.

- I have reviewed, I have been hoping I have been not missing anything, 
- but I've failed because it's a massive wall of text 
- also my rules / points at the beginning of my post prove it can be hard for a Tesseract begginer / user to respect all of the rules.
- also I have been apologising in advance at the beginning of my post
- human beings make mistakes, especially when they are not Tesseract experts

In this situation, it is rude to say: 

> zdenop : "Please respect"

Because it suggests insolently as if I haven't been trying to follow them at all, while the true is I have been trying as much as I could to not miss anything.


- I have spent several years already on github and have been contributing to many repositories to realise how rude some of developers are...
- once I meet such rude admin, I evacuate from the repo immediately, so I'm not going to contribute here anymore

Good bye.

**Comment by stweil** [comment]
@garry-ut99, there is only a handful of volunteers which try to solve the issues, but there are thousands of users who use Tesseract. If we would not apply strict rules for the issues which we accept, any development of Tesseract would stop because we'd drained by issues without being able to act.

Some basic rules are these:

- Ask on the user forum first.
- Don't report problems with third party software.
- Use supported Tesseract releases and don't report issues for unsupported old releases.

Maybe you did not note it, but I tried to help you. Your reply was not nice.

**Comment by garry-ut99** [comment]
@stweil 

I'm aware of what you just have written, but it would be good if you have been aware of what I have written as well: I have been trying to respect all rules, but it is not easy to do so in such big project for a novice user...it's about atmosphere and to not bitch novice users...

> stweil : Maybe you did not note it, but I tried to help you. Your reply was not nice.

Maybe you did not note it but  I have been not talking to you nor about you, nor mentioning your nickname...my comment has been adressed to zdenop only, so please stop manipluating the truth...
