### ISSUE TITLE
Tesseract use cmake & Visual studio2019 build show something error.

### ISSUE THREAD

**Issue by smart8546** [tesseract-ocr/tesseract#3148]
Environment
Tesseract Version: 
1.tesseract 4.1.1
2.leptonica-1.76.0 (Nov  3 2020, 10:24:30) [MSC v.1927 LIB Release x64]
3.libtiff 4.1.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
Platform: Windows 10 64-bit

I use tesseract.exe to OCR jpg to show something error, so i wnat do sothing?

Error message & command:
.\tesseract.exe .\Google.jpg eng
Tesseract Open Source OCR Engine v4.1.1 with Leptonica
Error in pixReadStreamPng: function not present
Error in pixReadStream: png: no pix returned
Error in pixRead: pix not read
Error during processing.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
