### ISSUE TITLE
OpenCL output erroe

### ISSUE THREAD

**Issue by myw31415926** [tesseract-ocr/tesseract#315]
Hello:
    I use Tesseract 3.4 on CentOS 7, and I test it by some sample words.  In general environmental condition(not opencl), it work successfully, and output words is right.  In opencl condition(./configure --enable-opencl), it can work, but output words is garbled. 
    Why?

**Comment by zdenop** [comment]
You should [read the wiki, search issues (also closed), search in the tesseract forum before you post your issues/question](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice).
Opencl is still experimental feature with a lot of open issues (and original committer is not fixing them...)

**Comment by amitdo** [comment]
Hi Zdenko!
I added a note about the state of OpenCL in Tesseract to this wiki page:
https://github.com/tesseract-ocr/tesseract/wiki/TesseractOpenCL
