### ISSUE TITLE
How to OCR a table?

### ISSUE THREAD

**Issue by XtremeGood** [tesseract-ocr/tesseract#3150]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

------------------------

### Environment : Python pytesseract

* **Tesseract Version**:  tesseract v5.0.0-alpha.20200328
* **Commit Number**: 
* **Platform**: Win 10 64 bit

![image](https://user-images.githubusercontent.com/40588378/98450967-7ef0f200-2167-11eb-8fc8-2e9d0c42f010.png)

That's the table and I want to extract out the dataframe so that I can perform linear regression on it.

But in the output I only get garbage.

```

    Code:
    ​
    img = ImageGrab.grabclipboard()
    img = Image.fromarray((np.array(img) * 255).astype(np.uint8))
    df = pytesseract.image_to_string(np.array(img),lang='eng')
    ​
    ​
    ​
    Output:
    ​
    'time 0 3 35 4 45 § rn TS)\nny\nCo 0 0 0.002 0.03 0.155 0.396 0.658 0.903 0.933 09/5 0.993\n\x0c'
    ​
    ​
    ​
    Code:
    img = ImageGrab.grabclipboard()
    img = Image.fromarray((np.array(img) * 255).astype(np.uint8))
    df = pytesseract.image_to_data(np.array(img),lang='eng', output_type='data.frame')
    ​
    Output:
    ​
    	level	page_num	block_num	par_num	line_num	word_num	left	top	width	height	conf	text
    0	1	1	0	0	0	0	0	0	572	70	-1	
    1	2	1	1	0	0	0	12	12	541	47	-1	
    2	3	1	1	1	0	0	12	12	541	47	-1	
    3	4	1	1	1	1	0	14	12	525	11	-1	
    4	5	1	1	1	1	1	14	13	29	10	59	time
    5	5	1	1	1	1	2	66	12	3	9	83	0
    6	5	1	1	1	1	3	96	12	6	9	83	3
    7	5	1	1	1	1	4	129	12	17	9	89	35
    8	5	1	1	1	1	5	175	12	7	9	93	4
    9	5	1	1	1	1	6	221	12	17	9	54	45
    10	5	1	1	1	1	7	272	12	6	9	27	§
    11	5	1	1	1	1	8	322	12	17	9	14	rn
    12	5	1	1	1	1	9	384	12	155	9	5	TS)
    13	4	1	1	1	2	0	12	29	32	10	-1	
    14	5	1	1	1	2	1	12	29	32	10	31	ny
    15	4	1	1	1	3	0	12	47	541	12	-1	
    16	5	1	1	1	3	1	12	47	25	12	65	Co
    17	5	1	1	1	3	2	63	48	6	9	83	0
    18	5	1	1	1	3	3	96	48	6	9	84	0
    19	5	1	1	1	3	4	128	48	32	9	87	0.002
    20	5	1	1	1	3	5	175	48	25	9	95	0.03
    21	5	1	1	1	3	6	221	48	32	9	60	0.155
    22	5	1	1	1	3	7	272	48	32	9	93	0.396
    23	5	1	1	1	3	8	322	48	32	9	93	0.658
    24	5	1	1	1	3	9	373	48	32	9	85	0.903
    25	5	1	1	1	3	10	423	48	32	9	92	0.933
    26	5	1	1	1	3	11	474	48	32	9	66	09/5
    27	5	1	1	1	3	12	521	48	32	9	90	0.993
```

**Comment by Shreeshrii** [comment]
See https://medium.com/@neemagaurav1996/ocring-identifying-page-structure-tesseract-hocr-760f3031f3ac

I get better results after doubling the image size 

![3150](https://user-images.githubusercontent.com/5095331/103155452-35676f80-47c6-11eb-9e15-880d95fe22f6.png)

and then  preprocessing it.

```
 convert 3150.png                           \
> -type Grayscale                             \
> -negate                                     \
> -define morphology:compose=darken           \
> -morphology Thinning 'Rectangle:1x30+0+0<'  \
> -negate                                     \
> 3150-nolines.png
```
![xxx](https://user-images.githubusercontent.com/5095331/103155472-65af0e00-47c6-11eb-854f-69f372e14899.png)

```
(base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract 3150-nolines.png - --psm 4 --tessdata-dir ~/tessdata_best
Time, 0 3 35 4 4.5 5 5.5 6.0 6.2 6.5 6.8
hours
C/o 0 0 0002 003 0.155 0.396 0.658 0.903 0.933 0.975 0.993
(base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract 3150-nolines.png - --psm 4 --tessdata-dir ~/tessdata_fast
Time, 0 3 3.5 4 4.5 5 5.5 6.0 6.2 6.5 6.8
hours
C/o O 0 0.002 0.03 0.155 0.396 0.658 0.903 0.933 0.975 0.993
```

Use tessdata_fast for best results.

**Comment by XtremeGood** [comment]
> 
> 
> See https://medium.com/@neemagaurav1996/ocring-identifying-page-structure-tesseract-hocr-760f3031f3ac
> 
> I get better results after doubling the image size
> 
> ![3150](https://user-images.githubusercontent.com/5095331/103155452-35676f80-47c6-11eb-9e15-880d95fe22f6.png)
> 
> and then preprocessing it.
> 
> ```
>  convert 3150.png                           \
> > -type Grayscale                             \
> > -negate                                     \
> > -define morphology:compose=darken           \
> > -morphology Thinning 'Rectangle:1x30+0+0<'  \
> > -negate                                     \
> > 3150-nolines.png
> ```
> 
> ![xxx](https://user-images.githubusercontent.com/5095331/103155472-65af0e00-47c6-11eb-854f-69f372e14899.png)
> 
> ```
> (base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract 3150-nolines.png - --psm 4 --tessdata-dir ~/tessdata_best
> Time, 0 3 35 4 4.5 5 5.5 6.0 6.2 6.5 6.8
> hours
> C/o 0 0 0002 003 0.155 0.396 0.658 0.903 0.933 0.975 0.993
> (base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract 3150-nolines.png - --psm 4 --tessdata-dir ~/tessdata_fast
> Time, 0 3 3.5 4 4.5 5 5.5 6.0 6.2 6.5 6.8
> hours
> C/o O 0 0.002 0.03 0.155 0.396 0.658 0.903 0.933 0.975 0.993
> ```
> 
> Use tessdata_fast for best results.

That is awesome, thanks @Shreeshrii

**Comment by zdenop** [comment]
You can do that also in python:

```python
import cv2
import numpy
import pytesseract
from PIL import ImageGrab 


image = numpy.array(PIL.ImageGrab.grabclipboard())
result = image.copy()
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
thresh = cv2.threshold(gray, 0, 255,
                       cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)[1]

# Remove horizontal lines
horizontal_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (40, 1))
remove_horizontal = cv2.morphologyEx(thresh,
                                     cv2.MORPH_OPEN,
                                     horizontal_kernel,
                                     iterations=2)
cnts = cv2.findContours(remove_horizontal, cv2.RETR_EXTERNAL,
                        cv2.CHAIN_APPROX_SIMPLE)
cnts = cnts[0] if len(cnts) == 2 else cnts[1]
for c in cnts:
    cv2.drawContours(result, [c], -1, (255, 255, 255), 5)

# Remove vertical lines
vertical_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (1, 40))
remove_vertical = cv2.morphologyEx(thresh,
                                   cv2.MORPH_OPEN,
                                   vertical_kernel,
                                   iterations=2)
cnts = cv2.findContours(remove_vertical, cv2.RETR_EXTERNAL,
                        cv2.CHAIN_APPROX_SIMPLE)
cnts = cnts[0] if len(cnts) == 2 else cnts[1]
for c in cnts:
    cv2.drawContours(result, [c], -1, (255, 255, 255), 5)

pytesseract.pytesseract.tesseract_cmd = r'F:\win64_llvm\bin\tesseract.exe'
tessdata_dir_config = r'--tessdata-dir "f:\Project-Personal\tessdata_best\tessdata"'
tessdata_dir_config += ' --oem 3 --psm 1'

df = pytesseract.image_to_string(np.array(result),
                                 lang='eng',
                                 config=tessdata_dir_config,
                                 output_type='string')
print(df)
```

with result::

```
Time, 0 3 35 4 4.5 5 5.5 6.0 6.2 6.5 6.8
hours
C/o 0 0 0002 003 0.155 0.396 0.658 0.903 0.933 0.975 0.993
```

You can also try '[tessdata with legacy engine](https://github.com/tesseract-ocr/tessdata)'  (`--oem 0 --psm 4`):

```
Time, 0 3 3.5 4 4.5 S 5.5 6.0 6.2 6.5 6.8
hours
C/Co 0 0 0.002 0.03 0.155 0.396 0,658 0.903 0.933 0,975 0.993
```

**Comment by Shreeshrii** [comment]
Thanks @zdenop 
You can add the tip to use legacy engine to FAQ and the python script as an example.
