### ISSUE TITLE
Apparent infinite loop on file (attached)

### ISSUE THREAD

**Issue by rcordovano** [tesseract-ocr/tesseract#3154]
### Environment

* **Tesseract Version**: v4.0.0.20190314
* **Commit Number**: Unknown
* **Platform**: Windows, 64-bit 

### Current Behavior:
Tesseract is integrated into the open source cyber forensics software Autopsy. We spawn a Tesseract process to do OCR on selected files. A user reported that Autopsy hung while processing a particular file (attached). We ascertained that the hang was due to a "runaway" Tesseract process analyzing the file. We are mitigating by placing a timeout on the Tesseract process, but you might be able to make a fix. The Autopsy issue report is at https://github.com/sleuthkit/autopsy/issues/6432. 

### Expected Behavior:
Tesseract process completes.

### Suggested Fix:
Unknown.

![autopsy-issue-6432](https://user-images.githubusercontent.com/1713605/99421121-0b1fb980-28cc-11eb-85ec-c49bdcc43c0e.png)

**Comment by stweil** [comment]
Tesseract 4.0.0 is an unsupported old version.

Latest Tesseract needs less than 3 seconds for the test image.

**Comment by egorpugin** [comment]
Please use newer version.
