### ISSUE TITLE
problem with unicharest

### ISSUE THREAD

**Issue by ggdhines** [tesseract-ocr/tesseract#316]
I'm following the instructions for creating a new font with Tesseract at http://michaeljaylissner.com/posts/2012/02/11/adding-new-fonts-to-tesseract-3-ocr-engine/ and am getting a unicharest file that looks like:

4
NULL 0 NULL 0
Joined 0 0,255,0,255,0,0,0,0,0,0 NULL 0 0 0     # Joined [4a 6f 69 6e 65 64 ]
|Broken|0|1 0 0,255,0,255,0,0,0,0,0,0 NULL 0 0 0        # Broken
A 0 0,255,0,255,0,0,0,0,0,0 NULL 0 0 0  # A [41 ]

(just trying with one character right now) . Later on I get an error:
Bad properties for index 3, char A: 0,255 0,255 0,0 0,0 0,0

My box file is looking right. Any suggestions on how to debug this?

**Comment by amitdo** [comment]
Use the official guide at https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract

You missed this step: https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#set_unicharset_properties-new-in-303

See also my answer here: https://github.com/tesseract-ocr/tesseract/issues/318

**Comment by ggdhines** [comment]
Seems to be a duplicate of #318 for now
