### ISSUE TITLE
Cannot specify custom language, tessdata dir and output formats simultaneously when using command line 

### ISSUE THREAD

**Issue by martindobrev** [tesseract-ocr/tesseract#3164]
### Environment

* **4.1.1**: 
* **Linux martin-VirtualBox 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux**: 

### Current Behavior:
When running these commands in the console, no errors shall be present:

```
tesseract test.png out pdf hocr                                    
-> SUCCESS

tesseract test.png out -l deu+fra pdf hocr
-> SUCCESS

test.png out --tessdata-dir ~/tessdata/ -l deu+fra pdf hocr
->read_params_file: Can't open pdf
->read_params_file: Can't open hocr

tesseract test.png out pdf hocr --tessdata-dir /home/temp -l deu+fra
->read_params_file: Can't open --tessdata-dir
->read_params_file: Can't open /home/temp
->read_params_file: Can't open -l
->read_params_file: Can't open deu+fra

```

### Expected Behavior:
Selecting languages, tessdata-dir and output formats simultaneously shall be possible

### Suggested Fix:
Maybe something is wrong when the parameters are read

**Comment by zdenop** [comment]
Please use  tesseract user forum for asking support.  This is not tesseract error: just you do not understand what command parameters means and how they effect each other...
