### ISSUE TITLE
use deep of tesseract

### ISSUE THREAD

**Issue by netwons** [tesseract-ocr/tesseract#3166]
How can I deeply tess?
im lang persion but not good
example:

![fff](https://user-images.githubusercontent.com/5950068/100837971-d7758f80-3486-11eb-8257-6be86c837eff.jpeg)

**He does not find everyone**

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Don't forget to read documentation first.
