### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sammar80** [tesseract-ocr/tesseract#3169]
Hey , I am trying to generate my model using images and gt.txt but I am getting this error

make training START_MODEL=eng MODEL_NAME=img PSM=8 TESSDATA=/usr/local/share/tessdata
lstmtraining \
  --debug_interval 0 \
  --traineddata data/img/img.traineddata \
  --old_traineddata /usr/local/share/tessdata/eng.traineddata \
  --continue_from data/eng/img.lstm \
  --learning_rate 0.0001 \
  --model_output data/img/checkpoints/img \
  --train_listfile data/img/list.train \
  --eval_listfile data/img/list.eval \
  --max_iterations 10000 \
  --target_error_rate 0.01
Loaded file data/eng/img.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 111 to 111!
Num (Extended) outputs,weights in Series:
  1,36,0,1:1, 0
Num (Extended) outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys64:64, 20736
  Lfx96:96, 61824
  Lrx96:96, 74112
  Lfx512:512, 1247232
  Fc111:111, 0
Total weights = 1404064
Previous null char=110 mapped to 110
Continuing from data/eng/img.lstm
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_7pgfigm.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_4tahm4_.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_cr8ezv4.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_b8ny7vf.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_4qxwhrz.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_2o1nblx.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_28xze1g.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_3zg2b3a.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_2ow51ra.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp__s2_ayk.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_3sqpb25.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_2s9vt7w.lstmf
Makefile:266: recipe for target 'data/img/checkpoints/img_checkpoint' failed
make: *** [data/img/checkpoints/img_checkpoint] Segmentation fault (core dumped)
melodic@melodic:~/tesseract_ocr/tesstrain$ sudo make training START_MODEL=eng MODEL_NAME=img PSM=8 TESSDATA=/usr/local/share/tessdata
[sudo] password for melodic: 
lstmtraining \
  --debug_interval 0 \
  --traineddata data/img/img.traineddata \
  --old_traineddata /usr/local/share/tessdata/eng.traineddata \
  --continue_from data/eng/img.lstm \
  --learning_rate 0.0001 \
  --model_output data/img/checkpoints/img \
  --train_listfile data/img/list.train \
  --eval_listfile data/img/list.eval \
  --max_iterations 10000 \
  --target_error_rate 0.01
Loaded file data/eng/img.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 111 to 111!
Num (Extended) outputs,weights in Series:
  1,36,0,1:1, 0
Num (Extended) outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys64:64, 20736
  Lfx96:96, 61824
  Lrx96:96, 74112
  Lfx512:512, 1247232
  Fc111:111, 0
Total weights = 1404064
Previous null char=110 mapped to 110
Continuing from data/eng/img.lstm
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_7pgfigm.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_4tahm4_.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_b8ny7vf.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_cr8ezv4.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_28xze1g.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp__s2_ayk.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_4qxwhrz.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_2o1nblx.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_2ow51ra.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_3zg2b3a.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_3sqpb25.lstmf
Loaded 1/1 lines (1-1) of document data/img-ground-truth/tmp_2s9vt7w.lstmf
Makefile:266: recipe for target 'data/img/checkpoints/img_checkpoint' failed
make: *** [data/img/checkpoints/img_checkpoint] Segmentation fault (core dumped

**Comment by Shreeshrii** [comment]
Your start_model needs to be from tessdata_best.

**Comment by sammar80** [comment]
@Shreeshrii  thank you now the training completed successfully  but when I try to test the model I get this error
tesseract tmprrtzmvdd.tif ot -l img
Failed to load any lstm-specific dictionaries for lang img!!
Tesseract Open Source OCR Engine v4.1.1 with Leptonica
Page 1
Empty page!!
Empty page!!

**Comment by sammar80** [comment]
thank you it worked I used oem 1 for instead of 2

**Comment by juhonkang** [comment]
I started with best data model but still get the error, any help please!
