### ISSUE TITLE
configure of tesseract is failing for "checking for pixCreate in -llept"

### ISSUE THREAD

**Issue by kavikon** [tesseract-ocr/tesseract#317]
Command run in tesseract 3.04.01 src on redhat linux 7.2 64 bit
./configure --prefix=/apps/tesseract --with-extra-libraries=/apps/build/lib --enable-debug CXPFLAGS="-I/apps/build/include -I/apps/build/include/libpng16 -I/apps/build/include/leptonica -lpng -ljpeg -lz" LDFLAGS="-L/apps/build/lib" LIBLEPT_HEADERSDIR=/apps/build/include/leptonica
my build location is /apps/build
This errors for 
checking for pixCreate in -llept... no
configure: error: leptonica library missing

I have kept my leptonica's liblept.a in /apps/build/lib but stil it fails with this error.
I am attaching the configure.log

any help is much appreciated
[configlog.txt](https://github.com/tesseract-ocr/tesseract/files/253517/configlog.txt)

**Comment by amitdo** [comment]
There is no environment variable named "CXPFLAGS".
There are "CFLAGS", "CPPFLAGS",  "CXXFLAGS".

**Comment by kavikon** [comment]
even after correcting to CXXFLAGS or CPPFLAGS it still throws the same error
were you able to compile it in linux in non standard location?

**Comment by amitdo** [comment]
Didn't try this...

**Comment by kavikon** [comment]
Need urgent help from any of the developers... All help is appreciated.I was trying to install it in linux never realized that it was not tried by any one successfully before.

**Comment by zdenop** [comment]
IMO this is not tesseract issue. If you decided to install libs in non standard location you should know how to deal with it. One of examples suggestion is on [wiki](https://github.com/tesseract-ocr/tesseract/wiki/Compiling#install-elsewhere--without-root). If it does not work - [tesseract user forum](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice).
