### ISSUE TITLE
Slowness in Tesseract OCR

### ISSUE THREAD

**Issue by SreemathiS** [tesseract-ocr/tesseract#3174]
I am currently working on performing OCR using Tesseract. I am using Tess4j version 4.4.1 to scan documents. We notice that any clear document is taking 20-30 sec to perform OCR. But if the image has some distortions or unclear its taking more than a min to OCR. I would like to understand what are all the major factors that would impact Tess4j performance. All our images would have distortions, have many lines, drawings, hand written (though hand written need not be OCRed). Also, we would like to understand how to get rid of this slowness? 

As per our project requirements we have nearly 650K documents to scan. So this slowness will definitely impact. 

Following is the code snippet we are using  

Tesseract tesseract = new Tesseract();
tesseract.setLanguage("eng");
tesseract.setDatapath(dataDirectory.toString());
String result = tesseract.doOCR(image);

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Make sure you read docs first, search forum and other issues (even closed).
