### ISSUE TITLE
Do I need to download Tesseract 5.0 in order to fix inword spacing?

### ISSUE THREAD

**Issue by kylefoley76** [tesseract-ocr/tesseract#3185]
I have the same problem described here

https://github.com/tesseract-ocr/tesseract/issues/781

My problem is that that issue was solved it seems to me in Tesseract 5.0 here
https://github.com/tesseract-ocr/tesseract/issues/781#issuecomment-329702881

That was in 2017 and still there is no stable version of Tesseract 5.0, so I'm a little skeptical that  that is the real solution. If that is the real solution then I'm a little worried that installing Tesseract 5.0 on my mac will be too hard since one cannot now install tesseract 5.0 using `brew`.  Whenever I have to install something manually without brew or pip, it is always an enormous struggle.

**Comment by amitdo** [comment]
The fix was applied years ago and should be available in the latest 4.x version.

If it's not working for you in that version, it won't work in 5.0 either.

**Comment by kylefoley76** [comment]
Please don't close this thread.  I still have some questions I want to ask but have not yet had time to ask them.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support
