### ISSUE TITLE
API documentation for version 5

### ISSUE THREAD

**Issue by clarkk** [tesseract-ocr/tesseract#3192]
Hi
Where to find documentation for the API?

There used to be something under the Wiki

**Comment by Shreeshrii** [comment]
See https://tesseract-ocr.github.io/tessdoc/

https://tesseract-ocr.github.io/tessapi/5.x/index.html

I am not sure whether it has been updated recently.

**Comment by Shreeshrii** [comment]
Also see

https://abi-laboratory.pro/?view=timeline&l=tesseract

https://abi-laboratory.pro/index.php?view=changelog&l=tesseract&v=current

**Comment by clarkk** [comment]
Is there some examples available like there used to be? :)

**Comment by Shreeshrii** [comment]
https://tesseract-ocr.github.io/tessdoc/#usage

**Comment by amitdo** [comment]
For the most updated API documentation you can simply read the header files:

https://github.com/tesseract-ocr/tesseract/tree/master/include/tesseract

**Comment by clarkk** [comment]
It would be great though if it was possible to get some simple best practice examples on the new API v5 :)
