### ISSUE TITLE
RFC: Move code written in languages other than C++ to  separate repos

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#3197]
* Training tools
  * Bash
  *  Python
* ScrollView - Java

ScrollView is a 'visual ocr debugger'. It's not supposed to be used by regular users. The Java code does not link to the C++ code. It uses sockets to talk with Tesseract. It's possible to make it a standalone program by changing just autotools related files. Users will be able to install it before or even after Tesseract installation.

**Comment by amitdo** [comment]
We can keep the C++ part of ScrollView in the main repo.

**Comment by egorpugin** [comment]
I propose to postpone this. We could consider it later.

**Comment by amitdo** [comment]
Okay :)

**Comment by ka7iu** [comment]
Ola look my device

śr., 30 gru 2020, 19:58 użytkownik Egor Pugin <notifications@github.com>
napisał:

**Comment by Shreeshrii** [comment]
As suggested earlier by @stweil in some other thread, I support moving the training tools python scripts to the tesstrain repo. These should then be modified to support creation of single line images and ground truth so that the files can be easily used by Makefile in tesstrain repo.

Is it possible to move the files across repos so as to retain the history?

**Comment by stweil** [comment]
It should be possible to retain the history for that file.

Would we remove the shell scripts for training from the `tesseract` repository at the same time?

**Comment by Shreeshrii** [comment]
>Would we remove the shell scripts for training from the tesseract repository at the same time?

That will also  require changes to tessdoc tesstutorial documentation. We should mark the current version with shell scripts for tesseract 4 and create a new page for tesseract 5.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesstrain/commit/37f4fa46d8fe

So I think the Python code can be removed now.

**Comment by stweil** [comment]
Yes, that's right. Done now with commit e6f15621c2ab2ecbfabf656942d8ef66f03b2d55.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/commit/93348a83a324a4
