### ISSUE TITLE
Can´t update Tesseract (Pro) Theme in Wordpress

### ISSUE THREAD

**Issue by brunoavalancha** [tesseract-ocr/tesseract#3209]
Hi,

I have been receiving emails from WordPress informing me that I need to update the Tesseract(Pro) theme from my current version (3.0.6) to the newest one (3.9.4). I have tried to do this manually by going to the dashboard and then to the updates section. After I update it manually it confirms the theme was updated, however, the next day I receive another email with the same issue and the problem keeps repeating every day.

I have also tried to update it by going to the Appearance and then to the themes section and my current theme doesn’t show any updates pending.

WordPress is updated to the latest version, as the plugins and they don’t seem to have any conflict.

How can I update my theme?

Thank you for your time and assistance.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by amitdo** [comment]
This repo is hosting Tesseract the ocr engine, not Tesseract the WP theme.
