### ISSUE TITLE
V4.0.0 / Debian 10 / Could not set option: hocr_char_boxes=1 

### ISSUE THREAD

**Issue by JeanLouisMassei** [tesseract-ocr/tesseract#3212]
Environment

* **Tesseract Version**: 4.0.0
* **Platform**: Debian Buster, 10

Current Behavior:
command "tesseract /path/to/file stdout -c hocr_char_boxes=1 hocr" produces standard horc result, (1 line = 1 word) and I get this error : "Could not set option: hocr_char_boxes=1"

Expected Behavior: 
hocr with 1 line = 1 char, like in the 5.0.0 version for Windows

Suggested Fix: 
Please add the flag "hocr_char_boxes=1" to debian version, so it will have the same result as Tesseract 5.0.0 on Windows

**Comment by stweil** [comment]
Tesseract 4.0.0 is no longer supported. Please use a newer version which supports that parameter.
