### ISSUE TITLE
box.train gives error message

### ISSUE THREAD

**Issue by vigneshg10** [tesseract-ocr/tesseract#3213]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: <!-- 5.0.0-alpha-20201231>
* **Commit Number**: <!-- ca114ace387f86821ce061713dc9aa3cc33a3cad >
* **Platform**: <!-- ubuntu 18.04.1 64-bit >

### Current Behavior: Error in processing. No tr file generated
![inrsym](https://user-images.githubusercontent.com/2225978/103508361-db7e3e00-4e86-11eb-98b9-57fb031a11f9.jpg)
use this file to create the box file and then try to create the tr file using box.train. The commands used are:
tesseract inrsym.jpg inrsym.exp0 makebox
tesseract inrsym.jpg inrsym.exp0 box.train
Page 1
Error during processing

**Comment by Shreeshrii** [comment]
You have used wrong file names. the following works:

```
(base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract inrsym.jpg inrsym makebox
Tesseract Open Source OCR Engine v5.0.0-alpha-20201231-111-ge1b9 with Leptonica
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 344

(base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract inrsym.jpg inrsym box.train
Tesseract Open Source OCR Engine v5.0.0-alpha-20201231-111-ge1b9 with Leptonica
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 344
APPLY_BOXES:
   Boxes read from boxfile:      29
   Found 29 good blobs.
Generated training data for 7 words

(base) ubuntu@tesseract-ocr-1:~/TEST$ ls inrsym* -l
-rw-rw-r-- 1 ubuntu ubuntu   659 Jan 12 11:19 inrsym.box
-rw-rw-r-- 1 ubuntu ubuntu 48964 Jan  4 06:47 inrsym.jpg
-rw-rw-r-- 1 ubuntu ubuntu 52454 Jan 12 11:19 inrsym.tr
(base) ubuntu@tesseract-ocr-1:~/TEST$
```

**Comment by vigneshg10** [comment]
thanks @Shreeshrii... it works...
