### ISSUE TITLE
Tesseract 4.x using Tess4j java wrapper leaking handles while disposing TessBaseAPIDelete 

### ISSUE THREAD

**Issue by JustCodeJJ** [tesseract-ocr/tesseract#3214]
Hi Team,

I am using Tess4j 4.3.1 which internally uses Tesseract 4.0 to do the OCR. But I started seeing the handles are leaking while disposing the API. This is not happening with Tess4j 3.5.3 which uses Tesseract 3.X. 

Is there a known issue?

Tesseract.class
    /**
     * Releases all of the native resources used by this instance.
     */
    protected void dispose() {
        if (api != null && handle != null) {
            **api.TessBaseAPIDelete(handle);**  --> Leaking the handles 
        }
    }

**Comment by zdenop** [comment]
1. Please respect guidelines for posting issue: we do not provide support for 3rd party projects (e.g. tesseract wrappers).
2.  Reproduce your problem with resent version of and with C/C++ code.  Tesseract 4.0 is too old.
