### ISSUE TITLE
fatal error LNK1169: one or more multiply defined symbols found

### ISSUE THREAD

**Issue by leminhyen2** [tesseract-ocr/tesseract#3222]
### Environment

* **Tesseract Version**: <5.0 Alpha>
* **Commit Number**: <built from source -->
* **Platform**: <Windows, 64-bit -->

### Current Behavior:
I'm trying to do a release build according to the tutorial https://github.com/tesseract-ocr/tessdoc/blob/master/Compiling.md#windows

But I encountered these errors near the end

org.sw.demo.tiff-4.1.0.lib(tif_error.c.148758b9.obj) : error LNK2005: TIFFSetErrorHandler already defined in tiff.lib(t
iff.dll) [C:\Users\Admin\Pictures\tesseract\build\tesseract.vcxproj]
org.sw.demo.tiff-4.1.0.lib(tif_warning.c.3b8474da.obj) : error LNK2005: TIFFSetWarningHandler already defined in tiff.l
ib(tiff.dll) [C:\Users\Admin\Pictures\tesseract\build\tesseract.vcxproj]
C:\Users\Admin\Pictures\tesseract\build\bin\Release\tesseract.exe : fatal error LNK1169: one or more multiply defined s
ymbols found [C:\Users\Admin\Pictures\tesseract\build\tesseract.vcxproj]

### Expected Behavior:
Everything runs as expected

**Comment by egorpugin** [comment]
Does it happen on clear checkout? Try the latest master, not tag.

**Comment by leminhyen2** [comment]
I tried to clean install again. It worked! 

Also, if you don't mind, may I ask how to generate a big libtesseract.dll file? I'm a newbie at C++

After I ran through "cmake --build . --config Release --target install" a tesseract.exe was generated but I want a libtesseract.dll to link to my C++ program.

I want to compile everything so that I can disable openMP

**Comment by egorpugin** [comment]
Try `-DBUILD_SHARED_LIBS=1` on cmake generation command (not  `cmake --build`!).

**Comment by minskiter** [comment]
> Try `-DBUILD_SHARED_LIBS=1` on cmake generation command (not on `cmake --build`!).



> Try `-DBUILD_SHARED_LIBS=1` on cmake generation command (not on `cmake --build`!).

# github.com/otiai10/gosseract/v2
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `Create':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:14: undefined reference to `tesseract::TessBaseAPI::TessBaseAPI()'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `Free':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:21: undefined reference to `tesseract::TessBaseAPI::End()'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o:C:/Users/minsk/go/pkg/mod/github.com/otiai10/gosseract/v2@v2.3.1/include/tesseract/baseapi.h:209: undefined reference to `tesseract::TessBaseAPI::Init(char const*, char const*, tesseract::OcrEngineMode, char**, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, bool)'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o:C:/Users/minsk/go/pkg/mod/github.com/otiai10/gosseract/v2@v2.3.1/include/tesseract/baseapi.h:209: undefined reference to `tesseract::TessBaseAPI::Init(char const*, char const*, tesseract::OcrEngineMode, char**, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, bool)'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `SetPixImage':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:81: undefined reference to `tesseract::TessBaseAPI::SetImage(Pix*)'
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:82: undefined reference to `tesseract::TessBaseAPI::GetSourceYResolution()'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `GetBoundingBoxesVerbose':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:119: undefined reference to `tesseract::TessBaseAPI::Recognize(tesseract::ETEXT_DESC*)'
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:125: undefined reference to `tesseract::TessBaseAPI::GetIterator()'
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:156: undefined reference to `tesseract::LTRResultIterator::Confidence(tesseract::PageIteratorLevel) const'
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:157: undefined reference to `tesseract::PageIterator::BoundingBox(tesseract::PageIteratorLevel, int*, int*, int*, int*) const'
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:126: undefined reference to `tesseract::PageIterator::Empty(tesseract::PageIteratorLevel) const'
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:127: undefined reference to `tesseract::PageIterator::Empty(tesseract::PageIteratorLevel) const'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `GetBoundingBoxes':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:183: undefined reference to `tesseract::TessBaseAPI::Recognize(tesseract::ETEXT_DESC*)'
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:184: undefined reference to `tesseract::TessBaseAPI::GetIterator()'
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:195: undefined reference to `tesseract::LTRResultIterator::Confidence(tesseract::PageIteratorLevel) const'
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:196: undefined reference to `tesseract::PageIterator::BoundingBox(tesseract::PageIteratorLevel, int*, int*, int*, int*) const'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o:C:/Users/minsk/go/pkg/mod/github.com/otiai10/gosseract/v2@v2.3.1/include/tesseract/baseapi.h:209: undefined reference to `tesseract::TessBaseAPI::Init(char const*, char const*, tesseract::OcrEngineMode, char**, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, bool)'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `GetDataPath':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:227: undefined reference to `tesseract::TessBaseAPI::TessBaseAPI()'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `Clear':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:29: undefined reference to `tesseract::TessBaseAPI::Clear()'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `ClearPersistentCache':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:35: undefined reference to `tesseract::TessBaseAPI::ClearPersistentCache()'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `SetVariable':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:75: undefined reference to `tesseract::TessBaseAPI::SetVariable(char const*, char const*)'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `SetPixImage':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:83: undefined reference to `tesseract::TessBaseAPI::SetSourceResolution(int)'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `SetPageSegMode':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:90: undefined reference to `tesseract::TessBaseAPI::SetPageSegMode(tesseract::PageSegMode)'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `GetPageSegMode':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:95: undefined reference to `tesseract::TessBaseAPI::GetPageSegMode() const'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `UTF8Text':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:100: undefined reference to `tesseract::TessBaseAPI::GetUTF8Text()'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `HOCRText':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:105: undefined reference to `tesseract::TessBaseAPI::GetHOCRText(int)'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `Version':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:207: undefined reference to `tesseract::TessBaseAPI::Version()'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `GetDataPath':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:229: undefined reference to `tesseract::TessBaseAPI::GetDatapath()'
C:\Users\minsk\AppData\Local\Temp\go-build854445650\b051\_x003.o: In function `__tcf_0':
..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:227: undefined reference to `tesseract::TessBaseAPI::~TessBaseAPI()'
collect2.exe: error: ld returned 1 exit status
![Uploading image.png…]()

**Comment by minskiter** [comment]
![image](https://user-images.githubusercontent.com/23184022/105707184-83020400-5f4d-11eb-86fd-b04979c126be.png)

**Comment by zdenop** [comment]
@minskiter : error did not come from tesseract, but from building 3rd party project:

>  In function Create': ..\..\..\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:14: undefined reference to tesseract::TessBaseAPI::TessBaseAPI()'

1. We do not support 3rd party project because lack of capacity. 
2. Use not stable version of any library in 3rd party project is bad decision.

**Comment by minskiter** [comment]
> @minskiter : error did not come from tesseract, but from building 3rd party project:
> 
> > In function Create': ......\go\pkg\mod\github.com\otiai10\gosseract\v2@v2.3.1/tessbridge.cpp:14: undefined reference to tesseract::TessBaseAPI::TessBaseAPI()'
> 
> 1. We do not support 3rd party project because lack of capacity.
> 2. Use not stable version of any library in 3rd party project is bad decision.

Thank you! I will try the stable version of tesseract.
