### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by LiteracyFanatic** [tesseract-ocr/tesseract#3228]
### Environment

* **Tesseract Version**: 5.0.0
* **Commit Number**: b0e46085f48d206797ad36ba643dbe9f12ad157a
* **Platform**: `Linux jordan-laptop 5.10.6-arch1-1 #1 SMP PREEMPT Sat, 09 Jan 2021 18:22:35 +0000 x86_64 GNU/Linux`

### Current Behavior:
Since commit e1b9f1b446ceaef3825934596aa63981f6a69a12, tesseract builds correctly with `make` but fails to install with `make install`. Installation works correctly when built with cmake though.

### Expected Behavior:
`make install` works.

[configure.log](https://github.com/tesseract-ocr/tesseract/files/5809282/configure.log)
[make.log](https://github.com/tesseract-ocr/tesseract/files/5809272/make.log)
[make-install.log](https://github.com/tesseract-ocr/tesseract/files/5809273/make-install.log)

**Comment by stweil** [comment]
This is fixed in commit 7c5415a2c1c10fa3be9f25763e2300732d5e72e5.
