### ISSUE TITLE
Segfault using my training data

### ISSUE THREAD

**Issue by amorri40** [tesseract-ocr/tesseract#324]
Tesseract works fine with the original eng.traineddata but when i use my own it segfaults when running the standard:

```
tesseract test.jpg test.txt
```

I have attached my training data if it helps:
[ali_traineddata_files.zip](https://github.com/tesseract-ocr/tesseract/files/268691/ali_traineddata_files.zip)

Here is the output from llvmdb:
```bash
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Warning in pixReadMemJpeg: work-around: writing to a temp file
Process 57115 stopped
* thread #1: tid = 0x2101d5, 0x00000001000e94a9 libtesseract.3.dylib`tesseract::Classify::ComputeCharNormArrays(FEATURE_STRUCT*, INT_TEMPLATES_STRUCT*, unsigned char*, unsigned char*) + 161, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x00000001000e94a9 libtesseract.3.dylib`tesseract::Classify::ComputeCharNormArrays(FEATURE_STRUCT*, INT_TEMPLATES_STRUCT*, unsigned char*, unsigned char*) + 161
libtesseract.3.dylib`tesseract::Classify::ComputeCharNormArrays:
->  0x1000e94a9 <+161>: movl   0x8(%r9), %r10d
    0x1000e94ad <+165>: testl  %r10d, %r10d
    0x1000e94b0 <+168>: jle    0x1000e94eb               ; <+227>
    0x1000e94b2 <+170>: movb   (%r15,%r14), %cl
```

Many thanks :)

**Comment by amitdo** [comment]
Please read this:
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#generate-the-unicharset-file

**Comment by amitdo** [comment]
... and this:
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#questions-about-the-training-process

**Comment by amorri40** [comment]
Thanks for your replies but after reading those and trying from scratch again, it still throws this segfault, is their another way i can debug it?

**Comment by amitdo** [comment]
Your unicharset file looks wrong.

Either you didn't run set_unicharset_properties or you did run it, but in a wrong way.

A debugger won't help you here.  

https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#set_unicharset_properties

**Comment by amitdo** [comment]
@zdenop, please close this issue.
