### ISSUE TITLE
lstmtraining terminates with resource error

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#3240]
A training process with latest code terminates after loading of a certain number (about 16000) of `lstmf` files:

    Loaded 1/1 lines (1-1) of document data/ocr-d-ground-truth/dta19/1827-heine_reisebilder02/01242.lstmf
    terminate called after throwing an instance of 'std::system_error'
      what():  Resource temporarily unavailable

With address sanitizer, it also aborts with a slightly different error message:

    Loaded 1/1 lines (1-1) of document data/ocr-d-ground-truth/dta19/1871-bauer_buehnenleben/01112.lstmf
    ==1494716==ERROR: AddressSanitizer failed to allocate 0xfe000 (1040384) bytes at address fdbae764000 (errno: 12)
    ==1494716==ReserveShadowMemoryRange failed while trying to map 0xfe000 bytes. Perhaps you're using ulimit -v

**Comment by stweil** [comment]
The abort happens in function `DocumentData::LoadPageInBackground` in the evaluation thread (`LSTMTester::RunEvalSync`):

    464       thread = std::thread(&tesseract::DocumentData::ReCachePages, this);

**Comment by Shreeshrii** [comment]
Related issues reported earlier:

https://github.com/tesseract-ocr/tesseract/issues/3111

https://github.com/tesseract-ocr/tesseract/issues/3109

**Comment by stweil** [comment]
Yes, issue #3111 reports the same problem, so I close the issue here.
