### ISSUE TITLE
Some error when using arabic language pack

### ISSUE THREAD

**Issue by adamdylan** [tesseract-ocr/tesseract#325]
This is command i tried:
`tesseract photo.jpeg out -l ara`
This is the error
```
Tesseract Open Source OCR Engine v3.04.00 with Leptonica
Cube ERROR (CubeRecoContext::Load): unable to read cube language model params from /opt/local/share/tessdata/ara.cube.lm
Cube ERROR (CubeRecoContext::Create): unable to init CubeRecoContext object
init_cube_objects(false, &tessdata_manager):Error:Assert failed:in file tessedit.cpp, line 205
```

Obviously i installed tesseract and the arabic language pack.
Thanks

**Comment by amitdo** [comment]
Run: `tesseract --list-langs`
Do you get `ara` in the output?

**Comment by adamdylan** [comment]
oops.
This is what i get:
`Error opening data file /opt/local/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.`
Any idea why? I ran `sudo port install tesseract-ara ` on my mac

**Comment by zdenop** [comment]
And the message is clear: there is no /opt/local/share/tessdata/eng.traineddata 
English traineddata is must for correct running of tesseract (because it is used for fallback).

**Comment by adamdylan** [comment]
I installed english too.
now runing:`tesseract --list-langs` return arabic and english.
still same error when runing `tesseract photo.jpeg out -l ara`
Any help?

**Comment by zdenop** [comment]
Do you have installed arabic cube files (e.g. [ara.cube.lm](https://github.com/tesseract-ocr/tessdata/blob/master/ara.cube.lm))?

**Comment by adamdylan** [comment]
Hey, its now running but not working :(
This is output:
`Warning in pixReadMemJpeg: work-around: writing to a temp file`
and i get an empty out.txt file

**Comment by zdenop** [comment]
But your original issue (wrong installation) was solved.
For asking support use tesseract user forum - there are more people...

**Comment by adamdylan** [comment]
I guess,
thanks
