### ISSUE TITLE
Tesseract fails with ELIST_ITERATOR::forward:Error:List would have returned a nullptr data pointer

### ISSUE THREAD

**Issue by MerlijnWajer** [tesseract-ocr/tesseract#3263]
### Environment

* **Tesseract Version**: `4.1.1`
* **Platform**: `Linux archivecd-merlijn-development-nuc-1 5.4.0-53-generic #59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Current Behavior:

Image can be found here: https://archive.org/~merlijn/pokettopurogures0000unse_0294.jp2

```
tesseract -l jpn+kor -c tessedit_create_txt=1 -c tessedit_create_hocr=1 -c hocr_char_boxes=1 -c hocr_font_info=1 /tmp/pokettopurogures0000unse_0294.jp2 /tmp/pokettopurogures0000unse_0294
```

### Expected Behavior:

Tesseract should not fail.

**Comment by stweil** [comment]
It works fine with git master and models from `tessdata_fast`. Which kind of models did you use?

**Comment by stweil** [comment]
The error occurs with latest code when using `tessdata_best` models.

**Comment by MerlijnWajer** [comment]
I use `tesseract-ocr-all` as data pack (from Ubuntu 20.04's repository). I assumed that would be tessdata-fast.

**Comment by stweil** [comment]
The bug exists in 4.1.1 and in branch 4.1, but was fixed later in the master branch. `git bisect` shows that it was fixed with commit 3a5e5089343798932d9952628acfdf56f3108c43. I am afraid that fix cannot be easily backported to the 4.1 branch.

**Comment by MerlijnWajer** [comment]
Not a problem, thanks for bisecting that bug! All the more reason for me to switch to 5.0 in the very near future. Maybe we can just close this bug report?

**Comment by stweil** [comment]
Yes. Thanks for reporting nevertheless.
