### ISSUE TITLE
Install Tesseract OCR PHP in Apache in Windows

### ISSUE THREAD

**Issue by alicealicia80** [tesseract-ocr/tesseract#3266]
Dear Sir,

Would like to know how I can install the Tesseract OCR for used in programming language PHP to the Apache that installed in Windows. 

And also I would like to use the features of OCR in the PHP to enable reading the text from the image file select from the selected and will be uploaded. 

Can I have the sample of source code for the php to generate the text with image uploaded. The image got two rows of text.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Make sure you read docs first, search forum and describe what you already tried.
