### ISSUE TITLE
incorrect OCR extraction from PNG image

### ISSUE THREAD

**Issue by bilelkhedira** [tesseract-ocr/tesseract#327]
![sc](https://cloud.githubusercontent.com/assets/19493015/15432773/dc38d8ca-1eaf-11e6-9ba1-41c3f5a34723.png)

OCR extraction result:
Nam: an 32:
m j..
L1..,.,.,...»1s3mm ssa
L1.:...:.m.,...»1s3;»z:zza 5533
L1c.(..,.a.5.,...».s3;»z:zzs msa
E| luginmjpg 52 J15 B
§	lugIlI7l_Ihum	>s.plvg 1:; ma
L1g.....gs.,...»1s3mzzs sm
mgms
Oulvzr
upznlxegksk
upznlxegksk
upznlxegksk
upznlxegksk
upznlxegksk
upznlxegksk
upznlxegksk

**Comment by zdenop** [comment]
Please read and follow [FAQ](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice) before creating issue.
