### ISSUE TITLE
Update 4.x release descriptions with correct links for release notes, etc

### ISSUE THREAD

**Issue by tfmorris** [tesseract-ocr/tesseract#3272]
It's unfortunate that the wiki is gone since there are so many links to it.  External links can't be fixed, but it would be good to at least fix up the major internal links like those in the release descriptions which point to Release Notes, Changelogs, etc. Of these, the most important is probably the 4.0.0 release. Relevant links below:

https://tesseract-ocr.github.io/tessdoc/ReleaseNotes.html#tesseract-release-notes-dec-26-2019---v411
https://github.com/tesseract-ocr/tesseract/releases/tag/4.1.0
https://tesseract-ocr.github.io/tessdoc/ReleaseNotes.html#tesseract-release-notes-jul-07-2019---v410
https://github.com/tesseract-ocr/tesseract/releases/tag/4.0.0
https://tesseract-ocr.github.io/tessdoc/ReleaseNotes.html#tesseract-release-notes-oct-29-2018---v400

**Comment by Shreeshrii** [comment]
Thanks for pointing out the issue. I have restored the stub pages on wiki pointing to the tessdoc pages.
