### ISSUE TITLE
Error looking up function 'TessPDFRendererCreateTextonly'

### ISSUE THREAD

**Issue by marcelocecin** [tesseract-ocr/tesseract#3274]
[error] java.lang.UnsatisfiedLinkError ( java.lang.UnsatisfiedLinkError: Error looking up function 'TessPDFRendererCreateTextonly': /lib/x86_64-linux-gnu/libtesseract.so.4: undefined symbol: TessPDFRendererCreateTextonly )
[error] --- Traceback --- error source first
line: module ( function ) statement
354: main ( text_read ) temp_text = region_layer.text()
331: main ( save_intent ) return text_read(raw_intent)
526: main ( parse_intent ) return save_intent(script_line)
[error] --- Traceback --- end --------------
IDE terminated: returned: 1

tesseract 4.1.1
leptonica-1.79.0
libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
Found AVX
Found SSE
Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4

Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import cv2
cv2.version
'4.2.0'

Ubuntu 20.04.1 LTS

**Comment by stweil** [comment]
You are reporting an error for linking against Java. So here is the wrong place for such reports as this repository does not provide the Java API.

**Comment by stweil** [comment]
`TessPDFRendererCreateTextonly` is not part of the official Tesseract code.
