### ISSUE TITLE
Can't find ara.cubes files for Arabic language , I need all cubes files and I can't find them

### ISSUE THREAD

**Issue by AhmedElsayedTaha** [tesseract-ocr/tesseract#3277]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by stweil** [comment]
You won't need them because they are no longer supported since several years.

**Comment by AhmedElsayedTaha** [comment]
@stweil I got a result yesterday but numbers are not accuracy even 10% percent . So is there a way to show numbers in Arabic ? Or is there another free library ?
