### ISSUE TITLE
Building tesseract 5.0.0 with Visual Studio 2017

### ISSUE THREAD

**Issue by zokai** [tesseract-ocr/tesseract#3278]
Hi,
Is it possible to build tesseract 5.0.0 developer library with Visual studio 2017?
It seems sw needs VS 2019  (C++20) to build tesseract 5.0.0.

Thank you

**Comment by amitdo** [comment]
Only VS 2019 is tested currently for Tesseract 5.0. 5.0 uses the C++**17** standard.

**Comment by egorpugin** [comment]
@zokai 
sw needs VS2019 only for itself.
You can still try to build tess with VS2017.
Just install VS2019 or VS2019 build tools (small distribution set of compilers etc.).

`sw build -compiler msvc-<19.20`

**Comment by zokai** [comment]
Thank you.
