### ISSUE TITLE
Roadmap for the new LSTM backend ?

### ISSUE THREAD

**Issue by ASDen** [tesseract-ocr/tesseract#328]
Is there any - approximate - expectation, when will the new LSTM backend for tesseract (presented [here](http://www.primaresearch.org/das2016/assets/DAS2016_Tutorial_Tesseract.pdf) )  be merged into master ? (or at least pushed public)

Regards

**Comment by amitdo** [comment]
Hi!
Good Question. The right place to ask this question is in the [tesseract-dev](https://groups.google.com/d/forum/tesseract-dev) mailing list. I hope you get an answer from Ray Smith.
