### ISSUE TITLE
Build instructions depend on cppan.org.

### ISSUE THREAD

**Issue by tdhintz** [tesseract-ocr/tesseract#3284]
The official build instructions for Visual Studio 2019 specify the use of cppan from cppan.org/client, which no longer exists.  What are the updated instructions?

**Comment by zdenop** [comment]
Read the docs.
https://github.com/tesseract-ocr/tessdoc/blob/master/Compiling-%E2%80%93-GitInstallation.md

**Comment by tdhintz** [comment]
https://tesseract-ocr.github.io/tessdoc/Compiling.html

**Comment by tdhintz** [comment]
@zdenop The Windows Visual Studio link at the bottom of the page you referenced points to this:

[Windows Visual Studio Build Instructions](https://github.com/tesseract-ocr/tessdoc/blob/master/Compiling.md#windows)

The Tesseract 5.0 portion of these instructions still direct the use of cppan.
