### ISSUE TITLE
index variable in OpenMP 'for' statement must have signed integral type	

### ISSUE THREAD

**Issue by tdhintz** [tesseract-ocr/tesseract#3285]
When OpenMP is ON the build on Visual Studio 2019 generates the following error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3016	'b': index variable in OpenMP 'for' statement must have signed integral type	libtesseract	C:\Work\Petri\50e\OpenMPOn\tesseract\src\ccmain\par_control.cpp	56	

Changing size_t to int allows the build to proceed.

`for (size_t b = 0; b < blobs.size(); ++b) {`

`for (int b = 0; b < blobs.size(); ++b) {`

**Comment by stweil** [comment]
According to [this discussion](https://developercommunity.visualstudio.com/content/problem/822384/openmp-compiler-errors-introduced-after-visual-stu.html), Microsoft changed Visual Studio in 2019 to be consistent with the [OpenMP standard 2.0](https://www.openmp.org/specifications/) which was valid in 2002 and which required signed integers in the `for` loop.

As using OpenMP has especially bad performance on Windows I suggest to simply disable it when using that compiler. Changing the code would not look reasonable for me.

**Comment by tdhintz** [comment]
In some use cases OpenMP is good.  In others its bad.  We use both to suite the circumstance.

size_t evaluates to unsigned long long, so your are probably right that int is inappropriate but so is size_t.

**Comment by stweil** [comment]
Could you please try the compiler flag `-openmp:experimental`? That should enable a newer standard OpenMP 4.0. Maybe that's sufficient to solve the issue.

**Comment by tdhintz** [comment]
Using /openmp:experimental yields the same error as before.

**Comment by tdhintz** [comment]
Regarding OpenMP performance on Windows, see my very last comment at the bottom of issue #3044.

**Comment by amitdo** [comment]
https://devblogs.microsoft.com/cppblog/improved-openmp-support-for-cpp-in-visual-studio/#new-openmpllvm-switch

**Comment by stweil** [comment]
Thank you for that hint. @tdhintz, please try the new option `-openmp:llvm`. Hopefully it solves this issue.

**Comment by tdhintz** [comment]
Let’s wait until some of the caveats are lifted.

**Comment by amitdo** [comment]
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.10.0

>/openmp:llvm is now available on x86 and ARM64, in addition to x64

**Comment by OgreTransporter** [comment]
`/openmp:llvm` can solve this issue.

Proposal:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 947693e9..c82ebbcf 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -264,6 +264,10 @@ if (OPENMP_BUILD)
         if(${CMAKE_VERSION} VERSION_LESS "3.9.0")
             add_library(OpenMP::OpenMP_CXX IMPORTED INTERFACE)
         endif()
+        if (MSVC AND ${MSVC_VERSION} GREATER 1919)
+            string(REPLACE "/openmp" "/openmp:llvm" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
+            string(REPLACE "-openmp" "/openmp:llvm" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
+        endif()
     endif()
     # https://stackoverflow.com/questions/12399422/how-to-set-linker-flags-for-openmp-in-cmakes-try-compile-function
     if (NOT OpenMP_FOUND AND CLANG AND WIN32)
@@ -273,7 +277,11 @@ if (OPENMP_BUILD)
         find_library(OpenMP_LIBRARY NAMES omp libomp.lib)
         message(">> OpenMP_LIBRARY: ${OpenMP_LIBRARY}")
         if (MSVC)
-            set(OpenMP_CXX_FLAGS "${OpenMP_CXX_FLAGS} /openmp")
+            if (${MSVC_VERSION} GREATER 1919)
+                set(OpenMP_CXX_FLAGS "${OpenMP_CXX_FLAGS} /openmp:llvm")
+            else()
+                set(OpenMP_CXX_FLAGS "${OpenMP_CXX_FLAGS} /openmp")
+            endif()
         else()
             set(OpenMP_CXX_FLAGS "${OpenMP_CXX_FLAGS} -fopenmp")
         endif()
```
