### ISSUE TITLE
Crash on Apple M1 using homebrew 3.0

### ISSUE THREAD

**Issue by chaintng** [tesseract-ocr/tesseract#3286]
### Environment

* **Tesseract Version**: Latest, 4.1.1
* **Platform**: Apple Silicon M1, Macbook Air

### Current Behavior:
I installed tesseract using `homebrew 3.0`, which claimed to have natively support apple m1 (https://brew.sh/2021/02/05/homebrew-3.0.0/)

`brew install tesseract`

After install, all the output logs looks good.

However, when i run `tesseract` in the command line
It crashed immediately, i got `137` exit code

Please see my screenshot
![image](https://user-images.githubusercontent.com/2979072/107136793-e0785680-6938-11eb-9257-6a770afeacb1.png)

I also tried install with `-s` flag
It still result the same.

### Expected Behavior:
It should able to work

**Comment by amitdo** [comment]
This version of Tesseract came out before  Apple's M1 was available to the general public.

**Comment by chaintng** [comment]
@amitdo but in the homebrew formulae, it show that it support Apple Silicon, Big Sur here
https://formulae.brew.sh/formula/tesseract#default

**Comment by stweil** [comment]
It works for me ...

**Comment by chaintng** [comment]
Does anybody know how to debug this?
I'm not sure where can i find the logs for this case :(

**Comment by stweil** [comment]
Check whether you are really running the tesseract executable from `/opt/homebrew/bin` by running `type tesseract`.

Then run it with a debugger, for example `lldb /opt/homebrew/bin/tesseract` to see why and where it crashes.

**Comment by chaintng** [comment]
yes, it's located there
and lldb doesn't have my any clue :(
![Uploading image.png…]()

**Comment by chaintng** [comment]
It's working after i completely uninstall homebrew and reinstall it.

Sorry for bother 🙏
