### ISSUE TITLE
Mixed Thai and English languages doesn't work correctly

### ISSUE THREAD

**Issue by chaintng** [tesseract-ocr/tesseract#3287]
### Environment

* **Tesseract Version**: 4.1.1
* **Platform**: Apple Silicon M1, Macbook Air

### Current Behavior:
<img width="634" alt="tha_eng" src="https://user-images.githubusercontent.com/2979072/107145651-bd1fcc80-6975-11eb-8d0b-f9f9585998e7.png">
I tried with the above picture
It's simple Thai with English test.

However, when i tried with below command

```
tesseract tha_eng.png tha_eng -l tha+eng
```

It doesn't convert english correctly, this is the output

```
สวัสดีครับ ทดสอบภาษาไทย กับ โ@รร๕6ล6%
```

I also play with order, `eng+tha`
But still doesn't work, with this output

```
ส ว ั ส ด ี ค ร ั บ ท ด ส อ บ ภา ษา ไท ย ก ั บ โ @ ร ร ๕ 6 ล 6%
```

### Expected Behavior:
It should convert to
```
สวัสดีครับ ทดสอบภาษาไทย กับ Tesseract
```

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/2626#issuecomment-774687257
