### ISSUE TITLE
How to get the original layout of the document

### ISSUE THREAD

**Issue by deepak011197** [tesseract-ocr/tesseract#3293]
I am trying to use tesseract 4.1.0 to extract text from documents. 

The code i am using for extracting the text is attached in the image tess.png
These are my custom config for tesseract: custom_config = r'-c preserve_interword_spaces=1 --oem 1 --psm 6 -l eng'
<img width="449" alt="tess" src="https://user-images.githubusercontent.com/78915831/107647884-a644e700-6ca1-11eb-8b71-b8fdd7193a30.png">

When I try to extract documents which have tabular layout, (Please refer to image doc.png under the "value offered" sub heading.) tesseract misses out to extract the text with preserving the "actual layout of the text too"

![doc png](https://user-images.githubusercontent.com/78915831/107647836-988f6180-6ca1-11eb-86b7-1e164f8114f2.jpeg)

If you look at the column "Solid credentials" the actual value is "Bachelor of commerce with Business Finance." But the way tesseract interprets this is totally different. It reads Bachelor of commerce with Scrum methodology Offer an advanced command of:\nBusiness Finance.

The above is just one example of many. 

Due to this, I am lacking the "key information due to wrongly segmented layout. Is there a way to over come this?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
