### ISSUE TITLE
tesseract - build and install (`configure`, `make`, `make install`...) tesseract version 3 (tesseract-ocr-3.XX.XX)

### ISSUE THREAD

**Issue by eduardolucioac** [tesseract-ocr/tesseract#3294]
**PROBLEM:**

I am trying build and install (`configure`, `make`, `make install`...) **tesseract** version 3 (`tesseract-ocr-3.02.02`) on Ubuntu Server 20.04 LTS and the following error is occurring...

    [...]
    -I../viewer -I/usr/local/include/leptonica -g -O2 -MT con_comp.lo -MD -MP -MF .deps/con_comp.Tpo -c con_comp.cpp  -fPIC -DPIC -o .libs/con_comp.o
    libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O3 -DNDEBUG -DUSE_STD_NAMESPACE -I../cutil -I../ccutil -I../ccstruct -I../dict -I../ccmain -I../classify -I../textord -I../wordrec -I../neural_networks/runtime -I../image -I../viewer -I/usr/local/include/leptonica -g -O2 -MT con_comp.lo -MD -MP -MF .deps/con_comp.Tpo -c con_comp.cpp -o con_comp.o >/dev/null 2>&1
    libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O3 -DNDEBUG -DUSE_STD_NAMESPACE -I../cutil -I../ccutil -I../ccstruct -I../dict -I../ccmain -I../classify -I../textord -I../wordrec -I../neural_networks/runtime -I../image -I../viewer -I/usr/local/include/leptonica -g -O2 -MT classifier_factory.lo -MD -MP -MF .deps/classifier_factory.Tpo -c classifier_factory.cpp -o classifier_factory.o >/dev/null 2>&1
    mv -f .deps/char_samp.Tpo .deps/char_samp.Plo
    mv -f .deps/con_comp.Tpo .deps/con_comp.Plo
    mv -f .deps/classifier_factory.Tpo .deps/classifier_factory.Plo
    make[2]: Leaving directory '/usr/local/lib/tesseract-ocr/cube'
    make[1]: *** [Makefile:481: all-recursive] Error 1
    make[1]: Leaving directory '/usr/local/lib/tesseract-ocr'
    make: *** [Makefile:390: all] Error 2

**QUESTION:**

What can I do to get more information about this error?

**IMPORTANT:**

It is a standard and well-known process for build and installing software (`configure`, `make`, `make install`...)... So, based on that, I think there are known ways to get more information so we can diagnose what's going on. There is almost no information on the internet about this specific error, so **I really need help with this**.

**Thanks! =D**

[Ref.: https://github.com/tesseract-ocr/tesseract/issues/2195 ]

**Comment by zdenop** [comment]
tesseract version 3 is old unsupported version. Use the latest stable release.

**Comment by eduardolucioac** [comment]
> tesseract version 3 is old unsupported version. Use the latest stable release.

We need to install a legacy application that uses this version of tesseract in **production**. So the risks of upgrading to the latest version are great and seem unpredictable to us. Any other suggestions!? **Thanks! =D**

**Comment by stweil** [comment]
Using old unsupported software is also an unpredictable risk. I suggest upgrading to the stable release 4.1.1 which is still highly compatible with Tesseract 3 and which is provided for Linux.

**Comment by eduardolucioac** [comment]
The solution was upgrade to version 3.05.02 , that is, 3 "MINORs" ahead which reduces our risks with compatibility - upgrade 1 "MAJOR" (4.1.1), in our view, would be very risky.

The same reasoning was used for the leptonica: "1.71" -> "1.74.1" (3 "MINORs").

**NOTES:**
I - The package "pkg-config" is required for this tesseract version;
II - Versioning logic reference -> "MAJOR.MINOR.REVISION.BUILDNUMBER" .

**Thanks! =D**

[**Refs.:** http://programmers.stackexchange.com/questions/24987/what-exactly-is-the-build-number-in-major-minor-buildnumber-revision ,
https://gist.github.com/braitsch/ee5434f91744026abb6c099f98e67613 ,
https://github.com/tesseract-ocr/tesseract/issues/941#issuecomment-304080060 ]
