### ISSUE TITLE
TessBaseAPIDetectOrientationScript appears to have been removed?

### ISSUE THREAD

**Issue by tdhintz** [tesseract-ocr/tesseract#3296]
### Environment

* **Tesseract Version**: 5.0
* **Commit Number**: today
* **Platform**: Visual Studio 2019 with current updates

### Current Behavior:
Breaks https://github.com/charlesw/tesseract

### Suggested Fix:
The C++ layer still appears but the C interface isn't found.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/commit/bee90f7835ca1

**Comment by tdhintz** [comment]
I guess I need guidance.  Will it be removed, or restored?  Is there a replacement?

**Comment by amitdo** [comment]
It was never was really supported by Tesseract's build tools.

IMO, It should be restored and not be under any special ifdef. 

In general, the C API should cover all the C++ API functions.

**Comment by amitdo** [comment]
Can you send a PR that restores this function?

**Comment by stweil** [comment]
@egorpugin, what do you suggest? Should we revert commit bee90f7?

**Comment by stweil** [comment]
@tdhintz, did you use `TessBaseAPIDetectOrientationScript` with C++ or with C code?

As far as I see, that function was only declared for C++ code. And for C++ there is a better alternative by calling `DetectOrientationScript`.

**Comment by amitdo** [comment]
@stweil see #544

I accidentally moved `TessBaseAPIDetectOrientationScript` to a wrong place in #1740.

**Comment by amitdo** [comment]
>And for C++ there is a better alternative by calling DetectOrientationScript.

better than what?

**Comment by tdhintz** [comment]
The user is a .Net wrapper written by Charles Weld. The .Net world uses it to interface to tesseract.

**Comment by amitdo** [comment]
What was the point of `#ifdef TESS_CAPI_INCLUDE_BASEAPI`?

**Comment by egorpugin** [comment]
> @egorpugin, Should we revert commit [bee90f7](https://github.com/tesseract-ocr/tesseract/commit/bee90f7835ca16d0a477d6e1ad28b80a8edcab8e)?

No, those were C++ functions in C header file. They used std::string or other C++ objects.

> what do you suggest?

Functionality can be restored by adding these methods into public C++ API (in case if they are not already there).

**Comment by egorpugin** [comment]
Like if we open `baseapi.h` and look for the topic function, it is there - https://github.com/tesseract-ocr/tesseract/blob/master/include/tesseract/baseapi.h#L624

**Comment by egorpugin** [comment]
Also possible solution is to restore C functions, remove ifdef and change to C types like `std::string` to `const char*`.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/commit/bee90f7835ca1#diff-51385491b62214d5db9658f70b5c137e14615d32f9df44902b3299f977e8ed21L369

It's just C.

                                            int* orient_deg,
                                                 float* orient_conf,

**Comment by egorpugin** [comment]
Ah, yes, sorry. Looked at other function.

Still, everything were under C++ ifdef.
We can try to restore apis without ifdef. It seems I did not try to remove ifdef or there were some errors.

**Comment by amitdo** [comment]
>Still, everything were under C++ ifdef.

As I said, the specific function that the OP asked about was accidentally moved to the wrong location under that ifdef.

**Comment by stweil** [comment]
It is still so in 4.1.1, so that needs a fix, too.

**Comment by egorpugin** [comment]
Restored in https://github.com/tesseract-ocr/tesseract/commit/f06b2c7c8dea4a9ef08f9cd52353ea35d8bb624d
