### ISSUE TITLE
Unittest: C++ exception with description "locale::facet::_S_create_c_locale name not valid" thrown in SetUp().

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#3301]
When building with g++ on macOS,  

```
======================================================
   tesseract 5.0.0-alpha-20201231: ./test-suite.log
======================================================

# TOTAL: 61
# PASS:  24
# SKIP:  0
# XFAIL: 0
# FAIL:  37
# XPASS: 0
# ERROR: 0
```
The error is the following, most probably related to googletest.

```
unknown file: Failure
C++ exception with description "locale::facet::_S_create_c_locale name not valid" thrown in SetUp().
```

[One of the log files](https://github.com/tesseract-ocr/tesseract/runs/1894830584?check_suite_focus=true#step:15:4) 

Please note that test status is marked with green check because of use of  `continue-on-error: true` for the `make check` step, so that the test results reports can be displayed at end.

**Comment by Shreeshrii** [comment]
Seems to be related to the different gcc compilers available on macOS.

Works OK with:

```
Run g++ --version
Configured with: --prefix=/Applications/Xcode_12.3.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode_12.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin


Run cat test-suite.log
======================================================
   tesseract 5.0.0-alpha-20201231: ./test-suite.log
======================================================

# TOTAL: 61
# PASS:  61
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0

```

Fails with the following three:

```
Run g++-8 --version
g++-8 (Homebrew GCC 8.4.0_2) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Run cat test-suite.log
======================================================
   tesseract 5.0.0-alpha-20201231: ./test-suite.log
======================================================

# TOTAL: 61
# PASS:  24
# SKIP:  0
# XFAIL: 0
# FAIL:  37
# XPASS: 0
# ERROR: 0

```

```
Run g++-9 --version
g++-9 (Homebrew GCC 9.3.0_1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Run cat test-suite.log
======================================================
   tesseract 5.0.0-alpha-20201231: ./test-suite.log
======================================================

# TOTAL: 61
# PASS:  24
# SKIP:  0
# XFAIL: 0
# FAIL:  37
# XPASS: 0
# ERROR: 0

```


```
Run g++-10 --version
g++-10 (Homebrew GCC 10.2.0_3) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Run cat test-suite.log
======================================================
   tesseract 5.0.0-alpha-20201231: ./test-suite.log
======================================================

# TOTAL: 61
# PASS:  24
# SKIP:  0
# XFAIL: 0
# FAIL:  37
# XPASS: 0
# ERROR: 0

```

**Comment by stweil** [comment]
The unittests use the locale settings from their environment to test whether the Tesseract API runs not only with `C.UTF-8` but also with typical other locale settings. The error thrown here indicates that there is an invalid setting. This can be easily reproduced:

    export LANG=XYZ.UTF-8
    make check

So in a next step we have to check all environment settings, for example by running `export` which lists all exported environment variables. How do test environments with `g++` on macOS differ from others?

**Comment by stweil** [comment]
I also get those exceptions with a local build using g++-10 on macOS and my default setting `LANG=de_DE.UTF-8`. The error also occurs with `LANG=C.UTF-8`.

`LANG=C make check` works fine.

**Comment by Shreeshrii** [comment]
Yes, it fails with g++-8, g++-9, g++-10 on macOS, ok with g++ and clang.

Should I add `LANG=C ` to `make check` for these compilers?

**Comment by stweil** [comment]
`unset LANG` also works fine. Yes, this is not a Tesseract issue, so I'd unset the locale for those compilers on macOS.

See related reports:
https://stackoverflow.com/questions/11190072/setting-locales-on-os-x-crashes
https://stackoverflow.com/questions/1745045/stdlocale-breakage-on-macos-10-6-with-lang-en-us-utf-8

**Comment by amitdo** [comment]
>ok with g++ and clang

Clang is the default compiler on macOS. Apple dropped GCC support long time ago, so the default `g++` is not really g++, it clang (I guess it just a symlink).

IMO there is no point in testing `g++`.

It okay to test the versions that were installed by Homebrew, like g++**-8**.

By default. g++

**Comment by stweil** [comment]
gcc, g++, clang and clang++ are identical files:

    % ls -l /usr/bin/gcc /usr/bin/g++ /usr/bin/clang*
    -rwxr-xr-x  1 root  wheel  137552 Jan  1  2020 /usr/bin/clang
    -rwxr-xr-x  1 root  wheel  137552 Jan  1  2020 /usr/bin/clang++
    -rwxr-xr-x  1 root  wheel  137552 Jan  1  2020 /usr/bin/g++
    -rwxr-xr-x  1 root  wheel  137552 Jan  1  2020 /usr/bin/gcc

**Comment by Shreeshrii** [comment]
>unset LANG also works fine. Yes, this is not a Tesseract issue, so I'd unset the locale for those compilers on macOS.

I tried both with `LANG=C make check` and `unset LANG`. The runtime errors are still there. Please see 
https://github.com/Shreeshrii/tesseract/runs/1900725829?check_suite_focus=true#step:10:2
and the error at
https://github.com/Shreeshrii/tesseract/runs/1900725829?check_suite_focus=true#step:16:4

**Comment by Shreeshrii** [comment]
One of the comments on https://stackoverflow.com/questions/1745045/stdlocale-breakage-on-macos-10-6-with-lang-en-us-utf-8 says

> today there is absolutely no need to use GCC or G++ on the Mac, the much better LLVM/Clang compiler suite is available from Apple free of charge, see the XCode home page.

**Comment by stweil** [comment]
The first link shows the exported environment variables. There are two more which are related to locale settings: `LC_ALL` and `LC_CTYPE` which still point to `en_US.UTF-8`. Unsetting those, too, should fix the issue.

**Comment by stweil** [comment]
Personally I tried g++ on macOS some time ago to get OpenMP support, but soon stopped that again and use Apple's clang for the daily work.

**Comment by Shreeshrii** [comment]
OK. 

Question:
Currently the CI I have added are only for `Release` builds. Should I also add the debug builds?
sw.yml uses both and the nightly run takes 4-5 hours.

**Comment by Shreeshrii** [comment]
Suggested changes made in https://github.com/tesseract-ocr/tesseract/pull/3302
