### ISSUE TITLE
Windows: CMake looking for requested version for tesseract when didn't specify version.

### ISSUE THREAD

**Issue by RiwEZ** [tesseract-ocr/tesseract#3304]
### Environment

- Tesseract version 5.0.0-alpha-20201231
- commit a219d64
- Leptonica 1.80.0
- cmake version 3.19.4
- Windows 10 64 bits

I build tesseract and leptonica using cmake following 
this https://tesseract-ocr.github.io/tessdoc/Compiling.html#windows on "Develop Tesseract"

my CMakeLists.txt
```
cmake_minimum_required(VERSION 3.19)

project(test CXX)

list(APPEND CMAKE_PREFIX_PATH "/Projects/cpp/CPE1/Project/lib/cmake/tesseract")
list(APPEND CMAKE_PREFIX_PATH "/Projects/cpp/CPE1/Project/lib/cmake/")

include_directories("/Projects/cpp/CPE1/Project/include")

add_executable(t t.cpp)

find_package(Tesseract REQUIRED)
target_link_libraries(t Tesseract::libtesseract)

find_package(Leptonica REQUIRED)
include_directories(${Leptonica_INCLUDE_DIRS})
target_link_libraries(t ${Leptonica_LIBRARIES})

```

### Current Behavior:
when I tried build my code, I got this error 

```
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
CMake Error at CMakeLists.txt:12 (find_package):
  Could not find a configuration file for package "Tesseract" that is
  compatible with requested version "".                                                      1\Projec

  The following configuration files were considered but not accepted:

    /Projects/cpp/CPE1/Project/lib/cmake/tesseract/TesseractConfig.cmake, version: 5.0.0-alpha-20201231 (64bit)



-- Configuring incomplete, errors occurred!
See also "D:/Projects/cpp/CPE1/Project/Uics/build/CMakeFiles/CMakeOutput.log".
```

I don't know why CMake is looking for requested version when I didn't specify it,
When I tried with find_package leptonica only, there is no error.

**Comment by Shreeshrii** [comment]
I have also been trying to setup a Github Actions CI for Windows build of Tesseract and then run the `basicapitest`, but not successful so far.

Tesseract Build is happening OK, some path issues related to Leptonica when trying to build `basicapitest`.

Sample Run 1.
[Workflow](https://github.com/Shreeshrii/tesseract/actions/runs/578174682/workflow)
[Log](https://github.com/Shreeshrii/tesseract/runs/1927074832?check_suite_focus=true#step:11:19)

```
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindLeptonica.cmake" in CMAKE_MODULE_PATH this project
-- Configuring incomplete, errors occurred!
See also "D:/a/tesseract/tesseract/test/CMakeFiles/CMakeOutput.log".
  has asked CMake to find a package configuration file provided by
  "Leptonica", but CMake did not find one.

  Could not find a package configuration file provided by "Leptonica" with
  any of the following names:

    LeptonicaConfig.cmake
    leptonica-config.cmake

  Add the installation prefix of "Leptonica" to CMAKE_PREFIX_PATH or set
  "Leptonica_DIR" to a directory containing one of the above files.  If
  "Leptonica" provides a separate development package or SDK, be sure it has
  been installed.
```

Sample Run 2.
[Workflow](https://github.com/Shreeshrii/tesseract/actions/runs/578839355/workflow)
[Log]()

**Comment by Shreeshrii** [comment]
@RiwEZ  Please see https://github.com/tesseract-ocr/tesseract/blob/b99ff07f6401e0a361699e9e3a4453a54bffab72/.github/workflows/vcpkg.yml
for a workflow that builds leptonica and image libraries using vcpkg, builds tesseract from --head of master branch and also builds  the basicapitest program using cmake.

Here is a log showing a successful build - https://github.com/Shreeshrii/tesseract/runs/1941040995?check_suite_focus=true

Please try the same approach for your project and see if works.

**Comment by RiwEZ** [comment]
Thanks, it's working now
