### ISSUE TITLE
How to improve output of Tesseract 5.0 alpha

### ISSUE THREAD

**Issue by FatimaArshad-DS** [tesseract-ocr/tesseract#3308]
Hi,
I need OCR to scan and output people's name. It sometimes doesnt recognize text. Here are two images
![image](https://user-images.githubusercontent.com/78070220/108844753-56014980-75fe-11eb-8b97-fdfde915dcdd.png)
For this image I get correct output. But for this image:
![image](https://user-images.githubusercontent.com/78070220/108844845-73361800-75fe-11eb-9e30-e273266c4a47.png)
This image doesnt produce anything. I am using this code:

      imgs = cv2.resize(imgs, (0, 0), fx=2, fy=2)
                # Convert to HSV color-space
                
        hsv = cv2.cvtColor(imgs, cv2.COLOR_BGR2HSV)

                

        text = tesseract_config(imgs, config="--psm 6")

These images look roughly the same. What's the difference that makes one detectable and other not?

**Comment by Shreeshrii** [comment]
Are you sure that your config of --psm 6 is being applied?

```
(base) ubuntu@tesseract-ocr-1:~/tesstrain$ cd ../TEST
(base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test1.png -
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 419
EF-SALARIED PERSON
(base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test2.png -
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 400
Empty page!!
Estimating resolution as 400
Empty page!!
(base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test2.png -  --psm 6
Warning: Invalid resolution 0 dpi. Using 70 instead.
NASAR
(base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test1.png -  --psm 6
Warning: Invalid resolution 0 dpi. Using 70 instead.
EF-SALARIED PERSON
```

**Comment by FatimaArshad-DS** [comment]
> Are you sure that your config of --psm 6 is being applied?
> 
> ```
> (base) ubuntu@tesseract-ocr-1:~/tesstrain$ cd ../TEST
> (base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test1.png -
> Warning: Invalid resolution 0 dpi. Using 70 instead.
> Estimating resolution as 419
> EF-SALARIED PERSON
> (base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test2.png -
> Warning: Invalid resolution 0 dpi. Using 70 instead.
> Estimating resolution as 400
> Empty page!!
> Estimating resolution as 400
> Empty page!!
> (base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test2.png -  --psm 6
> Warning: Invalid resolution 0 dpi. Using 70 instead.
> NASAR
> (base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test1.png -  --psm 6
> Warning: Invalid resolution 0 dpi. Using 70 instead.
> EF-SALARIED PERSON
> ```

I am using it in Jupyter. How do I make sure it is applied?

**Comment by FatimaArshad-DS** [comment]
> Are you sure that your config of --psm 6 is being applied?
> 
> ```
> (base) ubuntu@tesseract-ocr-1:~/tesstrain$ cd ../TEST
> (base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test1.png -
> Warning: Invalid resolution 0 dpi. Using 70 instead.
> Estimating resolution as 419
> EF-SALARIED PERSON
> (base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test2.png -
> Warning: Invalid resolution 0 dpi. Using 70 instead.
> Estimating resolution as 400
> Empty page!!
> Estimating resolution as 400
> Empty page!!
> (base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test2.png -  --psm 6
> Warning: Invalid resolution 0 dpi. Using 70 instead.
> NASAR
> (base) ubuntu@tesseract-ocr-1:~/TEST$ tesseract test1.png -  --psm 6
> Warning: Invalid resolution 0 dpi. Using 70 instead.
> EF-SALARIED PERSON
> ```

Image shown in question is cropped out from original image. When I use cropped image to get output I dont get it. But when I saved it and read it then Tesseract gives correct output. Why is that?

**Comment by zdenop** [comment]
Please respect that we do not provide support for 3rd party projects:
you either reproduce problem with tesseract command line or you have to use other relevant places for asking support (tesseract user forum, stackoverflow etc.)
