### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop*

### ISSUE THREAD

**Issue by munish259272** [tesseract-ocr/tesseract#3310]
### Environment

* **Tesseract Version**: 5.0.0-alpha-20201231

* **Platform**: Linux centos.example.com 5.9.13-1.el8.elrepo.x86_64 #1 SMP Mon Dec 7 11:45:32 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:

i am building with the steps below :
```
git clone https://github.com/tesseract-ocr/tesseract
cd tesseract
./autogen.sh LIBLEPT_HEADERSDIR=$HOME/Extrasoftware/local/include ./configure --prefix=$HOME/Extrasoftware/local/ --with-extra-libraries=$HOME/Extrasoftware/local/lib
```

the next step gives me below error:
`(base) [msingh@centos tesseract]$ make`
**make: *** No targets specified and no makefile found.  Stop**

Here are the files i see but i do not see makefile there.
```
(base) [msingh@centos tesseract]$ ls
abseil        AUTHORS         ChangeLog       config        CONTRIBUTING.md     Dockerfile  INSTALL         LICENSE      Makefile.in  src       tesseract.pc.cmake  unittest
aclocal.m4    autogen.sh      cmake           configure     doc                 googletest  INSTALL.GIT.md  m4           README.md    sw.cpp    tesseract.pc.in     VERSION
appveyor.yml  autom4te.cache  CMakeLists.txt  configure.ac  docker-compose.yml  include     java            Makefile.am  snap         tessdata  test
(base) [msingh@centos tesseract]$ 
```

**Comment by zdenop** [comment]
Please read the [docs](https://github.com/tesseract-ocr/tessdoc/blob/master/Compiling-%E2%80%93-GitInstallation.md).

**Comment by amitdo** [comment]
`./autogen.sh LIBLEPT_HEADERSDIR=$HOME/Extrasoftware/local/include ./configure --prefix=$HOME/Extrasoftware/local/ --with-extra-libraries=$HOME/Extrasoftware/local/lib`

You need to add a newline (press `Enter`) between the commands:

```./autogen.sh
./configure```

or add `&&` between them:

`./autogen.sh && ./configure `
