### ISSUE TITLE
How to build tesseract and training tools  3.04 in windows with VS2015?

### ISSUE THREAD

**Issue by camviluong** [tesseract-ocr/tesseract#333]
How to build tesseract and training tools  3.04 in windows with VS2015? I have check leptonica, but it's only libtesseract.lib, I need the training tools too like a setup of Tesseract 3.02

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support (see: [FAQ#rules-and-advices](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice))
