### ISSUE TITLE
Minimum system requirements

### ISSUE THREAD

**Issue by Announcement** [tesseract-ocr/tesseract#334]
So I just discovered this project, but I plan on implementing this on a very low powered ("performance") microcontroller. 

Is 2 x 300 MHz 32bit with 1 megabyte ROM & 512 kilobyte RAM enough?
Could I squeeze it down even further. I'd need it to be real time too.

Any benchmarking or related projects I could look in to, thank you.

**Comment by amitdo** [comment]
Please use [Tesseract users forum](https://groups.google.com/d/forum/tesseract-ocr) and ask this question (and other questions you might have) there.
