### ISSUE TITLE
Creating full text search with existing alto files

### ISSUE THREAD

**Issue by wezy01** [tesseract-ocr/tesseract#3343]
Hello,

I was wondering if it's possible, now or in a future version, to create full text searchable pdf files from existing tiff or jpg and existing alto of hocr files, so without ocr.

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

There already exist tools for doing that , for example https://github.com/ocropus/hocr-tools.
