### ISSUE TITLE
Tesseract started to die with pointer free issue (double free)...

### ISSUE THREAD

**Issue by oberw** [tesseract-ocr/tesseract#3348]
Tesseract started to die with a pointer issue. 
The problem began to show up yesterday, Mar. 19th.
The page, at which this issue appeard is attached (But I do not know if the problem originated earlier).
-w.

[page13.zip](https://github.com/tesseract-ocr/tesseract/files/6175392/page13.zip)
walter@velasquez:tesseract-test>make
time tesseract -l fra imagelist montechristo alto hocr pdf txt 
Tesseract Open Source OCR Engine v5.0.0-alpha-20201231-427-g87b0 with Leptonica
Page 0 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_006.tif
Page 1 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_007.tif
Page 2 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_008.tif
Page 3 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_009.tif
Page 4 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_010.tif
Page 5 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_011.tif
Page 6 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_012.tif
Page 7 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_013.tif
double free or corruption (!prev)
Command terminated by signal 6
17.31user 0.36system 0:16.83elapsed 105%CPU (0avgtext+0avgdata 440760maxresident)k
0inputs+20168outputs (0major+265984minor)pagefaults 0swaps

**Comment by stweil** [comment]
That looks like a bug introduced by commit f33e80e2f. I'll have a look.

**Comment by stweil** [comment]
Thank you for your report. The issue is fixed now by commit f176e7c274f9b208daca7b074380417ad4e78c05.

**Comment by oberw** [comment]
I can confirm that. Double-free is gone.

**Comment by egorpugin** [comment]
We need to replace such places with smart pointers.

**Comment by egorpugin** [comment]
See https://github.com/tesseract-ocr/tesseract/commit/db7a977eabb10038c5c3001efdb729268916b353
