### ISSUE TITLE
RFC: 'feature request' vs. 'enhancement'

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#3352]
I would like to re-add the 'enhancement' label and use it instead of 'feature request' for PRs. For issues I want to keep the 'feature request' label.

Any objection?

See previous discussion in  #1729.

**Comment by stweil** [comment]
'enhancement' is one of the "standard" labels which GitHub provides by default. Re-adding it is fine for me.

**Comment by amitdo** [comment]
Done.

Should I use it for already merged PRs and replace 'feature request'' with 'enhancement', or just for new PRs?

**Comment by stweil** [comment]
Do as you like. I have no personal preference for merged pull requests.
