### ISSUE TITLE
CI: Mingw-w64

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#3353]
@Shreeshrii,

Maybe you can also add Mingw-w64 to CI?

**Comment by Shreeshrii** [comment]
Thanks for the suggestion. I am setting up the workflow in my fork of tesseract and will create a PR when it works. See:

Msys2 for tesseract5 - master branch

https://github.com/Shreeshrii/tesseract/runs/2158509029?check_suite_focus=true

Msys2 for4.1.1

https://github.com/Shreeshrii/tesseract/actions/runs/672461769

Cross compile using deb packages from cygwin created by  @stweil 

https://github.com/Shreeshrii/tesseract/runs/2159686388?check_suite_focus=true

Need to add leptonica compilation to the last one.

**Comment by Shreeshrii** [comment]
@stweil I had installed leptonica as part of the deb packages but tesseract build doesn't find it.

```
2021-03-21 12:39:17 (4.74 MB/s) - ‘mingw64-x86-64-liblept5_1.77.0-51-gcdb4648-2_all.deb’ saved [6481804/6481804]

Selecting previously unselected package mingw64-x86-64-liblept5.
(Reading database ... 281751 files and directories currently installed.)
Preparing to unpack mingw64-x86-64-liblept5_1.77.0-51-gcdb4648-2_all.deb ...
Unpacking mingw64-x86-64-liblept5 (1.77.0-51-gcdb4648-2) ...
Setting up mingw64-x86-64-liblept5 (1.77.0-51-gcdb4648-2) ...
```

```
checking for x86_64-w64-mingw32-pkg-config... /usr/bin/x86_64-w64-mingw32-pkg-config
Please install dpkg-dev to use pkg-config when cross-building
checking pkg-config is at least version 0.9.0... no
checking for libcurl... no
checking for LEPTONICA... no
configure: error: Leptonica 1.74 or higher is required. Try to install libleptonica-dev package.
Error: Process completed with exit code 1.
```

This is the configure option that I had given:

```
           ./configure '--disable-shared' '--disable-openmp' '--disable-doc' --host=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32  CFLAGS='-Wall -Wextra -pedantic -g -O2'
```

**Comment by Shreeshrii** [comment]
@amitdo Both msys2 with master branch and for 4.1.1 are working. I decided not to do the crosscompilation. Is there any other option that you had in mind? Otherwise this can be closed.

MSYS2
https://github.com/tesseract-ocr/tesseract/runs/2168430526?check_suite_focus=true

MYS2-4.1.1
https://github.com/Shreeshrii/tesseract/runs/2158481396?check_suite_focus=true

**Comment by amitdo** [comment]
Thanks!
