### ISSUE TITLE
Spaces between characters when generating a pdf

### ISSUE THREAD

**Issue by nickbe** [tesseract-ocr/tesseract#337]
When creating a PDF from a scanned image, the latest dev build creates a space after each character - leaving out the real spaces completely: Tested on windows with the latest dev build.

So scanning this:
**products according to the attached customerlist No.**

becomes this:
**p r o d u c t s a c c o r d i n g t o t h e a t t a c h e d c u s t o m e r l i s t N o .**

**Comment by amitdo** [comment]
You mentioned in another issue that you are using Cygwin, so I guess this issue also happens with Cygwin, right?

Does this issue happens when you give it a page with many lines?

Could you upload the original image **and** the PDF file?

**Comment by nickbe** [comment]
Yes it's the cygwin version. The current VS Version does'nt create PDF versions for me at all.
The scans a basically all the same. It happens no matter what examples I'm using.

Here are some samples:
[sample1.txt](https://github.com/tesseract-ocr/tesseract/files/292199/sample1.txt)
[sample1.pdf](https://github.com/tesseract-ocr/tesseract/files/292200/sample1.pdf)
![sample1](https://cloud.githubusercontent.com/assets/10890765/15690874/fc4826d2-2785-11e6-8997-aa462f27a27e.png)

[sample2.pdf](https://github.com/tesseract-ocr/tesseract/files/292204/sample2.pdf)
![sample2](https://cloud.githubusercontent.com/assets/10890765/15690907/25f617aa-2786-11e6-97a8-6efc9598d5dd.png)
[sample2.txt](https://github.com/tesseract-ocr/tesseract/files/292205/sample2.txt)

[sample3.pdf](https://github.com/tesseract-ocr/tesseract/files/292217/sample3.pdf)
![sample3](https://cloud.githubusercontent.com/assets/10890765/15690995/92605a18-2786-11e6-92cd-81aa75facf90.png)
[sample3.txt](https://github.com/tesseract-ocr/tesseract/files/292218/sample3.txt)

**Comment by amitdo** [comment]
Which PDF viewer are you using? Adobe Acrobat Reader?

I checked the first PDF file with Chrome browser and Evince on Ubuntu 16.04. With these viewers the issue you describe does not exist.

**Comment by nickbe** [comment]
SumatraPDF. The viewer hasn't had any problems at all so far. And we're using it on several computers for years now including all our customers.

**Comment by amitdo** [comment]
The PDF renderer is tested with these viewer:
* Adobe Acrobat Reader
* PDFium (Chorome/Chromium)
* OS X Preview
* pdf.js (Firefox)
* Evince (poppler)

**Comment by nickbe** [comment]
You're right. I tested it in other PDF readers and there does not seem to be an obvious problem in the PDF itself. I report the problem to the developers of SumatraPDF instead.

**Comment by amitdo** [comment]
Just for reference:
https://github.com/sumatrapdfreader/sumatrapdf/issues/544

**Comment by jbreiden** [comment]
If the SumatraPDF engineer wants someone to talk to, send them my way.

**Comment by nickbe** [comment]
This I'll do :) Thanks
