### ISSUE TITLE
Tesseract skips recognizing some lines of text.  More and more lines are skipped while increasing DPI of the input image.

### ISSUE THREAD

**Issue by KoudelkaB** [tesseract-ocr/tesseract#3373]
### Environment

* **Tesseract Version**:  4.1
* **Platform**:  Windows  64-bit

### Current Behavior: Accuracy getting worse while increasing DPI of the input image:
When I render pages of the source document [deu+eng.print.pdf](https://github.com/tesseract-ocr/tesseract/files/6236043/deu%2Beng.print.pdf) for diffrerent DPIs and then process it by Tesseract 4.1 I get up to a maximum of **59%** recognised characters despite of **98%** for older Tesseract 3.05 at 600DPI.
Tesseract 4.1 does recognise **all rows in the document at 72DPI** but the letters are often wrong.
While increasing the DPI the number of succesfully recognized letters within a row grows but **number of recognized rows decreases!**
![1](https://user-images.githubusercontent.com/33930155/113135731-c06f6000-9222-11eb-9430-e3bb5dadffaf.jpg)
shows the first page rendered at 600DPI. When you process it by **tesseract.exe 1.jpg -l deu+eng --psm 1  pdf**
you get [1.pdf](https://github.com/tesseract-ocr/tesseract/files/6236140/1.pdf)
When you open the result in a browser and select all the text, you can see that **16 lines of the text does not have any letter recognized at all** while **remaining 29 lines have recognized all characters despite the font and letters are the same on  both types of rows**
The other problem is that the dots "...." are very often recongnised as a bunch of different characters (snuec...) despite all of them are the same.

When I change --psm command line parameter to different values I get slightly different results **but the overall accuracy is still very bad comaping to Tesseract 3.05**.

### Expected Behavior:  Accuracy getting better while increasing DPI of input image like in the older version of Tesseract.
I expect number of recognised rows to grow instead of decrease with growing DPI.

**Comment by amitdo** [comment]
1) You should test this with txt/hocr config options instead of pdf.
2) The issue with the dots recognition is a know issue, already discussed in other issues. Basicilly, the trained model data was not trained on similar images that contains a large sequence of dots.
3) If suggest that you upload another image with the dpi issue but without the dots issue.

**Comment by amitdo** [comment]
No feedback from the OP.

**Comment by amitguptamds** [comment]
I had the same issue and I solved it by reducing the file width and height. For large width and height OCR skips lines. Hope this helps
