### ISSUE TITLE
use the Viewer to debug recognition failed

### ISSUE THREAD

**Issue by martin-matj** [tesseract-ocr/tesseract#3374]
### Ubuntu 18.04 Desktop

* **Tesseract Version**:  5.0.0-alpha-20201231-523-g6684a
* **Commit Number**: 
* **Platform**: Ubuntu 18.04 Desktop

### Current Behavior:
when i run
tesseract phototest.tif test1 segdemo inter
 i got:

```
Tesseract Open Source OCR Engine v5.0.0-alpha-20201231-523-g6684a with Leptonica
Estimating resolution as 260
Starting sh -c "trap 'kill %1' 0 1 2 ; java -Xms1024m -Xmx2048m -jar /home/binary/tmp/tesseract/tesseract/java/ScrollView.jar & wait"
ScrollView: Waiting for server...
Socket started on port 8461
Client connected
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
sh: 1: kill: No such process

sh: 1: kill: No such process

Aborted (core dumped)

```
then java window showed up and then disappeared quickly

### Expected Behavior:
the debug window show up 
### Suggested Fix:
I compiled the source code by myself. and the ScrollView.jar.
all is ok. except when i make tesseract, i got
   ar: `u' modifier ignored since `D' is the default (see `U')
if i just run tesseract normally, nothing wrong.

**Comment by stweil** [comment]
Confirmed. I'll look for a fix.

**Comment by stweil** [comment]
The same bug already exists in Tesseract 4.1, and even the [old code of Tesseract 3.05](https://github.com/tesseract-ocr/tesseract/blob/f907620a1aee70006468c501992499d9f8d24064/ccmain/paramsd.cpp#L97) looks buggy because it exceeds the source string.

**Comment by stweil** [comment]
@martin-matj, maybe you can try fixing `ParamsEditor::GetFirstWords` yourself and see whether it works then. I'm afraid that I won't be able to fix it this week.

**Comment by stweil** [comment]
The same command triggers at least 3 different bugs which are shown when running a build with the address sanitizer. The buggy code in `ParamsEditor::GetFirstWords` is the first one which occurs. I just fixed another one in commit 722767633e864e810ac2586137fa9140db4161a2. A third one still needs closer examination.

**Comment by egorpugin** [comment]
By the way what is ScrollView?

**Comment by zdenop** [comment]
AFAIK ScrollView is [interface to display](https://github.com/tesseract-ocr/tessdoc/blob/master/ViewerDebugging.md) some tesseract internal states via java library piccolo.,

**Comment by egorpugin** [comment]
1. Is it possible to dump such states and open them in external viewer?
2. Is it possible to move code to tesseract main?

ScrollView looks like some external unnecessary subsystem integrated into libtess. I'd like to understand whther it is possible to avoid this.

**Comment by stweil** [comment]
ScrollView is a Java application, the source code in the `java` subdirectory, so it does not interfere with the Tesseract library.

The Tesseract code can optionally use ScrollView to show intermediate images, boxes, baselines and other data which is processed during an OCR. The Tesseract library can be built without that functionality by defining `GRAPHICS_DISABLED`.

**Comment by egorpugin** [comment]
> to show intermediate images, boxes, baselines and other data which is processed during an OCR

This is the question. Can we dump all these things near the image in non-interactive mode? So scrollview or any other tool will show them to user after?

**Comment by stweil** [comment]
No, that's not the same, because ScrollView also allows interaction with Tesseract. I see no need to change the status quo (beside fixing the existing bugs).

**Comment by amitdo** [comment]
There are two part of ScollView. One is written in C++, which draws images, and the second one that displays it in a window on screen and is written in Java. The Java code depends on a third party Java code, piccolo. These two parts communicate via sockets. 

https://github.com/piccolo2d/piccolo2d.java

I don't think that this 'visual debugger' is meant to be used by regular users.

**Comment by amitdo** [comment]
Piccolo Java code was not update was not been thouched Dec 30, 2014. There were a few changes to the build system a documentation since then.

https://github.com/piccolo2d/piccolo2d.java/commits/master

https://github.com/piccolo2d/piccolo2d.java

https://github.com/piccolo2d/piccolo2d.java/issues/278

**Comment by zdenop** [comment]
In this case I do not care how much often is external library updated, but I care if it provide expected functionality.
Or if we can provide the same/better functionality with other multiform tool without relaying on some heavy framework.
I agree with stweil: I do not see need to change the status quo either.

**Comment by egorpugin** [comment]
The general idea is to move out scrollview code into separate lib/exe if possible.
The possibility of this will be more clear after several modernization iterations.

**Comment by amitdo** [comment]
Citing myself:

>I don't think that this 'visual debugger' is meant to be used by regular users.

IMO, this should not block 5.0.0 release.

**Comment by tfmorris** [comment]
@stweil It sounds like you had fixed two of three identified bugs, but I was able to successfully run the ScrollView app with a private static build from the current HEAD of main. Perhaps this can be closed? I can't tell if there's more to reproducing it than just the command given by the OP, but that works fine for me.

**Comment by stweil** [comment]
Yes, I think it can be closed. @martin-matj, thank you for your report. Please re-open this issue if there remain more ScrollView related bugs.
