### ISSUE TITLE
mftraining error: Size > 0:Error:Assert failed:in file ../../../src/cutil/emalloc.cpp, line 32

### ISSUE THREAD

**Issue by Luhari** [tesseract-ocr/tesseract#3378]
### Environment

* **Tesseract Version**: 
 ```tesseract v5.0.0-alpha.20201127
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.3.2 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5
 Found libcurl/7.59.0 OpenSSL/1.0.2o (WinSSL) zlib/1.2.11 WinIDN libssh2/1.7.0 nghttp2/1.31.0
```

* **Platform**: Windows version 64bit

### Current Behavior:

I followed one of many tutorials of tesseract (https://towardsdatascience.com/simple-ocr-with-tesseract-a4341e4564b6), and first I got the unicharset error, but after some time searching the solution, I finally moved on (from 0 shapes detected to 18 shapes detected).

But now when I do
```
mftraining -F font_properties.txt -U unicharset -O eng.test.exp0.tr
```

It shows the following error:
```
Read shape table shapetable of 18 shapes
Size > 0:Error:Assert failed:in file ../../../src/cutil/emalloc.cpp, line 32
```
I've seen that there is a similar previous issue 
https://github.com/tesseract-ocr/tesseract/issues/1664
But in that issue the file of the error is different.

### Expected Behavior:
Gives me the shapetable, so I'll be able to continue with the training (cntraning, renaming those 4 files and generate the traineddata and test it)

Here are the .tif and the files that I generated following the tutorial, if it is of any help.
[files_used.zip](https://github.com/tesseract-ocr/tesseract/files/6255513/files_used.zip)

**Comment by stweil** [comment]
The included file `eng.test.exp0.tr` does not look like a .tr file. It seems to be a `unicharset` file.

**Comment by stweil** [comment]
The correct syntax should be

    mftraining -F font_properties -U unicharset -O font_name.unicharset font_name.font.exp0.tr

As you already have destroyed the .tr file because of the wrong syntax, you should recreate that file.

**Comment by Luhari** [comment]
Oh!

You are right, I was using the wrong syntax.

My bad and thank you for the answer ^^

I'm closing the issue

**Comment by Tejaskumar98** [comment]
Hi, my syntax is all correct... but still im getting the following error when i run the mftraining command.
![image](https://user-images.githubusercontent.com/46024195/185553482-aab379ea-81f3-4db7-a8a5-78d9f8098fa6.png)
i've followed the normal training methods mentioned in the documentation[link](https://tesseract-ocr.github.io/tessdoc/tess3/Training-Tesseract-3.00%E2%80%933.02.html) 
This is my first time posting a issue here, i dont know the procedure so pls Help me. Thank you.
This is all my files regarding the same. [Link to files](https://drive.google.com/file/d/1X4Snayx-1GQai70ow8B2kMyYZmQ4F2JK/view?usp=sharing)
