### ISSUE TITLE
Greek alphabets like Θ can't be recognized

### ISSUE THREAD

**Issue by ttbuffey** [tesseract-ocr/tesseract#3379]
### Environment

* **Tesseract Version**: 4.0
* **Commit Number**: 
* **Platform**: mac

### Current Behavior:
**Command:**
tesseract ~/Desktop/detector_sample_data-1.jpg ~/Desktop/result -l eng+ell+grc

### Expected Behavior:
**Greece National ID Card: Θ-420001** which has greek alphabets should be recognized, but **0-420001** is recognized

### Suggested Fix:
**for a english document which has few greek alphabets, the greek alphabets αβγδεζηθικλμνξοπρστυφχψωΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩABEZHIKMNOPTYX** should be recognized in the right way

**Comment by stweil** [comment]
This is not a software issue but more or less normal for OCR.

You can try using `-c load_number_dawg=0` and see whether that helps.

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for more questions.

**Comment by amitdo** [comment]
With the lstm engine, letter sequences that were not learnt during training have low chance to be recognized.

**Comment by stweil** [comment]
Yes, training some Greece National ID Card (~100 or more) with `tesstrain` would help to get better results.

**Comment by ttbuffey** [comment]
It's strange Θ-420001 **can't be recognized**，however， for the below sentense which contains greek alphabets **can be recognized**.
αβγδεζηθικλμνξοπρστυφχψωΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩABEZHIKMNOPTYX.

How can I solve this issue to able to recognize Θ-420001 ?

**Comment by ttbuffey** [comment]
@stweil @amitdo I have retrained a eng_finetuned.traineddata to recognize the greek alphabets. When i test in my local tesseract environment(4.1.1), I find it works. however, for my docker environment, it has an error:
**'Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/eng_finetuned.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng_finetuned\' Tesseract couldn\'t load any languages! Could not initialize tesseract.'**

in my dockerFile:
_**COPY ./tesseract/eng_finetuned.traineddata /usr/share/tesseract-ocr/4.00/tessdata/eng_finetuned.traineddata
COPY ./tesseract/ell.traineddata /usr/share/tesseract-ocr/4.00/tessdata/ell.traineddata**_
I copies my fine-tuned data and together with ell.traineddata downloaded from tesseract, 
the error occurs when I call  
**_"pytesseract.image_to_string(image, lang="eng_finetuned")"_**,
No error however is found when i call 
**_"pytesseract.image_to_string(image, lang="ell")"_**, the same way I copy the traineddata.

could you please help to point out the issue


PS: Docker tesseract version is 4.0.0, configured in Dockerfile:
RUN apt-get update && apt-get install -y build-essential tesseract-ocr poppler-utils
RUN apt-get install ffmpeg libsm6 libxext6  -y

**Comment by ttbuffey** [comment]
I have a question same as described in the below issue
https://github.com/Shreeshrii/tess4training/issues/15

@stweil  @amitdo Could you please point out why the performance decrease after I fine tune the english model.
