### ISSUE TITLE
PDF renderer in @egorpugin (unofficial) VC2015 build

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#338]
@egorpugin

>Try these binaries compiled by me.
https://www.dropbox.com/s/8t54mz39i58qslh/tesseract-3.05.00dev-win32-vc19.zip?dl=1
You have to install VC2015 x86 redist from microsoft.com in order to run them.
Leptonica is built with all libs except for libjp2k.

@nickbe

>This build does not create PDFs, but the cygwin from http://3.onj.me/tesseract/ build does.
So currently the VS build is not usable.

@jbreiden

>What is this business about certain builds not supporting PDF output? There is nothing special or weird with that section of code. Are they just old builds from before the feature was created, or is there something else going on?

@egorpugin

>Is there a simple command to check pdf generation?
I'll try to debug the issue (if any).

**Comment by amitdo** [comment]
@egorpugin

```
tesseract /path/to/phototest.tif phototest pdf
```

https://github.com/tesseract-ocr/tesseract/blob/master/testing/phototest.tif

**Comment by amitdo** [comment]
These traineddata files are required: eng, osd

**Comment by egorpugin** [comment]
Ok, and how should I understand what is incorrect? Where is tesseract output, error message, anything?
Entered this command, did some preparations and pdf is generated.
Works for me.
Latest binaries are here: https://www.dropbox.com/s/pxu2hp6mg1a64zj/tesseract-3.05.00dev-win32-vc19-2016-jun-03.zip?dl=1

**Comment by nickbe** [comment]
The other binaries simply didn't create a PDF.
But this one in fact does.

So, there's something wrong with the other VC builds.
Am Sa., Jun. 4, 2016 16:07 schrieb Egor Pugin : Ok, and how should I understand what is incorrect? Where is tesseract output, error message, anything?
 Entered this command, did some preparations and pdf is generated.
 Works for me.
 Latest binaries are here: https://www.dropbox.com/s/pxu2hp6mg1a64zj/tesseract-3.05.00dev-win32-vc19-2016-jun-03.zip?dl=1 (https://www.dropbox.com/s/pxu2hp6mg1a64zj/tesseract-3.05.00dev-win32-vc19-2016-jun-03.zip?dl=1)

**Comment by amitdo** [comment]
@egorpugin
How did you build these two (old and new) binaries?

**Comment by egorpugin** [comment]
Built liblept with every image library except jpeg2k, built tesseract with that lept. VS2015 Update 2.
I said that in previous thread (issue).
If tesseract.exe creates pdfs and other binaries not, give me simple repro for one of them, so I'll check.

**Comment by amitdo** [comment]
Since the problem does not exist in your **newer** build, maybe we should close this issue.

**Comment by egorpugin** [comment]
It works also on the old build. I checked.

**Comment by amitdo** [comment]
Do you have any guess why it does not work for @nickbe (the old build)?

**Comment by egorpugin** [comment]
Nobody wants to provide simple repro of this issue. I cannot guess what's the problem.

**Comment by amitdo** [comment]
I don't have Windows so I can't reproduce it myself...

**Comment by nickbe** [comment]
@amitdo: I didn't build any of these myself. I just followed download links and tried the various latest versions I found. Only thing I can say is that the mingW version worked, that the VC version from your link didn't and that the one from the link above works.

**Comment by amitdo** [comment]
Since both @nickbe and @egorpugin confirm that the PDF renderer feature works in the newer VC build, I'm closing this issue for now.
