### ISSUE TITLE
OCR Barcode

### ISSUE THREAD

**Issue by allancmello** [tesseract-ocr/tesseract#3385]
Tesseract does not read the numbers below the barcode and **_only shows the letter T_** that is missing from the image.
Is it possible to read the barcode numbers?

![image](https://user-images.githubusercontent.com/1229105/113897982-cd9bca00-97a1-11eb-81d5-323e04fa4c70.png)

------------------------

### Environment

* **Tesseract Version**: Latest
* **Platform**: Angular

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects. 
Reproduce your problem with resent version of tesseract executable and provide input image for reproducing error.
Make sure your read documentation.
