### ISSUE TITLE
getting to 0 option to work in ambigs

### ISSUE THREAD

**Issue by leoniesol** [tesseract-ocr/tesseract#339]
Placed ambigs problem in the mailing list but got no reply.  This I hope you can help.

Having trained tesseract in the Sinhala language we find we cannot get the 0 option in ambigs to work - no correction occurs even though the word is in the dictionary.

Please advise solution.

**Comment by amitdo** [comment]
I'm sorry, but we have a clear policy. We don't want to see questions here. only bug reports. I believe your problem is not a bug in Tesseract.

https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md

>Sometimes you will not get a respond to your issue or question. We apologize in advance! Please don't take it personally. There can be many reasons for this, including: time limits, no one knows the answer (at least not the ones that are available at that time) or just that your question has been asked (and has been answered) many times before...
