### ISSUE TITLE
Most recent tesseract version (github) bombs with signal 11

### ISSUE THREAD

**Issue by oberw** [tesseract-ocr/tesseract#3394]
NAME="openSUSE Tumbleweed"
# VERSION="20210311"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210311"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210311"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"

Most recent tesseract tesseract checkout (github) bombs with signal 11 on page 07 (attached zip) of 
a french language document.

walter@velasquez:tesseract-test>make
time tesseract -l fra imagelist montechristo alto hocr pdf txt 
Tesseract Open Source OCR Engine v5.0.0-alpha-20210401-57-g423f00 with Leptonica
Page 0 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_006.tif
Page 1 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_007.tif
Command terminated by signal 11
3.08user 0.02system 0:03.10elapsed 99%CPU (0avgtext+0avgdata 77596maxresident)k
0inputs+64outputs (0major+18867minor)pagefaults 0swaps
make: *** [Makefile:2: default] Fehler 139

[page07.zip](https://github.com/tesseract-ocr/tesseract/files/6291990/page07.zip)

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by stweil** [comment]
Thanks for reporting this issue. I can confirm it. It was introduced by commit f77b1c68814b15d0a2638b17aafb08ca96e26ccd.

**Comment by stweil** [comment]
Commit 33fa9d322361a68937987ed43d00f3237425d8c6 fixes this issue.

**Comment by oberw** [comment]
stweil, thanks.  Unfortunately, now we have incurred a new double free issue:

make
(cd ../tesseract; git rev-parse HEAD;git rev-parse --short HEAD)
81ecbfa53fc09c876161e2e789eaed4826e2b48c
81ecbfa5
time tesseract -l fra imagelist montechristo alto hocr pdf txt 
Tesseract Open Source OCR Engine v5.0.0-alpha-20210401-60-g81ec with Leptonica
Page 0 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_006.tif
Page 1 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_007.tif
Page 2 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_008.tif
Page 3 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_009.tif
Page 4 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_010.tif
Page 5 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_011.tif
double free or corruption (fasttop)
Command terminated by signal 6
10.94user 0.20system 0:10.89elapsed 102%CPU (0avgtext+0avgdata 441020maxresident)k
0inputs+8992outputs (0major+163375minor)pagefaults 0swaps
make: *** [Makefile:3: default] Fehler 134

**Comment by oberw** [comment]
Unfortunately I cannot attach the offending page 11 (too large). Where can I upload it without size limit (32 Mb) ?

**Comment by stweil** [comment]
You can upload it here: https://cloud.bib.uni-mannheim.de/s/4tW4tM2M7CG8EmB.

**Comment by oberw** [comment]
you may retrieve page11.zip from here: https://anonymousfiles.io/jSm93nNe/

**Comment by stweil** [comment]
Thanks again. That's now fixed with commit cca46e6b294b227770d676b8fe312cf9b0236a64.

**Comment by oberw** [comment]
thanks again and a tip to my hat towards MA.
Runs now as it did previsously.

walter@velasquez:tesseract-test>make
(cd ../tesseract; git rev-parse HEAD;git rev-parse --short HEAD)
cca46e6b294b227770d676b8fe312cf9b0236a64
cca46e6b
time tesseract -l fra imagelist montechristo alto hocr pdf txt 
Tesseract Open Source OCR Engine v5.0.0-alpha-20210401-61-gcca46 with Leptonica
Page 0 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_006.tif
....
approximately 500+ more....

**Comment by oberw** [comment]
Uh, oh. We are segfaulting again. Seems to be something very basic. 
See below. Before that last commit, tesseract was able to recognize the entire 600 page project.

[page06.zip](https://github.com/tesseract-ocr/tesseract/files/6298504/page06.zip)


walter@velasquez:tesseract-test>make
(cd ../tesseract; git rev-parse HEAD;git rev-parse --short HEAD)
91b2b4f4a08d4693b02838636c53a2af93397138
91b2b4f4
time tesseract -l fra imagelist montechristo alto hocr pdf txt 
Tesseract Open Source OCR Engine v5.0.0-alpha-20210401-66-g91b2b4 with Leptonica
Page 0 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_006.tif
Command terminated by signal 11
1.13user 0.03system 0:01.17elapsed 99%CPU (0avgtext+0avgdata 67472maxresident)k
0inputs+24outputs (0major+14559minor)pagefaults 0swaps
make: *** [Makefile:3: default] Fehler 139

**Comment by stweil** [comment]
This one was caused by commit 57c90eee02866ec929d8cd42e2de73a04464479f.

**Comment by stweil** [comment]
I get inconsistent results. After a fresh build, that image is processed without a crash.

**Comment by stweil** [comment]
Commit 4daf781916214fe7c8351724403b1d792ee1f8bd fixes the new regression.

**Comment by egorpugin** [comment]
How did it work previously? Returned trash after `buckets = std::make_unique<C_OUTLINE_LIST[]>(bxdim * bydim);`?
I had similar crashes on https://github.com/tesseract-ocr/tesseract/commit/57c90eee02866ec929d8cd42e2de73a04464479f?branch=57c90eee02866ec929d8cd42e2de73a04464479f&diff=unified#diff-483828f10960a9d2cb40bc2ea2d8e412340d3aef5b5d524a58546f5ece2a10f2L411-R430

**Comment by stweil** [comment]
The old code returned an empty `bucket_it`, and function `empty_buckets` did nothing for that case, too.

**Comment by egorpugin** [comment]
Who initialized that bucket_it to empty state?
I tried to undestand that code, but not sure I'm correct.

**Comment by stweil** [comment]
That was the result of function `start_scan` (which goes deep into the `ELIST` jungle).

**Comment by oberw** [comment]
I can confirm that the "bombing" has stopped :-) 
With another tip to my hat towards MA.... 

walter@velasquez:tesseract-test>make
(cd ../tesseract; git rev-parse --short HEAD)
4daf7819
time tesseract -l fra imagelist montechristo alto hocr pdf txt 
Tesseract Open Source OCR Engine v5.0.0-alpha-20210401-69-g4daf with Leptonica
Page 0 : ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_006.tif
.... approx 600 more pages...
