### ISSUE TITLE
Forgot to destroy mutex (operating system object leak) - ver <=4.1.1

### ISSUE THREAD

**Issue by fdivitto** [tesseract-ocr/tesseract#3397]
### Environment

* **Tesseract Version <=4.1.1**: 

### Current Behavior:

Operating system object leak when using LSTMRecognizer (that is tessdata ver 4). Each time you initialize a TessBaseAPI object you lose four mutexes.

### Suggested Fix:

SVMutex (svutil.h, svutil.cpp) hasn't a destructor, so CloseHandle (Windows) or pthread_mutex_destroy (*nix) is never called.
This should be fixed with version 5, but maybe this fix could be useful to people use <=4.1.1 versions.

```c++
SVMutex::~SVMutex() {
#ifdef _WIN32
  CloseHandle(mutex_);
#else
  pthread_mutex_destroy(&mutex_);
#endif
}
```

**Comment by egorpugin** [comment]
In master I do not see these variables ever freed as well.
https://github.com/tesseract-ocr/tesseract/blob/master/src/viewer/svutil.h#L56
Try to search here https://github.com/tesseract-ocr/tesseract/blob/master/src/viewer/svutil.cpp

@stweil

**Comment by stweil** [comment]
@fdivitto, you already suggested a solution for 4.1. Do you want to send a pull request against the 4.1 branch?

**Comment by stweil** [comment]
`SVSemaphore` has a similar issue.

**Comment by fdivitto** [comment]
Here is my pull request:

[https://github.com/tesseract-ocr/tesseract/pull/3398](https://github.com/tesseract-ocr/tesseract/pull/3398)

**Comment by stweil** [comment]
Thank you. The semaphore part is needed for git master, too.

**Comment by stweil** [comment]
Solved now.
