### ISSUE TITLE
tesseract opencl jupyterhub

### ISSUE THREAD

**Issue by Geronium** [tesseract-ocr/tesseract#3399]
Hello,

i'm trying to use tesseract with the gpu insite a docker container of jupyter. 

 i installed opencl and tesseract, i can see my gpu on opencl

"**clinfo** 
Number of platforms                               1
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 1.2 CUDA 11.2.109
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_nv_kernel_attribute cl_khr_device_uuid
  Platform Extensions function suffix             NV

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     Tesla V100-PCIE-32GB
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 1.2 CUDA
  Valid Device LUID                               No
  Device LUID                                     b0fb-6730fd7f0000
  Device Node Mask                                0
  Driver Version                                  460.32.03
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Topology (NV)                            PCI-E, 0000:5b:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               80
  Max clock frequency                             1380MHz
  Compute Capability (NV)                         7.0
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x64
  Max work group size                             1024
  Preferred work group size multiple (kernel)     32
  Warp size (NV)                                  32
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              34089730048 (31.75GiB)
  Error Correction support                        Yes
  Max memory allocation                           8522432512 (7.937GiB)
  Unified memory for Host and Device              No
  Integrated memory (NV)                          No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       4096 bits (512 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        2621440 (2.5MiB)
  Global Memory cache line size                   128 bytes
  Image support                                   Yes
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            268435456 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             32768x32768 pixels
    Max 3D image size                             16384x16384x16384 pixels
    Max number of read image args                 256
    Max number of write image args                32
  Local memory type                               Local
  Local memory size                               49152 (48KiB)
  Registers per block (NV)                        65536
  Max number of constant args                     9
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     4352 (4.25KiB)
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Kernel execution timeout (NV)                 No
  Concurrent copy and kernel execution (NV)       Yes
    Number of async copy engines                  7
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_nv_kernel_attribute cl_khr_device_uuid

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  NVIDIA CUDA
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [NV]
  clCreateContext(NULL, ...) [default]            Success [NV]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.3.0
  ICD loader Profile                              OpenCL 3.0"

i don't see opencl on tesseract 

But tesseract doesn't support opencl

**tesseract -v**
tesseract 4.1.1
 leptonica-1.78.0
  libgif 5.2.1 : libjpeg 9d : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 1.2.0 : libopenjp2 2.3.1
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.4.2 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4

I installed this packages

**dpkg -l | grep -i opencl**
ii  nvidia-cuda-doc                    10.1.243-3                        all          NVIDIA CUDA and OpenCL documentation
ii  nvidia-opencl-dev:amd64            10.1.243-3                        amd64        NVIDIA OpenCL development files
ii  nvidia-profiler                    10.1.243-3                        amd64        NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-visual-profiler             10.1.243-3                        amd64        NVIDIA Visual Profiler for CUDA and OpenCL
ii  ocl-icd-libopencl1:amd64           2.2.11-1ubuntu1                   amd64        Generic OpenCL ICD Loader
ii  ocl-icd-opencl-dev:amd64           2.2.11-1ubuntu1                   amd64        OpenCL development files
ii  opencl-c-headers                   2.2~2019.08.06-g0d5f18c-1         all          OpenCL (Open Computing Language) C header files

dpkg -l | grep -i sseract
ii  libtesseract-dev:amd64             4.1.1-2build2                     amd64        Development files for the tesseract command line OCR tool
ii  libtesseract4:amd64                4.1.1-2build2                     amd64        Tesseract OCR library
ii  tesseract-ocr                      4.1.1-2build2                     amd64        Tesseract command line OCR tool
ii  tesseract-ocr-eng                  1:4.00~git30-7274cfa-1            all          tesseract-ocr language files for English
ii  tesseract-ocr-osd                  1:4.00~git30-7274cfa-1            all          tesseract-ocr language files for script and orientation

and inside /etc/OpenCL/vendors i can find my icd 

**cat nvidia.icd** 
libnvidia-opencl.so.1

with pyopencl, i can list my gpu

**python testopencl.py** 

Platform: NVIDIA CUDA
Device: Tesla V100-PCIE-32GB (ALL | GPU)
        Global memory:          31.74853515625 GB
        Global cache:           2560.0 KB (READ_WRITE_CACHE)
        Global cache line:      128 B
        Local memory:           48.0 KB (LOCAL)
        Constant memory:        64.0 KB
        Compute units:          80
        Max work-group size:    1024
        Max work-item size:     [1024, 1024, 64]
        Lockstep unit:          32

I read a lot of time the documentation, they speak about a **tesseract_opencl_profile_devices.dat** and a **configure.ac** , but i don't have this files. Do you know, what i need to do, for tesseract work with opencl ?

Thank you

**Comment by stweil** [comment]
There is no support for OpenCL with Tesseract. It's a feature which is only available for developers.

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions or search the issues here for more issues related to OpenCL.

**Comment by Geronium** [comment]
Hello, thank you for your answer 

ok, so in production we need to use only cpu ?

I downloaded tesseract, after indicating as in the doc ./configure --enable-opencl, I have this error

"
(ocr) myuser@jupyter:~/tesseract-5.0.0-alpha-20210401$ make
make  all-recursive
make[1]: Entering directory '/app/home/myuser/tesseract-5.0.0-alpha-20210401'
Making all in .
make[2]: Entering directory '/app/home/myuser/tesseract-5.0.0-alpha-20210401'
  CXX      src/api/tesseract-tesseractmain.o
src/api/tesseractmain.cpp:35:12: fatal error: openclwrapper.h: No such file or directory
   35 | #  **include "openclwrapper.h" // for OpenclDevice**
      |            ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:8239: src/api/tesseract-tesseractmain.o] Error 1
make[2]: Leaving directory '/app/home/myusr/tesseract-5.0.0-alpha-20210401'
make[1]: *** [Makefile:8648: all-recursive] Error 1
make[1]: Leaving directory '/app/home/myusr/tesseract-5.0.0-alpha-20210401'
make: *** [Makefile:3152: all] Error 2"

i have an openclwrapper.h but at ./src/opencl/openclwrapper.h and if i copy the file to src/api/, a new error appear 

In file included from src/api/tesseractmain.cpp:36:
src/api/openclwrapper.h:130:61: error: ‘Image’ has not been declared
  130 |   static int initMorphCLAllocations(l_int32 wpl, l_int32 h, Image pixs);
      |                                                             ^~~~~
src/api/openclwrapper.h:133:29: error: ‘Image’ has not been declared
  133 |   static void pixGetLinesCL(Image pixd, Image pixs, Image *pix_vline, Image *pix_hline, Image *pixClosed,
      |                             ^~~~~
src/api/openclwrapper.h:133:41: error: ‘Image’ has not been declared
  133 |   static void pixGetLinesCL(Image pixd, Image pixs, Image *pix_vline, Image *pix_hline, Image *pixClosed,
      |                                         ^~~~~
src/api/openclwrapper.h:133:53: error: ‘Image’ has not been declared
  133 |   static void pixGetLinesCL(Image pixd, Image pixs, Image *pix_vline, Image *pix_hline, Image *pixClosed,
      |                                                     ^~~~~
src/api/openclwrapper.h:133:71: error: ‘Image’ has not been declared
  133 |   static void pixGetLinesCL(Image pixd, Image pixs, Image *pix_vline, Image *pix_hline, Image *pixClosed,
      |                                                                       ^~~~~
src/api/openclwrapper.h:133:89: error: ‘Image’ has not been declared
  133 |   static void pixGetLinesCL(Image pixd, Image pixs, Image *pix_vline, Image *pix_hline, Image *pixClosed,
      |                                                                                         ^~~~~
src/api/openclwrapper.h:164:89: error: ‘Image’ has not been declared
  164 |                                    int bytes_per_line, int *thresholds, int *hi_values, Image *pix,


Thanks again

**Comment by Geronium** [comment]
with the version 4.1.1, it's all right, after the installation, i can see opencl when i make tesseract -v

**tesseract -v** 
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 OpenCL info:
  Found 1 platform(s).
  Platform 1 name: NVIDIA CUDA.
  Version: OpenCL 1.2 CUDA 11.2.109.
  Found 1 device(s).
    Device 1 name: Tesla V100-PCIE-32GB.
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4

but when i convert an image to text, it doesn't use the gpu.

**Comment by stweil** [comment]
>  src/api/openclwrapper.h:130:61: error: ‘Image’ has not been declared

That's caused by recent changes (commit a792b67983930bb92ff2a40d2a2f1f81d059557d) which did not update that code.

**Comment by amitdo** [comment]
@stweil,

Maybe we should add a WARNING MESSAGE ABOUT OPENCL (ALL MESSAGE IN UPPERCASE) that will appear at the end of `configure` output?

**Comment by zdenop** [comment]
I would suggest to remove it from version 5 - there is no maintainer, there are bug/problems and IMO it has (almost) no effect on speed.

**Comment by stweil** [comment]
I disagree. Missing GPU support is a problem, especially for training which currently takes days, weeks or even months. OpenCL could be a solution with the advantage that it is not restricted to NVIDIA cards. We have plans to work on faster training. As soon as there is a different solution for training Tesseract with GPU I'd agree to remove OpenCL.

**Comment by kbrajwani** [comment]
@stweil Hey if you see the logs main problem is **src/api/openclwrapper.h:133:29: error: ‘Image’ has not been declared** .
Don't you think it can be solve by incluse image file i have tried the following in openclwrapper.h but it's not working. Can you please suggest something i have to reduce timing of ocr and i have gpu system so opencl can works better for me.
```
include <allheaders.h>
include "image.h"
```

**Comment by stweil** [comment]
Please don't use OpenCL unless you are an experienced software developer and want to fix the code yourself.

**Comment by kbrajwani** [comment]
Hey @stweil Thanks for reply. One last question can you please give suggestion if i have to do ocr of one document with 500 words in 1-1.5 second Then is this possible with tesseract? my image size is 2500*3200. I have set OMP_THREAD_LIMIT and tessedit_do_invert but still wants more improvement in time. i don't mind using any high-level machine.
