### ISSUE TITLE
BUG: In hOCRed text, some words overlap the previous word; as if there is no space between them

### ISSUE THREAD

**Issue by raindropsfromsky** [tesseract-ocr/tesseract#3403]
------------------------

### Environment

* **Tesseract Version**: I am using the [latest gImageReader](https://github.com/manisandro/gImageReader/releases/tag/ci-latest-master). 
* **Commit Number**: 
* **Platform**: Windows 10 Home, 64 bit

### Current Behavior:

The bug is described here: 
https://github.com/manisandro/gImageReader/issues/507

The gImageReader developer says that the problem originates from the hOCR output of Tesseract.

### Expected Behavior:
Please see the bug at https://github.com/manisandro/gImageReader/issues/507

### Suggested Fix:
The bounding boxes should be spaced apart properly.

**Comment by zdenop** [comment]
Please respect requirements for posting issue. 
Provide input about output file, version informations (tesseract and language data) etc.

**Comment by amitdo** [comment]
The OP did not provide the input image and the required information, like the Tesseract version that he used.
