### ISSUE TITLE
System.AccessViolationException How do I fix it?

### ISSUE THREAD

**Issue by littlewe1337** [tesseract-ocr/tesseract#3409]
The program closes after one or two hours

App: TesseractCombine.exe
ver: v4.0.30319
Description. The process was terminated due to an unprocessed exception.
Information about exclusion: System.AccessViolationException
in InteropRuntimeImplementer.TessApiSignaturesInstance.TessApiSignaturesImplementation.BaseApiRecognize(System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef)
in Tesseract.Page.Recognize()
in Tesseract.Page.GetText()
in TesseractCombine.FormMain.GetText(Byte[])
in TesseractCombine.FormMain.text_Lightshot(System.String, System.String, Int32)
in TesseractCombine.FormMain+d__31.MoveNext()
in System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
in  System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
in  System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
in  System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()

in 
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
in System.Threading.Tasks.Task.FinishContinuations()
in System.Threading.Tasks.Task.FinishStageThree()
in  System.Threading.Tasks.Task.FinishStageTwo()
in  System.Threading.Tasks.Task.Finish(Boolean)
in  System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
in  System.Threading.Tasks.Task.ExecuteEntry(Boolean)
in  System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
in  System.Threading.ThreadPoolWorkQueue.Dispatch()
in  System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by amitdo** [comment]
You have an issue with a third party tool/library which we do not support.
