### ISSUE TITLE
Can't compile libtesseract with GRAPHICS_DISABLED or DISABLED_LEGACY_ENGINE set

### ISSUE THREAD

**Issue by rweldin** [tesseract-ocr/tesseract#3412]
The current code as of commit a9682bb6e2c32797f455c95de66ea87e00624dbe will not compile with GRAPHICS_DISABLED or DISABLED_LEGACY_ENGINE set to 1. There are numerous errors generated from PointerVector which are noted in the attached Errors.txt file.

I'm compiling on Windows 10 with MSVS 2017 and using cmake to generate a solution file with the following options: cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=1 -DSW_BUILD_SHARED_LIBS=0 -DGRAPHICS_DISABLED=1 -DDISABLED_LEGACY_ENGINE=1 -DBUILD_TRAINING_TOOLS=0 ..

When setting GRAPHICS_DISABLED and DISABLED_LEGACY_ENGINE to 0 the current source compiles fine.

[Errors.txt](https://github.com/tesseract-ocr/tesseract/files/6411727/Errors.txt)

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/commit/d6cdc521

**Comment by egorpugin** [comment]
@rweldin 
Can you try to build tess with the same flags on VS2019?

**Comment by egorpugin** [comment]
Confirmed, reverted.
Seems the following CI is related to this mode (`DISABLED_LEGACY_ENGINE`).
https://github.com/tesseract-ocr/tesseract/actions/workflows/unittest-disablelegacy.yml

**Comment by egorpugin** [comment]
@Shreeshrii
Do you monitor created CIs?

There are a lot of them today.
We need to monitor them somehow. Maybe create badges on readme page.

**Comment by rweldin** [comment]
@egorpugin I don't have VS2019 setup on the machine I'm working on, but can do so tomorrow if you need additional testing there. When compiling on VS2017 after applying the reversion I now get an unresolved external symbol error which is noted in the attached Error.txt file. If you need any other information let me know.

[Error.txt](https://github.com/tesseract-ocr/tesseract/files/6418462/Error.txt)

**Comment by egorpugin** [comment]
@rweldin
1. VS2019 test is not needed that much, thank you.
2. (error) Try to rebuild all. Probably some old flag cached in some object files. I did not see this locally (VS2019).

**Comment by rweldin** [comment]
@egorpugin I'm getting the same error as noted in my previous comment. Perhaps this is related to commit 875bd48bd5281cc7866c5e390a1aab7c290c8874

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/2be896d2b938df6366328d4f0e116367af1d7252/src/viewer/scrollview.h#L161

https://github.com/tesseract-ocr/tesseract/blob/2be896d2b938df6366328d4f0e116367af1d7252/src/viewer/scrollview.h#L379-L381

So, it's not clear why the compiler complains about it.

Egor,

The autotools build does not disable compilation of cpp files and some of the headers in the `src/viewer` dir when `GRAPHICS_DISABLED` is defined. CMake does not do the same thing.

**Comment by egorpugin** [comment]
Autotools should not do conditional compilations.
I thought about it yesterday.

**Comment by egorpugin** [comment]
@rweldin
Please try on fresh build dir if you did not.

**Comment by rweldin** [comment]
Unfortunately I continue to receive the same error after trying multiple times. I tried to recompile after making each the following changes:

clone into a new directory
clear sw cache
install current release of cmake and generate a new VS solution

Below is the output from Visual Studio 2017:

3>   Creating library R:/tesseract/win64/Release/tesseract50.lib and object R:/tesseract/win64/Release/tesseract50.exp
3>scanedg.obj : error LNK2019: unresolved external symbol "private: static class tesseract::SVNetwork * tesseract::ScrollView::stream_" (?stream_@ScrollView@tesseract@@0PEAVSVNetwork@2@EA) referenced in function "private: static class tesseract::SVNetwork * __cdecl tesseract::ScrollView::GetStream(void)" (?GetStream@ScrollView@tesseract@@CAPEAVSVNetwork@2@XZ)
3>R:\tesseract\win64\bin\Release\tesseract50.dll : fatal error LNK1120: 1 unresolved externals
3>Done building project "libtesseract.vcxproj" -- FAILED.
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========

**Comment by egorpugin** [comment]
@rweldin 
Confirmed, fix was applied. Try it on master.

**Comment by rweldin** [comment]
@egorpugin all is well on the current master. Thank you!
