### ISSUE TITLE
Failed loading language 'eng on 4.1.1

### ISSUE THREAD

**Issue by ojades** [tesseract-ocr/tesseract#3414]
I have successfully installed tesseract on my docker app running ubuntu 18.04. I downloaded the `eng.traineddata` and stored in `/usr/local/share/tessdata`. But when I run ` tesseract --list-langs`, I get:

```
Error opening data file /usr/local/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
List of available languages (2):
eng
osd
```

I have tried different suggestions but no luck

**Comment by tandelDipak** [comment]
@ojades found the solution in forum. Check out this discussion https://groups.google.com/g/tesseract-ocr/c/KKTiag0VCFE/m/A4jpS6i6CwAJ

Let me know whether it solves your issue or not.

**Comment by ojades** [comment]
Thanks @tandelDipak that worked for me.

**Comment by xkid89** [comment]
Hello sorry for ask here but currently i face same the problem and solution on group not work for me. I using RHEL 8 and here my version tesseract. How to fix it please, thank you so much
```
tesseract 4.1.1
 leptonica-1.80.0
  libjpeg 6b (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0
 Found AVX2
 Found AVX
 Found SSE
```

Errors
```
[leon@localhost setup_tesseract_V2]$ tesseract --list-langs
Error opening data file /usr/local/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
List of available languages (2):
eng
tha
```

**Comment by zdenop** [comment]
And did you check if e.g. filesize is the same as in github repository?

**Comment by xkid89** [comment]
> And did you check if e.g. filesize is the same as in github repository?

It different with size notice in https://github.com/tesseract-ocr/tessdata_best/blob/main/eng.traineddata
My file downloaded from there but have 15.4MB

**Comment by xkid89** [comment]
update command install leptonica and tesseract
```
#= leptonica
tar -zxvf ./tar/leptonica-1.80.0.tar.gz
cd leptonica-1.80.0
sudo make clean
./configure
make
sudo make install

#= Tesseract
tar -zxvf ./tar/tesseract-4.1.1.tar.gz
cd tesseract-4.1.1
sudo make clean
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
./autogen.sh
./configure
make
sudo make install
sudo ldconfig
```

**Comment by zdenop** [comment]
If filesize differ - you have wrong language data and tesseract will failed to use them.

**Comment by xkid89** [comment]
Lucky dinner time i found problem.I using user not root so need add my current user to root group and provide permission for access *.traineddata
### Tesseract: must provide permission and add user to root group for access trained file
`sudo usermod -a -G groupname username`
### if still can’t access then provide permission this file
`chmod u=rwx,g=rwx,o=rwx [file_name]`

Thank you for support me @zdenop . Regards
