### ISSUE TITLE
how can I debug the tesseract?

### ISSUE THREAD

**Issue by SmartTransp** [tesseract-ocr/tesseract#3415]
* **Platform**: windows , linux

I wrote a simple code in python using tesseract and cv2 that detect numbers from license plate .
4 out of 10 it's working great 
is there any way to know why the other 6 times it doesn't work , I get garbage or even empty response? (on the same code...)
why it see "7" and not "1" ? why he see nothing and not even 1 number?

for example when the license is 53-7474-35 this is what I get:
`licensePlateNumber2 = pytesseract.image_to_string(rotated, config='--psm 11 -c tessedit_char_whitelist=0123456789')
print(licensePlateNumber2 )
153747435
`
 when I run the 
`print(image_to_date(rotated)`
I get this table :
```
level	page_num	block_num	par_num	line_num	word_num	left	top	width	height	conf	text
1	1	0	0	0	0	0	0	392	171	-1	
2	1	1	0	0	0	34	63	302	52	-1	
3	1	1	1	0	0	34	63	302	52	-1	
4	1	1	1	1	0	34	63	302	52	-1	
5	1	1	1	1	1	30	59	12	70	79	|
5	1	1	1	1	2	70	66	266	45	10	153:7474°35
2	1	2	0	0	0	7	145	385	24	-1	
3	1	2	1	0	0	7	145	385	24	-1	
4	1	2	1	1	0	7	145	385	24	-1	
5	1	2	1	1	1	3	139	216	32	0	ieee
5	1	2	1	1	2	261	139	131	32	0	—
```

is there any information I get from this to understand something ?

when I try to find 589-80-201 I get :
```
level	page_num	block_num	par_num	line_num	word_num	left	top	width	height	conf	text
1	1	0	0	0	0	0	0	391	164	-1	
2	1	1	0	0	0	25	9	363	115	-1	
3	1	1	1	0	0	25	9	363	115	-1	
4	1	1	1	1	0	25	9	363	115	-1	
5	1	1	1	1	1	25	9	363	115	95	 

you license plate 2 is  59900201
```

maybe I need to edit the image \ mask \ cut it somethig?
how can I know what the "tesseract" see and what it does? so mayen then I will understand what I need to chagne ?

THanks ,

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
