### ISSUE TITLE
tesseract: symbol lookup error: tesseract: undefined symbol: _ZN9tesseract16TessTextRendererC1EPKc

### ISSUE THREAD

**Issue by fusae** [tesseract-ocr/tesseract#342]
I follow these installation steps:
`./autogen.sh`
`./configure`
`make`
`make install`
I run `tesseract -v`, it works.
 then I run `tesseract pic.gif result`, I got that undefine symbol error. How to fix it?

**Comment by amitdo** [comment]
Please send your question to the [users mailing-list](https://groups.google.com/d/forum/tesseract-ocr).

https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md

**Comment by LeaderMalang** [comment]
**Here is the solution for ubuntu 18.04**
Please first install the libraries which are required for tesseract-ocr
`sudo apt install libtesseract-dev libleptonica-dev liblept5`
Then simple install tesseract using command 
`sudo apt install tesseract-ocr -y`
