### ISSUE TITLE
Tesseract doesn't recognize some words on images written in various langagues.

### ISSUE THREAD

**Issue by skydev66** [tesseract-ocr/tesseract#3423]
I've tested for an image that is written in English and Korean. 

![2](https://user-images.githubusercontent.com/61202332/117929610-989a0e80-b32f-11eb-883c-51c0c89e23c4.jpg)

As you can see, the image quality is not so bad.
However most of the words written in Korean were not recognized.

**Comment by amitdo** [comment]
Did you triyusing the `Hangul.traineddata`?

**Comment by skydev66** [comment]
Ah, I only tried with "kor.traineddata". I will test with "Hangul.traineddata".
Thank you.

**Comment by skydev66** [comment]
Could you provide that file?

**Comment by hglee** [comment]
Korean text does not deteted with default PSM for sample image.

Would you try with PSM 11? You can try like this

`tesseract.exe in.jpg out -l eng+kor --psm 11`

Or you can use PSM 7 after split image line by line.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tessdata_best/tree/master/script
https://github.com/tesseract-ocr/tessdata/tree/master/script
https://github.com/tesseract-ocr/tessdata_fast/tree/master/script
