### ISSUE TITLE
how to recognition hollow word?

### ISSUE THREAD

**Issue by cyenchen** [tesseract-ocr/tesseract#343]
recognition hollow word 
how to configure,like this image:
![image](https://cloud.githubusercontent.com/assets/18211005/15988507/2dfa0660-3086-11e6-9e39-f36645a31fed.png)

**Comment by amitdo** [comment]
Please send your question to the [users mailing-list](https://groups.google.com/d/forum/tesseract-ocr).

See [CONTRIBUTING](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md)
