### ISSUE TITLE
tesseract extracting text as html format

### ISSUE THREAD

**Issue by nabilalakhani** [tesseract-ocr/tesseract#3430]
hi
i am noob using tesseract with java
i tried extracting text from a .png and .jpg file but its giving output in html format
below is output

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name='ocr-system' content='tesseract'/>
</head>
<body>
  <div class='ocr_page' id='page_1' title='image "G:\file.JPG"; bbox 0 0 39 21; ppageno 0'>
   <div class='ocr_carea' id='block_1_1' title="bbox 7 7 33 16">
    <p class='ocr_par' id='par_1_1' lang='eng' title="bbox 7 7 33 16">
     <span class='ocr_line' id='line_1_1' title="bbox 7 7 33 16; baseline 0 0; x_size 20; x_descenders 5; x_ascenders 5">
      <span class='ocrx_word' id='word_1_1' title='bbox 7 7 33 16; x_wconf 92'>File</span>
     </span>
    </p>
   </div>
  </div>
</body>
</html>

Warning: Invalid resolution 0 dpi. Using 70 instead.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
