### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by MatCorr** [tesseract-ocr/tesseract#3440]
### Environment

* **Tesseract Version**: 4.1.1
* **Commit Number**: 7510304 (Downloaded the source code zip from [here](https://github.com/tesseract-ocr/tesseract/releases/tag/4.1.1))
* **Platform**: Ubuntu 18.04.3 LTS (Bionic Beaver) 64-bit

### Current Behavior:

After downloading, and unzipping the file, I run:

$ ./autogen.sh
$ ./configure
$ make

However, the make command ends up returning the following error:

/opt/conda/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -llept
collect2: error: ld returned 1 exit status
Reaping losing child 0x55df97727ad0 PID 88552
make[2]: *** [Makefile:543: libtesseract.la] Error 1
Removing child 0x55df97727ad0 PID 88552 from chain.
make[2]: Leaving directory '/home/tesseract-4.1.1/src/api'
Reaping losing child 0x56080c2f40f0 PID 88512
make[1]: *** [Makefile:501: all-recursive] Error 1
Removing child 0x56080c2f40f0 PID 88512 from chain.
make[1]: Leaving directory '/home/tesseract-4.1.1'
Reaping losing child 0x55bdb1945eb0 PID 88511
make: *** [Makefile:410: all] Error 2
Removing child 0x55bdb1945eb0 PID 88511 from chain.

Let me know if more information is necessary.

### Expected Behavior:

Command should run successfully.

### Suggested Fix:

Initially, given the "cannot find -llept" message, I assumed it had something to do with leptonica. But it has already been installed, as seen from the execution below:

$ sudo apt-get install -y libleptonica-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libleptonica-dev is already the newest version (1.78.0-1+nmu1ppa1~bionic1).
0 upgraded, 0 newly installed, 0 to remove and 203 not upgraded.

**Comment by zdenop** [comment]
> /opt/conda/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld:

This indicates that you are not using standard build system, but some alternative -> This is not tesseract problem but problem of your own setup and we can not do nothing with it.
