### ISSUE TITLE
Spaces betwen words frequently missing in exported PDFs (gImageReader, Win10)

### ISSUE THREAD

**Issue by ReaderGuy42** [tesseract-ocr/tesseract#3441]
------------------------

### Environment

* **Tesseract Version**: gImageReader 3.3.1 (17fa17)
* **Commit Number**: ?
* **Platform**: Window 64 bit

### Suggested Fix: (I tried it with the "Middle English" language option, which gave the same results: Words and letters are recognized near-perfectly and the hOCR and html files look great, but the exported PDFs with invisible text layer are lacking the spaces.

If you highlight and copy some text in the attached pdf you should see what I mean.

[1 - Copy.pdf](https://github.com/tesseract-ocr/tesseract/files/6526100/1.-.Copy.pdf)

Thanks :)

**Comment by amitdo** [comment]
gImageReader uses its own code for PDF export.

Report this issue to the gImageReader project.

**Comment by amitdo** [comment]
https://github.com/manisandro/gImageReader/issues/519
