### ISSUE TITLE
Tesseract-OCR

### ISSUE THREAD

**Issue by Amjadbaidas** [tesseract-ocr/tesseract#3444]
Hi,

I'm a new user of tesseract-OCR and I want to put some specs for a project that I want to do for one of our clients. I just have a question, is tesseract-OCR can be used on VM machine or not? and if yes, what are the best specs of the VM that guarantee the best performance for that?

Thanks in advance.

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
