### ISSUE TITLE
Root source structure update

### ISSUE THREAD

**Issue by egorpugin** [tesseract-ocr/tesseract#3445]
Hi,

Can we reorganize root of our sources as follows?
What do you think?

1. Move `abseil` and `googletest` into `third_party`.
2. Somehow hide `m4`? Move to some subdir? (e.g. `build/m4`)
3. Move `cmake` into `build/cmake`.
4. Move `snap` somewhere? `build/snap`?

![image](https://user-images.githubusercontent.com/4325333/119985234-123a2980-bfcb-11eb-8e87-e53ef046e314.png)

@stweil @amitdo @zdenop

**Comment by egorpugin** [comment]
After such changes we'll have -
![image](https://user-images.githubusercontent.com/4325333/119985837-d81d5780-bfcb-11eb-95bc-21011400535e.png)

**Comment by stweil** [comment]
`build` is a very common choice for out-of-tree builds, so I would not use that for files which are managed by Git.

Why should we change the root structure? Do you just want to reduce the number of entries in root? Then `abseil`, `googletest` and `test` could be moved to `unittest` and / or `unittest/third_party` (which already exists), and `java` could be moved to `src`.

**Comment by amitdo** [comment]
`abseil` and `googletest` are used only by the unit tests.

So maybe move it to `unittest/third_party` which is already exist?

**Comment by stweil** [comment]
@elopio, is it possible to move `snap/snapcraft.yaml` to a different place?

**Comment by amitdo** [comment]
My last message was written before I saw @stweil's message.

>and java could be moved to src.

-1

Don't mix C++ with Java.

**Comment by amitdo** [comment]
Unless you meant

src
* cpp
* java

**Comment by stweil** [comment]
Let me repeat my question: why should we change the directory structure at all? Personally I have no problems with it, and there is other work to be done which would really help all users of Tesseract.

Small changes like moving `abseil` and `googletest` to `unittest/third_party` are fine for me. I can do that it everybody agrees.

**Comment by egorpugin** [comment]
> Do you just want to reduce the number of entries in root?

Yes.

**Comment by egorpugin** [comment]
`java` is fine in the root. See https://github.com/protocolbuffers/protobuf

**Comment by zdenop** [comment]
Moving `abseil`, `googletest` to  `unittest` | `unittest/third_party` seems reasonable for me.

I thing we should avoid using generic names like `build` (or possible  `config`) . Personally I do not see to reason to hide m4 or cmake (e.g.  [xz](https://git.tukaani.org/?p=xz.git;a=tree;h=refs/heads/master;hb=refs/heads/master) or [opencv](https://github.com/opencv/opencv)) directory as there are quite common...

**Comment by amitdo** [comment]
It seems everyone agree to move `googletest` to `unittest/third_party`.

**Comment by stweil** [comment]
Implemented in pull request #3618. Should that be done before 5.0.0 is released?

**Comment by amitdo** [comment]
Yes, IMO.

**Comment by amitdo** [comment]
@egorpugin, 

Can we close this issue?

**Comment by egorpugin** [comment]
Yes, it's better now.
