### ISSUE TITLE
Windows msvc 2019 build broken [again]

### ISSUE THREAD

**Issue by gilgm12** [tesseract-ocr/tesseract#3448]
Master branch, latest - I've also tried several others.  cmake 3.20.0-rc1. (edit: just updated to cmake 3.20.3 release as a sanity check, same behavior)

Additionally - tess v4.1.1 doesn't build with cmake + sw. (line 61 of sw.cpp needs to concat _slib, not _l) so I'm working from 5 alpha + master.

![d315b11eaf30e6f4dcbeba58f00f78c2](https://user-images.githubusercontent.com/622590/120690805-e99aaf80-c462-11eb-8a24-9d2cec06e0be.png)

![0585a87bcae89b01afd2cea123e7d998](https://user-images.githubusercontent.com/622590/120690752-d7b90c80-c462-11eb-83c2-329e54054a9e.png)

Can anybody point me to a commit that will compile?

Hiccup appears to be here: loc.sw.self.f28e64-0.0.28.dll

Visual Studio 16 2019 Generator.

**Comment by gilgm12** [comment]
FWIW, this appears to be an issue with sw - the vcpkg route worked for me, and resulted in a clean build of 4.1.1.

**Comment by egorpugin** [comment]
Update VS2019 to 16.10.
