### ISSUE TITLE
Big time gap in default model and trained model

### ISSUE THREAD

**Issue by kbrajwani** [tesseract-ocr/tesseract#3450]
------------------------

### Environment

* **Tesseract Version**: tesseract 5.0.0-alpha-20210401-94-ga968
* **Platform**: ubuntu 18.04 colab 

### Current Behavior:

I have attached the image where we can see default model is taking time around 4 sec and trained model is about 6 sec. 

![image](https://user-images.githubusercontent.com/29722986/120894921-68951100-c638-11eb-9769-6d4d090d1018.png)

### Expected Behavior:

I want to reduce the time as per the default model.

**Comment by amitdo** [comment]
There is an option to convert a model marix type from double to int.

**Comment by kbrajwani** [comment]
Thanks @amitdo if you can see image there is int mode is already on.
I have check combine_tessdata -l for default and trained model both are same.
So if you are telling me to use convert_int at time of stop training then i already have done that.
Can you tell me what is the thing you recommend.

**Comment by amitdo** [comment]
https://tesseract-ocr.github.io/tessdoc/tess4/TrainingTesseract-4.00.html#lstmtraining-command-line

**Comment by kbrajwani** [comment]
@amitdo why you close the issue as i already tell you i have used convert_to_int parameters after that i am getting this time gap.
So can you tell me how can i reduce time?

**Comment by amitdo** [comment]
I didn't see your message.

**Comment by kbrajwani** [comment]
No problem do you know about this issue how can i solve as the combine_tessdata response are same for trained and default model.
Is there any difference which is making this much time difference?

**Comment by amitdo** [comment]
I don't know why there is a speed difference between the models.

**Comment by kbrajwani** [comment]
Hey @amitdo can you please assign this issue to any collaborator so I can get any solutions?  Or can you please give me some suggestions on how I can dig deep into it?

**Comment by amitdo** [comment]
>Hey @amitdo can you please assign this issue to any collaborator so I can get any solutions?

Sorry but no. I didn't did until now and I don't think it will help.

>Or can you please give me some suggestions on how I can dig deep into it?

I don't have a solution to every problem... Currently, I have no suggestion for you.

**Comment by kbrajwani** [comment]
No problem, Thanks for kind reply. Let's see if i can able to find solutions or some community members find the same issue.

**Comment by nagadomi** [comment]
@kbrajwani 
```
% combine_tessdata -l ../tessdata_fast/eng.traineddata 
LSTM: network=[1,36,0,1Ct3,3,16Mp3,3Lfys48Lfx96Lrx96Lfx192O1c1] ...
```
`tessdata_fast/eng.traindata` has a smaller LSTM hidden size than `eng2` and `eng_int`. I think that's why it's so fast.

`tessdata_fast/eng.traineddata` is not just an integer quantized model of `tessdata_best/eng.traineddata`, it seems to have a different network architecture. (And it can't finetuning)

**Comment by kbrajwani** [comment]
@nagadomi  Yes, You're right the main difference is here 3Lfys48Lfx96Lrx96Lfx192O1c1 and we are traning the model with 3Lfys64Lfx96Lrx96Lfx512O1c1 this config. 
Thanks
