### ISSUE TITLE
Using image_to_osd function i'm facing below mentioned issue

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [tesseract-ocr/tesseract#3451]
TesseractError: (1, 'Tesseract Open Source OCR Engine v5.0.0-alpha.20210506 with Leptonica UZN file C:\\Users\\1636587\\AppData\\Local\\Temp\\tess_f7xkng2a loaded. Estimating resolution as 331 Too few characters. Skipping this page UZN file C:\\Users\\1636587\\AppData\\Local\\Temp\\tess_f7xkng2a loaded. Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')

_____________________________________________________________________________________________________________________________

---------------------------------------------------------------------------
TesseractError                            Traceback (most recent call last)
<ipython-input-17-34915e21266c> in <module>
----> 1 rot_data = pytesseract.image_to_osd(image)

c:\users\1636587\appdata\local\conda\conda\envs\tensorflow-study\lib\site-packages\pytesseract\pytesseract.py in image_to_osd(image, lang, config, nice, output_type, timeout)
    541         Output.DICT: lambda: osd_to_dict(run_and_get_output(*args)),
    542         Output.STRING: lambda: run_and_get_output(*args),
--> 543     }[output_type]()
    544 
    545 

c:\users\1636587\appdata\local\conda\conda\envs\tensorflow-study\lib\site-packages\pytesseract\pytesseract.py in <lambda>()
    540         Output.BYTES: lambda: run_and_get_output(*(args + [True])),
    541         Output.DICT: lambda: osd_to_dict(run_and_get_output(*args)),
--> 542         Output.STRING: lambda: run_and_get_output(*args),
    543     }[output_type]()
    544 

c:\users\1636587\appdata\local\conda\conda\envs\tensorflow-study\lib\site-packages\pytesseract\pytesseract.py in run_and_get_output(image, extension, lang, config, nice, timeout, return_bytes)
    285         }
    286 
--> 287         run_tesseract(**kwargs)
    288         filename = kwargs['output_filename_base'] + extsep + extension
    289         with open(filename, 'rb') as output_file:

c:\users\1636587\appdata\local\conda\conda\envs\tensorflow-study\lib\site-packages\pytesseract\pytesseract.py in run_tesseract(input_filename, output_filename_base, extension, lang, config, nice, timeout)
    261     with timeout_manager(proc, timeout) as error_string:
    262         if proc.returncode:
--> 263             raise TesseractError(proc.returncode, get_errors(error_string))
    264 
    265

**Comment by amitdo** [comment]
We only support what we provide: The tesseract command line tool, the C++ and the C API.

You are using a third-party tool we don't support.
