### ISSUE TITLE
Failing OCR with black border and lower resolution

### ISSUE THREAD

**Issue by dersmon** [tesseract-ocr/tesseract#3453]
Originally I stumbled on this trying to use [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF), but it seems this is a tesseract problem.

### Environment
tesseract 4.1.1
Linux 5.4.123-1-MANJARO x86_64 GNU/Linux

### Current Behaviour:
I am trying to OCR some scanned books. Using the [original TIFF](https://drive.google.com/file/d/121SrPJ8NOCExnJwnCMscjYv3gjuv-3l7/view?usp=sharing) for OCR [works](https://drive.google.com/file/d/1E_J21st3kSYyi9o8lj8BDQLp3QhGjbH8/view?usp=sharing) (no extra tesseract options used).

As mentioned above, I do not want to OCR the original TIFF, but a PDF based on the scan TIFFs. On a lower resolution, the OCR fails:
[Image](https://drive.google.com/file/d/1Jaj9kE8rNcJ4GT629ResM8S4EEGQm3zU/view?usp=sharing) > [OCR](https://drive.google.com/file/d/14_trLgdaNR68dFDRKeuIRFZbbZopWYLr/view?usp=sharing)

Removing the black border on the low res version with a white one, the OCR succeeds again:
[Image](https://drive.google.com/file/d/1tkIlHZP65m_6gXnOgNo1lUn_o68HM1No/view?usp=sharing) > [OCR](https://drive.google.com/file/d/13e3yHbBzBPOepbUZGwq1iPEF-8Hcoljk/view?usp=sharing)

### Expected Behaviour:
OCR on the [low res version with black border](https://drive.google.com/file/d/1Jaj9kE8rNcJ4GT629ResM8S4EEGQm3zU/view?usp=sharing) should succeed.

**Comment by zdenop** [comment]
Tesseract is OCR engine so you have to preprocess images by yourself. This [requirement](https://github.com/tesseract-ocr/tessdoc/blob/main/ImproveQuality.md) is know for a long time and there is no plan to change it.
