### ISSUE TITLE
How we can create share dll file for libtesseract project.

### ISSUE THREAD

**Issue by shq251** [tesseract-ocr/tesseract#3454]
Hi all,

I am able to create tesseract.sln file as by refer below link.
https://tesseract-ocr.github.io/tessdoc/Compiling.html

CMD commands is attached.
[tesserct.sln_Creation.txt](https://github.com/tesseract-ocr/tesseract/files/6637557/tesserct.sln_Creation.txt)

When open tesseract.sln file, we can see that libtesseract project is static library(.lib) type not dynamic library(.dll).

I want to create dll file for libtesseract project.

How we can create a dynamic library(.dll) for libtesseract project.

Kindly share the steps to prepare the .dll file for libtesseract project.

Thanks in advance.

Saddam

**Comment by zdenop** [comment]
Please read the doc. + There are several reliable tutorial on internet.

**Comment by shq251** [comment]
I am looking for reliable tutorial on internet.
If you have any link kindly share with me.

**Comment by shq251** [comment]
> Please read the doc. + There are several reliable tutorial on internet.

I am looking for reliable tutorial on internet.
If you have any link kindly share with me.

**Comment by zdenop** [comment]
https://bucket401.blogspot.com/2021/04/custom-ocr-application-in-c.html
https://sk-spell.sk.cx/building-tesseract-and-leptonica-with-cmake-and-clang-on-windows
https://sk-spell.sk.cx/building-minimalistic-tesseract
....

**Comment by Saddamshq** [comment]
Thank you.
