### ISSUE TITLE
No tesstrain.sh file after installation

### ISSUE THREAD

**Issue by davidb1** [tesseract-ocr/tesseract#3455]
### Environment 

* **Tesseract Version**:  5
* **Commit Number**: built from source
* **Platform**: Ubuntu 18

### Current Behavior: 
Running 
```
git clone https://github.com/tesseract-ocr/tesseract.git
./autogen.sh
./configure --disable-graphics
make
make training
sudo make training-install
```
creates no tesstrain.sh for me, was the file removed? I don't see a mention of this in the docs

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/commit/93348a83a324a4

**Comment by masonyoungblood** [comment]
I'm having the same issue - I see that @amitdo has linked to where the file was removed from the tesseract repository, and that there are new scripts in the tesstrain repository, but the main training documentation has not been updated.

**Comment by amitdo** [comment]
Yes, the documentation was not updated yet. That's why I didn't close this issue.

**Comment by zdenop** [comment]
Documentation was improved: https://github.com/tesseract-ocr/tessdoc#training-for-tesseract-5

**Comment by amitdo** [comment]
AFAIK, the Python based tesstrain does not handle the legacy engine. So maybe we should have a new repo with just the tesstrain.sh (+ the two other .sh files).

**Comment by amitdo** [comment]
From version 5.0.0 [Release Notes](https://github.com/tesseract-ocr/tessdoc/blob/main/ReleaseNotes.md#tesseract-release-notes-nov-30-2021---v500):

* **Training scripts**
  *  Remove the Bash based training scripts.
  * Move the Python based training scripts to the [tesstrain repo](https://github.com/tesseract-ocr/tesstrain/tree/main/src/training).
