### ISSUE TITLE
OCR don't detect my sentence

### ISSUE THREAD

**Issue by ungaro59** [tesseract-ocr/tesseract#3459]
Hello,

I take a screenshot, always the same thing, to detect the phrase "Votre demande de paris a bien été prise en compte".
But, sometimes, the sentence is not in .TXT. Why ??  Tesseract V5 alpha.

Originals Images here :
https://mega.nz/file/1whm2JLR#lVUc46As7Glv-vm--F5KcPbU-9ROJinSQE1ZL2zpRos

![PhotoMISE_20210618_120450_R3C2](https://user-images.githubusercontent.com/6413732/122546811-9febc080-d02f-11eb-8a99-e7aea7e51cc3.jpg)
![PhotoMISE_20210618_110051_R8C6-VALIDE](https://user-images.githubusercontent.com/6413732/122546814-a0845700-d02f-11eb-8b6a-f2cce9e84b59.jpg)
![PhotoMISE_20210618_103050_R8C5-VALIDE](https://user-images.githubusercontent.com/6413732/122546817-a11ced80-d02f-11eb-8690-8280f4a2c4f8.jpg)
![PhotoMISE_20210617_225828_R11C4](https://user-images.githubusercontent.com/6413732/122546818-a11ced80-d02f-11eb-8236-35517302fe4f.jpg)

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
Do not forget to **READ DOCUMENTATION** before posting topic.
