### ISSUE TITLE
5 recognized as S

### ISSUE THREAD

**Issue by superbonaci** [tesseract-ocr/tesseract#3460]
Using on Ubuntu 21.04
````
ii  libtesseract4:amd64                              4.1.1-2.1                                                            amd64        Tesseract OCR library
ii  tesseract-ocr                                    4.1.1-2.1                                                            amd64        Tesseract command line OCR tool
ii  tesseract-ocr-eng                                1:4.00~git30-7274cfa-1.1                                             all          tesseract-ocr language files for English
ii  tesseract-ocr-osd                                1:4.00~git30-7274cfa-1.1                                             all          tesseract-ocr language files for script and orientation
````

On this picture:
![](https://i.imgur.com/VbLiR8u.png)
````
tesseract pic.png out
````

Output is `DO3qWzAcSU9y` when should be `DO3qWzAc5U9y`

**Comment by zdenop** [comment]
Non OCR engine (also commercial) will guarantee you 100% recognition - especially in cases like this (non word - mixed letters and numbers).

Anyway with [oem 0](https://github.com/tesseract-ocr/tessdoc/blob/6061205c02a9e2b06171047393dc7e0929c75189/Command-Line-Usage.md#available-ocr-engines-in-tesseract-4) I got better result:

`tesseract pic.png - --oem 0`
Estimating resolution as 174
D03qWZAc5U9y
