### ISSUE TITLE
Windows and Linus Tesseract produce drastically different results.

### ISSUE THREAD

**Issue by CakeCrusher** [tesseract-ocr/tesseract#3461]
### Environment
Running Tesseract on both Windows and Linux
Windows:
(downloaded from https://github.com/UB-Mannheim/tesseract/wiki)
* **Tesseract Version**:  v5.0.0-alpha.20210506
* **Platform**: Windows 10

Linux:
* **Tesseract Version**:  tesseract 4.1.1
* **Platform**: Ubuntu 20.04.2 LTS

### Current Behavior:
I got the most recent versions of tesseract on both Windows and Linux and I was disappointed at the significant performance drop on Linux.

Linux
https://imgur.com/a/EHyFroL

Windows
https://imgur.com/a/VyyzocY

Current code for both:
`
      import youtube_dl
      import cv2
      import os
      import pytesseract as pyt
      import numpy as np
      import re
      from functools import reduce
      from nltk import edit_distance
      import json
      
              for dep on Linux
      pyt.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'
              for dev on Windows
      pyt.pytesseract.tesseract_cmd = 'C:\\Apps\\tesseract\\tesseract.exe'
      ...
      def gather_image_data(self, image, saveImageOnFile = None):
          image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
      
          image_data = pyt.image_to_data(image)
          image_data = image_data.splitlines()
      
          processed_data = []
          for text_data_str in image_data[1:]:
              text_data = text_data_str.split()
              text_data[6], text_data[7], text_data[8], text_data[9] = int(text_data[6]), int(text_data[7]), int(text_data[8]), int(text_data[9])
              if len(text_data) == 12 and len(text_data[11]) > 3:
                  processed_data.append(text_data)
           ...
      
          if saveImageOnFile:
              proof_image = image.copy()
              for box in processed_data:
                  x, y, w, h, text = int(box[6]), int(box[7]), int(box[8]), int(box[9]), box[11]
                  cv2.rectangle(proof_image, (x,y), (w+x,h+y), (255,0,0), 1)
                  cv2.putText(proof_image, text, (x,y),cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (255,0,0), 2)
              cv2.imwrite(self.media_path+'/ID'+saveImageOnFile+'.jpg', proof_image)
      
          return processed_data
`

### Expected Behavior:
I understand that the versions are different but the results are still too different. I would expect results to vary by maybe 10% not 50%

### Suggested Fix:
(I dont really know but here..)
Implementing the training datasets from UB-Mannheim for the linux build.

**Comment by zdenop** [comment]
I am sorry, but this is not tesseract problem:
Use the same tesseract version and the same traineddata, if you want to report "problem". Otherwise it does not make sense.
And replicate problem with tesseract directly as do not support 3rd party project.
