### ISSUE TITLE
Black list for strings(not for char)

### ISSUE THREAD

**Issue by mikewazovski** [tesseract-ocr/tesseract#3462]
Hello, 

 I am wondering if there is an option to not only use char as a blacklist but also specific words? For instance, if tesseract converts the image to string not according to our requirements, we would like to add that string to a blacklist file. This would prevent the tesseract to do the same error twice and most probably easen the task of the tesseract.

**Comment by amitdo** [comment]
There is no option to blacklist words/strings.
