### ISSUE TITLE
Line Finding Problem in OCR

### ISSUE THREAD

**Issue by kajelas** [tesseract-ocr/tesseract#347]
In my OCR situation, Tesseract can not identify rows properly. Please see the attach box image below. (Blue squares are boxes found by Tesseract and red areas are marked as problematic area by me)

![qq 20160615195248](https://cloud.githubusercontent.com/assets/3959938/16078734/118747c2-3333-11e6-890a-5eeaac13f217.png)

It seems that Tesseract is not able to find the baseline correctly when the row spacing is small and the image is a little skew --- two chars in two rows are mistakenly vertically merged. Therefore, the OCR quality in "crowded" space is really poor.

How could I imporve the OCR quality in this situation? Are there any params can be used here?

**Comment by amitdo** [comment]
Please use the [users mailing-list](https://groups.google.com/d/forum/tesseract-ocr).

[Here is our guide](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md) for reporting issues and asking questions.

**Comment by ahmed-gamal97** [comment]
@amitdo 
I need to know how tesseract preform line finding exactly. Where I can find this information?
I read the paper (An Overview of the Tesseract OCR Engine) and I didn't get it.
