### ISSUE TITLE
Character Level Similarity Score

### ISSUE THREAD

**Issue by sajalroychowdhury** [tesseract-ocr/tesseract#3471]
### Environment

* **Tesseract Version**: 4.1.1
* **Platform**: Windows 64 bit

I am looking for a character level similarity score in tesseract-ocr , if it returns one as such . Example  , for a character 'J' , tesseract has guessed it as 'J' with  ,say , 95% confidence  , second guess is 'I' with 3% confidence , so on and forth. 

Is there such score available in tesseract-ocr ?

**Comment by amitdo** [comment]
The right place to ask questions is our forum.
