### ISSUE TITLE
Issues with swapping GenericVector for std::vector

### ISSUE THREAD

**Issue by nocun** [tesseract-ocr/tesseract#3473]
### Environment

* **Tesseract Version**: [master](https://github.com/tesseract-ocr/tesseract/commit/c583ecef2997586d86feed81ec58a179707b6705)
* **Commit Number**: [92b6c652](https://github.com/tesseract-ocr/tesseract/commit/92b6c652f36ceaf6ac8d77bc4e627117780a3e4c)..[65d882f9](https://github.com/tesseract-ocr/tesseract/commit/65d882f96e1fd4bb3c4cef43d07aece54eb83d36)
* **Platform**: Linux FC29 x86_64

### Problem
Replacing `GenericVector` with `std::vector` has resulted in a small execution time performance decrease (about 4% on my simple test). I am not sure whether some other bugs have been introduced this way.

Most of the issues I could see are from changing `generic_vector.init_to_size(n, x);` directly into `vector.resize(n, x);`. It is because `init_to_size()` not only resizes the vector but also resets *all* of its values (not only the new ones).

### Suggested Fix

Recheck the logic and update `GenericVector`'s changed lines:

gv.init_to_size(n, x) and gv.resize(n, x) should become:
```c++
v.clear();
v.resize(n, x);
```

gv.truncate(n) (other than truncate(0) which is just v.clear()) should become:
```c++
if (n < v.size()) {
    v.resize(n);
}
```

gv.resize_no_init(n) (I think this one was ok):
```c++
v.resize(n);
```

I have added an example in comments of a [commit](https://github.com/tesseract-ocr/tesseract/commit/9710bc0465fc0df1a5bc0e71177151e8c5901204#diff-1e9b4b30348fc110f27ca4095a364df6161b8ded2f04a2625674f06b09a1ab64) where the first performance hit was noted .

As far as I could see the code affected is within commit range [92b6c652](https://github.com/tesseract-ocr/tesseract/commit/92b6c652f36ceaf6ac8d77bc4e627117780a3e4c)..[65d882f9](https://github.com/tesseract-ocr/tesseract/commit/65d882f96e1fd4bb3c4cef43d07aece54eb83d36). I might be able to provide a PR but this could take some time.

**Comment by stweil** [comment]
Thank you for this valuable hint. What do you mean with the "performance decrease" of 4 %? Increased character error rates? Larger execution time?

**Comment by nocun** [comment]
Larger execution time measured between [bb6dbd2c](https://github.com/tesseract-ocr/tesseract/commit/bb6dbd2cd8d66bd4a09ea72503ac79e87e915ef1) and [c583ecef](https://github.com/tesseract-ocr/tesseract/commit/c583ecef2997586d86feed81ec58a179707b6705).

**Comment by stweil** [comment]
I am afraid that the necessary fixes will increase the execution time even further.

**Comment by nocun** [comment]
The difference is not large but measureable. After applying changes mentioned in the comments [here](https://github.com/tesseract-ocr/tesseract/commit/9710bc0465fc0df1a5bc0e71177151e8c5901204#diff-1e9b4b30348fc110f27ca4095a364df6161b8ded2f04a2625674f06b09a1ab64) execution time went back to normal so I have some hope.

There is yet another performance issue like that introduced in later commits but I have not found it yet.

**Comment by stweil** [comment]
@nocun, can you try whether pull request #3474 changes the performance for you?

**Comment by nocun** [comment]
Sure, I'll be happy to test it but from my initial grepping it looks like there were changes in a lot of places.

I just realised I pasted a wrong commit range, the GenericVector changes started in Oct 2020 and finished in Mar 2021, commits: [92b6c652](https://github.com/tesseract-ocr/tesseract/commit/92b6c652f36ceaf6ac8d77bc4e627117780a3e4c)..[65d882f9](https://github.com/tesseract-ocr/tesseract/commit/65d882f96e1fd4bb3c4cef43d07aece54eb83d36), sorry about that.

This is quite a lot of code to go through.

**Comment by nocun** [comment]
If you have other issues to work on I may try and change all the wrong code I can find but it will take me a few days.

**Comment by stweil** [comment]
> GenericVector changes started in Oct 2020 and finished in Mar 2021, commits: 92b6c652..65d882f9

My fix now covers that whole range. I looked for all replacements of `init_to_size`.

**Comment by nocun** [comment]
That was quick!

I ran your merged code from master and it looks better (runs faster) but still not exactly the same as originally. You can try to find and replace problematic `GenericVector::resize(x, n)` (`resize` is just an alias for `init_to_size`) and `truncate(n)` code conversions (`resize` in particular may be difficult to grep for) or I can bisect the other issue tomorrow.

Thank you.

**Comment by nocun** [comment]
Looks like the other thing may be related to some compiler optimization. The time differences are pretty slim but show up consistently.

The commit that introduced additional delays: [2a3682a3](https://github.com/tesseract-ocr/tesseract/commit/2a3682a35e643cefb86eefa4c9a3deddc75295bd)

Created a PR that makes the problem go away on my machine: #3481

Is there a CI pipeline that can track and report tesseract performance?

If you see no other problems with GenericVector replacements then this issue can be closed.

**Comment by egorpugin** [comment]
> Is there a CI pipeline that can track and report tesseract performance?

We don't have CI perf tests at the moment.

**Comment by egorpugin** [comment]
> The time differences are pretty slim

Can you also provide some numbers?

From 2a3682a3 I see copies in loops in two places
1. https://github.com/tesseract-ocr/tesseract/commit/2a3682a35e643cefb86eefa4c9a3deddc75295bd#diff-1e9b4b30348fc110f27ca4095a364df6161b8ded2f04a2625674f06b09a1ab64R396
2. https://github.com/tesseract-ocr/tesseract/commit/2a3682a35e643cefb86eefa4c9a3deddc75295bd#diff-53cf79bc0219e0046b2c3620c5c8d9aa31c2e45def2ccf11ae343a5e0a02c43aR204

Not sure if this is intended.

**Comment by nocun** [comment]
> Can you also provide some numbers?

493620us vs. 479074us on GCC (min of ~300 runs).
Clang was just as fast with `at()` as with `operator[]`.

I checked all the other code that looked weird, including copies in those 2 fors, `vector<bool>` and even `reserve()` + `resize()` pair which in the new code do initialize memory.

I was surprised to see that none of the above made any measurable difference, only getting the data pointer did.
I don't have any hard proofs of what optimizations are happening behind the scenes but my hunch is that GCC can see that this pointer can never be NULL after `Init()` and enables some optimizations down the line.

But this is a bit of a guessing game.
If you would like to test it on other platforms and defer the merge then thats ok of course.

> We don't have CI perf tests at the moment.

Those would be very cool to have.

**Comment by stweil** [comment]
> If you see no other problems with GenericVector replacements then this issue can be closed.

So can it be closed now, or is there anything still open?

**Comment by nocun** [comment]
@stweil yes, thank you so much for the support!
