### ISSUE TITLE
Failing OCR for good quality ID card

### ISSUE THREAD

**Issue by MagicAP-QA** [tesseract-ocr/tesseract#3479]
We are trying to extract the text from the ID cards but the tesseract is not giving satisfactory results even on Good quality images

### Environment

* **Tesseract Version**: tesseract 4.00.00alpha
* **Platform**:  Windows 10 64-bit

### Current Behavior:
we are not bale to extract correct text from this image 
![original_image](https://user-images.githubusercontent.com/47530093/123935771-27331f80-d9b2-11eb-90f3-c87fe9e57d39.jpg)

whereas this image is working fine
![DL_AL1](https://user-images.githubusercontent.com/47530093/123936264-a3c5fe00-d9b2-11eb-921f-80c355776f33.jpg)

### Expected Behavior:
good result on this image
![original_image](https://user-images.githubusercontent.com/47530093/123935771-27331f80-d9b2-11eb-90f3-c87fe9e57d39.jpg)

**Comment by rameshjes** [comment]
In my case, we had to use `ocrb` fonts in order to parse European id cards. So, maybe you can try that or use tesseract based on font type present in your id card.

**Comment by ttbuffey** [comment]
@MagicAP-QA  Hi, have you resolved this issue, I am also working on OCR extraction for id cards.
