### ISSUE TITLE
"tesseract -v" does not display additional lib-information

### ISSUE THREAD

**Issue by FeaRiTail** [tesseract-ocr/tesseract#348]
Hi guys,

after downloading and manually compiling leptonica and tesseract, I see the following output
when trying to list the version-information of tesseract:

> [con-tom@lapp01awdtst tess_test]$ tesseract -v
> tesseract 3.04.00
>  leptonica-1.72
> 
> 
> [con-tom@lapp01awdtst tess_test]$

Could this be related the following errors which I see when trying to ocr' a given TIFF oder PDF file:

Test 1:
>  tesseract eurotext.pdf test.txt --tessdata-dir /opt/tesseract/tesseract-CuBeInst/tessdata/ -l deu

Generates:
> Tesseract Open Source OCR Engine v3.04.00 with Leptonica
> Error in fopenReadStream: file not found
> %¦¦¦¦ in pixRead: image file not found: %PDF-1.6
> %¦¦¦¦ cannot be read!
> Error during processing.

Test 2:
>  tesseract eurotext.tif test.txt --tessdata-dir /opt/tesseract/tesseract-CuBeInst/tessdata/ -l deu

Generates 2:
> Tesseract Open Source OCR Engine v3.04.00 with Leptonica
> Error in pixReadMemTiff: function not present`

Can I provide additional information? If yes, please let me know which information is needed.

Thx and best regards,

Tom

**Comment by amitdo** [comment]
Hi Tom!

You need to install more packages:
https://github.com/tesseract-ocr/tesseract/wiki/Compiling#dependencies

After that, re-install leptonica and then tesseract.

If you have further questions about this issue please use the [users mailing-list](https://groups.google.com/d/forum/tesseract-ocr).

[Here is our guide](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md) for reporting issues and asking questions..
