### ISSUE TITLE
Tesseract fails to recognize big text

### ISSUE THREAD

**Issue by Euler-Maskerony** [tesseract-ocr/tesseract#3480]
### Environment

* **Tesseract Version**:  4.1.1
* **Platform**: Linux arch 5.10.46-1-lts

### Current Behavior:
Tesseract can't recognize text on [this](https://i.postimg.cc/3JDnTYD7/1.jpg) image.

### Suggested Fix:
I reduced size of the image and it works, but shouldn't Tesseract recognize it without any extra transformations?

**Comment by nocun** [comment]
I think this may be the issue with the text being white-on-black. Can you check it by manually inverting colors and trying again?

**Comment by wollmers** [comment]
Tried it with with tesseract version 5 and it works perfect:

```
$ tesseract big.jpg big.jpg  --tessdata-dir /usr/local/share/tessdata txt hocr
Tesseract Open Source OCR Engine v5.0.0-alpha-773-gd33ed with Leptonica
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 1841
$ cat big.jpg.txt
Pot: 192,100

```

**Comment by nocun** [comment]
@wollmers Did you use tessdata `best` or `fast`? I tried Tesseract 5 with `fast` and it failed.

**Comment by Euler-Maskerony** [comment]
@nocun Yes, I tried and it works. But I have some pictures with the same text size and on some of them Tesseract fails.

**Comment by wollmers** [comment]
> @wollmers Did you use tessdata `best` or `fast`? I tried Tesseract 5 with `fast` and it failed.

None of `best` or `fast`.

Just downloaded today for a fresh compile/installation on another server

```
wget https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata

$ tesseract big.jpg big.w4.oem1.jpg  --oem 1 --tessdata-dir /usr/local/share/tessdata txt hocr
Tesseract Open Source OCR Engine v5.0.0-alpha-20210401 with Leptonica
Estimating resolution as 1841
$ cat  big.w4.oem1.jpg.txt
Pot: 192,100
```

**Comment by stweil** [comment]
Here is the image used for this issue (the link above might not be available in some weeks).

![1](https://user-images.githubusercontent.com/6734573/124281878-790ead80-db4a-11eb-8055-2aaaf3bf3ac6.jpg)

**Comment by wollmers** [comment]
> Here is the image used for this issue (the link above might not be available in some weeks).

Images that small (33 KB) should be in the issue thread.

If I test an issue, I try to record the case in an own github repository like this: https://github.com/wollmers/ocr-tess-issues/tree/main/issues/issue_3304_big_text.

**Comment by amitdo** [comment]
>Yes, I tried and it works.

So, no issue recognizing the image you provided. Different results with different models is normal.

>But I have some pictures with the same text size and on some of them Tesseract fails.

So provide 2-3 examples. Use the latest 5.0.0 codebase.

**Comment by amitdo** [comment]
No feedback from the OP.

**Comment by milahu** [comment]
still an issue with tesseract 5.5.1

tesseract arguments

```
tesseract 003.tiff - -c tessedit_create_hocr=1 --dpi 600 -l deu+eng \
  --oem 1 --psm 6 --tessdata-dir ../tessdata_best >003.hocr
```

example: the book title "HOPIUM" is not recognized

<details>
<summary>
input: 003.tiff
</summary>

003.tiff.q01.s50.webp
50% of original size = 300 dpi

![003.tiff.q01.s50.webp](https://github.com/user-attachments/assets/cb626369-18e4-497d-898a-523d6eac6988)

</details>

tessdata-dir is [tessdata_best](https://github.com/tesseract-ocr/tessdata_best)


<details>
<summary>
output: 003.hocr
</summary>

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title></title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
  <meta name='ocr-system' content='tesseract 5.5.1' />
  <meta name='ocr-capabilities' content='ocr_page ocr_carea ocr_par ocr_line ocrx_word ocrp_dir ocrp_lang ocrp_wconf'/>
 </head>
 <body>
  <div class='ocr_page' id='page_1' title='image "../070-deskew/003.tiff"; bbox 0 0 2782 4308; ppageno 0; scan_res 600 600'>
   <div class='ocr_carea' id='block_1_1' title="bbox 397 1035 2440 3793">
    <p class='ocr_par' id='par_1_1' lang='deu' title="bbox 397 1035 2440 3793">
     <span class='ocr_line' id='line_1_1' title="bbox 397 1035 2440 1111; baseline 0 -18; x_size 76; x_descenders 18; x_ascenders 16">
      <span class='ocrx_word' id='word_1_1' title='bbox 397 1039 584 1094; x_wconf 96'>Texte</span>
      <span class='ocrx_word' id='word_1_2' title='bbox 608 1052 687 1094; x_wconf 93'>zu</span>
      <span class='ocrx_word' id='word_1_3' title='bbox 711 1035 1171 1103; x_wconf 92'>Zeitenwende,</span>
      <span class='ocrx_word' id='word_1_4' title='bbox 1196 1035 1650 1094; x_wconf 92'>Technokratie</span>
      <span class='ocrx_word' id='word_1_5' title='bbox 1674 1036 1806 1093; x_wconf 93'>und</span>
      <span class='ocrx_word' id='word_1_6' title='bbox 1828 1036 2338 1111; x_wconf 92'>Korporatismus</span>
      <span class='ocrx_word' id='word_1_7' title='bbox 2362 1039 2440 1093; x_wconf 85'>III</span>
     </span>
     <span class='ocr_line' id='line_1_2' title="bbox 829 2649 2022 2724; baseline -0.002 -16; x_size 73; x_descenders 16; x_ascenders 16">
      <span class='ocrx_word' id='word_1_8' title='bbox 829 2665 1390 2724; x_wconf 90'>regenauer.press</span>
      <span class='ocrx_word' id='word_1_9' title='bbox 1428 2650 1433 2723; x_wconf 96'>|</span>
      <span class='ocrx_word' id='word_1_10' title='bbox 1469 2649 1846 2722; x_wconf 96'>Anthologie</span>
      <span class='ocrx_word' id='word_1_11' title='bbox 1871 2651 2022 2706; x_wconf 96'>2024</span>
     </span>
     <span class='ocr_line' id='line_1_3' title="bbox 1035 3719 1817 3793; baseline -0.004 -16; x_size 75; x_descenders 17; x_ascenders 16">
      <span class='ocrx_word' id='word_1_12' title='bbox 1035 3719 1425 3778; x_wconf 92'>Tom-Oliver</span>
      <span class='ocrx_word' id='word_1_13' title='bbox 1448 3722 1817 3793; x_wconf 92'>Regenauer</span>
     </span>
    </p>
   </div>
  </div>
 </body>
</html>
```

</details>
