### ISSUE TITLE
CMake clang build fail

### ISSUE THREAD

**Issue by nocun** [tesseract-ocr/tesseract#3482]
### Environment

* **Tesseract Version**: master (currently [38f0fdcd](https://github.com/tesseract-ocr/tesseract/commit/38f0fdcd888ebea26d44ea11c8a3365eb73e3232))
* **Platform**: Linux (possibly Windows) when compiling with Clang 7

### Problem

The `CHECK_CXX_COMPILER_FLAG()` macros seem to still cause problems.

E.g. in [CMakeLists.txt:180](https://github.com/tesseract-ocr/tesseract/blob/master/CMakeLists.txt#L180):
```
...
    CHECK_CXX_COMPILER_FLAG("-mfpu=neon" HAVE_NEON)
```

x86 GCC does not support this flag so `HAVE_NEON` remains unset.
On the same x86 machine but using Clang this line sets the flag to 1.

The reason is that `g++ -mfpu=neon` will error out but `clang++ -mfpu=neon` just gives a warning:
```
clang-7: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
```
And the process will end with status 0 (no error). Actually you can put anything there and CMake will always set this flag to 1 when using Clang:
```
clang-7: warning: argument unused during compilation: '-mfpu=kettle' [-Wunused-command-line-argument]
```

This causes current cmake-clang jobs failures. I am unsure how to fix it easily.

**Comment by stweil** [comment]
@nocun, do you want to try pull request #3484? I'd merge that if it fixes this issue.

**Comment by nocun** [comment]
@stweil yes, this works, thank you!
