### ISSUE TITLE
sw.cpp changes

### ISSUE THREAD

**Issue by ollydev** [tesseract-ocr/tesseract#3497]
This one is for @egorpugin 

1) Can a build setting get added not require libarchive?
https://github.com/tesseract-ocr/tesseract/blob/master/sw.cpp#L88

2) When building from source with sw is it possible to only build libtesseract target? 
Currently I move in my own `sw.cpp` with no libarchive and only libtesseract target. It would be nice to not require this. https://github.com/ollydev/libTesseract/blob/master/.github/workflows/build.yml#L61

Thanks.

**Comment by egorpugin** [comment]
Hi,

1. Try to comment these lines

```
libtesseract.Public += "HAVE_LIBARCHIVE"_d;
libtesseract.Public += "org.sw.demo.libarchive.libarchive"_dep;
```

If you need command-line solution, then you have to wait for the next sw release with full package "features" or "options" support. Currently it is possible to make a condition there, but the current naive implementation is overly complex thus buggy sometimes.

2.
> When building from source with sw is it possible to only build libtesseract target?

You mean without all dependencies or without some deps?

**Comment by ollydev** [comment]
> When building from source with sw is it possible to only build libtesseract target?

`./sw build org.sw.demo.google.tesseract.tesseract` to only build tesseract.exe
`./sw build org.sw.demo.google.tesseract.libtesseract` to only build libtesseract.dll

For example. How only build [libtesseract target](https://github.com/tesseract-ocr/tesseract/blob/master/sw.cpp#L8) in the [sw.yml workflow](https://github.com/tesseract-ocr/tesseract/blob/master/.github/workflows/sw.yml#L26).

**Comment by zdenop** [comment]
Is there anything that should be done or could we close the issue?

**Comment by egorpugin** [comment]
@ollydev 

Sorry, missed your comment.
`./sw build -target google.tesseract.libtesseract-master`
