### ISSUE TITLE
Cygwin compatibility

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#350]
Currently Tesseract needs some patches so it can be built for Cygwin.
See here: https://github.com/matzeri/cygwin-pkg/tree/master/tesseract

I want to fix Tesseract's Cygwin compatibility, so no patches will be needed anymore.

Pinging @matzeri...
Hi Marco!

I have a question for you - why is the ['tesseract-undefined.patch'](https://github.com/matzeri/cygwin-pkg/blob/master/tesseract/tesseract-undefined.patch) needed?

**Comment by amitdo** [comment]
Some links related to the ['tesseract-training.patch'](https://github.com/matzeri/cygwin-pkg/blob/master/tesseract/tesseract-training.patch):

PR https://github.com/tesseract-ocr/tesseract/pull/60

My own patch to 'pango_font_info.cpp'
https://github.com/amitdo/text2tif/commit/0473f14f

**Comment by matzeri** [comment]
https://www.gnu.org/software/libtool/manual/html_node/Link-mode.html

cygwin, mingw, aix are example of platform requiring it. It is not harmful on the other platforms

**Comment by amitdo** [comment]
See PR #351.
