### ISSUE TITLE
Can't compile libtesseract with GRAPHICS_DISABLED or DISABLED_LEGACY_ENGINE set - Part 2

### ISSUE THREAD

**Issue by rweldin** [tesseract-ocr/tesseract#3502]
When compiling the current master, https://github.com/tesseract-ocr/tesseract/commit/b2fea77a27f02fb82bed8e6d9522e12f2f1f4c35, in Visual Studio 2017 I receive the error below. This issue was raised a couple of months ago in issue: https://github.com/tesseract-ocr/tesseract/issues/3412, but I'm not able to reopen that issue. A fix was applied and I was able to successfully compile a DLL, but I have not compiled the master branch since May 4th. I suspect a new commit after May 4th caused this issue to reappear.

If any additional information is needed please let me know.

3>   Creating library E:/src/tesseract/win64/Release/tesseract50.lib and object E:/src/tesseract/win64/Release/tesseract50.exp
3>scanedg.obj : error LNK2019: unresolved external symbol "private: static class tesseract::SVNetwork * tesseract::ScrollView::stream_" (?stream_@ScrollView@tesseract@@0PEAVSVNetwork@2@EA) referenced in function "private: static class tesseract::SVNetwork * __cdecl tesseract::ScrollView::GetStream(void)" (?GetStream@ScrollView@tesseract@@CAPEAVSVNetwork@2@XZ)
3>E:\src\tesseract\win64\bin\Release\tesseract.dll : fatal error LNK1120: 1 unresolved externals

I'm compiling on Windows 10 with MSVS 2017 and using cmake to generate a solution file with the following options: cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=1 -DSW_BUILD_SHARED_LIBS=0 -DGRAPHICS_DISABLED=1 -DDISABLED_LEGACY_ENGINE=1 -DBUILD_TRAINING_TOOLS=0 ..

**Comment by zdenop** [comment]
First of all - make sure you uninstall the previous installation of the tesseract BEFORE configuring&building the tesseract.

"no sw" build works for me (with Visual Studio 16):

``` sh
"c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" x64
set INSTALL_DIR=F:\win64
cmake -Bbuild.msvc -DBUILD_SHARED_LIBS=1 -DGRAPHICS_DISABLED=1 -DDISABLED_LEGACY_ENGINE=1 -DBUILD_TRAINING_TOOLS=0 -DSW_BUILD=OFF -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DCMAKE_PREFIX_PATH=%INSTALL_DIR% -DSW_BUILD=OFF
cmake --build build.msvc --config Release --target install
```

**Comment by rweldin** [comment]
Thank you for your response. I was able to resolve this issue and am closing it.
