### ISSUE TITLE
Crash in old CPU

### ISSUE THREAD

**Issue by hereis00** [tesseract-ocr/tesseract#3515]
### Environment

* **Tesseract Version**: 4.1.1 and 5-alpha
* **Platform**: Windows 10 x64

### Current Behavior:
Carshed in CPU G4560 and other old CPU. After googling, I confirm that the issue is about some CPU feature support. Is it possible if I complie a tesseract library that can work on those old CPU, if the answer is yes, what complie option should I use while compile?

**Comment by amitdo** [comment]
What's the full command you used?
Do you get any error message?
Is the crash followed by a system reboot?

What's the output of` tesseract -v`?

**Comment by hereis00** [comment]
I integrate tesseract to c++ project(with OpenCV), use code`tesseract::TessBaseAPI:SetPageMode(tesseract::PSM_SINGLE_LINE)`,`SetVariable("save_beset_choices", "T")`,`SetImage(...)`,`SetSourceResolution(96)`,`Recognize(0)`,`GetUTF8Text()`.Work well if CPU is i5 6500 which the output of `tesseract -v` is
```
tesseract 4.1.1
 leptonica-1.80.0 (Aug  4 2021, 09:39:39) [MSC v.1916 LIB Release x64]
  libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.0.6) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.1.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
```
crash if CPU is G4560 which the output of `tesseract -v` is
```
tesseract 4.1.1
 leptonica-1.80.0 (Aug  4 2021, 09:39:39) [MSC v.1916 LIB Release x64]
  libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.0.6) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.1.0
 Found SSE
```

**Comment by hereis00** [comment]
How can I compile a library without enabling AVX2, AVX, FMA by using sw or CMake or vcpkg?

**Comment by zdenop** [comment]
Try current code from master - IMO it should fix such problems.

**Comment by hereis00** [comment]
> Try current code from master - IMO it should fix such problems.

OK, I'll try master and report following effort.
Thanks for reply. @zdenop @amitdo

**Comment by hereis00** [comment]
It works!
There are so many dlls(42), do I need add all of the dlls that under compilation directory to my exe directory?
The tool Dependency only finds serval dlls related to tesseract50.dll, and I add these dlls to my exe directory, it works well so far.
The dlls I added to my exe directory:
```
org.sw.demo.danbloomberg.leptonica-1.81.1.dll
org.sw.demo.facebook.zstd.zstd-1.5.0.dll
org.sw.demo.gif-5.2.1.dll
org.sw.demo.glennrp.png-1.6.37.dll
org.sw.demo.jpeg-9.4.0.dll
org.sw.demo.madler.zlib-1.2.11.dll
org.sw.demo.tiff-4.3.0.dll
org.sw.demo.uclouvain.openjpeg.openjp2-2.4.0.dll
org.sw.demo.webmproject.webp-1.1.0.dll
org.sw.demo.xz_utils.lzma-5.2.4.dll
tesseract50.dll
```
The dlls under the output directory of compilation:
```
org.sw.demo.behdad.harfbuzz-2.8.2.dll
org.sw.demo.bzip2-1.0.8.dll
org.sw.demo.cairographics.cairo-1.17.4.dll
org.sw.demo.danbloomberg.leptonica-1.81.1.dll
org.sw.demo.expat-2.4.1.dll
org.sw.demo.facebook.zstd.zstd-1.5.0.dll
org.sw.demo.freedesktop.fontconfig.fontconfig-2.13.93.dll
org.sw.demo.freetype-2.11.0.dll
org.sw.demo.gif-5.2.1.dll
org.sw.demo.glennrp.png-1.6.37.dll
org.sw.demo.gnome.glib.gio-2.69.0.dll
org.sw.demo.gnome.glib.glib-2.69.0.dll
org.sw.demo.gnome.glib.gmodule-2.69.0.dll
org.sw.demo.gnome.glib.gobject-2.69.0.dll
org.sw.demo.gnome.pango.pango-1.48.2.dll
org.sw.demo.gnome.pango.pangocairo-1.48.2.dll
org.sw.demo.gnome.pango.pangoft2-1.48.2.dll
org.sw.demo.gnu.fribidi.fribidi-1.0.10.dll
org.sw.demo.gnu.gettext.intl-0.21.0.dll
org.sw.demo.gnu.iconv.libcharset-1.16.0.dll
org.sw.demo.gnu.iconv.libiconv-1.16.0.dll
org.sw.demo.jpeg-9.4.0.dll
org.sw.demo.libarchive.libarchive-3.5.1.dll
org.sw.demo.libffi-3.4.2.dll
org.sw.demo.lz4-1.9.3.dll
org.sw.demo.madler.zlib-1.2.11.dll
org.sw.demo.oberhumer.lzo.lzo-2.10.0.dll
org.sw.demo.pcre.pcre8-8.44.0.dll
org.sw.demo.python.lib-3.9.1.dll
org.sw.demo.tiff-4.3.0.dll
org.sw.demo.uclouvain.openjpeg.openjp2-2.4.0.dll
org.sw.demo.unicode.icu.common-69.1.0.dll
org.sw.demo.unicode.icu.data-69.1.0.dll
org.sw.demo.unicode.icu.i18n-69.1.0.dll
org.sw.demo.unicode.icu.stub.common-69.1.0.dll
org.sw.demo.unicode.icu.stub.data-69.1.0.dll
org.sw.demo.unicode.icu.stub.i18n-69.1.0.dll
org.sw.demo.unicode.icu.stub.toolutil-69.1.0.dll
org.sw.demo.webmproject.webp-1.1.0.dll
org.sw.demo.xmlsoft.libxml2-2.9.12.dll
org.sw.demo.xz_utils.lzma-5.2.4.dll
tesseract50.dll
```

**Comment by hereis00** [comment]
Since Dependency just analysed several dlls, I'm a liitle confused that do I have to add all the 42 dlls to my exe directory?
