### ISSUE TITLE
empty result

### ISSUE THREAD

**Issue by GlauberF** [tesseract-ocr/tesseract#3519]
I'm trying to get the text of an image, but I'm not getting it, returns empty value.

follow the image below
![t](https://user-images.githubusercontent.com/11314585/128751894-a2509e89-8697-4afa-b88a-5f377bca849b.png)

## Env
OS linux
tesseract.js@2.1.5

**Comment by zdenop** [comment]
Empty result is correct result for such input image. 
PS: We do not support captcha breaking.
