### ISSUE TITLE
Guidance to improve speed

### ISSUE THREAD

**Issue by vijuc895** [tesseract-ocr/tesseract#3524]
Hi Team,

I am working on printed document of English language. I need to extract all text from that image, but with simple tesseract it is taking 4 sec. Is it possible to fine tune for only English alphabet and numbers? Please help.

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions. GitHub issues are not a help forum.
