### ISSUE TITLE
Tesseract fails with custom binarization

### ISSUE THREAD

**Issue by jkryszyn** [tesseract-ocr/tesseract#3528]
### Environment

* **Tesseract Version**: 5.0.0-alpha
* **Commit Number**: 
* **Platform**: Ubuntu 20.04

### Current Behavior:

When binarization of an image is performed, ocr results are much worse than without binarization. Also ocr takes more time. Seems like Tesseract is always doing internal binarization . I even tried creating 1bpp image (MSB of the first byte = first pixel, 1 is white) with no luck.

### Expected Behavior:

If image is binarized, results should be at least as good as without. Ocr should be faster

**Comment by jkryszyn** [comment]
I'll try to elaborate and provide an example. This is an image I am trying to process. It is a scan of an invoice (polish language).

![1](https://user-images.githubusercontent.com/2608018/130059027-b68daf14-5471-4646-943a-b188eb4e0442.png)

My binarized version of this image looks like this:

![1_binary](https://user-images.githubusercontent.com/2608018/130059522-1704dce2-d804-4e73-b7c7-59568c345532.png)

It is perfectly readable to human. There is some minor degradation of letters.

From my point of view, results should be almost the same. I've performed many tests with different page segmentation modes and languages. For example if I set PSM to 3 (PSM_AUTO) and language to pol, I get this result for original image:

```
Faktura PROFORMA nr 1523596/19/2021/F
za energię elektryczną i świadczenie usług dystrybucji
Typ dokumentu sprzedaży: PROGNOZA PROFORMA

Wystawca

PGNiG Obrót Detaliczny sp. z 0.0.
ul. Gazowa 3, 50-513 Wrocław

tel. 22 515 15 15
kontaktQpgnig.pl

Str.1/1

Oryginał z dnia: 09.03.2021

Za okres: 01.03.2021 do 30.04.2021

Data sprzedaży: 30.04.2021
Sprzedawca

PGNiG Obrót Detaliczny sp. z o.o.
ul. Jana Kazimierza 3, 01-248 Warszawa
NIP: 5272706082
```

Which is almost perfect, but the result obtained using binarized image is this:

```
SIedli

Fakluta PROFORMA ne1523596019/4021/E „Nygińsłzuniat 09.03.202$
zacnęetalę eieklyczną I świddeżenić uslug Hyslybucji IZĄDKIEST". +... 01.03:2021ia39,04.2021
Tym dokumentu sprzedaży; PROGNOZA PROFORMA DAt zprzedożyz 30,04.202%
Wyśtiwcz Sprźediwcz
PGNIG Nktó! Detaliczny śp,X0o, PGNIG Dba! Detaliczny śp.źb,
ul. Gizówa g, 5-514 Wroclaw uL Jana Kazimierzą 3, DI-ZĄB Wotczówa
225151515 NIP;5272706082

A
kontskiGpąnig.pl
```

It's slightly better when I set language to english, but still far from perfect:

```
Stet
Faktura PROFORMA ne 1523596/19/2021/F Oo

inal 2 dnia: 09.03.2021
za energie elektryczng I $wiadezenie ustug dystrybucji iZaokres:. |. 01.03.2021 do 30,04.2021
Typ dokumentu sprzedazy: PROGNOZA PROFORMA Data sprzedaty: 30.04,202%
Wystawea Sprzedawca
PGNIG Obrot Detaliczny sp. z 0.0. PGNIG Obrét Detaliczny sp. z 0.0.

ul. Gazowa 3, 50-513 Wroclaw ul. Jana Kazimierza 3, 01-248 Warszawa

tel. 22 515 15 15 NIP: 5272706082
kontakt@pgnig.pl
```

I use OpenCV and my code is in C++. I initialize tesseract with `OEM_LSTM_ONLY`. I set image like this:

```
tess.SetImage(mat.data, mat.cols, mat.rows, mat.channels(), mat.step);
```

In case of binarized image, `mat.channels()` returns 1. I even tried to create 1bpp char array from my binarized image and set bytes_per_pixel to 0, but the result was exactly the same. It seems that no matter what, Tesseract still performs its own binarization which makes the image unprocessable.

**Comment by zdenop** [comment]
Seems like problem with d
hit: create PIX instead of setting data and set PIX.depth=1 =>

**Comment by zdenop** [comment]
BTW: which version of leptonica you use?

**Comment by jkryszyn** [comment]
> BTW: which version of leptonica you use?

This is `tesseract --version` output:

```
tesseract 5.0.0-alpha
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found SSE
```

Is there any good example how to prepare 1bpp PIX?

**Comment by amitdo** [comment]
>In case of binarized image, mat.channels() returns 1

Assuming you have 1 bpp (and not a grayscale with 0,  255 as the only pixels values) you should pass `0` instead of `1`.

**Comment by jkryszyn** [comment]
I found a bug in my code which was resulting in bad results. The problem was that I was doing binarization on an already binarized image myself. I've tested it with Mat, Pix, my own char array having 1bpp and ocr results are now ok. Thank you for all your responses and sorry.
