### ISSUE TITLE
CMAKE fails on 4.0.0 and 4.1.1 Android ARM

### ISSUE THREAD

**Issue by dpanic** [tesseract-ocr/tesseract#3543]
### Environment
* **Tesseract Version**:  4.0.0
* **Platform**: Linux master 5.4.0-81-generic 91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
```
[ 99%] Linking CXX shared library libtesseract.so
ld: error: unable to find library -lpthread
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/libtesseract.dir/build.make:3624: libtesseract.so.4.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/libtesseract.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
[  1%] Linking CXX shared library libtesseract.so
ld: error: unable to find library -lpthread
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/libtesseract.dir/build.make:3624: libtesseract.so.4.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/libtesseract.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

CMAKE:
```

    export API=28

    # Configure and build.
    export AR=$TOOLCHAIN/bin/llvm-ar
    export CC=$TOOLCHAIN/bin/$TARGET$API-clang
    export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
    export AS=$CC
    export LD=$TOOLCHAIN/bin/ld
    export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
    export STRIP=$TOOLCHAIN/bin/llvm-strip

    export LEPTONICA_LIBS="-L$ROOT/output/$OUTARCH/lib -llept"
    export LEPTONICA_CFLAGS="-I$ROOT/output/$OUTARCH/include/leptonica"
    export PKG_CONFIG_PATH="$ROOT/output/$OUTARCH/lib/pkgconfig"

    mkdir build
    cd build

    cmake \
        -D BUILD_TESTS=OFF \
        -D BUILD_TRAINING_TOOLS=OFF \
        -D CMAKE_ANDROID_ARCH_ABI=armeabi-v7a \
        -D CMAKE_ANDROID_STANDALONE_TOOLCHAIN=$TOOLCHAIN \
        -D CMAKE_BUILD_TYPE=Release \
        -D CMAKE_INSTALL_PREFIX:PATH=$ROOT/output/$OUTARCH/lib \
        -D CMAKE_SYSTEM_NAME=Android \
        -D CMAKE_SYSTEM_VERSION=28 \
        -D CMAKE_C_COMPILER=$CC \
        -D CMAKE_CXX_COMPILER=$CXX \
        -D CPPAN_BUILD=OFF \
        -D CMAKE_CXX_FLAGS="-Qunused-arguments -Wl,-rpath-link,$ROOT/output/$OUTARCH/lib" \
        ..

    make -j
    make install
```
### Expected Behavior:
Expected is to have **libtesseract.so** linked.

**Comment by zdenop** [comment]
Please use the latest code (master)

**Comment by dpanic** [comment]
@zdenop this works with following options:
```
    ./autogen.sh
    ./configure \
        --host=$TARGET \
        --disable-doc \
        --disable-openmp \
        --without-archive \
        --without-curl \
        --prefix $ROOT/output/$OUTARCH/
```

which is all fine. But this is 5.x tesseract.

Now I can't use Gosseract :-) which has bindings for 4.1.1 latest stable

**Comment by zdenop** [comment]
There were changes in v5/master regarding `pthread`. You can try also git version of 4.1 branch https://github.com/tesseract-ocr/tesseract/tree/4.1.  I see there code, that should help: https://github.com/tesseract-ocr/tesseract/blob/b2eb72b6e44e48f5b47904c977180bd5b24362eb/CMakeLists.txt#L179-L182
We are in release process of v5, so ask tesseract wrappers should be updated soon.

**Comment by dpanic** [comment]
Thank you.
Build works for both 5.X and 4.1.
However only 4.1 is starting on Android X86_64 without problems.

**Comment by dpanic** [comment]
NDK 20 or NDK 21 

I am able to build without problems ARM, X86 and X86_64
Only ARM64 is failing.

With following error:
/storage/development/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/../l
ib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libpng16.so, needed by /home/dpanic/projects/archive/khaoticen/projekat.com/engine/gosseract/dependencie
s/output/arm64-v8a/lib/liblept.so, not found (try using -rpath or -rpath-link)                  /storage/development/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/../l
ib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libjpeg.so, needed by /home/dpanic/projects/archive/khaoticen/projekat.com/engine/gosseract/dependencies
/output/arm64-v8a/lib/liblept.so, not found (try using -rpath or -rpath-link)                   /storage/development/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/../l
ib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libtiff.so, needed by /home/dpanic/projects/archive/khaoticen/projekat.com/engine/gosseract/dependencies
/output/arm64-v8a/lib/liblept.so, not found (try using -rpath or -rpath-link)                   /home/dpanic/projects/archive/khaoticen/projekat.com/engine/gosseract/dependencies/output/arm6
4-v8a/lib/liblept.so: undefined reference to `TIFFWriteScanline'                                /home/dpanic/projects/archive/khaoticen/projekat.com/engine/gosseract/dependencies/output/arm6
4-v8a/lib/liblept.so: undefined reference to `png_set_gAMA@PNG16_0'                             /home/dpanic/projects/archive/khaoticen/projekat.com/engine/gosseract/dependencies/output/arm6
4-v8a/lib/liblept.so: undefined reference to `jpeg_set_marker_processor@LIBJPEG_6.2'

**Comment by stweil** [comment]
So you should provide the missing shared libraries libpng16.so, libjpeg.so, libtiff.so.

**Comment by dpanic** [comment]
They're not missing, they are inside the lib folder.

I have succeeded to build with NDK22.
This should be updated in docs, this is very PITA, to manually test which
NDK works.

**Comment by zdenop** [comment]
This is a community project - we share what we create for our need and projects.
We are ready to accept commits also for platforms we do not use, but it is unrealistic to expect we will test something we do not use (regularly).

**Comment by dpanic** [comment]
That makes sense. Didn't wanted to sound rude or insult anybody, I was just
frustrated with amount of attempts I had until I got it to work :-)

Thank you for this great project!

**Comment by stweil** [comment]
@dpanic, maybe you can send a pull request which updates the documentation: https://github.com/tesseract-ocr/tessdoc/blob/master/Compiling.md.

**Comment by dpanic** [comment]
> @dpanic, maybe you can send a pull request which updates the documentation: https://github.com/tesseract-ocr/tessdoc/blob/master/Compiling.md.

Makes sense, I will do it this week. Cheers

**Comment by dpanic** [comment]
Done https://github.com/tesseract-ocr/tessdoc/pull/54
