### ISSUE TITLE
Obtaining all pages on tessinput.tif when using "get.images" configuration.

### ISSUE THREAD

**Issue by diogoalmiro** [tesseract-ocr/tesseract#3544]
### Environment
Tested on windows 10 - 64 with:
```
tesseract v5.0.0-alpha.20210506
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0
```
and on a docker alpine container:
```
tesseract 4.1.1
 leptonica-1.81.1
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.0) : libpng 1.6.37 : libtiff 4.2.0 : zlib 1.2.11 : libwebp 1.2.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
```

### Current Behavior:
When running `tesseract multiple-page.tif - get.images` tesseract overwrites `tessinput.tif` until it stops. Efectively only allowing to see the last page processed.

### Expected Behavior:
Either create a multiple page `tessinput.tif` or creating `tessinput-n.tif` for each page.

**Comment by amitdo** [comment]
You face a similar issue if you ocr more than one single page. In this case the solution should be to change `tessinput.tif` to `original-input-name-bw.tif`.

**Comment by diogoalmiro** [comment]
@amitdo I think it is acceptable to keep the name `tessinput.tif`. Once tesseract ends, I move the file to a more appropriate one.
The main problem is when running on a multiple page we can't know when to move the file, neither will tesseract "wait" for us to move the file.

**Comment by diogoalmiro** [comment]
Maybe a better solution would be to write to OUTPUTBASE.tessinput.tif simmilarly to any other config file and on this note also change the logfile to OUTPUTBASE.tesseract.log for consistency.

> CONFIGFILE
> 
> The name of a config to use. The name can be a file in tessdata/configs or tessdata/tessconfigs, or an absolute or relative file path. A config is a plain text file which contains a list of parameters and their values, one per line, with a space separating parameter from value.
> 
> Interesting config files include:
>
> • alto — Output in ALTO format (OUTPUTBASE.xml).
> • hocr — Output in hOCR format (OUTPUTBASE.hocr).
> • pdf — Output PDF (OUTPUTBASE.pdf).
> • tsv — Output TSV (OUTPUTBASE.tsv).
> • txt — Output plain text (OUTPUTBASE.txt).
> • **get.images** — Write processed input images to file (**tessinput.tif**).
> • **logfile** — Redirect debug messages to file (**tesseract.log**).
> • lstm.train — Output files used by LSTM training (OUTPUTBASE.lstmf).
> • makebox — Write box file (OUTPUTBASE.box).
> • quiet — Redirect debug messages to /dev/null.

**Comment by wollmers** [comment]
> You'll face a similar issue if you'll ocr more than one single page. In this case the solution should be to change `tessinput.tif` to `original-input-name-bw.tif`.

I vote for using `OUTPUTBASE` as much as possible, i.e. all created files related to an input image. That's exactly what users (including me) do in scripts: rename `tessinput.tif` to `basename.tessinput.tif` resp. with multipage-input `basename_$pagenumber.tessinput.tif`. `basename.bw.tif` is shorter.

**Comment by zdenop** [comment]
```diff
diff --git a/src/api/baseapi.cpp b/src/api/baseapi.cpp
index f602b04b..59df16a8 100644
--- a/src/api/baseapi.cpp
+++ b/src/api/baseapi.cpp
@@ -1276,7 +1276,11 @@ bool TessBaseAPI::ProcessPage(Pix *pix, int page_index, const char *filename,

   if (tesseract_->tessedit_write_images) {
     Pix *page_pix = GetThresholdedImage();
-    pixWrite("tessinput.tif", page_pix, IFF_TIFF_G4);
+    char outputname[MAX_PATH];
+    std::string str_filename = filename;
+    std::string stem = str_filename.substr(0, str_filename.find_last_of('.'));
+    sprintf(outputname, "%s.%04d.tif", stem.c_str(), page_index);
+    pixWrite(outputname, page_pix, IFF_TIFF_G4);
   }

   if (failed && retry_config != nullptr && retry_config[0] != '\0') {
```

This is a simple modification that will generate tif output with original_filename_without_ext .page_number.tif e.g. for multipage tif it will create individual tif per page.
Creating multipage tif would be more difficult and in some cases not desired (if input file would be list of different filenames)

**Comment by diogoalmiro** [comment]
> if input file would be list of different filenames

Can that happen?

> Basic command line usage:
> ```
> tesseract imagename outputbase [-l lang] [--oem ocrenginemode] [--psm pagesegmode] [configfiles...]
> ```

**Comment by zdenop** [comment]
Of course:
https://github.com/tesseract-ocr/tesseract/blob/4df822a3fc481f026250fcf2bb4c0e7583df1dd5/include/tesseract/baseapi.h#L805

and working with filelist is easier than multipage tif ;-)

try it by yourselt:
``` sh
ls *.png | tr " " "\n" >filelist
tesseract filelist result 
```

**Comment by amitdo** [comment]
@diogoalmiro

See [tesseract's manpage](https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc).

**Comment by stweil** [comment]
See pull request #3545 for a possible solution.

**Comment by stweil** [comment]
> I vote for using `OUTPUTBASE` as much as possible

For `tesseract.log` that's not so easy, because that is currently a parameter (`debug_file`) which can be set by users.

`tessinput.tif` was now replaced in latest Git by `OUTPUTBASE.processed.tif` (first page) and `OUTPUTBASE.processedN.tif` for any following page N.

**Comment by stweil** [comment]
Is the new naming fine and can we close this issue, or would someone suggest changes?

**Comment by amitdo** [comment]
>Is the new naming fine

See my comment in the PR.

**Comment by amitdo** [comment]
In other places, `DebugPixa` is used to output an image for debugging.

**Comment by stweil** [comment]
That writes a number of debug images to a single PDF file. Do you think that would be a good solution here? It won't be possible to run OCR then on the image because we don't support PDF.

**Comment by amitdo** [comment]
>Do you think that would be a good solution here?

I just wanted you to know that there are currently two different ways to output the result of image processing which is done by Tesseract.

Maybe we should also save the images in the pdf file in individual files?

**Comment by wollmers** [comment]
> Is the new naming fine and can we close this issue, or would someone suggest changes?

For me everything is fine as long as it follows the natural hierarchy `document` -> `image` -> `page`, is unique and pure ASCII, and easy to parse.

There can be potential problems with page or image numbers starting at 0 or 1, if `pdftoppm`, `convert` etc. are used to extract images. But that's up to the user.
