### ISSUE TITLE
mftraining -F font_properties -U unicharset error 

### ISSUE THREAD

**Issue by Buyi993-bit** [tesseract-ocr/tesseract#3547]
![屏幕快照 2021-09-03 上午1 00 48](https://user-images.githubusercontent.com/89996898/131886437-f874626f-6539-46b7-93ae-965ba706d308.png)

![屏幕快照 2021-09-03 上午1 02 30](https://user-images.githubusercontent.com/89996898/131886555-dbc8ddd5-a9d3-4f7e-a9ff-1b1e11ff6580.png)

Only the file shapetable can be obtained, while I can not create normproto, intemp, and pffmtable files at all. Please help!

**Comment by stweil** [comment]
The first snapshot shows a segmentation fault from `mftraining`. And as it looks like a recent software version, this should be examined.

@Buyi993-bit, could you please upload the files which are required to reproduce the issue? And please don't use screenshots for console messages. Copy+paste the text from the console to include it in the issue report.

**Comment by zdenop** [comment]
@stweil: your are right @Buyi993-bit seems to be recent software version, so unless Buyi993-bit tries to train for tesseract 3, [this part of docs should be relevant](https://github.com/tesseract-ocr/tessdoc/blob/master/tess4/TrainingTesseract-4.00.md):

> The clustering steps (mftraining, cntraining, shapeclustering) are replaced with a single slow lstmtraining step.

I am afraid he is following some outdated tutorial....
