### ISSUE TITLE
tesstrain.sh can only produce one image(by this,i mean one tif file) for larg training_text

### ISSUE THREAD

**Issue by norriswangxj** [tesseract-ocr/tesseract#3550]
problem 1:
here is the command line:
src/training/tesstrain.sh --fonts_dir /usr/share/fonts --lang eng \
        --noextract_font_properties --langdata_dir ../langdata --fontlist "Arial Bold" --linedata_only\
  --tessdata_dir ./tessdata --save_box_tiff  --output_dir ./train_dir_eng 

when use tesstrain.sh to produce training data,it only make one tif file for a training text which is obviously can not be rendered to only one single tif file.By my observing,one tif file resulted from text2image is to include a bout 60 lines  of text. But it will only procude a tif file including the first 60 lines,regardless the bigness of the training text.
and the log from tesstrain.sh is keep saying:
/usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.8pVIHXwhDu --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/eng-2021-09-06.ylk/eng.Arial_Bold.exp0 --max_pages=0 --font=Arial Bold --ptsize 12 --text=../langdata/eng/eng.training_text
Rendered page 0 to file /tmp/eng-2021-09-06.ylk/eng.Arial_Bold.exp0.tif
Rendered page 1 to file /tmp/eng-2021-09-06.ylk/eng.Arial_Bold.exp0.tif
Rendered page 3 to file /tmp/eng-2021-09-06.ylk/eng.Arial_Bold.exp0.tif
......
Rendered page 13 to file /tmp/eng-2021-09-06.ylk/eng.Arial_Bold.exp0.tif

and when tesstrain.sh finished,there is only one tif file inside the --output_dir.
and the resulted .box file contains desc for all chars inside the trainning text.
this makes a mismatching between the .box file and the tif file.

problem 2:
the command line include '--linedata_only',but the resulted .box file is based on each single char,not describing a line.
then,how does the resulted lstmf file combine the box file and the tif file correctly?

**Comment by amitdo** [comment]
The tesstrain.sh script was remove from this repo. The equivalent tesstrain.py script was moved to [another repo](https://github.com/tesseract-ocr/tesstrain/tree/master/src/training).

**Comment by norriswangxj** [comment]
tks。tesstrain.sh was included within 4.1.1,and is standing in several documentation.
I will try tesstrain.py and then report whether the problem is resolved by tesstrain.py

**Comment by Shreeshrii** [comment]
>when use tesstrain.sh to produce training data,it only make one tif file for a training text which is obviously can not be rendered to only one single tif file.By my observing,one tif file resulted from text2image is to include a bout 60 lines of text. But it will only procude a tif file including the first 60 lines,regardless the bigness of the training text.

The tif file is generated by the program text2image and should be a multipage tif.

>Rendered page 13 to file /tmp/eng-2021-09-06.ylk/eng.Arial_Bold.exp0.tif

So your tif file should have 13 pages.

**Comment by norriswangxj** [comment]
@Shreeshrii,

TKS for teaching。
When use tesstrain.sh,we specify "--tessdata_dir ./tessdata",and ./tessdata contains a dir named "configs" which is needed by making lstmf . What is other meaning by --tessdata_dir ?Are those .traineddata files   needed when we are tring to make starter training data?
