### ISSUE TITLE
configure: error: --with-tensorflow was given, but test for libtensorflow-dev failed

### ISSUE THREAD

**Issue by tranzmatt** [tesseract-ocr/tesseract#3552]
------------------------

### Environment

* **Tesseract Version**: 

5.0.0-beta-20210815

* **Commit Number**: 

60fd2b4abaa9c5c5c42d32db57576bc95d28a78a

* **Platform**:

Linux tachikoma 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linu

### Current Behavior:

configure fails with the above error

### Expected Behavior:

It finds my tensorflow

### Suggested Fix:

Ubuntu has no "libtensorflow" and I don't know any PPA that provides it.  I installed it with pip, which can put in my ~/.local folder.  If I could set something like "TENSORFLOW_ROOT" would be great.

**Comment by amitdo** [comment]
There is no reason to use `--with-tensorflow`. It will not give you anything.

This option is currently only for unit testing which is uses by Tesseract developers.
