### ISSUE TITLE
why can't it read the single character on the picture?

### ISSUE THREAD

**Issue by umutozgur** [tesseract-ocr/tesseract#3553]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by stweil** [comment]
> Please report an issue only for a BUG, not for asking questions.

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by umutozgur** [comment]
this is a bug. because it cannot find the places where it says 1 in the
picture.
Teşekkürler,


Umut Özgür ÇETİN


Stefan Weil ***@***.***>, 10 Eyl 2021 Cum, 11:32 tarihinde
şunu yazdı:
