### ISSUE TITLE
Using tesseract and mnist dataset together

### ISSUE THREAD

**Issue by nebiyebln** [tesseract-ocr/tesseract#3558]
hi, 
I made a license plate recognition system. I used the yolov5 model and the tesseract library to read text. I am building the project with linux operating system. but tesseract is insufficient to read license plate. I will ask you this; Can I use mnist dataset and tesseract together?

I have no clue how to do this.i need your help on this.I couldn't find any reference about it.please help me.

**Comment by zdenop** [comment]
Please respect guidelines for posting issues: we do not provide support for 3rd party projects. Use tesseract user forum for asking questions/support.
