### ISSUE TITLE
Tesseract generates too many different fonts making the output unusable with ghostscript

### ISSUE THREAD

**Issue by njunghans** [tesseract-ocr/tesseract#3559]
### Environment

* **Tesseract Version**: pyocr 0.7.2 
* **ocrmypdf version** : 12.2.0

### Current Behavior:
 [generated file](https://drive.google.com/file/d/1LsVWll-GFKTS29nhbqRhv4Ox8tv_B7KV/view?usp=sharing) has too many font definitions. For example the first page has 36 different font definitions. 

### Workflow : 
The PDF was created using ocrmypdf (with tesseract) on individual tiffs reduced to 300dpi resolution to create single page PDF files and then combining those using pypdf2. Upon which ghostscript postprocessing is started which then exceed 32gb of ram because of the number of fonts (as described [here](https://bugs.ghostscript.com/show_bug.cgi?id=704142)).

### Expected Behavior: 
Tesseract should have a way to limit/reduce the amount of different font definitions in the generated file.

**Comment by stweil** [comment]
Do you also have a smaller example?

The generated example was not created by Tesseract and Tesseract also does not add a lot of font definitions, so this is not a Tesseract issue.

**Comment by amitdo** [comment]
Tesseract  embeds  only **one** (faux) font in the PDF it produces.

**Comment by njunghans** [comment]
after retesting each step in the workflow, it seems you are correct, and the bug lies in the ghostscript command that follows. Sorry
