### ISSUE TITLE
Set whitelist for non english doesn't work

### ISSUE THREAD

**Issue by mickeyzo12** [tesseract-ocr/tesseract#3561]
### Environment

* **Commit Number**: 
* **Tesseract** Version: tesseract 3.05
* **Platform**: Platform: Windows, 64-bit
* **Platform**: Platform: visual studio 12, c++ 

### Current Behavior:

**whitelist** works very well in english language 
api->SetVariable("tessedit_char_whitelist", "qwertyuiopasdfghjklzxcvbnm1234567890") 
While using chi_tra, vie, ko... to work on this image
However, after specifying the whielist using following commands: for vie language
api->SetVariable("tessedit_char_whitelist", "a â ă o ô ơ á à ê ư abceghijklmn0123456789")
issue is occurred with above setup for **vie** language

It seems that whitelist could only accept English characters or digits(whitelist does work for numbers, I have tested that).
How come?

p.s. I tried this because I wanted Tesseract to detect only the words on whitelist.
### Expected Behavior:
non english whitelist should be set.

**Comment by zdenop** [comment]
tesseract 3.05 is unsupported version of tesseract.
