### ISSUE TITLE
 The pictures captured by the camera did not identify well after preprocessing

### ISSUE THREAD

**Issue by lvies** [tesseract-ocr/tesseract#3562]
Tesseract Version：4.1.1
Platform:Window10
![testa](https://user-images.githubusercontent.com/51877381/133545017-12e2b715-be45-4198-8035-9838c5375ea9.png)
![testb](https://user-images.githubusercontent.com/51877381/133545026-66cdd822-6885-4561-aa8c-d13496573a62.png)
Page.getText():

ACBEDFHGIKJLNHOP
RQSUTV¥WYaZbdcef

1ppp000012121010
&*(O+-,.:; O=%/

like this，the result has some faults.
I know that my image has some defects,but how can i improve this situation?
I have done the binarization of the picture,and try to improve dpi to 300
Because the pictures captured by the camera,I am worried if they can meet the standard for web pictures

**Comment by lvies** [comment]
i have used LTSM mode ,and my Identified word library file is trained by LTSM and Microsoft Yahei Standard font

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
