### ISSUE TITLE
Potential segmentation fault by incorrect index value

### ISSUE THREAD

**Issue by junsik-kim0** [tesseract-ocr/tesseract#3582]
### Environment

* **Tesseract Version**: 5.0.0-beta-20210916
* **Commit Number**: 
* **Platform**: Ubuntu 18.04

### Current Behavior:
A bug was found within the tesseract. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using tesseract. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the test-code"UnicharsetLoadKeepsTatweel"

Steps to reproduce:

  1. git clone https://github.com/tesseract-ocr/tesseract.git

  2. cd tesseract & ./autogen.sh & ./configure --prefix=$(pwd)/local --enable-shared=no CC="clang" CXX="clang++" CFLAGS="-g" CXXFLAGS="-g" LDFLAGS="-g"
  3. make
  4. Download the attached file and unzip(attach.zip)
  5. Build TEST CODE (case1.cc)
     clang++ -I./include -I./include -I./src/arch -I./src/ccmain -I./src/ccstruct -I./src/ccutil -I./src/cutil -I./src/dict  -I./src/training/unicharset -I./src/viewer -fopenmp -g -std=c++17 -c -o case1.o case1.cc
   clang++  -fsanitize=address -fopenmp -g -std=c++17 -g -o case1 case1.o  ./.libs/libtesseract.a -llept -lpthread -fopenmp
 6. Run
 ./case1

[attach.zip](https://github.com/tesseract-ocr/tesseract/files/7263157/attach.zip)

### Suggested Fix:
The library is using a value of -1 as INVALID_UNICHAR_ID, but there is no handling for value less than -1.  The test code seems to do an upper bound check. So It seems that you also need to check the lower bound.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/bb155a1bb4109ce3e13b0a902e5fd78e533e23ca/src/ccutil/unicharset.cpp#L279-L286

It's not part of the public API, but we might still want to change this code to detect a mistake in the internal code.

**Comment by stweil** [comment]
This issue was fixed in commit 842cca1d4.

**Comment by amitdo** [comment]
Yes you are right, I didn't realize the cast solve this issue.
