### ISSUE TITLE
Potential segmentation fault by incorrect index value

### ISSUE THREAD

**Issue by junsik-kim0** [tesseract-ocr/tesseract#3585]
### Environment

* **Tesseract Version**: 5.0.0-beta-20210916
* **Commit Number**: 
* **Platform**: Ubuntu 18.04

### Current Behavior:
A bug was found within the tesseract. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using tesseract. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the test-code"Primes"

crash log
```
=================================================================
==41975==ERROR: AddressSanitizer: SEGV on unknown address 0x605fa40c0024 (pc 0x0000004c60b5 bp 0x7ffea113d7d0 sp 0x7ffea113d7c0 T0)
==41975==The signal is caused by a READ memory access.
    #0 0x4c60b5 in tesseract::IndexMapBiDi::SparseToCompact(int) const /root/fuzz-test-generation/exp/tesseract/./src/ccutil/indexmapbidi.h:141:12
    #1 0x4c600a in main /root/fuzz-test-generation/exp/tesseract/case4.cc:13:7
    #2 0x7f2ac0d5fbf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #3 0x41b839 in _start (/root/fuzz-test-generation/exp/tesseract/case4+0x41b839)
```

Steps to reproduce:

  1. git clone https://github.com/tesseract-ocr/tesseract.git

  2. cd tesseract & ./autogen.sh & ./configure --prefix=$(pwd)/local --enable-shared=no CC="clang" CXX="clang++" CFLAGS="-g" CXXFLAGS="-g" LDFLAGS="-g"
  3. make
  4. Download the attached file and unzip(attach.zip)
  5. Build TEST CODE (case4.cc)
     clang++ -I./include -I./include -I./src/arch -I./src/ccmain -I./src/ccstruct -I./src/ccutil -I./src/cutil -I./src/dict  -I./src/training/unicharset -I./src/viewer -fopenmp -g -std=c++17 -c -o case4.o case4.cc
   clang++  -fsanitize=address -fopenmp -g -std=c++17 -g -o case4 case4.o  ./.libs/libtesseract.a -llept -lpthread -fopenmp
 6. Run
 ./case4

[attach.zip](https://github.com/tesseract-ocr/tesseract/files/7263657/attach.zip)

### Suggested Fix:
As a result of brief analysis, it is used as an index of a particular variable, and the data type is received as an Integer, which can be smaller than zero or bigger than vector size.
Also, for functions that receive Index from the outside, it is necessary to make sure that it is a valid index

**Comment by amitdo** [comment]
@stweil, you labeled this issue as `wontfix` but didn't close it.
