### ISSUE TITLE
Several non-descript cases of "core::Error" while compiling with GCC 10.3 in MSYS2

### ISSUE THREAD

**Issue by LigH-de** [tesseract-ocr/tesseract#3594]
### Environment

* **Tesseract Version**: HEAD
* **Commit Number**: 5.0.0-beta-20210916-63-g0d57
* **Platform**: media-autobuild suite = MSYS2 + MinGW64 + GCC 10.3 Win32 cross-compiler (ccache enabled) on Windows 7 SP1 x64 and Windows 10

### Current Behavior:

Several non-descript cases of "core::Error" while compiling with GCC 10.3:

```
...
  CXX      src/dict/libtesseract_la-dawg_cache.lo
terminate called after throwing an instance of 'core::Error'
terminate called recursively
make[1]: *** [Makefile:5779: src/cutil/libtesseract_la-oldlist.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/tesseract-git/build-32bit'
make: *** [Makefile:8149: all-recursive] Error 1
Making all in .
make[1]: Entering directory '/build/tesseract-git/build-32bit'
  CXX      src/cutil/libtesseract_la-oldlist.lo
  CXX      src/dict/libtesseract_la-dict.lo
  CXX      src/dict/libtesseract_la-stopper.lo
  CXX      src/dict/libtesseract_la-trie.lo
terminate called after throwing an instance of 'core::Error'
terminate called recursively
make[1]: *** [Makefile:5821: src/dict/libtesseract_la-trie.lo] Error 1
make[1]: Leaving directory '/build/tesseract-git/build-32bit'
make: *** [Makefile:8149: all-recursive] Error 1
```

See more verbose log files in [logs.zip](https://0x0.st/-0w8.zip) collected by [media-autobuild_suite](https://github.com/m-ab-s/media-autobuild_suite)

*I am a bit confused why it does not contain verbose C/C++ compiler errors with references to source lines.* 🤔 

### Expected Behavior:

successful compilation

### Suggested Fix:

none; I am not a C/C++ developer

**Comment by LigH-de** [comment]
So I did, but it still produced such an error.

[logs.zip](https://0x0.st/-0xQ.zip)

**Comment by stweil** [comment]
Disabling the ccache might also help.
