### ISSUE TITLE
non-word recognition worsened/disimproved since tesseract v3.0.4 ?

### ISSUE THREAD

**Issue by jakobkroeker** [tesseract-ocr/tesseract#360]
I'm using  fedora 22 and tesseract release 3.0.4 (compiled from source):

when trying to recognize non-words with mixed upper-lower-case letters
I observe issues at least since tesseract 3.0.4 while it is working with 3.0.2.

For example. try to recognize the following text (with Arial font) with the command line tool 
and see what you get:

```
FfZzVv
```

![hardcoretest](https://cloud.githubusercontent.com/assets/2487128/16398929/9f3a1974-3cce-11e6-8dd6-ebfdcb627be2.png)

(For the first line I get `FszVv` in 3.0.4 while with 3.0.2 I get the correct result.)

Disabling the dictionaries does not have any effect.

**Comment by arnaud-fontaine** [comment]
It seems I have the same issue. The following image is incorrectly recognized as "ERPS is a free software" (note the "S" whereas it should be "5" as of ERP5) from versions 3.03-rc1 and later of tesseract whereas it is correctly recognized with versions 3.02.02 and below:
[https://lab.nexedi.com/nexedi/erp5/raw/master/product/ERP5OOo/tests/test_document/cmyk_sample.jpg](url)

Here are the versions I tested:
- 3.04.01 (leptnonica: 1.73): NOK
- 3.03.03 (leptonica: 1.71): NOK
- 3.03-rc1 (leptonica: 1.71): NOK
- 3.02.01 (leptonica: 1.69): OK
- 3.02 (leptonica: 1.71): OK

Any idea?

**Comment by Brian51** [comment]
https://lab.nexedi.com/nexedi/erp5/raw/master/product/ERP5OOo/tests/test_document/cmyk_sample.jpg
Link above gives 404 error?
B.

**Comment by arnaud-fontaine** [comment]
Sorry, I fixed the URL.

**Comment by Brian51** [comment]
Thanks.
B.

**Comment by zdenop** [comment]
Is this issue still problem with current code (4.0)? I just tried it with `tessdata_best `and I got this result:
`FfZzVv`
and 
`ERP5 is a free software.`
