### ISSUE TITLE
Inappropriate string causes abnormal loop.

### ISSUE THREAD

**Issue by junsik-kim0** [tesseract-ocr/tesseract#3604]
### Environment

* **Tesseract Version**: 5.0.0-beta-20210916
* **Commit Number**: 
* **Platform**: Ubuntu 18.04

### Current Behavior:
A issue was found within the tesseract. The issue was found with a fuzzer based on the test-code"DoesNotConvertSpace". DoesNotConvertSpace API doesn't seem to be a public api. But this issue is related to utf8_step which it seems to be public api. I gave input string, utf8_step return 2. but real string size is 1.

```
std::string StringRenderer::ConvertFullwidthLatinToBasicLatin(const std::string &str) {
   std::string half_str;
   UNICHAR::const_iterator it_end = UNICHAR::end(str.c_str(), str.length());                   it_end : 0x77aa051                              
   for (UNICHAR::const_iterator it = UNICHAR::begin(str.c_str(), str.length()); it != it_end; ++it) {            it: 0x7aa050, 0x7aa052..    
```

In the code above, the ++ operator changes the memory address as much as the step returned by utf8_step function.
But if there is a mismatch between the utf8_step return value and the real string size, the syntax will loop abnormally.

crash log
```
==30255==ERROR: AddressSanitizer: stack-overflow on address 0x7ffea5a16000 (pc 0x000000c21f17 bp 0x7ffea5a14150 sp 0x7ffea5a14080 T0)
    #0 0xc21f17 in tesseract::UNICHAR::utf8_step(char const*) /root/fuzz-test-generation/exp/tesseract/src/ccutil/unichar.cpp:155:48
    #1 0xc21f17 in tesseract::UNICHAR::const_iterator::operator*() const /root/fuzz-test-generation/exp/tesseract/src/ccutil/unichar.cpp:174:19
    #2 0x4ea753 in tesseract::StringRenderer::ConvertFullwidthLatinToBasicLatin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /root/fuzz-test-generation/exp/tesseract/src/training/pango/stringrenderer.cpp:709:45
    #3 0x4d9df6 in main /ssd_array/utopia_paper/fuzz-test-generation/exp/tesseract/case7.cc:12:9 
```

Steps to reproduce:

  1. git clone https://github.com/tesseract-ocr/tesseract.git

  2. cd tesseract & ./autogen.sh & ./configure --prefix=$(pwd)/local --enable-shared=no CC="clang" CXX="clang++" CFLAGS="-g" CXXFLAGS="-g" LDFLAGS="-g"
  3. make
  4. Download the attached file and unzip(attach.zip)
  5. Build TEST CODE (case7.cc)
     clang++ -DPANGO_ENABLE_ENGINE -DTESS_COMMON_TRAINING_API= -DTESS_PANGO_TRAINING_API= -DTESS_UNICHARSET_TRAINING_API= -I./include -I./include -I./src/training -I./src/training/common-I./src/training/unicharset -I./src/api -I./src/ccmain -I./src/ccutil -I./src/ccstruct -I./src/arch-I./src/dict -I./src/classify -I./src/wordrec -I./src/classify -I./src/dict -I./src/viewer -I./src/cutil -I./abseil -I./src/training/pango/ -I -I./usr/include/leptonica -I/usr/include/pango-1.0  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I./src/training/common/ -I./include/tesseract -fopenmp -g -std=c++17 -c -o case7.o case7.cc
   clang++ -fopenmp -fsanitize=address -g -std=c++14 -g -o case7 case7.o ./.libs/libabseil.a ./.libs/libtesseract_training.a ./.libs/libgtest.a ./.libs/libgtest_main.a ./.libs/libtesseract.a -licui18n -licuuc -licudata -lpangocairo-1.0 -lpangoft2-1.0 -lfontconfig /usr/lib/x86_64-linux-gnu/libfreetype.so -llept -lcairo -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lpthread
 6. Run
 ./case7

[attach.zip](https://github.com/tesseract-ocr/tesseract/files/7396085/attach.zip)

### Suggested Fix:
There may be mismatches, need to change != to <= .

**Comment by stweil** [comment]
This scenario could only happen if the string contained invalid unicodes. Then changing the condition for the loop termination would solve the crash, but hide the fact that there is something wrong with the string. Therefore I prefer to see whether this crash occurs in real applications. I don't think so as I have never observed it nor seen any matching bug report.
