### ISSUE TITLE
--list-langs fails if english is not installed

### ISSUE THREAD

**Issue by fleaz** [tesseract-ocr/tesseract#3605]
### Environment

* **Tesseract Version**: 4.1.1
* **Platform**: Arch Linux, amd64 5.14.12 

### Current Behavior:
When installing tesseract and any other language except english, the `--list-langs` command fails. The exitcode is still 0 but there is output on stderr which e.g. breaks tools that call tesseract under the hood to use it and check for text on stderr to detect problems (Happened to me with ocrmypdf).

From what I can tell the rest of tesseract works just fine in that scenario.

```
$ tesseract --list-langs
Error opening data file /usr/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
List of available languages (2):
deu
osd
```

### Expected Behavior:
No error message and just a list of installed languages.

### Suggested Fix:
Don't try to open "eng.traineddata" when listing all available languages

**Comment by alerque** [comment]
Just for the record, I tested this out on Tesseract 5 and ENG is no longer hard coded as a dependency. OSD is still needed, but installing training data for any other language will enable function for that language without a hard dependency on ENG.

**Comment by amitdo** [comment]
>I already think for some time about adding a feature "default configuration" which allows users setting their own default parameters, for example the default language. But that are plans for the future.

@stweil, is there a separate issue for this?

**Comment by stweil** [comment]
There was no such issue, but I created one now: #3739.
