### ISSUE TITLE
Arabic and RTL languages

### ISSUE THREAD

**Issue by christophered** [tesseract-ocr/tesseract#361]
Hi there,
As everybody knows by now that the Cube engine is being discontinued and a new OCR engine based on LSTM will be introduced, even-though neither the Cube training tools or it's documentation been published.

One can only see that there is purposely neglect and sabotage to the  "RTL" Right to Left language community.
Hindering the developer community of training the Tesseract on RTL languages.

Issues such as that Tesseract while training considers all the letters and words as a single word, and the training is conducted as training a single word, along with many other issues while training RTL languages have been neglected for years and years, Tesseract showing no interest in solving any of the RTL languages issues.

And yet we ask Ray to publish the documentation and tools to train Cube before it is fully removed from tesseract, or at least assure the community that the RTL languages (Arabic, Hebrew...) will be considered in future version releases of Tesseract and future tools will be published helping the developer community in the training process of RTL languages.

List of some issues in the RTL training:
1) Tesseract consider all words as a single 1 Word while training.
"Generated training data for 1 words"

2) Tesseract fail to add some letters while training.
 "APPLY_BOXES: boxfile line * : FAILURE! Couldn't find a matching blob"

List of some issues in the RTL recognition:
3) Tesseract combines all the letters together while recognition.
4) Tesseract reverse the direction of the words while recognition.

Suggested solution for some of these problems:
2) The "box file" must be created with a criteria inwhich the boxes for each letter must not conjoin or merge with any other box, meaning that each box is an entity for a single glyph and does not have any part of it enter another box of another glyph.

3) Adding "ara.config" file in the folder you wish to train while modifiying it by setting "tessedit_ocr_engine_mode 0" instead of "1", or removing the entire line.

**Comment by jbreiden** [comment]
Left-to-right languages are incredibly important. Arabic,  for example, has hundreds of
millions of speakers and is the fifth most widely used language when including all variants.
I recommend looking at the DAS tutorial slides, they are interesting reading. The last 
set 'Building a Multi-Lingual OCR Engine' talks about in-progress numbers with Farsi 
and other languages that currently perform poorly with Tesseract 3. Machine learning 
has advanced quite a bit recently, and that's where the energy is.

http://www.vistawide.com/languages/top_30_languages.htm
https://github.com/tesseract-ocr/docs/tree/master/das_tutorial2016

**Comment by jbreiden** [comment]
Take a look at DAS 2016 slides

**Comment by christophered** [comment]
but what about solving the issues?

**Comment by ctrlcctrlv** [comment]
@christophered No one is hindered or attempting to sabotage RTL languages. Get over yourself. You can use and develop a fork of Tesseract 3.0 until the cows come home if you so choose.

The Arabic trained data is available in the tessdata repo, and if you want to submit patches to improve the LTSM engine for Arabic, you can. If not, that's fine, maybe someone else familiar with both the language and Tesseract will come around. In an open source community, you are not entitled to anything...if you want things fixed, submit patches -- you're already pretty close having already identified some problems.

**Comment by amitdo** [comment]
You replied to a 9 month old post.

Since then, LSTM code landed in the repo, and the OP opinion had changed.
https://github.com/tesseract-ocr/tesseract/issues/630#issuecomment-271392038

**Comment by AbdelsalamHaa** [comment]
Hi, im using tesseract 4.00 and leptonica 1.75.3 i used eng.traindata for some image and it worked very well . now im trying to use the same code for arabic i used ara.traindata but it gives a weird characters. is it due to getUTF8Text(); or that has nothing to do with it

**Comment by jishakrishnan** [comment]
Hi, I am facing the same issue Arabic text extracted using _pytesseract.image_to_string(filename,'lang=ara')_ is from left to 
<img width="350" alt="Screenshot 2020-10-11 at 12 56 05 PM" src="https://user-images.githubusercontent.com/14840214/95674509-b482d980-0bc1-11eb-8b4e-eb77834134a1.png">
right.
 original image
