### ISSUE TITLE
Deserialize header failed: UrdJN.lstmf

### ISSUE THREAD

**Issue by sameearif88** [tesseract-ocr/tesseract#3615]
------------------------

### Environment

* **Tesseract Version**:  4.1.1
* **Commit Number**: 
* **Platform**:  Linux samee-HP-Spectre 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
lstmtraining --traineddata "data/UrdJN.traineddata" --model_output "output/" --net_spec "[1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx96 Lrx96 Lfx256 O1c64]" --train_listfile "data/UrdJN.trainingfiles_text" --max_iterations 200000 --debug_interval -1
Num outputs,weights in Series:
  1,36,0,1:1, 0
Num outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys48:48, 12480
  Lfx96:96, 55680
  Lrx96:96, 74112
  Lfx256:256, 361472
  Fc64:64, 16448
Total weights = 520352
Built network:[1,36,0,1[C3,3Ft16]Mp3,3Lfys48Lfx96Lrx96Lfx256Fc64] from request [1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx96 Lrx96 Lfx256 O1c64]
Training parameters:
  Debug interval = -1, weights = 0.1, learning rate = 0.001, momentum=0.5
null char=63
Deserialize header failed: UrdJN.lstmf
Load of page 0 failed!
Load of images failed!!

**Comment by Shreeshrii** [comment]
Please try with the latest code from the `main` branch in github and see if the problem still exists.

**Comment by Shreeshrii** [comment]
No response from OP.

**Comment by amitdo** [comment]
Shreeshrii,

What about #2767 and #3012, should we close them too?

**Comment by Shreeshrii** [comment]
Yes. Please do.
