### ISSUE TITLE
Can't detect the 0 in the PNG file

### ISSUE THREAD

**Issue by arthw** [tesseract-ocr/tesseract#3616]
### Environment
Win10-64
tesseract-ocr-w64-setup-v5.0.0-alpha.20210811.exe

### Current Behavior:
Can't detect the '0' in single image

### Expected Behavior:
detect the '0'
### Suggested Fix:
No
### The images with '0'

![tmp](https://user-images.githubusercontent.com/14088817/139533385-866d8995-d366-4440-9fa2-eea2e7be86c7.png)

![a](https://user-images.githubusercontent.com/14088817/139533579-f882e2b1-032e-4b9e-a83a-29dd1b722df8.png)

**Comment by zdenop** [comment]
Please read the documentation

**Comment by arthw** [comment]
@zdenop 
Which document to resolve my issue?
Could you share the link?

Thank you!

**Comment by zdenop** [comment]
https://github.com/tesseract-ocr/tessdoc
