### ISSUE TITLE
Move tesseractmain.cpp outside of the api directory

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#3617]
The tesseract program should be separated from the library code.

**Comment by amitdo** [comment]
We discussed this issue before in #594, but unfortunately there was no consensus.

Let's try again :-)

**Comment by stweil** [comment]
`tesseractmain.cpp` is not really independent of the library internals. It uses header files which are not part of the public API. But moving it one level higher from `src/api/tesseractmain.cpp` to `src/tesseract.cpp` is possible of course. Would you suggest to do that before 5.0.0 is released?

**Comment by amitdo** [comment]
>`tesseractmain.cpp` is not really independent of the library internals. It uses header files which are not part of the public API.

You are right. IMO, it's problematic that others can't do exactly what we can do in tesseractmain with just libtesseract.

>But moving it one level higher from `src/api/tesseractmain.cpp` to `src/tesseract.cpp` is possible of course. Would you suggest to do that before 5.0.0 is released?

Yes, I do.

**Comment by amitdo** [comment]
Fixed in #3916.
