### ISSUE TITLE
From GitHub: strange tesseract process behavior in Python 2.7 calls.

### ISSUE THREAD

**Issue by ResidentMario** [tesseract-ocr/tesseract#362]
[StackOverflow query here](http://stackoverflow.com/questions/38165741/long-running-python-2-7-popen-processes-choice-between-resource-unavailability). Just thought I'd bring it up here as well, in case this is a `tesseract` issue and not a `subprocess.Popen` one.

**Comment by zdenop** [comment]
please follow [rules](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).
