### ISSUE TITLE
CI unittest-disablelegacy fails since some time

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#3620]
There was a build issue (missing include statements) which is fixed now, but two CI tests fail.

**Comment by Shreeshrii** [comment]
Reported in https://github.com/tesseract-ocr/tesseract/issues/3226

**Comment by amitdo** [comment]
LSTM does not support equation detection. only the legacy engine does.

**Comment by amitdo** [comment]
I now see that you closed this issue because it duplicated #3226 which is still open.

**Comment by amitdo** [comment]
>There was a build issue (missing include statements) which is fixed now

Can you give me a link to the reported build failure related to the missing include statement?

**Comment by stweil** [comment]
https://github.com/stweil/tesseract/runs/3479277718?check_suite_focus=true

**Comment by amitdo** [comment]
IMO, the right solution is to disable the delete in disable legacy mode (it will stay null all the time anyway in this mode). The header should not be included.

**Comment by amitdo** [comment]
Or just ignore the warning because in this case it's harmless IMO.

**Comment by stweil** [comment]
That code also triggers a clang crash. So ignoring of the warning is not a good solution.

Disabling the delete is fine if all other code with `equ_detect_` is disabled, too.

**Comment by amitdo** [comment]
You should consider all files that is disabled in autotools, including headers as deleted files for disable legacy mode. If there is an issue the solution should not be re-include them. but to disable some more code.

A crash is bad. so it needs to be fixed. I wanted to avoid more ugly ifdefs, thinking this code is harmless, but it was not a good idea to avoid them.

**Comment by amitdo** [comment]
The crash is a compiler time crash. A compiler should not crash due to errors in code it compiles. This crash is a clang bug. They telling you:

>PLEASE submit a bug report to https://bugs.llvm.org/
