### ISSUE TITLE
execute configure failed!!!

### ISSUE THREAD

**Issue by HatherP** [tesseract-ocr/tesseract#3621]
### Environment

* **Tesseract Version**: tesseract-4.1.0
* **Commit Number**: 
* **Platform**: Linux localhost.localdomain 2.6.32-573.el6.x86_64 #1 SMP Wed Jul 1 18:23:37 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:./configure

checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
./configure: line 3911: AX_SPLIT_VERSION: command not found
./configure: line 3912: s/^[^0-9]*//: No such file or directory
./configure: line 3914: s/^\([0-9][0-9]*\).*/\1/: No such file or directory
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
./configure: line 4128: syntax error near unexpected token `-Werror=unused-command-line-argument,'
./configure: line 4128: `AX_CHECK_COMPILE_FLAG(-Werror=unused-command-line-argument, WERROR=-Werror=unused-command-line-argument)'

when i execute configure,output this log,how can i continue to install

**Comment by zdenop** [comment]
Please respect guidelines for posting issues: use tesseract user forum for asking questions/support.
Please fix the reported problems before you made any post to forum.

**Comment by amitdo** [comment]
You are using a 11 years old distro.

Use 4.1.1 or 5.0.0 rc1 on RHEL 7 / 8 (or another distro).
