### ISSUE TITLE
Failed to initialise Tesseract Engine when multiple initializations performed

### ISSUE THREAD

**Issue by esraince1** [tesseract-ocr/tesseract#3622]
I try to initialize tesseract ocr in a custom exe. When I start exe instance and initialize Tesseract it works well. However, when I open another exe and initialize Tesseract again I got the error message below. Is there a limitation for number of Tesseract instances initialized ?

image

**Comment by stweil** [comment]
There is no such limit in the Tesseract code.

**Comment by esraince1** [comment]
Is there a way to detect the root cause of the problem , like a file is being holded by other Tesseract object or etc ?

**Comment by stweil** [comment]
It would help if you could copy+paste the error message (please avoid screenshots).

**Comment by zdenop** [comment]
As always:  do not describe problem by words - provide simple test case for replication of problem + details (tesseract version, tessdata type, OS version, etc).

**Comment by amitdo** [comment]
The OP did not provide the requested information.
