### ISSUE TITLE
RFC: Do not terminate with FF for single page text output

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#3628]
Currently each page is terminated by the FF character by default for text output.

What about not adding FF at end to single page text output?

[Help Info](https://tesseract-ocr.github.io/tessdoc/FAQ.html#what-page-separators-are-used-in-txt-output-by-tesseract-400)

**Comment by amitdo** [comment]
This FF can confuse people because it produces an unfamiliar symbol.

IMO, even for multi page tif it should not be used by default.

**Comment by stweil** [comment]
So the suggestion is to use no page separator by default? Is this a last minute change which is desired for 5.0.0?

Note that restoring FF is not so easy because it is difficult to enter on a command line.

**Comment by amitdo** [comment]
Note that restoring FF is not so easy because it is difficult to enter on a command line.

This issue can be solved by adding a config variable `page_separator form_feed`.

**Comment by amitdo** [comment]
>Note that restoring FF is not so easy because it is difficult to enter on a command line.

`-c page_separator="\f"`

**Comment by amitdo** [comment]
@Shreeshrii,

I implemented what you requested.

The question remains, should we change the default for **multi page images** page separator from form feed (`\f`) to `\n` (or `\n\n`).

**Comment by Shreeshrii** [comment]
Thanks @amitdo. My request was only RFC. I think others who use tesseract regularly should chime in regarding the implementation for mukti page tif.

**Comment by stweil** [comment]
I estimate that Tesseract is mostly used on single page images and that multi page TIFF is a rare use case. Therefore I don't think that additional changes for 5.0.0 are needed here.
