### ISSUE TITLE
about OCR geometric dimensioning info on images

### ISSUE THREAD

**Issue by powerfulant** [tesseract-ocr/tesseract#3629]
Dears, 
I'd like to use Tesseract to OCR geometric dimensioning info on images, 
and to clarify, the following is an example and what to be OCR-ed is in the red rectangle.
I do know there are lots of supported language, but the geometric dimensioning info I think is a little bit different,
Is there any way to realize it using Tesseract and is there any document which I can refer to for this?
![example1](https://user-images.githubusercontent.com/14267006/140616599-c77965b3-4360-42bb-a088-cad30911051c.png)
thanks a lot
Ant

**Comment by zdenop** [comment]
The same as here
https://groups.google.com/g/tesseract-ocr/c/CxvGYWbE3Ug/m/TFczEDmpBAAJ

**Comment by powerfulant** [comment]
Thank you, Zdenop,
To make things more specific and easier, 
I do not expect to give Tesseract the entire image but to just give Tesseract the area which is expected to be OCR-ed, which can be done by pre-processing the image, the following are 2 examples:
![example3](https://user-images.githubusercontent.com/14267006/140630428-69d3d5a4-70ed-447e-86d9-b5a217850027.png)
![example4](https://user-images.githubusercontent.com/14267006/140630430-cf58a4b7-100c-4d4b-9614-01595a1b0cba.png)
Could you or anybody else kindly give me some instructions on how to OCR such geometric information?

For further information: I already had a special font to display such characters once it is OCR-ed, but I still do not know how to mapping the OCR results to this font. Thanks a lot in advance if there is any instructions or documents about this as well.

Thanks again!
Ant

**Comment by wollmers** [comment]
@powerfulant 

You can OCR it, but your images have issues:

```
$ tesseract drawing.png - --tessdata-dir /usr/local/share/tessdata
Tesseract Open Source OCR Engine v5.0.0-alpha-773-gd33ed with Leptonica
libpng warning: iCCP: known incorrect sRGB profile
Error in boxClipToRectangle: box outside rectangle
Error in pixScanForForeground: invalid box
```

I removed the red border and converted to a standard sRGB profile:

![drawing cut](https://user-images.githubusercontent.com/1275557/140647222-67193aea-46f1-4dab-81dd-1b3f73b07a41.png)

Now it has a result:

```
$ tesseract drawing.cut.png - --psm 6 --tessdata-dir /usr/local/share/tessdata 
[ols uz -3]a]86[08)
(a2 cz]
```

For better results you need to train a model yourself with the font and all that special symbols.

See https://tesseract-ocr.github.io/tessdoc/#training-for-tesseract-4.

**Comment by powerfulant** [comment]
thank you so much, Helmut,Previously I post this question on GitHub but I was told to seek help for this on the forum, unfortunately, when I go to the forum, it seems that I can not start a new conversation there. But fortunately I see your reply.actually, in the original image, there is no red border. the red border is added by me to let others know what I want to OCR.I will learn into how to train a model for a font, do you think I should use Tasseract 4.0 or 5.0？Thanks again!Ant-------- 原始邮件 --------发件人： Helmut Wollmersdorfer ***@***.***>日期： 2021年11月7日周日 21:52收件人： tesseract-ocr/tesseract ***@***.***>抄送： powerfulant ***@***.***>, Mention ***@***.***>主    题： Re: [tesseract-ocr/tesseract] about OCR geometric dimensioning info on images (Issue #3629)
@powerfulant
You can OCR it, but your images have issues:
$ tesseract drawing.png - --tessdata-dir /usr/local/share/tessdata
Tesseract Open Source OCR Engine v5.0.0-alpha-773-gd33ed with Leptonica
libpng warning: iCCP: known incorrect sRGB profile
Error in boxClipToRectangle: box outside rectangle
Error in pixScanForForeground: invalid box

I removed the red border and converted to a standard sRGB profile:

Now it has a result:
$ tesseract drawing.cut.png - --psm 6 --tessdata-dir /usr/local/share/tessdata 
[ols uz -3]a]86[08)
(a2 cz]

For better results you need to train a model yourself with the font and all that special symbols.
See https://tesseract-ocr.github.io/tessdoc/#training-for-tesseract-4.
