### ISSUE TITLE
information about failure to recognize any charaters in those images

### ISSUE THREAD

**Issue by ytrezq** [tesseract-ocr/tesseract#363]
Hello, would it be possible to know what makes tesseract failing to recognize any characters in those images *(I tried many filters but tesseract fails in every cases)* ? Is‑it because the anti‑aliasing is huge or because there’s no space between letters ?

![cantal](https://cloud.githubusercontent.com/assets/3824869/16715547/6952422c-46e3-11e6-8ec6-a24a40f4aa45.jpeg)
![ackskin](https://cloud.githubusercontent.com/assets/3824869/16715571/22e588f2-46e4-11e6-8c39-03894e934059.jpeg)

thanks,

**Comment by rtaylor-qoppa** [comment]
Heh…  those are Captcha images – where the text has been distorted so 
that it is cannot be recognized by software like OCR.

 

The distortions are designed so that only a real human can read the text.

Tesseract will never be able to recognize this correctly.

 

-= Rich

**Comment by zdenop** [comment]
please follow [rules](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).
