### ISSUE TITLE
Re-open since closed: about OCR geometric information in image

### ISSUE THREAD

**Issue by powerfulant** [tesseract-ocr/tesseract#3630]
Thank you, Zdenop,
(Since my issue is closed, I guess I have to re-open a new one to request further help, sorry.)
To make things more specific and easier, 
I do not expect to give Tesseract the entire image but to just give Tesseract the area which is expected to be OCR-ed, which can be done by pre-processing the image, the following are 2 examples:
![example3](https://user-images.githubusercontent.com/14267006/140630428-69d3d5a4-70ed-447e-86d9-b5a217850027.png)
![example4](https://user-images.githubusercontent.com/14267006/140630430-cf58a4b7-100c-4d4b-9614-01595a1b0cba.png)
Could you or anybody else kindly give me some instructions on how to OCR such geometric information?

For further information: I already had a special font to display such characters once it is OCR-ed, but I still do not know how to mapping the OCR results to this font. Thanks a lot in advance if there is any instructions or documents about this as well.

Thanks again!
Ant

_Originally posted by @powerfulant in https://github.com/tesseract-ocr/tesseract/issues/3629#issuecomment-962542773_

**Comment by amitdo** [comment]
The right place to ask this kind of question is [our forum](https://groups.google.com/d/forum/tesseract-ocr).

**Comment by powerfulant** [comment]
Thanks a Amitdo, I will seek help in the forum.
