### ISSUE TITLE
Windows sw build failing

### ISSUE THREAD

**Issue by amanmamgain9** [tesseract-ocr/tesseract#3636]
### Environment
Windows
* **Tesseract Version**: <master + 4.1.1>
* **Commit Number**: 
* **Platform**: 

### Current Behavior:
This error now coming when building project, you can use the documentation provided here
https://tesseract-ocr.github.io/tessdoc/Compiling.html

If you follow the steps above you will get this error
fatal error C1083: Cannot open include file: 'jxl/decode.h': No such file or director

### Expected Behavior:
Should work, was working fine before

**Comment by stweil** [comment]
`jxl/decode.h` is part of the JPEG library, not of the Tesseract code. So this does not look like a Tesseract issue.

**Comment by amanmamgain9** [comment]
Yeah, but the instructions given don't work. Maybe just remove the opencv dependency in the example CMAKE file.
This happens when building using sw

**Comment by zdenop** [comment]
Which instruction? What did you did? 
Provide exact step for reproducing issue otherwise we can not help you.

**Comment by amanmamgain9** [comment]
https://tesseract-ocr.github.io/tessdoc/Compiling.html

I followed the instructions here, There is also a link to an example cmake+sw build
https://github.com/SoftwareNetwork/sw/tree/master/test/integrations/cmake/tess

**Comment by zdenop** [comment]
So you should report problem at right project: https://github.com/SoftwareNetwork/sw - not here. 
Also you would not report here problem with png library or disk, just because tesseract is using it.
