### ISSUE TITLE
White background TIF going in black background PDF being generated.

### ISSUE THREAD

**Issue by MartinDavidWaller** [tesseract-ocr/tesseract#3647]
### Environment

tesseract 4.1.1
 leptonica-1.80.0 (Nov 18 2021, 11:48:12) [MSC v.1916 LIB Release x64]
  libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.0.6) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11

Windows 10 Home, 64-bit 

### Current Behavior:

I'm processing a tif file with the command:

tesseract.exe test.tif x -l eng config.txt

where the config file contains one line:

tessedit_create_pdf     1  

the tif file has no text in it, but I have the same issue with tif files containing text. The text is not supplied as it's private data. Where the tif file has a white background the resulting pdf has a black bakground?

The attached zip file contains both the tif file and the resulting pdf file.

### Expected Behavior:

[bin.zip](https://github.com/tesseract-ocr/tesseract/files/7563297/bin.zip)

I expected the PDF to have a white background? 

### Suggested Fix:

Many thanks for any help you can provide.

Martin

**Comment by stweil** [comment]
Your TIFF file is black when I open it on MacOS.

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by amitdo** [comment]
On Linux, the TIFF file has white with GNOME Image Viewer, but with GIMP it is combination of black and transparent layer.

So this image seems to be unusual.

**Comment by MartinDavidWaller** [comment]
Hi Amitdo, many  thanks for taking the time to look into this for me. If I open the image using Gimp on Windows I get a combination of white and transparent! As you say, the image seems unusual. Interestingly, on windows, if I fire off GIMP once in windows and once in Ubuntu within virtual box I see the transparency and a white box!

I need to dig further!

Martin

![image](https://user-images.githubusercontent.com/8803621/142608306-25526723-0674-4657-942b-d993bd4b04b6.png)

**Comment by stweil** [comment]
Gimp on MacOS shows the same combination. Safari on MacOS shows a black image (like the image preview).

**Comment by MartinDavidWaller** [comment]
Hi,

Interestingly Safari 5.1.7 (The last one available for Windows) shows the image being black too!

Martin
