### ISSUE TITLE
unicharset_extractor : undefined symbol

### ISSUE THREAD

**Issue by vkoushik** [tesseract-ocr/tesseract#365]
Hi,

I am getting the below error in the tesseract training process

unicharset_extractor:symbol lookup error:unicharset_extractor:undefined symbol: _ZNK10UNICHARSET12save_to_fileEP8_IO_FILE

Can someone please help me with this issue?

**Comment by zdenop** [comment]
Please provide detail (OS detail, tesseract version, how you compile, logs...)

**Comment by vkoushik** [comment]
ubuntu version 15
tesseract version 3.03
i just gave the command 

unicharset_extractor eng.Arial.exp0.box 

as mentioned in the guide

**Comment by zdenop** [comment]
use the current version. Before compiling from source remove all other version of tesseract.

**Comment by vkoushik** [comment]
I installed ubuntu only yesterday on my virtual machine just to work on tesseract.I downloaded tesseract from Github and built from source according to the instructions on Github.

**Comment by zdenop** [comment]
1. Ubuntu has recent tesseract packages
2. 3.03 version is old - not officially produced version. Nobody will look at it.

**Comment by vkoushik** [comment]
Ok i removed tesseract and rebuilt it from source.It's working now thanks
