### ISSUE TITLE
TessPDFRenderer writes wrong PDF format

### ISSUE THREAD

**Issue by dnnspaul** [tesseract-ocr/tesseract#3652]
### Environment

* **Tesseract Version**: 4.1.1
* **Platform**: (Docker Container) Linux f31a8bcb5cbc 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

### Current Behavior:
_(Reproduction of problem with docker below)._

ProcessPages() writes data to PDF file but PDF can't be opened and is invalid.

```c++
int PdfOutput(char* input, char* output) {
    tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
    if (api->Init("/usr/share/tesseract-ocr/4.00/tessdata", "deu", tesseract::OEM_DEFAULT)) {
        fprintf(stderr, "Could not initialize tesseract.\n");
        return 1;
    }

    PIX *sourceImg100 = pixRead(input);
    if (!sourceImg100) {
      fprintf(stderr, "Leptonica can't process input file: %s\n", input);
      return 2;
    }
    api->SetImage(sourceImg100);
    api->SetInputName(input);
    api->SetOutputName(output);

    tesseract::TessPDFRenderer *renderer = new tesseract::TessPDFRenderer(
              output, "/usr/share/tesseract-ocr/4.00/tessdata", false);

    if (!renderer->happy()) {
         printf("Error, could not create PDF output file: %s\n",
                strerror(errno));
         delete renderer;
         return 3;
    }

    bool succeed = api->ProcessPages(input, nullptr, 0, renderer);
    if (!succeed) {
      fprintf(stderr, "Error during processing.\n");
      return 4;
    }
    api->End();
    pixDestroy(&sourceImg100);
    return 0;
}
```
the functions returns 0 and prints no errors.

Used image:
![1359120613](https://user-images.githubusercontent.com/4589085/142673255-91324b12-7728-4b08-92e8-b0cd0df4d1b7.jpg)
The created PDF:
[testjpg.pdf](https://github.com/tesseract-ocr/tesseract/files/7572262/testjpg.pdf)

Using tesseract cli, the created PDF is correct:
[outfile.pdf](https://github.com/tesseract-ocr/tesseract/files/7572268/outfile.pdf)

I've noticed some differences in the PDFs, especially at the end of the file, looking like there is a footer or something like that missing (left cli, right my function):
![image](https://user-images.githubusercontent.com/4589085/142673561-4f00c14e-2039-41bf-958d-7f48c912bae1.png)

#### Reproducing
```bash
git clone git@github.com:dnnspaul/gosseract.git
git checkout tesseract/bug/3652

docker build -t tessbug .
docker run -it -v $PWD/tmp:/tmp tessbug go run main.go
```

The corrupt PDF is in the subdirectory tmp "testjpg.pdf".

### Expected Behavior:
The written PDF file is valid and openable.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/6360e60877425747c207f296852b9c1d9298159f/src/tesseract.cpp#L552

**Comment by amitdo** [comment]
Try to examine what missing in your implementation compared to what Tesseract does:
https://github.com/tesseract-ocr/tesseract/blob/6360e60877425747c207f296852b9c1d9298159f/src/tesseract.cpp

**Comment by amitdo** [comment]
If you still can't figure out how to do what you want to do, try your luck in [our forum](https://groups.google.com/d/forum/tesseract-ocr).
