### ISSUE TITLE
Bad result in persian(fas) or arabic numbers

### ISSUE THREAD

**Issue by mohammad69h94** [tesseract-ocr/tesseract#3653]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/main/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: tesseract 4.0.0-beta.1
* **Commit Number**: 
* **Platform**: ubuntu 64bit

### Current Behavior:
image num is :۱۲۳۴۵۶۷۸۹
output is: ۱۳۳۳۷

**Comment by amitdo** [comment]
> https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+Numbers+arabic+is%3Aclosed
> 
> [tesseract-ocr/langdata#71](https://github.com/tesseract-ocr/langdata/issues/71)
