### ISSUE TITLE
Tesseract 4.1 leaking handles on Windows 10/11

### ISSUE THREAD

**Issue by lukaswerner** [tesseract-ocr/tesseract#3654]
### Environment

* **Tesseract Version**: 4.1.1 (I used vcpkg to compile it and it doesn't let me use 4.1.3)
* **Commit Number**: unknown
* **Platform**: Windows 10 64bit, Windows 11 64bit

### Current Behavior:
When creating TessBaseAPI objects, initializing them, ending them and deleting references in a loop, an application would leak handles, mutant/mutex handles to be more specific.

Minimal example to reproduce:

    #include <iostream>
    #include <tesseract/baseapi.h>
    #include <leptonica/allheaders.h>
    
    int main()
    {
        while (true) {
            tesseract::TessBaseAPI* api = new tesseract::TessBaseAPI();
            api->Init(NULL, "eng");
            api->End();
            delete api;
        }
    
        return 0;
    }

### Expected Behavior:
Tesseract should clean up all resources when `End`ing the API and deleting the reference.

### Suggested Fix:
I unfortunately have none, but I'm open to ideas and workarounds.

**Comment by stweil** [comment]
Could you please try that with 4.1.3 and 5.0.0-rc2?

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/commit/412d8a988ead3d350c7e9880599f9e1547afdcec

**Comment by lukaswerner** [comment]
Hi @stweil, thank you for your fast response. I finally managed to compile the 4.1.3 version. There the handle leakage is solved (actually already in 4.1.2). Thank you very much. May I ask why this is not yet in the official 4.1 release?

**Comment by stweil** [comment]
4.1.3 is the latest official 4.1 release. There is no Windows installer for 4.1.3 on https://github.com/UB-Mannheim/tesseract/wiki because 5.0.0 is better in many aspects.

**Comment by lukaswerner** [comment]
I see, thank you. Most parts of the build instructions for windows (e.g. vcpkg) would install 4.1.1, which is why I struggled with getting 4.1.3 compiled. And we're not ready yet to use version 5. But it works now, thank you very much!

**Comment by Shreeshrii** [comment]
@stweil It will be helpful to those who are still with 4.1 to have access to windows binaries for 4.1.3 since it is better than 4.1.1. I will suggest adding it at your convenience. Thanks!
