### ISSUE TITLE
Unable to differentiate between 1 and 7

### ISSUE THREAD

**Issue by mjessa12** [tesseract-ocr/tesseract#3658]
![image](https://user-images.githubusercontent.com/72001246/143620563-7e74dd37-30ef-4e6a-b144-93d34b905cda.png)

have the following image that i converted to grayscale and applied the following threshold, 
gaus = cv2.threshold(img, 50, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)[1]

and a config when converting to data as:
config = '-l eng --oem 3 --psm 6'
text = pyt.image_to_data(gaus, config=config, output_type=Output.DICT)

but i am getting the result as Dec27 instead of Dec21.  Any help?

**Comment by wollmers** [comment]
Your posted image works perfect:

```
$ tesseract --version
tesseract 5.0.0-alpha-773-gd33ed

$ tesseract dec21.png - -l t5data_best/eng --tessdata-dir /usr/local/share/tessdata 
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 220
Dec21

$ tesseract dec21.png - -l t5data_fast/eng --tessdata-dir /usr/local/share/tessdata 
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 220
Dec21

$ tesseract dec21.png - -l t5data/eng --tessdata-dir /usr/local/share/tessdata 
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 220
Dec21

$ tesseract dec21.png - -l t5data_fast/eng --oem 3 --psm 6 --tessdata-dir /usr/local/share/tessdata 
Warning: Invalid resolution 0 dpi. Using 70 instead.
Dec21
```

IMHO you should check your intermediate image produced via cv2.

**Comment by mjessa12** [comment]
Hmm,  for some images it can process but for some it gets confused between 21 and 27.  Is there anyway to fix this?

**Comment by amitdo** [comment]
We never gur 100% accurcy...

There no easy fix we can do for minor inarticulacy in recognition the text like this one.

You can re-post this question in our forum, with an example which (unlike the image you provided here) Tesseract actually fails to recognize the text. (Use Tessrtact itself and not a 3rd party tool to verify that the issue is not in the 3rd party tool).
