### ISSUE TITLE
failed to load font_properties

### ISSUE THREAD

**Issue by vkoushik** [tesseract-ocr/tesseract#366]
tesseract 3.05.00dev
ubuntu v15
Hi,

I am following the training tesseract and i created font_properties text file with input as

BradleyHandBold 0 1 0 0 0

and tried to use it with mftraining and i got the error
no shape table file present
failed to load font_properties from font_properties

Since i am doing the training for english language,i skipped shapeclustering step but i thought i have to go back to that step since mftraining is asking for shape table,i executed that code and it throwed error
failed to load font_properties from font_properties

Can someone please help me with this issue?
Thank you

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support.

**Comment by amitdo** [comment]
`Warning: No shape table file present: shapetable`

This warning message is indeed confusing, but everyone gets it, so unless you are training Tesseract for an Indic script, you should ignore it.

For the second part of this issue, follow @zdenop advice.

**Comment by vkoushik** [comment]
Ok thanks...but i am not getting replies in the google group.This is a simple work of creating a txt file with fontname and 5 spaced 1 or 0. I don't understand why this doesn't work.

**Comment by amitdo** [comment]
Did you used the `-F` flag?

`mftraining -F font_properties...`

`font_properties` should be the file name (including any extension like `.txt`) you saved the  font_properties file.
