### ISSUE TITLE
error in 'Develop Tesseract'

### ISSUE THREAD

**Issue by md3848** [tesseract-ocr/tesseract#3662]
**Tesseract Version:** I think the latest version [I use this code, according to what is mentioned in the guide]
`git clone https://github.com/tesseract-ocr/tesseract tesseract`
**Platform:** Window 10 64bit

i try build Tesseract with this method [ [Develop Tesseract](https://github.com/tesseract-ocr/tessdoc/blob/main/Compiling.md#develop-tesseract) ] but when i run this code [ cmake .. ] show this **error** after a while :

`Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:764, function execute1: When executing: C:/Users/mahdi/.sw/storage/tmp/cfg/581545/loc.sw.self.d6bee8-0.0.28.dll
Creating library C:/Users/mahdi/.sw/storage/tmp/cfg/581545/loc.sw.self.d6bee8-0.0.28.lib and object C:/Users/mahdi/.sw/storage/tmp/cfg/581545/loc.sw.self.d6bee8-0.0.28.exp
sw.cpp.dc907b35.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<struct sw::builder::Command> & __cdecl sw::driver::CommandBuilder::getCommand(void)" (__imp_?getCommand@CommandBuilder@driver@sw@@QEAAAEAV?$shared_ptr@UCommand@builder@sw@@@std@@XZ) referenced in function "void __cdecl build(struct sw::Build &)" (?build@@YAXAEAUBuild@sw@@@Z)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: class std::shared_ptr<struct sw::builder::Command> __cdecl sw::CompilerBaseProgram::getCommand(struct sw::Target const &)" (__imp_?getCommand@CompilerBaseProgram@sw@@QEAA?AV?$shared_ptr@UCommand@builder@sw@@@std@@AEBUTarget@2@@Z)
    "__declspec(dllimport) public: virtual class std::shared_ptr<struct sw::builder::Command> __cdecl sw::NativeCompiledTarget::getCommand(void)const " (__imp_?getCommand@NativeCompiledTarget@sw@@UEBA?AV?$shared_ptr@UCommand@builder@sw@@@std@@XZ)
C:\Users\mahdi\.sw\storage\tmp\cfg\581545\loc.sw.self.d6bee8-0.0.28.dll : fatal error LNK1120: 1 unresolved externals
command failed: exit code = 1120 (0x460)
Total errors: 1
sw command: F:/Windows/Programing/OpenCV/S.W/OpenCV/4.5.4/libraries/Source File/Tesseract/SW/sw.exe -static -platform x64 -compiler msvc-19.28 -d C:/tesseract/build/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps C:/tesseract/build/.sw/cmake/sw.txt -cmake-file-version 6
CMake Error at C:/Users/mahdi/.sw/storage/etc/sw/static/SWConfig.cmake:235 (message):
  sw: non-zero exit code: 1
Call Stack (most recent call first):
  CMakeLists.txt:349 (sw_execute)` 

**Full code in cmd : ** [cmd.txt](https://github.com/tesseract-ocr/tesseract/files/7612475/cmd.txt)

note1 : The code above refers to drive D, but my computer only has drive C and F!
note2 : I am trying to build opencv [ with cmake + vs ], but before that I have to build tesseract and then when building opencv with cmake the tesseract inputs ...

**Comment by amitdo** [comment]
The issue you have is with the sw build system, not with Tesseract.

https://github.com/SoftwareNetwork/sw
