### ISSUE TITLE
build opencv with  tesseract

### ISSUE THREAD

**Issue by md3848** [tesseract-ocr/tesseract#3665]
* **Tesseract Version**: 5.0.0
* **Platform**: windows10 64bit

i builded Tesseract with this method [ [Develop Tesseract](https://github.com/tesseract-ocr/tessdoc/blob/main/Compiling.md#develop-tesseract) ] but when try build opencv, cmake can't find Tesseract :

![image](https://user-images.githubusercontent.com/17591943/143862538-aa2e8445-7b4d-4789-a5c4-ad5cbe315eb3.png)

**Develop Tesseract :** 
1) Download and install Git / CMake / SW and put them in PATH.
2) sw setup
3) git clone https://github.com/tesseract-ocr/tesseract tesseract
4) cd tesseract
5) mkdir build && cd build
6) cmake ..
7) run "tesseract.sln" as administrator -> build "ALL_BUILD / INSTALL" projects as "Debug / Release" mode
8) add "install folder" to PATH ( Environment Variables )

*) Build OPENCV with cmake but But tesseract is not .... ( Picture above )

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/3636

**Comment by sturkmen72** [comment]
take a look at https://answers.opencv.org/question/171470/opencv-ocrtesseractcreate-v305/

**Comment by md3848** [comment]
Opencv does not seem to have a problem with tesseract 4.1.3
According to what I understood from the link above.

How can I use version 4.1.3 in this method [[Develop Tesseract](https://github.com/tesseract-ocr/tessdoc/blob/main/Compiling.md#develop-tesseract)]? Instead of the latest version?

This code downloads the latest version [5.0.0]
`git clone https://github.com/tesseract-ocr/tesseract tesseract`
To download version 4.1.3, I used this code:
`git clone --branch 4.1.3 https://github.com/tesseract-ocr/tesseract tesseract`
When I run this code "cmake ..", it shows the following error:

> CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPkgConfig.cmake:592 (message):
  A required package was not found
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.22/Modules/FindPkgConfig.cmake:814 (_pkg_check_modules_internal)
  CMakeLists.txt:221 (pkg_check_modules)

cmd full code : [cmd.txt](https://github.com/tesseract-ocr/tesseract/files/7623379/cmd.txt)
