### ISSUE TITLE
Failed loading multiple languages

### ISSUE THREAD

**Issue by PassionPenguin** [tesseract-ocr/tesseract#3676]
## Environment

* **Tesseract Version**: 
```su
tesseract --version
tesseract v5.0.0-rc1.20211030
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0
```
* **Commit Number**: latest, via chocolatey
* **Platform**: Windows 10 64bit build 21H2

### Current Behavior:

Correct for individual language, but failed loading multiple languages, same in ocrmypdf.

### Expected Behavior:

Multiple languages should be taken into consideration

### Screenshot

![image](https://user-images.githubusercontent.com/41184947/145622571-2dc380f1-55c8-46f1-a5a7-24ba464b4d49.png)

**Comment by stweil** [comment]
Please use the latest stable release 5.0.0.

**Comment by stweil** [comment]
This was already reported in issue #3635.
