### ISSUE TITLE
tesseract adding new line in arabic prediction

### ISSUE THREAD

**Issue by Haider-Ali-DS** [tesseract-ocr/tesseract#3677]
### Environment: Linux

* **Tesseract Version**: 4.1.1
* **Platform**:l inux 

### Current Behavior:
i have an arabic image which have a word  سام احمر it reads it as  ام احمر\nسام 
### Expected Behavior:
it should read it as سام احمر why is it including new line space in between character?
### Suggested Fix:
any suggestion or tips?

**Comment by amitdo** [comment]
Please attach the image and the hocr output.

**Comment by amitdo** [comment]
No feedback from the OP.
