### ISSUE TITLE
strngs.h replacement ?

### ISSUE THREAD

**Issue by HJarausch** [tesseract-ocr/tesseract#3687]
### Environment

* **Tesseract Version**: 5.0.0
* **Commit Number**: 
* **Platform**: Gentoo AMD64

**Comment by stweil** [comment]
That file was used for a proprietary string class which is no longer supported by release 5. Please update your software and use `char *`, `std::string`or whatever fits best to your needs.

**Comment by stweil** [comment]
gImageReader was already updated for release 5 in January, see https://github.com/manisandro/gImageReader/commit/399f5503f88af423ada70cc903a19bdee5e096e8.

**Comment by HJarausch** [comment]
Vielen Dank, Stefan
