### ISSUE TITLE
Does not recognise file with transparent background

### ISSUE THREAD

**Issue by nmondal** [tesseract-ocr/tesseract#369]
Hi,
I just found out it can not read from a file having transparent background!
![join](https://cloud.githubusercontent.com/assets/1222935/16919086/f631ea6a-4d25-11e6-99b1-0008f53daadb.jpg)
![join](https://cloud.githubusercontent.com/assets/1222935/16919087/f687b788-4d25-11e6-8351-8d372aea2448.png)

See yourself!
When I use the png with transparent background, it fails.
Using the same JPG file, it runs beautifully.

**Comment by jbreiden** [comment]
If you think that's exciting, check out the PDF output. Looks like we have at least one bug on our hands. Thanks for reporting this.

[foo.pdf](https://github.com/tesseract-ocr/tesseract/files/369763/foo.pdf)

**Comment by jbreiden** [comment]
This will take care of the PDF portion (so that we blend with white instead of just stripping the entire alpha channel). The recognition part is probably a discussion with Ray. Reading the source code, it is not clear to me why we don't recognize. Alpha looks like it is treated like any other color channel as opposed to something special.

```c++
--- tesseract/api/pdfrenderer.cpp	2016-07-06 13:19:57.000000000 -0700
+++ tesseract/api/pdfrenderer.cpp	2016-07-20 16:23:13.000000000 -0700
@@ -690,8 +690,9 @@
   int format, sad;
   findFileFormat(filename, &format);
   if (pixGetSpp(pix) == 4 && format == IFF_PNG) {
-    pixSetSpp(pix, 3);
-    sad = pixGenerateCIData(pix, L_FLATE_ENCODE, 0, 0, &cid);
+    Pix *p1 = pixAlphaBlendUniform(pix, 0xffffff00);
+    sad = pixGenerateCIData(p1, L_FLATE_ENCODE, 0, 0, &cid);
+    pixDestroy(&p1);
   } else {
     sad = l_generateCIDataForPdf(filename, pix, kJpegQuality, &cid);
   }
```
