### ISSUE TITLE
Feature Request: Add a way to set the traineddata file from memory in the C API

### ISSUE THREAD

**Issue by nico-abram** [tesseract-ocr/tesseract#3691]
I found a constructor in the C++ API that takes a pair of ptr, size arguments for the training data, but none for the C API. It would be nice to have one in the C API.

**Comment by amitdo** [comment]
I found a constructor in the C++ API that takes a pair of ptr, size arguments for the training data

In which file? If it's not in one of the files in the `include/tesseract` directory, it is not part of the API.

The training methods are not part of the API.

**Comment by nico-abram** [comment]
In include/tesseract/basepi.h

https://github.com/tesseract-ocr/tesseract/blob/706d3bac62954212e5236d91b3bff8e91cf7a3cc/include/tesseract/baseapi.h#L218-L224

**Comment by amitdo** [comment]
OK. now I understand.
