### ISSUE TITLE
OCR displaying wrong numbers in very simple cases

### ISSUE THREAD

**Issue by SHA65536** [tesseract-ocr/tesseract#3696]
### Environment

* **Tesseract Version**: tesseract v5.0.0.20211201
* **Platform**: Windows 64

### Current Behavior:
Using `tesseract example.png stdout --psm 10 --oem 3`
With image being
![](https://i.ibb.co/8XnCRGQ/example.png)
Returns "3)"

I tried using all the different psm's and oem's, and playing with the DPI doesn't seem to help

### Expected Behavior:
Should return "5"

### Suggested Fix:
No idea why it returns 3, the 5 is really clear, well contrasted and legible

**Comment by stweil** [comment]
The image gives `=` with some page segmentation modes in my test. The inverted image gives the correct result with `--psm 7` and `--psm 10`.

**Comment by zdenop** [comment]
Seems like somebody forget to read the [docs](https://github.com/tesseract-ocr/tessdoc/blob/main/ImproveQuality.md) before posting issue:

```
> tesseract prepocessed_i3696.png - --psm 10 --oem 3
5
```
