### ISSUE TITLE
In Chinese, the digital recognition rate is very low

### ISSUE THREAD

**Issue by pigzee** [tesseract-ocr/tesseract#370]
please， the digital accuracy rate is ok，about 90%， how to train can improve the digital accuracy rate（30%）？thank you！

**Comment by amitdo** [comment]
Please read this:
https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md

Try asking your question in the [users mailing-list](https://groups.google.com/d/forum/tesseract-ocr)
