### ISSUE TITLE
how to compile 5.0 in windows ?

### ISSUE THREAD

**Issue by tuteming** [tesseract-ocr/tesseract#3701]
vcpkg install tesseract:x64-windows for 64-bit. Use –head for the master branch.

is not 5.0, is 4.1.

can update this command?

**Comment by Shreeshrii** [comment]
See the workflow https://github.com/tesseract-ocr/tesseract/blob/main/.github/workflows/vcpkg.yml for how to build the main branch for the latest 5.0 code.

See Log file for details - https://github.com/tesseract-ocr/tesseract/runs/4676352073?check_suite_focus=true

```
1s
Run D:\a\tesseract\tesseract\build\bin\Release\tesseract.exe --version
tesseract 5.0.0
 leptonica-1.81.1 (Dec 31 2021, 23:08:42) [MSC v.1929 LIB Release x64]
  libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.1.2) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.1
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
```

**Comment by tuteming** [comment]
thanks. but, I do not know
- name: Configure and Build Tesseract (--head from main branch) with cmake
        run: |
             cmake . -B build -DCMAKE_BUILD_TYPE=Release -DSW_BUILD=OFF -DOPENMP_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF "-DCMAKE_TOOLCHAIN_FILE=${env:GITHUB_WORKSPACE}/vcpkg/scripts/buildsystems/vcpkg.cmake"
             cmake --build build --config Release --target install

can explain more detail? very thanks

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
