### ISSUE TITLE
about compile 5.0 in win10 again

### ISSUE THREAD

**Issue by tuteming** [tesseract-ocr/tesseract#3703]
Shreeshrii, very thanks for your help.
I have been compile sucessful.
but by:
cmake . -B build -DCMAKE_BUILD_TYPE=Release -DSW_BUILD=OFF -DOPENMP_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF "-DCMAKE_TOOLCHAIN_FILE=${env:GITHUB_WORKSPACE}/vcpkg/scripts/buildsystems/vcpkg.cmake"
cmake --build build --config Release --target install

I obtained tesseract.exe and tesseract50.lib, but no tesseract50.dll.
How can obtain dll, Thanks.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/3701#issuecomment-1003528186
