### ISSUE TITLE
MacOS brew version 4.1.x has been overwritten

### ISSUE THREAD

**Issue by JohnDuncanScott** [tesseract-ocr/tesseract#3711]
### Environment

* **Tesseract Version**: 4.1.x
* **Platform**: Mac

### Current Behavior:
I'm not sure where to log this issue, but this seemed the most sensible. Apologies if this is the wrong place.
- Multiple libraries depend on tesseract, SikuliX in this case
- 5.0.0 has breaking changes meaning a user cannot simply just use the latest version
- For Mac specifically, you must use a package manager to install tesseract (either MacPort or Brew)
- Having 2 package managers installed on the same Mac is not recommended at all and error prone
- Brew, from various discussions on StackOverflow, does not really support using specific commits when installing packages. It might work, but is not recommended and is not easy to do
- Brew does support having fixed versions, e.g. postgresql@11 (found via brew search postgresql)
- The version in brew has just been overwritten rather than using the brew versioning. This means the latest version in brew is 5.0.0, getting 4.1.x back requires going to a specific commit, which as stated above may cause issues

### Expected Behavior:
- Run brew install tesseract@4.1.3

### Suggested Fix:
- Upload 4.1.x to brew as a different version (this is probably the easier route)
- Alternatively update the tesseract documentation to specify how to get a previous version easily that has been tested to make sure it works

**Comment by stweil** [comment]
This is indeed the wrong place for your report. https://github.com/Homebrew/homebrew-core/issues might be the right one.

**Comment by stweil** [comment]
Regarding versions: there is no really good reason to install both Tesseract 4.1 and Tesseract 5. Packages / software which used the old version should be updated to use Tesseract 5.

**Comment by JohnDuncanScott** [comment]
I can understand not being able to have both installed simultaneously, but ultimately it will take a while for those packages to get up to date as presumably they would test the impact first, so it will take a while. But appreciate the help, thanks :).
