### ISSUE TITLE
MFtraining failed

### ISSUE THREAD

**Issue by vkoushik** [tesseract-ocr/tesseract#372]
Hello,

tesseract v3.05
ubuntu v15

I've created the .box and .tr files and i am in the step of mftraining. Since the number of  .tr files are large,i performed a ls command,stored the result to a variable and gave the variable to the mftraining command as shown in the screenshot.Then i executed the .sh file in the terminal and i got an error stating illegal malloc request size as shown in the screenshot.

As shown in the screenshot, the error seems to point to the program globalloc.cpp.

Is there a limit on the number of .tr files i can give as input?
![screen shot 2016-07-18 at 9 30 44 pm](https://cloud.githubusercontent.com/assets/18536586/16947703/7725aef4-4da8-11e6-81a3-02fe7ca0afa4.png)
![screen shot 2016-07-18 at 9 28 04 pm](https://cloud.githubusercontent.com/assets/18536586/16947721/888deed6-4da8-11e6-9d3e-c73d575a0cdb.png)

Can some one please help me with this issue?

Thank you

**Comment by Shreeshrii** [comment]
see https://groups.google.com/forum/#!msg/tesseract-ocr/eQ6HQdVE7Cw/3o1XPn2Q0CkJ

search forum and google for the error and possible solutions

**Comment by vkoushik** [comment]
The error in the link is different from mine. I've followed the guide and i've given -O eng.unicharset properly. The difference in my case is multiple .tr files

**Comment by amitdo** [comment]
There is a limit for the number of **fonts** you can train Tesseract, which is 64 fonts.

**Comment by vkoushik** [comment]
No actually the problem was with the unicharset file.Because there were number of unicharset files such as unicharset,eng.unicharset,output_unicharset, it was unknown which one to use. Hence, i started again from the first and used the other file and it worked.I was able to create the eng.trainedata successfully.

**Comment by amitdo** [comment]
This was a reply to your question:
>Is there a limit on the number of .tr files i can give as input?

AFAIK, there is no hard limit on the number of `.tr` files.

**Comment by vkoushik** [comment]
The total count of fonts i gave was 70

**Comment by amitdo** [comment]
Did you test that your training data actually work?

**Comment by vkoushik** [comment]
I am not sure.This is what i am getting
![screen shot 2016-07-19 at 6 50 37 pm](https://cloud.githubusercontent.com/assets/18536586/16983034/d3fde502-4e6a-11e6-91f6-45ce77b284bd.png)

**Comment by amitdo** [comment]
This output does not look like it is coming from Tesseract command line program...

In any case, as I said there is a 64 fonts limit.

**Comment by vkoushik** [comment]
No this is from a c++ program. The output from command line is a file named output with a black blank page.So, your saying there is a implicit limit 64 in tesseract is it?

**Comment by amitdo** [comment]
From Ray Smith DAS2014 Slides:

>Training Fundamentals
>● Character samples must be segregated by font
> => Trained on synthetic (rendered, distorted) data
>● Few samples required (4-10 of each combination is good. 1 is OK)
>● Not many fonts required. (32 used for Latin)
>● Not many fonts allowed. (MAX_NUM_CONFIGS=64: Long story.)
>● Number of different “characters” now limited only by memory.

**Comment by vkoushik** [comment]
oh ok thank you

**Comment by amitdo** [comment]
From Ray Smith DAS2014 slides:

Training Fundamentals
● Character samples must be segregated by font
=> Trained on synthetic (rendered, distorted) data
● Few samples required (4-10 of each combination is good. 1 is OK)
● Not many fonts required. (32 used for Latin)
● Not many fonts allowed. (MAX_NUM_CONFIGS: Long story.)
● Number of different “characters” now limited only by memory.

The `MAX_NUM_CONFIGS` is still `64` in the current codebase.
