### ISSUE TITLE
api question

### ISSUE THREAD

**Issue by tuteming** [tesseract-ocr/tesseract#3725]
I compile 5.01 in win10, basic test is ok. But test Sintun's tableExtractionDemo.cpp, 
I get
no member named 'GetNumberOfTables' in 'tesseract::TessBaseAPI'
no member named 'GetTableBoundingBox' in 'tesseract::TessBaseAPI'
no member named 'GetTableRows' in 'tesseract::TessBaseAPI'
no member named 'GetTableCols' in 'tesseract::TessBaseAPI'

finally, I check baseapi.h (5.01) with Sintun's baseapi.h, I found those funs have been omit.
Please advise how to solve this problem?

thanks

**Comment by amitdo** [comment]
Please don't ask questions here. It's not the right place. We [already told you](https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+author%3Atuteming+is%3Aclosed) to use our forum for asking qustions. Please respect our policy.
