### ISSUE TITLE
Tesseract not working for images such as meter reading snapshot

### ISSUE THREAD

**Issue by salmanwaseem007** [tesseract-ocr/tesseract#3726]
tesseract not working for images such as meter reading snapshot

I have tried grayscaling the image but it doesn't work

------------------------
![1](https://user-images.githubusercontent.com/49980019/149953516-ba19006d-0efd-4349-a146-7b419b90fc61.jpeg)

### Environment

* **Tesseract Version**: tesseract-ocr-w64-setup-v5.0.1.20220107
* tess4j Version**: 5.1.0
* Java 8, spring boot 2.6.2
* **Commit Number**: 
* **Platform**: Windows 10

### Current Behavior:

Current output

ASE Ri
crams, set

| ‘
PRT

| G4 AS5022406 06 012006

**Comment by stweil** [comment]
Tesseract was not designed for reading meters. You will have to preprocess such images yourself and ideally extract the relevant parts of the image before handling it with Tesseract.

**Comment by wollmers** [comment]
@salmanwaseem007 

Images with mixed background areas do not work well. If we cut out the line with the meter (white text on dark background), then it works perfect in single line mode:

![meter_cut](https://user-images.githubusercontent.com/1275557/150095812-495ed65d-4213-4e64-82f0-667a8b6f7b6f.png)

```
$ tesseract meter_cut.png - --psm 7 --tessdata-dir  /usr/local/share/tessdata
0589347 3
```
