### ISSUE TITLE
Arabic language : Results from tesseract differ from results from PyTesseract 

### ISSUE THREAD

**Issue by larawehbe** [tesseract-ocr/tesseract#3727]
Hi 

OS : Ubuntu 20.04 
Tesseract version: 
tesseract 5.0.1
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4
 Found libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Pytesseract version : 0.3.8
python version: 3.8.10

Results from tesseract are different from those of pytesseract

Results of tesseract  with default psm 3 : 
Empty page !!

Results from tesseract with psm 6 : 
اثراكر بلد ف الفالم و الأولى إثريفيا وعزبا
و تلقب بيلد الليون و نصف مليون شهيد.

Results from pytesseract with default psm 3 : 
  الزائر مي دولة تت في شمال آدرقيا ومي
عاشركير بلد في العالم و الآولى إفريقيا و عربيا
و تلقب بجلد الملبون و نصف ملبون شهید

Any idea how to fix this issue ?
Thanks in advance !

**Comment by stweil** [comment]
Isn't that the same as https://github.com/tesseract-ocr/tessdata_best/issues/67?

**Comment by larawehbe** [comment]
@stweil  yes it is the same as the comment but not the same issue
thats why i opened it in a new issue because now its tesseract/pytesseract issue and not os one

**Comment by amitdo** [comment]
@larawehbe, please attach the original image used as input to tesseract.

**Comment by amitdo** [comment]
See also: https://github.com/madmaze/pytesseract/issues/404.

**Comment by amitdo** [comment]
No response from the OP.
