### ISSUE TITLE
5.0.1 fails trying to link neon on armv7hl package build for Mageia cauldron

### ISSUE THREAD

**Issue by barjac** [tesseract-ocr/tesseract#3728]
Our builds of 5.0.1 for x86_64, i586 and aarch64 all complete without issue but we hit this on armv7hl.

Build log is here:
[buildlog.txt](https://github.com/tesseract-ocr/tesseract/files/7915526/buildlog.txt)

Any help would be appreciated,
Thanks

**Comment by barjac** [comment]
We have not seen this with earlier versions, however the last we packaged was 4.1.3.

I have tested an armv7hl build using current git main (31a9684) and the error is the same.
[build.log](https://github.com/tesseract-ocr/tesseract/files/7918655/build.log)

Our compiler supports neon, but armv7hl does not. We suspect some Makefile logic is perhaps not coping with this scenario correctly.

**Comment by stweil** [comment]
Tesseract currently assumes NEON support if either it is an `aarch64` host cpu or if the compiler support `-mfpu=neon`. The code is in `configure.ac`, so perhaps you can send a pull request which fixes those checks for your case.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/d9f232aef615f2a45fe5aa13bca5d3ee57b26972/configure.ac#L173-L181


https://github.com/tesseract-ocr/tesseract/blob/5884036ecdb2807419cbd21b7ca44b630f547d80/Makefile.am#L179-L191

**Comment by amitdo** [comment]
>Our compiler supports neon, but armv7hl does not.

Some armv7hl based CPUs supports Neon.

**Comment by stweil** [comment]
Then Tesseract should be compiled with NEON support (which normally is done automatically). The NEON code won't be used when Tesseract does not detect NEON support at runtime.

**Comment by amitdo** [comment]
The fault of the compile time error seem to be the manual use of `-mfpu=vfpv3-d16`. This clashes with what Tesseract is trying to do with armv7hf.

**Comment by barjac** [comment]
> The cause of the link time error seem to be the manual use of `-mfpu=vfpv3-d16`. This clashes with what Tesseract is trying to do with armv7hf.

Yes, a build for armv7hl without our default flags is OK, so this is our problem.
Thanks for looking into this and pointing out the cause.
