### ISSUE TITLE
Tesseract training for RTL language

### ISSUE THREAD

**Issue by sameearif88** [tesseract-ocr/tesseract#3730]
Issue: Characters change on reversing the text
Groundtruth: عَلیٰ عَبْدِہٖ الْکِتَاب
Reversed groundtruth: ۔ باَتِکْلا ٖہِدْبَع ٰیلَع

For RTL language training we have to reverse the groundtruth but characters change because of this.
عَ becomes ع after reversing the string so if we make unicharset file from .box file it won't include عَ which is the original character. Won't this affect the accuracy of the OCR? Is there a solution to fix this issue? Can we flip the image instead of reversing the groundtruth?

**Comment by wollmers** [comment]
The codepoints do not change (except ARABIC FULL STOP), they are just reversed:

```
$ uni identify عَلیٰ عَبْدِہٖ الْکِتَاب
     cpoint  dec    utf-8       html       name
'ع'  U+0639  1593   d8 b9       &#x639;    ARABIC LETTER AIN (Other_Letter)
'◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
'ل'  U+0644  1604   d9 84       &#x644;    ARABIC LETTER LAM (Other_Letter)
'ی'  U+06CC  1740   db 8c       &#x6cc;    ARABIC LETTER FARSI YEH (Other_Letter)
'◌ٰ'  U+0670  1648   d9 b0       &#x670;    ARABIC LETTER SUPERSCRIPT ALEF (Nonspacing_Mark)
'ع'  U+0639  1593   d8 b9       &#x639;    ARABIC LETTER AIN (Other_Letter)
'◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
'ب'  U+0628  1576   d8 a8       &#x628;    ARABIC LETTER BEH (Other_Letter)
'◌ْ'  U+0652  1618   d9 92       &#x652;    ARABIC SUKUN (Nonspacing_Mark)
'د'  U+062F  1583   d8 af       &#x62f;    ARABIC LETTER DAL (Other_Letter)
'◌ِ'  U+0650  1616   d9 90       &#x650;    ARABIC KASRA (Nonspacing_Mark)
'ہ'  U+06C1  1729   db 81       &#x6c1;    ARABIC LETTER HEH GOAL (Other_Letter)
'◌ٖ'  U+0656  1622   d9 96       &#x656;    ARABIC SUBSCRIPT ALEF (Nonspacing_Mark)
'ا'  U+0627  1575   d8 a7       &#x627;    ARABIC LETTER ALEF (Other_Letter)
'ل'  U+0644  1604   d9 84       &#x644;    ARABIC LETTER LAM (Other_Letter)
'◌ْ'  U+0652  1618   d9 92       &#x652;    ARABIC SUKUN (Nonspacing_Mark)
'ک'  U+06A9  1705   da a9       &#x6a9;    ARABIC LETTER KEHEH (Other_Letter)
'◌ِ'  U+0650  1616   d9 90       &#x650;    ARABIC KASRA (Nonspacing_Mark)
'ت'  U+062A  1578   d8 aa       &#x62a;    ARABIC LETTER TEH (Other_Letter)
'◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
'ا'  U+0627  1575   d8 a7       &#x627;    ARABIC LETTER ALEF (Other_Letter)
'ب'  U+0628  1576   d8 a8       &#x628;    ARABIC LETTER BEH (Other_Letter)

$ uni identify ۔ باَتِکْلا ٖہِدْبَع ٰیلَع
     cpoint  dec    utf-8       html       name
'۔'  U+06D4  1748   db 94       &#x6d4;    ARABIC FULL STOP (Other_Punctuation)
'ب'  U+0628  1576   d8 a8       &#x628;    ARABIC LETTER BEH (Other_Letter)
'ا'  U+0627  1575   d8 a7       &#x627;    ARABIC LETTER ALEF (Other_Letter)
'◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
'ت'  U+062A  1578   d8 aa       &#x62a;    ARABIC LETTER TEH (Other_Letter)
'◌ِ'  U+0650  1616   d9 90       &#x650;    ARABIC KASRA (Nonspacing_Mark)
'ک'  U+06A9  1705   da a9       &#x6a9;    ARABIC LETTER KEHEH (Other_Letter)
'◌ْ'  U+0652  1618   d9 92       &#x652;    ARABIC SUKUN (Nonspacing_Mark)
'ل'  U+0644  1604   d9 84       &#x644;    ARABIC LETTER LAM (Other_Letter)
'ا'  U+0627  1575   d8 a7       &#x627;    ARABIC LETTER ALEF (Other_Letter)
'◌ٖ'  U+0656  1622   d9 96       &#x656;    ARABIC SUBSCRIPT ALEF (Nonspacing_Mark)
'ہ'  U+06C1  1729   db 81       &#x6c1;    ARABIC LETTER HEH GOAL (Other_Letter)
'◌ِ'  U+0650  1616   d9 90       &#x650;    ARABIC KASRA (Nonspacing_Mark)
'د'  U+062F  1583   d8 af       &#x62f;    ARABIC LETTER DAL (Other_Letter)
'◌ْ'  U+0652  1618   d9 92       &#x652;    ARABIC SUKUN (Nonspacing_Mark)
'ب'  U+0628  1576   d8 a8       &#x628;    ARABIC LETTER BEH (Other_Letter)
'◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
'ع'  U+0639  1593   d8 b9       &#x639;    ARABIC LETTER AIN (Other_Letter)
'◌ٰ'  U+0670  1648   d9 b0       &#x670;    ARABIC LETTER SUPERSCRIPT ALEF (Nonspacing_Mark)
'ی'  U+06CC  1740   db 8c       &#x6cc;    ARABIC LETTER FARSI YEH (Other_Letter)
'ل'  U+0644  1604   d9 84       &#x644;    ARABIC LETTER LAM (Other_Letter)
'◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
'ع'  U+0639  1593   d8 b9       &#x639;    ARABIC LETTER AIN (Other_Letter)
```

If the training images are rendered from the groundtruth, then the images should be correct.

If it is rendered from the reversed groundtruth, then e.g. the combining ARABIC FATHA is applied to LAM and not AIN.

IMHO it's a problem of the scripts in the workflow to do it correct. Maybe the .box file is incorrect. One way would be, to reverse at grapheme level, e.g. in Perl:

```
use utf8;

  my @graphemes = $groundtruth =~ m/(\X)/g;

  my $groundtruth_reversed = join('', reverse(@graphemes));
```

All components handling text should work in grapheme logic, as graphemes represent glyphs in all writing systems.

But AFAIK Arabic has context shaping, i.e. the shape of glyphs is different for begin-, middle- and end-positions. And there is also BIDI, i.e. RTL and LTR can me mixed in one line.

**Comment by sameearif88** [comment]
> The codepoints do not change (except ARABIC FULL STOP), they are just reversed:
> 
> ```
> $ uni identify عَلیٰ عَبْدِہٖ الْکِتَاب
>      cpoint  dec    utf-8       html       name
> 'ع'  U+0639  1593   d8 b9       &#x639;    ARABIC LETTER AIN (Other_Letter)
> '◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
> 'ل'  U+0644  1604   d9 84       &#x644;    ARABIC LETTER LAM (Other_Letter)
> 'ی'  U+06CC  1740   db 8c       &#x6cc;    ARABIC LETTER FARSI YEH (Other_Letter)
> '◌ٰ'  U+0670  1648   d9 b0       &#x670;    ARABIC LETTER SUPERSCRIPT ALEF (Nonspacing_Mark)
> 'ع'  U+0639  1593   d8 b9       &#x639;    ARABIC LETTER AIN (Other_Letter)
> '◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
> 'ب'  U+0628  1576   d8 a8       &#x628;    ARABIC LETTER BEH (Other_Letter)
> '◌ْ'  U+0652  1618   d9 92       &#x652;    ARABIC SUKUN (Nonspacing_Mark)
> 'د'  U+062F  1583   d8 af       &#x62f;    ARABIC LETTER DAL (Other_Letter)
> '◌ِ'  U+0650  1616   d9 90       &#x650;    ARABIC KASRA (Nonspacing_Mark)
> 'ہ'  U+06C1  1729   db 81       &#x6c1;    ARABIC LETTER HEH GOAL (Other_Letter)
> '◌ٖ'  U+0656  1622   d9 96       &#x656;    ARABIC SUBSCRIPT ALEF (Nonspacing_Mark)
> 'ا'  U+0627  1575   d8 a7       &#x627;    ARABIC LETTER ALEF (Other_Letter)
> 'ل'  U+0644  1604   d9 84       &#x644;    ARABIC LETTER LAM (Other_Letter)
> '◌ْ'  U+0652  1618   d9 92       &#x652;    ARABIC SUKUN (Nonspacing_Mark)
> 'ک'  U+06A9  1705   da a9       &#x6a9;    ARABIC LETTER KEHEH (Other_Letter)
> '◌ِ'  U+0650  1616   d9 90       &#x650;    ARABIC KASRA (Nonspacing_Mark)
> 'ت'  U+062A  1578   d8 aa       &#x62a;    ARABIC LETTER TEH (Other_Letter)
> '◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
> 'ا'  U+0627  1575   d8 a7       &#x627;    ARABIC LETTER ALEF (Other_Letter)
> 'ب'  U+0628  1576   d8 a8       &#x628;    ARABIC LETTER BEH (Other_Letter)
> 
> $ uni identify ۔ باَتِکْلا ٖہِدْبَع ٰیلَع
>      cpoint  dec    utf-8       html       name
> '۔'  U+06D4  1748   db 94       &#x6d4;    ARABIC FULL STOP (Other_Punctuation)
> 'ب'  U+0628  1576   d8 a8       &#x628;    ARABIC LETTER BEH (Other_Letter)
> 'ا'  U+0627  1575   d8 a7       &#x627;    ARABIC LETTER ALEF (Other_Letter)
> '◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
> 'ت'  U+062A  1578   d8 aa       &#x62a;    ARABIC LETTER TEH (Other_Letter)
> '◌ِ'  U+0650  1616   d9 90       &#x650;    ARABIC KASRA (Nonspacing_Mark)
> 'ک'  U+06A9  1705   da a9       &#x6a9;    ARABIC LETTER KEHEH (Other_Letter)
> '◌ْ'  U+0652  1618   d9 92       &#x652;    ARABIC SUKUN (Nonspacing_Mark)
> 'ل'  U+0644  1604   d9 84       &#x644;    ARABIC LETTER LAM (Other_Letter)
> 'ا'  U+0627  1575   d8 a7       &#x627;    ARABIC LETTER ALEF (Other_Letter)
> '◌ٖ'  U+0656  1622   d9 96       &#x656;    ARABIC SUBSCRIPT ALEF (Nonspacing_Mark)
> 'ہ'  U+06C1  1729   db 81       &#x6c1;    ARABIC LETTER HEH GOAL (Other_Letter)
> '◌ِ'  U+0650  1616   d9 90       &#x650;    ARABIC KASRA (Nonspacing_Mark)
> 'د'  U+062F  1583   d8 af       &#x62f;    ARABIC LETTER DAL (Other_Letter)
> '◌ْ'  U+0652  1618   d9 92       &#x652;    ARABIC SUKUN (Nonspacing_Mark)
> 'ب'  U+0628  1576   d8 a8       &#x628;    ARABIC LETTER BEH (Other_Letter)
> '◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
> 'ع'  U+0639  1593   d8 b9       &#x639;    ARABIC LETTER AIN (Other_Letter)
> '◌ٰ'  U+0670  1648   d9 b0       &#x670;    ARABIC LETTER SUPERSCRIPT ALEF (Nonspacing_Mark)
> 'ی'  U+06CC  1740   db 8c       &#x6cc;    ARABIC LETTER FARSI YEH (Other_Letter)
> 'ل'  U+0644  1604   d9 84       &#x644;    ARABIC LETTER LAM (Other_Letter)
> '◌َ'  U+064E  1614   d9 8e       &#x64e;    ARABIC FATHA (Nonspacing_Mark)
> 'ع'  U+0639  1593   d8 b9       &#x639;    ARABIC LETTER AIN (Other_Letter)
> ```
> 
> If the training images are rendered from the groundtruth, then the images should be correct.
> 
> If it is rendered from the reversed groundtruth, then e.g. the combining ARABIC FATHA is applied to LAM and not AIN.
> 
> IMHO it's a problem of the scripts in the workflow to do it correct. Maybe the .box file is incorrect. One way would be, to reverse at grapheme level, e.g. in Perl:
> 
> ```
> use utf8;
> 
>   my @graphemes = $groundtruth =~ m/(\X)/g;
> 
>   my $groundtruth_reversed = join('', reverse(@graphemes));
> ```
> 
> All components handling text should work in grapheme logic, as graphemes represent glyphs in all writing systems.
> 
> But AFAIK Arabic has context shaping, i.e. the shapes of glyphs are different for begin-, middle- and end-positions. And there is also BIDI, i.e. RTL and LTR can me mixed in one line.

Thankyou! The perl script works for me.
