### ISSUE TITLE
Build with IronOCR(Tesseract 5 engine) on Unity fails

### ISSUE THREAD

**Issue by suzyrhkr** [tesseract-ocr/tesseract#3731]
**Tesseract Version**: latest Tesseract 5 engine
**Platform**: Mac OS 11.5.2

I want to apply IronOCR for my Unity project and I just installed IronOcr.2022.1.0 using NuGet, but some build errors exist shown as below.

<img width="1083" alt="Screenshot 2022-01-24 at 1 56 37 PM" src="https://user-images.githubusercontent.com/48341349/150724361-9c65142e-135a-4e7b-b959-a7d5e2c0ea86.png">

Is there any solution to use ironOCR on unity?
Any help would be appreciated. 

Thanks

**Comment by zdenop** [comment]
Please respect guidelines for posting issues: we do not provide support for 3rd party projects.
Reproduce your problem with recent version of the tesseract executable and provide an input image for reproducing the error.
