### ISSUE TITLE
Russian language: missing spaces when creating a searchable pdf

### ISSUE THREAD

**Issue by VladimirRIR** [tesseract-ocr/tesseract#3733]
Hello 

OS : Winodws (any ver)
Tesseract version: 4 as part of the "Syncfusion Suit" 
leptonica-leptonica-1.80.0
C#, Net FrameWork Version 4.0

Sorry for my basic Englis.

I use Tesseract as part of the "Syncfusion Suit". But they use Tesseract inside the project.

When creating a searchable pdf:
1. Scans of documents in Russian (jpg format)
2. Create PDF
3. OCR and save searchable pdf

The text is copied in the viewer programs (Adobe Reader, PDF X-Change Viewer) with missing spaces.

**Example of copied (missing spaces):** Рассмотрев учредительныедокументы,прёедставленныедля
**Mast be:** Рассмотрев учредительные документы, прёедставленные для

But, if extract the text layer from the pdf, the spaces are all in the right place.

[Examples of problems and correspondence with a Syncfusion  representative](https://www.syncfusion.com/forums/172092/ocr-pdf-the-text-is-copied-without-spaces)

The final message of the Syncfusion  specialist:
_On further analysis, we found the reported space image problem occurs in Google tesseract engine result from itself with Russian language with a provided image. Internally, we are using the Google tesseract engine to OCR image and render OCR text content into the PDF document_

**Comment by Shreeshrii** [comment]
Similar issue https://github.com/tesseract-ocr/tesseract/issues/2127

**Comment by Shreeshrii** [comment]
Also see https://github.com/tesseract-ocr/tesseract/issues/1900

**Comment by amitdo** [comment]
You provided the output, but didn't provide the original input image. 

Try to test Tesseract **5.0.1** with the official command line tool. We do not support third party tools.

Also test other pdf viewers like the build in Chrome pdf viewer.

**Comment by VladimirRIR** [comment]
Thank you very much. Excuse for troubling
