### ISSUE TITLE
Tesseract Training correction suggestions

### ISSUE THREAD

**Issue by vkoushik** [tesseract-ocr/tesseract#374]
Hi,

I was able to successfully train tessdata today after many issues and i would like to suggest some changes that can be added to the training guide

1. the command : unicharset_extractor lang.fontname.exp0.box lang.fontname.exp1.box ... didn't work the first tim.Hence, i have to prefix training/ to make it work.

2. the command: mftraining -F font_properties -U unicharset -O lang.unicharset lang.fontname.exp0.tr lang.fontname.exp1.tr ...
needs to be corrected to add suffix .txt to font_properties to make it work 

3. In the command: training/set_unicharset_properties -U input_unicharset -O output_unicharset --script_dir=training/langdata

The output is generated to output_unicharset.This output_unicharset should be given as input to the mftraining command. i.e instead of -U unicharset one should give -U output_unicharset

Thank you

**Comment by amitdo** [comment]
>the command: mftraining -F font_properties -U unicharset -O lang.unicharset lang.fontname.exp0.tr lang.fontname.exp1.tr ...
needs to be corrected to add suffix .txt to font_properties to make it work

It only needs the `.txt` suffix if you saved the file as `font_properties.txt`...

**Comment by amitdo** [comment]
>In the command: training/set_unicharset_properties -U input_unicharset -O output_unicharset --script_dir=training/langdata
The output is generated to output_unicharset.This output_unicharset should be given as input to the mftraining command. i.e instead of -U unicharset one should give -U output_unicharset

From the training guide:
```
mftraining -F font_properties -U unicharset -O lang.unicharset lang.fontname.exp0.tr lang.fontname.exp1.tr ...
```

This give you the command line usage. You don't supposed to cut and paste it as-is.

The following paragraph explains it.
>The -U file is the unicharset generated by unicharset_extractor above, and lang.unicharset is the output unicharset that will be given to combine_tessdata.

**Comment by vkoushik** [comment]
yes in the unicharset extractor command, two files are generated: unicharset and output_unicharset. I tried with output_unicharset and generated eng.unicharset.I copied the all the files to the tessdata folder to recognize text. It is throwing an error stating unichar in normproto is not in unicharset. Then i used the file named  unicharset, it ran without error. So, i understand is output_unicharset and unicharset works with mftraining but the eng.unicharset generated from mftraining does not work with tesseract but unicharset works.

**Comment by amitdo** [comment]
>the command : unicharset_extractor lang.fontname.exp0.box lang.fontname.exp1.box ... didn't work the first tim.Hence, i have to prefix training/ to make it work.

https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#building-the-training-tools
```
make training
sudo make training-install
```

If you run the second line, you should be able to run all the training commands without the prefix.

**Comment by vkoushik** [comment]
Those are the first commands which have to be executed before i can use training. I did that and tried and it throwed me error.It is similar to other commands such training/text2image,training/set_unicharset_properties etc, this has to be prefixed with training/

**Comment by zdenop** [comment]
@vkoushik: if it throwed you error it means you made something wrong (installation). Fix your installation instead of  adjusting manual to your mistakes. Your suggestion would not work for those who use packaged prepared by their distributor (windows or linux).
