### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Pankajprakashj** [tesseract-ocr/tesseract#3741]
Hi Team,

While installing the tesseract-5.0.0 I am getting the below error.
Can you do the needful 

I am using the below GCC and CMake versions 

gcc -10.3.0
cmake -3.14.3

-----------------------------------------------

$ make
Making all in .
make[1]: Entering directory `/tessract/tesseract-5.0.0'
  CXX      src/api/libtesseract_la-baseapi.lo
src/api/baseapi.cpp:31:10: fatal error: environ.h: No such file or directory
   31 | #include "environ.h"    // for l_uint8
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [src/api/libtesseract_la-baseapi.lo] Error 1
make[1]: Leaving directory `/tessract/tesseract-5.0.0'
make: *** [all-recursive] Error 1

-----------------------------------------------

Thanks
Pankaj Jadhav

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
