### ISSUE TITLE
Build for arm64 under macOS Big Sur fails

### ISSUE THREAD

**Issue by B-Michel** [tesseract-ocr/tesseract#3746]
**Environment**
```tesseract 5.0.1
macOS Big Sur 11.6.3
MacBook Pro M1
Xcode 13.2.1
autoconf 2.69
automake 1.16
pkg-config 0.29.2
```
**Current Behavior:**
Building tesseract for arm64 arch fails with error message :
```
Undefined symbols for architecture arm64:
  "tesseract::IntSimdMatrix::intSimdMatrixNEON", referenced from:
      tesseract::SIMDDetect::SIMDDetect() in libtesseract.a(libtesseract_la-simddetect.o)
      tesseract::SIMDDetect::Update() in libtesseract.a(libtesseract_la-simddetect.o)
  "tesseract::DotProductNEON(float const*, float const*, int)", referenced from:
      tesseract::SIMDDetect::SIMDDetect() in libtesseract.a(libtesseract_la-simddetect.o)
      tesseract::SIMDDetect::Update() in libtesseract.a(libtesseract_la-simddetect.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [tesseract] Error 1
make: *** [all-recursive] Error 1
```
Under same environment,  build for x86_64 arch has no problem

**Comment by stweil** [comment]
Builds with `configure && make` work for me without any problem on Monterey. I am surprised that you are running Big Sur on a MacBook Pro M1. Please give a complete list of the commands which you used to get the build error.

**Comment by B-Michel** [comment]
Sorry, I was using a deprecated tesseract-build script.
Using the current official [https://github.com/pokkinandpup/TesseractBuild](url) works without problems.
Thank you

**Comment by stweil** [comment]
That's not the official Tesseract build procedure and not required if you just want to build `tesseract` for macOS.
