### ISSUE TITLE
API examples

### ISSUE THREAD

**Issue by clarkk** [tesseract-ocr/tesseract#3747]
Few years ago you could find some simple API examples. Where can I find som short and simple examples on how to use the latest API version?

Have looked in the documentation but didn't find any

It's very helpful to have some short use-cases of the API also to make sure you use the API in the way it was meant to be used

UPDATE:
There are API examples for version 4 but not for version 5
https://github.com/tesseract-ocr/tessdoc#api-examples

**Comment by zdenop** [comment]
Please respect guidelines for posting issues: use tesseract user forum for asking questions/support.

**Comment by clarkk** [comment]
I'm not asking for support but asking to update the documentation. Thats a big difference
