### ISSUE TITLE
Will there be a tesseract release for YakketyYak?

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#375]
@jbreiden @zdenop 

Are there any plans to make a release with the changes for https://wiki.ubuntu.com/YakketyYak/ReleaseSchedule

Maybe 3.04.02 ?

Thanks!

**Comment by zdenop** [comment]
This is not issue according https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md
