### ISSUE TITLE
[Feature Request] Add an option to Tesseract to use external cloud OCR APIs

### ISSUE THREAD

**Issue by All3xJ** [tesseract-ocr/tesseract#3754]
Tesseract is good for non-handwriting text, but it isn't accurate at all for handwritten text.
Websites like Google are very accurate. Is it possible to add the possibility to upload and do the OCR in external websites and then "paste" the results in the PDF to make text searchable like tesseract already does?

**Comment by stweil** [comment]
Your question is not related to Tesseract and would be better asked on the Tesseract user forum. But the answer is yes, it is possible to add searchable text to images or PDF files, no matter where this text comes from as long as there is also information on the text position (bounding boxes, baselines) available. Here is an example which has images and text transcriptions made with eScriptorium: http://nbn-resolving.de/urn:nbn:de:bsz:180-digad-31525.

**Comment by amitdo** [comment]
We can split this to two feature requests:
1) Make Tesseract able to use the API of some cloud OCR (from Amazon, Google, Microsoft).
2) Make Tesseract's PDF renderer able to read hOCR/ALTO format and use the data instead of running and using Tesseract own OCR engine.

**Comment by A327380104** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，邮件已收到，我尽快给您回复。             祝您工作顺利、身体健康！

**Comment by wollmers** [comment]
IMHO that's a workflow or utility problem, thus outside the scope of Tesseract.

There are still utilities creating searchable PDF from hOCR or other OCR markup formats. Maybe a ready to use convenience wrapper to combine results makes sense for some users. But this can and should be completely independent from Tesseract.

As I understand https://readcoop.eu/transkribus/?sc=Transkribus or similar other projects they still provide searchable PDFs for handwritten OCR. No need to reinvent the wheel.

**Comment by zdenop** [comment]
@All3xJ : so you should ask support at Google directly (and so on). 
How I read you request:
You ask opensource project to provide support for closed source project. You asked free project to provide free support for commercial (and  at the end of day paid) solution. This does not sound reasonable for me. I see no benefit for tesseract.

**Comment by wollmers** [comment]
@All3xJ 

> yeah but Transkribus has not the amount of data and informations given by AI that Google (and so on) has.

We even don't know, what Google, Amazon or Microsoft provides as "data and information", let alone in which format and if they provide an exact technical specification for this format. I tried to find out and found nothing (1 hour wasted time). 

You have the same problem that most contributors to Tesseract also have, as they are involved solving workflow problems of OCR in their professional life at universities, libraries or archives: If not available, develop it yourself.

Technically you have two alternatives:

- convert the results to the same data format, e.g. hOCR, ALTO, Page-XML, ABBY-XML, or your own custom one. For hOCR there exist tools to create searchable PDF from it.
- merge the PDF results, or convert the PDFs to hOCR, then see above.

Whatever your favourite programming language is, it should be a more or less easy task. For Python or Java you will find libraries doing the basic things.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/3754#issuecomment-1036309861

I also think that we should not support the first feature request.

**Comment by All3xJ** [comment]
>We even don't know, what Google, Amazon or Microsoft provides as "data and information", let alone in which format and if they provide an exact technical specification for this format. I tried to find out and found nothing (1 hour wasted time).

I found this: https://cloud.google.com/vision/docs/handwriting

> Whatever your favourite programming language is, it should be a more or less easy task. For Python or Java you will find libraries doing the basic things.

Maybe it is, but I have 0 experience in these kind of things, and even though I can code, I don't know where to begin with this.

**Comment by amitdo** [comment]
We don't plan to implement this feature request.
