### ISSUE TITLE
[MSVC] error C2766: explicit specialization; 'std::hashstd::filesystem::path' has already been defined

### ISSUE THREAD

**Issue by QuellaZhang** [tesseract-ocr/tesseract#3758]
Hi All,

The MSVC team added Tesseract as part of RWC testing. The recent MSVC's change(https://github.com/microsoft/STL/pull/2564 and https://cplusplus.github.io/LWG/issue3657) broke Tesseract build. Could you please help look at this issue or provide some workarounds? Thanks in advance.

**Note**: This is an internal test, only reproduced on unreleased MSVC, the next version of VS will have this behavior.

BTW: How to display the cl command line when using sw.exe? We always use the command to reproduce issues.

**Repro steps:**

1. git clone --recursive  https://github.com/tesseract-ocr/tesseract F:\gitP\tesseract-ocr\tesseract
2. mkdir F:\gitP\tesseract-ocr\tesseract\build_amd64
3. cd F:\gitP\tesseract-ocr\tesseract\build_amd64
4. set PATH=F:\gitP\tesseract-ocr\sw_tools;%PATH%
5. sw setup
6. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 ..

**CMake log:**[configure.log](https://github.com/tesseract-ocr/tesseract/files/8107259/configure.log)

**Error info:**
[64/176] [org.sw.demo.jbeder.yaml_cpp-master]/src/parse.cpp
[65/176] [org.sw.demo.jbeder.yaml_cpp-master]/src/nodeevents.cpp
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:764, function execute1: When executing: [pub.egorpugin.primitives.command-master]/src/uv_command.cpp
C:\Users\CPPTESTLOCAL\.sw\storage\pkg\82\15\56e9\src\sdir\src\filesystem\include\primitives/filesystem.h(155): error C2766: explicit specialization; 'std::hash<std::filesystem::path>' has already been defined
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\filesystem(4342): note: see previous definition of 'hash<std::filesystem::path>'
command failed: exit code = 2
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:764, function execute1: When executing: [pub.egorpugin.primitives.command-master]/src/argument.cpp
C:\Users\CPPTESTLOCAL\.sw\storage\pkg\82\15\56e9\src\sdir\src\filesystem\include\primitives/filesystem.h(155): error C2766: explicit specialization; 'std::hash<std::filesystem::path>' has already been defined
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\filesystem(4342): note: see previous definition of 'hash<std::filesystem::path>'
command failed: exit code = 2
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:764, function execute1: When executing: [pub.egorpugin.primitives.command-master]/src/command.cpp
C:\Users\CPPTESTLOCAL\.sw\storage\pkg\82\15\56e9\src\sdir\src\filesystem\include\primitives/filesystem.h(155): error C2766: explicit specialization; 'std::hash<std::filesystem::path>' has already been defined
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\filesystem(4342): note: see previous definition of 'hash<std::filesystem::path>'
command failed: exit code = 2

**Comment by amitdo** [comment]
This is not really a Tesseract issue. The errors messages come from a build system called sw.

https://github.com/SoftwareNetwork/sw

CC: @egorpugin

**Comment by amitdo** [comment]
For a workaround,  you can use CMake or vcpkg.

We use them in the CI for daily testing:

https://github.com/tesseract-ocr/tesseract/blob/main/.github/workflows/cmake-win64.yml

 https://github.com/tesseract-ocr/tesseract/blob/main/.github/workflows/vcpkg.yml

**Comment by egorpugin** [comment]
As I remember, there was no std::fs::hash<path> before.
I'll prepare a fix.

**Comment by QuellaZhang** [comment]
> For a workaround, you can use CMake or vcpkg.

Thanks for your suggestion, I have switched to VCPKG. No more errors, please feel free to close this issue

**Comment by amitdo** [comment]
QuellaZhang,

Maybe you can help with this issue:
https://github.com/microsoft/vcpkg/issues/16019
