### ISSUE TITLE
How to remove different shades of green to black & white

### ISSUE THREAD

**Issue by mjessa12** [tesseract-ocr/tesseract#3762]
I have the following image and the code I am using to try and convert this image to black and white for pytesseract processing.  The problem that I am having is that the darker shade greens are not able to be processed while the 2 lighter shade greens are good.  Is there anyway to fix this?

```
    img = cv2.imread(img, cv2.IMREAD_GRAYSCALE)
    # gaus = cv2.adaptiveThreshold(img_gray, 255,cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 35,100)
    gaus = cv2.threshold(img, 100, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)[1]
    gaus = cv2.resize(gaus, (0, 0), fx=1.5, fy=1.5)  # scale image 1.25X
    gaus = cv2.bitwise_not(gaus)
    config = '-l eng --psm 6'
    text = pyt.image_to_data(gaus, config=config, output_type=Output.DICT)
```

![image](https://user-images.githubusercontent.com/72001246/155884015-ec7e628e-576e-4c15-9b00-37dce992c6c6.png)

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.
