### ISSUE TITLE
Problems on mac to read PDF with image 

### ISSUE THREAD

**Issue by AlexBravo95** [tesseract-ocr/tesseract#3766]
Hi, I'm having a problem on mac to use do.OCR(), on windows it works fine but on mac it fails.

We installed Tesseract locally and GS too but it still fails when trying to read the PDF.

I was reading that it usually fails on mac, I don't know if that's the case, can you help me?
Thanks
![image](https://user-images.githubusercontent.com/77693511/157754441-ed4bfefe-85e8-4e5f-810e-64c5b9837003.png)

implementation group: 'net.sourceforge.tess4j', name: 'tess4j', version: '5.1.1'
Java 1.8
Gradle proyect

**Comment by AlexBravo95** [comment]
![image](https://user-images.githubusercontent.com/77693511/157754892-c5d395ba-450b-46d0-a436-858d77dc83db.png)

Windows OK

**Comment by zdenop** [comment]
Please respect guidelines for posting issues: we do not provide support for 3rd party projects. Reproduce problem with recent version of the tesseract executable and provide an input image for reproducing the error.
