### ISSUE TITLE
Can not retrain Tesseract after editing boxes

### ISSUE THREAD

**Issue by SyedAjwad** [tesseract-ocr/tesseract#3771]
I have implemented the following things:
Manually adjusted the boxes of characters generated by tesseract. Generated the tesseract training file. Generated the unicharset file. But when I am using the 'shapeclustering' command to generate shape table it is just stuck. The command it is stuck on:
shapeclustering.exe -F font_properties -U unicharset -O font_name.unicharset font_name.font.exp0.tr

Tried with following Tesseract versions:
tesseract-ocr-w32-setup-v4.1.0.20190314
tesseract-ocr-w64-setup-v4.1.0.20190314
tesseract-ocr-w32-setup-v4.0.0.20181030
tesseract-ocr-w64-setup-v4.1.0-elag2019

The unicharset command does nothing with the 64 bit versions of tesseract. And the other commands generate a file named 'unicharset' while it should generate a file named 'font_name.unicharset' according to these tutorials:
https://towardsdatascience.com/simple-ocr-with-tesseract-a4341e4564b6
https://stackoverflow.com/questions/55036633/how-to-create-traineddata-file-for-tesseract-4-1-0[](https://user-images.githubusercontent.com/29895540/158365978-9c2f8e34-9fb2-43e1-a3c8-c220fc56cf1d.png)

It is stuck doing nothing as shown in the following image:

![image](https://user-images.githubusercontent.com/29895540/158900173-204f62e8-00fd-46da-8534-e47e2d364ae4.png)

If you need any more information then please do let me know. I have tried different approaches and searching for the solution of the problem but could not find anything useful.

Kind Regards,
Ajwad

**Comment by zdenop** [comment]
You are referring to external/not supported tutorials - please report your problems to their authors.
