### ISSUE TITLE
ld-elf.so.1: /usr/local/lib/libtesseract.so.5: Undefined symbol "__kmpc_global_thread_num"

### ISSUE THREAD

**Issue by frankble** [tesseract-ocr/tesseract#3777]
I need help finding the source of the following problem:
When I compile the gosseract sample ...

`package main

import (
	"fmt"
	"github.com/otiai10/gosseract/v2"
)

func main() {
	client := gosseract.NewClient()
	defer client.Close()
	client.SetImage("path/to/image.png")
	text, _ := client.Text()
	fmt.Println(text)
	// Hello, World!
}`

... on FreeBSD 12.3 with ...

`tesseract 5.0.0
 leptonica-1.76.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.2) : libpng 1.6.37+apng : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.1
 Found OpenMP 201511
 Found libarchive 3.5.2 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.0
 Found libcurl/7.80.0 OpenSSL/1.1.1l zlib/1.2.11 libssh2/1.10.0 nghttp2/1.46.0`

... and start the programm i get the following error:
ld-elf.so.1: /usr/local/lib/libtesseract.so.5: Undefined symbol "__kmpc_global_thread_num"

Possibly somebody can point me in the right direction what to do to fix this?
I already opened an issue in gosseract but nobody answered. I'm not sure if this is something depending on the gosseract part or is it because the libtesseract has a problem?

**Comment by stweil** [comment]
Maybe a missing `-openmp` compiler or linker option? This is not a Tesseract issue.

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by vmato** [comment]
This is a tesseract issue. And it is still actual

**Comment by stweil** [comment]
The missing symbol `__kmpc_global_thread_num` is not part of the Tesseract code (that's why I said it is not a Tesseract issue). It might be related to OpenMP, so either try to build Tesseract without OpenMP support (I'd suggest that) or try to find the library which provides that symbol and add it to the linker command line.

**Comment by frankble** [comment]
Only for the record: When installing tesseract from freebsd repo it doesn't work. We have to manually recompile tesseract to get it working like it did all the time up to now from repo. Hmm ... interessing point. Thanks!
