### ISSUE TITLE
Error in pixWriteTiff: function not present

### ISSUE THREAD

**Issue by wowanfengz** [tesseract-ocr/tesseract#378]
ubuntu 16.04

`tesstrain.sh --lang chi_sim --langdata_dir train_demo/langdata/ --tessdata_dir chi_sim_tessdata --fontlist Arial\ Unicode\ MS`

I used the training script, but the system reported the error.
why?

**Comment by yjhexy** [comment]
It seems that your leptonica library was build without tiffsupport. 
try "sudo apt-get install libtiff5-dev" in ubuntu 
or "yum install libtiff*" in centos
