### ISSUE TITLE
tesseract 5.1.0-20-gfacd5  works with traineddata-3.0.4 and not with traineddata_best-4.1.0 with this method TessResultIteratorWordFontAttributes

### ISSUE THREAD

**Issue by ken4ward** [tesseract-ocr/tesseract#3784]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/main/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: tesseract 5.1.0-20-gfacd5 
* **Commit Number**: 
* **Platform**: Darwin Kehindes-MBP 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
* traineddata-3.0.4
* traineddata_best-4.1.0

### Current Behavior:
**1st scenario**
I installed tesseract 5.1.0-20-gfacd5 from source + traineddata-3.0.4. I ran this code to get the font properties. It works fine.
```
public void checkFontProperties( String mobileElement, String saveReadFile, String uiFontName, boolean bold, boolean italic, boolean underline,
                                     boolean monospace, boolean serif, boolean smallcaps, int pointSize, ) throws Exception {

        saveScreenshot( mobileElement,  saveReadFile);
        System.setProperty("jna.encoding", "UTF8");
        TessBaseAPI tessBaseAPI = new TessBaseAPI();
        ITesseract images = new Tesseract();
        images.setTessVariable("user_defined_dpi", "348");

        String lang = "ubuntubold";
        File imageFile = new File(saveReadFile);
        BufferedImage image = ImageIO.read(new FileInputStream(imageFile)); // require jai-imageio lib to read TIFF
        fontFamily(image);
        ByteBuffer buf = ImageIOHelper.convertImageData(image);
        int bpp = image.getColorModel().getPixelSize();
        int bytespp = bpp / 8;
        int bytespl = (int) Math.ceil(image.getWidth() * bpp / 8.0);

        TessBaseAPIInit3(tessBaseAPI, "tessdata", lang);
        TessBaseAPISetPageSegMode(tessBaseAPI, TessAPI1.TessPageSegMode.PSM_AUTO);
        TessBaseAPISetImage(tessBaseAPI, buf, image.getWidth(), image.getHeight(), bytespp, bytespl);
        TessBaseAPIRecognize(tessBaseAPI, null);
        TessBaseAPIGetUTF8Text(tessBaseAPI);
        ResultIterator ri = TessBaseAPIGetIterator(tessBaseAPI);
        PageIterator pi = TessResultIteratorGetPageIterator(ri);
        TessPageIteratorBegin(pi);

        BoolPointer boldB = new BoolPointer(1);
        BoolPointer italicB = new BoolPointer(1);
        BoolPointer underlinedB = new BoolPointer(1);
        BoolPointer monospaceB = new BoolPointer(1);
        BoolPointer serifB = new BoolPointer(1);
        BoolPointer smallcapsB = new BoolPointer(1);
        IntBuffer pointSizeB = IntBuffer.allocate(1);
        IntBuffer fontIdB = IntBuffer.allocate(1);
        String fontName = TessResultIteratorWordFontAttributes( ri, boldB, italicB, underlinedB, monospaceB, serifB, smallcapsB, pointSizeB, fontIdB);
    }
```
2nd scenario
I installed tesseract 5.1.0-20-gfacd5 from source + traineddata-4.1.0. I ran the same code above to get the font properties. It returned null pointer error, because it did not see the font.
### Expected Behavior:
It should be able to work with both traineddata, more importantly traineddata_best.

### Suggested Fix:
It seems traineddata_best needs some improvement.

**Comment by zdenop** [comment]
duplicate to https://github.com/tesseract-ocr/tesseract/issues/1074
