### ISSUE TITLE
tesseract wrong output: additional chars added unnecessarily

### ISSUE THREAD

**Issue by FPEPOSHI** [tesseract-ocr/tesseract#3786]
Since we upgraded to version 5.1.0 from 4.x.y we are having bad results of OCR. 
Im using following configs:
--oem 1
--psm 6
-l deu

this is a part of pdf:
<img width="728" alt="Screenshot 2022-04-07 at 2 56 04 PM" src="https://user-images.githubusercontent.com/11835889/162203760-16035fa1-db08-413e-9c01-eaf81c256919.png">

------------------------

### Environment

* **Tesseract Version**: 5.1.0
* **Platform**: osx, debian

### Current Behavior:
Menge Beschreibung MwSt Preis/Einheit Einheit Gesamt
100 LOSTO0069 - Nachbestellung Speisekarten (Upload) 19,00% 0,8900 EUR 1 89,00 EUR
Dormagen-Speisekarte-DE

### Expected Behavior:
Menge Beschreibung MwSt Preis/Einheit Einheit Gesamt
100 LOST0069 - Nachbestellung Speisekarten (Upload) 19,00% 0,8900 EUR 1 89,00 EUR
Dormagen-Speisekarte-DE

**Comment by stweil** [comment]
Additional characters are a well known problem of OCR with neural networks and was reported here more than once. Using a different model or additional training typically helps.

Your example works with `script/Latin`.

**Comment by FPEPOSHI** [comment]
Sorry, previous version was `4.1.3`
Actually when I switch back to this version it works.

Update: 
I tried the trick with language and works with `5.1.0`, but still on older version works also without `eng`. I will use these configs till a new version is released. Thank you @stweil
