### ISSUE TITLE
syntax error near unexpected token `ENABLE_TRAINING,'

### ISSUE THREAD

**Issue by BigChase** [tesseract-ocr/tesseract#379]
Installation failed on CentOS, ./configure terminated with:

> ./configure: line 21977: syntax error near unexpected token `ENABLE_TRAINING,'
> ./configure: line 21977: `AM_COND_IF(ENABLE_TRAINING,           ac_config_files="$ac_config_files training/Makefile"'

Previous output:

> configure: WARNING: Training tools WILL NOT be built because of missing icu library.
> configure: WARNING: Try to install libicu-devel package.
> checking pango-1.0/pango/pango-features.h usability... no
> checking pango-1.0/pango/pango-features.h presence... no
> checking for pango-1.0/pango/pango-features.h... no
> configure: WARNING: Training tools WILL NOT be built because of missing pango library.
> configure: WARNING: Try to install libpango1.0-dev package.
> checking cairo/cairo-version.h usability... no
> checking cairo/cairo-version.h presence... no
> checking for cairo/cairo-version.h... no
> configure: WARNING: Training tools WILL NOT be built because of missing cairo library.
> configure: WARNING: Try to install libcairo-dev?? package.
> configure: WARNING: Training tools WILL NOT be built because of missing c++11 support.
> ./configure: line 21977: syntax error near unexpected token `ENABLE_TRAINING,'
> ./configure: line 21977: `AM_COND_IF(ENABLE_TRAINING,           ac_config_files="$ac_config_files training/Makefile"'

Confirmed cairo pango installed

> # yum install cairo pango
> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
> addons                                                                                                   | 1.9 kB     00:00     
> base                                                                                                     | 1.1 kB     00:00     
> extras                                                                                                   | 2.1 kB     00:00     
> updates                                                                                                  | 1.9 kB     00:00     
> Excluding Packages in global exclude list
> Finished
> Setting up Install Process
> Package cairo-1.2.4-5.el5.i386 already installed and latest version
> Package pango-1.14.9-8.el5.centos.3.i386 already installed and latest version
> Nothing to do

**Comment by Shreeshrii** [comment]
You need to install icu, cairo and pango development packages, please read
the configure errors posted above.



ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
https://rpmfind.net/linux/rpm2html/search.php?query=pango-devel

https://rpmfind.net/linux/rpm2html/search.php?query=cairo-devel

https://rpmfind.net/linux/rpm2html/search.php?query=icu-dev

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
