### ISSUE TITLE
Receiving "Empty Page" message

### ISSUE THREAD

**Issue by jimjg** [tesseract-ocr/tesseract#3791]
The attached image fails to produce any output.  I can submit individual lines and they get recognized, but my app is way too slow due to the repeated calls.  I'm using AutoIt3 scripting so the command line excursions are time consuming.

I've tried the command with --psm 4 with the same results.  I must be doing something really stupid.

![test](https://user-images.githubusercontent.com/20491723/163450716-a59035f1-1076-4b51-a971-9c91961ae5d9.jpg)

"C:\Program Files\Tesseract-OCR\tesseract.exe" ./test.jpg ./list

**Comment by jimjg** [comment]
I realize that ClearType is on in the above example, but turning it off doesn't change the results.  If I eliminate the top line (which is the reverse color) it works better, but still stumbles over a lot of the data.  I've tried 'thresholding" the image.

**Comment by zdenop** [comment]
First of all: you should ask questions at the tesseract user forum as indicated when you create a new issue. 
Next: make sure you first open issues (try to search  for "table") + read the documentation and try ALL suggestions mentioned in https://github.com/tesseract-ocr/tessdoc/blob/main/ImproveQuality.md
