### ISSUE TITLE
abracadabra detected in special case

### ISSUE THREAD

**Issue by okarpov** [tesseract-ocr/tesseract#3794]
At some special case an abracadabra detected (see screenshot attached - left-side is an image, right side is the text detected)
Can provide the original image 2550x3300 png  by request (confidential)
------------------------

### Environment

* **Tesseract Version**: 5.1.0
* **Commit Number**: -
* **Platform**: Windows 11 64-bit

### Current Behavior:
abracadabra detected

### Expected Behavior:
simple text recognition

### Suggested Fix:
-
![ocr_page1_ss](https://user-images.githubusercontent.com/2629775/163714856-c0af97a4-2d1c-4564-9d46-5ae00ce8bc2f.png)

**Comment by zdenop** [comment]
Your input image has complex layout. Tesseract is OCR engine with support only for simple document layouts as book page.
You need to make image segmentation by yourself and OCR each image segment individually.
