### ISSUE TITLE
Support for multithreading build by CMake doesn't work

### ISSUE THREAD

**Issue by krzysiekj94** [tesseract-ocr/tesseract#3797]
### Environment

* **Tesseract Version**: 5.1.0
* **Platform**: Windows 32-bit, compiled under MSVC 2017

### Current Behavior:

I have the problems & questions: 

1). Question 1: While preparing the build, I noticed that the "OPENMP_BUILD" setting is not included when building the solution see below: 

![image](https://user-images.githubusercontent.com/12548678/164738786-4abb58b6-d935-4c46-9fdb-894d5b846c70.png)

Anyone can say something more about it? Is using multiprocessing at the moment recommended? What's the state of it now? I only saw subject [# 1662](https://github.com/tesseract-ocr/tesseract/issues/1662) where it was turned off, but it was 4 years ago :o

2). Question: Are there any other ways to take advantage of multithreading in Tesseract besides OpenMP in Tesseract 5.1.0? Anyone have experience in this topic? For now I am working on 1 thread, but ultimately I would like to switch to multiple threads.

### Expected Behavior:

I would expect multithreading in Tesseract to be possible after select OPENMP_BUILD and using multithreading according to docs: https://tesseract-ocr.github.io/tessdoc/FAQ.html

### Suggested Fix:

Restoring the possibility of preparing Tesseract with the multithreading option

**Comment by krzysiekj94** [comment]
Does anyone know about this topic? Thank your for all reply.

**Comment by zdenop** [comment]
Please respect guidelines for posting issues: use tesseract user forum for asking questions/support.
