### ISSUE TITLE
some problem about text2image convert text file to tif and box

### ISSUE THREAD

**Issue by futureflsl** [tesseract-ocr/tesseract#3801]
Environment:
windows10 x64
tesseract 4.0/5.0

when I use command:
text2image --text charset.txt   --outputbase ./ch.simhei.exp0 --fonts_dir ./font  --font="simhei"  --fontconfig_tmpdir  ./tmp --writing_mode horizontal --strip_unrenderable_words

it can generate box and tif file.but I open it by jTessBoxEditor.the char all is block.
![360截图20220428080111878](https://user-images.githubusercontent.com/23259315/165650377-adae8617-dbf4-480f-bec3-dc02346d411e.png)

**Comment by zdenop** [comment]
This is not tesseract issue, but jTessBoxEditor.
