### ISSUE TITLE
Languages should be sorted

### ISSUE THREAD

**Issue by THausherr** [tesseract-ocr/tesseract#3803]
### Environment

* **Tesseract Version**: v5.0.1.20220107
* **Platform**: W10.0.19043.1645 64 bit

### Current Behavior:
![grafik](https://user-images.githubusercontent.com/6665575/165743066-f51710de-b305-43d3-b8d3-22943001de50.png)

### Expected Behavior:
Languages should be sorted

### Suggested Fix:
Sort

**Comment by zdenop** [comment]
Please report to your packager. We release source code not binary packages/installed.
