### ISSUE TITLE
Chinese error message when trying to download deu.traineddata

### ISSUE THREAD

**Issue by THausherr** [tesseract-ocr/tesseract#3804]
### Environment

* **Tesseract Version**: v5.0.1.20220107
* **Platform**: W10.0.19043.1645 64 bit

### Current Behavior:
![grafik](https://user-images.githubusercontent.com/6665575/165743907-78bfce56-1154-4b9c-9e38-e7760728ec7d.png)

The redacted part is a chinese text (but which ends with "r") which I have removed in case it contains personal data. I am not Chinese nor do I work in China.
I suspect that the text is a download failure because of a network failure because of a company proxy.
I got tesseract to work with german language by manually downloading the file from https://digi.bib.uni-mannheim.de/tesseract/tessdata_fast/

### Expected Behavior:
error message in english or german

### Suggested Fix:
create error message in english or german

**Comment by zdenop** [comment]
Please report to your packager. We release source code not binary packages/installed.

**Comment by stweil** [comment]
@THausherr, did you read the version history and use the latest installer?

[2022-01-18](https://github.com/UB-Mannheim/tesseract/commits/v5.0.1.20220118) Update Tesseract 5.0.1. Fixed model download.
    [2022-01-07](https://github.com/UB-Mannheim/tesseract/commits/v5.0.1.20220107) Update Tesseract 5.0.1. Model download is broken.

**Comment by THausherr** [comment]
Sorry - I used a download I already had because "deu" was missing, I did look at https://digi.bib.uni-mannheim.de/tesseract/ , but didn't see that there was a newer 5.0.1 .
