### ISSUE TITLE
TessPDFRenderer uses "long int" to store PDF offsets, which is too small on some platforms

### ISSUE THREAD

**Issue by mcsjosh** [tesseract-ocr/tesseract#3805]
### Environment

* **Tesseract Version**: 5.1.0 (compiled from source)
* **Commit Number**: 
* **Platform**: Windows 10 32-bit, gcc 11.2.0 via MSYS2)

### Current Behavior:
TessPDFRenderer uses `long int` to store PDF offsets, and on my platform `long int` is 32-bits.  As a result, TessPDFRenderer can only create valid PDF files if all offsets are below 2GiB.  Offsets between 2GiB and 4GiB are output as negative numbers in the Xref table.

### Expected Behavior:
Valid PDF Xref offsets can be as high as 9999999999 (10GB).  In order to support PDF output of that size, TessPDFRenderer should store offsets using a data type guaranteed to be at least 64-bit.

### Suggested Fix:
Make `TessPDFRenderer::offsets_` a vector of `long long int` rather than `long int`:
```diff
--- a/include/tesseract/renderer.h
+++ b/include/tesseract/renderer.h
@@ -229,11 +229,11 @@ private:
   // PDFs one page at a time. At the end, that metadata is
   // used to make everything that isn't easily handled in a
   // streaming fashion.
-  long int obj_;                  // counter for PDF objects
-  std::vector<long int> offsets_; // offset of every PDF object in bytes
-  std::vector<long int> pages_;   // object number for every /Page object
-  std::string datadir_;           // where to find the custom font
-  bool textonly_;                 // skip images if set
+  long int obj_;                       // counter for PDF objects
+  std::vector<long long int> offsets_; // offset of every PDF object in bytes
+  std::vector<long int> pages_;        // object number for every /Page object
+  std::string datadir_;                // where to find the custom font
+  bool textonly_;                      // skip images if set
   // Bookkeeping only. DIY = Do It Yourself.
   void AppendPDFObjectDIY(size_t objectsize);
   // Bookkeeping + emit data.
```

**Comment by stweil** [comment]
Thank you for this detailled report. We should check whether unsigned values are not even better. And instead of `long long int`, I would prefer using a POSIX data type like `int64_t` or `uint64_t`.

In any case it must be also checked whether this is an incompatible change of the public API.

Do you want to send a pull request?

**Comment by stweil** [comment]
> asking me to switch to either `int64_t` or `uint64_t` and then send a pull request

Yes, that one. And I think that we can handle it as a API compatible change because on most platforms the sizes don't change. Only for Windows 32 bit there will an incompatible change, but there it is a bug fix.

**Comment by p12tic** [comment]
> Only for Windows 32 bit there will an incompatible change, but there it is a bug fix.

Changing `std::vector<A>` to `std::vector<B>` doesn't change the layout of the vector itself as it's just 3 pointers in most implementations.

**Comment by mcsjosh** [comment]
Okay, I've created pull request #3808.

**Comment by stweil** [comment]
Thanks. It is merged now, so this issue can be closed.
