### ISSUE TITLE
Update or remove Travis CI

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#3806]
[Travis CI for Tesseract](https://travis-ci.org/github/tesseract-ocr/tesseract) stopped about a year ago. Travis announced that it moved their service to another location:

> "Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on."

Who manages Travis CI for Tesseract? Should we move or drop Travis CI?

**Comment by zdenop** [comment]
[seems](https://github.com/tesseract-ocr/tesseract/commit/0f651c187b67df984d71d5ec1ceda41d05fee6d0) @egorpugin added .travis.yml
[travis-ci.com](http://www.travis-ci.com/) seems like there offering the Trial and paid solution.

Condition for Trial:

> A free ‘Trial’ Plan, which any new user can select upon sign up, is a usage-based plan with an unlimited amount of users, which comes with a 10k trial pool of credits to start building right away. Once these credits run out, they are not replenished, and users must subscribe to a higher plan to continue building. Request OSS Credits allowance, or please consider one of our available plans. Trial credits are valid only for 30 days.

[OSS Credits allowance](https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source): 


> Each of the Travis CI Plans contains an amount of special OSS credits per month assigned to run builds only on public repositories. To find out more about it please [contact the Travis CI support team](mailto:support@travis-ci.com). In the email please include:
> 
> - Your account name and your VCS provider (like travis-ci.com/github/[your account name] )
> - How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or to discuss a renewable amount)

**Comment by stweil** [comment]
Are GitHub actions not sufficient? Or does Travis CI provide additional benefits? If it doesn't, I suggest to remove it.

**Comment by egorpugin** [comment]
+1 for removal.
I'll do it.
