### ISSUE TITLE
Q&A: Technical drawings OCR

### ISSUE THREAD

**Issue by ViterAlex** [tesseract-ocr/tesseract#3807]
-----------------------

### Environment

* **4.1.1**: 
* **Commit Number**: 
* **Windows**: 

### Current Behavior:
Doesn't recognize technical drawings

### Expected Behavior:
Recognize dimensions text and symbols on drawings
### Suggested Fix:
It's not an issue actually but question. I'm junior developer on .Net. I'm trying to OCR technical drawings (mechanicals). I'm looking for the tool of recognition. Is it possible to train tesseract engine on such specific symbols?
![frag02](https://user-images.githubusercontent.com/15142804/166159477-a23480cc-3694-423e-a1b5-b811a30969e0.png)
![frag03](https://user-images.githubusercontent.com/15142804/166159478-c36b4f50-d004-489e-8e8b-69f6845a07d9.png)
![frag04](https://user-images.githubusercontent.com/15142804/166159479-fbfffb64-9c8f-45be-ae0d-ac4c4c924237.png)
![frag01](https://user-images.githubusercontent.com/15142804/166159480-692ff031-e8dd-41fb-b6cb-35feec2f0f50.png)

Sorry, but it's really hard to find any information about this

**Comment by wollmers** [comment]
> ### Current Behavior:
> Doesn't recognize technical drawings

Tesseract mainly supports OCR of text documents.

> It's not an issue actually but question. I'm junior developer on .Net. I'm trying to OCR technical drawings (mechanicals). I'm looking for the tool of recognition. Is it possible to train tesseract engine on such specific symbols?

You can train Tesseract on any symbols. The ones in the sample have Unicode code points:

```
$ uni print U+2316 U+2300 U+23CA U+27C2
     cpoint  dec    utf-8       html       name
'⌀'  U+2300  8960   e2 8c 80    &#x2300;   DIAMETER SIGN (Other_Symbol)
'⌖'  U+2316  8982   e2 8c 96    &target;   POSITION INDICATOR (Other_Symbol)
'⏊'  U+23CA  9162   e2 8f 8a    &#x23ca;   DENTISTRY SYMBOL LIGHT UP AND HORIZONTAL (Other_Symbol)
'⟂'  U+27C2  10178  e2 9f 82    &#x27c2;   PERPENDICULAR (Math_Symbol)
```
I guess that there are a lot more symbols used, and some are not defined in Unicode. But you can use own code points in the PUA (Private Use Area).

You are left alone to train a model for technical drawings. Which one? CAD/CAM for machinery, buildings, electrical, plumbing, printed circuits, cartography, meteorology, military, gardening? 

The standard models support languages and writing systems. That's what the majority developers and contributors of Tesseract have expertise on.

Tesseract has problems removing the frames of table-like objects. You must remove them yourself during preprocessing.

> Sorry, but it's really hard to find any information about this

It's an FAQ. You should ask such questions in the forum.

**Comment by medhanshrath-t** [comment]
> ### Environment
> * **4.1.1**:
> * **Commit Number**:
> * **Windows**:
> 
> ### Current Behavior:
> Doesn't recognize technical drawings
> 
> ### Expected Behavior:
> Recognize dimensions text and symbols on drawings
> 
> ### Suggested Fix:
> It's not an issue actually but question. I'm junior developer on .Net. I'm trying to OCR technical drawings (mechanicals). I'm looking for the tool of recognition. Is it possible to train tesseract engine on such specific symbols? ![frag02](https://user-images.githubusercontent.com/15142804/166159477-a23480cc-3694-423e-a1b5-b811a30969e0.png) ![frag03](https://user-images.githubusercontent.com/15142804/166159478-c36b4f50-d004-489e-8e8b-69f6845a07d9.png) ![frag04](https://user-images.githubusercontent.com/15142804/166159479-fbfffb64-9c8f-45be-ae0d-ac4c4c924237.png) ![frag01](https://user-images.githubusercontent.com/15142804/166159480-692ff031-e8dd-41fb-b6cb-35feec2f0f50.png)
> 
> Sorry, but it's really hard to find any information about this

Hey did you have any luck in figuring this out?
