### ISSUE TITLE
generate pdf error with tesseract took too long to OCR - skipping

### ISSUE THREAD

**Issue by delegate-it** [tesseract-ocr/tesseract#3809]
### Environment
macOS Montenerey 12.2.1 with intel chip
***Tesseract Version**:  5.1.0
Platform : xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### Suggested Fix:
![Screenshot 2022-05-05 at 18 52 21](https://user-images.githubusercontent.com/45656979/166973458-3f0b2614-b079-4f07-b814-ee7b5bcb7f71.png)
![Screenshot 2022-05-05 at 18 53 06](https://user-images.githubusercontent.com/45656979/166973583-a1973e37-fe19-4517-8bf7-549fbd4c11c4.png)

**Comment by amitdo** [comment]
The image is too big. 

See https://github.com/DanBloomberg/leptonica/issues/138 and #3184.

**Comment by amitdo** [comment]
Also see https://github.com/ocrmypdf/OCRmyPDF/issues/428.

**Comment by zdenop** [comment]
So solution is to split image to smaller parts.
