### ISSUE TITLE
Question: Can anybody point me to code that handles splitting word into characters?

### ISSUE THREAD

**Issue by exander77** [tesseract-ocr/tesseract#3811]
I have hard time navigating the code.

I located `PAGE_RES_IT::ReplaceCurrentWord` that replaces fake boxes with real ones, but I can't locate where `src_b` and `rej_b` are assembled.

I have some boxes wrong, most likely related to diplopia, and I am looking for the cause.

**Comment by exander77** [comment]
Ok, so `RecodeBeamSearch::ExtractBestPathAsWords`  process words.

**Comment by amitdo** [comment]
Please use our forum for asking questions.
