### ISSUE TITLE
'unicode/errorcode.h' file not found

### ISSUE THREAD

**Issue by ken4ward** [tesseract-ocr/tesseract#3816]
### Environment

* **Tesseract Version**: tesseract-3.05.02
* **Commit Number**: 
* **Platform**: 21.3.0 Darwin Kernel Version 21.3 (MacOs monterey)

### Current Behavior:
I'm following this tutorial - https://tesseract-ocr.github.io/tessdoc/Compiling.html#macos
I am trying to build from source, Tesseract completed successfully. When I tried to compile it for training, it returns the error. 
I issued this command on the terminal - ```make training```
```
../../training/ligature_table.cpp:30:10: fatal error: 'unicode/errorcode.h' file not found
#include "unicode/errorcode.h"  // from libicu
```
I have icu4c installed using brew. I checked and could see the file in icu4c directory

### Expected Behavior:
It is supposed to compile fully.

**Comment by stweil** [comment]
Are you really trying to build tesseract-3.05.02 on MacOS? Why?

**Comment by stweil** [comment]
It works perfectly for me with Tesseract 5.x or the latest code from Git.

**Comment by ken4ward** [comment]
Thanks for the answer. I'm building from source. I want to train a new font, and it's not possible to use version 5 for it. My project is tied to version 3 because I need to get font properties, which is not provided in the LSTM tessdata. This is the reason I opted for 3. I have installed the training for version 5, and it worked perfectly. What's the workaround for version 3?

**Comment by stweil** [comment]
Tesseract 5 supports legacy models and training of such models, so no need to use an outdated version. It only removed some shell scripts which are still available in Tesseract 4. You can get them from there: https://github.com/tesseract-ocr/tesseract/tree/4.1/src/training.

**Comment by stweil** [comment]
You will need [tesstrain.sh](https://github.com/tesseract-ocr/tesseract/blob/4.1/src/training/tesstrain.sh) which requires [tesstrain_utils.sh](https://github.com/tesseract-ocr/tesseract/blob/4.1/src/training/tesstrain_utils.sh) and [language-specific.sh](https://github.com/tesseract-ocr/tesseract/blob/4.1/src/training/language-specific.sh).

**Comment by ken4ward** [comment]
@stweil It seems the tesstrain.sh is for training LSTM not legacy system. I noticed it’s constructing LSTM training data

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
