### ISSUE TITLE
Text is garbled in pdf.js (Cygwin / UB Mannheim binaries)

### ISSUE THREAD

**Issue by edubya** [tesseract-ocr/tesseract#382]
PDFs generated using either Cygwin (3.04.01) or one of the windows binaries (3.05.00dev) gives offset highlighted text and garbled text when copied, in pdf.js. Attached TIF is output from Scan Tailor. Related: #337 .

Copied from pdf.js:
An  exactmethodis  presentedfor  numericallycalculating,withinthe  frameworkof  thestochasticformulationof  chemicalkinetics,the   timeevolutionof  anyspatiallyhomog-
![image](https://cloud.githubusercontent.com/assets/4030380/17447416/41d2a3ac-5b1c-11e6-9d7f-19a43bcb76d6.png)

Attached txt output from tesseract:
An exact method is presented for numerically calculating, within the framework of the
stochastic formulation of chemical kinetics, the time evolution of any spatially homog-

[Gillespie-000.txt](https://github.com/tesseract-ocr/tesseract/files/404420/Gillespie-000.txt)
[Gillespie-000.pdf](https://github.com/tesseract-ocr/tesseract/files/404417/Gillespie-000.pdf)
[Gillespie-000.zip](https://github.com/tesseract-ocr/tesseract/files/404421/Gillespie-000.zip)

**Comment by zdenop** [comment]
IMO this is not tesseract problem but pdf rendered problem. I tried your files in acrobat reader and here is copied text from it:
An exact method is presented for numerically calculating, within the framework of the
stochastic formulation of chemical kinetics, the time evolution of any spatially homogeneous
mixture of molecular species which interreact through a specified set of coupled

Here is screenshot:

![image](https://cloud.githubusercontent.com/assets/574156/17740797/20c8ab48-649a-11e6-8456-448bffb04598.png)

**Comment by edubya** [comment]
i think as @ebogaard pointed out this issue and [sumatrapdf #544](https://github.com/sumatrapdfreader/sumatrapdf/issues/544) are very closely related to tesseract #373, which is more than just a pdf renderer issue. a lot of the pdfs referenced in that issue open correctly in adobe but not in other pdf renderers.

would be great to have the pdfs generated by tesseract render correctly in pdf.js

**Comment by jbreiden** [comment]
The vertical problem in pdf.js was fixed by adjusting font metrics for Tesseract. The fix was handed off to Ray and is pending a code merge from Ray. I suspect the horizontal problem is due to a flaw pdf.js when interpretting the Tz directive, but am not sure. Can only make forward progress if a programmer on the pdf.js  side can work with me.

**Comment by zdenop** [comment]
@jbreiden: Is this fixed or are you still waiting for Ray?

**Comment by jbreiden** [comment]
Should be in v4. Very easy to back port to v3 if desired.

**Comment by zdenop** [comment]
Good. Can you create Pull request against 3.05 branch?

**Comment by amitdo** [comment]
@jbreiden
Isn't a new `pdf.ttf` needed?

**Comment by jbreiden** [comment]
Yes there should be a new pdf.ttf in v4. Today is a major holiday in my country and I probably can't do anything (including take a careful look) until later, possibly Monday.

**Comment by amitdo** [comment]
https://en.wikipedia.org/wiki/Thanksgiving
:-)

**Comment by jbreiden** [comment]
Github Tesseract is currently wrong; there is a mismatch between code and font. 
Needs to have this. Checking with Ray to see what else might have been incorrectly 
synchronized.

$ md5sum pdf.ttf
e436074b54ed9cc5bf4789f79059b01b pdf.ttf

**Comment by jbreiden** [comment]
Everything is now correct on 3.05 and 4.x branches. Should fix vertical highlight problems but not horizontal ones in pdf.js / Firefox

**Comment by amitdo** [comment]
@jbreiden

https://wiki.mozilla.org/Mortar_Project

>Project Mortar is aiming to explore the possibility to bring PDFium library and the Pepper API based Flash plugin into Firefox.
