### ISSUE TITLE
Tesseract user-patterns option not working in CLI or Python

### ISSUE THREAD

**Issue by RakeshG1** [tesseract-ocr/tesseract#3823]
### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**: 

### Current Behavior: "user pattern" option doesn't have any effect on the input image, it's not using patterns in the user-patterns file, but rather writing whole text from the Image. I have tried both in python and using the command line, but none of the ways seems to be working.

`custom_patterns.txt`
![custom_patterns](https://user-images.githubusercontent.com/46260896/169698557-52146e91-b1d2-4d4c-a8c8-d12b97398e4a.png)

`Tesseract_CLI_Output`
![Tesseract_CLI_Output](https://user-images.githubusercontent.com/46260896/169698558-f38b010b-c31e-4933-8c4d-870cbf74a99d.png)

`Python_pytesseract_Output`
![Python_pytesseract_Output](https://user-images.githubusercontent.com/46260896/169698559-4ab2f2b6-4fc3-4a90-9718-ff01cfc0ffa9.png)

`Sample_4.png`
![Sample_4](https://user-images.githubusercontent.com/46260896/169698616-2db69df3-4d54-4d5e-a26f-8ee24765d2ba.png)

`Sample_3.png`
![Sample_3](https://user-images.githubusercontent.com/46260896/169698617-b3afe88d-6bbc-46a7-8eb2-f448250f105a.png)

### Suggested Fix: 
 
- Which version can handle this?
- Is it still an open Issue?
- Is any workaround solution for it, that I can try?

**Comment by stweil** [comment]
From the [documentation](https://tesseract-ocr.github.io/tessdoc/APIExample-user_patterns.html): "User patterns (like user dictionaries) are merely applied as a hint while decoding, but not exclusively."

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by RakeshG1** [comment]
I have just gone through the suggested user group, but I realized, for most of the questions/issues, it is not been answered for a long time. Also, I have gone through already the below documentation but none of the options is working.
https://tesseract-ocr.github.io/tessdoc/APIExample-user_patterns.html

Could you please confirm whether this is a working parameter for Tesseract or suggest to me how to handle the above use case.

Thanks in advance!
