### ISSUE TITLE
command line option to disable OpenCL

### ISSUE THREAD

**Issue by githubkusi** [tesseract-ocr/tesseract#3829]
Please allow to disable the OpenCL codepath with a command line parameter (e.g `--disable-opengl` or setting an environment variable `TESSERACT_NO_OPENCL`). Currently, OpenCL can only be disabled in the build process but not during runtime. Specifically I would like to prevent [this conditional statement](https://github.com/tesseract-ocr/tesseract/blob/76dbc212334500a7ad6cd5d11586387725aea544/src/opencl/openclwrapper.cpp#L2350) to be executed. Context: spurious errors in the profile file generation.

### Environment
* tesseract v4.1.1 with Leptonica
* Opensuse Tumbleweed
* Linux 5.17

**Comment by stweil** [comment]
There is no support for OpenCL, so any changes in that code must be done by people interested in using OpenCL. So if you want such changes, I suggest to write the code and create a pull request.
