### ISSUE TITLE
Dedection of Seven Segment Led displays

### ISSUE THREAD

**Issue by vaperon** [tesseract-ocr/tesseract#383]
I've managed to make Tesseract OCR work with plain text but i need to make this OCR work with seven segments led displays on an Android Studio project.

I've really tried to dug internet for it but couldn't find useful information about this one. If anyone worked on a similar project I'm desperate for your help. Please.

Thanks from now.

**Comment by zdenop** [comment]
Use tesseract user forum for asking support (search it before asking question - there were experiences/suggestion about 7 segment OCR in past)
