### ISSUE TITLE
Errors in image recognition

### ISSUE THREAD

**Issue by mgushinets** [tesseract-ocr/tesseract#3831]
### Environment

* **Tesseract Version**: 
tesseract 5.1.0
 leptonica-1.81.1 (Mar 18 2022, 15:34:11) [MSC v.1929 LIB Release x64]
  libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.1.3) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.1
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.5.2 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.2
 Found libcurl/7.81.0-DEV Schannel zlib/1.2.11

* **Platform**: 
Edition	Windows 10 Pro
Version	21H2
OS build	19044.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

### Current Behavior:
Please see this sample file:
![FL DL](https://user-images.githubusercontent.com/104155318/170934584-27abc04a-4d85-48ba-99bd-9d108171d64c.PNG)

Tesseract does not recognize correctly the number of driver`s license. It returns just  "W426-545-30-761 Hk, J"
And few other mistakes. Here is full output for this image:
[FLDL_OCR.txt](https://github.com/tesseract-ocr/tesseract/files/8796200/FLDL_OCR.txt)

### Expected Behavior:
Tesseract recognizes correctly the number of driver`s license as "W426-545-30-761-0"

**Comment by stweil** [comment]
You can try to preprocess the image, extract the relevant part of the image and run OCR only on that part.
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by mgushinets** [comment]
But we don`t know in advance which part of upcoming images is the most important for us. This means we need to have all the text extracted and process it afterwards. I understand this is not the easy task and appreciate any advices.

**Comment by amitdo** [comment]
https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html

Please use our forum as suggested by @stweil.
