### ISSUE TITLE
OCR recognizing things that arent characters and refusing to recognize things that are

### ISSUE THREAD

**Issue by IDontLikeGithub445** [tesseract-ocr/tesseract#3834]
------------------------

### Environment

* **Tesseract Version**: v5.1.0.20220510
* **Commit Number**: 
* **Platform**: Windows 32-bit (Using pytesseract as a wrapper)

### Current Behavior:
Returns a seemingly random (but consistant) string of texts
Running these two images:
https://imgur.com/a/B34dVSZ
through 
`Test = Image.open(r"C:\Users\xdutf\OneDrive\Documents\Raging Bloodgil.png")`

`OCR_text = pytesseract.image_to_string(Test)[:-1]`

`print(OCR_text)`
returns "istTe fare m= celexeeli |"

and
`Test = Image.open(r"C:\Users\xdutf\OneDrive\Documents\Young Sea Dragon.png")`

`OCR_text = pytesseract.image_to_string(Test)[:-1]`

`print(OCR_text)`
returns "a Zolvlare Bst-1-MPLE-le(el]

### Expected Behavior:
Returns the text "Raging Bloodgill" and "Young Sea Dragon" respectfully

### Suggested Fix:
I do not know

**Comment by zdenop** [comment]
Suggested Fix: reading [documentation](https://github.com/tesseract-ocr/tessdoc).
