### ISSUE TITLE
Problem with .uzn file for tesseract 

### ISSUE THREAD

**Issue by simas2275** [tesseract-ocr/tesseract#3837]
### Environment

* **Tesseract Version**: 5.1.0
* **Platform**: Windows 10 64bit

### Problem with .uzn file
After working with tesseract 4.1.0 everything worked perfectly. I used command `tesseract inputPhotoName.png outputName -l eng --oem 1 --psm 4 hocr` and tesseract automatically picked up `inputPhotoName.uzn` zone file and returns word which I have specified with coordinates. After I upgraded tesseract version from 4.1.0 to 5.1.0, tesseract 5.1.0 no longer takes `inputPhotoName.uzn` zone file and returns all founded words in image. 
After a lot of searching I cant find a solution how can I pass `inputPhotoName.uzn` file to tesseract 5.1.0. Maybe tesseract 5.1.0 no longer support .uzn files?

**`inputPhotoName.uzn` file content**: 215 3334 95 19
**Tesseract 4.1.0/5.1.0 commands**: tesseract inputPhotoName.png outputName -l eng --oem 1 --psm 4 hocr

**Comment by simas2275** [comment]
> Please try the latest code.

Now everything is working perfectly. Thanks!

**Comment by stweil** [comment]
The bug which is now fixed was introduced in commit 4b84a56d8.

**Comment by amitdo** [comment]
A new unittest for testing this functionality would be useful.
