### ISSUE TITLE
ProgressNotifier issue

### ISSUE THREAD

**Issue by iAlex97** [tesseract-ocr/tesseract#384]
I'm using the tess-two which is a fork of this repo made use in android projects. Since the latest version, the progress notifier for the word recognition no longer works (it stays at 0% then jumps to 100% when the OCR is done)

**Comment by zdenop** [comment]
1. Use tesseract forum for asking support
2. Do not use this issue tracker for project (if you have issue with tess-two - report it to tess-two authors/maintainers)
