### ISSUE TITLE
Thread limit errror

### ISSUE THREAD

**Issue by stiffchoco** [tesseract-ocr/tesseract#3840]
I ot the following error, while attempting ocr in my laravel project Error! The command did not produce any output. Generated command: OMP_THREAD_LIMIT=1 "tesseract" "tmp-img/4a1c5fb1-749b-420c-bf98-c0d6b7def428_1.jpg" "/tmp/ocrAlisjY" -l rus Returned message: Estimating resolution as 295

**Comment by zdenop** [comment]
Please respect the guidelines for posting issues!
Provide all necessary information + images for reproducing the problem. Make sure you read the [documentation first](https://github.com/tesseract-ocr/tessdoc/blob/main/ImproveQuality.md).

**Comment by amitdo** [comment]
The title does not match what is described in the issue.

**Comment by stiffchoco** [comment]
thanks for your help but, I was able to resolve it
