### ISSUE TITLE
XDG Specification

### ISSUE THREAD

**Issue by wael444** [tesseract-ocr/tesseract#3842]
> Please report an issue only for a BUG, not for asking questions.

### honestly, i don't think this is a bug but rather something missing.
------------------------

### Environment

* **Tesseract Version**: 
```
tesseract 4.1.1
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.1) : libpng 1.6.37 : libtiff 4.4.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
```
* **Platform**: 
```
Linux void-live 5.18.2_1 #1 SMP PREEMPT_DYNAMIC Mon Jun 6 13:41:56 UTC 2022 x86_64 GNU/Linux
```

### Current Behavior:
`$HOME/.tesseract`:
```
~/.tesseract
~/.tesseract/config
~/.tesseract/config/restore.cfg
~/.tesseract/config/init.cfg
~/.tesseract/config/servers.cfg
~/.tesseract/config/saved.cfg
```
### Expected Behavior:
```
~/.config/tesseract/
~/.config/tesseract/restore.cfg
~/.config/tesseract/init.cfg
~/.config/tesseract/servers.cfg
~/.config/tesseract/saved.cfg
```
### Suggested Fix:
follow the xdg specification:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by stweil** [comment]
None of the files mentioned here are used by the Tesseract code. Obviously you installed some other software which perhaps uses Tesseract but has its own conventions. Please identify that software and report the issue there.

**Comment by stweil** [comment]
Do those files belong to the Tesseract first-person shooter game (http://tesseract.gg/)? That's the same name, but otherwise completely unrelated to Tesseract OCR.

**Comment by wael444** [comment]
> That's the same name, but otherwise completely unrelated to Tesseract OCR.

oh my god i did not realize that i am so sorry
