### ISSUE TITLE
existing model trained by other tools

### ISSUE THREAD

**Issue by wanghaisheng** [tesseract-ocr/tesseract#385]
i am using https://github.com/tmbdev/clstm
and https://github.com/tmbdev/ocropy to train some rnn based model ,is there any way  to load such models in Tesseract?

**Comment by zdenop** [comment]
1. Use tesseract user forum for asking question/support
2. We do not provide support for external project.

**Comment by amitdo** [comment]
@wanghaisheng, short answer: No.

**Comment by wanghaisheng** [comment]
@amido  thx any way, i notice you working on both projects then came this question

**Comment by amitdo** [comment]
My user name is @amitdo, not amido :)

**Comment by wanghaisheng** [comment]
@amitdo my fault~
