### ISSUE TITLE
Tesseract can not recognize small superscript numbers behind words

### ISSUE THREAD

**Issue by Golddouble** [tesseract-ocr/tesseract#3853]
### Environment

* **Tesseract Version**: 4.0.0-2
* **Platform**: MX Linux-19 64bit (Debian 10 based)

Sometimes I have texts where the word is followed by a superscript number, because there are clues to that word at the bottom of the page.

### Current Behavior:
It can not recognize the small number "1".

### Expected Behavior:
It should recognize the small Number "1"

Gif-Animation:
![OCr training](https://user-images.githubusercontent.com/13977359/175815094-ebf5f435-9968-4009-8d32-2346c0d62187.gif)

Question:
So I guess this is a mix of letters and numbers in one word and at the same time different font sizes in the same word. Is there a way, to train Tesseract, so that it can correct recognize this small numbers?

Thank you.

**Comment by amitdo** [comment]
Related old discussion: https://github.com/tesseract-ocr/langdata/issues/62

**Comment by Golddouble** [comment]
Thank you @amitdo for the link.

The issue in this link looks like fizzling out.
So you want to say, that I can/have to train the recognition of superscript numbers in tesseract 4 ?

**Comment by amitdo** [comment]
Yes, you got it right.

Note that we're talking here about the LSTM OCR engine. The older OCR engine still exists in Tesseract 4/5. I don't remember how well it supports superscripts with the official training models.

**Comment by Golddouble** [comment]
Thank you.
