### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by Lambdac0re** [tesseract-ocr/tesseract#3859]
### Environment

* **Tesseract Version**:
```
tesseract 5.1.0
 leptonica-1.79.0
  libgif 5.1.9 : libjpeg 6b (libjpeg-turbo 2.0.6) : libpng 1.6.37 : libtiff 4.2.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.4.0
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.4.3 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.8
 Found libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
```
* **Commit Number**: debian binary
* **Platform**:  `Linux ip-172-31-76-234 5.10.0-14-cloud-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux`

### Current Behavior:
Using
`tesseract stdin stdout -l eng --oem 3 --psm 3`
this [image ](https://i.imgur.com/1gILv.png) produces following output:
`Floating point exception`

### Expected Behavior:
No floating point exception

### Suggested Fix:
?

**Comment by stweil** [comment]
Does the exception also happen if you don't use `stdin` but pass the image filename?

**Comment by stweil** [comment]
This issue was fixed in Leptonica commit https://github.com/DanBloomberg/leptonica/commit/480f5e74c24fdc2003c42a4e15d1f24c9e6ea469.
