### ISSUE TITLE
SW based CI broken regulary

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#3861]
@egorpugin 

This situation must be change, otherwise IMO we should stop using sw in the ci.

Could you only use stable, tested releases of sw?

if it's possible, I suggest to automatically  monitor sw ci, and after 2 serial failures, try to move back to the previous version.

**Comment by amitdo** [comment]
It was broken most of the time in the last 9 weeks, so it's not just the the dns thing.

Most of the failures ares due to error from sw.

**Comment by egorpugin** [comment]
`main` is green now.
I hope it will be stable from now.
Nightly failed on macos running all tests. I'll monitor it and disable lstm tests if the issues persists.

**Comment by amitdo** [comment]
You should split the 'sw.yml' file to two (sw, sw-win) or three files (sw-win, sw-mac, sw-linux), so the jobs won't exceed 6 hours.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/actions/runs/2673923745

This action runs **all** the tests without a problem on macOS 10.15 using Autotools and Homebrew.

-----

https://github.com/tesseract-ocr/tesseract/actions/runs/2673919562

This action runs **all** the tests on Ubuntu with Autotools and apt-get. The testing  process is MUCH faster than the one that runs with sw on Ubuntu. 

-----

sw

https://github.com/tesseract-ocr/tesseract/actions/runs/2667120450

**Comment by egorpugin** [comment]
Well, sw build deps during the process.

**Comment by amitdo** [comment]
I'm talking only about the testing phase in a job. Ignore the download and build time. If you enter to a specific job report, you can see the time it took to each phase to complete its tasks.

**Comment by egorpugin** [comment]
Could you point me directly on what times you are looking at?

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/runs/7350227421?check_suite_focus=true

`Make and run Unit Test 57m 8s`

-----

https://github.com/tesseract-ocr/tesseract/runs/7350215799?check_suite_focus=true

`Make and run Unit Test 53m 23s`

-----

sw

Ubuntu

https://github.com/tesseract-ocr/tesseract/runs/7331508265?check_suite_focus=true

`test-nightly 2h 46m 28s`

macOS

with **all** tests

https://github.com/tesseract-ocr/tesseract/runs/7260026383?check_suite_focus=true

`test-nightly 4h 58m 18s`

`Error: The operation was canceled`

**Comment by egorpugin** [comment]
Yes, you can check sw test command:
`./sw -static -shared -config "d,r" test -Dwith-tests=1`

It runs 4 configs in a row: static,shared x debug,release (2x2=4).
I assume non sw runs test only one configuration.

**Comment by amitdo** [comment]
I see.

Are all 4 modes necessary for PRs?

**Comment by egorpugin** [comment]
No, we can leave them only for nightly.

**Comment by amitdo** [comment]
@egorpugin, please fix the broken CI.

**Comment by amitdo** [comment]
@egorpugin,

sw fails for several days. There is a problem with webp.

There was a similar issue with cmake: https://github.com/tesseract-ocr/tesseract/commit/15200c6fe7733f71a6cf52fbc1e4d94150f9f168

**Comment by egorpugin** [comment]
Should be ok now.

**Comment by amitdo** [comment]
SW fails on Ubuntu in the last 7 days. There is some issue with glib.

**Comment by amitdo** [comment]
CI, SW on macOS 12 fails almost immediately for several days.

**Comment by egorpugin** [comment]
Looks like there is some race during setup phase.
I've made possible fix, lets see if it helps.

**Comment by amitdo** [comment]
>It runs 4 configs in a row: static,shared x debug,release (2x2=4).

>Are all 4 modes necessary for PRs?

>No, we can leave them only for nightly.

Can you make this change?

**Comment by egorpugin** [comment]
What do we need for PR? Shared release only?

**Comment by amitdo** [comment]
Choose what you want, shared or static.
