### ISSUE TITLE
OCR accuracy issue

### ISSUE THREAD

**Issue by momo898989** [tesseract-ocr/tesseract#3868]
Hi 
I have an OCR accuracy issue which was reported at this google forum as well.
https://groups.google.com/g/tesseract-ocr/c/v5DEFQgU3kk

Tesseract OCR V4 and 5 didn't detect Text OCR properly from this image.
[test.zip](https://github.com/tesseract-ocr/tesseract/files/9115590/test.zip)
```
1.1. Purpose of this document... ccc ccc ceecsetecsesceecseecsescsecsesescscsececneseeenesseessseenans
1.2. U.S. Electronic Submission Back ground 00.0.0... ccc ee ccetecseseeeceetetseeeneeeeenseseneceeeneeeenees
```

But I noticed that OCR shipped Adobe Acrobat (I think it's IRIS OCR) can work with this image well.

Is it a kind of bug or limitation of Tesseract OCR? or an issue on the sample image?

Thanks
Jason

**Comment by amitdo** [comment]
This is a known [issie](https://github.com/tesseract-ocr/tesseract/labels/TOC) of Tesseract's LSTM OCR engine.
