### ISSUE TITLE
Error:Assert failed:in file ../ccutil/tessdatamanager.h, line 173

### ISSUE THREAD

**Issue by javasgl** [tesseract-ocr/tesseract#387]
![code](https://cloud.githubusercontent.com/assets/5222868/17615147/be407af4-609e-11e6-8d1d-8b711e242506.png)
![env](https://cloud.githubusercontent.com/assets/5222868/17615151/c542e51c-609e-11e6-872d-ff4bf757fbc8.png)

**Comment by javasgl** [comment]
what is the cause  of this error?

**Comment by zdenop** [comment]
user

**Comment by prodanovic** [comment]
Lol, check out this link https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/JZ9G3D5HHNM/A--DXmm2BgAJ

**Comment by IamDixit** [comment]
had a similar issue.
Got it solved by taking a new training set from https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#updated-data-files-for-version-400-september-15-2017
