### ISSUE TITLE
segfault during debug

### ISSUE THREAD

**Issue by rmast** [tesseract-ocr/tesseract#3875]
------------------------

### Environment

* **Tesseract Version**: 5.2.0
* **Commit Number**: commit 8c573e4cefaa011de2b303fa4c967ac943dc55a6 (HEAD, stweil/main)
* **Platform**: Linux Ubuntu20b 5.15.0-1014-azure # 17~20.04.1-Ubuntu SMP Thu Jun 23 20:01:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

./configure --enable-graphics --enable-debug -disable-legacy

### Current Behavior:
tesseract  --dpi 300 -l Latin -c textord_restore_underlines=1 -c textord_show_final_rows=1 -c textord_debug_tabfind=1 -c textord_debug_bugs=1 175789293-f39ddfdb-6f3e-4598-8d16-80a1f4a88b36.jpg outputwithoutinvert3

[picture](https://user-images.githubusercontent.com/3341558/179373903-ef6cc246-f4e5-4633-a762-ded4dd22708f.jpg)

[ 3098.848254] tesseract[7316]: segfault at 18 ip 00007fda7f267264 sp 00007ffdacd759b0 error 4 in libtesseract.so.5.0.2[7fda7f0ef000+1c5000]
![image](https://user-images.githubusercontent.com/3341558/179633421-c459f5c3-a52a-4804-9f9c-2c7d5fa3dd33.png)

### Expected Behavior:
No dump

**Comment by stweil** [comment]
The crash occurs because `to_win` is used but was not created.

**Comment by stweil** [comment]
I fixed this issue in commit 99d6717c101308a4346f8fada011966905d2f1f2.
