### ISSUE TITLE
While running box.train I am getting this error. file name is correct. I was first trying it on tesseract 5.1 but it was giving just error during processing. then i downgraded to 4.0 alpha but it's giving this error.

### ISSUE THREAD

**Issue by ammar3010** [tesseract-ocr/tesseract#3884]
C:\Users\SAMSUNG\Desktop\tesseract training\train>tesseract eng.arial.exp1.tif train.my.exp1 box.train
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Page 1
Error during processing.
ObjectCache(660C5A88)::~ObjectCache(): WARNING! LEAK! object 01015950 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatalstm-punc-dawg)
ObjectCache(660C5A88)::~ObjectCache(): WARNING! LEAK! object 00FEFA78 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatalstm-word-dawg)
ObjectCache(660C5A88)::~ObjectCache(): WARNING! LEAK! object 00FEFB28 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatalstm-number-dawg)
ObjectCache(660C5A88)::~ObjectCache(): WARNING! LEAK! object 032D6DB8 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatapunc-dawg)
ObjectCache(660C5A88)::~ObjectCache(): WARNING! LEAK! object 00FEFA18 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddataword-dawg)
ObjectCache(660C5A88)::~ObjectCache(): WARNING! LEAK! object 032D6F80 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatanumber-dawg)
ObjectCache(660C5A88)::~ObjectCache(): WARNING! LEAK! object 049B6038 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatabigram-dawg)
ObjectCache(660C5A88)::~ObjectCache(): WARNING! LEAK! object 049B6670 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatafreq-dawg)

**Comment by zdenop** [comment]
Please respect the guidelines for posting issues!
Use the latest version of the tesseract.
Provide all necessary information + images and other files for reproducing the problem. 
Make sure you read the documentation first.
