### ISSUE TITLE
Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.

### ISSUE THREAD

**Issue by Pyprog08** [tesseract-ocr/tesseract#3887]
Hi,
i write to a python code that use tesseract to extract English and German words. It works well. i tried to use it on Docker but i had this error: 
Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.
Failed loading language \'deu\' Tesseract couldn\'t load any languages! Could not initialize tesseract.

this is what i use :
` text = pytesseract.image_to_string(imm,config='--psm 11 --oem 1 --tessdata-dir "C:\Program Files\Tesseract-OCR\tessdata" ',lang='deu+eng')`
in the requirments.txt i installed pytesseract and tesseract then i used this commad : RUN apt-get update && apt-get install tesseract-ocr -y
But it didnt work
Can you help me ?

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

You use a Windows path as argument for `--tessdata-dir`. That cannot work in a Docker / Linux environment which expects Linux paths.
