### ISSUE TITLE
TesseractError: (-8, 'Estimating resolution as 1600')

### ISSUE THREAD

**Issue by prati2a22** [tesseract-ocr/tesseract#3890]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/main/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 5.2.0
* **Commit Number**: 
* **Platform**: Ubuntu 20 

### Current Behavior:
Using tesseract 5 via pytesseract and it throws the error:

pytesseract.image_to_string(cell_img, lang='eng')).strip()
File "/data/anaconda3/envs/tabstructnet_py_3.6/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 417, in image_to_string
}[output_type](https://github.com/madmaze/pytesseract/issues/449)
File "/data/anaconda3/envs/tabstructnet_py_3.6/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 416, in
Output.STRING: lambda: run_and_get_output(*args),
File "/data/anaconda3/envs/tabstructnet_py_3.6/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 284, in run_and_get_output
run_tesseract(**kwargs)
File "/data/anaconda3/envs/tabstructnet_py_3.6/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 260, in run_tesseract
raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (-8, 'Estimating resolution as 1600')

### Expected Behavior:
Tried increasing the timeout value but still kept getting the error.

**Comment by zdenop** [comment]
Please respect the guidelines for posting issues: we do not provide support for 3rd party projects. Reproduce the problem with the tesseract executable and provide all necessary information + images for reproducing the problem. Make sure you read the documentation first.

**Comment by NaziTexh** [comment]
@@@@@@@@@@@[](url)
