### ISSUE TITLE
Failed to read data/tessdata/eng.traineddata

### ISSUE THREAD

**Issue by ajyothirmayi-bhargavi** [tesseract-ocr/tesseract#3897]
I am trying to train a model on top of  the english model. When I run the train command ;It gives the following error.

combine_tessdata -u data/tessdata/eng.traineddata  data/eng/foo
Failed to read data/tessdata/eng.traineddata
make: *** [Makefile:156: data/foo/unicharset] Error 1

I have downloaded the eng.traineddata from /tesseract-ocr/tessdata_best/blob/main/eng.traineddata

**Comment by MuFazil** [comment]
I am also facing the same issue
