### ISSUE TITLE
segmentation fault  shapeclustering -F

### ISSUE THREAD

**Issue by Daniel-ccx** [tesseract-ocr/tesseract#3898]
### Environment

* **Tesseract Version**: tesseract 5.2.0
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.3) : libpng 1.6.37 : libtiff 4.4.0 : zlib 1.2.11 : libwebp 1.2.4 : libopenjp2 2.5.0
 Found NEON
 Found libarchive 3.6.1 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.2
 Found libcurl/7.79.1 SecureTransport (LibreSSL/3.3.6) zlib/1.2.11 nghttp2/1.45.1
* **Commit Number**: build from main branch
* **Platform**: Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64

### Current Behavior:
shapeclustering -F font_properties -U unicharset pytones.fontjj.001.tr
output:
Reading pytones.fontjj.001.tr ...
[1]    97967 segmentation fault  shapeclustering -F font_properties -U unicharset pytones.fontjj.001.tr

**Comment by Daniel-ccx** [comment]
So I have to checkout branch 4.1 and passed

**Comment by amitdo** [comment]
>So I have to checkout branch 4.1 and passed

What do you mean?

**Comment by zdenop** [comment]
reporting issue without information/data/files for reproducing problem is useless...

**Comment by amitdo** [comment]
See #3925.
