### ISSUE TITLE
CI: msys2 jobs fail

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#3905]
~~since https://github.com/tesseract-ocr/tesseract/actions/runs/2706394219~~

since https://github.com/tesseract-ocr/tesseract/actions/runs/2699330828

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/runs/7940382175?check_suite_focus=true

`make training`

is ignored for some reason, and then

`make training-install`

is executated and it fails because the necessary files were not created.

**Comment by amitdo** [comment]
Last successful build:
https://github.com/tesseract-ocr/tesseract/actions/runs/2692193509

**Comment by amitdo** [comment]
It seem that https://github.com/tesseract-ocr/tesseract/tree/ee34b100bf9b54d3f201c7417d263988a9ad0b3f is the reason to the msys2 failure. macOS and Ubunto were not affected.

**Comment by amitdo** [comment]
@stweil, I undo the changes made in `Makefile.am` in commit 8c573e4cefaa011d and the msys2 jobs ran successfully.

See:
https://github.com/tesseract-msys/tesseract
https://github.com/tesseract-msys/tesseract/actions/runs/2920044195

**Comment by stweil** [comment]
msys2 failed because `.exe` extensions are not automatically added to `trainingtools`. The failure should be fixed by commit b7d7b85834a4fe4ae1d11ae0a315807aa11b6456.

**Comment by amitdo** [comment]
Thanks. I'll close this issue after I'll see the next daily msys2 runner successfully complete it jobs.
