### ISSUE TITLE
Tesseract unstable font property prediction

### ISSUE THREAD

**Issue by ken4ward** [tesseract-ocr/tesseract#3912]
### Environment

* **Tesseract Version**: Tesseract 3.0.5, TessData 3.0.4, Tesserct 5 Java binding 
* **Commit Number**: 
* **Platform**: 21.5.0 Darwin Kernel Version 21.5.0: root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin

### Current Behavior:
I  am using Tesseract 3.0.5 in a project, which is awesome. It works brilliantly well. Lately, I noticed its predictability changes when the same code is run multiple times for the same image text. I was able to train new fonts in different languages. An example is this: when I run to get the font properties of an image, I'm getting these properties: font-name, bold, italic, monospace, serif, and underline. I ran it multiple times on the same image text, and it produces different results for the same image text.

### Expected Behavior:
The text on the image should return this result: 
Ubuntu, FALSE, FALSE, FALSE, FALSE, FALSE, PASS, but subsequent runs produce different results for the same text on the same image. Are there settings to make it more resilient and specific than changing it at every new run?

###Actual behaviour
Runs    Font name    Bold    Italic    Monospace    Serif    Underline    Result
First run:    Ubuntu    FALSE    FALSE    FALSE    FALSE    FALSE    PASS
Second run:   Ubuntu-Italic    FALSE    TRUE    FALSE    FALSE    FALSE    FAIL
Third run:    Ubuntu-Bold    TRUE    FALSE    FALSE    FALSE    FALSE    FAIL

**Comment by stweil** [comment]
Please use the current Tesseract release 5.2.0. Old versions are unsupported.

As you are also using Java bindings you should make sure that is not a problem with that third-party software before reporting it here.

You may re-open the issue if you are sure that it is a Tesseract issue with the latest code.

**Comment by ken4ward** [comment]
Thanks @stweil . The latest Tesseract LSTM doesn’t support font property detection that’s the reason I’m using version 3.0.5. I’ve reviewed the code and have seen that the predictability of Tesseract is unstable, not the third party library.

**Comment by stweil** [comment]
Tesseract 5.2.0 still supports the legacy OCR engine with font properties. There should be no reason to stick to 3.0.5.
