### ISSUE TITLE
Traineddata is the same size as lang best traineddata after training

### ISSUE THREAD

**Issue by Aliw7979** [tesseract-ocr/tesseract#3914]
Hi, I trained 25 fonts and created checkpoints with size of 19MB but after combining old traineddata and checkpoint to create new traineddata, size of the new traineddata is the same as the old one.

I show you all steps and sh codes and every one of them was successful.

1.Generating training files (I extracted lstm from fas.traineddata):

```
rm -rf train/*
tesstrainPy/src/training/tesstrain.py --fonts_dir font \
        --lang fas \
        --noextract_font_properties  --linedata_only \
        --exposures "0" \
        --save_box_tiff \
        --langdata_dir langdata_lstm\
        --tessdata_dir latest/tesseract/tessdata \
        --maxpages 150 \
        --fontlist \
        "IRAban, Regular"          \
        "IRHoma, Regular"               \
        "IRNarges, Regular"             \
        "IRTerafik, Bold"   \
        "IRAmir, Regular"               \
        "IRJadid, Regular"              \
        "IRNaskh, Regular"                      \
        "IRTerafik, Italic" \
        "IRArshia, Regular"             \
        "IRKamran, Regular"             \
        "IRNazanin, Bold"       \
        "IRTerafik, Regular"            \
        "IRBadr, Bold"          \
        "IRKhorasan, Regular"           \
        "IRNazanin, Italic"     \
        "IRTitr, Regular"               \
        "IRBadr, Italic"   \
        "IRKoodak, Regular"       \
        "IRNazanin, Regular"            \
        "IRYakout, Bold"        \
        "IRBadr, Regular"               \
        "IRLotus, Bold"    \
        "IRNazli, Bold"         \
        "IRYakout, Italic"  \
        "IRCompset, Bold"       \
        --output_dir trainforB
```

2.Start training:

```
rm -rf output/*
OMP_THREAD_LIMIT=24 lstmtraining \
        --continue_from latest/tesseract/tessdata/fas.lstm \
        --model_output output/Bfonts \
        --traineddata latest/tesseract/tessdata/fas.traineddata \
        --train_listfile trainforB/fas.training_files.txt \
        --max_image_MB 35000\
        --randomly_rotate true\
        --debug_interval 10\
        --max_iterations 100000\

```

3.stop lstmtraining and create traineddata file:

```
lstmtraining \
         --stop_training \
        --continue_from output/Bfonts_checkpoint \
        --traineddata output/fas.traineddata \
        --model_output output/bfonts.traineddata

```

But after this step I will get traineddata with the same size as old traineddata.
You can see disk usage of each file in KB with this picture:

![Screenshot from 2022-09-04 11-16-06](https://user-images.githubusercontent.com/60917259/188303406-8f924f76-9942-4fc7-81f8-75341d3c9723.png)

### Environment

* **Tesseract Version**:  5.2
* **Platform**: Ubuntu 20.04.4 LTS

### Current Behavior:
New traineddata file is always same size as old traineddata
### Expected Behavior:
New traineddata should be bigger
### Suggested Fix:
I have doubt that my sh codes have some minor issues but I can't figure it out.

**Comment by stweil** [comment]
Why do you expect that the new traineddata should be bigger? The size of the LSTM component only depends on the specification of the neural network, but not on the size of the trained data.

PS. Please don't use screenshots for textual content. Copy + paste the text instead of producing images.

**Comment by Aliw7979** [comment]
I saw a [conversation](https://groups.google.com/g/tesseract-ocr/c/O8EEFSSj7_I) in google group with fewer fonts. 
After shree solved the problem, I thought that maybe my sh codes have problems.
PS. Sorry for uploading screenshots, I will replace them with codes.

**Comment by amitdo** [comment]
As @stweil said, there is no real issue here.
