### ISSUE TITLE
How to support Mac catalyst？

### ISSUE THREAD

**Issue by hardy720** [tesseract-ocr/tesseract#3915]
Our ios project runs on Mac through Catalyst, but "TesseractOCRiOS" runs on Mac with an error.How to support Mac catalyst？

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by hardy720** [comment]
Thank you for your reply. I can't open the link. Is there any other way to help me solve this problem? 

> 2022年9月6日 下午5:57，Stefan Weil ***@***.***> 写道：
> 
>  Tesseract user forum <https://groups.google.com/d/forum/tesseract-ocr>

**Comment by stweil** [comment]
Is the link blocked in China? I just have run a test, and it looks so. Then I am afraid that you have to find a solution for yourself.
