### ISSUE TITLE
Observe white space spaces in result when OCR Japanese.

### ISSUE THREAD

**Issue by shq251** [tesseract-ocr/tesseract#3916]
Tesseract version: Tesseract 5.0.0 beta (Release x86)
Leptonica version: leptonica-1.81.1 (Release x86)
Using "charlesw (https://github.com/charlesw/tesseract)" Wrapper for Tesseract and Leptonica :
tessdata type : tessdata_best (Get from https://github.com/tesseract-ocr/tessdata_best)
Note: in above tessdata_best included "extra spaces in result when ocr chinese #991" issue.

When do OCR observed white spaces into a output txt file.
```
        public void doOCR(string input_file)
        {
            string LANGUAGEs = @"jpn";
            var tessdata = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "tessdata");
            using (var ocrEngine = new TesseractEngine(tessdata, LANGUAGEs, EngineMode.Default))
            {
                var Output = System.IO.Path.ChangeExtension(input_file, null);
                using (IResultRenderer renderer = ResultRenderer.CreateTextRenderer(Output))
                {
                    var imageName = System.IO.Path.GetFileNameWithoutExtension(input_file);
                    using (var pixA = ReadImageFileIntoPixArray(input_file))
                    using (renderer.BeginDocument(imageName))
                        foreach (var pix in pixA)
                            using (var page = ocrEngine.Process(pix, imageName))
                                renderer.AddPage(page);
                }
            }
        }
```
![image0001](https://user-images.githubusercontent.com/85737996/188664796-03cc0f46-807a-4183-bc69-4bcc0840d816.png)
[image0001.txt](https://github.com/tesseract-ocr/tesseract/files/9498070/image0001.txt)

Kindly help to improve this issue.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/3904#issuecomment-1220908229

**Comment by shq251** [comment]
Hi Thank for your reply.

This similar issue happen for OCR to PDF file.

Copied text and save to "image0001.txt", found white spaces.
[image0001.txt](https://github.com/tesseract-ocr/tesseract/files/9507029/image0001.txt)

When we trying to search "string" from input image into output PDF file. Result not found, because of spaces.

Any ways to improve/control spaces at least for PDF file, so string can be search into output PDF file.

**Comment by amitdo** [comment]
As I said, this is a known issue and currently there is no solution.
