### ISSUE TITLE
Installation guide for tesseract 4.00 on Ubuntu

### ISSUE THREAD

**Issue by naourass** [tesseract-ocr/tesseract#3924]
While trying to test the legacy traineddata for Arabic, I discovered that recent versions of tesseract don't support it so I'm trying to install tesseract 4.00 on my Ubuntu 20.04 machine. Is there a binary build or an installation guide for tesseract-ocr 4.00 Focal?

**Comment by stweil** [comment]
All Tesseract versions support the legacy traineddata.

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by naourass** [comment]
@stweil I tested all recent versions from 4.1 and above none of them seems to support legacy trained data of Arabic language. After more research I've found out that the latest commit says:
![image](https://user-images.githubusercontent.com/4897498/191600766-35f2cc63-5ed0-44a8-b9d7-ae331f326d5c.png)

P.S. Legacy traineddata works fine for other languages but not for ara.

**Comment by stweil** [comment]
But you are free to use latest Tesseract with on older version of ara.traineddata which still contains the legacy model.

**Comment by naourass** [comment]
I tried all recent tesseract versions with older tessdata that include the legacy model. Other legacy languages are working fine, Arabic ara will give this error :
`read_params_file: Can't open txt mgr->GetComponent(TESSDATA_INTTEMP, &fp):Error:Assert failed:in file src/classify/adaptmatch.cpp`
