### ISSUE TITLE
scripts vs single languages

### ISSUE THREAD

**Issue by Kate-D-S** [tesseract-ocr/tesseract#3926]
Hello ! 

I need to OCR some poor quality documents which contain different alphabets e.g. german/polish/english.
I got a hint to use script/Latin instead of single languages. (I mean `-l scrpit/Latin`  vs `-l eng+pol+deu` )
 Why is it better? How scrpits works? Are those models for whole alphabets?

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.
