### ISSUE TITLE
Unnecessary space found in output pdf file

### ISSUE THREAD

**Issue by shq251** [tesseract-ocr/tesseract#3927]
We have installed the tesseract build **v5.0** with Japanese Traindata (jpn and jpn_vert) from below location.
https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v5.0.0-rc1.20211030.exe

Case 1: We have used P_00000.jpg input file and prepared "P_00000.txt" text file with Tesseract 5.0 using below command.
``"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe" P_00000.jpg P_00000 -l jpn``
In output text file, no unnecessary spaces found.
Case 2: We have used P_00000.jpg input file and prepared "P_00000.pdf" pdf file with Tesseract 5.0 using below command.
`"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe" P_00000.jpg P_00000 -l jpn pdf`
In output "P_00000.pdf" file, copy the text content and past to Notepad (file name"P_00000.pdf.txt") then observed unnecessary spaces. Output is not as same as "Case 1".
Why unnecessary spaces found in "Case 2" compare not "Case 1"?
Kindly help, How we will generate PDF file for JPN language without spaces
[P_00000.pdf](https://github.com/tesseract-ocr/tesseract/files/9626895/P_00000.pdf)
[P_00000.pdf.txt](https://github.com/tesseract-ocr/tesseract/files/9626896/P_00000.pdf.txt)
[P_00000.txt](https://github.com/tesseract-ocr/tesseract/files/9626897/P_00000.txt)
![P_00000](https://user-images.githubusercontent.com/85737996/191778414-d4344e29-bde0-4255-b403-ddf3f7acb96d.jpg)

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/3916#issuecomment-1239575207

The answer is the same.
