### ISSUE TITLE
Using uzn file, output from command line and programmatically using .net dll are different.

### ISSUE THREAD

**Issue by rhampole** [tesseract-ocr/tesseract#393]
I am using 3.04 tesseract ocr. Running command line like below gives me better result compared to programmatically calling the api.
"tesseract Page_00001_IP.tif Page_00001_IP -l eng -psm 4"

The api is called as follows.
                        var inputName = Path.GetFileName(imageFile).Replace(Path.GetExtension(imageFile), "");
                        using (var page = engine.Process(img, inputName, PageSegMode.SingleColumn))
                        {
                            text = page.GetText();
                        }
I have created the .uzn file same name as the image file. It contains regions specifying Left, Top, Width and Height. I appreciate any help to resolve this.

Thanks,
Ravi

**Comment by zdenop** [comment]
We do not provide support for tesseract wrapers. Please use tesseract user forum.
