### ISSUE TITLE
Wrong numbers dawg inside Arabic.traineddata?

### ISSUE THREAD

**Issue by naourass** [tesseract-ocr/tesseract#3933]
### Environment
* **Tesseract Version**: 5.2.0-40-g3559
* **Platform**: Ubuntu 20.04 on WSL

### Current Behavior:
If you extract [_Arabic.traineddata_](https://github.com/tesseract-ocr/tessdata_best/blob/main/script/Arabic.traineddata) with `combine_tessdata`, and then take the extracted **Arabic.lstm-number-dawg** and convert it to text using `dawg2wordlist`, you get a long list of random words from several scripts rather than numbers. Is this normal?

[extracted_Arabic.number.txt](https://github.com/tesseract-ocr/tesseract/files/9689524/extracted_Arabic.number.txt)

**Comment by amitdo** [comment]
What was the full dawg2wordlist command you used?

Does the other dawg also look wrong?

**Comment by amitdo** [comment]
The Arabic traineddata was trained on languages written with the Latin script along the Arabic script.

https://github.com/tesseract-ocr/langdata_lstm/blob/main/eng/eng.numbers

https://github.com/tesseract-ocr/langdata_lstm/blob/main/fra/fra.numbers

https://github.com/tesseract-ocr/langdata_lstm/blob/main/ita/ita.numbers

etc.

**Comment by naourass** [comment]
@amitdo If you check the nulbers dawg inside Arabic.traineddata you'll find a list doesn't include a single number, only random words from other scripts than Latin or Arabic. When you extract other dawgs like wordlist or punc, it seems accurate, but the numbers one seems suspicious. 

N.B. I want to use the extracted Arabic.number for training, but I'm not sure if it's the right file.

**Comment by amitdo** [comment]
See my above links, they also does not contain numbers.

**Comment by naourass** [comment]
@amitdo That's reassuring, thanks!

Any reference to understand why the numbers dawg contain such strings?

**Comment by naourass** [comment]
Looks like patterns where the empty spaces are digits. Pretty obvious.
