### ISSUE TITLE
I detected as i

### ISSUE THREAD

**Issue by eugaz** [tesseract-ocr/tesseract#3934]
### Environment

* **Tesseract Version**: 5.2.0-1
* **Commit Number**: 
* **Platform**: Linux arch 5.19.11-arch1-1 SMP PREEMPT_DYNAMIC Sat, 24 Sep 2022 18:24:15 +0000 x86_64 GNU/Linux

### Current Behavior:
`I` is transcribed as `i`:
````
tesseract image.png text
````
Test picture:
![](https://i.imgur.com/Z2bYsXJ.png)

Transcribed text:
````
java.net.SocksSocketimpl.connect
````

### Expected Behavior:
Detect proper letters.

**Comment by Moddy2024** [comment]
Can you tell where is the file that is causing this issue so that i can look into it.

**Comment by stweil** [comment]
I just have run a test:
```
tesseract https://camo.githubusercontent.com/7c59373c7004754c214d8feacb05a49ba37e3f3ae6509d9c3ae74f25526abacf/68747470733a2f2f692e696d6775722e636f6d2f5a32625973584a2e706e67 -
Estimating resolution as 547
java.net.SocksSocketImpl.connect
```

So the result looks perfect, and I wonder what was different in your setup.

**Comment by amitdo** [comment]
No feedback from the OP.
