### ISSUE TITLE
segmentation fault  shapeclustering -F font_properties -U unicharset -O chi.unicharset

### ISSUE THREAD

**Issue by jihh** [tesseract-ocr/tesseract#3939]
### Environment

* **Tesseract Version**: 5.2.0-45-gb5ee
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 9d : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.1 : libopenjp2 2.4.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.5.2 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.6 liblz4/1.9.3 libzstd/1.5.0
 Found libcurl/7.64.1 SecureTransport (LibreSSL/2.8.3) zlib/1.2.11 nghttp2/1.41.0
* **Commit Number**: [97a1a3e](https://github.com/tesseract-ocr/tesseract/commit/97a1a3e10f6383e0c4b25d4d141ad6ef71ad0f04)
* **Platform**: Darwin <hostname_hide> 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64

### Current Behavior:

```
% tesseract chi.pgssub.ocr.tif chi.pgssub.ocr -l chi_sim -psm 7 batch.nochop makebox
...
% <adjust box file by jTessBoxEditor >
...
% echo pgssub 0 0 0 0 0 >font_properties
...
% tesseract chi.pgssub.ocr.tif chi.pgssub.ocr -l chi_sim -psm 7 nobatch box.train
...
% unicharset_extractor chi.pgssub.ocr.box
...
% % shapeclustering -F font_properties -U unicharset -O chi.unicharset chi.pgssub.ocr.tr        
Reading chi.pgssub.ocr.tr ...
zsh: segmentation fault  shapeclustering -F font_properties -U unicharset -O chi.unicharset 

% shapeclustering` -F font_properties -U unicharset chi.pgssub.ocr.tr
Reading chi.pgssub.ocr.tr ...
zsh: segmentation fault  shapeclustering -F font_properties -U unicharset chi.pgssub.ocr.tr
```

### Attachments

* chi.pgssub.ocr.tif
* chi.pgssub.ocr.box
* font_properties

[file.zip](https://github.com/tesseract-ocr/tesseract/files/9724351/file.zip)

**Comment by amitdo** [comment]
[shapeclustering](https://github.com/tesseract-ocr/tessdoc/blob/2aeef9fc4709c19c3845b8d724b9e3128f5742ad/tess3/Training-Tesseract-3.03%E2%80%933.05.md#shapeclustering)

>shapeclustering should not normally be used except for the Indic languages. 

It is not needed for Chinese.

**Comment by amitdo** [comment]
See #3925.
