### ISSUE TITLE
tesseract cannot detect large texts.

### ISSUE THREAD

**Issue by openedhardware** [tesseract-ocr/tesseract#394]
Hello, everyone.

I have been developing text detecting APP with tesseract.

I have found weird issue that tesseract could not detect large texts on image.

Here is the original image:
http://i67.tinypic.com/23ur420.jpg

When I apply tesseract to this image, I get some text like this:

    GETUNTUPUF

    BUBBLE.

    BEFORE YOUR
    COMPETITION
    DUES

(NOTE: it does not matter to detect text correctly or not, I am just interested whether tesseract detects text or not.)

Here is the image I had detect text area from the original image.
http://i67.tinypic.com/qovfj9.png

Unfortunately when I apply tesseract to this image, I have got no text at all.

Any idea?

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support (please read&use [relevant wiki](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality) before).
