### ISSUE TITLE
Regression: gif not scraping in 5.2 that was OK in 5.1

### ISSUE THREAD

**Issue by jacekkopecky** [tesseract-ocr/tesseract#3940]
### Environment

* **Tesseract Version**: v5.2.0.20220712
* **Platform**: Windows 10, x64

### Current Behavior:

`tesseract.exe` v 5.2 only scrapes top line (window title) from this `gif` image:

<img width="300" alt="image-screenshot-pdf.gif" src="https://user-images.githubusercontent.com/807315/194534960-3c8ab221-910f-42af-a8d9-eb34d8b458f9.gif">

### Expected Behavior:

It should scrape all text.

Tesseract  v5.1.0.20220510 worked as expected, and both 5.1 and 5.2 work as expected with this equivalent `png` image:

<img width="300" alt="image-screenshot-pdf.png" src="https://user-images.githubusercontent.com/807315/194535081-097e4044-47bc-4a70-8f45-7788d69470ec.png">

### Suggested Fix:

It might have something to do with a different DPI estimation: 5.2 estimates resolution 132, while 5.1 estimated 168. However, running 5.2 with `--dpi 168` does not seem to fix anything.

**Comment by amitdo** [comment]
What's the output of tesseract -v for each version?

I want to see if the leptonica and gif library are used are exactly the same.

**Comment by jacekkopecky** [comment]
```
tesseract v5.1.0.20220510
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0
```

```
tesseract v5.2.0.20220712
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0
```

**Comment by zdenop** [comment]
It seems like there is a problem with thresholding/binarization :

`tesseract i3940.gif i3940.gif get.images` produced:

![i3940 gif processed](https://user-images.githubusercontent.com/574156/194582976-ebf48f3c-ca20-4fb9-b10f-c9c5c9f32ebc.jpg)

`tesseract i3940.png i3940.png get.images` produced:

![i3940 png processed](https://user-images.githubusercontent.com/574156/194583182-b57789cc-42bb-4a59-8a19-4aea2574e845.jpg)


By the way: gif has 256 colors (8 BitsPerPixel), and png version has 16,7 Million colors (32 BitsPerPixel)

**Comment by zdenop** [comment]
@amitdo : that commit is not the problem:  the input gif image has already an 8-bit depth, so it just makes a copy of it.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/compare/5.1.0...5.2.0

**Comment by zdenop** [comment]
ok. I got it: problem is causing Colormap.

**Comment by zdenop** [comment]
Explanation of problem/dilemma:

1. removing a colormap from a 8bit color image returns [32bit image](https://github.com/DanBloomberg/leptonica/blob/8afda76154789bedb82cf976e6485fbfb89c5d55/src/pixconv.c#L316-L320) => output pdf file size will increase - see issue #3092.
2. not removing colormap cause problem on images like above (interesting is that also image from issue 3092 is the 8bit  with colormap)
