### ISSUE TITLE
Very long question in the title [edited]

### ISSUE THREAD

**Issue by nissansz** [tesseract-ocr/tesseract#3945]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/main/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.
 

------------------------

### Environment

* **Tesseract Version**:  5.0
* **Commit Number**: 
* **Platform**:  win10 64bit

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.
