### ISSUE TITLE
libtesseract.so is gone after Tesseract-5.2.0 is built

### ISSUE THREAD

**Issue by viisautta** [tesseract-ocr/tesseract#3953]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/main/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment
Tesseract-5.2.0
Fedora 36

### Current Behavior:

cannot find libtesseract.so but libtesseract.a
[o@fedora build]$ find . -name "*.so*"
[o@fedora build]$ 
[o@fedora build]$ 
### Expected Behavior:
libtesseract.so is built ok.

**Comment by zdenop** [comment]
We do not provide binary packages. Contact provider of tesseract package for Fedora.
