### ISSUE TITLE
ionic x tesseract integrate with lang 7seg or similar to detect digital number 

### ISSUE THREAD

**Issue by davdavcoco** [tesseract-ocr/tesseract#3956]
I'm making ionic app and use tesseract to read digital number.
my guide is simon : https://www.youtube.com/watch?v=c6MyNU0jp28

after searching and i found i have to use like external traineddata like 7seg (https://github.com/Shreeshrii/tessdata_ssd). but i can't integrate it with my ionic app..

i try to add : 
corePath: "../../assets/scripts/tesseract-core.wasm.js",
workerPath: "../../assets/scripts/worker.min.js",
langPath: "../../assets/scripts/lang-data",

in my lang-data : 7seg.traineddata

await this.worker.loadLanguage("7seg");
await this.worker.initialize("7seg");

and its not work. it try to download the 7seg as zip. but shows error can't load language. any suggestion?

"tesseract.js": "^3.0.3"

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.
