### ISSUE TITLE
PDF renderer: Tesseract inserts spaces for non-text blocks it finds

### ISSUE THREAD

**Issue by bleze** [tesseract-ocr/tesseract#3957]
### Environment

* **Tesseract Version**: 5.2.0 and 4.1.3
* **Platform**:  Windows 10, x64

### Current Behavior:

Spaces are found by Tesseract and inserted in output PDF. It seems to be confused by the horizontal lines in the attached image.
I use this PDF to overlay on top of another PDF which already contains text, and this causes problems in the resulting PDF due to intersections.

### Expected Behavior:

Tesseract finding standalone spaces does not make sense to me. I would expect Tesseract to only find characters in the logo and disregard the lines. At least the lines should be underscores or something - not spaces.

### Suggested Fix:

Unsure if problem should be fixed in Tesseract or if the spaces should be filtered in the PDF renderer. I think Tesseract as it will fix all output formats.

![spaces](https://user-images.githubusercontent.com/1309917/199941539-66fa8776-5e0c-40d7-ad28-c99b28a35073.png)

**Comment by amitdo** [comment]
Please post hocr output.

**Comment by bleze** [comment]
hocr file created like this; tesseract.exe "C:\Tesseract\v.png" "c:\tesseract\v" --tessdata-dir "C:\Tesseract\tessdata_best-main" -l dan --psm 4 --oem 1 -c tessedit_create_hocr=1

Let me know if these parameters at not correct, thanks.

[v.zip](https://github.com/tesseract-ocr/tesseract/files/9948902/v.zip)

**Comment by amitdo** [comment]
Tesseract see this as a photo + a few line separators.

The hocr renderer correctly drop the spaces.

The pdf renderer should ignore any non-text blocks.

**Comment by amitdo** [comment]
Related PR: #3723.

**Comment by amitdo** [comment]
I tested it and it hangs forever. Seems the loop never ends. I'll see if I can fix it.

**Comment by amitdo** [comment]
@bleze,

See the fixed pdf output here:
https://github.com/tesseract-ocr/tesseract/pull/3959#issuecomment-1306716566
