### ISSUE TITLE
Replace deprecated LGTM by GitHub CodeQL

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#3958]
[LGTM announces that it will shut down in December 2022](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) and suggests to replace it by CodeQL.

This requires an update of README.md and adding the GitHub action.

**Comment by amitdo** [comment]
LGTM is showing [32 alerts (31 warnings, 1 recommendation)](https://lgtm.com/projects/g/tesseract-ocr/tesseract/alerts?mode=tree) while CodeQL is showing just [17 alerts](https://github.com/tesseract-ocr/tesseract/security/code-scanning).

**Comment by amitdo** [comment]
If you compare **security** alerts, both LGTM and CodeQL have 17 alerts.

https://lgtm.com/projects/g/tesseract-ocr/tesseract/alerts?mode=tree&tag=security

**Comment by amitdo** [comment]
There is an option to show more alerts (like LGTM does):

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs

**Comment by amitdo** [comment]
BTW, the severity of the 17 **security** alerts is marked as '**high**'.

**Comment by amitdo** [comment]
Should we remove [.lgtm.yml](https://github.com/tesseract-ocr/tesseract/blob/main/.lgtm.yml) now or wait for the final shutdown?

**Comment by stweil** [comment]
> Should we remove [.lgtm.yml](https://github.com/tesseract-ocr/tesseract/blob/main/.lgtm.yml) now or wait for the final shutdown?

Done, see commit c01ddc033c71f4833463665d74a371617c556307.
