### ISSUE TITLE
Tesseract does not support SIMD instructions on FreeBSD with amd64

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#3964]
The current autoconf build does not enable SIMD detection and compiler flags when running on FreeBSD for 64 bit AMD / Intel CPUs. This results in bad performance, and `tesseract -v` cannot show SIMD support (see https://github.com/tesseract-ocr/tesseract/issues/3960#issuecomment-1309994992).

**Comment by stweil** [comment]
I'll commit a fix.

**Comment by stweil** [comment]
With a fix in configure.ac the compiler builds the code for SIMD, but the values from get_cpuid don't show any SIMD support when running FreeBSD in my test with a QEMU virtual machine.

**Comment by stweil** [comment]
Cc @pkubaj who seems to be the maintainer for [Tesseract on FreeBSD](https://www.freshports.org/graphics/tesseract).

**Comment by amitdo** [comment]
https://gitlab.com/qemu-project/qemu/-/issues/164

**Comment by stweil** [comment]
`qemu -cpu host` passes all host features through to the virtual machine.

**Comment by amitdo** [comment]
CMake:

```
if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86|x86_64|AMD64|amd64|i386|i686")
...
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64.*|AARCH64.*")
```
Should we do something similar with Autotools?

**Comment by stweil** [comment]
I don't think that is necessary. See `https://git.savannah.gnu.org/cgit/config.git/plain/config.guess` for the values which can be detected automatically.

**Comment by stweil** [comment]
FreeBSD provides an old version of config.guess (timestamp='2018-08-29') which returns `amd64-unknown-freebsd13.1`. Recent versions of config.guess never return `amd64` for the CPU, but always use `x86_64`.
