### ISSUE TITLE
How to install tesseract 4.4.0 with brew or port ?

### ISSUE THREAD

**Issue by dschiller** [tesseract-ocr/tesseract#3965]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/main/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**: 

### Suggested Fix:

Refers to this isse where we need to install another version of tesseract: https://github.com/rainmanwy/robotframework-SikuliLibrary/issues/180

Are there any know brew taps out there which support installing tesseract 4.4.0 ?

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.
