### ISSUE TITLE
Terminate because of 'std::bad_alloc'

### ISSUE THREAD

**Issue by peterlawkp** [tesseract-ocr/tesseract#3966]
### Environment

* **Tesseract Version**: tesseract-ocr=4.1.1-2.1     tesseract-ocr-eng=1:4.00~git30-7274cfa-1.1
* **Platform**: linux-amd64

### Current Behavior:
I am running tesseract in docker.
The docker contains another java spring application.
Here is the error:

Error in pixSubtract: depths of pixs* unequal
Error in pixSubtract: pixs1 not defined
Error in pixErodeBrick: pixs not defined
Error in pixSeedfillBinary: pixs undefined or not 1 bpp
Error in pixOr: pixs1 not defined
Error in pixSubtract: pixs1 not defined
Error in pixGetWidth: pix not defined
Error in boxCreate: w and h not both >= 0
Error in pixClipRectangle: pixs not defined
Error in pixCountPixels: pixs not defined or not 1 bpp
Error in pixErodeBrick: pixs not defined
Error in pixSeedfillBinary: pixs undefined or not 1 bpp
Error in pixOr: pixs1 not defined
Error in pixGetHeight: pix not defined
Error in pixClipRectangle: pixs not defined
Error in pixCountPixels: pixs not defined or not 1 bpp
Error in pixGetHeight: pix not defined
Error in boxCreate: w and h not both >= 0
Error in pixClipRectangle: pixs not defined
Error in pixCountPixels: pixs not defined or not 1 bpp
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f5dafbe2602, pid=1, tid=291

 JRE version: OpenJDK Runtime Environment xxx
 Java VM: OpenJDK 64-Bit Server VM xxx
 Problematic frame:
 C  [libc.so.6+0x22602]  abort+0x1ee

 Core dump will be written. Default location: //core.1

 An error report file with more information is saved as:
 /tmp/hs_err_pid1.log
Detected 8 diacritics

Native Memory Tracking:

Total: reserved=3578231KB, committed=867875KB
-                 Java Heap (reserved=1536000KB, committed=380928KB)
                            (mmap: reserved=1536000KB, committed=380928KB)

-                     Class (reserved=1205663KB, committed=177047KB)
                            (classes #30378)
                            (  instance classes #28407, array classes #1971)
                            (malloc=5535KB #92054)
                            (mmap: reserved=1200128KB, committed=171512KB)
                            (  Metadata:   )
                            (    reserved=151552KB, committed=150008KB)
                            (    used=146538KB)
                            (    free=3470KB)
                            (    waste=0KB =0.00%)
                            (  Class space:)
                            (    reserved=1048576KB, committed=21504KB)
                            (    used=19360KB)
                            (    free=2144KB)
                            (    waste=0KB =0.00%)

-                    Thread (reserved=373978KB, committed=43882KB)
                            (thread #363)
                            (stack: reserved=372240KB, committed=42144KB)
                            (malloc=1313KB #2180)
                            (arena=424KB #725)

-                      Code (reserved=255624KB, committed=101916KB)
                            (malloc=7936KB #31264)
                            (mmap: reserved=247688KB, committed=93980KB)

-                        GC (reserved=102397KB, committed=59533KB)
                            (malloc=12429KB #68126)
                            (mmap: reserved=89968KB, committed=47104KB)

-                  Compiler (reserved=2638KB, committed=2638KB)
                            (malloc=2505KB #4253)
                            (arena=133KB #5)

-                  Internal (reserved=4588KB, committed=4588KB)
                            (malloc=4556KB #6082)
                            (mmap: reserved=32KB, committed=32KB)

-                     Other (reserved=25200KB, committed=25200KB)
                            (malloc=25200KB #332)

-                    Symbol (reserved=34309KB, committed=34309KB)
                            (malloc=31392KB #390810)
                            (arena=2917KB #1)

-    Native Memory Tracking (reserved=9591KB, committed=9591KB)
                            (malloc=93KB #1264)
                            (tracking overhead=9498KB)

-               Arena Chunk (reserved=26985KB, committed=26985KB)
                            (malloc=26985KB)

-                   Logging (reserved=4KB, committed=4KB)
                            (malloc=4KB #193)

-                 Arguments (reserved=25KB, committed=25KB)
                            (malloc=25KB #480)

-                    Module (reserved=613KB, committed=613KB)
                            (malloc=613KB #4136)

-              Synchronizer (reserved=609KB, committed=609KB)
                            (malloc=609KB #5050)

-                 Safepoint (reserved=8KB, committed=8KB)
                            (mmap: reserved=8KB, committed=8KB)

 If you would like to submit a bug report, please visit:
   https://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by zdenop** [comment]
Please respect the guidelines for posting issues: we do not provide support for 3rd party projects.
Reproduce the problem with the recent version of the tesseract executable and provide an input image for reproducing the error.
