### ISSUE TITLE
Getting "bad_alloc" after running ocr on a batch of picture

### ISSUE THREAD

**Issue by peterlawkp** [tesseract-ocr/tesseract#3968]
### Environment
* **Tesseract Version**:tesseract-ocr=4.1.1-2.1 tesseract-ocr-eng=1:4.00~git30-7274cfa-1.1
* **Platform**: Debian GNU/Linux 11 (bullseye)
Current Behavior:
I created a simple c++ app to ocr a batch of photo.
For processing one of the photo, the following error is shown.
I try to run on that particular photo without same error after restarting the tesseract-ocr.
Sorry that I can't upload the photo as there is sensitive personal information.

Below is the error printed:
Error in pixSubtract: depths of pixs\* unequal
Error in pixSubtract: pixs1 not defined
Error in pixErodeBrick: pixs not defined
Error in pixSeedfillBinary: pixs undefined or not 1 bpp
Error in pixOr: pixs1 not defined
Error in pixSubtract: pixs1 not defined
Error in pixGetWidth: pix not defined
Error in boxCreate: w and h not both >= 0
Error in pixClipRectangle: pixs not defined
Error in pixCountPixels: pixs not defined or not 1 bpp
Error in pixErodeBrick: pixs not defined
Error in pixSeedfillBinary: pixs undefined or not 1 bpp
Error in pixOr: pixs1 not defined
Error in pixGetHeight: pix not defined
Error in pixClipRectangle: pixs not defined
Error in pixCountPixels: pixs not defined or not 1 bpp
Error in pixGetHeight: pix not defined
Error in boxCreate: w and h not both >= 0
Error in pixClipRectangle: pixs not defined
Error in pixCountPixels: pixs not defined or not 1 bpp
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc

**Comment by zdenop** [comment]
Please respect the guidelines for posting issues!
Provide all necessary information + images for reproducing the problem. Make sure you read the documentation first.

**Comment by peterlawkp** [comment]
Sorry, please give me some time to collect the information I can share.

**Comment by amitdo** [comment]
4.1.1 is not supported by us. Does the issue happen with 5.2.0?

Without an image we can't reproduce the issue ourselves.

**Comment by peterlawkp** [comment]
I am trying to install and seeking help from forum as I can't install 5.2.0 in Debian GNU/Linux 11 (bullseye) no matter specifying5.2.0 or not specifying in the apt-get install.
For the image, sorry that there is personal sensitive information I can't share in here but it is not easy to reproduce as it somehow occurs while processing batch of photos only but not single image processing.

**Comment by zdenop** [comment]
IMO there is no problem to install tesseract 5.2 on debian - either from source or use prebuild binaries. I already point you to relevant page.

Also I you are not able to provide test case for reproducing problem, then you are alone with your problems unfortunately. We can not help you...

**Comment by peterlawkp** [comment]
As I can't provide image for further investigation. Let's close it.
