### ISSUE TITLE
Tesseract improve prediction accuracy

### ISSUE THREAD

**Issue by ken4ward** [tesseract-ocr/tesseract#3971]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/main/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 5.0.1-1.5.7, Tessdata: 3.04, Langdata: 3.04
* **Platform**: 21.5.0 Darwin Kernel Version 21.5.0: root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64 i386 Darwin

### Current Behavior:
3. How do I represent different font-weights in the font property in the landdata? An example is this, I recently trained a new Ubuntu font that ought to have varying font-weights, since only bold is provided as a property I'm struggling to understand how to differentiate the font-weights? This is the font https://fonts.google.com/specimen/Ubuntu

Ubuntu 0 0 0 0 0 = regular (font-weight: 400)
Ubuntu_Medium 0 1 0 0 0 = Medium (font-weight: 500). This is the confusing part. How do I configure this in the font properties?
Ubuntu_Bold 0 1 0 0 0 = Bold (font-weight: 700)

### Expected Behavior: 
It should be consistent in prediction and differentiate between font-weights.

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.
