### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by sameearif88** [tesseract-ocr/tesseract#3974]
Hello,

If there are 10,000 lines in training_text file and there are 120 fonts then each line is rendered for all fonts, that is there will be total 120,0000 lines in the image? Or is better to randomly pick a font for each line and render it on that font so that we have 10,000 lines in the image?

For training is it better to use line by line images or full page text images?

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.
