### ISSUE TITLE
Tesseract training on custom data.

### ISSUE THREAD

**Issue by VallabhMahajan1** [tesseract-ocr/tesseract#3976]
Tesseract Version: v4.0.0. Windows 10

I want to train tesseract to recognize Indic language data. I performed the following steps.

1. Get TIFF images.
2. Generate box files for those images. I used the following command to get the box file.
`tesseract.exe part1_char_level.TIFF part1_char_level -l mar --psm 4 wordstrbox`
3. I corrected the values from that box file.
4. Then I created LSTMF file using the below command.
`tesseract.exe part1_char_level.TIFF part1_char_level -l mar lstm.train`
5. Then I tried to train using 
`lstmtraining --model_output output/ --continue_from lstm_model/mar.lstm --traineddata trained_data/mar.traineddata --train_listfile train/mar.training_files.txt --eval_listfile eval/mar.training_files.txt --max_iterations 90 --debug_interval -1`

Output:
```
Loaded file lstm_model/mar.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Continuing from lstm_model/mar.lstm
Loaded 8/8 pages (1-8) of document train/part1_char_level.lstmf
Loaded 8/8 pages (1-8) of document train/part1_char_level.lstmf
```
```
Iteration 0: ALIGNED TRUTH : ÓÑºÓÑ®ÓÑ®ÓÑ¼ Óñ░ÓÑïÓñ╣Óñ┐ÓñªÓñ¥Óñ© ÓñªÓññÓÑìÓññÓñ¥ÓññÓÑìÓñ░Óñ» ÓñùÓñ¥ÓñÁÓñíÓÑç (Óñ¬ÓÑìÓñ▓ÓÑë.Óñ¿Óñé.ÓÑ½ÓÑ¡) ÓÑª.ÓÑªÓÑ¿.ÓÑªÓÑ«   ÓÑª.ÓÑªÓÑº (ÓÑºÓÑ¬ÓÑªÓÑ¡)
```
```
Iteration 0: BEST OCR TEXT : ÓÑºÓÑ®ÓÑ®ÓÑ¼  Óñ░ÓÑïÓñ╣Óñ┐ÓñªÓñ¥Óñ© ÓñªÓññÓÑìÓññÓñ¥ÓññÓÑìÓñ░Óñ» ÓñùÓñ¥ÓñÁÓñíÓÑç (Óñ¬ÓÑìÓñ▓ÓÑë.Óñ¿Óñé.ÓÑ½ÓÑ¡   ÓÑª.ÓÑªÓÑ¿.ÓÑªÓÑ«  0.ÓÑªÓÑº     (ÓÑºÓÑ¬ÓÑªÓÑ¡)
```

```
File train/part1_char_level.lstmf page 0 :
```
Can someone please help me where I might be wrong?

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.
