### ISSUE TITLE
Build Failed while building  from source for m1 mac

### ISSUE THREAD

**Issue by AryaPulkit** [tesseract-ocr/tesseract#3980]
tesseract git:(5ad5325a) make        
Making all in .
  CXXLD    tesseract
ld: warning: ignoring file /opt/homebrew/Cellar/leptonica/1.82.0_1/lib/liblept.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_getImagelibVersions", referenced from:
      _main in tesseract-tesseract.o
  "_getLeptonicaVersion", referenced from:
      _main in tesseract-tesseract.o
  "_lept_free", referenced from:
      _main in tesseract-tesseract.o
  "_pixDestroy", referenced from:
      _main in tesseract-tesseract.o
  "_pixRead", referenced from:
      _main in tesseract-tesseract.o
  "_setMsgSeverity", referenced from:
      _main in tesseract-tesseract.o
ld: symbol(s) not found for architecture x86_64

 
------------------------

### Environment

* **Tesseract Version**:  5.2.0
* **Commit Number**:    5ad5325a      
* **Platform**:  Mac M1 pro 

### **Current Behavior:**   I am trying to build tesseract from the source code. After executing 
    cd tesseract
    ./autogen.sh
    ./configure

I am trying to build using the make command. but I am getting errors probably due to Mac M1 Architecture. the error message indicates that the system is attempting to link a file built for a different architecture than the one the system is currently running on. In this case, the system is running on a macOS-x86_64 architecture, but it is trying to link a file built for macOS-arm64.

### **Suggested Fix:**
we will need to ensure that the required symbols are available to the linker for M1 Architecture. This may involve adding the appropriate libraries or object files to the linking process for the required symbols are defined in the source code.

[tesseract git:(5ad5325a) make.txt](https://github.com/tesseract-ocr/tesseract/files/10234805/tesseract.git.5ad5325a.make.txt)

**Comment by stweil** [comment]
Why is the system running on x86_64 although you are building on M1 (arm64)?

**Comment by AryaPulkit** [comment]
> Why is the system running on x86_64 although you are building on M1 (arm64)?

I am not sure why that is happening .

i am using 
arch -arm64 brew install pango 
arch -arm64 brew install leptonica  
 
similarly for all dependencies.

**Comment by stweil** [comment]
Please check the clang version. For me, it looks like this:

```
 % clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by AryaPulkit** [comment]
for me its x86.

build git:(5ad5325a) clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by stweil** [comment]
Reinstall the Apple command line tools?

**Comment by amitdo** [comment]
This is not an Tesseract issue. You install the wrong compiler that does not match your Mac architecture. You should seek help in the Hombrew community.
