### ISSUE TITLE
OCR result depends from amount of pixels around it

### ISSUE THREAD

**Issue by eatash** [tesseract-ocr/tesseract#3984]
### Environment

* **Tesseract Version**:
 $ tesseract --version
tesseract 4.1.3
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.38 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.2.2 zlib/1.2.11 liblzma/5.2.2 bz2lib/1.0.6 liblz4/1.7.1

* **Commit Number**: 
N/A
* **Platform**:
$ uname -a
Linux machinename 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
I have the following two images. I got these images from other cv2 preprocessing steps and want to finally perform OCR on the presently existing images.

I know that the images will only contains digits.

-----------------------
![image with digit 8](https://i.stack.imgur.com/A4zdI.png)

-----------------------

![image with digit 11](https://i.stack.imgur.com/q9zmT.png)

-----------------------

The code (1) reads the image and (2) removes all white space around the image so that the digits' borders are also the borders of the image.

Afterwards it (3) increases the space around the digits step-wise and performs a tesseract OCR step.

### BUG:
For the digit `8` this leads to relatively stable results (probably as `--psm 10` is specially meant for single characters). Unfortunately with the `11` this is not the case, even if I choose other values for `--psm`.

My fear is that with other digits/images I would have the same randomness as with the `11`.

Therefore I am looking for a solution where the borders around the image does not influence the OCR result.

    import numpy as np
    import cv2
    from matplotlib import pyplot as plt
    import pytesseract

    # (1)
    # img = cv2.imread('resultImg-8.png', cv2.IMREAD_UNCHANGED)
    img = cv2.imread('resultImg-11.png', cv2.IMREAD_UNCHANGED)
    print("img.shape=", img.shape)
    # (2)
    img = 255 * (img < 128).astype(np.uint8)  # To invert the text to white
    coords = cv2.findNonZero(img)  # Find all non-zero points (text)
    x, y, w, h = cv2.boundingRect(coords)  # Find minimum spanning bounding box

    # (3)
    for deltaAroundFigure in range(1, 12):
        rect = img[y - deltaAroundFigure:y + h + deltaAroundFigure, x - deltaAroundFigure:x + w + deltaAroundFigure]  # Crop the image - note we do this on the original image

        # custom_oem = r'--oem 1 --psm 8'
        # custom_oem = r'--oem 1 --psm 8 -c tessedit_char_whitelist=0123456789'
        custom_oem = r'--oem 1 --psm 10 -c tessedit_char_whitelist=0123456789'
        # custom_oem = r'--oem 1 --psm 10'
        ocrResultString = pytesseract.image_to_string(rect, config=custom_oem).strip()
        print(str(deltaAroundFigure) + " ocrResultString=" + ocrResultString + '/')

RESULTS:

`resultImg-8.png`

    img.shape= (300, 300)
    1 ocrResultString=8/
    2 ocrResultString=8/
    3 ocrResultString=8/
    4 ocrResultString=/
    5 ocrResultString=8/
    6 ocrResultString=/
    7 ocrResultString=8/
    8 ocrResultString=/
    9 ocrResultString=/
    10 ocrResultString=/
    11 ocrResultString=/

`resultImg-11.png`

    img.shape= (300, 300)
    1 ocrResultString=11/
    2 ocrResultString=/
    3 ocrResultString=/
    4 ocrResultString=/
    5 ocrResultString=1/
    6 ocrResultString=/
    7 ocrResultString=/
    8 ocrResultString=/
    9 ocrResultString=/
    10 ocrResultString=/
    11 ocrResultString=/

  [1]: https://i.stack.imgur.com/A4zdI.png
  [2]: https://i.stack.imgur.com/q9zmT.png

### Expected Behavior:
Amount of pixels around the image does not influence the OCR result

**Comment by amitdo** [comment]
1) You are using an old version of Tesseract, v4.1.3, which we do not support.
2) You are using a third party tool, pytesseract, which we do not support. Try to use tesseract 5.2.0 / 5.3.0 directly on the final preprocessed image.
3) psm 10 is meant for a **single** character only. It does not make sense to use it to recognize a number with more than one digit, like '11', or multiple digits separated by a white space, like '1 1'. 
4) You didn't provide the final image after all preprocessing. 
5) Why do you think that increasing the spaces between the digits will improve the result?
6) Tesseract was trained on full sentences containing both words, digits and other symbols. The default model is not optimizes for digits-only OCR.
7) Did you try psm 13?
8) If that does not work, you can add 1-pixel white border around the image and try different PSMs.

**Comment by eatash** [comment]
Thanks, 

all you comments were helpful!

I followed your recommendations and it helped a lot.

Additionally I took `jpg` as input format (instead of `png`). That was a further improvement.
