### ISSUE TITLE
Packages for Linux distros

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#3987]
@AlexanderP,

Hi, can you please upload Leptonica 1.83 and Tesseract 5.3.0 to https://mentors.debian.net ?

I hope @bgermann can help as a Debian sponsor.

See: https://github.com/DanBloomberg/leptonica/issues/656#issuecomment-1361851778

**Comment by bgermann** [comment]
I have updated the package and have changed debian/watch along the way.
For the future, please make sure to that uscan works and can actually download the tarballs (tesseract and test).
Also, please do not include .git in your uploads.

**Comment by amitdo** [comment]
So Tessract 5.3.0 is on it way to sid and hopeufully later it will move to bookworm. @AlexanderP and @#bgermann, thank you!

@AlexanderP,
What about Leptonica 1.83? Can you also upload it to Debian?

**Comment by bgermann** [comment]
That is @jbreiden's responsibility.

**Comment by amitdo** [comment]
https://tracker.debian.org/pkg/tesseract

>[**news**](https://tracker.debian.org/pkg/tesseract/news/)
>
>[2023-01-09][ Accepted tesseract 5.3.0-1 (source) into unstable ](https://tracker.debian.org/news/1407282/accepted-tesseract-530-1-source-into-unstable/)(Alexander Pozdnyakov) (signed by: bage@debian.org)

**Comment by amitdo** [comment]
https://tracker.debian.org/pkg/tesseract

>Migration status for tesseract (5.1.0-2 to 5.3.0-1): BLOCKED: Rejected/violates migration policy/introduces a regression
    Issues preventing migration:
    ∙ ∙ autopkgtest for [cataclysm-dda](https://tracker.debian.org/pkg/cataclysm-dda)/0.F-3-9: [amd64](https://ci.debian.net/packages/c/cataclysm-dda/testing/amd64): [Pass](https://ci.debian.net/data/autopkgtest/testing/amd64/c/cataclysm-dda/30235522/log.gz), [arm64](https://ci.debian.net/packages/c/cataclysm-dda/testing/arm64): [Regression](https://ci.debian.net/data/autopkgtest/testing/arm64/c/cataclysm-dda/30236211/log.gz) [♻ ](https://ci.debian.net/api/v1/retry/30236211)([reference](https://ci.debian.net/data/autopkgtest/testing/arm64/c/cataclysm-dda/30173242/log.gz)[ ♻](https://ci.debian.net/api/v1/retry/30173242)), [armel](https://ci.debian.net/packages/c/cataclysm-dda/testing/armel): [Pass](https://ci.debian.net/data/autopkgtest/testing/armel/c/cataclysm-dda/30187963/log.gz), [armhf](https://ci.debian.net/packages/c/cataclysm-dda/testing/armhf): [Pass](https://ci.debian.net/data/autopkgtest/testing/armhf/c/cataclysm-dda/30188214/log.gz), [i386](https://ci.debian.net/packages/c/cataclysm-dda/testing/i386): [Pass](https://ci.debian.net/data/autopkgtest/testing/i386/c/cataclysm-dda/30188493/log.gz), [ppc64el](https://ci.debian.net/packages/c/cataclysm-dda/testing/ppc64el): [Test in progress](https://ci.debian.net/status/pending), [s390x](https://ci.debian.net/packages/c/cataclysm-dda/testing/s390x): [Test in progress](https://ci.debian.net/status/pending)

CC: @reinerh

**Comment by reinerh** [comment]
@amitdo Sorry, the cataclysm-dda autopkgtest is a bit flaky. I've just requested a retry.
(And I'll improve the test in the next upload)

**Comment by amitdo** [comment]
@reinerh,

The migration of Tesseract 5.3.0 to Debian testing is blocked due to regression in tests (s390x) of your package.

**Comment by reinerh** [comment]
Hm, the s390x regression seems to be independent of my package (and only happens on s390x).
I retriggered the test, but it looks like it's more an infrastructure problem. I'll check with the debci developers.  
But your package should migrate now.

**Comment by stweil** [comment]
Some [Debian warnings](https://qa.debian.org/bls/bytag/W-compiler-flags-hidden.html) can be fixed by running `make` with more output (`make V=1` ).

**Comment by amitdo** [comment]
>**news**
>[2023-01-19][ tesseract 5.3.0-2 MIGRATED to testing
