### ISSUE TITLE
The font size returned by the recognize api is often incorrect

### ISSUE THREAD

**Issue by Sharcoux** [tesseract-ocr/tesseract#3988]
### Basic Information

I first opened the issue on tesseract.js there: https://github.com/naptha/tesseract.js/issues/707 but I got redirected here.

**Describe the bug**

The font_size property returned by the ocr is not accurate.

### Operating System

Ubuntu 22.04 Jammy

### uname -a

Linux fbillioud-Victus 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Compiler

webassembly (tesseract.js)

### Current Behavior

recognize the following image: 
![image](https://user-images.githubusercontent.com/797545/211445942-749e07ee-7c6f-41ef-8a12-e55be0c9f8d8.png)

If you log the result of data.lines.map(word => console.log(word.text, word.font_size)), you will receive somthing like that:

![image](https://user-images.githubusercontent.com/797545/211446038-c31c27c2-17f5-4838-906f-f5070d107825.png)

As you can see, sometimes the result is 3, sometimes it's 5. But all the characters are using the same font size

**Screenshots**
Here is the consequence:

![image](https://user-images.githubusercontent.com/797545/211446091-fc7a78a2-e175-4bb6-8d0f-4f26c802def0.png)

### Expected Behavior

An accurate answer would be "4"

### Suggested Fix

Train the model better on font size accuracy?

**Comment by stweil** [comment]
Running `tesseract https://user-images.githubusercontent.com/797545/211445942-749e07ee-7c6f-41ef-8a12-e55be0c9f8d8.png - -c hocr_font_info=1 hocr|fgrep x_fsize` I get different values ranging from 18, 21 and 23.

**Comment by amitdo** [comment]
The OP ignored the guidelines that appear when the user open an issue.

**Comment by amitdo** [comment]
The font size is just an rough estimate. IIRC, it is based on the text line height.

**Comment by amitdo** [comment]
Duplicate of #2165.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/2c4665466efac91c249460cd3d404afb4360f381/src/ccmain/ltrresultiterator.cpp#L168-L173

**Comment by amitdo** [comment]
1. You reported about a 3rd party library.
2. You didn't provide version info.
3. You attached a screenshot of the command line output.
