### ISSUE TITLE
why can't I output the correct Unicode with Visual Studio?

### ISSUE THREAD

**Issue by raviruia522** [tesseract-ocr/tesseract#3990]
`tesseract::TessBaseAPI* api = new tesseract::TessBaseAPI();`
   `if (api->Init("./tessdata", "chi_sim"))`
`{`
        `    fprintf(stderr, "Could not initialize tesseract.\n");`
        `    exit(1);`
    `}`
    `Pix* image = pixRead("./hinh/test.jpg");`
    `api->SetImage(image);`
    `char* outText = api->GetUTF8Text();`
    `printf("OCR output:\n%s", outText);`
    `api->End();`
    `delete api;`
    `delete[] outText;`
    `pixDestroy(&image);`

output: ![Screenshot 2023-01-13 210153](https://user-images.githubusercontent.com/44082224/212363500-36b44394-d3c1-403e-b37e-d381133c2c18.jpg)

instead of: 一 时 间 呐 喊 声 加 油 声 震 破 天 际
images: 
![test](https://user-images.githubusercontent.com/44082224/212366456-c24e1c8f-fb2f-438e-8501-b88dd45c6a7e.jpg)

please help me!

**Comment by amitdo** [comment]
We can't help people that does not respect our guideline for reporting issues. This guideline appears when you open a new issue, but you ignored it.
