### ISSUE TITLE
Best eng model still got Segmentation fault (Core dumped)

### ISSUE THREAD

**Issue by juhonkang** [tesseract-ocr/tesseract#3994]
### Basic Information

![image](https://user-images.githubusercontent.com/67153600/212598728-a85a6894-f2ba-4494-b828-9dcbd3b7ddf7.png)
![image](https://user-images.githubusercontent.com/67153600/212598774-c38f6a2a-1f25-4db1-b7cc-0e58a3cd24a0.png)

I downloaded the eng.trainedata from bestdata repo to train but still get error. 
Please help!

[Training data](https://drive.google.com/drive/folders/1BnE_a8ToMEZ_sGOE-szmb-omGU51Qm0T?usp=sharing)
[Model & Tesseract files](https://drive.google.com/drive/folders/1C7u7DcdDsrsbfaBA36pK6QsjOynVxKrg?usp=sharing)

### Operating System

Ubuntu 20.04 Focal

**Comment by zdenop** [comment]
1. Do not post screenshot - post text output/logs
2. Make sure you use the latest tesseract version (AFAIK Ubuntu has old version of tesseract)
3. Post all steps you did and why (e.g. why did you rename `eng` to `eng_2023`? Why under `model/tesseract_files/eng_2023 `
  components are named as `first_four`.*?)
4. Does example training (with ocrd-testset.zip) works without problem?

**Comment by amitdo** [comment]
The OP ignored the guidelines that appear when one opens a new issue. He also did not give further information as requested by @zdenop.
