### ISSUE TITLE
PSM_AUTO with jpn_vert gives garbage if the legacy engine is disabled at compile time

### ISSUE THREAD

**Issue by danpla** [tesseract-ocr/tesseract#3997]
### Basic Information

Tesseract 5.3.0

### Other Operating System

Windows 7

### uname -a

MINGW32_NT-6.1-7601 PC 3.3.6-341.x86_64 2022-11-20 15:12 UTC x86_64 Msys

### Compiler

GCC 12.2.0

### CPU

Intel Core i7 Q720

### Current Behavior

If tesseact is built without the legacy engine (`--disable-legacy`), recognizing vertical Japanese text with `jpn_vert` (from tessdata_fast) and `PSM_AUTO` (`--psm 3`) gives garbage. Here is an example image:
![1](https://user-images.githubusercontent.com/10910745/213862333-aa41ebee-469e-47a1-bb99-7e5c6d834b76.png)
Here is the output of `tesseract 1.png stdout -l jpn_vert --psm 3`:
```
…4

/
\

09$2pY
コ べ
ほり メー14
```
Here is the correct (albeit with some OCR errors) output that I get either without `--disable-legacy`, or when using `PSM_SINGLE_BLOCK_VERT_TEXT` (`--psm 5`) explicitly regardless of whether the legacy engine is enabled:
```
ケー タイ は
カバ パ バン に
入れ て ある し
```

### Suggested Fix

If this is a kind of feature rather than a bug, it should probably be documented somewhere.

**Comment by amitdo** [comment]
My guess it is caused by the lack of the OSD feature when the legacy engine is disabled.

**Comment by amitdo** [comment]
So it's not a bug but a feature...

You already found the solution  — using `--psm 5`.

**Comment by danpla** [comment]
> My guess it is caused by the lack of the OSD feature when the legacy engine is disabled.

I thought that PSM_AUTO has nothing to do with OSD since there is PSM_AUTO_OSD for that.

**Comment by amitdo** [comment]
>Here is the correct (albeit with some OCR errors) output that I get either without --disable-legacy

With `--psm 3`?

**Comment by danpla** [comment]
> > Here is the correct (albeit with some OCR errors) output that I get either without --disable-legacy
> 
> With `--psm 3`?

Yes.

**Comment by amitdo** [comment]
>I thought that PSM_AUTO has nothing to do with OSD since there is PSM_AUTO_OSD for that.

You are right.

Do you have traineddata.osd in your tessdata dir?

If the answer is 'yes', just to make sure --psm 3 works as expected, please try this:

Temporary remove traineddata.osd (or move the file to another dir) and rerun the test with the legacy engine **enabled**.

Do get the same result?

**Comment by danpla** [comment]
I tried this even before opening the issue. The presence of osd.traineddata has no effect on `--psm 3`, regardless of whether the legacy engine is enabled.

I also tried `--oem 1` to force LSTM for the program built without `--disable-legacy`, but the result was still correct. In other words, it seems like only `--disable-legacy` causes the problem.

**Comment by amitdo** [comment]
>Here is the correct (albeit with some OCR errors) output that I get either without --disable-legacy... regardless of whether the legacy engine is enabled:
>
>ケー タイ は
>カバ パ バン に
>入れ て ある し

The question is, if it does not use the osd model, how does it correctly know to read this right-to-left top-to-bottom.

**Comment by amitdo** [comment]
#4041 might resolve this issue.

**Comment by danpla** [comment]
I tested `main` and it looks like the problem has been fixed. Thanks!
