### ISSUE TITLE
Issue on installing Tesseract in Linux environment

### ISSUE THREAD

**Issue by arjun251** [tesseract-ocr/tesseract#4000]
### Basic Information

We are trying to install Tesseract in the **Azure cloud Linux environment**. We are struggling with the below error on installing.
We also tried running **apt-get update** command before installing tesseract-ocr, still the error remains same.
I am really glad and thankful if you can help me with the workaround solution.

**apt-get -f -y install tesseract-ocr**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libgif7 liblept5 libopenjp2-7 libtesseract4 tesseract-ocr-eng tesseract-ocr-osd
The following NEW packages will be installed:
  libgif7 liblept5 libopenjp2-7 libtesseract4 tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
0 upgraded, 7 newly installed, 0 to remove and 1 not upgraded.
Need to get 7225 kB of archives.
After this operation, 22.5 MB of additional disk space will be used.
Err:1 http://deb.debian.org/debian buster/main amd64 libgif7 amd64 5.1.4-3
  503  Service Unavailable [IP: 146.75.30.132 80]
Ign:2 http://deb.debian.org/debian buster/main amd64 libopenjp2-7 amd64 2.3.0-2+deb10u2
Err:3 http://deb.debian.org/debian buster/main amd64 liblept5 amd64 1.76.0-1+deb10u1
  503  Service Unavailable [IP: 146.75.30.132 80]
Err:4 http://deb.debian.org/debian buster/main amd64 libtesseract4 amd64 4.0.0-2
  503  Service Unavailable [IP: 146.75.30.132 80]
Err:5 http://deb.debian.org/debian buster/main amd64 tesseract-ocr-eng all 1:4.00~git30-7274cfa-1
  503  Service Unavailable [IP: 146.75.30.132 80]
Err:6 http://deb.debian.org/debian buster/main amd64 tesseract-ocr-osd all 1:4.00~git30-7274cfa-1
  503  Service Unavailable [IP: 146.75.30.132 80]
Err:7 http://deb.debian.org/debian buster/main amd64 tesseract-ocr amd64 4.0.0-2
  503  Service Unavailable [IP: 146.75.30.132 80]
Err:2 http://deb.debian.org/debian buster/main amd64 libopenjp2-7 amd64 2.3.0-2+deb10u2
  503  Service Unavailable [IP: 146.75.30.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/giflib/libgif7_5.1.4-3_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]
E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/o/openjpeg2/libopenjp2-7_2.3.0-2+deb10u2_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/l/leptonlib/liblept5_1.76.0-1+deb10u1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/t/tesseract/libtesseract4_4.0.0-2_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/t/tesseract-lang/tesseract-ocr-eng_4.00~git30-7274cfa-1_all.deb  503  Service Unavailable [IP: 146.75.30.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/t/tesseract-lang/tesseract-ocr-osd_4.00~git30-7274cfa-1_all.deb  503  Service Unavailable [IP: 146.75.30.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/t/tesseract/tesseract-ocr_4.0.0-2_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by zdenop** [comment]
> Err:1 http://deb.debian.org/debian buster/main amd64 libgif7 amd64 5.1.4-3
>   503  Service Unavailable [IP: 146.75.30.132 80]

This is not tesseract project issue.

**Comment by arjun251** [comment]
@zdenop Thanks for your response.
Can you help me what could cause this issue. It will be helpful, If you could explain me in detail,

**Comment by amitdo** [comment]
You have an issue with Debian package manager. My Guess it's related to the fact that you use Debian 'Busrer' which is too old and is no longer supported by the Debian project. You should use Debian 'Bullseye' instead.

Try to get support here:
https://www.debian.org/support

**Comment by stweil** [comment]
It might be an issue of your cloud provider: deb.debian.org is resolved to the IP address 146.75.30.132 which does not offer the expected HTTP server.

**Comment by amitdo** [comment]
About deb.debian.org/

From https://www.debian.org/mirror/list.en.html

>If your system moves around a lot, you may be best served by a "mirror" that is backed by **a global CDN**.
