### ISSUE TITLE
PDF creation mode without images? Only HOCR?

### ISSUE THREAD

**Issue by zvezdochiot** [tesseract-ocr/tesseract#4001]
### Your Feature Request

Hi @stweil .

For my project [mfbpdf](https://github.com/ImageProcessing-ElectronicPublications/mfbpdf) ([demo](https://github.com/ImageProcessing-ElectronicPublications/mfbpdf-demo)) need generate a PDF with only HOCR text (no images) after recognition for subsequent overlay on MFB. Is this PDF generation mode possible?

**Comment by zdenop** [comment]
Please respect guidance for posting issue - ask question in tesseract user forum.
