### ISSUE TITLE
dvd and bluray subtitle extraction

### ISSUE THREAD

**Issue by eddilara** [tesseract-ocr/tesseract#4004]
### Your Feature Request

it would be a GOD-SEND if tesseract could extract subtitle positioning from dvd and bluray subtitles
it would have to read the frame size...then be able to identify where in the frame the subtitle is
this might be outta the scope of tesseract...but even a api to work with ffmpeg or libav to work together to be able to do this would be very helpful
NISKE over at SUBTITLE EDIT...would like to enable this...but he doesn't exactly know where to start with it...
im not sure he's good at working with video programming either
this would save SOOOOOO much time when converting dvd and bluray subs

**Comment by amitdo** [comment]
In short, this won't happen.

You need to search for other tools that can preprocess the video and give Tesseract just the subtitles.

**Comment by amitdo** [comment]
ffmpeg already has [an (optional) dependency on libtesseract](https://github.com/FFmpeg/FFmpeg/search?q=tesseract&type=code).

[Google: "ffmpeg" "tesseract" "subtitles"](https://www.google.com/search?q=%22ffmpeg%22+%22tesseract%22+%22subtitles%22)

https://superuser.com/questions/1718669/ffprobe-ocr-of-a-subtitle-stream

**Comment by eddilara** [comment]
thanx
