### ISSUE TITLE
Can't correctly read simple text

### ISSUE THREAD

**Issue by ohenepee** [tesseract-ocr/tesseract#4012]
### Basic Information

Using v5.3.0

I initially started with v5.1.0, which still couldn't correctly recognize them

### Operating System

Ubuntu 22.04 Jammy

### Current Behavior

Its either I am doing something wrong or tesseract can't correctly read some simple text using LSTM. Legacy mode isn't helpful as it intermittently misidentify some numbers. I can't seem to recognize the number 9 if its the starting character in a text/line, it is always falsely recognized as the number 0. I also can't seem to read the text 5.11x. I've been banging my on this issue for days now.

These images below can't be correctly recognized as described above:
![LessThanOne-2022-11-26T10:05:31 427Z](https://user-images.githubusercontent.com/15159487/216224536-ac9438db-2b0e-4f1e-9d72-ee3c2d97df5e.png)
![LessThanOne-2022-11-26T20:37:56 890Z](https://user-images.githubusercontent.com/15159487/216224547-7a73cff9-70f1-44c8-9bbe-5d14dd812af7.png)
![LessThanOne-2022-11-27T03:07:28 120Z](https://user-images.githubusercontent.com/15159487/216224550-579d3c83-f9a3-4af7-b411-7d1544441618.png)
![LessThanOne-2022-11-27T05:42:14 544Z](https://user-images.githubusercontent.com/15159487/216224551-eb854951-f467-4250-b735-60f43a254c90.png)
![LessThanOne-2022-11-27T08:27:43 140Z](https://user-images.githubusercontent.com/15159487/216224553-7c62ecc3-4784-4860-880d-2b338f186c97.png)
![123](https://user-images.githubusercontent.com/15159487/216224604-30f5f559-3641-47f9-afd4-5b8781ce500b.png)

### Expected Behavior

To correctly recognize the text as is.

### Suggested Fix

Is there something I ought to do to get the correct text? I really wanted to train my own custom model but that looks like overkill for these simple texts. At least the training wiki already discourages me from persuing further as it recommends training for special cases, which I doubt this is.

**Comment by zdenop** [comment]
Please read the [documentation](https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html):

```
>tesseract i4012_980x_preprocessed.png -
9.80x
>tesseract i4012_926x_preprocessed.png -
9.26X
>tesseract i4012_923x_preprocessed.png -
9.23x

```

**Comment by ohenepee** [comment]
Would be much helpful if you could write what exact preprocessing steps you performed.

**Comment by zdenop** [comment]
Your post does not conform guidelines described in https://github.com/tesseract-ocr/tesseract/blob/main/CONTRIBUTING.md
I just did what is suggested in the documentation. It is your job to read it and to test suggestions.
