### ISSUE TITLE
Regression in extracting text from Excel TIF image

### ISSUE THREAD

**Issue by jwmepiq** [tesseract-ocr/tesseract#4014]
### Environment

[ExcelTest_Bug.zip](https://github.com/tesseract-ocr/tesseract/files/10669551/ExcelTest_Bug.zip)
[ExcelTest_text_TesseractV4.txt](https://github.com/tesseract-ocr/tesseract/files/10669573/ExcelTest_text_TesseractV4.txt)

Tesseract Version: 5.2.0 vs. 4.1.1.-rc2-37-gcla5
Ubuntu 20.04.3 LTS

### Current Behavior:

With the attached TIF image of an Excel file (in the zip), Tesseract version 5.2.0 extracts a minimal amount of text (only a single line "hiding rows 15 through 20").  However, in prior versions of Tesseract, namely the version 4.1.1 version noted above, but likely other versions as well, the amount of text extracted from the same TIF image is significantly larger (multiple lines of text, approximately 1K of text over multiple pages).  Attached a separate text file with the output of the V4.x text output.

### Expected Behavior:

Expecting version 5.2+ of Tesseract to at least replicate the behavior of prior versions in extracting text from this sample TIF.

### Suggested Fix:

Correct the text extraction to match the output from previous Tesseract versions.  Concerned with Tesseract's regression in ability to extract text from Excel files.

**Comment by vamsiyadavmolli** [comment]
This is an issue in 5.3 version as well. Tried using both best/fast trained data still we see this issue.

**Comment by dhairyagupta2603** [comment]
Hey, Just wanted to know the status of this issue. Can I take this up?

**Comment by stweil** [comment]
I can confirm the issue with the latest code. What about releases between 4.1.1 (working) and 5.2.0 (not working)? Can we narrow down which release introduced the regression?

**Comment by stweil** [comment]
According to `git bisect` the regression was introduced by commit 86d981eee69eb504cfd6c6e233f1fbf1862b5cfa.

**Comment by stweil** [comment]
Pull request #4136 fixes the regression.

**Comment by stweil** [comment]
@jwmepiq, thank you for reporting this nasty regression.

**Comment by tfmorris** [comment]
Now that #4136 has been merged and 5.3.3 released, I assume this can be closed

**Comment by stweil** [comment]
Yes, thanks.
