### ISSUE TITLE
Do not display the correct Unicode chain

### ISSUE THREAD

**Issue by raviruia522** [tesseract-ocr/tesseract#4024]
### Basic Information

My code:
`tesseract::TessBaseAPI* api = new tesseract::TessBaseAPI();
    if (api->Init("./tessdata", "chi_sim")) {
        fprintf(stderr, "Could not initialize tesseract.\n");
        exit(1);
    }
    Pix* image = pixRead("./image/test.png");
    api->SetImage(image);
    char* outText = api->GetUTF8Text();
    printf("OCR output:\n%s", outText);`
Image:
![test](https://user-images.githubusercontent.com/44082224/221419272-4f588b88-bf3e-435f-b9ec-138efe86c6fb.png)

Output: σæ¿ σ¢┤ τÜä τè» Σ║║ µùá Σ╕Ç Σ╕ì ΘÇÅ Θ£▓ τ¥Ç ΘÆª Σ╜⌐ τÜä τÑ₧ µâà
Instead of: 周 围 的 犯 人 无 一 不 透 露 着 钦 佩 的 神 情
Tesseract version: 5.3.0
I don't understand where I did it. please help me!

### Operating System

Windows 11

### Compiler

MSVS2022

**Comment by amitdo** [comment]
Do you get a Chinese output when using the official command line tool?

**Comment by amitdo** [comment]
https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170

**Comment by raviruia522** [comment]
> Do you get a Chinese output when using the official command line tool?
no, it's the characters below that can't be read, even if I add /utf-8 to Additional Options
 σæ¿ σ¢┤ τÜä τè» Σ║║ µùá Σ╕Ç Σ╕ì ΘÇÅ Θ£▓ τ¥Ç ΘÆª Σ╜⌐ τÜä τÑ₧ µâà
![Screenshot 2023-03-01 205428](https://user-images.githubusercontent.com/44082224/222160082-4a4a1558-a53e-42d2-9d2f-c94c732d2a9b.png)

**Comment by zdenop** [comment]
make output to text file instead of console. IMO this is not tesseract problem but terminal problem.

**Comment by amitdo** [comment]
Do you use the new terminal in Windows 11? It supports UTF-8 by default.

https://www.anoopcnair.com/windows-terminal-default-command-line-app/

**Comment by raviruia522** [comment]
thank you very much @amitdo  @zdenop
