### ISSUE TITLE
Estimating resolution as xxx  Empty page!!

### ISSUE THREAD

**Issue by LaiXiaoYu** [tesseract-ocr/tesseract#4029]
### Basic Information

tesseract v5.3.0.20221222
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0

### Operating System

Windows 10

### CPU

Intel core i9-9900K

### Current Behavior

Capture screen to BMP/JPG/PNG files, then use "tesseract  filename.bmp ff"
the image.width=44, image.height=18
there is problem: 
Z:\>tesseract JPGbitblt-85.jpg JPGbitblt-85
Estimating resolution as 184
Empty page!!
Estimating resolution as 184
Empty page!!

Z:\>tesseract JPGcanvas-85.jpg JPGcanvas-85
Estimating resolution as 228
Empty page!!
Estimating resolution as 228
Empty page!!

Z:\>tesseract JPGgetDIBits-85.jpg JPGgetDIBits-85
Estimating resolution as 184
Empty page!!
Estimating resolution as 184
Empty page!!

Z:\>tesseract PNGcanvas-85.png PNGcanvas-85
Estimating resolution as 228
Empty page!!
Estimating resolution as 228
Empty page!!

Z:\>tesseract PNGgetDIBits-25.png PNGgetDIBits-25
Estimating resolution as 184
Empty page!!
Estimating resolution as 184
Empty page!!

But if a use the software "Snipaste 2.4.0" to capture the same rect of the screen to BMP file, it would be ok

### Other Information

![JPGbitblt-85](https://user-images.githubusercontent.com/26377175/225088663-f58fdf8c-f577-44d3-b14d-0e473f38a8a5.jpg)
![JPGcanvas-85](https://user-images.githubusercontent.com/26377175/225088710-2e526651-066e-46e0-9126-4d8e5731aab8.jpg)
![JPGgetDIBits-85](https://user-images.githubusercontent.com/26377175/225088713-604c0ed7-c005-4b44-8891-04e666c0ff2e.jpg)
![PNGbitblt-25](https://user-images.githubusercontent.com/26377175/225088718-93d852a0-c8e0-4046-89f7-4fdb4ecdc0a8.png)
![PNGbitblt-85](https://user-images.githubusercontent.com/26377175/225088720-b81ec13a-53e1-47a6-bc13-b6c4ebc00843.png)
![PNGcanvas-25](https://user-images.githubusercontent.com/26377175/225088723-1ea53886-8687-4a20-8952-1d7f7f517e59.png)
![PNGcanvas-85](https://user-images.githubusercontent.com/26377175/225088729-b931a460-038e-4f24-a331-ddd607b12dfe.png)
![PNGgetDIBits-25](https://user-images.githubusercontent.com/26377175/225088730-b30b85ce-ce2d-4cae-89e3-4ccb54b01b52.png)
![PNGgetDIBits-85](https://user-images.githubusercontent.com/26377175/225088734-197219ba-5ff4-4c85-99dc-7b6177c9f20b.png)

**Comment by amitdo** [comment]
You didn't add the bmp image that Tesseract recognizes its text correctly.

Did you try to use one of these methods:
* Scaling
* Inverting
* Changing the psm parameter

Why do you use Leptonica 1.78? The latest version is 1.83.

**Comment by LaiXiaoYu** [comment]
thanks for your help
