### ISSUE TITLE
CMake: builds always use `-march=native`

### ISSUE THREAD

**Issue by bmwiedemann** [tesseract-ocr/tesseract#4030]
### Current Behavior

While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that
when building packages, machine code depends on which build worker is selected from our build pool.

### Expected Behavior

It should be possible to build without `-march=native` to get reproducible binaries.

### Suggested Fix

There is a fix in #3864

### tesseract -v

5.3.0

### Other Operating System

openSUSE-Tumbleweed 20230315

### uname -a

6.2.4

### Compiler

gcc-12

### CPU

various

**Comment by stweil** [comment]
Linux distributions should use the automake build which fixed that in commit 5884036ecdb2807419cbd21b7ca44b630f547d80. Does openSUSE use the cmake build? Why?

**Comment by bmwiedemann** [comment]
https://code.opensuse.org/package/tesseract-ocr/blob/master/f/tesseract-ocr.spec#_79 says we use cmake since we [moved from automake](https://code.opensuse.org/package/tesseract-ocr/c/2e7b3d056b) 2 months ago.

**Comment by amitdo** [comment]
>Does openSUSE use the cmake build? Why?

People see that we support both Autotools and CMake, and they choose the tool they prefer.

**Comment by stweil** [comment]
That's okay for individual users and for those who have special needs like using IDEs for Windows or macOS. But for Linux distributions I suggest to move back to automake. That minimized their risk and makes it easier for us.

**Comment by mimi1vx** [comment]
@stweil .. usually is cmake faster, you can use different builder than make like ninja, and it can be pretty easy debug and modified in comparsion with autotools ?

**Comment by zdenop** [comment]
Please check current code. Now the default setting should be the same as at autotools.

**Comment by bmwiedemann** [comment]
commit f779c434b0370a005b3c49f35f3f38810a781ca5 looks good, except that it does not mention this issue.
Test passed with it, too.

**Comment by stweil** [comment]
> @stweil .. usually is cmake faster

Autotools by default builds shared and static libraries and builds executables which use the shared tesseract library.

CMake by default seems to build only the static library, so the executables don't use a shared tesseract library and are much larger. @bmwiedemann, Linux distributions typically prefer shared linking. Do you use special flags when running CMake?

A single threaded build with CMake takes around 1:46 on my MacBook and uses 99 % cpu.
A single threaded build with Autotools and `--disable-shared` takes around 2:26 seconds and uses 91 % cpu. So yes, it is a bit slower because it obviously does not use the full cpu power.

**Comment by amitdo** [comment]
>Autotools by default builds shared and static libraries

I don't think it's a good default. what do you think?

**Comment by stweil** [comment]
As far as I know that's the normal default for autotools. And typically a distribution requires both, shared libraries for the binaries and additional static libraries for development packages. So for distributions that default is fine.

**Comment by zdenop** [comment]
@stweil : with `-DBUILD_SHARED_LIBS=ON` you can build shared libs with [cmake](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html)
