### ISSUE TITLE
best chinese data add extra spaces in text, while fast data doesn't

### ISSUE THREAD

**Issue by l1t1** [tesseract-ocr/tesseract#4031]
### Current Behavior

when use the fast data(https://digi.bib.uni-mannheim.de/tesseract/tessdata_fast/chi_sim.traineddata) is works well.
when use the best data (https://github.com/tesseract-ocr/tessdata_best/blob/main/chi_sim.traineddata),
it show extra sapces in many Chinese charactors. it's hard to read to Chinese people
for example
```
D:\>tesseract 7.jpg stdout -l chi_sim
Estimating resolution as 315
��� 联 社 电 报

2023-03-17 20:52 星期 五

【华为 总 裁 任正非 : 华为 2022 年 研
发 经 费 达 238 亿 美元 】

财 联 社 3 月 17 日 电 ， 华 为 总 裁 任 正 非 日 前 在 " 难
题 揭 榜 " 火花 奖 公 司 内 外 的 获奖 者 及 出 题 专家 座
谈 会 上 的 讲话 中 透露 ， 华 为 现在 还 属于 困难 时
期 ， 但 在 前 进 的 道路 上 并 没有 停 步 。2022 年 华
为 的 研发 经 费 达 238 亿 美元 ， 未 来 在 前 沿 探索 上
还 会 继续 加 大 投入 。

TMT 行 业 观 察 华为 最 新 动态

Error during processing.
```

### Expected Behavior

no extra space, just as does
```
D:\>tesseract 7.jpg stdout -l chi_sim
Estimating resolution as 315
���联社电报

2023-03-17 20:52 星期五

【华为总裁任正非: 华为2022年研
发经费达238亿美元】

财联社3月17日电，华为总裁任正非日前在`难
题揭榜"火花奖公司内外的获奖者及出题专家座
谈会上的讲话中透露，华为现在还属于困难时
期，但在前进的道路上并没有停步。2022年华
为的研发经费达238亿美元，未来在前沿探索上
还会继续加大投入。

TMT行业观察     华为最新动态

Error during processing.
```

### Suggested Fix

let best data works as fast data

### tesseract -v

D:\>tesseract -v
tesseract v5.3.0.20221214
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0

### Other Operating System

Windows 7 32bit

**Comment by l1t1** [comment]
![7](https://user-images.githubusercontent.com/23301704/226085905-26d698ae-69ea-47af-9758-e266779b79e6.jpg)
 image file

**Comment by amitdo** [comment]
Maybe there is a difference in the config file.

You can try to unpack the best & fast data files and compare their config file.

https://github.com/tesseract-ocr/tesseract/blob/f0b8c0254b24a3df7751708f67fa567b4aff2e11/doc/combine_tessdata.1.asc

**Comment by amitdo** [comment]
Why do you use Leptonica 1.78? The latest version is 1.83.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tessdata_fast/commit/80d92b7db61cb6ddc519049990be34e4c913566f

**Comment by amitdo** [comment]
The 'best' repo did not recieve a similar patch.

https://github.com/tesseract-ocr/tessdata_best/commits/main/chi_sim.traineddata

**Comment by l1t1** [comment]
> Why do you use Leptonica 1.78? The latest version is 1.83.

I just download the file https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v5.3.0.20221214.exe

the config extract from chi_sim.traineddata fast version
```
#Fixes https://github.com/tesseract-ocr/tesseract/issues/991
preserve_interword_spaces 1
```
the config extract from chi_sim.traineddata best version
```
tessedit_load_sublangs chi_sim_vert
# Important configurations for CJK mode

# New Segmentation search params
language_model_ngram_on             1
segsearch_max_char_wh_ratio         1.3
language_model_ngram_space_delimited_language F
language_model_use_sigmoidal_certainty T
language_model_ngram_nonmatch_score -20

# Chinese symbols are more complex than Latin.  Adjust the blob filtering
# thresholds so they do not get filtered out as noise or containers.
# Also force word segmentation to reduce the length of blob sequences.
edges_use_new_outline_complexity    T
edges_children_fix                  T
edges_max_children_per_outline     10
edges_max_children_layers           5
edges_children_count_limit       1000
tosp_force_wordbreak_on_punct       F
textord_force_make_prop_words       T
textord_noise_sizelimit             0.2
textord_noise_normratio             6
textord_max_noise_size              7

# Make use of the fact that Chinese is monospaced, and incorporate that
# into character segmentation cost for search, and inject this cost to
# word rating.
classify_integer_matcher_multiplier 4
assume_fixed_pitch_char_segment     T
tessedit_char_blacklist             氵宀灬丿丶ˇ幺扌亻〆‰囗
segment_nonalphabetic_script        1
allow_blob_division                 F

# Since we do not have a dictionary for Chinese yet, none of the results
# will be found in dawg.  We need to relax the stopping condition and turn
# off dictionary based penalties.  Instead, we get additional constraints
# from script consistency.
stopper_nondict_certainty_base   -2

# Force use of a single x-height mode when the text is written horizontally.
# This information could come from the unicharset (script_has_xheight), but
# it is better in the config file so as to be available when training.
textord_single_height_mode        T

# Use character height as x-height, and estimate it from character pitch and
# kerning width.
textord_use_cjk_fp_model T
```

**Comment by amitdo** [comment]
@stweil,

Why do you ship 1.78 with 5.3.0 in the mingw binary?

**Comment by l1t1** [comment]
I append the two lines of fast config to the best config, then overwrite the data file with
`combine_tessdata -o chi_sim.traineddata chi_sim.config`
it works as expect

**Comment by heshpdx** [comment]
Also try using this directive on the cmdline for "best"
`-c preserve_interword_spaces=1`

**Comment by l1t1** [comment]
thanks @heshodx
