### ISSUE TITLE
Strange behavior when using Tesseract in Windows cmd

### ISSUE THREAD

**Issue by l1t1** [tesseract-ocr/tesseract#4034]
### Current Behavior

![2023-03-18_213026](https://user-images.githubusercontent.com/23301704/226109311-7d9b18be-5e6f-49f0-b558-cf22952a28e0.png)
the chinese character already in the cmd window doubled after an call to tesseract, but the new output is right and
all english letter characters isn't effected.

### Expected Behavior

it doesn't effect the contents of cmd windows.

### Suggested Fix

as above

### tesseract -v

tesseract v5.3.0.20221214
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0

### Other Operating System

windows 7 32bit

**Comment by l1t1** [comment]
in addition 
1. if I continue use CLI, it doesn't effect the cmd window
2. when call tesseract, all the content of the cmd window shows bold font as follwing, and return to normal font after the call is finished

**Comment by l1t1** [comment]
![2023-03-18_214928](https://user-images.githubusercontent.com/23301704/226110711-e85fd651-8523-401f-ae4f-e88f193d61e3.png)
the bold font screen

**Comment by amitdo** [comment]
I don't understand what exactly is the issue here.

We don't support pytesseract or any other 3rd party tool.

Does the issue occur when you use the official tesseract command line tool?

**Comment by l1t1** [comment]
confirmed, using the official tesseract command line tool has the problem,
see attachment

https://user-images.githubusercontent.com/23301704/226149985-f30a1935-4058-4e92-a40b-c0fbf8803095.mp4

**Comment by amitdo** [comment]
Instead of using an image/video, next time, please copy and paste the text, as you did in https://giub.com/tesseract-ocr/tesseract/issues/4032#issue-1630321061

**Comment by amitdo** [comment]
>**confirmed**, using the official tesseract command line tool **has** the problem

This comment confuses me. With Pytesseract, it seems that every character is printed twice, while this does not happen with Tesseract itself.

**Comment by l1t1** [comment]
With Pytesseract, it double the Chinese characters (the output of prior command)on the above of the current command

**Comment by amitdo** [comment]
but it does not happen with tesseract CLI, right?

As I said, we don't support 3rd party tools.

Pytesseract uses Tesseract but it addS some things to what Tesseract does. Sometimes the result is better than Tesseract and sometimes it is worst.

**Comment by l1t1** [comment]
it also happens  with tesseract CLI,see the video the first line changes as soon as I run the CLI.

**Comment by l1t1** [comment]
it also happens  with tesseract CLI,see the video the first line changes as soon as I run the CLI.

**Comment by l1t1** [comment]
so the title of issue you modified isn't right

it should be `when Tesseract  run, it double characters (chinese) that already on the screen immediately, and then it output it's result(the Chinese characters in it is right)`

**Comment by amitdo** [comment]
The title of an issue should not be so long.

I change the title, but not to what you suggested.

**Comment by amitdo** [comment]
This looks like a bug in the Windows cmd.

Maybe you can try to run Tesseract with an [alternative console](https://github.com/search?q=windows+console+stars%3A%3E2000).

**Comment by zdenop** [comment]
First of all [Windows 7 is unsupported for a long time](https://www.microsoft.com/en-us/windows/end-of-support) and Python 3.8 received only security updated. Ensure all your software is actively supported.

Windows cmd has problems with displaying of  UTF-8 (especially from older windows version). IMO latin scripts/fonts are OK usually, but preferred tesseract output should be file on Windows (AFAIK pyteseract processing OCR output via file).

Next: Please make your issue report reproducible - provide image/link to used input + information about type of langdata (fast/best/tessdata).

**Comment by l1t1** [comment]
it's very easy to reproduce the issue
1. open windows cmd
2. run tessertact
3. the Chinese character of screen doubled
4. input `echo "英伟达 A100 和 H100 GPU " `
5. run tessertact
6. the screen changed to ```echo "英英伟伟达达 A100 和和 H100 GPU "
"英英伟伟达达 A100 和和 H100 GPU "```
note: the charactors has been doubled, will not be doubled again.

**Comment by l1t1** [comment]
you only need input `tesseract`, no other arguments.

**Comment by l1t1** [comment]
https://github.com/cmderdev/cmder has the same issue

**Comment by l1t1** [comment]
![2023-03-22_091748](https://user-images.githubusercontent.com/23301704/226777458-9856489b-4560-49c8-8ee7-5539b1f4418e.png)

**Comment by amitdo** [comment]
He does not complain about the output of tesseract itself here, but about the display of the **previous** output that was changed **after** tesseract command was used.

**Comment by hglee** [comment]
This was introduced in #2546 and affects to Windows 7 cmd and Windows 10 cmd with 'Legacy console mode'. Windows 10 default cmd and Windows Terminal app should work fine.

This is an old Windows problem, and it's not easy to fix. The current recommendation is to set the Windows 7 cmd's default code page to UTF-8 (65001).  You can change the code page before execution tesseract by `chcp 65001` in cmd, @l1t1

**Comment by amitdo** [comment]
Bottom line: We don't support Windows 7/8/8.1.
