### ISSUE TITLE
how to recognize handwriting picture

### ISSUE THREAD

**Issue by l1t1** [tesseract-ocr/tesseract#4035]
### Current Behavior

I used script/HanS/HanT data and chi_sim/chi_tra 
they return empty result or very poor results

```
D:\>tesseract zq.jpg stdout -l script/HanS_vert
Empty page!!
Empty page!!

D:\>tesseract zq.jpg stdout -l script/HanT_vert
Empty page!!
Empty page!!

D:\>tesseract htv.webp stdout -l script/HanT_vert
Estimating resolution as 919
Detected 92 diacritics
5 點

i

id

笠 其 送 嗇 林 上線
洛陽 親友 號 (想 閏 二 全 水 全 在 _ 到 天
A

EI™

a
Error during processing.

D:\>tesseract zq.jpg stdout -l chi_sim_vert
Empty page!!
Empty page!!

D:\>tesseract zq.jpg stdout -l chi_tra_vert
Empty page!!
Empty page!!

D:\>tesseract htv.webp stdout -l chi_tra_vert
Estimating resolution as 919
Detected 92 diacritics
��� 1

人

名 E

平 記 送 從 枋 心 也
洪 陽 親友 娠 相 聞 -- 片 冰 《 在 玉 吉
J

EK

晶
Error during processing.

D:\>
```

### Expected Behavior

it works as normal print picture does

### tesseract -v

tesseract v5.3.0.20221214
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0

### Other Operating System

windows 7 32bit

### Other Information

the picture files
as webp cannot upload, I rename it to jpg 
![zq](https://user-images.githubusercontent.com/23301704/226165708-aab1990e-77f8-4bb1-b3d4-c062221298ab.jpg)

**Comment by l1t1** [comment]
![htv webp](https://user-images.githubusercontent.com/23301704/226165878-0d3c92cd-9dac-4c98-a93c-b032a98678e8.jpg)

**Comment by l1t1** [comment]
```
D:\>tesseract zq.jpg stdout -l script/HanS_vert
Empty page!!
Empty page!!

D:\>tesseract zq.jpg stdout -l script/HanT_vert
Empty page!!
Empty page!!

D:\>tesseract htv.jpg stdout -l script/HanT_vert
Error, cannot read input file htv.jpg: No such file or directory
Error during processing.

D:\>tesseract htv.webp stdout -l script/HanT_vert
Estimating resolution as 919
Detected 92 diacritics
5 點

i

id

笠 其 送 嗇 林 上線
洛陽 親友 號 (想 閏 二 全 水 全 在 _ 到 天
A

EI™

a
Error during processing.
```

**Comment by amitdo** [comment]
The training for all language was done using synthetically  generated images with ttf/otf fonts. Don't expect these models to give you good results on handwritten text images.

**Comment by piscopancer** [comment]
@amitdo so what if I need written text recognition? I agree with OP in that it is highly expected from a tool like tesseract to be capable of processing handwritten texts, especially in Chinese. does tesseractjs repository include .traineddata of handwriting? Afaik, no. Where should these .traineddata be found? Or are there known projects/contributors who have put effort and time to generate .traineddata and for public use? I tried searching, found none. This is weird, but can you explain why  
- there is no official tesseract traineddata for written texts out of the box,
- and if it's possible for me to create my own traineddata for handwritten Chinese and use it my nodejs project for inference, and also share it with other people, assuming its simply a single generated file that is supposed to be fed to a worker config?
