### ISSUE TITLE
how to add new words to data file?

### ISSUE THREAD

**Issue by l1t1** [tesseract-ocr/tesseract#4036]
### Current Behavior

it recognized AI to Al now

### Expected Behavior

it recognized AI to AI

### tesseract -v

tesseract v5.3.0.20221214
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0

### Other Information

![likf webp](https://user-images.githubusercontent.com/23301704/226176165-88860005-ff04-4fb7-9bab-aa7ead563574.jpg)

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.

**Comment by l1t1** [comment]
sorry, google is blocked in my region.

**Comment by l1t1** [comment]
could you open the discuss feature of github web site?

**Comment by stweil** [comment]
> could you open the discuss feature of github web site?

I don't think that splitting discussions on two different forums is the right way to handle Internet restrictions imposed by some regions of the world. But if you want a separate discussion forum for your region, you can always create one on your personal tesseract fork.

**Comment by amitdo** [comment]
>you can always create one on your personal tesseract fork.

Oh no!

People will start 'calling' @amitdo, @stweil and @zdenop in their questions...
