### ISSUE TITLE
Please, help to upgrade Tesseract for Capture2Text.

### ISSUE THREAD

**Issue by Mirdgard** [tesseract-ocr/tesseract#4038]
### Your Feature Request

Please, help to upgrade Tesseract for Capture2Text.
Maybe, help me with some hints, how I can do it myself. I'm a noob.
Here is a link, that describes a problem --
https://sourceforge.net/p/capture2text/tickets/218/

**Comment by data-man** [comment]
You can try https://github.com/xiaoyifang/Capture2Text

**Comment by zdenop** [comment]
Please respect the guidelines for posting issues: we do not provide support for 3rd party projects.

**Comment by Mirdgard** [comment]
> You can try https://github.com/xiaoyifang/Capture2Text

  Thank you for the information. But the version you suggested even lower -- >  v4.6.2

 > Please respect the guidelines for posting issues: we do not provide support for 3rd party projects.

 I will respect that, good fellow. Thank you for the clarification.
