### ISSUE TITLE
Can't build tesseract under Windows 11

### ISSUE THREAD

**Issue by LayxProud** [tesseract-ocr/tesseract#4044]
### Current Behavior

I've been trying to build this library for days now, nothing helps! I'm following instructions from [here ](https://tesseract-ocr.github.io/tessdoc/Compiling.html#windows).
0. Cleaned my system of any earlier build attempts
1. Downloaded sw, added it to PATH, ran sw setup from admin cmd, ran sw --self-upgrade also
2. Clone tesseract repo, made build subdir, ran cmake .. from there
3. cmake done, then I decided to try to compile it from console with cmake --build . --config Release --target install. After a long process right at the end I get this:
```
 Building Custom Rule D:/tesseract/src/training/CMakeLists.txt
  text2image.cpp
  degradeimage.cpp
     Creating library D:/tesseract/build/bin/Release/text2image.lib and object D:/tesseract/build/bin/Release/text2imag
  e.exp
org.sw.demo.gnome.pango.pangocairo-1.50.12.lib(pangowin32-dwrite-fontmap.cpp.52835365.obj) : error LNK2019: unresolved
external symbol __imp_DWriteCreateFactory referenced in function pango_win32_font_description_from_logfontw_dwrite [D:\
tesseract\build\src\training\text2image.vcxproj]
D:\tesseract\build\bin\Release\text2image.exe : fatal error LNK1120: 1 unresolved externals [D:\tesseract\build\src\tra
ining\text2image.vcxproj]
```
Same error occurs if I launch .sln in my VS 2022
4. I believe that this problem has something to do with  Dwrite.dll, however I clearly have it in my "C:\Windows\System32" folder
5. Before this I was getting errors with pointer to incomplete class type "Pixa" and "Box", as I was trying to build earlier versions of tesseract.

I'm very tired, Linux installation was nice and easy, opencv installation was nice and easy, but tesseract keeps upsetting me. Need help.

**Comment by LayxProud** [comment]
Tried adding "Dwrite.lib" to the list of additional dependencies of text2image, build good, but no use, after linking tesseract to a test project, get a ton of errors. I guess, it is built poorly.

![image](https://user-images.githubusercontent.com/49621292/229216132-2b5f27aa-6404-4357-a229-f667356ffbef.png)

**Comment by zdenop** [comment]
So you are able to build tesseract, but you are not able to use it in your project. Right?
From the last comment, I think you forget to include leptonica (tesseract dependency) for linking.
Anyway, I think it is time to review building documentation.

**Comment by LayxProud** [comment]
I'm rebuilding it again right now, cleaned everything and reinstalled sw, made all preparations, ran cmake. Result:
```
-- --------------------------------------------------------
--
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Configuring done (613.4s)
-- Generating done (1.2s)
-- Build files have been written to: D:/tesseract/build
```

Success, I guess. Then open my .sln file with Visual Studio 2022, choose Release, x64, select to build ALL_BUILD. Begins a long process of building sw dependencies. See [3558/3558], all good. Again, same error:
`Error	LNK2019	unresolved external symbol __imp_DWriteCreateFactory referenced in function pango_win32_font_description_from_logfontw_dwrite	text2image D:\tesseract\build\src\training\org.sw.demo.gnome.pango.pangocairo-1.50.12.lib(pangowin32-dwrite-fontmap.cpp.52835365.obj)	1`	

I won't try adding anything to linker, however will try something with sw build/install commands. Still need instructions on this matter.

**Comment by LayxProud** [comment]
I just don't understand. Configured tesseract with SW_BUILD = ON and without training tools, built it. To include it into project I need <leptonica/allheaders.h>. Where should I take it? Isn't sw build supposed to install everything I need and place it some obvious location?

So I tried to build leptonica independently, included it with tesseract into project, now I lack leptonica's dependencies, like libtiff, libpng, etc. Yesterday I built every dependency myself, included every library into basic open image->read text project, but it kept crashing after trying to create tesseract::TessBaseAPI object. 

I don't believe that installation is so complicated, on UNIX it's just 3 lines of make instructions, on windows it's a 3-day experience.

**Comment by LayxProud** [comment]
Finally installed tesseract with vcpkg and included it in my Qt project. I'm not sure if the issue should be closed, as cmake and .sln build of binaries is still a mess. However, I'm fine with vcpkg solution.

Just in case, step-by-step guide by me:
1. Install vcpkg
2. Run vcpkg install leptonica:x64-windows
3. Run vcpkg install tesseract:x64-windows 
4. Include tesseract lib in .pro file. For me it looks like this:
```
LIBS += -L$$PWD/../../../../../../Programs/vcpkg/installed/x64-windows/lib/ -ltesseract53

INCLUDEPATH += $$PWD/../../../../../../Programs/vcpkg/installed/x64-windows/include
DEPENDPATH += $$PWD/../../../../../../Programs/vcpkg/installed/x64-windows/include
```

Also, works fine with Visual Studio, however I need to manually drop tesseract .dll files near my .exe file

**Comment by zdenop** [comment]
@egorpugin : can you check and update sw documentation for building (and using) tesseract?

@LayxProud : As far as I know Qt qmake (.pro file) build is depreciated in favor of cmake.  You can build tesseract with cmake easily - have a look at [github workout file](https://github.com/tesseract-ocr/tesseract/actions/runs/4579822157/workflow) / https://github.com/tesseract-ocr/tesseract/actions/runs/4579822157.
There are several tutorials how to build tesseract (and leptonica) with cmake.

**Comment by LayxProud** [comment]
@zdenop I don't know how to thank you enough. This workflow really helped me and now I have my own tesseract! I really wish that all these instructions were listed in the official build documentation instead of sw nonsense.

**Comment by egorpugin** [comment]
It seems pango lib has missing dependency to dwrite.lib. I'll fix it.

**Comment by egorpugin** [comment]
It was sw issue. This fix will arrive with the next update.
