### ISSUE TITLE
lstmf file creation from box and tif fails on some images

### ISSUE THREAD

**Issue by MaloMaisonneuve** [tesseract-ocr/tesseract#4047]
### Current Behavior

For some images, I am getting the "Empty page!!" error when running `tesseract img.tif img.box lstm.train`.
To reproduce, run `tesseract 85.tif 85.box lstm.train` with the images provided below.

Here, the text does not contain any unknown characters to Tesseract by default.
After resizing the tif image to center vertically the text (and adapting the box file accordingly), it magically worked.
You can test this behaviour with  `tesseract 85-cropped.tif 85-cropped.box lstm.train`
I am not sure why this is happening. Shouldn't the generation of lstmf files be independant on the image size? In my mind, providing the coordinates of the box file should be enough, and image size shouldn't matter. However, I might be missing something :)

Another weird thing I have noticed is that this command also fails when the image contains only one new character (example of the ± character). Is there any way to get some insight on how `lstm.train` operates in this area, or is the code behind this function kept private?

Thanks in advance!

[lstmf.zip](https://github.com/tesseract-ocr/tesseract/files/11171920/lstmf.zip)

### Expected Behavior

The shown command should produce a `.lstmf` file.

### tesseract -v

tesseract v5.2.0.20220712
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0

### Operating System

Windows 10

**Comment by zdenop** [comment]
Please have a look at https://github.com/tesseract-ocr/tesstrain how to do training.

**Comment by MaloMaisonneuve** [comment]
Hi,

I'm well aware of the documentation as I've been working on fine-tuning Tesseract for the last couple of months.
I am not training a model from the ground  up, but only fine-tuning it.

For various reasons, I'm fine-tuning the model on custom generated data, implying that I cannot use Tesseract code to fine-tune the model according to a given font file.
Hence the need to manually generate lstmf files from box and tif files.

Is there another documentation regarding this custom process that I am not aware of?
Otherwise, do you have some answers to my questions?

**Comment by amitdo** [comment]
Tesseract do layout analysis with the command you gave it.
The layout analysis phase fails => "Empty Page!!"

This will happen also when you try to recognize the image instead of using it for training.

**Comment by amitdo** [comment]
If all your images are just 1-textline each (no columns, no blocks, no paragraphs, no tables, no frames, no photos/drawings) you can try changing the psm to `13`.

**Comment by MaloMaisonneuve** [comment]
Thanks for the reply @amitdo .

Good to know that it is the layout analysis which fails.
However, I don't think it should. The images are binary, and the text is not complicated.
Also, why would it fail on the first set of images (85.png  & 85.tif), and not on a cropped version of them?
As for the `psm` option, I don't think this is relevant as I am not in an inference phase, but merely trying to build .lstmf files which are required for he fine-tuning step.

As the generation of lstmf files is called whenever Tesseract is either trained of fine-tuned, I find it to be quite an important bug to solve. It means that Tesseract throws away some of the samples it should be training on, and thus might train on a subset of the given training set, without the user being necessarily aware of this. I have run into situations where the fine-tuned model could not recognize certain characters, because the .lstmf files were not generated for the images containing such characters.

I've also tested with the latest Tesseract version and it is still failing. Because this is an ongoing bug, I think this issue should be re-opened.
