### ISSUE TITLE
JXL (JPEG XL) support

### ISSUE THREAD

**Issue by schrmh** [tesseract-ocr/tesseract#4048]
### Your Feature Request

I want to use tesseract to search text in screenshots stored in JXL but I get this when trying `tesseract image.jxl text`:
```
Error in fopenReadStream: file not found
Error in pixRead: image file not found: �
Image file � cannot be read!
Error during processing.
```

I have hundreds of thousands in screenshots in JXL by now since those files take on average, after **lossless** convertion only about 47% of the space compared to when they were PNG (`cjxl -q 100 -m 1 -e 9 --brotli_effort 11 -E 3 -I 100 -g 3 -j 1 in.png out.jxl`). No other common file format can compete there.

**Comment by zdenop** [comment]
tesseract uses [leptonica](https://github.com/DanBloomberg/leptonica) for image-opening images, so we can do nothing here.
The future of JPEG XL is questionable (see e.g. https://www.phoronix.com/news/Chrome-Dropping-JPEG-XL-Reasons), so I doubt if anyone would be willing to invest time and resources to support it in leptonica.
