### ISSUE TITLE
Make Tesseract detect long s character: ſ

### ISSUE THREAD

**Issue by Geremia** [tesseract-ocr/tesseract#4049]
### Your Feature Request

¿How can I make Tesseract detect the long s character:

### ſ

**Comment by stweil** [comment]
Use a model which was trained with ſ, for example script/Fraktur. See https://github.com/UB-Mannheim/tesseract/wiki/FAQ for more options.

And please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
