### ISSUE TITLE
Error reported when using: sw build org.sw.demo.google.tesseract.tesseract

### ISSUE THREAD

**Issue by ZhuHust** [tesseract-ocr/tesseract#4050]
### Your Feature Request

I use three computers (two VS2019 and one VS2017) according to the tutorial. I first use: _**sw setup**_ on Git and then: _**sw build org.sw.demo.google.tsseeract.tsseeract**_, but always reported the following error. And file _D:/dev/cppan2/client2/src/sw/builder/command.cpp_ is not on my computer, I don't know how to solve the problem.I searched for someone who encountered a similar problem in 2020, but they didn't seem to provide a suitable solution. Please help me and provide suggestions
error:
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:840, function execute1: When executing: [pub.egorpugin.primitives.command-0.3.1]/src/command.cpp
C:/Users/ZhuWenbo/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(142): error C2039: "contains":  "std::basic_string<char,std::char_traits<char>,std::allocator<char>>" ĳԱ
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\xstring(4871): note: μstd::basic_string<char,std::char_traits<char>,std::allocator<char>>
C:/Users/ZhuWenbo/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): note: 鿴ڱĺ ģ ʵauto primitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ()<const char(&)[6]>(_T1) const
        with
        [
            _T1=const char (&)[6]
        ]
C:/Users/ZhuWenbo/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C3487: bool: зرʽƵΪͬ: ǰΪvoid
C:/Users/ZhuWenbo/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(144): error C3487: bool: зرʽƵΪͬ: ǰΪvoid
C:/Users/ZhuWenbo/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(144): error C2562: primitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ():voidֵ
C:/Users/ZhuWenbo/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): note: μprimitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ()
C:/Users/ZhuWenbo/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C2296: ||: Ƿvoid
C:/Users/ZhuWenbo/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C2297: ||: ǷҲvoid
command failed: exit code = 2
Total errors: 1

**Comment by amitdo** [comment]
@egorpugin

**Comment by egorpugin** [comment]
Install VS2022.

**Comment by ZhuHust** [comment]
> Thank you. Do you mean that if I use _**sw**_ to install dependencies, only VS2022 can success?  The project I am currently developing has been using VS2019 for a long time. I dare not modify the software version. Can Tesssract5.3.1 use **Cmake** to compile for VS2019, or which versions can be used in VS2019?

**Comment by zdenop** [comment]
cmake build (without sw) works with VS2019

**Comment by egorpugin** [comment]
@ZhuHust 

Sw requires VS2022 for itself.
You will be able to build using VS2019 still.

**Comment by zdenop** [comment]
@egorpugin : maybe implementing a sw check for minimum compiler version would be useful...

Anyway, this is not the tesseract issue.
