### ISSUE TITLE
Error in the test：mgr->GetComponent(TESSDATA_NORMPROTO, &fp):Error:Assert failed:in file ../../../src/classify/adaptmatch.cpp, line 554

### ISSUE THREAD

**Issue by Serendipit2024** [tesseract-ocr/tesseract#4054]
### Environment

* **Tesseract Version**: <v5.3.1.20230401>
* **Platform**: <Windows, version 64-bit >

**Comment by zdenop** [comment]
Please provide all details for reproducing problem

**Comment by Serendipit2024** [comment]
> Please provide all details for reproducing problem

I found the problem，encountered an error interrupt while executing the command to generate the tr file.    Unable to generate normproto file due to missing tr file, So the generated training data file is incorrect.Now I'm checking my box files.

**Comment by amitdo** [comment]
We can't help people that ignore our guidelines and don't provide the requested information.
