### ISSUE TITLE
I get "Error opening data file..." when using pytesseract

### ISSUE THREAD

**Issue by PriyankaLikkam** [tesseract-ocr/tesseract#4056]
input:
os.environ['TESSDATA_PREFIX'] = "C:\Program Files\Tesseract-OCR\tessdata"
custom_config = r'--tessdata-dir "/content/kan.traineddata" -l kan'
custom_config = r'-l kan --psm 6'

for img in img_list:
  im = cv2.imread(f'/content/sample_data/sample_images/{img}')
  img_rgb = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)
  output = pytesseract.image_to_string(img_rgb, config=custom_config)
  print(output)
  dictionary = {'img_filename':img, 'ocr_output':str(output)}
  df_output = df_output.append(dictionary, ignore_index=True)

output:
TesseractError: (1, 'Error opening data file C:\\Program Files\\Tesseract-OCR\tessdata/kan.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'kan\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')

**Comment by zdenop** [comment]
Please respect the guidance for posting issue:

- We do not support 3rd party projects (pytesseract). Replicate the problem with tesseract executable
- provide all required information

**Comment by amitdo** [comment]
Your code have mistakes.

```
os.environ['TESSDATA_PREFIX'] = "C:\Program Files\Tesseract-OCR\tessdata"
custom_config = r'--tessdata-dir "/content/kan.traineddata" -l kan'
custom_config = r'-l kan --psm 6'
```

instead of:

 ```
custom_config = r'--tessdata-dir "full/path/to/tessdatadir"'
custom_config += r'-l kan --psm 6'
```
In the path to Tesseract's data dir, don't add the file name (`kan.traineddata`).

If you still have issues, read what @zdenop wrote.
