### ISSUE TITLE
user_words option not recognized by tesseract 5.3.1

### ISSUE THREAD

**Issue by AlejandroFNadal** [tesseract-ocr/tesseract#4059]
### Current Behavior

The parameter --user-words is not recognized as a parameter in tesseract 5.3.1, even though in the man page is listed as a parameter. If said parameter requires an extra flag to be used, this is not clarified in the manual and I haven't found an explanation online either. 

### Expected Behavior

I would expect the --user-words parameter to accept a list of words as a txt file, each word separated by a linejump, and only output said words, applying some type of heuristics to approximate the words found with the words of the provided dictionary

### tesseract -v

```
tesseract 5.3.1
 leptonica-1.82.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.1.1) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
```

### Operating System

Ubuntu 22.04 Jammy

### uname -a

`Linux Trantor 6.2.0-10005-tuxedo #5 SMP PREEMPT_DYNAMIC Wed Mar 22 12:42:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Compiler

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04) 
```

### CPU

12th Gen Intel i7-12700H (20) @ 4.600GHz

### Virtualization / Containers

None

**Comment by stweil** [comment]
How exactly did you run `tesseract`?

**Comment by AlejandroFNadal** [comment]
Hello @stweil , thanks for your time answering. 

I have tried it like this:
`tesseract -l spa ./data/1966-03-03.jpg ./test_output --user_words /usr/share/dict/spanish`

And the response is: `Error, unknown command line argument '--user_words'`

Just in case, I also tried to use an equal sign between user_words and the path.

> That won't work of course.

Would you mind pointing me to the docs where I can find how to use this feature? I have checked in this manual: 

https://github.com/tesseract-ocr/tesseract/blob/main/doc/tesseract.1.asc#config-files-and-augmenting-with-user-data

In said manual, it just says: 

> --user-words FILE

> Specify the location of user words file.

Which I feel I have imitated in my command. 

> Note that the dictionary is not an exclusive list of words, but only a hint for the OCR which will still detect other words, too.

That is good to know, thanks :)

> And please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

I would do so next time that I have a question, thanks for pointing that out.

**Comment by zdenop** [comment]
`Error, unknown command line argument '--user_words'` is the correct response to your command. You made a typo in your command.

**Comment by AlejandroFNadal** [comment]
That was quite dumb on my part, I am sorry. Thanks for your patience
