### ISSUE TITLE
unicharset_extractor error extracting Sgaw Karen: Invalid start of Myanmar syllable:0x102c

### ISSUE THREAD

**Issue by ben417** [tesseract-ocr/tesseract#4061]
### Current Behavior

unicharset_extractor --output_unicharset data/kar/my.unicharset --norm_mode 3 data/kar/all-gt
Extracting unicharset from plain text file data/kar/all-gt
Invalid start of Myanmar syllable:0x102c
Invalid start of Myanmar syllable:0x103a
Invalid start of Myanmar syllable:0x103a
Normalization failed for string 'ကညီလံာ်ခီၣ်ထံး'
Wrote unicharset file data/kar/my.unicharset

### Expected Behavior

No errors

### Suggested Fix

Is normalization required? Is there anyway I can just disable it? My data is already normalized exactly the way I want it.

### tesseract -v

tesseract -v
tesseract 5.3.1-3-g9422
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.4) : libpng 1.6.39 : libtiff 4.4.0 : zlib 1.2.11 : libwebp 1.3.0 : libopenjp2 2.5.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.6.2 zlib/1.2.11 liblzma/5.4.1 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.4
 Found libcurl/7.86.0 SecureTransport (LibreSSL/3.3.6) zlib/1.2.11 nghttp2/1.47.0
…/tesstrain main !? 🐍 v3.11.3 (tesstrain)
➜  unicharset_extractor -v
5.3.1-3-g9422

### Operating System

macOS 13 Ventura

### uname -a

uname -a
Darwin bens-macbook.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64

### Compiler

clang

### CPU

Intel

### Virtualization / Containers

None

### Other Information

I'm trying to train a Sgaw Karen OCR model, and get the error below. My test string is valid, copied directly from here: https://en.wikipedia.org/wiki/S%27gaw_Karen_alphabet.

There's a similar issue with Western Pwo, like this test string ဖၡိ from here: https://en.wikipedia.org/wiki/Western_Pwo_language

This isn't terribly surprising, I've have seen a number of systems that don't handle Karen correctly. Like Safari/Mac until recently and Firefox still. I guess the parsing probably happens in a library of some kind? If that's the case what is it? I can open a bug report with them too.

**Comment by amitdo** [comment]
Here the relevant code:

https://github.com/tesseract-ocr/tesseract/blob/60fd2b4abaa9c5c5c42d32db57576bc95d28a78a/src/training/unicharset/validate_myanmar.cpp

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/f1e3697dd4ff6ee3726edc629a2d63b6a9dcade8/src/training/unicharset_extractor.cpp#L115-L116

Did you try using `--norm_mode 2`?

**Comment by ben417** [comment]
Yes, I tried all 3 modes.

**Comment by ben417** [comment]
Thanks for the code links.

I'm not a C++ person so I had a try at getting GPT4 to fix it for me. That's not really working out, but here's some of the sequences I identified while trying to get it to work.

# These combinations are Sgaw tone marks
0x102C 0x103A
0x1062 0x103A
0x1063 0x103A

0x102C following vowel marks
0x1036 0x102C
0x1032 0x102C
... and so on, 0x102C should be able to follow all the vowels (in Burmese 0x102C is a vowel, but in Sgaw Karen it is part of a tone mark that comes after the vowels)

0x1062 following vowels (in Karen, 0x1062 may be either a vowel mark or tone mark following the vowel (in combination with 0x103A))
0x1037 0x1062
0x1030 0x1062
... and so on, 0x1062 should be able to follow all vowels and medial consonants, including
0x1062 0x1062 (0x1062 may follow itself when it's a vowel then part of the tone mark)

0x1062 following letters:
0x1010 0x1062
0x1014 0x1062
... and so on, 0x1062 should be able to follow all normal Myanmar letters including consonants, medials, and these independent vowels:
0x1027 0x1062
0x1021 0x1062

**Comment by ben417** [comment]
(Side note, what happened to the Pwo string I pasted above? Most of it's vowels and tone marks are stripped out. GitHub issues must have done it? Unbelievable...)

**Comment by amitdo** [comment]
Fixed in #4065.
