### ISSUE TITLE
Should tesseract work on handwritten text?

### ISSUE THREAD

**Issue by erezarnon** [tesseract-ocr/tesseract#4069]
### Current Behavior

On the attached image, it gives the following gibberish output

`tesseract img.jpg - -l eng`
```
Estimating resolution as 195
Error in boxClipToRectangle: box outside rectangle
Error in pixScanForForeground: invalid box
JAMES Sys 22YLO>= 3

pL ye
(2 € 5 Zz. 7E hy K Lins =

pis 7 2 o

i;
/ A
LAOS, =
y

Z tn ps er

. , = > wr) £ > sr} os Lea
ed hy ‘ q By & 4A/l K_ £A ps me See

- x oS 2 oy ae)
v =
7 A
| ie :
‘ s 4 y he 6
/ a =
y ye VooP aly
A J 7 SO LEY
s A
J y zy \< ft
Baek BY ZOY i phi
¢ a ff !
```

![order](https://user-images.githubusercontent.com/11790423/236913579-dd71dcec-b166-4af7-b8ec-cca7a54f7f82.jpg)

### tesseract -v

tesseract 5.1.0
 leptonica-1.82.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.1.1) : libpng 1.6.38 : libtiff 4.4.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.5.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.6.0 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.8
 Found libcurl/7.85.0 OpenSSL/3.0.5 zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.49.0 librtmp/2.3

### Other Operating System

Ubuntu 22.10

### uname -a

Linux erez-ThinkPad-T14-Gen-3 5.19.0-41-generic #42-Ubuntu SMP PREEMPT_DYNAMIC Mon Apr 17 19:17:03 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
