### ISSUE TITLE
used vs2010 complice for eeror:

### ISSUE THREAD

**Issue by molyswu** [tesseract-ocr/tesseract#407]
Hi, When I use VS to compile the following error

 fatal error C1083: 无法打开包括文件:“allheaders.h”: No such file or directory
Excuse me is the reason?

**Comment by zdenop** [comment]
You forget to read instructions ;-)

**Comment by Shreeshrii** [comment]
Use latest installer for windows from
https://github.com/UB-Mannheim/tesseract/wiki

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com
