### ISSUE TITLE
PSM for maintaining the English / Western reading order for PDF scanned text with double column layout

### ISSUE THREAD

**Issue by kodymoodley** [tesseract-ocr/tesseract#4072]
### Your Feature Request

Traditional English literature with double column text are read from top to bottom per page and left to right for each column. I have noticed some OCR'd documents in a dataset I came across that did not maintain this kind of order in the extracted text. I have no idea if the documents were OCR'd by tesseract or not but I was wondering if tesseract has this feature to extract text by maintaining the reading order. If tesseract does provide this, I plan to re-OCR the documents to correct the order. 

I had a look through tesseracts PSM list and it does not seem to provide anything for what I need (double column). But perhaps I am misunderstanding how PSM works?

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for asking questions.
