### ISSUE TITLE
Error in pixReadMemTiff: function not present

### ISSUE THREAD

**Issue by ucas010** [tesseract-ocr/tesseract#4076]
### Current Behavior

`time tesseract test.jpeg -l chi_sim`
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
Error opening data file /root/tesseract/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.

real	0m0.005s
user	0m0.002s
sys	0m0.003s

### tesseract -v

tesseract 4.1.1
 leptonica-1.79.0
  libjpeg 6b (libjpeg-turbo 1.2.90) : zlib 1.2.7
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE

### Operating System

RHEL 8

### Other Operating System

centOs 7.9

### uname -a

Linux gpu-node02 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stweil** [comment]
I suggest to use the newer Tesseract which is provided with your operating system instead of a self-compiled one.

And please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by zhujinrun** [comment]
**You can install the tiff denpency, and reinstall your leptonica:**

```bash
sudo yum -y install libtiff-devel

cd leptonica-1.74.4
./configure --prefix=/usr/local/
make
sudo make install
```
