### ISSUE TITLE
GitHub actions vcpkg-4.1.1 failing since two years

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#4078]
### Current Behavior

Since two years the GitHub action vcpkg-4.1.1 always fails. @Shreeshrii, can this action be removed?

**Comment by zdenop** [comment]
I am wandering if we need workflow in GitHub action for vcpkg ([there are 2](https://github.com/tesseract-ocr/tesseract/actions/workflows))...
vcpkg is maintained outside of tesseract project and we can not influence it directly.
AFAIK vcpkg it is using cmake for building tesseract&leptonica, so if cmake build is ok, also vcpkg should work too.

**Comment by amitdo** [comment]
Regarding vcpkg-4.1.1, I suggest to remove it.

**Comment by stweil** [comment]
Thanks. It's now removed.
