### ISSUE TITLE
positional ocr of dvd and bd subs

### ISSUE THREAD

**Issue by eddilara** [tesseract-ocr/tesseract#4081]
### Your Feature Request

if you combine ffmpeg and tesseract....it should be possible to get positional frame data of the text in the frame
and its been a  BADLY needed feature for those of us that do OCRing of dvd and bd subs for many many years now

I have attached a very good example of the sub file that has a lot of this positional use 

(and yes I understand theres no positional data in the sub file...thats where ffmpeg in conjunction with tesseract  should come in...it should be able to find that data in relation to the size of the frame)

the output subtitle would have to be .ass since its one of the more popular types with positional use

[subs.zip](https://github.com/tesseract-ocr/tesseract/files/11523304/subs.zip)

**Comment by amitdo** [comment]
This feature is outside the scope of Tesseract itself.

**Comment by amitdo** [comment]
Duplicate of #4004 from the same OP.
