### ISSUE TITLE
How can I proceed with Cropped Images?

### ISSUE THREAD

**Issue by qarimbas** [tesseract-ocr/tesseract#4084]
Hello,

I have a detection model that finds texts and crops them. I would like to use Tesseract for recognizing the texts inside the cropped images. The problem is that finding all OCR results are taking too much time. Is there a way for speeding up the process? And since I have a detection model, is it possible to use Tesseract recognition module only?

Thanks in advance.

**Comment by amitdo** [comment]
Please use our [forum](https://groups.google.com/d/forum/tesseract-ocr) for support.
