### ISSUE TITLE
Tesseract.js Tables recognitions Text Extraction

### ISSUE THREAD

**Issue by desousar** [tesseract-ocr/tesseract#4085]
### Current Behavior

I already read the issue [1979](https://github.com/tesseract-ocr/tesseract/issues/1979) but it doesn't help me.

I run Tesseract.js in my browser importing the CDN [https://unpkg.com/tesseract.js@4.0.2/dist/tesseract.min.js](https://unpkg.com/tesseract.js@4.0.2/dist/tesseract.min.js) (so only client side process).

I want to extract the text that is inside this table/grid.

Here are 2 examples:
A: 
![good2](https://github.com/tesseract-ocr/tesseract/assets/44868857/192de308-6c87-4d65-bb9d-4afc987d24a9)
B: 
![bad2](https://github.com/tesseract-ocr/tesseract/assets/44868857/04ffb07d-c7a0-45db-bd5e-38d3489ee071)

You can use https://tesseract.projectnaptha.com/ to test each of them ;)

I use `await Tesseract.recognize(blob, 'eng');`

Result: The text in A is well extracted, but the text in B is not (do not care about highlighting).

I think A is correctly recognized because of the thresholding preprocessing (the table is hell gray and therefore can be removed). But the table of B is black.

Can someone help me ?

**Comment by amitdo** [comment]
You ignored this rule, which is one of the rules listed when you open a bug report:

>Don't open an issue which involves 3rd party tools that use Tesseract as a library. Only report about an issue with the Tesseract command line tool or the C/C++ API.

Please respect our rules when submitting a bug report.
