### ISSUE TITLE
White font on dark background

### ISSUE THREAD

**Issue by MeinDeutschkurs** [tesseract-ocr/tesseract#4086]
### Current Behavior

Missing lines with white text on dark background. Yes, the arabic part seems to be logic, because of the language German.

Input:
![Unknown-2](https://github.com/tesseract-ocr/tesseract/assets/129950466/391631ec-0f34-4081-b8a0-60e869f71cf4)

Output:
Warum ziehen Lachse so beharrlich
flussaufwarts?

3-Flucht vor dem Salzwasser
4-Mangel an Lebensraum

d@bbuw (ilo! yujyam clonc

### Expected Behavior

Get all text from the image.

### Suggested Fix

I have no idea, I'm not a programmer. Sorry.

### tesseract -v

tesseract 5.3.1
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.5.1) : libpng 1.6.39 : libtiff 4.5.0 : zlib 1.2.11 : libwebp 1.3.0 : libopenjp2 2.5.0
 Found NEON
 Found libarchive 3.6.2 zlib/1.2.11 liblzma/5.4.1 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.4
 Found libcurl/7.88.1 SecureTransport (LibreSSL/3.3.6) zlib/1.2.11 nghttp2/1.51.0

### Operating System

macOS 13 Ventura

### uname -a

Darwin 10.0.0.3 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103 arm64

### Compiler

was taken from brew 

### CPU

M1 7GPU

### Virtualization / Containers

none

**Comment by amitdo** [comment]
https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html

**Comment by amitdo** [comment]
These images would probably give you a better result:

![i4086-2](https://github.com/tesseract-ocr/tesseract/assets/13571208/ba1fca01-18dd-424d-af82-38e3f630eebc)

![i4086-3](https://github.com/tesseract-ocr/tesseract/assets/13571208/f04c8d27-adcd-4093-9ec3-c5fbbd792fa5)

Both were made using GIMP.

**Comment by MeinDeutschkurs** [comment]
Thank you very much for your advice, @amitdo. I was reading the advices. And yes, it helped a lot. Amazing, thx. I also found an alternative, which is natively available on macOS. It makes "LiveText" available for command line. The live text results are overwhelming - in comparison, but it's not platform independent and - except to the GitHub repo, which makes use of it, closed source. https://github.com/Shakshi3104/LiTeX - So I'm pending between solutions.
