### ISSUE TITLE
Windows Command Line Install

### ISSUE THREAD

**Issue by KrishPatel13** [tesseract-ocr/tesseract#4089]
### Your Feature Request

As a user, I would like to make use of Tesseract in the software I am developing. 

For which, our client and/or users are mostly non-technical background. We already have a Installation script for our software.
I do not use MacOS. But I did saw a Homebrew and "sudo apt install ... "1-liner command tesseract installation for MacOS.
Link for reference: _https://tesseract-ocr.github.io/tessdoc/Installation.html_

Since our software depends upon Tesseract, we would like to make sure that we install it for all users. Specifically speaking of Windows,

Do we have a one-command line installation for it?

As I had to downloads the binaries (exe file) and manually click "Next" ... To install Tesseract. 
How can I automate that for windows (or have a 1-click install ? )

**Comment by amitdo** [comment]
We don't provide an installer.

The installer you're talking about is made by another entity:

https://github.com/UB-Mannheim/tesseract/wiki

So you should ask them about their installer.
