### ISSUE TITLE
tesseract hangs if no available cpu core

### ISSUE THREAD

**Issue by Paul-Taylor-EU** [tesseract-ocr/tesseract#4091]
### Current Behavior

Running tesseract 5.3.0 I repeatedly got //Page 1//200 Diacritics//hangs

I tried different ways of preparing the input, updating tesseract, etc.

Then I ran "top" and found another process that was taking "100% CPU", although I think there are four cpu cores on my laptop and 400% is actually full capacity.

When I killed the zombie process and re-ran tesseract, it worked.

### Suggested Fix

If the program can't allocate the cpus or processes that it requires, generate an error message to say so! Don't just hang!

### tesseract -v

tesseract 5.3.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.2.2 zlib/1.2.11 liblzma/5.2.2 bz2lib/1.0.6 liblz4/1.7.1
 Found libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3

### Operating System

Ubuntu 20.04 Focal

### uname -a

Linux maclane 5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Actually Ubuntu 18.04

### Compiler

Ubuntu package from
sudo add-apt-repository ppa:alex-p/tesseract-ocr5

### CPU

Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz

**Comment by zdenop** [comment]
Do you have images/steps that can help to replicate problem?
Did you tried to disable OpenMP (see https://github.com/tesseract-ocr/tesseract/issues/1081)?

**Comment by Paul-Taylor-EU** [comment]
This happened with both .tiff and .png formats. It was a page just containing text (in French) from a 1922 Polish maths journal. SO I doubt whether the nature of the input was the issue.

The zombie process was a mail reader, or some program it called, so that can't be reproduced.  However, after I killed that, tesseract worked fine.

I don't know what OpenMP is.  Neither running the program nor searching the Web gave me any suggestion as to the possible cause or solution.

**Comment by Paul-Taylor-EU** [comment]
Following the link to #1081 did not enlighten me as to what OpenMP is.  I am using a Ubuntu package, as above, and did not compile tesseract myself

**Comment by stweil** [comment]
Tesseract has no special code which waits for available CPU cores. The binaries which are provided by Debian or Ubuntu use OpenMP, a library which provides multithreading, and up to 4 threads. It only depends on the operating system how CPU cores are assigned to individual processes and threads. Even if a process tries to use all available CPU cores, other processes will still get processing time unless that process has a higher priority.

So I am afraid that nothing can be done on the Tesseract side for the issue reported here, unless we have a test scenario which allows us to reproduce the problem.
