### ISSUE TITLE
I have some problems when using the api

### ISSUE THREAD

**Issue by yyf117** [tesseract-ocr/tesseract#4094]
### Your Feature Request

when I use the function GetComponentImages,this function returns a pointer to Boxa type.when I want to operate on that pointer,visual studio prompts the following error：
pointer to incomplete class type "Boxa" is not allowed.  （The same problem also occurs in types such as Pixa, Boxaa, etc..I checked using visual studio and find that Boxa,Pixa type have only type declarations but no definitions.The api interface does not appear to be the cause of the problem.Mainly these of the types tesseract uses are not defined and implemented.I don't know how to fix it）

Here is my code：

#include <iostream>
#include <leptonica/allheaders.h>
#include "opencv2/opencv.hpp"
#include <tesseract/baseapi.h>
#include <tesseract/publictypes.h>
#include <opencv2/imgproc.hpp>

using namespace cv;

int main()
{

    std::string filename = "3.png";
    Mat img;
    img = imread(filename);
    cv::cvtColor(img,img,COLOR_BGR2RGB);
    if (img.data==nullptr)
    {
        printf("No image data \n");
        return -1;
    }
    int w = img.cols;
    int h = img.rows;
    tesseract::TessBaseAPI api;
    // Initialize tesseract-ocr with English, without specifying tessdata path
    if (api.Init(NULL, "eng"))
    {
        std::cout << stderr << std::endl;
        exit(1);
    }
    api.SetImage((uchar*)img.data, img.cols, img.rows, img.channels(), img.step);
    
    //Pix* pix=api.GetInputImage();
    Boxa* boxes = api.GetComponentImages(tesseract::RIL_TEXTLINE, true, NULL, NULL);
    boxes->         //try to do something,Here is where it went wrong

    api.End();

	return 0;
}

**Comment by zdenop** [comment]
Please respect the guidelines for posting issues: use tesseract user forum for asking questions/support.
