### ISSUE TITLE
Does tesseract-ocr have Romanian language?

### ISSUE THREAD

**Issue by me-suzy** [tesseract-ocr/tesseract#4095]
### Your Feature Request

I need to test some PDF old book writtent in Romanian, and I need to see if tesseract-ocr is much better OCR then AbbYY Finereader.

Does tesseract-ocr have Romanian language?

is **ron.traineddata** for romania ?

**Comment by zdenop** [comment]
Please respect the guidelines for posting issues: use tesseract user forum for asking questions/support.
