### ISSUE TITLE
Unable to compile 3.04-rc1 under ubuntu 14.04

### ISSUE THREAD

**Issue by grapemix** [tesseract-ocr/tesseract#41]
The same issue is reported in https://code.google.com/p/tesseract-ocr/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&groupby=&sort=&id=1307

But the problem is still exists and the ticket is closed.

I got the error during compiling.

The error is:
libtool: link: g++ -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o  ./.libs/libtesseract.so -lrt -llept -lpthread
 ./.libs/libtesseract.so: undefined reference to `l_generateCIDataForPdf'
 ./.libs/libtesseract.so: undefined reference to `l_CIDataDestroy'

---------------------------------------------------------------------------------------------------
tesseract -v
tesseract 3.03
 leptonica-1.72
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8
--------------------------------------------------------------------------------------------------
And here is the deb package I installed:
      "autoconf",
      "automake",
      "libtool",
      "libpng12-dev",
      "libjpeg-turbo8-dev",
      "g++",
      "libtiff5-dev",
      "libopencv-dev",
      "libopencv-objdetect-dev",
      "libopencv-highgui-dev",
      "libopencv-legacy-dev",
      "libopencv-contrib-dev",
      "libopencv-videostab-dev",
      "libopencv-superres-dev",
      "libopencv-ocl-dev",
      "libcv-dev",
      "libhighgui-dev",
      "libcvaux-dev",
      "libtesseract-dev",
      "git",
      "cmake",
      "build-essential",
      "libleptonica-dev",
      "liblog4cplus-dev",
      "libcurl3-dev",
      "python2.7-dev",
      "tk8.5",
      "tcl8.5",
      "tk8.5-dev",
      "tcl8.5-dev",
      "imagemagick"

I basically follow the instruction in https://realpython.com/blog/python/setting-up-a-simple-ocr-server/

Please help. Thanks.

**Comment by zdenop** [comment]
That error means that you are not linking against leptonica 1.72 library (but probably against some older version). It is not tesseract problem.

**Comment by grapemix** [comment]
Thanks for you quick response. My bad, I assume the lib will be ready after configure. Anyway, for the future reference, since we have to compile leptonica in ubuntu 14.04, we should use `LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make` instead of make.

Then the problem will be resolved.

Thanks.

**Comment by Sayanava** [comment]
Hi,
I am using tesseract-3.04.00 and for leptonica i tried both with 1.72 & 1.71.Still i get the below mentioned issue:-
./.libs/libtesseract.so: undefined reference to `l_generateCIDataForPdf'
./.libs/libtesseract.so: undefined reference to `l_CIDataDestroy'

Request help on this.

**Comment by ws233** [comment]
Why do you need to compile it manually? The repository already contains prebuilt library binaries for arm and Mac-os architectures for you. Just download and use them.

**Comment by ws233** [comment]
Sorry, got lost in thoughts and published the commit here. Will remove it as soon as I'll reach my laptop :)

**Comment by Sayanava** [comment]
Sorry for the inconvenience.Was able to resolve the issue.Thanks.

**Comment by itamargreen** [comment]
How did you resolve it?

**Comment by johnny5550822** [comment]
Yes, how did you solve it @Sayanava ?

**Comment by leejason** [comment]
I removed previous 3.03 and re-install 3.04 from scratch. It works.
