### ISSUE TITLE
Latest trained data file crashed upon init when using tesseract 3.02 for several languages

### ISSUE THREAD

**Issue by iori57** [tesseract-ocr/tesseract#410]
Hi,

My Android app is still using an older version of tess two library, which was based on tesseract 3.02. Last time it used to work because it uses trained data for version 3.02, but since tesseract has moved to github seems like we could only download the latest version of trained data now. 

I tested with english and several european languages trained data and it works perfectly fine, however when I try Arabic, Japanese and Chinese the app crashes straightaway upon tesseract init.

My questions are, is the latest trained data in github only works with latest 3.05 version of tesseract? If so, is there a way to download the older versions of trained data? If not what could be the problem for the crash?

Thanks!

**Comment by amitdo** [comment]
You can't use a trainddata which was prepared with a version of Tesseract that is newer than the version you use to do OCR.

**Comment by amitdo** [comment]
https://sourceforge.net/projects/tesseract-ocr-alt/files/

https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md

**Comment by iori57** [comment]
Thanks for the quick response! Cheers

**Comment by hmilyyjm** [comment]
i have the same question,i will try~~~
