### ISSUE TITLE
Error during processing after detecting 20 diacritics

### ISSUE THREAD

**Issue by jeremiecourlivant** [tesseract-ocr/tesseract#4100]
### Current Behavior

I have a pdf that convert with convert from ImageMagick with the command convert -density 300 -quality 100 -alpha remove file.pdf file.jpg

Then when I make this command : tesseract 'file.jpg' 'file' pdf , the command fails with this logs : 

Estimating resolution as 241
Detected 20 diacritics
Error during processing.

The image and the pdf source : 

![3276000700067-DUSTBINS REMIX SLIM SENSEA BLACK-FUCHENG-ARTWORK](https://github.com/tesseract-ocr/tesseract/assets/17291406/0bcbd732-d0e3-4841-b1f6-0e35c1742112)
[3276000700067-DUSTBINS REMIX SLIM SENSEA BLACK-FUCHENG-ARTWORK.pdf](https://github.com/tesseract-ocr/tesseract/files/12029056/3276000700067-DUSTBINS.REMIX.SLIM.SENSEA.BLACK-FUCHENG-ARTWORK.pdf)

### Expected Behavior

A pdf in result or more logs to precise the error.

### tesseract -v

tesseract 5.3.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.2.2 zlib/1.2.11 liblzma/5.2.2 bz2lib/1.0.6 liblz4/1.7.1
 Found libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3

### Other Operating System

Linux Mint 19 Tara

### Virtualization / Containers

Directly on my computer

### Other Information

Tesseract works with other pdf with the same proccess, convert then tesseract in the same environnement.

**Comment by jeremiecourlivant** [comment]
After I check, I can show the image.

So in the attachments, the pdf source and the image.

Thanks,
Jérémie

![3276000700067-DUSTBINS REMIX SLIM SENSEA BLACK-FUCHENG-ARTWORK](https://github.com/tesseract-ocr/tesseract/assets/17291406/0bcbd732-d0e3-4841-b1f6-0e35c1742112)
[3276000700067-DUSTBINS REMIX SLIM SENSEA BLACK-FUCHENG-ARTWORK.pdf](https://github.com/tesseract-ocr/tesseract/files/12029056/3276000700067-DUSTBINS.REMIX.SLIM.SENSEA.BLACK-FUCHENG-ARTWORK.pdf)

**Comment by stweil** [comment]
The error is throwns because that image has four color components:
```
253006252-0bcbd732-d0e3-4841-b1f6-0e35c1742112.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 300x300, segment length 16, baseline, precision 8, 3451x2058, components 4
```

The function `tesseract::TessPDFRenderer::imageToPDFObj` currently only handles images with one (DeviceGray color space) or three (DeviceRGB color space) color components. DeviceCMYK color space is not implemented.

With modified code, it creates this PDF:
[out.pdf](https://github.com/tesseract-ocr/tesseract/files/12029698/out.pdf)

**Comment by jeremiecourlivant** [comment]
Thank you for your response.

I test to use convert with the -colorspace RGB with jpg and it's working. I also test with extensions and tiff and it's working too.

So my problem it's solved.
