### ISSUE TITLE
Having trouble with simple OCR

### ISSUE THREAD

**Issue by chiwalfrm** [tesseract-ocr/tesseract#4107]
### Current Behavior

ubuntu@awstokyo:~/extra$ tesseract /tmp/bsavecharts3.jpg - quiet | head -1
Alpha Trend+ High © 0.00 0.00 9.09 0.00 0.00 0.00 0.00 3049.34

![bsavecharts3](https://github.com/tesseract-ocr/tesseract/assets/19750415/9d875074-d1a9-4bdf-b858-139e564555a4)

### Expected Behavior

The last number should be 30049.34.  It's missing a 0.

### tesseract -v

ubuntu@awstokyo:~/extra$ tesseract -v
tesseract 4.1.1
 leptonica-1.82.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.1.1) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found libarchive 3.6.0 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.8
ubuntu@awstokyo:~/extra$

### Operating System

Ubuntu 22.04 Jammy

### uname -a

ubuntu@awstokyo:~/extra$ uname -a
Linux awstokyo 5.19.0-1028-aws #29~22.04.1-Ubuntu SMP Tue Jun 20 19:13:00 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### CPU

Graviton (AWS)

**Comment by Parryword** [comment]
According to Wikipedia page of Tesseract,
> Tesseract's output will have very poor quality if the input images are not preprocessed to suit it: Images (especially [screenshots](https://en.wikipedia.org/wiki/Screenshot)) must be [scaled](https://en.wikipedia.org/wiki/Image_scaling) up such that the text [x-height](https://en.wikipedia.org/wiki/X-height) is at least 20 pixels

The character height of the font in your image is about 10px. Furthermore, very light colors like yellow may cause binarization problems.

**Comment by chiwalfrm** [comment]
thank you for that explanation
