### ISSUE TITLE
Tesseract build error

### ISSUE THREAD

**Issue by zky97** [tesseract-ocr/tesseract#4109]
How do I solve this problem when I try to build
use cmake Ver：3.27
`-- Setting policy CMP0091 to NEW
-- Configuring tesseract version 5.3.2-10-ga726...
-- IPO / LTO supported
-- CMAKE_SYSTEM_PROCESSOR=<AMD64>
-- sw: processing dependencies
[146/146] C:/Users/xxx/.sw/storage/tmp/cfg/164237/loc.sw.self.0abdc1-0.0.30.dll
Exception in file D:/dev/cppan2/client2/src/sw/driver/module.cpp:74, function Module: Bad config ABI version. Module ABI (31) is greater than binary ABI (30). Update your sw binary. Will rebuild on the next run.
sw command: C:/ProgramFiles/sw-master-windows/sw.exe -static -platform x64 -compiler msvc-19.35 -d G:/GIT/tesseract/build/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps G:/GIT/tesseract/build/.sw/cmake/sw.txt -cmake-file-version 7
CMake Error at C:/Users/xxx/.sw/storage/etc/sw/static/SWConfig.cmake:253 (message):
  sw: non-zero exit code: 1
Call Stack (most recent call first):
  CMakeLists.txt:394 (sw_execute)

-- Configuring incomplete, errors occurred!`

**Comment by zdenop** [comment]
This is not tesseract issue but [sw ](https://software-network.org/) issue - please report it at [software-network issue tracker](https://github.com/SoftwareNetwork/sw/issues).
