### ISSUE TITLE
not recognizing simple image

### ISSUE THREAD

**Issue by kodeine** [tesseract-ocr/tesseract#411]
So i'm trying to ocr the following images but looks we its not doing it 100%. six is written as five. nine is written as 3. Any suggestions?

![4](https://cloud.githubusercontent.com/assets/8620059/18191919/f9a3192a-7094-11e6-8c76-51033519563b.png) <> 03074728779 

![3](https://cloud.githubusercontent.com/assets/8620059/18191916/f9a1d7a4-7094-11e6-8350-deda3bd85289.png)  <> 03214281580

![2](https://cloud.githubusercontent.com/assets/8620059/18191918/f9a32d7a-7094-11e6-988f-3a797fac907e.png) <> 03214325330

![1](https://cloud.githubusercontent.com/assets/8620059/18191917/f9a21eb2-7094-11e6-81a9-a8d4a1f86fb1.png) <> 03224455785

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support
