### ISSUE TITLE
MSYS2 pacman error

### ISSUE THREAD

**Issue by alexmironof** [tesseract-ocr/tesseract#412]
`pacman -S mingw-w64-tesseract-ocr-osd` returns can't find target `mingw-w64-tesseract-ocr-osd`

**Comment by Shreeshrii** [comment]
Those instructions maybe old.

See
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-tesseract-ocr/PKGBUILD

For 3.05 dev version with the latest binaries for Windows with all bug
fixes., Use the pkg from
https://github.com/UB-Mannheim/tesseract/wiki
- sent from my phone. excuse the brevity.

**Comment by alexmironof** [comment]
thanks for response
