### ISSUE TITLE
Ignore: "[tesseract] Image too small to scale!! (2x?? vs min width of 3)"

### ISSUE THREAD

**Issue by JoKalliauer** [tesseract-ocr/tesseract#4121]
### Your Feature Request

I would like to ignore the Warning that the Image is too small.

I ocr several pdfs within a folder, and this warning distracts from more important ones, can I disable specific warnings?

## Version:
_Creator_: `ocrmypdf 14.3.0 / Tesseract OCR-PDF 5.3.2-8-gd1ab`
_Producer_: `pikepdf 8.2.1`

## OS:
```bash
 Static hostname: STATIK38
       Icon name: computer-container
         Chassis: container
      Machine ID: 70e072ba97f8467aab25f052fd97f265
         Boot ID: 5581b2892bd84ebabc6d720ed3f35653
  Virtualization: wsl
Operating System: Ubuntu 22.04.3 LTS
          Kernel: Linux 5.15.90.1-microsoft-standard-WSL2
    Architecture: x86-64
```

**Comment by stweil** [comment]
It is currently not possible to disable warnings from Tesseract, but of course it is possible to filter any `stdout` and `stderr` output by using a pipe with `grep`, for example.
