### ISSUE TITLE
Update all datasets that are older than 6 years and increase accuracy of the LSTM models

### ISSUE THREAD

**Issue by urosjarc** [tesseract-ocr/tesseract#4123]
### Current Behavior

When it comes to the opensourced product there is always
conflict of interest when they compete with paid products...

Google has Vision AI which is paid product and there is an tessaract-ocr which is opensourced product...
And as I see it google has no interest to make significant contribution to this product because of it...

What grinds my gears is that all dataset are on average 6 years old, and accuracy of the software is catastrophic.
I tried many settings and image manipulation techniques but best data models are joust failing to read simple text like they are a
small toddler trying to read a book...

The average accuracy of the models are around 75% if you apply advanced image manipulation techniques and text extraction to
serve tesseract the best data for the OCR.

# Few examples of failed OCR...

![_naslov](https://github.com/tesseract-ocr/tessdata_best/assets/8678755/007f1855-23b9-4c06-9e20-349701cf8257)
"3.1 Izjave ee ii"

![_naslov](https://github.com/tesseract-ocr/tessdata_best/assets/8678755/296a6105-c4fe-4fb9-a58d-22e6c44023da)
"2.1 Relacija deljivosti ee"

![_naslov](https://github.com/tesseract-ocr/tessdata_best/assets/8678755/6c5cd073-7cc1-4be6-94ec-554e9f7013c7)
"3.2 Množice ---M"

# Datasets all older than 6 years
![image](https://github.com/tesseract-ocr/tessdata_best/assets/8678755/f8814f11-65ed-43b9-8c60-e05b3d0b6c1f)

**Comment by stweil** [comment]
This is a [duplicate](https://github.com/tesseract-ocr/tessdata_best/issues/79), so I close it.
