### ISSUE TITLE
Tesseract Custom Model Not Recognized after Training

### ISSUE THREAD

**Issue by demian-DL** [tesseract-ocr/tesseract#4125]
### Your Feature Request

Hello Tesseract Community,

I am facing a challenge with my custom-trained Tesseract model, and I'm hoping for some guidance on resolving this issue.

**Background:**

I've successfully trained a custom model (ocrtensor.traineddata).
The training finished without any error and I've copied the generated .traineddata file to /usr/share/tesseract-ocr/4.00/tessdata/.
I'm trying to use this model in a Jupyter Notebook container with the pytesseract Python package.
Problem:

Even though the model was working fine previously, I am now encountering an error when trying to use the model. The error suggests that Tesseract can't initialize with the custom model:

```TesseractError: (1, "Error: LSTM requested, but not present!! Loading tesseract. Error: Tesseract (legacy) engine requested, but components are not present in /usr/share/tesseract-ocr/4.00/tessdata/ocrtensor.traineddata!! Failed loading language 'ocrtensor' Tesseract couldn't load any languages! Could not initialize tesseract.")```

**Steps Tried:**

Ensured the Tesseract version compatibility (using version 4).
Checked file permissions (even tried with chmod 777).
Restarted Jupyter Notebook container multiple times.
Tried executing Tesseract from the terminal directly.
Made sure the TESSDATA_PREFIX environment variable is set correctly.
Tried Tesseract with logging enabled for additional error details.
I'm unsure why the model suddenly isn't recognized when it was working just a while ago. If anyone has insights or suggestions on what might be going wrong, I would greatly appreciate it.

Thank you for your assistance.

**Comment by zdenop** [comment]
Read the error message carefully and fix the problem.

**Comment by AhmadHakami** [comment]
I faced the same problem with the finetuned version, even when I set `export TESSDATA_PREFIX` with the traineddata file directory and run `tesseract --list-langs`, it is found there but the error message remains the same when run `tesseract <image-path>` -l`<finetuned-name>.traineddata`

any updates on this issue or how to solve it?

thanks in advance

**Comment by AhmadHakami** [comment]
figured it out 

after run `tesseract --help`  and received ` tesseract imagename outputbase [options...] [configfile...]` you have to define parameters ordinally to make it work

good luck :)

**Comment by surya-1729** [comment]
what are the parameters that you mean? after training, i see files - finetunedmodel.traineddata, checkpoint files. could you detail a bit.
