### ISSUE TITLE
CMakeLists.txt caused missing "allheaders.h" error

### ISSUE THREAD

**Issue by zhantong** [tesseract-ocr/tesseract#413]
Follow the latest compilation guide for windows platform faces VS compile error:

“allheaders.h”: No such file or directory

This error actually comes from CMakeLists.txt:

```
if (NOT USES_CPPAN)
    target_link_libraries       (tesseract ${Leptonica_LIBRARIES})
    export(TARGETS tesseract FILE ${CMAKE_BINARY_DIR}/TesseractTargets.cmake)
else()
    target_link_libraries       (tesseract cppan)
    file(WRITE ${CMAKE_BINARY_DIR}/TesseractTargets.cmake "include(${CMAKE_BINARY_DIR}/cppan.cmake)\n")
    export(TARGETS tesseract APPEND FILE ${CMAKE_BINARY_DIR}/TesseractTargets.cmake)
endif()
```
Here `USES_CPPAN` is undefined, and the if statement is always True. Since Leptonica is loaded from CPPAN, and `target_link_libraries(tesseract cppan)` is never excuted, error happens!

After modify the codes above into
```
target_link_libraries       (tesseract cppan)
file(WRITE ${CMAKE_BINARY_DIR}/TesseractTargets.cmake "include(${CMAKE_BINARY_DIR}/cppan.cmake)\n")
export(TARGETS tesseract APPEND FILE ${CMAKE_BINARY_DIR}/TesseractTargets.cmake)
```
VS builds tesseract305.dll successfully.

`USES_CPPAN` needs definition!
pull request #416

**Comment by zhantong** [comment]
#416

**Comment by zhantong** [comment]
#416

**Comment by zdenop** [comment]
@egorpugin - Can you have a look at this?

**Comment by egorpugin** [comment]
Hi, sure.
The issue is that I removed USES_CPPAN definition and you downloaded the new version.
The modern variable is 'CPPAN_BUILD'.
I'll fix this and close the PR.
@zhantong  thanks for pointing this out!

**Comment by egorpugin** [comment]
See 193032a

**Comment by Lotto2** [comment]
Hi, 

in the version i downloaded, the correction discribed in [https://github.com/tesseract-ocr/tesseract/commit/193032a7786fafc4e633869a1b10457f849cb34b](url) is present.

I loaded the project in VS 2013. Compiling the  project results in a long list of errors 

error C1083: "allheaders.h": No such file or directory	d:\projekte\vs\sharpmapprojekte\tesseract\tesseract-master\ccmain\tesseractclass.h	29	1	libtesseract304
error C1083: "allheaders.h": No such file or directory	D:\Projekte\VS\SharpMapProjekte\Tesseract\tesseract-master\ccstruct\imagedata.cpp	33	1	libtesseract304
...
total of 110 errors of that kind.

In all the sourcefiles named the line 

`#include "allheaders.h"`

is found. But file allheaders.h is nowhere to be found.

Can someone please help me?

**Comment by egorpugin** [comment]
Try to follow this guide https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows

**Comment by Lotto2** [comment]
Hi egorpugin,

i tried to follow this guide. 

the batch did not work correct.

`cmake .. -DSTATIC=1`

result:

...
CMake Error at CMakeLists.txt:54 (find_package):
  Could not find a package configuration file provided by "Leptonica"
  (requested version 1.71) with any of the following names:

    LeptonicaConfig.cmake
    leptonica-config.cmake

  Add the installation prefix of "Leptonica" to CMAKE_PREFIX_PATH or set
  "Leptonica_DIR" to a directory containing one of the above files.  If
  "Leptonica" provides a separate development package or SDK, be sure it has
  been installed.
...

What / where is Leptonica?

**Comment by egorpugin** [comment]
Did you do all steps with `cppan` decribed there?
