### ISSUE TITLE
Not recognizing correctly image with clear digit on it

### ISSUE THREAD

**Issue by dwissmann** [tesseract-ocr/tesseract#4143]
### Current Behavior

Using product in python and latest version of openCV and pytessaract.
After a ton of other preprocessing using openCV, I end up with a cropped image with just one digit on it (as intended). I tried everything from sharpening, blurring, filtering but the gist is that any image of the number 5 (see image as attachment) is either not recognized or is recognized as a 2. But it is clearly a 5. This is what I us:
ocrStr = pytesseract.image_to_string(thr, config='--oem 3 --psm 6 digits') where thr is the image attached. I also tried with any iteration of psm 10, white listing numbers etc.

No clue why this is happening. Any insight would be very appreciated.

![hardSu-5-3=2-sharp](https://github.com/tesseract-ocr/tesseract/assets/7606167/680faaea-2e23-462a-ae84-e4c57355fb45)
 

### Operating System

macOS 11 Big Sur

**Comment by yashwantpradhan** [comment]
I want to work on this issue.

**Comment by jihchao** [comment]
I have same problem, have any updates?

**Comment by jihchao** [comment]
> ```
> tesseract I_read_documentation_instead_of_writing_issue.png - --psm 6
> 5
> ```

thanks, that's helpful, I'm missing the psm parameter.
