### ISSUE TITLE
Change the defaults of text2image to match the new standards

### ISSUE THREAD

**Issue by DesBw** [tesseract-ocr/tesseract#4147]
### Your Feature Request

Now, tesseract wants single line texts with the single line images. The defaults in text2image are set to the old standards where pages of texts  were used to train. Now, lines of texts. 

Just to note two parameters: 
- The _ysize_ needs to be around 250-300 because we have just a single line of text in the image. 
- For the _--max_pages_ parameter as well, the default needs to be 1. 

Changing the default values to the new standards would be reduce the confusion it causes for new users.

**Comment by stweil** [comment]
The training process did not change, so pages of text still work.

**Comment by Dellu** [comment]
I know it works. But, it would make more sense to default to the standard training format.
