### ISSUE TITLE
LATEX is absolutely necessary for AI (ChatGPT or BARD)

### ISSUE THREAD

**Issue by me-suzy** [tesseract-ocr/tesseract#4152]
### Your Feature Request

LATEX is absolutely necessary for reading technical and scientific books !! Tesseract must do everything Mathpix does: find, reading and transform with LATEX any formulas (mathematics, physics, chemistry, informatics, mechanics, etc)

I always use Internet Archive for download books , and after that I scann those with Mathpix or Overleaf, that are briliant to correctly identify the characters from text and, MUCH MORE IMPORTANT, know to transform any text and formulas into LATEX language. 

Internet Arhive use Tesseract, but does't have LATEX language included. Also, Tesseract can be use with Python, so it will be the most important feauture to include LATEX into scanning. Otherwise, all technical and scientific books are equal to zero. It will not be able to recognize the formulas correctly. 

Look at what a wonderful thing the applications that use LATEX do, look how well they know how to recognize formulas.

If tesseract does not introduce LATEX as quickly as possible, it will be replaced by others that already scan the text perfectly and know how to transform any formula into LATEX.

ChapGPT or BARD (and all others AI) use LATEX all the time. Otherwise, cannot solve problems that contain formulas. Right now, everyone uses LATEX app to introduce problems into AI.

**Comment by stweil** [comment]
I'm afraid that only a small minority is interested in OCR for technical books with formulas. Therefore I don't expect such changes for Tesseract. But it's Open Source – anyone can contribute new code for new features.
