### ISSUE TITLE
Version 5.3.3 is overheating my laptop

### ISSUE THREAD

**Issue by Dellu** [tesseract-ocr/tesseract#4155]
### Current Behavior

I am sorry, I don't have any reproducible issue. But, Lstmtraining in the latest version seems to consume more energy;  triggering overheating and shutting down of my pc. I never had this issue before (version 5.2). 

### tesseract -v

5.3.3

### Operating System

Ubuntu 22.04 Jammy

### Other Operating System

Ubuntu 23.04

### CPU

Intel i7-3610QM

### Other Information
I used to run the training for days & weeks; millions of iterations, with no issue. Now, I cannot run it more than 50,000 iterations. It shuts down due to thermal issues (overheating). 

**10 Power Consumers**

Usage | Events/s | Category | Description
-- | -- | -- | --
286% | 11.5 | Process | [PID 46987] lstmtraining --debug_interval 0 --traineddata data...
0.2% | 258.0 | kWork | dbs_work_handler
0.7% | 108.6 | Timer | tick_sched_timer
0.2% | 24.3 | kWork | blk_mq_run_work_fn
0.1% | 23.1 | Process | [PID 15] [rcu_preempt]
5.5% | 0.10 | Process | [PID 44751] /usr/bin/gnome-system-monitor
0.1% | 17.4 | Interrupt | [4] block(softirq)
0.0% | 12.0 | kWork | psi_avgs_work
0.0% | 9.2 | kWork | ieee80211_iface_work
1.4% | 1.5 | Process | [PID 6464] /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority ...

_No response_

**Comment by stweil** [comment]
Please run `tesseract -v` with 5.3.3. Which AVX variants does your laptop support? Depending on your CPU AVX instructions require more power than other instructions. It looks like your tesseract binary was built with multithreading support (usage is greater than 100%). Running single threaded might reduce the power consumption sufficiently to solve the overheating problem.

**Comment by Dellu** [comment]
Thank you for answering dear Stefan. THis is what I get when I run tesseract -v: 
`~$ tesseract -v
tesseract 5.3.3
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.2) : libpng 1.6.39 : libtiff 4.5.0 : zlib 1.2.13 : libwebp 1.2.4 : libopenjp2 2.5.0
 Found AVX
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.6.2 zlib/1.2.13 liblzma/5.4.0 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.2
 Found libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh/0.10.4/openssl/zlib nghttp2/1.52.0 librtmp/2.3`
