### ISSUE TITLE
Option to turn off TARGET_ERROR_RATE

### ISSUE THREAD

**Issue by DesBw** [tesseract-ocr/tesseract#4157]
Given the unreliability of the error measuring methods, I would be nice if we would be able to turn off the feature that stops the training on account of low error rate. 

_TARGET_ERROR_RATE = -1 (off)_ kind of feature. 

I want to train my model further. But, the model is hitting 0 error rate so fast; that I couldn't continue to train it. When I actually test the output model, the accuracy is nowhere close to 100%. 

As I described in the forum (https://groups.google.com/g/tesseract-ocr/c/WgDY03Qta7E), I usually get around 95% accuracy on the synthetic data, and around 91% accuracy on scanned docs.

**Comment by stweil** [comment]
I think that this is already possible. The training stops as soon as the error rate drops below `TARGET_ERROR_RATE`. So any negative value will disable such stopping.

**Comment by DesBw** [comment]
oh, really?
I didn't know that one.  I couldn't find it in the documentation. I just wrote that hypothetically. 
Thank you.
