### ISSUE TITLE
asciidoc: FAILED: combine_lang_model.1.asc: line 46: unexpected error:

### ISSUE THREAD

**Issue by 295206527** [tesseract-ocr/tesseract#4165]
### Current Behavior

[root@mysql04 tesseract-5.3.3]# make
Making all in .
make[1]: Entering directory `/home/python/downloads/tesseract-5.3.3'
  CXX      src/api/libtesseract_la-baseapi.lo
  CXX      src/api/libtesseract_la-altorenderer.lo
  CXX      src/api/libtesseract_la-capi.lo
  CXX      src/api/libtesseract_la-hocrrenderer.lo
  CXX      src/api/libtesseract_la-lstmboxrenderer.lo
  CXX      src/api/libtesseract_la-pdfrenderer.lo
  CXX      src/api/libtesseract_la-renderer.lo
  CXX      src/api/libtesseract_la-wordstrboxrenderer.lo
  CXX      src/arch/libtesseract_la-intsimdmatrix.lo
  CXX      src/arch/libtesseract_la-simddetect.lo
  CXX      src/ccmain/libtesseract_la-applybox.lo
  CXX      src/ccmain/libtesseract_la-control.lo
  CXX      src/ccmain/libtesseract_la-linerec.lo
  CXX      src/ccmain/libtesseract_la-ltrresultiterator.lo
  CXX      src/ccmain/libtesseract_la-mutableiterator.lo
  CXX      src/ccmain/libtesseract_la-output.lo
  CXX      src/ccmain/libtesseract_la-pageiterator.lo
  CXX      src/ccmain/libtesseract_la-pagesegmain.lo
  CXX      src/ccmain/libtesseract_la-pagewalk.lo
  CXX      src/ccmain/libtesseract_la-paragraphs.lo
  CXX      src/ccmain/libtesseract_la-paramsd.lo
  CXX      src/ccmain/libtesseract_la-pgedit.lo
  CXX      src/ccmain/libtesseract_la-reject.lo
  CXX      src/ccmain/libtesseract_la-resultiterator.lo
  CXX      src/ccmain/libtesseract_la-tessedit.lo
  CXX      src/ccmain/libtesseract_la-tesseractclass.lo
  CXX      src/ccmain/libtesseract_la-tessvars.lo
  CXX      src/ccmain/libtesseract_la-thresholder.lo
  CXX      src/ccmain/libtesseract_la-werdit.lo
  CXX      src/ccmain/libtesseract_la-adaptions.lo
  CXX      src/ccmain/libtesseract_la-docqual.lo
  CXX      src/ccmain/libtesseract_la-equationdetect.lo
  CXX      src/ccmain/libtesseract_la-fixspace.lo
  CXX      src/ccmain/libtesseract_la-fixxht.lo
  CXX      src/ccmain/libtesseract_la-osdetect.lo
  CXX      src/ccmain/libtesseract_la-par_control.lo
  CXX      src/ccmain/libtesseract_la-recogtraining.lo
  CXX      src/ccmain/libtesseract_la-superscript.lo
  CXX      src/ccmain/libtesseract_la-tessbox.lo
  CXX      src/ccmain/libtesseract_la-tfacepp.lo
  CXX      src/ccstruct/libtesseract_la-blamer.lo
  CXX      src/ccstruct/libtesseract_la-blobbox.lo
  CXX      src/ccstruct/libtesseract_la-blobs.lo
  CXX      src/ccstruct/libtesseract_la-blread.lo
  CXX      src/ccstruct/libtesseract_la-boxread.lo
  CXX      src/ccstruct/libtesseract_la-boxword.lo
  CXX      src/ccstruct/libtesseract_la-ccstruct.lo
  CXX      src/ccstruct/libtesseract_la-coutln.lo
  CXX      src/ccstruct/libtesseract_la-detlinefit.lo
  CXX      src/ccstruct/libtesseract_la-dppoint.lo
  CXX      src/ccstruct/libtesseract_la-image.lo
  CXX      src/ccstruct/libtesseract_la-imagedata.lo
  CXX      src/ccstruct/libtesseract_la-linlsq.lo
  CXX      src/ccstruct/libtesseract_la-matrix.lo
  CXX      src/ccstruct/libtesseract_la-mod128.lo
  CXX      src/ccstruct/libtesseract_la-normalis.lo
  CXX      src/ccstruct/libtesseract_la-ocrblock.lo
  CXX      src/ccstruct/libtesseract_la-ocrpara.lo
  CXX      src/ccstruct/libtesseract_la-ocrrow.lo
  CXX      src/ccstruct/libtesseract_la-otsuthr.lo
  CXX      src/ccstruct/libtesseract_la-pageres.lo
  CXX      src/ccstruct/libtesseract_la-pdblock.lo
  CXX      src/ccstruct/libtesseract_la-points.lo
  CXX      src/ccstruct/libtesseract_la-polyaprx.lo
  CXX      src/ccstruct/libtesseract_la-polyblk.lo
  CXX      src/ccstruct/libtesseract_la-quadlsq.lo
  CXX      src/ccstruct/libtesseract_la-quspline.lo
  CXX      src/ccstruct/libtesseract_la-ratngs.lo
  CXX      src/ccstruct/libtesseract_la-rect.lo
  CXX      src/ccstruct/libtesseract_la-rejctmap.lo
  CXX      src/ccstruct/libtesseract_la-seam.lo
  CXX      src/ccstruct/libtesseract_la-split.lo
  CXX      src/ccstruct/libtesseract_la-statistc.lo
  CXX      src/ccstruct/libtesseract_la-stepblob.lo
  CXX      src/ccstruct/libtesseract_la-werd.lo
  CXX      src/ccstruct/libtesseract_la-fontinfo.lo
  CXX      src/ccstruct/libtesseract_la-params_training_featdef.lo
  CXX      src/classify/libtesseract_la-classify.lo
  CXX      src/classify/libtesseract_la-adaptive.lo
  CXX      src/classify/libtesseract_la-adaptmatch.lo
  CXX      src/classify/libtesseract_la-blobclass.lo
  CXX      src/classify/libtesseract_la-cluster.lo
  CXX      src/classify/libtesseract_la-clusttool.lo
  CXX      src/classify/libtesseract_la-cutoffs.lo
  CXX      src/classify/libtesseract_la-featdefs.lo
  CXX      src/classify/libtesseract_la-float2int.lo
  CXX      src/classify/libtesseract_la-fpoint.lo
  CXX      src/classify/libtesseract_la-intfeaturespace.lo
  CXX      src/classify/libtesseract_la-intfx.lo
  CXX      src/classify/libtesseract_la-intmatcher.lo
  CXX      src/classify/libtesseract_la-intproto.lo
  CXX      src/classify/libtesseract_la-kdtree.lo
  CXX      src/classify/libtesseract_la-mf.lo
  CXX      src/classify/libtesseract_la-mfoutline.lo
  CXX      src/classify/libtesseract_la-mfx.lo
  CXX      src/classify/libtesseract_la-normfeat.lo
  CXX      src/classify/libtesseract_la-normmatch.lo
  CXX      src/classify/libtesseract_la-ocrfeatures.lo
  CXX      src/classify/libtesseract_la-outfeat.lo
  CXX      src/classify/libtesseract_la-picofeat.lo
  CXX      src/classify/libtesseract_la-protos.lo
  CXX      src/classify/libtesseract_la-shapeclassifier.lo
  CXX      src/classify/libtesseract_la-shapetable.lo
  CXX      src/classify/libtesseract_la-tessclassifier.lo
  CXX      src/classify/libtesseract_la-trainingsample.lo
  CXX      src/cutil/libtesseract_la-oldlist.lo
  CXX      src/dict/libtesseract_la-context.lo
  CXX      src/dict/libtesseract_la-dawg.lo
  CXX      src/dict/libtesseract_la-dawg_cache.lo
  CXX      src/dict/libtesseract_la-dict.lo
  CXX      src/dict/libtesseract_la-stopper.lo
  CXX      src/dict/libtesseract_la-trie.lo
  CXX      src/dict/libtesseract_la-hyphen.lo
  CXX      src/dict/libtesseract_la-permdawg.lo
  CXX      src/textord/libtesseract_la-alignedblob.lo
  CXX      src/textord/libtesseract_la-baselinedetect.lo
  CXX      src/textord/libtesseract_la-bbgrid.lo
  CXX      src/textord/libtesseract_la-blkocc.lo
  CXX      src/textord/libtesseract_la-blobgrid.lo
  CXX      src/textord/libtesseract_la-ccnontextdetect.lo
  CXX      src/textord/libtesseract_la-cjkpitch.lo
  CXX      src/textord/libtesseract_la-colfind.lo
  CXX      src/textord/libtesseract_la-colpartition.lo
  CXX      src/textord/libtesseract_la-colpartitionset.lo
  CXX      src/textord/libtesseract_la-colpartitiongrid.lo
  CXX      src/textord/libtesseract_la-devanagari_processing.lo
  CXX      src/textord/libtesseract_la-drawtord.lo
  CXX      src/textord/libtesseract_la-edgblob.lo
  CXX      src/textord/libtesseract_la-edgloop.lo
  CXX      src/textord/libtesseract_la-fpchop.lo
  CXX      src/textord/libtesseract_la-gap_map.lo
  CXX      src/textord/libtesseract_la-imagefind.lo
  CXX      src/textord/libtesseract_la-linefind.lo
  CXX      src/textord/libtesseract_la-makerow.lo
  CXX      src/textord/libtesseract_la-oldbasel.lo
  CXX      src/textord/libtesseract_la-pithsync.lo
  CXX      src/textord/libtesseract_la-pitsync1.lo
  CXX      src/textord/libtesseract_la-scanedg.lo
  CXX      src/textord/libtesseract_la-sortflts.lo
  CXX      src/textord/libtesseract_la-strokewidth.lo
  CXX      src/textord/libtesseract_la-tabfind.lo
  CXX      src/textord/libtesseract_la-tablefind.lo
  CXX      src/textord/libtesseract_la-tabvector.lo
  CXX      src/textord/libtesseract_la-tablerecog.lo
  CXX      src/textord/libtesseract_la-textlineprojection.lo
  CXX      src/textord/libtesseract_la-textord.lo
  CXX      src/textord/libtesseract_la-topitch.lo
  CXX      src/textord/libtesseract_la-tordmain.lo
  CXX      src/textord/libtesseract_la-tospace.lo
  CXX      src/textord/libtesseract_la-tovars.lo
  CXX      src/textord/libtesseract_la-underlin.lo
  CXX      src/textord/libtesseract_la-wordseg.lo
  CXX      src/textord/libtesseract_la-workingpartset.lo
  CXX      src/textord/libtesseract_la-equationdetectbase.lo
  CXX      src/viewer/libtesseract_la-scrollview.lo
  CXX      src/viewer/libtesseract_la-svmnode.lo
  CXX      src/viewer/libtesseract_la-svutil.lo
  CXX      src/wordrec/libtesseract_la-tface.lo
  CXX      src/wordrec/libtesseract_la-wordrec.lo
  CXX      src/wordrec/libtesseract_la-associate.lo
  CXX      src/wordrec/libtesseract_la-chop.lo
  CXX      src/wordrec/libtesseract_la-chopper.lo
  CXX      src/wordrec/libtesseract_la-drawfx.lo
  CXX      src/wordrec/libtesseract_la-findseam.lo
  CXX      src/wordrec/libtesseract_la-gradechop.lo
  CXX      src/wordrec/libtesseract_la-language_model.lo
  CXX      src/wordrec/libtesseract_la-lm_consistency.lo
  CXX      src/wordrec/libtesseract_la-lm_pain_points.lo
  CXX      src/wordrec/libtesseract_la-lm_state.lo
  CXX      src/wordrec/libtesseract_la-outlines.lo
  CXX      src/wordrec/libtesseract_la-params_model.lo
  CXX      src/wordrec/libtesseract_la-pieces.lo
  CXX      src/wordrec/libtesseract_la-plotedges.lo
  CXX      src/wordrec/libtesseract_la-render.lo
  CXX      src/wordrec/libtesseract_la-segsearch.lo
  CXX      src/wordrec/libtesseract_la-wordclass.lo
  CXX      src/ccutil/libtesseract_ccutil_la-ccutil.lo
  CXX      src/ccutil/libtesseract_ccutil_la-clst.lo
  CXX      src/ccutil/libtesseract_ccutil_la-elst2.lo
  CXX      src/ccutil/libtesseract_ccutil_la-elst.lo
  CXX      src/ccutil/libtesseract_ccutil_la-errcode.lo
  CXX      src/ccutil/libtesseract_ccutil_la-serialis.lo
  CXX      src/ccutil/libtesseract_ccutil_la-scanutils.lo
  CXX      src/ccutil/libtesseract_ccutil_la-tessdatamanager.lo
  CXX      src/ccutil/libtesseract_ccutil_la-tprintf.lo
  CXX      src/ccutil/libtesseract_ccutil_la-unichar.lo
  CXX      src/ccutil/libtesseract_ccutil_la-unicharcompress.lo
  CXX      src/ccutil/libtesseract_ccutil_la-unicharmap.lo
  CXX      src/ccutil/libtesseract_ccutil_la-unicharset.lo
  CXX      src/ccutil/libtesseract_ccutil_la-params.lo
  CXX      src/ccutil/libtesseract_ccutil_la-ambigs.lo
  CXX      src/ccutil/libtesseract_ccutil_la-bitvector.lo
  CXX      src/ccutil/libtesseract_ccutil_la-indexmapbidi.lo
  CXXLD    libtesseract_ccutil.la
  CXX      src/lstm/libtesseract_lstm_la-convolve.lo
  CXX      src/lstm/libtesseract_lstm_la-fullyconnected.lo
  CXX      src/lstm/libtesseract_lstm_la-functions.lo
  CXX      src/lstm/libtesseract_lstm_la-input.lo
  CXX      src/lstm/libtesseract_lstm_la-lstm.lo
  CXX      src/lstm/libtesseract_lstm_la-lstmrecognizer.lo
  CXX      src/lstm/libtesseract_lstm_la-maxpool.lo
  CXX      src/lstm/libtesseract_lstm_la-network.lo
  CXX      src/lstm/libtesseract_lstm_la-networkio.lo
  CXX      src/lstm/libtesseract_lstm_la-parallel.lo
  CXX      src/lstm/libtesseract_lstm_la-plumbing.lo
  CXX      src/lstm/libtesseract_lstm_la-recodebeam.lo
  CXX      src/lstm/libtesseract_lstm_la-reconfig.lo
  CXX      src/lstm/libtesseract_lstm_la-reversed.lo
  CXX      src/lstm/libtesseract_lstm_la-series.lo
  CXX      src/lstm/libtesseract_lstm_la-stridemap.lo
  CXX      src/lstm/libtesseract_lstm_la-tfnetwork.lo
  CXX      src/lstm/libtesseract_lstm_la-weightmatrix.lo
  CXXLD    libtesseract_lstm.la
  CXX      src/arch/libtesseract_native_la-dotproduct.lo
  CXXLD    libtesseract_native.la
  CXX      src/arch/libtesseract_avx_la-dotproductavx.lo
  CXXLD    libtesseract_avx.la
  CXX      src/arch/libtesseract_avx2_la-intsimdmatrixavx2.lo
  CXXLD    libtesseract_avx2.la
  CXX      src/arch/libtesseract_avx512_la-dotproductavx512.lo
  CXXLD    libtesseract_avx512.la
  CXX      src/arch/libtesseract_fma_la-dotproductfma.lo
  CXXLD    libtesseract_fma.la
  CXX      src/arch/libtesseract_sse_la-dotproductsse.lo
  CXX      src/arch/libtesseract_sse_la-intsimdmatrixsse.lo
  CXXLD    libtesseract_sse.la
  CXXLD    libtesseract.la
  CXX      src/tesseract-tesseract.o
  CXXLD    tesseract
asciidoc -b docbook -d manpage -o - doc/combine_lang_model.1.asc | \
xsltproc --nonet -o doc/combine_lang_model.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl -
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
asciidoc: FAILED: combine_lang_model.1.asc: line 46: unexpected error:
asciidoc: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/asciidoc", line 6018, in asciidoc
    document.translate(has_header) # Generate the output.
  File "/usr/bin/asciidoc", line 1666, in translate
    Section.translate()
  File "/usr/bin/asciidoc", line 2307, in translate
    Section.translate_body()
  File "/usr/bin/asciidoc", line 2315, in translate_body
    next.translate()
  File "/usr/bin/asciidoc", line 2974, in translate
    self.translate_entry()
  File "/usr/bin/asciidoc", line 2806, in translate_entry
    writer.write(entrytag[0],trace='list entry open')
  File "/usr/bin/asciidoc", line 4458, in write
    self.write_line(arg)
  File "/usr/bin/asciidoc", line 4440, in write_line
    self.f.write((line or '') + self.newline)
IOError: [Errno 32] Broken pipe
make[1]: *** [doc/combine_lang_model.1] Error 4
make[1]: Leaving directory `/home/python/downloads/tesseract-5.3.3'
make: *** [all-recursive] Error 1
[root@mysql04 tesseract-5.3.3]# rpm -qa | grep asciidoc
asciidoc-8.6.8-5.el7.noarch
[root@mysql04 tesseract-5.3.3]# 

Hello everyone, I encountered an error while compiling. Could you please ask if there are any version requirements for asciidoc
大家好 我在编译的时候报错 ，麻烦问下 asciidoc 有版本要求吗。

### Other Operating System

CentOS7

**Comment by zdenop** [comment]
I can not reproduce it on `Debian GNU/Linux 12 (bookworm)`  with `asciidoc 10.2.0`. 
[version 8.6.9 is from 2012,](https://sourceforge.net/projects/asciidoc/files/asciidoc/) so please update your system to more recent version.
