### ISSUE TITLE
Windows VC 2015 compilation failing

### ISSUE THREAD

**Issue by jdukat** [tesseract-ocr/tesseract#417]
Hi,
I'm following the instruction for Windows from: https://github.com/tesseract-ocr/tesseract/wiki/Compiling
I have cloned the master branch today, copied cppan and installed cmake 3.6.1 for Windows.
cppan runs without issues.
Then I run cmake and it goes with multiple errors. Log attached.
VC 2015 solution file is not created.
Any clues?

[CMake_outputs.zip](https://github.com/tesseract-ocr/tesseract/files/455681/CMake_outputs.zip)

**Comment by egorpugin** [comment]
Hi,
These logs are not very useful as does not content actual build logs.
Could you please try to do:
```
cppan --self-upgrade
cd your_tesseract_dir
cppan
```
and try to rebuild VS solution?

On my system I don't see any errors.

**Comment by jdukat** [comment]
Thanks for comment, I'll check with cppan upgrade later today.
I assumed the successful output of cmake should generate VS solution. I couldn't find any .sln file in the build directory. Should it be there, or somewhere else?

**Comment by egorpugin** [comment]
If you following instructions from here https://github.com/tesseract-ocr/tesseract/wiki/Compiling#master-branch-305-and-later the `tesseract.sln` is in `build` directory inside your tesseract dir.

**Comment by jdukat** [comment]
Ok, so let's clarify: yes, I follow these instructions. I clone the tesseract repo. Build directory doesn't exist and I create it as described in the instruction. Inside build dir, I run cmake, and it finishes with errors. Logs were attached. Solution (.sln) file is not created. I will double check it later today (don't have access to my dev machine now) but I'm really quite confident it hasn't been created.

**Comment by jdukat** [comment]
Double checked, the .sln file is not created in the build dir.
Note, the cmake run is full of this kind of errors:

-- Build files have been written to: C:/Users/jarek/.cppan/storage/obj/03/76/d289/build/amd64-msvc-19.0-32
CMake Error at C:/Users/jarek/.cppan/storage/obj/03/76/d289/generate.cmake:106 (include):
  include could not find load file:

    C:/Users/jarek/.cppan/storage/obj/03/76/d289/build/amd64-msvc-19.0-32/exports/pvt_cppan_demo_gif__5_1_4-fixed.cmake
Call Stack (most recent call first):
  cppan/CMakeLists.txt:45 (include)

Note the ...-fixed.cmake include error. In the folder where this file is expected to reside, there are these files:
06.09.2016  18:52             2,140 cppan-helpers-private.cmake
06.09.2016  18:52             2,322 cppan-helpers.cmake
06.09.2016  18:52             2,816 cppan.cmake
06.09.2016  18:55                 0 pvt_cppan_demo_gif__5_1_4-aliases.cmake
06.09.2016  18:52             4,707 pvt_cppan_demo_gif__5_1_4.cmake

Any clue? I have zero experience with cppan and cmake, so no idea how to attempt to resolve it.

**Comment by egorpugin** [comment]
Could you try to remove `C:/Users/jarek/.cppan/storage` completely and try again?

**Comment by jdukat** [comment]
Tried that, didn't help.

**Comment by egorpugin** [comment]
Can you provide full log of `cmake ..` command from `build` dir?

**Comment by jdukat** [comment]
I was unable to get all log into a single file.
I've once again deleted whole content of C:/Users/jarek/.cppan and removed the build directory in tesseract folder.
run cppan again, log attached and then run cmake again, with redirect to cmake.log, also attached, but some errors got printed to the console anyway (they're not present in log or in CMakeError.log file. All console dump is in the cmd.log.
[tesseract_build_log.zip](https://github.com/tesseract-ocr/tesseract/files/457627/tesseract_build_log.zip)

**Comment by egorpugin** [comment]
It seems that first error is in the zlib.
```
-- Preparing build tree for pvt.cppan.demo.zlib-1.2.8 with config amd64-msvc-19.0-32
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/jarek/.cppan/storage/obj/82/1e/e49e/build/amd64-msvc-19.0-32
-- Configuring incomplete, errors occurred!
See also "C:/Users/jarek/.cppan/storage/obj/ec/64/e827/build/amd64-msvc-19.0-32/CMakeFiles/CMakeOutput.log".

```
Could you also attach `C:/Users/jarek/.cppan/storage/obj/ec/64/e827/build/amd64-msvc-19.0-32/CMakeFiles/CMakeOutput.log` and `CMakeError.log` from there?

**Comment by jdukat** [comment]
There seem to be no error log in that folder. I've zipped it all.
[amd64-msvc-19.0-32.zip](https://github.com/tesseract-ocr/tesseract/files/457644/amd64-msvc-19.0-32.zip)

**Comment by egorpugin** [comment]
Hmmmm. I'm trying to repro the issue locally and cannot.
I removed whole storage couple of times and it works everytime.

**Comment by egorpugin** [comment]
Try `cppan --self-upgrade` once again and run without removing storage. I've slightly updated the client, maybe the issue is gone. At the moment that's all I can advise. Need to think more.

**Comment by jdukat** [comment]
No luck again :(
Well, thanks for trying. I'm now trying to use just binaries from here: 
https://github.com/charlesw/tesseract/tree/master/src/lib/TesseractOcr/x64
not trivial either as there are no .lib files and need to match .h files to these binaries, but I'm still trying :)

**Comment by egorpugin** [comment]
To use tesseract in your application in theory you could use CPPAN just in case if it will be working for you.
See https://github.com/cppan/tesseract_example
Also https://github.com/cppan/tesseract_example/tree/master/with_cppan - that's a very simple example to build small programs with cppan. It's like scripting but with C++.

**Comment by jdukat** [comment]
I think I'm quite close to make it run with binaries above, but if not lucky, I'll try the method above. Any hints on how to this sample from visual studio?

**Comment by egorpugin** [comment]
I've added these 3 lines https://github.com/cppan/tesseract_example/blob/master/with_cppan/main.cpp#L2
CPPAN will create a solution for you near the main.cpp :)

**Comment by jdukat** [comment]
Heh, as you wrote it, I've just made libtesseract load into my VS project.
Created lib from dll, completed api .h files with all the scattered dependencies and made it load, init and ... fail to recognize my bitmap :) But it works from command line with tesseract.exe, so just something wrong with params i'm passing. I'm not using leptonica. instead trying to ocr a screenshot that I have in memory in BMP format... but we're going off topic here.

Thanks much for all your help!!!
