### ISSUE TITLE
can't recognize the japanese correctly

### ISSUE THREAD

**Issue by jack-gits** [tesseract-ocr/tesseract#4170]
### Current Behavior

**_command Line:_**
` tesseract template_2.png stdout -l jpn_vert+eng --psm 3 --oem 1`

**_output:_**

```
Estimating resolution as 130
Detected 19 diacritics
Wis も

PASSPORT PN X$1234567
Soin @ SAT
SAKURA !
JAPAN. 20 FEB 1979
f KANAGAWA
20 WAR 2006
a sa

の > ご へ の > スラ > ヘ ヘ AAA ヘ AAA ヘ AA へ AA へ
XS12345673JPN7902206F 1603202<<<<<<<<<<<<<<02
```

**_Image:_**
![template_2](https://github.com/tesseract-ocr/tesseract/assets/30545972/552a71d5-baf3-40ce-ab2a-f6b47e8d802d)

### Expected Behavior

lots of words in the image are not recognized.

### tesseract -v

tesseract 5.3.3-30-gea0b
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 9e : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found SSE4.1
 Found libcurl/7.87.0 SecureTransport (LibreSSL/3.3.6) zlib/1.2.11 nghttp2/1.45.1

### Operating System

macOS 12 Monterey

### uname -a

Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Thu Jun  8 23:56:13 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_ARM64_T6000 x86_64

### CPU

M1

**Comment by zdenop** [comment]
This is the expected result: tesseract is **the OCR engine**. 
So you need to first clean the input image (remove graphics element) - see details in [documentation](https://tesseract-ocr.github.io/tessdoc/). 
In case of not simple text (unified text block) do text detection and pass individual text blocks to tesseract.
