### ISSUE TITLE
Ocr's some numbers as text strings

### ISSUE THREAD

**Issue by allhavebrainimplantsandmore** [tesseract-ocr/tesseract#4177]
### Current Behavior

I know there are settings to tweak and things you play with but it's so strange that only a tiny fraction of numbers get recognized as text strings by default. Is there any way to report and collect what tesseract's default recognition misses so it can update the engine to improve it? I'm literally seeing some patterns in what tesseract misses and maybe it can be updated and improved so it works better and more flawless out of the box?

### Suggested Fix

A way to report misses in default tesseract behavior to update its recognition engine for all to benefit. 

### tesseract -v

tesseract 5.3.2

### Other Operating System

Fedora 39

**Comment by zdenop** [comment]
Closing as the reporter does not provide anything that we can reproduce.
