### ISSUE TITLE
unicharset_extractor does not build anymore

### ISSUE THREAD

**Issue by bertsky** [tesseract-ocr/tesseract#4181]
### Current Behavior

When building from git source (tag 5.3.4), the `unicharset_extractor` binary cannot be linked anymore:

```
  CXXLD    unicharset_extractor
/usr/bin/ld: src/training/unicharset_extractor-unicharset_extractor.o: in function `tesseract::Main(int, char**)':
/usr/include/c++/8/bits/fs_path.h:184: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: /usr/include/c++/8/bits/fs_path.h:184: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: /usr/include/c++/8/bits/fs_path.h:1055: undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'
/usr/bin/ld: /usr/include/c++/8/bits/fs_path.h:177: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: /usr/include/c++/8/bits/fs_path.h:545: undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
```

My configuration was: `configure --disable-openmp --disable-shared CXXFLAGS="-g -O2 -fPIC"`, followed by `make install` and `make training-install`. I am on Debian 10 (GCC 8) x86_64.

### Expected Behavior

Expected the build to run through.

### Suggested Fix

Rumour has it this means you need to link against `stdc++fs`. But not being versed myself in autoconf, I don't know how to modify configure.ac to find out if this is actually the case.

### tesseract -v

```
tesseract 5.3.4
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.2) : libpng 1.6.36 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX512BW
 Found AVX512F
 Found AVX512VNNI
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.6 liblz4/1.8.3 libzstd/1.3.8
 Found libcurl/7.64.0 NSS/3.42.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
```

### Other Operating System

Debian 10

### uname -a

x86_64

### Compiler

GCC 8

**Comment by zdenop** [comment]
https://github.com/tesseract-ocr/tesseract?tab=readme-ov-file#installing-tesseract:

> A C++ compiler with good C++17 support is required for building Tesseract from source.

**Comment by bertsky** [comment]
ouch! ok, thanks!
