### ISSUE TITLE
Tesseract fails to OCR text with very clear hexadecimal digits

### ISSUE THREAD

**Issue by yurivict** [tesseract-ocr/tesseract#4183]
### Current Behavior

Here is the image:
![image](https://github.com/tesseract-ocr/tesseract/assets/271906/e602f6da-6f7f-4e09-b7e5-ef37babec838)

And here is what Tesseract produces as OCR:
```
74
3a

31
3c

72
2C

74
Oa
```

### Expected Behavior

n/a

### Suggested Fix

n/a

### tesseract -v

```
$ tesseract -v
tesseract 5.3.4
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 3.0.1) : libpng 1.6.40 : libtiff 4.4.0 : zlib 1.3 : libwebp 1.3.2
 Found SSE4.1
 Found OpenMP 201811
 Found libarchive 3.7.2 zlib/1.3 liblzma/5.4.4 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.5
 Found libcurl/8.5.0 OpenSSL/3.0.12 zlib/1.3 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.58.0
```

### Other Operating System

FreeBSD 14.0

### uname -a

```
$ uname -a
FreeBSD yv.noip.me 14.0-STABLE FreeBSD 14.0-STABLE #1 stable/14-n266076-2001d7f6a272: Sat Dec 30 13:33:21 PST 2023     unknown@nohost.com:/disk-samsung/obj/disk-samsung/freebsd-src/amd64.amd64/sys/GENERIC amd64
```

### Compiler

clang-16

### CPU

Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz

### Virtualization / Containers

n/a

### Other Information

n/a

**Comment by stweil** [comment]
Try to invert the image before running OCR.

**Comment by yurivict** [comment]
Regular text is OCRed fine when it is white on black, it's only hexadecimal digits that fail.

**Comment by stweil** [comment]
Please try black on white nevertheless. Does it work then?

**Comment by stweil** [comment]
The inverted text works better, but still not perfect, with `-c thresholding_method=2`.

**Comment by zdenop** [comment]
@yurivict : read documenation before posting issue!

```
tesseract i4183.png - something_that_is_alredy_covered_by_documenation
6d 20 64 6f 63 73 20 68 6f 77 20 74 6f 20 72 75
6e 20 50 79 74 68 6f 6e 20 74 65 73 74 73 2c 20
73 65 65 20 68 74 74 70 73 3a 2f 2f 67 69 74 68
75 62 2e 63 6f 6d 2f 61 70 61 63 68 65 2f 74 76
6d 2f 69 73 73 75 65 73 2f 31 32 31 35 38 0a Oa
2e 69 6e 63 6Cc 75 64 65 20 3c 62 73 64 2e 70 6f
```
