### ISSUE TITLE
Two little bugs for tesseract

### ISSUE THREAD

**Issue by ArendelleLeah** [tesseract-ocr/tesseract#4184]
### Current Behavior

1. Sometimes, It created the wrong file name, For example: I typed Output.txt, and It created Output.txt.txt
2. I've tested 218 examples, It worked almost perfectly, thanks to Tesseract, but It also has a little bug.
Here's the results
218 succeed, 98.2%.
3 Empty page!! (It's results), 1.38%
1 Wrong Number(I'll put details in file name) 0.46%
**Pay attention: Because Github doesn't let me upload .bmp, I format all the pictures from bmp to jpg...**
SucceedExample![SucceedExample](https://github.com/tesseract-ocr/tesseract/assets/104239071/c1db1a8c-275e-4f1b-8a6d-200a2260418b)
EmptyPage1 ![EmptyPage1](https://github.com/tesseract-ocr/tesseract/assets/104239071/f07b5ddb-17e8-4655-9c1c-30c131c43190)
EmptyPage2 ![EmptyPage2](https://github.com/tesseract-ocr/tesseract/assets/104239071/e93c8c9a-d587-41df-8539-200bcaa01416)
EmptyPage3 ![EmptyPage3](https://github.com/tesseract-ocr/tesseract/assets/104239071/499262b6-067a-4ea5-810d-d69cc5700ee9)
The result is=124919, But It Should Be =134919 ![124919, ButItShouldBe134919](https://github.com/tesseract-ocr/tesseract/assets/104239071/b27586de-cf8d-488d-a935-1112c928733d)
![cmd](https://github.com/tesseract-ocr/tesseract/assets/104239071/bc8aa17c-5338-410e-a2f7-70a89d3073f3)
**WrongFileName**
![WrongFileName](https://github.com/tesseract-ocr/tesseract/assets/104239071/c5143ee3-07aa-4df4-a5b9-537c033dd85d)

### Expected Behavior

I want Tesseract to create the correct file name, and It can run even perfectly. even if it's almost perfect.

### tesseract -v

C:\Program Files\Tesseract-OCR>tesseract C:\Users\Administrator\Desktop\OCRStudying\EmptyPage1.bmp C:\Users\Administrator\Desktop\OcrStudying\Output.txt
Empty page!!
Empty page!!

C:\Program Files\Tesseract-OCR>tesseract C:\Users\Administrator\Desktop\OCRStudying\EmptyPage2.bmp C:\Users\Administrator\Desktop\OcrStudying\Output.txt
Empty page!!
Empty page!!

C:\Program Files\Tesseract-OCR>tesseract C:\Users\Administrator\Desktop\OCRStudying\EmptyPage3.bmp C:\Users\Administrator\Desktop\OcrStudying\Output.txt
Empty page!!
Empty page!!

C:\Program Files\Tesseract-OCR>tesseract C:\Users\Administrator\Desktop\OCRStudying\SucceedExample.bmp C:\Users\Administrator\Desktop\OcrStudying\Output.txt

C:\Program Files\Tesseract-OCR> 

### Operating System

Windows 10

### Other Operating System

21H2(19044.1682)

### CPU

12400F

**Comment by ArendelleLeah** [comment]
**All the files are here!!!**
![124919, ButItShouldBe134919](https://github.com/tesseract-ocr/tesseract/assets/104239071/a5f3fd24-75e4-4c1b-a17d-72c961ada52f)
![cmd](https://github.com/tesseract-ocr/tesseract/assets/104239071/dce33476-a5ae-4a22-ad89-4537c1a6178d)
![EmptyPage1](https://github.com/tesseract-ocr/tesseract/assets/104239071/8ee46d83-b5eb-4622-9139-dac092639374)
![EmptyPage2](https://github.com/tesseract-ocr/tesseract/assets/104239071/c1cb15fc-81db-4ed8-9301-79904b7d8bb8)
![EmptyPage3](https://github.com/tesseract-ocr/tesseract/assets/104239071/f3a873fd-0fc0-4b52-8455-c3ab44963998)

**Comment by zdenop** [comment]
Not reading the documentation by user is not tesseract bug.
