### ISSUE TITLE
multithreaded tesseract causes Linux crash

### ISSUE THREAD

**Issue by drpixie** [tesseract-ocr/tesseract#4185]
### Current Behavior

`tesseract CauseCrash.png CauseCrash`

causes Linux to crash/reboot - impressive. This happens for several image files, a sample image file attached.

![CauseCrash](https://github.com/tesseract-ocr/tesseract/assets/1305379/b991e597-5954-4121-840f-791d75b07afc)

But
`export OMP_THREAD_LIMIT=1`
`tesseract CauseCrash.png CauseCrash`

seems to function without crashing Linux.

### Expected Behavior

Runs to completion, produces text output.

### tesseract -v

tesseract -v
tesseract 5.3.4
 leptonica-1.82.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.1.1) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.6.0 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.8
 Found libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16

### Operating System

Ubuntu 22.04 Jammy

### Other Operating System

Linux Mint, details...
[code]
System:
  Kernel: 5.15.0-92-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: MATE 1.26.0 wm: marco
    dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASUSTeK model: Z170M-PLUS v: Rev X.0x serial: <superuser required>
    UEFI-[Legacy]: American Megatrends v: 3805 date: 05/16/2018
Battery:
  Device-1: hidpp_battery_0 model: Logitech MX Vertical Advanced Ergonomic Mouse serial: <filter>
    charge: 55% (should be ignored) status: Discharging
CPU:
  Info: quad core model: Intel Core i5-7600K bits: 64 type: MCP arch: Kaby Lake rev: 9 cache:
    L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 4110 high: 4194 min/max: 800/4200 cores: 1: 4088 2: 4080 3: 4194 4: 4079
    bogomips: 30399
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel HD Graphics 630 vendor: ASUSTeK driver: i915 v: kernel ports: active: HDMI-A-2
    empty: DP-1,HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:5912
  Display: x11 server: X.Org v: 1.21.1.4 compositor: marco v: 1.26.0 driver: X:
    loaded: modesetting unloaded: fbdev,vesa gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 2560x1440 s-dpi: 96
  Monitor-1: HDMI-2 mapped: HDMI-A-2 model: Philips PHL 272B8Q res: 2560x1440 dpi: 109
    diag: 685mm (27")
  OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1
    direct render: Yes
Audio:
  Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: ASUSTeK driver: snd_hda_intel
    v: kernel bus-ID: 00:1f.3 chip-ID: 8086:a170
  Sound Server-1: ALSA v: k5.15.0-92-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I219-V vendor: ASUSTeK driver: e1000e v: kernel port: N/A
    bus-ID: 00:1f.6 chip-ID: 8086:15b8
  IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:
  Local Storage: total: 1.59 TiB used: 530.54 GiB (32.5%)
  ID-1: /dev/nvme0n1 vendor: Crucial model: CT1000P2SSD8 size: 931.51 GiB speed: 31.6 Gb/s
    lanes: 4 serial: <filter> temp: 32.9 C
  ID-2: /dev/sda vendor: Samsung model: HD753LJ size: 698.64 GiB speed: 3.0 Gb/s
    serial: <filter>
Partition:
  ID-1: / size: 915.77 GiB used: 155.04 GiB (16.9%) fs: ext4 dev: /dev/nvme0n1p3
  ID-2: /boot/efi size: 47.2 MiB used: 6 MiB (12.8%) fs: vfat dev: /dev/nvme0n1p2
Swap:
  ID-1: swap-1 type: partition size: 19.07 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/sda1
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 16 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002
  Device-1: 1-9:2 info: Kingston HyperX Alloy FPS Mechanical Gaming Keyboard
    type: Keyboard,Mouse,HID driver: hid-generic,usbhid rev: 2.0 speed: 12 Mb/s chip-ID: 0951:16b7
  Device-2: 1-10:3 info: Logitech Unifying Receiver type: Keyboard,Mouse,HID
    driver: logitech-djreceiver,usbhid rev: 2.0 speed: 12 Mb/s chip-ID: 046d:c52b
  Hub-2: 2-0:1 info: Super-speed hub ports: 10 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
Sensors:
  System Temperatures: cpu: 29.8 C mobo: 27.8 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: apt: 2780
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //mirror.aarnet.edu.au/pub/linuxmint-packages vanessa main upstream import backport
    2: deb http: //mirror.aarnet.edu.au/pub/ubuntu/archive jammy main restricted universe multiverse
    3: deb http: //mirror.aarnet.edu.au/pub/ubuntu/archive jammy-updates main restricted universe multiverse
    4: deb http: //mirror.aarnet.edu.au/pub/ubuntu/archive jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 230 Uptime: 1h 9m Memory: 15.43 GiB used: 4.14 GiB (26.8%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Unknown python3.10 client inxi: 3.3.13
[/code]
 

### uname -a

Linux slab 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### CPU

Intel Core i5-7600K bits: 64 type: MCP arch: Kaby Lake rev: 9 cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB

### Virtualization / Containers

n/a

### Other Information

Graphics: Device-1: Intel HD Graphics 630 vendor: ASUSTeK driver: i915 v: kernel ports: active: HDMI-A-2 empty: DP-1,HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:5912

**Comment by stweil** [comment]
Typically such crashes occur on hardware with an insufficient power supply. Multithreaded Tesseract will make heavy use of all available AVX2 units which require more power than other CPU instructions.

**Comment by stweil** [comment]
See also issue #2064.

**Comment by drpixie** [comment]
Hi @stweil  - thanks for the feedback. I doubt it's power, the machine is a desktop with plenty of power capacity, and runs severe loads without problem - but difficult to diagnose as machine crashes don't leave any traces. I was thinking bug in libraries for graphics processor ... ?

**Comment by stweil** [comment]
Even with plenty of power the machine might have a mainboard which does not deliver that power to the CPU.

Tesseract uses its own code for AVX2, no external library. You could use that code for a local test.
