### ISSUE TITLE
Add ICD Codes in english trained Data

### ISSUE THREAD

**Issue by MananHindustani** [tesseract-ocr/tesseract#4193]
### Your Feature Request

Hi,
As per our requirement we want International Statistical Classification of Disease [ICD] trained with eng.traineddata for the better accuracy. Also can we an extra attribute to know if text is bold or not etc,
Thanks,

**Comment by stweil** [comment]
Then why do you write an issue here?

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by MananHindustani** [comment]
Hi !
We are using tesseract 5.3.0 with eng.traindata.

We are getting lots of issues like
for example 
I10  becomes 110 
I25 become 125
