### ISSUE TITLE
Some CI jobs (GitHub Actions) are failing

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#4194]
### Current Behavior

They complain about nodejs 16. 

https://github.com/tesseract-ocr/tesseract/actions

**Comment by amitdo** [comment]
The solution: update all actions to use  `actions/checkout&*@v4`.

**Comment by stweil** [comment]
I updated all checkout actions now, but I am afraid that was not the reason for the failing CI jobs.

**Comment by amitdo** [comment]
You are right.

**Comment by amitdo** [comment]
msys2:

https://packages.msys2.org/base/mingw-w64-leptonica

>Repo(s):
    clang64, clangarm64, mingw64, ucrt64 

https://github.com/msys2/MINGW-packages/commit/d0bed5dd8f14c0

With this commit, they removed 32-bit support for leptonica.

**Comment by amitdo** [comment]
unittest-disablelegacy:

https://github.com/tesseract-ocr/tesseract/actions/runs/8129379770/job/22216419083

The reason for the failure is unclear.

**Comment by amitdo** [comment]
cmake, ubuntu 22.04 clang-14:

https://github.com/tesseract-ocr/tesseract/actions/runs/8133022714/job/22224110737

autotools, ubuntu 22.04 clang-14

https://github.com/tesseract-ocr/tesseract/actions/runs/8132678362/job/22223385796


A simple solution is tp remove clang-14 from the yml file.

Note that clang-14 on macOS and clang-15 pn Linux have no issues.

**Comment by stweil** [comment]
> The reason for the failure is unclear.

Timeout? It looks like the time for the test jumped from less than 20 minutes to more than 6 hours about 4 months ago. I have no idea why that happened.

**Comment by amitdo** [comment]
About msys2. Turns out that mingw-w64 started to remove 32-bit support for many packages a while ago.

So lets remove the mingw-w64 i686 job.

**Comment by amitdo** [comment]
For `unittest.yml` you added commands to remove (rm) stuff to make more space available. For `unittest-disablelegacy.yml` you didn't do the same thing. Could this be the reason for the issue?

**Comment by amitdo** [comment]
I fixed `cmake`, `autotools` and `msys2` action. Still trying to fix the `unittest-disablelegacy`.

**Comment by amitdo** [comment]
I fixed the `unittest-disablelegacy` action as well.
