### ISSUE TITLE
Please add the API call to translate the language code to the full language name

### ISSUE THREAD

**Issue by yurivict** [tesseract-ocr/tesseract#4201]
### Your Feature Request

Functions like ```GetAvailableLanguagesAsVector``` return language codes.
There's a [page](https://tesseract-ocr.github.io/tessdoc/Data-Files#data-files-for-version-400-november-29-2016) listing all languages with their full names, but these full names don't seem to be available through the API.

Could you please add an API call that would return the full language name for the language code?

Thank you,
Yuri

**Comment by yurivict** [comment]
Thank you for the comprehensive answer and the demo program.
I agree with you that Tesseract doesn't need that API call.

**Comment by stweil** [comment]
Regarding frk.traineddata, it looks like the ISO code should be `deu_latf`. Then the full language name `German (Fraktur Latin)` can be derived automatically.
