### ISSUE TITLE
Warning: LSTMTrainer deserialized an LSTMRecognizer! Error, data/eng/eng_num_vert.lstm is an integer (fast) model, cannot continue training

### ISSUE THREAD

**Issue by dfegjyhb** [tesseract-ocr/tesseract#4203]
### Current Behavior
Warning: LSTMTrainer deserialized an LSTMRecognizer!

Error, data/eng/eng_num_vert.lstm is an integer (fast) model, cannot continue training
Failed to continue from: data/eng/eng_num_vert.lstm
make: *** [Makefile:351: data/eng_num_vert/checkpoints/eng_num_vert_checkpoint] Error 1

### Expected Behavior

i trying Fine tune  lstm . i got error 
Error, data/eng/eng_num_vert.lstm is an integer (fast) model, cannot continue training
Failed to continue from: data/eng/eng_num_vert.lstm
make: *** [Makefile:351: data/eng_num_vert/checkpoints/eng_num_vert_checkpoint] Error 1

### Operating System

Ubuntu 20.04 Focal

### CPU

i7-11 gen

**Comment by dfegjyhb** [comment]
how to download eng checkpoint

**Comment by dfegjyhb** [comment]
Warning: LSTMTrainer deserialized an LSTMRecognizer!

**Comment by amitdo** [comment]
Did you use a model from the `tessdata_fast` reoi? Fine tuning models from that repo is not supported.

**Comment by amitdo** [comment]
Use a model from the `tessdata_best` repo for fine tuning.

**Comment by amitdo** [comment]
>yes @amitdo i'm using tessdata_fast model , still i get same error

You should use tesstada_**best**.

**Comment by dfegjyhb** [comment]
> > yes @amitdo i'm using tessdata_fast model , still i get same error
> 
> You should use tesstada_**best**.

thanks for your help..it's work.  

can you share the best hyperparameter details, i  tried 200000 ITERATIONS, I did not get the best accuracy.


i attached Screenshot of train log 
![image](https://github.com/tesseract-ocr/tesseract/assets/162717684/fda5af73-498a-4b20-95f5-143b1c6b7729)
