### ISSUE TITLE
Add the NN for a 'random' ASCII language

### ISSUE THREAD

**Issue by yurivict** [tesseract-ocr/tesseract#4210]
### Your Feature Request

A the moment Tesseract seems to be focused on OCRing texts in different languages.

However, sometimes the need arises to OCR texts with random ASCII characters.

I am suggesting to add the 'random' language with the ASCII "alphabet", and to train the network on random "texts" composed of all ASCII characters.

**Comment by amitdo** [comment]
We don't plan to do it.

You can train Tesseract yourself with the desired fonts and text.
