### ISSUE TITLE
CI: vcpkg failure due to missing xz tarball

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#4218]
### Current Behavior

https://gist.github.com/thesamesam/223949d5a074ebc3dce9ee78baad9e27

>This repository has been disabled.

GitHub disabled the repo because it was discovered it contained a nasty backdoor.

https://gist.github.com/thesamesam/223949d5a074ebc3dce9ee78baad9e27

**Comment by amitdo** [comment]
https://github.com/microsoft/vcpkg/issues/37893

https://github.com/microsoft/vcpkg/issues/37839

**Comment by stweil** [comment]
Relatedd vcpkg issue: https://github.com/microsoft/vcpkg/issues/37893.

**Comment by zdenop** [comment]
Very interesting talk about this here https://youtu.be/LaRKIwpGPTU?si=PxG0Ykat99Yv9YGJ

**Comment by amitdo** [comment]
https://tukaani.org/xz-backdoor/

**Comment by amitdo** [comment]
The issue was solved.
