### ISSUE TITLE
Can I use 3.0.5tessdata to replace 3.0.2 tessdata?

### ISSUE THREAD

**Issue by lxj0276** [tesseract-ocr/tesseract#422]
I find the 3.0.5 model is better than 3.0.2.Now my project is building by vs2010 and tesseract3.0.2.I replace the 3.0.2 tessdata by 3.0.5 tessdata ,it shows "allow_blob_division",than I use "combine_tessdata -e chi_sim.traineddata chi_sim.config" and notes the line of "allow_blob_division",finally "combine_tessdata -o chi_sim.traineddata chi_sim.config",but the tessdata is invalid.

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/410#issuecomment-244120707
