### ISSUE TITLE
Mac m1, not able to compile 

### ISSUE THREAD

**Issue by herou** [tesseract-ocr/tesseract#4221]
### Current Behavior

Java spring project: fat file, but missing compatible architecture (have (i386,x86_64,unknown), need (arm64e))

### Expected Behavior

Project should compile

### Suggested Fix

No idea

### Operating System

macOS 12 Monterey

### CPU

silicon m1

**Comment by zdenop** [comment]
This is not a proper issue report. This is a C++ project, not Java.
This project compiles without problem on Apple M1 see https://github.com/tesseract-ocr/tesseract/issues/3286

**Comment by herou** [comment]
> This is not a proper issue report. This is a C++ project, not Java. This project compiles without problem on Apple M1 see #3286

Where should I report this issue?
