### ISSUE TITLE
SW Pipeline for Ubuntu failed

### ISSUE THREAD

**Issue by adozenlines** [tesseract-ocr/tesseract#4231]

**Comment by amitdo** [comment]
@egorpugin

Please fix the sw build.

**Comment by amitdo** [comment]
The solution is obvious. We should stop using sw for PRs.

**Comment by stweil** [comment]
@egorpugin, do we need 3 different build systems for Tesseract? Or can we drop sw builds?

**Comment by amitdo** [comment]
SW is is his baby. No chance he will agree to let it go.

SW in a build system developed by one man. Nobody use it.

... except Tesseract and Leptonica.

Egor is the only one that can fix sw when the CI fails. The CI fails quite frequently and for days/weeks each time. He does not monitor it, so I have to ask him to fix it every time it fails.

**Comment by egorpugin** [comment]
Just keep it for now.
I have notifications about failures.

Failures occur when there is new version of dependencies. Like the newest python 3.13 in current case.

**Comment by stweil** [comment]
I suggest to run it less often then, not on push/pull. Would that be okay for you?
And can we reduce the scheduled runs from daily to weekly, for example?

**Comment by egorpugin** [comment]
Yes, it is ok to remove from pushes.
Let's change schedule from daily to 3 days.

**Comment by stweil** [comment]
Thanks. I updated the GitHub workflow now.

**Comment by stweil** [comment]
Pushes are either the result of an accepted pull request (which was already checked) or a direct push from a maintainer (who ideally has checked what is pushed). Any missed issues will be caught in the next daily runs. So even without an explicit push action there remain lots of checks.
