### ISSUE TITLE
text2image needs pango_training.so which in turn is not installed

### ISSUE THREAD

**Issue by leleliu008** [tesseract-ocr/tesseract#4232]
### Current Behavior

`text2image` needs `pango_training.so` which in turn is not installed

### Expected Behavior

`pango_training.so`  installed.

### Suggested Fix

https://github.com/tesseract-ocr/tesseract/blob/main/src/training/CMakeLists.txt#L405-L412

```
TARGETS text2image
```

change to:

```
TARGETS text2image pango_training
```

### Operating System

Ubuntu 22.04 Jammy

### Other Operating System

Android

### uname -a

Linux leleliu008 6.5.0-28-generic #29-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar 28 23:46:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Compiler

Android NDK r26d (clang version 17.0.2)

### CPU

aarch64

### Other Information

source: https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.3.4.tar.gz

**Comment by stweil** [comment]
Did you build Tesseract yourself (if yes: how)? And how did you install it?

**Comment by stweil** [comment]
I am curious:

Are there useful applications for training on Android?
And how did you create that nice dependency diagram?

**Comment by leleliu008** [comment]
> Are there useful applications for training on Android?

I found this when I built it for Android, I think this problem is nothing to do with specific platform.



> And how did you create that nice dependency diagram?

I create it in dot https://graphviz.org/doc/info/command.html

**Comment by zdenop** [comment]
> I found this when I built it for Android, I think this problem has nothing to do with a specific platform.

Why do you try to build training tools if you are not able/want to use them on your platform? Just to get extra issues?

> I din't give you the reproduce steps, because it is very clear if you look at the source code https://github.com/tesseract-ocr/tesseract/blob/main/src/training/CMakeLists.txt#L405-L412

I see no reason why to install `pango_training`:
```
$ ldd build/bin/text2image | grep -i pango
        libpangocairo-1.0.so.0 => /lib/arm-linux-gnueabihf/libpangocairo-1.0.so.0 (0xb6660000)
        libpango-1.0.so.0 => /lib/arm-linux-gnueabihf/libpango-1.0.so.0 (0xb65f0000)
        libpangoft2-1.0.so.0 => /lib/arm-linux-gnueabihf/libpangoft2-1.0.so.0 (0xb3980000)
```

The reason is very simple - the official build process for training tools uses static linking.

**Comment by leleliu008** [comment]
If you want to static linking, you should change `add_library(pango_training ${pango_training_src})` to `add_library(pango_training STATIC ${pango_training_src})`

**Comment by leleliu008** [comment]
It a feature not a bug, so I'm closing.
