### ISSUE TITLE
Potential Null Pointer Dereference in Function `RecodeBeamSearch::ContinueContext`

### ISSUE THREAD

**Issue by hribz** [tesseract-ocr/tesseract#4247]
### Current Behavior

In the Function `RecodeBeamSearch::ContinueContext`, If the condition on line 906 is false, then the `previous=previous->prev` statement at the end of each iteration of the `for` loop will lead to a null pointer dereference.

https://github.com/tesseract-ocr/tesseract/blob/5d5a633a5d7abfb155a605be90f8033f82e9744f/src/lstm/recodebeam.cpp#L901-L910

### Suggested Fix

If `previous` could be nullptr, an error handling branch should be added, as shown below:

```cpp
if (previous != nullptr) {
    ...
} else {
    // Add error handling code here
}
``` 

If `previous` cannot be nullptr, maybe can remove the check for `previous`, as shown below:

```cpp
while (previous->duplicate || previous->code == null_char_) {
  previous = previous->prev;
}
prefix.Set(p, previous->code);
full_code.Set(p, previous->code);
```

**Comment by stweil** [comment]
I never had a NULL pointer deference in this function and never saw a bug report which reported one. Therefore I think the checks should be removed.

Do you want to send a pull request?

**Comment by hribz** [comment]
> I never had a NULL pointer deference in this function and never saw a bug report which reported one. Therefore I think the checks should be removed.
> 
> Do you want to send a pull request?

Yeah, I have send a pull request.

**Comment by egorpugin** [comment]
From the name `previous` it can be nullptr.

**Comment by hribz** [comment]
> From the name `previous` it can be nullptr.

But if the for loop is entered and `previous` is `nullptr`, it will inevitably cause a null pointer dereference. Currently, it seems there is no path where `previous` would be `nullptr` when entering the for loop. Or do you think an error handling branch should be added?

**Comment by stweil** [comment]
> From the name `previous` it can be nullptr.

Yes, but obviously the loop always terminates before the nullptr is reached. Otherwise we'd have lots of Tesseract crashes.

**Comment by egorpugin** [comment]
From
`for (int p = length - 1; p >= 0; --p, previous = previous->prev) {`
to
`for (int p = length - 1; p >= 0 && previous ; --p, previous = previous->prev) {`

**Comment by stweil** [comment]
@egorpugin, would you prefer the nullptr check in the for statement although that case never occurred up to now?

**Comment by stweil** [comment]
I updated the PR. Please review.
