### ISSUE TITLE
id < this->size():Error:Assert failed:in file unicharset.cpp, line 278

### ISSUE THREAD

**Issue by CDanU** [tesseract-ocr/tesseract#425]
Tesseract Open Source OCR Engine v3.05.00dev with Leptonica
row xheight=132.409, but median xheight = 101.7
row xheight=126.5, but median xheight = 101.7
row xheight=126.5, but median xheight = 101.7
row xheight=119, but median xheight = 101.7
row xheight=86.6667, but median xheight = 101.7
row xheight=76.6667, but median xheight = 101.7
row xheight=246, but median xheight = 101.7
id < this->size():Error:Assert failed:in file unicharset.cpp, line 278
zsh: segmentation fault (core dumped)  **tesseract de.elab.exp0.png de.elab.exp0.box box.train**

boxfile: @https://gist.github.com/CDanU/e14b3b1c0ba3a3502fb86a55bad0a30d
img: https://cloud.githubusercontent.com/assets/15148226/18413673/1edce808-77af-11e6-9ba4-94524dcf2243.png

Maybe the image is too big ? If that is the case it would be nice to get a better message.

tesseract 3.05.00dev
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.6.25 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.5.1

**Comment by zdenop** [comment]
There are clear instruction for training and [how to generate training images](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#generate-training-images-and-box-files). Other approaches are not supported.
