### ISSUE TITLE
macOS regression due to "Fix Cygwin compatibility"

### ISSUE THREAD

**Issue by ilovezfs** [tesseract-ocr/tesseract#426]
A user reported to Homebrew in https://github.com/Homebrew/homebrew-core/issues/4764 that the tesseract build was broken if built from the HEAD of master (currently a75ab450a8cc9a2b69cf05f5c4f7a39bc44cbacc) using the options

```
brew install tesseract --HEAD --with-opencl
```

which means that we pass `--enable-opencl` to `configure`.

I bisected the build failure and found that it's a regression caused by https://github.com/tesseract-ocr/tesseract/commit/b1c921b59e6af1e68fd026cbc30540929b818552

Reverting

```
libtesseract_la_LDFLAGS += -version-info $(GENERIC_LIBRARY_VERSION) -no-undefined
```

back to

```
libtesseract_la_LDFLAGS += -version-info $(GENERIC_LIBRARY_VERSION)
```

fixed the build. A "real" fix will be more involved of course, since I'm sure you don't want to break Cygwin again.

The build error presents as

```
==> Installing tesseract
==> Using the sandbox
==> Cloning https://github.com/tesseract-ocr/tesseract.git
Cloning into '/Users/joe/Library/Caches/Homebrew/tesseract--git'...
remote: Counting objects: 794, done.
remote: Compressing objects: 100% (733/733), done.
remote: Total 794 (delta 125), reused 235 (delta 42), pack-reused 0
Receiving objects: 100% (794/794), 3.78 MiB | 1.10 MiB/s, done.
Resolving deltas: 100% (125/125), done.
Checking connectivity... done.
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/tesseract/HEAD-a75ab45_2 --enable-opencl
==> make install
Last 15 lines from /Users/joe/Library/Logs/Homebrew/tesseract/03.make:
  "_clReleaseProgram", referenced from:
      OpenclDevice::ReleaseOpenclEnv(_GPUEnv*) in libtesseract_opencl.a(openclwrapper.o)
  "_clSetKernelArg", referenced from:
      OpenclDevice::pixReadFromTiffKernel(unsigned int*, int, int, int, unsigned int*) in libtesseract_opencl.a(openclwrapper.o)
      pixDilateCL_55(int, int) in libtesseract_opencl.a(openclwrapper.o)
      pixErodeCL_55(int, int) in libtesseract_opencl.a(openclwrapper.o)
      pixDilateCL(int, int, int, int) in libtesseract_opencl.a(openclwrapper.o)
      pixErodeCL(int, int, unsigned int, unsigned int) in libtesseract_opencl.a(openclwrapper.o)
      pixORCL_work(unsigned int, unsigned int, _cl_mem*, _cl_mem*, _cl_mem*) in libtesseract_opencl.a(openclwrapper.o)
      pixANDCL_work(unsigned int, unsigned int, _cl_mem*, _cl_mem*, _cl_mem*) in libtesseract_opencl.a(openclwrapper.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libtesseract.la] Error 1
make: *** [install-recursive] Error 1
```

Complete log is here: https://gist.github.com/y-fedorov/0e5a302dd68ff9d8647f03ba4c15050a

**Comment by amitdo** [comment]
Thanks for reporting! We need to fix it.

FYI, OpenCL support is [quite buggy](https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+is%3Aopen+label%3AOpenCL)

**Comment by ilovezfs** [comment]
I wonder if you'd have any more luck with pocl.

**Comment by amitdo** [comment]
Haven't tried that. If someone want to try it...

**Comment by amitdo** [comment]
Does it also fail when OpenCL is disabled?

**Comment by ilovezfs** [comment]
OP said that's fine
```
$ brew install tesseract - is OK
$ brew install tesseract --HEAD - is OK
```

**Comment by amitdo** [comment]
@zdenop, did you lately compile Tesseract with OpenCL enabled on Linux / Windows?

**Comment by zdenop** [comment]
I tried it few minutes ago on linux. Build process looks fine, but OCR segfault...

**Comment by amitdo** [comment]
Just wanted to know that it is at least compiles on Linux. Thanks.

**Comment by amitdo** [comment]
@stweil, can you fix that?

**Comment by stweil** [comment]
Sure – just need some time. Not today. Good night.

**Comment by zdenop** [comment]
I have to revert this patch because of side effects. Other solution should be found or [implemented](https://github.com/tesseract-ocr/tesseract/issues/2009#issuecomment-431561738)...
