### ISSUE TITLE
Inconsistencies, sometimes, on similar characters. Is there a list of mistakes for characters that are very similar?

### ISSUE THREAD

**Issue by DeborahAnn032** [tesseract-ocr/tesseract#4269]
### Current Behavior

Hello, I am using Tesseract to extract some data from screenshots. 
I've noticed that sometimes there are mistakes in interpreting characters like '0' and 'O', 'P' and 'R' or '-' and '—' or the other way around. This happen with the same font.

### Expected Behavior

No expected behaviour since it's understandable that without OCR preprocessing such mistakes can occur.

### Suggested Fix

Is there a comprehensive list/map of all characters that are usually mistaken recognised that are very similar?
I need that list in order to calculate effective string distance with Levenshtein.

### tesseract -v

5.3.1

### Operating System

macOS 13 Ventura

**Comment by zdenop** [comment]
Please respect the guidelines for posting issues: use tesseract user forum for asking questions/support
