### ISSUE TITLE
PDBCMake Error: TARGET_PDB_FILE is allowed only for targets with linker created artifacts

### ISSUE THREAD

**Issue by kinghelong** [tesseract-ocr/tesseract#4279]
### Current Behavior

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:common_training>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:common_training>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:common_training>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:common_training>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:unicharset_training>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:unicharset_training>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:unicharset_training>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:unicharset_training>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

### Operating System

Windows 11

### Compiler

vs2022

### CPU

AMD 5600G

**Comment by zdenop** [comment]
no step to replicate problem

**Comment by kimvnhung** [comment]
I have same issue like this while configuring CMakeLists.txt .
I'm using Qt Creator to open CMake file and configuring the source project.
I'm using Windows 10  and MSVC 2019 compiler

**Comment by zdenop** [comment]
@kimvnhung : We do not support configuration via Qt Creator. As you can check our win cmake works without problem https://github.com/tesseract-ocr/tesseract/actions/workflows/cmake-win64.yml

**Comment by Ladyslav** [comment]
@zdenop, hi
 
 I have the same issue with TARGET_PDB_FILE.
 1) $<TARGET_PDB_FILE:unicharset_training>
     TARGET_PDB_FILE is allowed only for targets with linker created artifacts.
 2) $<TARGET_PDB_FILE:common_training>
     TARGET_PDB_FILE is allowed only for targets with linker created artifacts.					
		
VS 2022, windows 11

**Comment by zdenop** [comment]
please provide steps to replicate problem.

**Comment by Ladyslav** [comment]
@zdenop, sure 
I cloned the latest version of Tesseract (main branch) and set up the SW-master Windows client to configure a CMake build in Visual Studio 2022. After opening the 'tesseract' folder in VS2022, I initiated the CMake generation process for the 'x64-Debug' configuration. During this process, I encountered errors related to TARGET_PDB_FILE. This issue seems to be consistent when generating in this configuration. Thank you in advance!

**Comment by egorpugin** [comment]
I see.

All such conditions
```
if (MSVC)
  install(FILES $<TARGET_PDB_FILE:common_training> DESTINATION bin OPTIONAL)
endif()
```
should be updated to
```
if (MSVC AND BUILD_SHARED_LIBS)
  install(FILES $<TARGET_PDB_FILE:libtesseract> DESTINATION bin OPTIONAL)
endif()
```

**Comment by zdenop** [comment]
thanks egor.
