### ISSUE TITLE
Unable to compile tesseract on Solaris

### ISSUE THREAD

**Issue by l1gi** [tesseract-ocr/tesseract#4288]
### Current Behavior

Hello,

while trying to upgrade ghostscript-10.02.1 to ghostscript-10.03.1 on Solaris I have hit an issue with building tesseract which ghostscript bundles. I have created a [bug report](https://bugs.ghostscript.com/show_bug.cgi?id=707794).

As suggested I have tried to isolate the issue and found that I see the same behavior with standalone tesseract.
```
tesseract-5.4.1$ gmake
Making all in .
gmake[1]: Entering directory '/scratch/userland-gate/components/ghostscript/tesseract-5.4.1'
  CXX      src/tesseract-tesseract.o
In file included from /usr/local/include/leptonica/alltypes.h:37,
                 from /usr/local/include/leptonica/allheaders.h:35,
                 from src/tesseract.cpp:34:
/usr/local/include/leptonica/environ.h:70:9: error: ‘atomic_int’ does not name a type
   70 | typedef atomic_int l_atomic;
      |         ^~~~~~~~~~
In file included from /usr/local/include/leptonica/alltypes.h:62:
/usr/local/include/leptonica/regutils.h:123:5: error: ‘l_atomic’ does not name a type
  123 |     l_atomic index;     /*!< index into saved files for this test; 0-based    */
      |     ^~~~~~~~
gmake[1]: *** [Makefile:7775: src/tesseract-tesseract.o] Error 1
gmake[1]: Leaving directory '/scratch/userland-gate/components/ghostscript/tesseract-5.4.1'
gmake: *** [Makefile:8156: all-recursive] Error 1
```
Before I go to file a bug against GCC I need at least a failing test program to isolate the issue. Could you look into it and try to help me debug the issue, please? Could you create a short program to test l_atomic on Solaris, please?

configure output attached.
[configure.out.txt](https://github.com/user-attachments/files/16442366/configure.out.txt)

Thank you in advance,
Martin Rehak

### Expected Behavior

Successful tesseract build. I have been successfully building ghostscript with bundled tesseract for years without issue.

### Other Operating System

Solaris 11.4

### uname -a

SunOS ST-ul-cbe 5.11 11.4.72.176.0 i86pc i386 i86pc virtualbox

### Compiler

$ g++ --version
g++ (GCC) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### CPU

NA

### Virtualization / Containers

$ VBoxManage --version
5.1.22r115126

### Other Information

I think it is not related to the virtualisation environment.

**Comment by stweil** [comment]
This is the relevant code in `environ.h` (`/usr/local/include/leptonica/environ.h` in your case):
```
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L) && !defined(__STDC_NO_ATOMICS__)
#include <stdatomic.h>
typedef atomic_int l_atomic;
#else
typedef int l_atomic;
#endif
```

It checks whether your standard C library claims to support `atomic_int`. If yes (like in your case and on most modern systems), it declares `typedef atomic_int l_atomic;`.

So you have to find out why on your Solaris system `atomic_int` is unknown although it claims to support atomics. I suggest to search all include paths for `atomit_int`.

**Comment by amitdo** [comment]
@stweil,

IMO, the answer should be more simple: we don't support Solaris.

**Comment by stweil** [comment]
It looks like the C compiler gcc has no problems (Leptonica build works), but the C++ compiler g++ fails with the same code.

There exist two simple solutions to avoid the problem with `atomic_int` and C++:
1. Use clang++ instead of g++ for Tesseract (`configure CXX=clang++ [...]`). clang++ has problems with the chrono header, therefore this still fails.
2. Use g++, but disable atomic_int (`configure CXXFLAGS="-g -O2 -std=c++17 -D__STDC_NO_ATOMICS__=1" [...]`

Solution 2 builds a working Tesseract.

**Comment by l1gi** [comment]
Okay, taking 2. as a workaround. Thank you very much for you help. Will look for Linux/Solaris difference on atomic headers later.
