### ISSUE TITLE
ParagraphInfo always sets justification to unknown

### ISSUE THREAD

**Issue by taxophobia** [tesseract-ocr/tesseract#429]
This may be an oversight, setting justification in ccmain/pageiterator.cpp:ParagraphInfo seems to work fine. Patch attached.
[set_justification.patch.zip](https://github.com/tesseract-ocr/tesseract/files/478642/set_justification.patch.zip)

**Comment by amitdo** [comment]
You are right and the patch looks OK to me.

**Comment by zdenop** [comment]
thanks
