### ISSUE TITLE
tesseract picture export format 

### ISSUE THREAD

**Issue by bruzzler5** [tesseract-ocr/tesseract#4290]
### Your Feature Request

Hello,

I'm OCRizing extremely compressed pdfs from NARA. When I'm using any of the offered export formats for the pictures, I get file sizes of 5-10 times of the original. I didn't find an option in tesseract to export the pictures in the format of the un-OCRized pdf. Any solution or by-pass in tesseract? Maybe this is possible with the (external) hOCR-tools?

**Comment by zdenop** [comment]
Use the tesseract user forum for asking questions.

**Comment by stweil** [comment]
Related PR: #4171. See discussion there.
