### ISSUE TITLE
roadmap/changelog for upcoming releases?

### ISSUE THREAD

**Issue by clarkk** [tesseract-ocr/tesseract#430]
Is it possible to find a roadmap/changelog for upcoming releases like 3.05 so the "public" can follow the development..

Personally I would really like some optimization.. The accuracy is quite good but the speed is really bad!

**Comment by amitdo** [comment]
Hopefully, a  shiny new code that includes a LSTM based OCR engine will land in this repo very soon. It will be in alpha state initially.

[Modernization Efforts](https://github.com/tesseract-ocr/docs/blob/master/das_tutorial2016/6ModernizationEfforts.pdf)
[Building a Multilingual OCR Engine](https://github.com/tesseract-ocr/docs/blob/master/das_tutorial2016/7Building%20a%20Multi-Lingual%20OCR%20Engine.pdf)

**Comment by zdenop** [comment]
Please use tesseract user forum for asking questions

**Comment by amitdo** [comment]
Sorry, @zdenop...
:)

**Comment by clarkk** [comment]
Will 3.05 be based on LSTM?

**Comment by stweil** [comment]
A roadmap would help planning development and inform users about future features which they can expect. I could not find one for 3.05, so I assume that there is no officially published roadmap. Maybe it would be a good idea to create one on the [Tesseract wiki](https://github.com/tesseract-ocr/tesseract/wiki).

**Comment by amitdo** [comment]
In general, only Ray can share this roadmap. You can ask him to do so in the dev forum. 
https://groups.google.com/d/forum/tesseract-dev

>and inform users about future features which they can expect. I could not find one for

For the next release the major feature is the LSTM based engine, which users can read about in the DAS 2016 slides.

Regarding sharing the dates for releases, some open source projects do share a schedule, while others just declare "We'll have a new release when it's ready...".

**Comment by Shreeshrii** [comment]
LSTM release is going to be 4.0 as per zdenko since it is a major change.

I would request zdenko for a release/tag of repo before that for 3.05. A
change log for that could be created by summarizing the commit notes.

Some recent updates of interest to many users are...
Improvement for Windows versions
Availability of training tools on windows
Various bug fixes since 3.04.1
Etc

**Comment by amitdo** [comment]
+1 for tagging the tip of the repo before the completely new code as `3.04.2` or `3.05`.

**Comment by amitdo** [comment]
https://groups.google.com/forum/#!topic/tesseract-dev/mZ2IUsvWgbY

**Comment by amitdo** [comment]
Ray also updated the page that @Shreeshrii created. 
https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM#40
