### ISSUE TITLE
Tessaract does not recognize highlighted text, with "blue" background and "white" font colour

### ISSUE THREAD

**Issue by susnigdha1** [tesseract-ocr/tesseract#4316]
### Current Behavior

Tessaract does not recognize highlighted text, with "blue" background and "white" font colour

### Expected Behavior

Tessaract should recognize highlighted text, with "blue" background and "white" font colour

### tesseract -v

tess4j:5.10.0

### Operating System

Windows 10

**Comment by zdenop** [comment]
Please respect the guidelines for posting issues!
Provide all necessary information + images for reproducing the problem. Make sure you read the documentation first.
