### ISSUE TITLE
Configure failure

### ISSUE THREAD

**Issue by ashinpan** [tesseract-ocr/tesseract#4323]
### Current Behavior

cmake-gui . .
configure 
(fails with the following message)
Found leptonica version: 1.84.1
CMake Error at /home/pan/Develop/tesseract/build/CMakeFiles/CMakeScratch/TryCompile-5Ng17c/cmTC_208fdTargets.cmake:21 (set_target_properties):
  The link interface of target "leptonica" contains:

    WebP::webp

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /home/pan/Develop/tesseract/build/CMakeFiles/CMakeScratch/TryCompile-5Ng17c/CMakeLists.txt:16 (include)

CMake Error at cmake/CheckFunctions.cmake:34 (try_run):
  Failed to generate test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:409 (check_leptonica_tiff_support)

Configuring incomplete, errors occurred!

### Operating System

Ubuntu 24.04 Noble

### Other Operating System

Linux mint 22

**Comment by zdenop** [comment]
Use cmake, provide real log so we can replicate problem.

**Comment by stweil** [comment]
None of these files is part of the Tesseract source code. Please try an autoconf or a cmake build from the command line

**Comment by ashinpan** [comment]
@stweil What follows is the log of a cmake build from the command line:

pan@pan-desktop:~/Develop/tesseract/build$ cmake ..
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring tesseract version 5.4.1-35-g61ed...
-- Setting build type to 'Release' as none was specified.
-- IPO / LTO supported
-- CMAKE_SYSTEM_PROCESSOR=<x86_64>
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Success
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Success
-- Performing Test HAVE_AVX512F
-- Performing Test HAVE_AVX512F - Success
-- Performing Test HAVE_FMA
-- Performing Test HAVE_FMA - Success
-- Performing Test HAVE_SSE4_1
-- Performing Test HAVE_SSE4_1 - Success
-- Performing Test OPENMP_SIMD
-- Performing Test OPENMP_SIMD - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1")
-- Found leptonica version: 1.84.1
CMake Error at /home/pan/Develop/tesseract/build/CMakeFiles/CMakeScratch/TryCompile-eRuUcm/cmTC_8b962Targets.cmake:21 (set_target_properties):
  The link interface of target "leptonica" contains:

    WebP::webp

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /home/pan/Develop/tesseract/build/CMakeFiles/CMakeScratch/TryCompile-eRuUcm/CMakeLists.txt:16 (include)


CMake Error at cmake/CheckFunctions.cmake:34 (try_run):
  Failed to generate test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:409 (check_leptonica_tiff_support)


-- Configuring incomplete, errors occurred!

**Comment by zdenop** [comment]
It seems like the error is coming from the leptonica. How did you install leptonica?

**Comment by ashinpan** [comment]
I have been using the manually built master version of leptonica for many builds of tesseract. Now, the master version of leptonica and that of tesseract seem no longer compatible. Therefore, I remove the manual build of leptonica and try to use distro-provided leptonica (1.82). Now the build is successful. So, @zdenop you are right, thanks a lot.

**Comment by zdenop** [comment]
Just note - master Leptonica and Tesseract are perfectly compatible. 
E.g. for the Windows we run the latest code tests daily: https://github.com/tesseract-ocr/tesseract/actions/runs/11309394926/job/31453201755

**Comment by ashinpan** [comment]
@zdenop Then, I don't know. Perhaps this is a Tesseract bug?
