### ISSUE TITLE
CI: some autotools jobs fail

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#4328]
### Other Information

>Run export "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig"
  export "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig"
  cd test
  clang++-15 -o basicapitest testing/basicapitest.cpp -I/usr/local/include -L/usr/local/lib `pkg-config --cflags --libs tesseract lept ` -pthread -std=c++17
  ./basicapitest
  shell: /usr/bin/bash -e {0}
Package -llept was not found in the pkg-config search path.
Perhaps you should add the directory containing `-llept.pc'
to the PKG_CONFIG_PATH environment variable
Package '-llept', required by 'tesseract', not found
testing/basicapitest.cpp:1:[10](https://github.com/tesseract-ocr/tesseract/actions/runs/11447717603/job/31849673550#step:14:11): fatal error: 'allheaders.h' file not found
#include <allheaders.h>
         ^~~~~~~~~~~~~~
1 error generated.
Error: Process completed with exit code 1.

**Comment by stweil** [comment]
See commit b4a4f5c6cbe1f13dd247ee641393bf223ddc36fe.
