### ISSUE TITLE
Wrong version number when compiling DLL from source

### ISSUE THREAD

**Issue by Sicos1977** [tesseract-ocr/tesseract#4329]
### Current Behavior

![image](https://github.com/user-attachments/assets/99b09cd0-094f-4e0d-a002-5dc0e7d94269)

### Expected Behavior

I expect it to give 5.4.1 as the version number ... Yes I know that I show this from a C# project but I just return the version number from the DLL that I compiled from here --> https://github.com/tesseract-ocr/tesseract/releases/tag/5.4.1

### Suggested Fix

Fix version number

### Operating System

Windows 11

**Comment by stweil** [comment]
This looks like you used a 5.3.2 library. Make sure that there are no old Tesseract libraries and source codes on your build host.

**Comment by Sicos1977** [comment]
I also thought that that happened so I removed all tesseract versions and recompiled everything from scratch but still am getting this error. I will do some futher investigation if visual studio is caching something somewhere without me knowing it.

**Comment by Sicos1977** [comment]
![image](https://github.com/user-attachments/assets/54eb3700-6051-4efb-9d96-1dd2a2ac9626)
