### ISSUE TITLE
Feature Request: Use strings instead of numbers for oem and psm

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#4332]
### Your Feature Request

Use strings instead of numbers for `oem` and `psm` in the command line.

**Comment by stweil** [comment]
Which strings would you suggest? The macro names from include/tesseract/publictypes.h, maybe without the "OEM_" and "PSM_" prefixes? Upper or lower case?

**Comment by amitdo** [comment]
Stefan, this was suggested by you 6 years ago here:

https://github.com/tesseract-ocr/tesseract/issues/1604#issuecomment-399785152

>I‌ wonder whether we should drop the numeric values and replace them by symbolic strings (e. g. `--oem lstm+legacy`).

I added the also `psm`:

> Same idea for psm.
> 
> `--psm <mode>` modes: osd, auto, auto-osd, column, block, word. char...

**Comment by amitdo** [comment]
>@Shreeshrii commented on Jun 25, 2018
>
>Symbolic strings is a good idea. However for compatibility, I would suggest also supporting the existing numeric values, both for oem and psm.

**Comment by amitdo** [comment]
Stefan, you used a 'confused' emoji as reaction to one of my comments. What confused you?

**Comment by stweil** [comment]
Sorry, it was the wrong choice. I was surprised that you remembered things which I had written 6 years ago. Perhaps I was also a little bit confused why this feature was never implemented up to now. I think I'll not wait longer, but implement it (if nobody else wants to do it).

**Comment by stweil** [comment]
It's now implemented in Git master. Does this require a new minor release, or is a bugfix release sufficient?

**Comment by amitdo** [comment]
I don't know. Choose what you think is the right one.
