### ISSUE TITLE
[RFC] The legacy engine - should we keep it or drop it?

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#4342]
We talked about this topic years ago.

@stweil, do you still think we should keep it?

**Comment by stweil** [comment]
We just added a legacy model to tessdata_contrib ...

And yes, there is still no alternative to get character attributes.

**Comment by amitdo** [comment]
Regardibg font attributes, they are not so reliable.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/433
