### ISSUE TITLE
tesseract-ocr no longer installable on Ubuntu:22.04 due to missing libleptonica6 dependency

### ISSUE THREAD

**Issue by mirekphd** [tesseract-ocr/tesseract#4343]
### Current Behavior

I'm trying to install Tesseract OCR (`tesseract-ocr`) on Ubuntu (from one of PPA archives: `ppa:alex-p/tesseract-ocr-devel` or `ppa:alex-p/tesseract-ocr-daily`). However, the installation fails due to `libleptonica6` no longer being installable:
```
 #32 8.592 The following packages have unmet dependencies:
 #32 8.648  libtesseract5 : Depends: libleptonica6 (>= 1.75.3) but it is not installable
 #32 8.649  tesseract-ocr : Depends: libleptonica6 (>= 1.75.3) but it is not installable
```

### Expected Behavior

Latest `tesseract-ocr` should be installable on Ubuntu 22.04.

### tesseract -v

latest

### Other Operating System

Ubuntu 22.04

### Virtualization / Containers

To reproduce in Docker:
```
$ docker run --rm -it --name test -u 0 ubuntu:22.04 bash -c "apt update && apt install -y software-properties-common && add-apt-repository -y ppa:alex-p/tesseract-ocr-devel && apt update && apt install -y tesseract-ocr"
# note you can swap the PPA archive to `ppa:alex-p/tesseract-ocr-daily` or `ppa:alex-p/tesseract-ocr5.3` with the same result 
```

### Other Information

This started to happen on Oct 30 and subsequent days, while on Oct 29 and earlier it used to install correctly.

**Comment by mirekphd** [comment]
A workaround is to switch to one of stable PPAs, e.g. `ppa:alex-p/tesseract-ocr5`:

```
$ docker run --rm -it --name test -u 0 ubuntu:22.04 bash -c "apt update && apt install -y software-properties-common && add-apt-repository -y ppa:alex-p/tesseract-ocr5 && apt update && apt install -y tesseract-ocr && tesseract --version"
[..]
Setting up liblept5:amd64 (1.82.0-3build1) ...
Setting up libtesseract5:amd64 (5.4.1-1ppa1~jammy1) ...
[..]
tesseract 5.4.1
 leptonica-1.82.0
```

**Comment by stweil** [comment]
Did you report this to the Ubuntu maintainers?

**Comment by amitdo** [comment]
CC: @Alexanderp

**Comment by AlexanderP** [comment]
Added a new version:
tesseract-lept5 - 5.4.1+git6449-61ed4d9f-2ppa1~jammy1 
That should solve the problem

**Comment by mirekphd** [comment]
Many thanks @AlexanderP for your quick reaction. Indeed `tesseract-ocr` is installable again from the [tesseract-ocr-devel](https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr-devel) and [tesseract-ocr-daily](https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr-daily) PPAs.
