### ISSUE TITLE
leptonica library with pdf support (>= 1.71) is missing

### ISSUE THREAD

**Issue by canny07** [tesseract-ocr/tesseract#435]
![leptonica](https://cloud.githubusercontent.com/assets/17674215/18988851/44796cb8-8726-11e6-8854-9ff87c11ad96.png)
I followed the steps of installation of `tesseract-ocr`. After `autogen.sh` , I tried `./configure` but terminal is showing `leptonica library with pdf support (>= 1.71) is missing` and no further installation is happening.
I searched for this problem extensively. I installed `leptonica-17.3` from source. Then I tried `./configure` again. The problem persisted. I again searched. In one closed issue, there was suggestion for `./configure --with-extra-includes=/usr/local/include --with-extra-libaries=/usr/local/lib
` instead of `./configure`. I didn't work.
The problem is still the same. 
What to do? 
Any suggestion is welcome.

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support.

**Comment by Neppord** [comment]
I have the same bug. Since it is telling you that you have the wrong version, but that is not the real issue.

 this is bug and not a "asking support".

**Comment by Neppord** [comment]
@canny07 i made it work by setting the library path diffierntly. It is probably a old version of leptonica that is "blocking the sight"  for the config script .

**Comment by canny07** [comment]
@Neppord Yeah It seems so. For my case, I found that the older version was the reason of trouble. So, I removed it and downloaded and installed the latest version from the source. 
Thanks for answering :)

**Comment by amitdo** [comment]
First, it is recommended to uninstall an older Leptonica before install new one.

Running `sudo ldconfig` after `sudo make install` in both Leptonica and Tesseract installation should prevent the issue you had.

Anyway, it's not a bug in Tesseract.

**Comment by stweil** [comment]
> Anyway, it's not a bug in Tesseract.

In some way it is. I had to fix my Tesseract configuration to get PDF support for the Windows version. Maybe I should have sent a PR earlier – I'll do it now.

**Comment by stweil** [comment]
Please test and review pull request #473 which should fix this issue.

**Comment by amitdo** [comment]
The cause of their issue is not related to libpng.
