### ISSUE TITLE
CLI: Unexpected handling of parameters using -c VAR=VALUE

### ISSUE THREAD

**Issue by sdubinsky** [tesseract-ocr/tesseract#4354]
_Note by @amitdo. The original title was:` Inconsistency Between --oem and -c "tessedit_ocr_engine_mode"`_

### Current Behavior

As far as I can tell, these two options should be identical, however the attached image produces different output.  With  --oem it says 11, with the config var it says 1.  I should add that with any --oem value other than 0, it returns '1' not '11'.

Full command: 

```
tesseract -l eng --oem 0 --psm 7  -c "tessedit_char_whitelist=0123456789"  ramdisk/test_0.png  -
tesseract -l eng --psm 7  -c "tessedit_char_whitelist=0123456789" -c "tessedit_ocr_engine_mode=0" ramdisk/test_0.png  -
```

![test_0](https://github.com/user-attachments/assets/a1766c20-42a0-4fa4-8885-be63b8e2b37d)

### Expected Behavior

Both commands should return the same result, ideally 11.

### Suggested Fix

They should either return the same information or the docs should be updated to clarify the difference.

### tesseract -v

tesseract 5.4.1
 leptonica-1.84.1
  libgif 5.2.2 : libjpeg 6b (libjpeg-turbo 3.0.2) : libpng 1.6.40 : libtiff 4.6.0 : zlib 1.3.1.zlib-ng : libwebp 1.4.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libcurl/8.9.1 OpenSSL/3.2.2 zlib/1.3.1.zlib-ng libidn2/2.3.7 nghttp2/1.62.1

### Other Operating System

Fedora 42.

### uname -a

Linux deux-ex 6.11.7-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov  8 19:23:10 UTC 2024 x86_64 GNU/Linux

### CPU

Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12)

### Virtualization / Containers

None.

**Comment by zdenop** [comment]
Why do you think the OEM default value is 0?

https://github.com/tesseract-ocr/tesseract/blob/43b8d743fce4e83cbbe6198b6a917ab5c672a82b/include/tesseract/publictypes.h#L263-L277

https://github.com/tesseract-ocr/tesseract/blob/43b8d743fce4e83cbbe6198b6a917ab5c672a82b/src/tesseract.cpp#L688-L692

https://github.com/tesseract-ocr/tesseract/blob/43b8d743fce4e83cbbe6198b6a917ab5c672a82b/src/ccmain/tessedit.cpp#L100-L109

**Comment by zdenop** [comment]
Did you read the info above? The problem is not in Tesseract but in your assumption (default = 0).

**Comment by sdubinsky** [comment]
I'm not assuming the default is 0, I'm setting it explicitly in both cases.

**Comment by sdubinsky** [comment]
Once via --oem, once via -c "ocr_engine_mode"

**Comment by zdenop** [comment]
Which tessdata you use?

**Comment by sdubinsky** [comment]
eng.traineddata

**Comment by sdubinsky** [comment]
I'm not sure how to find the version

**Comment by zdenop** [comment]
Check filesize of eng.traineddata and compare it with https://github.com/tesseract-ocr/tessdata, https://github.com/tesseract-ocr/tessdata_best, https://github.com/tesseract-ocr/tessdata_fast

+ make sure you use the latest tessract (5.5.0)

**Comment by sdubinsky** [comment]
I am using the first version linked.

**Comment by zdenop** [comment]
OK. I think I know ( ;-) ) the reason:
`tessedit_ocr_engine_mode` is INIT variable
https://github.com/tesseract-ocr/tesseract/blob/43b8d743fce4e83cbbe6198b6a917ab5c672a82b/src/ccmain/tesseractclass.cpp#L119-L123

 e.g. it must be set during initialisation of API/language model (see `enginemode` variable in `init` ):

https://github.com/tesseract-ocr/tesseract/blob/43b8d743fce4e83cbbe6198b6a917ab5c672a82b/src/tesseract.cpp#L736-L741

But variables speficied via "-c" argument are setup by function `SetVariablesFromCLArgs` after init phase. E.g. `-c "tessedit_ocr_engine_mode=0"` has no effect and OEM_DEFAULT is used....

**Comment by sdubinsky** [comment]
Thanks!

**Comment by zdenop** [comment]
@amitdo : why do you claim it is a bug? Can you elaborate on this?

**Comment by amitdo** [comment]
@zdenop,
Is your question is about the referenced commit or in general?

**Comment by zdenop** [comment]
@amitdo : My question is about your claims (bug, wrong handling of parameters).

**Comment by amitdo** [comment]
You already analyzed what;s wrong in the code which makes any init parameter set with -c a no-op.

I don't see how this can't be classified as a bug.

**Comment by stweil** [comment]
Not any. It depends on the parameter. Many parameters are used after init, and these parameters work fine. Examples: debug output, thresholding, ...

**Comment by amitdo** [comment]
Yes, I know, but 'wrong handling of parameters' is still true. because the code wrongly defer the task of parsing the -c VAR=VALUE (and pushing them to vectors to be used by init()).

**Comment by stweil** [comment]
So ideally Tesseract should
- Set all parameters to default values.
- Optionally read parameter values from a global configuration file (missing implementation).
- Optionally read parameter values from a user's configuration file (missing implementation).
- Apply parameters which are given with `-c` on the command line.
- Set parameters which are implicitly given with command line arguments like `--psm` or `--dpi`.
- Run init.

**Comment by amitdo** [comment]
Using:

`tesseract in.tif out pdf`

Works fine when the config file is in the right path.

**Comment by amitdo** [comment]
I mean, the confie files are already given to init() in current code.

**Comment by amitdo** [comment]
* Set all parameters to default values.

For the parameters that are set with -c this is already done by tesseract (with C macros).

**Comment by amitdo** [comment]
Zdenko,

About your patch - LGTM.

About that comment. I think you added it. You just didn't take into account the INIT parameters.

>Maybe some parameter should be set after init??? 

I don't think there is a good reason to do this.

**Comment by amitdo** [comment]
BTW, the number of INIT parameters is very small.
