### ISSUE TITLE
Training issue : APPLY_BOXES failure : Couldn't find a matching blob

### ISSUE THREAD

**Issue by adimux-payday** [tesseract-ocr/tesseract#436]
I had many APPLY_BOXES errors when trying to feed back Tesseract a corrected box file (that I corrected using jTessBoxEditor / Qt Box Editor softwares) using this command :

`
`tesseract fra.factures.IMG_2192.jpg  fra.factures.IMG_2192.box nobatch box.train.stderr
`

The errors were **concerning** the **newly added boxes** only :

```
APPLY_BOXES: boxfile line 256/C ((588,625),(616,679)): FAILURE! Couldn't find a matching blob
FAIL!
APPLY_BOXES: boxfile line 257/A ((620,626),(645,679)): FAILURE! Couldn't find a matching blob

etc.
```

for all the 20 ~ characters I drew the boxes for.
The characters that I added were those ones : "CARBURANT INCLUS TVQ C 9.975% 2,28$". You will recognize them in the image I have uploaded next to this issue.

It's well known that this error is **triggered** when **there are overlapping boxes**, which is **not the case in my box file** (attached to this issue by the way if you want to look).

To see the boxes, you can use one of those two softwares for example :

jTessBoxEditor : https://github.com/nguyenq/jTessBoxEditor
QtBoxEditor : https://zdenop.github.io/qt-box-editor/

Box file (rename it to .box file instead of .box.txt if you want to try) :
[fra.factures.IMG_2192.box.txt](https://github.com/tesseract-ocr/tesseract/files/503354/fra.factures.IMG_2192.box.txt)
Image :
![fra factures img_2192](https://cloud.githubusercontent.com/assets/21318949/18998248/e41d9242-8705-11e6-8686-8e6136421574.jpg)

**Comment by Brabahou** [comment]
Hi
I have the same issue. Did you find the source of error ?

**Comment by Shreeshrii** [comment]
@zdenop  Please close - duplicate https://github.com/tesseract-ocr/tesseract/issues/1166

**Comment by Deallinker** [comment]
I have the same issue,too....
