### ISSUE TITLE
Text Extraction is failed

### ISSUE THREAD

**Issue by jahangir21121** [tesseract-ocr/tesseract#4371]
### Current Behavior

in android platform kotlin

When hindi text image is provide to tha.traineddata (Thai File) it returning text in thai basically it is converting hindi to thai script.

### Expected Behavior

When i provide hindi image then it should not convert text to thai as thai text is not in the image.
![Hindi](https://github.com/user-attachments/assets/a9ebe828-413d-4ff6-900d-193f424871c1)

### Suggested Fix

I dont know

**Comment by zdenop** [comment]
You specifically instructed Tesseract to extract Thai words from the image, yet you complain that Tesseract did just that?

**Comment by jahangir21121** [comment]
I am intrested to  get the thai result but thai.traineddata file with hindi image return me the thai text but i dont have any thai text in hindi image

**Comment by zdenop** [comment]
Tesseract is OCR engine (not language detector). It never worked as you wish. Even when you provide image without text, tesseract will try to interpret some graphics element as text.

**Comment by jahangir21121** [comment]
I have one question if provide image with out text then it should return empty string. why it interpet the wrong text??

**Comment by amitdo** [comment]
You can change the oage segmentation mode to 0. This will outout the result of Orientation and Script Detection. You can then use this information and manually choose the right model to ocr the image.

**Comment by amitdo** [comment]
As @zdenop said, when you explicitly request Tesseract to OCR an image using a specific model (-l lang), Tesseract will try do exactly what you told ir, recognize text using that model.

**Comment by amitdo** [comment]
See the feature request in #4374.

Meanwhile, you cab do it manually, as I pointed out in https://github.com/tesseract-ocr/tesseract/issues/4371#issuecomment-2558532802
