### ISSUE TITLE
Arabic text missing

### ISSUE THREAD

**Issue by Carmina16** [tesseract-ocr/tesseract#4375]
### Current Behavior

There are whole lines missing from a high-quality image.

### tesseract -v

tesseract v5.5.0.20241111
 leptonica-1.85.0
  libgif 5.2.2 : libjpeg 8d (libjpeg-turbo 3.0.4) : libpng 1.6.44 : libtiff 4.7.0 : zlib 1.3.1 : libwebp 1.4.0 : libopenjp2 2.5.2
 Found SSE4.1
 Found libarchive 3.7.7 zlib/1.3.1 liblzma/5.6.3 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6
 Found libcurl/8.11.0 Schannel zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0

### Operating System

Windows 10

### Other Information

The `tessdata_best/ara` model was used.

**Comment by Carmina16** [comment]
[arabic.zip](https://github.com/user-attachments/files/18228028/arabic.zip)

**Comment by amitdo** [comment]
This is a known issue. See #657.
