### ISSUE TITLE
OCR does not work on 99% similar input samples

### ISSUE THREAD

**Issue by H-K-47** [tesseract-ocr/tesseract#4377]
### Current Behavior

I have 3 images, they have basically the same layout with the same information given on similar places.

![Kush-Card-13](https://github.com/user-attachments/assets/e5f7d349-5442-4b77-b77c-c7c482a0f916)
# Good Output, but (c) character not recognized
tesseract.exe Kush-Card-13.jpg - -l eng

```
Estimating resolution as 360
;—————— ~Ve-

= ——
yy Engulfing Aura

Ix
**eC

ESE: Ze
”APCOM CO,, LTD. SS Z

MHW:KD 105/108

BRS
```

![Kush-Card-12](https://github.com/user-attachments/assets/fcca1fa8-27f3-45b0-b0d1-7f7d5751f0c8)
# Nothing
tesseract.exe Kush-Card-12.jpg - -l eng

![Kush-Card-11](https://github.com/user-attachments/assets/aac9718a-3bdf-42f7-adf6-db1ed107322c)
# (C) symbol mapped to @ but completely missing the 2 big words at the center
tesseract.exe Kush-Card-11.jpg - -l eng

```
Estimating resolution as 458
Detected 19 diacritics
| a
t a l
)

 @CAPCOM CO.,LTD. SE MHW:KD 103/108 ~~
```

### Expected Behavior

Similar output and recognition of text

### tesseract -v

tesseract v5.5.0.20241111
 leptonica-1.85.0
  libgif 5.2.2 : libjpeg 8d (libjpeg-turbo 3.0.4) : libpng 1.6.44 : libtiff 4.7.0 : zlib 1.3.1 : libwebp 1.4.0 : libopenjp2 2.5.2
 Found AVX512BW
 Found AVX512F
 Found AVX512VNNI
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.7.7 zlib/1.3.1 liblzma/5.6.3 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6
 Found libcurl/8.11.0 Schannel zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0

### Operating System

Windows 10

**Comment by stweil** [comment]
This is a case for the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr), not for Tesseract issues (see https://github.com/tesseract-ocr/tesseract/blob/main/CONTRIBUTING.md).
