### ISSUE TITLE
Problem with cross copiled static library

### ISSUE THREAD

**Issue by josepaul28** [tesseract-ocr/tesseract#44]
Hi, every one

I cross compile the static library of tesseract and iam getting this error when build:

![captura de pantalla de 2015-07-10 09 42 35](https://cloud.githubusercontent.com/assets/4372141/8620905/40bf6540-26e8-11e5-8e62-705e0081e02c.png)

anyone know what is the problem?

Thanks in advance, regards.

**Comment by zdenop** [comment]
For general questions and support please use tesseract-ocr user forum. See FAQ[1]

[1] https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advises

**Comment by jimregan** [comment]
From the looks of it, you haven't set the include path for leptonica's headers, but it's hard to tell from the screenshot. In general, console logs are much more useful than screenshots, so when you write to the forum, please try to include a log.
