### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Molochnik** [tesseract-ocr/tesseract#441]
Hello,
I have just downloaded the latest version and found that there are a lot of leaks after a singe page conversion. They can be easily located using visual leak detector:
1) genericvector.h, line 626 ,   T* new_array = new T[size];
2) params.cpp, line 35,   new tesseract::ParamsVectors();
3) strngs.cpp,  line 32,    STRING_HEADER* new_header = (STRING_HEADER*)(alloc_string(alloc))
4) dawg_cache.cpp, line 100,    new SquishedDawg(fp, dawg_type, lang_, perm_type, dawg_debug_level_);
5)  strngs.cpp,  line 107,    memcpy(AllocData(1, kMinCapacity), "", 1);//when called from dawg()
6) dict.cpp, line 190,   static DawgCache *cache = new DawgCache();  // evil global singleton
7) dawg.cpp, line 342, edges_ = (EDGE_ARRAY) memalloc(sizeof(EDGE_RECORD) * num_edges_);

All of these leaks have root in "int TessBaseAPI::Init" so the single usage of this method cannot do big harm though it doesn't look good. Could anyone correct that?

**Comment by amitdo** [comment]
For (1) see:
http://stackoverflow.com/questions/10447683/c-new-tsize-doesnt-work
http://stackoverflow.com/questions/1751378/validity-of-int-array-new-int-size

**Comment by amitdo** [comment]
related issue: #264

**Comment by amitdo** [comment]
Did you run vld against the Tesseract command line program or your own program that uses the API?

**Comment by Shreeshrii** [comment]
Another old issue re memory leak

https://github.com/gnewtothis101/tesseract-ocr/issues/1390

**Comment by Molochnik** [comment]
I used my own code, but the problem remains even I leave only one function:
```
		tesseract::TessBaseAPI  api;
		if (api.Init(lngpath.c_str(), lng.c_str())) return false;

```

**Comment by Molochnik** [comment]
Totally VLD detects 27 leaks (some of them are the same) and all are in Init method.

**Comment by Molochnik** [comment]
When I use old .traineddata files (downloaded somewhere 3 years ago) VLD detects 27 leaks, when I changed them to files downloaded from https://github.com/tesseract-ocr/tessdata, VLD detects 30 leaks  no matter which language I am using.

**Comment by amitdo** [comment]
Use api->End() for cleanup.

**Comment by Molochnik** [comment]
I tried that before with no effect.

**Comment by amitdo** [comment]
Do you get all these leak reports with the Tesseract command line program?

**Comment by Molochnik** [comment]
Yes I, I run it with only one option --tessdata-dir "C:\program files\Test\"
and get 15 leaks in the same places

**Comment by amitdo** [comment]
@stweil,
maybe you want to explore this... :)

**Comment by stweil** [comment]
I already watched this discussion thread and will have a closer look as soon as my time permits that – not this weekend. :-)

**Comment by Shreeshrii** [comment]
PR related to memory leaks

https://github.com/tesseract-ocr/tesseract/pull/38

**Comment by stweil** [comment]
@amitdo, I can confirm 15 memory leak blocks as reported by @Molochnik. I used this command to detect the leaks on Linux with latest Tesseract built in subdirectory `bin/debug/x86_64-linux-gnu`:

    LD_LIBRARY_PATH=bin/debug/x86_64-linux-gnu/api/.libs valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all bin/debug/x86_64-linux-gnu/api/.libs/tesseract --tessdata-dir /usr/local/share/tessdata

A simple fix reduces the number from 3024 bytes in 15 blocks to 272 bytes in 10 blocks:

    diff --git a/ccutil/params.cpp b/ccutil/params.cpp
    index ce2b430..9b604fb 100644
    --- a/ccutil/params.cpp
    +++ b/ccutil/params.cpp
    @@ -31,9 +31,9 @@
     #define EQUAL         '='
     
     tesseract::ParamsVectors *GlobalParams() {
    -  static tesseract::ParamsVectors *global_params =
    -    new tesseract::ParamsVectors();
    -  return global_params;
    +  static tesseract::ParamsVectors global_params =
    +    tesseract::ParamsVectors();
    +  return &global_params;
     }
     
     namespace tesseract {

I'll send a PR with this modification.

**Comment by amitdo** [comment]
Thanks @stweil

I hope zdenko will merge it (I had higher permissions for a a few weeks but waive them).

**Comment by stweil** [comment]
@Molochnik, maybe you can try how many leaks remain in your tests after pull request #447. For me, no leaks remain for the simple case of running `tesseract --tessdata-dir /usr/share/tessdata`.

**Comment by stweil** [comment]
With PR #449 there remain only 2,368 bytes in 2 blocks after processing a simple PNG image.

**Comment by Molochnik** [comment]
I have just checked the latest version - VLD reported: "no memory leaks detected". Perfect!
