### ISSUE TITLE
APPLY_BOXES: boxfile line FAILURE! Couldn't find a matching blob for മ in malayalam

### ISSUE THREAD

**Issue by rkvsraman** [tesseract-ocr/tesseract#445]
I am training tesseract for malayalam.  The tif and the box files and the tesstrain log are shared here https://drive.google.com/drive/folders/0Bz8Xp0bwrlkdblNWMEZnaGpWTEk?usp=sharing 

I am using the Noto Sans Malayalam which is one of the default fonts in Ubuntu

Surprisingly i get errors for only the blobs which have the character മ  in them. 

The ResegmentCharbox method applybox.cpp does not find an overlap for the character box. 

Does it have to do anything with the shape of the character. 

These blobs are:

മ്
മ
മം
മാ
മി
മീ
മു
മൂ
മ്മ
മ്മം
മ്മാ
മ്മി
മ്മീ
മ്മേ
മ്മ്യ
മ്മ്യാ

I checked the tif and box file using http://zdenop.github.io/qt-box-editor/ and it all looks fine.

**Comment by amitdo** [comment]
Does this failure occur with **all** the instances of the glyph?

**Comment by rkvsraman** [comment]
Almost all of them.

**Comment by rkvsraman** [comment]
#451 could be the reason for this.

**Comment by Shreeshrii** [comment]
@zdenop  Please close - duplicate https://github.com/tesseract-ocr/tesseract/issues/1166
