### ISSUE TITLE
Telugu - Simple characters are not being recognized

### ISSUE THREAD

**Issue by Mathrubhasha** [tesseract-ocr/tesseract#450]
Great work and I tried Chinese and English, they work like a charm.
I recently saw that the support for Telugu (Tel) and Hindi (Hin) are supported and there was no limit for my excitement until I saw the results unless I am missing something.
Please fix.

**Comment by Mathrubhasha** [comment]
![telugu-1-ocr](https://cloud.githubusercontent.com/assets/23067666/19712773/393e5734-9b06-11e6-9dda-f58cfa1b6859.png)
![hindi-a-ocr](https://cloud.githubusercontent.com/assets/23067666/19712776/439d370e-9b06-11e6-8cb1-56ebc3e27df6.png)

**Comment by Mathrubhasha** [comment]
I have attached both Telugu (tel) and Hin (hin) language related results. Please help!!

**Comment by rkvsraman** [comment]
Both the images (Telugu and Hindi) seem to be handwritten. Please try a printed text and let us know the accuracy. AFAIK, Tesseract performs well on printed Hindi Text. I have tried for Kannada and even that does well. I have no reason to think it wud'nt do for Telugu but let me give it a try.

**Comment by Mathrubhasha** [comment]
Hello Raman,
  I am in need of support for hand written text for my project. Just checking if that is going to be possible in near future.

Thanks for the great work.

**Comment by amitdo** [comment]
Unless this is a font designed to look like a handwriting, and not an actual handwriting, we can't help you. Sorry.

**Comment by Mathrubhasha** [comment]
Hello Mr. Amit,
Thanks for your quick response.
 I totally understand and agree and I have lot of respect on your ongoing work.

I'm not sure if I can post this but,
Www.myscript.com developed handwritten text to actual text and is currently supported for languages like Telugu and Hindi for android.
I am looking for something like this for a generic solution that suppprts android and iOS and web.

This is just FYI and nothing beyond that if it interests you.

Thank you all for your great work!!!

**Comment by amitdo** [comment]
Hello,

Although I contributed some code for this project, I'm not a core developer of it.

Thanks for the link.

**Comment by HaithemKahil** [comment]
Hello
it's my first time to use tesseract engine and i have a printed text in hindi language 
when i try to ocr the text some characters are not being recognized 
is the problem related to the hin cube files?
![screenshot from 2017-12-23 20-51-52](https://user-images.githubusercontent.com/28069496/34322279-24f5a71c-e823-11e7-9272-4f0af8f3e823.png)
or am i missing something ?
Thank you in advance
here is an example
![ocr_image_test](https://user-images.githubusercontent.com/28069496/34322254-aaa73d68-e822-11e7-9e4c-544fc782ab47.png)
![ocr_text_result](https://user-images.githubusercontent.com/28069496/34322255-aad1619c-e822-11e7-8b84-987f49e4fb5d.png)

**Comment by Shreeshrii** [comment]
@HaithemKahil 

With tesseract 4.00alpha and hin.traineddata from tessdata_fast, the results for your image are accurate.

177, आसींद राजस्थान की निर्वाचक नामावली 2014 भाग संख्या - 4.
अनुभाग संख्या : 1 रतनपुरा ग्राम - रतनपुरा तहसील - आसीन्द जिला - भीलवाडा 311001

@zdenop  Please close the issue.
