### ISSUE TITLE
Failure to box  മ character in malayalam

### ISSUE THREAD

**Issue by rkvsraman** [tesseract-ocr/tesseract#451]
I ran 

tessreract mal.png malreco -l mal segdemo inter

on following image

![mal](https://cloud.githubusercontent.com/assets/1249525/19714653/896c983a-9b6d-11e6-8f55-9b61c486b49d.png)

I see that the character  മ  is not at all getting boxed which is visible from following images. 

![screen shot 2016-10-26 at 11 12 22 am](https://cloud.githubusercontent.com/assets/1249525/19714667/9e5a7f0a-9b6d-11e6-878b-b27e5c40b868.png)

![screen shot 2016-10-26 at 11 13 43 am](https://cloud.githubusercontent.com/assets/1249525/19714668/9e60d6e8-9b6d-11e6-81b3-ff2affab7f27.png)

**Comment by rkvsraman** [comment]
This i think is the  reason why training മ character fails in #445

**Comment by Shreeshrii** [comment]
Is this with the mal.traineddata from tessdata repository or with your traineddata?

Are there differences in output with each?

**Comment by rkvsraman** [comment]
I tried with mal.traineddata from tessdata repository 

This is irrespective of any traineddata. The segmentation of the bounding box itself is flawed.

**Comment by Shreeshrii** [comment]
Is this issue still there with the latest code and traineddata from tessdata_best and tessdata_fast?

**Comment by zdenop** [comment]
Closed because of missing input from reporter.
