### ISSUE TITLE
Laravel 5.1 empty string return

### ISSUE THREAD

**Issue by waleedtfps** [tesseract-ocr/tesseract#452]
so i was testing it on my local machine windows 10 install laravel install.
`Route::get('/test', function () {
	
	$tesseract = new TesseractOCR(public_path("text.png"));
$tesseract->tessdataDir("D:\\");
$tesseract->psm(6);
$tesseract->lang('en');
var_dump ($tesseract->run());
});`

its return a empty string. 
but if i try it from command line  works .
tesseract is added to $path and its working well on cmd .
Any idea what causing this issue ?

**Comment by amitdo** [comment]
[Guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md)

Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr)
