### ISSUE TITLE
Replace all NULLs with nullptr

### ISSUE THREAD

**Issue by egorpugin** [tesseract-ocr/tesseract#455]
Since tess is using c++11 we need to `s/NULL/nullptr/`.

**Comment by amitdo** [comment]
http://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html

**Comment by stweil** [comment]
What about finishing this job? Several thousand `NULL` macros are still in the code. Replacing them could be done per directory. About 293 files would need changes. Here are the file counts per directory:

      7 api
     36 ccmain
     48 ccstruct
     40 ccutil
     40 classify
      6 cutil
      9 dict
      4 doc
     20 lstm
     52 textord
      2 training
      4 viewer
      4 vs2010
     21 wordrec

**Comment by egorpugin** [comment]
It's all about Ray. Such changes can break his merges.

**Comment by amitdo** [comment]
@theraysmith, can you fix it with clang-tidy?
http://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html

**Comment by stweil** [comment]
@egorpugin, I think this issue can be closed now.
