### ISSUE TITLE
Error when compiling Tesseract 3.01 on RHEL5

### ISSUE THREAD

**Issue by iamcool345** [tesseract-ocr/tesseract#458]
Hi,
 I have a compile error as the result of running 'make' for Tesseract 3.01: 
[root@localhost tesseract-3.01]# make
make  all-recursive
make[1]: Entering directory `/root/tesseract-3.01'
Making all in ccutil
make[2]: Entering directory `/root/tesseract-3.01/ccutil'
make[3]: Entering directory `/root/tesseract-3.01/ccutil'
if /bin/sh ../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I. -I..   -I/usr/local/include/leptonica -DTESSDATA_PREFIX=/usr/local/share/ -g -O2 -MT ambigs.lo -MD -MP -MF ".deps/ambigs.Tpo" -c -o ambigs.lo ambigs.cpp; \
        then mv -f ".deps/ambigs.Tpo" ".deps/ambigs.Plo"; else rm -f ".deps/ambigs.Tpo"; exit 1; fi
 g++ -DHAVE_CONFIG_H -I. -I. -I.. -I/usr/local/include/leptonica -DTESSDATA_PREFIX=/usr/local/share/ -g -O2 -MT ambigs.lo -MD -MP -MF .deps/ambigs.Tpo -c ambigs.cpp  -fPIC -DPIC -o .libs/ambigs.o
In file included from params.h:26,
                 from tprintf.h:23,
                 from ambigs.h:25,
                 from ambigs.cpp:24:
strngs.h:1: error: stray '\357' in program
strngs.h:1: error: stray '\273' in program
strngs.h:1: error: stray '\277' in program
In file included from unicharset.h:24,
                 from ambigs.h:27,
                 from ambigs.cpp:24:
strngs.h:1: error: stray '\357' in program
strngs.h:1: error: stray '\273' in program
strngs.h:1: error: stray '\277' in program
make[3]: *** [ambigs.lo] Error 1
make[3]: Leaving directory `/root/tesseract-3.01/ccutil'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/tesseract-3.01/ccutil'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/tesseract-3.01'
make: *** [all] Error 2

OS:  Linux localhost.localdomain 2.6.18-194.el5xen #1 SMP Tue Mar 16 22:01:26 EDT 2010 x86_64 x86_64 x86_64 GNU/Linux

Leptonica 1.67 installed.
Thanks for help.

**Comment by Brian51** [comment]
Hi iamcool345, Try updating to a more recent version of Leptonica and/or the more recent version of Tesseract as well.

B.

**Comment by amitdo** [comment]
[Guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md)

Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).

**Comment by zdenop** [comment]
This is old error that was already fixed.
