### ISSUE TITLE
Minor win32 sintax issues under Windows unicode

### ISSUE THREAD

**Issue by Molochnik** [tesseract-ocr/tesseract#460]
There are small issues in the code that cause compilation errors under Windows unicode project.
The problem is that some of win32 api functions are called without a proper postfix "A" which forces compiler to use non-unicode version of these functions. Here are all of them:
baseapi.cpp
377 WIN32_FIND_DATA -> WIN32_FIND_DATAA
379 FindFirstFile-> FindFirstFileA
381 FindNextFile -> FindNextFileA

svutil.cpp
82 STARTUPINFO -> STARTUPINFOA
84 GetStartupInfo -> GetStartupInfoA
85 CreateProcess -> CreateProcessA

mainblk.cpp
69 GetModuleFileName -> GetModuleFileNameA

P.S.
The same problem exists in the latest Leptonica library but among the similar errors that can be located by the compiler there are some that it is not able to find e.g. when the code uses GetTempPath instead of GetTempPathA.

**Comment by amitdo** [comment]
>The problem is that some of win32 api functions are called without a proper postfix "A" which forces compiler to use non-unicode version of these functions. Here are all of them

I'm not a Windows guy, but I think you are wrong here.

https://msdn.microsoft.com/en-us/library/windows/desktop/dd374089(v=vs.85).aspx


>Windows API functions that manipulate characters are generally implemented in one of three formats:
>
>    A generic version that can be compiled for either Windows code pages or Unicode
    A Windows code page version with the letter "A" used to indicate "ANSI"
    A Unicode version with the letter "W" used to indicate "wide"

cc: @egorpugin

**Comment by egorpugin** [comment]
> A generic version that can be compiled for either Windows code pages or Unicode

This should be used by default. No suffix - compiler will choose it without user.
No need to rename functions.

**Comment by Molochnik** [comment]
> This should be used by default. No suffix - compiler will choose it without user.
> No need to rename functions.

You are right on one condition - if you use "TCHAR" type vars as WinApi function parameters instead of "char" and likewise LPCTSTR instead of LPCSTR, LPTSTR instead of LPSTR and so on.

**Comment by egorpugin** [comment]
So, types should be fixed, not functions.

**Comment by Molochnik** [comment]
> So, types should be fixed, not functions.
yes sure, but I think functions can be fixed easier

**Comment by Shreeshrii** [comment]
@Molochnik Is this issue still there with the latest code?

**Comment by zdenop** [comment]
Closed because of missing input from reporter.
