### ISSUE TITLE
Memory leak of EDGEPT objects

### ISSUE THREAD

**Issue by BobNagy** [tesseract-ocr/tesseract#462]
I am using the tesseract API in my Windows app and performing batch OCR of many jpg and some png files.  Due to the number of images involved, I have not yet isolated the cause of this leak to one particular file or situation, but I suspect there is a corner case involved because this does not seem to happen with every file.

Vld reports leaks like this :

>>>
---------- Block 707297183 at 0x219EB3B8: 32 bytes ----------
  Leak Hash: 0x6F1A7A6E, Count: 1, Total 32 bytes
  Call Stack (TID 17004):
    ntdll.dll!RtlAllocateHeap()
    f:\dd\vctools\crt\vcstartup\src\heap\new_scalar.cpp (19): operator new() + 0x9 bytes
    ccstruct\polyaprx.cpp (82): ApproximateOutline() + 0x7 bytes
    ccstruct\blobs.cpp (327): ApproximateOutlineList() + 0xE bytes
    ccstruct\blobs.cpp (346): TBLOB::PolygonalCopy() + 0x19 bytes
    ccstruct\blobs.cpp (799): TWERD::PolygonalCopy() + 0xE bytes
    ccstruct\pageres.cpp (316): WERD_RES::SetupForRecognition() + 0x11 bytes
    ccmain\control.cpp (200): tesseract::Tesseract::SetupWordPassN()
    ccmain\control.cpp (1254): tesseract::Tesseract::ClassifyBlobAsWord()
    ccmain\control.cpp (1222): tesseract::Tesseract::ClassifyBlobPlusOutlines() + 0x1C bytes
    ccmain\control.cpp (1156): tesseract::Tesseract::SelectGoodDiacriticOutlines() + 0x23 bytes
    ccmain\control.cpp (1073): tesseract::Tesseract::AssignDiacriticsToNewBlobs() + 0xA1 bytes
    ccmain\control.cpp (958): tesseract::Tesseract::ReassignDiacritics()
    ccmain\control.cpp (256): tesseract::Tesseract::RecogAllWordsPassN() + 0x14 bytes
    ccmain\control.cpp (348): tesseract::Tesseract::recog_all_words() + 0x1C bytes
    api\baseapi.cpp (902): tesseract::TessBaseAPI::Recognize() + 0x1C bytes
    api\baseapi.cpp (1225): tesseract::TessBaseAPI::ProcessPage() + 0xA bytes
    api\baseapi.cpp (1174): tesseract::TessBaseAPI::ProcessPagesInternal() + 0x65 bytes
    api\baseapi.cpp (1084): tesseract::TessBaseAPI::ProcessPages() + 0x18 bytes
  Data:
    3D 00 6D 00    11 00 FA FF    00 01 00 00    A8 B9 9E 21     =.m..... .......!
    B8 B8 9E 21    00 00 00 00    00 00 00 00    00 00 00 00     ...!.... ........

Visual Leak Detector detected 436 memory leaks (29648 bytes).
Largest number used: 220661446 bytes.
Total allocations: 4294967295 bytes.
Visual Leak Detector is now exiting.
<<<

In this instance, most of the leaks were very similar to the one shown above; all 32 byte objects, all allocated at polyaprx.cpp (82), but some had slightly different call stacks.
In other instances, Vld reports zero leaks, so I suspect I have some image files that are goofy in some way and setting tesseract through a code path that produces the leak.

I have looked through all recent checkins, and I don't see any change that seems likely to fix this.
My sources came from master branch on 10/19/16.

**Comment by Shreeshrii** [comment]
@BobNagy Do you still see these leaks with the latest code?

**Comment by zdenop** [comment]
Closed because of missing input from reporter.
