### ISSUE TITLE
Is tesseract-ocr currently using lstm?

### ISSUE THREAD

**Issue by WenchenLi** [tesseract-ocr/tesseract#465]
Hi,
I went through the all the slides in das tutorial 2016 https://github.com/tesseract-ocr/docs/tree/master/das_tutorial2016.

May I ask is the version install through `sudo apt-get install tesseract-ocr ` using lstm by calling `tesseract ` at terminal?

Thanks!

**Comment by Shreeshrii** [comment]
No, Ray has not updated the code with LSTM yet and as far as I know hasn't
communicated a date when it will be done.

**Comment by zdenop** [comment]
Please do not use issue tracker for asking question - use teseract user forum

**Comment by Shreeshrii** [comment]
@zdenop

There have been a number of questions re tesseract 4.0 or version with
LSTM. It will be helpful for the community to know the status.

I have added a wiki page with available info at
https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM

Please change the language as you deem fit and update when there is info
available about the release.

Thanks.
