### ISSUE TITLE
Unable to process chalkboard writings

### ISSUE THREAD

**Issue by thomasbaldwin** [tesseract-ocr/tesseract#468]
Hey guys,

First of all I wanted to say thanks for the continued work on this! It's real cool and me and a friend are using it for a school project. However, the issue we're running into is that it doesn't seem to be able to process the below image, and instead returns an empty text file. 

Here's the image we're trying to read:

![test](https://cloud.githubusercontent.com/assets/5099084/20042014/966ac404-a440-11e6-8f94-11ae45df5c94.jpg)

And here's the error we're getting:

<img width="496" alt="screen shot 2016-11-06 at 4 47 50 pm" src="https://cloud.githubusercontent.com/assets/5099084/20042036/cd1aac30-a440-11e6-9a68-7f7f37c72c22.png">

Any suggestions as to what we can do to try and achieve this goal of processing text, numbers, and symbols on a chalkboard?

Thanks for the help,
Thomas

P.S. It works well with other images such as this:

![test3](https://cloud.githubusercontent.com/assets/5099084/20042183/86969eba-a443-11e6-9707-b73ab9db63ef.jpg)

So is the issue that the chalkboard writing has too much noise?

**Comment by amitdo** [comment]
Hi Thomas,

```
convert 468.jpg  -bordercolor black -border 20x20 468-b.jpg
tesseract 468-b.jpg - -psm 11
```

>I+I
>
>2+2m

For further questions, please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).
