### ISSUE TITLE
Add Windows binary to 3.04.00 release

### ISSUE THREAD

**Issue by niksedk** [tesseract-ocr/tesseract#47]
I think this would make a lot of users happy :)

**Comment by jbreiden** [comment]
Better to wait for 3.04.01 due to PDF data corruption bug discussed in developer forum

**Comment by jbreiden** [comment]
Unless Windows doesn't use stdout. In that case, go for it.

**Comment by Shreeshrii** [comment]
cygwin test version is available at http://domasofan.spdns.eu/tesseract/ thanks to 
Simon Eigeldinger

**Comment by abdul202** [comment]
i wish someone create the latest version for windows

**Comment by hathawad** [comment]
Where would this be available when its produced?

**Comment by Zenadix** [comment]
+100000

**Comment by correosdelbosque** [comment]
Happy happy happy. thank you

**Comment by Borkason** [comment]
> Where would this be available when its produced?

I don’t even find any binaries. Can a fella help me out? :pray:

**Comment by peirick** [comment]
If you have Visual Studio 2015, checkout my repository at https://github.com/peirick/leptonica and click on build_tesseract.bat. After that you still need to download the language packs.

**Comment by winkelement** [comment]
Thanks @peirick !
Worked perfect :+1:

**Comment by SarunasSS** [comment]
I need a .dll to make a wrapper for python. @Shreeshrii haven't found in the link you posted, but maybe you know alternative?

@peirick does the script also build a .dll?

**Comment by peirick** [comment]
No the script only builds the *.exe and the *.lib for static linkage. I run into problems with memorymangement using the *.dll.

**Comment by SarunasSS** [comment]
Could you share your version of the code to compile the .dll and then I
could have a look at it?

On Wed, Jan 20, 2016 at 5:32 PM, peirick <notifications@github.com> wrote:

> No the script only builds the *.exe and the *.lib for static linkage. I
> run into problems with memorymangement using the *.dll.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tesseract-ocr/tesseract/issues/47#issuecomment-173239390>
> .
>



-- 
Pagarbiai,
Šarūnas

**Comment by Shreeshrii** [comment]
[See issue 209](https://github.com/tesseract-ocr/tesseract/issues/209)
