### ISSUE TITLE
Tesseract cannot recognize clean webpage screenshot

### ISSUE THREAD

**Issue by LinxiFan** [tesseract-ocr/tesseract#472]
I'm using Tesseract (3.04.01 with leptonica-1.73) to segment a clean screenshot of a web page. Here is the command I use:

        tesseract screen.png output.txt

screen.png:

![screen.png](https://i.stack.imgur.com/wfwEi.png)

output.txt:

    a CSS Regwstratmnﬁ x

    C (D localnostr

    Accoum Dexans

    Eu a Pine: 5" a

    Fiﬁ/(‘3’ 22pm; J. , km?“ ”9

    Persuna‘ Dexaus Funhev \muvmanun

    «m s , (35‘ m Was :6 ms

    FMS, Emms' (u v Jaruawy

    *1: \(uax y ,

    Chum

    Terms and Mamng
    m any ‘ ‘ Regwsley»

    w lc‘asehe :avicxﬂza \zh»,:\':\e

    Mm , (ism-ye I/Exzavheilédgémzéi

     
The output is complete garbage except for a few words like "Terms and". Could anyone please tell me which command line options I should set to make it work? Thanks in advance!

**Comment by amitdo** [comment]
[Guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md)

Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).
