### ISSUE TITLE
reading from images other than specified image filename!

### ISSUE THREAD

**Issue by jerkey** [tesseract-ocr/tesseract#476]
to reproduce:
$ ls
1a.tiff 1b.tiff 1c.tiff
$ tesseract 1a.tiff 1a
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Page 1
Page 2
Page 3
Page 4
$ cat 1a.txt
_file contains text read from 1a.tiff AND 1b.tiff AND 1c.tiff WTF please_

**Comment by amitdo** [comment]
Did you try to open 1a.tiff with an image viewer that can present multi-page tiff? This tiff file contains 4 images.

**Comment by zdenop** [comment]
I can not reproduce described behavior. Please upload somewhere your files, that demonstrate problem.

**Comment by zdenop** [comment]
Close because of no proof of described error
