### ISSUE TITLE
orientation detection affected by output renderer

### ISSUE THREAD

**Issue by jbreiden** [tesseract-ocr/tesseract#48]
Orientation detection works if we ask for PDF output and fails if we ask for text output. Weird.

tesseract -l deu+eng /bw_2015-03-01_081225.png bad
tesseract -l deu+eng /bw_2015-03-01_081225.png good pdf

#good.txt
R etwas zu studieren, zu verstehen und
dann an andere weiterzugeben; Material zu
entwickeln, mit dem etwas leicht und
verständlich vermittelt werden kann. 2 1 O ?

#bad.txt
.CONuQmDNED S<C2><AE><C2><A3><C2><AE>1H Ev.<E2><80><94>0.1 Cw
DHCHQHQU md? <E2><80><9E>CO<E2><80><94>UMD? HMUBOL DNNU EQ<EF><AC><81><E2><80><94>Om<EF><AC><82>wz
ohu<EF><AC><81><EF><AC><82>d mmm<EF><AC><81>v <E2><80><9E>Gwhm<EF><AC><81>v<E2><80><94>ho 5N\C<C2><AE>h<EF><AC><81><E2><80><94><C2><AE>_ 3N Om

![bw_2015-03-01_081225](https://cloud.githubusercontent.com/assets/4961958/8760334/c87883a8-2cca-11e5-8e1b-16ee50a59d9b.png)

**Comment by jbreiden** [comment]
Nevermind. tessedit_pageseg_mode 1 is inside the pdf config file.

**Comment by stweil** [comment]
Fixed with PR #1943.
