### ISSUE TITLE
Farsi number mismatch order

### ISSUE THREAD

**Issue by maryamtooty** [tesseract-ocr/tesseract#480]
OK, I use lasted version of tesseract ocr on my project. Install it from nuget.
On English, result is almost fine. On Persian numbers for example.
۲۳۴۵۶۷
Gives me
۷۲۳۴۵۶
Or
۱۲۳۴۵۶۷۸۹
Gives this
۹۸۷۴۵۶۳۲۱

Each test has a different result. I even check master ocr project, source code, and noticed the bug coming from pointer handler.
Give me a solution for this please, I can't fix it and my project is on the dead line.

**Comment by amitdo** [comment]
>I even check master ocr project, source code, and noticed the bug coming from pointer handler.

If you think you know where exactly is the source of the issue, please link to the relevant file and line in the source code.

**Comment by roozgar** [comment]
​which trained data are you using?!​

**Comment by maryamtooty** [comment]
I use farsi trained data. It called fas.traineddata
And of course I try to find the exact problem line in the source, but I failed.

**Comment by maryamtooty** [comment]
I traced the runtime error until marshalHelper.cs
PrtToString as I could remember.

**Comment by roozgar** [comment]
​rtl languages like persian or arabic are using cube engine and havent good
accuracy ​...

​also the PersianOcr <https://github.com/reza1615/PersianOcr> you used
their trained data is a dead project and didnt reached its goal :( ​

**Comment by maryamtooty** [comment]
I checked them all, sorry to say that. But asking you people was my final
solution.

**Comment by roozgar** [comment]
​the  best result you can reach in tesseract is this you reached
if your problem is reversed results you can done it with your programming
language!

regards​

**Comment by Shreeshrii** [comment]
@roozgar Is this issue fixed with tesseract4 and traineddata from tessdata_fast?

**Comment by Shreeshrii** [comment]
The order problem seems to be fixed in the tessdata_best/fas.traineddata. Though accuracy issues remain.

![fas-numbers](https://user-images.githubusercontent.com/5095331/40245173-73a2ff86-5ae2-11e8-8613-593d4be6038f.png)

```
 tesseract fas-numbers.png - --tessdata-dir ../tessdata_best --psm 3 --oem 1 -l fas  -c page_separator=''
۳۳۳۳۵۷
۷۵۶

۱۳۳/۸۹(
مره در

۳۳۳۷
۷۳۵۶

3۳7۳/۸۹(
ی

7۳
(۶

۱۹(


```

**Comment by Shreeshrii** [comment]
I 'plusminus' trained using Arabic traineddata as base for fas. Resulting traineddata is at
https://github.com/Shreeshrii/tessdata_shreetest/raw/master/fas-tune-best.traineddata

That gives better result on the same image used above.

```
$ tesseract fas-numbers.png - --tessdata-dir ../tessdata_best --psm 3 --oem 1 -l fas-tune-best  -c page_separator=''
۲۳۴۵۶۷
VY۳۴۵۶

۱۲۳۴۵۶۷۸۹
۹۸۷۴۵۶۳۲۱

۲۳۴۵۶۷
Vvr۳۴o۶s

۱۲۳۴۵۶۷۸۹
۹۸۷۴۵۶۳۲۱

۲۳۴۵۶۷
4

۱۲۳۴۵۶۷۸۹
۹۸۷۴۵۶۳۲۱

```

**Comment by Shreeshrii** [comment]
A different training, which does not include the English alphabet etc from Arabic traineddata gives the following result:

```
 tesseract fas-numbers.png - --tessdata-dir ../tessdata_best --psm 3 --oem 1 -l fas-script-best  -c page_separator=''
۳۴۵۶
۳۳۴۵۶

۱۱۳۴۵۶۸۹
۹۸۴۵۶۳۲۱

۳۵۶۷
۳۴۵۶

۱۰۳۴۶۸۹
۴۵۶۳۲۱

۲۳۴۵۶۷
۷۳۲۳۴۵۶

۱۳۳۴۵۰۸۹
۹۸۷۴۵۶ ۳۲۱

```

**Comment by Shreeshrii** [comment]
The ordering problem reported by OP is fixed in current code using tessdata_best/fas.traineddata.

@zdenop  This issue can be closed.

**Comment by redP4rrot** [comment]
For Farsi and other RTL language like Hebrew, Arabic &... If numeric system is FTL as it supposed to. It's better to made your own special tdata for your task.
This error happened because tdata designed for right to left alphabet.

**Comment by mojtabaasadi** [comment]
@Shreeshrii  can you share your training data?
