### ISSUE TITLE
Tesseract wordlist2dawg dawg is empty

### ISSUE THREAD

**Issue by sjaanus** [tesseract-ocr/tesseract#482]
I am trying to train tesseract with my own data and want to generate frequent file list with wordlist2dawg. https://github.com/tesseract-ocr/tesseract/blob/master/doc/wordlist2dawg.1.asc

Running command

`wordlist2dawg data/freq_file_list.txt eng1.freq-dawg eng1.unicharset`
This is output

```
Loading unicharset from 'eng1.unicharset'
Reading word list from 'data/freq_file_list.txt'
Reducing Trie to SquishedDawg
Dawg is empty, skip producing the output file
Wordlist looks like this
```

```
Akbronco
Akstiletto
Ankyros
Ash
Bo
Boar
Boltor
Braton
Bronco
Burston
Carrier
Dakra
Dual
Ember
Fang
Fragor
....
```
It is not generating the dawg file, any suggestions what is wrong?

**Comment by zdenop** [comment]
Please provide all input files

**Comment by sjaanus** [comment]
Added both files
[freq_file_list.txt](https://github.com/tesseract-ocr/tesseract/files/605711/freq_file_list.txt)

**Comment by zdenop** [comment]
Please provide also information about tesseract version and OS.

**Comment by sjaanus** [comment]
I am using Tesseract 3.05-dev on Windows 10.

**Comment by Shreeshrii** [comment]
@sjjanus

Your unicharset only has CAPITAL letters, while your word list has words in mixed case. I tried your word list with the eng.unicharset and it works fine. If fails when I use eng1.unicharset.txt provided by you.

Tested with 4.0 on windows10

**Comment by Shreeshrii** [comment]
@sjjanus Please close the issue if solved.

**Comment by blacklong617** [comment]
I got the same result,I think there maybe two probability.
1、The encoding of the input files freq_file_list.txt and eng1.unicharset.txt may not meet the requirements .
2、The unicharset you provide is not the correct.The unicharset file must be regenerated whenever inttemp, normproto and pffmtable are generated. use : 
mftraining -F font_properties -U unicharset -O regenerated.unicharset  *.tr

**Comment by ibr123** [comment]
hi,
what if the language was Arabic, which doesn't have capital case or small case, but the same problem was generated, what could be the issue?

**Comment by Shreeshrii** [comment]
@blacklong617 @ibr123 

Please note tesseract version, o/s, commit number if known.

Also share the input files.

**Comment by ibr123** [comment]
[ara_frequent.txt](https://github.com/tesseract-ocr/tesseract/files/929641/ara_frequent.txt)
[ara.unicharset.txt](https://github.com/tesseract-ocr/tesseract/files/929645/ara.unicharset.txt)
these are the input files, the tesseract version is: tesseract 4.00.00alpha and OS is windows 10
and thanks for your response

**Comment by Shreeshrii** [comment]
your ara_frequent.txt is encoded in ANSI with windows style end of line
markers. the first few lines show up as the following, instead of in Arabic.

íÊæÞÚ
ÇáÚáãÇÁ
Ãä
ÊÕÈÍ
ÝÇßåÉ
ÇáßÑÒ
æÇÍÏÉ
ãä
æÓÇÆá
ÚáÇÌ
ÇáÏÇÁ
ÇáÓßÑí
ÝÇáãÇÏÉ
ÇáÓßÑíÉ

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Also see https://github.com/tesseract-ocr/tesseract/blob/master/training/tesstrain_utils.sh#L339

```
 # -r arguments to wordlist2dawg denote RTL reverse policy
    # (see Trie::RTLReversePolicy enum in third_party/tesseract/dict/trie.h).
    # We specify 0/RRP_DO_NO_REVERSE when generating number DAWG,
    # 1/RRP_REVERSE_IF_HAS_RTL for freq and word DAWGS,
    # 2/RRP_FORCE_REVERSE for the punctuation DAWG.
```

**Comment by Shreeshrii** [comment]
@sjaanus Is your issue resolved? Please mention the solution and close the issue.

**Comment by Shreeshrii** [comment]
Is this issue still there? If not, please close the issue.

**Comment by zdenop** [comment]
Closing because of missing input from reporter.

**Comment by vineemike** [comment]
i am also facing the same issue. wordlist2dawg not creating the word-dawg file.  using windows 10 and tesseract version 3.0.2. Kindly assist
