### ISSUE TITLE
Simple test about self training data, but the result is so strange.

### ISSUE THREAD

**Issue by Curtis0624** [tesseract-ocr/tesseract#483]
Hi，
Attached is the target image (Image61.tif, characters are"330") and all train data(.traineddata, .box and .tif).
[SimpleTest.zip](https://github.com/tesseract-ocr/tesseract/files/602968/SimpleTest.zip)

traindata1\fontyp.traineddata
Trained data just includes "3". The result is 333.
traindata2\fontyp.traineddata
Trained data includes "3" and "5". The result is 355 and why the second character isn't "3"?
The situations are the same using tesseract-OCR 3.02 or 3.05.00dev .
Could anybody help me? Thanks a lot!!

**Comment by Curtis0624** [comment]
More information:
1. OS is windows 7.
2. Tesseract-OCR 3.02 or 3.05.00dev .
3. Command line:
Tesseract Image61.tif result -l fontyp

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support.

**Comment by Curtis0624** [comment]
Thanks.
