### ISSUE TITLE
Installing Tesseract in AIX 6.1 and GCC 4.0.0

### ISSUE THREAD

**Issue by KrishnenduP** [tesseract-ocr/tesseract#484]
Hi,
We are getting compilation error while trying to install Tesseract in AIX 6.1 and GCC 4.0.0.
If anyone has installed Tesseract in AIX please let me know the steps for installation.
Currently, we are getting the following error
ibtool: compile: gcc -DHAVE_CONFIG_H -I. -I.. -g -O2 -MT jpegio.lo -MD -MP -MF .deps/jpegio.Tpo -c jpegio.c -DPIC -o .libs/jpegio.o

jpegio.c:112:21: error: jpeglib.h: No such file or directory

jpegio.c:114: error: expected ')' before 'cinfo'

jpegio.c:115: error: expected ')' before 'cinfo'

jpegio.c:122: error: expected '=', ',', ';', 'asm' or 'attribute' before 'jpeg_comment_callback'

jpegio.c: In function 'pixReadStreamJpeg':

jpegio.c:228: error: 'JSAMPROW' undeclared (first use in this function)

jpegio.c:228: error: (Each undeclared identifier is reported only once

jpegio.c:228: error: for each function it appears in.)

jpegio.c:228: error: expected ';' before 'rowbuffer'

jpegio.c:231: error: storage size of 'cinfo' isn't known

jpegio.c:232: error: storage size of 'jerr' isn't known

jpegio.c:246: error: 'BITS_IN_JSAMPLE' undeclared (first use in this function)

jpegio.c:254: error: 'rowbuffer' undeclared (first use in this function)

jpegio.c:260: error: 'jpeg_error_do_not_exit' undeclared (first use in this function)

jpegio.c:265: error: 'JPEG_COM' undeclared (first use in this function)

jpegio.c:265: error: 'jpeg_comment_callback' undeclared (first use in this function)

jpegio.c:271: error: 'JCS_GRAYSCALE' undeclared (first use in this function)

jpegio.c:278: error: 'JCS_YCCK' undeclared (first use in this function)

jpegio.c:279: error: 'JCS_CMYK' undeclared (first use in this function)

jpegio.c:286: error: expected ';' before 'calloc'

jpegio.c:290: error: expected ';' before 'calloc'

jpegio.c:336: error: 'JDIMENSION' undeclared (first use in this function)

jpegio.c:336: error: expected ')' before numeric constant

jpegio.c:374: error: expected ')' before numeric constant

jpegio.c: In function 'freadHeaderJpeg':

jpegio.c:472: error: storage size of 'cinfo' isn't known

jpegio.c:473: error: storage size of 'jerr' isn't known

jpegio.c:492: error: 'jpeg_error_do_not_exit' undeclared (first use in this function)

jpegio.c:503: error: 'JCS_YCCK' undeclared (first use in this function)

jpegio.c:505: error: 'JCS_CMYK' undeclared (first use in this function)

jpegio.c: In function 'fgetJpegResolution':

jpegio.c:530: error: storage size of 'cinfo' isn't known

jpegio.c:531: error: storage size of 'jerr' isn't known

jpegio.c:546: error: 'jpeg_error_do_not_exit' undeclared (first use in this function)

jpegio.c: In function 'pixWriteStreamJpeg':

jpegio.c:655: error: 'JSAMPROW' undeclared (first use in this function)

jpegio.c:655: error: expected ';' before 'rowbuffer'

jpegio.c:657: error: storage size of 'cinfo' isn't known

jpegio.c:658: error: storage size of 'jerr' isn't known

jpegio.c:670: error: 'rowbuffer' undeclared (first use in this function)

jpegio.c:700: error: 'jpeg_error_do_not_exit' undeclared (first use in this function)

jpegio.c:710: error: 'JCS_GRAYSCALE' undeclared (first use in this function)

jpegio.c:714: error: 'JCS_RGB' undeclared (first use in this function)

jpegio.c:757: error: 'JPEG_COM' undeclared (first use in this function)

jpegio.c:757: error: expected ')' before 'JOCTET'

jpegio.c:763: error: expected ')' before 'calloc'

jpegio.c:784: error: expected expression before ')' token

jpegio.c: At top level:

jpegio.c:1115: error: expected ')' before 'cinfo'

jpegio.c:1125: error: expected ')' before 'cinfo'

jpegio.c:1144: error: expected '=', ',', ';', 'asm' or 'attribute' before 'jpeg_comment_callback'

make: 1254-004 The error code from the last command is 1.

Stop.

make: 1254-004 The error code from the last command is 1.

Stop.

make: 1254-004 The error code from the last command is 2.

Thanks,
Krishnendu

**Comment by amitdo** [comment]
`jpegio.c` is part of Leptonica
https://github.com/DanBloomberg/leptonica/blob/master/src/jpegio.c

https://github.com/DanBloomberg/leptonica/issues

**Comment by stweil** [comment]
The errors are the result of a missing libjpeg or libjpeg-turbo. Install the developer (including header files) version of one of those libraries.
