### ISSUE TITLE
 build error in ubuntu 16.04

### ISSUE THREAD

**Issue by blairq** [tesseract-ocr/tesseract#485]
commit c1c1e426b32794d5e84134ee81bf895ff0228fe5

system : ubuntu 16.04
there is an errror on lstmrecoginzer.cpp and other files.
the infamous 'isnan()' error
one way to fix NOW it is replacing  isnan() with std::isnan()

go into lstm dir and execute 

> sed -i 's/isnan/std::isnan/g' `grep "isnan" -rl`

have fun

**Comment by zdenop** [comment]
You can sent pull requests...

**Comment by stweil** [comment]
PR #491 should fix this build problem (which also breaks the continuous integration tests).

**Comment by stweil** [comment]
@blairq, could you please repeat your test with the latest version from git?

**Comment by amitdo** [comment]
This issue should be closed.
