### ISSUE TITLE
Error: LSTM requested, but not present!! Loading tesseract.

### ISSUE THREAD

**Issue by nolsigan** [tesseract-ocr/tesseract#487]
Hi, I'm trying to work with the newly updated LSTM tesseract.

Tesseract gives me this error when I try
```sh
$ tesseract image.jpg out -oem 4

Error: LSTM requested, but not present!! Loading tesseract.
```

It seems like I don't have the tessdata for LSTM.

Where can I get it?

**Comment by zdenop** [comment]
Current master repository is for delepers and not for users.

**Comment by amitdo** [comment]
The LSTM traineddata files aren't available yet.

**Comment by nolsigan** [comment]
Thanks for your replies!

**Comment by amitdo** [comment]
The LSTM traineddata files are available now.
https://github.com/tesseract-ocr/tessdata

**Comment by nolsigan** [comment]
Thank you! I'll try it out
