### ISSUE TITLE
Text creation not disabled in other output configs

### ISSUE THREAD

**Issue by jimregan** [tesseract-ocr/tesseract#49]
As discussed on the list: https://groups.google.com/d/msgid/tesseract-dev/32c065ee-aefa-441a-b37b-b6bdc234c8ab%40googlegroups.com

**Comment by zdenop** [comment]
fixed with 43834da7a2aa443849a6b219d589a61677c46a11

**Comment by jimregan** [comment]
Should the box creation and unlv configs have this too?

**Comment by zdenop** [comment]
IMO yes.

**Comment by jimregan** [comment]
Ok, if it turns out to be needed elsewhere, new issues are cheap.
