### ISSUE TITLE
text2image exit when some of chinese characters can NOT be rendered with some fonts

### ISSUE THREAD

**Issue by albertyou2** [tesseract-ocr/tesseract#490]
I'am trying to use text2image to create my  XXX.tif file and XXX.box file.
I found that only If all the characters can be rendered ,the text2image works fine.
It will broken when some characters can NOT be renderd with some fonts (the chinese fonts file usually  would NOT contain all the characters of chinese)

Is there a method to skip the character which could not be  rendered?(for example: use '  ' instead of the characters or just skip them)

thank you !

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support.

**Comment by Shreeshrii** [comment]
Text2image has the option to use only renderable characters. Please check
help for syntax

text2image --help

**Comment by Shreeshrii** [comment]
--strip_unrenderable_words

**Comment by albertyou2** [comment]
@Shreeshrii 
YES it works! thank you

**Comment by albertyou2** [comment]
@Shreeshrii Sorry ,I met a anther error :
 cluster text.size() == start_byte_to_box.size():error
