### ISSUE TITLE
Build fails on 4.0 Ubuntu 14.04

### ISSUE THREAD

**Issue by SteveLeeIBM** [tesseract-ocr/tesseract#497]
I just downloaded the latest tesseract release on Ubuntu 14.04.

hostname = tegra-ubuntu
uname -m = armv7l
uname -r = 3.10.40-gdacac96
uname -s = Linux
uname -v = #2 SMP PREEMPT Mon Nov 21 19:37:51 UTC 2016

| #define PACKAGE_NAME "tesseract"
| #define PACKAGE_VERSION "4.00.00dev"
| #define PACKAGE_YEAR "2016"
| #define PACKAGE_DATE "11/11"
| #define PACKAGE "tesseract"
| #define VERSION "4.00.00dev"

I compiled and installed leptonica-1.73.tar.gz successfully.

I followed the instructions:
https://github.com/tesseract-ocr/tesseract/wiki/Compiling

./autogen.sh
./configure
make
However when I attempt to make , it fails with
g++: error: unrecognized command line option '-mavx' (see below)

Any help would be greatly appreciated.
Thanks
Steve

ubuntu@tegra-ubuntu:~/workspace/tesseract$ make
make  all-recursive
make[1]: Entering directory `/home/ubuntu/workspace/tesseract'
Making all in arch
make[2]: Entering directory `/home/ubuntu/workspace/tesseract/arch'
make[3]: Entering directory `/home/ubuntu/workspace/tesseract/arch'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2 -DNDEBUG -I../ccutil  -I/usr/local/include/leptonica -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include   -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -mavx -g -O2 -std=c++11 -MT libtesseract_avx_la-dotproductavx.lo -MD -MP -MF .deps/libtesseract_avx_la-dotproductavx.Tpo -c -o libtesseract_avx_la-dotproductavx.lo `test -f 'dotproductavx.cpp' || echo './'`dotproductavx.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I/usr/local/include/leptonica -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -mavx -g -O2 -std=c++11 -MT libtesseract_avx_la-dotproductavx.lo -MD -MP -MF .deps/libtesseract_avx_la-dotproductavx.Tpo -c dotproductavx.cpp  -fPIC -DPIC -o .libs/libtesseract_avx_la-dotproductavx.o
g++: error: unrecognized command line option '-mavx'
make[3]: *** [libtesseract_avx_la-dotproductavx.lo] Error 1
make[3]: Leaving directory `/home/ubuntu/workspace/tesseract/arch'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/ubuntu/workspace/tesseract/arch'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/workspace/tesseract'
make: *** [all] Error 2

ubuntu@tegra-ubuntu:~/workspace/tesseract$ cd arch/
ubuntu@tegra-ubuntu:~/workspace/tesseract/arch$ less Makefile

noinst_HEADERS =
noinst_LTLIBRARIES = libtesseract_avx.la libtesseract_sse.la
#lib_LTLIBRARIES = libtesseract_avx.la libtesseract_sse.la
#libtesseract_avx_la_LDFLAGS = -version-info $(GENERIC_LIBRARY_VERSION)
#libtesseract_sse_la_LDFLAGS = -version-info $(GENERIC_LIBRARY_VERSION)
libtesseract_avx_la_CXXFLAGS = **-mavx**
libtesseract_sse_la_CXXFLAGS = -msse4.1
libtesseract_avx_la_SOURCES = dotproductavx.cpp
libtesseract_sse_la_SOURCES = dotproductsse.cpp
all: all-recursive

**Comment by stweil** [comment]
`-mavx` requires a sufficiently new `gcc` compiler. The build tools should check whether it works. For now, simply remove that option in your local configuration (or update your software).

**Comment by amitdo** [comment]
>-mavx requires a sufficiently new gcc compiler. The build tools should check whether it works. For now, 

mavx is supported since gcc 4.4. released in April 21, 2009.
https://gcc.gnu.org/gcc-4.4/changes.html
https://gcc.gnu.org/releases.html

He said he his system is Ubuntu 14.04.
http://packages.ubuntu.com/search?keywords=g%2B%2B

>uname -m = armv7l

AVX is only supported on x86. ARM SIMD is called NEON.
Tesseract has no support for NEON.

https://github.com/tesseract-ocr/tesseract/wiki/NeuralNetsInTesseract4.00#for-open-source-contributors
>There is a C++ implementation if the hardware does not have SSE and/or AVX, but the code could benefit from SIMD implementations for other hardware, such as ARM. See the new arch directory for where to insert the code.

**Comment by amitdo** [comment]
I believe this issue was fixed.

Neon still not supported, but Tesseract should work on ARM.
