### ISSUE TITLE
error LNK2019: unresolved external symbol __imp__l_CIDataDestroy referenced in function - libtesseract304

### ISSUE THREAD

**Issue by kasiselvamk** [tesseract-ocr/tesseract#50]
hi Team ,
      we can't able to figure it out ,why we are getting this below error while linking. but, it compiles fine.;

version's : tesseract304 , leptonica-1.72, liblept168d.lib + other libs (got it from leptonica-1.68-win32-lib-include-dirs.zip ), visual studio 2010.

plz help us to resolve this issue..plz...

Error details :-
Error	1	error LNK2019: unresolved external symbol __imp__l_CIDataDestroy referenced in function "private: static bool __cdecl tesseract::TessPDFRenderer::imageToPDFObj(struct Pix *,char *,long,char * *,long *)" (?imageToPDFObj@TessPDFRenderer@tesseract@@CA_NPAUPix@@PADJPAPADPAJ@Z)	D:\tesseract-master\vs2010\libtesseract\pdfrenderer.obj	libtesseract304
Error	2	error LNK2019: unresolved external symbol __imp__l_generateCIDataForPdf referenced in function "private: static bool __cdecl tesseract::TessPDFRenderer::imageToPDFObj(struct Pix *,char *,long,char * *,long *)" (?imageToPDFObj@TessPDFRenderer@tesseract@@CA_NPAUPix@@PADJPAPADPAJ@Z)	D:\tesseract-master\vs2010\libtesseract\pdfrenderer.obj	libtesseract304
Error	3	error LNK2019: unresolved external symbol __imp__pixGenerateCIData referenced in function "private: static bool __cdecl tesseract::TessPDFRenderer::imageToPDFObj(struct Pix *,char *,long,char * *,long *)" (?imageToPDFObj@TessPDFRenderer@tesseract@@CA_NPAUPix@@PADJPAPADPAJ@Z)	D:\tesseract-master\vs2010\libtesseract\pdfrenderer.obj	libtesseract304
Error	4	error LNK2019: unresolved external symbol __imp__pixSetSpp referenced in function "private: static bool __cdecl tesseract::TessPDFRenderer::imageToPDFObj(struct Pix *,char *,long,char * *,long *)" (?imageToPDFObj@TessPDFRenderer@tesseract@@CA_NPAUPix@@PADJPAPADPAJ@Z)	D:\tesseract-master\vs2010\libtesseract\pdfrenderer.obj	libtesseract304
Error	5	error LNK2019: unresolved external symbol __imp__pixGetSpp referenced in function "private: static bool __cdecl tesseract::TessPDFRenderer::imageToPDFObj(struct Pix *,char *,long,char * *,long *)" (?imageToPDFObj@TessPDFRenderer@tesseract@@CA_NPAUPix@@PADJPAPADPAJ@Z)	D:\tesseract-master\vs2010\libtesseract\pdfrenderer.obj	libtesseract304
Error	6	error LNK2019: unresolved external symbol __imp__pixForegroundFraction referenced in function "protected: float __thiscall tesseract::EquationDetect::ComputeForegroundDensity(class TBOX const &)" (?ComputeForegroundDensity@EquationDetect@tesseract@@IAEMABVTBOX@@@Z)	D:\tesseract-master\vs2010\libtesseract\equationdetect.obj	libtesseract304
Error	7	error LNK2019: unresolved external symbol __imp__pixaConvertToPdf referenced in function "public: static void __cdecl tesseract::LineFinder::FindAndRemoveLines(int,bool,struct Pix *,int *,int *,struct Pix * *,class tesseract::TabVector_LIST *,class tesseract::TabVector_LIST *)" (?FindAndRemoveLines@LineFinder@tesseract@@SAXH_NPAUPix@@PAH2PAPAU3@PAVTabVector_LIST@2@4@Z)	D:\tesseract-master\vs2010\libtesseract\linefind.obj	libtesseract304
Error	8	error LNK1120: 7 unresolved externals	D:\tesseract-master\vs2010\DLL_Debug\libtesseract304d.dll	libtesseract304

**Comment by zdenop** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advises
