### ISSUE TITLE
Add vcpkg port

### ISSUE THREAD

**Issue by sdcb** [tesseract-ocr/tesseract#500]
Vcpkg is a tool to acquire and build C++ open source libraries on Windows:
https://blogs.msdn.microsoft.com/vcblog/2016/09/19/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/

Provide a vcpkg port for tesseract would be very convenience.

**Comment by egorpugin** [comment]
You could use https://cppan.org/ also. It's already present in repository.

**Comment by amitdo** [comment]
Egor,
It you would like to add support for Leptonica and Tesseract to the Microsoft vcpkg ports collection:
https://github.com/Microsoft/vcpkg/blob/master/CONTRIBUTING.md

**Comment by egorpugin** [comment]
I won't be adding vcpkg port. If someone else need this, please do it.

**Comment by amitdo** [comment]
@sdcb
You might want to add a request to add Tesseract:
https://github.com/Microsoft/vcpkg/issues?q=is%3Aissue+label%3A%22new+port+request%22+is%3Aopen

**Comment by amitdo** [comment]
@zdenop, please close this issue.

**Comment by amitdo** [comment]
https://github.com/Microsoft/vcpkg/tree/master/ports/tesseract
