### ISSUE TITLE
OCR runtime error -  Attempted to read or write protected memory.

### ISSUE THREAD

**Issue by Ivanzo1987** [tesseract-ocr/tesseract#513]
I'm trying OCR sample for C#, when I try with spanish language a runtime error occurs.
{"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."}

Code:
```
public OCRForm()
      {
         InitializeComponent();
         InitOcr(@"", "spa", OcrEngineMode.TesseractCubeCombined);
        
      }
private void InitOcr(String path, String lang, OcrEngineMode mode)
      {         
         try
         {
            if (_ocr != null)
            {
               _ocr.Dispose();
               _ocr = null;
            }
            _ocr = new Tesseract(path, lang, mode);
            languageNameLabel.Text = String.Format("{0} : {1}", lang, mode.ToString());
         }
         catch (Exception e)
         {
            _ocr = null;
            MessageBox.Show(e.Message, "Failed to initialize tesseract OCR engine", MessageBoxButtons.OK);
            languageNameLabel.Text = "Failed to initialize tesseract OCR engine";
         }
      }
```

**Comment by amitdo** [comment]
[Guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md)

Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).

**Comment by stweil** [comment]
@Ivanzo1987, if the same runtime error also occurs with the original Tesseract executable, then reporting that as an issue would be correct. In this case we'd need additional information (Tesseract version, platform, command line used, copy of image).

**Comment by Ivanzo1987** [comment]
Emgu Version 3.1


________________________________
De: Stefan Weil <notifications@github.com>
Enviado: miércoles, 30 de noviembre de 2016 16:47
Para: tesseract-ocr/tesseract
Cc: Ivanzo1987; Mention
Asunto: Re: [tesseract-ocr/tesseract] OCR runtime error - Attempted to read or write protected memory. (#513)


@Ivanzo1987<https://github.com/Ivanzo1987>, if the same runtime error also occurs with the original Tesseract executable, then reporting that as an issue would be correct. In this case we'd need additional information (Tesseract version, platform, command line used, copy of image).

-

**Comment by stweil** [comment]
Emgu is third party software, not the original Tesseract, so you will have to discuss or report any issue there.

**Comment by Ivanzo1987** [comment]
Ok, where I can download tesseract OCR for C# ??


________________________________
De: Stefan Weil <notifications@github.com>
Enviado: miércoles, 30 de noviembre de 2016 17:11
Para: tesseract-ocr/tesseract
Cc: Ivanzo1987; Mention
Asunto: Re: [tesseract-ocr/tesseract] OCR runtime error - Attempted to read or write protected memory. (#513)


Emgu is third party software, not the original Tesseract, so you will have to discuss or report any issue there.

-

**Comment by stweil** [comment]
Tesseract is written in C++ (not C#). The [Tesseract wiki](https://github.com/tesseract-ocr/tesseract/wiki/Downloads) has hints where you can get a binary installation.

**Comment by Ivanzo1987** [comment]
Ok, I will try it, thanks


________________________________
De: Stefan Weil <notifications@github.com>
Enviado: miércoles, 30 de noviembre de 2016 17:24
Para: tesseract-ocr/tesseract
Cc: Ivanzo1987; Mention
Asunto: Re: [tesseract-ocr/tesseract] OCR runtime error - Attempted to read or write protected memory. (#513)


Tesseract is written in C++ (not C#). The Tesseract wiki<https://github.com/tesseract-ocr/tesseract/wiki/Downloads> has hints where you can get a binary installation.

-
