### ISSUE TITLE
LSTM: Warnings on console when using -oem 4 on command line on windows

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#522]
While using png files as input and using oem 4 - LSTM, tesseract gives warnings on console in command mode. oem 0, 1, 2 and 3 gives no warnings.

On Windows 10, using 4.0 Alpha binaries provided by @stweil  and 4.0 alpha traineddata 

>>tesseract hin001.png hin001-hin-3 -oem 3 -l hin
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica

>>tesseract hin001.png hin001-hin-4 -oem 4 -l hin
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
...

The warnings seem to be given per line, so a page with 20 lines of text gets about 40 lines of messages.

I have not tested this in the linux environment. The warnings are probably from leptonica.

**Comment by zdenop** [comment]
What is an issue?

**Comment by Shreeshrii** [comment]
There are a large number of warning messages when using -oem 4, not with other oem modes.

Is there a way to eliminate these? 

C:\shree>tesseract san001.png san001 -oem 4 -l san
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Detected 18 diacritics
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file
Warning in pixWriteMemPng: work-around: writing to a temp file
Warning in fopenReadFromMemory: work-around: writing to a temp file



![san001](https://cloud.githubusercontent.com/assets/5095331/20835038/62d4e128-b8be-11e6-8d49-4ee9f2077b47.png)

**Comment by amitdo** [comment]
The warnings are indeed from Leptonica. They will not appear in Linux. You should ignore these ugly warnings.

>Is there a way to eliminate these?

https://github.com/tesseract-ocr/tesseract/issues/292#issuecomment-222529057

**Comment by Shreeshrii** [comment]
Warnings are not limited to png, same for tif, gif and jpg.

**Comment by zdenop** [comment]
1. use tesseract user forum for asking question.
2. this is more leptonica build problem (allowed warnings)
3.  Did you tried https://github.com/tesseract-ocr/tesseract/wiki/FAQ#how-can-i-suppress-tesseract-info-line?

**Comment by zdenop** [comment]
> They will not appear in Linux. 
Because that problem is related to windows...

**Comment by Shreeshrii** [comment]
@zdenop @amitdo Thanks!

@stweil Is the version of leptonica included with the windows binaries a debug version?

**Comment by amitdo** [comment]
>Warnings are not limited to png, same for tif, gif and jpg.

Still same answer...

It not a bug, although from a end user point of view it sure looks confusing.

**Comment by stweil** [comment]
The warnings are an indicator for potential optimizations and require more examination by developers, so I see there an issue to be discussed here.

AFAIK Leptonica warns when an image file is going to be mapped to memory, something that is unsupported for Leptonica's Windows code which uses a temporary file copy as an alternative.

If OCR of a single image results in many (number of lines) of those warnings, that might be caused by the same image being opened very often, or Tesseract acts on in-memory line images, but Leptonica for Windows has to write those images to disk. Then it is clear that at least for Windows the performance suffers and something should be done - either in Leptonica code or in Tesseract.

**Comment by stweil** [comment]
> Is the version of leptonica included with the windows binaries a debug version?

No, it is production code. Such warnings also occurr(ed) with Tesseract 3.05 and earlier, for example when processing JPEG 2000 images (but only once per image). Some improvements in newer Leptonica code reduced the cases where this kind of warnings are shown.

**Comment by Shreeshrii** [comment]
++ dan.bloomberg@gmail.com

cc:ing Dan Bloomberg for his input regarding Leptonica

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment]
@stweil
#292 (comment)
How did you compile Leptonica?

**Comment by amitdo** [comment]
http://www.leptonica.org/source/README.html

>4. Compile-time control over stderr output (see environ.h)
>
>   Leptonica provides both compile-time and run-time control over
   messages and debug output (thanks to Dave Bryan).  Both compile-time
   and run-time severity thresholds can be set.  The run-time threshold
   can also be set by an environmental variable.  Messages are
   vararg-formatted and of 3 types: error, warning, informational.
   These are all macros, and can be further suppressed when
   NO_CONSOLE_IO is defined on the compile line.  For production code
   where no output is to go to stderr, compile with -DNO_CONSOLE_IO.

**Comment by amitdo** [comment]
https://github.com/DanBloomberg/leptonica/blob/7e0191abd/src/environ.h#L290

**Comment by amitdo** [comment]
It not a bug, but I agree that there is a place for improvements.

**Comment by stweil** [comment]
> How did you compile Leptonica?

Basically I used `./configure: make; make install`, but in a cross build on Debian GNU Linux.

**Comment by DanBloomberg** [comment]
In production, there should be no need to see any leptonica output (info, warnings, errors) to stderr.
Methods for suppressing them are described above by Amit.
These messages are arguably INFO rather than WARNING.

Writes to file for in-memory I/O on Windows are no longer required for gif and tiff formats. They were never required for webp.  They are still required for jpeg, jp2k and png.

**Comment by amitdo** [comment]
Dan,
Thanks for the info.

>Reads and writes from/to file for in-memory I/O on Windows are no longer required for gif and tiff formats.

Since which version?

The solution to the optimization problem might be in this specific case to always save the textlines images to tiff in memory.

**Comment by stweil** [comment]
Technically, the warnings occur on any platform which does not have a `fmemopen` function. Leptonica outputs them using a macro `L_WARNING`. It is possible to call `setMsgSeverity` from Tesseract code to disable any warning message from Leptonica (I don't think that would be a good idea).

**Comment by DanBloomberg** [comment]
Amit,

1.73 required r/w for in-memory I/O for gif and tiff on Windows. The current github master (and soon to be release 1.74.0) does not.  The tiff patch was contributed by Stefan.

Yes, any 1 bpp images (e.g., in tesseract/viewer and ccstruct) can be output in IFF_TIFF_G4, which typically has better compression than png.  Grayscale and color can be output in TIFF_ZIP or TIFF_LZW, which are typically inferior to png in compression.

**Comment by DanBloomberg** [comment]
Stefan, we can downgrade those messages in leptonica to INFO, and you can use setMsgSeverity() to disable INFO statements.

**Comment by stweil** [comment]
That would be possible, yes. But without those nagging messages, I'd never have had a look on that part of Leptonica.

**Comment by DanBloomberg** [comment]
Nevertheless, this seems like a reasonable thing to do to solve this annoyance and still present other WARNING messages.

**Comment by DanBloomberg** [comment]
Annoying messages have now been downgraded to INFO at github head.

You can use this in tesseract code to suppress all INFO and less urgent messages at run time:
     setMsgSeverity(L_SEVERITY_WARNING);

Alternatively, for a bit more flexibility, you can define the environmental variable
 #define  LEPT_MSG_SEVERITY   L_SEVERITY_WARNING
and use
     setMsgSeverity(L_SEVERITY_EXTERNAL);

You can also change the severity level to WARNING and higher at compile time with this compiler flag:
    -DDEFAULT_SEVERITY=4
This can be over-ridden at run time with either of the first two methods.

**Comment by amitdo** [comment]
>Reads and writes from/to file for in-memory I/O on Windows are no longer required for gif and tiff formats.

I wonder how giflib and libiff do the equivalence of fmemopen on Windows.

**Comment by zdenop** [comment]
@DanBloomberg : Thanks for support. Maybe it would be good to enable all warning for debug builds and hide them for release builds.

**Comment by DanBloomberg** [comment]
@zdenop  That's an interesting idea.  Default setting is for INFO, WARNING and ERROR, but for a release that will be used in production it makes sense to only show ERROR.

**Comment by DanBloomberg** [comment]
@amitdo 

Look at the leptonica wrappers for tiff (tiffio.c) and gif (gifio.c) to see how it is done.

Even better, the webp library implements compression and decompression directly with memory buffers, not with file streams. This is very nice, because it's platform independent, and you can easily read and write to files using it (see webpio.c). I wish the other image compression libraries had been implemented that way, but ...
