### ISSUE TITLE
LSTM: missing config file lstm.train

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#526]
[Sat Dec 3 15:06:31 DST 2016] /usr/local/bin/tesseract /tmp/tmp.6Fy6JZCueq/eng/eng.Verdana_Italic.exp0.tif /tmp/tmp.6Fy6JZCueq/eng/eng.Verdana_Italic.exp0 lstm.train
read_params_file: Can't open lstm.train

https://github.com/tesseract-ocr/tesseract/tree/master/tessdata/configs
does not have the file lstm.train in it

**Comment by amitdo** [comment]
Fixed in 65517794f9bb

**Comment by theraysmith** [comment]
Fixed in https://github.com/tesseract-ocr/tesseract/commit/65517794f9bbc41a202d1fe410ff269f00257e57
