### ISSUE TITLE
which versions of leptonica are being enforced; release version vs. SO version

### ISSUE THREAD

**Issue by DanBloomberg** [tesseract-ocr/tesseract#540]
We're in the process of updating leptonica to version 1.74.0.

This will go out with debian with SO version 5.1.0.

I see in CMakeLists.txt:
   set(MINIMUM_LEPTONICA_VERSION 1.71)

Two questions:
(1) Should this be increased?  1.71 is at least 2 years old, likely still binary compatible.

(2) With autotools, the SO version defines the binary interface compatibility, which is why we're bumping it up from 5.0.0 in 1.73 to 5.1.0 in 1.74.  Does cmake use the SO version?

**Comment by Shreeshrii** [comment]
Also see https://github.com/tesseract-ocr/tesseract/issues/536

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/Compiling
Ray added the 1.73 requirement for 4.0.

There is pending patch from Jeff that will need 1.74.
https://github.com/tesseract-ocr/tesseract/issues/233#issuecomment-246744997

Anyway, the two build system should be updated.

**Comment by jbreiden** [comment]
Not 100% sure, but I think I already have a requirement on 1.73 to support PDF generation.

**Comment by amitdo** [comment]
Since commit 11f205707 we depend on 1.74.0

**Comment by jbreiden** [comment]
That is pretty aggressive. Hope the multipage TIFF users appreciate it.

**Comment by amitdo** [comment]
If you want to support 1.73 you can provide a patch... :-)

**Comment by amitdo** [comment]
I mean, the code will still use your patch for 1.74 but will fallback to the previous behaviour for 1.73.

**Comment by DanBloomberg** [comment]
I thought that with 1.74, and SO 5.1, there is no longer a need for that tiff patch on debian.

btw, github release 1.74.0 is now also up as 1.74 (in the usual configure-make tarball) on leptonica.org:
     leptonica.org/source/leptonica-1.74.tar.gz

**Comment by amitdo** [comment]
Jeff,
Any chance you will provide a Leptonica 1.74 PPA for Ubuntu 16.04?

**Comment by jbreiden** [comment]
1.73 has O (n^3) for seeks on multi page TIFF. 1.74 drops that to O(n^2)
for the existing API and O(n) for some new API calls.

I have never made a PPA before and am not sure what is involved. Priority
is official Leptonica packaging. Unclear if l will even get that far before
the new year, due to travel.

So the answer is maybe, but I wasn't planning on it, and certainly not
right now.

**Comment by amitdo** [comment]
OK, I thought that you are familiar with PPAs. I didn't mean to push you to prepare a PPA.

**Comment by amitdo** [comment]
Jeff made a Leponica 1.74.1 package for Debian:
https://packages.debian.org/sid/libleptonica-dev

**Comment by amitdo** [comment]
Unofficial Ubuntu PPAs:
https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr

**Comment by stweil** [comment]
There are still numerous platforms without prebuild Leptonica 1.74.x. I just suggested updating the version for [MacPorts](https://github.com/macports/macports-ports/pull/180). Maybe fallback code which is slower for multi page tiffs but which works with older Leptonica versions would really be a good idea.

**Comment by jbreiden** [comment]
I'm totally fine with any decision, including reverting the new TIFF calls until Leptonica 1.74  is more widespread. This was the changelist.

https://github.com/tesseract-ocr/tesseract/commit/245eebdf293ac19f1fb85c36e51daaaa1b5e5a3e

**Comment by amitdo** [comment]
Current CMakeLists.txt:

>set(MINIMUM_LEPTONICA_VERSION 1.74)

**Comment by amitdo** [comment]
This issue can be closed.
