### ISSUE TITLE
Failed loading language 'eng'

### ISSUE THREAD

**Issue by Omnipresent** [tesseract-ocr/tesseract#541]
I am getting this error while trying to run tesseract 

    root@bbf7a623fb77:/tesseract-3.0/bin# ./tesseract sample1.jpg cat
    Tesseract Open Source OCR Engine v3.04.00 with Leptonica
    Failed loading language 'eng'
    Tesseract couldn't load any languages!
    Could not initialize tesseract.

I know this question has been asked before but my question is different in that I am installing tesseract in a different location and actually have the `eng.traineddata` files in the paths but tesseract can't seem to pick them up. 

This is how I install tesseract:

    $ ./autogen.sh
    $ mkdir /tesseract-3.0
    $ LIBLEPT_HEADERSDIR=/leptonica-1.71/include/ \
      ./configure --prefix=/tesseract-3.0/  \
      --with-extra-libraries=/leptonica-1.71/lib/ 
    $ make -j2
    $ make install

My `eng.traineddata` files are here:

    root@bbf7a623fb77:/tesseract-3.0# ls -al /tesseract-3.0/share/tessdata/
    total 2204
    drwxr-xr-x 4 root root    4096 Dec  7 01:53 .
    drwxr-xr-x 4 root root    4096 Dec  7 01:46 ..
    drwxr-xr-x 2 root root    4096 Dec  7 01:46 configs
    -rw-r--r-- 1 root root 1957934 Dec  7 01:52 eng.cube.bigrams
    -rw-r--r-- 1 root root   34068 Dec  7 01:52 eng.cube.fold
    -rw-r--r-- 1 root root   33325 Dec  7 01:52 eng.cube.lm
    -rw-r--r-- 1 root root   31811 Dec  7 01:52 eng.cube.nn
    -rw-r--r-- 1 root root   34662 Dec  7 01:53 eng.cube.params
    -rw-r--r-- 1 root root   31928 Dec  7 01:53 eng.cube.size
    -rw-r--r-- 1 root root   31984 Dec  7 01:53 eng.cube.word-freq
    -rw-r--r-- 1 root root   31924 Dec  7 01:53 eng.tesseract_cube.nn
    -rw-r--r-- 1 root root   31950 Dec  7 01:53 eng.traineddata
    -rw-r--r-- 1 root root     568 Dec  7 01:46 pdf.ttf
    drwxr-xr-x 2 root root    4096 Dec  7 01:46 tessconfigs

I've even set the `TESSDATA_PREFIX` environment variable

    root@bbf7a623fb77:/tesseract-3.0# echo $TESSDATA_PREFIX
    /tesseract-3.0/share

My reason for installing tesseract in path other than `/usr/local` is that I'll be transferring the pre-compiled libraries to another machine on which I do not have access to install in `/usr/local`

**Comment by Shreeshrii** [comment]
Your tessdata prefix should be

TESSDATA_PREFIX /tesseract-3.0/share

Not

TESSDATA_PREFIX /tesseract-3.0/share/tessdata

It is the prefix before tessdata directory.

**Comment by amitdo** [comment]
The right place to ask this kind of question is [our forum](https://groups.google.com/d/forum/tesseract-ocr).

**Comment by danielsnider** [comment]
BTW, the traineddata file that finally worked for me is from:
https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata

On Ubuntu 16.04 I put it here `/usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata`.

This fixes the error:
```
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
```
