### ISSUE TITLE
Add Devanagari-extended and Vedic extensions to Devanagari.unicharset

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#545]
http://www.alanwood.net/unicode/devanagari-extended.html
http://www.alanwood.net/unicode/vedic-extensions.html

Sample image which uses some of these characters is attached.

Or at a minimum add support for U+0951, U+0952, U+A8F3, U+1CDA 

![swarankit](https://cloud.githubusercontent.com/assets/5095331/21003508/b913fb04-bd51-11e6-88c1-bc402c36e5c4.png)

**Comment by zdenop** [comment]
This report should be in tessdata or langdata  repository
