### ISSUE TITLE
LSTM: Training - Error msg - No block overlapping textline:

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#546]
```
Loaded 1059/1059 pages (0-1059) of document /tmp/tmp.HeGbXAKgjI/san/san.Santipur_OT_Medium.exp0.lstmf
Error in pixaGetCount: pixa not defined
Error in pixaGetCount: pixa not defined
Bad box coordinates in boxfile string! दि ['ए\\^', 25 सर्व 341 2126 768 2194 44
Loaded 885/885 pages (0-885) of document /tmp/tmp.HeGbXAKgjI/san/san.Uttara.exp0.lstmf
No block overlapping textline: तत्पश्चात् इहैव समरे सौख्यं
No block overlapping textline: द्वाभ्यां न क्षुत्पिपासे अद्यापि
No block overlapping textline: अङ्के तु तस्मै (चेटीं विद्यन्ते
No block overlapping textline: इंचमितो दिने केन कल्कितम् पूजा
Page 31
Page 34
Error in pixaGetCount: pixa not defined
Error in pixaGetCount: pixa not defined
Error in pixaGetCount: pixa not defined
Error in pixaGetCount: pixa not defined
Loaded 914/914 pages (0-914) of document /tmp/tmp.HeGbXAKgjI/san/san.Uttara.exp0.lstmf
Loaded 1096/1096 pages (0-1096) of document /tmp/tmp.HeGbXAKgjI/san/san.Santipur_OT_Medium.exp0.lstmf
Bad box coordinates in boxfile string! दि ['ए\\^', 25 सर्व 341 2126 768 2194 44
Page 35

```

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/5deebe6c279f70215935c1f86baa7e7016c7f2a7/ccmain/linerec.cpp#L115

**Comment by amitdo** [comment]
>Error in pixaGetCount: pixa not defined

https://github.com/DanBloomberg/leptonica/issues/223

**Comment by Shreeshrii** [comment]
```
Page 3
Loaded 13/13 pages (1-13) of document /tmp/tmp.jX9oLgyrCZ/ara/ara.Traditional_Arabic.exp0.lstmf
No block overlapping textline: سُانَّلا
No block overlapping textline: لَعَجَ يذِلَّا نَوقُتَّتَ مْكُلَّعَلَ مْكُلِبْقَ نْمِ نَيذِلَّاوَ مْكُقَلَخَ يذِلَّا مُكُبَّرَ اودُبُعْا
No block overlapping textline: ىلَعَ انَلْزَّنَ امِمَّ بٍيْرَ فِي مْتُنْكُ نْإِوَ نَومُلَعْتَ مْتُنْأَوَ ادًادَنْأَ لِلَّهِ اولُعَتَجْ لَافَ مْكُلَ
No block overlapping textline: نَادِبْعَ
No block overlapping textline: ينَقِدِاصَ مْتُنْكُ نْإِ للَّهِا نِودُ نْمِ مْكُءَادَهَشُ اوعُدْاوَ هِلِثْمِ نْمِ ةٍرَوسُبِ اوتُأْفَ
No block overlapping textline: نَيرِفِاكَلْلِ
No block overlapping textline: اهَتِتَحْ نْمِ يرِتَجْ تٍانَّجَ مْلَهُ نَّأَ تِالِحَاصَّلا اولُمِعَوَ اونُمَآ نَيذِلَّا رِشِّبَوَ
No block overlapping textline: امَلَّكُ رُاهَنْلْأَا
No block overlapping textline: مْلَهُوَ
No block overlapping textline: لًاثَمَ بَرِضْيَ نْأَ ييِحْتَسْيَ لَا للَّهَا نَّإِ نَودُلِاخَ اهَيفِ مْهُوَ ةٌرَهَّطَمُ جٌاوَزْأَ اهَيفِ
No block overlapping textline: امَ
No block overlapping textline: امَّأَوَ مْبِّهِرَ نْمِ قُّلْحَا هُنَّأَ نَومُلَعْيَفَ اونُمَآ نَيذِلَّا امَّأَفَ اهَقَوْفَ امَفَ ةًضَوعُبَ
No block overlapping textline: نَيذِلَّا
Page 4

```

**Comment by Shreeshrii** [comment]
The number of errors reduced to a couple 
```

Page 5
Loaded 75/75 pages (1-75) of document /tmp/tmp.ZhCBJPqjME/ara/ara.Traditional_Arabic.exp0.lstmf
No block overlapping textline: _
No block overlapping textline: :: ."
 
```
after adding the following to ara.config

`textord_min_linesize 2.5
`

**Comment by theraysmith** [comment]
pixaGetCount errors fixed.
For no block overlapping textline, see new section in training tesseract 4.00.

**Comment by ibr123** [comment]
i got the same message for Japanese which is:
No block overlapping textline: 俄然屁、30観光銚 差 塞翁が馬ランチに的配達硬翌月 -ふ陜西 脛骨 智
yet i was able to create LSTM files for the fonts that i specified, i think the LSTM are OK because i noticed in this [issue](https://github.com/DanBloomberg/leptonica/issues/223) the user zdenop said 

> If there is error message I expect something serious is happening. But nothing bad has happened. There is expected output. This will confuse end-users (current version of tesseract hides leptonica warnings, but this error message is there...)
so are the LSTM files are not defected although the error message was shown?
MOTE, im using tesseract 4.00.00alpha with leptonica 1.74.1

**Comment by Shreeshrii** [comment]
As mentioned by Ray in the comment above, please see https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#error-messages-from-training

>**No block overlapping textline:** occurs when layout analysis fails to correctly segment the image that was given as training data. The textline is dropped. Not much problem if there aren't many, but if there are a lot, there is probably something wrong with the training text or rendering process.
