### ISSUE TITLE
List variables / languages via API

### ISSUE THREAD

**Issue by jeroenooms** [tesseract-ocr/tesseract#547]
Is it possible to add to the [APIexample](https://github.com/tesseract-ocr/tesseract/wiki/APIExample) wiki on how to accomplish the equivalent of `tesseract --list-langs` and `tesseract --print-parameters` via the API?

## list langs

To list languages I currently use something like the following. However the problem is that I first need to initialize the english engine which might not be available. Is there a way to list languages without initializing any engine?

```cpp
  tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
  if (api->Init(NULL, "eng"))
    throw std::runtime_error(std::string("Unable to find training data for"));
  api->GetAvailableLanguagesAsVector(langs);
  std::vector<std::string> available;
  for(int i = 0; i < langs->length(); i++)
    available.push_back(langs->get(i).c_str());
```

## list parameters

The only method I can find in the base API to list supported parameters is:

```cpp
api->PrintVariables(stdout);
```

However this prints a text dump which is difficult to read by machines. Is there an api to iterate over the supported variables strings and stick them into a `std::vector<std::string>`?

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support.

**Comment by amitdo** [comment]
>list parameters
>
>The only method I can find in the base API to list supported parameters is:
However this prints a text dump which is difficult to read by machines. Is there an api to iterate over the supported variables strings and stick them into a std::vector<std::string>?

I don't think there is a method in the API for that.
but if someone will send a PR ...

**Comment by amitdo** [comment]
I see that you made a [R binding for Tessaract](https://github.com/ropensci/tesseract)
You might want to add a link to it from [AddOns](https://github.com/tesseract-ocr/tesseract/wiki/AddOns#tesseract-wrappers)
