### ISSUE TITLE
Tesseract security considerations

### ISSUE THREAD

**Issue by joshimar** [tesseract-ocr/tesseract#548]
I am integrating Tesseract into an application, but I have some questions before keep going with the process.
I think every application should have security filters and considerations in order to avoid malicious and bad input data, so my questions are:

1. Does Tesseract have special code to handle bad or malicious input data? 
2. Or just have a few validations to tell the user the correct input data?
3. Releases are performed after doing some security reviews and testing?
4. Or just functional testing?

I will appreciate your answers.
Thanks a lot!

**Comment by zdenop** [comment]
Posted on 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/bVq_mGnPsN4/LqYyZg1ICQAJ
