### ISSUE TITLE
LSTM: Tutorial - Recognition model output instructions

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#550]
As per https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#combining-the-output-files

```
Either of these files can be converted to a recognition model as follows:

training/lstmtraining --model_output ~/tesstutorial/eng_from_chi/eng.lstm \
  --continue_from ~/tesstutorial/eng_from_chi/base_checkpoint

Finally, combine your new model with the language model files into a traineddata file:

training/combine_tessdata -o tessdata/eng.traineddata \
  ~/tesstutorial/eng_from_chi/eng.lstm \
  ~/tesstutorial/engtrain/eng.lstm-number-dawg \
  ~/tesstutorial/engtrain/eng.lstm-punc-dawg \
  ~/tesstutorial/engtrain/eng.lstm-word-dawg

The dawg files are optional. It will work without them, but they do usually provide some small improvement in accuracy.

NOTE  The unicharset used for the lstm has to match the unicharset used to generate the lstm-*-dawg files, but doesn't have to match the unicharset for the inttemp and base tesseract dawg files.

```
1. The given command does not create the recognition model. For that the command has to be appended with --stop_training.

```
training/lstmtraining --model_output ~/tesstutorial/sanskrit2003_from_full/san.lstm \
  --continue_from ~/tesstutorial/sanskrit2003_from_full/sanskrit2003_checkpoint \
  --stop_training
 ```

@theraysmith  Please review whether the modified commands are ok. thanks.

Wiki page needs to be updated for it.

**Comment by Shreeshrii** [comment]
See Ray's comment re unicharset in https://github.com/tesseract-ocr/tesseract/issues/527

The unicharset from LSTM Training is included within the .LSTM model file. 

However this means that the old versions of dawg2wordlist cannot be used with the LSTM daag files to get the original lists.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00---Finetune

**Comment by Shreeshrii** [comment]
Also see comments for https://github.com/tesseract-ocr/tesseract/issues/634

for LSTM training we should use both of these during first step of training - creating lstmf files.

--linedata_only --noextract_font_properties

**Comment by theraysmith** [comment]
Edits made. Filed question over unicharset extraction as a separate issue (https://github.com/tesseract-ocr/tesseract/issues/653)
