### ISSUE TITLE
tesseract training tools under msys2/mingw64 don't build

### ISSUE THREAD

**Issue by djusHa** [tesseract-ocr/tesseract#562]
Hi,

building training tools in current master branch under MSYS2/mingw64 throws following Error:
...x86_64-w64-mingw32/bin/ld.exe: cannot find -licui18n

It seems the lib is named differently.

My quick Solution is to change libicu in training/Makefile like so:
sed -i 's/^libicu = -licui18n -licuuc/libicu = -licuin -licuuc/' training/Makefile

Then it's building fine.

Thanks for your awesome Work.

**Comment by zdenop** [comment]
Can you try revert this https://github.com/tesseract-ocr/tesseract/commit/7755e05e506ea7a31ff50dd7a8b86dfd885c639c ?

**Comment by stweil** [comment]
Current Mingw-w64 as included in Cygwin includes these libraries in package `mingw64-x86_64-icu`:  libicudata.dll.a  libicui18n.dll.a  libicuio.dll.a  libicule.dll.a  libiculx.dll.a  libicutest.dll.a  libicutu.dll.a  libicuuc.dll.a, so that should work. Which version of Mingw-w64 did you use?

**Comment by stweil** [comment]
@zdenop, reverting that commit will work with old versions of icu. We don't support them for Linux, and for Windows there are also newer versions available. If support for both old and new versions is required, we need a test in configure.

**Comment by djusHa** [comment]
@stweil 
where can i see the version of mingw-w64?

Ouput from mingw64 console:
$ uname -rv
2.6.0(0.304/5/3) 2016-09-07 20:45

My Host is Windows 7 x64, MSYS2 is installed a few days ago, must be pretty up to date.

**Comment by stweil** [comment]
If you use MSYS / MinGW from http://www.mingw.org/, then even the latest installation is old. :-(
That packages are not suitable for builds of Tesseract (old libraries, old compiler, only 32 bit). Don't use them for Tesseract 4.

Use Mingw-w64 from https://mingw-w64.org/ or install Cygwin from https://cygwin.com/ with the mingw64-* packages. Both solutions allow building 32 or 64 bit Tesseract for Windows.

**Comment by djusHa** [comment]
I'm using MSYS2 Installer from https://msys2.github.io/
Have no Problems to compile other Linux Packages...

**Comment by stweil** [comment]
I'll have a look tomorrow. Good night for today.

**Comment by djusHa** [comment]
ok, good night.

**Comment by stweil** [comment]
msys2.github.io provides a recent package `mingw64/mingw-w64-x86_64-icu` 57.1-1 with these libraries in `/mingw64/lib`:

    libicudt.dll.a  libicuin.dll.a    libicuio.dll.a  libicule.dll.a
    libiculx.dll.a  libicutest.dll.a  libicutu.dll.a  libicuuc.dll.a

This results in the reported build error.

Cygwin has a package `mingw64-x86_64-icu` 57.1-2 with these files in `/usr/x86_64-w64-mingw32/sys-root/mingw/lib`:

    libicudata.dll.a  libicuio.dll.a  libiculx.dll.a    libicutu.dll.a
    libicui18n.dll.a  libicule.dll.a  libicutest.dll.a  libicuuc.dll.a

Note that the versions are nearly identical. I was wrong when I thought that it was a problem of old versions of libicu. We need a `configure` which supports both variants. I'll send a PR.

**Comment by stweil** [comment]
PR #572 addresses all issues which I had with the MSYS2 Installer from https://msys2.github.io/.

**Comment by djusHa** [comment]
Thanks for your effort!

**Comment by stweil** [comment]
@djusHa, the latest version in git includes the changes now. Don't forget to run `./autogen.sh` before trying a new build.

**Comment by djusHa** [comment]
Thumbs up! :-)

It compiles fine now.
Even with the PKGBUILD from Tesseract Wiki:
https://github.com/tesseract-ocr/tesseract/wiki/Compiling#msys2
