### ISSUE TITLE
I meet a problem when make training 

### ISSUE THREAD

**Issue by BrianZhu01** [tesseract-ocr/tesseract#570]
The error as list :
libtool: link: g++ -g -O2 -std=c++11 -o .libs/lstmtraining lstmtraining.o  ./.libs/libtesseract_training.a ./.libs/libtesseract_tessopt.a -licui18n -licuuc ../api/.libs/libtesseract.so /usr/gcc482/lib/../lib64/libstdc++.so -lm -llept -lpthread -fopenmp -Wl,-rpath -Wl,/usr/gcc482/lib/../lib64
./.libs/libtesseract_training.a(unicharset_training_utils.o): In function `tesseract::SetupBasicProperties(bool, bool, UNICHARSET*)':
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:65: undefined reference to `u_isalpha_54'
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:67: undefined reference to `u_islower_54'
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:69: undefined reference to `u_isupper_54'
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:71: undefined reference to `u_isdigit_54'
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:73: undefined reference to `u_ispunct_54'
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:85: undefined reference to `uscript_getScript_54'
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:85: undefined reference to `uscript_getName_54'
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:98: undefined reference to `u_toupper_54'
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:98: undefined reference to `u_tolower_54'
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:115: undefined reference to `u_charMirror_54'
./.libs/libtesseract_training.a(unicharset_training_utils.o): In function `~IcuErrorCode':
/home/brian02/tesseract-master/training/icuerrorcode.h:47: undefined reference to `icu_54::ErrorCode::~ErrorCode()'
./.libs/libtesseract_training.a(unicharset_training_utils.o): In function `tesseract::SetupBasicProperties(bool, bool, UNICHARSET*)':
/home/brian02/tesseract-master/training/unicharset_training_utils.cpp:119: undefined reference to `u_charDirection_54'
./.libs/libtesseract_training.a(unicharset_training_utils.o): In function `tesseract::IcuErrorCode::handleFailure() const':
/home/brian02/tesseract-master/training/icuerrorcode.h:55: undefined reference to `icu_54::ErrorCode::errorName() const'
./.libs/libtesseract_training.a(unicharset_training_utils.o): In function `tesseract::IcuErrorCode::~IcuErrorCode()':
/home/brian02/tesseract-master/training/icuerrorcode.h:47: undefined reference to `icu_54::ErrorCode::~ErrorCode()'
./.libs/libtesseract_training.a(unicharset_training_utils.o): In function `~IcuErrorCode':
/home/brian02/tesseract-master/training/icuerrorcode.h:47: undefined reference to `icu_54::ErrorCode::~ErrorCode()'
./.libs/libtesseract_training.a(unicharset_training_utils.o): In function `tesseract::IcuErrorCode::~IcuErrorCode()':
/home/brian02/tesseract-master/training/icuerrorcode.h:51: undefined reference to `icu_54::UMemory::operator delete(void*)'
./.libs/libtesseract_training.a(unicharset_training_utils.o):(.data.rel.ro._ZTIN9tesseract12IcuErrorCodeE[_ZTIN9tesseract12IcuErrorCodeE]+0x10): undefined reference to `typeinfo for icu_54::ErrorCode'
 How can I resolved it? I have install libicu-dev.

**Comment by BrianZhu01** [comment]
I mainly meet this error, when i make training it :
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../lstm -I../arch -I../viewer -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I/usr/local/include/leptonica -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -g -O2 -std=c++11 -MT normstrngs.lo -MD -MP -MF .deps/normstrngs.Tpo -c normstrngs.cpp  -fPIC -DPIC -o .libs/normstrngs.o
normstrngs.cpp:25:49: fatal error: unicode/normalizer2.h: No such file or directory
 #include "unicode/normalizer2.h"  // From libicu
                                                 ^
compilation terminated.
make[1]: *** [normstrngs.lo] Error 1
make[1]: Leaving directory `/home/brian02/tesseract-master/training'
make: *** [training] Error 2
 Then， I copy the file from in the icu ,and get the above errors ,who can help me ? I just a new learner,thanks!

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/571#issuecomment-267436603

**Comment by belchiorneto** [comment]
I have same, i can solve removing libicu and reinstalling from source: 
http://www.linuxfromscratch.org/blfs/view/cvs/general/icu.html

**Comment by BrianZhu01** [comment]
I just not build the static library.  it a simple problem
