### ISSUE TITLE
which version of icu for tesseract4.0 ? 

### ISSUE THREAD

**Issue by BrianZhu01** [tesseract-ocr/tesseract#571]
I have install the icu_54 for it, but have meet some errors when make training tools. 
and  who know which  verision for tesseract4.0 ?

**Comment by stweil** [comment]
Both older (Debian libicu-dev 52.1-8+deb8u4) and newer (Debian libicu-dev 57.1-5) versions work for me. There are known issues for Windows which are addressed in PR #574.

**Comment by BrianZhu01** [comment]
@stweil, my system is centos6.5,

**Comment by Shreeshrii** [comment]
Please Google search for icu-dev or icu-devel libs for CentOS.

**Comment by amitdo** [comment]
>which version of icu for tesseract 4.0 ?
 
probably version >=4.4

As said by Shree, you need to install the package icu-devel.

**Comment by Shreeshrii** [comment]
http://rpmfind.net/linux/rpm2html/search.php?query=libicu-devel

**Comment by BrianZhu01** [comment]
it's not icu version problem for me , I just forget to rebuild the static library.  so if you also meet some error , it may other reason caused!
