### ISSUE TITLE
"make install" ends with some errors

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#573]
I wanted to update my working tesseract (version from August) by pulling and compiling the latest version but `make install` ends with some errors:
```
$ sudo make install
...
Makefile:333: recipe for target 'install-dataDATA' failed
make[3]: *** [install-dataDATA] Error 1
make[3]: Leaving directory '/work/usr/local/src/tesseract/tessdata/configs'
Makefile:403: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/work/usr/local/src/tesseract/tessdata/configs'
Makefile:461: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/work/usr/local/src/tesseract/tessdata'
Makefile:483: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

$ tesseract --version

tesseract: error while loading shared libraries: libtesseract.so.4: cannot open shared object file: No such file or directory
```

Full output see http://dpaste.com/1AMP4MA.txt

Please can you help?

**Comment by Wikinaut** [comment]
I think it was due to a version conflict on my debian 8 with a packaged-tesseract. After removal of the packaged tesseract, it works (but make install errors remain).

**Comment by zdenop** [comment]
> install-dataDATA
This indicates problem with configuration. How did you configured  build?

**Comment by Wikinaut** [comment]
this is my standard procedure:

```
make clean
git pull
./autogen.sh
./configure --enable-debug
make
sudo make install
```

**Comment by stweil** [comment]
Extract from your build protocol:

    make[3]: Entering directory '/work/usr/local/src/tesseract/tessdata/configs'
    make[3]: Nothing to be done for 'install-exec-am'.
     /bin/mkdir -p '/usr/local/share/tessdata/configs'
     /usr/bin/install -c -m 644 inter makebox box.train unlv ambigs.train api_config kannada box.train.stderr quiet logfile digits hocr tsv linebox pdf rebox strokewidth bigram txt '/usr/local/share/tessdata/configs'
    /usr/bin/install: „inter“ und „/usr/local/share/tessdata/configs/inter“ sind die gleiche Datei

So you are building in `/work/usr/local/src/tesseract` and want to install to `/usr/local`. The installer says that `/work/usr/local/src/tesseract/tessdata/configs/inter` and `/usr/local/share/tessdata/configs/inter` are the same file and fails therefore. Do you have a symbolic link somewhere (either in your build directory or in the installation directory) which connects both directory hierarchies?

**Comment by Wikinaut** [comment]
Yeah, you are right. I _had_ indeed such a link when I build the last version !
I will now re-compile and report here, and close, if it solved.

Nevertheless, perhaps the "make" could be improved to catch (capture?) such a user mistake.

**Comment by stweil** [comment]
Well, make did catch that mistake and said that the installation failed because for some files source and destination were identical ("sind die gleiche Datei").

**Comment by Wikinaut** [comment]
I reported that issue, and close it now. Issue solved by removing my softlink for tessdata.

**Comment by rahulrewa9200** [comment]
root@scube014:~/qingy-fork-master/src/libraries# make clean
Making clean in libraries
/bin/bash: line 20: cd: libraries: No such file or directory
make: *** [clean-recursive] Error 1
pls find this problem .

**Comment by slimshady045** [comment]
make install
`if` [ -L /usr/include/sound ]; then \
        rm -f /usr/include/sound; \
        ln -sf /media/ss/DATA/SOFTWARE/Rt-Linux-HDaudio-5.18/alsa-driver-RTv5.18/alsa/include/sound /usr/include/sound; \
else \
        rm -rf /usr/include/sound; \
        install -d -m 755 -g root -o root /usr/include/sound; \
        for f in include/sound/*.h; do \
                install -m 644 -g root -o root $f /usr/include/sound; \
        done \
fi
install: cannot stat 'include/sound/*.h': No such file or directory
Makefile:188: recipe for target 'install-headers' failed
make: *** [install-headers] Error 1

**Comment by slimshady045** [comment]
**similar problem with my alsa make install**



 make install
if [ -L /usr/include/sound ]; then \
        rm -f /usr/include/sound; \
        ln -sf /media/ss/DATA/SOFTWARE/Rt-Linux-HDaudio-5.18/alsa-driver-RTv5.18/alsa/include/sound /usr/include/sound; \
else \
        rm -rf /usr/include/sound; \
        install -d -m 755 -g root -o root /usr/include/sound; \
        for f in include/sound/*.h; do \
                install -m 644 -g root -o root $f /usr/include/sound; \
        done \
fi
install: cannot stat 'include/sound/*.h': No such file or directory
Makefile:188: recipe for target 'install-headers' failed
make: *** [install-headers] Error 1

**Comment by vee-varun** [comment]
I got the same error.
just preceded sudo to make install
then boom

**Comment by zdenop** [comment]
@vee-varun : can you be more specific? What kind of error you get, what version of code you used, of etc?

**Comment by yonga9479** [comment]
I have same errors.
Not "make install", but "sudo make install" in terminal.
Then i have solved.

**Comment by felipsoarez** [comment]
I would like to add that I had the same problem on my system

> OS: Manjaro 20.2.1 Nibia
> Kernel: x86_64 Linux 5.10.2-2-MANJARO

When installing bitcoin-0.21;

To solve it I had to install the new version of boost `$ pamac install boost=1.75.0-1`
