### ISSUE TITLE
Add tesseract version+commit string to a .h file

### ISSUE THREAD

**Issue by neoneye** [tesseract-ocr/tesseract#574]
# Problem 
For iOS there are [many forks](https://github.com/gali8/Tesseract-OCR-iOS/network), where it's difficult to figure out what version of Tesseract that it's derived from. 

# Solution
Add a define in the `capi.h` file, like this:

    #define TESSERACT_ID "3.06.01dev, 13e46ae1c4d8acccf15654b0e6ddbddbd363618a"

This will make it easier to determine what version of Tesseract that it is.

I use Tesseract on iPhone and iPad.

I have read the contributing guide.

Thank you for this awesome ocr library.

**Comment by amitdo** [comment]
There is something like what you asked for, but currently it is only available in the debug build.

https://github.com/tesseract-ocr/tesseract/blob/dc124043ec/configure.ac#L24
https://github.com/tesseract-ocr/tesseract/blob/dc124043ec/api/baseapi.cpp#L139
https://github.com/tesseract-ocr/tesseract/blob/dc124043ec/api/capi.h#L112

**Comment by neoneye** [comment]
[Tesseract for iOS](https://github.com/gali8/Tesseract-OCR-iOS) comes with `.a` files, there are no `.cpp` files. Just by looking at the code there is no way to tell what version of Tesseract that is being used. One has to actual execute the code to figure out the version.

It would be more helpful if the version string was in a `.h` file.

**Comment by zdenop** [comment]
You report issue in wrong project ;-) Tesseract provide information about version. See:
[const char* TessBaseAPI::Version()](https://github.com/tesseract-ocr/tesseract/blob/master/api/baseapi.cpp#L139) and how to [use it](https://github.com/tesseract-ocr/tesseract/blob/master/api/tesseractmain.cpp#L52) (in c++).

**Comment by neoneye** [comment]
Sorry, I overlooked that it's already here.

In the [baseapi.h](https://github.com/tesseract-ocr/tesseract/blob/master/api/baseapi.h#L23), there is this line. Exactly something like this that I was looking for.

    #define TESSERACT_VERSION_STR "4.00.00alpha"

Thank you for your assistance.
