### ISSUE TITLE
Segmentation fault on specific PNG image

### ISSUE THREAD

**Issue by vikinsights** [tesseract-ocr/tesseract#575]
I am running tesseract on this image [http://imgur.com/a/yIX5N](url) and i get a segmentation fault. I am wondering how i can go about to troubleshoot the problem or, in case one of the developers would know if this is a known bug. I am running on Windows and this is the version of tesseract under use:

> c:\> tesseract.exe --version
tesseract 3.05.00dev
 leptonica-1.73
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0

**Comment by stweil** [comment]
Did you compile Tesseract yourself or did you use binaries from the net? Could you try a newer version?

**Comment by jbreiden** [comment]
The image link is 404, so impossible to make progress.

**Comment by stweil** [comment]
The image is available [here](http://i.imgur.com/fDnFq1a.jpg).
