### ISSUE TITLE
lstmtraining: scrollview:waiting for server...

### ISSUE THREAD

**Issue by sunshinfight** [tesseract-ocr/tesseract#578]
It doesn't work when I run lstmtraining usage command like [guider](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#training-from-scratch),and show "scrollview:waiting for server..." in basetrain.log.
First I think the training-tools are not compiled successfully,I reinstall it,but it still error.Then I think change the param "debug_interval" to 0,and it worked.
So am I wrong or it is a bug?
Thanks,sorry for my bad English.

**Comment by stweil** [comment]
You also have to build `ScrollView.jar`:

    make ScrollView.jar

In addition, it is necessary to set the environment variable `SCROLLVIEW_PATH` to the directory with `ScrollView.jar`. This information is currently missing in the Wiki page.

**Comment by bclyc** [comment]
@stweil Hi,
I did "make ScrollView.jar" ans add its path to the environment variable  `SCROLLVIEW_PATH` but the program still can't find it. I found in viewer/svutil.cpp `GetEnv(SCROLLVIEW_PATH)` doesn't work, so I changed the path in program. But after started ScrollView, it stopped with error:
`
#A fatal error has been detected by the Java Runtime Environment:
#SIGSEGV (0xb) at pc=0x00007ffff5174009, pid=21858, tid=21859
#JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
#Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
#Problematic frame:
#C  [libjava.so+0x1d009]  JNU_GetEnv+0x19

#Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %P" (or dumping to /usr/workspace/tesseract/core.21858)

#An error report file with more information is saved as:
#/usr/workspace/tesseract/hs_err_pid21858.log

#If you would like to submit a bug report, please visit:
#http://bugreport.java.com/bugreport/crash.jsp
#The crash happened outside the Java Virtual Machine in native code.
#See problematic frame for where to report the bug.
#sh: 1: kill: No such process
`
Do you have any idea how to solve this? Thanks.

**Comment by akhudek** [comment]
You can also disable the scrollview requirement by configuring the project with:

./configure --disable-graphics

**Comment by vermouthmjl** [comment]
I have the same problem with lstmtraining.
As I am on Windows, the only way I can get tesseract to build is by doing cppan. `autogen.sh` cannot be run, and I am therefore unable to configure the project to disable graphics. 
I found the .jar files from http://auto-download.com/download/get/Z4gnbJdP/tess_debug_zip.html as http://rdaemons.blogspot.fr/2011/02/tesseract-ocr-setting-up-interactive.html suggested, and put the three .jar files with all the binaries built with cppan. But no luck, still stuck with waiting for server...

**Comment by Shreeshrii** [comment]
Run lstmtraining with --debug -1

Or 0.

Then scrollview will not be called.

**Comment by vermouthmjl** [comment]
Thanks for your reply @Shreeshrii 
Unfortunately, whether I run lstmtraining with --debug_level -1 or 0, scrollview are always called.
I only get `Starting java -Xms512m -Xmx1024m -Djava.library.path=. -jar ./ScrollView.jar` in the log. Then when I kill the process, a bunch of waiting for server appear in the log.

**Comment by Shreeshrii** [comment]
Is it different if you use the windows  binaries provided by ub manneheim

https://github.com/UB-Mannheim/tesseract/wiki

**Comment by vermouthmjl** [comment]
It is the same with binaries of 8 january of UB Manneheim. It looks like --debug_level has no bearing on what happens.

**Comment by Shreeshrii** [comment]
On linux and WSL (Bash on windows 10) I was able to get around the problem
by using   --debug_interval -1

@stweil Is this different for windows?

**Comment by vermouthmjl** [comment]
I wasn't able to disable the use of scrollViewer, but by putting the three jar files from the BU Manneheim binaries in the working directory from which I call lstm, quite a few jar windows open, and the program appears to do some training. 
I confirm this happened even with --debug_level -1.

**Comment by vermouthmjl** [comment]
Considering https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#debug-interval-and-visual-debugging, I now understand that my error is I was setting debug_level instead of debug_interval.

**Comment by vermouthmjl** [comment]
Otherwise, for me, when I put the three .jar files inside the folder in which I run lstmtraining, the windows are correctly shown.

**Comment by Eugenij** [comment]
just replace WinMain function in your project with int main(int argc, char *argv[]) otherwize WinMain is newer call... i.e. main symbol exist in tesseract library

**Comment by zdenop** [comment]
@vermouthmjl : if I understand you correctly, your issue is solved?

**Comment by vermouthmjl** [comment]
@zdenop yep it's fine now. Thanks.
