### ISSUE TITLE
have error : Error in findTiffCompression: function not present

### ISSUE THREAD

**Issue by cpusoft** [tesseract-ocr/tesseract#58]
i have success install tesseract , 
tesseract 3.02.02
 leptonica-1.71
  libjpeg 6b : libpng 1.2.49 : zlib 1.2.8

and my libtiff locate in /usr/lib64
locate libtiff
/usr/lib64/libtiff.so.3
/usr/lib64/libtiff.so.3.9.4
/usr/lib64/libtiffxx.so.3
/usr/lib64/libtiffxx.so.3.9.4

so i add  ~/.bash_profile  with
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib64 
and relogin.

but the error still there:  
Tesseract Open Source OCR Engine v3.02.02 with Leptonica
Error in findTiffCompression: function not present
Error in pixReadStreamTiff: function not present
Error in pixReadStream: tiff: no pix returned
Error in pixRead: pix not read
Unsupported image type.

how i solve it ? thx alot

**Comment by zdenop** [comment]
that means that leptonica was not compiled with tiff support

**Comment by cpusoft** [comment]
i have tried leptonica-1.71/1.72 ,  both have same error.
should i use early leptonica ,   which version of leptonica  is compatible ？
thx

**Comment by zdenop** [comment]
what does it mean "i have tried"?
If you compile leptonica without libtiff support it does not help to try any version...
This is definitely not tesseract issue.

**Comment by hzy9981** [comment]
same question

**Comment by zdenop** [comment]
same solution: build leptonica with tiff support.

**Comment by hzy9981** [comment]
configure: error: libpng support requested but library not found

zdenop <notifications@github.com> 于2018年7月9日周一 下午3:31写道：
