### ISSUE TITLE
Tag master as 4.0.0alpha

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#581]
Currently when using debug version, tesseract reports the gitver version. However, even when using the master branch, it reports it as 3.05dev.

Please add a tag on master for 4.0.0alpha so that config.ac gets the correct tag for gitrev.

**Comment by Shreeshrii** [comment]
It would also be helpful to remove the ifdef limiting the display of GITREV to the debug build, so that it is displayed in all builds from GitHub source.

**Comment by zdenop** [comment]
GITREV should be used for debuging and not in release mode.
tag in master created:
https://github.com/tesseract-ocr/tesseract/tree/4.00.00alpha
also visible in https://github.com/tesseract-ocr/tesseract/releases
