### ISSUE TITLE
Clean build warnings

### ISSUE THREAD

**Issue by egorpugin** [tesseract-ocr/tesseract#584]
Currently we see tons of warnings during MSVC builds.
They should be fixed during `modernizing code` phase.
See this log for warnings https://ci.appveyor.com/api/buildjobs/3v0vmv6xjy658f79/log

**Comment by stweil** [comment]
Similar warnings can be produced on Linux using clang++. But even the default debug build with gcc produces tons of warnings (mainly signed/unsigned mismatch).

**Comment by egorpugin** [comment]
I've also removed /W1 (warning level 1, default is 3) in leptonica for MSVC.
So, @DanBloomberg probably should look at those warnings in lept.
https://ci.appveyor.com/project/DanBloomberg/leptonica/build/job/v45bwi40a8n9q9cu/log

**Comment by DanBloomberg** [comment]
In leptonica:
- 95% of these are because I use floats and floating point numbers (like 1.0) are assumed to be doubles.
- Most of the rest are implicit conversions from float to int, where the ints are indices into a 2d image array.

**Comment by egorpugin** [comment]
* 1.0 -> 1.0f
* make casts explicit

What do you think?

**Comment by stweil** [comment]
Mixing float and double can result in additional code (and execution time) for conversions between both types.

**Comment by DanBloomberg** [comment]
Any program may do a few tens of these, so we're talking about a small fraction of a microsecond.

Eliminating these windows compiler warnings is not high on my todo list.  I'll try to remember to add "f" to numbers in files that I'm modifying for other reasons.

**Comment by zdenop** [comment]
Closing this, because more info is provided in #1036
