### ISSUE TITLE
Problems in Compiling to Windows

### ISSUE THREAD

**Issue by unholyHub** [tesseract-ocr/tesseract#588]
I followed the [steps](https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows) required to get to .sln file for Visual Studio but I get a bunch of errors.

Here is a [screenshot](http://i.imgur.com/puq3uAR.png).

**Comment by egorpugin** [comment]
Try to run `cppan --clean-packages .*jpeg.*`, then run `cppan` in tesseract folder and then check your solution again.

**Comment by egorpugin** [comment]
Also make sure you have the latest cppan client installed: `cppan --self-upgrade`

**Comment by unholyHub** [comment]
I will check these commands on Monday.

It is the latest version of cppan.

Also the hanging on 7 process still goes on.

**Comment by egorpugin** [comment]
Kill those processes. It's MSBuild.exe/CL.exe issue.

**Comment by unholyHub** [comment]
Yes, managed that problem. Now I will check the clean packages argument later on. 
Stay tuned.

**Comment by unholyHub** [comment]
After 
`cppan --clean-packages .*jpeg.*`
and 
`cppan --self-upgrade`

I get this 

![clipboard01](https://cloud.githubusercontent.com/assets/5253959/21307804/ca31d14a-c5df-11e6-8a56-7ddfbffbfafa.png)

**Comment by egorpugin** [comment]
Clean `tiff` now. :)
```
cppan --clean-packages .*tiff.*
cppan
```

You may try instead of this remove the whole storage `c:\users\zhivko\.cppan\storage`.
Or try to run `cppan --clean-packages .*`.

**Comment by unholyHub** [comment]
I tried with no success.

**Comment by egorpugin** [comment]
Did you remove storage?
If no, do 
```
cppan --clean-packages .*lepton.*
cppan
```

Issue is somewhere between tiff/leptonica.

**Comment by unholyHub** [comment]
Look now what I got
![clipboard01](https://cloud.githubusercontent.com/assets/5253959/21316793/096242ac-c60b-11e6-9392-0a77ed2d8ef8.png)

**Comment by egorpugin** [comment]
Can you go into that file and a picture of code line?

**Comment by egorpugin** [comment]
Oh, by the way. libtiff is known to not work on MSVC < 2015 (2013,2012,2010 etc.).
I don't have VS2013 to fix the issue, but it should not be very hard.

**Comment by egorpugin** [comment]
The issue is in snprintf function or macro. It is changed in VS2015.

**Comment by unholyHub** [comment]
So I have to install older version of VS

**Comment by egorpugin** [comment]
What version do you have? 2013 or 2015? or even 2017?

**Comment by unholyHub** [comment]
![image](https://cloud.githubusercontent.com/assets/5253959/21345168/b819da0c-c6a7-11e6-8212-6dd38a79531a.png)

**Comment by egorpugin** [comment]
No need to downgrade. It should work fine on VS2015.

**Comment by unholyHub** [comment]
But still not working

**Comment by unholyHub** [comment]
The mistake is mine. 
In the last step I always used:
`cmake .. -DSTATIC=1` instead of `cmake ..`
and now compiles perfectly

**Comment by egorpugin** [comment]
Should we close this ticket?

**Comment by unholyHub** [comment]
Yes, tag it as Closed

**Comment by Shreeshrii** [comment]
@egorpugin Please see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-dev/Vx3Z-MReD3c/BMRy_IkSCAAJ

discussion regarding compiling 3.05 branch with vs 2010.

Does 3.05 branch need Leptonica 1.74 and not 1.74.1 ?

**Comment by egorpugin** [comment]
1.74 means >=1.74.* i.e. when we have 1.74.1, 1.74==1.74.1, when we have 1.74.2, 1.74==1.74.2

As for 3.05+vs2010, one must gather (download, build) all deps manually.
3.05+vs2015+cppan works fine.
