### ISSUE TITLE
Accuracy problem?

### ISSUE THREAD

**Issue by wierzba3** [tesseract-ocr/tesseract#589]
I'm testing this out and it's recognizing 1 word per 20 at best, even when take screenshots of typed text in a text editor.

Is this just a limit of the technologies abillities at this time?

**Comment by amitdo** [comment]
[Guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md)

Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).
