### ISSUE TITLE
Add a new config file  'pdftxt'  to create PDF and TEXT output at the same time

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#59]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-dev/XllxjvK5HtU/C4mebS6lcJoJ

Jeff suggested that users create a myconfig file. I think it will be useful to actually provide the configuration as 'pdftxt' .

========================================

tessedit_create_txt 1
tessedit_create_pdf 1

========================================

Then make sure that you invoke the command line such that 
Tesseract writes to files instead of stdout, e.g. 

    tesseract myimage.tif myoutput pdftxt

This will read myimage.tif and pdftxt (config file), and produce myoutput.pdf and myoutput.txt

**Comment by jimregan** [comment]
Not generally useful, IMO - I don't see there being a whole lot of demand for this.

**Comment by Shreeshrii** [comment]
Zdenko also has same opinion. So you can close the issue.

I'll add to FAQ if that is ok.

- sent from my phone. excuse the brevity.

**Comment by jimregan** [comment]
Sure, the FAQ seems a good place for this information.
