### ISSUE TITLE
Problems with unicode lib while building in Windows

### ISSUE THREAD

**Issue by Izaron** [tesseract-ocr/tesseract#592]
![image](https://cloud.githubusercontent.com/assets/5406399/21318185/3e53f010-c619-11e6-89fb-584df597505a.png)

I used this - https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows
When I try to build it in Debug or Release (I need to get tesseract .lib and .dll for my project), I get bunch of errors because the unicode .lib file is missing. ALL errors associated with this.
I tried
```
cppan --clean-packages .*unicode.*
cppan
```
Same errors

**Comment by egorpugin** [comment]
Try to update from master, upgrade cppan (if you're not on the latest client `cppan --self-upgrade`), run cmake as `cmake ..` and not `cmake .. -DSTATIC=1`. I've removed STATIC flag from wiki page.

**Comment by Izaron** [comment]
Without STATIC=1 I get:
```
20>LINK : fatal error LNK1104: cannot open file '..\Debug\tesseract305d.lib'
19>LINK : fatal error LNK1104: cannot open file '..\Debug\tesseract305d.lib'
18>LINK : fatal error LNK1104: cannot open file '..\Debug\tesseract305d.lib'
17>LINK : fatal error LNK1104: cannot open file '..\Debug\tesseract305d.lib'
```

**Comment by egorpugin** [comment]
Can you do please following steps and send `1.txt` and `2.txt` to me?
```
cppan --clean-packages .*unicode.*
cppan
mkdir win32
cd win32
cmake .. > 1.txt 2>&1
cmake --build . --config Release > 2.txt 2>&1
```

**Comment by Izaron** [comment]
I removed the folder C:/Users/HOME/.cppan and re-downloaded the repository to start over. Here are my steps.
```
git clone https://github.com/tesseract-ocr/tesseract tesserac
cd tesserac
cppan --self-upgrade
cppan
mkdir win32
cd win32
cmake .. > 1.txt 2>&1
```
Then I had this issue - https://github.com/tesseract-ocr/tesseract/issues/464#issuecomment-264166445 There was two cmake.exe processes, I stopped one with memory 2304KB (second had bigger memory 4496KB). Also sometimes can hangs 3 processes.
`cmake --build . --config Release > 2.txt 2>&1`
I have build error unfortunately... Can you look at it?
https://gist.github.com/Izaron/c0471f1727af1ca7c0f67b398a1a5cd4 - 1.txt
https://gist.github.com/Izaron/d1116ae559c7a40cbebcf7794f7f0a35 - 2.txt

I tried to do this several times and get different number of errors in 2.txt. I have no idea the reason why this is happening

**Comment by egorpugin** [comment]
What VS do you have? Is it VS 2015?

**Comment by Izaron** [comment]
I have correct VS 2015.
It's question marks because of default russian language. In UTF-8: https://gist.github.com/Izaron/071268b9ba1c863bd6b055d6f37ce077
I built it again. As you can see, quite a different number of errors

**Comment by egorpugin** [comment]
I see. Probably there are some issues with your environment.
```
-- include search.h - not found
-- function lfind - not found
```
This file and function cannot be found on your system for some reason, but actually they're available.
I'm thinking on how we can fix this.

**Comment by Izaron** [comment]
Finally build it .dll and .lib, thank you very much @egorpugin!
In new example project I put all folders to includes in properties and linked tesseract305.lib, so I can include <baseapi.h>, but can not include <allheaders.h>. Should I build leptonica for windows to use allheader.h and pixRead?
Also built files are named tesseract305, is this normal?

**Comment by egorpugin** [comment]
How do you want to use tess?
If you have a project with cmake build, see this example https://github.com/cppan/tesseract_example/tree/master/with_cmake

If you want to build that file https://github.com/cppan/tesseract_example/blob/master/with_cppan/main.cpp
run from command line 
```
cppan --build https://github.com/cppan/tesseract_example/raw/master/with_cppan/main.cpp
```
The VS solution appear in that folder.

**Comment by Izaron** [comment]
I have failed again with this **simple** command.
But I sure I understand what the problem is. In the console cppan writes that downloads and unpacks **18** different packages. But I do it every time, not all files downloads - on my PC only from 4 to 11 files random files during all this time, but sometimes this is enough to build some projects. That is why as a result of build errors is different - from 50 to 1500, and sometimes 0.
All I need - .lib and .dll files of the dependencies (including leptonica) and built .lib and .dll of 4.0.0 tesseract (current master branch, right?), in order that I can update it in one of my project from older version.
Can you give me all these dependency files? I can add them to any project for using leptonica and tesseract and compile , including current tesseract master (although I was able to magically compile it with 9 downloaded dependencies). Thanks for the support!

**Comment by egorpugin** [comment]
Could you contact me in some IM chat?
Probably we could find solution faster.
Maybe in skype (same username as here).

**Comment by egorpugin** [comment]
Sorry, updated previous comment with correct username.
