### ISSUE TITLE
RFC: Reorganize source tree

### ISSUE THREAD

**Issue by egorpugin** [tesseract-ocr/tesseract#594]
I'd like to propose changes to tesseract source tree structure.
Today the common way is to have `src` folder with all program stuff and `include` folder with public headers. Now we have a lot of dirs in the root - that's very annoying.
On the first stage I propose:
1. move all sources into `src`
2. move training tools from `training` to `tools/training`

Later we can try to move public headers to `include` directory.

The new look will be like:
![pic](http://i.imgur.com/K8NkI8T.png)

If there are no objections, I'll commit changes.

**Comment by jbreiden** [comment]
Make sure to get positive confirmation from Ray before doing something like this. He's considering a different, very disruptive change involving the non-LSTM recognizer. It would collide very badly with source reorganization.

**Comment by egorpugin** [comment]
Yea, I'll act only in case of positive reply from Ray.

**Comment by stweil** [comment]
Related: I suggest to remove some large binaries (mainly in `testdata` and `testing`) which are used for tests and add them to a new repository `[test](https://github.com/tesseract-ocr/test)`. Like `googletest`, this new repository can then be added as a submodule.

**Comment by stweil** [comment]
cc: @Shreeshrii

**Comment by Shreeshrii** [comment]
>I suggest to remove some large binaries (mainly in testdata and testing) which are used for tests and add them to a new repository test. Like googletest, this new repository can then be added as a submodule.

Yes. I think it is a good idea. It would also be useful to streamline the various other test related folders at the same time.

**Comment by Shreeshrii** [comment]
However this may require @theraysmith / @jbreiden to create the new repo.

**Comment by zdenop** [comment]
done. enjoy ;-)

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/test

**Comment by theraysmith** [comment]
How about the following first stage:
Move all the source to src.
Create pointer headers in include that #include the real header for the public headers.
Try to avoid creating any APIs that make use of the old classifier.

**Comment by stweil** [comment]
@egorpugin, will you send a pull request for the first step, moving all source to src?

**Comment by egorpugin** [comment]
Sure.

**Comment by egorpugin** [comment]
Changes are in master. Please, check build scripts. I did small updates, cmake & cppan seems ok, but autotools is untested.

**Comment by Shreeshrii** [comment]
The training folder should also go under src.

Thanks.

**Comment by egorpugin** [comment]
Done.

**Comment by stweil** [comment]
Getting rid of `vs2010` would be even better. I have a local patch for `gettimeofday`, so at least that part could be eliminated.

**Comment by zdenop** [comment]
This is part of the game, but content of directory is needed and it is platform (compiler?) dependent...
There is already android directory. I have not clue if for IOS or Mac something special is needed, but it would make sense to organize it better....

**Comment by amitdo** [comment]
>Create pointer headers in include that #include the real header for the public headers.

What's the benefit here?

**Comment by stweil** [comment]
I'd appreciate if we could reduce the number of API includes (those which get installed, currently 58).

Several of them have a high probability of a naming conflict with other include files, for example `capi.h`, `errcode.h`, `functions.h`, `helpers.h`, `input.h`, `network.h` and more. We could avoid such conflicts by requiring include statements like `#include "tesseract/capi.h"` instead of `#include "capi.h"`.   That's an API change of course. Can we do it nevertheless?

**Comment by zdenop** [comment]
Are there any guidelines/standard for include statements of header files from the project?

BTW: I was suggesting this change [some time ago](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-dev/75lhPVAOIho/E7yZYOTVAgAJ) for `allheader.h` but there were problems with it...

**Comment by egorpugin** [comment]
From my pov public headers must go into `include/tesseract` folder.
Then they'll be included like `#include <tesseract/...>`.
Instead of not really informing `#include <allheaders.h>`.

**Comment by Shreeshrii** [comment]
May I also suggest an `examples` folder where sample programs using api are provided. Currently these are included as part of the wiki.

**Comment by stweil** [comment]
Should that `examples` folder be added to https://github.com/tesseract-ocr/tesseract? Or maybe to https://github.com/tesseract-ocr/test?

**Comment by Shreeshrii** [comment]
See https://github.com/google/googletest/tree/master/googletest
for an example of project directory structure



ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by egorpugin** [comment]
It's better to put examples inside `tesseract-ocr/tesseract`.

**Comment by amitdo** [comment]
>From my pov public headers must go into include/tesseract folder.
Then they'll be included like #include <tesseract/...>

+1

**Comment by Shreeshrii** [comment]
> > Create pointer headers in include that #include the real header for the public headers.

> What's the benefit here?

Probably something to do with merging the code in Google's development branch.

@theraysmith  Please clarify regarding this.

**Comment by Shreeshrii** [comment]
A side effect of source reorganization:

History of the source files is not carried though to the new file location. eg. see

https://github.com/tesseract-ocr/tesseract/commits/master/src/ccmain/pageiterator.h

It maybe useful to tag https://github.com/tesseract-ocr/tesseract/tree/e95ff1159e652d9b8ae6bc4aafdb196981942e6a so that it is easy to locate older version of source files.

**Comment by amitdo** [comment]
Yes, thats because the way git works. Same issue was with reorganization of the wiki.

Only the view of individual files' history is lost. Git's blame still works. The general history is still there.

**Comment by Shreeshrii** [comment]
>Only the view of individual files' history is lost

That's the part I was looking at.

Please see 

https://github.com/tesseract-ocr/tesseract/blob/e95ff1159e652d9b8ae6bc4aafdb196981942e6a/src/ccmain/pageiterator.h#L205-210

I thought there was duplication there  and was trying to locate when the change was made. I think having a tag marking the source reorg maybe helpful. 

But, I am not very familiar with workings of GitHub, maybe the experts don't need it.

**Comment by amitdo** [comment]
Try the **Blame** button in individual file's view:
https://github.com/tesseract-ocr/tesseract/blame/master/src/ccmain/pageiterator.h

**Comment by amitdo** [comment]
```
bool BoundingBox(PageIteratorLevel level,
                   int* left, int* top, int* right, int* bottom) const;
bool BoundingBox(PageIteratorLevel level, const int padding,
                   int* left, int* top, int* right, int* bottom) const;
```

It's not a duplication. It a feature in C++ (and other programing languages) called 'function overloading'.
https://en.wikipedia.org/wiki/Function_overloading

**Comment by Shreeshrii** [comment]
@amitdo Got it now. Thank you for explaining.

**Comment by amitdo** [comment]
> Create pointer headers in include that #include the real header for the public headers.

@stweil, do you know what's the reason to do so?

**Comment by stweil** [comment]
The current code implements what was discussed above: third party code now includes the Tesseract API with code like `#include "tesseract/capi.h"`, so the problem with potential name conflicts is fixed.

If we want to write the include statements in the Tesseract code similarly, more code would have to be moved, and Ray's suggestion would be one possible solution. I see currently no need for that.

**Comment by stweil** [comment]
The latest changes include header files for C and for C++.

Do you know bindings or other third party applications which use more than these files (from the Python binding):

    #include <tesseract/baseapi.h>
    #include <tesseract/publictypes.h>
    #include <tesseract/resultiterator.h>

**Comment by amitdo** [comment]
These are the only bindings I know that use the C++ API directly.

**Comment by amitdo** [comment]
What do you think about moving `tesseractmain.cpp` outside of `api`?

Either to the `/src`, or to new dir under it (`bin` / `prog` / `exec`).

And maybe we should also rename the file to `tesseract`.

**Comment by zdenop** [comment]
@amitdo: I agree. it is "just" example how to use tesseract API ;-), but it is not part of API.

**Comment by egorpugin** [comment]
We could put it under `/tools` or even more better `/examples` as it's really the example.

**Comment by zdenop** [comment]
Should something else (e.g. renaming /moving  tesseractmain some where) be done for 4.0 release or can we close the issue?

**Comment by amitdo** [comment]
@egorpugin commented on Dec 19, 2016

>Later we can try to move public headers to include directory.

What about this part of 'reorganize source tree'?

**Comment by egorpugin** [comment]
The proposition is still there.

**Comment by amitdo** [comment]
+1

**Comment by amitdo** [comment]
Can we agree on moving all programs to a directory named `tools`?

**Comment by amitdo** [comment]
The training tools should go to `tools/training`.

Agree?

**Comment by egorpugin** [comment]
I agree.
Tessmain could be put into tools/tess..main.cpp.

**Comment by amitdo** [comment]
>One thing is that maybe singular form will be better.
tool/...

@zdenop, @stweil
Do you agree?

**Comment by zdenop** [comment]
If training tools will be part of this directory, then plural is right form IMO.

**Comment by amitdo** [comment]
@egorpugin,

Let's split this to 2 stage.

Can you please send a PR with the first stage:
* Create a new dir named **tools**.
* Move tesseractmain.cpp to '/tools'
* tesseractmain.cpp -> tesseract.cpp
* Fix CMake, sw

Second stage (separate PR) will handle the training tools.

**Comment by stweil** [comment]
Alternate proposal:

- Move all sources for libtesseract to new `lib/.../...` (directory structure under `lib` similar to the current one under `src`, or split for `legacy`, `lstm` and maybe `common`)
- Sources for `tesseract` and training tools stay at their current place

**Comment by amitdo** [comment]
@zdenop, @egorpugin

**Comment by egorpugin** [comment]
I don't like lib dir.

**Comment by zdenop** [comment]
As I mentioned in on other place: I would prefer if we are able to provide tesseract library (libtesserract?) as individual repository (e.g. without training tools and tesseract executable). 

Background: several interesting projects integrated tesseract ([OpenCV](https://docs.opencv.org/3.4/d7/ddc/classcv_1_1text_1_1OCRTesseract.html), [BluePrism](https://www.blueprism.com/uploads/resources/Blue-Prism-v6-Overview-Data-Sheet.pdf), [Apache tika](https://docs.opencv.org/3.4/d7/ddc/classcv_1_1text_1_1OCRTesseract.html)) and I would like to see more such integration - (with hope) to get contribution from such integrator (or at lease they could provide results from their internal testing: e.g. one integrator suggested to allow to "plug-in custom OCR engine" to tesseract. The reason is that for amount fields they found tesseract not efficient and they use customs OCR engine for such fields.)

**Comment by egorpugin** [comment]
How are separate repos related to other projects & integrations?

If training tools (TTs) are needed for everyday usage, they must be near.
If they are used rarely, it's ok to move them out.
And even with that it is questionable to me to split things apart. TTs look good here. We just need to split them from sources a bit more (in separate folder etc.).

Also TTs depend on internal tess headers, it's +1 for not moving them out (atleast now).

**Comment by stweil** [comment]
Separate repositories might be considered as soon as we have a code base which no longer requires major API changes. I don't think we have reached that goal yet.

Changes like removal of proprietary data types or adding of a logging API would be complicated with several repositories which have to synchronized.

We already have that situation with heavily used third party like the Python wrapper [tesserocr](https://github.com/sirfz/tesserocr) which currently cannot be used with our Git master because of commit 90bcff3732db2b732b4e329848c4a89677e339d2.

**Comment by egorpugin** [comment]
Also it will be very useful if we drop EXPORT_ALL_SYMBOLS stuff and export needed symbols using TESS_API manually.
As I understand without EXPORT_ALL_SYMBOLS there will be link errors on win.

**Comment by amitdo** [comment]
About separating between the library and the tools.

We have multiple suggestions here, so how do we move forward?

**Comment by amitdo** [comment]
`tesserctmain.cpp` is still under `api`. My new suggestion: Move it to `src` root. Also, change it to `tesserct.cpp`.

**Comment by amitdo** [comment]
@stweil, @egorpugin, @zdenop

What do you think about my latest proposal?

**Comment by egorpugin** [comment]
1. No need to shorten. We have paths bigger than 8.3.
2. The proper layout would be:
```
src/tesseract/... all our dirs except for trainig
src/tools/training/... our training dir
---
src/tools/tesseract/tesseractmain.cpp
or 
src/tools/tesseract/main.cpp
or
src/tools/tesseractmain.cpp
```

**Comment by zdenop** [comment]
+1  from moving from api directory.
But I not fan of big trees ;-) (`src/tools/tesseract/`)

**Comment by egorpugin** [comment]
What about such layout?
```
src/tesseract/...
src/training/...
src/tesseractmain.cpp
```

**Comment by zdenop** [comment]
I have no problem with it...
