### ISSUE TITLE
Can not find iOS framework

### ISSUE THREAD

**Issue by youzhenyu** [tesseract-ocr/tesseract#600]
I now have a framework.
But crash "actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 53".
Under the framework where the latest

This problem I use pod 'TesseractOCRiOS' update and download the traineddata https://github.com/tesseract-ocr/tessdata/tree/bf82613055ebc6e63d9e3b438a5c234bfd638c93

**Comment by youzhenyu** [comment]
上面的问题我用pod 'TesseractOCRiOS’更新并下载了traineddata
https://github.com/tesseract-ocr/tessdata/tree/bf82613055ebc6e63d9e3b438a5c234bfd638c93

**Comment by youzhenyu** [comment]
Now the question is "Can't analyse layout. Make sure 'osd.traineddata' available in 'tessdata' "
But in the Bundle with this file.
How to solve?

**Comment by zdenop** [comment]
Use tesseract user forum for asking support
