### ISSUE TITLE
Compile Error - Raspian - Raspberry Pi 3

### ISSUE THREAD

**Issue by yakeer** [tesseract-ocr/tesseract#601]
Hey,
Trying to install openalpr, which requires tesseract as a dependency.

Everything goes fine until I try to 'make' tesseract

The first error is:

g++: error: unrecognized command line option '-mavx'

I'm not sure how to go further. Can anyone help?

Full error stacktrace:
`pi@raspberrypi:~/openalpr/libraries/tesseract $ make -j4
make all-recursive
make[1]: Entering directory '/home/pi/openalpr/libraries/tesseract'
Making all in arch
make[2]: Entering directory '/home/pi/openalpr/libraries/tesseract/arch'
make[3]: Entering directory '/home/pi/openalpr/libraries/tesseract/arch'
/bin/bash ../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I/usr/local/include/leptonica -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -mavx -g -O2 -std=c++11 -MT libtesseract_avx_la-dotproductavx.lo -MD -MP -MF .deps/libtesseract_avx_la-dotproductavx.Tpo -c -o libtesseract_avx_la-dotproductavx.lo test -f 'dotproductavx.cpp' || echo './'dotproductavx.cpp
/bin/bash ../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I/usr/local/include/leptonica -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -msse4.1 -g -O2 -std=c++11 -MT libtesseract_sse_la-dotproductsse.lo -MD -MP -MF .deps/libtesseract_sse_la-dotproductsse.Tpo -c -o libtesseract_sse_la-dotproductsse.lo test -f 'dotproductsse.cpp' || echo './'dotproductsse.cpp
libtool: compile: g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I/usr/local/include/leptonica -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -mavx -g -O2 -std=c++11 -MT libtesseract_avx_la-dotproductavx.lo -MD -MP -MF .deps/libtesseract_avx_la-dotproductavx.Tpo -c dotproductavx.cpp -fPIC -DPIC -o .libs/libtesseract_avx_la-dotproductavx.o
g++: error: unrecognized command line option '-mavx'
Makefile:537: recipe for target 'libtesseract_avx_la-dotproductavx.lo' failed
make[3]: *** [libtesseract_avx_la-dotproductavx.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
libtool: compile: g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I/usr/local/include/leptonica -pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -msse4.1 -g -O2 -std=c++11 -MT libtesseract_sse_la-dotproductsse.lo -MD -MP -MF .deps/libtesseract_sse_la-dotproductsse.Tpo -c dotproductsse.cpp -fPIC -DPIC -o .libs/libtesseract_sse_la-dotproductsse.o
g++: error: unrecognized command line option '-msse4.1'
Makefile:544: recipe for target 'libtesseract_sse_la-dotproductsse.lo' failed
make[3]: *** [libtesseract_sse_la-dotproductsse.lo] Error 1
make[3]: Leaving directory '/home/pi/openalpr/libraries/tesseract/arch'
Makefile:584: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/pi/openalpr/libraries/tesseract/arch'
Makefile:478: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/openalpr/libraries/tesseract'
Makefile:386: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by amitdo** [comment]
In arch/Makefile.am, disable or remove these lines:

>libtesseract_avx_la_CXXFLAGS = -mavx
libtesseract_sse_la_CXXFLAGS = -msse4.1

The code in master is in 'alpha' state and the support for ARM seems to be less good than for x86.

**Comment by amitdo** [comment]
@zdenop, @stweil 

We need to get the CPU type in configure.ac and add a condition around those lines in the Makefile.am.

**Comment by zdenop** [comment]
@yakeer: if tesseract is dependency for other library/application I would suggest to use stable release [3.04.01](https://github.com/tesseract-ocr/tesseract/releases/tag/3.04.01) or [3.05 branch](https://github.com/tesseract-ocr/tesseract/tree/3.05) (bug fixes for 3.04 version with small enhancement of API)

**Comment by zdenop** [comment]
@yakeer: please check current master if it compile on Raspberry Pi 3.

**Comment by Shreeshrii** [comment]
I got this error with latest master (commit c124f87d5ba974c7854cfc857f5f2b0cb5236f61
) - it worked before (first week of dec)

```
checking host system type... x86_64-unknown-linux-gnu
./configure: line 4228: syntax error near unexpected token `-mavx,'
./configure: line 4228: `AX_CHECK_COMPILE_FLAG(-mavx, avx=1, avx=0)'
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --enable-debug --no-create --no-recursion
checking for g++... g++
```

```
checking host system type... x86_64-unknown-linux-gnu
./configure: line 4229: syntax error near unexpected token `-msse4.1,'
./configure: line 4229: `AX_CHECK_COMPILE_FLAG(-msse4.1, sse41=1, sse41=0)'
/bin/bash ./config.status --recheck

```

I was able to get around it by commenting out the following 2 lines in configure.ac

```
## Checks for supported compiler options.
AM_CONDITIONAL([AVX_OPT], false)
AM_CONDITIONAL([SSE41_OPT], false)
##AX_CHECK_COMPILE_FLAG([-mavx], [avx=1], [avx=0])
##AX_CHECK_COMPILE_FLAG([-msse4.1], [sse41=1], [sse41=0])
```

**Comment by zdenop** [comment]
`sudo apt-get install autoconf-archive`
see: http://stackoverflow.com/questions/30412576/autotools-syntax-error-with-ax-check-compile-flag

**Comment by Shreeshrii** [comment]
@zdenop  Thanks! It works now.

**Comment by stweil** [comment]
Is this still an issue, or can it be closed? I could successfully compile Tesseract on Raspbian using configure / make.
