### ISSUE TITLE
ParamsModel::Incomplete line errors when using Vietnamese / VIE language

### ISSUE THREAD

**Issue by AR0x7E7** [tesseract-ocr/tesseract#602]
Hi there, tired to run following command on the attached Image:

`$ tesseract TH.jpg outbutbase -l vie -psm 7`

![th](https://cloud.githubusercontent.com/assets/1496858/21446802/66d4839c-c8fd-11e6-8550-942a48363229.jpg)

Getting only "ParamsModel::Incomplete line" erros, see here:
![2016-12-23_10h46_01](https://cloud.githubusercontent.com/assets/1496858/21446813/9528b056-c8fd-11e6-8e9b-1634cd763e6e.jpg)

Specs: 
Windows Server 2012R2

```
C:\Users\Administrator\Desktop\Tesseract-OCR>tesseract --version
tesseract 3.05.00dev
 leptonica-1.73
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0
```

Installed Vietnamese language during setup wizard

**Comment by zdenop** [comment]
see comments in https://github.com/tesseract-ocr/tesseract/issues/373
