### ISSUE TITLE
Warning in pixReadMemPng: work-around: writing to a temp file

### ISSUE THREAD

**Issue by amtlab** [tesseract-ocr/tesseract#606]
I installed tesseract using sudo port install tesseract tesseract-eng.
I took a screenshot using command+shift+3 on Mac, and try to ocr the screenshot. However, I get the following message, and the output file is empty.
$ tesseract screenshot.png output
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Warning in pixReadMemPng: work-around: writing to a temp file
What might be causing this?
Thanks for your help!

**Comment by amitdo** [comment]
You should ignore this message.

**Comment by amtlab** [comment]
Regardless the message, the output is empty. Is it an error? Thanks!

**Comment by stweil** [comment]
I cannot say whether this is an error without seeing the screenshot – did it contain text?

Usually text in a screen-shot has a low resolution, something typically at most 120 dpi. For Tesseract, 300 dpi are suggested. You can try to rescale your screen-shot. Or you can try the experimental Tesseract 4.

**Comment by amtlab** [comment]
Thank you for helping with this.
Yes, definitely has text.
When I try to build tesseract from source, I get this from ./configure
checking host system type... x86_64-apple-darwin16.1.0
./configure: line 4237: syntax error near unexpected token `-mavx,'
./configure: line 4237: `AX_CHECK_COMPILE_FLAG(-mavx, avx=1, avx=0)'
Is there prebuilt binary for tesseract 4 for Mac somewhere?

**Comment by amitdo** [comment]
See https://github.com/tesseract-ocr/tesseract/issues/601#issuecomment-269197286
You need an equivalent package for Mac.

**Comment by amtlab** [comment]
Do you happen to know what that might be? I searched mavx on macports, but nothing turned up.

**Comment by amitdo** [comment]
https://www.macports.org/ports.php?by=library&substr=autoconf-archive

**Comment by amitdo** [comment]
>Warning in pixReadMemPng: work-around: writing to a temp file

You won't see this message with leptonica 1.74.2 and above.

https://github.com/DanBloomberg/leptonica/commit/aa21bcc4be077c5

**Comment by amitdo** [comment]
@zdenop, please close this issue.
