### ISSUE TITLE
c1ee2fe - not working with 4.0alpha traineddata

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#609]
Please see https://github.com/manisandro/gImageReader/issues/141#issuecomment-269117278

The program works with the older traineddata files but not the new 4.0 version. I thought that the master branch will be compatible with 4.0 traineddata...

It will be good to have separate instructions for building 3.05 and 4.0 versions. 

Which snapshot is recommended to use for 4.0.0alpha? Thanks!

**Comment by amitdo** [comment]
>Which snapshot is recommended to use for 4.0.0alpha? Thanks!

3rd party tools should build against 3.04.1 or maybe 3.05.

**Comment by amitdo** [comment]
Maybe you use 3.04 traineddata with Tesseract 4.00 ...

**Comment by Shreeshrii** [comment]
Amit,
3.04 data is working with it. 4.0 version is not working.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
He is just making a test build for me to test 4.0 with gui.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
FYI, the version I had built in early Dec under bash on windows10 from
master works with the 4.0 traineddata.

I can try building it again tomorrow and check.

- excuse the brevity, sent from mobile

**Comment by amitdo** [comment]
>He is just making a test build for me to test 4.0 with gui.

The master is a moving target. If he wants to build against 4.00 he should use the latest snapshot that can be compiled.

**Comment by amitdo** [comment]
Shree,
If you'll still have this issue, please provide more info than just 'not working'.

**Comment by amitdo** [comment]
look at your tessdata folder. You can check the size of the a traineddata file and compare it to the one in the repo.

For Hindi
https://github.com/tesseract-ocr/tessdata/blob/4.00/hin.traineddata
24.6 MB
vs.
https://github.com/tesseract-ocr/tessdata/blob/3.04.00/hin.traineddata
13.5 MB

**Comment by amitdo** [comment]
Remember that we can only support our code. If there is a issue with a 3rd party program that can't be demonstrated with the Tesseract command line program, this is not the right place to report about it.

**Comment by Shreeshrii** [comment]
Thanks. I am building the latest snapshot to test in command mode.
