### ISSUE TITLE
Error: LSTM requested, but not present!! Loading tesseract.

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#611]
When using traineddata version 3.04 (san.traineddata renamed as sa34.traineddata for testing) and explicitly requesting LSTM engine, the following Error is produced. However, program loads tesseract and continues to process the page.

Label could be changed from 'Error' to 'Warning' ...

```
tesseract san001.jpg san001-sa34 --oem 1 -l sa34
Error: LSTM requested, but not present!! Loading tesseract.
Tesseract Open Source OCR Engine v4.00.00alpha-204-g8b3c6ac with Leptonica
Detected 18 diacritics

real    2m17.554s
user    2m15.719s
sys     0m0.922s

```

**Comment by Wikinaut** [comment]
You have to **update** the traineddata.

I had the same message, and then updated my locally outdated traineddata (pulled it from https://github.com/tesseract-ocr/tessdata.git ) - problem solved.

In my view, this issue can be closed.

**Comment by sezanzeb** [comment]
Did that as well, but am still getting the error message.

The versions in the arch repos are

```
community/tesseract-data-deu_frak 2:4.1.0-3
community/tesseract 5.2.0-2
```
