### ISSUE TITLE
Linking error for Training Tools on Windows with VS 2015

### ISSUE THREAD

**Issue by solomennikm** [tesseract-ocr/tesseract#612]
After making VS solution with next steps:
 cd tesseract
 cppan
 mkdir build
 cd build
 cmake ..

I want to build text2image project, but build failed with errors:
 
text2image.obj : error LNK2019: unresolved external symbol "struct tesseract::ParamsVectors * __cdecl GlobalParams(void)" (?GlobalParams@@YAPAUParamsVectors@tesseract@@XZ) referenced in function "void __cdecl `dynamic initializer for 'FLAGS_bidirectional_rotation''(void)" (??__EFLAGS_bidirectional_rotation@@YAXXZ)
pango_font_info.obj : error LNK2001: unresolved external symbol "struct tesseract::ParamsVectors * __cdecl GlobalParams(void)" (?GlobalParams@@YAPAUParamsVectors@tesseract@@XZ)
tlog.obj : error LNK2001: unresolved external symbol "struct tesseract::ParamsVectors * __cdecl GlobalParams(void)" (?GlobalParams@@YAPAUParamsVectors@tesseract@@XZ)
common_training.lib(commandlineflags.obj) : error LNK2001: unresolved external symbol "struct tesseract::ParamsVectors * __cdecl GlobalParams(void)" (?GlobalParams@@YAPAUParamsVectors@tesseract@@XZ)
text2image.obj : error LNK2019: unresolved external symbol "public: __thiscall UNICHARSET::UNICHARSET(void)" (??0UNICHARSET@@QAE@XZ) referenced in function _main
...

tesseract.exe was built and work fine.
text2image project has references on tesseract project and dependencies from ..\Debug\tesseract305d.lib

**Comment by amitdo** [comment]
This is a known issue. See https://github.com/tesseract-ocr/tesseract/pull/595#issuecomment-268362325

**Comment by solomennikm** [comment]
This issue is about Leptonica and other libs, but in my case problem seems is with resolving symbols from tesseract main library that itself built fine, Not only in text2image but also in other Training Tools, for example ambiguous_words:

ambiguous_words.obj : error LNK2019: unresolved external symbol "public: __thiscall WERD_CHOICE::WERD_CHOICE(char const *,class UNICHARSET const &)" (??0WERD_CHOICE@@QAE@PBDABVUNICHARSET@@@Z) referenced in function _main
ambiguous_words.obj : error LNK2019: unresolved external symbol "public: __thiscall WERD_CHOICE::~WERD_CHOICE(void)" (??1WERD_CHOICE@@QAE@XZ) referenced in function _main
ambiguous_words.obj : error LNK2019: unresolved external symbol "public: bool __thiscall tesseract::Dict::NoDangerousAmbig(class WERD_CHOICE *,class GenericVector<struct DANGERR_INFO> *,bool,class MATRIX *)" (?NoDangerousAmbig@Dict@tesseract@@QAE_NPAVWERD_CHOICE@@PAV?$GenericVector@UDANGERR_INFO@@@@_NPAVMATRIX@@@Z) referenced in function _main

**Comment by egorpugin** [comment]
text2image cannot be built with cmake on windows.
Let me try  to build tess with your steps. (I'll report here.)

**Comment by egorpugin** [comment]
Works for me. What version of tesseract are you using?
I've already fixed issue you report on master, but not on other branches.

**Comment by solomennikm** [comment]
There is some other details. To make cmake work I download gtk+ from 
https://dl.hexchat.net/gtk-win32/vc14/x86/gtk-Win32.7z
set PKG_CONFIG_PATH=D:/gtk/win32/lib/pkgconfig
after cmake I also add paths 
D:\gtk\Win32\include
and
D:\gtk\Win32\lib
in text2image project

**Comment by solomennikm** [comment]
I am using last sources from github from master

**Comment by egorpugin** [comment]
Oh, you probably have old cmake.
Which cmake version do you have?
3.6 is known to not work with tess right now (your errors).

**Comment by solomennikm** [comment]
Really, I have 3.6.2, I will try 3.7.1. Thank you.

**Comment by solomennikm** [comment]
Great! It was built. Thanks again.

**Comment by egorpugin** [comment]
I'll add an error message for cmake 3.6 (on cppan side).
