### ISSUE TITLE
I need help training Tesseract 4.0

### ISSUE THREAD

**Issue by christophered** [tesseract-ocr/tesseract#615]
Hi there,
I am ready to test Tesseract 4.0 to make sure that the Arabic Language is not forgotten, but I am facing alot of problems in the training process, I know that Ray has done a great job in this version by documenting everything, but still i need some help.

Can somebody list the commands, line-by-line, from creating a tif+box from the text that i've attached, to creating an "ara.traineddata" assuming the font is timesnewroman.
My text is only 22 words, Download the text:  [arabic1.txt](https://github.com/tesseract-ocr/tesseract/files/673277/arabic1.txt)

**Do not , I repeat, Don't direct me to the documentation page, I need line-by-line help**
Thank you

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00---Finetune

**Comment by christophered** [comment]
@Shreeshrii
Thanks, your an amazing contributor
