### ISSUE TITLE
TesseractError: (-11, 'Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica\nDetected 386 diacritics\nFound AVX\nFound SSE')

### ISSUE THREAD

**Issue by nolsigan** [tesseract-ocr/tesseract#619]
Hi, I've got this error suddenly

```
TesseractError: (-11, 'Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica\nDetected 386 diacritics\nFound AVX\nFound SSE')
```

Can anyone help me with this error? I have no idea what's causing the problem.
It worked fine on every other images I have

**Comment by Shreeshrii** [comment]
Are you using a different language for this image?

**Comment by Shreeshrii** [comment]
This is usually not an error, just an info message. Your output file should be created.

**Comment by amitdo** [comment]
>Detected 386 diacritics

Sometimes, this means the image has lot of 'noise'.

**Comment by zdenop** [comment]
First of all: It seem like output from some tesseract wrapper. We do not provide support for 3d party sw. 
Next: Use tesseract user forum for asking support. Please follow [instruction](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md) and make sure you read [wiki first](https://github.com/tesseract-ocr/tesseract/wiki) (at least FAQ and ImproveQuality).

**Comment by nolsigan** [comment]
I was using python wrapper and yes, it seems like it's not an error but wrapper considers it as an error and terminates process.

I just made program skip those particular images when it throws exception.

Thanks all for your comments and I will be sure to ask on user forum next time 😃
