### ISSUE TITLE
expanded from macro 'clock_gettime'

### ISSUE THREAD

**Issue by ruochenxing** [tesseract-ocr/tesseract#621]
I find this:https://github.com/civetweb/civetweb/pull/356

macOS Sierra
use 'brew install tesseract' to install:

/usr/include/time.h:177:5: error: conflicting types for 'clock_get_time'
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
./openclwrapper.h:63:23: note: expanded from macro 'clock_gettime'
#define clock_gettime clock_get_time
                      ^
/usr/include/mach/clock.h:75:15: note: previous declaration is here
kern_return_t clock_get_time
              ^
1 error generated.
make[1]: *** [openclwrapper.lo] Error 1
make: *** [install-recursive] Error 1

thx!

**Comment by stweil** [comment]
That's not code from latest Tesseract. Please close this issue here and report it at the right place (wherever that is).

**Comment by ruochenxing** [comment]
fixed

**Comment by amitdo** [comment]
For some reason `3.05.00dev` does not have this fix: https://github.com/tesseract-ocr/tesseract/commit/8e9159b09155

https://github.com/tesseract-ocr/tesseract/blob/3.05.00dev/opencl/openclwrapper.h#L63

**Comment by zdenop** [comment]
@ruochenxing : can you please clarify if there was problem with tesseract (if yes which branch you used)? and how did you fix it?

**Comment by tangsipeng** [comment]
i found the same problem when i brew install 
i fix it by
comment   //#define clock_gettime clock_get_time
in  openclwrapper.h 
this may help https://github.com/balabit/syslog-ng/issues/1249
