### ISSUE TITLE
Khmer Language Support

### ISSUE THREAD

**Issue by choungchamnab** [tesseract-ocr/tesseract#622]
Do Tesseract support khmer language  ?

**Comment by stweil** [comment]
Please read the [documentation](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files).

**Comment by Shreeshrii** [comment]
@choungchamnab 

Please see comment by @theraysmith  at https://github.com/tesseract-ocr/tesseract/issues/654#issuecomment-274574951

If you are able to point to resources for building a text corpus for Khmer language, it will help in adding support for the language.

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tessdata/blob/master/khm.traineddata

**Comment by Shreeshrii** [comment]
On further testing,

khmer works with the 3.0x format traineddata or --oem 0. Using --oem 1 leads to only numbers and punctuation, as referred in https://github.com/tesseract-ocr/tesseract/issues/654 by Ray.

@zdenop , please reopen the issue, as khmer is not working  with --oem 1. Thanks.

Sample outputs attached.
[khm.Leelawadee_UI_Bold.exp0-0.txt](https://github.com/tesseract-ocr/tesseract/files/729037/khm.Leelawadee_UI_Bold.exp0-0.txt)
[khm.Leelawadee_UI_Bold.exp0-1.txt](https://github.com/tesseract-ocr/tesseract/files/729036/khm.Leelawadee_UI_Bold.exp0-1.txt)
