### ISSUE TITLE
DotProductSSE can't be used on Android, but im on a Debian.

### ISSUE THREAD

**Issue by m4n3dw0lf** [tesseract-ocr/tesseract#626]
$tesseract out.png result
Tesseract Open Source OCR Engine v4.00.00alpha-238-ge6ccfb2 with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.
DotProductSSE can't be used on Android
Abortado

I am on a debian not a android, there is a way to fix? i mess around a little bit with the arch/dotproductsse.cpp but i was not able to make it work, sorry about my english.

**Comment by amitdo** [comment]
What's the output of `uname -a`?

**Comment by m4n3dw0lf** [comment]
really?
Linux debian 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02) x86_64 GNU/Linux

**Comment by amitdo** [comment]
I wanted to make sure you are not on machine with ARM CPU.

**Comment by m4n3dw0lf** [comment]
i make my way out of that, now it works thnx.

**Comment by pevogam** [comment]
It would be great if you elaborated how exactly you solved your issue for others that experience the same problem. Since quite some time passed from Dec 29. 2016, I will open another issue.
