### ISSUE TITLE
Autotools configure error on OS X 10.11.6 (AX_CHECK_COMPILE_FLAG undefined)

### ISSUE THREAD

**Issue by bringhurst** [tesseract-ocr/tesseract#628]
This is using glibtoolize from homebrew for autogen.sh.

```
$ git clone https://github.com/tesseract-ocr/tesseract.git
Cloning into 'tesseract'...
remote: Counting objects: 15316, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 15316 (delta 8), reused 0 (delta 0), pack-reused 15293
Receiving objects: 100% (15316/15316), 35.47 MiB | 7.87 MiB/s, done.
Resolving deltas: 100% (11818/11818), done.
$ cd tesseract/
$ git rev-parse HEAD
3817aa3079e741bd3a98af11d489f7a332e71ab3
$ ./autogen.sh 
Running aclocal
Running libtoolize
./autogen.sh: line 74: libtoolize: command not found
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
glibtoolize: copying file 'config/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
./autogen.sh: line 75: libtoolize: command not found
Running autoheader
Running automake --add-missing --copy
configure.ac:316: installing 'config/compile'
configure.ac:87: installing 'config/config.guess'
configure.ac:87: installing 'config/config.sub'
configure.ac:69: installing 'config/install-sh'
configure.ac:69: installing 'config/missing'
api/Makefile.am: installing 'config/depcomp'
Running autoconf

All done.
To build the software now, do something like:

$ ./configure [--enable-debug] [...other options]
$ ./configure
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
Using git revision: 4.00.00alpha-239-g3817aa3
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of g++... gcc3
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
./configure: line 4237: syntax error near unexpected token `-mavx,'
./configure: line 4237: `AX_CHECK_COMPILE_FLAG(-mavx, avx=1, avx=0)'
$
```

So, it looks like AX_CHECK_COMPILE_FLAG is undefined on OS X.

This appears related to https://github.com/tesseract-ocr/tesseract/commit/02a6970cf361ae12e2e2b5374f87bd09b3802bfd#diff-67e997bcfdac55191033d57a16d1408a

Since this error is a bit cryptic, it might be nice to add a check to see if AX_CHECK_COMPILE_FLAG is defined is added, and perhaps print a message to give some guidance on how to get it (probably something in homebrew? upgrade autoconf maybe?).

A poor workaround for this error is to add http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_check_compile_flag.m4 to the project's m4 directory, then rerun autogen.sh before running configure again -- that gets around the error on my machine.

**Comment by amitdo** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/autoconf-archive.rb

**Comment by sirfz** [comment]
+1 on Ubuntu 16.04

```
$ ./configure --enable-debug                                                                                                                                              2 ↵
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
Using git revision: 4.00.00alpha-239-g3817aa3
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of g++... gcc3
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
./configure: line 4249: syntax error near unexpected token `-mavx,'
./configure: line 4249: `AX_CHECK_COMPILE_FLAG(-mavx, avx=1, avx=0)'
```

**Comment by zdenop** [comment]
-1 for laziness (not reading [doc](https://github.com/tesseract-ocr/tesseract/blob/master/INSTALL.GIT.md) and not searching other issues e.g. #601 and #610).

**Comment by amitdo** [comment]
Yesterday I added the missing dependency to this wiki page:
https://github.com/tesseract-ocr/tesseract/wiki/Compiling

**Comment by zdenop** [comment]
Information in INSTALL.GIT.md
<https://github.com/tesseract-ocr/tesseract/blob/master/INSTALL.GIT.md> is
there already 4 days...And of course: installing from source expect that
user is  familiar with compiling software on your operation system.


Zdenko

**Comment by sirfz** [comment]
Thanks for the info.

Note on your expectation of user-familiarity with compile software, I personally am not that familiar with c/c++ compilers since I barely do any programming in those languages but merely compile software using (usually) autoconf with simple steps.

I'm sure I'm not the only one, just for some perspective though I did find the solution immediately after posting my comment so I accept the -1 for laziness :)

**Comment by amitdo** [comment]
I'm sure I'm not the only one, just for some perspective though I did find the solution immediately after posting my comment so I accept the -1 for laziness :)
:+1: 

:laughing:

**Comment by bringhurst** [comment]
Hey @zdenop, if not keeping track of every package that I have installed makes me lazy, then I guess I'm lazy. :)

What about printing out something like "install autoconf-archive", instead of "syntax error near unexpected token"?

Would you accept a patch?

**Comment by zdenop** [comment]
Replying in reverse order ;-) (based on importance):

1. Patches are welcomed!
2. Error message is output of autoconf. Maybe other test for compiler parameter would be more suitable, but this one seems to be standard (based on few minutes of googling).
3. Installing sw from source without tracking dependencies (or at lease reading INSTALL file) is IMO nonsense.
