### ISSUE TITLE
OEM_LSTM_ONLY very slow

### ISSUE THREAD

**Issue by rudrabhoj** [tesseract-ocr/tesseract#632]
Using Tesseract 4 (libtesseract) in my project [decipher_text](https://github.com/rudrabhoj/decipher_text).
When I use OEM_TESSERACT_ONLY, it takes little over 7-8 seconds to complete the recognization of a page in English. But when I try to instead use OEM_LSTM_ONLY, it takes 10-15 minutes, if not more, to do the same. I am using i5 2400. Ubuntu 16.04 x86_64.

Part of code where this is used:
`  if (ocrUnit->process->Init(tessDataPath, languageArg, tesseract::OEM_LSTM_ONLY)){`  
    `//Again, handle error here`  
    `//`     
    `//`       
    `//`       
    `//`       
  `}`   

Entire file in which it was used could be seen [here](https://github.com/rudrabhoj/decipher_text/blob/master/src/Control/TesseractRecognize.cxx). (Note: File is from an older, stabler version)

**Comment by amitdo** [comment]
Hi,

Did you test it with the Tesseract command line?
How did you compile it? Did you use debug mode?
Can you provide an image?

**Comment by Shreeshrii** [comment]
Also see comments in https://github.com/tesseract-ocr/tesseract/issues/40

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by theraysmith** [comment]
Debug mode is known to be ~50x slower than optimized mode.
Please re-open if you are seeing this slow-down in optimized mode.
