### ISSUE TITLE
TessBaseAPI::ProcessPagesMultipageTiff has obsolete OpenCL code

### ISSUE THREAD

**Issue by jbreiden** [tesseract-ocr/tesseract#635]
https://github.com/tesseract-ocr/tesseract/issues/233
https://github.com/tesseract-ocr/tesseract/commit/11f205707eda769dbe6cc7d6839745f1b01a1d76

When this patch was submitted, we reduced multipage TIFF seeks O(n).
But that's only on the regular code path. The OpenCL code path is still O(n^3).
That's not really sensible. Recommend removing the OpenCL path from 
ProcessPagesMultipageTiff() and then thinking about next steps.

To be honest, it's pretty hard to keep code synchronized and I'm a little
curious why current approach was chosen, versus integrating
OpenCL calls directly into much lower level libraries such as Libtiff.
Libtiff is doing the actual computational work, such G4 decompression.

**Comment by amitdo** [comment]
Most of the OpenCL code should be part of Leptonica.

There are two questions here:
1. Does @DanBloomberg want this code in Leptonica?
2. Are the authors of the code willing to relicense it (Apache 2 -> BSD)

**Comment by amitdo** [comment]
The code is here: 
https://github.com/tesseract-ocr/tesseract/tree/master/opencl

**Comment by DanBloomberg** [comment]
Amit, there are several good reasons why this code should NOT be in leptonica.

(1) Maintenance: I (and any competent C programmer with a background in image processing and analysis) can maintain all of leptonica.  From the beginning of the leptonica project, I understood that maintenance is critical: over the lifetime of the library, the time spent fixing/improving it will far exceed the time spent on the first implementation.  There is no way I could fix errors in the low-level code in this file.

(2) Portability: We have enough trouble maintaining portability with just plain old ansi C over several OS platforms.  The operations here take it to another level: hardware.  What restrictions are there on the hardware for this code to be compiled properly?  Does it work seamlessly on all Intel processors?  What about AMD?  What about ioS and Android?

(3) Benefit: Are the multiple complications from introducing this code into leptonica worth the pain?  As Jeff said, we've already fixed the multipage tiff wrapper, so the time is now O(n), where n is the number of pages.  And this is just a wrapper into tifflib.  Most other operations that are easily parallellized are already fast enough for most applications. Leptonica is intended to be a general utility that gives good performance with a simple implementation.  Emphasis on simple. If in production for a particular application, it is necessary to speed up a particular low-level operation (such as convolution) this should be done as an adjunct to leptonica, not as part of it.

Other image processing libraries have a different genesis and philosophy.  OpenCV was built by Intel engineers in Russia, and is now maintained by Itseez.  It is large and heterogeneous, and might be a good place to house this Intel GPU-based image processing code.

**Comment by jbreiden** [comment]
Getting back to ProcessPagesMultipageTiff(), there is no work being done by Leptonica. It is just TIFF decode and all computation is being done by Libtiff. Anyway, the OpenCL code is now behind. It should either be re-synchronized, migrated to libtiff, or disabled. No sense in keeping it as an O(n^3) code path.

**Comment by amitdo** [comment]
OK Dan, thanks for your detailed response!

**Comment by jbreiden** [comment]
This would disable the inefficient OpenCL calls. It would have the side effect of turning fairly large quantities of Tesseract's OpenCL code into dead code.

```diff
--- baseapi.cpp.orig	2017-01-26 13:10:45.011521878 -0800
+++ baseapi.cpp	2017-01-26 13:11:12.511896362 -0800
@@ -980,26 +980,13 @@
                                             int tessedit_page_number) {
 #ifndef ANDROID_BUILD
   Pix *pix = NULL;
-#ifdef USE_OPENCL
-  OpenclDevice od;
-#endif  // USE_OPENCL
   int page = (tessedit_page_number >= 0) ? tessedit_page_number : 0;
   size_t offset = 0;
   for (; ; ++page) {
     if (tessedit_page_number >= 0)
       page = tessedit_page_number;
-#ifdef USE_OPENCL
-    if ( od.selectedDeviceIsOpenCL() ) {
-      pix = (data) ?
-          od.pixReadMemTiffCl(data, size, page) :
-          od.pixReadTiffCl(filename, page);
-    } else {
-#endif  // USE_OPENCL
       pix = (data) ? pixReadMemFromMultipageTiff(data, size, &offset)
                    : pixReadFromMultipageTiff(filename, &offset);
-#ifdef USE_OPENCL
-    }
-#endif  // USE_OPENCL
     if (pix == NULL) break;
     tprintf("Page %d\n", page + 1);
     char page_str[kMaxIntSize];
```

**Comment by zdenop** [comment]
@jbreiden: Thanks. Can you please discuss with Ray about rest of OpenCl code? It is simple not maintained (I took 2 years to get fixes for reported issues)

**Comment by jbreiden** [comment]
Last week Ray said he was still looking into removing the non LSTM recognizer, which is still in use for OSD which is orientation script detection. If that is successful, I think that 100% of the opencl code will be unused.  If that happens I suspect the next step is removal. (In general I like both AMD and the idea of faster computation to the GPU, but not enough to keep unmaintained code.)

**Comment by amitdo** [comment]
Here are the files with `#ifdef USE_OPENCL`:
https://github.com/tesseract-ocr/tesseract/blob/d55f462c9c/ccmain/thresholder.cpp#L267
https://github.com/tesseract-ocr/tesseract/blob/4ac54a27c6/ccstruct/otsuthr.cpp#L53
https://github.com/tesseract-ocr/tesseract/blob/e949812e63/textord/linefind.cpp#L590
