### ISSUE TITLE
Is it worth training Tesseract 4 for handwritten text

### ISSUE THREAD

**Issue by akash-flipkart** [tesseract-ocr/tesseract#637]
Hi,
I am woking on interpretation of handwritten text (English). I just stumbled upon the new version of tesseract and was wondering if the new version can support handwritten text after training. 

Any leads would be beneficial.

Thank you

**Comment by WilliamTambellini** [comment]
Here is what I found :
- using CNN for chinese char recognition : 
http://people.idsia.ch/~juergen/icdar2011a.pdf
- handwritten recognition using RNN & LSTM :
http://people.idsia.ch/~juergen/tpami_2008.pdf

**Comment by zdenop** [comment]
Please use tesseract user form for asking questions, support...
