### ISSUE TITLE
Why the box coordinates of box file and tsv file are different?

### ISSUE THREAD

**Issue by Tangzy7** [tesseract-ocr/tesseract#638]
I just drew the box according the output coordinates of box file and tsv file,  but I found they were different.

**Comment by zdenop** [comment]
Please provide files (input files, output files) that demonstrate your issue. also provide more information about you OS, tesseract etc.

**Comment by amitdo** [comment]
hocr & tsv use 'left, top, right, bottom' coordinates while box uses 'left, bottom, right, top'.
