### ISSUE TITLE
Compilation failure with gcc 4.4.7

### ISSUE THREAD

**Issue by WilliamTambellini** [tesseract-ocr/tesseract#640]
Compilation of 4.0.0alpha fails with gcc 4.4.7 (gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)):

`libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I../viewer -I/usr/local/include/leptonica -g -O2 -MT simddetect.lo -MD -MP -MF .deps/simddetect.Tpo -c simddetect.cpp  -fPIC -DPIC -o .libs/simddetect.o
In file included from ../ccutil/genericvector.h:29,
                 from ../ccutil/params.h:25,
                 from ../ccutil/tprintf.h:23,
                 from simddetect.cpp:19:
../ccutil/helpers.h: In member function ‘void tesseract::TRand::set_seed(const std::string&)’:
../ccutil/helpers.h:50: error: ‘hash’ is not a member of ‘std’
`

Steps to reproduce: under an "old" OS (centos6 for example) follow the autogen&configure&make compilation steps and see the compilation error.

Rootcause: std hash was not officially supported in gcc 4.4, only in the TechnicalReport "tr1" namespace i.e. : std::tr1::hash<T> ... 

Possible fix: perhaps just enforcing a "recent" gcc at configure time ?

**Comment by WilliamTambellini** [comment]
Good news: does compile correctly at least with gcc 4.8.

**Comment by WilliamTambellini** [comment]
Update: there was a AX_GCC_VERSION but that would be better to simply check that the compiler has std::hash: 
for example: "ax_cxx_have_hash" 
https://www.gnu.org/software/autoconf-archive/ax_cxx_have_hash.html
?

**Comment by amitdo** [comment]
The code makes use of a few c++ 11 features.

**Comment by WilliamTambellini** [comment]
Yep, C++11 seems now to be a must have at least for master/version 4.
So would you accept a pull request adding a std hash check to the autoconf script ?

**Comment by zdenop** [comment]
@WilliamTambellini: can you please post config.log and output from configure?

**Comment by WilliamTambellini** [comment]
@zdenop 
config.log:
[config.log.txt](https://github.com/tesseract-ocr/tesseract/files/690637/config.log.txt)
configure output:
[configure.out.txt](https://github.com/tesseract-ocr/tesseract/files/690648/configure.out.txt)

**Comment by amitdo** [comment]
it also use `nullptr` and `unique_ptr` and maybe other stuff.
For `unique_ptr` you need libstdc++ 4.6

**Comment by WilliamTambellini** [comment]
so perhaps a global cpp 11 check would be better:
https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx.html
?

**Comment by stweil** [comment]
Just a side though: adding that test will add a 2nd dependency on autoconf-archive. This is fine (autoconf-archive should be available for all relevant hosts) – but as autoconf-archive is often not installed, that case needs a more user friendly error message than today.

**Comment by amitdo** [comment]
The licence for `AX_CXX_COMPILE_STDCXX` is permissive:

>Copying and distribution of this file, with or without modification, are permitted in any medium without royalty provided the copyright notice and this notice are preserved. This file is offered as-is, without any warranty.

So maybe we can embed it in our codebase. We probably need approval from Ray for this.

**Comment by stweil** [comment]
If we had a simple way to detect whether `autoconf-archive` is missing, `autogen.sh` could also download the missing m4 flies when needed. I think this is possible even with a less permissive license.

**Comment by zdenop** [comment]
We already have test for c++11 support (without dependency on autoconf-archive). So it should be enough to modify test to produce error in case of missing c++11 support...

**Comment by amitdo** [comment]
>We already have test for c++11 support (without dependency on autoconf-archive). So it should be enough to modify test to produce error in case of missing c++11 support...

https://github.com/tesseract-ocr/tesseract/blob/38cb4acaf906configure.ac#L355

For g++ it will detect c++11 support for version >= 4.7.

**Comment by amitdo** [comment]
and for Clang version >= 3.0.
