### ISSUE TITLE
Inverse text problem found by Viewerdebugging

### ISSUE THREAD

**Issue by Tangzy7** [tesseract-ocr/tesseract#641]
I used Viewerdebugging and used "Recog Blob" to classify each Blob. I just found that some blobs are input as white-on-black text. However,some are black-on-white text. See the 2 images. The white-on-black text cannot be recognized correctly
![wechatimg11](https://cloud.githubusercontent.com/assets/23446696/21705811/2ba6f2ae-d3fd-11e6-8ee7-a48fef1a8940.jpeg)

![wechatimg12](https://cloud.githubusercontent.com/assets/23446696/21705816/37713a90-d3fd-11e6-9f33-fe8694c64144.jpeg)

**Comment by amitdo** [comment]
It looks like you are trying to OCR vertical (Chinese / Japanese) text.
https://github.com/tesseract-ocr/tesseract/issues/627#issuecomment-269644398uecomment-269644398

**Comment by zdenop** [comment]
This is a know behavior - for tesseract 4 and above you need to use black on white (or dark on light) images 
https://github.com/tesseract-ocr/tessdoc/blob/main/ImproveQuality.md#inverting-images
