### ISSUE TITLE
OCR recognition improvement for single word(s) behind a specially colored background

### ISSUE THREAD

**Issue by featureRequestOnly** [tesseract-ocr/tesseract#645]
hi, would be appreciated if there would be support for (all) colored falling words images at the game [typing maniac](http://www.mindjolt.com/typing-maniac.html). the troubley background colors are yellow, iced words and purple.

**Comment by craigtao** [comment]
“hi, would be appreciated if there would be support for (all) colored falling words images at the game typing maniac. the troubley background colors are yellow, iced words and purple.”

hi, what mean? i don't know

**Comment by amitdo** [comment]
See #1900

**Comment by amitdo** [comment]
@zdenop, please close this issue.
