### ISSUE TITLE
How to add desired character to existing language in tesseract 4.0

### ISSUE THREAD

**Issue by Tangzy7** [tesseract-ocr/tesseract#646]
I found the a desired character file in source training data. So I guessed that in language.traineddata there is information of desired character. How can I add my unique character like ↑↓ into trained language?

**Comment by Tangzy7** [comment]
I found the a desired character file in source training data. So I guessed that in language.traineddata there is information of desired character. How can I add my unique character like ↑↓ into trained language?

**Comment by zdenop** [comment]
Please use tesseract user forum for asking questions, support...
