### ISSUE TITLE
configure fails again

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#647]
git pull

5b45e5a236875b0c13bf70cddbaaafd7ac6760fe

```
./configure: line 4229: syntax error near unexpected token `-mavx,'
./configure: line 4229: `AX_CHECK_COMPILE_FLAG(-mavx, avx=1, avx=0)'
```

**Comment by amitdo** [comment]
You should install `autoconf-archive`

**Comment by Wikinaut** [comment]
Thanks, `autoconf-archive`appears to be a new prerequisite. I also had to update Leptonica to the new version (using the git repo version).

Remaining question:
Is there a quick way to check the Leptonica version as it is reported to Tesseract ?

For the record: my system reports now
```
$ tesseract  --version
tesseract 4.00.00alpha-245-g5b45e5a
 leptonica-1.74.1
  libjpeg 6b (libjpeg-turbo 1.3.1) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8
 Found AVX
 Found SSE
```

**Comment by Wikinaut** [comment]
(solved, but a question to @amitdo pending: Is there a quick way to check the Leptonica version as it is reported to Tesseract ? )

**Comment by amitdo** [comment]
`pkg-config --modversion lept`

Programmatically:
https://github.com/tesseract-ocr/tesseract/blob/534a23701577/api/tesseractmain.cpp#L53

**Comment by Wikinaut** [comment]
@amitdo thanks for perfect info!

**Comment by philippkeller** [comment]
`autoconf-archive` is not supported on redhat (and therefore on AWS AMI), see [this issue](https://bugzilla.redhat.com/show_bug.cgi?id=1313438). Is there a chance to get tesseract without that dependeny again?

**Comment by BudiKusasi** [comment]
> You should install autoconf-archive

How do we install autoconf-archive.. any one'd explain that in clear detail ?

**Comment by philippkeller** [comment]
@BudiKusasi did you try [this approach](https://github.com/tesseract-ocr/tesseract/issues/777#issuecomment-361896845)? (you probably did, because you also commented in this branch). In the end this worked for me
