### ISSUE TITLE
[Clarification request/bug?] "Warning. Invalid resolution 0 dpi. Using 70 instead."

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#649]
Current version https://github.com/tesseract-ocr/tesseract/commit/5b45e5a236875b0c13bf70cddbaaafd7ac6760fe gives always the `"Warning. Invalid resolution 0 dpi. Using 70 instead."`.

When tesseract cannot extract a resolution (for example, for `ppm` inputs), what will be the correct way to set a reasonable dpi ? The original dpi in my case was 200, or 300 in another case. 

It is not apparent from
`$tesseract --print-parameters` 
what option to set the correct value has to be used.

Please can you assist, is it a bug ?

**Comment by amitdo** [comment]
Tesseract uses Leptonica for getting the DPI.

For ppm, I think you only have one solution - to convert it to a more advanced format like png or tiff. 
https://linux.die.net/man/1/ppm2tiff

**Comment by Wikinaut** [comment]
@amitdo You are right, that there are more advanced lossless coding schemes, but `unpaper` (app for cleaning and preprocessing images) only works with `ppm` (or `pgm` or `pbm`), see https://github.com/Flameeyes/unpaper/blob/master/doc/file-formats.md .

In order to save further conversion time and lower SSD wear, I usually pass ppm to tesseract (if I use unpaper).

**Comment by CoCa520** [comment]
when I run tesseract to process image + box file to make training data set, I got: Warning. Invalid resolution 1 dpi. Using 70 instead. 
How can I deal with it？
