### ISSUE TITLE
LSTM: Training - <Undecodable>  ALIGNED TRUTH

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#650]
running training process for Sanskrit - Devanagari script, throws up errors such as the following, when using --debug_interval -1

```
Iteration 5010: ALIGNED TRUTH : द्ध्वा ल्गु ज्<Undecodable><Undecodable><Undecodable> द्द स्तू स्त्रे द्यो शाः स्वे न्ह 

Iteration 5034: ALIGNED TRUTH : खं चः द्धो ङ्गा भौ न्यं न्यु ज्<Undecodable><Undecodable> त्कृ वां निः

Iteration 5068: ALIGNED TRUTH : व्यः श्मि क्ष्ण खाः टी णिं त्सै न्तां ल्म ष्<Undecodable><Undecodable><Undecodable>
```

The relevant lines from training text are:

```
द्ध्वा ल्गु ज्ञां द्द स्तू स्त्रे द्यो शाः स्वे न्ह नुः

खं चः द्धो ङ्गा भौ न्यं न्यु ज्ञे त्कृ वां निः 

व्यः श्मि क्ष्ण खाः टी णिं त्सै न्तां ल्म ष्टिं 
```

Specifically the syllables giving error in this sample are `ज्ञां` `ज्ञे `ष्टिं`.

While first part of the conjunct is decoded, the later parts are not.

| Syllable | Devanagari characters | Unicode code points |
|---|---|---|
| ज्ञां | ज  ्  ञ  ा  ं  | U+091C U+094D U+091E U+093E U+0902 |
| ज्ञे | ज  ्  ञ  े | U+091C U+094D U+091E U+0947 |
| ष्टिं | ष  ्  ट  ि  ं | U+0937 U+094D U+091F U+093F U+0902 |
------------------------------------

**Comment by Shreeshrii** [comment]
These are there in san.unicharset being used by the training process.

```
ज्ञां 1 3,76,61,242,294,446,0,0,294,446 Devanagari 27 0 27 ज्ञां	# ज्ञां [91c 94d 91e 93e 902 ]x

ज्ञे 1 3,76,61,255,251,423,0,0,251,423 Devanagari 27 0 27 ज्ञे	# ज्ञे [91c 94d 91e 947 ]x

ष्टिं 1 3,76,61,253,238,384,0,0,238,384 Devanagari 52 0 52 ष्टिं	# ष्टिं [937 94d 91f 93f 902 ]x
```

**Comment by Shreeshrii** [comment]
```
Iteration 18247: ALIGNED TRUTH : مْهُعَبِاصَأَ نَولُعيَ<Undecodable><Undecodable> قٌربَوَ دٌعْرَوَ تٌامَلُظُ
Iteration 18247: BEST OCR TEXT : مْهُعَبِاصَأَ نَولُعيَ<Undecodable><Undecodable> قٌرْبَوَ دٌعْرَوَ تٌامَلُظُ
```

**Comment by theraysmith** [comment]
Added this to the training instructions:
`<Undecodable>` can occur in either the ALIGNED_TRUTH or OCR TEXT output early
in training. It is a consequence of unicharset compression and CTC training.
(See Unicharset Compression and train_mode above). This should be harmless and
can be safely ignored. Its frequency should fall as training progresses.
