### ISSUE TITLE
Inconsistent result of tesseract 3.04 in for loop

### ISSUE THREAD

**Issue by tgaudin** [tesseract-ocr/tesseract#652]
Hi,

I'm building a program where I need to run several times Tesseract on the same image. Hence I've noticed strange behavior of the OCR occurring when you run similar code:

```c++
for (int i = 0; i < 100; i++) {
	ocr->SetImage((unsigned char *) img.data, img.size().width, img.size().height, img.channels(), img.step1());
	ocr->SetPageSegMode(tesseract::PSM_SINGLE_WORD);
	ocr->Recognize(0);
	tesseract::ResultIterator* ri = ocr->GetIterator();
	if(ri != 0) {
		char *word;
		do {
			word = ri->GetUTF8Text(tesseract::RIL_SYMBOL);
			if(word != 0 ) {
				float conf = ri->Confidence(tesseract::RIL_SYMBOL);
				printf("-> word:%s, confidence: %f\n", word, conf );
			}
			delete[] word;
		} while((ri->Next(tesseract::RIL_SYMBOL)));

		delete ri;
	}
	ocr->Clear();
}
```
If the input image is ![alt text](https://cloud.githubusercontent.com/assets/14755997/21854516/4cef13a2-d81b-11e6-9f15-6b727fd54766.png) I get the following result:

```
-> word:P, confidence: 88.156876
-> word:P, confidence: 88.156876
-> word:I, confidence: 99.609375
-> word:I, confidence: 99.609375
-> word:I, confidence: 99.609375
...
```
Even stranger, this behavior only happens with some images.

I'm using Tesseract 3.04, and I tested this code on both Linux (Linux 4.1.5-1-ARCH x86_64) and OS X (Sierra 10.12.2) and I'm getting the same results.

**Comment by amitdo** [comment]
I don't know if it will help in this case, but try also calling `ClearAdaptiveClassifier()`.

**Comment by tgaudin** [comment]
It's actually working now! Interesting...
Thanks you very much @amitdo!
