### ISSUE TITLE
Arabic - text2image error

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#655]
In order to minimize the RTL/LTR effect, I created a training text file with arabic language text, one word per line. However the image generated by text2image has some pages with RTL text and some with LTR text i.e. aligned with right margin and left margin.

[ara.one-word-per-line.zip](https://github.com/tesseract-ocr/tesseract/files/701624/ara.one-word-per-line.zip)

**Comment by amitdo** [comment]
This behaviour is controlled by the pango library that text2image uses. It also happening with gedit, which  also uses pango.

**Comment by theraysmith** [comment]
That sounds like its working as intended.
