### ISSUE TITLE
Not recognizing number 8

### ISSUE THREAD

**Issue by kaitoqueiroz** [tesseract-ocr/tesseract#656]
I'm having a problem with number 8, it is read as 3...
I'm usin PSM 6, language english and pattern A to Z, 0 to 9 and ":" to ";"
Result:
![image](https://cloud.githubusercontent.com/assets/1447491/21891559/67411cec-d8ba-11e6-8fdd-98fb73780d66.png)

I already change PSM, but no success.
Anyone can help?

**Comment by zdenop** [comment]
use tesseract user forum for asking support
