### ISSUE TITLE
OpenCL failure of training tools on FreeBSD, cairo perhaps?

### ISSUE THREAD

**Issue by RNCTX** [tesseract-ocr/tesseract#663]
Hey guys, first of all, I've tried your new 4.0 version on OSX (built from source against homebrew dependencies) and it's fantastic, bravo.

I went to install it on my 11.0 FreeBSD NAS and discovered, however, that the CL build of the training tools does not work. The main program compiles and tests fine with OpenCL on Intel CPU libs, however.

Here's a paste of my attempt to build 'training', error at the bottom...

http://pastebin.com/LP4MDwmz

Your wiki suggests cairo2 being a requirement but such a thing does not exist?  FreeBSD seems to be pretty current on the cairo library and it's still on 1.xx per the official site. Am I missing something in regard to the existence of a cairo v2? Or is that cairo2 reference to some ancillary cairo project that I'm not aware of?

Relevant dependencies on my system and where they came from (FreeBSD 11.0 release, amd64)...

tesseract 4.0 pulled from here on git today
gcc-4.9.4 (pkg binary)
beignet-1.2.0 (pkg binary OpenCL implementation for Intel)
opencl-2.1 (pkg binary)
autoconf-2.69_1 (pkg binary)
autoconf-archive-0.2016.09.16 (pkg binary)
libtool-2.4.2_3 (pkg binary)
pkgconf-0.9.7 (pkg binary)
png-1.6.27 (pkg binary)
jpeg-turbo-1.5.1 (pkg binary)
tiff-4.0.7_1 (pkg binary)
zlib1g (n/a, integral to base system)
icu-58.2,1 (pkg binary)
pango-1.38.0_1 (pkg binary)
cairo-1.14.6_1,2 (pkg binary)
leptonica (1.74 built from today's git source)

**Comment by Shreeshrii** [comment]
You need the 'dev' packages for it.

See https://www.cairographics.org/download/

You maybe able to install the debian packages with dpkg

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by RNCTX** [comment]
FreeBSD (generally) has combined binary and lib packages into one for most things. Lemme check on cairo, though... will reply back.

**Comment by Shreeshrii** [comment]
You need 'development' version of packages for building

if you plan to install the training tools, you also need the following
libraries:

sudo apt-get install libicu-dev
sudo apt-get install libpango1.0-dev
sudo apt-get install libcairo2-dev

You also need to install Leptonica <http://www.leptonica.org/>.

One option is to install the distro's Leptonica package:

sudo apt-get install libleptonica-dev

but if you are using an oldish version of Linux, the Leptonica version may
be too old, so you will need to build from source.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by RNCTX** [comment]
Its BSD, not Linux.

Yes, I installed the Leptonica source via their git, it works fine. I'm assuming that the issue here is CL related since both the main binary and the training tools build fine without CL enabled.

The BSD cairo package mentioned in the first post includes the same libs that the debian package does, so is the correct one.  FreeBSD does not separate lib and binary packages anymore, they combine them.

https://svnweb.freebsd.org/ports/head/graphics/cairo/pkg-plist?revision=406748&view=markup

https://packages.debian.org/sid/amd64/libcairo2-dev/filelist

**Comment by amitdo** [comment]
Looks like something is wrong with your OpenCL installation.

Please also provide output of `./configure.`

**Comment by RNCTX** [comment]
https://gist.github.com/anonymous/94fdb0f9cec4f085476f842bced1351d

**Comment by RNCTX** [comment]
After some further investigation on this, I'm going to call it a pkg error from FreeBSD that I'll have to sort through myself.  I found a couple of conflicting libs for other ports on this machine that were installed as dependencies, and worse yet installed in oddball locations.  If anyone else should stumble across this with FreeBSD that's where to look (pkgconfig settings/outputs), they have made a mess of switching package management tools in that OS and it seems the users are left to their own devices to fix it.

In my case, I'm using portmaster to verify installed packages and search for conflicting libraries, and consolidating *.pc files into the current preferred pkgconfig directory under /usr/local/lib (which was not the preferred pkgconfig directory when they released their last major revision of their new package management too, it apparently preferred /usr/local/share).

This issue can be marked closed.
