### ISSUE TITLE
Please fix the compile with clang

### ISSUE THREAD

**Issue by yurivict** [tesseract-ocr/tesseract#67]
````
In file included from ./blamer.h:27:
./matrix.h:292:63: error: reinterpret_cast from 'nullptr_t' to 'BLOB_CHOICE_LIST *' is not allowed
    : BandTriMatrix<BLOB_CHOICE_LIST *>(dimension, bandwidth, NOT_CLASSIFIED) {}
                                                              ^~~~~~~~~~~~~~
./matrix.h:33:24: note: expanded from macro 'NOT_CLASSIFIED'
#define NOT_CLASSIFIED reinterpret_cast<BLOB_CHOICE_LIST*>(NULL)
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````

clang-3.4.1

**Comment by zdenop** [comment]
I am not able to reproduce error with clang version 3.7.0 on opensuse 42.1 64bit...

**Comment by amutu** [comment]
I can repreduce this error
[xx@ ~/work/tesseract-3.04.01]$ clang --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.3
Thread model: posix

**Comment by amutu** [comment]
and also 11.0RC2 with clang 3.8.0：
[~/work_space/tesseract-3.04.01]$ clang --version
FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
Target: x86_64-unknown-freebsd11.0
Thread model: posix
InstalledDir: /usr/bin

ibtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I../cutil -I../viewer -I../opencl -I/usr/local/include/leptonica -g -O2 -std=c++11 -MT blread.lo -MD -MP -MF .deps/blread.Tpo -c blread.cpp  -fPIC -DPIC -o .libs/blread.o
--- blamer.lo ---
In file included from blamer.cpp:21:
In file included from ./blamer.h:27:
./matrix.h:292:63: error: reinterpret_cast from 'nullptr_t' to 'BLOB_CHOICE_LIST *' is not allowed
    : BandTriMatrix<BLOB_CHOICE_LIST *>(dimension, bandwidth, NOT_CLASSIFIED) {}
                                                              ^~~~~~~~~~~~~~
./matrix.h:33:24: note: expanded from macro 'NOT_CLASSIFIED'
#define NOT_CLASSIFIED reinterpret_cast<BLOB_CHOICE_LIST*>(NULL)
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by amutu** [comment]
I see the HEAD already include the fix,thanks!
