### ISSUE TITLE
LSTM: Training - Box file format

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#670]
@theraysmith 

Two different types of box file formats are mentioned in Training Tesseract 4.0 wiki.

Please see attached and confirm the format (specially for the Wordstr format). The lstmf files created by the two box/tiff pairs are different in size, even though they are for the same tif file.

[frk.embedsiver.exp0.zip](https://github.com/tesseract-ocr/tesseract/files/721095/frk.embedsiver.exp0.zip)

**Comment by Shreeshrii** [comment]
I created the files using the following batch file:

```
    img_files=${img_files}' '$(ls frk*.tif)
    for img_file in ${img_files}; do
       echo ${img_file} "lstm.train"
        time tesseract "${img_file}" "${img_file%.*}"  -l deu_frak lstm.train
    done    
```

**Comment by Shreeshrii** [comment]
When using the WordStr format in one of the box files, 

```
WordStr 1350 3106 1755 3190 0 #Personer.
WordStr 895 2861 1194 2927 0 #Møller. 
WordStr 895 2742 1528 2811 0 #Emilie, hans Kone.
WordStr 899 2618 1507 2691 0 #Birch, Cancelliraad.
WordStr 894 2497 1546 2567 0 #Laura, hans Datter.
WordStr 895 2377 1317 2447 0 #Fru Krogh.
WordStr 897 2256 1724 2329 0 #Otto Rosen, Fuldmægtig.
WordStr 896 2134 1759 2207 0 #Anders,Tjener hos Birch.
WordStr 898 2015 1669 2085 0 #EnTjener hos Møller.
WordStr 696 1746 2422 1821 0 #Handlingen foregaaer i Kjøbenhavn, i Slutningen af 1848.
```
I get an error (utf8 buffer too big) during processing and the unicharset is not built fully (stops at that line and does not process other box files, but does not stop)
```
=== Phase UP: Generating unicharset and unichar properties files ===
[Sat Jan 21 18:53:04 DST 2017] /usr/local/bin/unicharset_extractor -D /tmp/tmp.hxOIFoYXPH/frk/ /tmp/tmp.hxOIFoYXPH/frk/frk.embedsiver.exp0.box /tmp/tmp.hxOIFoYXPH/frk/
frk.embedsiverline.exp0.box /tmp/tmp.hxOIFoYXPH/frk/frk.UnifrakturMaguntia.exp0.box /tmp/tmp.hxOIFoYXPH/frk/frk.Walbaum-Fraktur.exp0.box
**Utf8 buffer too big, size=57 for Handlingen foregaaer i Kjøbenhavn, i Slutningen af 1848.**
Extracting unicharset from /tmp/tmp.hxOIFoYXPH/frk/frk.embedsiver.exp0.box
**Extracting unicharset from /tmp/tmp.hxOIFoYXPH/frk/frk.embedsiverline.exp0.box**
Extracting unicharset from /tmp/tmp.hxOIFoYXPH/frk/frk.UnifrakturMaguntia.exp0.box
Extracting unicharset from /tmp/tmp.hxOIFoYXPH/frk/frk.Walbaum-Fraktur.exp0.box
Wrote unicharset file /tmp/tmp.hxOIFoYXPH/frk//unicharset.
[Sat Jan 21 18:53:04 DST 2017] /usr/local/bin/set_unicharset_properties -U /tmp/tmp.hxOIFoYXPH/frk/frk.unicharset -O /tmp/tmp.hxOIFoYXPH/frk/frk.unicharset -X /tmp/tmp
.hxOIFoYXPH/frk/frk.xheights --script_dir=../langdata
Loaded unicharset of **size 48** from file /tmp/tmp.hxOIFoYXPH/frk/frk.unicharset
```
If I do not use this box file, then the unicharset is built with all of the box files
```
=== Phase UP: Generating unicharset and unichar properties files ===
[Sat Jan 21 18:58:01 DST 2017] /usr/local/bin/unicharset_extractor -D /tmp/tmp.wyo1280N2G/frk/ /tmp/tmp.wyo1280N2G/frk/frk.embedsiver.exp0.box /tmp/tmp.wyo1280N2G/frk/
frk.UnifrakturMaguntia.exp0.box /tmp/tmp.wyo1280N2G/frk/frk.Walbaum-Fraktur.exp0.box
Extracting unicharset from /tmp/tmp.wyo1280N2G/frk/frk.embedsiver.exp0.box
Extracting unicharset from /tmp/tmp.wyo1280N2G/frk/frk.UnifrakturMaguntia.exp0.box
Extracting unicharset from /tmp/tmp.wyo1280N2G/frk/frk.Walbaum-Fraktur.exp0.box
Wrote unicharset file /tmp/tmp.wyo1280N2G/frk//unicharset.
[Sat Jan 21 18:58:02 DST 2017] /usr/local/bin/set_unicharset_properties -U /tmp/tmp.wyo1280N2G/frk/frk.unicharset -O /tmp/tmp.wyo1280N2G/frk/frk.unicharset -X /tmp/tmp
.wyo1280N2G/frk/frk.xheights --script_dir=../langdata
Loaded unicharset of **size 143** from file /tmp/tmp.wyo1280N2G/frk/frk.unicharset
Setting unichar properties

```

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/a75ab450a8cc9a2b69cf05f5c4f7a39bc44cbacc/ccmain/applybox.cpp#L71

**Comment by Shreeshrii** [comment]
@amitdo Thanks for pointing out that the string needs to be space delimited. I tried with that version also, it is also getting an error...

Ref: https://github.com/amitdo/tesseract/issues/3#issuecomment-274262671

**Comment by amitdo** [comment]
I updated relevant wiki [section](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#creating-training-data).

`unicharset_extractor` needs some more code to read the textline (`WordStr`) format right.

**Comment by theraysmith** [comment]
@amitdo is correct. unicharset_extractor doesn't read the WordStr box file format.
Sorry this is an un-tested path.
Furthermore, it isn't just a case of modifying unicharset_extractor.
For the Indic languages, the unicharset needs to know the syllable/grapheme clusters, and it can't get that from the Wordstr box file format. The best it can do is extract the unicodes used in the WordStr box file or you start with an existing unicharset for that training path.

**Comment by Shreeshrii** [comment]
Duplicate - https://github.com/tesseract-ocr/tesseract/issues/832

**Comment by Shreeshrii** [comment]
@theraysmith Please also see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/Xu4_aOCFhlQ/Yb2G59zTAgAJ about 
Training Tesseract4.0 (LSTM) on word level bounding boxes

Will this be addressed when you update the unicharset_extractor?

I am wondering whether there is a way to use the `text2image` algorithm to create box files given image and ground truth files.

**Comment by amitdo** [comment]
Ray, please consider a new box format with new name - '<lang>-linebox' for training the LSTM engine, For example see here:
https://github.com/tesseract-ocr/tesseract/issues/832#issuecomment-298688350

**Comment by christophered** [comment]
@Shreeshrii @amitdo any updates regarding this matter?

**Comment by c-c-3** [comment]
Are there difference between box file formats of tesseract 3 and tesseract 4? Or we can use box and tiff pairs of tesseract 3 to train tessearact 4 and can we use the starter trained data of tesseract 4 generated using the tesstrain.sh command.

**Comment by Shreeshrii** [comment]
Wordstr format done via https://github.com/tesseract-ocr/tesseract/commit/15f2a4b2c166ad18fe8d980e303d5052a47c37d3

lstmbox format done via https://github.com/tesseract-ocr/tesseract/commit/2ae65b2493dfb90d73212ba58e94c428fc870b0e
