### ISSUE TITLE
Allow attaching of box and tif files to issues

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#672]
If possible, please allow for .box and .tif extensions to be uploaded as attachments to issues.

Currently, we have to change image format and give extension of .txt for box files or upload in a zip file.

Thanks!

**Comment by amitdo** [comment]
This is github restriction. There is no way to change it.

A possible solution - make a zip file out of the files you wants to attach.

**Comment by Shreeshrii** [comment]
Thanks!
