### ISSUE TITLE
Is that possible to get the text from the price tag in that photo?

### ISSUE THREAD

**Issue by andersonlin** [tesseract-ocr/tesseract#676]
hello~

I've tried this command but cannot get correct text (the version is 3.0.4 with chi_sim.traineddata data file).

command: tesseract h1.jpg stdout -l chi_sim

photo: ![h1](https://cloud.githubusercontent.com/assets/743123/22244016/d5fd61fa-e264-11e6-9a55-cd2db095f216.jpg)

**Comment by zdenop** [comment]
Please use tesseract user forum for asking questions/support
