### ISSUE TITLE
Does Tesseract Actually Deskew the Image?

### ISSUE THREAD

**Issue by PedroBarcha** [tesseract-ocr/tesseract#677]
Hi there,
I've been reading Tesseract's code and I've realized that are several skew estimation functions around. However I am really confused: does Tesseract actually deskew the image? 
Here [1] we find that "The line finding algorithm is designed so that a skewed page can be recognized without having to de-skew, thus saving loss of image quality." Does it mean that no deskewing is done?
On the other hand, I've seen some posts around Tesseract's Google Groups referring to Leptonica's deskewing algorithm, even though I couldn't find any call to it's functions anywhere in Tesseract's code.
So, can anyone explain the real deal to me?
Thanks in advance!
(I'm sorry to post this here, I've tried tesseract's Google Groups but got no answer)
[1]:https://github.com/tesseract-ocr/docs/blob/master/tesseracticdar2007.pdf

**Comment by akiradeveloper** [comment]
I am concerning this topic too.

According to the wiki below, it seems Tesseract does deskewing internally but it didn't recognize any text when I passed a image that's 45 degrees skewed. Then I am wondering why.

https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

**Comment by akiradeveloper** [comment]
I use tessedit_write_images config to see the preprocessed image.

The original image is this (found in google)

![130909_1](https://cloud.githubusercontent.com/assets/785824/26772220/21add7ae-49ff-11e7-8ad7-574eb5b57299.jpg)

and the tessinput.tif is this

![tessinput](https://cloud.githubusercontent.com/assets/785824/26772263/535c376e-49ff-11e7-8891-10b76735db87.jpg)

I use PSM=6 and OEM=1 (line only). Is this the proof that tesseract does _not_ do any deskewing?

**Comment by akiradeveloper** [comment]
Also I found a discussion in tessseract-ocr https://groups.google.com/forum/#!topic/tesseract-ocr/yBsm8BWOVi4

**Comment by amitdo** [comment]
>I'm sorry to post this here, I've tried tesseract's Google Groups but got no answer

The issue tracker is not the right place for asking question.

https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md

>Sometimes you will not get a respond to your issue or question. We apologize in advance! Please don't take it personally. There can be many reasons for this, including: time limits, no one knows the answer (at least not the ones that are available at that time) or just that your question has been asked (and has been answered) many times before...
