### ISSUE TITLE
[ANDROID] imagedata.cpp doesn't compile

### ISSUE THREAD

**Issue by junteken** [tesseract-ocr/tesseract#678]
I want to upgrade my tesseract into 4.x in Android platform.
I pull the 4.0 source from github and copy it.

There is problem that is imagedata.cpp doesn't compile.
So I met link error which using that file.
I looked into 'obj' directory in ccstruct folder.
I can see the other files (blamer.o, blobbox.o...)
Only imagedata.cpp file doesn't exist.

What did I wrong? I checked Makfile.am which specify imagedata.cpp to be compile

Please help me~ :)

**Comment by amitdo** [comment]
Right now, the new LSTM engine in 4.0 is disabled for Android. 

This line appears multiple times.
>#ifndef ANDROID_BUILD

I suggest you to use 3.04.1 / 3.05 for the time being.

**Comment by junteken** [comment]
amitdo thank you for reply
