### ISSUE TITLE
LSTM: incorrect recognition with multilanguage text in one line

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#683]
Please see attached example of with English, Hindi and Arabic scripts in a single line.

[ara-hin-eng-tesseract.log.txt](https://github.com/tesseract-ocr/tesseract/files/734443/ara-hin-eng-tesseract.log.txt)
[ara-hin-eng.txt](https://github.com/tesseract-ocr/tesseract/files/734444/ara-hin-eng.txt)

![ara-hin-eng](https://cloud.githubusercontent.com/assets/5095331/22361161/144e6598-e47d-11e6-8af6-3bd8259bf8f8.png)

S ऐक्य aikya, s.m. Oneness, unity, singleness, identity, sameness,
harmony (=eRata); total, aggregate, product.

H %) UTU aigun [S. s.m. Unskilfulness, stupidity, &c.=augun,
५.५.

‎jval, uyyal, s.m. Stag; deer, hart; wild goat.‏ رزه ايل ـم
‎UedT ela, s .f. Cardamoms. (See ila.)‏ ايال ؟
‎H p) YTH ilam, s.m. Auction, public sale (=/ilam, nilam, q.q.v.).‏

‎£? elét, sm. Ambassador, envoy, delegate, agent:-elét karna, To _

‎

**Comment by Shreeshrii** [comment]
Another sample with English and Hindi


[Devanagari_ligatures_Monier-Williams_1846_enhanced-hin-eng.txt](https://github.com/tesseract-ocr/tesseract/files/734445/Devanagari_ligatures_Monier-Williams_1846_enhanced-hin-eng.txt)

[Devanagari_ligatures_Monier-Williams_1846_enhanced-hin-eng.log.txt](https://github.com/tesseract-ocr/tesseract/files/734449/Devanagari_ligatures_Monier-Williams_1846_enhanced-hin-eng.log.txt)

![devanagari_ligatures_monier-williams_1846_enhanced](https://cloud.githubusercontent.com/assets/5095331/22361180/5b99de5a-e47d-11e6-972e-af8b61a898a5.png)

**Comment by Shreeshrii** [comment]
this issue is a duplicate of https://github.com/tesseract-ocr/tesseract/issues/1275

**Comment by amitdo** [comment]
Shreeshrii,

This is an old report, please retest.

If this is the same issue as #1579, close #683.

**Comment by Shreeshrii** [comment]
@amitdo Here are the results with tessdata_best and tessdata_fast with --oem 1 and --psm 6. 

Issue #1579 says that the 2nd language is NOT recognized at all in multi-language images. In my test of the above image with three languages including one RTL, different combinations are recognized in different lines.

tesseract 4.0.0-rc3-20-g9c2d
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0

 *****  ./ara-hin-eng.png LANG ara+hin+eng TESSDATA tessdata_best OEM 1 PSM 6 ****

5 ‏ايكيه‎ TFT aikya, s.m. Oneness, unity, singleness, identity, sameness,
harmony (=eKata); total, aggregate, product.

H ‏119لا ايكن‎ aigun [S. FT-HTOT], s.m. Unskilfulness, stupidity, &c.=augun,
0.

A Lliyal gyal, uyyal, sam. Stag; deer, hart; wild goat.

S MW) TAT ela, s.f. Cardamoms. (See ilaci.)

11 ‏ايلام‎ 39419 lam, s.m. Auction, public sale (=lilam, nilam, q.q.v.).

Ambassador, envoy, delegate, agent:—el¢7 karna, To -‏ .5.10 ,اه ايلجى ظ.


 *****  ./ara-hin-eng.png LANG ara+hin+eng TESSDATA tessdata_fast OEM 1 PSM 6 ****

5 ‏أيكيه‎ ऐक्य aikya, $.m. Oneness, unity, singleness, identity, sameness,
harmony (=exatd); total, aggregate, product.

H (IIT aigun [S. अव+गुण], s.m. Unskilfulness, stupidity, &c.=augun,
१.४.

A bl ty]. gyal, uyyal, s.m. Stag; deer, hart; wild goat.

S | UT eld, s.f. Cardamoms. (See iad.)

H aX! SAF iam, s.m. Auction, public sale (=lilam, nilam, q.q.v.).

7? xh) elct, sm. Ambassador, envoy, delegate, agent:—elci karnd, TO 200000


tesseract 4.00.00alpha
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0

  
 *****  ./ara-hin-eng.png LANG ara+hin+eng TESSDATA tessdata_best OEM 1 PSM 6 ****
 
5 ‏ايكيه‎ TFT aikya, s.m. Oneness, unity, singleness, identity, sameness,
harmony (=eKata); total, aggregate, product.

H ऐसुण aigun [S. FT-HTOT], s.m. Unskilfulness, stupidity, &c.=augun,
0.

A gyal, uyyal, sam. Stag; deer, hart; wild goat.

S MW) TAT ela, s.f. Cardamoms. (See ilaci.)

11 ‏ايلام‎ 39419 lam, s.m. Auction, public sale (=lilam, nilam, q.q.v.).

P elér, s.m. Ambassador, envoy, delegate, agent:—el¢7 karna, To -


 *****  ./ara-hin-eng.png LANG ara+hin+eng TESSDATA tessdata_fast OEM 1 PSM 6 ****
 
5 ‏أيكيه‎ ऐक्य aikya, $.11. unity, singleness, identity, sameness,
harmony (=exatd); total, aggregate, product.

H (IIT aigun [S. अव+गुण], s.m. Unskilfulness, stupidity, &c.=augun,
१.४.

A जता, gyal, uyyal, s.m. Stag; deer, hart; wild goat.

S | UT eld, s.f. Cardamoms. (See iad.)

H aX! SAF iam, s.m. Auction, public sale (=lilam, nilam, q.q.v.).

7? xh) elct, sm. Ambassador, envoy, delegate, agent:—elci karnd, TO 200000
