### ISSUE TITLE
HOCR: x_font missing, x_fsize broken in 4.00-alpha

### ISSUE THREAD

**Issue by meldorq** [tesseract-ocr/tesseract#684]
I compared the HOCR output generated with recent builds of tesseract 3.04.02dev and 4.00.00alpha on various test images.

It seems that font recognition is broken in 4.00.00alpha:

With the command line parameter
**-c hocr_font_info=1**
3.04 generates font info for every word, which looks like this:
`x_font Verdana_Bold; x_fsize 21`

When I do the same with 4.00.00alpha, the font info looks like this:
`x_fsize 61491592`

The x_font attribute is missing entirely, and x_fsize has an incredibly large value.

The complete command line was:
`tesseract test-0.png  result --oem 1 -l deu -c hocr_font_info=1 hocr`

Version information:

3.04:
```
$ tesseract -v
tesseract 3.04.02dev
 leptonica-1.74.1
  libjpeg 6b (libjpeg-turbo 1.3.1) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8
```

4.00:
```
$ tesseract -v
tesseract 4.00.00alpha
 leptonica-1.74.1
  libjpeg 6b (libjpeg-turbo 1.3.1) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8

 Found AVX
 Found SSE

```

**Comment by amitdo** [comment]
The new LSTM engine does not support font recpognition.

**Comment by meldorq** [comment]
OK, but then the presence of the x_fsize attribute is misleading.

Will the LSTM engine ever support font recognition?

**Comment by amitdo** [comment]
>Will the LSTM engine ever support font recognition?

Only @theraysmith can answer this question.

I don't think that exact font identification is important feature. The estimated size of a word/line might be useful information. Same for emphasis of words.

**Comment by jbreiden** [comment]
Sounds to me like we should retire **hocr_font_info**, and remove the related HOCR output code.

**Comment by amitdo** [comment]
Same as #1074 

It does work in 4.00 with `--oem 0`.

with `--oem 1`, `x_fsize` should come with the right (estimated) size (#1173).

@zdenop, please close this issue.
