### ISSUE TITLE
During training using text file to fine-tune error: could not find font names...Please correct font arg..

### ISSUE THREAD

**Issue by harinath141** [tesseract-ocr/tesseract#688]
Hi,
I am trying to fine-tune Telugu language by training using wiki instructions.
When I tried the tesstrain.sh text2image command it's giving an error.screen shot attached

![image](https://cloud.githubusercontent.com/assets/17981729/22419985/0317a542-e706-11e6-8694-c52858b8d29c.png)

**Comment by Shreeshrii** [comment]
Take a look at language-specific.sh

Make sure that the fonts listed under telugu_fonts are available on your
system.

Change the list to match the fonts.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
text2image --fonts_dir= --text ./langdata/tel/tel.training_text
--outputbase teltest  --find_fonts --min_coverage=.9

Give your fonts for location with above command

I had recently posted in another thread a modified version of the above
which pipes the output of above to grep and sed to create a list of fonts.

The above command does not just list fonts it also creates sample images.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
On UNIX, Commands such as the following can be used to find out available
fonts which have coverage for the training text.


text2image --find_fonts \
--fonts_dir /usr/share/fonts \
--text ./langdata/ara/ara.training_text \
--min_coverage .8  \
--outputbase ./langdata/ara/ara \
|& grep raw | sed -e 's/ :.*/" \\/g'  | sed -e 's/^/  "/'
>./langdata/ara/fontslist.txt

this font list can be plugged into training/language-specific.sh

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
@harinath141 Were you able to get it to work? If so, please note the solution and close the issue.

**Comment by harinath141** [comment]
@Shreeshrii  Yeah It worked,
At phase -D throwing an error of missing common.punc in langdata folder.I copied Common.punc file in folder after that Training of lstm completed Succesfully.

**Comment by Shreeshrii** [comment]
FYI, 

to generate more training images with different levels of degradation modify the command to include more levels of exposures. eg.

```
training/tesstrain.sh --fonts_dir /mnt/c/Windows/Fonts --lang san_latn  \
  --linedata_only --noextract_font_properties --exposures "-1 0 1" \
   --langdata_dir ../langdata --tessdata_dir ./tessdata \
   --output_dir ~/tesstutorial/san_latn
  
```

to generate training images in more random fashion, modify tesstrain_utils.sh to shuffle the text and split it into eight different training text files for use with one of the fonts in each set of eight that are trained as a set.

```
        local counter=0
        local textnum=0
        for font in "${FONTS[@]}"; do
           if [[ "${textnum}" -eq 0 ]]; then
               shuf ${LANGDATA_ROOT}/${LANG_CODE}/${LANG_CODE}.training_text -o ${LANGDATA_ROOT}/${LANG_CODE}/${LANG_CODE}.training_text.txt
               split -a 1 -d -n r/8 ${LANGDATA_ROOT}/${LANG_CODE}/${LANG_CODE}.training_text.txt ${LANGDATA_ROOT}/${LANG_CODE}/${LANG_CODE}.training_text
           fi 
           TRAINING_TEXT=${LANGDATA_ROOT}/${LANG_CODE}/${LANG_CODE}.training_text${textnum} 
            generate_font_image "${font}" &
            let counter=counter+1
            let rem=counter%par_factor
            if [[ "${rem}" -eq 0 ]]; then
              wait
            fi
           let textnum=textnum+1
           if [[ "${textnum}" -eq 8 ]]; then
               let textnum=0
           fi 
        done
        wait
```
