### ISSUE TITLE
Request: new 4.0.O-alpha windows binaries

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#689]
@stweil @egorpugin  

It would be great if you can provide for download windows binaries with the latest 4.0.0 alpha code,  including the new training programs 
Lstmtraining
And
Lstmeval 

Thank you.

**Comment by egorpugin** [comment]
Here you are
https://www.dropbox.com/s/obiqvrt4m53pmoz/tesseract-4.0.0-alpha.zip?dl=1

**Comment by stweil** [comment]
There is also a new installer in our [wiki](https://github.com/UB-Mannheim/tesseract/wiki).

**Comment by Shreeshrii** [comment]
+ tesseract-ocr google group

Thank you both so much for your prompt response in providing the windows
binaries.

I have added links to both at
https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM#400-alpha-for-windows

Unofficial experimental binaries of tesseract-ocr 4.0.0-alpha (Jan 30,
2017) are available from the following links:

   - Windows Installer made with MinGW-w64
   <http://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-4.00.00dev.exe>
   from UB Mannheim <https://github.com/UB-Mannheim/tesseract/wiki>
   - zip file with cppan generated .dll and .exe files
   <https://www.dropbox.com/s/obiqvrt4m53pmoz/tesseract-4.0.0-alpha.zip?dl=1>,
   You have to install VC2015 x86 redist from microsoft.com in order to run
   them.

Please correct the description if it is not correct.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by stweil** [comment]
> There is also a new installer in our wiki.

Now an updated version which includes PR #698 is available. It no longer tries to use AVX.

**Comment by Shreeshrii** [comment]
@stweil Thanks. I have downloaded the new version and will give it a try.

Wondering though how  it is related to win32, since I am running under windows 10, with wit 64bit os and x-64 based processor. 

![sysinfo](https://cloud.githubusercontent.com/assets/5095331/22583959/cf6cf428-ea15-11e6-8d88-dc4f92a59acc.png)

**Comment by stweil** [comment]
We currently build only installers with 32 bit executables (which work also on 64 bit Windows like yours). Building both 32 and 64 bit installers is possible, but requires more resources.

**Comment by Shreeshrii** [comment]
Thanks for clarifying.

Have you/others at UB Mannheim tried LSTM training with the windows binaries?

In my earlier test, I found that lstmtraining was not reading .lstmf files created on windows. I will have to test the exact same case under bash and windows to confirm it.  I am wondering if it could be related to Unix vs DOS/Windows EOL differences.

Is there a way to compare the .lstmf files (binary files)?

**Comment by stweil** [comment]
No, we did not try training on Windows. The problem which you observe could be related to several issues which I noticed while working on Tesseract 4 for big endian machines, more concretely on wrong assumptions about the size of an enum variable. You can compare binary files created on Windows with files created on Linux using `cmp -l`. I'd expect that the Linux files have some additional 0 bytes, so they are a little bit larger.

**Comment by wizofe** [comment]
Site is broken :(

**Comment by stweil** [comment]
@wizofe, which site is broken?

**Comment by wizofe** [comment]
https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-4.00.00dev.exe
Which is referenced the main site downloads. I found that its the filename that changed (path is correct) so probably you need to update the link!

**Comment by stweil** [comment]
That was a link to the latest version, at the time of the posting pointing to https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-4.0.0dev-20170130.exe. I removed that link because it was too unspecific.

All available versions can be found at https://digi.bib.uni-mannheim.de/tesseract/.

**Comment by wizofe** [comment]
That's great. Basically other projects link to it like Mozilla iris so I'm going to update them as well!

**Comment by stweil** [comment]
I fixed the server configuration. Now that old URL is automatically redirected to the latest 4.00.00dev installer (which is still old, so not recommended for new users).
