### ISSUE TITLE
Did OCR post-processing in 2015, now that feature seems to be gone

### ISSUE THREAD

**Issue by Sleemanmunk** [tesseract-ocr/tesseract#690]
Back in 2015, I used some tools I found that came with tesseract that performed post-processing to correct ocr errors (i.e. they accepted text in and returned it out). I used them for my dissertation work in text error correction. Now it looks like tesseract has been refactored and they're gone. Regrettably I don't remember what the executables were called. Is there any way to get that old version of tesseract, or is there a way to use the new tesseract for OCR postprocessing instead of OCR directly?

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support/questions.
