### ISSUE TITLE
JP2 files not working

### ISSUE THREAD

**Issue by askonivala** [tesseract-ocr/tesseract#692]
Trying to run "tesseract filename.jp2 out -l deu_frak" results:

Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Warning in fgetJp2kResolution: image resolution not found

There is a fix to this somewhere, but could not find it:

https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1373390.html

**Comment by Shreeshrii** [comment]
tesseract -v
will show what libs leptonica has with it. It might not have jp2 support.

 tesseract -v

tesseract 4.00.00alpha
 leptonica-1.74.1
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib
1.2.8

 Found AVX
 Found SSE


ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by jbreiden** [comment]
How did you install tesseract and on what operating system?

**Comment by jbreiden** [comment]
Also are you just talking about the warning message or its something else going wrong as well?

**Comment by askonivala** [comment]
I am so sorry for the incomplete report and not testing this issue properly. Running "tesseract filename.jp2 out -l deu_frak" resulted to the above given error message and an empty out.txt file or freezing of app, so I automatically (but little bit stupidly) assumed that the OCR scanning is not working. After you reply, I tested it with lots of other jp2 files, and it in fact works despite of the warning. The jp2 files that I was using were simply somehow corrupted, it is my mistake, which I apologise!

By the way, I encountered problems also with multipaged TIFFs, tesseract now outputting empty txt files. But I am probably doing something wrong here as well and it's not a bug. I am using Ubuntu 16.04.1 LTS Server without any graphics system and installed tesseract with "apt-get install".

```
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0
```

**Comment by jbreiden** [comment]
The best thing for bug reports is to attach your input data (and try to make the smallest, simplest example that reproduces the problem) along with exact commands used, and the output data. For support questions, use the forum. I'm going to close this bug now, but please re-open this bug if you think you've found a problem.

Note that the particular warning you saw will go away in a future Tesseract, and will be replaced with one that says something like "Unknown image resolution, making a guess". Which is hopefully a little more clear.

**Comment by jbreiden** [comment]
PS. You can use jhove to validate JPEG 2000 files.
