### ISSUE TITLE
compiling using vs2013 -library not found

### ISSUE THREAD

**Issue by varun1994varun** [tesseract-ocr/tesseract#693]
I want to build Tesseract using visual studio 2013.
I have followed all the steps as mentioned in https://vorba.ch/2014/tesseract-3.03-vs2013.html which is the site mentioned in the compiling section.
Everything went well but in the last step while building the solution I got a link error which is cannot read liblept171.lib and cannot include "allfrex.h".
I am new to this and haven't figured out any solution yet.
Is this the right way or please guide if any other way is possible to build tesseract in visual studio 2013

Thank you.

These are the steps mentioned in that link:

 
17 [Previously](tesseract-cygwin.html) I wrote about how to compile Tesseract OCR 
18 using Cygwin. While this is nice if you want to compile Tesseract for your own 
19 system where you can install Cygwin on your own, compiling with Visual Studio is 
20 better if you intend to distribute the compiled package so users don't have to 
21 install Cygwin. 
22 
 
23 Compiling Tesseract 3.02.02 with Visual C++ 2008 (Express) is [covered by the 
24 documentation](http://tesseract-ocr.googlecode.com/svn/trunk/vs2008/doc/setup.html) 
25 whereas compiling Tesseract 3.03 isn't covered at all, though. 
26 
 
27 Unfortunately newer versions of Tesseract also require a new version of 
28 [Leptonica](http://www.leptonica.org/), a C library for image processing and 
29 image analysis applications, which in turn requires new versions of zlib, 
30 libpng, libtiff, libjpeg and giflib. Tesseract provides pre-compiled versions of 
31 Leptonica, which prevents you from having to collect and set up projects for all 
32 of these libraries in Visual Studio, which can be a tedious task. 
33 
 
34 Yesterday I found a project on GitHub that includes a Visual Studio solution 
35 file for all dependencies required to compile Tesseract 3.03: 
36 [charlesw/tesseract-vs2012](https://github.com/charlesw/tesseract-vs2012). While 
37 following the build instructions there, I stumpled over several build errors, 
38 which I could easily resolve by removing a definition. The necessary change is 
39 in [my fork](https://github.com/pvorb/tesseract-vs2013) of the repository 
40 mentioned above. 
41 
 
42 This is a write-up of all steps that are required to compile Tesseract 3.03 with 
43 Visual Studio 2013. 
44 
 
45 ## Prerequisites 
46 
 
47  1. Install [Git](http://git-scm.com/). 
48  2. Install SVN. There are many versions of SVN. You can, for example, install 
49     the binary package from [SlickSVN](http://www.sliksvn.com/en/download) for 
50     free. 
51  3. Install [Visual Studio 2013 for Windows Desktop](http://www.visualstudio.com/downloads/download-visual-studio-vs) 
52     (the Express version will be enough). You don't need the optional features 
53     except for "Microsoft Foundation Classes for C++". 
54 
 
55 ## Building the dependencies 
56 
 
57  1. Create a directory where you want to compile Tesseract. In this document, 
58     I'll assume it's `C:\Tesseract-Build\`. 
59  2. Open a CMD prompt and change to that directory. 
60 
 
61     ~~~ 
62     cd \Tesseract-Build\ 
63     ~~~ 
64  3. Clone the dependencies repository from GitHub. 
65 
 
66     ~~~ 
67     git clone git://github.com/pvorb/tesseract-vs2013.git 
68     ~~~ 
69  4. Open the "VS 2013 Developer Command Prompt". (It can be found in the Start 
70     Menu.) 
71  5. Change to the newly cloned repository. 
72 
 
73     ~~~ 
74     cd \Tesseract-Build\tesseract-vs2013 
75     ~~~ 
76  6. Build the dependencies 
77 
 
78     ~~~ 
79     msbuild build.proj 
80     ~~~ 
81  7. You can close the "VS 2013 Developer Command Prompt". 
82 
 
83 ## Building Tesseract 
84 
 
85  1. Re-open the first command prompt and ensure it's still in 
86     `C:\Tesseract-Build\`. 
87  2. Get the latest source from SVN. 
88 
 
89     ~~~ 
90     svn checkout http://tesseract-ocr.googlecode.com/svn/trunk/ tesseract-ocr 
91     ~~~ 
92  3. Change to the newly checked-out repository. 
93 
 
94     ~~~ 
95     cd tesseract-ocr 
96     ~~~ 
97  4. Apply the patch provided in `tesseract-vs2013`. 
98 
 
99     ~~~ 
100     svn patch ..\tesseract-vs2013\vs2013+64bit_support.patch 
101     ~~~ 
102  5. Copy both directories in `C:\Tesseract-Build\tesseract-vs2013\release\` to 
103     `C:\Tesseract-Build\`. Now you should have 
104 
 
105       - `C:\Tesseract-Build\include\` 
106       - `C:\Tesseract-Build\lib\` 
107  6. Open `C:\Tesseract-Build\tesseract-ocr\vs2013\tesseract.sln` with Visual 
108     Studio 2013. 
109  7. Press `F7` on your keyboard. Both `libtesseract303` and `tesseract` should 
110     compile without errors.

**Comment by Shreeshrii** [comment]
see https://github.com/tesseract-ocr/tesseract/wiki/Compiling

section under windows re building with cppan

@egorpugin  will it work with vs2013?

**Comment by egorpugin** [comment]
Not tested, but in general should be ok.
I remember some issues with libtiff dependency, but I fixed something, so 100% not sure.

**Comment by Shreeshrii** [comment]
Thanks!

It would be helpful to users if you update the wiki regarding cppan
compilation of tesseract. Right now it seems to me that it is for training
tools since that comes on top.

Many users compile tesseract not for development or training but just to
get the latest version of the software.

I don't have Visual studio so I haven't tried it.

- excuse the brevity, sent from mobile

**Comment by egorpugin** [comment]
I've added a section with simple tess library build.
https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows

**Comment by varun1994varun** [comment]
Thank you very much!
I followed all the steps as mentioned and I was able to build the solution successfully without any errors.
Now I added a new cpp file with the code given in api example.But I did not get any ouput .I also tried writing the output to a txt file but in vain.
Can  you please help me how to get the txt,hocr,pdf output file after building the solution.
I am currently trying it in visual studio 2013  as well as 2015 version.
Regards.

API example:
#include <tesseract/baseapi.h>
#include <leptonica/allheaders.h>

int main()
{
    char *outText;

    tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
    // Initialize tesseract-ocr with English, without specifying tessdata path
    if (api->Init(NULL, "eng")) {
        fprintf(stderr, "Could not initialize tesseract.\n");
        exit(1);
    }

    // Open input image with leptonica library
    Pix *image = pixRead("/usr/src/tesseract/testing/phototest.tif");
    api->SetImage(image);
    // Get OCR result
    outText = api->GetUTF8Text();
    printf("OCR output:\n%s", outText);

    // Destroy used object and release memory
    api->End();
    delete [] outText;
    pixDestroy(&image);

    return 0;
}

**Comment by egorpugin** [comment]
It depends on what your are trying to do.
If you need to build user-app, follow one of these guides 
https://github.com/cppan/tesseract_example/tree/master/
https://github.com/cppan/tesseract_example/tree/master/with_cppan

**Comment by varun1994varun** [comment]
Thank You,It is working.

I  would like you guys to provide videos on step by step process of building tesseract on various platforms which would really guide us especially the beginners and save many hours of searching in the net.

**Comment by hanikh** [comment]
I want to build Tesseract with vs2013. I have followed all steps of this tutorial:
https://vorba.ch/2014/tesseract-3.03-vs2013.html
but in the last step, I got this error:
can not find include file: 'version.h' 
what should I do?
Thanks

**Comment by Shreeshrii** [comment]
try with cppan and directions given in
https://github.com/tesseract-ocr/tesseract/wiki/Compiling

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by zdenop** [comment]
@hanikh Please do not complain here that some tutorial outside of this project does not work for you. (Especially when you decide to ignore instructions provided here on github)

**Comment by AbdelsalamHaa** [comment]
Hi , I have build tesseract4.0 using vs 2017 with leptonica 1.75.3 . it workred very well . i want to include tesseract4.0 into other project but that project has a lot of library which was built in vs 2013 . Im trying to use vs 2013  to build tesseract 4.0 to match with my project . unfortunately i couldn't do exist of constexper in publictry.h file in tesseract 4.0 . so im asking is there any way to build tesseract 4.0 using vs 2013

**Comment by stweil** [comment]
VS 2013 is not supported any more.

**Comment by AbdelsalamHaa** [comment]
Oh , i see . thanks a lot . any advice u think i can do since it's relay difficult to recompile all the library in my project using other version of visual studio . thanks in advance
