### ISSUE TITLE
Output format txt has different result from output format pdf in v3.05.00dev

### ISSUE THREAD

**Issue by shareworlds** [tesseract-ocr/tesseract#694]
![test1](https://cloud.githubusercontent.com/assets/23392731/22503425/a5baa5fe-e8ac-11e6-9d5e-36db771b3654.png)

When i use command "tesseract test.png out", the result is "01234567Beabcdelghijklmnopqrstuvwxyz". 
It has 4 wrong text.
But when i use command "tesseract test.png out pdf", the result is perfect correct.
Does someone know how to also make the result is correct when output is txt?

**Comment by Shreeshrii** [comment]
Are you just looking at the PDF or the text in it?

The difference could be based on the default page segmentation mode used by
each method.

- excuse the brevity, sent from mobile

**Comment by jbreiden** [comment]
Post your PDF please.

**Comment by amitdo** [comment]
No feedback from the OP, so I suggest to close this issue.
