### ISSUE TITLE
incorrect character box positions 

### ISSUE THREAD

**Issue by X-Wei** [tesseract-ocr/tesseract#697]
I tested tesseract with a small image of just one word, it seems that the positions of char-boxes are vertically shifted. 

Here is my test image: 

![test](https://cloud.githubusercontent.com/assets/1615196/22559650/1562e05e-e972-11e6-82a4-6cf7ca395543.jpg)

when I run tesseract `tesseract test.jpg out batch.nochop makebox`, I get: 

```
B 10 20 43 62 0
e 49 18 70 53 0
r 73 20 93 52 0
t 94 20 111 62 0
h 113 21 141 64 0
o 145 21 170 53 0
u 173 21 199 53 0
d 205 20 229 63 0
, 233 10 245 33 0
```

If I plot the boxes out, it looks like this:

![test_boxes](https://cloud.githubusercontent.com/assets/1615196/22559725/5247541e-e972-11e6-83e6-fb8ce76603f5.png)

Is this a bug, or do I use some wrong arguments here ?

**Comment by Shreeshrii** [comment]
I think your x-y axis are not correct.

  the coordinate system used in the box file has (0,0) at the bottom-left

- excuse the brevity, sent from mobile

**Comment by X-Wei** [comment]
That's effectively the case, thank you very much for the quick reply !
