### ISSUE TITLE
where is include folder and lib for opencv build

### ISSUE THREAD

**Issue by hoangtocdo90** [tesseract-ocr/tesseract#704]
Im want to build opencv text + tessract ocr. but i can't find how to get include and lib folder.
I find some old  build in source forge page but only 3.02 version but i want 4.0 or 3.05
https://sourceforge.net/projects/tesseract-ocr-alt/files/?source=navbar
some one can tell me where is include + lib folder or how to build it from source .
Sorry for posting in here but i did many search but haven't any result
Big thank! sorry for my bad english

**Comment by egorpugin** [comment]
Hi, for what platform are you trying to build opencv.text?

You could try to build it using CPPAN (https://cppan.org/). 
I'm using opencv.text on windows. All is fine.
https://cppan.org/pvt.cppan.demo.intel.opencv.contrib.text/version/3.2.0

To build it with cppan, download the client and run `cppan --build 	pvt.cppan.demo.intel.opencv.contrib.text-3.2.0`.

**Comment by hoangtocdo90** [comment]
Thank you very much!
So simple and easy guide. Im' very happy. Thanks !
