### ISSUE TITLE
Add 'topics' to this repo

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#705]
https://github.com/blog/2309-introducing-topics

**Comment by amitdo** [comment]
Suggested topics:
* ocr
* lstm
* machine-learning
*tesseract-ocr

**Comment by amitdo** [comment]
[tesseract](https://github.com/search?utf8=%E2%9C%93&q=topic%3Atesseract&type=Repositories&ref=searchrstesults)
[tesseract-ocr](https://github.com/search?utf8=%E2%9C%93&q=topic%3Atesseract-ocr&type=Repositories&ref=searchresults)
[ocr](https://github.com/search?utf8=%E2%9C%93&q=topic%3Aocr&type=Repositories&ref=searchresults)
[lstm](https://github.com/search?utf8=%E2%9C%93&q=topic%3Alstm&type=Repositories&ref=searchresults)
[machine-learning](https://github.com/search?utf8=%E2%9C%93&q=topic%3Amachine-learning&type=Repositories&ref=searchresults)

**Comment by amitdo** [comment]
@zdenop, only Ray can do it?

**Comment by zdenop** [comment]
done

**Comment by amitdo** [comment]
Thanks, Zdenko!

**Comment by amitdo** [comment]
Why does it add 'org:tesseract-ocr' to the our topics?

**Comment by Shreeshrii** [comment]
Look ok on web interface:

![tmp](https://user-images.githubusercontent.com/5095331/29661044-80c31798-88e0-11e7-9f7b-e9c8ceb9b8bf.png)

**Comment by amitdo** [comment]
Click on a topic and you see what I'm talking about.

**Comment by amitdo** [comment]
I find our that it addS 'org' to any topic in any organization.

That's yet another case of bad UX in GitHub IMO.

**Comment by amitdo** [comment]
>I found out that it adds 'org' to any topic in any organization.

They fixed the issue.
