### ISSUE TITLE
Segmentation fault when use through python(tesserocr)

### ISSUE THREAD

**Issue by StephenShang** [tesseract-ocr/tesseract#710]
when i use tesseract through command line, it works. But when I call it through python(tesserocr), it crashes and said Segmentation fault.
![1](https://cloud.githubusercontent.com/assets/1935079/22725932/50036f4c-ee0b-11e6-93db-6f06af554c65.JPG)

**Comment by StephenShang** [comment]
I compile it myself in Ubuntu 14.04. The version is 3.04

**Comment by zdenop** [comment]
We do not support 3rd party solution. Please contact author of your solution or use tesseract user forum.
