### ISSUE TITLE
error while running tesseract 

### ISSUE THREAD

**Issue by vibhashenoy** [tesseract-ocr/tesseract#711]
I got this error while running a test case which involves verifying a toast message using tesseract on intellij3.4. java version 1.8.0_121)

A fatal error has been detected by the Java Runtime Environment:
 SIGSEGV (0xb) at pc=0x00007f10e046333a, pid=4980, tid=0x00007f111d577700
 JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode linux-amd64 compressed oops)
 Problematic frame:
C  [libtesseract.so.3.0.3+0x22533a]  ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const+0x16a

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 53

tried executing "ulimit -c unlimited" still doesn't set it right.
any suggestion will be of great help.

**Comment by zdenop** [comment]
We do not support 3rd party solution. Please contact author of your solution or use tesseract user forum.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/FAQ#actual_tessdata_num_entries_-tessdata_num_entrieserrorassert-failedin-file-ccutiltessdatamanagercpp-line-55_
