### ISSUE TITLE
PDF Output for Pipes in Windows

### ISSUE THREAD

**Issue by wadex1** [tesseract-ocr/tesseract#714]
PDF Output being a standard feature has some problems in Windows.
If you use stdout as tesseract output and pipe or redirect the PDF Output to another Executable, e.g pdftotext, every linefeed is converted to CR/LF in the resulting PDF, corrupting this PDF file.

It could easily prevented by implementing

`#ifdef WIN32`
`  if (_setmode(_fileno(stdout), _O_BINARY) == -1)`
`    tprintf("ERRROR: cout to binary: %s, strerror(errno));`
`#endif`

somewhere near TessPDFRenderer call, maybe in tesseractmain.cpp.
You would need to include fcntl.h and io.h too.

I tested it and it worked fine redirecting and piping in Windows.

Many thanks to the whole bunch of developers.

wadex1

**Comment by jbreiden** [comment]
Terrific, we want that. Thanks.

**Comment by wadex1** [comment]
Hi again,
I'm not sure about the appropriate location to put the code.
If all output is sent binary, not only PDF but text output will be binary too.
I don't know if this breaks any other compatibilities, especially with piping or redirecting the text output in Windows.

Maybe somebody could look for the correct place to insert.

I think this modification is quite necessary if we want to pipe PDF output to e.g. pdftotext.exe in Windows.
Running pdftotext on the tesseract PDF output is the only way for me to have text output with a decent layout and piping would save me from using temporary files.

Best regards

**Comment by zdenop** [comment]
Issue is still there even suggested fix is already [in (wrong?) place](https://github.com/tesseract-ocr/tesseract/blame/5dfce7471c1830c7e96d07ece8342f6e3b09436f/src/api/baseapi.cpp#L1105). Commands:
```
tesseract.exe Vigcd.jpg x pdf
tesseract.exe Vigcd.jpg - pdf >x2.pdf

```
produce different pdf on windows: [x.pdf](https://github.com/tesseract-ocr/tesseract/files/2423057/x.pdf) has unix line endings and [x2.pdf](https://github.com/tesseract-ocr/tesseract/files/2423056/x2.pdf) has dos line endings and there can not be displayed in pdf viewers (tested in acrobat reader)

**Comment by jbreiden** [comment]
The code @zdenop linked to is for stdin. Sounds like we need this for stdout, and probably somewhere in or near pdfrenderer.cpp since that is the one place where Tesseract produces binary output. Maybe I forgot to do anything from this bug report? I don't have access to a Windows computer so not something I'll be able to test directly.

**Comment by zdenop** [comment]
You are right - my fault, it is for stdin. I can test if your provide me right place - otherwise I will place it [here](https://github.com/tesseract-ocr/tesseract/blob/master/src/api/tesseractmain.cpp#L404).

**Comment by jbreiden** [comment]
That looks like a good spot to me.
