### ISSUE TITLE
Releasing version 3.05

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#715]
From #707:

@amitdo commented:
>I also think we should release a last 3.0x version in the upcoming 2-6 weeks.

@zdenop  commented:
>If 3.05 should be the last version with legacy OCR Engine (old engine) then there should be possibility to read [OCR result from memory](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-dev/mZ2IUsvWgbY/2yz-b1cUAgAJ).

@jbreiden commented:
>https://wiki.ubuntu.com/ZestyZapus/ReleaseSchedule
>
>Feb 16 is the final deadline for changes to Ubuntu 17.04. I am not comfortable shipping anything from 4.x to these users, but we can consider taking a snapshot of the 3.0.5 branch. It does have some bug and compatibility fixes that are good for users. Regarding training data, I would not ship an update that at all. This would be purely be a code update.
>
>I know the long standing issue has been restoring an API call (last seen in version 3.0.2) to send results to memory instead of file. I respect that idea, but we don't have it, and it's not that easy to add. I think it is fair to say that it would be impossible before deadline. So the question is, do we ship an update to users this cycle or not. And if so, should I take a snapshot? And if so, what would it be called?
>
>A few more thoughts that are somewhat related
>
>* I see no reason that this has to be the last ever release on the 3.0.x branch.
>*  My guess is by the next next release in Oct 2017 that 4.x will be ready for the vast majority of users
>*  I'm not planning to ship both 3.0.x and 4.x at the same time with Debian/Ubuntu. I think it will be very rare for people to want both, and those who do will be advanced users who can work from source code.

@Shreeshrii commented:
>@jbreiden Good idea to do a code update for 3.05 for Ubuntu 17.04. There are a number of bug fixes and changes and it would be good to get them out to the users. Thanks!

**Comment by amitdo** [comment]
I added [Release Notes for 3.05](https://github.com/tesseract-ocr/tesseract/wiki/ReleaseNotes#to-be-released-as-v305---in-feb-2017-), based ion the [3.05 branch](https://github.com/tesseract-ocr/tesseract/commits/3.05).

**Comment by amitdo** [comment]
@zdenop, @egorpugin 

Some minor fixes to 3.05:

README.md
>The latest stable version is 3.04.01, released in February 2016.

=>
>The latest stable version is 3.05, released in February 2017.

tesseract/api/baseapi.h
`#define TESSERACT_VERSION_STR "3.05.00dev"`
=>
`#define TESSERACT_VERSION_STR "3.05.00"`

configure.ac
`AC_INIT([tesseract], [3.05.00dev], [https://github.com/tesseract-ocr/tesseract/issues])`
=>
`AC_INIT([tesseract], [3.05.00dev], [https://github.com/tesseract-ocr/tesseract/issues])`

```
PACKAGE_YEAR=2015
PACKAGE_DATE="07/11"
```
=>
```
PACKAGE_YEAR=2017
PACKAGE_DATE="02/14"
```

ChangeLog
>
See [ReleaseNotes](https://github.com/tesseract-ocr/tesseract/wiki/ReleaseNotes
)

AUTHORS
Please add Nick White to the Community Contributors.

CONTRIBUTING.md
https://github.com/tesseract-ocr/tesseract/commit/bf9f40cac631

**Comment by egorpugin** [comment]
You could create a PR with these changes. :)

**Comment by jbreiden** [comment]
Thinking about his, I have never had an easy time doing a new Tesseract release for Debian. Maybe shipping a new version right at the cutoff date is not such a smart idea.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794489
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816857
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815056
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815860
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815970

**Comment by amitdo** [comment]
So, when?

**Comment by amitdo** [comment]
Maybe you want to use this strategy:
 
1. Make one unified deb package for Debian 9, Ubuntu 16.04, Ubuntu 17.04.
2. Push it to Debian & Ubuntu 'backports' repos. For Debian 9 and Ubuntu 17.04 you will need to wait until they are released. For Ubuntu 16.04 you can start when you want to.

**Comment by Shreeshrii** [comment]
@zdenop 

You should tag the 3.05 branch with the release. It can be updated in case there are any additional changes.

**Comment by Shreeshrii** [comment]
Or, if you think it is not ready for release yet, then at least tag as 3.05.0-beta. Thanks!

**Comment by zdenop** [comment]
Done: https://github.com/tesseract-ocr/tesseract/releases/tag/3.05.00

**Comment by jbreiden** [comment]
Being super cautious, I am comparing symbols from libtesseract.3.0.4 and libtesseract.3.0.5. Here are symbols that disappeared in 3.0.5.

```
-_Z14WriteParamDescP8_IO_FILEtP10PARAM_DESC@Base
-_Z9read_listPKc@Base
-_ZN16GENERIC_2D_ARRAYIN9tesseract17TrainingSampleSet13FontClassInfoEE6ResizeEiiRKS2_@Base
-_ZN8WERD_RES19FakeWordFromRatingsEv@Base
-_ZN9tesseract11ObjectCacheINS_4DawgEEC1Ev@Base
-_ZN9tesseract11ObjectCacheINS_4DawgEEC2Ev@Base
-_ZN9tesseract13DocumentCache13LoadDocumentsERK13GenericVectorI6STRINGEPKcPFbRKS2_PS1_IcEE@Base
-_ZN9tesseract13DocumentCache15GetPageBySerialEi@Base
-_ZN9tesseract17ViterbiStateEntryD1Ev@Base
-_ZN9tesseract17ViterbiStateEntryD2Ev@Base
-_ZN9tesseract18DawgPositionVectorD1Ev@Base
-_ZN9tesseract18DawgPositionVectorD2Ev@Base
-_ZN9tesseract4Dict4LoadEPNS_9DawgCacheE@Base
-_ZNK9tesseract4Dict19ProcessPatternEdgesEPKNS_4DawgERKNS_12DawgPositionEibPNS_18DawgPositionVectorEP12PermuterType@Base
-_ZNK9tesseract9ImageData8PreScaleEiPP3PixPiS4_P13GenericVectorI4TBOXE@Base
```

[3.0.4.symbols.amd64.txt](https://github.com/tesseract-ocr/tesseract/files/784668/3.0.4.symbols.amd64.txt)
[3.0.5.symbols.amd64.txt](https://github.com/tesseract-ocr/tesseract/files/784670/3.0.5.symbols.amd64.txt)

**Comment by jbreiden** [comment]
Now I want to test against gimagereader, but can't from my chroot jail. It fails on both `3.0.4` and `3.0.5`

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

**Comment by jbreiden** [comment]
This is the release candidate for 3.0.5, I'm going to do a compatibility check with the gimagereader author.

[tesseract-3.0.5-candidate.zip](https://github.com/tesseract-ocr/tesseract/files/784689/tesseract-3.0.5-candidate.zip)

**Comment by jbreiden** [comment]
Okay, I got gimagereader working. This gives me a lot of confidence.

https://help.ubuntu.com/community/BasicChroot#Accessing_graphical_applications_inside_the_chroot

**Comment by Shreeshrii** [comment]
@sandromani

Have you tried building gImageReader with 3.05  release candidate?

**Comment by jbreiden** [comment]
I'd like to figure things out such that gimagereader doesn't need to be rebuilt.

**Comment by innir** [comment]
Hi, 
I'm the maintainer of gimagereader in Debian. I just checked with the debs @jbreiden provided. Gimagereader crashes when compiled against 3.0.4 but run with 3.0.5, see https://gist.github.com/innir/a4662ad7043c9cc27e9f7bdaff8f8acf.

Recompiling gImageReader against 3.0.5 resolves the crash.

This is really easy to fix upstream. You just have to bump the SONAME if your symbols change! Not too hard to get! Please make a 3.0.5.1 release and bump the SONAME!

Best,
Philip

**Comment by innir** [comment]
@manisandro no problem on your side, gImageReader works fine with 3.0.5 :)

**Comment by manisandro** [comment]
Thanks for checking @innir , I haven't yet had time to build 3.0.5.

**Comment by jbreiden** [comment]
Upstream was hoping 3.0.5 would be application binary interface (ABI) compatible with 3.0.4. Am I reading the crashlog correctly that the unhappy symbol is RecogAllWordsPassN? Because I don't think that has changed. Is there a preferred ABI compatibility checking tool?

**Comment by egorpugin** [comment]
Hi,

I've heard about this ABI tracker. Maybe it's possible to add tesseract (& leptonica) there somehow.
https://lvc.github.io/abi-compliance-checker/
https://abi-laboratory.pro/tracker/
https://abi-laboratory.pro/tracker/timeline/qt/ (qt example)

**Comment by innir** [comment]
@jbreiden I think it's in Recognize() or one of the functions Recognize() calls. Hard to tell as the next two lines in the crash log are empty :(
Anyway, if symbols are removed, the SONAME has to be bumped, if symbols are only added that's not necessary - AFAIR. Those ABI trackers are good, but I'm not sure if they catch things like this: https://github.com/tesseract-ocr/tesseract/pull/259/files

**Comment by manisandro** [comment]
abipkgdiff output (comparing 3.04.01 and 3.05.00):

    ================ changes of libtesseract.so.3.0.4===============c++filt 
    Functions changes summary: 0 Removed, 0 Changed, 0 Added function
    Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
    Function symbols changes summary: 11 Removed, 41 Added function symbols not referenced by debug info
    Variable symbols changes summary: 0 Removed, 3 Added variable symbols not referenced by debug info

    11 Removed function symbols not referenced by debug info:

        WriteParamDesc(_IO_FILE*, unsigned short, PARAM_DESC*)
        read_list(char const*)
        GENERIC_2D_ARRAY<tesseract::TrainingSampleSet::FontClassInfo>::Resize(int, int, tesseract::TrainingSampleSet::FontClassInfo const&)
        WERD_RES::FakeWordFromRatings()
        tesseract::DocumentCache::LoadDocuments(GenericVector<STRING> const&, char const*, bool (*)(STRING const&, GenericVector<char>*))
        tesseract::DocumentCache::GetPageBySerial(int)
        tesseract::DawgPositionVector::~DawgPositionVector(), aliases tesseract::DawgPositionVector::~DawgPositionVector()
        tesseract::DawgPositionVector::~DawgPositionVector()
        tesseract::Dict::Load(tesseract::DawgCache*)
        tesseract::Dict::ProcessPatternEdges(tesseract::Dawg const*, tesseract::DawgPosition const&, int, bool, tesseract::DawgPositionVector*, PermuterType*) const
        tesseract::ImageData::PreScale(int, Pix**, int*, int*, GenericVector<TBOX>*) const

    41 Added function symbols not referenced by debug info:

        TessBaseAPIDetectOrientationScript
        WriteParamDesc(_IO_FILE*, unsigned short, PARAM_DESC const*)
        GenericVector<tesseract::DawgPosition>::clear()
        STRING::SkipDeSerialize(bool, tesseract::TFile*)
        WERD_RES::FakeWordFromRatings(PermuterType)
        tesseract::TessBaseAPI::GetTSVText(int)
        tesseract::TessBaseAPI::GetHOCRText(ETEXT_DESC*, int)
        tesseract::TessBaseAPI::AnalyseLayout()
        tesseract::TessBaseAPI::DetectOrientationScript(int*, float*, char const**, float*)
        tesseract::ColPartition::SortByBBox(void const*, void const*)
        tesseract::DocumentData::SetDocument(char const*, char const*, long long, bool (*)(STRING const&, GenericVector<char>*))
        tesseract::DocumentData::IsPageAvailable(int, tesseract::ImageData**)
        tesseract::DocumentData::LoadPageInBackground(int)
        tesseract::DocumentData::UnCache()
        tesseract::DocumentCache::TotalPages()
        tesseract::DocumentCache::LoadDocuments(GenericVector<STRING> const&, char const*, tesseract::CachingStrategy, bool (*)(STRING const&, GenericVector<char>*))
        tesseract::DocumentCache::GetPageRoundRobin(int)
        tesseract::DocumentCache::GetPageSequential(int)
        tesseract::DocumentCache::CountNeighbourDocs(int, int)
        tesseract::ParamsVectors::~ParamsVectors()
        tesseract::ParamsVectors::~ParamsVectors(), aliases tesseract::ParamsVectors::~ParamsVectors()
        tesseract::TessTsvRenderer::AddImageHandler(tesseract::TessBaseAPI*)
        tesseract::TessTsvRenderer::EndDocumentHandler()
        tesseract::TessTsvRenderer::BeginDocumentHandler()
        tesseract::TessTsvRenderer::TessTsvRenderer(char const*), aliases tesseract::TessTsvRenderer::TessTsvRenderer(char const*)
        tesseract::TessTsvRenderer::TessTsvRenderer(char const*, bool)
        tesseract::TessTsvRenderer::TessTsvRenderer(char const*)
        tesseract::TessTsvRenderer::TessTsvRenderer(char const*, bool), aliases tesseract::TessTsvRenderer::TessTsvRenderer(char const*, bool)
        tesseract::TessTsvRenderer::~TessTsvRenderer()
        tesseract::TessTsvRenderer::~TessTsvRenderer()
        tesseract::TessTsvRenderer::~TessTsvRenderer(), aliases tesseract::TessTsvRenderer::~TessTsvRenderer()
        tesseract::ReCachePagesFunc(void*)
        tesseract::Dict::FinishLoad()
        tesseract::Dict::SetupForLoad(tesseract::DawgCache*)
        tesseract::Dict::Load(char const*, STRING const&)
        tesseract::DawgCache::~DawgCache(), aliases tesseract::DawgCache::~DawgCache()
        tesseract::DawgCache::~DawgCache()
        tesseract::ImageData::SkipDeSerialize(bool, tesseract::TFile*)
        tesseract::Dict::ProcessPatternEdges(tesseract::Dawg const*, tesseract::DawgPosition const&, int, bool, tesseract::DawgArgs*, PermuterType*) const
        tesseract::Dict::IsSpaceDelimitedLang() const
        tesseract::ImageData::PreScale(int, int, float*, int*, int*, GenericVector<TBOX>*) const

    3 Added variable symbols not referenced by debug info:

        typeinfo for tesseract::TessTsvRenderer
        typeinfo name for tesseract::TessTsvRenderer
        vtable for tesseract::TessTsvRenderer

**Comment by zdenop** [comment]
Is there anything we can do (in tesseract project) to fix this issue?

**Comment by lvc** [comment]
> I've heard about this ABI tracker. Maybe it's possible to add tesseract (& leptonica) there somehow.

Done:

https://abi-laboratory.pro/tracker/timeline/tesseract/
https://abi-laboratory.pro/tracker/timeline/leptonica/

![tesseract-2](https://cloud.githubusercontent.com/assets/1517837/24391524/af496122-13a0-11e7-8dd5-c138319425db.png)

About the tracker: https://abi-laboratory.pro/index.php?view=abi-tracker

**Comment by amitdo** [comment]
Next release - 3.05.1
https://groups.google.com/forum/#!topic/tesseract-dev/7vwsJNCAUcQ
