### ISSUE TITLE
Tesseract outputs page dimensions in ocrx_word artifacts

### ISSUE THREAD

**Issue by majorbossy** [tesseract-ocr/tesseract#718]
[test.pdf](https://github.com/tesseract-ocr/tesseract/files/770565/test.pdf)
![test](https://cloud.githubusercontent.com/assets/25739284/22877715/9d091ece-f1ce-11e6-867c-dd7fe106ec43.png)

[test.hocr.txt](https://github.com/tesseract-ocr/tesseract/files/770570/test.hocr.txt)

Hi

In the attached hocr you can search for "bbox 0 0" and see that there are multiple occurrences of ocrx_word artifacts where the bbox coordinates are the same as those of the ocr_page artifact.

These ocrx_word occurrences seem to be occurring in relation to vertical and horizontal lines in the image.

If you search for "Party" in the pdf, you will see that the bbox for the last two instances goes out to the end of the underlining, despite the fact that the text has been correctly identified as "Party A" and "Party B"

The image was redacted using Paint and Windows clipboard, but despite any damage I have inflicted on the file, the text is still correctly identified.
Whatever the state of the image, it can't be correct for an ocrx_word to have the same coordinates as that of the ocr_page.

I downloaded the Windows Installer version from UB Mannheim on 18/1/17 (the current version doesn't run on my system!):

tesseract 4.00.00alpha
 leptonica-1.73
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0

Windows 10
Version	10.0.14393 Build 14393
  
The command I'm running is:
"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe" -oem 4 -psm 6 -c tessedit_create_hocr=1 -c tessedit_create_pdf=1 test.png test

I've turned the auto psm off, since it seems to lose the right-hand column of tables completely, and I'd rather carry out my own psm.

OEM 4 is just amazing. Great work!!

Major B

**Comment by Shreeshrii** [comment]
For latest version, use OEM 1 for the LSTM engine. In the first
experimental version it was OEM 4.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
With default psm, psm 3, the table is getting treated as multi column input
as running columns. The right hand side info is most probably there after
the left hand info.

- excuse the brevity, sent from mobile

**Comment by amitdo** [comment]
Maybe we should print a warning:

>oem.4 was selected. That value is out of range [0-3].
Using oem 3, which is the default mode.

Something similar should be used for psm out-of-range value.

**Comment by majorbossy** [comment]
Ok. Looks like I need to wait for a working build of the latest version (I'm a java-restricted etl/sql developer).

If I use the latest UB Mannheim build with:

"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe" -oem 1 -psm 3 -c tessedit_create_hocr=1 -c tessedit_create_pdf=1 test.png test

I get:

read_params_file: parameter not found: ëPNG


And if I try:

"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe" test.png test

I get:

Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
DotProductAVX can't be used on Android

And the exe bombs out. I think this is a known issue, and I just need to wait.

Thanks

**Comment by Shreeshrii** [comment]
you need
--oem and --psm now

instead of -oem
-psm is still accepted for historical reasons

two dashes instead of one

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
you could try

Please try:
https://smani.fedorapeople.org/tmp/gImageReader_3.2.1_
qt5_i686_tesseract4.0.0.git2f10be5.exe
https://smani.fedorapeople.org/tmp/gImageReader_3.2.1_
qt5_x86_64_tesseract4.0.0.git2f10be5.exe

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment]
>"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe" -oem 1 -psm 3 -c tessedit_create_hocr=1 -c tessedit_create_pdf=1 test.png test

That is a wrong usage. It should be:
>"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe" test.png test -oem 1 -psm 3 -c tessedit_create_hocr=1 -c tessedit_create_pdf=1

**Comment by majorbossy** [comment]
"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe" test.png test --oem 1 --psm 3 -c tessedit_create_hocr=1 -c tessedit_create_pdf=1
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
ObjectCache(01210A88)::~ObjectCache(): WARNING! LEAK! object 05981790 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR/tessdata/eng.traineddatalstm-punc-dawg)
ObjectCache(01210A88)::~ObjectCache(): WARNING! LEAK! object 05963128 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR/tessdata/eng.traineddatalstm-word-dawg)
ObjectCache(01210A88)::~ObjectCache(): WARNING! LEAK! object 059631D8 still has count 1 (id C:\Program Files (x86)\Tesseract-OCR/tessdata/eng.traineddatalstm-number-dawg)

I think we're flogging a dead horse with this build.

I'll have a go at doing a java build tonight.

Thanks for your assistance.
Major B

**Comment by majorbossy** [comment]
It's not java, is it? Doh! 
Whatever, I'll try to build from source tonight.
Cheers.

**Comment by Shreeshrii** [comment]
@stweil - problem with latest 4.o windows build

I am able to reproduce the problem

```
C:\Users\User\shree>"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe"  -- version
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.
ObjectCache(56930A88)::~ObjectCache(): WARNING! LEAK! object 03658DF0 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatalstm-punc-dawg)
ObjectCache(56930A88)::~ObjectCache(): WARNING! LEAK! object 03658EA0 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatalstm-word-dawg)
ObjectCache(56930A88)::~ObjectCache(): WARNING! LEAK! object 03658F50 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatalstm-number-dawg)
ObjectCache(56930A88)::~ObjectCache(): WARNING! LEAK! object 03668ED8 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatapunc-dawg)
ObjectCache(56930A88)::~ObjectCache(): WARNING! LEAK! object 03658D90 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddataword-dawg)
ObjectCache(56930A88)::~ObjectCache(): WARNING! LEAK! object 03658E40 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatanumber-dawg)
ObjectCache(56930A88)::~ObjectCache(): WARNING! LEAK! object 0300D858 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatabigram-dawg)
ObjectCache(56930A88)::~ObjectCache(): WARNING! LEAK! object 0300D628 still has count 1 (id \Program Files (x86)\Tesseract-OCR\tessdata/eng.traineddatafreq-dawg)

C:\Users\User\shree>"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe"  san001.png test --oem 1
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Detected 18 diacritics
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by wadex1** [comment]
Hi there,

if you still get the message "DotProductAVX can't be used on Android", could it be that you try to run 32-bit code on a 64-bit machine ? This is what I'm experiencing.

If I build the lastest version with MINGW64-32 bit and try to run on a 64-bit Windows, I get this error and a crash.

If I build with 64 bit all is fine running on Windows 64 bit.
If I build with 32 bit all is fine running on Windows 32 bit.

Maybe somebody could look into the code again and check if the test for AVX is performed at runtime, not at build time.

Greetings.

**Comment by stweil** [comment]
@Shreeshrii, the output which you got is not from our [UB Mannheim](https://github.com/UB-Mannheim/tesseract/wiki) build (dated 2017-02-02). I assume that binary was build with `cmake` (which still is buggy for 32 bit Windows).
@wadex1, all builds with `configure` should work with Windows. I just repeated the test with 32 bit Tesseract on 64 bit Windows, and it works well.

**Comment by Shreeshrii** [comment]
I will uninstall and check again tomorrow.

**Comment by stweil** [comment]
> the output which you got is not from our UB Mannheim build

I now see what is different: I tested `tesseract --version` while you accidentally called `tesseract -- version` (note the blank between `--` and `version`).

**Comment by Shreeshrii** [comment]
@stweil You are right, I messed up in giving the version command.

I reinstalled versions for 2/2/17 as well as 1/30/17. Getting the error regarding AVX for both versions.

Is it possible that your local version of binary is different from the one linked from wiki?

```
C:\Users\User\shree>"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe"  san001.png test --oem 1
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Detected 18 diacritics
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
DotProductAVX can't be used on Android

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

C:\Users\User\shree>"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe"  --version
tesseract 4.00.00alpha
 leptonica-1.74.1
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.5.0) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0

 Found AVX
 Found SSE
```

**Comment by majorbossy** [comment]
Hi

I see there is a new UB Mannheim version (that works!). Thank you.

I still get one instance of "bbox 0 0 2496 3457" (ie page size) on an ocrx_word item. 
(see attached)


[test.hocr.txt](https://github.com/tesseract-ocr/tesseract/files/780304/test.hocr.txt)

Regards

**Comment by majorbossy** [comment]
Lots of examples in this one. 
[test1.hocr.txt](https://github.com/tesseract-ocr/tesseract/files/780337/test1.hocr.txt)
![test1](https://cloud.githubusercontent.com/assets/25739284/23024243/332fed4a-f451-11e6-8e18-87d61fb5342c.png)

**Comment by majorbossy** [comment]
Interestingly, they are all line segments interpreted as "I" with high word confidence!

**Comment by stweil** [comment]
My previous tests on 64 bit Windows were invalid, because my computer obviously uses an Intel CPU without AVX support. All my previous installers include indeed a tesseract.exe which fails with a AVX capable CPU. This is fixed in a new installer which I just finished.

**Comment by majorbossy** [comment]
![capture](https://cloud.githubusercontent.com/assets/25739284/23043204/7a309cde-f493-11e6-8d27-d08e90712f57.JPG)

It's not "I". It's pipes, underscores and hyphens.

**Comment by majorbossy** [comment]
Hi all

I think this is due to me abusing the psm. It's probably a bit much to switch off segmentation and still expect tess to handle tables properly.

I don't get this issue when the psm is 11.

Thanks
