### ISSUE TITLE
How to overwrite the langdata?

### ISSUE THREAD

**Issue by privatez** [tesseract-ocr/tesseract#719]
Forexample:
In the 'eng.tessdata',There are nine file.
But i want delete some file and create a new 'eng.tessdata'.
what can i do?

**Comment by Shreeshrii** [comment]
see
https://github.com/tesseract-ocr/tesseract/blob/master/doc/combine_tessdata.1.asc

**Comment by zdenop** [comment]
Please use tesseract use forum for askiny question. Please read wiki first.
