### ISSUE TITLE
STATS output on library usage

### ISSUE THREAD

**Issue by matthill** [tesseract-ocr/tesseract#72]
Using Tesseract as a library, I get a ton of this information printed to the console:

Total count=0
Min=0.00 Really=0
Lower quartile=0.00
Median=0.00, ile(0.5)=0.00
Upper quartile=0.00
Max=0.00 Really=0
Range=1
Mean= 0.00
SD= 0.00
Bottom=0, top=38, base=0, x=0

Is there any option or way to disable this?

**Comment by zdenop** [comment]
This is not bug - use tesseract forum for asking support[1]
[1] https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice

**Comment by matthill** [comment]
I disagree.  The default behavior should not be to output debug information to the console.  That should be something that needs to be turned on rather than vice-versa.

**Comment by jimregan** [comment]
There's a quote I like from the movie Jerry Maguire. Right before the more famous 'show me the money' line, there's 'help me help you'. It comes up a lot in open source.

Part of why this is not a bug report is for reasons of semantics: you didn't phrase it as a bug report, you phrased it as a support question, and you needed to add a comment to clarify that you think this is an issue. Help us help you: make your issues look like issues.

That said... issues that involve using Tesseract as a library are second class citizens, because producing a library is not the goal here. A number of people have, over the years, made some steps towards making it suitable for use as a library, though, going by some of the issues that have been filed, it's still not fully suitable for everyone's idea of what a library should be. In those cases, patches/pull requests are welcome, but otherwise, expect to see the issue left open until someone else feels like fixing it.

As for your issue, set the variable 'debug_file' to '/dev/null'. If you don't find that completely suitable, feel free to open another issue - or, better, a pull request.

**Comment by matthill** [comment]
I can take a look at patching it.  Can you point me in the right direction as to where this may be emitted from in the code?  Any idea why it happens in my compile but not in the 14.04 Tesseract lib included with Ubuntu?

Pointing to /dev/null isn't ideal, since I need to run on Windows as well.

**Comment by zdenop** [comment]
@matthill: First of all: there is an strong group of people using tesseract in C# and java (via wrappers of tesseract library) - so using user forum you can gain better support.
Next: I do not believe that nobody except you have this problem and would not report it... AFAIR this is first report regarding this output. So I expected it is connected to your code (e.g. how you use library, maybe some parameters etc.). So as I wrote on forum - please provide simple example to demonstrate problem.

**Comment by jimregan** [comment]
The debug printing routing will select 'nul' on windows, if 'debug_file' is set to '/dev/null'.

I have no idea why it happens in your compile and not in Ubuntu: you haven't said how you compiled it.

**Comment by matthill** [comment]
@zdenop I've posted on the user forum as you've suggested.  I can leave this alone if you like.  I assumed this report is valuable for you and that you would want to get more information.  But if it's not important and/or interesting, I can definitely drop it and go away :)

I know other users (of my library) have run into this.  Here's a user forum post describing their issue: https://groups.google.com/forum/#!searchin/openalpr/quartile/openalpr/2x9r5_n6KvY/6ywYI8swTsMJ  I also know of one other that has run into it.  Perhaps other people just don't take the time to report it.  Or perhaps I'm using Tesseract in a strange way that only affects me.

Here's my usage of the Tesseract library
https://github.com/openalpr/openalpr/blob/master/src/openalpr/ocr.cpp

The only non-standard thing I do (I think) is turn on this option: tesseract.SetVariable("save_blob_choices", "T"); and read all the various possibilities.

I compiled the 3.04 library as follows:
export LIBLEPT_HEADERSDIR=/storage/projects/alpr/libraries/leptonica-1.72/src/
./configure --with-extra-libraries=/storage/projects/alpr/libraries/leptonica-1.72/src/.libs/
make

**Comment by pracplayopen** [comment]
We also see this information compiling 3.04 branch with default options, as of today.

I notice the original poster got no response on forums, so I'm copying here too.

We did run 'strip --strip-debug' on both tesseract304 and lept172 bins and libraries before release.   This is for an existing code base that is being ported from windows to linux.   All the unit tests are passing in both cases, it appears to be just cosmetic but it's quite a large amount of info to be reported if/when everything is working.

**Comment by amitdo** [comment]
Doing 'strip' won't help you here.

>As for your issue, set the variable 'debug_file' to '/dev/null'.

>The debug printing routing will select 'nul' on windows, if 'debug_file' is set to '/dev/null'.

**Comment by pracplayopen** [comment]
Not sure what you mean...

if you're saying 'strip' won't remove the message here, agree.

just included for thoroughness (it's about only thing we changed from
source w/default builds of aforementioned branches)

**Comment by pracplayopen** [comment]
whups missed 2nd part of reply.

we're unfamiliar outside of tesseract beyond emgu and our examples... if
others reading this are the same, here is the instructions on changing
'debug_file' in tesseract

https://github.com/tesseract-ocr/tesseract/wiki/FAQ#how-can-i-make-the-error-messages-go-to-tesseractlog-instead-of-stderr

thx, will try and report

**Comment by pracplayopen** [comment]
also here is a cross-post to users thread (the response I got there is to
upgrade... which we definately plan on doing once we get existing stuff
working on both platforms ;)

https://groups.google.com/d/msg/tesseract-ocr/-K5d2euBJ_I/rEm2eNgdAgAJ

sorry for cross post but more people were complaining than posting answers
so hopefully this bumps up this thread.

will lyk, gr8 work on tesseract... excited to try new version

**Comment by amitdo** [comment]
You'll get the same problem with any newer version, and the solution is the same.

**Comment by pracplayopen** [comment]
sounds good thx 4 reply

**Comment by pracplayopen** [comment]
suggestion corrected the issue, thx again.
