### ISSUE TITLE
Tesseract with OpenCL without speed improvement

### ISSUE THREAD

**Issue by jsamon** [tesseract-ocr/tesseract#722]
I compile tesseract 3.04 with OpenCL support and I install it on an Ubuntu 16.04 64-bit machine. The machine  has an intel core i5 CPU and an nvidia geforce 1080gtx with cuda 8.0 GPU. 

When I run tesseract from command line  I get:

$ tesseract phototest.tif out -l eng
tesseract: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by tesseract)
[DS] Profile read from file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 1:GeForce GTX 1080 score is 0.106336
[DS] Device[2] 0:(null) score is 0.895098
[DS] Selected Device[1]: "GeForce GTX 1080" (OpenCL)
Tesseract Open Source OCR Engine v3.04.02dev with Leptonica

I make a lot of tests using C++ API, python wrapper and command line but I didn’t notice any improvement on speed. Do I miss something?

**Comment by stweil** [comment]
There had been some [code improvements](https://github.com/tesseract-ocr/tesseract/commits/3.05) for OpenCL in 3.05. Maybe you want to try that version.

**Comment by jsamon** [comment]
Well I install tesseract 3.05.00 (I also install leptonica from source) but the result was the same. No speed improvement. How can we explain that I don’t have any speed up?
Please note (see below) a warning related to libOpenCL.so “no version information available (required by tesseract)”.  


$ tesseract -v
tesseract: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by tesseract)
tesseract 3.05.00
 leptonica-1.74.1
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8

 OpenCL info:
  Found 1 platforms.
  Platform name: NVIDIA CUDA.
  Version: OpenCL 1.2 CUDA 8.0.46.
  Found 1 devices.
    Device 1 name: GeForce GTX 1080.



$ tesseract test.tif out
tesseract: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by tesseract)
[DS] Profile file not available (tesseract_opencl_profile_devices.dat); performing profiling.

[DS] Device: "GeForce GTX 1080" (OpenCL) evaluation...
[DS] Device: "GeForce GTX 1080" (OpenCL) evaluated
[DS]          composeRGBPixel: 0.015255 (w=1.2)
[DS]            HistogramRect: 0.009756 (w=2.4)
[DS]       ThresholdRectToPix: 0.007360 (w=4.5)
[DS]        getLineMasksMorph: 0.004570 (w=5.0)
[DS]                    Score: 0.097692

[DS] Device: "(null)" (Native) evaluation...
[DS] Device: "(null)" (Native) evaluated
[DS]          composeRGBPixel: 0.015348 (w=1.2)
[DS]            HistogramRect: 0.058428 (w=2.4)
[DS]       ThresholdRectToPix: 0.018490 (w=4.5)
[DS]        getLineMasksMorph: 0.122624 (w=5.0)
[DS]                    Score: 0.854966
[DS] Scores written to file (tesseract_opencl_profile_devices.dat).
[DS] Device[1] 1:GeForce GTX 1080 score is 0.097692
[DS] Device[2] 0:(null) score is 0.854966
[DS] Selected Device[1]: "GeForce GTX 1080" (OpenCL)
Tesseract Open Source OCR Engine v3.05.00 with Leptonica

**Comment by jbreiden** [comment]
I think the OpenCL implementation is at risk in general. The OpenCL TIFF decoder has fallen behind the C implementation and is currently disabled.  There is no OpenCL implementation for the LSTM recognizer in Tesseract 4.x. I'm not sure what the performance we expect from OpenCL on the Tesseract 3.x recognizer, but your report is not giving me much confidence.

If I were in charge of OpenCL stuff on Tesseract (and I am definitely not!) I would look at the LSTM recognizer. Specifically the portion that is currently using AVX2 assembly instructions, which is the primary hotspot.

**Comment by zdenop** [comment]
OpenCL is just experimental feature, so having no effect is possible results.
Please read other issues/tesseract forums about OpenCL.

**Comment by stweil** [comment]
Tesseract tests whether OpenCL is better than the CPU and calculates a score based on weighted timings of several different basic operations.

Here is a typical result on a MacBook Pro:

    [DS] Device: "Iris" (OpenCL) evaluation...
    [DS] Device: "Iris" (OpenCL) evaluated
    [DS]          composeRGBPixel: 0.009361 (w=1.2)
    [DS]            HistogramRect: 0.167102 (w=2.4)
    [DS]       ThresholdRectToPix: 0.004588 (w=4.5)
    [DS]        getLineMasksMorph: 0.015459 (w=5.0)
    [DS]                    Score: 0.510220

    [DS] Device: "(null)" (Native) evaluation...
    [DS] Device: "(null)" (Native) evaluated
    [DS]          composeRGBPixel: 0.022881 (w=1.2)
    [DS]            HistogramRect: 0.074672 (w=2.4)
    [DS]       ThresholdRectToPix: 0.042662 (w=4.5)
    [DS]        getLineMasksMorph: 0.140875 (w=5.0)
    [DS]                    Score: 1.103025

The CPU is faster for `HistogramRect` and slower for all other operations. The weighted score favors OpenCL. If `HistogramRect` is used very often, it would be better to use the CPU. This is what I observe for a larger image.

Instead of using a weighted score, Tesseract could always use the faster option. I expect that this potential mix of CPU and OpenCL would give the shortest execution time.
