### ISSUE TITLE
[Clarification request/Improvement] Add version and github info always, also when --enable-debug was missing

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#723]
I know, that `tesseract --version` outputs the exact version and github commit hash, **if** it was compiled with `./configure --enable-debug`, example:
```
tesseract 4.00.00alpha-278-gc768b58
 leptonica-1.74.1
  libjpeg 6b (libjpeg-turbo 1.3.1) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8

 Found AVX
 Found SSE
```

I wonder, why this is not output, when the configuration setting was not given and I suggest to modify the build code so that the version and github commit hash is **always** shown with the `--version`command.

**Comment by Shreeshrii** [comment]
Yes. I agree, adding version info with github commit hash in non-debug builds will be very helpful.

An earlier request - https://github.com/tesseract-ocr/tesseract/issues/581#issuecomment-267339390

**Comment by Shreeshrii** [comment]
Needs change in 

https://github.com/tesseract-ocr/tesseract/blob/fd0683f9e03934bbdf7fbebb4d21d64c37b68bc0/api/baseapi.cpp#L140

**Comment by zdenop** [comment]
Duplicate to #581

**Comment by Wikinaut** [comment]
@zdenop Is https://github.com/tesseract-ocr/tesseract/blob/fd0683f9e03934bbdf7fbebb4d21d64c37b68bc0/api/baseapi.cpp#L140 the only change needed, and would you accept a corresponding pull request ?

**Comment by zdenop** [comment]
I am against to show GIT_REV in release mode:

- Experienced users/testers should know what they are doing, what their are testing
- Inexperienced users should use released stable version

**Comment by Wikinaut** [comment]
@zdenop Where exactly is your problem to print the GIT_REV when users use --version ?

I *have a problem when, as an expert, I run always the latest version, but sometimes after git pull the latest build is not the "installed" build. As a user I want to have the fastest code, i.e. built *without* --enable-debug.

I again request to think over it, and to always - if available - burn the GIT_REV into the code. I ask you for this.

**Comment by Wikinaut** [comment]
Not using `--enable-debug` increases processing speed about 6%.

**Comment by stweil** [comment]
@zdenop, what about using GIT_REV only for versions without tag, no matter whether it is a debug or a release build? Then released stable versions would not show GIT_REV.

**Comment by amitdo** [comment]
>Not using --enable-debug increases processing speed about 6%.

Only ~6%? With LSTM mode?

https://github.com/tesseract-ocr/tesseract/issues/40#issuecomment-263432042

**Comment by amitdo** [comment]
BTW, maybe we should add another debug/optimization option `-Og`?
https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

**Comment by Shreeshrii** [comment]
```
#!/bin/bash
# git rev-list  `git rev-list --tags --no-walk --max-count=1`..HEAD --count
revisioncount=`git log --oneline | wc -l`
projectversion=`git describe --tags --long`
cleanversion=${projectversion%%-*}
#echo "$projectversion-$revisioncount"
#echo "$cleanversion-$revisioncount"
sed -i -e 's/.*TESSERACT_VERSION_STR.*/#define TESSERACT_VERSION_STR "'"$cleanversion-$revisioncount"'"/g' ./api/baseapi.h
```

can be used to update the TESSERACT_VERSION_STR with the latest commit #.

**Comment by Shreeshrii** [comment]
This has now been implemented.```
tesseract -v
tesseract 4.0.0-beta.1-59-g2cc4
 leptonica-1.76.0
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8

 Found AVX
 Found SSE
```

Please check with latest code from master and close the issue.

**Comment by Wikinaut** [comment]
I tried to build the new master version but ```make``` stopped with
```
libtool:   error: REVISION '00' must be a nonnegative integer
libtool:   error: '4:00' is not valid version information
```

**Comment by Shreeshrii** [comment]
How are you trying to build? I used the following today, without any problem.

#!/bin/bash
./autogen.sh
./configure --disable-openmp  --disable-graphics --disable-opencl
make
sudo make install
sudo ldconfig
make training
sudo make training-install

**Comment by Wikinaut** [comment]
```
make distclean
git pull upstream master
./autogen.sh
./configure
make
```

**Comment by Shreeshrii** [comment]
@stweil Please see make error above.

**Comment by stweil** [comment]
@Wikinaut, it looks like you are using git, but your latest tag does not match the expectations (MAJOR.MINOR.PATCH with MAJOR, MINOR and PATCH being numerical values, maybe followed by additional non-numeric characters). The latest tag should be `4.0.0-beta.1`. What do you get if you run `git describe --abbrev=4`?

**Comment by Wikinaut** [comment]
I just built the master branch, as usual.

**Comment by Wikinaut** [comment]
@stweil have a look (I just updated this above) to the make output

libtool: link: ( cd ".libs" && rm -f "libtesseract_api.la" && ln -s "../libtesseract_api.la" "libtesseract_api.la" )
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11 -L/usr/local/lib -llept  -version-info 4:00 -no-undefined   -o libtesseract.la -rpath /usr/local/lib  libtesseract_api.la ../ccmain/libtesseract_main.la ../textord/ltesseract_textord.la ../wordrec/libtesseract_wordrec.la ../classify/libtesseract_classify.la ../dict/libtesseract_dict.la ../arch/libtesseract_arch.la ../arch/libtesseract_avx.la ../arch/libtesseract_avx2.la ../arch/libtesseract_sse.l../lstm/libtesseract_lstm.la ../ccstruct/libtesseract_ccstruct.la ../cutil/libtesseract_cutil.la ../viewer/libtesseract_viewer.la ../ccutil/libtesseract_ccutil.la ../opencl/libtesseract_opencl.la  -lpthread 


Especially to ``` -version-info 4:00 ```. Is the colon correct?

**Comment by stweil** [comment]
@Wikinaut, your local git has the latest code, but not the latest tags. It still uses the old tag `4.00.00dev`. Are you pulling from your personal fork (where the tag might be missing)? If you pull from `tesseract-ocr`, you should automatically get the latest tag, unless you have disabled that in your git settings. Try `git pull --tags` to force pulling all tags.

**Comment by stweil** [comment]
The error message which you see comes from ` -version-info 4:00`. It should be ` -version-info 4:0`.

**Comment by Shreeshrii** [comment]
What info do u see for `git remote -v`?

**Comment by Wikinaut** [comment]
@Shreeshrii 
```
origin  git@github.com:Wikinaut/tesseract.git (fetch)
origin  git@github.com:Wikinaut/tesseract.git (push)
upstream        https://github.com/tesseract-ocr/tesseract.git (fetch)
upstream        https://github.com/tesseract-ocr/tesseract.git (push)
```

**Comment by Shreeshrii** [comment]
> Try `git pull --tags` to force pulling all tags.

and then

> run `git describe --abbrev=4`

**Comment by stweil** [comment]
`git fetch --all --tags`, then we are sure that you won't miss a tag. :-)

**Comment by Wikinaut** [comment]
ok, works now.

Result as wanted:
```
tesseract -v
tesseract 4.0.0-beta.1-59-g2cc4
 leptonica-1.75.3
  libjpeg 6b (libjpeg-turbo 1.5.1) : libpng 1.2.50 : libtiff 4.0.8 : zlib 1.2.8

 Found AVX2
 Found AVX
 Found SSE
```

Closing this as solved, thanks.

**Comment by amitdo** [comment]
>tesseract 4.0.0-beta.1-59-g2cc4

@stweil, according to the semver 2.0.0 spec, there should be only one `-`. The rest should be replaced by dots.

BTW, from where the field before the commit hash comes from?
 (59 here)

**Comment by Shreeshrii** [comment]
I think that is number of commits since last tag, beta.1

**Comment by stweil** [comment]
`4.0.0-beta.1-59-g2cc4` is not a semver tag, so I don't think that the semver spec applies here.

As @Shreeshrii already said, 59 is the number of commits since the last tagged version. The 'g' before the hash might stand for 'git'.
