### ISSUE TITLE
Not able to get correct ouput for tables 

### ISSUE THREAD

**Issue by varun1994varun** [tesseract-ocr/tesseract#724]
Hi,
I am currently using tesseract version 3.05 with leptonica version 1.73.
I want to get the ouput from an image which consists of tables of numerical data.
But  the output which I am getting after the processing of tesseract is way different than the original image.
Should I modify anything in the config file or the code to make it work?
A reference  is attached which is similar to the original image.
https://www.google.com/search?q=sensex+data&espv=2&biw=1280&bih=914&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjaxcG9oZbSAhXDVyYKHXKjBnIQ_AUICCgD#imgrc=REJCkEnS1S-bLM:

Thank You.

**Comment by Shreeshrii** [comment]
You need to pre process your image.
Convert to black and white and 300 dpi.

See attached files for image converted using Irfanview, processed using --oem 0 (legacy tesseract ocr engine) and --oem 1 (new lstm engine).

```
#!/bin/bash
export TESSDATA_PREFIX=/mnt/c/Users/User/shree/tesseract-ocr
 
    img_files=$(ls ./Sen*bw.png)
    for img_file in ${img_files}; do
        ls ${img_file}
        filename=$(basename "${img_file##*/}" .png)
        echo ${filename} "oem 1"
        time tesseract ${img_file} ${filename}-eng-oem1  --oem 1 --psm 6 -l eng   logfile
        cp tesseract.log ${filename}-eng-oem1-log.txt
        echo ${filename} "oem 0"
        time tesseract ${img_file} ${filename}-eng-oem0  --oem 0 --psm 6 -l eng   logfile
        cp tesseract.log ${filename}-eng-oem0-log.txt
    done    
```

```
./SensexMonthly-bw.png
SensexMonthly-bw oem 1

real    2m19.615s
user    4m52.203s
sys     0m7.031s

SensexMonthly-bw oem 0

real    0m30.366s
user    0m27.828s
sys     0m0.781s
```
[SensexMonthly-bw-eng-oem0.txt](https://github.com/tesseract-ocr/tesseract/files/782442/SensexMonthly-bw-eng-oem0.txt)
[SensexMonthly-bw-eng-oem1.txt](https://github.com/tesseract-ocr/tesseract/files/782443/SensexMonthly-bw-eng-oem1.txt)
![sensexmonthly-bw](https://cloud.githubusercontent.com/assets/5095331/23054732/adf795d0-f507-11e6-8bec-d2fd46bf1073.png)

**Comment by varun1994varun** [comment]
Hi Shreeshrii,
Thanks for your reply.
I am able to get the desired output with the preprocessing of the images.
Cheers!

**Comment by amitdo** [comment]
Another option:
https://github.com/tesseract-ocr/tesseract/issues/736#issuecomment-381418910
Should be tested on all supported platforms.

You can replace putenv with _putenv
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/putenv-wputenv?view=vs-2017
