### ISSUE TITLE
Can tesseract be used to do bar code identification？

### ISSUE THREAD

**Issue by cfk1990** [tesseract-ocr/tesseract#725]
I want to build a model with a image of bar code as input and output the number sequence corresponding to the bar code. 
Input:
![image](https://cloud.githubusercontent.com/assets/10412402/23064393/df2e88a0-f54a-11e6-860b-c0ea20f1575f.png)

Output:
6922872789071

This task is similar to speech recognition. Can tesseract be used to do this?

**Comment by jbreiden** [comment]
Why don't you use zxing which is built specifically for this?

**Comment by zdenop** [comment]
OCR is  Optical Character Recognition. Anyway - use tesseract user forum for asking questions.
