### ISSUE TITLE
Pdf-Output with jbig2enc?

### ISSUE THREAD

**Issue by boredland** [tesseract-ocr/tesseract#726]
Searching for a place to introduce JBig2-compression into my quite typical workflow I stumbled upon tesseract actually generating sandwiches - which is nice. Are there any plans to offer alternative to the, i assume, flate-compression currently used?

**Comment by jbreiden** [comment]
JBIG2 and mixed raster content is a very challenging topic.  No current plans with respect to Tesseract.

**Comment by amitdo** [comment]
>Are there any plans to offer alternative to the, i assume, flate-compression currently used?

https://github.com/tesseract-ocr/tesseract/blob/ca16a08c10/api/pdfrenderer.cpp#L729
