### ISSUE TITLE
LSTM: Marathi traineddata does worse compared to Hindi traineddata for Marathi documents

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#729]
Images and Ground truth at 
https://github.com/Shreeshrii/tess4eval_marathi

OCR eval reports at
https://shreeshrii.github.io/tess4eval_marathi/

**Comment by Shreeshrii** [comment]
Similarly for Nepali - please see https://groups.google.com/forum/#!topic/tesseract-ocr/m2Dx6a-srvo

> I got the same result as yours with hin.traineddata which is better than nep.traineddata. I think the langdata need some revisions

**Comment by amitdo** [comment]
If the the source of the issue is the traineddata, maybe you should move this issue to the langdata issues.

**Comment by Shreeshrii** [comment]
Ok. Will do.
