### ISSUE TITLE
tesseract-3.04.00 fails to compile with --disable-graphics

### ISSUE THREAD

**Issue by tom111** [tesseract-ocr/tesseract#73]
When scrollview is disabled in configure, linking fails (because it still uses scrollview)

    libtool: link: g++ -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o  ./.libs/libtesseract.so -lrt -llept -lpthread
    ./.libs/libtesseract.so: undefined reference to `ScrollView::Brush(ScrollView::Color)'
    ...
    ./.libs/libtesseract.so: undefined reference to `window_wait(ScrollView*)'
    ./.libs/libtesseract.so: undefined reference to `ScrollView::TextAttributes(char const*, int, bool, bool, bool)'
    collect2: error: ld returned 1 exit status
    Makefile:577: recipe for target 'tesseract' failed

**Comment by zdenop** [comment]
This is fixed in 27b8a5cc89898c3f12dae57a58b15efddee9fe18
