### ISSUE TITLE
Training: how to create a image using text2image when the text contains mixed language

### ISSUE THREAD

**Issue by dipthomas** [tesseract-ocr/tesseract#730]
I will training a new model to recognize chinese, english and some special symbol, now i can not create the image with text2image because the font file may not cover all text. How could I to solve this situation.

**Comment by Shreeshrii** [comment]
What version of Tesseract are you using?

Have you tried using multiple languages for recognition, eg. -l eng+chi

- excuse the brevity, sent from mobile

**Comment by dipthomas** [comment]
@Shreeshrii , I am using Tesseract 4.0, and I want to train a model including English, Chinese and some math symbol like △. 
Now the problem is I can not generate the training image via a single font. (text2image)

**Comment by Shreeshrii** [comment]
The training process drops unrenderable words. So the letters not included
in the font will get dropped, if you use a combined text with multiple
languages and run text2image with different fonts.

You will then get some images with text in one language and some in the
other.

However, I don't know how successful this will be. You will need a large
amount of text to train.

I have not had much success in training 4.0. please share your experiences
if you try the above approach.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
Have you tried with
https://github.com/tesseract-ocr/tessdata/blob/master/chi_sim.traineddata

https://github.com/tesseract-ocr/langdata/tree/master/chi_sim
shows the kind of combination you are talking about ..

https://github.com/tesseract-ocr/langdata/blob/master/chi_sim/chi_sim.training_text
https://github.com/tesseract-ocr/langdata/blob/master/chi_sim/desired_characters
https://github.com/tesseract-ocr/langdata/blob/master/chi_sim/chi_sim.training_text.unigram_freqs

You can try to find fonts that support the training text by using command
similar to following (change location of fonts and langdata to match your
setup):

text2image --find_fonts \
--fonts_dir /usr/share/fonts \
--text ./langdata/chi_sim/chi_sim.training_text \
--min_coverage .9  \
--outputbase ./langdata/chi_sim/chi_sim\
|& grep raw | sed -e 's/ :.*/" \\/g'  | sed -e 's/^/  "/'
>./langdata/chi_sim/fontslist.txt

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
https://chinesefontdesign.com/tag/simplified-chinese-font

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
@dipthomas If problem is resolved, please close the issue. Thanks!

**Comment by hanoilu** [comment]
@Shreeshrii Your reply is very detailed, thank you

**Comment by yuvarajanS** [comment]
Hi @Shreeshrii ,
I am looking for a trained data for the bullet character. It should work even if we are using mulitple language in a single string.

Can you please provide the trained data for bullet character or guide me how to do do this?

**Comment by Shreeshrii** [comment]
Try using the best/Latin traineddata

You can use the command

Combine_tessdata -u to unpack the traineddata file and check that the
unicharset has the bullet character.

**Comment by yuvarajanS** [comment]
I tried Latin, we didnt get bullet character!

tried Combine_tessdata, using that i am able to unpack that trained data.Can you help us how to see the uncharset contains the bullet character?
Can you please help on this?

Thanks

**Comment by Shreeshrii** [comment]
what is the unicode number for bullet character?

**Comment by yuvarajanS** [comment]
its (U+2022) •

**Comment by Shreeshrii** [comment]
Please see https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for--a-few-characters

and follow instructions there for the bullet character.

**Comment by shobamohan123** [comment]
I wish to add person with disability symbol into tesseract dataset. How shall i do this? Can anyone help me for this?

**Comment by Shreeshrii** [comment]
Use plus minus type of training, see wiki for details

**Comment by shobamohan123** [comment]
I tried for creating tff file for the PwD symbol using jesstexteditor and faied to do so. I google about plus minus type of training and find your respository files in the link https://github.com/Shreeshrii/tessdata4alpha/blob/master/fast/digits.traineddata. However after downloading the file, i cant view this file. Can you please help me?

**Comment by Shreeshrii** [comment]
Tesseract training wiki page is at

https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00

Please read the whole page and focus on the following regarding plusminus
training.

https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for--a-few-characters

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
>>I tried for creating tff file for the PwD symbol using jesstexteditor
and faied to do so.

Are you sure that the font you used has that symbol?

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by shobamohan123** [comment]
Hi Shree,
Yes, it has the symbol but i got error message as the image does not have recognized font.

**Comment by Shreeshrii** [comment]
Please try training using tesstrain.sh - if you are training for tesseract
4.00

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by shobamohan123** [comment]
Hi 
I am reviewing the link https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00.
I am new to this tesseract i would like to ask some of the basic question
the installing instructions given in the link is suitable for windows?
I am using tesseract in python, installed in anaconda navigator,for reading the numbers from license plate. I need the test data which are only numbers from 0 to 9 along with PwD symbol. I dont require albhapets a to z.
Can you please guide me for creating test data?

**Comment by Shreeshrii** [comment]
Sorry, I am not familiar with python.

For your application tesseract 3.0x would also be suitable.

Why do you want to use tesseract 4?



On 28-Feb-2018 3:00 PM, "shobamohan123" <notifications@github.com> wrote:

Hi
I am reviewing the link https://github.com/tesseract-ocr/tesseract/wiki/
TrainingTesseract-4.00.
I am new to this tesseract i would like to ask some of the basic question
the installing instructions given in the link is suitable for windows?
I am using tesseract in python, installed in anaconda navigator,for reading
the numbers from license plate. I need the test data which are only numbers
from 0 to 9 along with PwD symbol. I dont require albhapets a to z.
Can you please guide me for creating test data?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tesseract-ocr/tesseract/issues/730#issuecomment-369176923>,
or mute the thread

**Comment by shobamohan123** [comment]
Thank you. Is tesseract 3.0x having provision for training other than fonts? Please give insights about it.

**Comment by shobamohan123** [comment]
I have a simple doubt about training. I read training articles its all highlighting the training the numbers and alphabets but i haven't found information about training kind of symbol. You had great experience in the training can you suggest me is there possiblities to train like symbols.

**Comment by Shreeshrii** [comment]
Yes. It should be possible. Use fonts which support the symbol for
training. http://www.fileformat.info/info/unicode/char/267f/fontsupport.htm

You can look at jtessboxeditor for 3.0x training

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by shobamohan123** [comment]
Thank you. I will try and updates you further

**Comment by shobamohan123** [comment]
I entered utf-8 characters of wheelchair i.e. 0xE2 0x99 0xBF (e299bf) in notepad++ and save this as .txt document. I opened the JTessboxEditorFX and created .tif and .box files and saved it in the folder name sample under JTessBoxEditor. Is it right way of doing? If you provide me step by steps procedure for creating trained data is great help for me.

**Comment by Shreeshrii** [comment]
Look at the sample for Vietnamese in jtessboxeditor.

You will need to provide other required files for training (from langdata
repo).

It has been a while since I used jtessboxeditor. Please read it's help file.

**Comment by Shreeshrii** [comment]
I would suggest that you make training text with all characters you need to
recognize and train it.

On 01-Mar-2018 3:41 PM, "ShreeDevi Kumar" <shreeshrii@gmail.com> wrote:

Look at the sample for Vietnamese in jtessboxeditor.

You will need to provide other required files for training (from langdata
repo).

It has been a while since I used jtessboxeditor. Please read it's help file.

**Comment by Shreeshrii** [comment]
@shobamohan123 

Take a look at https://github.com/openalpr/train-ocr

That might be more in line with what you are trying to do.
