### ISSUE TITLE
Misaligned (wrong?) debug log

### ISSUE THREAD

**Issue by kolomiyets** [tesseract-ocr/tesseract#735]
System: Ubuntu Server 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

--> Context 
Mean rms=0.216%, delta=0.082%, train=0.291%(1.84%), skip ratio=0%
Iteration 2095731: ALIGNED TRUTH : B5-0304/2002 B5-0304/2003 IPA-Mitteln Freyler unterstreicht, Nachbarländer! taxfrei Bleib wiederfanden, „Zimmermann-Depesche".
Iteration 2095731: BEST OCR TEXT : B5-0304/2002 B5-0304/2003 IPA-Mitteln Freyler unterstreicht, Nachbarländer! taxfrei Bleib wiederfanden, „Zimmermann-Depesche".
File /tmp/tmp.2tf2jsTb4V/deu/deu.Comic_Sans_MS_Bold.exp0.lstmf page 12456 (Perfect):
Mean rms=0.216%, delta=0.082%, train=0.291%(1.84%), skip ratio=0%

---> Misaligned debug log below: Rückständen <> Riückständen but displays (Perfect)

Iteration 2095732: ALIGNED TRUTH : Rückständen Helyette Taschkent Asymmetrie hinausgeht". Mühlecker Abschlußprüfung Vergleich Hebelenhof explodierender explodierenden Prüße gelernt? Elsternstraße (Fluggastdatensätze), gelernt; Bechstedter gelernt: Münzunion
Iteration 2095732: BEST OCR TEXT : Riückständen Helyette Taschkent Asymmetrie hinausgeht". Mühlecker Abschlußprüfung Vergleich Hebelenhof explodierender explodierenden Prüße gelernt? Elsternstraße (Fluggastdatensätze), gelernt; Bechstedter gelernt: Münzunion
File /tmp/tmp.2tf2jsTb4V/deu/deu.Bodoni_MT_Condensed.exp0.lstmf page 15594 (Perfect):

At the same time non-perfect matches show no char difference at all.

Iteration 2095511: ALIGNED TRUTH : Flugverbotslisten. („Emmas technischen, Friedrich-Naumann-Stiftung, eSafety initiative! „globalen" Silencer "signing"
Iteration 2095511: BEST OCR TEXT : Flugverbotslisten. („Emmas technischen, Friedrich-Naumann-Stiftung, eSafety initiative! „globalen" Silencer "signing"
File /tmp/tmp.2tf2jsTb4V/deu/deu.Verdana_Bold_Italic.exp0.lstmf page 6013 :
Mean rms=0.214%, delta=0.076%, train=0.276%(1.753%), skip ratio=0%

**Comment by Shreeshrii** [comment]
```

Iteration 1479: ALIGNED TRUTH : 21373 32172
Iteration 1479: BEST OCR TEXT : 21373 32172
File /tmp/tmp.Uh8MurvPxb/ssd/ssd.Digital_dream.exp0.lstmf page 672 (Perfect):
Mean rms=0.463%, delta=0.324%, train=1.284%(4.784%), skip ratio=0%
Iteration 1480: ALIGNED TRUTH : 25406 36400 87320 54223 44911 92660 09541
Iteration 1480: BEST OCR TEXT : 25406 36400 87320 54223 4498911 92660 09541
File /tmp/tmp.Uh8MurvPxb/ssd/ssd.Digital_dream.exp0.lstmf page 1044 (Perfect):
Mean rms=0.463%, delta=0.323%, train=1.282%(4.77%), skip ratio=0%
Iteration 1481: ALIGNED TRUTH : 70653 77523 77060 00068 04759 13686 82664
```

Iteration is marked perfect when there is visible difference in the debug output:

44911 
4498911

**Comment by Shreeshrii** [comment]
Another example

```
File /tmp/tmp.Uh8MurvPxb/ssd/ssd.Digital_dream.exp0.lstmf page 749 (Perfect):
Mean rms=0.422%, delta=0.253%, train=0.988%(3.92%), skip ratio=0%
Iteration 1613: ALIGNED TRUTH : 55062 03298
Iteration 1613: BEST OCR TEXT : 5506e2 03298
File /tmp/tmp.Uh8MurvPxb/ssd/ssd.Digital_dream.exp0.lstmf page 859 (Perfect):
```

**Comment by amitdo** [comment]
I think 'Perfect' here means the BEST OCR TEXT and the ground truth text match perfectly.

**Comment by Shreeshrii** [comment]
@amitdo Yes, but the text being displayed under ALIGNED TRUTH is not matching the BEST OCR TEXT in these cases. 

In most cases when the lines are marked perfect, they do match, in these 'rare' cases they don't.

**Comment by amitdo** [comment]
The ground truth is the transcribed text for each line in the image.

'ALIGNED TRUTH' is not 'Ground Truth'.

**Comment by amitdo** [comment]
The ground truth is taken from the box file.

**Comment by Shreeshrii** [comment]
What is 'ALIGNED TRUTH'?

In  lstmtrainer.cpp

```
  STRING ocr_text = DecodeLabels(ocr_labels);
  STRING truth_text = DecodeLabels(truth_labels);
```
```
    tprintf("Iteration %d: BEST OCR TEXT : %s\n", training_iteration(),
            ocr_text.string());
```
```
    STRING text = DecodeLabels(labels);
    tprintf("Iteration %d: ALIGNED TRUTH : %s\n",
            training_iteration(), text.string());
```

**Comment by amitdo** [comment]
There is a technical explanation here: 
https://github.com/tmbdev/ocropy/issues/17

**Comment by Shreeshrii** [comment]
Thanks, Amit.

Maybe, like ocropy, tesseract should also display all three - Ground Truth, Aligned Truth and OCR text during debug.

**Comment by amitdo** [comment]
>Maybe, like ocropy, tesseract should also display all three - Ground Truth, Aligned Truth and OCR text during debug.

I agree :-)

**Comment by Shreeshrii** [comment]
@amitdo Is there any TODO here or should this be closed?

**Comment by amitdo** [comment]
TODO: Add GROUND TRUTH to the training output.

**Comment by Shreeshrii** [comment]
I added

```
    if (truth_text.string() != text.string()) {
         tprintf("Iteration %d: GROUND  TRUTH : %s\n",
            training_iteration(), truth_text.string());
    }
```

But, still it seems to print matching aligned and ground truth ...

```
Iteration 1043: GROUND  TRUTH : Your of both find Sign first In article . American International the video Public Software product
Iteration 1043: ALIGNED TRUTH : Your of both find Sign first In article . American International the video Public Software product
Iteration 1043: BEST OCR TEXT : Vour of both find Sign first In article . American International the video Public Software product
File /tmp/eng-2019-03-30.Lcy/eng.Consolas.exp0.lstmf page 26 :
Mean rms=1.865%, delta=3.23%, train=13.296%(25.289%), skip ratio=0%
Iteration 1044: GROUND  TRUTH : This PATENTSCOPE your Profile different iPod 2003 password new News will through their
Iteration 1044: ALIGNED TRUTH : This PATENTSCOPE your Profile different iPod 2003 password new News will through their
Iteration 1044: BEST OCR TEXT : This PATENTSCOPE your Profile different iPod 2003 password new News will through their
File /tmp/eng-2019-03-30.Lcy/eng.Courier_New_Bold.exp0.lstmf page 36 (Perfect):
Mean rms=1.859%, delta=3.206%, train=13.215%(25.189%), skip ratio=0%
Iteration 1045: GROUND  TRUTH : Contact Sign on at Show 13 C how 0 ... Loading... here, one 0 rights should World ounder has
Iteration 1045: ALIGNED TRUTH : Contact Sign on at Show 13 C how 0 ... Loading... here, one 0 rights should World ounder has
Iteration 1045: BEST OCR TEXT : Contact Sign on at Show 13 C how O0 ... Loading... here, one 0 rights should World ounder has
File /tmp/eng-2019-03-30.Lcy/eng.Courier_New.exp0.lstmf page 37 :
Mean rms=1.854%, delta=3.193%, train=13.123%(25.095%), skip ratio=0%

```

What am I missing?

**Comment by amitdo** [comment]
drop the '.string()' from the condition.

**Comment by amitdo** [comment]
Also, I think you should compare   truth_text to ocr_text, and not to text.

**Comment by Shreeshrii** [comment]
>drop the '.string()' from the condition.

Thanks. 

> I think you should compare truth_text to ocr_text, and not to text.

In most cases GROUND TRUTH (truth_text) is same as ALIGNED TRUTH (text). Rather than print all 3 lines I thought to print it only when different.

Should I swap, i.e. print GROUND TRUTH and OCR TEXT in all cases and add ALIGNED TRUTH when different?

**Comment by Shreeshrii** [comment]
@amitdo Please see https://github.com/tesseract-ocr/tesseract/pull/2361

Is that alright?

**Comment by amitdo** [comment]
Shreeshrii,

Welcome back! :-)

Can we close this issue?

**Comment by Shreeshrii** [comment]
```
Iteration 192455: GROUND  TRUTH : জুয়াড়ি গেলো। 2016-07-10, দুঃখ' আলু শিল্প পৌঁছে ইউনিকোড ভালো
Iteration 192455: BEST OCR TEXT : জ্ুয়াড়ি গেলো। 2016-07-10, দুঃখ' আলু শিল্প পৌঁছে ইউনিকোড ভালো
File /tmp/ben-2021-03-15.kM8/ben.Vrinda.exp0.lstmf line 3027 :
Mean rms=0.438%, delta=0.467%, train=1.63%(5.604%), skip ratio=0%
Iteration 192456: GROUND  TRUTH : সাথে (94) আকাশ_পাগলা অর্থ অসাবধানতা নরম. মুক্তিযুদ্ধের উষ্ণ
Iteration 192456: ALIGNED TRUTH : সাথে (94) আকাশ_পাগলা অর্থ অসাবধানতা নরম. মুক্তিযুদ্ধের উষণ
Iteration 192456: BEST OCR TEXT : সাথে (94) আকাশ_পাগলা অর্থ অসাবধানতা নরম. মুক্তিযুদ্ধের উষ
File /tmp/ben-2021-03-15.kM8/ben.FreeSerif.exp0.lstmf line 1988 :
Mean rms=0.439%, delta=0.467%, train=1.633%(5.617%), skip ratio=0%
Iteration 192457: GROUND  TRUTH : দশকের দেখলো। খাওয়া গ্রাহকদের অডিও ভাই আগেই
File /tmp/ben-2021-03-15.kM8/ben.FreeSerif_Italic.exp0.lstmf line 614 (Perfect):
```
