### ISSUE TITLE
Compile time option NO_CUBE_BUILD disables some features which are not actually related to cube engine in file api/baseapi.cpp

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#74]
look for these functions:
 * ProcessPagesMultipageTiff(...)
 * ProcessPagesInternal(...)
 * TessBaseAPI::ProcessPage(...)

I think NO_CUBE_BUILD in these functions should be changed to SOMETING_ELSE, probably back to ANDROID_BUILD. 

Ray might not wants these features on Android, but I see no reason to disable them in a desktop/server environment.

**Comment by zdenop** [comment]
Thanks for testing.

**Comment by amitdo** [comment]
Thanks Zdenko (@zdenop) for this one, and thanks in general for your work on tesseract.
