### ISSUE TITLE
3000 page limit on OCRing mulitpage tiffs

### ISSUE THREAD

**Issue by bstace** [tesseract-ocr/tesseract#743]
Teseract 3.04 - Was trying to command line OCR a 9206 multi-page tiff document on Mac OS 10.11, but it stops at page 3000.  Turns out opencl/openclwrapper.cpp line 93 (static const l_int32 MAX_PAGES_IN_TIFF_FILE = 3000;) specifically limits OCRing Tiffs to 3000 pages.  This const appears to only control the bounds of a for loop, so maybe this variable should be more dynamic and be based on the number of pages the input Tiff has instead?  just a thought.

**Comment by jbreiden** [comment]
Weird. Let's get rid of that limit.

**Comment by jbreiden** [comment]
@dbloomberg

**Comment by DanBloomberg** [comment]
Sorry about that.  

Removed the 3000 page restriction on multipage tiff files.  There are now no limits, and this is pushed to the leptonica master: https://github.com/danbloomberg/leptonica

**Comment by jbreiden** [comment]
https://github.com/DanBloomberg/leptonica/commit/fd65f6b374f4e63ee55ff90a8524bee4a4381b18

Same change needed in opencl/openclwrapper.cpp (alternative: kill OpenCL/TIFF entirely)

**Comment by amitdo** [comment]
Only relevant to 3.05.

**Comment by bstace** [comment]
yeah, I might have a make my own custom build of 3.04.01 with the change to openclwrapper.cpp.

**Comment by jbreiden** [comment]
@bstace Are you getting any benefit from the OpenCL? Is it faster? How much faster?

**Comment by bstace** [comment]
@jbreiden I would think it's faster with it on, but haven't tested it.  Kinda new to tess - is there a way to easily turn it off to see?

**Comment by amitdo** [comment]
@zdenop, please close this issue.
