### ISSUE TITLE
How to split words by myself before recognize?

### ISSUE THREAD

**Issue by mobilesolution2016** [tesseract-ocr/tesseract#746]
The content as title, does a function in TessBaseAPI class like below:

api->setCharBoxes(RECT* pCharBoxes, int numOfBoxes);

Then tesseract recognize each character by boxes rect specialed only.

**Comment by amitdo** [comment]
The right place to ask this kind of question is [our forum](https://groups.google.com/d/forum/tesseract-ocr).

**Comment by amitdo** [comment]
@zdenop, please close this issue.
