### ISSUE TITLE
tesseract tag ignored WARNING LEAK

### ISSUE THREAD

**Issue by zshzj** [tesseract-ocr/tesseract#747]
the shell
`echo Run Tesseract for Training.. `
`tesseract.exe num.font.exp0.tif num.font.exp0 -l eng -psm 7 nobatch box.train `
`echo Compute the Character Set.. `
`unicharset_extractor.exe num.font.exp0.box `
`mftraining -F font_properties -U unicharset -O num.unicharset num.font.exp0.tr `
`echo Clustering.. `
`cntraining.exe num.font.exp0.tr `
`echo Rename Files.. `
`rename normproto num.normproto `
`rename inttemp num.inttemp `
`rename pffmtable num.pffmtable `
`rename shapetable num.shapetable  `
`echo Create Tessdata.. `
`combine_tessdata.exe num. `
`echo. & pause`

> The result, TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.WARNING! LEAK! object 032F8F80 still has count 1

`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>echo Run Tesseract for Training..
`Run Tesseract for Training..
`
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>tesseract.exe num.font.exp0.tif num.font.exp0 nobatch box.train
`Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`Page 1
`APPLY_BOXES:
`   Boxes read from boxfile:       6
`   Found 6 good blobs.
`Generated training data for 1 words
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`Page 2
`APPLY_BOXES:
`   Boxes read from boxfile:       6
`   Found 6 good blobs.
`Generated training data for 1 words
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`Page 3
`APPLY_BOXES:
`   Boxes read from boxfile:       6
`   Found 6 good blobs.
`Generated training data for 1 words
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`Page 4
`APPLY_BOXES:
`   Boxes read from boxfile:       6
`   Found 6 good blobs.
`Generated training data for 1 words
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`Page 5
`APPLY_BOXES:
`   Boxes read from boxfile:       6
`   Found 6 good blobs.
`Generated training data for 1 words
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`Page 6
`APPLY_BOXES:
`   Boxes read from boxfile:       6
`   Found 6 good blobs.
`Generated training data for 1 words
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.
`Page 7
`APPLY_BOXES:
`   Boxes read from boxfile:       6
`   Found 6 good blobs.
`Generated training data for 1 words
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.                                                                                                       `
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.                                                                                                       `
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.                                                                                                       `
`Page 8                                                                                                                                                                                `
`APPLY_BOXES:tesseract                                                                                                                                                                 `
`   Boxes read from boxfile:       6                                                                                                                                                   `
`   Found 6 good blobs.                                                                                                                                                                `
`Generated training data for 1 words                                                                                                                                                   `
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.                                                                                                       `
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.                                                                                                       `
`TIFFFetchNormalTag: Warning, Incompatible type for "RichTIFFIPTC"; tag ignored.                                                                                                       `
`Page 9                                                                                                                                                                                `
`Error during processing.                                                                                                                                                              `
`ObjectCache(56A00A88)::~ObjectCache(): WARNING! LEAK! object 032F8F80 still has count 1 (id \Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr\tessdata/eng.traineddatalstm-pu  `
`nc-dawg)                                                                                                                                                                              `
`ObjectCache(56A00A88)::~ObjectCache(): WARNING! LEAK! object 024CEA68 still has count 1 (id \Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr\tessdata/eng.traineddatalstm-wo  `
`rd-dawg)                                                                                                                                                                              `
`ObjectCache(56A00A88)::~ObjectCache(): WARNING! LEAK! object 024CE918 still has count 1 (id \Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr\tessdata/eng.traineddatalstm-nu  `
`mber-dawg)                                                                                                                                                                            `
`ObjectCache(56A00A88)::~ObjectCache(): WARNING! LEAK! object 027677F8 still has count 1 (id \Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr\tessdata/eng.traineddatapunc-da  `
`wg)                                                                                                                                                                                   `
`ObjectCache(56A00A88)::~ObjectCache(): WARNING! LEAK! object 033D7560 still has count 1 (id \Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr\tessdata/eng.traineddataword-da  `
`wg)                                                                                                                                                                                   `
`ObjectCache(56A00A88)::~ObjectCache(): WARNING! LEAK! object 024CEB18 still has count 1 (id \Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr\tessdata/eng.traineddatanumber-  `
`dawg)                                                                                                                                                                                 `
`ObjectCache(56A00A88)::~ObjectCache(): WARNING! LEAK! object 024CEB68 still has count 1 (id \Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr\tessdata/eng.traineddatabigram-  `
`dawg)                                                                                                                                                                                 `
`ObjectCache(56A00A88)::~ObjectCache(): WARNING! LEAK! object 024CE968 still has count 1 (id \Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr\tessdata/eng.traineddatafreq-da  `
`wg)                                                                                                                                                                                   `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>echo Compute the Character Set..                                                                                           `
`Compute the Character Set..                                                                                                                                                           `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>unicharset_extractor.exe num.font.exp0.box                                                                                 `
`Extracting unicharset from num.font.exp0.box                                                                                                                                          `
`Wrote unicharset file ./unicharset.                                                                                                                                                   `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>mftraining -F font_properties -U unicharset -O num.unicharset num.font.exp0.tr                                             `
`Warning: No shape table file present: shapetable                                                                                                                                      `
`Reading num.font.exp0.tr ...                                                                                                                                                          `
`                                                                                                                                                                                      `
`Error: Unable to open num.font.exp0.tr!                                                                                                                                               `
`"Fatal error encountered!" == NULL:Error:Assert failed:in file ../../../../ccutil/globaloc.cpp, line 75                                                                               `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>echo Clustering..                                                                                                          `
`Clustering..                                                                                                                                                                          `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>cntraining.exe num.font.exp0.tr                                                                                            `
`Reading num.font.exp0.tr ...                                                                                                                                                          `
`                                                                                                                                                                                      `
`Error: Unable to open num.font.exp0.tr!                                                                                                                                               `
`"Fatal error encountered!" == NULL:Error:Assert failed:in file ../../../../ccutil/globaloc.cpp, line 75                                                                               `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>echo Rename Files..                                                                                                        `
`Rename Files..                                                                                                                                                                        `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>rename normproto num.normproto                                                                                             `
`not found file。                                                                                                                                                                      `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>rename inttemp num.inttemp                                                                                                 `
`not found file。                                                                                                                                                                      `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>rename pffmtable num.pffmtable                                                                                             `
`not found file。                                                                                                                                                                      `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>rename shapetable num.shapetable                                                                                           `
`not found file。                                                                                                                                                                      `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>echo Create Tessdata..                                                                                                     `
`Create Tessdata..                                                                                                                                                                     `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>combine_tessdata.exe num.                                                                                                  `
`Combining tessdata files                                                                                                                                                              `
`Error: traineddata file must contain at least (a unicharset fileand inttemp) OR an lstm file.                                                                                         `
`Error combining tessdata files into num.traineddata                                                                                                                                   `
`                                                                                                                                                                                      `
`C:\Users\qyw\Downloads\jTessBoxEditor-master\tesseract-ocr>echo.   & pause                                                                                                            `

**Comment by Shreeshrii** [comment]
Please provide the o/s, version of tesseract and leptonica and other relevant details.

Please attach num.font.exp0.tif for testing.

**Comment by zshzj** [comment]
@Shreeshrii 
OS:Microsoft Windows 7  6.1.7601 Service Pack 1 Build 7601
tesseract version:
`tesseract.exe --version`
`tesseract 4.00.00alpha`
`leptonica-1.74.1`
  `libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.5.0) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libo
penjp2 2.1.0`
tif [file](https://github.com/zshzj/tesseract_demo)

**Comment by Shreeshrii** [comment]
@zshzj Thanks for the tif file.

I was able to OCR the file, and the OCRed text was produced, even though the warning was given. See attached file.

[num.font.exp0.txt](https://github.com/tesseract-ocr/tesseract/files/824312/num.font.exp0.txt)

`WARNING! LEAK! object` errors come when some file is not found during processing.

`tesseract.exe num.font.exp0.tif num.font.exp0 -l eng -psm 7 nobatch box.train`

expects you to provide both the .tif file and it's corresponding box file.

You can create it using the following command and then have to edit it to match the tif.

`tesseract.exe num.font.exp0.tif num.font.exp0 -l eng makebox' 

You can use jtessboxeditor to edit the box file. If you want to train for 4.0 - LSTM, then use the `Mark EOL` function to add a tab character to end of line.

Box file is attached, renamed with .txt extension for uploading.

[num.font.exp0.box.txt](https://github.com/tesseract-ocr/tesseract/files/824326/num.font.exp0.box.txt)


The file is at 72 dpi, you will get better results in recognition if it is at 300dpi. The warning is because the tif format might be non-standard. Try to convert before processing.

**Comment by zshzj** [comment]
@Shreeshrii Thanks for your advice
this is my box file 
[num.font.exp0.box.txt](https://github.com/tesseract-ocr/tesseract/files/824371/num.font.exp0.box.txt)

i think this command has a problem,It does not generate a **_num.font.exp0.tr_** file

> mftraining -F font_properties -U unicharset -O num.unicharset num.font.exp0.tr

> Error: Unable to open num.font.exp0.tr!

**Comment by zshzj** [comment]
@Shreeshrii 
How to solve this error

**Comment by Shreeshrii** [comment]
No idea on how to fix it.

Mftraining has had unresolved problems earlier also.

You can try debug to see if u get more info.

 Or, Split your 200 page tif into smaller pieces to see if it makes a
difference.

- excuse the brevity, sent from mobile

**Comment by Shreeshrii** [comment]
Your box file is missing for page 9 -

b 32 10 52 40 7
x 54 10 70 30 7
a 78 10 91 30 7
e 98 10 112 30 7
b 116 10 130 40 7
h 138 10 160 40 7
t 32 10 43 36 9
u 43 10 61 36 9
s 68 10 80 30 9
t 80 10 82 30 9
x 95 10 110 36 9
p 118 0 138 30 9

ie. last column should be 8. That's the page you are getting the error.

**Comment by Shreeshrii** [comment]
Also missing page 59, etc. Please use jtessboxeditor, check each page, make sure boxes are correctly mapping the letters etc. before training.

**Comment by zshzj** [comment]
@Shreeshrii  Thinks 
I reduced the tif file to 20, It was successful
