### ISSUE TITLE
error about openmp

### ISSUE THREAD

**Issue by yhl41001** [tesseract-ocr/tesseract#748]
my computer does not install openmp, i configure with --disable-openmp, but i still could not compile with error:
./.libs/libtesseract.so: undefined reference to `omp_get_thread_num'
./.libs/libtesseract.so: undefined reference to `GOMP_sections_end_nowait'
./.libs/libtesseract.so: undefined reference to `omp_get_num_threads'
./.libs/libtesseract.so: undefined reference to `GOMP_parallel'
./.libs/libtesseract.so: undefined reference to `GOMP_parallel_sections'
./.libs/libtesseract.so: undefined reference to `GOMP_sections_next'
so, if have some bugs about the configure!

**Comment by zdenop** [comment]
which tesseract version (revision) you use?

**Comment by yhl41001** [comment]
I use 4.0 version, and i set the _OPENMP undef manually, then it could compile.

**Comment by zdenop** [comment]
Please submit config.log and output of this commnad (onfigure.log):
`./configure --prefix=/usr 2>& | tee configure.log`

**Comment by amitdo** [comment]
@yhl41001, do you still have this issue?

If you do, please response to zdenop.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
