### ISSUE TITLE
Compile to EMScripten/asm.js

### ISSUE THREAD

**Issue by brettz9** [tesseract-ocr/tesseract#75]
For those of us who know nothing of C, might someone be kind enough to use EMScripten/asm.js to compile to JavaScript on our behalf for use in the browser (without Node.js, etc.)?  Would no doubt be quite slow but would be handy for some web apps...  The other existing ports (Ocrad and GOCR) do not seem to hold a candle to the quality of Tesseract. Thanks!

**Comment by brettz9** [comment]
A particularly compelling use case beyond regular web apps would be as a browser add-on for running OCR against images encountered on the web and placing the OCR'd results in a dialog, in-place on the web page, etc..

In my Firefox add-on for [decoding QR codes](https://github.com/brettz9/qr-secret-decoder-ring/), I already have infrastructure in place which could largely be reused to allow OCR against images found while browsing the web, whether as a regular image, as a frame in a video, as a background image, SVG element, canvas, or, probably PDF too, given that ImageMagick has [already been ported](http://manuels.github.io/unix-toolbox.js/).

**Comment by jimregan** [comment]
In short: there's too much involved, so don't hold your breath.

**Comment by brettz9** [comment]
Ok, thanks for the reply!

**Comment by amitdo** [comment]
@brettz9, It seems that someone is working on this: 
https://github.com/naptha

**Comment by brettz9** [comment]
Will look into it...Thanks!
