### ISSUE TITLE
Community Contributions - MRZ Traineddata

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#753]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/t7GdSDRrGpI/gMzJEcfXEAAJ

https://groups.google.com/group/tesseract-ocr/attach/10d7c711c9cc80/mrz.traineddata?part=0.1&authuser=0

> Just created a tesseract 3.04 trained data (see attached). 
I call it "MRZ" because it has the OCR-B as the only font and trained with characters A-Z, 0-9 and the lesser-than symbol (<). Seems to be fast and accurate in my projects.

**Comment by Shreeshrii** [comment]
Is there a list where community contributions for traineddata are listed?

This should be tested and added.

**Comment by stweil** [comment]
Maybe add them to https://github.com/tesseract-ocr/tesseract/wiki/Data-Files?

**Comment by amitdo** [comment]
Is that you want?
https://github.com/tesseract-ocr/tesseract/wiki/AddOns#community-training-projects

**Comment by Shreeshrii** [comment]
Thanks. Added to community Training Projects.

**Comment by JeromeDesseaux** [comment]
First of all, thanks for sharing your training files :)

Not working for me : got a TesseractError: (-11, 'index >= 0 && index < size_used_:Error:Assert failed:in file ../ccutil/genericvector.h, line 589')

Using Pytesseract wrapper in Python 3 and Tesseract v3.03

Any help would be appreciated :)

**Comment by stweil** [comment]
Tesseract v3.03 is a really old version and no longer supported as far as I know. What about using v3.05 (or even the latest experimental version from GitHub)?

**Comment by JeromeDesseaux** [comment]
Same error using version 3.05 and leptonica 1.74.4.

**Comment by Shreeshrii** [comment]
see the discussion in the forum thread at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/t7GdSDRrGpI/gMzJEcfXEAAJ and try the ocr-b traineddata posted there.

**Comment by JeromeDesseaux** [comment]
I found it elsewhere on an open-repo here, on GitHub. But anyway, thanks; Its working :)

**Comment by Shreeshrii** [comment]
Please post the working link here for future users who have the same question. Thanks!

**Comment by JeromeDesseaux** [comment]
here it is : https://github.com/Exteris/tesseract-mrz/blob/master/lang/OCRB.traineddata.gz?raw=true

**Comment by stweil** [comment]
The corresponding GitHub project is [Exteris/tesseract-mrz/](https://github.com/Exteris/tesseract-mrz/).

**Comment by vuks87** [comment]
Is ocrb.traineddata available for tesseract 4 legacy engine mode?
