### ISSUE TITLE
Multiple I/O on disk for creating LSTM training dataset

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#754]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/OJI3bsi_JMY/NHlt8uEfEAAJ

>I'm new to tesseract and wondered why the lstm dataset creation for the training process has to write the file again and again in TrainLineRecognizer. I've seen 200MB/s IO on the disk while creating the training data set. As far I can see for the training case it would be sufficient to just load it once and write it at the end. The same applies to the box and tif file - but these are only read and not written...

**Comment by stweil** [comment]
LSTM training takes a lot of time and has no well defined duration. Therefore saving intermediate results (with a configurable frequency) is a good thing. It allows tests based on those intermediate results, and those results can also be used to resume the learning process if it was interrupted for whatever reason.

**Comment by Shreeshrii** [comment]
Thanks @stweil .
