### ISSUE TITLE
Not able to read numbers?

### ISSUE THREAD

**Issue by Omnipresent** [tesseract-ocr/tesseract#759]
I'm trying to process the following image using tesseract 3.04
<img width="157" alt="number" src="https://cloud.githubusercontent.com/assets/115446/23871059/3ae3fb32-07ff-11e7-8d02-f1c33e7a8d10.png">

The image seems pretty clean. however, it extracts the following from this image using the `eng` lang

> .ESHBEE

**Questions**
1. Is there a way to read numbers like these from tesseract? 
2. If I have to train a separate lang for these type of numbers, can the trained lang be integrated into the `eng` lang?

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support. Make sure you read relevant wiki first.
