### ISSUE TITLE
OpenMP support

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#76]
In ccmain/par_control.cpp you can see this code:

#pragma omp parallel for num_threads(10)
for (int b = 0; b < blobs.size(); ++b) {
...
}

configure.ac should have an option to activate OpenMP in tesseract code (maybe with AC_OpenMP?).

**Comment by zdenop** [comment]
committed but it seems that this is only occurrence of OpenMP support...

**Comment by ryanfb** [comment]
Hi, when I try to compile on a Mac with this commit in (for testing #71), I now get the following error:
```
configure: error: conditional "OPENMP" was never defined.
Usually this means the macro was only invoked conditionally.
```

**Comment by zdenop** [comment]
Did you run ./autogen.sh after git pull? Was it without error? Can you provide config.log?

**Comment by ryanfb** [comment]
Here's a `config.log` for the current `master` branch after `./autogen.sh` && `./configure`: https://gist.github.com/c134a55446c99b9702fe

Same process succeeds if I revert bb19f2c.

**Comment by ryanfb** [comment]
I think this *may* be related to this problem/answer: http://stackoverflow.com/a/32122781
As I believe the conftest should find `<omp.h>` when given `-fopenmp`. I'm currently letting the gcc reinstall run, and will report back after.

But also the configure process probably shouldn't fail by default if there's no OpenMP support detected/enabled.

**Comment by ryanfb** [comment]
Confirmed that after `brew reinstall gcc --without-multilib`, I can use e.g. `brew install --HEAD --cc=gcc-5 tesseract` and the configure/make will succeed with bb19f2c in. Without `--cc=gcc-5` it fails due to [the lack of OpenMP support in the current Clang/LLVM compiler shipped with OS X](http://clang-omp.github.io/) (i.e. the default Mac "`gcc`").

**Comment by zdenop** [comment]
Thanks for testing and report. Should be fixed in f331a57b8e4d1b38980c71f576ec5ffe6ba7cf9e.

**Comment by amitdo** [comment]
@ryanfb, @zdenop
FYI, Clang 3.7 now support OpenMP.

>
OpenMP 3.1 is fully supported, but disabled by default. To enable it, please use the -fopenmp=libomp command line option.

http://llvm.org/releases/3.7.0/tools/clang/docs/ReleaseNotes.html#openmp-support

**Comment by zdenop** [comment]
Patches are welcommed ;) Anyway tesseract can use OpenMP only in one place....
