### ISSUE TITLE
Assertion in stringrenderer when running text2image

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#765]
While running the training for `frk` with a longer training text, I get [assertions in stringrenderer.cpp](https://github.com/tesseract-ocr/tesseract/blob/master/training/stringrenderer.cpp#L553) for 5 of 12 fonts. They can be reproduced by running `text2image` for that text with a single language:

    $ text2image --fonts_dir=/usr/share/fonts --font="Proclamate Light, Light" --text=../langdata/frk/frk.training_text --outputbase=/tmp/frk
    Stripped 157 unrenderable words
    Rendered page 0 to file /tmp/frk.tif
    # ...
    Rendered page 1163 to file /tmp/frk.tif
    Stripped 57 unrenderable words
    cluster_text.size() == start_byte_to_box.size():Error:Assert failed:in file ../training/stringrenderer.cpp, line 553

**Comment by Shreeshrii** [comment]
@stweil I think you mean `fonts' instead of `languages` in the above.

**Comment by stweil** [comment]
Yes, thanks. I fixed it in my original post.

**Comment by zdenop** [comment]
duplicate to #1781. Closing this because there are more information.
