### ISSUE TITLE
tesseract 3.05 can not use opencl

### ISSUE THREAD

**Issue by blacklong617** [tesseract-ocr/tesseract#767]
I want use opencl to speed up tesseract. I define USE_OPENCL in C/C++->Preprocessor->Preprocessor Definitions(VS2015) .
and include"CL/cl.h" in openclwrapper.h.
And rebuild the libtesseract  project , and succeeded.
When I use GetUTF8Text, the  String return is NULL but return correct string when I don't use opencl.
Can you tell me ,where is the problem?
Can Opencl use in teseeract 3.05?
Thanks!

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support/questions.

**Comment by blacklong617** [comment]
Hi , zdenop ,
   Can you help me at there. I can't use the tesseract user forum because I don't have a Google account .I am very sorry for that.
Thanks!
