### ISSUE TITLE
Box files created by tesseract using makebox not compatible with 4.0 LSTM training

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#768]
LSTM training requires box files which have a TAB at end of line and spaces to demarcate words.

Box files generated by tesseract from image files do not have these. 

The synthetic box/tiff pairs generated by text2image have the spaces and tabs.

**Comment by Shreeshrii** [comment]
Related/Duplicate https://github.com/tesseract-ocr/tesseract/issues/832

**Comment by Shreeshrii** [comment]
Box files created by tesseract 4.00.00alpha master branch with `makebox` option cannot be used for LSTM training, as they do not have:

* Tab character to mark end of line
* Space between words

**Comment by Shreeshrii** [comment]
Also, `makebox` option creates box files with different box sizes and locations on the same image depending on the OEM mode.

[Uploading boxfiletest-0.box.txt…]()
![boxfiletest](https://user-images.githubusercontent.com/5095331/27507096-ccec61e0-58e5-11e7-9686-281955978db6.png)
[Uploading boxfiletest-1.box.txt…]()

**Comment by Shreeshrii** [comment]
Testing with current code, after new unicharset_extractor, there are additional problems in box files for complex scripts such as Devanagari.

The synthetic tif/box files created by `text2image` create one box for each aksara (conjunct-cluster+combining mark). These are broken into components by the unicharcompressor/recoder.

```
जु 110 4633 154 4679 0
ला 147 4645 205 4679 0
ई 198 4640 235 4694 0
- 233 4656 245 4660 0
से 244 4645 288 4692 0
प्टे 281 4645 318 4692 0
म् 311 4655 341 4678 0
ब 330 4645 366 4678 0
र 357 4645 389 4678 0
  389 4644 406 4691 0
```

However, the box files created by `tesseract` using the `makebox` config file, split the components and create a box for each. This happens both with Devanagari and hin traineddatas from tessdata_best.

```
ज 107 4632 124 4695 0
ु 124 4632 150 4695 0
ल 150 4632 168 4695 0
ा 168 4632 187 4695 0
ई 187 4632 213 4695 0
- 233 4656 241 4661 0
स 241 4656 246 4661 0
े 255 4644 274 4693 0
ष 274 4644 286 4693 0
् 286 4644 297 4693 0
ट 297 4644 309 4693 0
े 309 4644 318 4693 0
म 318 4644 328 4693 0
् 328 4644 344 4693 0
ब 344 4644 358 4693 0
र 358 4644 388 4693 0
```
However, the older 4.0alpha hin.traineddata in tessdata repo has the akharas.

```
जु 107 4632 166 4695 0
ला 166 4632 190 4695 0
ई 190 4632 213 4695 0
- 213 4632 234 4695 0
से 239 4656 246 4661 0
प् 274 4644 297 4693 0
टे 297 4644 323 4693 0
म् 323 4644 344 4693 0
ब 344 4644 358 4693 0
र 358 4644 382 4693 0
```

**Comment by Shreeshrii** [comment]
The `tesseract` `makebox` created box files for Devanagari script get the following errors related to normalization regarding combiner marks:

```
=== Phase UP: Generating unicharset and unichar properties files ===
[Mon Oct 16 17:35:49 DST 2017] /usr/local/bin/unicharset_extractor --output_unicharset /tmp/tmp.fN2Jr9NHXJ/bih/bih.unicharset --norm_mode 2 /tmp/tmp.fN2Jr9NHXJ/bih/bih.m
akebox.exp0.box /tmp/tmp.fN2Jr9NHXJ/bih/bih.Siddhanta.exp0.box
Extracting unicharset from box file /tmp/tmp.fN2Jr9NHXJ/bih/bih.makebox.exp0.box
Word started with a combiner:0x941
Normalization failed for string 'ु'
Word started with a combiner:0x93e
Normalization failed for string 'ा'
Word started with a combiner:0x947
Normalization failed for string 'े'
Word started with a combiner:0x94d
Normalization failed for string '्'
Word started with a combiner:0x947
Normalization failed for string 'े'
Word started with a combiner:0x94d
Normalization failed for string '्'
Word started with a combiner:0x94d
Normalization failed for string '्'
Word started with a combiner:0x94b
Normalization failed for string 'ो'
Word started with a combiner:0x93f
Normalization failed for string 'ि'
Word started with a combiner:0x94d
Normalization failed for string '्'
Word started with a combiner:0x94d
Normalization failed for string '्'
Word started with a combiner:0x94d
Normalization failed for string '्'
Word started with a combiner:0x93f
Normalization failed for string 'ि'
Word started with a combiner:0x941
Normalization failed for string 'ु'
Word started with a combiner:0x94d
Normalization failed for string '्'
Word started with a combiner:0x94d
Normalization failed for string '्'
```

So, some change needs to be made where the box file is being written that it combines the consonant clusters and combining marks and then creates the boxes.

Possibly this will also happen for other complex scripts.

**Comment by idrisalshikh** [comment]
I get the same message with Arabic language as shown below

idris@ubuntu:~/tesseract-ocr$ training/lstmtraining --model_output ~/mylottutorial/plusminus/ \
> --continue_from  ~/mylottutorial/ara.lstm \
> --train_listfile ~/mylottutorial/ara.training_files.txt \
> --traineddata    ./tessdata/ara.traineddata \
> --old_traineddata ./tessdata/ara.traineddata \
> --max_iterations 1000

Loaded file /home/idris/mylottutorial/ara.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 307 to 307!
Num (Extended) outputs,weights in Series:
  1,48,0,1:1, 0
Num (Extended) outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys64:64, 20736
  Lfx96:96, 61824
  Lrx96:96, 74112
  Lfx384:384, 738816
  Fc307:307, 118195
Total weights = 1013843
Previous null char=2 mapped to 2
Continuing from /home/idris/mylottutorial/ara.lstm
Loaded 104/104 pages (1-104) of document /home/idris/mylottutorial/ara.mylotus_Bold.exp0.lstmf
^C
idris@ubuntu:~/tesseract-ocr$ clear

idris@ubuntu:~/tesseract-ocr$ training/tesstrain.sh \
> --fonts_dir /home/idris/mylot \
> --lang ara --linedata_only \
> --noextract_font_properties --langdata_dir ./langdata \
> --tessdata_dir ./tessdata \
> --output_dir ~/mylottutorial \
> --fontlist "mylotus Bold"

=== Starting training for language 'ara'
[Mon Nov 13 01:52:41 PST 2017] /usr/local/bin/text2image --fonts_dir=/home/idris/mylot --font=mylotus Bold --outputbase=/tmp/font_tmp.Rf99kiznKj/sample_text.txt --text=/tmp/font_tmp.Rf99kiznKj/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.Rf99kiznKj
Stripped 1 unrenderable words
Rendered page 0 to file /tmp/font_tmp.Rf99kiznKj/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using mylotus Bold

[Mon Nov 13 01:52:42 PST 2017] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.Rf99kiznKj --fonts_dir=/home/idris/mylot --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.s7NZRqv0Qa/ara/ara.mylotus_Bold.exp0 --max_pages=3 --font=mylotus Bold --text=./langdata/ara/ara.training_text
Stripped 2 unrenderable words
Rendered page 0 to file /tmp/tmp.s7NZRqv0Qa/ara/ara.mylotus_Bold.exp0.tif
Rendered page 1 to file /tmp/tmp.s7NZRqv0Qa/ara/ara.mylotus_Bold.exp0.tif
Stripped 10 unrenderable words
Rendered page 2 to file /tmp/tmp.s7NZRqv0Qa/ara/ara.mylotus_Bold.exp0.tif

=== Phase UP: Generating unicharset and unichar properties files ===
[Mon Nov 13 01:52:44 PST 2017] /usr/local/bin/unicharset_extractor --output_unicharset /tmp/tmp.s7NZRqv0Qa/ara/ara.unicharset --norm_mode 2 /tmp/tmp.s7NZRqv0Qa/ara/ara.mylotus_Bold.exp0.box
Extracting unicharset from box file /tmp/tmp.s7NZRqv0Qa/ara/ara.mylotus_Bold.exp0.box
Word started with a combiner:0x64b
Normalization failed for string ' ً'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64f
Normalization failed for string 'ُت'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًام'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64f
Normalization failed for string 'ُأ'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x650
Word started with a combiner:0x651
Normalization failed for string 'ِّر'
Word started with a combiner:0x64f
Normalization failed for string 'ُي'
Word started with a combiner:0x64f
Word started with a combiner:0x651
Normalization failed for string 'ُّل'
Word started with a combiner:0x650
Normalization failed for string 'ِحل'
Word started with a combiner:0x64f
Normalization failed for string 'ُه'
Word started with a combiner:0x64e
Word started with a combiner:0x651
Normalization failed for string 'َّط'
Word started with a combiner:0x650
Word started with a combiner:0x651
Normalization failed for string 'ِّف'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Word started with a combiner:0x64b
Normalization failed for string 'ًام'
Word started with a combiner:0x64b
Normalization failed for string 'ًى'

**Comment by Shreeshrii** [comment]
Getting error with text2image generated files for language kur_ara, with beta.1

```

=== Phase UP: Generating unicharset and unichar properties files ===
[Sat Mar 31 11:43:07 DST 2018] /usr/local/bin/unicharset_extractor --output_unicharset /tmp/tmp.XimA98vj8L/kur_ara/kur_ara
.unicharset --norm_mode 3 /tmp/tmp.XimA98vj8L/kur_ara/kur_ara.Amiri.exp0.box /tmp/tmp.XimA98vj8L/kur_ara/kur_ara.Arial_Uni
code_MS.exp0.box /tmp/tmp.XimA98vj8L/kur_ara/kur_ara.Scheherazade.exp0.box /tmp/tmp.XimA98vj8L/kur_ara/kur_ara.Tahoma.exp0
.box /tmp/tmp.XimA98vj8L/kur_ara/kur_ara.Times_New_Roman.exp0.box
Extracting unicharset from box file /tmp/tmp.XimA98vj8L/kur_ara/kur_ara.Amiri.exp0.box
Word started with a combiner:0x64e
Normalization failed for string 'َا'
Word started with a combiner:0x650
Normalization failed for string 'ِر'
Word started with a combiner:0x64e
Normalization failed for string 'َا'
Word started with a combiner:0x64e
Normalization failed for string 'َا'
Word started with a combiner:0x64e

```

**Comment by amitdo** [comment]
@Shreeshrii, please close this issue.

**Comment by Shreeshrii** [comment]
Thanks!
