### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by mote166** [tesseract-ocr/tesseract#769]
idk how to reproduce this or the cause. :

Warning: assert(): Movement distance is excessive: dx=0, dy=-30.3788, dz=0 failed in phar:///jar/versions/Tesseract/tesseract104.phar/src/pocketmine/entity/Entity.php on line 1478

**Comment by mote166** [comment]
also theres no game sounds (moving,jumping.. etc)

**Comment by Shreeshrii** [comment]
This list is for Tesseract OCR. Not the game.

- excuse the brevity, sent from mobile
