### ISSUE TITLE
Update from 3.04 to 3.05

### ISSUE THREAD

**Issue by clarkk** [tesseract-ocr/tesseract#773]
After installing `3.05` I still get `3.04` when running `pkg-config --modversion tesseract`

How I installed `3.05`

```
cd /var/bin && wget http://www.leptonica.com/source/leptonica-1.74.1.tar.gz && tar -xvf leptonica-1.74.1.tar.gz
cd leptonica-1.74.1 && ./configure && make && make install

cd /var/bin && wget https://github.com/tesseract-ocr/tesseract/archive/3.05.00.tar.gz -O tesseract-3.05.00.tar.gz && tar -xvf tesseract-3.05.00.tar.gz
cd tesseract-3.05.00 && ./autogen.sh && ./configure && make && make install && ldconfig
```

When compiling my program that uses tesseract its also still using `3.04`

```
g++ -std=c++11 txtocr.cpp -o txtocr -llept -ltesseract
```

**Comment by stweil** [comment]
So you have installed both 3.04 (maybe from your Linux distribution) and 3.05 (built in the steps above). Do you need both, or can you remove 3.04?

**Comment by clarkk** [comment]
I will uninstall everything and try to clone master
