### ISSUE TITLE
Configure raising syntax error, with autoconf-archive

### ISSUE THREAD

**Issue by Jenkyrados** [tesseract-ocr/tesseract#777]
Getting the famous : 

```
./configure: line 4250: syntax error near unexpected token `-mavx,'
./configure: line 4250: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'

```
However, actually read the doc and googled around, and i do have the autoconf-archive package installed ><

**Comment by stweil** [comment]
Did you run `./autogen.sh` _after_ the installation of `autoconf-archive`?

**Comment by Jenkyrados** [comment]
That was it. Thanks!

**Comment by amitdo** [comment]
>However .... i do have the autoconf-archive package installed

Are you sure?

If you OS is Ubuntu/Debian you can run this command:
`dpkg -s autoconf-archive | grep Status`

Try to re-run `./autogen.sh` and then `./configure`.

**Comment by mcheung63** [comment]
still has error:

/Users/peter/Downloads/tesseract>./configure --prefix=/Users/peter/Downloads/tesseract-install
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
Using git revision: 4.00.00dev-625-g9c2fa0d1
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of g++... gcc3
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-apple-darwin16.7.0
checking host system type... x86_64-apple-darwin16.7.0
./configure: line 4238: syntax error near unexpected token `-mavx,'
./configure: line 4238: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'

**Comment by stweil** [comment]
Did you run ./autogen.sh after the installation of autoconf-archive? (see also comment above)

**Comment by mcheung63** [comment]
where i can find/install/download autoconf-archive? thanks

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/Compiling#macos

**Comment by amitm02** [comment]
for the life of god I can't manage to install or compile "autoconf-archive" on Amazon Linux AMI (it has yum, not apt-get).
Can anyone point me to instruction about how to install it?

**Comment by amitdo** [comment]
https://aws.amazon.com/amazon-linux-ami/faqs/

>Q: How do I enable the Extra Packages for Enterprise Linux (EPEL) repository?

Read the answer.

**Comment by amitm02** [comment]
thanks @amitdo, but no luck:

> [ec2-user@ip-172-31-31-253 ~]$ sudo yum install autoconf-archive --enablerepo=epel
> Loaded plugins: priorities, update-motd, upgrade-helper
> 1039 packages excluded due to repository priority protections
> No package autoconf-archive available.
> Error: Nothing to do

**Comment by bweigel** [comment]
@amitdo @amitm02 I had the same problem. I could not install autoconf-archive via yum, even after enabling the epel-repo. I resorted to compiling autoconf-archive myself, which allowed me to compile tesseract on a current Amazon Linux AMI. Following are the steps:

1. Download autoconf-archive source & compile (http://babyname.tips/mirrors/gnu/autoconf-archive/?C=M;O=D)
```
cd /tmp
wget http://babyname.tips/mirrors/gnu/autoconf-archive/autoconf-archive-2017.09.28.tar.xz
tar xf autoconf-archive-2017.09.28.tar.xz 
cd autoconf-archive-2017.09.28
./configure && make && make install 

# copy the generated macros to /usr/share/aclocal/, such that autogen.sh can find them
cp ./m4/* /usr/share/aclocal/
```
2. Download and install tesseract (given you already have leptonica)
```
cd /tmp
git clone https://github.com/tesseract-ocr/tesseract.git
cd tesseract
./autogen.sh
PKG_CONFIG_PATH=... LIBLEPT_HEADERSDIR=...  \
    ./configure --prefix=... --with-extra-includes=... --with-extra-libraries=... 
make && make install
```

Hope this helps.

**Comment by amitdo** [comment]
>Download autoconf-archive source & compile (http://babyname.tips/mirrors/gnu/autoconf-archive/?C=M;O=D)

Use the official site instead of a site for baby names...
https://www.gnu.org/software/autoconf-archive/Downloads.html

**Comment by amitdo** [comment]
It turned out that babyname.tips is listed as mirror in gnu.org 
https://www.gnu.org/prep/ftp
😆

**Comment by BudiKusasi** [comment]
How do we install autoconf-archive on Msys2+minGW ? ..would any one explain it to me clearly in detail ?
