### ISSUE TITLE
[C-API] TessBaseAPIRecognize() segfaults when no language data files is available

### ISSUE THREAD

**Issue by jflesch** [tesseract-ocr/tesseract#779]
Hello,

When working on https://github.com/jflesch/pyocr/issues/51 , someone reported to me the following issue:

When no language data file is available at all (not even English), TessBaseAPIRecognize() segfaults.
Also happens when TESSDATA_PREFIX is set to an invalid directory.

Tested with libtesseract 3.04.01 (Debian Sid).

Example code:
```C
#include <stdio.h>
#include <stdlib.h>

#include <leptonica/allheaders.h>

#include <tesseract/capi.h>

/*
 * gcc -Wall -Werror -g -ggdb -ltesseract -llept test.c -o test.out
 * ./test.out ~/git/pyocr/tests/input/real/basic_doc.jpg
 */

int main(int argc, char **argv)
{
	TessBaseAPI *handle;
	PIX *image;

	setenv("TESSDATA_PREFIX", "/opt/tulipe", 1 /* overwrite */);

	handle = TessBaseAPICreate();
	TessBaseAPIInit3(handle, NULL, "fra");
	TessBaseAPISetVariable(handle, "tessedit_zero_rejection", "F");
	image = pixRead(argv[1]);
	TessBaseAPISetImage2(handle, image);

	TessBaseAPIRecognize(handle, NULL);

	TessBaseAPIDelete(handle);

	return 0;
}
```

Stacktrace:
```
(gdb) bt
#0  0x00007ffff76f2597 in tesseract::Tesseract::recog_all_words(PAGE_RES*, ETEXT_DESC*, TBOX const*, char const*, int) () from /usr/lib/x86_64-linux-gnu/libtesseract.so.3
#1  0x00007ffff76dcb7f in tesseract::TessBaseAPI::Recognize(ETEXT_DESC*) ()
   from /usr/lib/x86_64-linux-gnu/libtesseract.so.3
#2  0x0000555555554aa2 in main (argc=2, argv=0x7fffffffe3d8) at test.c:27
```

PS: This is a very low-priority issue for me. I can work around it really easily on Python side.

**Comment by zdenop** [comment]
@jflesch : Problem is that you are not using[ c-api as designed](https://github.com/tesseract-ocr/tesseract/wiki/APIExample#example-using-the-c-api-in-a-c-program) ;-) : you forget to check return value. So instead of 
```
TessBaseAPIInit3(handle, NULL, "fra");`
```
you use something like this:
```
if(TessBaseAPIInit3(handle, NULL, "eng") != 0)
		die("Error initializing tesseract\n");
```

**Comment by jflesch** [comment]
Oops :-)
Thanks for the reply, and sorry for wasting your time. I'll make sure I didn't miss any other return values in Pyocr.

**Comment by zdenop** [comment]
no problem. With testing you issue thanks for test case) I found and fix another problem ;-)

BTW: maybe it would be good if you join your effort with @jbarlow83 : he is [wrapping leptonica in python](https://github.com/jbarlow83/OCRmyPDF/blob/master/src/ocrmypdf/leptonica.py) in his project [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF). leptonica provides several great function for ocr preprocesing like descew and dewarp removing background)

**Comment by jflesch** [comment]
Interesting. I did write my own [image manipulation library](https://gitlab.gnome.org/World/OpenPaperwork/libpillowfight) based on unpaper's algorithms (the idea at the time was mainly to reduce dependency on stuff like OpenCV as much as possible because they made installing [my project](https://gitlab.gnome.org/World/OpenPaperwork/libpillowfight) a lot more complicated). But unskewing is the only algo I haven't re-implemented yet. I'll have a look later at what leptonic and OCRmyPDF provide exactly.

**Comment by zdenop** [comment]
I spoke with some developer (not python) and he was quite surprised why tesseract users are using/looking for other libraries for OCR image preprocessing if all really needed is in leptonica ;-)
Maybe easy to use python wrapper could help to promote it.
@jbarlow83 make a good job in this area, but to have leptonica as separate python module could help gain more attention...

**Comment by jflesch** [comment]
Actually, to be honest, in [Paperwork](https://gitlab.gnome.org/World/OpenPaperwork/paperwork), I don't really worry much about accuracy. OCR is used for indexing documents only. Fuzzy-searching takes care of non-entirely-accurate OCR results. So at the moment I don't even bother pre-processing images at all before passing them to Tesseract.
The image manipulations I do are to fix [user perception of the document](https://gitlab.gnome.org/World/OpenPaperwork/libpillowfight#automatic-color-equalization-ace) or try to simplify their content before exporting to make the files smaller (Unpaper's algorithms / SWT).

But I'm wondering: Is there an official recommendation for set of pre-processing algorithms to apply before passing an image to Tesseract ? Are some algorithms that would make documents match more closely what was used for training Tesseract for instance ? (grayscale ? pure b&w ? unskewing ? etc)

**Comment by amitdo** [comment]
It depends on which ocr engine in 4.0.0 you want to use (lstm/legacy).

**Comment by zdenop** [comment]
Some recommendations is on [ImproveQuality](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality) - not sure how many of them are must for 4.0.

Deskew, dewarp, noise removing and crop should also applicable general also for your project.
Passing only text region (or graphics removing including lines), maybe trying other binarization method (tesseract use Otsu) could improve result too.

**Comment by jflesch** [comment]
Thanks :)
