### ISSUE TITLE
--version: git version number is not upated, when only doing "git pull; make; sudo make install"

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#78]
I have a working repo and installation of tesseract. When I pull the latest version from git, make and install, the git version information when printed via ```tesseract --version``` is not updated.

Reporting this as a bug, but not being sure, whether this is the correct term. Please close the issue if you think that my report is wrong, because one may not use the short sequence (pull - make - install).

I simply do not know, whether the following short sequence was ever designed to work.

How to reproduce the bug:

```
git pull
make
sudo make install
```

The following sequence however works, but recompiles everything:
```
make distclean
git pull
./autogen.sh
make
sudo make install
```

**Comment by zdenop** [comment]
This is not bug ;-). I you install from git repository, you should follow instruction - https://github.com/tesseract-ocr/tesseract/blob/master/INSTALL.GIT#L16

**Comment by Wikinaut** [comment]
@zdenop I thought that *updating* (via git pull) does not require the compilation of all items.
Thanks.

**Comment by zdenop** [comment]
git pull can change also autoconf input files (e.g. 628de5ba3fe2879cff80343e327e3bae7f6b0634) so you need to run ./autogen.sh && ./configure...
