### ISSUE TITLE
Configure error on RHEL 7.2

### ISSUE THREAD

**Issue by vipulswarup** [tesseract-ocr/tesseract#782]
I am trying to build Tesseract from source on Red Hat 7.2. Upon running "./configure" I get the below error messages:

./configure: line 4188: syntax error near unexpected token `-mavx,'
./configure: line 4188: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'

Issue 647 (https://github.com/tesseract-ocr/tesseract/issues/647) is similar. I tried "autoconf-archive" via `yum install autoconf-archive`

But that package is not found by yum. Is there some other package that I should be installing on Red Hat?

**Comment by Shreeshrii** [comment]
http://rpm.pbone.net/index.php3?stat=3&search=autoconf-archive&srodzaj=3&dist[]=93

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by a455bcd9** [comment]
I have the same error, I installed `autoconf-archive-2016.09.16-1.el7.noarch` but I still got the same error message when I run `./configure --enable-debug`:

```
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
./configure: line 4188: syntax error near unexpected token `-mavx,'
./configure: line 4188: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'
```
