### ISSUE TITLE
Remove remaining cube related code 

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#784]
Please see https://groups.google.com/forum/#!msg/tesseract-ocr/24rrQjxLJl8/hNJEtLx4FQAJ

**Comment by amitdo** [comment]
>Moved cube aside without deleting it.

Since then, Ray deleted the Cube code.

...except that leftover in the enum.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/d2fcfcaec2/ccstruct/publictypes.h#L268

**Comment by stweil** [comment]
Keeping the old enum entries for Cube is not necessarily wrong. If API compatibility is a goal, those old entries must not be reused (but maybe should raise an error message when used from the command line). And of course the comments for the Cube entries also need an update.

Here is a more complete list of files which still contain text / code related to Cube:

    ChangeLog
    ccmain/docqual.cpp
    ccmain/fixspace.cpp
    ccstruct/publictypes.h
    ccstruct/ratngs.h
    ccutil/tessdatamanager.h
    ccutil/unicharset.cpp
    dict/dict.h
    training/tesstrain_utils.sh
    training/text2image.cpp

**Comment by amitdo** [comment]
PR #1281 clean ccstruct/publictypes.h

 @stweil, what about the rest of files?

**Comment by stweil** [comment]
I assume that ChangeLog will still contain cube related information for some time (maybe until 4.1.0 is released), but the other files are less obvious. There is some code which was related to cube, but might be used by LSTM as well, for example the parameter `output_word_boxes`. This needs more investigations to clarify the situation.

**Comment by Shreeshrii** [comment]
@stweil Can this be closed?
