### ISSUE TITLE
stdin on windows is possibly broken?

### ISSUE THREAD

**Issue by djusHa** [tesseract-ocr/tesseract#785]
Hi,
trying to pipe a pdf file, converted by graphicsmagic to tif, to tesseract stdin gives me following error output, but the generated PDF is ok.

my cmd line:
`gm.exe convert -density 300 pdfin.pdf tif:- | tesseract.exe stdin pdfout -l deu pdf`

---

tesseract version:
tesseract 4.00.00alpha                                                                                      
 leptonica-1.74.1 (Mar 23 2017, 02:16:52) [MSC v.1910 LIB Release x64]                                      
  libgif 5.1.4 : libjpeg 9b : libpng 1.6.28 : libtiff 4.0.7 : zlib 1.2.11 : libwebp 0.6.0 : libopenjp2 2.1.2
                                                                                                            
 Found AVX                                                                                                  
 Found SSE

---

tesseracts output:
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Page 1
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Page 2
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Page 3
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Page 4
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found

Maybe a Bug?

**Comment by jbreiden** [comment]
Do you get the same error messages when using text output?

gm.exe convert -density 300 pdfin.pdf tif:- | tesseract.exe txtout - -l deu

**Comment by djusHa** [comment]
no error, text output seems to be ok!

**Comment by jbreiden** [comment]
The error messages are harmless, but annoying. This change will get rid off half of them. I'll make a change in Leptonica to get rid of the other half. Thanks for the report.

```
--- api/pdfrenderer.cpp	2017-01-20 14:57:59.000000000 -0800
+++ api/pdfrenderer.cpp	2017-03-23 08:51:31.000000000 -0700
@@ -709,9 +709,8 @@
   L_COMP_DATA *cid = NULL;
   const int kJpegQuality = 85;
 
-  int format, sad;
-  findFileFormat(filename, &format);
-  if (pixGetSpp(pix) == 4 && format == IFF_PNG) {
+  int sad;
+  if (pixGetSpp(pix) == 4 && pixGetInputFormat(pix) == IFF_PNG) {
     Pix *p1 = pixAlphaBlendUniform(pix, 0xffffff00);
     sad = pixGenerateCIData(p1, L_FLATE_ENCODE, 0, 0, &cid);
     pixDestroy(&p1);
```

**Comment by djusHa** [comment]
thank you too.

**Comment by jbreiden** [comment]
Leptonica change will look something like this. These changes  are both forward and backward compatible, no need to adjust version dependencies.

```c++
--- leptonica/src/pdfio2.c	2017-03-09 08:41:53.000000000 -0800
+++ eptonica/src/pdfio2.c	2017-03-23 09:32:21.000000000 -0700
@@ -496,7 +496,7 @@
 /*!
  * \brief   l_generateCIDataForPdf()
  *
- * \param[in]    fname
+ * \param[in]    fname [optional]; can be null
  * \param[in]    pix [optional]; can be null
  * \param[in]    quality for jpeg if transcoded; 75 is standard
  * \param[out]   pcid compressed data
@@ -504,11 +504,15 @@
  *
  * <pre>
  * Notes:
+ *      (0) You must set either filename or pix.
  *      (1) Given an image file and optionally a pix raster of that data,
  *          this provides a CID that is compatible with PDF, preferably
  *          without transcoding.
  *      (2) The pix is included for efficiency, in case transcoding
  *          is required and the pix is available to the caller.
+ *      (3) We don't try to open files named "stdin" or "-" for Tesseract
+ *          compatibility reasons. We may remove this restriction
+ *          in the future.
  * </pre>
  */
 l_int32
@@ -526,24 +530,29 @@
     if (!pcid)
         return ERROR_INT("&cid not defined", procName, 1);
     *pcid = NULL;
-    if (!fname)
-        return ERROR_INT("fname not defined", procName, 1);
+    if (!fname && !pix)
+        return ERROR_INT("fname and pix not defined", procName, 1);
 
-    findFileFormat(fname, &format);
-    if (format == IFF_UNKNOWN)
-        L_WARNING("file %s format is unknown\n", procName, fname);
-    if (format == IFF_PS || format == IFF_LPDF) {
-        L_ERROR("file %s is unsupported format %d\n", procName, fname, format);
-        return 1;
+    if (fname && strcmp(fname, "-") != 0 && strcmp(fname, "stdin") != 0) {
+        findFileFormat(fname, &format);
+        if (format == IFF_UNKNOWN)
+          L_WARNING("file %s format is unknown\n", procName, fname);
+        if (format == IFF_PS || format == IFF_LPDF) {
+          L_ERROR("file %s is unsupported format %d\n",
+                  procName, fname, format);
+          return 1;
+        }
+        if (format == IFF_JFIF_JPEG) {
+          cid = l_generateJpegData(fname, 0);
+        } else if (format == IFF_JP2) {
+          cid = l_generateJp2kData(fname);
+        } else if (format == IFF_PNG) {
+          cid = l_generateFlateDataPdf(fname, pix);
+        }
+
     }
 
-    if (format == IFF_JFIF_JPEG) {
-        cid = l_generateJpegData(fname, 0);
-    } else if (format == IFF_JP2) {
-        cid = l_generateJp2kData(fname);
-    } else if (format == IFF_PNG) {  /* use Jeff's special function for png */
-        cid = l_generateFlateDataPdf(fname, pix);
-    } else {  /* any other format ... */
+    if  (!cid) {
         if (!pix)
             pixt = pixRead(fname);
         else
@@ -555,7 +564,7 @@
         pixDestroy(&pixt);
     }
     if (!cid) {
-        L_ERROR("file %s format is %d; unreadable\n", procName, fname, format);
+        L_ERROR("totally kerflummoxed\n", procName);
         return 1;
     }
     *pcid = cid;
```

**Comment by jbreiden** [comment]
I didn't realize this until now, but sending image data via stdin will cause image recompression and generational loss.

```cat foo.jpg | tesseract - - pdf````

Whereas using filename will not.

```tesseract foo.jpg - pdf````

What happens exactly will depend on the file format, but just wanted to raise awareness,

**Comment by stweil** [comment]
> +    if (fname && strcmp(fname, "-") != 0 && strcmp(fname, "stdin") != 0) {

I'd not add filename handling to Leptonica, but do that on the caller side. The caller then has to pass NULL if needed.

**Comment by jbreiden** [comment]
That would introduce a dependency on Lepntonica HEAD. (NULL will error out in Leptonical 1.74). Let's do this as a 4 step dance. 

(1) Hack "stdin" into Leptonica as writting above.
(2) Wait a long long time for next Leptonica to release and get everywhere
(3) Switch Tesseract to NULL
(4) Remove hack from Leptonica

**Comment by jbreiden** [comment]
Leptonica fix is in; Dan will be uploading to github shortly. Very similar to above except a small tweak to not use variable `cid` uninitialized.

**Comment by zdenop** [comment]
Is this issue still valid with recent code (leptonica & tesseract)?

**Comment by zdenop** [comment]
`cat Vigcd.jpg | tesseract.exe stdin pdfout -l eng pdf` works for me. Closing as fixed.

**Comment by SvenLauterbach** [comment]
Hi,

in which version of tesseract/leptonica is this fixed? When I try to run a similar command like the issue author i still get the error message:

`convert -density 300 ~/Downloads/scan.pdf -depth 8 tiff:- | tesseract stdin $(cat /proc/sys/kernel/random/uuid) -l deu+eng pdf`

output: 
```
Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica
Page 1
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
```

OS is Ubuntu 18.04, `tesseract --version` output:

```
tesseract 4.0.0-beta.1
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX
 Found SSE

```

**Comment by zdenop** [comment]
Your version of tesseract is too old. 4.0 was already released. See https://github.com/tesseract-ocr/tesseract/releases

**Comment by SvenLauterbach** [comment]
Ok, thanks for the quick answer. Tried updating via apt-get, but the version installed seems to be the latest version available in Ubuntu. I will use the compile the last release and try again.

**Comment by Shreeshrii** [comment]
You can also install latest version from the ppa by alex.

https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr
