### ISSUE TITLE
Supported compilers

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#789]
I think we should publish in the README the official supported compilers, including minimum version for each compiler.

**Comment by amitdo** [comment]
Someting like this:

## Supported Compilers
* GCC 4.8 and above
* Clang 3.4 and above
* MSVC 2015, 2017

Other Compilers might work, but are not officially supported.

**Comment by amitdo** [comment]
Clang is not tested right now with CI. Can someone fix that?

**Comment by amitdo** [comment]
I mean Clang + libc++ on Mac.

Testing Clang + libstdc++ on Linux would be nice.

**Comment by zdenop** [comment]
make a PR please.

**Comment by egorpugin** [comment]
Hi,

I've activated macos builds (clang).
See
https://travis-ci.org/tesseract-ocr/tesseract/builds/215040103
https://travis-ci.org/tesseract-ocr/tesseract/builds

**Comment by amitdo** [comment]
Thank Egor.

Zdenko, I'll send a PR in the following days.
