### ISSUE TITLE
copy the title instead of holding the pointer

### ISSUE THREAD

**Issue by jbreiden** [tesseract-ocr/tesseract#79]
This is a report from someone who makes Tesseract work on Android.
We can make his life easier by copying the string instead of holding onto 
the pointer.

https://github.com/tesseract-ocr/tesseract/blob/master/api/renderer.cpp#L55

In separate news, I see that  the renderers are not doing proper escaping
of that title before the put it into PDF or HOCR output. Maybe somebody
will worry about that some day.

Here's the relevant part of the report.

>I can pass a title from Java through JNI to Tesseract's BeginDocument() just 
>fine and that title will show up properly in the PDF. But if after calling 
>BeginDocument() I release the array of bytes representing that title using 
>ReleaseStringUTFChars in my
>Java_com_googlecode_tesseract_android_TessBaseAPI_nativeBeginDocument 
>method in JNI [1], then the title will show up in the PDF as garbled text, apparently 
>read from uninitialized memory. I'm guessing this means that Tesseract needs 
>the reference to that char* to stay around 
>
>https://gist.github.com/rmtheis/19965abdfca5c2c9eb26

**Comment by jbreiden** [comment]
change written, currently under review

**Comment by jbreiden** [comment]
Change is in Ray's hands and will eventually migrate here. The person in critical need has a copy.

**Comment by amitdo** [comment]
@jbreiden, we didn't get the patch. 
https://github.com/tesseract-ocr/tesseract/blob/2c837dffc3/api/renderer.cpp#L71

**Comment by amitdo** [comment]
cc: @theraysmith

**Comment by jbreiden** [comment]
This was the patch. I strongly suspect it made it in.

```diff
--- tesseract/api/baseapi.cpp   2015-06-12 17:25:51.000000000 -0700
+++ tesseract/api/baseapi.cpp   2015-08-18 17:46:15.000000000 -0700
@@ -991,8 +991,7 @@
   }
 
   // Begin producing output
-  const char* kUnknownTitle = "";
-  if (renderer && !renderer->BeginDocument(kUnknownTitle)) {
+  if (renderer && !renderer->BeginDocument(unknown_title_)) {
     return false;
   }
 
@@ -1166,8 +1165,7 @@
   }
 
   // Begin the output
-  const char* kUnknownTitle = "";
-  if (renderer && !renderer->BeginDocument(kUnknownTitle)) {
+  if (renderer && !renderer->BeginDocument(unknown_title_)) {
     pixDestroy(&pix);
     return false;
   }
--- tesseract/api/baseapi.h     2015-03-09 15:43:40.000000000 -0700
+++ tesseract/api/baseapi.h     2015-08-18 17:52:49.000000000 -0700
@@ -879,6 +879,12 @@
                                  int timeout_millisec,
                                  TessResultRenderer* renderer,
                                  int tessedit_page_number);
+  // There's currently no way to pass a document title from the
+  // Tesseract command line, and we have multiple places that choose
+  // to set the title to an empty string. Using a single named
+  // variable will hopefully reduce confusion if the situation changes
+  // in the future.
+  const char *unknown_title_ = "";
 };  // class TessBaseAPI.
 
 /** Escape a char string - remove &<>"' with HTML codes. */
--- tesseract/api/renderer.h    2014-08-12 11:22:47.000000000 -0700
+++ tesseract/api/renderer.h    2015-08-18 17:17:41.000000000 -0700
@@ -77,7 +77,7 @@
     bool EndDocument();
 
     const char* file_extension() const { return file_extension_; }
-    const char* title() const { return title_; }
+    const char* title() const { return title_.c_str(); }
 
     /**
      * Returns the index of the last image given to AddImage
@@ -126,7 +126,7 @@
 
   private:
     const char* file_extension_;  // standard extension for generated output
-    const char* title_;           // title of document being renderered
+    STRING title_;                // title of document being renderered
     int imagenum_;                // index of last image added
 
     FILE* fout_;                  // output file pointer
```

**Comment by jbreiden** [comment]
Yes, it went in as part of this commit.

https://github.com/tesseract-ocr/tesseract/commit/c1c1e426b32794d5e84134ee81bf895ff0228fe5

**Comment by amitdo** [comment]
Since you originally linked to `renderer.cpp`, I thought that the patch will be in that file.

I'm sorry for the mistake.
