### ISSUE TITLE
[os x 10.11.5]can't build   error: AC_CONFIG_MACRO_DIRS([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4    Something went wrong, bailing out!

### ISSUE THREAD

**Issue by niutao** [tesseract-ocr/tesseract#790]
run ./autogen.sh 

Running aclocal
Running /usr/local/bin/glibtoolize
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
glibtoolize: copying file 'config/ltmain.sh'
.libtoolize:   error: AC_CONFIG_MACRO_DIRS([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4

  Something went wrong, bailing out!

**Comment by zdenop** [comment]
What source are you using? "config" and "m4" is not part of [tesseract distribution.](https://github.com/tesseract-ocr/tesseract)

**Comment by amitdo** [comment]
No feedback from the user. I suggest to close this issue.
