### ISSUE TITLE
Error when using edited training_files.txt 

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#794]
tesstrain.sh creates training_files.txt  which is a listing of generated .lstmf files.

If this file is edited in a text editor, for example, to use only a few files for testing,  and saved then lstmtraining gives error when reading it.

If a new text file is  created using a subset of .lstmf files, eg. with following command, that file is accepted.

```
ls -1 *.Dig*.lstmf > train.txt
```

Files are attached.
ssd.training_files.txt is the original file, edited in notepad++, saved with unix EOL and utf8 with BOM setting. This does not work.

train.txt works.

[train.txt](https://github.com/tesseract-ocr/tesseract/files/875418/train.txt)
[ssd.training_files.txt](https://github.com/tesseract-ocr/tesseract/files/875419/ssd.training_files.txt)

**Comment by amitdo** [comment]
Your editor implants a (invisible) UTF-8 BOM.

**Comment by Shreeshrii** [comment]
Saving the file as UTF-8 (without the BOM setting) worked.

Thanks, Amit.

**Comment by Shreeshrii** [comment]
UTF-8 does not work.

Encoding as reported in notepad++ needs to be ANSI. 

I probably have a global setting to open all files as UTF-8.

**Comment by amitdo** [comment]
With Gedit I opened the file you created with notepad++ and did 'save as...' with encoding (of that file only) set to 8859-1. This made the terminal and the editor files equal in size.

Try to do something similar with notepad++.
http://docs.notepad-plus-plus.org/index.php/Convert_Or_Encode%3F
