### ISSUE TITLE
./configure: line 4238: syntax error near unexpected token `-mavx,' under Mac OSX

### ISSUE THREAD

**Issue by rgex** [tesseract-ocr/tesseract#796]
> ./configure
> checking for g++... g++
> checking whether the C++ compiler works... yes
> checking for C++ compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> Using git revision: 4.00.00alpha-358-g362b68e
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... config/install-sh -c -d
> checking for gawk... no
> checking for mawk... no
> checking for nawk... no
> checking for awk... awk
> checking whether make sets $(MAKE)... yes
> checking for style of include used by make... GNU
> checking whether make supports nested variables... yes
> checking dependency style of g++... gcc3
> checking whether to enable maintainer-specific portions of Makefiles... no
> checking build system type... x86_64-apple-darwin16.4.0
> checking host system type... x86_64-apple-darwin16.4.0
> ./configure: line 4238: syntax error near unexpected token `-mavx,'
> ./configure: line 4238: `AX_CHECK_COMPILE_FLAG(-mavx, avx=true, avx=false)'

Some issues with the same problem mention that installing autoconf-archive as a fix. However it is already installed on my system

> brew info autoconf-archive
> autoconf-archive: stable 2017.03.21 (bottled)
> Collection of over 500 reusable autoconf macros
> https://savannah.gnu.org/projects/autoconf-archive/
> /usr/local/Cellar/autoconf-archive/2017.03.21 (582 files, 3.4MB) *
>   Poured from bottle on 2017-03-30 at 17:48:56
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/autoconf-archive.rb
> ==> Dependencies
> Required: autoconf ✔

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/777#issuecomment-288116640
