### ISSUE TITLE
Can't Compile on Sierra with Macports

### ISSUE THREAD

**Issue by jsl303** [tesseract-ocr/tesseract#798]
I'm trying to follow the compiling wiki, but having a problem to get it to work.
https://github.com/tesseract-ocr/tesseract/wiki/Compiling
I'd appreciate any help!
sudo port install autoconf autoconf-archive automake leptonica pkgconfig
git clone https://github.com/tesseract-ocr/tesseract.git
  cd tesseract
  ./autogen.sh
Unable to find a valid copy of libtoolize or glibtoolize in your PATH!
./autogen.sh: line 59: bail_out: command not found
Running aclocal
Running 
./autogen.sh: line 87: -f: command not found

  Something went wrong, bailing out!
Thanks in advance!

**Comment by amitdo** [comment]
>Unable to find a valid copy of libtoolize or glibtoolize in your PATH!

You need to install the `libtool` package.

**Comment by jsl303** [comment]
Thanks so much! That worked perfectly! Can we add sudo port install libtool in the wiki?

**Comment by stweil** [comment]
> Can we add `sudo port install libtool` in the wiki?

It's already mentioned there.

**Comment by amitdo** [comment]
Yeah, I added the missing info to the wiki page right after posting my answer above :)

**Comment by amitdo** [comment]
>Unable to find a valid copy of libtoolize or glibtoolize in your PATH!

Maybe we should add here: "Make sure you have installed the 'libtool' package." ?
