### ISSUE TITLE
Can't build for windows

### ISSUE THREAD

**Issue by erichfrazer** [tesseract-ocr/tesseract#799]
frustrated. Why is open source always so sloppy when it comes to stuff like this? 
How does one build tess for Windows? The 2 lines for "how to build", which is basically finding and installing cppan, and running it, is not sufficient instructions by far. So how do you guys expect somebody to want to use this software if they have to spend a weekend trying to figure out how to get it to build? How about some serious steps of how to build it on windows, this time? Do I use a developer command prompt? Do I need cmake? Do I need mingw installed? What, exactly, are the steps? What are some of the common failure issues? A complete release includes complete how to build and how to install instructions.

**Comment by stweil** [comment]
If you just want to use Tesseract for Windows, I suggest using one of the binaries which already exist.

The [Tesseract wiki](https://github.com/tesseract-ocr/tesseract/wiki/Compiling) has more than two lines of documentation on building for Windows, and you are free to improve it.

I think the first problem is that there are several ways how it can be done. You have the choice of using either cmake or autoconf. It's possible to build with gcc, clang or MSVC. And you can use MSYS2, Mingw-w64 or CYGWIN. You can even cross compile on a Linux machine. Finally, you have to decide whether you want 32 or 64 bit binaries.

Personally I use cross compilation on Linux because compilation on Linux is much faster than on Windows.
As soon as you have installed all prerequisites, building becomes easy. I use autoconf:

    ./autogen.sh
    ./configure --host=i686-w64-mingw32 CXXFLAGS="-Wall -g"
    make install training-install
    make ScrollView.jar

Exactly the same commands also work on CYGWIN where you also can cross build using Mingw-w64.
64 bit binaries require `--host=x86_64-w64-mingw32`.

**Comment by amitdo** [comment]
>Why is open source always so sloppy when it comes to stuff like this?


:-1: 

If you have a issue with the software, just report about it, do not insult the developers!
:

**Comment by stweil** [comment]
> Why is open source always so sloppy when it comes to stuff like this?

@erichfrazer, I see from your GitHub profile that you work for a software company in Redmond, so you'll know how to do it the right way.

**Comment by erichfrazer** [comment]
oh sure, easy to bash MS. When I release software to consumers in the form of SDKs or code that is visible to the public, you can be damned sure I have to document the heck out of it and ensure it at least compiles. This tesseract stuff has taken me days to compile, not hours or minutes. The thing is, it's so easy (in the end) to simply write an actual Visual Studio or MS-compatible makefile and then get the whole thing to compile. But no, everybody has to try and go as far as possible to avoid MS, using mingw, cppan, msys2, cmake, blah de blah de blah, and none of that shit works well or is obvious, and none of it allows you to compile w/o having a degree in college-kid Linux.

SOMEBODY should write some VS2015 compatible vcxprojs and make them so they glob in place right in the middle of the tesseract / leptonica / whatever enlistments, and allows you to compile the darned thing.

Even cmake is silly that you can't target a bunch of different processor type and release mode builds all at the same time. I want to build x64, win32, release AND debug. This is not easy, and is very error prone trying to get this done with cmake.

Not as angry, because I got it to compile, but still cranky.

**Comment by amitdo** [comment]
>But no, everybody has to try and go as far as possible to avoid The Big Bad Company, using mingw, cppan, msys2, **cmake**, blah de blah de blah....

I have news for you. Microsoft officially supports CMake these days.
https://blogs.msdn.microsoft.com/vcblog/2016/10/05/cmake-support-in-visual-studio/

They also release this tool which also work with CMake
https://github.com/Microsoft/vcpkg

https://blogs.msdn.microsoft.com/vcblog/2016/09/19/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/

Maybe you can be more constructive and add support for Tesseract to the vcpkg repo?
https://github.com/Microsoft/vcpkg/issues/465

**Comment by erichfrazer** [comment]
I'm not the one releasing the software!! Why don't you come debug my Traffic App?

**Comment by amitdo** [comment]
It was nice talking with you...

**Comment by essamzaky** [comment]
First Thanks for Tesseract team for great work
Building form source for Windows using visual studio is not straight forward as described in tutorial
it failed to run VS2010 and succeeded in VS2015 but the generated files can't run in my machine.

most of VS developers like me not familiar with cross platform tools , i just want ask , would you create something like OpenCV? , it's just one zipped file  contain all what you need to build including the dependencies , GUI Cmake just used to select src path, dst pat and target Developing IDE  then build.

Is the previous scenario can be achieved ?

**Comment by amitdo** [comment]
Hi essamzaky,

Just to let you (and otherS who will read this comment), the build scripts are maintained mostly by a very small community team. For the VS/CMake build, there is only one man that work on it currently (not me) in his spare time.

@egorpugin, do you have any comment?

**Comment by egorpugin** [comment]
One should open a ticket with build errors provided and we'll try help with that.

**Comment by amitdo** [comment]
>it failed to run VS2010 

Copied from another issue:

>Does Tesseract 4.0 built with CMake supports VS2010 or not?

egorpugin commented

>No. Not out of the box.
>
>One needs fixing some bugs in tiff library that comes from cppan.
Or there's always manual way of including dependencies. In this case VS2010 might work.
>
>With cppan VS2015 and VS2017 are only supported.

**Comment by Shreeshrii** [comment]
Perhaps links to the old tutorials (external) for building with vs2008,
2010 etc should be removed from wikim

- excuse the brevity, sent from mobile

**Comment by essamzaky** [comment]
@Shreeshrii  Building from source using manual way might work for VS2010 , VS2008 as egorpugin commented
so if there is someone succeeded to build using manual way , it's better to describe how to use the manual way.
i succeeded to build most of dependence in my spare time i will back and build the rest of the solution and write about  my trial to build using the manual way.

**Comment by vdevan** [comment]
I had problems myself and finally decide to do it the hardway. I do not see why this needs to re-invented. Hence I have provided a complete solution kit along with binaries for Windows. Solution kit is made for Visual Studio 2015. Please check the link below and do replicate this, so we do not have this as an issue anymore.
https://github.com/vdevan/TesseractTrainingTools

**Comment by amitdo** [comment]
See also:
https://github.com/peirick/VS2015_Tesseract

**Comment by vdevan** [comment]
Yes I have added his link as well. Main difference is I have provided 
the training tools which was not there on the Peirick's link

என்றும் அன்புடன்
வாசு
அன்பைத் தவிர வேறு ஒன்றும் வேண்டேன் பராபரமே!


Always lovingly
Vasu Devan V.
God give me strength to love everyone.
http://www.kamban.com.au
http://brahas.com

**Comment by essamzaky** [comment]
Thanks for useful links, hope to update it soon for tesseract 4.0

**Comment by egorpugin** [comment]
Several people are doing the same things.
Look, we have manual deps management from peirick, vdevan, maybe others.
This just is not worth it.

**Comment by essamzaky** [comment]
Hi @egorpugin 
Finally i run the cppan today with build the VS2015 and it's working, i did the following steps 
delete the following folders "C:\Users\emz\tesseract" , "C:\Users\emz.cppan".
launch cmd from run and execute the following:
git clone https://github.com/tesseract-ocr/tesseract.git
cd tesseract
cppan
mkdir build
cd build
cmake .. -G "Visual Studio 14 2015" -DCPPAN_USE_CACHE=0

Thanks egor

**Comment by Shreeshrii** [comment]
win32 and win64 binaries for the latest builds are available from the artifacts tab on job details from 

https://ci.appveyor.com/project/zdenop/tesseract

click on platform: win32 / win64

click on artifacts tab

download the zip file with .exe and .dll files, eg. 

for build 854 for branch 3.05 https://ci.appveyor.com/api/buildjobs/dvitkw19012r6x7h/artifacts/build%2Fbin%2Ftesseract-3.05.854.zip

for build 853 for master for 4.00
https://ci.appveyor.com/api/buildjobs/ppvggc1nq30dawab/artifacts/build%2Fbin%2Ftesseract-master.853.zip

**Comment by korhun** [comment]
@egorpugin -> Thank you very much! The information provided in [wiki](https://github.com/tesseract-ocr/tesseract/wiki/Compiling) did not worked for me, bu this worked. Why don't you change the wiki?

For x64 this worked for me:
cd tesseract
cppan
mkdir build_x64
cd build_x64
cmake .. -G "Visual Studio 14 2015 Win64" -DCPPAN_USE_CACHE=0

**Comment by zaryk** [comment]
Wiki didn't work for me either.  Used -DCPPAN_USE_CACHE=0.  Files show in the build folder, also have this:

cmake .. -G "Visual Studio 15 2017" -DCPPAN_USE_CACHE=0


> CMake Error: install(EXPORT "TesseractTargets" ...) includes target "libtesseract" which requires target "e3a1c7a4" that is not in the export set.
> CMake Error: install(EXPORT "TesseractTargets" ...) includes target "libtesseract" which requires target "e3a1c7a4" that is not in the export set.
> CMake Error: install(EXPORT "TesseractTargets" ...) includes target "libtesseract" which requires target "e3a1c7a4" that is not in the export set.
> CMake Error: install(EXPORT "TesseractTargets" ...) includes target "libtesseract" which requires target "e3a1c7a4" that is not in the export set.
> -- Generating done
> -- Build files have been written to: C:/Use.....build32
