### ISSUE TITLE
Finding Rect coordinates

### ISSUE THREAD

**Issue by FPCscott** [tesseract-ocr/tesseract#802]
Is there an easy way to find the coordinates for specific data that we are trying to harvest?  We have 2 areas of interest that we are trying to read.   So far the best option that I've found is trial and error.  Hoping there is a sample project to draw the area  on a scanned image or some other good way.

Any help would be appreciated.

**Comment by Shreeshrii** [comment]
have you looked at
`hocr`
and
`tsv` 
output formats?

see https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support
