### ISSUE TITLE
coordinates of a skewed image

### ISSUE THREAD

**Issue by varun1994varun** [tesseract-ocr/tesseract#804]
Hi,I have given a skewed image as input to Tesseract-ocr.
The plain text output generated de-skews the image and is giving the correct output.
But in hocr output, the bounding box coordinates of the words are with respect to the original skewed image.
So,Is there any way to get the coordinates of the words of image which is deskewed by the tesseract or can we get hold of deskewed image itself?
Thank you.

**Comment by zdenop** [comment]
Please use tesseract user forum for asking questions.
