### ISSUE TITLE
Tesseract doesn't see the changes after Arabic traning 

### ISSUE THREAD

**Issue by am0awad** [tesseract-ocr/tesseract#805]
Hello All,

I want to ask about the issue that I faced after making training for tesseract for **Arabic**, I have Ubuntu & Tesseract-ocr 3.04
**Steps**:

1.  $ convert ara.arial.exp1.jpg ara.arial.exp1.tif 
2.  $ tesseract ara.arial.exp1.tif ara.arial.exp1 -l ara batch.nochop makebox
3. edit the boxes using Qt Box Editor
4. then run the script:
`
tesseract ara.arial.exp1.tif ara.arial.exp1.box nobatch box.train -l ara 
unicharset_extractor ara.arial.exp1.box
echo "arial 0 0 1 0 0" > font_properties # tell Tesseract informations about the font
shapeclustering -F font_properties -U unicharset ara.arial.exp1.box.tr 
mftraining -F font_properties -U unicharset -O ara.unicharset ara.arial.exp1.box.tr 
cntraining ara.arial.exp1.box.tr 
mv inttemp ara.inttemp
mv normproto ara.normproto
mv pffmtable ara.pffmtable
mv shapetable ara.shapetable
combine_tessdata ara.`
5. $ cp ara.traineddata /usr/share/tesseract-ocr/tessdata
6. $ tesseract ara.arial.exp1.tif out -l ara 

When I run the 6th one I have a bad result and the tesseract engine doesn't see the changes that I made it through Qt Box Editor
Any help!!

**Comment by amitdo** [comment]
Don't try to train Tesseract version earlier than 4.0 for Arabic. It's hopeless.
This subject has been discussed many times here and in the forum.

For 4.0 only train with the LSTM method.

**Comment by amitdo** [comment]
I've updated the wiki.
https://github.com/tesseract-ocr/tesseract/wiki/Training-Tesseract#background-and-limitations

**Comment by am0awad** [comment]
@amitdo  Thanks, this is the reason why I don't get any progress!
