### ISSUE TITLE
Tesseract v3.04.01 outputs to stderr

### ISSUE THREAD

**Issue by deajan** [tesseract-ocr/tesseract#811]
Hello,
Using tesseract v3.04.01 on Fedora 25, a standard transformation like
```tesseract somefile.png pdf -l eng > output 2> error```
will write ```Tesseract Open Source OCR Engine v3.04.01 with Leptonica``` to error file even if the transformation worked as expected.
tesseract v3.02 on Ubuntu 12.04.5 writes to stdout instead of stderr.

Regards,
Ozy.

**Comment by zdenop** [comment]
1. Current stable version is 3.05
2. Banner text output is to stderr because from 3.04 there is possible to output OCR result to stdin and banner text should not be part of  OCR output (stdout)
