### ISSUE TITLE
Docker image fails to build

### ISSUE THREAD

**Issue by benstadin** [tesseract-ocr/tesseract#817]
The docker image fails to build. Host is Ubuntu 16.04.

The following commands were used to start the build:

```
git clone https://github.com/tesseract-ocr/tesseract.git
cd tesseract
sudo docker build -t docker-tesseract .
```

Error message:

```
$ cmake .. -DLeptonica_DIR=leptonica-$LEPT_VER/build
CMake Error at /usr/share/cmake-3.7/Modules/CMakeDetermineCCompiler.cmake:48 (message):
  Could not find compiler set in environment variable CC:

  gcc-4.8.
Call Stack (most recent call first):
  CMakeLists.txt:47 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/root/build/tesseract-ocr/tesseract/build/CMakeFiles/CMakeOutput.log".

travis_time:end:0b3c16ed:start=1491933375378626936,finish=1491933375393151695,du
The command "cmake .. -DLeptonica_DIR=leptonica-$LEPT_VER/build" exited with 1.
$ make
make: *** No targets specified and no makefile found.  Stop.

travis_time:end:2a97cb84:start=1491933375396141259,finish=1491933375399900930,du
The command "make" exited with 2.

```

**Comment by amitdo** [comment]
CC: @ianblenke (#282)

**Comment by xlight** [comment]
try HTTPS://hub.Docker.com/r/xlight/docker-tesseract4

Amit D. <notifications@github.com>于2017年4月12日 周三上午2:12写道：

**Comment by amitdo** [comment]
https://github.com/xlight/docker-tesseract4/blob/master/Dockerfile

@xlight ,

Why the `--enable-debug`? With this option Tesseract will be compiled with -O0 and will be VERY slow.

**Comment by Shreeshrii** [comment]
@amitdo

since 4.0 version is alpha, --enable-debug is useful to track errors.

**Comment by amitdo** [comment]
It's not a good idea to use it with a docker image.

**Comment by Shreeshrii** [comment]
Related issue: https://github.com/tesseract-ocr/tesseract/issues/893

@amitdo I have updated wiki compilation page regarding --enable-debug. Thanks!

**Comment by speedfl** [comment]
@amitdo why do you say that it is not a good idea?

**Comment by xlight** [comment]
I built it with enable debug , because I want to know the reason why lstmtraining with eval_listfile coredump.
But It does not help

**Comment by Shreeshrii** [comment]
@xlight please see https://github.com/tesseract-ocr/tesseract/issues/893 and help @speedfl 
Thanks!

**Comment by amitdo** [comment]
>why do you say that it is not a good idea?

Because of its slowness. I think that users of Docker Hub images expect to get an optimized build, not a debug one.

**Comment by speedfl** [comment]
Ah oh course. I tried without but I am getting the issue 893...
Btw thx to @xlight for his docker file. I just added the download and move of some traineddata.

**Comment by Shreeshrii** [comment]
@xlight 

> I want to know the reason why lstmtraining with eval_listfile coredump. 

Please try with the latest code. I think the coredump problem is fixed by the latest commits by Ray. However, there seems to be a `Deserialize failed` message, so the eval may still not be running.

**Comment by amitdo** [comment]
@stweil, can you fix it?

**Comment by Shreeshrii** [comment]
Added page to wiki - https://github.com/tesseract-ocr/tesseract/wiki/4.0-Dockerfile

**Comment by Shreeshrii** [comment]
>Definitions of Docker containers and scripts that help to compile and run Tesseract 4 are available at:

https://github.com/tesseract-shadow/tesseract-ocr-compilation

**Comment by Shreeshrii** [comment]
@zdenop This issue can be closed.

**Comment by amitdo** [comment]
>The docker image fails to build. Host is Ubuntu 16.04.

The file `Dockerflle` in our repo is still not fixed.

Maybe we should remove this file (and `docker-compose.yml`).

**Comment by Shreeshrii** [comment]
Sorry, did not realize the dockerfile was in tesseract repo. It seems to be related to travis build. Is it being used?

**Comment by amitdo** [comment]
It supposed to be used by users that want docker image of Tesseract.

I think we should remove it from the our repo.

**Comment by stweil** [comment]
The Dockerfile configures a Docker container which builds Tesseract using the Travis configuration, so it can be used to locally test problems with that configuration (only the Linux part, not the macOS part). I can fix it, but that needs some time.

**Comment by amitdo** [comment]
>I can fix it, but that needs some time.

OK. If you plan to fix it, we can keep it.

**Comment by stweil** [comment]
See pull request #932 for a fix.

**Comment by amitdo** [comment]
Does your PR solves the OP issue?

>CMake Error at /usr/share/cmake-3.7/Modules/CMakeDetermineCCompiler.cmake:48 (message):
>  Could not find compiler set in environment variable CC:
>
>  gcc-4.8.

**Comment by stweil** [comment]
@benstadin, could you please retry your docker build with the changes from #932?

@amitdo, I did not get the same error message initially, therefore I don't know. The `Dockerfile` uses the master branch of https://github.com/travis-ci/travis-build. If there is an issue with that latest version, it might damage the docker build process. I looked for a stable version of `travis-build`, but the latest release was made in 2014.
