### ISSUE TITLE
Fontlist fails 

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#820]
Hi,
im using tesseract 3.05.00dev on windows CMD, i was able to create .tif files and .box file when i run the command for a single font, yet when i try to create fontlist  an error is generated for every font, the error message is **Font Arial failed with 7909 hits = 17.73%** and there is an error message for every font with the same description, the command that i use is **text2image --text=testtxt.txt --outputbase=eng --fonts_dir=C:\Tesseract\Tesseract-OCR3.03\test_fonts --find_fonts --min_coverage=1.0 --render_per_font=false --fontconfig_tmpdir=C:\Tesseract\Tesseract-OCR3.03** notice in the in the folder test_fonts there is only 5 fonts which all support English  and i changed the coverage but the error is the same even if the coverage is 17 the error is changed but still there is an error, i created a text file by notepad and saved it UTF8 but the case is the same, how can i solve this problem?
Thanks

**Comment by amitdo** [comment]
HI,

I don't think there is a bug here. The right place to ask questions is [our forum](https://groups.google.com/d/forum/tesseract-ocr).
