### ISSUE TITLE
segmentation fault with --psm 0

### ISSUE THREAD

**Issue by pritamdodeja** [tesseract-ocr/tesseract#821]
Command below results in a segmentation fault
tesseract a.jpg stdout --oem 1 --psm 0 -l eng  

Environment details:
Which operating system - Ubuntu 16.10 Yakkety Yak on x86_64
Which version/commit of tesseract - top of Changelog says 2017-03-24 - v4.00.00-alpha
How was tesseract built or - I compiled it from source

Command above works with --psm 3 is used instead.

Pritam Dodeja

**Comment by amitdo** [comment]
Try `tesseract a.jpg stdout --oem 0 --psm 0 -l eng`

**Comment by amitdo** [comment]
Also try with this image:
https://github.com/tesseract-ocr/tesseract/raw/master/testing/phototest.tif

**Comment by pritamdodeja** [comment]
Find below

 tesseract phototest.tif stdout --oem 0 --psm 0 -l eng
TIFFFetchNormalTag: Warning, ASCII value for tag "Photoshop" does not end in null byte. Forcing it to be null.
TIFFFetchNormalTag: Warning, ASCII value for tag "Photoshop" does not end in null byte. Forcing it to be null.
TIFFFetchNormalTag: Warning, ASCII value for tag "Photoshop" does not end in null byte. Forcing it to be null.
Page 1
Page number: 0
Orientation in degrees: 0
Rotate: 0
Orientation confidence: 15.98
Script: Latin
Script confidence: 460.00

tesseract phototest.tif stdout --oem 1 --psm 0 -l eng
TIFFFetchNormalTag: Warning, ASCII value for tag "Photoshop" does not end in null byte. Forcing it to be null.
TIFFFetchNormalTag: Warning, ASCII value for tag "Photoshop" does not end in null byte. Forcing it to be null.
TIFFFetchNormalTag: Warning, ASCII value for tag "Photoshop" does not end in null byte. Forcing it to be null.
Page 1
Segmentation fault (core dumped)

tesseract phototest.tif stdout --oem 1 --psm 3 -l eng
TIFFFetchNormalTag: Warning, ASCII value for tag "Photoshop" does not end in null byte. Forcing it to be null.
TIFFFetchNormalTag: Warning, ASCII value for tag "Photoshop" does not end in null byte. Forcing it to be null.
TIFFFetchNormalTag: Warning, ASCII value for tag "Photoshop" does not end in null byte. Forcing it to be null.
Page 1
This is a lot of 12 point text to test the
ocr code and see if it works on all types
of file format.

The quick brown dog jumped over the
lazy fox. The quick brown dog jumped
over the lazy fox. The quick brown dog
jumped over the lazy fox. The quick
brown dog jumped over the lazy fox.

Pritam

**Comment by amitdo** [comment]
The warning are ugly but seems harmless.

With --oem 1 and --psm 0 Tesseract works as expected.

With --oem 1 and --psm 0 Tesseract segfault.
The reason - The new LSTM engine has no OSD feature **currently**, only the older engine has it.

For now, the solution is to always use --oem 0 when using --psm 0

**Comment by amitdo** [comment]
BTW, you should use 'osd' instead of 'eng' with --psm 0.

Using 'eng' will result in always detecting 'Latin' as the script, even if the text is written in other script.

**Comment by pritamdodeja** [comment]
From what I have read, tesseract v4 greatly improves ocr due to LSTM.  If I know that my text is going to be of a certain orientation and script  (top to bottom and English), how do I take advantage of the newer engine?  Thanks for the help and sorry for the delay in my response.

**Comment by amitdo** [comment]
The new engine is in alpha stage. It's not yet considered ready to replace the stable 3.05 version.
There is a plan to add an OSD feature to the LSTM engine.

**Comment by pritamdodeja** [comment]
Is there any update on this?  Let me know if you want me to do any testing etc.  Thanks!

**Comment by amitdo** [comment]
I'm sorry, but there is no update on this issue.

**Comment by Shreeshrii** [comment]
>From what I have read, tesseract v4 greatly improves ocr due to LSTM. If I know that my text is going to be of a certain orientation and script (top to bottom and English), how do I take advantage of the newer engine? 

If you want to OCR English text, use the program (latest version built from master branch in github) with default options or specify language as English.

`tesseract ./testing/eurotext.tif eurotext`

or
`tesseract ./testing/eurotext.tif eurotext --oem 1 --psm 6 -l eng`

**Comment by ivanzz1001** [comment]
tesseract4.0.0 alpha, execute the following command:
<pre>
[root@localhost workspace]# /opt/tesseract4.0/bin/tesseract pic/tesseract-chinese-1.png stdout --psm 0 
Warning. Invalid resolution 0 dpi. Using 70 instead.
Failed loading language 'osd'
Tesseract couldn't load any languages!
Warning: Auto orientation and script detection requested, but osd language failed to load
Estimating resolution as 219
Segmentation fault (core dumped)
</pre>
But exactly, the osd.traineddata is the right space:
<pre>
[root@localhost workspace]# ls /opt/tesseract4.0/share/tessdata/
chi_sim.traineddata       chi_tra.traineddata       configs/                  ori.traineddata           pdf.ttf                   
chi_sim_vert.traineddata  chi_tra_vert.traineddata  eng.traineddata           osd.traineddata           tessconfigs/ 
</pre>
then I use the "--oem 0" options:
<pre>
[root@localhost workspace]# /opt/tesseract4.0/bin/tesseract pic/tesseract-chinese-1.png stdout --psm 0 --oem 0
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
</pre>

Then I use tesseract3.05.1, It seems that tesseract always detect the script is "Latin", not what I expected Chinese.

**Comment by amitdo** [comment]
try this:

>tesseract pic/tesseract-chinese-1.png stdout -l osd --psm 0 --oem 0

**Comment by abir26** [comment]
I am having the same problem with Tesseract 4.0.0-beta /leptonica-1.75.3
I get this error : "Error: Illegal Parameter specification!
"Fatal error encountered!" == NULL:Error:Assert failed:in file globaloc.cpp, line 75 " when I run my code in JAVA or an empty output when I use the command line or c++ code and that's whenever I use a segmentation mode with OSD (--psm= 0,1 or 12). Also I get the Orientation, WritingDirection and DeskewAngle always equal to 0. 
<img width="883" alt="osd problem" src="https://user-images.githubusercontent.com/38217333/38503968-c959f4fe-3c13-11e8-8380-ddc5ce6744bd.png">

**Comment by stweil** [comment]
I think this was fixed in commit 27ce472666a6332f38888cd6855e1162fb82c729, so this issue could be closed.
