### ISSUE TITLE
[4.00] no document for net_spec in lstm training

### ISSUE THREAD

**Issue by xlight** [tesseract-ocr/tesseract#822]
I want to know how to tweak the net_spec.
but I did not find any document about these chars and numbers except few words in "Training Just a Few Layers" of [here](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00)

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/VGSLSpecs

**Comment by xlight** [comment]
thanks
shame
