### ISSUE TITLE
How to detect table region after the update in Tablefind.cpp?

### ISSUE THREAD

**Issue by AzkaGilani** [tesseract-ocr/tesseract#825]
Previously i have been using this variable **"textord_dump_table_images"** to get the bounding box for detected tables preset in document images. But after the recent update, this parameter has been removed. So, how can i get the output for table regions by tesseract-ocr?

**Comment by amitdo** [comment]
Just for reference, it was removed in this commit.
https://github.com/tesseract-ocr/tesseract/commit/a1c22fb0d0f6bde165ec7b7c3125420b0ba1d541#diff-4515c1af024bb873af6ca896567e98cfL146

**Comment by amitdo** [comment]
Just for reference, it was removed in this commit.
https://github.com/tesseract-ocr/tesseract/commit/a1c22fb0d0f6bde165ec7b7c3125420b0ba1d541#diff-4515c1af024bb873af6ca896567e98cfL146

**Comment by amitdo** [comment]
Currently, it is possible to get the bbox of table blocks with the API but not with the command line.

**Comment by AzkaGilani** [comment]
How to get that with the help of API? i am unable to find any documentation for that

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/7231e676/ccstruct/publictypes.h#L48
https://github.com/tesseract-ocr/tesseract/blob/7b5b16779a/ccmain/pageiterator.cpp#L357

Iterate through the page blocks, check the type of each block, and if it's of table type get its bbox.

**Comment by AzkaGilani** [comment]
Thankyou for your reply :) I tried this but it returns BlockType=1( PT_UNKNOWN ) on all the images either they contain table or not. Any idea?

**Comment by amitdo** [comment]
>I tried this but it returns BlockType=1( PT_UNKNOWN ) on all the images either they contain table or not. Any idea?

Sorry, no. You can try askiing in [our forum](https://groups.google.com/d/forum/tesseract-ocr).
In general, that's the the right place to ask questions.

if the value is 1, then the block is recognized as  `PT_FLOWING_TEXT`. enums start from 0.

**Comment by AzkaGilani** [comment]
Hey thanks for the help. I have posted on that forum. :)
bdw any idea that why i am getting 1 for whole image? shouldnt it return output for each block in the image?
I am really sorry for asking these basic questions as i am purely a newbie in tesseract.

**Comment by amitdo** [comment]
Not sure, but I think that the table recognition only work when the table has full frame (square, solid lines).

**Comment by AzkaGilani** [comment]
![table2](https://cloud.githubusercontent.com/assets/20331292/25085387/df813fe2-232f-11e7-98b3-ec4b627e5daa.png)
I guess there is some other issue. It returns the same output even on this image too

**Comment by amitdo** [comment]
Try to set this variable to true.
https://github.com/tesseract-ocr/tesseract/blob/a1c22fb0d/textord/tablefind.cpp#L151

**Comment by AzkaGilani** [comment]
```
        if (! ( api->SetVariable("textord_show_tables", "true")))
        {cout<<"variable not set"<<endl;}
        else
        {cout<<"variable is set"<<endl;}
        if (! ( api->SetVariable("textord_tablefind_recognize_tables", "true")))
        {cout<<"variable not set!!"<<endl;}
        else
        {cout<<"variable is set!!"<<endl;}
        
        tesseract::PageIterator *ri = api->GetIterator();
        tesseract::PageIteratorLevel level = tesseract::RIL_BLOCK;

        if (ri != 0) {
            do {
                      cout<<ri->BlockType()<<endl;
                
            } while (ri->Next(level));
        }
```
Still getting Block type 1 for all images:/

**Comment by AzkaGilani** [comment]
Do you have any idea that after setting variable, how can i see its output? for example, i have set **textord_show_tables** but how can i see the result of that variable on my image?

**Comment by amitdo** [comment]
You didn't set `textord_tablefind_recognize_tables` in your code. Do it instead of setting another variable.

**Comment by AzkaGilani** [comment]
api-> SetVariable("textord_tablefind_recognize_tables", "true")
        
        tesseract::PageIterator *ri = api->GetIterator();
        tesseract::PageIteratorLevel level = tesseract::RIL_BLOCK;

        if (ri != 0) {
            do {
                      cout<<ri->BlockType()<<endl;
                
            } while (ri->Next(level));
        }

**Comment by AzkaGilani** [comment]
I have set this variable. How can i see the effect of that variable on my image??
I am really sorry for asking such a noob question.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/ViewerDebugging

I don't think it will help.

**Comment by AzkaGilani** [comment]
Okay :/

**Comment by Shreeshrii** [comment]
Amit, Is  variable "textord_dump_table_images" also removed from 3.05 branch?

**Comment by AzkaGilani** [comment]
Yes it has been removed

**Comment by amitdo** [comment]
>Amit, Is variable "textord_dump_table_images" also removed from 3.05 branch?

No.
https://github.com/tesseract-ocr/tesseract/blob/3.05/textord/tablefind.cpp#L146

**Comment by Shreeshrii** [comment]
So @azkagilani should be able to use 3.05 branch for earlier code to work.

- excuse the brevity, sent from mobile

**Comment by AzkaGilani** [comment]
@shreeshrii 
Actually i compiled the latest version of tesseract and in that this variable was missing. I will compile using 3.05 branch now.
Can you please tell me that after setting the variable "textord_dump_table_images" , how will i be able to get the output bounding box fot table from it??
This is the major puzzle that is i am unable to understand :(

**Comment by amitdo** [comment]
>Previously i have been using this variable "textord_dump_table_images" to get the bounding box for detected tables preset in document images.

**Comment by hopescheffert** [comment]
@amitdo @AzkaGilani @Shreeshrii  Did you ever find out how to get the bounding box around the tables detected in 3.05? I have the ViewerDebugger but that pops up with a handful of windows and all I want is the coordinates for that bounding box. I know it finds the tables, I just need that information as coordinates, instead of a window/image.
Here is an example:
![image](https://user-images.githubusercontent.com/14129035/27975295-21321b96-6327-11e7-9805-354287ab9976.png)
