### ISSUE TITLE
unverified memory allocation -> app crash.

### ISSUE THREAD

**Issue by lcarrere** [tesseract-ocr/tesseract#827]
Hello,

in dawg.cpp there is a non verified memory allocation:

edges_ = (EDGE_ARRAY) memalloc(sizeof(EDGE_RECORD) * num_edges_);

This can  cause application crash in high memory usage context. I can manage to propose a modification but it sounds to me that lot of refactoring is required depending the way you want to handle such context.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/master/cutil/emalloc.cpp
https://github.com/tesseract-ocr/tesseract/blob/master/cutil/danerror.cpp
https://github.com/tesseract-ocr/tesseract/blob/master/ccutil/globaloc.cpp
https://github.com/tesseract-ocr/tesseract/blob/master/ccutil/errcode.cpp

**Comment by zdenop** [comment]
Closing as current code does not memalloc anymore. If you experience app crash because of memory allocation please make a new issue file details how to reproduce it.

**Comment by stweil** [comment]
The issue was fixed in pull request #860 / commit 300841f9a.
