### ISSUE TITLE
Tesseract 4 Tesstrain

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#828]
Hi,
im trying to run this command on bash (on windows 10): **training/tesstrain.sh --fonts_dir /usr/share/fonts --lang ara --langdata_dir ../langdata --tessdata_dir ./tessdata --output_dir ./output1**
yet it keeps generating the error: **ERROR: text2image not found** although the text2image exists on the directory: training, keep in mind all the binaries tesstrain and text2image i didn't chose their location when i installed them, i simply followed the compilation of the tesseract 4 and leptonica 1.74.1, also the command i got it from the [website](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00)
note: i also tried the same command for eng, yet the same result
thanks

**Comment by amitdo** [comment]
[A guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).
Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).
