### ISSUE TITLE
LSTM : Training - Support WordStr Box file option

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#832]
WordStr Box file option has been defined in the training wiki for 4.0 LSTM. However it is not yet implemented in the code.

This will be useful for using scanned images for training.

Thanks!

See related discussion at https://github.com/tesseract-ocr/tesseract/issues/591

**Comment by amitdo** [comment]
See also https://github.com/tesseract-ocr/tesseract/issues/670#issuecomment-274275423 and below.

**Comment by amitdo** [comment]
+1

Even better would be a new line box format (`image1.linebox`).

Maybe something like this.

```
linebox left, top, right, bottom
text <t e x t h e r e>
linebox ...
text ...
```
@theraysmith, what do think about that?

**Comment by Shreeshrii** [comment]
Ray's comment copied from https://github.com/tesseract-ocr/tesseract/issues/670 (closing that issue now as duplicate)

> unicharset_extractor doesn't read the WordStr box file format.
Sorry this is an un-tested path.
Furthermore, it isn't just a case of modifying unicharset_extractor.
For the Indic languages, the unicharset needs to know the syllable/grapheme clusters, and it can't get that from the Wordstr box file format. The best it can do is extract the unicodes used in the WordStr box file or you start with an existing unicharset for that training path.

**Comment by Shreeshrii** [comment]
@amitdo Will your changes - https://github.com/amitdo/tesseract/commit/8fe2d918e447
work now that the new unicharset_extractor has been posted.

**Comment by amitdo** [comment]
I don't know...

**Comment by ferjad** [comment]
@Shreeshrii @amitdo
Any update on line level training for LSTM? Or if tesseract supports training from images now.
I see the unicharset extractor has changed and there are some lstm specific changes. Going through some other issues I have seen that training from images is not supported, what does this imply?

**Comment by amitdo** [comment]
>Any update on line level training for LSTM?

It's still not supported :(

**Comment by godofcheerup** [comment]
@amitdo Hi. Is it possible to train tesseract 4.00 Beta.1 in images which I owned? Not yet?

**Comment by amitdo** [comment]
It's still not supported.

**Comment by NyanProgrammer** [comment]
I want to know if its possible doing this training , and what are the key part of the code to do it, i need some explanation about what are the process or maybe what is the vision and criteria for the current tesseract development and make this change possible.

**Comment by Shreeshrii** [comment]
Done via https://github.com/tesseract-ocr/tesseract/commit/15f2a4b2c166ad18fe8d980e303d5052a47c37d3
