### ISSUE TITLE
TensorFlow and Tesseract

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#838]
Tesseract 4.00 can be used with tensorflow in some way.

 @theraysmith,
This feature needs Documentation - How to use it?

**Comment by Omnipresent** [comment]
Would like to know this as well

**Comment by maamountki** [comment]
anyone have clue for this? tensorflow is well optimized for CPUs, GPUs and TPUs especially after releasing XLA compiler, would be nice to use tesseract with it.

**Comment by stweil** [comment]
As far as I know Tesseract currently cannot be linked with Tensorflow.

**Comment by bclyc** [comment]
I'm using TF and tesseract in the same project but seperately, would like to know the answer too.

**Comment by SragAR** [comment]
You can use tesseract and tensorflow together in  Python.
Use pytesseract module.
https://github.com/madmaze/pytesseract

**Comment by maamountki** [comment]
@SragAR How can i use it with tensorflow? It's just wrapper for tesseract, I don't see anything implemented to work with tensorflow.

**Comment by theceday** [comment]
-The model in tesseract is exactly same as with this one, or modified version of it?
https://github.com/tensorflow/models/tree/master/research/street

-I am looking for a way to do training in tensorflow, maybe try a few other models like crnn etc
Is the easiest way to do this (if using another model), using tensorflow C++ API directly right?

**Comment by stevenliy** [comment]
> 
> 
> -The model in tesseract is exactly same as with this one, or modified version of it?
> https://github.com/tensorflow/models/tree/master/research/street
> 
> -I am looking for a way to do training in tensorflow, maybe try a few other models like crnn etc
> Is the easiest way to do this (if using another model), using tensorflow C++ API directly right?

Anyone can answer ?

**Comment by theceday** [comment]
probably its the same infrastructure code though with a different network setup.
https://github.com/tensorflow/models/blob/master/research/street/python/vgsl_train.py
for tesseract see here:
https://github.com/tesseract-ocr/tesseract/wiki/VGSLSpecs

and somewhere in issues or mail group, there is very detailed info about actual parameters used for each language during training.

**Comment by stweil** [comment]
The Tesseract code has some conditional parts which depend on macro `INCLUDE_TENSORFLOW`, so it is prepared to be compiled with Tensorflow. That requires a separate installation of Google's protocol buffers and Tensorflow and much patience to hack the build environment until it works. After spending several hours on this I am still not successful.

**Comment by theceday** [comment]
as far i know, it has an custom OP to handle variable size height dimension, if you want to use it you need to compile tensorflow from sources last time i checked, you cant load an custom OP with precompiled tensorflow. (however i am not sure this is still the case)
compiling tf is not hard with ubuntu, but in windows it was giving some headaches, though currently it might have less issues with bazel version. I havent compiled the OP though.

**Comment by stweil** [comment]
Now Tesseract can be built with TensorFlow (see pull request #2461).

**Comment by Shreeshrii** [comment]
Analytics India Magazine: How Developers Can Benefit From Intel optimization of TensorFlow.
https://analyticsindiamag.com/how-developers-intel-tensorflow-optimization/?utm_source=rss&utm_medium=rss&utm_campaign=how-developers-intel-tensorflow-optimization

**Comment by amitdo** [comment]
See also my comment and the following comment by stweil: https://github.com/tesseract-ocr/tesseract/issues/3552#issuecomment-915383851
