### ISSUE TITLE
Tesseract 4.00alpha Arabic Character

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#840]
Hi,

I'm using tesseract 4.00alpha with leptonica 1.74.1 to train Arabic model for to make recognition for images, I'm using langdata that are recommended [this](https://github.com/tesseract-ocr/langdata.git) and also i use the trained data in [this](https://github.com/tesseract-ocr/tessdata), so after i create .lstmf file i use that file for the recognition of images with Arabic text, the command: **tesseract image.tif output -l ara --oem 1** .

the the recognition is fine at the output file, yet i have a character that is recognized wrong, see, in Arabic  the "ال" means "the" and its connected to the next word so if a word start with the letter "m" which is equivalent to "م" the word's beginning will look like 
![reg](https://cloud.githubusercontent.com/assets/26926171/25390534/6b351c68-29dc-11e7-9977-c2710dac1357.png)
which is formed of three letters: ا then ل then م which is true ...... in picture above the font is Arial, but in some fonts the writing is a bit different, for the same case "the" and "m" will look like 
![irr](https://cloud.githubusercontent.com/assets/26926171/25390737/1027367a-29dd-11e7-977e-0a418855337e.png)
that font in the previous picture is traditional Arabic, so in this case the recognition will be as the following: ا then م then ل which technically is true, but actually is wrong because although the order is different between the two fonts " in writing" but but pronunciation should be the same, which the recognition in turn should be the same as well.
i couldn't know if that both shapes are defined in ara.traineddata or not because when i use the ara.traineddata against this [website](https://mazoea.com/te/traineddata/) it keeps failing in parsing.

anyways, i know its a tricky case, but any suggestion is very appreciated  :)

Thanks

**Comment by amitdo** [comment]
Just a general note. I don't think **most** users will be able to beat the official traineddata with their own traineddata. That's Relevant for most languages, including Arabic.

**Comment by amitdo** [comment]
When/where this form of Arabic writing, 'traditonal Arabic' is used?
How common is it?

**Comment by ibr123** [comment]
Hi amitdo, first of all thanks for your reply
for the first comment, i was using the official traineddata for Arabic, after i saw this [issue](https://github.com/tesseract-ocr/tesseract/issues/487) and actually i tried to detect an image with traineddata i made with the LSTM file i also create but seems they are not compatible according to the previous issue. i tried to follow the suggested steps, from compiling to training.

as for the second comment, the case i described isn't an exclusive case for the traditional Arabic font, its a method of writing that multiple fonts can follow, in the training i did, i used other fonts (from windows) that follows the same pattern for writing in the same was as i mentioned above and they are, Sakkal Majalla, Arabic Typesetting, to give you an example from English, you notice that the a letter, most of fonts write it like this 
![a2](https://cloud.githubusercontent.com/assets/26926171/25421363/3a479b7e-2a65-11e7-92f3-c48114c2b713.png)
but other fonts write the same letter like this:
![a1](https://cloud.githubusercontent.com/assets/26926171/25421388/51cbe6ec-2a65-11e7-949b-1e15fdf25d71.png)

since we are on this issue, there is also another case which tesseract recognize a letter before the next one, in both shapes as the following
![la1](https://cloud.githubusercontent.com/assets/26926171/25421426/8552bcb6-2a65-11e7-8a02-5138ff2c2c00.png)

![la2](https://cloud.githubusercontent.com/assets/26926171/25421428/8a6d76be-2a65-11e7-9c01-ee01ccc8e3a3.png)

that shape is two letters, and it sounds like "la" in "land", they should be recognized as ا then ل , but actually they are same as the case i described before which results in being recognized as: ل then ا 

again, its a tricky case, but i think any feedback with different language can make a big boost of the accuracy of the Tesseract engine

thanks a lot

**Comment by ibr123** [comment]
by the way i forgot to mention that i created ara.traineddata using jTessBoxEditor 1.6, which it uses tesseract 3.05.00dev and leptonica 1.73 ,if you run the traineddata file against the [website](https://mazoea.com/te/traineddata/) it shows that it detects the shapes that i mentioned earlier, look to the second shape it matches the first case, and the last two shapes match the second case i mentioned
just drag and drop the file


[ara.zip](https://github.com/tesseract-ocr/tesseract/files/957811/ara.zip)
to the blue rectangle at [this](https://mazoea.com/te/traineddata/)

**Comment by amitdo** [comment]
Are you trying to train 3.05 or the non-LSTM OCR engine in 4.00?
See the remark about Arabic.
https://github.com/tesseract-ocr/tesseract/wiki/Training-Tesseract#background-and-limitations

**Comment by amitdo** [comment]
[4.00 with lLSTM]
 ( لا ) vs ( ال ) is a known issue. See https://github.com/tesseract-ocr/tesseract/issues/648#issuecomment-285633162 and the comments below it.

**Comment by ibr123** [comment]
no I'm not training against 3.05 but its obvious that the traineddata file that is taken from GitHub (official traineddata) isn't readable by the website that i referred to earlier which shows you how the letters are drawn, so i made a small train on the 3.05 for testing purposes.
i only mentioned this thing (the 3.05 traineddata) to point that the characters in this issue can be detected in earlier models
i looked at the issue that you have sent, well, this case is similar to the case 
![irr](https://cloud.githubusercontent.com/assets/26926171/25433462/1b0f3c2c-2a91-11e7-9692-56230c2103aa.png)
see here technically the م precedes the ل  in terms of shape, but for reading or pronouncing the word, the ل precedes the م so you can say there is a swap in the writing "in some fonts", but in the case of لا the writing isn't swapped, it is ل then ا in both writing and pronouncing, but what i think happens is that tesseract detect the ل "in red"
![la3](https://cloud.githubusercontent.com/assets/26926171/25433732/1cf53072-2a92-11e7-8aa6-b2b5d605641a.png)
as an ا , and it detects the ا "in green"
![la4](https://cloud.githubusercontent.com/assets/26926171/25433786/4dffd7f8-2a92-11e7-9507-6aff20232174.png)

as an ل, which is the opposite to what it suppose to be, so what i humbly suggest is to make or add another character as a whole: which is the "لا"
keep in mind it sometimes the لا appears as the following:
![la1](https://cloud.githubusercontent.com/assets/26926171/25433878/bf98b132-2a92-11e7-8475-1cdfda4b3032.png)
 also i think this might work for the الم as well because it comes only in this position so make another character that looks like 
![irr](https://cloud.githubusercontent.com/assets/26926171/25433930/f0999f44-2a92-11e7-97c8-2b369ee55931.png)
i wish i explained my idea in a good way,
if you need any help in this issue, "in case you don't have a good background of the arabic language" maybe i can help :)
thanks

**Comment by ibr123** [comment]
seems this issue  of 

![](https://cloud.githubusercontent.com/assets/26926171/25433930/f0999f44-2a92-11e7-97c8-2b369ee55931.png) 
and 

![](https://cloud.githubusercontent.com/assets/26926171/25433878/bf98b132-2a92-11e7-8475-1cdfda4b3032.png)

is solved with the Tesseract: 4.00.00dev-690-g1b0379c and Leptonica: 1.74.4
