### ISSUE TITLE
not able to covert image to text using tesseract 

### ISSUE THREAD

**Issue by jayakumartest** [tesseract-ocr/tesseract#850]
Hi 
I am having hand typewritten image and trying to convert as text using tesseract  command , but it is giving output as plain text . what could be the problem?
tesseract.exe test.png out.txt
could you please help me.

Thanks
Jay,

**Comment by amitdo** [comment]
[A guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).
Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).
