### ISSUE TITLE
Update Doxygen documentation 

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#870]
https://tesseract-ocr.github.io/index.html 

was Generated on Mon Jul 20 2015 18:38:23 by  doxygen 1.8.8

Please update. Thanks!

**Comment by Shreeshrii** [comment]
Documentation of tesseract generated from source code by insight.io can be found at https://www.insight.io/github.com/tesseract-ocr/tesseract

Both of these are linked from 
https://github.com/tesseract-ocr/tesseract/wiki/Documentation

**Comment by Shreeshrii** [comment]
If https://www.insight.io/github.com/tesseract-ocr/tesseract
provided the same functionality as Doxygen, then this issue can be closed.

**Comment by stweil** [comment]
Up to now, Insight.io only shows the files with syntax highlighting. I got an error message that code analysis failed for my projects.

**Comment by Shreeshrii** [comment]
Could a travis script such as this be used to automatically update doxygen documentation?

https://github.com/miloyip/rapidjson/blob/master/travis-doxygen.sh

**Comment by stweil** [comment]
I have sent a [pull request](https://github.com/tesseract-ocr/tesseract-ocr.github.io/pull/1) which updates the documentation. It is possible to automatically update that documentation, but that would add a new revision for each change of the master branch. Maybe it is sufficient to update the documentation each time a release is tagged.

**Comment by Shreeshrii** [comment]
Thanks, @stweil . I have added to documentation page on wiki.

> New documentation is also visible here.

Is that as of master branch on May 20th or relative to some tag?

**Comment by stweil** [comment]
It's based on the latest git master branch.

**Comment by Shreeshrii** [comment]
Thanks!

**Comment by chongzhe** [comment]
@stweil Hi, insight.io creator here, tesseract-ocr should work fine on insight.io with full code intelligence not just syntax highlighting. Would you mind shooting an email to chongzhe@insight.io with regarding to the errors you see, we will help you solve the issue:)

Thanks!
