### ISSUE TITLE
[3.04.1] segfault at 400000000 ip 00007f7604b1fca0 sp 00007fff1e25b7f0 error 4 in libtesseract.so.3.0.4[7f76048b1000+334000]

### ISSUE THREAD

**Issue by vfuyong** [tesseract-ocr/tesseract#872]
We are an enterprise utilizing tesseract for years, and we recently upgraded to 3.04.1 successfully by compiling from source code. When running the command below, segmentation fault is received from Ubuntu 10.04.4 (code 139). 

Does anyone have ideas as why this might occur? Thanks heaps. 
tesseract -psm 1 -l eng /var/opt/app/main.jpg /var/opt/app/main_1 characters hocr

**Comment by zdenop** [comment]
Current stable release is 3.05. Soon will (within week) be released 3.05.1 version with more bugfixes....
