### ISSUE TITLE
tessedit.cpp Error

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#873]
Hi,
I'm using tesseract 4.00alpha with leptonica 1.74.1 on Ubuntu 14.04, first i was training on the a VirtualBox and i was able to create LSTMF files, but now i use the same tesseract, lepptonica and Ubutnu versions on a different machine (VMware) and i couldn't create LMSTF files, and i compiled the tesseract in both cases the same, according to this [website](https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32) ,I'm pasting part of log file that is created at tmp file......
=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=./tessdata
[Thu May 4 00:52:11 PDT 2017] /usr/local/bin/tesseract /tmp/tmp.vDN2ALtI8c/ara/ara.Arabic_Typesetting.exp0.tif /tmp/tmp.vDN2ALtI8c/ara/ara.Arabic_Typesetting.exp0 lstm.train ../langdata/ara/ara.config
Info in bmfCreate: Generating pixa of bitmap fonts from string
lstm_recognizer_->DeSerialize(tessdata_manager.swap(), &fp):Error:Assert failed:in file tessedit.cpp, line 202
ERROR: /tmp/tmp.vDN2ALtI8c/ara/ara.Arabic_Typesetting.exp0.lstmf does not exist or is not readable

keep in mind i copied the tessedit from the working version of tesseract and replaced it at the new machine but the same error occurred

Thanks

**Comment by ibr123** [comment]
UPDATE :-
i have installed the tesseract again today and the same error was generated but the only difference that the line number has changed

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=./tessdata
[Thu May 4 04:43:32 PDT 2017] /usr/local/bin/tesseract /tmp/tmp.RwajXhdHOo/ara/ara.Arabic_Typesetting.exp0.tif /tmp/tmp.RwajXhdHOo/ara/ara.Arabic_Typesetting.exp0 lstm.train /home/ibr/Desktop/Tesseract4/langdata/ara/ara.config
Info in bmfCreate: Generating pixa of bitmap fonts from string
lstm_recognizer_->DeSerialize(&fp):Error:Assert failed:in file tessedit.cpp, line 193
ERROR: /tmp/tmp.RwajXhdHOo/ara/ara.Arabic_Typesetting.exp0.lstmf does not exist or is not readable

**Comment by Shreeshrii** [comment]
Error message Info in bmfCreate: Generating pixa of bitmap fonts is similar to issue https://github.com/tesseract-ocr/tesseract/issues/893

That error/info message is from Leptonica

https://github.com/cotdp/leptonica/blob/master/src/bmf.c

**Comment by amitdo** [comment]
>Info in bmfCreate: Generating pixa of bitmap fonts from string

It just info message, not an error message.

The two issues does not seem related to each other.

**Comment by ibr123** [comment]
as i understood from the issue 893, that guy is facing a trouble with building the tesseract with liptonica, but i built it fine and I'm even capable to detect text from images, if you can see in the log message when I'm using the tesstrain.sh i'm able yo create the data that is stored in the tmp file, my problem is in the last phase which is generating lstm files.
keep in mind that i have installed and complied the tesseract 4alpha and leptonica 1.74.1 twice, within month in between i guess, the first one works fine and I'm able to create the lstmf files, but in the second i can't amd i followed the same steps in both cases
Thanks

**Comment by Shreeshrii** [comment]
@amitdo is right. It is unrelated. Sorry for the confusion.

@ibr123 It is possible that the source for the two installs is from different commits from master.

**Comment by ibr123** [comment]
Hi Shree,

i was thinking the same thing, its just i always follow the steps and links to install and compile from this [site](https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32)
so is there a way currently to solve this issue? cause i might need to install the tesseract on a server because all the work i did already on a VMware for testing purposes

**Comment by Shreeshrii** [comment]
You are getting tesseract source by

`git clone https://github.com/tesseract-ocr/tesseract.git`

As you can see from https://github.com/tesseract-ocr/tesseract/commits/master
there have been many changes to 4.0 code over last one month.

What you could do is note the commit number from an install which works for you, and then use source as of that commit for your installation. Please note that 4.0 code is still in alpha stage and may change quickly.

config.log should show you the commit - search for GIT-REV

```
| #define GIT_REV "4.00.00alpha-458-g2ea946d"
```

**Comment by ibr123** [comment]
Hi,

i looked at the config.log of the tesseract revision that works, took the revision  number  and switched the tesseract to that branch while installing the tesseract, and that revision was **"4.00.00alpha-367-g5baa8c8"**
i made sure that its the correct revision by making detection of an image, i noticed that on the terminal the tesseract prints its revision number
![ocrerror](https://cloud.githubusercontent.com/assets/26926171/25889397/49639c4e-3572-11e7-909e-5c7fcf8eab3c.png)
yet the same error was generated at the phase E where creating lstm files
i even tried to install the suggested revision: **"4.00.00alpha-458-g2ea946d"** and the result was the same error but different line number at the tessedit.cpp, at the revision  **"4.00.00alpha-367-g5baa8c8"** the error is: **stm_recognizer_->DeSerialize(&fp):Error:Assert failed:in file tessedit.cpp, line 202**
and at the revision **"4.00.00alpha-458-g2ea946d"** the error was
**stm_recognizer_->DeSerialize(&fp):Error:Assert failed:in file tessedit.cpp, line 193**
i even deleted that line from the tessedit.cpp and the error stayed the same, after that i tried to delete the whole tessedit.cpp and same problem, so is it loaded on somewhere ? or is it not compatible with VMware because the revision **"4.00.00alpha-367-g5baa8c8"** works fine with the virtual box but not with the VMware 
Thanks

**Comment by Shreeshrii** [comment]
Sorry, I do not know enough about VMware and Virtual Box to identify the
problem.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by ibr123** [comment]
@Shreeshrii 
no worries :) i mentioned the virtual box and the VMware just in case, i just like to share the details in case they were any help, i dont know either if its virtual box or VMware, the interesting point that in both cases or in both revisions the same line of code failed 
thanks for the response

**Comment by Shreeshrii** [comment]
@ibr123 I am able to run training with the following version -

 tesseract -v
tesseract 4.00.00alpha-460-gb86b4fa
 leptonica-1.74.1
  libgif 5.0.5 : libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.0 : libopenjp2 2.1.0

Please try with this commit. If it doesn't work, share your input files/font.

**Comment by Shreeshrii** [comment]
```

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=../tessdata
[Thu May 11 13:55:50 DST 2017] /usr/local/bin/tesseract /tmp/tmp.D3w1Zt6gOu/ara/ara.Arabic_Typesetting.exp0.tif /tmp/tmp.D3w1Zt6gOu/ara/ara.Arabic_Typesetting.exp0 lstm.
train ../langdata/ara/ara.config
Tesseract Open Source OCR Engine v4.00.00alpha-460-gb86b4fa with Leptonica
Page 1
Page 2
Loaded 56/56 pages (1-56) of document /tmp/tmp.D3w1Zt6gOu/ara/ara.Arabic_Typesetting.exp0.lstmf
Page 3
Loaded 117/117 pages (1-117) of document /tmp/tmp.D3w1Zt6gOu/ara/ara.Arabic_Typesetting.exp0.lstmf

```

**Comment by ibr123** [comment]
@Shreeshrii are the libraries and leptonica version at this [site](https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32) are valid? meaning did you install them with the tesseract v4.00.00alpha-460-gb86b4fa ?

**Comment by Shreeshrii** [comment]
When you use

git clone https://github.com/tesseract-ocr/tesseract.git

It will pickup the latest version of source from GitHub. Later, you can
update by

Git pull origin

Or do a new clone of the repository.

If you configure with --enable-debug it will show the git revision for

tesseract -v

**Comment by ibr123** [comment]
Finally I'm able to create LSTM files, without switching to any other branches, the version of the tesseract is in the image below
![lstm](https://user-images.githubusercontent.com/26926171/27028983-3370d0e8-4f6f-11e7-9377-60158f0c11a8.png)

**Comment by GitHub30** [comment]
I solved. if you run on Ubuntu, `apt-get update && apt-get -y upgrade`.
