### ISSUE TITLE
Tesseract master branch-Build Issue

### ISSUE THREAD

**Issue by varun1994varun** [tesseract-ocr/tesseract#876]
Hi,I want to build the Tesseract using the master branch.
I followed the steps as you mentioned.
But when I enter **cmake ..** I am getting the following error.
Help me on this.
Thank you

C:\Users\Varun\Desktop\New folder\tesseract-master\Win64>cmake ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:47 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:47 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Varun/Desktop/New folder/tesseract-master/Win64/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Varun/Desktop/New folder/tesseract-master/Win64/CMakeFiles/CMakeError.log".

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support
