### ISSUE TITLE
Must supply a list of training filenames! --train_listfile

### ISSUE THREAD

**Issue by liuxia2016** [tesseract-ocr/tesseract#879]
Hello all,

I  lstmtraining chi_sim, but have the error "Must supply a list of training filenames! --train_listfile".
The context is "./cntrain/chi_sim.SimSun.exp0.lstmf" in my chi_sim.training_files.txt. Please give me a help!

lstmtraining -U ./cntrain/chi_sim.unicharset \
--script_dir ./langdata \
--debug_interval 100 \
--continue_from ./cnoutput/chi_sim.lstm \
--append_index 5 –net_spec '[1,0,0,1 Ct5,5,16 Mp3,3 Lfys64 Lfx128 Lrx128 Lfx384 O1c1]' \
--learning_rate 10e-5 \
--net_mode 192 \
--perfect_sample_delay 19 \
--max_iterations 10000 \
--model_output ./cnoutput/base  --max_image_MB 600 \
--train_listfile ./cntrain/chi_sim.training_files.txt  \
--eval_listfile ./cntrain/chi_sim.training_files.txt &>./cnoutput/basetrain.log

**Comment by Shreeshrii** [comment]
on what operating system are you trying this?

what commit number for source code are you using?

**Comment by Shreeshrii** [comment]
You have used the complete net_spec. With append_index, it has to be just the top layers, eg.

```
lstmtraining -U ~/tesstutorial/ara/ara.unicharset \
  --script_dir ../langdata   \
  --append_index 5 --net_spec '[Lfx256 O1c105]' \
  --continue_from ~/tesstutorial/aralayer_from_ara/ara.lstm \
  --model_output ~/tesstutorial/aralayer_from_ara/aralayer \
  --train_listfile ~/tesstutorial/ara/ara.training_files.txt \
  --target_error_rate 0.01 \
  --debug_interval  -1
```

**Comment by liuxia2016** [comment]
Thank you for your help. I solved it by removing "--append_index 5"

**Comment by Shreeshrii** [comment]
Please close the issue if problem is resolved.

**Comment by Shreeshrii** [comment]
@zdenop  Issue can be closed.
