### ISSUE TITLE
Getting "Error: Illegal sample size!" when using custom language

### ISSUE THREAD

**Issue by victorjonsson** [tesseract-ocr/tesseract#88]
Hello there!

I have done some training and created my own combined language file. When using my custom language I get error code 5000

````
$ tesseract waa.whatevva.exp0.tif out -l waa

Error: Illegal sample size!
signal_termination_handler:Error:Signal_termination_handler called:Code 5000
Abort trap: 6
````

When I ran `combine_tessdata`I got the following output

```
Combining tessdata files
TessdataManager combined tesseract data files.
Offset for type 0 is 140
Offset for type 1 is 141
Offset for type 2 is -1
Offset for type 3 is 2214
Offset for type 4 is 299822
Offset for type 5 is 300066
Offset for type 6 is -1
Offset for type 7 is -1
Offset for type 8 is -1
Offset for type 9 is -1
Offset for type 10 is -1
Offset for type 11 is -1
Offset for type 12 is -1
Offset for type 13 is 300067
Offset for type 14 is -1
Offset for type 15 is -1
Offset for type 16 is -1
```

Anybody having an idea of what I'm doing wrong?

**Comment by zdenop** [comment]
I am sorry but we do not provide for custom training.
Try to use forum for help/support. But please make sure you use the latest tesseract code and provide more information (tesseract version, locale settings, how you did training, link to data used for training, waa.traineddata....)
