### ISSUE TITLE
Installation deletes (overwrites?) part of the PATH, WINDOWS

### ISSUE THREAD

**Issue by miguelalche** [tesseract-ocr/tesseract#882]
Hey friends! 
First thanks for mantaining this open source project. 

However I must tell you that when I Installed this and clicked on Add to Path and Set TESSDATA_PREFIX variable almost everything I had on the path stopped working.
very similar to what happened to this guy here: 
https://stackoverflow.com/questions/43014724/how-to-reset-system-variable-path-after-tesseract-installation

I've tried the solution proposed, but unluckily windows didn't make the shadow copies of my old PATH.

So now I'm here trying to piece toghether again my path...

**Comment by stweil** [comment]
That's why there is a [hint](https://github.com/UB-Mannheim/tesseract/wiki) which suggests not to use that option.

**Comment by miguelalche** [comment]
Hi Stweil, thanks for answering so fast! 
I completely missed that... guess it's my fault.

But just for a heads up I installed the 3.05.00dev version which I understand is the latest one that is stable. 
and the problem of the path happened anyways, so it's not on older versions of the installer (I understand that since 4 is experimental, version 3 isn't "old", correct me if I am)

**Comment by Shreeshrii** [comment]
@zdenop  Issue can be closed.

**Comment by Shreeshrii** [comment]
@stweil Please update the windows binaries on your site with the latest version. Please also check that lstm.train config file is being included. (saw an error on another issue related to missing lstm.train - not sure which package it was from). Thanks!

**Comment by stweil** [comment]
> Please update the windows binaries on your site with the latest version.

Done now for both Tesseract 3.05 and Tesseract 4.

**Comment by Shreeshrii** [comment]
Thanks, Stefan!
