### ISSUE TITLE
api->getutf8text() return unknown encoding result with -l fas

### ISSUE THREAD

**Issue by Nigje** [tesseract-ocr/tesseract#895]
I am using tesseract api for persian language. when i call api->getutf8text(), that return unknown encoding string.

        char*outText = api->GetUTF8Text();
	String^ result = gcnew String(outText);

for example result is 

Ø§Ø¨Ø±Ø§Ø² Ø¯Ø§Ø´Øª: Ø§Ù…Ø§Ù… Ø±Ø¶Ø§ Ø¨Ø±Ø®Ø§Ù„Ù Ø¯ÛŒÚ¯Ø± Ø§Ø¦Ù…Ù‡ Ø¨Ø§ Ø¬Ù†Ú¯ Ù†Ø±Ù…

also i know fas.traineddata and result are ISO 639-2T but i don't known how tesseract convert utf-8 to ISO-639-2T .

when i am using tesseract.exe in cmd
tesseract.exe  test.tiff  outputFile  -l fas
The result is stored properly in outputFile.txt

**Comment by amitdo** [comment]
[A guide for reporting issues](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).
Please use the [forum](https://groups.google.com/d/forum/tesseract-ocr).
