### ISSUE TITLE
Tesseract couldn't load any languages

### ISSUE THREAD

**Issue by aubryll** [tesseract-ocr/tesseract#901]
I never used a library as complicated as this one, I use Linux Java. Well I manage to make tess4j work, then copied all the source packages and libraries into my project, everything seemed fine but when I try running it I get the errors 
`Info in bmfCreate: Generating pixa of bitmap fonts from string
Error opening data file ./eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7d7f292197, pid=24436, tid=0x00007f7db9f03700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.so+0xc3197]  tesseract::Tesseract::recog_all_words(PAGE_RES*, ETEXT_DESC*, TBOX const*, char const*, int)+0x5e7
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/big-daddy/netbeansprojects/LicencePlateRecognition/hs_err_pid24436.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#`

What I dont understand is why does Tess4j default project manage to load the language files whilst mine fails?

**Comment by Shreeshrii** [comment]
> Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.

Please set this variable for tesseract to find the traineddata files.

**Comment by aubryll** [comment]
It is set that's why the tess4j works in its default package before
importing it into my project
On May 11, 2017 10:04 AM, "Shreeshrii" <notifications@github.com> wrote:
>>
>> Please make sure the TESSDATA_PREFIX environment variable is set to your
"tessdata" directory.

**Comment by zdenop** [comment]
We do not provide support for 3rd party project (Tess4j). Please consult issue at Tess4j authors.
