### ISSUE TITLE
Tesseract-OCR is unable to find text in SOME images

### ISSUE THREAD

**Issue by AzkaGilani** [tesseract-ocr/tesseract#902]
Hey, i have been using tesseract for text extraction from images. But due to some unknown reasons, it is unable to extract text from some images even if the image is clean. I am unable to find the reason for this. Is there anything that i am missing in preprocessing?
original image:
![depot](https://cloud.githubusercontent.com/assets/20331292/25936270/625951fc-3640-11e7-9542-32636ed6126e.jpg)
Binarized image:
![depot 1 jpg-binarized](https://cloud.githubusercontent.com/assets/20331292/25936398/fbb85e7e-3640-11e7-86b5-e811f5593e0b.png)

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support.
