### ISSUE TITLE
Extra space added in text output

### ISSUE THREAD

**Issue by 17nikhil** [tesseract-ocr/tesseract#923]
The output text file contained a space between characters while there was no space between the characters in the image.
![test](https://cloud.githubusercontent.com/assets/25953522/26097345/e807f4de-3a41-11e7-8179-44a9782d3419.JPG)
[out.txt](https://github.com/tesseract-ocr/tesseract/files/1003713/out.txt)

**Comment by mm-manu** [comment]
Same problem here. I've tried different parameters related to spaces with no success. They seem not to work in Tesseract 4.0 :/
e.g. 
tosp_table_xht_sp_ratio	0.33	Expect spaces bigger than this
tosp_min_sane_kn_sp	1.5	Don't trust spaces less than this time kn
textord_spacesize_ratiofp	2.8	Min ratio space/nonspace
textord_spacesize_ratioprop	2	Min ratio space/nonspace

**Comment by emilfihlman** [comment]
Experiencing the same issue: tesseract is adding spaces between every letter making search unusable.

**Comment by Shreeshrii** [comment]
set the config variable - "preserve_interword_spaces" to 1

Please see if the above fixes the issue for you. 

Ref: https://github.com/tesseract-ocr/tesseract/issues/1009

**Comment by emilfihlman** [comment]
My issue apparently is with ghostscript mangling the text (tesseract produces badly sized pdfs and there is no option to specify output size). Sorry for the false flag.

**Comment by zdenop** [comment]
Seems to be working in current code:
```
>tesseract i923.JPG -
Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 474
ESTA67
ES767
UNA4567
PRUEBAS887
```
