### ISSUE TITLE
Unicharset --- |Broken|0|1 

### ISSUE THREAD

**Issue by Anida-qin** [tesseract-ocr/tesseract#931]
#318 
I followed the solution #318 pulled before. 
And after i ran 
`set_unicharset_properties -U unicharset -O new_unicharset --script_dir=/home/qs/Downloads/langdata`
It shows like this
Loaded unicharset of size 29 from file unicharset
Setting unichar properties
Other case c of C is not in unicharset
Other case f of F is not in unicharset
Other case K of k is not in unicharset
Other case a of A is not in unicharset
Other case l of L is not in unicharset
Other case y of Y is not in unicharset
Other case s of S is not in unicharset
Other case m of M is not in unicharset
Other case i of I is not in unicharset
Other case e of E is not in unicharset
Other case t of T is not in unicharset
Other case w of W is not in unicharset
Other case n of N is not in unicharset
Other case o of O is not in unicharset
Writing unicharset to file new_unicharset

Seems correct, but the contents in new_unicharset is 

29
NULL 0 NULL 0
Joined 7 0,69,188,255,486,1218,0,30,486,1188 Latin 1 0 1 Joined	# Joined [4a 6f 69 6e 65 64 ]a
|Broken|0|1 f 0,69,186,255,892,2138,0,80,892,2058 Common 2 10 2 |Broken|0|1	# Broken
9 8 0,66,200,255,89,156,0,39,104,173 Common 3 2 3 9	# 9 [39 ]0
7 8 12,68,196,255,72,160,0,60,75,173 Common 4 2 4 7	# 7 [37 ]0
1 8 49,69,192,255,45,128,0,66,74,173 Common 5 2 5 1	# 1 [31 ]0
2 8 30,69,194,255,80,160,0,27,97,173 Common 6 2 6 2	# 2 [32 ]0
6 8 58,66,219,255,87,156,0,54,104,173 Common 7 2 7 6	# 6 [36 ]0
/ 10 0,65,219,255,59,228,0,36,62,238 Common 8 6 8 /	# / [2f ]p
3 8 0,66,196,255,84,158,0,32,103,173 Common 9 2 9 3	# 3 [33 ]0
C 5 58,65,219,255,87,192,0,32,107,209 Latin 10 0 10 C	# C [43 ]A
F 5 57,68,216,255,68,210,0,31,77,209 Latin 11 0 11 F	# F [46 ]A
k 3 57,68,216,255,85,177,0,35,93,198 Latin 12 0 12 k	# k [6b ]a
A 5 52,68,216,255,100,216,0,17,98,231 Latin 13 0 13 A	# A [41 ]A
5 8 12,66,199,255,82,160,0,36,103,173 Common 14 2 14 5	# 5 [35 ]0
4 8 0,68,198,255,93,161,0,41,96,173 Common 15 2 15 4	# 4 [34 ]0
L 5 59,68,216,255,64,193,0,31,74,206 Latin 16 0 16 L	# L [4c ]A
Y 5 59,68,216,255,91,205,0,47,91,223 Latin 17 0 17 Y	# Y [59 ]A
8 8 57,66,219,255,88,162,0,41,103,174 Common 18 2 18 8	# 8 [38 ]0
S 5 57,64,219,255,87,174,0,30,100,200 Latin 19 0 19 S	# S [53 ]A
M 5 57,68,216,255,99,301,0,35,117,286 Latin 20 0 20 M	# M [4d ]A
I 5 59,68,216,255,10,155,0,50,29,173 Latin 21 0 21 I	# I [49 ]A
E 5 59,68,216,255,68,210,0,31,80,219 Latin 22 0 22 E	# E [45 ]A
T 5 59,68,216,255,85,227,0,47,88,236 Latin 23 0 23 T	# T [54 ]A
W 5 54,68,216,255,106,314,0,41,117,318 Latin 24 0 24 W	# W [57 ]A
0 8 58,66,187,255,88,164,0,45,103,180 Common 25 2 25 0	# 0 [30 ]0
N 5 59,68,216,255,87,262,0,27,104,249 Latin 26 0 26 N	# N [4e ]A
O 5 57,64,219,255,91,209,0,34,106,233 Latin 27 0 27 O	# O [4f ]A
\ 10 0,67,219,255,28,250,0,71,62,261 Common 28 10 28 \	# \ [5c ]p

And i do anything successfully and finally i got traindata. But here is a problem now. There is no output when i used the traindata to test the image. I think there is maybe something wrong with unicharset. 
Could anyone help?

**Comment by Anida-qin** [comment]
Here are my train data
box
[http://pan.baidu.com/s/1hsA8U4O](url)
image
[http://pan.baidu.com/s/1pLHgoQn](url)

**Comment by Brian51** [comment]
Hi Anida.qin, Your links return page 404 page error?

**Comment by Shreeshrii** [comment]
If you copy the url and paste, it works. It is a page in chinese (i think).

**Comment by Brian51** [comment]
Thanks that worked.

**Comment by Anida-qin** [comment]
Sorry to reply late. I solve the problem now. Maybe I did something wrong when do the command box.train  . It goes with the invalid .tr file. But there is also broken line there, but finally i found it can be ignored if you only have few CreateInt() lines when use command mftraining. So i closed this issue.
