### ISSUE TITLE
tessesract hasn't been released to the ubuntu store

### ISSUE THREAD

**Issue by elopio** [tesseract-ocr/tesseract#938]
Hello!

In #700 we added the packaging to release tesseract to the snaps store. But it hasn't been published there yet. Now we have a very cool new service that can help you doing that, and will take care of the continuous delivery for you.

Please take a look at https://build.snapcraft.io/
After logging in there with your github account, you can tell it to make a new release to the unstable channel in the store every time that your master branch changes. Then your latest changes will be available to all the ubuntu users out there with no effort.

We are in beta, so I would appreciate any comments about your experience using the service.

pura vida.

**Comment by zdenop** [comment]
This is not tesseract problem. We will not release tesseract outside of github.

**Comment by elopio** [comment]
@zdenop oh, that's sad. But I understand.
The work of automating the continuous delivery is very simple, so would you mind if I set up a mirror that keeps tesseract in the Ubuntu store updated after every change in your repo?

**Comment by zdenop** [comment]
Yes you can do it. 
This is the way how binary version of tesseract is distributed: volunteers (responsible for fixing distribution/packaging) create packages and put them to distribution channel of their choice.

**Comment by elopio** [comment]
I think that the maintainers are unnecessary intermediaries if we design good tools to automate the delivery, and safe and isolated packages so upstream developers can't break users' machines. We are working towards that, and if we do it right, at some point in the future you might like me to transfer the ownership in the store to you. We will see :)

Now this aligns nicely with a few things I have to test constantly, so happy to maintain it. I'll keep you posted about stats, feedback and such. If you need something snap or ubuntu related, just ping me.

pura vida.
