### ISSUE TITLE
Kurdish trained data is a mix of dialects & alphabets

### ISSUE THREAD

**Issue by brandones** [tesseract-ocr/tesseract#939]
I had very limited success doing OCR in Kurdish using the trained data. I think this is because it was trained on a mix of Kurmanji (the largest dialect, written in a Latin alphabet with a few circumflexes) and Sorani (the second-largest dialect, written in a modified Persian alphabet) sources. It keeps wanting to find Arabic/Persian characters in my Kurmanji documents. I imagine that splitting the training data by alphabet (say, into Kurdish-Kurmanji and Kurdish-Sorani) would improve the OCR quality dramatically.

Please let me know if there's any way I can contribute to the Kurdish transcription quality.

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support

**Comment by Shreeshrii** [comment]
Tesseract langdata has two languages for kurdish

https://github.com/tesseract-ocr/langdata/tree/master/kur
https://github.com/tesseract-ocr/langdata/tree/master/kur_ara

Please review the training text, wordlist etc there and if there is a mix in those files, please file a issue under langdata. Thanks.
