### ISSUE TITLE
How to upgrade tesseract?

### ISSUE THREAD

**Issue by tengerye** [tesseract-ocr/tesseract#944]
I installed the tesseract through pip install. The latest version of it is 3.04.01. When I tried to compile my C++ code, it has errors with libtiff. Since the 3.05 version has abandoned such dependency, I am wondering if there is a way to upgrade my tesseract, AND AT THE SAME TIME, I can write both C++ and Python code on that. Thank you so much in advance.

**Comment by zdenop** [comment]
We do not support 3rd party project. Please use tesseract user forum.
