### ISSUE TITLE
Need of Cube traineddata files for other languages like por, spa, etc.,

### ISSUE THREAD

**Issue by MerlinArul** [tesseract-ocr/tesseract#946]
Hi ,

Anyone please help me in finding / Creating lang.cube.* files for all the other languages in tessdata folder. like eng language has. Please help me out in training data for cube. Or anyone already have those cube files please share with me.

Thanks and Regards,
Merlin

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support.

**Comment by MerlinArul** [comment]
can i know the forum insite details

**Comment by stweil** [comment]
See https://github.com/tesseract-ocr/tesseract/wiki#support.
