### ISSUE TITLE
Assertion fails in remove_unichar_ids when tilde-crunching.

### ISSUE THREAD

**Issue by nullpointersetc** [tesseract-ocr/tesseract#948]
Hi, everyone. We're getting an assertion failure in remove_unichar_ids on some pages, and it has to do with "unlv_tilde_crunching" (I admit that I don't know what this is).  Apparently it has something to do with merging blobs when there is only one blob.

```C++
void WERD_CHOICE::remove_unichar_ids(int start, int num) {
  ASSERT_HOST(start >= 0 && start + num <= length_);
  ...
```
* This assertion fails with start==1 and num==1 but length_==1.
* remove_unichar_ids is being called by WERD_RES::MergeAdjacentBlobs, which is being called by Tesseract::write_results.
* Because the call is made only when unlv_tilde_crunching is true, we're working around it by setting it to false.
* Tesseract: 3.04.01, compiled in Visual Studio 2010.
* Operating System: Windows 10 Pro 1511, 16 GB RAM

**Comment by amitdo** [comment]
'unlv_tilde_crunching' is related to a feature nobody uses.

AFAIK, Setting it to 'false' has no negative effect on the OCR accuracy.

**Comment by amitdo** [comment]
If you want to learn more about this feature, see this old paper.

The ISRI Analytic Tools for OCR Evaluation - Semantic Scholar
https://pdfs.semanticscholar.org/dc3e/f1e05b4b629de5db721efb156d82556ff362.pdf

Search for 'tilde'.

**Comment by nullpointersetc** [comment]
Thanks! We'll go with "no crunching".
