### ISSUE TITLE
How do I convert data from version 3.02 to 3.05?

### ISSUE THREAD

**Issue by androdro** [tesseract-ocr/tesseract#950]
I've been creating Tesseract 3.02 application uses Visual Studio and already train and have tesseract data for 3.02. Now my company want me to develop on android which I'm using rmtheis TessTwo API which uses Tesseract version 3.05. So how can I convert my 3.02 data to 3.05? Or is it 3.02 can be used on 3.05 without need to change (though I believe this i not true)?
Please help thank you

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support
