### ISSUE TITLE
how to get include and lib without Compilation?

### ISSUE THREAD

**Issue by weituotian** [tesseract-ocr/tesseract#955]
for some reason, the network in my country is very bad!!

so i want to use the lib and dll directly.
and finally i found no where to download it?

compile it is so hard for me, is there a solution?

**Comment by Shreeshrii** [comment]
you can get the latest appveyor build artifacts from

win32

https://ci.appveyor.com/project/zdenop/tesseract/build/master.993/job/c8rtk21uqliscckn/artifacts

win64

https://ci.appveyor.com/project/zdenop/tesseract/build/master.993/job/c6uplulmcrk7bew8/artifacts

**Comment by semanser** [comment]
@Shreeshrii Thanks for the links! How can I use this build in my QT C++ project?

**Comment by weituotian** [comment]
@Shreeshrii 
thanks for you help.
i try download it, but i can not find any .lib file there.

i perfer files below

1. libtesseract304d.lib
1. giflib416-static-mtdll-debug.lib
1. giflib416-static-mtdll-debug.lib
1. giflib416-static-mtdll.lib
1. giflib416-static-mtdll.lib
1. libjpeg8c-static-mtdll-debug.lib
1. libjpeg8c-static-mtdll-debug.lib
1. libjpeg8c-static-mtdll.lib
1. libjpeg8c-static-mtdll.lib
1. liblept171-static-mtdll-debug.lib
1. liblept171-static-mtdll-debug.lib
1. liblept171-static-mtdll.lib
1. liblept171-static-mtdll.lib
1. liblept171.lib
1. liblept171.lib
1. liblept171d.lib
1. liblept171d.lib
1. libpng143-static-mtdll-debug.lib
1. libpng143-static-mtdll-debug.lib
1. libpng143-static-mtdll.lib
1. libpng143-static-mtdll.lib
1. libtiff394-static-mtdll-debug.lib
1. libtiff394-static-mtdll-debug.lib
1. libtiff394-static-mtdll.lib
1. libtiff394-static-mtdll.lib
1. zlib128-static-mtdll-debug.lib
1. zlib128-static-mtdll-debug.lib
1. zlib128-static-mtdll.lib
1. zlib128-static-mtdll.lib

**Comment by zdenop** [comment]
@weituotian: we provide source code only - e.g. we do not produce and distribute windows libraries (with header files), that you can use in your project.

**Comment by weituotian** [comment]
@zdenop and you know where to get what we want?

**Comment by stweil** [comment]
@weituotian, get the code and compile it yourself. You won't save much network bandwidth if you could get libraries.

**Comment by zdenop** [comment]
@weituotian. you can try to ask on tesseract user forum.
