### ISSUE TITLE
Accuracy for Nepali Language is Low in some text

### ISSUE THREAD

**Issue by nirajan-pant** [tesseract-ocr/tesseract#958]
The accuracy of Nepali trainned data is low is some documents. Whole line is recognized as a single word and recognized text seems to be just a string of random character. Here is sample -  

Original Image:
![tess_recog_nep](https://cloud.githubusercontent.com/assets/10336295/26553903/679ae88a-44ad-11e7-9402-f81e6714d386.png)

Recognized Text:
हसेरै बिदा गर्छु भन्थे तिमीलाई
तरमक्कानर्क्सट्टेरासर्यो||
रोक्कभ-शेयीमनश्रित्रमडारिएकाबादललाईं
तरआशबनीबर्सिक्विरै||

Real Text:
हसेरै बिदा गर्छु भन्थे तिमीलाई
तर मुस्कान कतै डेरा सर्यो ||
रोक्छु भन्थे यी मनभित्र मडारिएका बादललाई
तर आशु बनी बर्सिदियो ||

**Comment by Shreeshrii** [comment]
which traineddata file did u use?

**Comment by nirajan-pant** [comment]
I have used - https://github.com/tesseract-ocr/tessdata/blob/master/nep.traineddata

**Comment by Shreeshrii** [comment]
Did you use `--oem 1` to use the LSTM engine and LSTM laanguage model?

I get the following output 

```
हसेरै बिदा गर्छु भन्थे तिमीलाई

तर मुस्कान कतै डेरा सर्यो ||

रोक्छु भन्थे यी मनभित्र मारिएका बादललाई
तर आशु बनी बर्सिदियो ||
```
command used was:

tesseract nep.png nep -l nep --oem 1 --psm 6 --tessdata-dir ../tessdata

**Comment by nirajan-pant** [comment]
Thank you very much. LSTM only mode (--oem 1) perform better than Tesseract + LSTM (--oem 2) mode.

**Comment by Shreeshrii** [comment]
Please close the issue.
