### ISSUE TITLE
Did you use UW3 dataset during training?

### ISSUE THREAD

**Issue by vaasily** [tesseract-ocr/tesseract#959]
Hi Ray,

I'm going to compare different OCR engines on University of Washington (UW3) dataset.

Did you use the UW3 dataset during training your LSTM model? If so, the comparison will be useless.

Thanks.

**Comment by amitdo** [comment]
>Did you use the UW3 dataset during training your LSTM model?

I'm not Ray, but AFAIK the answer is NO.

What are the other OCR engines in your comparison?

**Comment by vaasily** [comment]
Hi Amit,

Thanks for the answer.

I'm going to compare the following OCR engines:
1) Tesseract 4
2) Tesseract 3
3) ABBYY Cloud OCR SDK
4) Microsoft Computer Vision API
5) Google Cloud Vision API

**Comment by Shreeshrii** [comment]
Tesseract 3 has different versions and the accuracy and performance differs
in those too.

See https://groups.google.com/forum/#!topic/tesseract-dev/LErriuT-sck

for posts regarding Tesseract performance and accuracy across versions 2.04
- 3.04.01

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment]
@vaasily, what were the results of your comparison?

**Comment by amitdo** [comment]
@zdenop, please close this issue.

**Comment by chixma** [comment]
> Hi Ray,
> 
> I'm going to compare different OCR engines on University of Washington (UW3) dataset.
> 
> Did you use the UW3 dataset during training your LSTM model? If so, the comparison will be useless.
> 
> Thanks.

Could you please tell me how to download the UW-3 dataset? I failed to find it on the Internet.

**Comment by lynx97** [comment]
@chixma  I also do not find UW-3 dataset on the internet.
