### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [tesseract-ocr/tesseract#96]
I would like to point out that identifiers like "[`TESSERACT_API_BASEAPI_H__`](https://github.com/tesseract-ocr/tesseract/blob/545a0634dab4c0c168d37bf2b757f246d2aeef12/api/baseapi.h#L20)" and "[`TESSERACT_CCUTIL_PLATFORM_H__`](https://github.com/tesseract-ocr/tesseract/blob/ae6f195b1f3458fed31f8d0dbf97ac2ee9ee381b/ccutil/platform.h#L20)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by zdenop** [comment]
Yes, you can make a pull request.

**Comment by zdenop** [comment]
I did one more check with google [cpplint](https://github.com/google/styleguide/tree/gh-pages/cpplint):
it ask to use API_BASEAPI_H_, while your doc suggest to use API_BASEAPI_H... 
I think we should fit to google-style (and there should be more style fixes)

**Comment by amitdo** [comment]
According to their [C++ Style Guide](https://google.github.io/styleguide/cppguide.html#The__define_Guard) it should be: `TESSERACT_API_BASEAPI_H_`
