### ISSUE TITLE
very slow in OCRing for Thai Language

### ISSUE THREAD

**Issue by Jasmeet13Kaur** [tesseract-ocr/tesseract#962]
Hi,
I am using 3.04.00 version of tesseract and try to execute the command TesseractConsole.exe .\test_Thai.tif "<PATH>\html" "-l tha"+"<PATH>\html.txt".
It takes too long to generate the html.txt file with the data.
Note: I have picked up the trained data from : https://github.com/tesseractocr/tessdata/blob/master/tha.traineddata

Thanks,

**Comment by zdenop** [comment]
TesseractConsole.exe is not part of tesseract project. We do not support 3rd party programs. Please contact its author.
