### ISSUE TITLE
Text recognition from camera picture issues

### ISSUE THREAD

**Issue by davecoffin** [tesseract-ocr/tesseract#963]
Attached are two images, one with the word Keyword, and the other with a random string. The file with the word Keyword outputs an accurate result (Keyword). The second file though outputs something very odd: `"'Eﬂ'fé'i'ibiboss`

Any idea why? The second picture is the result of someone taking a photo of a serial number, which is what i am trying to achieve in my app. The Keyword image is a screenshot from the web, so it is perfectly skewed with a white background. Was I wrong in assuming that ocr could accurately determine the text in the second photo?

<img width="100" alt="ocrtest" src="https://cloud.githubusercontent.com/assets/1245462/26419801/dd4dfa72-408e-11e7-8115-e29b35beb05a.png">

<img width="100" alt="ocrtest" src="https://cloud.githubusercontent.com/assets/1245462/26419800/dd4dad74-408e-11e7-97a2-e9892bd73fcb.png">

**Comment by Shreeshrii** [comment]
works with latest code from master branch, using the LSTM engine ie. --oem 1

$ tesseract test.png stdout --oem 1 --psm 6 -l eng
Warning. Invalid resolution 0 dpi. Using 70 instead.
_SA1C17010068

$ tesseract test.png stdout --oem 0 --psm 6 -l eng
Warning. Invalid resolution 0 dpi. Using 70 instead.
mgAﬁ'Ei'ib'fboss

**Comment by davecoffin** [comment]
Thanks @Shreeshrii, I will move to the forum, my apologies I am new to this technology!
