### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [tesseract-ocr/tesseract#97]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [BeamSearch::Cleanup](https://github.com/tesseract-ocr/tesseract/blob/5378679dce5b9604e56657a466800db5fb6a390d/cube/beam_search.cpp#L35)
- [Bmp8::FreeBmpBuffer](https://github.com/tesseract-ocr/tesseract/blob/10ea4f0636dc997054bda3a0cd463d39e1e13a8d/cube/bmp_8.cpp#L48)
- [CharClassifier](https://github.com/tesseract-ocr/tesseract/blob/10ea4f0636dc997054bda3a0cd463d39e1e13a8d/cube/classifier_base.h#L49)
- [CubeObject::Cleanup](https://github.com/tesseract-ocr/tesseract/blob/524a61452d2cc1ed152ebd7e759713ec68e1e953/cube/cube_object.cpp#L55)
- [CubeRecoContext](https://github.com/tesseract-ocr/tesseract/blob/524a61452d2cc1ed152ebd7e759713ec68e1e953/ccmain/cube_reco_context.cpp#L57)

**Comment by amitdo** [comment]
Fixed.
