### ISSUE TITLE
Problem with edges

### ISSUE THREAD

**Issue by Panos68** [tesseract-ocr/tesseract#977]
Hello,
I was trying to get the text of the image i am providing bellow (i am using extract_text before the apply of tesseract) and i wanted to get the result of fitting room above which is very clear and in white background with black letters. I didnt get that result on the output file so i tried to cut only that part of the image and use the tesseract and i got the result i was looking for. Probably there is a bug how tesseract is detecting the edges, any helpful information about this?
![18870210_10155396251410842_855716923_o](https://cloud.githubusercontent.com/assets/28709382/26761770/3dbb29a2-4936-11e7-992d-9f27c2255770.jpg)

**Comment by zdenop** [comment]
Tesseract is OCR engine and it requires image with text input (e.g. it is not text detection tool). So it not is not a bug, but tesseract is not not tool you expected.
