### ISSUE TITLE
Leptonica Compiling Error

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#981]
Hi,

I wanted to install and compile leptonica and then tesseract on a server following this [website](https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32)
i installed and downloaded leptonica 1.74.1 and tesseract 4.00.00alpha on VM and VB before following the same steps exactly, yet today i found this error coming out on the terminal
![env_error](https://cloud.githubusercontent.com/assets/26926171/26831244/5b97d520-4ad4-11e7-9a87-bf86bc754e79.png)

i tried to comment the error section but that caused another problems, i even tried to get the leptonica.gz again and running the steps once more, yet the same problem.

keep in mind that the OS on the server is Ubuntu 14.04, which is the same OS that i used on VM and OS on VB and worked on both cases, is this issue cause by a dependency or what exactly?
Please any ideas? as i need to get the server up and running as soon as possible
Thanks

**Comment by Shreeshrii** [comment]
use leptonica 1.74.2

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by ibr123** [comment]
thanks, but what is the command to get the newer version, its not:
wget http://www.leptonica.com/source/leptonica-1.74.2.tar.gz

and is it an alpha version too or a full release?

**Comment by Shreeshrii** [comment]
https://github.com/DanBloomberg/leptonica/releases/tag/1.74.2

I think it is a full release.

Please see https://github.com/tesseract-ocr/tesseract/pull/979
for fixes made recently that require this change


ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by stweil** [comment]
According to the snapshot, your Leptonica build fails. Then that's unrelated to Tesseract, isn't it?

**Comment by ibr123** [comment]
@Shreeshrii same problem has occurred with Leptonica 1.74.2, it i feel its kind of a compiler issue, isn't it?
@stweil yes you are right, the compilation of the leptonica has failed, and i couldn't continue to install tesseract
@zdenop i really didn't know why you have closed this issue before i even got the chance to try what was suggested by shree??!! at least if something is wrong with the question, or its irrelevant to this group at least mention that in a comment then close it !!!!! :(

**Comment by zdenop** [comment]
You are not able to build leptonica => you need to solve it  with leptonica project team (e.g. not here).
