### ISSUE TITLE
Training tools can't be built: ICU_UC & ICU_I18N not found

### ISSUE THREAD

**Issue by billydekid** [tesseract-ocr/tesseract#982]
Hi,
I tried to compile tessearct 3.05.01 on CentOS 6.7 with gcc 4.8.2.
I'm unable to activate training tools since configure step didn't find following libs:

```
checking for ICU_UC... no
checking for ICU_I18N... no
```

I already install libicu-dev completely. It installed in /usr/lib64
Following the my configure command:

`PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --with-extra-libraries=/usr/lib64`

What the right command to use? or I miss something?

Thank you,
[bayu]

**Comment by stweil** [comment]
You missed several things. First, you should have used the [user forum](https://github.com/tesseract-ocr/tesseract/wiki#support). Second, I‌ assume that `libicu-dev` installed `/usr/x86_64-w64-mingw32/lib/pkgconfig/icu-uc.pc`, Then `--with-extra-libraries=/usr/lib64/pkgconfig` would be correct.

**Comment by billydekid** [comment]
OK, apologize and thank you.
[bayu]
