### ISSUE TITLE
Tesseract Locks Up when Multiple Programs Attempt to Process

### ISSUE THREAD

**Issue by ryan-cahill** [tesseract-ocr/tesseract#984]
### Environment
Version: 4.00.00alpha, from [here](https://github.com/tesseract-ocr/tesseract/releases/tag/4.00.00alpha)
`uname -a` output: Linux T1 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
Running two or more programs which all attempt to process images with Tesseract seems to lock up all programs indefinitely.

### Expected Behavior:
Running two or more programs involving Tesseract would not block all programs from executing.

### Suggested Fix:
I don't actually know enough about the codebase itself to to suggest a fix, but would be interested in more information or a workaround.

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesseract/issues/961

What is the  hardware you are using?
Is this being run under WSL?

I saw improvement by disabling openmp, you can gI've it a try.

**Comment by Shreeshrii** [comment]
Try using the latest code from github instead of the initial alpha, there have been many changes and bug fixes.

**Comment by ryan-cahill** [comment]
This actually has nothing to do with training though, just evaluation with the LSTM. I'm running on an Ubuntu 16 VM which has 16GB RAM from the host and 4 cores, so I doubt it has anything to do with the hardware. I'll try the latest code and see what happens

**Comment by stweil** [comment]
The problems which we observed with training also exist for the tesseract ocr process. It uses multithreading causing a significant overhead for thread synchronisation. Your 4 cores will be sufficient for a single tesseract process, but if you run more than one, the effects which you have seen are not surprising.

Disabling OpenMP and the related multithreading would help for your case. Use `configure --disable-openmp`.

**Comment by ryan-cahill** [comment]
Thanks @stweil and @Shreeshrii. Will disabling OpenMP affect processing time in a negative way though? For example, if I'm only running one process using Tesseract, will it run more slowly with OpenMP disabled? It sounds like there must be some kind of tradeoff here

**Comment by stweil** [comment]
Yes, for a single process disabling OpenMP will increase the run time – not by a factor 4, but maybe 2. You'll have to try it yourself.

**Comment by ryan-cahill** [comment]
Great, I'll give that a shot and see what happens. Thanks again for the support, closing now
