### ISSUE TITLE
Autotools: USING_MULTIPLELIBS

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#985]
What's the point of this option?

Libtool Convenience Libraries
https://www.gnu.org/software/automake/manual/automake.html#Libtool-Convenience-Libraries

https://github.com/tesseract-ocr/tesseract/commit/bf4a09d72a
https://github.com/tesseract-ocr/tesseract/commit/67f47008c

**Comment by amitdo** [comment]
CC: @jimregan

**Comment by zdenop** [comment]
AFAIR somebody wanted to have option compile only individual parts of tesseract. 
IMO it does not make sense and I think it should go away - there is other way how do deal with it (e.g. we implement disable graphics, disable cube)

**Comment by amitdo** [comment]
>IMO it does not make sense

That's exactly what I thought. and thus opened this issue.

**Comment by amitdo** [comment]
>I think it should go away

:+1: 

>there is other way how do deal with it (e.g. we implement disable graphics, disable cube)

I don't understand. How are those options related here?
