### ISSUE TITLE
Include with leptonica path instead of direct

### ISSUE THREAD

**Issue by xsacha** [tesseract-ocr/tesseract#987]
Currently the following is used:
#include "allheaders.h
#include "pix.h"

I think this should be changed to:
#include <leptonica/allheaders.h>
#include <leptonica/pix.h>
so that we can avoid pollution of the includes, especially where other projects use Tesseract.

Leptonica currently includes: include and include/leptonica, allowing this functionality. However, it should be changed to only include the include directory in my opinion.

I understand this may have been done for a time where there was usage of 'lept' and 'leptonica' paths. Is this still the case?

**Comment by stweil** [comment]
That's a change which would require modifications on the Leptonica side first. The current pkg-config settings `lept.pc` only add the `leptonica` directory to the include path.

**Comment by xsacha** [comment]
Thanks. That indeed is a blocker.
