### ISSUE TITLE
Japanese Images Recognition 

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#988]
Hi,

while i made some Images Recognition for the Japanese language i found that the resulted Japanese text has different spacing between its characters, i have no background in Japanese but in the original documents or images the spacing is different meaning some times its more like spaces between English letters and other times the space similar to the space between English words, while in the resulted text all spaces are similar between all characters.

Thanks

**Comment by Shreeshrii** [comment]
As suggested in https://github.com/tesseract-ocr/tesseract/issues/1009

use `-c preserve_interword_spaces=1` to remove extra spaces

Also see https://github.com/tesseract-ocr/tesseract/issues/991

**Comment by ibr123** [comment]
@Shreeshrii  Thanks

**Comment by ibr123** [comment]
Hi,

just adding information, this `-c preserve_interword_spaces=1` argument works good with Japanese (i didn't try it with English) but for Arabic its better not to use it, since the Arabic language has Cursive  writing system, so i detected a text with both cases, with the argument and without it, when i used the argument for Arabic some of the words were detected correctly but are joined to the next word which is incorrect, but without that argument the same words didn't  join to the next word

**Comment by Shreeshrii** [comment]
Fixed via https://github.com/tesseract-ocr/tessdata_fast/pull/7

@zdenop  Please close this issue, after PR is merged in tessdata_fast.
