### ISSUE TITLE
Assert failed

### ISSUE THREAD

**Issue by jorgeflorez** [tesseract-ocr/tesseract#989]
Hello,
I was trying to perform OCR using [tesserocr](https://github.com/sirfz/tesserocr) wrapper (python)
and this code:

```
from tesserocr import PyTessBaseAPI
from PIL import Image

img = Image.open("/home/jorgeflorez/Downloads/c1.png")
tesseract = PyTessBaseAPI(lang="spa")
tesseract.SetImage(img)
tesseract.Recognize()
print tesseract.GetUTF8Text()   
tesseract.End()
```

For the image I tried I got this in console:
`start >= 0 && start + num <= length_:Error:Assert failed:in file ratngs.cpp, line 321`

I reported the problem and talked to the creator of the wrapper and he provided me with a workaround to make it work

```
from tesserocr import PyTessBaseAPI
from PIL import Image

filePath = "/home/jorgeflorez/Downloads/c1.png"

tesseract = PyTessBaseAPI(lang="spa")
tesseract.SetImageFile("/home/jorgeflorez/Downloads/c1.png")
tesseract.Recognize()
print tesseract.GetUTF8Text()
```

He thinks that most likely the problem is in tesseract and not in pillow. So here I am trying to let you know :)

This is what I am using 
Linux localhost.localdomain 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

tesseract 3.05.01
 leptonica-1.74.1
  libjpeg 6b (libjpeg-turbo 1.2.90) : libpng 1.5.13 : libtiff 4.0.3 : zlib 1.2.7

And this is the [image](https://drive.google.com/file/d/0Bw6WjPemSDnHcTg4S25sN1A1ZU0/view?usp=sharing)

I am not very familiar with the C++ API, otherwise I would create a program and try to reproduce it with it and be sure this is a tesseract issue. Thanks in advance.

Best Regards.
Jorge

**Comment by sirfz** [comment]
Reference issue in tesserocr: sirfz/tesserocr/issues/55

**Comment by amitdo** [comment]
@sirfz, can you provide an C++ example program that reproduces the issue?

**Comment by sirfz** [comment]
Not tested but it should look something like (based on the [basic API example](https://github.com/tesseract-ocr/tesseract/wiki/APIExample#basic-example)):

```cpp
#include <tesseract/baseapi.h>
#include <leptonica/allheaders.h>

int main()
{
    tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
    ETEXT_DESC monitor;

    // Initialize tesseract-ocr with Spanish, without specifying tessdata path
    if (api->Init(NULL, "spa")) {
        fprintf(stderr, "Could not initialize tesseract.\n");
        exit(1);
    }

    // Open input image with leptonica library
    Pix *image = pixRead("pil_image.png");
    api->SetImage(image);
    // Recognize (should crash here)
    api->Recognize(&monitor);

    return 0;
}
```

Here's the image saved using PIL:

![pil_saved](https://user-images.githubusercontent.com/4741099/27263250-3286f884-546e-11e7-8654-e2fe905512e5.png)

**Comment by sirfz** [comment]
After writing the code above, I modified tesserocr to call `Recognize(NULL)` instead of `Recognize(&monitor)` and it no longer crashes. For some reason it's triggering on some images but I guess my current usage is wrong and I should use `NULL` instead when there's no monitor?

**Comment by amitdo** [comment]
>but I guess my current usage is wrong and I should use NULL instead when there's no monitor?

Yes.

If you want to use monitor, see here:
https://github.com/tesseract-ocr/tesseract/blob/8aa0a2dd48b8b0a5aa174882ad079239dc20d8c5/api/baseapi.cpp#L1173

**Comment by sirfz** [comment]
Thanks @amitdo for pointing to a usage example, will definitely add the timeout feature to tesserocr :+1:

**Comment by amitdo** [comment]
The original issue was fixed by @sirfz in his tesserocr, so this issue should be closed.
