### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [tesseract-ocr/tesseract#99]
Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html) ⇒ [InputBuffer constructor](https://github.com/tesseract-ocr/tesseract/blob/a303ab9d00016789f8edb331adbb9e1948d1a714/training/fileio.cpp#L135)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [SquishedDawg::build_node_map](https://github.com/tesseract-ocr/tesseract/blob/10ea4f0636dc997054bda3a0cd463d39e1e13a8d/dict/dawg.cpp#L358)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html) ⇒ [CCUtilMutex constructor](https://github.com/tesseract-ocr/tesseract/blob/10ea4f0636dc997054bda3a0cd463d39e1e13a8d/ccutil/ccutil.cpp#L27)

**Comment by zdenop** [comment]
As you can see on [README](https://github.com/tesseract-ocr/tesseract) we use https://lgtm.com and coverity.com for code analysis.

**Comment by elfring** [comment]
Do these analysis tools point also the open issues out which I reported?

**Comment by stweil** [comment]
Coverity Scan reports some of those errors – unless they are already fixed. :-)
LGTM does not report the mentioned errors.

- fseek ⇒ InputBuffer constructor, still buggy, not reported
- malloc ⇒ SquishedDawg::build_node_map, was fixed some time ago
- pthread_mutex_init ⇒ CCUtilMutex constructor, still buggy, not reported

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by stweil** [comment]
Sure, but my question was more specific. There is currently a lot of code which does not follow those principles, and more such code could get merged. Without a lot of man power, it is impossible to detect all missing checks of return values. So it is important to have tools which report violations. Do you know such tools?

**Comment by stweil** [comment]
As there are still some of the mentioned errors still not fixed, I reopen this issue.

**Comment by stweil** [comment]
Just tell us the names of those tools, then we can decide.

**Comment by elfring** [comment]
Examples:
* [AspectC++](https://aspectc.org/ "Software development with AspectC++?")
* [Coccinelle](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle")
* [Cppcheck](http://cppcheck.sourceforge.net/ "Static C/C++ code analysis")

**Comment by stweil** [comment]
Thank you. I know and used the last two. Coccinelle itself does not find problems – it needs scripts written to do this. Cppcheck did not report missing handling of return values last time when I used it (well, that was some years ago).

**Comment by elfring** [comment]
>Coccinelle itself does not find problems

This software tool can also find and adjust various questionable source code. It supports the C programming language better than C++ so far.


>(well, that was some years ago)

I suggest to try Cppcheck out again to see if this analysis tool was improved in desired ways in the meantime.

-----

Would you like to get help from any additional development tools?

**Comment by zdenop** [comment]
@elfring : Will you provide output of your code analyze?
Maybe as new issue (grouped by type) so we can close it with commit? Patches are welcomed too ;-)

**Comment by elfring** [comment]
Will the mentioned tools become relevant for [your software development process](https://github.com/tesseract-ocr/tesseract/blob/126ca8050c178769dc9149b8bab357ab6e3fc871/CMakeLists.txt#L7 "Building software with CMake")?

**Comment by zdenop** [comment]
@elfring : I am sorry, but I did not get point of your question. Primary build system are autotools. Of course I am interested also in support cmake ...

**Comment by elfring** [comment]
Did your interest increase for the application of the tool “[AspectC++](https://aspectc.org/ "aspect-oriented software development")” (together with related information sources for example)?

**Comment by zdenop** [comment]
What does it mean practically? 
There is basically not intention to extend dependency to another libraries.
Also the main development is done in google, so unless the some approaches are accepted by Ray, it does not make sense to implement it by community...

**Comment by stweil** [comment]
@elfring, I don't think that Tesseract will switch from C++ to Aspect C++ as that is currently not a common standard. As far as I could see Aspect C++ cannot be used to check the existing code. Nor can Coccinelle because it only supports C but not C++. So only cppcheck remains which can be used in addition to Coverity Scan and LGTM.

The problems with `malloc` will be addressed by replacing that code with modern C++ data types. See also the [planning page](https://github.com/tesseract-ocr/tesseract/wiki/Planning#future-releases) in the wiki.

If you have fixes for ignored return values, they are welcome.

**Comment by elfring** [comment]
>As far as I could see Aspect C++ cannot be used to check the existing code.

I suggest to take another look at the provided technology.
Which systematic development methods do you know for [the handling of cross-cutting concerns](https://en.wikipedia.org/wiki/Cross-cutting_concern "Description for cross-cutting concerns")?


>Nor can Coccinelle because it only supports C but not C++.

This tool can be useful for limited source code analysis and corresponding transformations.
Would you like to help in any ways to improve the support for the C++ programming language here?


>If you have fixes for ignored return values, …

I would prefer the application of available known methodologies.

**Comment by zdenop** [comment]
@elfring: any help with improving code is welcomed. Pointing to new tools/methodology is interesting but... we have limited sources and most of active contributors will probably still continue to use what they are familiar. 
So if there is problem with code, you can fix, please create new issue/send PR.

**Comment by elfring** [comment]
It is probably obvious that I am trying for a while to get more software developers familiar also with other helpful methodologies.
:crystal_ball: I am curious if their popularity will grow.
