### ISSUE TITLE
Deserializing LSTMF Header  

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#992]
Hi,

while following the steps in this [website](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00---Replace-Top-Layer) i got an error at the second step which was as the following:-

![lstm](https://user-images.githubusercontent.com/26926171/27178963-2b27410c-51d5-11e7-861a-1ccc7b075405.png)

what does that mean? also how to solve this problem?, so i can continue with the training

NOTE: im using tesseract 4.00.00alpha with leptonica 1.74.1, also all LSTMFs and the used files were created on Ubuntu 14.04

**Comment by Shreeshrii** [comment]
Check that the lstmf file exists in the location referred to.

What environment, o/s, hardware are you running this on?

**Comment by ibr123** [comment]
correct, the path at the training_files.txt was wrong, thanks
