### ISSUE TITLE
lstmtraining Generic Vector Failed

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#993]
Hi,

while i was training the LSTM through this command
`lstmtraining -U ~/tesstutorial/jpntrain/jpn.unicharset \
  --script_dir /home/ibr/langdata --debug_interval 0 \
  --continue_from   tesstutorial/jpn.lstm \
  --append_index 5 --net_spec '[Lfx256 O1c105]' \
  --model_output /home/ibr/tesstutorial/new_jpn_lstm \
  --train_listfile ~/tesstutorial/jpneval/jpn.training_files.txt \
  --eval_listfile ~/tesstutorial/jpntrain/jpn.training_files.txt \
  --max_iterations 5000 &>~/tesstutorial/basetrain.log`

it went fine and started the iterations until the iteration 900 it gave the error:

![lstm dumping](https://user-images.githubusercontent.com/26926171/27182531-27761344-51e4-11e7-889e-ae91bad36f3a.png)

although the error came, it created checkpoint file, I'm using Tesseract 4.00alpha, leptonica 1.74.1 and OS is Ubuntu 14.04

i got the command from this [website](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00---Replace-Top-Layer)

any ideas?

**Comment by Shreeshrii** [comment]
please use the latest source from master branch in github, and leptonica
1.74.2

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by ibr123** [comment]
i installed and compiled both leptonica 1.74.2 and latest tesseract and ran the command but i got the following error:
![lstm2](https://user-images.githubusercontent.com/26926171/27259772-53c203ea-5423-11e7-85d1-359dab2c2fbe.png)

as you can see, this deserialization error is different from the one that i got  #992

 its not saying that the header deserialization failed, so what does that mean? and the path is correct

**Comment by Shreeshrii** [comment]
As stated in the error, you are missing

https://github.com/tesseract-ocr/langdata/blob/master/radical-stroke.txt

**Comment by Shreeshrii** [comment]
Please copy the error text from terminal rather than adding a screenshot. You can mark it as ```code```.

**Comment by ibr123** [comment]
thanks for the response, i modified the path yet i deserialization fails, but as you can see that error has gone
`ibr@ubuntu:~/leptonica-1.74.2/tesseract$ training/lstmtraining -U ~/tesstutorial/jpntrain/jpn.unicharset \
>   --script_dir /home/ibr/leptonica-1.74.2/langdata --debug_interval 0 \
>   --continue_from   /home/ibr/tesstutorial/jpn.lstm \
>   --append_index 5 --net_spec '[Lfx256 O1c105]' \
>   --model_output /home/ibr/tesstutorial/engtrain2 \
>   --train_listfile ~/tesstutorial/jpneval/jpn.training_files.txt \
>   --eval_listfile ~/tesstutorial/jpntrain/jpn.training_files.txt \
>   --max_iterations 5000
Loaded file /home/ibr/tesstutorial/jpn.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Continuing from /home/ibr/tesstutorial/jpn.lstm
Appending a new network to an old one!!Setting unichar properties
Setting properties for script Common
Setting properties for script Latin
Setting properties for script Katakana
Setting properties for script Hiragana
Setting properties for script Han
Warning: given outputs 105 not equal to unicharset of 546.
Num outputs,weights in serial:
  Lfx256:256, 394240
  Fc546:546, 140322
Total weights = 534562
Built network:[1,0,0,1[C5,5Ft16]Mp3,3Lfys64Lfx128Lrx128Lfx256Fc546] from request [Lfx256 O1c105]
Training parameters:
  Debug interval = 0, weights = 0.1, learning rate = 0.0001, momentum=0.9
Deserialize failed: /home/ibr/tesstutorial/jpneval/jpn.HGGothicE.exp0.lstmf read 0/1670 pages`

NOTE: the terminal freezes after running this command, until i stop the command by "Ctrl C"

**Comment by Shreeshrii** [comment]
1. You have not mentioned the environment hardware/software on which you are running this?

2. Please rerun tesstrain.sh to recreate the lstmf files using the latest version of tesseract and then try training.

**Comment by Shreeshrii** [comment]
@ibr123  Is your problem solved? Please mention the solution and close the issue.

**Comment by ibr123** [comment]
@Shreeshrii  actually I switched back to liptonica 1.74.1 and started fine tuning since I decided I need the old unicharset and I just want to add layers to existing lstm file, so I needed to finish this task ASAP and as you know fine tuning takes many days, so I didn't have the chance to try your solution which is creating lstmf by the latest tesseract as it requires installation and compiling and the machine is already occupied by the tuning.
BUT since I don't need to create from scratch anymore I can close this issue, so if its fine by you I will close it, reply back to me for the next action.
Thanks

**Comment by amitdo** [comment]
@zdenop, please close this issue.
