### ISSUE TITLE
USE_OPENCL not defined in CMAKE

### ISSUE THREAD

**Issue by xsacha** [tesseract-ocr/tesseract#994]
USE_OPENCL should be turned off in CMAKE if OpenCL is not found. Also, potentially should be enabled by default if it is found unless there are reasons otherwise.

**Comment by amitdo** [comment]
CC: @egorpugin

**Comment by egorpugin** [comment]
Sorry, I do not familiar with opencl setup. Feel free to contribute required changes.

**Comment by stweil** [comment]
Adding USE_OPENCL by default would be a bad idea. The OpenCL code is still buggy and does not improve the performance very much (or even not at all). Only developers who know what they are doing should use it.

**Comment by amitdo** [comment]
Should this issue be closed then? IMO, there's no point to keep it open if nobody going to do something about it.

**Comment by stweil** [comment]
I see no need to keep it open.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
