### ISSUE TITLE
SUGG: Font Recognition and Font Similarity Learning

### ISSUE THREAD

**Issue by ghost** [tesseract-ocr/tesseract#996]
As the development of OCR is moving towards LSTM, new difficulties arise, such as having created lstm/traineddata for different fonts.

**Example situations:**

- I have created multiple lstm/ traineddata models, each for a different font and form of writing, and want to choose the most suitable one.
- Or, I just want to identify the font type from an image, and similar font types, instead of a full ocr.

I suggest integrating a new feature which gives the ability to train deconvolutional networks in identifying the Font Type and provide similar font matches suggestion from an image.

**Demostration:**
An example of such implementation would be the Adobe DeepFont, have a look:
- [Video of Deep Font demonstration](https://youtu.be/5eJ3IXYcw3M?t=2m30s)
- [Document](http://on-demand.gputechconf.com/gtc/2016/presentation/s6293-hailin-jin-deepfont.pdf)
- [Detailed research](https://pdfs.semanticscholar.org/7bf7/8e62c9ae7ffa54a1c6281a0e0e11a0720456.pdf)
- [Python script demonstration](https://www.dropbox.com/sh/o320sowg790cxpe/AAAJr15UkGQ7vEG9YitS2ETma/BCF%20format?dl=0)
- [The AdobeVFR_release files
](https://www.dropbox.com/sh/o320sowg790cxpe/AADDmdwQ08GbciWnaC20oAmna?dl=0)
- [The developer page, he suggests using cuda-convnet as well as anna package for training deconvolutional networks. ](http://www.atlaswang.com/deepfont.html)

- [Whatthefont
](https://www.myfonts.com/WhatTheFont/)

Related research:
[A Sequence Learning Approach for Multiple Script Identification](http://www.academia.edu/15249794/A_Sequence_Learning_Approach_for_Multiple_Script_Identification)

The result:
I will know what is the name of the font from an image, along with similar font matches to it.

![untitled-1](https://user-images.githubusercontent.com/16248376/27267965-01204664-54b5-11e7-95bc-f603a411d399.jpg)

Thank you all for your contributions:
@theraysmith @tmbdev @mittagessen @zuphilip @zdenop @stweil @amitdo @Shreeshrii @kba @zuphilip

**Comment by amitdo** [comment]
We don't plan to implement this feature request.
