### ISSUE TITLE
MSVC: uint32_t undefined

### ISSUE THREAD

**Issue by xsacha** [tesseract-ocr/tesseract#999]
Tesseract version: 3.05.01 (tag)
Using: MSVC 2015 on Windows 10
When: USE_OPENCL is defined
Issue: openclwrapper.cpp complains about missing types (uint32_t and others that are defined in _cstdint_)

Solution: Adding #include **<**cstdint**>** to the top of the cpp file resolves the error and results in a successful build.
See: https://github.com/xsacha/tesseract/commit/83d8e85fa5d08874b725d111f748dc2df5e48227

**Comment by stweil** [comment]
Confirmed. The POSIX data types were introduced by copying code from git master. I suggest adding the include statement for `cstdint` to `ccutil/host.h`.

**Comment by Shreeshrii** [comment]
@stweil Please also check 3.05.01 build failure reported in forum at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/g8lTxxYiJ2E/KL07qF_LAQAJ

Should I ask them to open an issue for it?

**Comment by stweil** [comment]
See pull request #1001.

**Comment by xsacha** [comment]
Thanks!
